### ISSUE TITLE
Classe EnumParaInteger.cs

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#10]
Prezado Adenilton,

Gostei muito do seu projeto, o que será muito útil para minha empresa de desenvolvimento de software com relação à implementação da NFC-e. Entretanto, baixei o projeto e o mesmo não inclui a classe EnumParaInteger.cs. Você poderiam me ajudar?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
Ops, foi mal, acabei de colocar o arquivo.

**Comment by robertocvsiqueira** [comment]
Já baixei a nova versão. Obrigado!

**Comment by adeniltonbs** [comment]
This issue was moved to ZeusAutomacao/DFe.NET#10
