### ISSUE TITLE
Consulta pela Chave Retornaque a NFe não esta na SEFAZ

### ISSUE THREAD

**Issue by nebrio** [ZeusAutomacao/DFe.NET#100]
Boa tarde!
Estou continuando meus testes e ao testar a consultar pela chave retorna assim:
versao = 3.10
tpAmb = taHomologacao
verAplic = SP_NFE_PL_008h2
cStat = 217
xMotivo = Rejeição: NF-e não consta na base de dados da SEFAZ
cUF = SP
chNFe = ***************\* (substitui a chave não identificar a empresa)
protNFe = 
procEventoNFe = System.Collections.Generic.List`1[NFe.Classes.Servicos.Consulta.procEventoNFe]

Está dizendo que a NFe está rejeitada mas não está.... o que pode ser?

Obrigado

**Comment by adeniltonbs** [comment]
Essa mensagem é devolvida quando a "NF-e não consta na base de dados da SEFAZ" rsrs. Consulte a chave direto no site para ter certeza que a chave está correta e/ou a NFe existe para a UF de SP, no ambiente de Homologação.

**Comment by nebrio** [comment]
Valeu.
Mancada minha consultando NFe de Produção em ambiente de Homologação.
