### ISSUE TITLE
Separar método da consulta

### ISSUE THREAD

**Issue by Hugoxz** [ZeusAutomacao/DFe.NET#1005]
O método CTeDistDFeInteresse realiza a consulta e faz o parse do XML retornado para as classes CTe.
Sugiro que seja separado o método da consulta e o processo de "pós-consulta", pois houve um caso de que o processo de serialização de um documento lançava um exception, fazendo com que eu nem conseguisse acessar o XML de retorno (no meu caso eu nem utilizo os objetos que foram gerados pelo parser pois eu armazeno direto os documentos recebidos pelo retorno).

**Comment by marcosgerene** [comment]
@Hugoxz 
Eu não apenas a impressão do CTe do Zeus. Para o restante uso o https://github.com/ACBrNet/ACBr.Net.CTe

O @robertorp deve estar atolado de serviço, por isso não respondeu, e até aonde eu sei só ele vai contribuindo com o CTe aqui... Se quiser mandar um PR faço um esforço para olhar, ou pelo menos poste aqui uma forma de simular o erro, prints do retorno do VS, o xml que causa o erro, etc.
