### ISSUE TITLE
Emissão DANFE Aplicação Web (C# MVC)

### ISSUE THREAD

**Issue by guilhermefmbatista** [ZeusAutomacao/DFe.NET#101]
Prezados, bom dia!
Estou com bastante dificuldade em emitir a DANFE em uma aplicação web.
@celinolimac Vi que você utiliza em uma aplicação web. Como está emitindo a Danfe?
Alguém mais que utiliza essa excelente biblioteca já conseguiu?

**Comment by guidi** [comment]
@guilhermefmbatista qual problema você está tendo?

**Comment by celinolimac** [comment]
olá @guilhermefmbatista na emissao do danfe utilizo o crystal reports para montar o layout e temos uma procedure no banco onde depois de autorizado o uso da NFE os dados são salvos em algumas tabelas e essa procedure traz esses dados e monta no layout do danfe feito no crystal... podendo assim imprimir direto ou salvar o pdf.

Qualquer duvida posta ai...

abraço

**Comment by guilhermefmbatista** [comment]
@guidi não estou conseguindo usar o modelo da biblioteca em minha aplicação web.
@celinolimac Você poderia me fornecer o layout do danfe feito no Crystal? Me ajudaria bastante. Se sim, pode enviar no meu e-mail guilhermefmbatista@gmail.com
Obrigado!

**Comment by celinolimac** [comment]
Olá

@guilhermefmbatista  da uma olhada no seu email..

valew

**Comment by guilhermefmbatista** [comment]
Recebi aqui.
Muito obrigado novamente.
Abraços

**Comment by SilverioMiranda** [comment]
Poderia postar postar em algum lugar que todos possam acessar? :)

**Comment by leandrossantos** [comment]
@celinolimac você poderia me passar o relatorio da DANFe de NFCe em crystal, preciso para usar numa aplicação web. meu email é leandro@rondosoft.com.br

**Comment by celinolimac** [comment]
@leandrossantos mandei para seu email.

@SilverioMiranda irei postar e compartilhar o link

**Comment by guidi** [comment]
@celinolimac  também gostaria desse relatório, se puder me enviar fico grato. ****@gmail.com

**Comment by leandrossantos** [comment]
obrigado @celinolimac

**Comment by guidi** [comment]
@celinolimac recebido, valeu.

**Comment by odacirz** [comment]
Boa tarde,

Se possível poderia enviar pra mim também odacir_z@hotmail.com

**Comment by celinolimac** [comment]
segue link para download:

http://www.4shared.com/file/dXv5jbY1ce/Danfe.html

**Comment by DjanGomes** [comment]
Qual a versão do CrystalReport vc usou?
