### ISSUE TITLE
Criar exportação da DACTE Fast para Stream

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#1010]
Criar exportação da DACTE Fast para Stream

**Comment by marcosgerene** [comment]
Não estou no escritório, o código consiste nisso:
```
public void ExportarPdf(Stream outputStream)
{
       Relatorio.Prepare();
      Relatorio.Export(new PDFExport(), outputStream);
      outputStream.Position = 0;
}
```

Se quiser implementar eu aceito o PR.

**Comment by flavionootech** [comment]
É isso mesmo, porém estou com uma dúvida, me parece que ja funcionava e foi retirado.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/1032
