### ISSUE TITLE
Consultando todas as notas emitidas com NFeDistribuicaoDFe 

### ISSUE THREAD

**Issue by bencz** [ZeusAutomacao/DFe.NET#1012]
Olá.
Estou tentando obter todas as notas emitidas contra o CNPJ, usando a função NFeDistribuicaoDFe, mas, estou obtendo o seguinte erro:

`Serviço NFeDistribuicaoDFe, versão 1.01, não disponível para a UF SP, no ambiente de Produção para emissão tipo Normal, documento: !'`

Testei diversas combinações de versão e tipo, mas, todos retornam erro.

O meu código de teste é:

            var servico = new NFe.Utils.ConfiguracaoServico();
            servico.cUF = DFe.Classes.Entidades.Estado.SP;
            servico.tpAmb = DFe.Classes.Flags.TipoAmbiente.Producao;
            servico.VersaoNFeDistribuicaoDFe = DFe.Classes.Flags.VersaoServico.Versao100;
            servico.tpEmis = NFe.Classes.Informacoes.Identificacao.Tipos.TipoEmissao.teNormal;

            NFe.Servicos.ServicosNFe s = new NFe.Servicos.ServicosNFe(servico, CarregaCertificado());
            var r = s.NfeDistDFeInteresse("SP", "[CNPJ]", "000000000000000");

**Comment by robertorp** [comment]
Ele não esta achando a url da versão 1.01 
poderia verificar qual url usa para SP?

**Comment by bencz** [comment]
Essa URL é do ambiente nacional... http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=

**Comment by felixsevero** [comment]
Pela mensagem do Zeus, você não esqueceu de informar o Modelo de Documento?
