### ISSUE TITLE
Dúvida - MDFE Download XML

### ISSUE THREAD

**Issue by gustavoignan** [ZeusAutomacao/DFe.NET#1014]
Bom dia!!

Estou começando a usar o Zeus Automação agora... estou conseguindo transmitir MDFE e imprimir normalmente... vocês estão de parabéns!!

Porém, como estou migrando da solução do Governo para vocês, não tenho todos os XML's "Proc" enviados anteriormente para poder cancelar, encerrar, etc.

Existe alguma implementação que eu possa utilizar dentro das classes, para baixar o xml ?

**Comment by robertorp** [comment]
O que você pode fazer é 
![image](https://user-images.githubusercontent.com/10251705/65049592-5ba02d80-d93c-11e9-8a0b-2195d830ff62.png)
monta o objeto manualmente é seja feliz
