### ISSUE TITLE
MOC CT-e 3.00a QRCode MDF-e e CT-e

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#1015]

**Comment by guimagcpd** [comment]
Bom dia... Gente...
Recebi ontem da Uninfe e da TecnoSped e-mails informando a respeito da nova regra que trata essa MOC ai...

já está em vigor
As novidades apresentadas pelo MOC CT-e 3.00a entra em vigor nas seguintes datas:

Ambiente de homologação: 22/07/2019
Ambiente de produção: 26/08/2019

E em breve estará sendo obrigado em produção....
Acredito que fomos pegos de surpresa não ..

vou passar os links que vi..., resumindo, diz que tera de ter QRCode tanto no CTE como no MDFE também nas impressões...  queria ver se esta implementação ja tem data para o Zeus, porque testes como aqui no MT ja não estão sendo possíveis depois que atualizei as schemas... ele diz que precisa informar a tag qrCode.

https://blog.tecnospeed.com.br/ct-e-3-00a/?utm_campaign=news_300719&utm_medium=email&utm_source=RD+Station

http://www.ndd.com.br/blog/nddcargo/atualizacoes-dos-mocs-mdf-e-e-ct-e-3-00-sao-publicadas/

**Comment by marcosgerene** [comment]
Ambos recebendo webservice sincronos, icmspart caindo do cte... li muito por cima, mas gostei do que vi..

O QrCode na impressão já foi implementado pelo @robertorp e já teve alguns ajustes feitos por mim.

Vou manter essa issue aberta por mais alguns dias para consulta geral.
