### ISSUE TITLE
Erro Nao foi possivel converter o stream para o certificado. Ajuda

### ISSUE THREAD

**Issue by scalarerp** [ZeusAutomacao/DFe.NET#1017]
Pessoal, estou precisando saber se alguem tem alguma dica, instalei o IIS Express no windows 10 e tambem o visual studio, quando rodo o sistema pelo visual studio a NFE autoriza normalmente, mas quando rodo o sistema compilado no IIS do windows aparece este erro, já revisei tudo e não tenho idéia deste erro.
Alguém teria alguma dica?
Erro Nao foi possivel converter o stream para o certificado

**Comment by scalarerp** [comment]
Este erro vem do CertificadoDigital.cs >> ObterDoArrayBytes.
Observação é que tenho todos meus clientes funcionando normalmente com o sistema, somente noste windows 10 que tá assim.

**Comment by scalarerp** [comment]
Alterei o sistema para pegar o erro:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Acesso negado

Alguem tem alguma dica?

**Comment by scalarerp** [comment]
Resolvido, no windows 10 liberei o acesso para a pasta MachineKeys (C:\ProgramData\Microsoft\Crypto\RSA) para os usuarios do IIS.

**Comment by ChristopherBaumg** [comment]
Me encontro com o mesmo problema. @scalarerp resolveste somente dando acesso total ao grupo de usuários: IIS_IUSRS ? Ou teve algo mais? Pois foi o que eu fiz mas ainda com o mesmo erro retornando.

**Comment by EttorePaludeto** [comment]
Salve, salva rapazeada!

Alguém tem uma luz para esse problema de certificado? Estou usando .NET 6, Vs22 e Win10....não tá indo de jeito nenhum. Liberei os acessos a pasta MachineKeys, mas nada!

Estou apenas testando o código no console, ou seja, nem IIS estou usando.

Valeuuuuuuu! 

![image](https://user-images.githubusercontent.com/38463108/171645782-4fe8167e-8381-4de3-ab90-5993eca9c120.png)

**Comment by Degobi** [comment]
Estava com o mesmo erro, consegui resolver utilizando a resposta do amigo acima, (C:\ProgramData\Microsoft\Crypto\RSA)
![Screenshot_2](https://github.com/ZeusAutomacao/DFe.NET/assets/87071652/ac471108-3423-43bb-b3b0-c002d9723a8d)
![Screenshot_3](https://github.com/ZeusAutomacao/DFe.NET/assets/87071652/844f22a1-d0d5-4a3f-b098-35980e221668)


Depois disso, foi mandar transmitir que passou!
