### ISSUE TITLE
FastReports

### ISSUE THREAD

**Issue by rodrigofornasier** [ZeusAutomacao/DFe.NET#102]
Boa tarde, baixei a solução, mas não consigo compilar pois falta a dll do FastReports. Pode me ajudar ?
Poderia me dizer a diferença do brach master e Danfe ?

Grato !

**Comment by guidi** [comment]
@rodrigofornasier baixa o fastreports direto do site do fabricante e instala na sua máquina que vai compilar normal.

**Comment by rodrigofornasier** [comment]
Baixo a versão demo mesmo ? É isso ?

**Comment by guidi** [comment]
@rodrigofornasier Sim, você pode baixar a versão demo mesmo que vai poder testar normal, porém acredito que ela expire em 30 dias.

**Comment by rodrigofornasier** [comment]
Show cara ! Obrigado pela força !

**Comment by adeniltonbs** [comment]
Não expira, a única limitação da versão demo é uma marca dágua na impressão
