### ISSUE TITLE
MUDANÇA DE AMBIENTE NACIONAL EMISSÃO DE NF-E/NFA-E (Estado do PA)

### ISSUE THREAD

**Issue by ocult** [ZeusAutomacao/DFe.NET#1025]
**Recebemos e-mail de um cliente do PA, será necessário alterar algo no Zeus para atender essa mudança??**

_Segue e-mail na íntegra:_

> A partir do dia 2 de setembro as Notas Fiscais Eletrônicas (NF-e) e Notas Fiscais Avulsas Eletrônicas (NFA-e), emitidas por contribuintes do Pará, passarão a ser autorizadas por meio da SEFAZ Virtual do Rio Grande do Sul (SVRS).
> 
> O novo ambiente de autorização possui disponibilidade e capacidade de atendimento superior às do ambiente que será desativado. Assim, para não correr o risco de ficar sem emitir NF-e, a partir do dia 02/09/2019, as empresas deverão atualizar seus sistemas emissores de NF-e:
> 
> - Empresas que utilizam o emissor público gratuito precisarão atualizar a versão de seu sistema emissor, isto é, realizar o download da nova versão do aplicativo, cuidando para realizar o backup das notas anteriormente emitidas.
> 
> - Empresas que utilizam sistema próprio de emissão devem alterar em seus sistemas os endereços de internet (URL dos Web Services) por meio dos quais a aplicação emissora se comunicará com o ambiente autorizador da SVRS.
> 
> Os contribuintes que não realizarem a modificação, não conseguirão emitir NF-e, pois o ambiente de autorização da SEFAZ Virtual do Ambiente Nacional será desativado e não poderá mais ser utilizado.
> 
> Quanto aos contribuintes que utilizam o aplicativo emissor de NFA-e, fornecido pela SEFA, poderão continuar utilizando normalmente, uma vez que a atualização será feita pela Secretaria da Fazenda.
> 
> A SEFA informa o endereço dos Web Services do novo ambiente:
> 
> Serviço Versão URL
> NfeConsultaCadastro 1.00
> RecepcaoEvento 1.00
> NfeInutilizacao 3.10
> NfeConsultaProtocolo 3.10
> NfeStatusServico 3.10
> NFeAutorizacao 3.10
> NFeRetAutorizacao 3.10
> NfeInutilizacao 4.00
> NfeConsultaProtocolo 4.00
> NfeStatusServico 4.00
> NfeConsultaCadastro 4.00
> RecepcaoEvento 4.00
> NFeAutorizacao 4.00
> NFeRetAutorizacao 4.00
> 
> Maria Neyara de Andrade Moura
> Secretaria da Fazenda do Estado do Pará
> Diretoria de Arrecadação - DAIF
> Célula de Análise e Controle das Obrigações Acessórias - CCOA
> 
> Call Center - 08007255533
> 
> Enviado em:
> 21/08/2019 14:23:36

**Comment by MoacirKuhn** [comment]
Alguém tem alguma avaliação para este email gerado pelo SEFAZ do PA?

**Comment by marcosgerene** [comment]
@ocult @MoacirKuhn 

Estou meu corrido aqui e não atendo o PA, então não posso te responder de bate pronto. Assim que sobrar um tempo eu vejo isso, mas são mudanças de URL (pelo que entendi no e-mail), logo basta alterar a classe de endereçamento, se nao me engano chama NFeEnderco o EnderecoNFe...

Se o @robertorp não responder antes vejo mais pro fim da tarde

**Comment by MoacirKuhn** [comment]
Posso fazer os testes desta alteração. Porém, ainda não tive retorno do SEFAZ do PA, pois pelo que percebi não tem transição entre os ambientes. No ambiente de homologação ainda funciona a URL atual e não a nova, Vai passar a ser uma situação crítica esta mudança.

**Comment by MoacirKuhn** [comment]
Nesta link se encontra o procedimento da alteração:

http://sefa.pa.gov.br/index.php/noticias/15474-autorizacao

Em conversa com o Suporte da SEFAZ PA, no ambiente de homologação já está liberado para testes da mudança pra URL do RS;

**Comment by marcosgerene** [comment]
@MoacirKuhn @ocult 

Testem o PR que mandei.

**Comment by MoacirKuhn** [comment]
Hj no final do dia vamos(Eu e o Anderson) efetuar os testes e dar o retorno. Muito Obrigado!

**Comment by ocult** [comment]
> @MoacirKuhn @ocult
> 
> Testem o PR que mandei.

Testado... faltou uma pequena alteração, comentei no PR! Com aquele alteração funcionou.

**Comment by ocult** [comment]
Faltou mais um "if" para funcionar em produção...
