### ISSUE TITLE
Dúvida: Erro no load do assembly DFe.Wsdl

### ISSUE THREAD

**Issue by bilhega** [ZeusAutomacao/DFe.NET#1029]
Srs, boa tarde.

O erro abaixo esta acorre do no tentativa de uma consulta no status do serviço do CT-e.

`Não foi possível carregar o tipo CTe.CTeOSDocumento.Common.WsdlConfiguracao do assembly DFe.Wsdl, Version=1.0.0.756, Culture=neutral, PublicKeyToken=null.`

```
Stack:
   em CTe.Servicos.Factory.WsdlFactory.CriaWsdlCteStatusServico(ConfiguracaoServico configuracaoServico)
   em CTe.Servicos.ConsultaStatus.StatusServico.ConsultaStatus(ConfiguracaoServico configuracaoServico)
....
```
Onde devo verificar para tentar identificar o problema ?

**Comment by marcosgerene** [comment]
@bilhega 

Isso é versão da biblioteca, você usa nuget ou referencia as dlls diretamente?

Você usa todos os projetos (dessa biblioteca) da mesma forma (nuget, refereciando dll etc)?

Já tentou atualizar suas referências?

**Comment by bilhega** [comment]
@marcosgerene 

Através de nuget mesmo. E sim, já atualizei tudo por aqui... mas mesmo problema. 
Vou iniciar um do zero e adicionar todas minhas referências uma a uma, e vamos ver. Utilizo o .net 4.5.2 neste projeto, sera que preciso subir para uma mais nova?

**Comment by marcosgerene** [comment]
@bilhega 
Eu compilo as dlls daqui, não referencio via nuget, não sei como está lá...

Acredito que o @robertorp pode te ajudar melhor nisso, mas a sua ideia de remover as referencias e refazer é válida sim.

Sobre o .Net 4.5.2, tem um PR aberto prestes a ser aceito que vai migrar o projeto pra .net standard, acredito que a versão mínima requerida vai ser a 4.6.2.

**Comment by danilobreda** [comment]
@marcosgerene a biblioteca **NFe.Wsdl** continua no .net framework 4.5. O **NFe.Wsdl.Standard**, que está reescrito e migrado para .net standard que realmente a versão inicial é 4.6.1 [seguindo esse link](https://docs.microsoft.com/pt-br/dotnet/standard/net-standard)

@bilhega  Sobre o erro o @robertorp  fez alterações [neste commit](https://github.com/ZeusAutomacao/DFe.NET/commit/28d2c793ce4951e2131f2f6209762706d2773590) que acredito que foi para resolver o problema... A versão utilizado é a 1.0.1.927 ?

[Segue link do nuget](https://www.nuget.org/packages/Zeus.Net.NFe.NFCe/)

**Comment by bilhega** [comment]
@danilobreda Aplicando a nova versão pelo nuget, que contém o referido commit, sanou o erro. Obrigado.
@marcosgerene Obrigado pelo apoio!
