### ISSUE TITLE
XML Autorizado no https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx porem ao consultar o protocolo retorna nulo NFProt

### ISSUE THREAD

**Issue by manoelpvh** [ZeusAutomacao/DFe.NET#1031]
Ola gostaria de saber por que nao consigo fazer a consulta do protocolo sendo que ao criar o arquivo xml ele esta como autorizado no endereço mas Retorno.protNFe esta vindo NULL

**Comment by marcosgerene** [comment]
@manoelpvh 
Não entendi a pergunta, então vou supor o cenário....

Você emitiu a nota de forma assíncrona, ela foi autorizada mas não pegou o retorno de autorização (ficou retornando 103/104 falando sobre o lote). Neste caso:

```
void Transmitir(MinhaClasseNFe bjetonfe, ref string resposta)
{
	// ... constroi objeto nfe, valida, assina, etc...

	NFe.Servicos.Retorno.RetornoNFeAutorizacao retorno = null; //Objeto de retorno da emissão
	using (var _certificado = CertificadoDigital.ObterCertificado(_configuracao.Certificado))
	using (var servicoNfe = new NFe.Servicos.ServicosNFe(_configuracao, _certificado))
		retorno = servicoNfe.NFeAutorizacao(1, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe>() { _nfe }); //Eu prefiro trabalhar de forma sincrona quando possível
			
	var protocolo = retorno.Retorno.protNFe; //Pega o protocolo de retorno

	//Se a UF não implementa a forma sincrona, na propria emissão eu tenho o número do recibo, 
	//se for este o caso basta consultar o número do recibo para pegar o protNFe
	if (protocolo == null && !string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec)) 
	{
		//Tento por 3 vezes pegar o protNFe pelo número do recibo, 
		//talvez o evento NFeRetAutorizacao seja a resposta para o que precisa
		
		for (int tentativas = 0; tentativas < 3; tentativas++)
		{
			NFe.Servicos.Retorno.RetornoNFeRetAutorizacao retornoAutorizacao = null;
			using (var _certificado = CertificadoDigital.ObterCertificado(_configuracao.Certificado))
			using (var servicoNFe = new NFe.Servicos.ServicosNFe(_configuracao, _certificado))
				retornoAutorizacao = servicoNFe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);

			if (retornoAutorizacao.Retorno.protNFe.Count > 0)
				protocolo = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();

			if (protocolo != null)
				break;

			Thread.Sleep(1000);
		}

		if (protocolo == null)
		{
			throw new Exception("Não foi possível recuperar o protocolo da NFe.");
		}
	}

	if (new List<int> { 100, 150 }.Contains(protocolo?.infProt?.cStat ?? 0)) //Se o cstat do protocolo é 100 ou 150 a NFe foi transmitida, então faço os tratamenos
	{
		//NFe transmitida, monte o nfeproc e salve, marque sua nota como emitida, etc
	}
	else if (protocolo?.infProt != null)
		resposta = protocolo.infProt.xMotivo; //Não foi emitida, pega o motivo...
	else
		resposta = retorno.RetornoCompletoStr; //Não foi emitida e não tenho o protocolo então retorna o xml de retorno da sefaz inteiro
}
```

Indo mais direto ao ponto, com o número do recibo você pode consultar o protocolo assim:

```
NFe.Servicos.Retorno.RetornoNFeRetAutorizacao retornoAutorizacao = null;
using (var _certificado = CertificadoDigital.ObterCertificado(_configuracao.Certificado))
using (var servicoNFe = new NFe.Servicos.ServicosNFe(_configuracao, _certificado))
	retornoAutorizacao = servicoNFe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);

if (retornoAutorizacao.Retorno.protNFe.Count > 0)
	protocolo = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();
```

**Comment by manoelpvh** [comment]
esse problema aconteceu tb quando usei a aplicação do zeus fiquei achando que fizeram alguma modificação no endereço do webservice ou algo do tipo pois peguei o arquivo xml que gerei coloquei no endereço de RS para validar e diz que a nota esta autorizada para uso, porem a messagem que me retorna na consulta é:

<retConsSitNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SVRSnfce201809061124</verAplic><cStat>217</cStat><xMotivo>Rejeicao: NF-e nao consta na base de dados da SEFAZ</xMotivo><cUF>11</cUF><dhRecbto>2019-09-03T16:01:28-03:00</dhRecbto><chNFe>11190921652642000145650010000004411000004411</chNFe></retConsSitNFe>


![FOTO](https://user-images.githubusercontent.com/16401521/64255111-bb371b80-ceee-11e9-925b-7c0f664ed8f9.png)

**Comment by marcosgerene** [comment]
@manoelpvh Seu retorno foi lote processado e não emitido.

Para pegar o retono correto você precisar consultar o  recibo até ter um protocolo de retorno. Isso ocorre porque a emissão é feita de forma assincrona.

Note este trecho do código:

```
for (int tentativas = 0; tentativas < 3; tentativas++)
{
	NFe.Servicos.Retorno.RetornoNFeRetAutorizacao retornoAutorizacao = null;
	using (var _certificado = CertificadoDigital.ObterCertificado(_configuracao.Certificado))
	using (var servicoNFe = new NFe.Servicos.ServicosNFe(_configuracao, _certificado))
		retornoAutorizacao = servicoNFe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);

	if (retornoAutorizacao.Retorno.protNFe.Count > 0)
		protocolo = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();

	if (protocolo != null)
		break;

	Thread.Sleep(1000);
}
```

Eu tento 3 vezes (com pausa de um minuto por tentativa) pegar o retorno, esse retorno pode ser positivo (cstat 100 ou 150) ou não. Em caso de retorno negativo ele vai retornar o cstat do erro e o xMotivo.

Note este trecho do código:

```
if (new List<int> { 100, 150 }.Contains(protocolo?.infProt?.cStat ?? 0)) //Se o cstat do protocolo é 100 ou 150 a NFe foi transmitida, então faço os tratamenos
{
	//NFe transmitida, monte o nfeproc e salve, marque sua nota como emitida, etc
}
else if (protocolo?.infProt != null)
	resposta = protocolo.infProt.xMotivo; //Não foi emitida, pega o motivo...
else
	resposta = retorno.RetornoCompletoStr; //Não foi emitida e não tenho o protocolo então retorna o xml de retorno da sefaz inteiro
```

Com o protocolo.infProt.xMotivo consigo saber o que aconteceu.

Lote processado não significa nota emitida, mas sim que o seu lote foi recebido e foi processado pelas sefaz. Para saber o real retorno da sefaz você precisa do xMotivo do infProt do protNFe e você obtem isso com o evento NFeRetAutorizacao() usando o número do recibo.

**Comment by manoelpvh** [comment]
o RetEnviNFe retornou agora 

<cStat>897</cStat>
<xMotivo>Rejeicao: Codigo numerico em formato invalido</xMotivo>

mas essa mensagem so aparece se eu usar o IndicadorSincronizacao.sincrono

**Comment by marcosgerene** [comment]
@manoelpvh 
>o RetEnviNFe retornou agora
>
>897
>Rejeicao: Codigo numerico em formato invalido
>
>mas essa mensagem so aparece se eu usar o IndicadorSincronizacao.sincrono

Como eu disse anteriormente:

>Lote processado não significa nota emitida, mas sim que o seu lote foi recebido e foi processado pelas sefaz. Para saber o real retorno da sefaz você precisa do xMotivo do infProt do protNFe e você obtem isso com o evento NFeRetAutorizacao() usando o número do recibo.

**Você NÃO ESTAVA TENDO SUCESSO, lote processado não é sucesso, sua nota NÃO ESTAVA dando transmitindo**.

Partindo disso, agora vamos tratar seu erro: >Rejeicao: Codigo numerico em formato invalido


A resposta está aqui:

https://blog.tecnospeed.com.br/nt-2019-001-nfe/

Mais especificamente aqui: 
![image](https://user-images.githubusercontent.com/15945003/64274113-1aaa2100-cf19-11e9-84bd-d93eb6982091.png)


O cNF agora é validado. Eu mesmo antes usava o cNf igual o nNF, mudei meu sistema assim:

```
 _ide.cNF = $"1{_ide.nNF.ToString("0000000")}";
```
Se o único erro da sua nota for esse, corrija o cNF conforme a NT exige que a sua nota vai transmitir =)

**Comment by manoelpvh** [comment]
mano, obrigado era isso mesmo eu fiz como foi explicado no endereço 

https://atendimento.tecnospeed.com.br/hc/pt-br/articles/360034114933-Rejei%C3%A7%C3%A3o-897-Informado-C%C3%B3digo-num%C3%A9rico-em-formato-inv%C3%A1lido

e deu certo!

**Comment by marcosgerene** [comment]
@manoelpvh 

>mano, obrigado era isso mesmo eu fiz como foi explicado no endereço
>
>https://atendimento.tecnospeed.com.br/hc/pt-br/articles/360034114933-Rejei%C3%A7%C3%A3o-897-Informado-C%C3%B3digo-num%C3%A9rico-em-formato-inv%C3%A1lido
>
>e deu certo!

Por nada, tmj
