### ISSUE TITLE
Problemas com Encerramento MDF-e

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#1036]
Boa noite, aqui no MT, estamos tendo que emitir NF-e para produtor rural CPF., alguns destes produtores, tem que usar transporte proprio para levar sua produção a outro estabelecimento, que deve ser acobertado pelo MDFe, o que ocorre é que fiz um MDFe para o produtor, só que quando tentamos invocar o metodo para obter MDFe's não encerrados o projeto até o presente teste apresentava falta de recurso, pois vi que no código baixado daqui não dispunha do campo CPF na solicitação e a mesma era formada com o campo CNPJ...
Para resolver o problema do cliente, pensei , vou adicionar o campo CPF aqui no projeto e vai dar certo. SEM SUCESSO também infelizmente, então pensei, não vou buscar por MDFe não encerrado, vou fazer direto a solicitação do ENCERRAMENTO do mesmo, então descobri olhando para o código que também não há referencia a CPF dentro do código do MDFe para encerramento, pensei, vou colocar aqui no fonte e resolver o problema. obtive mais erros. Logo não sei se os erros são do sefaz ou de falta de algum recurso do componente e por isso resolvi postar este problema que agora é grave aqui pois tenho MDFe's por encerrar , e não consigo...

Desde já agradeço a quem puder ajudar com esta questão... Obrigado.

Foto do Trecho da falta do campo CPF no componente...
![image](https://user-images.githubusercontent.com/11932503/64999389-99a63e80-d8b5-11e9-9164-0d9fa50b2d29.png)

**Comment by guimagcpd** [comment]
Complementando...
Acabo de fazer os testes de Consulta não Encerrados pelo UNINFE e deu certo obtive retorno. e também fiz o encerramento pelo Uninfe tb obtive retorno positivo, resumindo... é uma falta do recurso na DLL do projeto aqui e estou dando estes feeds porque eu estou passando por isso aqui no MT com CPF de cliente produtor rural, e isto pode se tornar uma necessidade de todos um DIA.

desde já agradeço .

**Comment by robertorp** [comment]
https://github.com/ZeusAutomacao/DFe.NET/commit/103130abf36929343cc9460e875601a8ad7b6980
Ajustes feito. 
Obrigado, pode ficar a vontade também para contribuir diretamente com os fontes, através de pull requests.
