### ISSUE TITLE
CEP do enderToma do CTe nao considera zero a esquerda.

### ISSUE THREAD

**Issue by MurilloConti** [ZeusAutomacao/DFe.NET#1038]
Olá pessoal, 
Primeiramente parabéns pela DLL, muito completa.
Notei apenas um problema quando é preciso informar um tomador toma4 e o CEP é iniciado por 0 o mesmo é desconsiderado, visto que o tipo do campo é long e não existe um proxyCEP nessa classe. 
Já até fiz a alteração, se quiserem posso contribuir com um pull request.

**Comment by marcosgerene** [comment]
@MurilloConti 
Por favor, envie o PR.

Obrigado

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/1041
