### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by MarceloLeandro** [ZeusAutomacao/DFe.NET#104]
Amigo, estou com uma dúvida referente a sua dll, mais especifico na consulta do webservice, vi que você utilizou os annotations e a classe soaphttpprotocol, porém, ao realizar chamada do web service da sefaz "asmx" está ok, mas pra chamar um wsdl web service da sefaz em java, ele retorna um erro de soap serializaçao....nao consegue receber como xmlnode aquele resultado que é passado pelo java....poderia dar um help nisso?

**Comment by robertorp** [comment]
Não tem como você converter como uma string (antes de retornar o xmlnode vc converte para string) não? Porque pelo que entendi você esta chamando as dll no java.

**Comment by MarceloLeandro** [comment]
public XmlNode ExecuteZip([XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")] string nfeDadosMsgZip)
        {
            var results = Invoke("nfeAutorizacaoLoteZip", new object[] {nfeDadosMsgZip});
            return ((XmlNode) (results[0]));

Na estrutura da dll, ele usa var....entao recebe qualquer coisa...mas quando voce passa, ele da o erro no metodo invoke da classe soap

InnerException = {"org.xml.sax.SAXException: SimpleDeserializer encountered a child element, which is NOT expected, in something it was trying to deserialize."}

**Comment by MarceloLeandro** [comment]
Ao realizar a chamada pelo invoke para um wsdl java...deve-se fazer algo? ou é da mesma forma de consulta do asmx?

**Comment by SilverioMiranda** [comment]
Poderia utilizar o aplicativo de testes "NFe.AppTeste" no mesmo webservice que você está tendo problemas, e qual é a sefaz/url dele?

**Comment by MarceloLeandro** [comment]
Estou com problema, quando a url passada é  wsdl e não asmx...no caso exemplo:
https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao?wsdl
UF - PE... utilizam o wsdl...

o erro que dá quando passa na parte do Invoke(); 

é:InnerException = {"org.xml.sax.SAXException: SimpleDeserializer encountered a child element, which is NOT expected, in something it was trying to deserialize."}

Já no caso de "ASMX" ele funciona normalmente... voce recebe o xml de retorno da sefaz...
já teve prob do tipo...?

**Comment by adeniltonbs** [comment]
Marcelo, bom dia.
Implementei, no commit 71d17ed82f1ceba5d3f6141380f378b8cf58cdc9, o envio da mensagem para a SEFAZ compactada, usando o método nfeAutorizacaoLoteZip.

Veja o exemplo de uso na classe NFe.AppTeste.MainWindow, no método BtnCriareEnviar3_Click e BtnCarregaXmlEnvia_Click.

Note que o método NFeAutorizacao da classe NFe.Servicos.ServicosNFe passou a ter um parâmetro a mais "compactarMensagem", que por padrão é falso. Se colocar true na chamada, o método NFeAutorizacao  irá encaminhar a mensagem compactada para a SEFAZ.

Eu testei na SEFAZ SRVS, mas acredito que vai funcionar para todas as SEFAZes.

Dê uma olhada como foi implementado o consumo desse método, para ver se sua dúvida é sanada. Se seu objetivo era encaminhar a mensagem para a SEFAZ compactada, utilizando esta biblioteca, bastará testar para sua SEFAZ e postar aqui os resultados.

Bom dia,

**Comment by MarceloLeandro** [comment]
Na verdade, não é nem a questão da sefaz compactada, utilizo a normal mesmo sem o "zip", o ponto da dúvida é a chamada do web service (método invoke) - Execute onde, independente qual seja o web service da sefaz, quando chamar em alguma uf que seja wsdl(java) ele me retorna aquele erro que postei acima, substituindo por um asmx, ele me retorna normal e consigo no "return (xmlnode)(results[0)" receber o xml de resposta da sefaz...você já tentou consumir algum web services desse...seja StatusServiço, Consulta protocolo, com uma url wsdl deles? tipo a uf PE....e etc
Agradeço a atenção!!!

**Comment by adeniltonbs** [comment]
Testei aqui com a aplicação de demonstração de uso da biblioteca para a UF de PE. Veja os resultados que obtive abaixo:

# Ambiente de homologação:

![image](https://cloud.githubusercontent.com/assets/6733483/13463053/3997419e-e069-11e5-9141-cf93efe42f1a.png)

![image](https://cloud.githubusercontent.com/assets/6733483/13463064/45188604-e069-11e5-8e92-d0668ca2ad58.png)

# Ambiente de produção:

![image](https://cloud.githubusercontent.com/assets/6733483/13463114/8460f90e-e069-11e5-9c18-27d9e9093162.png)

![image](https://cloud.githubusercontent.com/assets/6733483/13463259/2f3c82b2-e06a-11e5-8054-139133f18094.png)

Você está fazendo esses testes no aplicativo de demonstração de uso da biblioteca?

**Comment by MarceloLeandro** [comment]
Certo, vou tentar fazer os testes.
Eu estava implementando essa chamada do metodo execute dessa forma:

 [XmlAttribute(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao")]
        public nfeCabecMsg nfeCabecMsg { get; set; }
        [SoapHeader("nfeCabecMsg", Direction = SoapHeaderDirection.InOut)]
        [SoapDocumentMethod("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2/nfeStatusServicoNF2", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Bare)]
        [WebMethod(MessageName = "nfeInutilizacaoNF2")]
        [return: XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")]
        public override async Task<XmlNode> CallWebService([XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")] XmlNode nfeDadosMs)
        {
            IAsyncResult asyncresult = await Task.Run(() => BeginInvoke("nfeInutilizacaoNF2", new object[] { nfeDadosMs }, null, null));
            asyncresult.AsyncWaitHandle.WaitOne();
            var results = EndInvoke(asyncresult);
            //var results =  Invoke("nfeStatusServicoNF2", new object[] {nfeDadosMs});
            return ((XmlNode)(results[0]));
        }
    }

Usando Async e também testei sem o async, somente com o Invoke, como você fez na dll
ai foi exatamente neste var result onde ele faz a chamada que aconteceu isto de no caso da URL wsdl ele da o erro, porem, na asmx como na uf BA, ele passa e me da o retorno.

Ao passar a url para chamada do Execute...voce passou essa normal ->    https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao?wsdl

??
ou utiliza outra URL?

Vlw!!!

**Comment by adeniltonbs** [comment]
Só uma informação adicional. Esse ?wsdl que você vê no final de algumas urls não significam necessariamente que o serviço é de outro tipo, embora alguns o sejam. Acessar uma url de um serviço SOAP com ?wsdl no final faz com que ele exiba a descrição de consumo do serviço.

**Comment by MarceloLeandro** [comment]
Isso...

**Comment by adeniltonbs** [comment]
Marcelo a url é essa mesma "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao?wsdl", aliás você pode consultar isso nos fontes da biblioteca.

Agora posso tentar sanar suas dúvidas quanto ao consumo da biblioteca apenas. Dúvidas de outra ordem sugiro colocar num local mais apropriado para isso, como o stackoverflow.

**Comment by MarceloLeandro** [comment]
Amigos...na dll, o método Execute onde possui os soap attributes: webmethod,xmlElement e etc,  é possível parametrizar esses atributos, para construirmos uma abstração disso e reutilizar? e é preciso passa-los? sem declara os soap attributes só chamando o invoke com a url e o nfeCabecMsg ele funciona? Seria uma solução interessante caso haja essas possibilidades...
Aguardo!!!
