### ISSUE TITLE
Notas emitidas por CNPJ

### ISSUE THREAD

**Issue by claudioluciano** [ZeusAutomacao/DFe.NET#1040]
Estou com duvida se é possível consultar as notas emitidas por um CNPJ, hoje consigo consultar as notas emitidas contra um CNPJ pelo metodo `NfeDistDFeInteresse` se não for, seria possível por **web crawler**? 

Provavelmente aqui não seria o melhor lugar para fazer perguntas, mas não encontrei nada no SO e nem em lugar nenhum....

**Comment by marcosgerene** [comment]
Eu também gostaria de saber sobre isso, muitas vezes recebemos clientes de outros sistemas e nem eles ou o escritório sabem informar sequer a última NFe emitida (número).

**Comment by SilverioMiranda** [comment]
Pra testar qual o ultimo número de NF emitida é só tentar enviar tentando usar um número que você sabe que foi gerada

Tipo
Você sabe que foi gerada até a 1000 daí só tentar emitir nf com os 1001 pra frente, é o único jeito que o contador me passou pra poder achar, como da um erro no retorno informando que o n° já foi usado é só ficar testando e a hora que der certo cancelar aquela nf e usar a partir daquele número


mas as NF geradas pelo CNPJ que eu saiba não tem como saber
