### ISSUE TITLE
Encerramento MDF-e Produtor Rural

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#1043]
Bom dia , gostaria de reportar um outro problema no componente relacionado a outra demanda que fiz anteriormente que foi parcialmente resolvida..

Ocorre que não estou conseguindo encerrar pelo Zeus um MDF-e emitido por pessoa FISICA - CPF, aparentemente no código não ta apontando que o encerramento é para um CPF e sim para um CNPJ
e o erro que da ao tentar encerrar é este abaixo..
![image](https://user-images.githubusercontent.com/11932503/65442219-c5677e00-ddf9-11e9-9d1a-852b83673855.png)

vi no código que o procedimento de encerramento está apontando para um CNPJ mesmo o emitente sendo uma PF com CPF...
Segue print da parte que creio ser o problema...
![image](https://user-images.githubusercontent.com/11932503/65442307-ee880e80-ddf9-11e9-9a03-f0375cdebfd9.png)

acredito que ai deveria haver uma validação onde se a pessoa tiver um CNPJ usar a rotina como está porem se for CPF alterar o campo para CPF
conforme proximo print.
![image](https://user-images.githubusercontent.com/11932503/65442421-1bd4bc80-ddfa-11e9-8460-838a70d8128f.png)

Desde já agradeço aos que lerem, Bom trabalho.

**Comment by danilobreda** [comment]
Também existe um problema na questão de tageamento do xml
![image](https://user-images.githubusercontent.com/14843499/65717593-200e0d80-e078-11e9-850a-59d0af0b0061.png)

Na imagem podemos ver que realmente o campo CPF não esta sendo utilizado...

Porem o que achei estranho foi a imagem abaixo...
![image](https://user-images.githubusercontent.com/14843499/65717716-61062200-e078-11e9-8b8a-fa69f7025f99.png)
Ele adiciona zero no campo caso for cpf, deixando-o com o mesmo tamanho do cnpj. Isso esta correto?

**Comment by robertorp** [comment]
https://github.com/ZeusAutomacao/DFe.NET/commit/a78f103a208a5477a0d5cf056b50ad283f341d5a
Ajustado
Lançarei versão mais tarde.
