### ISSUE TITLE
Sugestão: Adicionar dll de Danfe(Standard) no nugget Zeus.NFe.NFCe

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1047]
Existe um trabalho a mais hoje para o uso do projeto, aonde tenho que pegar toda versão nova todas as dll geradas pelo **NFe.Danfe.Fast.Standard **e** NFe.Danfe.Base.Standard**... e gerar na mão o nuget e utilizar no meu sistema.

Aqui utilizamos 100% nuget, não mais dll igual é feito em desktop por exemplo.

Seria interessante já deixar esses 2 projetos no nuget principal. **Zeus.NFe.NFCe**

É claro que ainda fica obrigatório o copiar/colar dos .frx.
Porem fazendo isso já é uma mão na roda para mim e com certeza quem for utilizar! :D

**Comment by robertorp** [comment]
Vou adicionar no domingo. 
Agora uma sugestão somente
é preciso realmente copiar os frx, ele não poderia estar dentro da dll danfe.fast.standard não?

**Comment by danilobreda** [comment]
@robertorp poderia sim, teria que ser de alguma maneira com que ele já copie na saída de build né? ou algo assim... deve ter algumas opções especiais do nugget... vou pesquisar a fundo sobre, mas só as dll por enquanto já seria uma ajuda gigante!

**Comment by jbecchi967** [comment]
Olá,

Primeiramente, parabéns pelo projeto, está sendo muito útil para a minha solução.

No momento estou na mesma situação do @danilobreda, existe alguma previsão de quando as .dll estarão disponíveis no nuget?

Valeu!

**Comment by danilobreda** [comment]
Acredito que esse ponto ainda seja interessante, porem um nuget separado.

**Comment by danilobreda** [comment]
Segue o Nuget de exemplo que gero atualmente... eu não adiciono os .frxs nele, e acredito que esse seja o caminho correto.

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Bredas.Danfe</id>
    <version>1.1.0</version>
    <title>Bredas.Danfe</title>
    <authors>Bredas</authors>
    <owners>Bredas</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectUrl>https://github.com/ZeusAutomacao/DFe.NET</projectUrl>
    <iconUrl>https://avatars0.githubusercontent.com/u/32456879?s=200&amp;v=4</iconUrl>
    <description>Biblioteca para geração de nf-e e nfc-e.</description>
    <releaseNotes></releaseNotes>
    <copyright>zeus</copyright>
    <language>pt-BR</language>
    <tags>nfc-e nf-e nfce nfe</tags>
  </metadata>
  <files>
    <file src="lib\netstandard2.0\NFe.Danfe.Base.Standard.dll" target="lib\netstandard2.0\NFe.Danfe.Base.Standard.dll" />
    <file src="lib\netstandard2.0\NFe.Danfe.Fast.Standard.dll" target="lib\netstandard2.0\NFe.Danfe.Fast.Standard.dll" />
  </files>
</package>
```
@robertorp poderia começar a gerar esses nugets?

**Comment by evertonbatini** [comment]
No README.md tem essas informações:

> Impressão (.NetCore/.NetStandard):
> 
> A impressão da NFe utiliza o FastReport.OpenSource (https://github.com/FastReports/FastReport), sendo ele instalado automatico ao utilizar o pacote nuget do Zeus.

Da a impressão que já vem a Danfe junto no pacote do Zeus, mas precisa adicionar as duas Dll's manualmente.

**Comment by danilobreda** [comment]
@robertorp era interessante criar um nuget separado apenas para esse processo, hoje internamente eu crio um para utilizar. Quem utiliza nuget e precise usar hoje .net core não tem o que fazer, não vai conseguir utilizar! Isso deve ser sanado.

**Comment by denernun** [comment]
> Vou adicionar no domingo.
> Agora uma sugestão somente
> é preciso realmente copiar os frx, ele não poderia estar dentro da dll danfe.fast.standard não?

> @robertorp era interessante criar um nuget separado apenas para esse processo, hoje internamente eu crio um para utilizar. Quem utiliza nuget e precise usar hoje .net core não tem o que fazer, não vai conseguir utilizar! Isso deve ser sanado.

Isso ajudaria bastante mesmo ! Alguma previsão @robertorp ? ou como poderíamos a ajudar nisso, apesar de não entender nada de nuget...infelizmente.

**Comment by danilobreda** [comment]
Será feita na #1198
