### ISSUE TITLE
Duplicidade ao enviar NFe

### ISSUE THREAD

**Issue by PauloZier** [ZeusAutomacao/DFe.NET#1048]
Estou com um problema ao enviar NFes e obter retorno de duplicidade. Com este problema eu implementei um log no método e uma consulta de protocolo com a chave da nova nota a ser enviada. 

Reparei que mesmo com a chave sendo inexistente no sefaz houve retorno de duplicidade.

O que posso fazer ?

**Comment by rodrigordi** [comment]
Paulo,
bom dia! Rodrigo está de férias e retornará no dia  16/10.

Na ocasião ele irá retornar seu e-mail.

Cordialmente,

Marcelo Rocha
RDI

De: Paulo Zier <notifications@github.com>
Enviada em: segunda-feira, 30 de setembro de 2019 10:14
Para: ZeusAutomacao/DFe.NET <DFe.NET@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ZeusAutomacao/DFe.NET] Duplicidade ao enviar NFe (#1048)


Estou com um problema ao enviar NFes e obter retorno de duplicidade. Com este problema implementei um log no método e uma consulta de protocolo com a chave da nova nota a ser enviada.

Reparei que mesmo com a chave sendo inexistente no sefaz houve retorno de duplicidade.

O que posso fazer ?

**Comment by PauloZier** [comment]
Muito obrigado!

**Comment by marcosgerene** [comment]
@PauloZier 
A combinação de número, modelo e série para o emissor não pode se repetir, e não necessariamente a chave vai bater.

Ex: Emiti a nota número 10 em 08/2017 e vou tentar emitir o número 10 de novo agora...
minha chave gerada será: 351909... e a antiga é 351708... (aonde 35 é UF (SP), 19 ou 17 é o ano e 09 ou 08 é o mês).

A chave não existirá mas o número já foi utilizado anteriormente, logo duplicidade.

**Comment by PauloZier** [comment]
Marcos bom dia !

Primeiramente muito obrigado pela atenção e pela biblioteca.

Nós utilizamos uninfe pra envio de notas e não tínhamos problemas, queremos
migrar para o zeus pelo motivo de velocidade de operação e maior controle
do que está acontecendo no programa.
Utilizando o zeus temos estes problemas de retorno em duplicidade muito
constantemente.

Em seg, 30 de set de 2019 10:55, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@PauloZier 

>Utilizando o zeus temos estes problemas de retorno em duplicidade muito
constantemente.

Existe um erro na implementação então, pois é o usuário que define os parametros (número, série e modelo) que gerariam uma duplicidade.

Cole aqui sua rotina de transmissão para que eu possa tentar te ajudar melhor.

**Comment by PauloZier** [comment]
/* Marcos bom dia!
* Ontem verifiquei um log e a nota foi validada no Sefaz e da mesma forma
me retornou duplicidade
*/

public string EnviarNFe(string xml)
        {
            try
            {
                var nfe = new Classes.NFe().CarregarDeXmlString(xml);

                //limpando todas informaçoes
                LimparDados();

                //validando certificado
                ValidarCertificadoException();

                if (nfe.infNFe.ide.mod == ModeloDocumento.NFCe)
                {
                    nfe.Assina();

                    if (string.IsNullOrWhiteSpace(this.CIdToken)) throw new
Exception(
"Não foi encontrado o IdToken para emissão de NFC-e, verificar as
configurações."
);
                    if (string.IsNullOrWhiteSpace(this.Csc)) throw new
Exception(
"Não foi encontrado o CSC para emissão de NFC-e, verificar as configurações."
);


                    nfe.infNFeSupl = new infNFeSupl();
                    if (ConfiguracaoServico.Instancia.VersaoLayout ==
 VersaoServico.Versao400)
                        nfe.infNFeSupl.urlChave =
 nfe.infNFeSupl.ObterUrlConsulta(nfe, ConfiguracaoDanfeNfce.VersaoQrCode);

                    nfe.infNFeSupl.qrCode =
 nfe.infNFeSupl.ObterUrlQrCode(nfe, ConfiguracaoDanfeNfce.VersaoQrCode, this
.CIdToken, this.Csc);
                }


                string ChaveAcessoNFe = nfe.infNFe.Id.Substring(3, 44);


//se o tipo de ambiente configurado no zeus, for diferente do
informado na NF-e, dá erro.
                if (nfe.infNFe.ide.tpAmb !=
 ConfiguracaoServico.Instancia.tpAmb)
                    throw new Exception(
$"Documento enviado difere o tipo de emissão.
\nConfigurado:{ConfiguracaoServico.Instancia.tpAmb.ToString()} \nNF-e
Enviada:{nfe.infNFe.ide.tpAmb.ToString()}"
);


                //salvando Xml Cru
                SalvarArquivoXml(ChaveAcessoNFe + "-NFe"
, Status.Autorizados, DateTime.Now, xml);

                //definindo Modelo 55 ou 65 .... e UF
                SetModelo(nfe.infNFe.ide.mod.GetHashCode().ToString());
                SetUF(nfe.infNFe.ide.cUF.GetHashCode().ToString());


                int numLote = 1;//

                nfe.Assina();
//não precisa validar aqui, pois o lote será validado em
ServicosNFe.NFeAutorizacao

                var servicoNFe = new ServicosNFe
(ConfiguracaoServico.Instancia);
                RetornoNFeAutorizacao retornoNFeAutorizacao =
 servicoNFe.NFeAutorizacao(numLote, IndicadorSincronizacao.Assincrono, new
List<Classes.NFe> { nfe });


//103-Lote recebido com sucesso | 104-Lote processado | 105-Lote em
processamento
                if (retornoNFeAutorizacao.Retorno.cStat == 103 ||
 retornoNFeAutorizacao.Retorno.cStat == 104 ||
 retornoNFeAutorizacao.Retorno.cStat == 105)
                {
                    // Tempo para conferir a variavel
                    Thread.Sleep(500);

//se for Lote em processamento aguardar um tempo para consultar recibo.
                    if (retornoNFeAutorizacao.Retorno.cStat == 105)
                        Thread.Sleep(2000);

                    RetornoNFeRetAutorizacao retAutorizacao =
 servicoNFe.NFeRetAutorizacao(retornoNFeAutorizacao.Retorno.infRec.nRec);

                    // retorno correto (esperado)
                    if (retAutorizacao.Retorno.protNFe[0].infProt.cStat ==
100)
                    {

                        //definindo e montando xml de retorno
                        string xmlRetorno =
 ClsXml.montarXmlNfe(nfe.ObterXmlString(), retAutorizacao.RetornoCompletoStr);
                        //salvando xml de retorno no disco (autorizado)
                        SalvarArquivoXml(ChaveAcessoNFe + "-procNFe"
, Status.Autorizados, DateTime.Now, xmlRetorno);


                        int xCstat = retAutorizacao.Retorno.protNFe[0
].infProt.cStat;
                        string xMotivo = retAutorizacao.Retorno.protNFe[0
].infProt.xMotivo;
                        //100 - NFe Autorizada
                        bool xErro = (xCstat != 100);

                        //definindo os dados
                        SetarDados(xCstat, xErro, xMotivo, xmlRetorno);


                        //return xmlRetorno; //Antes

                        return retAutorizacao.RetornoCompletoStr;

                    }
                    //novo (Tratando NFe Duplicada
                    else if (retAutorizacao.Retorno.protNFe[0
].infProt.cStat == 204)
                    {

                        string xmlRetorno = "";


//pegando numero do recibo no xMotivo (apenas para 204)
                        string nRec = retAutorizacao.Retorno.protNFe[0
].infProt.xMotivo;
                        //pegando apenas o numero
                        nRec = nRec.Substring(nRec.IndexOf("nRec")).Replace(
"nRec:", "").Replace("]", "");


                        var ConsultandoStatusNFe =
 servicoNFe.NfeConsultaProtocolo(ChaveAcessoNFe);

                        if
 (ConsultandoStatusNFe.Retorno.procEventoNFe.Count > 0)
                        {
                            for (int i = 0; i <
 ConsultandoStatusNFe.Retorno.procEventoNFe.Count; i++)
                            {
                                if ((int
)ConsultandoStatusNFe.Retorno.procEventoNFe[i].retEvento.infEvento.tpEvento
== 110111) //cancelamento
                                {
                                    //protocolo NFe
                                    var protocolo =
 ConsultandoStatusNFe.Retorno.protNFe.infProt.nProt;
                                    var CNPJEmit = nfe.infNFe.emit.CNPJ;
                                    var justificativa =
 ConsultandoStatusNFe.Retorno.procEventoNFe[i].evento.infEvento.detEvento.xJust;

                                    RetornoRecepcaoEvento
 retSefazCancelamento = servicoNFe.RecepcaoEventoCancelamento(1, 1
, protocolo, ChaveAcessoNFe, justificativa, CNPJEmit);

                                    XmlCancelamento =
 ClsXml.MontarXML_CancelamentoOuCCe(retSefazCancelamento.EnvioStr,
ConsultandoStatusNFe.RetornoCompletoStr);
                                    SalvarArquivoXml(ChaveAcessoNFe +
"_110111_01-procEventoNFe"
, Status.Autorizados, nfe.infNFe.ide.dhEmi.DateTime, XmlCancelamento);

                                }
                            }
                        }
                        if
 (ConsultandoStatusNFe.Retorno.protNFe.infProt.cStat == 100)
                        {
                            RetornoNFeRetAutorizacao retAutorizacaoDupl =
 servicoNFe.NFeRetAutorizacao(nRec);

                            //definindo e montando xml de retorno
                            xmlRetorno =
 ClsXml.montarXmlNfe(nfe.ObterXmlString(),
retAutorizacaoDupl.RetornoCompletoStr);
                            //salvando xml de retorno no disco (autorizado)
                            SalvarArquivoXml(ChaveAcessoNFe + "-procNFe"
, Status.Autorizados, DateTime.Now, xmlRetorno);
                        }




//Dados da primeira consulta de autorização (vai retornar DUPLICADA,
mas tem o preenchimento da NFe se o recibo da duplicada tiver
autorizado)
                        int xCstat = retAutorizacao.Retorno.protNFe[0
].infProt.cStat;
                        string xMotivo = retAutorizacao.Retorno.protNFe[0
].infProt.xMotivo;
                        //135 - Inutilização de numeros Autorizado
                        bool xErro = (xCstat != 100);

                        //definindo os dados
                        SetarDados(xCstat, xErro, xMotivo, xmlRetorno);


                        return retAutorizacao.RetornoCompletoStr;
                    }
                    //Quando ocorre algum erro entra aqui
                    else
                    {

                        //salvando xml na pasta denegado
                        SalvarArquivoXml(ChaveAcessoNFe + "-procNFe"
, Status.Denegados, DateTime.Now, retAutorizacao.RetornoCompletoStr);


                        int xCstat = retAutorizacao.Retorno.protNFe[0
].infProt.cStat;
                        string xMotivo = retAutorizacao.Retorno.protNFe[0
].infProt.xMotivo;
                        //135 - Inutilização de numeros Autorizado
                        bool xErro = (xCstat != 100);

                        //definindo os dados
                        SetarDados(xCstat, xErro, xMotivo, "");

                        return retAutorizacao.RetornoCompletoStr;
                    }
                }
                else
                {
                    int xCstat = retornoNFeAutorizacao.Retorno.cStat;
                    string xMotivo = retornoNFeAutorizacao.Retorno.xMotivo;
                    //135 - Inutilização de numeros Autorizado
                    bool xErro = (xCstat != 100);

                    //definindo os dados
                    SetarDados(xCstat, xErro, xMotivo, "");

                    return retornoNFeAutorizacao.RetornoCompletoStr;
                }
            }
            catch (Exception ex)
            {
                //definindo os dados
                SetarDados(0, true, ex.ToString(), "");

                return ex.ToString();
            }

Em ter, 1 de out de 2019 às 08:56, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@PauloZier 

Você está recebendo esse problema de uma NFe ou NFCe?

-------

O que faz isso (setmodelo e setuf)?

//definindo Modelo 55 ou 65 .... e UF
SetModelo(nfe.infNFe.ide.mod.GetHashCode().ToString());
SetUF(nfe.infNFe.ide.cUF.GetHashCode().ToString());

-------

use ```isto``` quando for postar código... segue seu código "ajustado" (não mexi em nada, só para os outros amigos também verificarem:

```
public string EnviarNFe(string xml)
{
try
{
	var nfe = new Classes.NFe().CarregarDeXmlString(xml);

	//limpando todas informaçoes
	LimparDados();

	//validando certificado
	ValidarCertificadoException();

	if (nfe.infNFe.ide.mod == ModeloDocumento.NFCe)
	{
		nfe.Assina();

		if (string.IsNullOrWhiteSpace(this.CIdToken)) throw new Exception("Não foi encontrado o IdToken para emissão de NFC-e, verificar as configurações.");
		if (string.IsNullOrWhiteSpace(this.Csc)) throw new Exception("Não foi encontrado o CSC para emissão de NFC-e, verificar as configurações.");

		nfe.infNFeSupl = new infNFeSupl();
		if (ConfiguracaoServico.Instancia.VersaoLayout == VersaoServico.Versao400)
			nfe.infNFeSupl.urlChave = nfe.infNFeSupl.ObterUrlConsulta(nfe, ConfiguracaoDanfeNfce.VersaoQrCode);

		nfe.infNFeSupl.qrCode = nfe.infNFeSupl.ObterUrlQrCode(nfe, ConfiguracaoDanfeNfce.VersaoQrCode, this.CIdToken, this.Csc);
	}

	string ChaveAcessoNFe = nfe.infNFe.Id.Substring(3, 44);

	//se o tipo de ambiente configurado no zeus, for diferente do informado na NF-e, dá erro.
	if (nfe.infNFe.ide.tpAmb != ConfiguracaoServico.Instancia.tpAmb)
		throw new Exception($"Documento enviado difere o tipo de emissão.\nConfigurado:{ConfiguracaoServico.Instancia.tpAmb.ToString()} \nNF-e Enviada:{nfe.infNFe.ide.tpAmb.ToString()}");

	//salvando Xml Cru
	SalvarArquivoXml(ChaveAcessoNFe + "-NFe", Status.Autorizados, DateTime.Now, xml);

	//definindo Modelo 55 ou 65 .... e UF
	SetModelo(nfe.infNFe.ide.mod.GetHashCode().ToString());
	SetUF(nfe.infNFe.ide.cUF.GetHashCode().ToString());

	int numLote = 1;
	nfe.Assina();
	//não precisa validar aqui, pois o lote será validado em ServicosNFe.NFeAutorizacao

	var servicoNFe = new ServicosNFe(ConfiguracaoServico.Instancia);
	RetornoNFeAutorizacao retornoNFeAutorizacao = servicoNFe.NFeAutorizacao(numLote, IndicadorSincronizacao.Assincrono, new List<Classes.NFe> { nfe });

//103-Lote recebido com sucesso | 104-Lote processado | 105-Lote em processamento
	if (retornoNFeAutorizacao.Retorno.cStat == 103 || retornoNFeAutorizacao.Retorno.cStat == 104 || retornoNFeAutorizacao.Retorno.cStat == 105)
	{
		// Tempo para conferir a variavel
		Thread.Sleep(500);

		//se for Lote em processamento aguardar um tempo para consultar recibo.
		if (retornoNFeAutorizacao.Retorno.cStat == 105)
			Thread.Sleep(2000);

		RetornoNFeRetAutorizacao retAutorizacao = servicoNFe.NFeRetAutorizacao(retornoNFeAutorizacao.Retorno.infRec.nRec);

		// retorno correto (esperado)
		if (retAutorizacao.Retorno.protNFe[0].infProt.cStat == 100)
		{
			//definindo e montando xml de retorno
			string xmlRetorno = ClsXml.montarXmlNfe(nfe.ObterXmlString(), retAutorizacao.RetornoCompletoStr);
			//salvando xml de retorno no disco (autorizado)
			SalvarArquivoXml(ChaveAcessoNFe + "-procNFe", Status.Autorizados, DateTime.Now, xmlRetorno);


			int xCstat = retAutorizacao.Retorno.protNFe[0].infProt.cStat;
			string xMotivo = retAutorizacao.Retorno.protNFe[0].infProt.xMotivo;
			
			//100 - NFe Autorizada
			bool xErro = (xCstat != 100);

			//definindo os dados
			SetarDados(xCstat, xErro, xMotivo, xmlRetorno);

			//return xmlRetorno; //Antes
			return retAutorizacao.RetornoCompletoStr;
		}
		//novo (Tratando NFe Duplicada
		else if (retAutorizacao.Retorno.protNFe[0].infProt.cStat == 204)
		{
			string xmlRetorno = "";

			//pegando numero do recibo no xMotivo (apenas para 204)
			string nRec = retAutorizacao.Retorno.protNFe[0].infProt.xMotivo;
			
			//pegando apenas o numero
			nRec = nRec.Substring(nRec.IndexOf("nRec")).Replace("nRec:", "").Replace("]", "");


			var ConsultandoStatusNFe = servicoNFe.NfeConsultaProtocolo(ChaveAcessoNFe);

			if (ConsultandoStatusNFe.Retorno.procEventoNFe.Count > 0)
			{
				for (int i = 0; i < ConsultandoStatusNFe.Retorno.procEventoNFe.Count; i++)
				{
					if ((int)ConsultandoStatusNFe.Retorno.procEventoNFe[i].retEvento.infEvento.tpEvento == 110111) //cancelamento
					{
						//protocolo NFe
						var protocolo = ConsultandoStatusNFe.Retorno.protNFe.infProt.nProt;
						var CNPJEmit = nfe.infNFe.emit.CNPJ;
						var justificativa = ConsultandoStatusNFe.Retorno.procEventoNFe[i].evento.infEvento.detEvento.xJust;

						RetornoRecepcaoEvento retSefazCancelamento = servicoNFe.RecepcaoEventoCancelamento(1, 1, protocolo, ChaveAcessoNFe, justificativa, CNPJEmit);

						XmlCancelamento = ClsXml.MontarXML_CancelamentoOuCCe(retSefazCancelamento.EnvioStr, ConsultandoStatusNFe.RetornoCompletoStr);
						SalvarArquivoXml(ChaveAcessoNFe + "_110111_01-procEventoNFe", Status.Autorizados, nfe.infNFe.ide.dhEmi.DateTime, XmlCancelamento);
					}
				}
			}
			if (ConsultandoStatusNFe.Retorno.protNFe.infProt.cStat == 100)
			{
				RetornoNFeRetAutorizacao retAutorizacaoDupl = servicoNFe.NFeRetAutorizacao(nRec);

				//definindo e montando xml de retorno
				xmlRetorno = ClsXml.montarXmlNfe(nfe.ObterXmlString(), retAutorizacaoDupl.RetornoCompletoStr);
				//salvando xml de retorno no disco (autorizado)
				SalvarArquivoXml(ChaveAcessoNFe + "-procNFe", Status.Autorizados, DateTime.Now, xmlRetorno);
			}

			//Dados da primeira consulta de autorização (vai retornar DUPLICADA, mas tem o preenchimento da NFe se o recibo da duplicada tiver autorizado)
			int xCstat = retAutorizacao.Retorno.protNFe[0].infProt.cStat;
			string xMotivo = retAutorizacao.Retorno.protNFe[0].infProt.xMotivo;
			
			//135 - Inutilização de numeros Autorizado
			bool xErro = (xCstat != 100);
			
			//definindo os dados
			SetarDados(xCstat, xErro, xMotivo, xmlRetorno);


			return retAutorizacao.RetornoCompletoStr;
		}
		//Quando ocorre algum erro entra aqui
		else
		{
			//salvando xml na pasta denegado
			SalvarArquivoXml(ChaveAcessoNFe + "-procNFe" , Status.Denegados, DateTime.Now, retAutorizacao.RetornoCompletoStr);

			int xCstat = retAutorizacao.Retorno.protNFe[0].infProt.cStat;
			string xMotivo = retAutorizacao.Retorno.protNFe[0].infProt.xMotivo;
			//135 - Inutilização de numeros Autorizado
			bool xErro = (xCstat != 100);

			//definindo os dados
			SetarDados(xCstat, xErro, xMotivo, "");

			return retAutorizacao.RetornoCompletoStr;
		}
	}
	else
	{
		int xCstat = retornoNFeAutorizacao.Retorno.cStat;
		string xMotivo = retornoNFeAutorizacao.Retorno.xMotivo;
		//135 - Inutilização de numeros Autorizado
		bool xErro = (xCstat != 100);

		//definindo os dados
		SetarDados(xCstat, xErro, xMotivo, "");

		return retornoNFeAutorizacao.RetornoCompletoStr;
	}
}
catch (Exception ex)
{
	//definindo os dados
	SetarDados(0, true, ex.ToString(), "");

	return ex.ToString();
}
```

**Comment by PauloZier** [comment]
De uma NF-e

Em ter, 1 de out de 2019 10:40, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by PauloZier** [comment]
Marcos se quiser me adicionar no whats

43996032381

Paulo Zier

Em ter, 1 de out de 2019 11:07, Paulo Zier <paulozier42@gmail.com> escreveu:

**Comment by marcosgerene** [comment]
@PauloZier 

Eu conheço pouco seu código, fiz algumas melhorias (na minha visão, dificil mexer num código "de primeiro contato").

Tenta com o que te mandei agora, veja se tem sucesso.

```
public string EnviarNFe(string xml)
{
	try
	{
		var nfe = new Classes.NFe().CarregarDeXmlString(xml);

		//limpando todas informaçoes
		LimparDados();

		//validando certificado
		ValidarCertificadoException();

		//marcosgerene - sai daqui essa assinatura e verificação
		//if (nfe.infNFe.ide.mod == ModeloDocumento.NFCe)
		//{
		//	nfe.Assina();
		//
		//	if (string.IsNullOrWhiteSpace(this.CIdToken)) throw new Exception("Não foi encontrado o IdToken para emissão de NFC-e, verificar as configurações.");
		//	if (string.IsNullOrWhiteSpace(this.Csc)) throw new Exception("Não foi encontrado o CSC para emissão de NFC-e, verificar as configurações.");
		//
		//	nfe.infNFeSupl = new infNFeSupl();
		//	if (ConfiguracaoServico.Instancia.VersaoLayout == VersaoServico.Versao400)
		//		nfe.infNFeSupl.urlChave = nfe.infNFeSupl.ObterUrlConsulta(nfe, ConfiguracaoDanfeNfce.VersaoQrCode);
		//
		//	nfe.infNFeSupl.qrCode = nfe.infNFeSupl.ObterUrlQrCode(nfe, ConfiguracaoDanfeNfce.VersaoQrCode, this.CIdToken, this.Csc);
		//}

		//marcosgerene - Antes de pegar a chave e assinuar faz o seu "SetModelo e SetUF"
		
		//definindo Modelo 55 ou 65
		SetModelo(nfe.infNFe.ide.mod.GetHashCode().ToString());
		SetUF(nfe.infNFe.ide.cUF.GetHashCode().ToString());

		//marcosgerene - não sei como tava seu calculo do Id então resolvi colocar mais uma validação
		string ChaveAcessoNFe = DFe.Utils.ChaveFiscal.ObterChave(ufEmitente: nfe.infNFe.emit.enderEmit.UF,
                                                                 dataEmissao: nfe.infNFe.ide.dhEmi.DateTime,
                                                                 cnpjEmitente: nfe.infNFe.emit.CNPJ,
                                                                 modelo: nfe.infNFe.ide.mod,
                                                                 serie: nfe.infNFe.ide.serie,
																 numero: nfe.infNFe.ide.nNF,
                                                                 tipoEmissao: (int)nfe.infNFe.ide.tpEmis,
                                                                 cNf: int.Parse(nfe.infNFe.ide.cNF)).Chave;
		
		if (nfe.infNFe.Id != ChaveAcessoNFe)
			throw new Exception("A chave informada difere da chave calculada");

		string ChaveAcessoNFe = ChaveAcessoNFe.Substring(3, 44);

		//se o tipo de ambiente configurado no zeus, for diferente do informado na NF-e, dá erro.
		if (nfe.infNFe.ide.tpAmb != ConfiguracaoServico.Instancia.tpAmb)
			throw new Exception($"Documento enviado difere o tipo de emissão.\nConfigurado:{ConfiguracaoServico.Instancia.tpAmb.ToString()} \nNF-e Enviada:{nfe.infNFe.ide.tpAmb.ToString()}");

		//salvando Xml Cru
		SalvarArquivoXml(ChaveAcessoNFe + "-NFe", Status.Autorizados, DateTime.Now, xml);

		//definindo Modelo 55 ou 65 .... e UF    ====> marcosgerene - não sei pra que serve isso, então faz antes de assinar e pegar a chave, porque a chave depende disso.
		//SetModelo(nfe.infNFe.ide.mod.GetHashCode().ToString());
		//SetUF(nfe.infNFe.ide.cUF.GetHashCode().ToString());

		int numLote = 1; //marcosgerene - seria legal informar isso como parametro do método...
		nfe.Assina();
		
		if (nfe.infNFe.ide.mod == ModeloDocumento.NFCe)
		{
			//	nfe.Assina(); - marcosgerene -estava assinando 2x, perde performace.
		
			if (string.IsNullOrWhiteSpace(this.CIdToken)) throw new Exception("Não foi encontrado o IdToken para emissão de NFC-e, verificar as configurações.");
			if (string.IsNullOrWhiteSpace(this.Csc)) throw new Exception("Não foi encontrado o CSC para emissão de NFC-e, verificar as configurações.");
		
			nfe.infNFeSupl = new infNFeSupl();
			if (ConfiguracaoServico.Instancia.VersaoLayout == VersaoServico.Versao400)
				nfe.infNFeSupl.urlChave = nfe.infNFeSupl.ObterUrlConsulta(nfe, ConfiguracaoDanfeNfce.VersaoQrCode);
		
			nfe.infNFeSupl.qrCode = nfe.infNFeSupl.ObterUrlQrCode(nfe, ConfiguracaoDanfeNfce.VersaoQrCode, this.CIdToken, this.Csc);
		}
				
		//Todo seu método é feito de forma sincrona, tanto que você usa Thread.Sleep... não vejo porque não usar Sincrono aqui...	
		NFe.Servicos.Retorno.RetornoNFeAutorizacao retorno = null;
		
		using (var _certificado = CertificadoDigital.ObterCertificado(ConfiguracaoServico.Instancia.Certificado))
            using (var servicoNfe = new NFe.Servicos.ServicosNFe(ConfiguracaoServico.Instancia, _certificado))
				retorno = servicoNfe.NFeAutorizacao(1, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe>() { _nfe });

		//independente de 103,104 ou 105 eu quero o número do recibo ou o protocolo...
		const int maxtentativas = 5;
		
		var protocolo = retorno.Retorno.protNFe;
		if (!new List<int> { 100 }.Contains(protocolo?.infProt?.cStat ?? 0) && !string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec))
		{
			for (int tentativas = 0; tentativas < maxtentativas; tentativas++)
			{
				NFe.Servicos.Retorno.RetornoNFeRetAutorizacao retornoAutorizacao = null;
				using (var _certificado = CertificadoDigital.ObterCertificado(ConfiguracaoServico.Instancia.Certificado))
				using (var servicoNFe = new NFe.Servicos.ServicosNFe(ConfiguracaoServico.Instancia, _certificado))
					retornoAutorizacao = servicoNFe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);

				if (retornoAutorizacao.Retorno.protNFe.Count > 0)
					protocolo = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();

				if (protocolo != null)
					break;

				Thread.Sleep(1000);
			}

			if (protocolo == null)
			{
				throw new Exception("Não foi possível recuperar o protocolo da NFe.");
			}
		}
		
		if (new List<int> { 100 }.Contains(protocolo?.infProt?.cStat ?? 0))
		{
			//monta o objeto nfeproc
			var _nfeproc = new NFe.Classes.nfeProc() 
			{
				versao = nfe.infNFe.versao,
				NFe = nfe,
				protNFe = protocolo
			};
	
			string xmlNFeProc = _nfeproc.ObterXmlString();
	
			//salvando xml de retorno no disco (autorizado)
			SalvarArquivoXml(ChaveAcessoNFe + "-procNFe", Status.Autorizados, DateTime.Now, xmlNFeProc);
			
			int xCstat = protocolo.infProt.cStat;
			string xMotivo =  protocolo.infProt.xMotivo;
			
			//100 - NFe Autorizada
			bool xErro = (xCstat != 100);

			//definindo os dados
			SetarDados(xCstat, xErro, xMotivo, xmlNFeProc);

			//return xmlRetorno; //Antes
			return retorno.RetornoCompletoStr;
		}
		//else if 204 ...
		//else
	}
	catch (Exception ex)
	{
		//definindo os dados
		SetarDados(0, true, ex.ToString(), "");

		return ex.ToString();
	}
}
```

**Comment by PauloZier** [comment]
Marcos muito obrigado por toda a ajuda! vou tentar este código sim, ficou
show.

Mais uma vez obrigado e desculpas por atrapalhar.

Em ter, 1 de out de 2019 às 11:12, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
@PauloZier 
Poste aqui o resultado se deu certo...

**Comment by PauloZier** [comment]
Sim Marcos pode deixar, ainda não emitimos nota na empresa mas assim que
emitirmos te aviso.

Em ter, 1 de out de 2019 18:05, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by marcosgerene** [comment]
Vou fechar a issue, caso não tenha sucesso reabra, por favor.
