### ISSUE TITLE
FastReport

### ISSUE THREAD

**Issue by clebertorrent** [ZeusAutomacao/DFe.NET#105]
Onde eu consigo a dll ? pois não estou conseguindo compilar..

**Comment by adeniltonbs** [comment]
Dê uma olhada nesse issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/102 e nesse aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/69

**Comment by clebertorrent** [comment]
Obrigado
