### ISSUE TITLE
[Dúvida] Melhores praticas para implementação

### ISSUE THREAD

**Issue by valentimmx** [ZeusAutomacao/DFe.NET#1050]
Bom dia pessoal.

Conheci este componente ontem e gostei muito da organização, estruturação e empenho do pessoal aqui da comunidade. Parabéns aos envolvidos!

Estou estudando as melhores maneiras de implementa-lo junto a meu ERP e começar a contribuir, e venho aqui pedir sugestões de como vocês tem feito essa integração:
Integrado a Solution do ERP, Solution separada e exportando as DLLs, etc.

Enfim, estou buscando uma forma na qual o ZeusNFe fique facil de dar commit/update aqui com o git e a importação dele pra dentro de meu ERP seja simples e o minimo engessada possivel.

EDIT:
Estou pensando em deixar o Zeus em uma Solution separada, dar build, pegar estas DLLs do AppTeste e importar pra dentro do meu projeto, o que acham?

![image](https://user-images.githubusercontent.com/17087193/66056676-e0c73d00-e50d-11e9-9494-10835dbee4b8.png)

Fico grato desde já!

**OBS.: Meu ERP é integralmente em C#.**

**Comment by eduprog** [comment]
@renanmthy  para não inflar aqui, me chama em pvt no telegram ou skype e lhe passo como fizemos aqui na empresa. Foi tranquilo. `eduprog `no skype ou e-mail `eduprog@gmail.com`

**Comment by leandrovip** [comment]
Olá, tenho interesse também nestas informações, poderia criar um grupo? Whats ou Telegram? Seria muito bom. 

[]´s

**Comment by viniciusverasdossantos** [comment]
ja existe um grupo no skype. e telegram. DFe.NET Zeus/ Outros Componentes p/ Automação Come
