### ISSUE TITLE
Erro ao executar o app de teste NFe.Danfe.AppTeste

### ISSUE THREAD

**Issue by pbalbino** [ZeusAutomacao/DFe.NET#1051]
Parabéns pelo projeto. Estou iniciando os estudos no projeto e ao executar o projeto de teste NFe.Danfe.AppTeste aparece o erro na imagem abaixo e não executa:

![Capturar](https://user-images.githubusercontent.com/25305220/66146257-cd39d600-e5e2-11e9-8f54-d994581efb09.PNG)

Estou utilizando o Visual Studio Enterprise 2017
Version 15.9.16

**Comment by danilobreda** [comment]
Olá acredito que isso seja um problema de permissão de usuário, recomendo retirar da pasta Download e jogar em um driver C: por exemplo ou algo assim e verificar as permissões, ou mesmo executar o visualstudio em modo administrador.

Pode ser também algum antivirus, pois a nfe utiliza certificados e conexoes que podem causar alguma interferência...

Existe também essa solução para a resolução desse erro específico: [https://github.com/Codealike/Codealike-KnowledgeBase/blob/master/clear-visual-studio-component-cache.md](https://github.com/Codealike/Codealike-KnowledgeBase/blob/master/clear-visual-studio-component-cache.md)

Caso não funcione verifique se o runtime do .net framework 4.5 está instalado e também recomendo atualizar o vs para uma nova versão, mesmo que a community que é de graça(Você pode ter as 2 versões em paralelo!).

Aguardo seu retorno.

**Comment by pbalbino** [comment]
Obrigado Danilo, após mover o fonte para o drive C: e instalar o VS 2019 o erro não ocorreu mais. Gostaria de saber se pode me ajudar em mais uma dúvida, porém não sei se aqui é o canal para isso, mas queria saber se com esse componente eu consigo imprimir o DANFE de NFCe em uma impressora térmica da Bematech "MP 4200 TH"?

**Comment by danilobreda** [comment]
@pbalbino  criei uma nova [issue aqui](https://github.com/ZeusAutomacao/DFe.NET/issues/1058), para que possam responder mais rapidamente e diretamente.
Fique tranquilo par perguntar qualquer coisa... Já pode fechar essa issue 👍
