### ISSUE TITLE
Erro ao usar o Metodo MDFeEventoIncluirDFe()

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1055]
retorna esse erro: O tipo MDFe.Classes.Informacoes.Evento.CorpoEvento.MDFeEvIncDFeMDFe não era esperado. Use o atributo XmlInclude ou SoapInclude para especificar tipos que não são conhecidos estaticamente.

**Comment by alexsiilvaa** [comment]
Criado PR com a correção
https://github.com/ZeusAutomacao/DFe.NET/pull/1061
