### ISSUE TITLE
É possível imprimir o DANFE de NFCe em impressora térmica da Bematech "MP 4200 TH"?

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1058]
Gostaria de saber se pode me ajudar em mais uma dúvida, porém não sei se aqui é o canal para isso, mas queria saber se com esse componente eu consigo imprimir o DANFE de NFCe em uma impressora térmica da Bematech "MP 4200 TH"?

_Originally posted by @pbalbino in https://github.com/ZeusAutomacao/DFe.NET/issues/1051#issuecomment-538971301_

**Comment by marcosgerene** [comment]
Sim, é a mesma estrutura da NFe, só que DanfeNFCE ao invés da NFe

**Comment by danilobreda** [comment]
@pbalbino respondido?

**Comment by pbalbino** [comment]
Obrigado!
