### ISSUE TITLE
NFe Danfe - Data e Hora da impressão vir como parametro

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1059]
A data e hora da impressão do DANFE esta vindo como hora do servidor, poderia ser uma variável para que eu possa definir qual a hora da impressão corretamente.
Essa problema acontece pois o horário do servidor não é o mesmo local da maquina que esta imprimindo, por ser um sistema web. Porem eu consigo passar por variável um horário correto.

![image](https://user-images.githubusercontent.com/14843499/66600394-c8919680-eb7b-11e9-99fb-8eed6a604c37.png)

**Comment by marcosgerene** [comment]
@danilobreda 
Eu não tenho essa necessidade, mas concordo com você, mas tem que manter o padrão caso o usuário não informe nada.... mande o PR que aceito aqui.

Abraço

**Comment by danilobreda** [comment]
Ainda não tive tempo de modificar, outro campo de data/hora deverá conter o UTC local da hora da emissão da nota fiscal eletronica.
