### ISSUE TITLE
Dúvida procedimentos de configuração AppTeste

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#106]
Adenilton boa noite. 

Parabéns pelo seu projeto .. acho que um dos mais completos que já vi para CSHARP. 
Very useful !

Vc tem um passo a passo das configurações do AppTest para eu ver se está tudo ok com a NFe 3.0 ???

Vou adaptá-lo para fazer a leitura dos itens da NF de um arquivo TXT  de um cliente.. se ficar bom te mando o resultado para vc analisar.

Abraço e parabéns novamente.

Ricardo Oliveira

**Comment by LeonardoMoraes1989** [comment]
Olá rcoproc, boa noite,
Eu também estou precisando desse passo a passo das configurações.
Inclusive estou tomando erro na hora de emitir uma NFCe normal em homologação, se conseguir ajuda, me avisa por favor.

**Comment by adeniltonbs** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki/Nunca-emiti-uma-NF,-meu-sistema-n%C3%A3o-tem-isso.-Preciso-implantar-NFe-e-agora%3F

Obs; Se vocês não entenderem como funciona o projeto da NFe, conforme descrito no "Manual de Orientação do Contribuinte", certamente terão muita dificuldade para consumir a biblioteca.

Para emitir uma NFe/NFCe usando o aplicativo de demonstração (cujos métodos estão documentados por meio de comentários no código, assim como toda a biblioteca e seus métodos/propriedades), depois de preencher os campos nas guias "Certificado", "Geral", "WebService" e "Emitente", basta clicar no botão "Criar e Enviar 3.0".

![image](https://cloud.githubusercontent.com/assets/6733483/13743835/f540363c-e9c2-11e5-8127-1b363886c867.png)

**Comment by rcoproc** [comment]
Adenilton.. boa noite eu fiz os procedimentos e configurações conforme me disse acima.

Na hora hora de criar e enviar.. aparece a mensagem  "Erros de valida~cão: o Elemento enderEmit apresenta elemento filho cMun no espaço para nome ... Lista de possíveis elementos esperados: xLgr,"

![erro_ender_emit](https://cloud.githubusercontent.com/assets/7529472/14128408/0c5dfa4e-f5f7-11e5-9ed1-eb6dfb7fcd9d.JPG)

Veja o xml como está:

```
  <finNFe>1</finNFe>
  <indFinal>1</indFinal>
  <indPres>1</indPres>
  <procEmi>0</procEmi>
  <verProc>1.0.1</verProc>
</ide>
<emit>
  <CNPJ>01110262000171</CNPJ>
  <xNome>ARMAZEM 2071 COMERCIO DE ARTIGOS ESPORTIVOS LTDA</xNome>
  <enderEmit>
    <xLgr>AV HIST RUBENS DE MENDONCA</xLgr>
    <nro>3300</nro>
    <xBairro>JD ACLIMACAO</xBairro>
    <cMun>5103403</cMun>
    <xMun>CUIABA</xMun>
    <UF>MT</UF>
    <CEP>78050000</CEP>
    <cPais>1058</cPais>
    <xPais>BRASIL</xPais>
    <fone>6539014149</fone>
  </enderEmit>
  <IE>131676644</IE>
  <CRT>3</CRT>
</emit>
<det nItem="1">
  <prod>
```

**Comment by adeniltonbs** [comment]
Veja este guia:
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114
