### ISSUE TITLE
DACTE Cte Anulação - Conversão especificada não é válida

### ISSUE THREAD

**Issue by mvtaraujo** [ZeusAutomacao/DFe.NET#1062]
Estou com problemas no DACTE quando o CTe é de anulação. Já tentei localizar o problema mais não consegui. Alguém com o mesmo problema?

No resource vi que tinha uma conversão errada, achei que fosse ela, corrigi, mais não adiantou.

switch(Convert.ToInt32((tpCTe)Report.GetColumnValue(&quot;cteProc.CTe.infCte.ide.tpServ&quot;)))
      {
        case 0: Text42.Text = &quot;NORMAL&quot;; break;
        case 1: Text42.Text = &quot;SUBCONTRATAÇÃO&quot;; break;
        case 2: Text42.Text = &quot;REDESPACHO&quot;; break;
        case 3: Text42.Text = &quot;REDESPACHO INTERMEDIÁRIO&quot;; break;
        case 4: Text42.Text = &quot;SERV. VINC. MULTIMODAL&quot;; break;
        case 6: Text42.Text = &quot;TRANSPORTE DE PESSOAS&quot;; break;
        case 7: Text42.Text = &quot;TRANSPORTE DE VALORES&quot;; break;
        case 8: Text42.Text = &quot;EXCESSO DE BAGAGEM&quot;; break;
      }

**Comment by marcosgerene** [comment]
O problema está na conversão da data de emissão do CTe original, o erro estoura na linha 242 do report.
```
Text211.Text += "   emissão: " + FormatDateTime(((DateTimeOffset)Report.GetColumnValue("cteProc.CTe.infCte.infCteAnu.dEmi")).Date, @"dd/MM/yyyy");
```

Vou estudar uma correção, posto updates.

---------

O erro acontece porque o tipo do campo na classe infCteAnu é DateTime e no relatório está DateTimeOffset.

![image](https://user-images.githubusercontent.com/15945003/66965693-faf63480-f050-11e9-8389-1286cd1777e6.png)

----------

Não sei se é a melhor abordagem porque não sei quem colocou DateTimeOffset, preciso que analisem melhor, mas de qualquer forma corrigi o relatório para ficar igual a classe, se for necessário utilziar DateTimeOffset no proximo commit deve-se arrumar na classe e no .frx.

PR: https://github.com/ZeusAutomacao/DFe.NET/pull/1063

[]'s

**Comment by mvtaraujo** [comment]
Obrigado @marcosgerene
