### ISSUE TITLE
[Duvida] Deserializar XSD em Classe

### ISSUE THREAD

**Issue by valentimmx** [ZeusAutomacao/DFe.NET#1065]
Boa tarde pessoal.

As entidades referentes a NFe, Retornos da Sefaz e etc, foram criadas manualmente ou foram deserializadas dos schemas XSD?

Caso tenha sido do XSD, como voces fazem para que essa deserialização fique limpa assim? Com a documentação, nomes dos campos identicos aos do XML e etc.

Eu tentei fazer pelo XSD.exe do Visual Studio e XSD2Code porém ambos me retornaram classes meio bugadas, com as definições todas emendadas como mostra a imagem abaixo.

![image](https://user-images.githubusercontent.com/17087193/67108028-f8f0ba80-f1a3-11e9-89d6-21587e31c8e2.png)

Até da pra trabalhar assim, porém pra quem gosta de código limpo, isso não soa nada agradavel, vejam:

![image](https://user-images.githubusercontent.com/17087193/67108538-22f6ac80-f1a5-11e9-8d89-40cbac009ac5.png)

Faço esta pergunta pois estou usando apenas a DLL do Zeus e preciso recriar estas entidades dentro de meu ERP para trabalhar com os objetos retornados pela DLL.
" - Ah mas as entidades podem ser usadas referenciando a DLL"
Sim, podem, porém se eu ficar passeando com uma entidade da DLL dentro de meu ERP, o acoplamento com o Zeus será muito grande, e quero evitar isso.

Fico aberto a sugestões, muito obrigado pela atenção.

**Comment by valentimmx** [comment]
As entidades estão fragmentadas em muitos namespaces diferentes, leva muito tempo pra junta-las todas em um unico namespace.
Até é viavel desprender tempo pra isso, porém quando sair alguma atualização de leiaute, terei que implementar manualmente campo a campo, e minha intenção é automatizar essa parte de deserializar XSD para classe.

E também eu gostaria de conhecer a ferramenta que gerou essa deserialização, caso exista. É muito util.

**Comment by marcosgerene** [comment]
@renanmthy 
![image](https://user-images.githubusercontent.com/15945003/67119336-4fb6be00-f1bd-11e9-94e5-2cea2c610abe.png)

Na patinha =)

**Comment by valentimmx** [comment]
> @renanmthy
> ![image](https://user-images.githubusercontent.com/15945003/67119336-4fb6be00-f1bd-11e9-94e5-2cea2c610abe.png)
> 
> Na patinha =)

Obrigado Marcos! Vou criar manualmente aqui então.

Fica aqui este registro e confirmação de que temos falta de deserializadores eficientes no mercado.
Ou caso exista e queiram colaborar com a informação, envie um e-mail que acrescento aqui no ticket.

Abraços!
