### ISSUE TITLE
[Dúvida] - Campo descrição de produto - Excesso texto

### ISSUE THREAD

**Issue by CaioSantAnna** [ZeusAutomacao/DFe.NET#1066]
Estou tendo problemas com descrição de produto maior do que a largura definida para a coluna de descrição.

![image](https://user-images.githubusercontent.com/23192736/67242512-133cc980-f42c-11e9-9620-ada3f6347eb4.png)

Eu gostaria que o relatório tivesse o mesmo comportamento do campo dados adicionais que se adequa ao conteúdo e cresce em altura.

Eu cheguei a dar uma olhada na documentação do fastreport e a fazer diversos testes com propriedades mas não obtive sucesso.

Alguém sabe me informar onde preciso mexer para que caso a descrição do produto exceda a largura original, o relatório quebre de linha e o texto não seja cortado ?

Obrigado.

**Comment by marcosgerene** [comment]
@CaioSantAnna 

Tem uma propriedade (configuração) no Danfe chamada ```detalheVendaNormal```, que é um enum. Atribua o valor ```DuasLinhas```.

![image](https://user-images.githubusercontent.com/15945003/67248399-bd235280-f43a-11e9-8677-6e6199e29ac8.png)

A propriedade chama duas linhas, mas permite N linhas, basicamente ativa o ```CanGrow``` da linha no report.

**Comment by CaioSantAnna** [comment]
Obrigado pelo retorno.
