### ISSUE TITLE
DistribuicaoDFE

### ISSUE THREAD

**Issue by yelken** [ZeusAutomacao/DFe.NET#1067]
Pessoal, boa tarde.

A API DistribuicaoDFE já foi migrada para .NET CORE?

**Comment by danilobreda** [comment]
Olá @yelken, foi sim, foi implementado [aqui esta ele. ](https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Wsdl.Standard/DistribuicaoDFe/NfeDistDFeInteresse.cs) [Aqui o commit](https://github.com/ZeusAutomacao/DFe.NET/commit/6c19f3d56a3c13156561bee56624521bbb997859). Ainda não tive a necessidade e por isso não testei porem acredito que o @viniciusverasdossantos já tenha utilizado.

Qualquer feedback é muito importante pra gente!

**Comment by yelken** [comment]
Valeu @danilobreda!

Já irei utilizar e com certeza contribuir.
