### ISSUE TITLE
Unexpected character '$'

### ISSUE THREAD

**Issue by clebertorrent** [ZeusAutomacao/DFe.NET#107]
Está dando erro neste linha, o que faço ?

throw new Exception(
                    $"O serviço {servico} não pode ser criado no método {MethodBase.GetCurrentMethod().Name}!");

**Comment by rftd** [comment]
ou muda para o vs 2015 ou altera esta linha para 
string.format("O serviço {0} não pode ser criado no método {1}!", servico, MethodBase.GetCurrentMethod().Name);

**Comment by clebertorrent** [comment]
Beleza meu amigo, deu certo, obrigado.

Posso aproveitar este tópico e pedir um auxilio em como conseguir executar e emitir a nf de teste ?

**Comment by adeniltonbs** [comment]
Veja este guia:
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114
