### ISSUE TITLE
Instruções de implementação da DistribuicaoDFE

### ISSUE THREAD

**Issue by yelken** [ZeusAutomacao/DFe.NET#1072]
Pessoal, bom dia!

Estou implementando a DistribuicaoDFE mas não encontrei nenhum APP de teste ou que chame homologação, qual classe devo instanciar para o consumo dessa API?

Tem alguma boa prática que é seguida?

Obrigado pela ajuda

**Comment by robertorp** [comment]
Este aplicativo talvez ajude você meu amigo.
https://github.com/AOPack/DFe-App

Vou fechar a issue, mas se surgir alguma dúvida, abra outra issue ou simples reopen essa issue. Obrigado amigo!
