### ISSUE TITLE
NFCe - Marca d´água "Demo Version"

### ISSUE THREAD

**Issue by pbalbino** [ZeusAutomacao/DFe.NET#1074]
Estou utilizando o componente pra fazer a impressão do danfe NFCe e notamos que aparece uma marca d´água "Demo Version", gostaria de saber como posso fazer pra remover. Preciso adquirir alguma licença?

Olhando nesse site [https://www.fast-report.com/pt/buy/price_table/](https://www.fast-report.com/pt/buy/price_table/), qual dessas licenças devo adquirir?

**Comment by mvidaldev** [comment]
Não é o cristal reports?

________________________________
De: pbalbino <notifications@github.com>
Enviado: quarta-feira, 27 de novembro de 2019 09:49
Para: ZeusAutomacao/DFe.NET <DFe.NET@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ZeusAutomacao/DFe.NET] NFCe - Marca d´água "Demo Version" (#1074)


Estou utilizando o componente pra fazer a impressão do danfe NFCe e notamos que aparece uma marca d´água "Demo Version", gostaria de saber como posso fazer pra remover. Preciso adquirir alguma licença?

**Comment by pbalbino** [comment]
Pelo que li na documentação é o FastReport

**Comment by robertorp** [comment]
Depende da sua aplicação e de sua necessidade. 
FastReport você monta o que precisa somente. 

No meu caso era aplicação desktop olha oque selecionei 
Cliquei em comprar... 
1- .net Ms Visual Studio 
2- fastreport.net (existe o clube.. não sei o que é) 
3- vc precisa de report online? Não.. (meu caso..)
4- vc precisa de suporte pra .net core? não (meu caso) 
5- vc precisa de report para asp mvc ? Não (meu caso) 
6- selecione o tipo de licença no caso eu selecionei single 399 euros.. a ultima vez que comprei pagei 1799 em reais por isso

**Comment by pbalbino** [comment]
@robertorp obrigado pelas informações, vou verificar.
