### ISSUE TITLE
nfedistribuicaodfe “Erro de referência”

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1077]
Olá, não estou conseguindo fazer o download dos xml Nfe emitidas contra o CNPJ, apresenta erro de regência, estou usando o modelo de exemplos. Obrigado

**Comment by robertorp** [comment]
Poste mais detalhes por favor amigo , prints de como está sua configuração, os passos , o que você está preenchendo?

**Comment by sigridslima** [comment]
private void button4_Click(object sender, EventArgs e)
        {
            try
            {
                #region NFeDistribuicaoDFe

                if (txtCNPJ.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("O CNPJ deve ser informado!");
                }

                if (txtNSU.Text != "")
                {
                    //MessageBox.Show("Ultimo NSU Retornado");
                }
                else
                {
                    MessageBox.Show("NSU deve ser maior ou igual a 0");
                }
                if (txtChave.Text != "")
                {
                    //MessageBox.Show("Chave Eletrônica NFe");
                }
                else
                {
                    MessageBox.Show("Chave Eletrônica devem ser informados");
                }

                var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
                var retornoNFeDistDFe = servicoNFe.NfeDistDFeInteresse(_configuracoes.Emitente.enderEmit.UF.ToString(), txtCNPJ.Text, ultNSU: txtNSU.Text, chNFE: txtChave.Text);

                TrataRetorno(retornoNFeDistDFe);

                #endregion
            }
            catch (ComunicacaoException ex)
            {
                MessageBox.Show(ex.Message, "Erro Comunicacao");
            }
            catch (ValidacaoSchemaException ex)
            {
                MessageBox.Show(ex.Message, "Erro Schema");
            }
            catch (Exception ex)
            {
                if (!string.IsNullOrEmpty(ex.Message))
                    MessageBox.Show(ex.Message, "Erro Geral");
            }
        }

erro: Referencia de objeto nao definida para uma instancia de um objeto

**Comment by robertorp** [comment]
Os passos que vc utiliza são como? o que vc adiciona quando o aplicativo teste pede, preciso dos passos todos de todos valores que você digita de acordo com o que ele pede

**Comment by sigridslima** [comment]
Então primeiro faço a maifestação com ciencia da operação de recebido, ate ai tudo certo, recebo a vinculação do processo a nota, depois tento fazer a distribuição, o aplicativo teste solicita o cnpj do destinatario da nota, o NSU ultimo retorno e depois a chave de acesso. Ai nao faz comunicação com webservice e retorna o erro: Referencia de objeto nao definida para uma instancia de um objeto

**Comment by robertorp** [comment]
olha a linha que marquei pesquisando pelo ultimo NSU 

![image](https://user-images.githubusercontent.com/10251705/70527377-8d372800-1b2a-11ea-86e1-5ee3dd5e2752.png)

a outra linha pesquisando todas NF emitidas contra o cnpj 

![image](https://user-images.githubusercontent.com/10251705/70527441-b48df500-1b2a-11ea-9923-03fe9608402d.png)

Esse código é o que uso no sistema, tente simular isso no appteste

**Comment by danilobreda** [comment]
@sigridslima você utiliza .net framework ou .net core?

**Comment by sigridslima** [comment]
Uso net framework

**Comment by sigridslima** [comment]
> olha a linha que marquei pesquisando pelo ultimo NSU
> 
> ![image](https://user-images.githubusercontent.com/10251705/70527377-8d372800-1b2a-11ea-86e1-5ee3dd5e2752.png)
> 
> a outra linha pesquisando todas NF emitidas contra o cnpj
> 
> ![image](https://user-images.githubusercontent.com/10251705/70527441-b48df500-1b2a-11ea-9923-03fe9608402d.png)
> 
> Esse código é o que uso no sistema, tente simular isso no appteste

roberrp, nao conseguir implementar algumas rotinas como: BuscarUltimaDistribuicaoDfe , EmissorFiscalNFE emissorNfe.
Aguardo

**Comment by sigridslima** [comment]
Encontrei um exemplo mais tbm nao obtive sucesso

Erro: System.ArgumentException: 'X509FindType, 'FindBySubjectName', requer o tipo que o tipo do argumento findvalue seja 'System.String'. O tipo do argumento findValue é 'System.Security.Cryptography.X509Certificates.X509Certificate2'.'

Meu Certificado e A1.
As referencia web service
Namespace NfeRecepcao: https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx
Namespace Distribuicao: https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx


Codigo:

appConfig:

 <system.serviceModel>
        <bindings>
            <basicHttpBinding>
                <binding name="RecepcaoEventoSoap">
                  <security mode="Transport">
                    <transport clientCredentialType="Certificate" proxyCredentialType="None" realm=""/>
                    <message clientCredentialType="Certificate" algorithmSuite="Default"/>
                  </security>
                </binding>
                <binding name="RecepcaoEventoSoap1" />
              
                <binding name="NFeDistribuicaoDFeSoap">
                  <security mode="Transport">
                    <transport clientCredentialType="Certificate" proxyCredentialType="None" realm=""/>
                    <message clientCredentialType="Certificate" algorithmSuite="Default"/>
                  </security>
                </binding>
                <binding name="NFeDistribuicaoDFeSoap1" />
            </basicHttpBinding>
        </bindings>
        <client>
            <endpoint address="https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx"
                binding="basicHttpBinding" bindingConfiguration="RecepcaoEventoSoap"
                contract="NfeRecepcao.RecepcaoEventoSoap" name="RecepcaoEventoSoap" />
            <endpoint address="https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx"
                binding="basicHttpBinding" bindingConfiguration="NFeDistribuicaoDFeSoap"
                contract="Distribuicao.NFeDistribuicaoDFeSoap" name="NFeDistribuicaoDFeSoap" />
        </client>
    </system.serviceModel>

Form:

private void BaixarXml(XmlDocument xml)
        {
            String caminho = "C:/Teste/nome_certificado.pfx";
            String senha = "1234";
            X509Certificate2 certificado = new X509Certificate2(caminho, senha);

            var NFe_Sc = new Distribuicao.NFeDistribuicaoDFeSoapClient();

//minha duvida e aqui
            NFe_Sc.ClientCredentials.ClientCertificate.SetCertificate(StoreLocation.CurrentUser, StoreName.My, X509FindType.FindBySubjectName, certificado);
//minha duvida e aqui

            XElement x = XElement.Parse(xml.InnerXml);

            var arquivo = NFe_Sc.nfeDistDFeInteresse(x).ToString();

            var xmlNota = ConverterStringToXml(arquivo);
            var conteuZip = xmlNota.GetElementsByTagName("docZip")[0].InnerText;

            byte[] dados = Convert.FromBase64String(conteuZip);
            //TODO: fazer uso dos dados da variável retorno
            var xmlRetorno = descompactar(dados);
        }

private void button4_Click(object sender, EventArgs e)
        {
            //Download da NFe, Para Download da xml por chave é necessario que a versão seja 1.01
            var texto = @"<distDFeInt xmlns=""http://www.portalfiscal.inf.br/nfe"" versao = ""1.01"">
    <tpAmb>1</tpAmb>
    <cUFAutor>29</cUFAutor>
    <CNPJ>MEU CNPJ</CNPJ>
    <consChNFe>
        <chNFe>CHAVE ACESSO</chNFe>
    </consChNFe>
    </distDFeInt>";

            var xml = ConverterStringToXml(texto);
            BaixarXml(xml);
        }

**Comment by sigridslima** [comment]
`private void button4_Click(object sender, EventArgs e)
        {
            //Download da NFe, Para Download da xml por chave é necessario que a versão seja 1.01
            var texto = @"<distDFeInt xmlns=""http://www.portalfiscal.inf.br/nfe"" versao = ""1.01"">
    <tpAmb>1</tpAmb>
    <cUFAutor>29</cUFAutor>
    <CNPJ>MEU CNPJ</CNPJ>
    <consChNFe>
        <chNFe>CHAVE ACESSO</chNFe>
    </consChNFe>
    </distDFeInt>";

            var xml = ConverterStringToXml(texto);
            BaixarXml(xml);
        }`

**Comment by sigridslima** [comment]
Encontrei um exemplo mais tbm nao obtive sucesso

Erro: System.ArgumentException: 'X509FindType, 'FindBySubjectName', requer o tipo que o tipo do argumento findvalue seja 'System.String'. O tipo do argumento findValue é 'System.Security.Cryptography.X509Certificates.X509Certificate2'.'

Meu Certificado e A1.
As referencia web service
Namespace NfeRecepcao: https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx
Namespace Distribuicao: https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

Codigo:

Form:

private void BaixarXml(XmlDocument xml)
        {
            String caminho = "C:/Teste/nome_certificado.pfx";
            String senha = "1234";
            X509Certificate2 certificado = new X509Certificate2(caminho, senha);

            var NFe_Sc = new Distribuicao.NFeDistribuicaoDFeSoapClient();

//minha duvida e aqui
            NFe_Sc.ClientCredentials.ClientCertificate.SetCertificate(StoreLocation.CurrentUser, StoreName.My, X509FindType.FindBySubjectName, certificado);
//minha duvida e aqui

            XElement x = XElement.Parse(xml.InnerXml);

            var arquivo = NFe_Sc.nfeDistDFeInteresse(x).ToString();

            var xmlNota = ConverterStringToXml(arquivo);
            var conteuZip = xmlNota.GetElementsByTagName("docZip")[0].InnerText;

            byte[] dados = Convert.FromBase64String(conteuZip);
            //TODO: fazer uso dos dados da variável retorno
            var xmlRetorno = descompactar(dados);
        }

private void button4_Click(object sender, EventArgs e)
        {
            //Download da NFe, Para Download da xml por chave é necessario que a versão seja 1.01
            var texto = @"<distDFeInt xmlns=""http://www.portalfiscal.inf.br/nfe"" versao = ""1.01"">
////    <tpAmb>1</tpAmb>
 //   <cUFAutor>29</cUFAutor>
   // <CNPJ>MEU CNPJ</CNPJ>
   // <consChNFe>
      //  <chNFe>CHAVE ACESSO</chNFe>
    //</consChNFe>
    //</distDFeInt>";

            var xml = ConverterStringToXml(texto);
            BaixarXml(xml);
        }

**Comment by sigridslima** [comment]
Encontrei um exemplo mais tbm nao obtive sucesso

Erro: System.ArgumentException: 'X509FindType, 'FindBySubjectName', requer o tipo que o tipo do argumento findvalue seja 'System.String'. O tipo do argumento findValue é 'System.Security.Cryptography.X509Certificates.X509Certificate2'.'

Meu Certificado e A1.
As referencia web service
Namespace NfeRecepcao: https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx
Namespace Distribuicao: https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

Form:

private void BaixarXml(XmlDocument xml)
        {
            String caminho = "C:/Teste/nome_certificado.pfx";
            String senha = "1234";
            X509Certificate2 certificado = new X509Certificate2(caminho, senha);

            var NFe_Sc = new Distribuicao.NFeDistribuicaoDFeSoapClient();

//minha duvida e aqui
            NFe_Sc.ClientCredentials.ClientCertificate.SetCertificate(StoreLocation.CurrentUser, StoreName.My, X509FindType.FindBySubjectName, certificado);
//minha duvida e aqui

            XElement x = XElement.Parse(xml.InnerXml);

            var arquivo = NFe_Sc.nfeDistDFeInteresse(x).ToString();

            var xmlNota = ConverterStringToXml(arquivo);
            var conteuZip = xmlNota.GetElementsByTagName("docZip")[0].InnerText;

            byte[] dados = Convert.FromBase64String(conteuZip);
            //TODO: fazer uso dos dados da variável retorno
            var xmlRetorno = descompactar(dados);
        }
![PRINT](https://user-images.githubusercontent.com/21263061/70677947-60405d80-1c6f-11ea-83f6-f6557a9fd08f.jpg)
