### ISSUE TITLE
resNFe retornando da consulta do manifesto com atributo "versao" com valor "4.00"

### ISSUE THREAD

**Issue by VGsss** [ZeusAutomacao/DFe.NET#1079]
Bom dia/tarde/noite, estou enfrentando um problema onde, ao fazer a consulta do manifesto através do ServicoNFe.NFeDistribuicaoDFe em ambiente de Homologação,
a schema de retorno dos XMLs do tipo resNFe está vindo como "resNFe_v4.00.xsd". 

O schema válido mais atual para resNFe que encontrei é a versão 1.01.

Exemplo de retorno no XML:
`<docZip schema="resNFe_v4.00.xsd"></docZip>`

Esse retorno é previsto ou estou dando alguma bobeira na leitura dos XMLs da SEFAZ?

PS: Isso começou recentemente.

**Comment by robertorp** [comment]
Olá , bom dia, ainda persiste o problema?
