### ISSUE TITLE
Url qrCode Goiás

### ISSUE THREAD

**Issue by rodrigomartins50** [ZeusAutomacao/DFe.NET#108]
Bom dia @adeniltonbs, qual seria a url para informar no qrCode em Goiás?

**Comment by adeniltonbs** [comment]
Boa tarde Rodrigo, se você conseguir essa informação, compartilhe comigo pra que eu possa colocar na biblioteca rsrs. A SEFAZ de GO não disponibilizou essa informação em seu portal http://www.nfe.go.gov.br/, sugiro que entre em contato com essa SEFAZ.

**Comment by rodrigomartins50** [comment]
Consegui essa informação com eles sim @adeniltonbs, vlw

Segue e-mail de resposta deles:

Boa tarde,

A aplicação de consulta via QR Code ainda está em desenvolvimento, mas as URLs serão essas:

Produção: http://nfe.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf

Homologação: http://homolog.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf​​

O CSC deve ser gerado através de webservice. Segue abaixo as URLs do serviço para geração, consulta e revogação do CSC:

Homologação: https://homolog.sefaz.go.gov.br/nfe/services/v2/CscNFCe?wsdl

Produção: https://nfe.sefaz.go.gov.br/nfe/services/v2/CscNFCe?wsdl​
​
Att.

Marcelo Dias da Silva
Gestor de Tecnologia da Informação
Projeto Nota Fiscal Eletrônica
Secretaria da Fazenda do Estado de Goiás

**Comment by adeniltonbs** [comment]
Adicionados na biblioteca, conforme commit f8be35499eba42467e076505c05457a17cfff3cb. Obr por compartilhar a informação.

**Comment by robertorp** [comment]
Sou de goiás também, tenho ate um projeto exemplo de consulta já pronto do CSC e fazer CSC

Link: https://www.dropbox.com/sh/d5ayg1yn0q6x1dv/AAAZeyJRQjZrKYe7EMjIv67ta?dl=0

Obs: em goiás nfc-e já está em produção "assistida" 
obs2: aqui já emitidos nf-e com o Zeus em produção em uma aplicação c# , WPF , vou começar a desenvolver esta semana ainda a nfc-e com android(java) e wpf(c#), então talvez possamos trocar alguma experiência rodrigo ! se quiser.. e so add, robertoalves18@hotmail.com ou robertoalvespereira18@gmail.com

**Comment by rodrigomartins50** [comment]
Bom dia @robertorp, vlw por compartilhar seu projeto de consulta do CSC, vamos conversando sim, tbm já tenho um projeto em produção utilizano Zeus para emissão de NF-e, agora já vou deixar ele preparado para emissão de NFC-e,vlw.

**Comment by adeniltonbs** [comment]
@robertorp Se desejar compartilhar com a comunidade, pode adicionar no projeto e fazer um pull request. Certifique-se de documentar bem o código, as propriedades e métodos.
