### ISSUE TITLE
NfeDistDFeInteresse sempre retorna nota resumida mesmo após ser feito Manifesto por Ciência da Operação

### ISSUE THREAD

**Issue by giogama** [ZeusAutomacao/DFe.NET#1080]
Pessoal,

Tenho uma aplicação que consulta por NSU, até ai tudo bem.
Todas as Notas Resumidas eu vou realizando o Manifesto por Ciência da Operação, chave por chave, e sempre no Lote 1 e Evento 1. Verifico o Status de cada Manifesto e esta tudo correto - 128.

Ai o último passo é consultar, por chave, um a um e neste momento não retorna nenhum documento, código Status = 137. Quando eu consulto por NSU (eu armazeno o NSU e a chave de cada nota consulta no primeiro passo), retorna só o Resumo da Nota.

Como faço para baixar a Nota Completa após o Manifesto?

**Comment by robertorp** [comment]
Já corrigiu o problema? Aparentemente parece ser um problema da sefaz.

**Comment by giogama** [comment]
Acredito ser problema da SEFAZ mesmo, algumas vezes após ser feito o Manifesto por Ciência da Operação, demora a disponibilizar o XML completo.
