### ISSUE TITLE
BarcodeChave Error CS0103 O nome 'cteProc' não existe no contexto atual

### ISSUE THREAD

**Issue by giogama** [ZeusAutomacao/DFe.NET#1081]
Ao gerar um PDF da Dacte apresenta a seguinte mensagem.

cteProc procCte = new cteProc().CarregarDeXmlString(sXML);

                                var dacte = new DacteFrCte(procCte, new ConfiguracaoDacte()
                                {
                                    Logomarca = null,                                    
                                    DocumentoCancelado = false,
                                    QuebrarLinhasObservacao = false,
                                    Desenvolvedor = "Enerwatt - Engenharia",
                                },                                    
                                    arquivoRelatorio: string.Empty);

                                dacte.ExportarPdf(Path.Combine(sPath, sArquivo));

{"(BarcodeChave): Error CS0103: O nome 'cteProc' não existe no contexto atual\r\n(Text60): Error CS1061: 'System.DateTime' não contém uma definição para 'DateTime' e nenhum método de extensão 'DateTime' aceita que um primeiro argumento de tipo 'System.DateTime' seja encontrado (você não está usando uma diretriz ou referência de assembly?)\r\n(86,22): Error CS0246: O nome de namespace ou o tipo 'infCTeSupl' não pôde ser encontrado. Precisa de uma diretiva using ou de uma referência de assembly?\r\n"}

**Comment by robertorp** [comment]
posta o xml que vc esta tentando carregar ele

**Comment by giogama** [comment]
Eu encontrei o problema. O arquivo template do Relatório (CTeRetrato.frx) estava referenciando uma versão inferior do Assembly CTe.Classes. Ajustado isso, funcionou perfeitamente.
