### ISSUE TITLE
Danfe NFCe 58mm

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#1084]
Olá, alguém já implementou a Danfe Nativa para impressoras 58mm ?

**Comment by robertorp** [comment]
Ainda não temos em 58mm amigo.

**Comment by marcosmarchiore** [comment]
Alguém se interessa em gerar posso ajudar financeiramente ao desenvolvedor.

**Comment by marcosgerene** [comment]
https://github.com/marcosgerene/Gerene.DFe.EscPos
