### ISSUE TITLE
NFe - Danfe Cabeçalho com nome fantasia + razão social

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1087]
Alguns clientes estão pedindo que no cabeçalho da DANFE deveria sair o "Nome Fantasia" destacado, e a "Razão Social" menor em baixo.
Vocês já tiveram algum caso assim? 
Como poderia ser resolvido?
Fico no aguardo.

**Comment by marcosgerene** [comment]
@danilobreda 

Alguns clientes meus pedem ajustes pontuais, então edito o frx de forma "exclusiva" para eles e carrego o frx em tempo de execução ao invés de pegar o padrão.

**Comment by danilobreda** [comment]
@marcosgerene obrigado pela ideia, vou fazer dessa maneira nesse momento.
