### ISSUE TITLE
App Teste - DANFE NFCe Normal

### ISSUE THREAD

**Issue by LeonardoMoraes1989** [ZeusAutomacao/DFe.NET#109]
Olá amigos, boa noite,

Após configurar a aplicação de teste, gostaria de saber os passos que preciso realizar para:

1 - Conseguir emitir NFC-e (normal)
2 - Emitir NFe e visualizar o DANFE gerado.

Atualmente, eu clico no botão "Criar e Salvar XML 3.0", salvo o xml numa pasta e em seguida, clico no botão botão "DANFE NFCe Normal", só que é apresentado a mensagem de erro em anexo.
Quando eu clico em "DANFE NFCe Contigência", consigo verificar normalmente o NFCe.

Agradeço a ajuda de todos.
Muito obrigado antecipadamente,
Leo
![nfeproc](https://cloud.githubusercontent.com/assets/16878925/13732771/43119bcc-e968-11e5-9c65-dcf3c08f8f7f.png)

**Comment by adeniltonbs** [comment]
1 - Para emitir uma NFCe: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/106
2 - Aqui te passo uma atividade, procure no "Manual de orientação do contribuinte", disponível em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=, o que é o objeto "nfeProc" (página 181 do manual) e o objeto "protNFe" (página 36 do manual).

Desculpa a chatice aqui, mas vou repetir, se quiseres trabalhar com NFe/NFCe, vais ter que se familiarizar com o projeto por estudar o "Manual de orientação do contribuinte" ou qualquer outra documentação que o explique.

**Comment by adeniltonbs** [comment]
Veja este guia:
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114
