### ISSUE TITLE
A conexão subjacente estava fechada: Erro inesperado em um envio CTe

### ISSUE THREAD

**Issue by leandrovm76** [ZeusAutomacao/DFe.NET#1090]
Olá pessoal

Alguém conseguiu sanar de vez este problema, se sim qual foi a solução. Por gentileza

**Comment by robertorp** [comment]
Certificado Digital, algo na Sefaz, Algo local no computador (cadeia de certificado, ou até mesmo se for windows 7 se não me engano tem que instalar uns kb) 

Comece tentando acessar o E-CAC pra ver se consegue acessar normalmente

**Comment by leandrovm76** [comment]
Olá obrigado pelo retorno.
Já efetuamos este procedimento porém permanece o erro.

**Comment by marcosgerene** [comment]
Duplicou em outra issue, então fechei esta, vou tentar ajudar o amigo na issue nova.
