### ISSUE TITLE
A conexão subjacente estava fechada

### ISSUE THREAD

**Issue by leandrovm76** [ZeusAutomacao/DFe.NET#1092]
Estamos com este problema, alguém tem uma luz por favor ....

**Comment by marcosgerene** [comment]
@leandrovm76 

Existe MUITA documentação desse problema, como pode ver abaixo:
https://github.com/ZeusAutomacao/DFe.NET/issues/219
https://github.com/ZeusAutomacao/DFe.NET/issues/1090
https://github.com/ZeusAutomacao/DFe.NET/issues/879
https://github.com/ZeusAutomacao/DFe.NET/issues/822
https://github.com/ZeusAutomacao/DFe.NET/issues/706
https://github.com/ZeusAutomacao/DFe.NET/issues/629
https://github.com/ZeusAutomacao/DFe.NET/issues/338

Então preciso que você seja mais específico para te ajudar respondendo algumas perguntas:

1. Qual tipo de certificado você usa A1 ou A3?
2. Qual sistema operacional você usa? Você rodou TODOS os updates do SO?
3. Este erro ocorre o tempo todo ou funciona uma vez e depois começa a dar erro?
4. Você usa nuget ou compila as dlls? Se usa nuget, qual a versão?

**Comment by leandrovm76** [comment]
Olá, Marcos
Obrigado pela ajuda.
Certificado seria A1 e os sistema que utilizamos é em nuvem desenvolvido em .NET e API.

**Comment by marcosgerene** [comment]
@leandrovm76 

>Certificado seria A1 

Ok, certicado A1 já é um bom começo, elimina alguns problemas velhos conhecidos da comunidade.

> os sistema que utilizamos é em nuvem

Windows Server? Distro Linux? você tem controle do servidor (sistema operacional) ou usa hospedagem compartilhada? Conseguiria rodar updates nesse servidor? consegue executar um demo lá para testar a comunicação?

>  desenvolvido em .NET e API.

.Net Full? Core?


Por favor, seja BEM mais especifico nas respostas, respostas vazias geram mais perguntas.

**Comment by danilobreda** [comment]
@leandrovm76 setando o canal de comunicação para TLS na mão igual é demonstrado nos links das Issues acima, resolveu? se for Linux o ambiente, já pode ser alguns problemas diferentes.

Explica pra gente também se é um sistema que já estava em funcionamento a um tempo e começou a dar erro ou não... você não esta explicando legal para a gente o problema.

Outra pergunta que me veio, você é desenvolvedor ou apenas utiliza o sistema?

**Comment by WashingtonAutocom** [comment]
Olá.
Só para deixar um feedback de como o meu caso foi resolvido, perdão caso não esteja no padrão de vocês ou se tenha errado em algo, só informar que eu faço a correção.
Eu estava com o mesmo erro no MDFe.AppTeste para o servidor de homologação, no de produção estava funcionando perfeitamente, a minha maquina de desenvolvimento é Windwos 10 atualizado, com .Net Framework 4.8 instalado assim com o SDK, O certificado utilizado é uma A1 valido.

Pelo que olhei para .Net Framework abaixo de 4.6 o protocolo utilizado por padrão é o SSL ou TLS1.0, porem conforme aviso no portal do DFe [LINK](https://dfe-portal.svrs.rs.gov.br/Mdfe/Avisos), a Sefaz desativou para o servidor de homologação o suporte aos protocolos antigos SSL, TLS1.0 e TLS1.1 ficando somente o TLS1.2 ativo, nesse caso como o DFe.NET é compilado usando o .Net 4.5 em produção funciona mais em homologação não.

Para resolver, pode ser forçado a utilização do protocolo com o código **"System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;"**, embora não seja uma boa pratica na utilização do protocolo com .Net  de acordo com o relato aqui [LINK](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), o indicado é deixar o sistema operacional decidir qual protocolo usar, para isso bastaria adicionar no registro do windows os valores nas chaves abaixo.

Chave: [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
Valor: "SystemDefaultTlsVersions"=dword:00000001
Valor: "SchUseStrongCrypto"=dword:00000001
Chave: [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
Valor: "SystemDefaultTlsVersions"=dword:00000001
Valor: "SchUseStrongCrypto"=dword:00000001
Exemplo:
![Exemplo Registro Windows](https://user-images.githubusercontent.com/65791820/85933006-6cf16f80-b8a8-11ea-8b64-398c8640b144.jpg)

Em anexo deixo o arquivo .reg para adicionas as chaves automaticamente. Em fim realizar esses procedimentos para resolver ou compilar o DFe.NET no framework 4.6 ou superior.
[ModificacaoRegistro ErroTLS1.2.zip](https://github.com/ZeusAutomacao/DFe.NET/files/4841308/ModificacaoRegistro.ErroTLS1.2.zip)

Espero ajudar alguém no futuro eu realizei os testes nas duas resoluções e para mim funcionaram perfeitamente.

**Comment by WashingtonAutocom** [comment]
Ainda sobre o post anterior eu esqueci de colocar a verificação que eu fiz no servidor da Sefaz para saber realmente qual protocolo estava funcionando no servidor da Sefaz, com isso deu pra confirmar porque em produção funcionava e em homologação não, vale ressaltar que os protocolos antigos em produção até estão marcados como obsoletos, ou seja serão mesmo desativados em breve, o que confirma os avisos da Sefaz. o site que usei foi o [TLS Scanner da GeekFlare](https://gf.dev/tls-scanner)

Verificação no servidor em Produção
Para consultar o resultado completo: [https://gf.dev/tests/6c1anqaj58a](https://gf.dev/tests/6c1anqaj58a)
![ConsultaServidorProducao](https://user-images.githubusercontent.com/65791820/86007403-b7303900-b9ed-11ea-9d29-e0d24d6c11d4.jpg)



Verificação no servidor em Homologação
Para consultar o resultado completo: [https://gf.dev/tests/h01n1021fel](https://gf.dev/tests/h01n1021fel)
![ConsultaServidorHomologacao](https://user-images.githubusercontent.com/65791820/86007422-be574700-b9ed-11ea-9cfc-0f919ef300e2.jpg)


Link útil.
[10 Online Tool to Test SSL, TLS and Latest Vulnerability](https://geekflare.com/ssl-test-certificate/)
