### ISSUE TITLE
Resumão MDF-e - Nota Técnica 2020.001 - MDF-e Integrado (v 1.03)

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#1093]
Nota Técnica no final da página -> https://dfe-portal.svrs.rs.gov.br/Mdfe/Documentos#  

**Data Homologação: 09/03/2020
Data Produção: 06/04/2020**

**MDF-e Integrado** 

**Alterações de Schema Geral do MDF-e**
![image](https://user-images.githubusercontent.com/10251705/75608743-31ed5400-5ae1-11ea-851b-eb6d0c397bd4.png)

Antes tinha apenas a descrição do produto predominante, hoje teremos o grupo predominante
![image](https://user-images.githubusercontent.com/10251705/75608764-52b5a980-5ae1-11ea-8284-f313f6c9ad89.png)
![image](https://user-images.githubusercontent.com/10251705/75608784-71b43b80-5ae1-11ea-9fbb-f0eb936ff781.png)
![image](https://user-images.githubusercontent.com/10251705/75608796-8db7dd00-5ae1-11ea-9e24-59ec221deaa0.png)

**Alterações de Schema do Modal Rodoviário**
![image](https://user-images.githubusercontent.com/10251705/75608810-a45e3400-5ae1-11ea-83e8-6ea317eb3563.png)
![image](https://user-images.githubusercontent.com/10251705/75608825-c3f55c80-5ae1-11ea-9c72-bedf00cf30c9.png)
![image](https://user-images.githubusercontent.com/10251705/75608830-cbb50100-5ae1-11ea-80a9-f91c4f9f7bfb.png)
![image](https://user-images.githubusercontent.com/10251705/75608833-d7a0c300-5ae1-11ea-96fc-9155b8e50e17.png)

Implementação em breve!

**Comment by marcosgerene** [comment]
@robertorp 
Latitude e longitude então é somente para lotação?

**Comment by marcosgerene** [comment]
https://www.projetoacbr.com.br/forum/topic/55702-nota-técnica-2020001-mdf-e/


![image](https://user-images.githubusercontent.com/15945003/75609448-59471f80-5ae7-11ea-9824-862de79f3d0a.png)


https://www.projetoacbr.com.br/forum/topic/56540-dúvida-ciot-e-nt202001/

Geração do CIOT pela e-Frete (unico que disponibiliza WS também no modo gratuíto)

https://github.com/marcosgerene/CiotEFrete

**Comment by rodolfo4cs** [comment]
Prorrogado para 06/06/2020 devido a pandemia do COVID-19

[Adiamento Regras de Validação da NT do MDF-e Integrado - COVID-19](https://dfe-portal.svrs.rs.gov.br/Mdfe/Avisos/1075)

somente regras opcionais terão seu prazo original mantido!

**Comment by robertorp** [comment]
Foi prorrogado novamente, para 06/09/2020, as validações somente. 

![image](https://user-images.githubusercontent.com/10251705/85857810-eeee7500-b790-11ea-9c09-9c885b28835f.png)

fonte: https://dfe-portal.svrs.rs.gov.br/Mdfe/Avisos
