### ISSUE TITLE
Consulta CCC

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#1096]
Olá amigos.

A SVRS disponibiliza uma consulta centralizada de contribuintes, gostaria de saber se vocês conhecem ou já fizeram essa consulta via webservice, procurei a url para montar o webservice mais não encontrei.

[https://dfe-portal.svrs.rs.gov.br/NFE/CCC](https://dfe-portal.svrs.rs.gov.br/NFE/CCC)

**Comment by robertorp** [comment]
Se tiver um webserive centralizado que retorne até a IE passa para nós, que nós iremos implementar com o maior prazer possível. 

enquanto isso, hoje no meu sistema uso esse aqui: https://receitaws.com.br/ , observação, ele não retorna IE

**Comment by leandrossantos** [comment]
Obrigado @robertorp assim que eu conseguir a url do webervice da Consulta CCC eu passo sim, passei para um amigo meu esse outro https://www.sintegraws.com.br/ que você compra pacote de consultas e tem consulta por IE
