### ISSUE TITLE
Schemas

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#11]
Adenilton,

Quais schemas que devo especificar na aba Geral, diretório de schemas, do aplicativo de testes? Existe algum lugar na internet em que possa baixá-los?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
Você pode baixar os schemas mais recentes diretamente no site da Nfe em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=. Neste caso você deve baixar os arquivos compactados mais recentes para cada serviço que você deseja utilizar, e, em seguida descompactá-los todos em um único diretório. É este diretório que deve ser informado na aba geral.

**Comment by robertocvsiqueira** [comment]
Obrigado, Adenilton! Já baixei e estou usando.
