### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by ciceroaferreira** [ZeusAutomacao/DFe.NET#110]
Estou tentando montar a lista de produtos, mas o relatório está trazendo somente o ultimo produto da lista. Como faço para popular a área de produtos  com mais de um produto?

**Comment by adeniltonbs** [comment]
Cícero, poderia nos fornecer mais detalhes sobre o problema? Vc está usando a aplicação de testes para imprimir um DANFE a partir do XML é isso?
