### ISSUE TITLE
Como usar a Classe "ProdutoEspecifico"?

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1101]
Bom dia pessoal como consigo carregar um produto especifico do xml para classe com o zeus?

**Comment by denernun** [comment]
Bom dia, vc tem que carregar todo o xml pra classe e navegar nos produtos, não dá pra carregar um produto especifico. Creio eu.

**Comment by ThalisonSantos** [comment]
@denernun eu falo da classe ProdutoEspecifico que pode ser armas, veiculos , medicamentos e etc

**Comment by ThalisonSantos** [comment]
alguém tem alguma luz?
