### ISSUE TITLE
Campo CMT na classe veicProd com tipo incorreto

### ISSUE THREAD

**Issue by mvtaraujo** [ZeusAutomacao/DFe.NET#1102]
O campo CMT da classe veicProd está como decimal, porém ele deve ser do tipo string de acordo com o manual e schema.

A descrição dele confunde um pouco. (CMT-Capacidade Máxima de Tração - em Toneladas 4 casas decimais)

**Comment by danilobreda** [comment]
Apenas para referencia:
![image](https://user-images.githubusercontent.com/14843499/80098721-be494f80-8543-11ea-9356-fb7ac08bcb43.png)
De acordo com o manual Manual_de_Orientacao_Contribuinte_v_6.00.pdf

**Comment by marcosgerene** [comment]
Acabei de receber uma nota de um fornecedor com o CMT separado por virgula, o campo é string, foi mal formatado, não deveria ser, mas é.

**Comment by marcosgerene** [comment]
Vou abrir PR.
