### ISSUE TITLE
Duvida com a Tag da NFe ProdutosEspecificos

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1106]
como faço pra ler um produtos com varios registros de produtoEspecifico?

`
-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>

-<arma>

<tpArma>0</tpArma>

<nSerie>ABC123456</nSerie>

<nCano>ABC123456</nCano>

<descr>PISTOLA G2C APARELHO PONTARIA 9MM TAURUS RAIADA DIREITA SEMI-AUTOMATICA PISTOL GRIP</descr>

</arma>`

**Comment by marcosgerene** [comment]
@ThalisonSantos 
Posta o xml se possível

**Comment by ThalisonSantos** [comment]
@marcosgerene 
[35200461482725000743550010007336431637973733.zip](https://github.com/ZeusAutomacao/DFe.NET/files/4528741/35200461482725000743550010007336431637973733.zip)

**Comment by marcosgerene** [comment]
@ThalisonSantos 
Eu reportei isso aqui https://github.com/ZeusAutomacao/DFe.NET/issues/356

Acho que o problema que reportei na época é o mesmo, basicamente a biblioteca está implementada de forma incorreta para medicamentos e armamento.

![image](https://user-images.githubusercontent.com/15945003/80320740-9af5fd00-87ee-11ea-9179-c2e316954e3b.png)

Vou linkar o @robertorp e o @adeniltonbs  aqui, para que também vejam, mas se trata de um bug.

**Comment by robertorp** [comment]
é verdade, vou dar uma olhada hoje.

**Comment by robertorp** [comment]
Irei olhar se esse bug permanece ainda. Creio eu que sim.
