### ISSUE TITLE
Erro: Não foi possível criar um canal seguro para SSL/TLS Certificado A1/A3

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#1110]
Ola estou com o erro de Não foi possível criar um canal seguro para SSL/TLS
Com certificado a1 e a3 em sp. 
Windows 10 atualizado 1909 e 64bits
Já não sei o que faço.

**Comment by marcosgerene** [comment]
@fabiociaf 

Vamos do básico, testou o(s) mesmo(s) certificado(s) com a mesma aplicação em outro ambiente (pc/OS)?
Se a resposta for sim e deu certo, provavelmente não é sua aplicação e nem o certificado, então sobra o ambiente.

Algumas considerações sobre o ambiente:

1 - Nas configurações avançadas do IE se o TLS 1.2 está habilitado?
2 - Existe algum firewall além do firewall do windows? Tentou desativar?
3 - Tentou desativar o anti-virus?

**Comment by ghost** [comment]
1- nas configuração esta 1.2 e desativei os anteriores e o 1.3 experimental.
2 - somente o windows. Não tentei desativar.
3- Esta sem antivírus apenas o defender.

**Comment by robertorp** [comment]
Certificado data de validade?
Cadeias de Certificado Digital (No Zeus tem uma propriedade que ignora isso) 

Já conseguiu resolver? Se Sim poste a solução se quiser é claro.

**Comment by fabiohcnobre** [comment]
Certificado data deCertificado data de validade? validade?
Está valido. No teste do A1 valido ate o final do ano, no teste do A3 validade para 2022.
Cadeias de Certificado Digital (No Zeus tem uma propriedade que ignora isso)
Esse campo? Esta como false.
ValidarCertificadoDoServidor>false</ValidarCertificadoDoServidor

Ainda sigo na procura de uma solução para isso.

**Comment by marcosgerene** [comment]
@fabiociaf 

O seu erro ocorre sempre igual o amigo acima (que não consegue emitir) ou ocorre a partir da segunda NFe/requisição?

Se for a partir da segunda requisição olhe: https://github.com/ZeusAutomacao/DFe.NET/issues/822

Se for a partir da primeira, ai a conversa é outra.

**Comment by fabiohcnobre** [comment]
@marcosgerene 
Fabiociaf (perfilempresa) = fabiohcnobre (perfilparticular)
Ocorre igual a parti da primeira.

**Comment by marcosgerene** [comment]
@fabiociaf @fabiohcnobre 

Então vamos ao cenário.
   - O erro ocorre a todo momento, não é intermitente, logo podemos descartar #822 
   - O certificado está válido e o erro ocorre em A1 e A3, vamos descartar o certificado;
   - Sua aplicação e o certificado do teste funcionam em outros PCs? Se sim, vamos descartar aplicação.

Nesse cenário eu falaria "formata o PC", mas faltou uma questão. No PC em questão, se você baixar um emissor de NFe gratuíto (tem que ser desktop) a emissão é feita com sucesso ou o problema persiste. (Existe emissor de monte gratuíto na internet)

Faça o teste, baixe um emissor gratuíto, instale e tente consumir o webservice com o(s) certificado(s) previamente testados.

Se tiver sucesso, ai infelizmente não consigo te ajudar (não pelo menos via issue), se o erro persistir, é o PC.

**Comment by fabiohcnobre** [comment]
Creio que algo com PC e o .NET ou algo do gênero.
Porque eu usei o app teste do Zeus e não funcionou. 
Outro emissor funcionou normalmente. 
Vou esperar lançar mais algumas atualizações de correções do windows e testar novamente.

**Comment by marcosgerene** [comment]
>Creio que algo com PC e o .NET ou algo do gênero.
Porque eu usei o app teste do Zeus e não funcionou.
Outro emissor funcionou normalmente.
Vou esperar lançar mais algumas atualizações de correções do windows e testar novamente.

Qual emissor usou para teste?

**Comment by fabiohcnobre** [comment]
Temos uma parceria com uma software house.

**Comment by marcosgerene** [comment]
@fabiohcnobre 

A questão é qual linguagem/plataforma do app que testou e teve sucesso

**Comment by fabiohcnobre** [comment]
Delphi

**Comment by marcosgerene** [comment]
Talvez o @rftd saiba te dar alguma informação mais útil, mas não sei a disponibilidade dele

**Comment by danilobreda** [comment]
@fabiohcnobre @fabiociaf voce estava usando .net core? ou .net framework?

**Comment by fabiohcnobre** [comment]
.net WPF

**Comment by ghost** [comment]
Tambem verifiquei que SC deu o mesmo erro. 
Ou seja não e o servidor.

**Comment by danilobreda** [comment]
Tenho 3 sugestões para você:

-  ~~Você conseguiu rodar o "NFe.AppTeste" que esta contido no código fonte do Zeus e verificar se nele também acontece a mesma coisa? Digo isso pois as configurações da ConfiguracaoApp podem estar incorreta e a default do AppTeste as vezes resolva esse problema, ou pelo menos identifica isso.~~  **(Você disse que já testou... não tinha visto)**

- Algo tambem que pode ajudar é definir ConfiguraoAPP -> propriedade ProtocoloDeSeguranca para: `SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

- Caso a versão do .net for menor que 4.6.1 tente definir para 4.6.1 e verificar se funciona, pois existem alguns bugs de TLS para a versão 4.5.2 e outras menores.

O problema acontece quando? Ao verificar status do SEFAZ? Ou emitir nota?

**Comment by ghost** [comment]
Danilo, 
Uso o SecurityProtocolType.Tls12 porque a SEFAZ pede para usar isso para todos. 
A versão que eu uso do meu sistema 4.7.2 ja teste nessa versão e na 4.8.
Alem do NFe.AppTeste que esta na versão dele.

**Comment by robertorp** [comment]
@fabiociaf  conseguiu?

**Comment by fabiohcnobre** [comment]
Ainda não Roberto estou achando que é erro de cadeia certificadora do certificado. 

O difícil que é uns clientes no estado de Sp e Sc sem condições de ir lá agora.

**Comment by marcosgerene** [comment]
@fabiociaf @fabiohcnobre 
Estou fechando o tópico por estar inativo a algum tempo, por favor reabra se julgar necessário.

**Comment by ghost** [comment]
Pode finalizar meu chamado mais achamos um caso que resolve 90% dos erros que estava dando.
- Atualização do windows 100%, o sistema operacional tem que e está todo atualizado.
- O certmgr.msc tem que esta com os certificados atualizados e ativado
Como mostro na imagem:
![print](http://ciaf.com.br/dfe/img/certmgr.msc.jpg)
