### ISSUE TITLE
Problema com o nuget (Standard)

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#1113]
Lancei um projeto novo para impressão do SAT e NCe em EscPOS.
https://github.com/marcosgerene/Gerene.DFe.EscPos

O projeto é em .NetStandard e o Demo em .NetFramework.

Uso nele duas dependências além do Zeus, ambas tiveram sucesso, o Zeus não.

A referência no .Net Std.
![WhatsApp Image 2020-05-07 at 16 33 10](https://user-images.githubusercontent.com/15945003/81338550-360a9480-9083-11ea-83a5-730c76ef5921.jpeg)

.Net Full
![WhatsApp Image 2020-05-07 at 16 33 10 (1)](https://user-images.githubusercontent.com/15945003/81338494-196e5c80-9083-11ea-8772-7bef0a26f267.jpeg)

O erro:

![image](https://user-images.githubusercontent.com/15945003/81338772-87b31f00-9083-11ea-8c0f-0f808cd1b2cd.png)

Não consegui solucionar.

**Comment by marcosgerene** [comment]
@danilobreda

**Comment by marcosgerene** [comment]
https://github.com/marcosgerene/Gerene.DFe.EscPos/commit/f1a93a9e9bcebbfcc6b6313c101c98622a0cdb9a

**Comment by danilobreda** [comment]
@marcosgerene voce conseguiria elaborar uma branch para mim com o problema para que eu possa dar uma analisada? Esse problema esta ligado a vários bugs do SDK do .net framework + .net core.

**Comment by danilobreda** [comment]
Opa consegui reproduzir o problema e vou analisar o que pode estar acontecendo.

**Comment by danilobreda** [comment]
@marcosgerene encontrei alguns problemas como [essa issue](https://github.com/dotnet/standard/issues/481)... que podem ser um dos motivos do problema. 
Porem o que percebi após uma analise foi o seguinte.
O projeto seu GereneDFeEscPos você apenas está setando como saída no csproj como .netstandard2.0... 
`<TargetFramework>netstandard2.0</TargetFramework>`
O Zeus está diferente de um projeto como o da ACBR por exemplo (que dei uma analisada)... ele tem 2 saídas de DLLs no nuget totalmente diferentes... (segue imagem)

![image](https://user-images.githubusercontent.com/14843499/81372787-96c0be00-90d1-11ea-93f9-d9e242418149.png)

Então o processo que verifiquei que é executado é o seguinte:
- Caso o runtime for 4.0+ ele vai setar as libs do .net 4+.
- Caso for .Net core ou .net standard, ele vai setar o .net standard.

O problema que verifiquei é que como voce setou o target para  **.netstandard2.0.** no projeto "GereneDFeEscPos"... quando o projeto .net framework tenta utilizar ele tenta pegar as dlls do .net standard, e ai não acha pois é um projeto .net framework! (isso tudo na imagem acima)

A solução é no seu projeto GereneDFeEscPos você trocar o `<TargetFramework>netstandard2.0</TargetFramework>`
para 
`<TargetFrameworks>net462;netstandard2.0</TargetFrameworks>`
Assim ele irá selecionar as dlls do .net framework do nuget, quando for .net framework o target. E não do .net standard.

Solucionado o problema!

Vai ficar assim sua lib intermediaria:

![image](https://user-images.githubusercontent.com/14843499/81373368-fec3d400-90d2-11ea-9a52-77b077abe52d.png)


Pelo primeiro link que te passei podemos ver que a maneira como é "gerado" toda a saída das dlls ao buildar o projeto, o .net core trata totalmente diferente do .net framework.  Talvez a origem de todo o problema esteja ai.

Infelizmente não sei como solucionar o problema do nosso Nuget Gerado! Acredito que ele esteja com alguma definição errada, ou falta de configuração... e vou estudar melhor para saber se existe uma maneira de ele selecionar isso automaticamente ou algo assim. Para que não precise ser setado multitarget nos projetos intermediários.

Outra questão é porque não usar o .net core no Windows Forms do projeto Demo... já está funcionando 100% no .net core 3.1+. Tente utilizar que fica 10! (faz um .net framework e outro .net core :D)

**Comment by marcosgerene** [comment]
@danilobreda 
>A solução é no seu projeto GereneDFeEscPos você trocar o <TargetFramework>netstandard2.0</TargetFramework>
para
<TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
Assim ele irá selecionar as dlls do .net framework do nuget, quando for .net framework o target. E não do .net standard.

Tentei fazer a mudança, mas não tive sucesso, se puder fazer um PR lá agradeço, se funcionar com o Zeus "raiz" volto a setar ele como "motor da deserealização" do xml da NFCe.

> Outra questão é porque não usar o .net core no Windows Forms do projeto Demo... já está funcionando 100% no .net core 3.1+. Tente utilizar que fica 10! (faz um .net framework e outro .net core :D)

O demo é em winforms, basicamente  é Ctrl C Crtl V no .Net Core e boa, consigo implementar em 10 minutos, vou colocar sim =)

**Comment by danilobreda** [comment]
@marcosgerene feito, [aguardando aprovação](https://github.com/marcosgerene/Gerene.DFe.EscPos/pull/3/files)
