### ISSUE TITLE
Onde encontro os manuais?

### ISSUE THREAD

**Issue by DevMatheusMartinez** [ZeusAutomacao/DFe.NET#1115]
No readme do projeto, na parte de como usar a ferramenta, esta escrito que antes de fazer qualquer coisa é pra ler os manuais, mas eu não consegui achar esses manuais, alguém pode me ajudar?

**Comment by guidi** [comment]
São os manuais de orientação e de integração de DFe, tem disponível na internet só dar um google.

Exemplo: http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=

**Comment by DevMatheusMartinez** [comment]
Entendi, obrigado.
