### ISSUE TITLE
Como emitir nota fiscal?

### ISSUE THREAD

**Issue by DevMatheusMartinez** [ZeusAutomacao/DFe.NET#1116]
Boa noite gente, estou desenvolvendo um sistema de Controle e Gerenciamento de vendas e produtos.

Esse projeto vocês podem encontrar aqui: https://github.com/DevMatheusMartinez/Controle-e-Gerenciamento-de-Vendas-e-Produtos

O projeto é feito em c# WindowsForm e estou usando SQLite como banco de dados, nele você pode cadastrar seus produtos e vende-los, semelhante ao um sistema de mercado.

Estava tudo indo bem até chegar na parte da NF, pois ao fechar o pedido do cliente eu gostaria que o software imprimisse uma nota fiscal, mas não sei como fazer isso. 

Será que alguém pode me dar uma ajuda? obrigado desde já.

**Comment by fabiohcnobre** [comment]
Podemos te ajudar, temos o nosso discord e o skype 
https://discord.gg/cFqqAW
Que pode tirar suas duvidas.

**Comment by adrbarros** [comment]
Seguido a Opção acima, outra alternativa pra acompanhar é baixar o Projeto do Zeus onde encontrará um Demo com as seguencias para emissão da NF-e, assim tendo uma base da codificação básica

**Comment by DevMatheusMartinez** [comment]
> Seguido a Opção acima, outra alternativa pra acompanhar é baixar o Projeto do Zeus onde encontrará um Demo com as seguencias para emissão da NF-e, assim tendo uma base da codificação básica

Sim, eu baixei a demo, mas não consigo dar sequencia nela, por causa do certificado digital que eu não tenho e a lanchonete que eu estou desenvolvendo o sistema não possui esse certificado ainda mas esta correndo atrás.

**Comment by adrbarros** [comment]
Bom, para os testes em ambiente de homologação, você vai ter que ter um certificado para testes.
Assim é mais facil também para as Orientações do Grupo

**Comment by marcosgerene** [comment]
@DevMatheusMartinez 
Vou fechar a issue por falta de movimentação, abra uma nova issue caso necessário
