### ISSUE TITLE
Erro enviando NFCe - 397 QR-Code divergente da Nota Fiscal 

### ISSUE THREAD

**Issue by prandini** [ZeusAutomacao/DFe.NET#112]
Quando envio o lote de xml ao serviço de homologação (PR) ocorre este erro no XML de Retorno:

![xmlretorno](https://cloud.githubusercontent.com/assets/10118776/14094398/4eaddc5a-f52c-11e5-9811-b86b4a2c8065.png)

Alguém passou por este mesmo problema, e conseguiu resolver? Estou meio confuso pois o Digest Value é gerado automático.

Obrigado!

**Comment by adeniltonbs** [comment]
Não consigo fazer o teste por aqui na UF do PR:
![image](https://cloud.githubusercontent.com/assets/6733483/14095977/90a3937a-f53b-11e5-892a-8a48a49b1ea5.png)

Poderia submeter o xml que está sendo enviado para a SEFAZ do PR a uma validação no link https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx? e postar o resultado ou nos enviar o xml para darmos uma olhada?

**Comment by prandini** [comment]
Opa demorei a responder.

fiz a validação pelo site:

![xml](https://cloud.githubusercontent.com/assets/10118776/14129821/fa6ce7fc-f603-11e5-99d7-7ee1d1ce0756.png)

testando pelo site, da o mesmo erro (397) também ocorre outros, mas acho que é por causa do tempo que foi criado o xml.

e o xml segue em anexo ;
[41160308045279000131650010000123451000012349.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/194620/41160308045279000131650010000123451000012349.zip)

**Comment by adeniltonbs** [comment]
Eu habilitei o grupo infNFeSupl e enviei uma NFCe em homologação para a UF de SE, utilizando o aplicativo de teste da biblioteca. Veja o resultado da consulta abaixo:
![image](https://cloud.githubusercontent.com/assets/6733483/14142597/1d56039e-f65d-11e5-8a44-d391c04c34db.png)

Vou anexar o xml desta NFCe aqui [teste.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/195513/teste.zip)

Agora eu percebi um detalhe: No seu xml o elemento root não é enviNFe e sim NFe. Até aí tudo bem, a SEFAZ também vai aceitar dessa forma. Mas isso me mostra duas coisas: Ou você não usou esta biblioteca para emitir sua NFCe ou você fez algumas adaptações nela, estou certo?

Faça uma comparação do xml em anexo nesta mensagem com o xml que vc me enviou.

Outra coisa, estou fazendo um commit da aplicação de demonstração, corrigindo o valor dos pagamentos na nota de demonstração.

**Comment by prandini** [comment]
Ola adeniltonbs, obrigado pela resposta eu estava de mudança por isso a demora a responder.

Aqui também esta habilitado o grupo infNFeSupl, comparei o teu XML com o meu aqui e realmente tem estas diferenças citadas acima.

Sobre as tuas perguntas, eu usei a sua biblioteca e não fiz nenhuma alteração nela, somente fiz algumas modificações no app de teste, uma para pegar o estado selecionado no app, outra para corrigir o valor dos pagamentos (que você corrigiu no teu ultimo commit).

Vou começar a realizar novos testes para ver o porque que sai diferente os dois XMLs

**Comment by prandini** [comment]
@adeniltonbs Sobre o xml estar diferente, era porque eu simplesmente mandava criar ele "Criar e Salvar XML 3.0" e depois eu carregava e enviava ele; quando utilizo o "Criar e Enviar 3.0" o XML fica identico;

O erro 397 não está mais ocorrendo, porém estou tendo o mesmo problema relatado neste tópico:
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/68

*_464 = Codigo de Hash no QR-Code difere do calculado *_

alguém já conseguiu resolver este problema com o calculo do Hash do QRCode no PR?

**Comment by adeniltonbs** [comment]
No post https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/68 o vasist disse "Ola Pessoal, comigo esta tudo ok com o hash do QRCode no PR." Dê uma olhada nesse issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/99
