### ISSUE TITLE
DANFe na Web

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#1121]
Olá amigos, como gerar a DANFe ara Web usando essa DLL e a FastReports, alguma dica pra mim, sou leigo na área Web só mexo com desenvolvimento desktop.

**Comment by guidi** [comment]
Leandro, a forma que fazemos aqui é gerar um PDF no servidor WEB, a aplicação web recebe o caminho desse PDF e exibe em tela, atente para o fator de segurança, esse PDF só deve estar acessível dentro de uma sessão logada da sua aplicação WEB, ou através de outro método de autenticação, como um token por exemplo.

**Comment by leandrossantos** [comment]
> Leandro, a forma que fazemos aqui é gerar um PDF no servidor WEB, a aplicação web recebe o caminho desse PDF e exibe em tela, atente para o fator de segurança, esse PDF só deve estar acessível dentro de uma sessão logada da sua aplicação WEB, ou através de outro método de autenticação, como um token por exemplo.

Obrigado @guidi mais a minha dúvida é de como fazer usando a Fastreports que acompanha o projeto aqui, tudo via linhas de comando, sem a necessidade de uma outra aplicação entende.

**Comment by danilobreda** [comment]
Era interessante saber qual framework do .NET você esta querendo focar para essa questão.. O .net core e .net framework ambos suportam a impressão do DANFE na web. (Em uma aplicação ASP NET por exemplo). Ambos em HTML e suporte para geração em PDF também.
Hoje eu utilizo a geração do DANFE em .net core em HTML em ambiente Linux!... o PDF eu parei de utilizar o do FastReport por questões de uso alto de memória, e utilizo o nuget Wkhtmltopdf.NetCore em um serviço separado para CONVERSÃO de HTML para PDF.

Um bom exemplo do que eu utilizo é o projeto [DEMO que esta aqui](https://github.com/ZeusAutomacao/DFe.NET/tree/master/NFe.Danfe.AppTeste.NetCore)

**Comment by denernun** [comment]
Para o NFC-e eu gero um pdf em uma aplicação em .net framework 4.5, os
demais eu gero em .net core no Linux, assim como todas as demais operações.
Existe a opção de gerar o pdf ou qualquer outro formato do NFC-e em .net
core ? Para impressão local na impressora térmica, utilizo um serviço em
Delphi que já tem alguns anos. Mas tem cliente que só quer gerar e enviar o
pdf pro cliente, já que usa o mobile pra fazer a venda.

**Comment by danilobreda** [comment]
@denernun NFC-e ainda não tem para .net core nem o processo de integração e nem impressão DANFE...  Já para .net framework tem a impressão e integração. Acredito que até final do ano, vamos ter o NFC-e funcionando totalmente em .net core! Vou iniciar a migração em breve.

**Comment by denernun** [comment]
Maravilha! Não tenho problema nenhum hoje, só o fato de manter dois
projetos mesmo.

Se pudesse eu ajudaria, mas não tenho capacidade técnica pra isso ainda,
venho do mundo Delphi desde 1996 e ACBr desde 2006, e apesar disso, fiz a
webapi em .netcore completa em um menos de um mês, esse projeto de vocês
está muito bom, código bem documentado, fácil de implementar e dar
manutenção.

Parabéns e obrigado aos envolvidos !

**Comment by henriquegnetzka** [comment]
Oi pessoal! Estou chegando agora por aqui... @danilobreda você já tem a DANFE em HTML? Quer incluir no projeto? Se não, vou fazer por aqui e posso enviar! hehe

**Comment by danilobreda** [comment]
@henriquegnetzka Tem sim! Utilizamos o FastReport OpenSource para impressão. Gera em HTML e também em pdf e imagem, porem não recomendo o pdf pelo alto uso de memória. (Utilizo o nuget Wkhtmltopdf.NetCore em um serviço separado para CONVERSÃO de HTML para PDF.)
Para Demo tempos a pasta [NFe.Danfe.AppTeste.NetCore](https://github.com/ZeusAutomacao/DFe.NET/tree/master/NFe.Danfe.AppTeste.NetCore) que contem um exemplo de como utilizar.

**Comment by henriquegnetzka** [comment]
Entendi! Valeu pelo retorno! Vou gerar por aqui sem o FastReport, pra gente não faz sentido usá-lo... Temos uma função para renderização de HTML, e daí gerar o PDF pelo wkhtml fica tranquilo. Se ficar legal eu subo aqui como opção. : )

**Comment by danilobreda** [comment]
Vou fechar a issue, qualquer novas dúvidas só criar uma nova Issue! 👍

**Comment by marcosgerene** [comment]
@henriquegnetzka 

Cara, se você puder fazer a gentileza de postar o código do seu HTML ficaremos agradecidos.

Hoje usamos o FastReports porque é open source e faz "o mesmo serviço", de gerar o HTML, mas um código "puro" em HTML acredito que seria bem legal, inclusive na questão de custo de processamento.

Obrigado, abraço

**Comment by henriquegnetzka** [comment]
Claro @marcosgerene, vamos postar sim! Devemos implementar a biblioteca entre esta semana e a próxima, daí vamos ver se conseguimos e posto sem problemas!
