### ISSUE TITLE
Problemas ao cancelar NFe

### ISSUE THREAD

**Issue by ludero** [ZeusAutomacao/DFe.NET#1123]
Boa tarde, estou implementando o evento de cancelamento e configurei todos os serviços para a versão 4.0, mas debugando verifiquei que a versão do NFeRecepcao fica sempre na versão 1.0 ocorrendo o erro de validação na imagem.

![image](https://user-images.githubusercontent.com/14300543/83806499-fc2fac80-a687-11ea-82f5-8d12f8b0f3b0.png)

Pesquisando mais um pouco, verifiquei que está utilizando uma versão antiga do schema.
Não consegui encontrar no código como corrigir isso.
Alguma dica?
Obrigado

**Comment by robertorp** [comment]
[Schemas.Nfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/4738016/Schemas.Nfe.zip)
Testa esses aí, ouve uma época em que a sefaz disponibilizou schemas com erro justamente aí. 

Com a vida da versão da NF-e 4.00 o que foi mudado foi o layout da NF-e é urls. 
Layout de eventos continuaram os mesmos. Ou seja é normal você encontrar um xml de evento de cancelamento ou carta correção 1.00 ou 3.10 pois os mesmos não mudaram.

**Comment by ludero** [comment]
Deu certo!!! Valeuuuuu.
