### ISSUE TITLE
Quantidade Total de Itens no DANFE NFCe

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#1125]
Uma dúvida. Na quantidade total de itens é o SOMATÓRIO das quantidades dos itens, ou a CONTAGEM (COUNT) dos itens? Pois no Danfe NATIVO, está a CONTAGEM. E no Danfe FAST está o SOMATÓRIO (SUM).

Outra dúvida, no danfe NATIVO, tem como configurar o detalhe de itens para sair apenas uma linha não?

![image](https://user-images.githubusercontent.com/19655107/84071132-9737c780-a9a3-11ea-8f27-197f24fc513f.png)

![image](https://user-images.githubusercontent.com/19655107/84071260-c817fc80-a9a3-11ea-8251-6fb2b4d99d06.png)

*NO CASO DA QUANTIDADE DE ITENS, SE FOR MESMO POR CONTAGEM (COUNT) E NAO SOMATÓRIO (SUM), JA ALTEREI O .FRX. SO AGUARDO A CONFIRMAÇÃO PRA MIM ENVIAR O PULL REQUEST.

**Comment by danilobreda** [comment]
O Correto seria [como no manual](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=/xyXbAFZ71k=):

![image](https://user-images.githubusercontent.com/14843499/84216465-fd097980-aa9f-11ea-84c2-6219bf9cf3f5.png)

ou seja, é CONTAGEM (COUNT), e não a quantidade em kg ou quantidade somadas... Caso o cliente peça é interessante adicionar em informações complementares da NFCe.

Aguardamos o pull request :D

**Comment by danilobreda** [comment]
> Outra dúvida, no danfe NATIVO, tem como configurar o detalhe de itens para sair apenas uma linha não?

Quanto a essa questão não tenho essa informação, talvez aguardar com o @marcosgerene ou @robertorp  que utiliza essa questão. Acredito que seja apenas algo em relação ao design e que pode ser adicionado caso não exista.

**Comment by marcosgerene** [comment]
@danilobreda @gui-abrantes 

O Danfe nativo foi feito pelo @robertorp "na unha" se não me engano, eu sinceramente não sei "o quão simples" é mexer no código dele.

Se precisar de algo "fora" do FastReports para Danfe, tem a opção do EscPos em outro projeto meu (https://github.com/marcosgerene/Gerene.DFe.EscPos). Agora se quiser continuar usando o Danfe Nativo atual com esse ajuste, abra uma issue específica para isto e aguarde um retorno do @robertorp OU envie um PR, ficarei feliz em analisar e aceitar o mesmo =)

**Comment by gui-abrantes** [comment]
Sobre a PR de mudar o .frx, mudei aqui e funcionou direitinho....a PR já está no ar! valeu!

**Comment by marcosgerene** [comment]
@gui-abrantes 

Fiz algumas considerações no PR.
Por favor, reveja o mesmo e reabra se possível.
Vou fechar a issue e aguardar o PR.

Obrigado
