### ISSUE TITLE
Problemas com impressão FastReport

### ISSUE THREAD

**Issue by douglashferreira** [ZeusAutomacao/DFe.NET#1127]
Bom dia,

gostaria de saber se tem um jeito fácil de os dados Adicionais não ficarem por cima dos itens quando é muito grande.

![attachfilehandler](https://user-images.githubusercontent.com/17594937/84657348-87137100-aeea-11ea-8481-0e79366680a7.png)

**Comment by marcosgerene** [comment]
@douglashferreira 

Esses dias tive essa conversa com o @adrbarros no particular...

Essa mudança dos adicionais "subirem" fui eu que fiz, porque cortava adicionais muito grandes antes, agora o problema é que "ele cresce e sobrescreve os itens.

Eu sinceramente não tive tempo de ver o código ainda, mas quero ver hoje se possível... 

Por favor, posta o XML aqui, vou estudar uma solução.


Abraços

**Comment by douglashferreira** [comment]
@marcosgerene, eu tentei um bom tempo mas não consegui resolver isso.

Obrigado pela ajuda!

[DadosAdicionaisGrande.zip](https://github.com/ZeusAutomacao/DFe.NET/files/4780280/DadosAdicionaisGrande.zip)
Não deixou anexar xml dai zipei

**Comment by marcosgerene** [comment]
@douglashferreira @adrbarros 

Acredito que tenho uma solução:

![image](https://user-images.githubusercontent.com/15945003/84663710-e75ae080-aef3-11ea-9942-31cdc7afd893.png)

[antes.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/4780572/antes.pdf)
[depois.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/4780573/depois.pdf)

**Comment by marcosgerene** [comment]
@douglashferreira 

Reabra a issue se o problema persistir.
