### ISSUE TITLE
Web Service Autorizacao

### ISSUE THREAD

**Issue by MarceloLeandro** [ZeusAutomacao/DFe.NET#113]
Ocorre para vocês ao executar o webservice de autorização o retorno não vim um object "ret.."
e vim null? sabem dizer por que acontece isto, dele vir nulo...se o xml passado para consulta é correto, além de url's e etc.?
Agradeço!!

**Comment by adeniltonbs** [comment]
Comigo, usando a biblioteca, até agora nunca aconteceu.

**Comment by MarceloLeandro** [comment]
Resolvido amigo, era prob com a classe NfeCabecMsg
