### ISSUE TITLE
Debuggar usando o nuget

### ISSUE THREAD

**Issue by rafjsouza** [ZeusAutomacao/DFe.NET#1130]
Pessoal boa tarde estou com uma dúvida.
Tenho o projeto do Zeus DFE baixado, porém estou usando o projeto do Nuget no meu projeto, eu consigo debugar usando o símbolos no meu projeto mesmo utilizando o Zeus do Nuget?

**Comment by marcosgerene** [comment]
Boa noite,

Acredito que não. Até aonde eu conheço só é possível debugar uma dll compilada "em Debug", o nuget nosso é gerado para Release.

Acredito que seu problema na verdade esteja relacionado à issue https://github.com/ZeusAutomacao/DFe.NET/issues/1131, então vou fechar essa issue.

Se não nenhuma ligação, por favor reabra a mesma.
