### ISSUE TITLE
Problema ao manifestar na nova versão do pacote nuget

### ISSUE THREAD

**Issue by henrique25** [ZeusAutomacao/DFe.NET#1131]
Boa tarde, 
venho tendo o seguinte problema ao manifestar uma nfe como CienciaDaEmissao

_Erros na validação:
O elemento 'http://www.portalfiscal.inf.br/nfe:descEvento' é inválido - O valor 'Ciência da Emissão' é inválido dependendo do tipo de dados 'String' - Falha na restrição Enumeration_

O problema aparentemente está no Enum NFeTipoEvento

Nessa imagem está o NFeTipoEvento do pacote nuget que tenho em meu projeto
![image](https://user-images.githubusercontent.com/24814282/84956340-58a2bb00-b0cf-11ea-81a9-357beca43968.png)

Nessa imagem tenho o NFeTipoEvento na versão mais atual do zeus
![image](https://user-images.githubusercontent.com/24814282/84956407-84be3c00-b0cf-11ea-9e52-3219805bd535.png)

Repare que na versão do nuget, a operação de ciência está escrito **TeMdCienciaDaEmissao**
e na versão mais atual do zeus está **TeMdCienciaDaOperacao**.
Peço por gentileza que seja liberado uma nova versão de pacote nuget com essa alteração feita.

**Comment by rafjsouza** [comment]
Estou com esse mesmo problema

**Comment by marcosgerene** [comment]
O problema já foi resolvido e reportado ao @robertorp para dar update no nuget.

Revert no commit que ocasionou o problema:
https://github.com/ZeusAutomacao/DFe.NET/commit/ee6637b8950f3a71ce032a97beecfe27b6081847

Reaproveitando o commit sem o problema:
https://github.com/ZeusAutomacao/DFe.NET/commit/9b758555b0c3ca01db87c489a9aaa1b91190adc3

**Comment by robertorp** [comment]
Vou gerar um nuget amanhã, obrigado!
