### ISSUE TITLE
DACTE CTe OS (modelo 67)

### ISSUE THREAD

**Issue by capoani** [ZeusAutomacao/DFe.NET#1134]
Olá amigos, gostaria de saber se o projeto possui impressão de CTe OS modelo 67. 
Notei que existe a emissão porém não encontrei a impressão. Caso não possua conhecem algum projeto open source que a faça?
Abraço. 
Tiago

**Comment by marcosgerene** [comment]
@capoani 

Nao, a impressao atual atende apenas 57.

Para .Net desconheço opensource para tal.

**Comment by robertorp** [comment]
Não tem impressão para CT-e OS infelizmente ;( , mas um dia terá!
