### ISSUE TITLE
Impressoras NFCe

### ISSUE THREAD

**Issue by pbalbino** [ZeusAutomacao/DFe.NET#1135]
Gostaria de saber se existe alguma impressora térmica conhecida que não imprime o DANFE NFCe?

Tenho um cliente que possui uma impressora Bematech MP-2800 TH e queria saber se imprime, como não estou com ela em mãos pra testar queria saber se alguém já utilizou?

Estou usando o método Imprimir da classe DanfeBase (namespace: NFe.Danfe.Fast) do projeto NFe.Danfe.Fast.

Obs.: Eu já imprimo utilizando uma sweda si-300s.

Obrigado!

**Comment by guidi** [comment]
@pbalbino MP-2800 funciona normal, tenho alguns clientes usando sem problemas.

**Comment by pbalbino** [comment]
> @pbalbino MP-2800 funciona normal, tenho alguns clientes usando sem problemas.

Obrigado pela informações, o cliente vai me enviar a impressora pra teste, vlw!
