### ISSUE TITLE
Remoção de restrição sealed na classe NFe.Servicos.ServicosNFe

### ISSUE THREAD

**Issue by rafjsouza** [ZeusAutomacao/DFe.NET#1138]
Pessoal boa tarde, estou com uma dúvida.
Teria algum motivo espcial da classe NFe.Servicos.ServicosNFe  ter a restrição sealed? Para quem usa o nuget seria muito
mais fácil sobrescrever o comportamento dela se pudéssemos estendê-la. 
Estou em uma situação onde o comportamento de alguns métodos dela precisam ser diferentes, porém não gostaria de ter que reescrever uma outra classe ServicosNFe copiando os métodos da original, pois fica muito mais complicado atualizar o Zeus e manter as duas classes atualizadas. 
Caso seja possível, poderia enviar um PR com a alteração?

![image](https://user-images.githubusercontent.com/22361235/86825846-4250a500-c066-11ea-959d-d38310661cb7.png)

**Comment by marcosgerene** [comment]
@rafjsouza 

Eu não vejo nenhum motivo especial para tal, na minha opinião seria bem interessante a sobrescrita.

Abra um PR, vou pedir para o @robertorp e o @danilobreda darem uma olhada também.

**Comment by danilobreda** [comment]
Essa classe é bem importante e muda constantemente por conta de ser a porta de entrada para toda a comunicação com o Sefaz. Ela deveria(na teoria) ser utilizada para atender TODOS os serviços que o Sefaz tem.

> Estou em uma situação onde o comportamento de alguns métodos dela precisam ser diferentes,

Qual seria esse comportamento? fiquei curioso... a classe não te atende por qual motivo?

> porém não gostaria de ter que reescrever uma outra classe ServicosNFe copiando os métodos da original, pois fica muito mais complicado atualizar o Zeus e manter as duas classes atualizadas.

Eu acredito que nem deve... esse não é o caminho correto.

Eu utilizo tambem utilizo nuget!  
Eu não uso ela diretamente nas minhas classes de repositórios ou serviços... tenho uma classe intermediaria para que ai sim eu possa usar o Zeus, no meu caso chamo essa classe intermediaria de "NotaFiscalEletronicaServices.cs". Utilizo a injeção de dependência dessa classe minha, o que facilita bastante seu uso no código do sistema.
Aqui esta um exemplo de como uso essa classe intermediaria:
![image](https://user-images.githubusercontent.com/14843499/86870682-3c32e680-c0af-11ea-89c0-a0f708c24027.png)

**Comment by rafjsouza** [comment]
Bom dia @danilobreda 
> Qual seria esse comportamento? fiquei curioso... a classe não te atende por qual motivo?


Então, na documentação da sefaz no Item Padrão de Certificado digital, é informado que pode ser utilizado um certificado para assinatura dos documentos e outro certificado para transmissão, que não precisa ter o CNPJ da empresa do certificado que assina, como mostra na imagem a seguir: 
![image](https://user-images.githubusercontent.com/22361235/86915694-cb182100-c0f8-11ea-84a9-e918492010ea.png)

Isso é bem útil nos casos de certificado A3, pois tenho uma aplicação que só é responsável por assinar os documentos dos clientes utilizando o A3, minha aplicação do servidor é responsável por transmitir o documento assinado. 
Isso me ajuda a manter o controle mais fácil na minha aplicação do servidor e minha aplicação cliente não precisa comunicar diretamente com a sefaz usando o Zeus, quando A3.

Porém o comportamento padrão da classe NFe.Servicos.ServicosNFe é sempre assinar os xmls antes do envio.
O que eu fiz por enquanto foi reescrever alguns métodos da classe de serviço para ter o comportamento que preciso.
Por exemplo,  para o evento de cancelamento, eu criei método público que recebe os parâmetros do cancelamento igual no método de `RecepcaoEventoCancelamento`, porém só gera a classe `evento`. A partir dessa classe posso mandar o xml para a minha aplicação client só fazer a assinatura usando o A3.
Depois de assinar, o xml é enviado novamente para o servidor e o servidor transmite para a Sefaz usando o A1 da minha empresa.  Para ele somente transmitir e não assinar novamente usando o A1 eu precisei reescrever o método de `RecepcaoEvento `para não assinar os eventos caso já tenha uma assinatura. Isso resolveu bem pra mim.
Deixei como um parâmetro opcional no método, dessa forma:
![image](https://user-images.githubusercontent.com/22361235/86919375-82636680-c0fe-11ea-843d-79a504774967.png)

Como é uma funcionalidade que a Sefaz permite fazer, eu acho muito interessante o Zeus ter uma forma de fazer isso também, pois melhorou 100% o controle dos eventos para o A3 e minha aplicação client só ficou com a responsabilidade de assinar os documentos e não mais transmitir.
Se achar interessante essa funcionalidade eu posso organizar aqui meu código e mandar um PR. Acho que ajudaria muito as outras pessoas também.

Então, esse é o motivo do questionamento, alterar os comportamentos, mas se for possível integrarmos isso direto no Zeus ficaria muito melhor.

**Comment by marcosgerene** [comment]
@rafjsouza 

Eu mantenho a opinião de que a classe não deveria ser sealed, mas confesso que não consigo defender isso com unhas e dentes, basicamente não acho os argumentos para manter fechado "bons o suficiente".

De qualquer forma, mesmo que a gente não chegue em um consenso, nada impede que o @rafjsouza modique localmente isso, essa é a graça do Open Source =D

Bem, estou me abstendo da discussão, realmente não tenho argumentos válidos, vou deixar para o @robertorp e o @danilobreda  esta tarefa =D

Abraços

**Comment by denernun** [comment]
Bom dia, achei bem interessante essa questão, realmente não sabia que
existia isso.

E se existe na documentação, e você já fez alguma coisa em cima disso,
ficaria agradecido se fosse implementado.

Obrigado

**Comment by guidi** [comment]
Amigos, bom dia,

também tive a mesma necessidade do amigo @rafjsouza, conforme expliquei na issue #1133 para um outro amigo, uso um aplicativo assinador no client para viabilizar o uso do a3 com aplicação na nuvem, como achei que era um necessidade específica minha e não agregaria muito para o projeto, acabei alterando o zeus localmente, sobrescrevendo alguns métodos, como mais usuários estão tendo essa necessidade, pode ser interessante dar essa possibilidade.

**Comment by danilobreda** [comment]
Assim como o @denernun também não sabia que existia essa possibilidade!! e acredito que viabiliza o processo que o @guidi  quer fazer, que é bem parecido com o meu processo que estou desenvolvendo para suportar A3 em um sistema web.

>  Se achar interessante essa funcionalidade eu posso organizar aqui meu código e mandar um PR. Acho que ajudaria muito as outras pessoas também.

@rafjsouza se for possível fazer um PR a gente te agradece demais! se ficar muito complicado pra vc... pode mandar o código para danilo@bredas.com.br que eu te ajudo nisso.

Quanto a questão do **sealed**, tenho medo de que se deixar aberto as pessoas vão começar a fazer sua "própria" regra de negócio e não informando a gente desse processo ou dessa necessidade.
Outro problema é o ponto de limite de quebra de código dessa classe em futuras alterações, ao alterar ela vamos ter que pensar também nas pessoas que estenderam, um processo que foi muito complicado na época da migração do .net core :(

Assim como o @marcosgerene eu também não tenho muitos outros argumentos válidos para o caso..Então caso você ainda ache necessário @rafjsouza , pode retirar o sealed da classe junto ao PR. (lembrando que pra acessar as props de uma classe derivada vai ter que deixar as props aberto como public?) (também tem a questão do virtual nos métodos, é necessário para possibilitar override?..)

O objetivo do Zeus é resolver todo o problema mesmo de comunicação com o Sefaz! E acredito que o PR vai solucionar o seu e abrir para muitos outros programadores essa possibilidade interessantíssima!

**Comment by rafjsouza** [comment]
> Quanto a questão do sealed, tenho medo de que se deixar aberto as pessoas vão começar a fazer sua "própria" regra de negócio e não informando a gente desse processo 

Vendo por essa forma eu concordo com o @danilobreda , pode acontecer de muitas pessoas criarem mesmo a própria regra e não contribuírem para adaptar o Zeus. Até o final de semana então eu mando o PR pra vocês. 
Obrigado pela atenção.

**Comment by danilobreda** [comment]
Vou fechar a Issue por acredito que o problema tenha sido resolvido. @rafjsouza se possível fazer o pull request para implementar seu case, a gente agradeceria! 👍
