### ISSUE TITLE
Como configurar e emitir uma NFe/NFCe utilizando a aplicação de testes desta biblioteca?

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#114]
Com a aplicação de demonstração de uso da biblioteca aberta, Comece preenchendo os dados solicitados nas guias "**Certificado**", "**Geral**", "**WebService**", "**Emitente**" e "**DANFE**".

Abaixo segue orientação a respeito do preenchimento dessas guias:
## Guia Certificado:

![image](https://cloud.githubusercontent.com/assets/6733483/14143367/3fec6c0a-f661-11e5-92c6-128700b744b9.png)

Para certificados A1:
- Se o certificado estiver instalado no repositório do windows, apenas clique no botão ao lado do campo "Número de Série" e selecione o certificado. Note que ao fazer isso este campo é preenchido com o número de série do certificado;
- Se não instalou o certificado no repositório do windows, mas tem em posse o arquivo *.pfx deste, então clique no botão ao lado do campo "Arquivo", selecione o certificado no diretório onde está armazenado e informe a senha deste no campo "Senha". Veja a imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/6733483/14143493/f59e1fee-f661-11e5-8908-179df8ee223c.png)

Para certificados A3:
- Clique no botão ao lado do campo "Número de Série" e selecione o certificado. Note que ao fazer isso este campo é preenchido com o número de série do certificado. Deste modo toda vez que a aplicação for aberta e alguém tentar usar algum serviço (recepção, status, etc)  o PIN do certificado será solicitado somente na primeira vez;
- Se não desejar que o PIN seja solicitado pelo menos uma vez a cada nova instância da aplicação, informe o PIN do certificado A3, no campo "Senha".
## Guia Geral:

![image](https://cloud.githubusercontent.com/assets/6733483/14143629/b7e7a138-f662-11e5-83b3-8db832ee6074.png)
- Selecione a forma de emissão. Note que, excetuando-se a forma de emissão "Normal", as demais devem ser utilizadas para contingência, somente. Para NFCe a única forma de contingência prevista é a "NFC-e Offline". dê uma olhada no manual de contingência para mais informações http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=;
- Selecione o tipo de documento "Nfe" ou "NFCe"; 
- Informe o diretório dos Schemas (Obs: Os schemas mais recentes suportados pela biblioteca estão em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste/Schemas)
- Marque a opção "Salvar arquivos XML's em:" se desejar que cada xml utilizado no consumo dos diversos serviços sejam salvos;
## Guia WebService:

![image](https://cloud.githubusercontent.com/assets/6733483/14145152/202c8136-f669-11e5-992d-2ba55879d64b.png)
- Em "Selecione a UF de destino:" você deve informar a UF onde sua empresa está situada e não a "UF do destinatário da NFe/NFCe";
- Em "Selecione o Ambiente de Destino", cabe apenas saber que o ambiente de Testes é chamado de "Homologação" e as NFes/NFCes emitidas neste ambiente não possuem validade fiscal;
- Para as opções em "Selecione a versão de cada serviço", é necessário olhar no portal da NFe/NFCe de seu estado quais as versões utilizadas pela SEFAZ para cada serviço. No caso de NFe em produção você pode olhar em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs= e NFe em homologação em http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=.
- No campo "TimeOut (milisegundos)" informe quanto tempo gostaria de aguardar a resposta do servidor.
## Guia Emitente:

![image](https://cloud.githubusercontent.com/assets/6733483/14145372/023d7cce-f66a-11e5-9ecd-c03c6769541e.png)
- Não deve haver dificuldades para preencher esta guia. Os únicos campos que cabem uma explicação adicional são: "Cód. Cidade" - informe neste campo o código do IBGE para o município onde o emitente da NFe/NFCe está situado. Você pode consultar o código IBGE do município no próprio site do IBGE (http://www.cidades.ibge.gov.br/xtras/home.php) e o campo "CRT" - neste campo você deve informar a forma de tributação de sua empresa. Se tiver dúvidas a respeito da tributação consulte o contador. Obs: a CRT "RegimeNormal" deve ser escolhida por empresas não optantes pelo Simples Nacional, como Lucro Presumido e Lucro Real, por exemplo.
## Guia Email:

![image](https://cloud.githubusercontent.com/assets/6733483/14145573/baf8b968-f66a-11e5-9f55-c46764ef814c.png)
- Não foi implementado na biblioteca o envio de emails até o presente momento, então não precisa preencher nada nesta guia.
## Guia DANFE:

![image](https://cloud.githubusercontent.com/assets/6733483/14145609/d812bb34-f66a-11e5-9541-7ce508e1dda5.png)
- Aqui cabe explicação a respeito do "Identificador do CSC:" e do "CSC". Estas informações são obtidas junto à Secretaria da Fazenda de seu Estado. Algumas Sefazes disponibilizam esta informação em seu portal em área restritiva, que pode ser acessada usando o certificado da empresa. Mais esclarecimentos, consulte o contador.

Obs: 
Estes dois campos são usados na montagem do Qr-Code do DANFE da NFCe;
A biblioteca não tem suporte ao DANFE da NFe até o presente momento;

Depois de preencher as informações, conforme indicadas acima, clique no botão "Salvar Configurações para arquivo"

![image](https://cloud.githubusercontent.com/assets/6733483/14145756/63bb199c-f66b-11e5-88c7-dc1a4d2d5b11.png)
## Enviando uma NFe/NFCe:
- Com a aplicação devidamente configurada, clique no botão "Criar e Enviar 3.0"
  ![image](https://cloud.githubusercontent.com/assets/6733483/14145826/afe52970-f66b-11e5-8537-899e5db8b586.png)

A aplicação irá solicitar o "Número da Nota:" e a "Id do Lote:"
O número da nota é sequencial, não informe aqui um número que já tenha sido emitido por sua empresa. Se fizeres isso, a NFe/NFCe será rejeitada por duplicidade com ou sem diferença na chave de acesso, dependo do caso. A "Id do Lote" pode informar o número 1. Você deve controlar a Id do lote em sua aplicação.

O resultado ao clicar no botão "Criar e Enviar 3.0" é descrito abaixo:
- Na guia "Envio" é mostrado toda a mensagem xml que foi encaminhada à SEFAZ, conforme imagem abaixo:
  ![image](https://cloud.githubusercontent.com/assets/6733483/14145954/411c5832-f66c-11e5-9b11-c509d8ddae63.png)
- Nas guias "Retorno" e "XML Retorno" é mostrado o resultado do serviço consumido, conforme imagem abaixo:
  ![image](https://cloud.githubusercontent.com/assets/6733483/14145992/6afe5bc8-f66c-11e5-9053-96f96a05a830.png)
  Note que neste caso, vamos usar o recibo Campo "nRec" da mensagem de retorno, para consultar o resultado do processamento da NFe/NFCe.

O consumo do serviço de consulta é demonstrado pelo botão "Consultar Recibo Lote 3.0", que retornará o seguinte, se tudo estiver correto com sua NFe/NFCe:
![image](https://cloud.githubusercontent.com/assets/6733483/14146063/b245573e-f66c-11e5-9780-c4f185afe006.png)
## Imprimindo uma NFCe:

1 - Salve em um arquivo o xml de envio que foi gerado ao clicar no botão "Criar e Enviar 3.0";
2 - Clique no botão "Adicionar proc ao XMl" e selecione o arquivo xml salvo no passo 1;
![image](https://cloud.githubusercontent.com/assets/6733483/14146246/50135f10-f66d-11e5-8922-ed94cf192d8a.png)

3 - Note que a aplicação indicará que um novo arquivo XML foi salvo.
4 - Clique no botão "DANFE NFCe...", conforme imagem abaixo e selecione no explorer o XML salvo no passo 2.

![image](https://cloud.githubusercontent.com/assets/6733483/14146304/89a2e840-f66d-11e5-9aca-dbe52167c1b7.png)

Note que é necessária a instalação do Fast Report para a impressão. Pelo menos da versão de demonstração deste.
O DANFE da NFCe será visualizado e você pode imprimir. Mas a biblioteca ainda pode imprimir diretamente na impressora ou salvar um pdf com o DANFE.

Para mais dúvidas, abra um issue. O uso dos demais botões não estão cobertos neste guia, por acreditar que após entender como o projeto da NFe funciona, não terão dificuldades em entender o uso destes.

**Comment by rcoproc** [comment]
Excelente Material Adenilton.. parabéns.!!!. funciona perfeitamente.

**Comment by apbertoletti** [comment]
> Informe o diretório dos Schemas (Obs: Os schemas mais recentes suportados pela biblioteca estão em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste/Schemas)

@adeniltonbs este link esta quebrado.

Não seria melhor você sugerir que baixem o pacote de esquema mais atualizados direto do portal da SEFAZ, naquele link de downloads que tem por lá?
