### ISSUE TITLE
Converter string para nfeProc

### ISSUE THREAD

**Issue by CarlosAurelioMRF** [ZeusAutomacao/DFe.NET#1142]
Olá,

Aqui está acontecendo um problema quando vai usar o FuncoesXml.XmlStringParaClasse e está retornando o erro:
`Item has already been added. Key in dictionary: 'NFe.Classes.nfeProc'  Key being added: 'NFe.Classes.nfeProc'`

O erro está sendo gerado lá no _BuscarNoCache_ porque as vezes acaba sendo acessado ao mesmo tempo de locais diferentes.

Quais os problemas de colocar um lock no CacheSerializers?

**Comment by danilobreda** [comment]
@CarlosAurelioMRF foi feita alteração necessária para não dar mais este problema, que ja tinha sido levantado anteriormente por outros.
Caso você utilize o nosso nugget, falta apenas a gente lançar uma nova versão @robertorp vai nos ajudar nisso :)

Qualquer problema ou a não resolução do problema com esse PullRequest, só nos retornar!

**Comment by danilobreda** [comment]
@CarlosAurelioMRF O problema do cache é grande, após uma analise mais detalhada tive que reverter o meu pullrequest a parte do lock via  #1145 
Será feito um novo config para esse processo que com certeza irá resolver seu caso.
Novas novidades te informo nessa issue.

**Comment by danilobreda** [comment]
Problema resolvido! Não é para dar o erro mais, caso aconteça, abra uma nova issue! 👍
