### ISSUE TITLE
Setar pela combobox o tipo de Saida ou Entrada da NFE

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1143]
Ola, estou com dificuldades em setar no meu form por um combobox o tipo de saida ou entrada da nota: 

tpNF = TipoNFe.Saida,

Gostaria de selecionar pela minha combobox // cbmTipoDocumento.Text (Entrada =tpNF = TipoNFe.tnEntrada,), ou (Saida =tpNF = TipoNFe.tnSaida) algum poderia me orientar,  obrigado

**Comment by danilobreda** [comment]
@sigridslima é relativamente simples fazer esse processo, pois você pode fazer um "if(cmbTipoDocumento.SelectedItem ou Text == "Saida") tpNF = TipoNFE.Saida"
Se você ainda é iniciante em c#, recomendo você não inicie com Nota fiscal eletrônica, pois queira ou não é um processo um pouco complicado! 

Vou te mandar uns links para te ajudar:
[C# Tutorial - How to use a Combobox in C#.NET | FoxLearn](https://www.youtube.com/watch?v=uUdmtgJBjk4)
[26 - (APLICAÇÃO WINDOWS - COMBO BOX)](https://www.youtube.com/watch?v=2iepnxK44-s)

**Comment by sigridslima** [comment]
Obrigado amigo, ja tinha feito esse procedimento, porem queria ve um codigo mais limpo. obrigado pela atenção. abraço.
