### ISSUE TITLE
Discussão sobre CACHE e adoção de LOCK em FuncoesXml 

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1146]
A ideia dessa Issue é entendermos o problema que está acontecendo na Issue #1142 que tem haver com um log meu recentemente de um erro igual no meu ambiente de produção.

Primeiro é interessante darmos uma revisão para entender a necessidade do cache na classe **FuncoesXml** que teve origem na issue #610 .
`private static readonly Hashtable CacheSerializers = new Hashtable();`

Pelo entendimento [Segue o link para mais detalhes](https://docs.microsoft.com/pt-br/dotnet/api/system.xml.serialization.xmlserializer?view=netcore-3.1#dynamically-generated-assemblies) esse cache é necessário por conta a maneira com que criamos o **XmlSerializer**. Segundo o link acima da microsoft, ao utilizar esses metodos/construtores os assemblies são gerados e nunca liberados. Causando **memory leak**, que é o problema central da issue #610 e que foi resolvido com sucesso com o cache.

A Issue #1142 porem nos conta de um problema que realmente pode acontecer em casos 'raros' onde a classe estática é acessada por mais de uma thread ao mesmo tempo, ou seja em ambientes com concorrência massiva (que pode ser uma api, onde mais de um usuário está batendo no mesmo endpoint ao mesmo tempo).

Porem para realmente verificar se esse é o problema criei um exemplo chamando o metodo FuncoesXml.XmlStringParaClasse em ambiente com múltiplas threads para simular um ambiente de concorrência alta [https://github.com/danilobreda/ZeusLockTest
](https://github.com/danilobreda/ZeusLockTest
)

O resultado foi que realmente o código acima de teste da o erro indicado anteriormente na issue. **Podemos concluir** que o sistema de cache da classe **FuncoesXML não é THREAD SAFE**. **E pode causar problemas em ambiente de alta concorrência**. **Como sistemas web.**

No mesmo projeto de teste acima coloquei um exemplo de classe com FuncoesXML com lock o que fez com que o erro desaparecesse
```
private static XmlSerializer BuscarNoCache(string chave, Type type)
{
	lock (type) //aqui <-
	{
		if (CacheSerializers.Contains(chave))
		{
			return (XmlSerializer)CacheSerializers[chave];
		}

		var ser = XmlSerializer.FromTypes(new[] { type })[0];
		CacheSerializers.Add(chave, ser);

		return ser;
	}
}

Esse lock é explicitamente para o 'type' que vem, ou seja caso caia 2 vezes aqui ao mesmo tempo porem com 'types' diferentes, não é feito o lock, apenas caso os types forem iguais.
```

**Problemas de performance?** Eu rodei o [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) para saber a diferença de e com lock e o resultado foram praticamente iguais com 0,01ms de diferença.

**Problemas de performance de alta concorrência?** Existe sim um problema onde sistemas de alta concorrência terão locks constantemente, porem são casos bem raros e são hoje totalmente inviáveis pelo bug atual. Para resolver esse problema seria necessário a reestruturação da classe toda, ou uma analise mais detalhada do XMLSerializer para os dias de hoje.

**Problemas de compatibilidade?** O lock foi incluído no .net na versão 3.0 do C#, ou seja é bem antigo. Acredito que não teremos esse problema.

Segue alguns links que pesquisei sobre lock com XMLSerializer
[https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/keywords/lock-statement](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/keywords/lock-statement)
[https://stackoverflow.com/questions/10714790/how-can-i-lock-by-cache-key](https://stackoverflow.com/questions/10714790/how-can-i-lock-by-cache-key)
[https://www.it-swarm.dev/pt/c%23/xmlserializer-dando-filenotfoundexception-no-construtor/967284903/](https://www.it-swarm.dev/pt/c%23/xmlserializer-dando-filenotfoundexception-no-construtor/967284903/](url))

Fica aqui minha analise sobre o caso. Aguardo a analise de todos 👍

**Comment by robertorp** [comment]
No caso de problemas de performance de alta concorrência, talvez seria interessante ter o código de lock somente onde é feita o add na listagem 

```
private static XmlSerializer BuscarNoCache(string chave, Type type)
{
	
		if (CacheSerializers.Contains(chave))
		{
			return (XmlSerializer)CacheSerializers[chave];
		}

		var ser = XmlSerializer.FromTypes(new[] { type })[0];

                lock (type) //aqui <- talvez crie um método para isso 
	        {
		       CacheSerializers.Add(chave, ser);
                }

		return ser;
	
}
```
talvez até cria um método para isso
se observarmos a issue #1142  o problema é que ele tenta adicionar 2 chaves no mesmo tempo com o mesmo Id no dicionário.

Daria certo isso que disse?

**Comment by robertorp** [comment]
Pensei aqui agora, não daria certo o que falei. 
Pois ele passaria da parte da verificação se tem a chave é tentaria adicionar duas vezes da mesma forma.

**Comment by CarlosAurelioMRF** [comment]
Para resolver o meu problema temporariamente eu alterei o metodo e coloquei ele da seguinte forma:

```
        private static XmlSerializer BuscarNoCache(string chave, Type type)
        {
            if (CacheSerializers.Contains(chave)) return (XmlSerializer)CacheSerializers[chave];

            lock (CacheSerializers)
            {
                if (CacheSerializers.Contains(chave)) return (XmlSerializer)CacheSerializers[chave];

                var ser = XmlSerializer.FromTypes(new[] { type })[0];

                CacheSerializers.Add(chave, ser);

                return ser;
            }
        }
```

**Comment by danilobreda** [comment]
@robertorp a maneira com que o @CarlosAurelioMRF  demonstrou acima acho que era como você queria, bem performático e com o lock de recorrencia preservado... pois na maioria das vezes ele já vai estar no cache correto?
Acho que ficaria melhor o código que o @CarlosAurelioMRF colocou.

**Comment by robertorp** [comment]
Sim sim, até o momento o mais bem pensado foi o dele do meu ponto vista. Fico show, ele vai usar o lock somente quando realmente precisar é somente algumas vezes que tera que usar ele.

**Comment by danilobreda** [comment]
Fiz o pullrequest para análise.

**Comment by danilobreda** [comment]
Pessoal algum retorno quanto a esse processo posso aprovar?

**Comment by marcosgerene** [comment]
@danilobreda 
Você está usando em produção a sua mudança ?

**Comment by danilobreda** [comment]
@marcosgerene em produção ainda não por conta de não ter lançado versão ainda, mas em stage esta funcionando 100%! Fiz alguns testes de carga que antes estava dando erro e agora sem erros.

**Comment by marcosgerene** [comment]
@danilobreda na forma como meu sistema trabalha, a maneira anterior funcionava perfeitamente, por isso perguntei sobre o teste em produção, ou seja, "no mundo real", seria legal uma validação nesse sentido...

De resto, pelo tempo que está aberto e que você testou, não vejo mais nenhum problema.

Abraços
