### ISSUE TITLE
Alterações do Sefaz

### ISSUE THREAD

**Issue by lkfischer** [ZeusAutomacao/DFe.NET#1149]
Pessoal estou com uma duvida como eu faço para saber quando o Sefaz ira fazer alguma alteração em sua API?

Obrigado pessoal.

**Comment by danilobreda** [comment]
As alterações não só das API's como outros pontos são todos levantados em cima de [Notas Técnicas] (https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=tW+YMyk/50s=) do SEFAZ

Algumas adesões de adoção de [versão](https://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=), regras de calculo de imposto, etc. São definidos por estado por leis estaduais etc.

Mas fique tranquilo que o Zeus cuida de bastante parte da implementação de alterações de notas técnicas. Como [essa nota técnica que vamos implementar.](https://github.com/ZeusAutomacao/DFe.NET/issues/1093). Isso porque muitas empresas utiliza o Zeus e emitem notas diariamente e precisam estar de acordo com as API's.

Como somos uma biblioteca opensource e da "comunidade" você também pode ajudar quanto ao seu desenvolvimento.
Mas lembre-se que o uso dessa biblioteca não lhe dá quaisquer garantias de suporte.

**Comment by lkfischer** [comment]
@danilobreda , obrigado pela resposta por isso a minha pergunta em relação as alterações do SEFAZ, pois gostaria de estar a par e também se possível ajudar.
