### ISSUE TITLE
Eventos faltantes na NFe.Classes.Servicos.Evento

### ISSUE THREAD

**Issue by rafjsouza** [ZeusAutomacao/DFe.NET#1150]
Olá pessoal bom dia
Estou com uma dúvida, estou tentando desserializar alguns eventos para a seguinte classe NFe.Classes.Servicos.Consulta.procEventoNFe.
Para alguns tipos de evento, estou com erro de desserialização por causa do enum NFeTipoEvento.
Caso eu passe algum evento com código diferente do que consta no enum ele não serializa, porém tem alguns códigos de evento que não estão nesse enum, como **790700** (Averbação para Exportação) ou **990900** (Confirmacao de Internalizacao da Mercadoria na SUF) ou  **990910**(Vistoria SUFRAMA) e etc. 
Gostaria de saber o porque não existe esses códigos no enum **NFeTipoEvento** e quais seriam as consequências de incluir os eventos faltantes, pois todos tem a estrutura do procEventoNFe.

Obrigado.

**Comment by danilobreda** [comment]
Duplicado pela issue [953](https://github.com/ZeusAutomacao/DFe.NET/issues/953). E acredito que não tenha sido resolvido ainda / feito pull request! Por ser um ERRO de desserialização pelo Zeus não ter suporte a esses dados, acredito que deve ser sanado adicionando os numerais de eventos no enum.

Quanto as consequenciais de adicionar os novos elemetnos no enum... help @marcosgerene @robertorp 

EDIT:
Opa confundi a issue #953, pois ela é do CTe... esse problema mencionado pelo desenvolvedor é do NFe...
Alguém saberia aonde teria uma lista desses possíveis eventos?

**Comment by marcosgerene** [comment]
@rafjsouza 

Por favor, poste o XML que não deserealiza, acredito que a partir dai podemos dar um pontapé inicial no ajuste.

**Comment by rafjsouza** [comment]
@danilobreda esses eventos são eventos do fisco, ou seja, são eventos gerados automaticamente pela Sefaz em processos internos, então alguns desses códigos são os mesmo tanto para CTe quanto para NFe. Nesse [site ](https://blog.oobj.com.br/eventos-do-fisco-impacto-faturamento/) aqui explica um pouco e tem link de uma nota técnica da Sefaz com alguns desses eventos de NFe e CTe. 
Seria bom realmente se conseguíssemos uma lista com todos os eventos.

@marcosgerene segue o xml 
[procEventoNFe-790700.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5071857/procEventoNFe-790700.zip)

**Comment by marcosgerene** [comment]
@rafjsouza 

Uma breve explicação:

https://fiscal.io/blog/evento-averbacao-exportacao-nfe-790700-e-seus-beneficios/


XSD:
[e790700_v1.00.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5074377/e790700_v1.00.zip)

> Caso eu passe algum evento com código diferente do que consta no enum ele não serializa, porém tem alguns códigos de evento que não estão nesse enum, como 790700 (Averbação para Exportação) ou 990900 (Confirmacao de Internalizacao da Mercadoria na SUF) ou 990910(Vistoria SUFRAMA) e etc.
Gostaria de saber o porque não existe esses códigos no enum NFeTipoEvento e quais seriam as consequências de incluir os eventos faltantes, pois todos tem a estrutura do procEventoNFe.

Se esse evento está nos schemas, na teoria todos os eventos estão (ou deveriam) estar. Logo, respondendo sua pergunta, deve-se incluir todos os números no enum e mapear as classes faltantes (nesse caso, "itensAverbados").

É um processo relativamente simples e não muito trabalhoso, acredito que em meio dia de trabalho possa ser feito, agora não sei qual a disponibilidade dos devs...

De qualquer forma, vou tentar implementar esse evento em especial que você levantou e postou o XML. Infelizmente, não estou com tempo hábil para levantar os demais faltantes, se você quiser levantar a lista dos faltantes e postar aqui, podemos ir implementando um a um conforme a disponibilidade.

---

@rafjsouza
Teste, por favor https://github.com/ZeusAutomacao/DFe.NET/pull/1152

**Comment by rafjsouza** [comment]
Bom dia pessoal, @marcosgerene  funcionou sim, obrigado, assim que eu conseguir eu levanto os eventos diferentes que nós utilizamos e mando o PR incluindo eles.

Obrigado!
