### ISSUE TITLE
Renderização da DANFE em HTML

### ISSUE THREAD

**Issue by henriquegnetzka** [ZeusAutomacao/DFe.NET#1151]
@danilobreda Tudo bem? Estou terminando aqui o mecanismo de impressão em HTML (e PDF pelo wk). Eu precisei fazer duas pequenas alterações em duas classes. Posso subir um pull para você avaliar? Daí vou terminar de fazer os testes (estamos terminando o código de barras, entendendo se será melhor fazer via imagem ou fonte mesmo) e daí subo tudo...

No caso da renderização, precisarei subir algumas funções de processamento de texto. Você tem alguma recomendação de onde eu possa colocá-las? São duas funções, na verdade:

- Uma que transforma um objeto (e seus filhos) e um dictionary (string/object).
- Uma que processa o texto com tags ({NFe.infNFe.ide.nNF}, por exemplo), substituindo pelo valor.

As funções são nossas mesmo, do framework do [Nimbly](https://nimbly.com.br), mas podemos publicá-las sem problema. Faz sentido pra ti subir isso nesta biblioteca mesmo? Como você recomenda que eu faça? Eu pensei sem criar outra "independente", mas acho que só vai dar trabalho... 

Este post foi separado do #1121 pois aquele tratava de outro assunto.

Marcando @marcosgerene que estava interessado na feature também.

**Comment by danilobreda** [comment]
@henriquegnetzka acho legal que você crie um projeto (.csproj) novo, e coloque tudo que precise ai dentro... e manda via pullrequest pra gente analisar. Quanto ao wk, acho que **não** seria uma boa colocar ele nesse projeto, para transformar em .pdf a gente pode recomendar que o usuário utilize o wk para isso, as dependencias dele são bem pesadas. Eu na vida real utilizo o fastreport para gerar em html e o wk em outro microservice que gera pdf de diferentes relatorios e danfes.

**Comment by henriquegnetzka** [comment]
Fechado, beleza! Então, na real eu vi aqui e utilizamos o SelectPdf para renderizar, o wk não renderizava a contento. Mas, tendo a DANFE em Html, é bem simples mesmo passar pro PDF, talvez possamos disponibilizar isso na documentação de alguma forma.

Estamos acertando algumas coisas do layout e, especialmente, a paginação; assim que tiver tudo feito, encaminho aqui. Eu preciso de permissão pra fazer o pull, me avisa se pode me dar. Se não, mando como anexo aqui mesmo.

**Comment by danilobreda** [comment]
@henriquegnetzka perfeito... quanto a permissão, é só fazer um fork do projeto do Zeus pro seu github pessoal...
![image](https://user-images.githubusercontent.com/14843499/90415437-7799db00-e087-11ea-98f7-5a1ecf1949c5.png)

Vai aparecer o Projeto Zeus no seu repositorio pessoal (da sua conta) e ai só você fazer as alterações por la... você vai ter total acesso a esse seu repositório.
Quando estiver feliz com as alterações é so fazer um pullrequest do seu repositório pessoal para o repositório do Zeus. (branch master) que o pullrequest aqui nesse projeto do Zeus será criado e a gente pode analizar...

Qualquer coisa recomendo [esse vídeo](https://www.youtube.com/watch?v=l1rwvDvD1og)

**Comment by henriquegnetzka** [comment]
E aí, pessoal! Tudo bem? Bom, o projeto avançou mas morreu na praia: não consegui fazer a paginação no PDF. A NT da DANFE determina que o número da página precisa aparecer ali "Página 1 / 3" no cabeçalho, e não rolou não... Consegui apenas para 1 folha.

Algum insight?

**Comment by danilobreda** [comment]
@henriquegnetzka o que vc utilizou para converter do html pro pdf? Acredito que o problema desse conversor em si, porem só de gerar em HTML pra gente já é uma maravilha... converter de html pra pdf ja é outros 500... eu tenho o mesmo problema hoje pois o OpenFastReport gero em html e depois converto pra pdf em outra API.

**Comment by henriquegnetzka** [comment]
Então, eu tentei alguns, mas em todos cheguei no mesmo lugar! Aqui a gente usa (com muito sucesso) o SelectPdf; mas, mesmo nos que usam o wk, tive dificuldades em paginar! Esse é o problema, na verdade... porque a paginação tem a linha variável; se fosse a linha com tamanho fixo, estava fácil.. mas ela é variável; eu posso ter 25 produtos em uma página, ou 2, porque a descrição do produto "é muito grande".

A única ressalva disso, mesmo, é que se for mandar o HTML pro cliente (ou um link para ele abrir a DANFE), aí tem "zero problemas"!

Vou me organizar aqui pra subir isso na semana que vem então!

**Comment by danilobreda** [comment]
@henriquegnetzka tudo bem? Com o final do ano chegando, estou começando a pegar mais o projeto, já estou até migrando o mesmo para ser suportado para .NET 5, gostaria muito de pelo menos ter acesso ao código para testar e já integrar no Zeus. Como posso ter acesso ao código? Mesmo que não for um código que está compilando ou que não tenha exemplos, eu me viro aqui! 
Tenho problemas com o wk, porem aprendi a contornar o mesmo depois de meses tentando varias coisas :D, existem alguns segredos da paginação no mesmo, algumas tags secretas de html, porem preciso relar no código para ver o que posso fazer!

Imprimo boletos escolares com o wk, detalhe que cada banco é um layout diferente e sempre funcionou bem... acredito que eu possa ajudar!

**Comment by henriquegnetzka** [comment]
@danilobreda, tudo bem?

Feliz ano novo!

Mil desculpas, muita correria por aqui no final do ano! Mas vamos lá, aqui está o código!

- Foram alteradas 3 classes pra permitir que a classe tivesse 100% da DANFe em suas propriedades, conseguindo "ir e voltar" do XML mas também do JSON.
- Criamos o template em HTML
- A unit Funcoes tem algumas funções que ajudam a converter um objeto em um dicionário, e outra função para renderizar um texto usando as tags. A função permite muito mais coisas (como formatação, tags especiais e etc); eu deixei ali o código (talvez não compile), mas acho que você vai "se encontrar" nele e apagar algum código que não faça sentido (as formatações são importantes).

O problema, até agora único, é a paginação mesmo. Não encontrei como resolvê-lo... E também tem uma questão da formatação da nota (a página 2 muda, exige o cabeçalho e o rodapé mas não outros dados)... Eu tinha criado a "NFeVerticalPagina2.html", mas ficou uma baita gambiarra e eu desfiz! hehe

Vai me falando dos avanços, bora tentar matar isso!

[DANFe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5795590/DANFe.zip)

**Comment by adeniltonbs** [comment]
Bom dia @henriquegnetzka, parabéns pela iniciativa.

Para o DANFE em html com paginação sugiro usar a biblioteca opensource do FastReports que já usamos no projeto. https://github.com/FastReports/FastReport

Basta usar os arquivos de DANFE já existentes e pedir para exportar para HTML. Usamos isso em uma API para um front end React.

principais vantagens que posso mencionar:
- Você reaproveitará o mesmo design (arquivo .frx) tanto para aplicações desktop como para web. Esses arquivos de design já estão prontos na bilbioteca;
- Suporta paginação e outros n recursos já implementados no FastReports;
- Suporte a exportação em outros formatos  BMP, PNG, JPEG, GIF, TIFF, EMF e PDF mediante uso de um plugin;
- Ela possui um editor de design de relatórios da comunidade e gratuito.
![image](https://user-images.githubusercontent.com/6733483/104191865-d841ff80-53fc-11eb-94cf-1069520dfafe.png)

**Comment by henriquegnetzka** [comment]
Oi @adeniltonbs !! hehe, obrigado! Parabéns a vocês aí pelo projeto!

Pois é, a gente usava o FR em outro projeto (desk)... Mas não pretendemos voltar pra ele não! hehe... Tanto por expertise de equipe quanto para "simplificar" o máximo aqui da arquitetura... Hoje nós usamos o FR para renderizar o PDF mesmo, na verdade! E é disso que estamos fugindo! hehe

Mas se não quiserem migrar a renderização para "fora" do FR, vou continuar tocando aqui! Falta "tão pouco" (paginação) que acho, mesmo, que valha a pena! Talvez seja o caso de pagar a plataforma de renderização de PDF inclusive...

**Comment by marcianobandeira** [comment]
olá @henriquegnetzka parabéns pelo trabalho com o danfe com modelo em html.

Também acho interessante fugir um pouco do fast report e ter algo mais independente, no meu caso aqui, estava testando o danfe com o fastreport, no windows funciona até bem, mas como preciso utilizar servidor linux, recebo um erro FastReport.Utils.CompilerException: (153,103): Error CS0117: Please, don't use the method 'NewLine'.

Devido a isso resolvi buscar alternativas, e a principal delas seria renderizar o danfe diretamente no client angular com html.

Acho que seria bem enriquecedor ao projeto DFe.NET incorporar esse seu trabalho. Como está hoje, conseguiu resolver o lance da paginação?
