### ISSUE TITLE
Retorno da Sefaz problemas de acentuação no motivo da rejeição

### ISSUE THREAD

**Issue by bruno-crr** [ZeusAutomacao/DFe.NET#1153]
Boa tarde, estou com problema em tratar o motivo da rejeição abaixo, ela vem com caracteres especieia diferente de outras rejeicoes que já trato que não vem com acentuação.
Alguém já viu este erro ou tem alguma idéia de como resolver

erro 600
Rejei��o: CSOSN incompat�vel na opera��o com N�o Contribuinte [nItem: 1]

erro 610
Rejeicao: Total da NF difere do somatorio dos Valores que compoem o Valor Total da NF

**Comment by marcosgerene** [comment]
@bruno-crr 
Você não pode usar CST (CSOSN) 101 com destinatário não contribuinte. Tente com 102.

**Comment by bruno-crr** [comment]
Opa talvez eu nao tenha me expressado direito, o problema nao é como resolver a rejeição e sim sobre os caracteres que estão vindo no campo motivo do xml de retorno deste erro especifico, o erro de baixo ele retorna as palavras sem acentuação e o de cima com caracteres coringa.

**Comment by marcosgerene** [comment]
@bruno-crr 

Então o problema deve estar no Encoding.

Poste o XML de retorno e sua rotina para ler o mesmo para que eu possa tentar ajudar.

**Comment by danilobreda** [comment]
@bruno-crr Caso vc esteja utilizando o nugget, não é para dar esse problema. Caso você esteja compilando, com certeza os arquivos seu deve estar com Encoding incorreto. Verifica ai, pois já tive esses problemas.

Caso você esteja utilizando nugget fala pra gente, porque deve ser um bug.

**Comment by bruno-crr** [comment]
estou usando o nugget sim.
esse é o xml de retorno com a rejeição, outras rejeições que eu forço vem normal, apenas esta até agora que veio com esse problema

Rejeição 600

`<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>AM4.00</verAplic><nRec>130000156256409</nRec><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>13</cUF><cMsg>1300</cMsg><xMsg>Continue Tentando</xMsg><protNFe versao="4.00"><infProt><tpAmb>2</tpAmb><verAplic>AM4.00</verAplic><chNFe>13200832549086000100550010000003921063899890</chNFe><dhRecbto>2020-08-14T17:01:33-04:00</dhRecbto><cStat>600</cStat><xMotivo>Rejei��o: CSOSN incompat�vel na opera��o com N�o Contribuinte [nItem: 1]</xMotivo></infProt></protNFe></retConsReciNFe>`

**Comment by marcosgerene** [comment]
@bruno-crr 
O problema que você está tendo é com encoding. Eu sofro(ia) muito com isso no SAT, na NFe nunca tive esse problema.

Poste o trecho do código aonde você recebe esse xml (pelo que entendi é a rotina de consultar recibo) para que possamos analisar melhor, provavelmente isso tenha que ser melhorado internamente na biblioteca.

**Comment by bruno-crr** [comment]
Código para consulta o recibo:

                `RetornoNFeRetAutorizacao` retornoRecibo = null;

                for (var i = 0; i < tentativas; i++)
                {
                    retornoRecibo = _servicoNFe.NFeRetAutorizacao(numRecibo.Retorno.infRec.nRec); 
                    if (retornoRecibo.Retorno.protNFe.Count > 0)
                        break;

                    await Task.Delay(1000);
                }

                return retornoRecibo;`

**Comment by bruno-crr** [comment]
e no final eu gravo:

                     ` var novoaArquivo = $@"C:\NFe\LogWs\{chave}-retConsReciNFe.xml";

                      FuncoesXml.ClasseParaArquivoXml(retornoRecibo .Retorno, novoaArquivo);`

**Comment by marcosgerene** [comment]
@bruno-crr 

Coloque um breakpoint nesta linha e veja por favor se o retorno está vindo com acentuação correta.
```
FuncoesXml.ClasseParaArquivoXml(retornoRecibo.Retorno, novoaArquivo);
```

Se tiver, então o problema está na função ```ClasseParaArquivoXml```. Se não tiver, ai o buraco é mais em baixo.

---

Vamos tentar algo diferente, altere essa linha
```
FuncoesXml.ClasseParaArquivoXml(retornoRecibo.Retorno, novoaArquivo);
```

Assim:
```
string xml = FuncoesXml.ClasseParaXmlString(retornoRecibo.Retorno);
File.WriteAllText(arquivo, xml, Encoding.UTF8);
```

A ideia aqui é usar UTF-8 para gravar o arquivo texto, se der certo, ai a gente melhora esse código, se necessário.

**Comment by bruno-crr** [comment]
A imagem do print o erro já vem no xml de retorno, apliquei o que me pediu
 
`string xml = FuncoesXml.ClasseParaXmlString(retornoRecibo.Retorno);

File.WriteAllText(arquivo, xml, Encoding.UTF8);`

mas não funcionou, gravei o xml aplicando o Econding.UTF8 , e erro persistiu.

![erroenconding](https://user-images.githubusercontent.com/52460702/90431550-36112c00-e097-11ea-9ae3-885458c04087.png)

**Comment by marcosgerene** [comment]
@bruno-crr 

O seu print mostra que o problema vem antes de persistir em disco, o que citei acima não funciona mesmo.

Vou dar uma olhada nesse código e tentar te ajudar de alguma forma.

**Comment by bruno-crr** [comment]
Ok, 
o erro vem pelo objeto retornado pelo método de consulta recibo da biblioteca, antes de realmente gravar em disco, 
o curioso é que em outras rejeições que testei não acontece, apenas nessa rejeição até o momento cstat 600.

Obrigado pela ajuda até aqui!

**Comment by marcosgerene** [comment]
@bruno-crr 

Peguei o seu recibo (130000156261467) e consultei usando o Demo (vou até publicar a alteração no demo com o botão de consultar recibo para testes).

Esta foi minha resposta:
```
<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><nRec>130000156261467</nRec><cStat>248</cStat><xMotivo>Rejeição: UF do Recibo diverge da UF autorizadora</xMotivo><cUF>35</cUF><dhRecbto>2020-08-17T15:56:11-03:00</dhRecbto></retConsReciNFe>
```

![image](https://user-images.githubusercontent.com/15945003/90433630-8772e880-e0a2-11ea-84e2-b47919f4bf76.png)

Por favor, compile a versão mais atual, referencie a mesma e teste, veja se o problema é sanado.
Inclusive, faça o teste com o demo (vou linkar o commit aqui).

**Comment by bruno-crr** [comment]
mas deu o erro, pq o UF de emissao da nota é AM vc precisa colocar o aplicativo demo para a UF do Amazonas.

**Comment by marcosgerene** [comment]
@bruno-crr 
Subi o demo, realmente, eu coloquei SP. Vou fazer o teste que você disse.

---

Infelizmente não consigo fazer o teste porque não tenho o certificado do emitente. Por favor, faça o teste pelo demo e poste o resultado.

**Comment by bruno-crr** [comment]
Segue o erro dentro do app demo

![recibo pelo app demo](https://user-images.githubusercontent.com/52460702/90434394-54792680-e09b-11ea-9d34-0af658d86e18.png)

**Comment by marcosgerene** [comment]
@bruno-crr 
Já existia o botão de consulta de recibo e eu não vi... acabei duplicando ele =X

De qualquer forma, a unica forma de eu tentar te ajudar é com seu certificado, não consigo simular o problema.

Vou deixar para o @robertorp ou o @danilobreda ver se alguém tem uma ideia melhor.

**Comment by bruno-crr** [comment]
Pra simula o erro, basta apenas usar o csosn 203 em uma NFe para cliente definido como não contribuitne(consumidor final)

**Comment by danilobreda** [comment]
@bruno-crr  aqui em SP o erro vem normal, será que o problema está na parte do SEFAZ do AM ?

**Comment by marcosgerene** [comment]
@bruno-crr 
Não tenho certificados AM. O problema não ocorre em SP.

**Comment by bruno-crr** [comment]
entendi, então o problema provavelmente está na Sefaz do Amazonas que retorna o xml dessa rejeição com enconding errado?

**Comment by marcosgerene** [comment]
Acredito que sim,mas não consigo validar

**Comment by bruno-crr** [comment]
eu entendo, obrigado pela ajuda até aqui, por hora eu adicionei um replace desse cararcter qndo trato o xml de retorno rejeitado, mas se alguém que usa o projeto tiver como verificar posteriormente para casos futuros.

**Comment by marcosgerene** [comment]
@bruno-crr 

Vou fechar a issue, se tiver novidades sobre o assunto, por favor, reabra
