### ISSUE TITLE
Erro no Endereçador para a UF PA

### ISSUE THREAD

**Issue by reislanes** [ZeusAutomacao/DFe.NET#1154]
O endereçador do Zeus está retornando as urls incorretas para o estado do Pará. Desde o dia 2 de setembro de 2019 que o estado passou a adotar o SEFAZ Virtual do Rio Grande do Sul (SVRS) para emissão de NFe. Entretanto o endereçador continua enviando para os webservices antigos.
Esta é a resposta exibida no programa de teste da Nfe:
<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SVRS201809041041</verAplic><nRec>315200024951186</nRec><cStat>410</cStat><xMotivo>Rejeicao: UF informada no campo cUF nao e atendida pelo Web Service</xMotivo><cUF>31</cUF></retConsReciNFe>

**Comment by marcosgerene** [comment]
@reislanes qual versão você está usando ?

O problema foi solucionado em: https://github.com/ZeusAutomacao/DFe.NET/issues/1025

O commit: https://github.com/ZeusAutomacao/DFe.NET/commit/12503b3cbfec1e6a1991056bdc4f7d9850e133e7

**Comment by adrbarros** [comment]
Uso no Para sem problemas

**Comment by marcosgerene** [comment]
Estou fechando a issue por falta de retorno.

Por favor, atualize suas referencias e tente novamente.

Se julgar necessárii, reabra a issue.
