### ISSUE TITLE
Dúvida Impressão

### ISSUE THREAD

**Issue by pauloamorim2006** [ZeusAutomacao/DFe.NET#1156]
Bom dia!

Estou criando uma API no Asp Net Core 3.1. Referenciei todas as dependências do Zeus em meu projeto, inclusive adicionei o fastreport, conforme o NFe.Danfe.AppTeste.NetCore.

Porém no método ExportarPdf() da classe NFe.Danfe.Fast.Standard.DanfeBase na linha Relatorio.Prepare(); está voltando o seguinte erro ao preparar o relatório:

Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado.

Utilizei o mesmo fonte que está no exemplo para chamar:

	string xml = Funcoes.BuscarArquivoXml(nomeArquivoXml);
	using (MemoryStream stream = new MemoryStream()) // Create a stream for the report
	{
		try
		{
			var report = GeraClasseDanfeFrNFe(xml);
			byte[] bytes = report.ExportarPdf(); //<====== Ocorre aqui o erro
			Funcoes.SalvaArquivoGerado(nomeArquivoPdf, bytes);

			return new ArquivoImpressao { ArquivoPDF = nomeArquivoPdf, ArquivoXML = nomeArquivoXml };                       
		}
		catch (Exception ex)
		{
			throw new Exception($"Erro ao gerar o PDF: {ex.Message}");
		}
	}		
	
Eu tenho que fazer algum procedimento para que não dê esse erro? Existe algum problema em utilizar o Asp Net Core 3.1 com a impressão do Fast?

Acredito que ele esteja usando essa referência System.Windows.Forms em algum lugar. Eu tenho que fazer algum procedimento para carregar as dependências?

Muito obrigado!

**Comment by danilobreda** [comment]
Tente utilizar os nugets do fastreport na mesma versão que esta no projeto do Zeus:   

```
 <PackageReference Include="FastReport.OpenSource" Version="2019.3.19" />
 <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2019.3.19" />
```
Veja se o problema é solucionado... algumas versões do fast o pessoal lança com muitos bugs ! :/

**Comment by pauloamorim2006** [comment]
Certinho. Estava com a última versão do Fast. Muito obrigado, @danilobreda!

**Comment by denernun** [comment]
Aproveitando o gancho...instalei o pacote agora via nuget, antes estava
usando as referências direto no projeto:

<PackageReference Include="Zeus.Net.NFe.NFCe" Version="1.0.1.1031" />

Mas agora está dando erro nessas referências, o resto está tudo ok:

using NFe.Danfe.Base;
using NFe.Danfe.Base.NFe;
using NFe.Danfe.Fast.Standard.NFe;

Como resolvo isso ?

Obrigado !

**Comment by pauloamorim2006** [comment]
@denernun , infelizmente eu não utilizo pelo nuget.

Adiciono os projetos na minha solution (debugar o fonte caso for preciso):

![image](https://user-images.githubusercontent.com/13454233/90690061-70b9c680-e247-11ea-8183-a0db905b53c1.png)

**Comment by denernun** [comment]
Eu também faço assim, só queria ver como ficava do outro jeito...sem
problemas.

Valeu pelo retorno!

**Comment by pauloamorim2006** [comment]
Muito obrigado pela ajuda!

**Comment by danilobreda** [comment]
@denernun ainda não temos o nuget do projeto do DANFE, eu pedi a criação pro pessoal na issue #1047 ! da uma força lá 👍
