### ISSUE TITLE
Error CS0103: O nome 'cteProc' não existe no contexto atual

### ISSUE THREAD

**Issue by ryanlucaslemos** [ZeusAutomacao/DFe.NET#1157]
Utilizamos o Zeus para geração dos pdfs, porém na impressão de alguns ctes é exibido essa mensagem:
> (Text181): Error CS0103: O nome 'cteProc' não existe no contexto atual
> (Text182): Error CS0103: O nome 'cteProc' não existe no contexto atual
> (Text184): Error CS0103: O nome 'cteProc' não existe no contexto atual

Olhei no CTeRetrato.frx, parece ser algo relacionado ao modal Rodoviário. Porém não compreendo o funcionamento do FastReport para desenvolver uma correção.

**Comment by marcosgerene** [comment]
@ryanlucaslemos 

Poste seu xml, vou testar aqui.

**Comment by ryanlucaslemos** [comment]
@marcosgerene segue:

`<cteProc versao="3.00" xmlns="http://www.portalfiscal.inf.br/cte"><CTe xmlns="http://www.portalfiscal.inf.br/cte"><infCte Id="CTe42200709296295001646570030003120701595755631" versao="3.00"><ide><cUF>42</cUF><cCT>59575563</cCT><CFOP>5353</CFOP><natOp>PRESTACAO DE SERVICO AEREO</natOp><mod>57</mod><serie>3</serie><nCT>312070</nCT><dhEmi>2020-07-09T12:28:14-03:00</dhEmi><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>1</tpAmb><tpCTe>0</tpCTe><procEmi>0</procEmi><verProc>NDDigital CTe 4.8.3</verProc><cMunEnv>4202404</cMunEnv><xMunEnv>BLUMENAU</xMunEnv><UFEnv>SC</UFEnv><modal>02</modal><tpServ>0</tpServ><cMunIni>4202404</cMunIni><xMunIni>BLUMENAU</xMunIni><UFIni>SC</UFIni><cMunFim>4211306</cMunFim><xMunFim>NAVEGANTES</xMunFim><UFFim>SC</UFFim><retira>1</retira><xDetRetira>ROD BR 470SNSAO DOMINGOSNAVEGANTESSC88370888</xDetRetira><indIEToma>1</indIEToma><toma3><toma>0</toma></toma3></ide><compl><Entrega><comData><tpPer>1</tpPer><dProg>2020-07-14</dProg></comData><semHora><tpHor>0</tpHor></semHora></Entrega><xObs>Base Legal:[Bases com IE centralizada - Dispositivo Legal - Ajuste SINIEF n. 10/89 |Sujeito a ICMS Anexo 2, Art. 51 do RICMS-SC/01 ]  Produto:[ECOMM_CORP] OR:[BNU01] DE:[NVT] Pagto:[ PX - FRETE PAGO EM CONTA CORRENTE];  SHC:[NOR-CARGA NORMAL]</xObs></compl><emit><CNPJ>09296295001646</CNPJ><IE>255809930</IE><xNome>AZUL LINHAS AEREAS BRASILEIRAS SA</xNome><enderEmit><xLgr>V TR VP</xLgr><nro>3</nro><xBairro>CARIANOS</xBairro><cMun>4205407</cMun><xMun>FLORIANOPOLIS</xMun><CEP>88047902</CEP><UF>SC</UF></enderEmit></emit><rem><CNPJ>07432517001847</CNPJ><IE>257477446</IE><xNome>SIMPRESS COMERCIO LOCACAO E SERVICOS LTDA</xNome><fone>04773349963</fone><enderReme><xLgr>R JOSE PEREIRA LIBERATO</xLgr><nro>525</nro><xBairro>S JOAO</xBairro><cMun>4208203</cMun><xMun>ITAJAI</xMun><CEP>88304401</CEP><UF>SC</UF><cPais>1058</cPais><xPais>Brasil</xPais></enderReme></rem><dest><CNPJ>46377727001670</CNPJ><IE>255988656</IE><xNome>CAEDU COMERCIO VAREJISTA DE ARTIGOS DO VESTUARIO SA</xNome><fone>01113738230</fone><enderDest><xLgr>ROD BR 470</xLgr><nro>SN</nro><xBairro>SAO DOMINGOS</xBairro><cMun>4211306</cMun><xMun>NAVEGANTES</xMun><CEP>88370888</CEP><UF>SC</UF><cPais>1058</cPais><xPais>Brasil</xPais></enderDest></dest><vPrest><vTPrest>18.60</vTPrest><vRec>18.60</vRec><Comp><xNome>BC/TAXA EMISSAO</xNome><vComp>1.00</vComp></Comp><Comp><xNome>FRETE</xNome><vComp>12.56</vComp></Comp><Comp><xNome>IN/AD-VALOREM_</xNome><vComp>1.21</vComp></Comp><Comp><xNome>KA/CAPATAZIA</xNome><vComp>0.13</vComp></Comp><Comp><xNome>SU/COLETA ESPE</xNome><vComp>3.70</vComp></Comp></vPrest><imp><ICMS><ICMS00><CST>00</CST><vBC>18.60</vBC><pICMS>12.00</pICMS><vICMS>2.23</vICMS></ICMS00></ICMS></imp><infCTeNorm><infCarga><vCarga>183.76</vCarga><proPred>CARTUCHO</proPred><xOutCat>NORMAL</xOutCat><infQ><cUnid>00</cUnid><tpMed>CUBAGEM</tpMed><qCarga>0.0000</qCarga></infQ><infQ><cUnid>01</cUnid><tpMed>PESO CUBADO</tpMed><qCarga>0.2500</qCarga></infQ><infQ><cUnid>01</cUnid><tpMed>PESO REAL</tpMed><qCarga>2.4000</qCarga></infQ><infQ><cUnid>01</cUnid><tpMed>PESO TAXADO</tpMed><qCarga>2.5000</qCarga></infQ><infQ><cUnid>03</cUnid><tpMed>VOLUMES</tpMed><qCarga>1</qCarga></infQ></infCarga><infDoc><infNFe><chave>42200707432517001847550030002886091000236372</chave></infNFe></infDoc><infModal versaoModal="3.00"><aereo><nOCA>57759575563</nOCA><dPrevAereo>2020-07-14</dPrevAereo><natCarga><xDime>40X5X1</xDime></natCarga><tarifa><CL>G</CL><vTar>12.56</vTar></tarifa></aereo></infModal></infCTeNorm><autXML><CNPJ>07947821000189</CNPJ></autXML></infCte><infCTeSupl><qrCodCTe>https://dfe-portal.svrs.rs.gov.br/cte/qrCode?chCTe=42200709296295001646570030003120701595755631&amp;tpAmb=1</qrCodCTe></infCTeSupl><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#CTe42200709296295001646570030003120701595755631"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>rnenEKLgFQSar6uqRbj/so6qa4U=</DigestValue></Reference></SignedInfo><SignatureValue>NUqzOODFMyeOk4Z9X1sGZyMqgn+OooWkHzUttt2FGvrtZXeKDz+ZLHPRO7Og+UVY0eRAyOlf/wAOtNmEjf4XXvzgN5yCQB6qIv34DcKUFlj7FyH4FaQUBoburg9OD4kIOdjhVaEYMXxpqTIc6wcx7auJ4OWNhMeFnJrjGnxI27atMQgV8TCagS6FAoFLrz9BmwETTEufUeCCUzg39xdT8gLBidLUtWS6vWTD41gzRTsWpLn0fCr4Uc4p9XvGd2fXTB82ze7gWxHzfYwfH+g7MxrtwNgOPqdMWrfWWsKo+7uv62hZSXNsCyIl9p1XtuUnBkEEzs0lff3lPqW7tRSbEQ==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHszCCBZugAwIBAgIIZg+Cg6+KmecwDQYJKoZIhvcNAQELBQAwTDELMAkGA1UEBhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxKDAmBgNVBAMMH1NFUkFTQSBDZXJ0aWZpY2Fkb3JhIERpZ2l0YWwgdjUwHhcNMTkwNzI1MTcxMzAwWhcNMjAwNzI0MTcxMzAwWjCCAQUxCzAJBgNVBAYTAkJSMRMwEQYDVQQKDApJQ1AtQnJhc2lsMRQwEgYDVQQLDAsoRU0gQlJBTkNPKTEYMBYGA1UECwwPMDAwMDAxMDA5MTY0MzQ2MRQwEgYDVQQLDAsoRU0gQlJBTkNPKTEUMBIGA1UECwwLKEVNIEJSQU5DTykxKDAmBgNVBAsMH1NFUkFTQSBDZXJ0aWZpY2Fkb3JhIERpZ2l0YWwgdjUxFzAVBgNVBAsMDjYyMTczNjIwMDAwMTgwMRQwEgYDVQQLDAsoRU0gQlJBTkNPKTEsMCoGA1UEAwwjQVpVTCBMSU5IQVMgQUVSRUFTIEJSQVNJTEVJUkFTIFMuQS4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQClpzuqptKWEvQv+BnLGihGdQ6Bll3DDNYgqh++anTlCZ1l0Byq7CcUlyS6dmgD2mt/qAAJIvElO/KCaidTUdYyb0z+Amu5sOXYnRiiWN/r2AAcvLeLTAmO1kN1EUQ2vBS+b8DTa5lD7OPmuB3UtTxgHxKTSnrBVuMSMDzy5pbVztIux1Vnd4qNodc1Zo8rVOHcotvdT9FbzE4hxJp4txrarfNo2iGyNjDqgJlFavSliqHp7CeP6r5n9gACbX6XNwhGKVucxdm18MVo+lIwzRtDhp/jYF5AHBtQ4lo+rmXszM7FdsSAtuCX/SX8eHb95KhGyZLVMkVp1hRPk1o6Pl6LAgMBAAGjggLcMIIC2DAfBgNVHSMEGDAWgBRWda9Kc7LYCMR9+2woHBHV98GozDCBlwYIKwYBBQUHAQEEgYowgYcwRwYIKwYBBQUHMAKGO2h0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9jYWRlaWFzL3NlcmFzYWNkdjUucDdiMDwGCCsGAQUFBzABhjBodHRwOi8vb2NzcC5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3NlcmFzYWNkdjUwgbsGA1UdEQSBszCBsIEZVFJJQlVUQVJJT0BWT0VBWlVMLkNPTS5CUqA+BgVgTAEDBKA1EzMyNjA0MTk4NDMyNTY5MTg0ODQ1MDAwMDAwMDAwMDAwMDAwMDAwMzI4MjMzOTBTU1AgU1CgHwYFYEwBAwKgFhMUVEhBSVMgVklFSVJBIEhBQkVSTEmgGQYFYEwBAwOgEBMOMDkyOTYyOTUwMDAxNjCgFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMHEGA1UdIARqMGgwZgYGYEwBAgEGMFwwWgYIKwYBBQUHAgEWTmh0dHA6Ly9wdWJsaWNhY2FvLmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL2RlY2xhcmFjYW8tc2NkLnBkZjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgZsGA1UdHwSBkzCBkDBJoEegRYZDaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FjZHY1LmNybDBDoEGgP4Y9aHR0cDovL2xjci5jZXJ0aWZpY2Fkb3MuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FjZHY1LmNybDAdBgNVHQ4EFgQUofU79POXqxQCQVmFsrVWZgUzIeIwDgYDVR0PAQH/BAQDAgXgMA0GCSqGSIb3DQEBCwUAA4ICAQCsdI/G2Bi2g61IXQ7GGKbtD8pbCddNsEgCEKebU6jp4h8+gUx/mQEF/h7PrXm/ZO0zeNEh5fWVuDATWtw4D4lrp80gBcyIeYuO6a7f/MB8ymXBdSyDdTLnuZdIGk9RTuaCbQpZy5Q6Fa/8KaEVeQjhV0sAle6Q1R+mUa4R/GVhW7yWooK9U5pWN+tbU739NRXhPBz8WXRSdQ8tA3NI1lK5VAMwfm/qPocjrHuJmnjyOxcSRyOYgR6oMkdF+5Oi1IRNlgKXpl1MwT01LNUnxED9gpvhsK27Sxa0xJiFrDxQPqHs5GBCsvc3ATaxgjf2YdesPkFaPJxlzPf+srWXQamk/eKDsow4vdeBiwb1vJ/6/XAoijS2WgIX9GkmgG4jLyuW4q5kDQ5e5XKFw4ifLhTZmQwzQedaeF5kCzOm8DGrxDGg7S0P8UxaYqhNHY7G7XWupjhyT9IDLJS11rcSyBxUBXlHCl4TyS+43lyTg3Uu21KJbGA+S6s0ph/TiBcBv0Udu1Xh5DTVd3TNLDur97+QUm5EHM5mUaWVJxcjVjwAGA5W18s7yhAVyqx9PVzpxrosDxa/nbQO1AWZRWc+0I+eXYGXbB0poWCWgNAy1LjSmjMFuthO9wmkFd1glpTiD2GkmiyJoToSx8My0atP26flRMqMiw1Yn2RNDRjQTIlTJA==</X509Certificate></X509Data></KeyInfo></Signature></CTe><protCTe versao="3.00" xmlns="http://www.portalfiscal.inf.br/cte"><infProt Id="CTe342200082070635"><tpAmb>1</tpAmb><verAplic>RS20200625174630</verAplic><chCTe>42200709296295001646570030003120701595755631</chCTe><dhRecbto>2020-07-09T12:28:17-03:00</dhRecbto><nProt>342200082070635</nProt><digVal>rnenEKLgFQSar6uqRbj/so6qa4U=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso do CT-e</xMotivo></infProt></protCTe></cteProc>`

**Comment by marcosgerene** [comment]
Modal aéreo não é atendido... mas pelo pouco que vi do se xml é bem simples de fazer...

**Comment by ryanlucaslemos** [comment]
Está ocorrendo também em multi modal. Há uma forma, de não exibir essas informações específicas dos modais que ainda não são atendidos? Assim o PDF seria gerado sem essa informação. Ou quebraria do mesmo jeito?

**Comment by marcosgerene** [comment]
>Modal aéreo não é atendido... mas pelo pouco que vi do se xml é bem simples de fazer...

Testa aqui, implementei rapidamente o modal rodoviário, ainda falta a questão de produtos perigosos pela ONU, mas para seu xml é o suficiente.
[Arquivo removido]

> Está ocorrendo também em multi modal. Há uma forma, de não exibir essas informações específicas dos modais que ainda não são atendidos? Assim o PDF seria gerado sem essa informação. Ou quebraria do mesmo jeito?

Na arquivo que te mandei já faz isso, não quebra para modais diferentes.

---

Edit:
Fiz uma correção e adicionei a tag de itens perigosos, agora o CTe atende rodoviário e aéreo.
[CteRetrato.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5132300/CteRetrato.zip)

**Comment by ryanlucaslemos** [comment]
O primeiro xml passou. Porém testei com dois multimodais e apresenta esse erro:

![image](https://user-images.githubusercontent.com/42043408/91344158-f1327700-e7b3-11ea-9943-12bc748afb5c.png)

Segue um dos xmls que ocorreu esse erro:

`
<cteProc xmlns="http://www.portalfiscal.inf.br/cte" versao="3.00">
  <CTe xmlns="http://www.portalfiscal.inf.br/cte">
    <infCte Id="CTe51200813574672000748570010000414941000598752" versao="3.00">
      <ide>
        <cUF>51</cUF>
        <cCT>00059875</cCT>
        <CFOP>6353</CFOP>
        <natOp>Prest. Serv. Estabelecimento Comercial</natOp>
        <mod>57</mod>
        <serie>1</serie>
        <nCT>41494</nCT>
        <dhEmi>2020-08-21T09:19:38-03:00</dhEmi>
        <tpImp>1</tpImp>
        <tpEmis>1</tpEmis>
        <cDV>2</cDV>
        <tpAmb>1</tpAmb>
        <tpCTe>0</tpCTe>
        <procEmi>0</procEmi>
        <verProc>KMM CT-e - 1.104.1</verProc>
        <cMunEnv>5107925</cMunEnv>
        <xMunEnv>Sorriso</xMunEnv>
        <UFEnv>MT</UFEnv>
        <modal>06</modal>
        <tpServ>0</tpServ>
        <cMunIni>5105580</cMunIni>
        <xMunIni>Marcelandia</xMunIni>
        <UFIni>MT</UFIni>
        <cMunFim>1501303</cMunFim>
        <xMunFim>Barcarena</xMunFim>
        <UFFim>PA</UFFim>
        <retira>1</retira>
        <indIEToma>1</indIEToma>
        <toma3>
          <toma>0</toma>
        </toma3>
      </ide>
      <compl>
        <xEmi>EVIZENTIM</xEmi>
        <xObs>CPNDI No: 0022075717 MERCADORIA COM DESTINO A EXPORTACAO - IMPOSTOS SUSPENSOS E/OU BENEFICIOS INTERNOS  Usuario: EVIZENTIM Data emissao: 21/08/2020 08:19 Operacao: 8257; Lote No 1364 /   - MERCADORIA PARA FORMACAO DE LOTE PARA POSTERIOR EXPORTACAO - Isencao do ICMS conforme RICMS/MT, artigo 5o, inciso II e  9 e 10</xObs>
      </compl>
      <emit>
        <CNPJ>13574672000748</CNPJ>
        <IE>137450869</IE>
        <xNome>HIDROVIAS DO BRASIL - VILA DO CONDE S.A.</xNome>
        <xFant>HIDROVIAS DO BRASIL - VILA DO CONDE S.A.</xFant>
        <enderEmit>
          <xLgr>R GENESIO ROBERTO BAGGIO</xLgr>
          <nro>1111</nro>
          <xBairro>CENTRO</xBairro>
          <cMun>5107925</cMun>
          <xMun>Sorriso</xMun>
          <CEP>78890000</CEP>
          <UF>MT</UF>
          <fone>6635444867</fone>
        </enderEmit>
      </emit>
      <rem>
        <CNPJ>04409153000733</CNPJ>
        <IE>137557698</IE>
        <xNome>COPAGRI - COMERCIAL PARANAENSE AGRICOLA LTDA</xNome>
        <xFant>COPAGRI</xFant>
        <fone>6533589938</fone>
        <enderReme>
          <xLgr>AV DOUTOR HELIO RIBEIRO</xLgr>
          <nro>487</nro>
          <xBairro>RESIDENCIAL PAIAGUAS</xBairro>
          <cMun>5103403</cMun>
          <xMun>Cuiaba</xMun>
          <CEP>78048250</CEP>
          <UF>MT</UF>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
        </enderReme>
      </rem>
      <exped>
        <CNPJ>17211227000189</CNPJ>
        <IE>136328407</IE>
        <xNome>NAZARE AGROPECUARIA LTDA</xNome>
        <fone>6635319101</fone>
        <enderExped>
          <xLgr>ESTRADA RURAL</xLgr>
          <nro>S/N</nro>
          <xCpl>FAZENDA NAZARE</xCpl>
          <xBairro>ZONA RURAL</xBairro>
          <cMun>5105580</cMun>
          <xMun>Marcelandia</xMun>
          <CEP>78535000</CEP>
          <UF>MT</UF>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
        </enderExped>
      </exped>
      <receb>
        <CNPJ>13574672000152</CNPJ>
        <IE>155315692</IE>
        <xNome>HIDROVIAS DO BRASIL - VILA DO CONDE S.A</xNome>
        <fone>1139056027</fone>
        <enderReceb>
          <xLgr>AVENIDA VERDE E BRANCO</xLgr>
          <nro>S/N</nro>
          <xBairro>ITUPANEMA</xBairro>
          <cMun>1501303</cMun>
          <xMun>Barcarena</xMun>
          <CEP>68445000</CEP>
          <UF>PA</UF>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
        </enderReceb>
      </receb>
      <dest>
        <CNPJ>04409153000733</CNPJ>
        <IE>137557698</IE>
        <xNome>COPAGRI - COMERCIAL PARANAENSE AGRICOLA LTDA</xNome>
        <fone>6533589938</fone>
        <enderDest>
          <xLgr>AV DOUTOR HELIO RIBEIRO</xLgr>
          <nro>487</nro>
          <xBairro>RESIDENCIAL PAIAGUAS</xBairro>
          <cMun>5103403</cMun>
          <xMun>Cuiaba</xMun>
          <CEP>78048250</CEP>
          <UF>MT</UF>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
        </enderDest>
      </dest>
      <vPrest>
        <vTPrest>12273.75</vTPrest>
        <vRec>12273.75</vRec>
        <Comp>
          <xNome>Frete Peso</xNome>
          <vComp>248.91</vComp>
        </Comp>
      </vPrest>
      <imp>
        <ICMS>
          <ICMS45>
            <CST>40</CST>
          </ICMS45>
        </ICMS>
      </imp>
      <infCTeNorm>
        <infCarga>
          <vCarga>33695.17</vCarga>
          <proPred>MILHO</proPred>
          <xOutCat>GRANEL</xOutCat>
          <infQ>
            <cUnid>01</cUnid>
            <tpMed>PESO REAL</tpMed>
            <qCarga>49310.0000</qCarga>
          </infQ>
          <infQ>
            <cUnid>01</cUnid>
            <tpMed>PESO COBRADO</tpMed>
            <qCarga>49310.0000</qCarga>
          </infQ>
          <infQ>
            <cUnid>03</cUnid>
            <tpMed>QUANTIDADE</tpMed>
            <qCarga>0.0000</qCarga>
          </infQ>
          <infQ>
            <cUnid>00</cUnid>
            <tpMed>CUBAGEM (M3)</tpMed>
            <qCarga>0.0000</qCarga>
          </infQ>
          <vCargaAverb>33695.17</vCargaAverb>
        </infCarga>
        <infDoc>
          <infNFe>
            <chave>51200804409153000733550010000057461000056188</chave>
          </infNFe>
        </infDoc>
        <infModal versaoModal="3.00">
          <multimodal>
            <COTM>0986-0519</COTM>
            <indNegociavel>0</indNegociavel>
            <seg>
              <infSeg>
                <xSeg>AIG SEGUROS BRASIL S.A</xSeg>
                <CNPJ>33040981000150</CNPJ>
              </infSeg>
              <nApol>87372018010654000627</nApol>
              <nAver>99999</nAver>
            </seg>
          </multimodal>
        </infModal>
      </infCTeNorm>
      <autXML>
        <CNPJ>02355037000168</CNPJ>
      </autXML>
      <infRespTec>
        <CNPJ>02355037000168</CNPJ>
        <xContato>Leopoldo Suarez</xContato>
        <email>kmm@kmm.com.br</email>
        <fone>554230263000</fone>
      </infRespTec>
    </infCte>
    <infCTeSupl>
      <qrCodCTe><![CDATA[https://www.sefaz.mt.gov.br/cte/qrcode?chCTe=51200813574672000748570010000414941000598752&tpAmb=1]]></qrCodCTe>
    </infCTeSupl>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
      <SignedInfo>
        <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
        <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
        <Reference URI="#CTe51200813574672000748570010000414941000598752">
          <Transforms>
            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
          </Transforms>
          <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
          <DigestValue>MKPyp0UxfFIjxF0lVM8Pn9QXmDA=</DigestValue>
        </Reference>
      </SignedInfo>
      <SignatureValue>SU0MynxtJNtpCzuHOsaYIVBWoYohTNDpkQQ8VPGNncYwaWGEuREIlUlc2LD/oGKoMMG2aG92luKF NBxCdu5AQzFXy62YW6Fbnpe/0qe74Bzl3K4GHs5VSucGhfsJKr1PiAqIrLJy9nQCpHiuCLguYbT3 CceI4TKM+qgktmy4A3hUmBzSbYaaASHeaIpJESMhPE38eimth86VydluZF+zngu7z08PQSg0z8fN 0XY1wOWHGOLbTf82n9w0PjvwVytt7ds5yq6WbqJqK1jhB/32H9JJ+Mrw/IkyJe/tLVI5PeJbnU0K JS74PFCpslMdRwlp85ZTStzy1XzLsA9w1xwmaA==</SignatureValue>
      <KeyInfo>
        <X509Data>
          <X509Certificate>MIIH4jCCBcqgAwIBAgIIDGxy8IFDf5owDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCQlIxEzAR
BgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFs
IGRvIEJyYXNpbCAtIFJGQjEYMBYGA1UEAxMPQUMgVkFMSUQgUkZCIHY1MB4XDTE5MTEyNzE3NDQw
OFoXDTIwMTEyNjE3NDQwOFowggEGMQswCQYDVQQGEwJCUjELMAkGA1UECBMCTVQxEDAOBgNVBAcT
B1NPUlJJU08xEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVj
ZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05QSiBBMTEbMBkG
A1UECxMSQVIgU1AgQ0VSVElGSUNBRE9TMRcwFQYDVQQLEw4yNTI2ODQyMjAwMDE3MzE9MDsGA1UE
AxM0SElEUk9WSUFTIERPIEJSQVNJTCBWSUxBIERPIENPTkRFIFMgQToxMzU3NDY3MjAwMDc0ODCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALVliEsV1RWEOUfHdDDEvu+lGJDq5FCOq/nw
ZmtX3SLdxqkE/UuVY4ZRzDVA5GCDzGjGk7LEeaBVnf/fLl/rO9Kd0w1U8+9DjS3RYUhBO0HIB/96
sxdqnwjcYviYJzQWUjQbJYhBIT35o50dwh+BwkvZ/NbIpU4SXVd9dXXujylakNe1f7kdeqTSOMOX
7VX7SREvnpuOkj9XjXUTfgaZaPXoZ1UgMYSIHkNtHByW+0Cbk3Voxb8+P6h4sz32q1/Xyq+Y9RiG
BCDLXDD+eatvpipBWZEKQSOyKECI0XZ5TXXPaxxPzlJ4ojsm8URhd80tRfm995U6KDRkzGvtDh6n
SPsCAwEAAaOCAuIwggLeMIGcBggrBgEFBQcBAQSBjzCBjDBVBggrBgEFBQcwAoZJaHR0cDovL2lj
cC1icmFzaWwudmFsaWRjZXJ0aWZpY2Fkb3JhLmNvbS5ici9hYy12YWxpZHJmYi9hYy12YWxpZHJm
YnY1LnA3YjAzBggrBgEFBQcwAYYnaHR0cDovL29jc3B2NS52YWxpZGNlcnRpZmljYWRvcmEuY29t
LmJyMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUU8ul5HVQmUAsvlsVRcm+yzCqicUwcAYDVR0gBGkw
ZzBlBgZgTAECASUwWzBZBggrBgEFBQcCARZNaHR0cDovL2ljcC1icmFzaWwudmFsaWRjZXJ0aWZp
Y2Fkb3JhLmNvbS5ici9hYy12YWxpZHJmYi9kcGMtYWMtdmFsaWRyZmJ2NS5wZGYwgbYGA1UdHwSB
rjCBqzBToFGgT4ZNaHR0cDovL2ljcC1icmFzaWwudmFsaWRjZXJ0aWZpY2Fkb3JhLmNvbS5ici9h
Yy12YWxpZHJmYi9sY3ItYWMtdmFsaWRyZmJ2NS5jcmwwVKBSoFCGTmh0dHA6Ly9pY3AtYnJhc2ls
Mi52YWxpZGNlcnRpZmljYWRvcmEuY29tLmJyL2FjLXZhbGlkcmZiL2xjci1hYy12YWxpZHJmYnY1
LmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIG2BgNV
HREEga4wgauBG2JydW5hLmRhbWFzY2Vub0BoYnNhLmNvbS5icqA4BgVgTAEDBKAvBC0wNzA4MTk3
MTA5NjA5NzAxODUwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgHgYFYEwBAwKgFQQTUkVORSBQ
SU5UTyBEQSBTSUxWQaAZBgVgTAEDA6AQBA4xMzU3NDY3MjAwMDc0OKAXBgVgTAEDB6AOBAwwMDAw
MDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBAGHIxtFOr9ulYEXf6CHgdbGNMf0A9SF43B5OCTgi
Sa1IFEz7IPJQDn5W8gON/CCJ5EkERr8e5yGjywMmmxHg6kWzrOvWsfnxKqTqbnjHrSJ4EzE4yY74
VdVLKphqJhOEqVtQZHsPR0gLWN4W06CaHnW3wa4GEbgYjQjBnfRkFRrYjyMkbzK4PMKx0nrum9eA
6CMJYPEyNPGiI8JXJX2YajKSVoc3LQ31v2R8oM2mfN+T9TAuksFbRffzlirgJyADwNSlbgyL7Cja
4kH9cCt3GpI+14BFPlzWg3tIdjwQ5ozWWUSL7f2K4gge3HiS1I5los0LYCzSvf9uNXxY2rGfrMoG
LmhWBQF91WmGX63B/j0HAbCaHZtqo+TWzHlE0i17Qf/vSGHwl76M87BQDpdUPtJ2D2iyIZ6PR3pW
qdmETwCx0DFts70Jx7R8xHFHa4SctZIAYn3ZlRoIOWQfzric3a6DGgahXnuvoT1ilCSKmRE2Himn
dL/axgrbjOcUHD/r9Ci7QVjy091zMVk4sem//zFP2rWslnvVCJH9BVK5zl2lxQG/r8SnFqL/okSB
lRqZrESAv62cYPyEARUu8iLz+fPT9RTETmhpSB5w+y2WDN8mZ5C4dtdYbDlSLzbIlw6qj8KOv1su
Ew8rksiBpcL10vZRUv2TA7eI51/ItrRdbfbZ</X509Certificate>
        </X509Data>
      </KeyInfo>
    </Signature>
  </CTe>
  <protCTe versao="3.00">
    <infProt>
      <tpAmb>1</tpAmb>
      <verAplic>MT20200708016</verAplic>
      <chCTe>51200813574672000748570010000414941000598752</chCTe>
      <dhRecbto>2020-08-21T08:19:47-04:00</dhRecbto>
      <nProt>151200409152625</nProt>
      <digVal>MKPyp0UxfFIjxF0lVM8Pn9QXmDA=</digVal>
      <cStat>100</cStat>
      <xMotivo>Autorizado o Uso do CT-e</xMotivo>
    </infProt>
  </protCTe>
</cteProc>
`

**Comment by marcosgerene** [comment]
@ryanlucaslemos 

Eu acabei de atualizar o frx, teste novamente, por favor.

**Comment by ryanlucaslemos** [comment]
Testei, o erro mudou:
```
(Text256): Error CS0103: O nome 'cteProc' não existe no contexto atual
(Text257): Error CS0103: O nome 'cteProc' não existe no contexto atual
(Text258): Error CS0103: O nome 'cteProc' não existe no contexto atual
(Text259): Error CS0103: O nome 'cteProc' não existe no contexto atual
```

Tem algum material sobre o funcionamento do Fast Report ou como utilizam ele no Zeus? 
Posso contribuir e corrigir esses erros que eu for encontrando na geração de PDFs. Só preciso entender como funciona...

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/1158/commits/d39a2918133c25e52d02b16f316e7de55132a956

Tenta com esse:
[CteRetrato.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5132416/CteRetrato.zip)

**Comment by ryanlucaslemos** [comment]
Funcionou!!!! Legal!!
