### ISSUE TITLE
Adicionar dados do cartão de Crédito na detPag - card

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1159]
Ola pessoal hoje tive a necessidade de informar um pagamento para nfce como cartao de credito e retornou a rejeição 391 que e referente aos dados de cartão. 

//tPag Cartao Credito = 3
            if (cbmVenda.Text == "Cartão de Crédito")
            {
                // igual a versão 4 retorna isso
                var p4 = new List<pag>
            {
                //new pag {detPag = new detPag {tPag = FormaPagamento.fpDinheiro, vPag = valorPagto}},
                //new pag {detPag = new detPag {tPag = FormaPagamento.fpCheque, vPag = icmsTot.vNF - valorPagto}}
                new pag
                {
                    detPag = new List<detPag>
                    {
                        new detPag {tPag = FormaPagamento.fpCartaoCredito, vPag = valorPagto},
                    }
                }

            };
                return p4;
            }
Não estou conseguindo adicionar o card, tentei assim mas sem sucesso, peço a colaboraçãos dos amigos.
Code:
new detPag {tPag = FormaPagamento.fpCartaoCredito, vPag = valorPagto, card = TipoIntegracaoPagamento.TipNaoIntegrado},

Obrigado

**Comment by denernun** [comment]
Eu uso assim, espero que ajude.

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by sigridslima** [comment]
Dener as imagens nao apareceram para mim
[image: image.png]

**Comment by denernun** [comment]
Acho que agora dá certo:

            new detPag {tPag = FormaPagamento.fpCartaoCredito, vPag =
valorPagto, card = TipoIntegracaoPagamento.TipNaoIntegrado},

            new detPag
            {
                tPag = FormaPagamento.fpCartaoCredito,
                vPag = valorPagto,
                card = new card
                {
                    tpIntegra = TipoIntegracaoPagamento.TipNaoIntegrado
                }
            };

**Comment by sigridslima** [comment]
Ok amigo deu certo, muito obrigado

**Comment by danilobreda** [comment]
@sigridslima Qualquer outra dúvida só abrir outra issue! 👍
