### ISSUE TITLE
sat fiscal.. alguém

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#116]
estava lendo e pesquisando sobre o assunto e me deparei com isso 

http://t2ti.com/erp2/modulos/c/sat.php

esse curso do t2ti eles modificaram o Zeus para funcionar no SAT , 

se alguém tiver o curso e quiser compartilhar seria de grande ajuda =) (compartilhas os fontes do sat somente... o curso não)

**Comment by gercenio** [comment]
@robertorp  bom dia tudo bem, bom tenho um exemplo SAT, feito em C#, porem acabei de descobrir que o emulador não funciona, o mesmo tem diversos problemas de comunicação, porem ontem conversando com um amigo e possível usar a NFC-e tendo um SAT la como contingencia, porem apenas emitindo quando o webservice da receita esta no ar entendeu?

**Comment by adrbarros** [comment]
Bom dia, eu tenho uma implementação do SAT Fiscal achei bem interessante o projeto e gostaria de contribuir com o mesmo. É bem fácil de implementar, Obs.: o Emulador funciona sim tem que fazer alguns ajustes!!!

**Comment by gercenio** [comment]
Ola @adrbarros , bom dia gostaria de entender melhor sua solução de integração você poderia entrar em contato comigo por e-mail gercenio@gmail.com por favor?

**Comment by ipsolucoes** [comment]
Bom dia! Preciso implementar um projeto para emissão de cupom (sat) no c#, por onde começar? Posso utilizar a biblioteca Zeus? Tem algum exemplo?
Obrigado!

**Comment by robertorp** [comment]
https://github.com/ACBrNet/ACBr.Net.Sat
@ipsolucoes
