### ISSUE TITLE
Bug de Exibição do PDF para documentos com mais de uma página

### ISSUE THREAD

**Issue by ryanlucaslemos** [ZeusAutomacao/DFe.NET#1160]
Está acontecendo um bug. Quando uma NFe possui muitos produtos e consome a página toda, os dados adicionais estão sendo escritos em cima dos produtos:

![pdfBugado](https://user-images.githubusercontent.com/42043408/91976965-3bf24880-ecf8-11ea-8f65-7e75a413d67e.PNG)

**Comment by guidi** [comment]
@ryanlucaslemos se eu não me engano isso teria sido resolvido na #1127, está com a biblioteca atualizada?

**Comment by ryanlucaslemos** [comment]
Fiz o clone no projeto há uns dias atrás. Dia 24/08 para ser mais preciso. Mas de Fato estava utilizando uma dll mais antiga e não percebi. Obrigado. Vou fechar a issue.
