### ISSUE TITLE
Implementar o Responsável técnico (infRespTec)

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1163]
Ola amigos, estou com dificuldade em chamar meu método infRespTec.
Ja viz a atualização na minha classe, porem quando vou gerar essa nova tag nao consigo no xml.
Ex.
    var infRespTec = new List<infRespTec>
                {
                   new infRespTec {CNPJ = "_000000", xContato = "_contato", email = "_contato@hotmail.com", fone = "_contato"},
                };
Aguardo, obrigado.

**Comment by denernun** [comment]
Olá, veja se ajuda:

var infNFe = new infNFe
{
   infRespTec = new infRespTec
   {
       CNPJ = "",
       email = "",
       fone = "",
       xContato = ""
   }
};

**Comment by sigridslima** [comment]
Ola amigo boa noite, coloquei como me sugeri-o, mas agora deu erro de validação (Schema) e fiz outros metodo tbm deu erro de validação.
Tentei assim:
   protected virtual infRespTec GetResponsavel()
        {
            var respTec = new infRespTec()
            {
                CNPJ = "",
                xContato = "",
                email = "",
                fone = ""
            };
            return respTec;
        }

chamei assm

var infNFe = new infNFe
                {
                    versao = versao.VersaoServicoParaString(),
                    ide = GetIdentificacao(numero, modelo, versao),
                    emit = GetEmitente(),
                    dest = GetDestinatario(versao, modelo),
                    autXML = GetCnpjAutorizado(),
                    //aqui
                    infRespTec = GetResponsavel(),
                    //aqui
                    transp = GetTransporte()
                };

Aguardo

**Comment by danilobreda** [comment]
Se deu algum erro de validação quer dizer que tem alguma propriedade que você passou que esta da maneira incorreta ou com valor incorreto ou formato de valor incorreto que o SEFAZ determina.

Se você compartilhar o erro retornado na validação, a gente pode te ajudar, porem é algo que no debugging vc consegue descobrir sozinho, o erro fala o campo que está incorreto e o motivo.

**Comment by sigridslima** [comment]
Ola boa noite, entao esta informando que necessita informar os seguintes dados quando acrescento o codigo do amigo @denernun .
Erro: Lista de possiveis elementos esperados; exportar, compra, cana.
Print do erro.
http://eginformatica.net/error/error.png

**Comment by denernun** [comment]
Olá, aquele código que passei, foi só um exemplo de como deveria ser
informada a tag infRespTec, e não tem relação com essa mensagem de erro.

Essas outras validações que você passou, como a própria mensagem mostra,
são outras tags que, dependendo do tipo de nota que está emitindo, são
obrigatórias.

infNFe.exporta - representa informações de embarque, infNFe.compra -
representa informações de compra e assim por diante.

Esses erros são mais de "negócio", do que, erro "técnico".

Recomendo a leitura das Notas Técnicas, para poder entender melhor como
funciona essa amarração.

Qualquer coisa, estamos aí !

**Comment by danilobreda** [comment]
@sigridslima conseguiu resolver o problema?

**Comment by sigridslima** [comment]
Olá amigo, infelizmente ainda não, sempre q coloco o código citado acima, apresenta erro de esquema, seguir as normas técnica e comparei com um xml funcional e nada. Aqui na Bahia esse campo não está sendo obrigatório. Mas vou fazer mais um teste para vê. Obrigado até o momento.

**Comment by robertorp** [comment]
Me diz qual documento é ? MDF-e ? NFC-e ? NF-e ? etc..? Porque aqui uso normalmente

**Comment by sigridslima** [comment]
Nf-e

**Comment by robertorp** [comment]
![image](https://user-images.githubusercontent.com/10251705/93481348-d6e04a80-f8d4-11ea-901e-62ab9e9102a0.png)
eu informo assim é da certo, antes verifico se a UF exige, talvez seja somente seus schemas não? 

link dos schemas que utilizo hoje https://drive.google.com/open?id=1kDOYW0q7Nwu5KR9DlszSDKCRqPVwxbil

**Comment by sigridslima** [comment]
Aguardo confirmação para download. obrigado

**Comment by sigridslima** [comment]
Ola, ainda perciste o erro mesmo depois que atualizei os schemas que o roberto enviou.
http://eginformatica.net/error/error.png

Tentei fazer assim, mas sem sucesso:

protected virtual infRespTec GetResponsavel()
        {
            var respTec = new infRespTec()
            {
                CNPJ = "xx",
                xContato = "xx",
                email = "xx",
                fone = "xx"
            };
            return respTec;
        }

estou chamando assim:
protected virtual infNFe GetInf(int numero, ModeloDocumento modelo, VersaoServico versao)
{
 var infNFe = new infNFe
                {
                    versao = versao.VersaoServicoParaString(),
                    ide = GetIdentificacao(numero, modelo, versao),
                    emit = GetEmitente(),
                    dest = GetDestinatario(versao, modelo),
                    autXML = GetCnpjAutorizado(),                  
//aqui                   
 infRespTec = GetResponsavel(),
//aqui    
                    transp = GetTransporte()
                };
}

Aguardo algum ideia.

**Comment by robertorp** [comment]
que tipo de nf-e vc esta fazendo? aí deu erro no produto , detalhe do produto , diz que falta algo de algum tipo de produto especifico ou vc adicionou um produto especifico e não adicionou alguma coisa , cana , cobustivel etc..

**Comment by danilobreda** [comment]
@sigridslima conseguiu resolver o problema?

**Comment by danilobreda** [comment]
Estou fechando a issue por falta de feedback, qualquer coisa só criar outra issue 👍
