### ISSUE TITLE
Alterar dhRecbto para DateTimeOffset

### ISSUE THREAD

**Issue by CarlosAurelioMRF** [ZeusAutomacao/DFe.NET#1164]
Ao exemplo do documento fiscal 51200929618103000100550010000084931422771334 o campo dhRecbto está -04:00 mas está sendo convertido padrão -03:00.

**Comment by marcosgerene** [comment]
@CarlosAurelioMRF 
Posta o XML, por favor, a partir dele posso tentar entender melhor o problema.

**Comment by CarlosAurelioMRF** [comment]
@marcosgerene segue o arquivo:

https://drive.google.com/file/d/1lp7Y9ziQ3L50hg_klm4KCbJO8dS3wSV_/view?usp=sharing

**Comment by marcosgerene** [comment]
@CarlosAurelioMRF 
Cara, nem tinha visto seu post, desculpa... estou numa correria enorme, assim que possível analiso e retorno.

**Comment by marcosgerene** [comment]
Fiz um PR, por favor teste se resolve seu problema, pelo que vi no código não existe nenhum problema na mudança, vou aguardar algum colega aceitar o PR.

**Comment by danilobreda** [comment]
@CarlosAurelioMRF só para deixar claro que esse problema não tem ligação com o Zeus e sim o tratamento que é feito com o DateTime na sua saída, o DateTimeOffset não vai te ajudar nisso, a conversão de datetime para datetimeoffset pode ser feita tanto de uma para outra. Vou tentar explicar pra você abaixo:

Se temos uma NFe com 2020-09-03T20:28:48-04:00, o horário em UTC é 2020-09-04T00:28:48Z, agora por qual motivo o -4 virou -3? Por conta do datetime local seu ser -3.... mas o horário não vai estar errado será a saída 2020-09-03T21:28:48-03:00 
Todos os horários acima estão no mesmo momento/instante são todos equivalente.

**Qual a diferença entre datetime em formato UTC (ex: DateTime.ToUniversalTime()) e datetimeoffset? Nenhuma é apenas uma questão de perspectiva**.

Vou deixar [aqui um link sobre isso](https://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset) caso você esteja com alguma dúvida na qual não consegui detalhar.

Agora uma outra questão, que é mais complicado ainda, se vem -4 porque não imprime -4? porque -3? Por conta do seu servidor/ambiente estar em GMT -3. 
Você nunca deve levar em conta o horário do servidor, e **sim do GMT onde o cliente está sendo feito a requisição**...
Caso seja uma empresa onde a matriz é em um estado GMT -3 e a filial em GMT -4 começa a acontecer alguns problemas... caso uma imprima/visualize/contabilize o DANFE da outra.
Por isso eu sempre guardo no meu banco de dados todos os horários (não só NFe) em UTC (GMT - 0) e imprimo dependendo do GMT do navegador da pessoa.
Você não deve imprimir no horário que vem da NFe, isso está incorreto! 

No exemplo da filial e matriz, de maneira incorreta, as 2 iriam imprimir o DANFE as 2020-09-03T20:28:48 (2020-09-03T20:28:48-04:00). Sendo que o correto seria uma imprimir 2020-09-03T20:28:48(GMT-4) e a outra 2020-09-03T21:28:48(GMT-3)

Você deve preservar a região do seu client!. Que de qualquer forma, DateTime ou DateTimeOffset não vai resolver esse problema.

**Comment by marcosgerene** [comment]
@danilobreda 

Excelente ponto e explicação, só tenho um ponto sobre isso.

> só para deixar claro que esse problema não tem ligação com o Zeus e sim o tratamento que é feito com o DateTime na sua saída

Entendi seu contexto, mas tenho uma pequena discordância. Se retorna com UTC no XML, o Zeus deve estar estruturado com UTC, ou seja, fiel ao arquivo XML.

Qualquer tratamento deve ser feito pelo ERP, na minha visão o Zeus deve apenas conter os dados de forma fiel os dados do xml. Por isso, considero um bug.

No restante, sem mais consideracões.

Obrigado pelos esclarecimentos.

**Comment by CarlosAurelioMRF** [comment]
@danilobreda entendo seu ponto de vista mas assim como o Marcos disse não concordo, as informações retornadas pelo objeto diferem do arquivo XML, assim como o portal de consulta nfe na minha aplicação existe uma tela onde o usuário visualiza a nota de forma detalhada e ao retornar -03:00 é demonstrado um horário diferente do que está no arquivo XML caracterizando um bug.

Ao demonstrar esses dados do arquivo XML não é considerado horário do servidor, é considerado o arquivo XML. Neste caso o Zeus deveria seguir conforme está no arquivo enviado.

**Comment by danilobreda** [comment]
@marcosgerene  @CarlosAurelioMRF  entendi o ponto de vista de vocês quanto a representação do valor, e realmente o datetimeoffset representa de forma correta o retorno pois ele mantém o GMT de entrada :D

Apenas reitero o problema **exemplo de filial** que demonstrei, que mesmo mudando para offset vai ter o mesmo problema (eu tenho alguns casos assim hoje e a solução de pegar o GMT do client/navegador ao imprimir um DANFE por exemplo, é a solução que encontramos).

Abaixo está um exemplo onde converto as props dhEvento (datetime) e dhEmi (datetimeoffset):
![image](https://user-images.githubusercontent.com/14843499/92920993-a0548c80-f409-11ea-8cda-1e4dd4ea2fce.png)
Perceba que ambas tive o problema de conversão para arrumar o offset do client.

**Comment by denernun** [comment]
Olá pessoal, eu trato clientes de todos os estados, e sempre levo em
consideração a hora original da emissão, independente de eu estar em SP e o
emitente no AM, o importante é o horário original da emissão.
Não havia reparado nesse detalhe no xml, já que tenho um resumo da nota no
banco.

Mas concordo que o que deve vir no objeto é a hora do XML.
