### ISSUE TITLE
X509Certificate2 error Invalid Provider PrivateKey ?

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#1165]
Olá pessoal, estou com um problema aqui que começou da seguinte forma, em um Windows 10 o problema não ocorre e no Windows Server 2016 ele ocorre, toda vez que vou pegar o PrivateKey do certificado ele dá o erro Invalid Provider,

System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   em System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   em System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   em System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   em System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   em classesEasy.NfeStatusServico3.nfeStatusServicoNFCompletedEventArgs.ßéÀ(X509Certificate2 , Int32 , Int32 )
   em classesEasy.CertificadoDigital.UploadNewCertificate(Byte[] pfx, String caminhoPFX, String password, String documento, String nome, String& message) na M:\easy\classesEasy\CertificadoDigital.cs:linha 473 Message: Invalid provider type specified.

Estou utilizando o usuário administrador em ambas as aplicações.

Tanto no Server como no Windows 10.

Alguém já viu algo sobre isso.

Li sobre uma incompatibilidade de privatekey com versões superir a 3.5 do framework.
Se alguém passou por isso e tem uma solução agradeço.

**Comment by robertorp** [comment]
veja no Zeus se configurou certinho A1 ou repositorio ou arquivo ou byte[] etc..

**Comment by danilobreda** [comment]
Vê se as configurações estão certinhas como abaixo:
Principalmente a parte destacada que tem haver com o erro...
Também achei esse [link interessante](https://stackoverflow.com/questions/32430835/using-x509certificate2-to-get-privatekey-causes-cryptographicexception-invalid)

![image](https://user-images.githubusercontent.com/14843499/92652630-9b85c080-f2c3-11ea-8490-a1e62db5f6af.png)

**Comment by marcosgerene** [comment]
@danilobreda 
Interessante, nunca preenchi esses 2 campos em destaque... para que serve exatamente ?

**Comment by danilobreda** [comment]
@marcosgerene são utilizados para assinatura dos xmls, porem o valor default deles já é o correto, não precisam ser informados. É que pode acontecer de alguém deixar uma string vazia ou mesmo outro valor, causando alguns problemas ao bater no SEFAZ e ele tentar validar a assinatura com o certificado etc.

**Comment by marcosgerene** [comment]
@danilobreda  entendi, valeu

**Comment by robertorp** [comment]
Zeus já preenche eles dessa forma, não danilo?

**Comment by marcosmarchiore** [comment]
Pessoal, depois de pesquisas e com a ajuda do @danilobreda  
![image](https://user-images.githubusercontent.com/9381885/92755436-3208bf00-f362-11ea-95cf-757812173df4.png)

Mudando esta flag o problema no servidor parou.

Obrigado a todos pela contribuição
