### ISSUE TITLE
Erro na geração do PDF de evento de CTe

### ISSUE THREAD

**Issue by ryanlucaslemos** [ZeusAutomacao/DFe.NET#1167]
Bom dia, encontro-me com o seguinte erro na geração de alguns PDFs de eventos para CTe:
``Text55: Error in expression: procEventoCTe.eventoCTe.infEvento.detEvento.EventoContainer.xCondUso``

Segue o xml de um evento que ocasionou esse problema:

``
<procEventoCTe versao="3.00"
  xmlns="http://www.portalfiscal.inf.br/cte">
  <eventoCTe xmlns="http://www.portalfiscal.inf.br/cte" versao="3.00">
    <infEvento Id="ID6101104220083635146500013457001000000119100000119501">
      <cOrgao>42</cOrgao>
      <tpAmb>1</tpAmb>
      <CNPJ>03391986000166</CNPJ>
      <chCTe>42200836351465000134570010000001191000001195</chCTe>
      <dhEvento>2020-09-08T15:59:02-03:00</dhEvento>
      <tpEvento>610110</tpEvento>
      <nSeqEvento>01</nSeqEvento>
      <detEvento versaoEvento="3.00">
        <evPrestDesacordo>
          <descEvento>Prestacao do Servico em Desacordo</descEvento>
          <indDesacordoOper>1</indDesacordoOper>
          <xObs>Cte deveria ter sido cancelado pelo emitente Existe o Cte 120 em substituicao!</xObs>
        </evPrestDesacordo>
      </detEvento>
    </infEvento>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
      <SignedInfo>
        <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
        <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
        <Reference URI="#ID6101104220083635146500013457001000000119100000119501">
          <Transforms>
            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
          </Transforms>
          <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
          <DigestValue>3GUXiYtRjI6EK7C+K7a4BQ01AzQ=</DigestValue>
        </Reference>
      </SignedInfo>
      <SignatureValue>EH7iFEqB1cv/JgdIf7oOkTzzjvNl34RglvmqKYSO0qu/R57aucs3kLBYngabo+G+sQY2buW9a3KwzN8OR9hKbl6r6TqcvNIywuKjvHCAWzTuR/81KzBH4ZuY94E7f1sJlFeu8O/9y1XsQVjr+a3rhoa9Z+1p4WFwN+lTEP37JOD297twumgSxEUNgxlfKRMFAONF5r5w3I7EjsNt87Suao+1rsUoUGw8N1PJ6YjZfTfM6/XVfwGE+Fu8x+xdveIuX24u9vJXexSZjS9d1kW21c3VxDeF97Vu/RkQ07DpKBRJFkj4WjuK2tWilHSS49rm7UldnNgnqY3RCFAV1gtX9g==</SignatureValue>
      <KeyInfo>
        <X509Data>
          <X509Certificate>MIIH8DCCBdigAwIBAgIIfRlkYLiNE94wDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEYMBYGA1UEAxMPQUMgVkFMSUQgUkZCIHY1MB4XDTIwMDcxNDE1MTk0N1oXDTIxMDcxNDE1MTk0N1owggEdMQswCQYDVQQGEwJCUjELMAkGA1UECBMCU0MxEjAQBgNVBAcTCUNPTkNPUkRJQTETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLEw1SRkIgZS1DTlBKIEExMSgwJgYDVQQLEx9BUiBTQyBGT1JURSBDRVJUSUZJQ0FETyBESUdJVEFMMRcwFQYDVQQLEw4yNjYwODMxOTAwMDE5ODFFMEMGA1UEAxM8SU5DT0JJTyBJTkRVU1RSSUEgRSBDT01FUkNJTyBERSBCSU9NQVNTQSBMVERBOjAzMzkxOTg2MDAwMTY2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsNom2IlhuZvGvKccurBZczUMdb1yWQLZYVC/lYraeL4p0MtiQQtKfsxFuoqVsWrHIF1r+vPjws1biB6zP7uY2otMZf+zUIgT12Xyy1CKoFMnUDCsvDd/CK2Xve+IvKgRu2wlNjV7GIIfjGnU5CAFc5ru05Cah9fUNXBuEFtU6H/bcrkjQl5LYYOsRpGXDAKz3/sEwtEtkdL/7NMX9WdMJy8NfeDAc+a+OM7Tf/qJxLqCYdrD10yIRMklMvPd22YikVK1S/9aA1VS5yFs0kebTLR8JZNLSic8NIWr4w88InHdtghsE0ShZ1VhNJ3qZTBjUJI0onN+Te7RDkpjDDlSZwIDAQABo4IC2TCCAtUwgZwGCCsGAQUFBwEBBIGPMIGMMFUGCCsGAQUFBzAChklodHRwOi8vaWNwLWJyYXNpbC52YWxpZGNlcnRpZmljYWRvcmEuY29tLmJyL2FjLXZhbGlkcmZiL2FjLXZhbGlkcmZidjUucDdiMDMGCCsGAQUFBzABhidodHRwOi8vb2NzcHY1LnZhbGlkY2VydGlmaWNhZG9yYS5jb20uYnIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBRTy6XkdVCZQCy+WxVFyb7LMKqJxTBwBgNVHSAEaTBnMGUGBmBMAQIBJTBbMFkGCCsGAQUFBwIBFk1odHRwOi8vaWNwLWJyYXNpbC52YWxpZGNlcnRpZmljYWRvcmEuY29tLmJyL2FjLXZhbGlkcmZiL2RwYy1hYy12YWxpZHJmYnY1LnBkZjCBtgYDVR0fBIGuMIGrMFOgUaBPhk1odHRwOi8vaWNwLWJyYXNpbC52YWxpZGNlcnRpZmljYWRvcmEuY29tLmJyL2FjLXZhbGlkcmZiL2xjci1hYy12YWxpZHJmYnY1LmNybDBUoFKgUIZOaHR0cDovL2ljcC1icmFzaWwyLnZhbGlkY2VydGlmaWNhZG9yYS5jb20uYnIvYWMtdmFsaWRyZmIvbGNyLWFjLXZhbGlkcmZidjUuY3JsMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwga0GA1UdEQSBpTCBooEVamFjaWVsQGluY29iaW8uY29tLmJyoDgGBWBMAQMEoC8ELTE0MDIxOTYzNDY5MjEzNzA5NjgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAbBgVgTAEDAqASBBBWQUxNSVIgR0FTUEVSSU5JoBkGBWBMAQMDoBAEDjAzMzkxOTg2MDAwMTY2oBcGBWBMAQMHoA4EDDAwMDAwMDAwMDAwMDANBgkqhkiG9w0BAQsFAAOCAgEAakK14HNTBXhNU/+fERE3ZV66BMcNRqeG51iQIUUgql3imzytESIUr3WLI+H+qf6SZB5rzlfgHwpsCEviJ0vOu9pASD1brINRAdnUUkLxjdJIT/Rw+FXq47bcGlDRl9yVXChjJGbiTkR5lSc585ccNIJ2sN/2vsFA5rwQcO2gFo4oyfyoGcH0QW9fk/jk0CoeefWVeV+hMlUpqsatklhLw+NHiTUFtKu7NNMjZYVvcqOH8BxFgLB8OxiSCdrdSJTLXg710d6O2CjwQLex12bMSuaj0icLsNY8c6uq9K1OBZ+vS+DOOsEwcHOq93RDPRnFrz+ZVY3+lHp2TFKZe8QJtskBngwG2a7kM8OtPYSsVVUoiTBLswxfL4GDtrFhDKO79R5/F1KBUJ7ot9dFNGIf/UoRzLXZDp3rBXVtVyuSDCOO1c667nIpROk2eNHXElzzjMu+DgEq6qX14NidZb9ItW89jiE3YyjVZai4gSU1VkihgIi7GMDDKVqTiX8XVPv7LSz5BRuOMTD3B+Wni+m777pAe1r4dvKU6/I3GdFavTAD2ArkxksL7ZNkAKdsJv3DZ3CinuC6wverBV/4QYBYzzChHWQcrObX+q2p1zzwfM0gtbtx4GPohHEvuxqFNBoyD2tZGlbO1wc9pcMUhtFN1LEnzgraR2l56kFT1wfK0DI=</X509Certificate>
        </X509Data>
      </KeyInfo>
    </Signature>
  </eventoCTe>
  <retEventoCTe xmlns="http://www.portalfiscal.inf.br/cte" versao="3.00">
    <infEvento Id="ID342200116544479">
      <tpAmb>1</tpAmb>
      <verAplic>RS20191021102444</verAplic>
      <cOrgao>42</cOrgao>
      <cStat>135</cStat>
      <xMotivo>Evento registrado e vinculado a CT-e</xMotivo>
      <chCTe>42200836351465000134570010000001191000001195</chCTe>
      <tpEvento>610110</tpEvento>
      <xEvento>Prestação Serviço Desacordo Registrado</xEvento>
      <nSeqEvento>1</nSeqEvento>
      <dhRegEvento>2020-09-08T16:01:42-03:00</dhRegEvento>
      <nProt>342200116544479</nProt>
    </infEvento>
  </retEventoCTe>
</procEventoCTe>
``

**Comment by robertorp** [comment]
Isso é impressão de Evento de "Prestação de serviço em desacordo"

Somente o pai @marcosgerene  sabe dizer se a impressão do Zeus suporta esse evento.

**Comment by marcosgerene** [comment]
@ryanlucaslemos 

Preciso do xml do CTe e do evento para testar melhor.

Obrigado

**Comment by ryanlucaslemos** [comment]
O CTe gera o PDF normalmente.
@marcosgerene O xml do evento de desacordo eu já enviei, segue o xml do CTe:

``
<cteProc versao="3.00" xmlns="http://www.portalfiscal.inf.br/cte"><CTe xmlns="http://www.portalfiscal.inf.br/cte"><infCte versao="3.00" Id="CTe42200836351465000134570010000001191000001195"><ide><cUF>42</cUF><cCT>00000119</cCT><CFOP>6932</CFOP><natOp>PREST DE SERV DE TRANSP INICIADA EM UNIDADE DA FED DIVERSA</natOp><mod>57</mod><serie>1</serie><nCT>119</nCT><dhEmi>2020-08-17T16:12:14-03:00</dhEmi><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>5</cDV><tpAmb>1</tpAmb><tpCTe>0</tpCTe><procEmi>0</procEmi><verProc>3.0.1.0.0</verProc><cMunEnv>4204301</cMunEnv><xMunEnv>CONCORDIA</xMunEnv><UFEnv>SC</UFEnv><modal>01</modal><tpServ>0</tpServ><cMunIni>4108601</cMunIni><xMunIni>GOIOERE</xMunIni><UFIni>PR</UFIni><cMunFim>4204301</cMunFim><xMunFim>CONCORDIA</xMunFim><UFFim>SC</UFFim><retira>1</retira><indIEToma>1</indIEToma><toma3><toma>3</toma></toma3></ide><compl><fluxo><xRota>47</xRota></fluxo><Entrega><semData><tpPer>0</tpPer></semData><semHora><tpHor>0</tpHor></semHora></Entrega><origCalc>GOIOERE</origCalc><destCalc>CONCORDIA</destCalc><xObs>CIOT 020022212099/6815 - EMPRESA OPTANTE DO SIMPLES NACIONAL - NAO GERA CREDITO DE ICMS -   - VEICULO: MLV8D02 RENAVAM: 994683200 - MOTORISTA: GABRIEL STEDILLE CPF: 084025249-82 | SEGURO DA CARGA POR CONTA DO: Emitente do CT-e, SEGURADORA: MIA TRANSPORTES LTDA, APOLICE: 12345678</xObs><ObsCont xCampo="LEI DA TRANSPARENCIA"><xTexto>PERCENTUAL APROXIMADO DOS TRIBUTOS: : 16,06%  Fonte: IBPT</xTexto></ObsCont><ObsCont xCampo="CPFMOTORISTA"><xTexto>08402524982</xTexto></ObsCont><ObsCont xCampo="PLACA"><xTexto>MLV8D02</xTexto></ObsCont></compl><emit><CNPJ>36351465000134</CNPJ><IE>260410624</IE><xNome>MIA TRANSPORTES LTDA</xNome><xFant>MIA TRANSPORTES LTDA</xFant><enderEmit><xLgr>R. EST CACHIMBO</xLgr><nro>000</nro><xBairro>INTERIOR</xBairro><cMun>4204301</cMun><xMun>CONCORDIA</xMun><CEP>89728000</CEP><UF>SC</UF><fone>4999316786</fone></enderEmit></emit><rem><CNPJ>00518707000194</CNPJ><IE>8160319403</IE><xNome>AMITEC IND. COM. AMIDOS LTDA</xNome><fone>4435222829</fone><enderReme><xLgr>R. RUA ESPIRITO SANTO</xLgr><nro>S/N</nro><xBairro>JARACATIA</xBairro><cMun>4108601</cMun><xMun>GOIOERE</xMun><CEP>87360000</CEP><UF>PR</UF><cPais>1058</cPais><xPais>BRASIL</xPais></enderReme></rem><dest><CNPJ>03391986000166</CNPJ><IE>253933617</IE><xNome>INCOBIO INDUSTRIA E COMERCIO DE BIOMASSA LTDA</xNome><fone>4934428065</fone><enderDest><xLgr>R. LINHA GASPERINI- CX POSTAL 12</xLgr><nro>0</nro><xBairro>INTERIOR</xBairro><cMun>4204301</cMun><xMun>CONCORDIA</xMun><CEP>89715899</CEP><UF>SC</UF><cPais>1058</cPais><xPais>BRASIL</xPais></enderDest><email>nfe@incobio.com.br</email></dest><vPrest><vTPrest>780.00</vTPrest><vRec>780.00</vRec><Comp><xNome>FRETE VALOR</xNome><vComp>780.00</vComp></Comp></vPrest><imp><ICMS><ICMSSN><CST>90</CST><indSN>1</indSN></ICMSSN></ICMS></imp><infCTeNorm><infCarga><vCarga>17836.00</vCarga><proPred>FECULA DE MANDIOCA CML - ( BAG 900 KG)</proPred><infQ><cUnid>01</cUnid><tpMed>PESO BRUTO</tpMed><qCarga>9100.0000</qCarga></infQ></infCarga><infDoc><infNFe><chave>41200800518707000194550030000473681000670178</chave></infNFe></infDoc><infModal versaoModal="3.00"><rodo><RNTRC>52646833</RNTRC></rodo></infModal></infCTeNorm><autXML><CNPJ>04898488000177</CNPJ></autXML></infCte><infCTeSupl><qrCodCTe>https://dfe-portal.svrs.rs.gov.br/cte/qrcode?chCTe=42200836351465000134570010000001191000001195&amp;tpAmb=1</qrCodCTe></infCTeSupl><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#CTe42200836351465000134570010000001191000001195"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>DHtO526TVqrSRNFq+8zmSg+LzKM=</DigestValue></Reference></SignedInfo><SignatureValue>W9dZX3S+pw2XA09DYQaxA2Wx/ab13L0pGsA2XYwvKHZaxhpqCrKOMz1VwgnO7fC7cIERjXgVieRcA4OhJs71HenzjMrZGWu8xAL/gQuoaD9aL79eLR1BLUK0GYAFoc+J7vJkz1HZIN7AhxgWKfyMaQf9LSwMbuBytlmM3VVRUxyFpAUvQNI3pGIyVzLOSEfEDLLJroNGKTs223v0oKRI+ieZyvm6tFYG+4l3dvgWdOmJaW/KKJ29IeE/Gb5+N/IRoWod/Wk/YKMu+g+ufaCiWrO4VCafi5fyTiXOeSE+1tAUXWvNXfoDHGnA2cCsidpxsvodYiSCfftpPhDVRQ4xjg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHxDCCBaygAwIBAgIIXT8gAwReiBgwDQYJKoZIhvcNAQELBQAwgYkxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTQwMgYDVQQLEytBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhIHYyMRIwEAYDVQQLEwlBQyBTT0xVVEkxGzAZBgNVBAMTEkFDIFNPTFVUSSBNdWx0aXBsYTAeFw0yMDAzMDQxOTA1NTFaFw0yMTAzMDQxODQyMDBaMIHsMQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE0MDIGA1UECxMrQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFJhaXogQnJhc2lsZWlyYSB2MjESMBAGA1UECxMJQUMgU09MVVRJMRswGQYDVQQLExJBQyBTT0xVVEkgTXVsdGlwbGExFzAVBgNVBAsTDjA3MzczMDU1MDAwMTk2MRowGAYDVQQLExFDZXJ0aWZpY2FkbyBQSiBBMTEsMCoGA1UEAxMjTUlBIFRSQU5TUE9SVEVTIExUREE6MzYzNTE0NjUwMDAxMzQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDdcv5PcKMSnGEYMJA8MOm0UDiN3YDi3NYCjIYCYlgPF5KZTQZqerU6O77zSBIWiwsx1B9eCzgmstn8khUnQwe5tk9ls3PHNLAtedNIW+deHQPEVTS7xODqnS8CxTzYpoFvMUrre2ggVZD70iBi4i467L1t+UNPlJHblXBBHl89Wz/TMiv4FNDAJSopUxU6rNpb1bDOMzAhdLSk2ZpSQtnyj6xIBo/EjhP8m3ShbIVDgfvyV+E+eiiV9FMex9nkpl8bNXbJS7cmaa9v7DQlX2vB8zSBIiR1HYHUJeQDG8E0On2MB1fIonhOryQNwRosG3TGW0HPHEdPmBq5nP+/noszAgMBAAGjggLJMIICxTBUBggrBgEFBQcBAQRIMEYwRAYIKwYBBQUHMAKGOGh0dHA6Ly9jY2QuYWNzb2x1dGkuY29tLmJyL2xjci9hYy1zb2x1dGktbXVsdGlwbGEtdjEucDdiMB0GA1UdDgQWBBTwozfmTvhupvv5tIdCxjLofsoYNjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFDWuMRT2XtJ6T1j+NKgaZ5cKxJsHMF4GA1UdIARXMFUwUwYGYEwBAgEmMEkwRwYIKwYBBQUHAgEWO2h0dHBzOi8vY2NkLmFjc29sdXRpLmNvbS5ici9kb2NzL2RwYy1hYy1zb2x1dGktbXVsdGlwbGEucGRmMIHeBgNVHR8EgdYwgdMwPqA8oDqGOGh0dHA6Ly9jY2QuYWNzb2x1dGkuY29tLmJyL2xjci9hYy1zb2x1dGktbXVsdGlwbGEtdjEuY3JsMD+gPaA7hjlodHRwOi8vY2NkMi5hY3NvbHV0aS5jb20uYnIvbGNyL2FjLXNvbHV0aS1tdWx0aXBsYS12MS5jcmwwUKBOoEyGSmh0dHA6Ly9yZXBvc2l0b3Jpby5pY3BicmFzaWwuZ292LmJyL2xjci9BQ1NPTFVUSS9hYy1zb2x1dGktbXVsdGlwbGEtdjEuY3JsMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgbEGA1UdEQSBqTCBpoEXanVsaWFuYWFsYW4wN0BnbWFpbC5jb22gGAYFYEwBAwKgDxMNSlVMSUFOQSBST01BTqAZBgVgTAEDA6AQEw4zNjM1MTQ2NTAwMDEzNKA9BgVgTAEDBKA0EzIzMDA4MTk5MDA3OTA5MDQ0OTc2MDAwMDAwMDAwMDAwMDAwMDAwMDUzOTgyNzZTU1BTQ6AXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBAHE4W0K5QPZ3CYnMbmusRy27TUyH6DVBoB/p+pLZ3uO7o1EoWGavcAYrMWXF18ER7/DgIw1Hv5ELdg5M/SIGhiPle8w7v1TIXuSrSIQEI+MeTDCn+VwPmvTAbP9isZWESFglExQ7iekyuvZbnXULrYv8s0ZbeSMaL3ZSGj6BTLi8yBD96awCyfBCkLETyWvZ29N9ugkJDOHUOfF4MVvpHcx0dKmZ6an4CQuZIFBvTXt66M0Q65SepZsH6tr3QYDi1wTHJmDS6CexFOe5UwBn5kobMERCxT/KM4amQOhFTTOLz0R7/Y7gKvKfwJcbamNTAtCWxXWqjU3ej+2CTjtBgsLQr4Naqe6xvHfrqYLzjE0FS3UUtVTvtnL/eQkjro37qbyBu6n5Lb+RRwg6BT0Oh5S1XiSAcJvM2QQXeNrnoGqRMU0JULwcpDB5+ZkuDelbzJFsqDR7sQvnc0DGMUCCibSKIX0O1yKaYCiPGmAe98gkf4ImWZIxRhQ7qnagBxkpkb2Ge8sciaIezJ+ujQsAs7QEmlH1n9qoZnlJA83u+51xai+KRTcPQQLPRfcGa/TJjtOnztrSqpbp+as97vVZHMOpNcXzNdM01GCRTU4/WcWJlFVWneZElOE+tg4eUwI5dB/HVx8KvWS+WrH9yxBWtVcjpWcfsQg2NspN/iPMgrOS</X509Certificate></X509Data></KeyInfo></Signature></CTe><protCTe versao="3.00" xmlns="http://www.portalfiscal.inf.br/cte"><infProt Id="CTe342200103879261"><tpAmb>1</tpAmb><verAplic>RS20200625174630</verAplic><chCTe>42200836351465000134570010000001191000001195</chCTe><dhRecbto>2020-08-17T16:12:38-03:00</dhRecbto><nProt>342200103879261</nProt><digVal>DHtO526TVqrSRNFq+8zmSg+LzKM=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso do CT-e</xMotivo></infProt></protCTe></cteProc>
``

**Comment by marcosgerene** [comment]
@ryanlucaslemos 
Por favor, teste o PR aberto e me avisa.

Abraço

**Comment by marcosgerene** [comment]
@ryanlucaslemos 
Vou aceitar o PR e fechar a issue, se o problema persistir, reabra, por favor.
