### ISSUE TITLE
Erro ao visualizar NF-e (Exportar PDF)

### ISSUE THREAD

**Issue by SouzaMatheus-dev** [ZeusAutomacao/DFe.NET#1169]
No método usado para exportar PDF quando o campo informações adicionais que equivale ao campo infAdic no XML, quando o usuário entra com uma informção e inclui [ ]
![Nota1](https://user-images.githubusercontent.com/37388147/94058292-377cf500-fdb7-11ea-93ab-506bfb30a51e.png)
 o método retorna o erro: {"mensagem":"TextInfAdicionais: Error in expression:  001 Boleto num.50 "}, na minha aplicação eu fiz um replace e deu certo, mas queria saber se tem alguma solução definitiva, ou se já passaram por isso.

**Comment by marcosgerene** [comment]
@SouzaMatheus-dev 

Os Brackets (colchetes) indicam ao FastReports uma função interna, por isso o erro.

Algumas documentações: 
https://stackoverflow.com/questions/12636732/escape-square-brackets-in-fast-report-strings
https://www.fast-report.com/documentation/UserManFrNET-en/index.html?textobjectexpressions.htm

Poste o XML, vou tentar tratar isso de alguma forma, mas aqui internamente eu simplesmente troco os colchetes por parenteses.

**Comment by SouzaMatheus-dev** [comment]
Entendi, eu também fiz essa tratativa aqui. Mas me foi solicitado que eu retornasse para o meu usuário com os [ ].

**Comment by marcosgerene** [comment]
Preciso do xml na formatação correta. Por favor, poste zipado.

**Comment by SouzaMatheus-dev** [comment]
[XML.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5272318/XML.zip)

Como solicitado

**Comment by marcosgerene** [comment]
Mandei um PR, por favor teste.

PS: Marquei como bug por causa da impressão sem ICMS.

**Comment by SouzaMatheus-dev** [comment]
Testei aqui e funcionou perfeitamente.
![Resolvido](https://user-images.githubusercontent.com/37388147/94160793-62b92000-fe5b-11ea-9dbf-a150501c257f.png)
![Resolvido2](https://user-images.githubusercontent.com/37388147/94160800-63ea4d00-fe5b-11ea-8ba2-445d75d37419.png)
![Resolvido3](https://user-images.githubusercontent.com/37388147/94160803-6482e380-fe5b-11ea-9647-e729ff062dd2.png)

Muito obrigado.

**Comment by cvenancio** [comment]
@marcosgerene, 

Passei por este problema mesmo após a correção. Encontrei na documentação do FastReport algo que acredito solucionar o problema definitivamente. É o atributo AllowExpressions="false" no elemento TextObject.

A linha 1445 do NFeRetrato.frx pode ser alterada para:
`<TextObject Name="TextInfAdicionais" AllowExpressions="false" Left="1.45" Top="26.91" Width="468.5" Height="29.8" CanGrow="true" GrowToBottom="true" CanBreak="false" Font="Times New Roman, 8pt"/>`

Acredito que isso substituiria os _Replaces_ e resolveria o problema de segurança que existe atualmente.

**Comment by marcosgerene** [comment]
@cvenancio Se quiser abrir um PR para propor a mudança o pessoal pode analizar, eu sou contra a mudança.
