### ISSUE TITLE
Erro de QRCode.

### ISSUE THREAD

**Issue by ciceroaferreira** [ZeusAutomacao/DFe.NET#117]
Alguém já passou por isso ? Não estou encontrando o erro... Está dando erro de QrCode.
![zeus](https://cloud.githubusercontent.com/assets/15364864/14249386/dc358988-fa4f-11e5-85fc-308725c5e4b6.png)

**Comment by mvidaldev** [comment]
Isso é o erro de hash provavelmente o CSC está errado

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Mon, 4 Apr 2016 06:28:28 -0700

**Comment by ciceroaferreira** [comment]
Marcos obrigado pela resposta..
Mas verifiquei o CSC na sefaz e está correto.. A unica coisa que fiz foi colocar 4 zeros antes.

![image](https://cloud.githubusercontent.com/assets/15364864/14249792/dd99ac9e-fa51-11e5-9676-b3bc01499880.png)

**Comment by mvidaldev** [comment]
o codigo csc no parana tem 36 caracteres, não sei muito bem como funciona no RS, mas aqui onde deu esse erro, eu fui lá no site, com a senha do cliente, copiei em um txt e colei no aplicativo, só então funcionou, já atualizou os schemas para a versão nova?

eu coloquei no meu ftp pra ficar mais pratico 

www.casters.com.br/schemas.rar

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Mon, 4 Apr 2016 06:42:33 -0700

**Comment by ciceroaferreira** [comment]
O CSC tem 36 caracteres tem razão. E o identificador do CSC ? É um caracter
certo ?

Obrigado

Cicero

2016-04-04 10:44 GMT-03:00 Marcos Vidal notifications@github.com:

> o codigo csc no parana tem 36 caracteres, não sei muito bem como funciona
> no RS, mas aqui onde deu esse erro, eu fui lá no site, com a senha do
> cliente, copiei em um txt e colei no aplicativo, só então funcionou, já
> atualizou os schemas para a versão nova?
> 
> eu coloquei no meu ftp pra ficar mais pratico
> 
> www.casters.com.br/schemas.rar
> 
> Marcos VidalAnalista de SistemasCasters Automação Comercial
> (45)3523-6012
> (45)9903-6551
> 
> Date: Mon, 4 Apr 2016 06:42:33 -0700
> From: notifications@github.com
> To: Zeus.Net.NFe.NFCe@noreply.github.com
> CC: marcosvidal@outlook.com
> Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro de QRCode. (#117)
> 
> Marcos obrigado pela resposta..
> 
> Mas verifiquei o CSC na sefaz e está correto.. A unica coisa que fiz foi
> colocar 4 zeros antes.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/117#issuecomment-205301714

## 

______________________________Cicero Ferreira_
Technical Consultant / ITSM (ITIL)

_mobile:_ +55 51 9328-1783
_e-mail:_ cicero.ferreira@gmail.com
_linkedin Profile http://br.linkedin.com/pub/cicero-ferreira/14/738/882_

**Comment by mvidaldev** [comment]
geralmente 6 digitos 000001

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Mon, 4 Apr 2016 06:49:54 -0700

**Comment by ciceroaferreira** [comment]
Marcos... Salvou minha vida.. Muito Obrigado..

Forte Abraço

Cicero

2016-04-04 10:51 GMT-03:00 Marcos Vidal notifications@github.com:

> geralmente 6 digitos 000001
> 
> Marcos VidalAnalista de SistemasCasters Automação Comercial
> (45)3523-6012
> (45)9903-6551
> 
> Date: Mon, 4 Apr 2016 06:49:54 -0700
> 
> From: notifications@github.com
> To: Zeus.Net.NFe.NFCe@noreply.github.com
> CC: marcosvidal@outlook.com
> Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro de QRCode. (#117)
> 
> O CSC tem 36 caracteres tem razão. E o identificador do CSC ? É um caracter
> 
> certo ?
> 
> Obrigado
> 
> Cicero
> 
> 2016-04-04 10:44 GMT-03:00 Marcos Vidal notifications@github.com:
> 
> > o codigo csc no parana tem 36 caracteres, não sei muito bem como funciona
> > 
> > no RS, mas aqui onde deu esse erro, eu fui lá no site, com a senha do
> > 
> > cliente, copiei em um txt e colei no aplicativo, só então funcionou, já
> > 
> > atualizou os schemas para a versão nova?
> > 
> > eu coloquei no meu ftp pra ficar mais pratico
> > 
> > www.casters.com.br/schemas.rar
> > 
> > Marcos VidalAnalista de SistemasCasters Automação Comercial
> > 
> > (45)3523-6012
> > 
> > (45)9903-6551
> > 
> > Date: Mon, 4 Apr 2016 06:42:33 -0700
> > 
> > From: notifications@github.com
> > 
> > To: Zeus.Net.NFe.NFCe@noreply.github.com
> > 
> > CC: marcosvidal@outlook.com
> > 
> > Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro de QRCode. (#117)
> > 
> > Marcos obrigado pela resposta..
> > 
> > Mas verifiquei o CSC na sefaz e está correto.. A unica coisa que fiz foi
> > 
> > colocar 4 zeros antes.
> > 
> > —
> > 
> > You are receiving this because you commented.
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > —
> > 
> > You are receiving this because you authored the thread.
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > <
> > https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/117#issuecomment-205301714
> 
> ## 
> 
> ______________________________Cicero Ferreira_
> 
> Technical Consultant / ITSM (ITIL)
> 
> _mobile:_ +55 51 9328-1783
> 
> _e-mail:_ cicero.ferreira@gmail.com
> 
> _linkedin Profile http://br.linkedin.com/pub/cicero-ferreira/14/738/882_
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/117#issuecomment-205303581

## 

______________________________Cicero Ferreira_
Technical Consultant / ITSM (ITIL)

_mobile:_ +55 51 9328-1783
_e-mail:_ cicero.ferreira@gmail.com
_linkedin Profile http://br.linkedin.com/pub/cicero-ferreira/14/738/882_

**Comment by mvidaldev** [comment]
Que isso rapá, sofremos todos os dias com os mandos e desmandos da receita, temos que nos unir pra tentar ao menos aliviar um pouco da nossa frustração e resolver os problemas que eles nos causam.
abraços.

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Mon, 4 Apr 2016 06:53:06 -0700
