### ISSUE TITLE
Carta de Crédito - Impressão de DANFE - {"Cadeia de caracteres não foi reconhecida como DateTime válido."}

### ISSUE THREAD

**Issue by mmedeirosbz** [ZeusAutomacao/DFe.NET#1170]
Estou tentando gerar um danfe para carta de, seleciono os dois xml (um da NFE processada e outro do evento processado).  Ao tentra exibir o DANFE ou exportar pra PDF tomo o erro: Cadeia de caracteres não foi reconhecida como DateTime válido. 

Já revisei o xml e nao vejo problema nas datas. Podem me ajudar?

var danfe = new DanfeFrEvento(proc, procEvento, new ConfiguracaoDanfeNfe(_configuracoes.ConfiguracaoDanfeNfce.Logomarca, RdbDuasLinhas.IsChecked ?? false, ChbCancelado.IsChecked ?? false), "NOME DA SOFTWARE HOUSE");
danfe.Visualizar();  ---- erro aqui!

xml do evento:
`
<?xml version="1.0" encoding="UTF-8"?><procEventoNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><evento versao="1.00"><infEvento Id="ID1101103320091546745300010855001100000021177252189701"><cOrgao>33</cOrgao><tpAmb>2</tpAmb><CNPJ>15467453000108</CNPJ><chNFe>33200915467453000108550011000000211772521897</chNFe><dhEvento>2020-09-23T19:14:16-03:00</dhEvento><tpEvento>110110</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Carta de Correção</descEvento><xCorrecao>teste de carta homologa</xCorrecao><xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#ID1101103320091546745300010855001100000021177252189701"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>6+7gx6EpdqvWE/Sj4qCKqZ8wa+I=</DigestValue></Reference></SignedInfo><SignatureValue>dhh8oqtH4Ok6FzJRLBWg82oaP2nkw3D3kW88+lFcwODxLGmTC6h8ULoddlI1hVOEDIOPCkPNhwhCUpp/n5FnFdxV3MZ5NI8xXYaOnfaI7V+OSB8ArNze6o5r13jGHxNvCPrik7pKXH3y51oKiw8UazruEAKs4+MwkBJbuc3zXDQh75A9XFLkfaUVpKXtDfML3VDzXB7UcG+qxD4ntcBT3f/cyxniuejHp19uuLOP/UcAW62Kb5jqe/iUK11skL5NOFMEV0bcwCooPcx63FP4Oz6Iw1YVqFuG8y06e58GxwogSsJrAbpKjwpaoq0b01ZdcSjN1D/M5ODl/mw+PddHhQ==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHnTCCBYWgAwIBAgIIYrju/f4np48wDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEXMBUGA1UEAxMOQUMgQ05ETCBSRkIgdjMwHhcNMjAwMTA2MjA0NTUzWhcNMjEwMTA2MjA0NTUzWjCB5DELMAkGA1UEBhMCQlIxCzAJBgNVBAgTAlJKMRcwFQYDVQQHEw5SSU8gREUgSkFORUlSTzETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLEw1SRkIgZS1DTlBKIEExMRcwFQYDVQQLEw4zNDE3MzY4MjAwMDMxODExMC8GA1UEAxMoQkVCRUwgQkFCWSBDT05GRUNDQU8gTFREQToxNTQ2NzQ1MzAwMDEwODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKhcioENdHMvfw6JhZ5+dpW0f8tS3rqxyxaz6R/QYPBo0/LXAO9eD9K/IM1DcZbQMv79gKZBL3ZdX2QD9GESpbFpXo4dNAeRrtXWOTdgMOfSLA0e0aCJSNWfbePtOQwbvhHIBZEsBYj+R+HwEafQZvQaynGL2tACZaO5We7Xs8s3BbX4o0DpOlm+ztAHuro/8G57BxQgXWKKWevsRdR7KjYhKhBsPFVGjwTLz9KAwHlmPZlznvW1ThphGA4tiUyP4FVoTrvS57tdDJocBZlaGve/k9ivcuDIq4bUKbXwv54Lg9m53RYZRCVe/KEhL6+QR+Xyd5jelo4PmWj6Ht5SFckCAwEAAaOCAsEwggK9MB8GA1UdIwQYMBaAFGsfNBVBGuqbHsoi0s7d77vpMsqJMA4GA1UdDwEB/wQEAwIF4DBpBgNVHSAEYjBgMF4GBmBMAQIBNDBUMFIGCCsGAQUFBwIBFkZodHRwOi8vcmVwb3NpdG9yaW8uYWNzcGNicmFzaWwub3JnLmJyL2FjLWNuZGxyZmIvYWMtY25kbC1yZmItcGMtYTEucGRmMIGmBgNVHR8EgZ4wgZswS6BJoEeGRWh0dHA6Ly9yZXBvc2l0b3Jpby5hY3NwY2JyYXNpbC5vcmcuYnIvYWMtY25kbHJmYi9sY3ItYWMtY25kbHJmYnY1LmNybDBMoEqgSIZGaHR0cDovL3JlcG9zaXRvcmlvMi5hY3NwY2JyYXNpbC5vcmcuYnIvYWMtY25kbHJmYi9sY3ItYWMtY25kbHJmYnY1LmNybDCBiQYIKwYBBQUHAQEEfTB7ME0GCCsGAQUFBzAChkFodHRwOi8vcmVwb3NpdG9yaW8uYWNzcGNicmFzaWwub3JnLmJyL2FjLWNuZGxyZmIvYWMtY25kbHJmYnY1LnA3YjAqBggrBgEFBQcwAYYeaHR0cDovL29jc3AuYWNzcGNicmFzaWwub3JnLmJyMIG/BgNVHREEgbcwgbSBGUJFQkVMQkFCWV9SSkBZQUhPTy5DT00uQlKgKQYFYEwBAwKgIBMeUk9EUklHTyBERSBNRURFSVJPUyBQSVpaT0NIRVJPoBkGBWBMAQMDoBATDjE1NDY3NDUzMDAwMTA4oDgGBWBMAQMEoC8TLTIyMTExOTc0MDExNzQzNjY3NDUwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggIBAD0LDIUM2WKoI9TF/TCgsT2YAVplGzg57uS4Jxx9XeAhWaTSrjIDbsELzc4Dlpc6p8CPG17sffit4p+bsxh8yQsyqZRsci16VPbOEisdEcBwi1t1MCoDBn+TeTNOyZ9/vCMz7TpPa2PM39P4rZKoyC2dOFEqCTz2ZRrATxi6DEiOz9pYDGbilU5jAx7rxgsKRSBGlzH7rLjDwTJt3q84G/mf3Al2JTN8pqSCORMqElj6fLoqIqa8c8lquj4mqQvEXbcTmj2plZ2ZomDUJ8Z8svYo3xSHkulxjzCaLyCBOBxwjj0ilmABB8pNJLNtXGoqmXOcnLIXiR5FXD5+JyTDl1bzoqxnAIzrzL4YCPC8H1o4L7BnWf7B7N5shF4ezFfbUhpf3eoQzrXymtzicN1j837JShpeJ5lY8Zq/eXZiggm/24dU/Dj1C6gSGgyXjIxo/b9U96kOEHnyxq5iO/2vIj/eJKz7Sj/qv6CaVmMPRi7mU0Vfx4mIgvwcIiZszSppUN0tviU1lJff8L3IY66t1AvlaieIZ7x84XInRVISl51zbaKWrPQQ3yL0017i1bw1lTeB3bwdKaHQ46Ma+OnqdzlTTGhBKsAR4AqCInN8CyHXCdKJCsT93AW9juQZg4AVpPvVRP7+S1GXbycQAa7jlBsZ60epFPe8G9U2MKPLvPlc</X509Certificate></X509Data></KeyInfo></Signature></evento><retEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento><tpAmb>2</tpAmb><verAplic>SVRS202006040706</verAplic><cOrgao>33</cOrgao><cStat>135</cStat><xMotivo>Evento registrado e vinculado a `NF-e</xMotivo><chNFe>33200915467453000108550011000000211772521897</chNFe><tpEvento>110110</tpEvento><nSeqEvento>1</nSeqEvento><CNPJDest>03469265000121</CNPJDest><emailDest>bebelbaby_rj@yahoo.com.br</emailDest><dhRegEvento>2020-09-23T19:14:16-03:00</dhRegEvento><nProt>333200000404298</nProt></infEvento></retEvento></procEventoNFe>`

[33200915467453000108550011000000211772521897-procEventoNfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5272456/33200915467453000108550011000000211772521897-procEventoNfe.zip)

**Comment by marcosgerene** [comment]
@mmedeirosbz 

Para testar a impressão de um evento é necessário o xml do evento e da **NFe original**.

---

Testei o xml de outra NFe como base e não tive problemas na impressão:

![image](https://user-images.githubusercontent.com/15945003/94142586-e74c7400-fe44-11ea-942f-a8ac5b4a8ffd.png)


Por favor, envie os dois XMLs (NFe e evento) zipados para que eu possa testar.

**Comment by mmedeirosbz** [comment]
[nfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5280580/nfe.zip)

eu insiro os dois xmls e da erro na impressao... 
os dois xmls estão anexados... e obrigado pelo apoio mano...

**Comment by marcosgerene** [comment]
@mmedeirosbz Não houve qualquer erro aqui, mesmo com seus xmls.

Por favor compile e teste no demo, fiz isso aqui. 

Provavelmente seu erro está na sua rotina de geração interna.

----

![image](https://user-images.githubusercontent.com/15945003/94263688-d4e93d80-ff0b-11ea-84d0-1fca1ca7e3e6.png)

**Comment by mmedeirosbz** [comment]
No demo aqui, ultima versao, dá o mesmo erro... mandei print no anexo... nao sei o que pode ser...   

![Screenshot_23](https://user-images.githubusercontent.com/15366975/94595497-4bb26d80-0261-11eb-8fb5-790ae803f880.jpg)

**Comment by mmedeirosbz** [comment]
o erro ocorre quando chama a visualizacao do relatorio... 
![Screenshot_24](https://user-images.githubusercontent.com/15366975/94693262-de0e4c00-0309-11eb-9606-d2b54a367f17.jpg)

**Comment by marcosgerene** [comment]
@mmedeirosbz 

Nao consegui reproduzir o erro aqui com seus xmls.

Confira se esta usando os mesmos xmls que me mandou. Se não estiver, poste os xmls que está usando.

**Comment by mmedeirosbz** [comment]
[nfes.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5306669/nfes.zip)


São esses dois XMLs .... 

Consigo emitir danfe com o xml da NFe tranquilamente...  parece que alguma data esta em formato incompativel com o form de eventos..

**Comment by marcosgerene** [comment]
Demo com os seuss XMLs.

![impressao](https://user-images.githubusercontent.com/15945003/94715013-4b7aa680-0323-11eb-95af-9babb7cb084b.gif)

[teste.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/5307014/teste.pdf)

**Comment by mmedeirosbz** [comment]
mano alguma ideia do que pode estar ocorrendo??? parece ser algo com o FASTREPORT

**Comment by mmedeirosbz** [comment]
em FastReport.Code.AssemblyDescriptor.InvokeEvent(String name, Object[] parms)
   em FastReport.Report.InvokeEvent(String name, Object[] parms)
   em FastReport.Base.InvokeEvent(String name, Object param)
   em FastReport.BandBase.SaveState()
   em FastReport.Engine.ReportEngine.ShowBandToPreparedPages(BandBase band, Boolean getData)
   em FastReport.Engine.ReportEngine.ShowBand(BandBase band, Boolean getData)
   em FastReport.Engine.ReportEngine.StartFirstPage()
   em FastReport.Engine.ReportEngine.RunReportPage(ReportPage page)
   em FastReport.Engine.ReportEngine.RunReportPages()
   em FastReport.Engine.ReportEngine.RunReportPages(ReportPage page)
   em FastReport.Engine.ReportEngine.Run(Boolean runDialogs, Boolean append, Boolean resetDataState, ReportPage page)
   em FastReport.Report.Prepare(Boolean append)
   em FastReport.Report.Show(Boolean modal, IWin32Window owner)
   em NFe.Danfe.Fast.DanfeBase.Visualizar(Boolean modal) na C:\Users\CATALOG\Source\Repos\ZeusAutomacao\DFe.NET\NFe.Danfe.Fast\DanfeBase.cs:linha 52
   em NFe.Danfe.AppTeste.MainWindow.btnEventoNFe_Click(Object sender, RoutedEventArgs e) na C:\Users\CATALOG\Source\Repos\ZeusAutomacao\DFe.NET\NFe.Danfe.AppTeste\MainWindow.xaml.cs:linha 264

**Comment by mmedeirosbz** [comment]
detalhes do erro

**Comment by danilobreda** [comment]
é .net framework ou o core?

**Comment by mmedeirosbz** [comment]
.net framework

**Comment by mmedeirosbz** [comment]
O DANFE carrega normal.. o problema ocorre somente pra carta de correcao

**Comment by mmedeirosbz** [comment]
parece ser no relatorio.... fastreport

**Comment by danilobreda** [comment]
@mmedeirosbz no projeto demo do .net framework rodou na sua maquina? na do @marcosgerene rodou! Então é algo errado com seu código, tem algum datetime sendo gerado de maneira incorreta ai no seu código que influencia a impressão!
Em algum lugar vc manda pro fastreport um datetime customizado?

**Comment by mmedeirosbz** [comment]
Não mano... estou usando o projeto demo tb... da ultima versao... carrego os xmls da mesma forma que ele carregou e da o erro de conversao string pra datetime.. .

**Comment by marcosgerene** [comment]
@mmedeirosbz 

Não é no fast e nem no Zeus seu problema, é algo ai. Infelizmente, só debugando na sua máquina para saber.

Agora cabe ver se alguém da comunidade está disposto a prestar esse tipo de suporte de forma paga (acho bem difícil alguém topar um acesso remoto gratuitamente).
 
PS: Não estou falando de mim, eu não presto esse tipo de suporte/consultoria,mesmo que de forma paga, não tenho tempo hábil para tal.

**Comment by danilobreda** [comment]
Qual o formato de horário da sua maquina? GMT -3? Brasil? Ou está em formato americano? De qual estado você é?

**Comment by mmedeirosbz** [comment]
Sou do RJ e GMT -3 - Brasil ... mano no mesmo demo gero DANFE da NFe sem probelmas... o erro so ocorre no Danfe da carta de correcao..  realemnet deve ser problema do meu ambiente...  já descasquei a exception toda em busca do local exato e qual informacao que gera esse erro (datetime)

**Comment by mmedeirosbz** [comment]
Alguma outra sugestão???

**Comment by ThalisonSantos** [comment]
@mmedeirosbz vocês esta usando as dlls do Fast Report do projeto ou tem alguma versão sua?

**Comment by mmedeirosbz** [comment]
as dll sao as do projeto mesmo... tenho ate elas em outro projeto mas nao a uso... a referencia no demo esta nas que estao no projeto zeus..

**Comment by danilobreda** [comment]
@mmedeirosbz você poderia testar a edição que esta na branch [tentativa_1170](https://github.com/ZeusAutomacao/DFe.NET/tree/fix/tentativa_1170)
[https://github.com/ZeusAutomacao/DFe.NET/tree/fix/tentativa_1170](https://github.com/ZeusAutomacao/DFe.NET/tree/fix/tentativa_1170)
Fiz uma alteração caso o que eu ache que está acontecendo o erro que irá aparecer é "Erro - ZeusDFE dhEmi em formato incorreto." Verifica para mim isso?

Estou tentando de tudo para descobrir o problema 👍. Com certeza é ambiente, tenta testar também em outra maquina se possível!

**Comment by mmedeirosbz** [comment]
Usei essa branch e deu mesmo o erro que vc indicou... "Erro - ZeusDFE dhEmi em formato incorreto." 
![Screenshot_25](https://user-images.githubusercontent.com/15366975/94951831-5bc58980-04bb-11eb-8a3a-88cc9e12e52c.jpg)

**Comment by mmedeirosbz** [comment]
outra coisa:  no server windows 2012 onde publico minha aplicacao roda atraves do demo sem problema...

**Comment by danilobreda** [comment]
@mmedeirosbz ok, agora sabemos aonde está dando o problema 👍 vou dar uma analisada agora, com certeza vou chegar em um resultado.

**Comment by danilobreda** [comment]
@mmedeirosbz eu fiz outra alteração nesse mesmo branch, você poderia testar pra mim pra ver se o erro é resolvido?
Pode efetuar um PULL no git do branch ou mesmo baixar novamente.
No aguardo.

**Comment by danilobreda** [comment]
Só para entender seu problema, por algum motivo do ambiente/sistema operacional/configuracao de datas, sua "cultura" default é a **InvariantCulture**, fazendo com que a transformação de data cause problemas entre datetime e datetimeoffset...

Por Exemplo... No seu computador nesse exemplo abaixo vai dar erro nos 2 metodos, se testar em outra maquina(como acontece na minha) vai dar erro apenas no método _DaErro_
```
class Program
    {
        static void Main(string[] args)
        {
            var value = DateTimeOffset.Parse("2020-09-23T19:13:28-03:00", CultureInfo.InvariantCulture);
            var valueString = value.ToString();

            NaoDaErro(valueString);
            DaErro(valueString);
        }

        public static void NaoDaErro(string data)
        {
            var saida = (DateTimeOffset)DateTimeOffset.Parse(data);
        }

        public static void DaErro(string data)
        {
            var saida = (DateTimeOffset)DateTimeOffset.Parse(data, CultureInfo.InvariantCulture);
        }
    }
```

**Comment by mmedeirosbz** [comment]
Show Danilo,  aqui ocorreu assim:

- ao chamar danfe.visualizar; a aplicação teste trava, ate parece carregar o fast mas trava logo apos;
- ao chamar  danfe.ExportarPdf(@"c:\teste.pdf"); executa com sucesso e salva o pdf;

desde ja agradeço mano.. entendi o problema....

**Comment by danilobreda** [comment]
@mmedeirosbz legal que pelo menos conseguimos gerar algo :D quanto ao Fast não faço ideia do que pode ter acontecido :/ talvez ele mesmo está tendo problemas pra renderizar em sua maquina por talvez o mesmo motivo do problema acima.

@marcosgerene verifica se você acha interessante essa alteração no .frx do evento. Pois pelo que vimos é um caso isolado, mas faz sentido... Fiz o PullRequest.
Pelo jeito resolveu **parcialmente** o problema do nosso amigo porem não sei o que pode ocorrer nessa modificação.

**Comment by marcosgerene** [comment]
@danilobreda 

Tenho uma atualização do PostgreSQL grande para fazer no fds, sobrando um tempo testo com calma, te chamo no whatsapp caso eu tenha duvidas, abraço

**Comment by danilobreda** [comment]
@mmedeirosbz o código já está no branch principal nosso, o nugget será lançado em breve. Qualquer dúvida só abrir nova issue.
