### ISSUE TITLE
Sobrando muito papel na Impressão da NFC-e

### ISSUE THREAD

**Issue by dkraide** [ZeusAutomacao/DFe.NET#1172]
Oi pessoal, bom dia ! 
  Estou implementando o Zeus agora no meu projeto pela primeira vez, e estou com um probleminha. Ao imprimir a NFC-e, está sobrando muito papel no final. Alguém conseguiria me dizer como posso fazer pra solucionar ? Tentei procurar em outras Issues e não consegui =(. No exemplo a baixo nem está sobrando muito, tem outros exemplos que sobram bem mais.

![c398bbb1-6304-4b55-b1db-596ea060b939](https://user-images.githubusercontent.com/43674712/94341563-b012ca00-ffe0-11ea-927d-a9bb827b3353.jpg)

**Comment by marcosgerene** [comment]
@dkraide 

Isso é configuração da impressora/papel. Existe várias formas de resolver, mas você vai ter que manipular pc-a-pc. Eu simplesmente desisti disso e fiz um projeto para impressão em ESCPOS.

Segue: https://github.com/marcosgerene/Gerene.DFe.EscPos

[]'s
