### ISSUE TITLE
Erro ao imprimir DANFE no aspnet CORE

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1173]
Pessoal boa tarde.

Estou com esse erro ao gerar o byte do pdf do zeus :

                    Relatorio.Prepare();
                    Relatorio.Export(new PDFSimpleExport(), stream);
                    return stream.ToArray();

The operation is invalid [GDI+ status: Win32Error]

Esse problema ocorre no projeto NFe.Danfe.Fast.Standart na classe DanfeBase linha 53.
Fico no aguardo.

**Comment by danilobreda** [comment]
Erro acontece por conta do problema identificado na issue #1119 Antes era só comigo e consegui resolver em produção no .frx, como temos um caso com o mesmo problema vou solucionar logo a questão, até segunda já esta ok.
Estou em contato no Telegram com o desenvolvedor para pedir mais detalhes.

Como solução temporária foi passado para o dev não utilizar logo por enquanto.

**Comment by marcosgerene** [comment]
Vou fechar a issue porque a PR do @danilobreda resolve a questão.

Se o problema persistir, por favor reabra.
