### ISSUE TITLE
Manifesto de NF-e para contribuinte do RS não está funcionando

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#1175]
Manifesto de NF-e para contribuinte do RS não está funcionando.
Verificado que no fonte existia uma validação de quando o estado é RS atribuía o código 43 e não 91 para o órgão, causando rejeição no envio dos eventos de manifesto

**Comment by robertorp** [comment]
poderia mandar print, mais detalhes por favor?

**Comment by flavionootech** [comment]
Na criação do evento de manifesto da NF-e. o órgão para quando RS estava colocando o código 43 causando rejeição, alterado para 91 mesmo no RS e funcionou, chego a conclusão que o endpoint é do SVAN

**Comment by danilobreda** [comment]
@flavionootech esse problema é do Zeus ou algo que é configurável? Posso fechar a issue ou o problema permanece?

**Comment by danilobreda** [comment]
Por falta de retorno vou fechar a issue, qualquer coisa só abrir uma nova issue, ou voltar com as prints que reabro o mesmo 👍
