### ISSUE TITLE
Assinatura Digital NFCe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1177]
pessoal não se já ocorreu com alguém, mas notei que quando tenta validar um NFCe com um certificado vencido ele gera uma Comunicação Exception como uso essa exceção pra emitir em contingência está gerando muitas.

**Comment by guidi** [comment]
No meu caso quando o usuário abre a aplicação eu valido o certificado, se estiver vencido eu aviso o usuário e pergunto se quer mudar pro modo contingência permanente (todas as notas são geradas em contingência offline), caso ele confirme eu mudo, caso não, eu não permito o uso da aplicação.

**Comment by ThalisonSantos** [comment]
@guidi interessante vou ter que fazer algo desse tipo então

**Comment by robertorp** [comment]
Veja se ajuda 
https://github.com/AutomacaoNet/CertificadoExtNet

**Comment by ThalisonSantos** [comment]
@robertorp valeu deu uma boa facilitada aqui
