### ISSUE TITLE
Sem comunicação com o serviço NFeDistribuicaoDFe

### ISSUE THREAD

**Issue by AcciolyDSI** [ZeusAutomacao/DFe.NET#1179]
Olá, pessoal, tudo bem com vocês?

Tenho um job que roda a cada 2 horas com a função de buscar notas emitidas para um CNPJ e sempre que encontra ele registra 
as informações numa tabela da minha base de dados, posteriormente o front lista essa tabela para o usuário e na tela ele
pode dar ciência da emissão, confirmar, ou desconhecimento da operação ou ainda operação não realizada.

Isso serve para agilizar as entradas no sistema e a guarda dos xml baixados pois na ciência ou confirmação da operação o sistema baixa o xml e já deixa pré-lançado no sistema.

Acontece que sempre vejo no log Exception: NFe.Utils.Excecoes.ComunicacaoException: Sem comunicação com o serviço NFeDistribuicaoDFe: The operation has timed out

Vocês estão experimentando esse tipo de problema também? Pois aqui esta frequente.

Segue o log abaixo registrado pela minha aplicação:

03/10/2020 07:55:33 - Log Info -> Iniciando tarefa... NfeDistDFeInteresse
03/10/2020 07:55:33 - Log Info -> Começando a executar a tarefa... NfeDistDFeInteresse
03/10/2020 07:55:33 - Log Info -> Executando tarefa... NfeDistDFeInteresse
03/10/2020 07:55:33 - Log Info -> NSU: Obtendo o último nsu registrado
03/10/2020 07:55:33 - Log Info -> NSU: 6762
03/10/2020 07:55:33 - Log Info -> NfeDistDFeInteresse: consultando...
03/10/2020 07:55:39 - Log Erro -> Exception: NFe.Utils.Excecoes.ComunicacaoException: Sem comunicação com o serviço NFeDistribuicaoDFe:
The operation has timed out
   at NFe.Servicos.ServicosNFe.NfeDistDFeInteresse(String ufAutor, String documento, String ultNSU, String nSU, String chNFE) in E:\Projects\helix.api\Helix.Api.Invoice\NFe.Servicos\ServicosNFe.cs:line 809
   at Helix.Api.App.Jobs.Invoices.DfeJob.<NfeDistDFeInteresse>d__12.MoveNext() in E:\Projects\helix.api\Helix.Api.App\Jobs\Invoices\DfeJob.cs:line 72
03/10/2020 07:55:39 - Log Info -> Finalizando a execução da tarefa... NfeDistDFeInteresse

Se alguém puder me dar uma luz, ficarei imensamente agradecido.

Abraços

**Comment by danilobreda** [comment]
Na maioria das vezes eu recebo essa mensagem quando o SEFAZ está com algum problema, ou mesmo na rede, com problema de velocidade!
É esporádico ou frequente?

**Comment by AcciolyDSI** [comment]
Opa Danilo , tudo bem?

Rapaz com frequência, vez ou outra retorna um 503, serviço indisponível, com certeza é um problema na SEFAZ, esse serviço roda no ambiente nacional, então imagino que seja milhões consultando esse endpoint e o servidor deles não esta suportando tantos acessos, pois rodava bem a uns 7, 8 meses atrás +-. Revisei meu código, aumentei o intervalo de buscas mas mesmo assim a maioria das vezes retorna sem comunicação ou serviço indisponível. Postei o problema para saber se alguém estava tendo esse tipo de problema e se existe alguma mágica, macumba que possa melhorar. O meu job não para com o erro, ele continua rodando, o que me preocupou foi o número de insucessos é muito maior que o de sucesso, ou seja, ocorre muito mais serviço sem comunicação ou serviço indisponível que o retorno comum que seria nada encontrado ou notas encontradas. É uma api online então eu descarto problemas de rede, pois se fosse o sistema estaria fora do ar também e só ocorre consultando esse serviço específico.

Mesmo assim muito obrigado por me retornar

Abraços

**Comment by danilobreda** [comment]
@AcciolyDSI talvez o tempo de retorno desse serviço seja o que mais está se estendendo por isso apenas ele esteja dando erro... verifiquei o codigo e não achei nenhum problema que pelo menos me alertasse, a única questão seria a propriedade **TimeOut** que está na classe **ConfiguracaoServico**...  O default é 2000 ou seja 2 segundos, caso você não esteja setando ele, esse pode ser o problema, 2 segundos é muito pouco talvez para esse serviço especifico. Eu seto sempre 15(15000) segundos a 20 segundos(20000), verifica se ajeitando essa propriedade o problema é resolvido pelo menos resultando em um numero menor de erros.

Fico no aguardo.

**Comment by danilobreda** [comment]
Lembre-se que quando o certificado está vencido (se não estou enganado) esse erro também aparece ok?

**Comment by adrbarros** [comment]
Olá, Esses problemas estão acontecendo desde 30/09, hora busca algumas notas e hora não busca nada, acusando erro 503 ou Timeout (Obs.: meu timeout para esse serviço é de 60000. No grupo do Skype Zeus muitos estão passando pelo mesmo problema

**Comment by AcciolyDSI** [comment]
Olá @adrbarros, tudo bem ? Então era o que eu suspeitava, problemas na SEFAZ, eu precisava ter certeza que não era apenas eu com esse problema, valeu pelo retorno, tudo bom pra vc.

**Comment by AcciolyDSI** [comment]
> Lembre-se que quando o certificado está vencido (se não estou enganado) esse erro também aparece ok?

Minha api já faz essa gestão do certificado, qualquer chamada na SEFAZ só ocorre se existir um certificado válido cadastrado na aplicação.

**Comment by AcciolyDSI** [comment]
> @AcciolyDSI talvez o tempo de retorno desse serviço seja o que mais está se estendendo por isso apenas ele esteja dando erro... verifiquei o codigo e não achei nenhum problema que pelo menos me alertasse, a única questão seria a propriedade **TimeOut** que está na classe **ConfiguracaoServico**... O default é 2000 ou seja 2 segundos, caso você não esteja setando ele, esse pode ser o problema, 2 segundos é muito pouco talvez para esse serviço especifico. Eu seto sempre 15(15000) segundos a 20 segundos(20000), verifica se ajeitando essa propriedade o problema é resolvido pelo menos resultando em um numero menor de erros.
> 
> Fico no aguardo.

No meu é configurado em 15000, e não seria esse o problema, pois é apenas nessa consulta de notas destinadas, todo o restante funciona normalmente, emissão de NF-e e MDF-e, talvez aumentando o timeout apenas nessa consulta, mas ai começa a ficar meio que gambiarra, a SEFAZ é que deveria adotar um padrão e infelizmente não segue padrão algum, começa pelos nos nomes das propriedades, só Deus na causa. Valeu.

**Comment by AcciolyDSI** [comment]
Olá @danilobreda e @adrbarros, tudo bem com vocês?, Obrigado pela atenção e esclarecimentos, vou encerrar o post, pois era realmente um problema na SEFAZ e parece que resolveram, pois nos meus logs não esta mais aparecendo o erro. Abraços e tudo de bom pra vocês.

**Comment by apolovictor** [comment]
Qual o endpoint que voces utilizam para realizar a requisicao das ultimas nfes emitidas em nome do cnpj? Quais os parametros podem ser configurados? Data inicial e final? Os certificados? Eu so encontro para consulta por chave da nfe, nsu, o evento de recepcao para realicao a ciencia da operacao ou as outras opcoes de manifestacao... mas o principal nao encontro. A lista das ultimas nfes emitidas em nome do cnpj. E nao encontro nada nos manuais e schemas da sefaz.
