### ISSUE TITLE
Marca d'agua de NF-e Cancelada

### ISSUE THREAD

**Issue by SouzaMatheus-dev** [ZeusAutomacao/DFe.NET#1181]
Boa tarde. 

É possível mudar a cor da escrita quando a flag de documento cancelado está marcada?

![cancelado](https://user-images.githubusercontent.com/37388147/95983388-e9787180-0df7-11eb-92dd-cb0b68cf6785.png)

Pois por padrão ela vem cinza, e ai ocorre de ficar escondida a escrita. Como podemos ver no anexo.

**Comment by marcosgerene** [comment]
@SouzaMatheus-dev 

Sim, é possível, mas temos dois impecílios:
   1. Em impressoras preto-e-branco a gente tem que pensar em uma escala de cinza;
   2. Não podemos colocar "preto" ou mais forte do que isso, caso contrário, vai esconder os produtos presentes na nota.

O que poderia ser feito é algo parecido com o NFCe aonde a marcação do documento cancelado não é uma marca d'agua, mas sim um elemento que tem "seu próprio espaço" quando impresso.

De qualquer forma, se você tiver uma ideia para melhorar poste aqui, que posso te ajudar.

Ou se você quiser fazer uma alteração por conta própria, também é possível, só salvar o FRX modificado e referenciar ele ao chamar a impressão, eu faço isso quando personalizo algo para os clientes.

**Comment by SouzaMatheus-dev** [comment]
Entendi @marcosgerene. 
Vou levar em conta o que você comentou e assim que resolver isso eu posto aqui. 

O exemplo que o usuário me passou é esse abaixo (acho que ele não pensou nessa questão da impressão que você ponderou)

![image](https://user-images.githubusercontent.com/37388147/95998821-9f00f000-0e0b-11eb-8c99-e987ba16a287.png)

**Comment by marcosgerene** [comment]
@SouzaMatheus-dev 
A cor vermelha, quando impressa, vai ser um cinza claro, parecido com o nosso.

Agora quanto a questão dele "tomar a folha toda" e ser na diagonal é interessante sim

**Comment by SouzaMatheus-dev** [comment]
Beleza. 
Estou tentando fazer a alteração no arquivo FRX como sugeriu. Mas ainda não consegui alterar a cor, para ver como fica.

**Comment by marcosgerene** [comment]
Testa esse aqui:

[teste1.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5381623/teste1.zip)

**Comment by SouzaMatheus-dev** [comment]
Tá ok, vou testar aqui. No caso esse exemplo de teste você alterar no NfeRetrato.frx ?

Eu pensei que fosse no NfeEvento.frx. Talvez eu estivesse alterando no arquivo errado

**Comment by marcosgerene** [comment]
NFeRetrato.frx

**Comment by danilobreda** [comment]
@marcosgerene  Caso "Girar o texto" pode dar problema pra mim gerar em HTML via openfastreport, caso for gerar um pull disso vou testar depois pra ver como fica.

**Comment by marcosgerene** [comment]
@danilobreda 
Nesse caso, não vou sequer cogitar abrir um PR dessa alteração. Com o frx que enviei, o @SouzaMatheus-dev pode usar de forma personalizada, faço isso com alguns clientes.

Abraços

**Comment by SouzaMatheus-dev** [comment]
Muito obrigado pelas dicas. Estou customizando meu arquivo. 
No momento eu fiz retirada da cor que preenche os campos do header. Pois pensando na impressão, eu mantenho a escala de cinza e como retirei os preenchimentos dos campos, fica visível e sem corte a marca d'água.

![Sem título](https://user-images.githubusercontent.com/37388147/96151377-bc07f280-0ee1-11eb-87df-68a54906a6ef.png)


O resultado como solicitado pelo cliente ficou assim:

![Sem título](https://user-images.githubusercontent.com/37388147/96152436-edcd8900-0ee2-11eb-9897-31f8eab89f7f.png)
