### ISSUE TITLE
Duvida NFe.AppTeste.NetCore

### ISSUE THREAD

**Issue by iannkzw** [ZeusAutomacao/DFe.NET#1182]
No projeto NFe.AppTeste.NetCore, o metodo CarregarNSUs já faz a ciência da operação por baixo dos panos? Sempre que uso, ele já traz uma resNfe e uma procNfe referente com a mesma chave...
Gostaria de saber se é exatamente isso que ele faz ou se tenho que usar manifestar a ciência da operação antes..

**Comment by danilobreda** [comment]
Internamente ele chama o método **NfeDistDFeInteresse** que tem a seguinte descrição: _Serviço destinado à distribuição de informações resumidas e documentos fiscais eletrônicos de interesse de um ator, seja este pessoa física ou jurídica._

O mesmo pelo que verifiquei apenas pesquisa as notas, ele não faz ciencia da operação. 
A Ciencia de operação é apenas executada internamente no metodo **RecepcaoEvento** com evento do tipo **ServicoNFe.RecepcaoEventoManifestacaoDestinatario**
Esse metodo não é chamado pelo CarregarNSUs  do NFe.AppTeste.NetCore 👍
