### ISSUE TITLE
Impressão do CUPOM no ASPNET.CORE 3.1

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1183]
Pessoal tudo bem?

Gostaria de saber se existe uma previsão para que a impressão do cupom fiscal NFCe estreja pronto .
Quando eu vou fazer a impressão no netcore ocorre essa mensagem abaixo:
NFCE ainda não implementado para .netstandard ou .netcore, apenas disponivel em .net framwork. Crie uma issue no nosso github para mais informações: https://github.com/ZeusAutomacao/DFe.NET

Segue o meu metodo:
 private static DanfeFrNfce GeraClasseDanfeFrNCe(string xml, byte[] logoempresa, string Token, string Csc)
        {
            try
            {
                #region Carrega um XML com nfeProc para a variável
                nfeProc proc = null;
                try
                {
                    proc = new nfeProc().CarregarDeXmlString(xml);
                }
                catch //Carregar NFe ainda não transmitida à sefaz, como uma pré-visualização.
                {
                    proc = new nfeProc() { NFe = new NFe.Classes.NFe().CarregarDeXmlString(xml), protNFe = new NFe.Classes.Protocolo.protNFe() };
                }

                if (proc.NFe.infNFe.ide.mod != ModeloDocumento.NFCe)
                {
                    throw new Exception("O XML informado não é um NFCe!");
                }

                #endregion

                DanfeFrNfce danfe = new DanfeFrNfce(proc: proc, configuracaoDanfeNfce: new ConfiguracaoDanfeNfce()
                {
                    Logomarca = logoempresa,
                    DocumentoCancelado = false
                }, Token, Csc);
                
                return danfe;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
Obrigado pela atenção!

**Comment by danilobreda** [comment]
@khaddmussistemas a emissão está funcionando? É só a impressão que não está? Pois na época eu **não** implementei ambos para .net core.

**Comment by denernun** [comment]
Bom dia,

A emissão funciona perfeitamente em net core, uso na webapi netcore 3.1 sem
problemas.

A impressão de NFC-e não está implementado ainda. Eu uso um monitor no
cliente, que já tinha em Delphi/ACBr/Redis para fazer a impressão.

**Comment by leandrovip** [comment]
Se estiver utilizando mini-impressora (impressora não fiscal) para a função e se for SO Windows, talvez possa utilizar o https://github.com/marcosgerene/Gerene.DFe.EscPos para realizar a impressão.

[]´s

**Comment by danilobreda** [comment]
Acredito que vou conseguir implementar em breve (no máximo 1 mes), caso alguém tenha interesse em contribuir, o processo inicialmente deve ser o parecido com o que foi feito no DANFE do NFe para .net core.

**Comment by danilobreda** [comment]
@marcosgerene faz sentido gerar a impressão desse recurso sendo que já existe o seu projeto [https://github.com/marcosgerene/Gerene.DFe.EscPos ](https://github.com/marcosgerene/Gerene.DFe.EscPos) ? No caso a gente deixaria como "não suportado" esse recurso e indicaria para uso a sua biblioteca. (Isso principalmente indicado no readme)

**Comment by marcosgerene** [comment]
@danilobreda 

Eu não usaria nem em .Net Full a impressão do Zeus para NFCe mais. 

A unica vantagem é a questão de personalização, editar o FRX ao gosto do cliente. Mas isso demanda tempo e conhecimento, alem do que se trata de um documento fiscal, não tem muito o que adaptar.

As desvantagens da configuração de tamanho pesam mais pra mim, por isso parti para EscPos.

Concluindo, acho um esforço desnecessário.

**Comment by danilobreda** [comment]
@robertorp também gostaria de saber a sua opinião sobre 👍

**Comment by danilobreda** [comment]
@marcosgerene @robertorp  talvez o único ponto positivo que vejo seria a impressão em pdf, html etc.. que para um sistema do web é interessante... mas eu n me arrisco a aplicar NFCe em pdf no sistema web hoje que tenho... o mesmo deve dar mto bugs e dor de cabeça... por conta de navegadores e padrões de impressoras. Dor de cabeça que já tenho com NFe em alguns clientes.. Imagina um frente de caixa!

**Comment by denernun** [comment]
Olá,

Tenho um sistema web emitindo NFCe, e essa questão da impressão em PDF só é
interessante para envio ao cliente por email ou a visualização em tela,
para impressão em impressoras térmicas, sobra muito papel, e os clientes
reclamaram tanto, que tive que criar um "monitor de impressão" para uso
local.

Sem problemas até agora.

**Comment by danilobreda** [comment]
Vou fazer a implementação por conta da necessidade possível de previsualização em HTML e envio de email do PDF... porem não recomendamos o uso do mesmo no caso de impressão direto em impressora. Utilizem  https://github.com/marcosgerene/Gerene.DFe.EscPos

Vou fechar a issue, pois o mesmo será feito junto a issue #1198

**Comment by danilobreda** [comment]
Implementado impressão de NFC-e em #1280
