### ISSUE TITLE
Impressão de Danfe Asp.Net Core com muitos itens e dados adicionais grande

### ISSUE THREAD

**Issue by evertonbatini** [ZeusAutomacao/DFe.NET#1184]
Quando tem muitos itens e muitos dados adicionais, está sobrepondo os textos conforme a imagem:

![image](https://user-images.githubusercontent.com/46816210/96639652-63c55c00-12f8-11eb-817f-b3f6d947a003.png)

**Comment by danilobreda** [comment]
Esse problema tinha na versão antiga do .frx, o mesmo foi atualizado dia 08/10/2020.
Segue um DANFE meu gerado nessa nova versão em produção no meu sistema
[93_35201010331198000140550070000000791811854190.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/5412000/93_35201010331198000140550070000000791811854190.pdf)

Verifica se atualizando o **frx** o problema é resolvido.

**Comment by danilobreda** [comment]
Resolvido em #1127
Mesma dúvida em #1160
Resolvido para .net core em #1178

**Comment by evertonbatini** [comment]
@danilobreda Estou utilizando sem passar o .frx, o Zeus pega do Resources e após atualizar o NuGet da o seguinte erro ao gerar o danfe: "System.MissingMethodException: 'Method not found: 'System.DateTime NFe.Classes.Protocolo.infProt.get_dhRecbto()'.'"

![image](https://user-images.githubusercontent.com/46816210/96716294-3bcb0c80-137b-11eb-9dbb-6311f9a5e367.png)

Era pra funcionar usando pelo NuGet? Ou devo baixar o .frx e passar o caminho do arquivo?

**Comment by danilobreda** [comment]
Verifica se os nugets estão atualizados td certinho, tenta executar o mesmo via clone do github aqui e ve se acontece tambem, se acontecer é um bug nosso, caso contrario tem haver com algo na versão sua que está utilizando do nuget/dlls
Tem um dotnet core demo pra te ajudar nisso.

Será que tem haver com o #1164 @marcosgerene ?
Eu lembro que alguém já falou desse problema...

**Comment by marcosgerene** [comment]
@danilobreda 

Uso o Zeus em dois projetos, em um compilo ele na mão, em outro a estrutura de impressão é bem modificada.

De qualquer forma, o erro que ele ta recebendo é porque as versões de referência da impressão e do sistema não batem, aposto uma caixinha de bigbig que tem referencia errada ai... rs

**Comment by danilobreda** [comment]
@evertonbatini conseguiu resolver o problema, ou executou o teste no projeto nosso aqui e verificou se o mesmo da erro?

**Comment by evertonbatini** [comment]
@danilobreda 

Estou achando que pode ser essa coluna no frx

`<Column Name="dhRecbto" DataType="System.DateTime"/>`

Acredito que precisa mudar o tipo para System.DateTimeOffset

Eu ajustei aqui local, mas não estou conseguindo passar o arquivo físico do frx pra testar, eu passo um arquivo que não existe e mesmo assim o erro que dá é ref. o campo dhRecbto :(

Se não for isso, realmente não tenho ideia, porque não tem referencia adicionada aqui, apenas instalei o pacote pelo NuGet mesmo.

**Comment by danilobreda** [comment]
É realmente não entendi muito bem o que está acontecendo, temos vários usuários que utilizam sem problemas... o arquivo do .frx é [esse aqui](https://github.com/ZeusAutomacao/DFe.NET/blob/b0b12b544cf7fc5d753220505f5b4d684acb36ca/NFe.Danfe.Fast.Standard/NFe/NFeRetrato.frx). Verifica se é esse mesmo, quanto ao nuget, não temos ainda o projeto DANFE no nuget, por isso acredito que talvez esteja com código antigo ai...

Como te falei anteriormente, se você dar um clone limpo no nosso projeto aqui do github e testar nele, via projeto do danfe .net core ele funciona perfeitamente? ou está dando problemas? A gente precisa saber se é problema do seu ambiente ou do nosso código, sem isso difícil a gente solucionar esse problema.

Temos que ter a possibilidade de replicar o problema nas nossas maquinas.

Qualquer coisa cria um projeto Demo do problema e sobe em um github seu, eu ja fiz muito isso... e funciona mto bem.

**Comment by evertonbatini** [comment]
humm o danfe não está no NuGet, então é isso

**Comment by evertonbatini** [comment]
Era isso mesmo, resolvido 

![image](https://user-images.githubusercontent.com/46816210/97360029-6554ce00-187c-11eb-8c2a-5bc7bb255ec3.png)

**Comment by danilobreda** [comment]
@evertonbatini Top fico feliz em ter ajudado 👍
