### ISSUE TITLE
Erro 403 - Forbidden MDFe Homologação

### ISSUE THREAD

**Issue by caviunabruno** [ZeusAutomacao/DFe.NET#1185]
Estou implementando o MDFe aqui na empresa e desde quarta quando estava fazendo testes estou tendo esse erro, já emiti alguns manifestos em homologação mas agora só me retorna esse erro.

Se tento acessar os links de homologação: https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeRecepcao/MDFeRecepcao.asmx tenho o mesmo erro.

Às vezes ocorre também com o link de produção. Alguém mais com esse erro ou alguém que saiba me dizer se isso é temporário?

**Comment by caviunabruno** [comment]
O erro acontece com todos os serviços do MDFe.

Estou usando TLS 1.2

**Comment by danilobreda** [comment]
Com certeza seu certificado expirou... verifica ai

**Comment by caviunabruno** [comment]
Era isso mesmo, acabei testando com outro cliente e não tive o erro, mas eu jurava que já tinha feito esse teste anteriormente e que tinha dado erro também... rs.

Mas eu fiquei na dúvida com o seguinte: se eu consulto status do serviço de NFe nesse cliente que estava dando erro no MDFe diz que o certificado ainda é válido, o erro só acontecia mesmo com o MDFe, tá certo isso? Não é o mesmo certificado para as duas operações?

![retornocertificado](https://user-images.githubusercontent.com/39994930/97167285-50394b80-1765-11eb-953c-5f04938cb5db.JPG)

**Comment by danilobreda** [comment]
É sim porem os certificados da NFe (a validação de certificado no servidor da NFe) costumam demorar um pouco mais para serem invalidados. Talvez se esperar alguns dias vc vai começar a receber um retorno diferente ai no status.

Uma coisa interessante... Pela janela de dias ser grande, vários clientes ligam na empresa reclamando (no mesmo dia e horário) que  "ta dando erro", e confundimos até com erro do software, pelo grande número de clientes reclamando, mas sempre é porque nesse dia a NFe realmente invalidou o status de vários certificados que já haviam sido expirados.

**Comment by caviunabruno** [comment]
Maravilha Danilo, obrigado pelos esclarecimentos!
