### ISSUE TITLE
A conexão subjacente estava fechada: Erro inesperado em um envio.

### ISSUE THREAD

**Issue by dirceudvc** [ZeusAutomacao/DFe.NET#1186]
Olá pessoal, estou tentando consultar o Status do Serviço como Homologação, meu certificado é o A1, windows 7, TLS 1.2, estou estudando o ZEUS automação em C#, mas esbarrei nesse problema e não consigo avançar, o que eu poderia estar verificando para conseguir consultar o Status do Serviço.
Obrigado.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/1092

**Comment by danilobreda** [comment]
@dirceudvc conseguiu resolver o problema?

**Comment by dirceudvc** [comment]
Olá Danilo, ainda não deu certo, tentei de várias formas, habilitando o emulador, tentando como homologação e produção, mesmo encontrando vários tópicos com esse problema, não consegui resolver, debuguei, até cheguei na linha que dava o problema, mas não consegui, meu sistema operacional é windows 7 Ultimate.

**Comment by danilobreda** [comment]
Primeiro passo seria sair do windows 7 para desenvolvimento, e partir para windows 10... [Windows 7 já está sem suporte da microsoft desde janeiro de 2020](https://support.microsoft.com/pt-br/windows/o-suporte-ao-windows-7-terminou-em-14-de-janeiro-de-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962).
 Outro passo seria identificar se o mesmo problema acontece em outras maquinas... se sim, ou é a rede do seu ambiente, ou o próprio certificado estar vencido.
Você está utilizando .net core ou .net framework 4.x?
Qual linha está dando o problema?

**Comment by dirceudvc** [comment]
Olá Danilo, ainda não testei no Windows 10, meu certificado A1, estava quase vencendo quando fiz os testes, mas, essa semana eu renovei, irei realizar esses testes que você disse e retorno com o resultado, obrigado por sua atenção.

**Comment by dirceudvc** [comment]
Olá, Estou debugando pelo Windows 10 Pro em outra máquina, estou utilizando o .net framework 4.5 certificado A1 com data renovada, a internet está conectando normalmente, gostaria de saber se é necessário o Emulador Sat-Cfe estar executando.
Na aba Certificado, informei o numero de série
Na aba Geral, marquei Normal e Tipo de Docto NFCe
Na aba WebService, marquei Homologação e tudo 3.10 e TimeOut(milisegundos) 10000
Na aba Emitente, Email e Danfe, não informei nada
O erro ocorre em Nfe.AppTeste em BtnStatusServico_Click, nessa linha:
var retornoStatus = servicoNFe.NfeStatusServico();

Debugando linha a linha, está dando esse erro:
Unable to automatically step into the server. Connecting to
the server machine 'homologacao.nfce.fazenda.sp.gov.br'
failed. The Visual Studio 2015 Remote Debugger
(MSVSMON.EXE) does not appear to be running on the
remote computer. This may be because a firewall is preventing
communication to the remote computer. Please see Help for
assistance on configuring remote debugging.

**Comment by robertorp** [comment]
desativa o ant virus e tente novamente (somente um teste... não sei se é isso.. somente seguindo o que diz a exception)

**Comment by denernun** [comment]
A versão dos serviços deve ser 4.0 e não 3.10.

**Comment by dirceudvc** [comment]
Desativei o Antivírus(AVG), continua dando a mesma mensagem de erro, quanto a versão dos serviços, não tenho essa opção na Aba WebService, só existem as opções 1.00, 2.00 e 3.10

**Comment by denernun** [comment]
Estranho....será que vc não está usando uma versão desatualizada ? Meu
AppTeste roda beleza....

[image: image.png]

**Comment by danilobreda** [comment]
Essa deveria ser a tela... Acredito que esteja desatualizado o seu Zeus
![image](https://user-images.githubusercontent.com/14843499/99976183-e15e0b00-2d81-11eb-89b0-00ced17615a7.png)

**Comment by dirceudvc** [comment]
Realmente, então a versão do meu Zeus, está desatualizado, por favor, para baixar a versão atualizada, seria em github.com/ZeusAutomação/DFe.net, clicar em  Download ZIP ?
Obrigado.

**Comment by robertorp** [comment]
isso @dirceudvc  so clicar no download zip que baixa os fontes completos, ou simplesmente referencia no nuget.. no meu sistema uso a versão do nuget.

**Comment by dirceudvc** [comment]
Pelo GitHub, selecionei alberteije/SAT-CF-e-CSharp, selecionei Code e baixei o Download ZIP, mas essa versão não está atualizada, não tem o 4.00

**Comment by robertorp** [comment]
alberteije?  isso é um repositorio a parte dos cursos T2TI , acho que ele sabera resolver sua dúvida, mas por alto digo 
os repositorios dele provavelmente não estão com Zeus atualizado, motivo de BO mas.. esse especifico que vc mandou CF-e = SAT isso? aí é outra historia ...

**Comment by dirceudvc** [comment]
Entendi, comprei o curso que vem com apostila, achei que aqui estaria atualizado, irei fazer o download pelo ZeusAutomacao/DFe.NET, e tentar executar para estudar como funciona, muito obrigado a todos pela atenção.

**Comment by danilobreda** [comment]
Acredito que o problema foi solucionado, qualquer outra dúvida só abrir uma issue novamente 👍

**Comment by vagnercardosomagalhaes** [comment]
Pessoal, estou usando C# no Visual Studio 2015 e  recebo essa mesma mensagem de erro qdo rodo um teste aqui em casa. Estou tentando fazer uma consulta por cnpj. 
O erro acontece qdo chega na parte -> string json = cliente.DownloadString(url);

Public static Empresa ObterCnpj(string cnpj)
{
string url = "https://www.receitaws.com.br/v1/cnpj/" +cnpj;
Cliente WebClient = new WebClient();
Client.Encoding = Encoding.UTF8;
string json = cliente.DownloadString(url);
var empresa = JsonConvert.DeserializeObject(json);
retornar empresa;

}

Obrigado pela força!
