### ISSUE TITLE
Campos "PesoL" e "PesoB" na classe "veicProd" com tipo incorreto

### ISSUE THREAD

**Issue by rrpinajr** [ZeusAutomacao/DFe.NET#1187]
Os campos "PesoL" e "PesoB" da classe veicProd estão como decimal, porém ele deve ser do tipo string de acordo com o manual e schema.

(PesoL-Peso Líquido - em Toneladas 4 casas decimais)
(PesoB-Peso Bruto - em Toneladas 4 casas decimais)
A descrição informam casas decimais, o tipo informa string. 

Tenho uma situação crítica para solucionar, a manifestação do SEFAZ está trazendo uma NFe onde estes campos estão preenchido com um valor usando o "vírgula como separador" o que falha a serialização para a classe (NFe.Classes.NFe).

**Comment by danilobreda** [comment]
Você pode compartilhar o xml do nfe que está dando problema ao serializar para testes se possível?
Caso você queira, pode fazer a modificação e realizar um pullrequest.

**Comment by rrpinajr** [comment]
Como faço para anexar o modelo xml ao PR?

**Comment by rrpinajr** [comment]
Segue o modelo do xml como solicitado.

[xml_modelo_falha_serializacao_veicProd.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5454367/xml_modelo_falha_serializacao_veicProd.zip)

**Comment by rafjsouza** [comment]
@danilobreda creio que deve ser o mesmo caso dessa issue #1102

**Comment by rrpinajr** [comment]
Sim, inclusive utilizei esta #1102 de modelo, para fazer referência ao campos que no meu xml falhou...

A propósito segue o modelo de xml com "cStat"=302" - Uso Denegado: Irregularidade fiscal do destinatário


[Modelo-nfeProc-denegada.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5454424/Modelo-nfeProc-denegada.zip)

**Comment by danilobreda** [comment]
Esperar o @marcosgerene se posicionar pois não tenho muito conhecimento de como arrumar isso :/

**Comment by rrpinajr** [comment]
Esse último, o cStat (tag protNFe) está declarado com tipo 'byte", o valor "302" estoura o tamanho de 255 bits... precisa mudar pelo menos para  o tipo "short" ou "int"

**Comment by marcosgerene** [comment]
@danilobreda

O campo é C segundo o manual, ou seja, é uma string. Na minha visão é ridículo, mas é o que tem pra hoje.
Quanto ao cStat no protNFe nunca entendi o porque ser byte.

Nesses ultimos 20 dias e nos próximos 20 dias estou bem atolado de serviço, vou tentar contribuir com código, mas acho bem improvável, talvez o @robertorp ou o @danilobreda possam te ajudar, mas em ambos os casos a suas observações são válidas.

[]'s

**Comment by marcosgerene** [comment]
@danilobreda

O campo é C segundo o manual, ou seja, é uma string.

Nesses ultimos 20 dias e nos próximos 20 dias estou bem atolado de serviço, vou tentar contribuir com código, mas acho bem improvável, talvez o @robertorp ou o @danilobreda possam te ajudar, mas em ambos os casos a suas observações são válidas.

[]'s

**Comment by marcosgerene** [comment]
@rrpinajr 
Por favor, teste esse PR https://github.com/ZeusAutomacao/DFe.NET/pull/1189

**Comment by rafjsouza** [comment]
Bom dia @danilobreda  e @marcosgerene . Eu e o @rrpinajr  testamos o PR #1189 com as ultimas modificações e funcionou, muito obrigado. Agora como funciona para aprovar o PR e ir para a versão do nuget?

**Comment by marcosgerene** [comment]
O @robertorp é o cara do nuget, vou conversar com ele.

[]'s

**Comment by robertorp** [comment]
vou fazer sim, amanhã de manhã! antes do meio dia !
