### ISSUE TITLE
InfEventoEnv dhEvento para DateTimeOffset

### ISSUE THREAD

**Issue by rafjsouza** [ZeusAutomacao/DFe.NET#1191]
Mesma situação da issue #1164  porém para a classe NFe.Classes.Servicos.Evento.infEventoEnv, peguei a mesma situação onde o xml está com -04:00 mas está sendo serializado para  -03:00.

Abri um PR para resolver: #1190

**Comment by rafjsouza** [comment]
@danilobreda ou @marcosgerene assim que puderem podem me ajudar nessa questão?

**Comment by marcosgerene** [comment]
@rafjsouza 

Olhei o PR e para mim está ok. 
Não vou aceitar porque estou sem tempo para testar. 
Vou aguardar o @robertorp ou o @danilobreda testar.

[]'s
