### ISSUE TITLE
Cancelamento para o Estado PE: Falha no schema.

### ISSUE THREAD

**Issue by IgorOliveiraVilaNova** [ZeusAutomacao/DFe.NET#1192]
![Erro cancelamento](https://user-images.githubusercontent.com/2027566/97599221-7cafca80-19e6-11eb-8368-548d4f7e6700.jpg)

Estou efetuando o preenchimento de todos os dados para o cancelamento de uma nota, mas acaba ocorrendo erro do schema.
Nesse caso, Isso ocorrem em ambiente de produção, mas em homologação não ocorre esse erro do schema.

**Comment by danilobreda** [comment]
Olá @IgorOliveiraVilaNova qual é o erro completo que está dando do schema? Você poderia nos enviar o xml que está sendo gerado, e dando erro do evento de cancelamento?

**Comment by IgorOliveiraVilaNova** [comment]
O erro que é retornado para mim no retorno é:
215 - Rejeição: Falha no esquema XML

`<envEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>1</idLote><evento versao="1.00"><infEvento Id="ID1101112620104085461400023655002000000411127637670601"><cOrgao>26</cOrgao><tpAmb>1</tpAmb><CNPJ>40854614000236</CNPJ><chNFe>26201040854614000236550020000004111276376706</chNFe><dhEvento>2020-11-03T18:14:22+00:00</dhEvento><tpEvento>110111</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Cancelamento</descEvento><nProt>126200078587327</nProt><xJust>Produto lançado errado</xJust></detEvento></infEvento></evento></envEvento>`

Somente removi as tags de Signature, mas se necessário, volto a anexar o XML com a Signature.

**Comment by danilobreda** [comment]
@IgorOliveiraVilaNova Esse problema é estranho pois muitos de nós utilizamos esse cancelamento e funciona 100%... O que acontece as vezes é o usuário colocar um espaço a mais ou caractere especial na **justificativa** as vezes causando esse problema...

Verifica se o problema acontece apenas nesse estado ou em outros tambem, é algo momentâneo ou acontece todas as vezes?
Verifica também se dando um clone no código daqui e executando o mesmo acontece... pois se você estiver utilizando uma versão antiga do Zeus, pode acontecer esse problema tambem.

Outra questão que pode ser também, você está indicando nas configurações o ambiente correto (Servidor do SVRS por ser PB na versão de evento 4.0) ?

**Comment by robertorp** [comment]
Enter também veja se é isso, passei por um problema com a tecla enter estes dias

**Comment by IgorOliveiraVilaNova** [comment]
@danilobreda
Cheguei a acompanhar com o cliente esse cancelamento, e executamos também usando somente caracteres normais na justificativa, mas o mesmo erro acontece.
Somente ocorreu nesse estado, em outros estados o cancelamento funcionou perfeito. Esse cliente fez várias requisições em horários diferentes e o mesmo erro ocorre.

O que mais achei estranho é que em desenvolvimento não ocorre esse erro, então acredito eu que a configuração do serviço está OK também.
O que vi de diferença da requisição em produção para a homologação é que a data em Homologação estava como -03:00, mas em produção está como +00:00
Por acaso essa mera mudança de fuso pode ocorrer falha de esquema?

Edit: Só pra desencargo, a configuração do serviço que estou fazendo é essa:
![ConfigServico](https://user-images.githubusercontent.com/2027566/98120522-cf78fe80-1e8c-11eb-93a2-ad8cc8b2fd44.jpg)

**Comment by danilobreda** [comment]
@marcosgerene @robertorp  será que as alterações que ocorreram para DateTimeOffset está causando esse tipo de erro? Realmente não sei qual problema pode ser...

**Comment by rafjsouza** [comment]
@danilobreda para essa classe o Pull Request que altera para DateTimeOffset o dhEvento da classe NFe.Classes.Servicos.Evento.infEventoEnv (#1190)  ainda está pendente, então no master ele ainda está como Datetime. Creio que a alteração para DateTimeOffset deve ajudar a resolver esse problema, visto que o que o @IgorOliveiraVilaNova falou sobre o fuso horário pode sim ocasionar falha. 

No manual fala que o fuso horário deve ser um dos seguintes valores para dhEvento:
 **_Data e hora do evento no formato AAAA-MMDDThh:mm:ssTZD (UTC - Universal Coordinated Time,
onde TZD pode ser -02:00 (Fernando de Noronha), -03:00
(Brasília) ou -04:00 (Manaus), no horário de verão serão -
01:00, -02:00 e -03:00. Ex.: 2010-08-19T13:00:15-03:00._**

Página 42 do manual:
![image](https://user-images.githubusercontent.com/22361235/98149070-e11dce80-1eab-11eb-8998-3ab14f264ed6.png)

@IgorOliveiraVilaNova, o fuso horário do servidor de produção deve estar diferente dos valores permitidos, sendo assim ao serializar o objeto Datetime para XML, como Datetime não possui GMT, vai ficar o padrão da máquina.

**Comment by danilobreda** [comment]
@IgorOliveiraVilaNova  o problema ainda ocorre? Nesses últimos meses os servidores do SEFAZ tem tido alguns problemas malucos, talvez esse tenha sido o caso...

**Comment by IgorOliveiraVilaNova** [comment]
@danilobreda Cara, estava ocorrendo sim. O horário do meu servidor está como +00:00 e não posso efetuar a mudança desse fuso, por conta de todas as outras funcionalidades do sistema. Mas acabei recompilando o projeto com as mudanças que eu precisava e apliquei no meu sistema.

Sobre isso: Não poderiamos ter um valor fixo de fuso horário? Ou então nas configs do serviço definirmos qual será o fuso para não termos problemas com a configuração do servidor?

**Comment by robertorp** [comment]
Mas não é interessante, enviar do cliente via request não? digo data hora completo junto com fuso horário

**Comment by IgorOliveiraVilaNova** [comment]
Sim, seria interessante também essa opção.

**Comment by danilobreda** [comment]
@IgorOliveiraVilaNova 
[https://github.com/ZeusAutomacao/DFe.NET/issues/1164#issuecomment-691045269](https://github.com/ZeusAutomacao/DFe.NET/issues/1164#issuecomment-691045269)
Aqui eu mostro como faço via requisição, antes da impressão eu altero os campos de data/hora... Deve funcionar da mesma maneira para a emissão, pois são campos de datas... Igual o @robertorp disse. 

Tem um problema de multifilial em diferentes fusos que esse código resolve na impressão.

**Comment by IgorOliveiraVilaNova** [comment]
@danilobreda Mas o porém é que o erro é mais ao enviar o evento

**Comment by danilobreda** [comment]
@IgorOliveiraVilaNova o xml que está sendo gerado do evento é o mesmo e utilizado por varias empresas que utilizam o ZEUS, acredito que pernambuco é um estado bem nichado, como o problema está acontecendo apenas lá, **eu entraria em contato com o SEFAZ da região** ou algum departamento deles para que possam resolver esse problema com você ou indicar a falha. Lembrando que verifiquei o xml que vc nos deu com gerados do ZEUS e outros em produção que tenho e até mesmo XMLS da internet de outros sistemas, e todos estão da mesma maneira, no mesmo padrão, principalmente o campo de data/hora (+00), por isso não acho que o Zeus irá resolver algo ou é o problema.

**Comment by rafjsouza** [comment]
@danilobreda no método **ServicosNFe.RecepcaoEventoCancelamento** poderíamos receber como parâmetro opcional a data do evento (dhEvento) e atribuir o Datetime.Now para o dhevento somente se este não for passado por parâmetro. Como o dhEvento já está como DatetimeOffset, isso possilitará passar o GMT nesse parâmetro.

**Comment by danilobreda** [comment]
@rafjsouza fiz a solução, no pullrequest fiz algumas perguntas para a implementação, se você poder me ajudar a responder fico grato :D

**Comment by rafjsouza** [comment]
@danilobreda  respondido.

**Comment by danilobreda** [comment]
Issue resolvida
