### ISSUE TITLE
RetornoNFeDistDFe com informações divergentes

### ISSUE THREAD

**Issue by felixsevero** [ZeusAutomacao/DFe.NET#1193]
Estou utilizando o AppTeste para aprender sobre a Distribuição de Documentos. Percebi que uma parte do retorno é diferente para eventos diferentes. Por exemplo, a tag `detEvento` para um evento de cancelamento é:
```XML
<detEvento versao="1.00">
    <descEvento>Cancelamento</descEvento>
    <nProt>143200000979796</nProt>
    <xJust>Testando o evento de cancelamento para a Manifestação do Destinatário.</xJust>
</detEvento>
```
Enquanto a mesma tag para o evento da carta de correção é:
```XML
<detEvento versao="1.00">
    <descEvento>Carta de Correção</descEvento>
    <xCorrecao>Testando a Carta de Correção para a Manifestação do Destinatário.</xCorrecao>
    <xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso>
</detEvento>
```
Com isso, as informações para o evento da carta de correção não são exibidas adequadamente, como na imagem:

![image](https://user-images.githubusercontent.com/23054347/97615919-a8d54680-19fa-11eb-8276-2ced0b37e8e1.png)

Eu sei que o retorno da Sefaz está correto, pois deserializei manualmente o retorno, que está no formato gZIP, como abaixo:
```XML
<loteDistDFeInt>
  <docZip NSU="106" schema="procEventoNFe_v1.00.xsd">H4sIAAAAAAAEAK1Y2ZLi2LX9FaL8SGdJQghQmcoIjSCBBJqR3oQkNA9olv6mww8d90b4B/zY+WM+gqyh22Vfu32JhDzD3muPZ8c5e1uUucO0XlbnIuvNWq+s7PzzB+QjDH+Y9WmSVZ8/BHVdfIKgrus+FnlZ28ktrBw7+Rhmt4/XEspu3ofXrffA+C8AwOSpx4xzP3/gaASBwd8SXcAIjC7W2AZBcRiGERzDMPAPfnwQeIFgCL5aLVcoBiMAxjmVvp2/LtEt9D7c1gWRXl8XW+g52FLimX/9LeQWeixunQB44fU/EQrEPHi2bvBU/3UBL+AXBH5ZbFQE+wTjn7DlC4x+guEt9JUG6PQ+epo56fZlK1O8+5fNLfTdbAuc+2Xj4wT3bb51vZr5QQSmjeo9vq+UDXw/c70ZlZel9/bL219yoNK3/W3/2HCAz1Svqu3MzWf27Adcs8IubbAl2Fl4myifq4CcBrMws+u3n8sw/7iFviFO4JmrVfkr8UPIt/+ZuSArwiIB/K49K7wkn/36ywz59W8vxAQNeD7O1r/+bRoDqPbtf7MwnymQ+NOEhGDTr+uNXnot88cKvoZn3qzIwbjyyllTh0k4PqAn7UvPbxK7BCvvynszrwScuQN0CoGMzJ55aVhV75tu7jTpw8HP5J2kVmD93niz/MmaTaTAAV40wSe2E+bAlHzm5OmnGTd7mdnVrAUi335uvbB6cIKweWUKLE4BSGsneTmZF6ZFXgFJtQ3IAHf+aXa1q4l65rz9nDhNkv80s5O3v96bvLaBJiAKpZe9/fJwajG5FBDcGzurQ9d2vZ++QNuzvPDKd4vzZloA1F8C+OcZ99By5nwLy2Q5sAGoATxX1aX9rjhQMQmnQdq49lNyDoxOgT1Z7T2wJ+bvsmFCf8K79jP6X907UYMg2W9/de1n0jwzZcrO+ktyQl8LxOtWCX0A25TeDypMh37MSx9agIMKwTgECNwq9P/04cnluVx2AwiUneVZCOIIEqAGcRK8OsjdGZH4eRnWQfojSFWeUBFIZqgXAPviIMvsZVqBUQT7MIO+0+vfgfu9huDYvlSBjTyQZO8RUsebaTL3+cOf/nA9VEs7q255mVbfjf8zxbysBYex8NyX6ot9Dx3/Tbj/223Q90rSoQ/S5o848KvznhC6nTTeK+ydJS2tyBWnoU072MnxvKEQyNI6+PMW+p5yC311Ohh/nyxfw/okrI+ZWW/Y9rRshsVirhkHayyiy4KDOSct6f1GNDbwMYAyT13PrfRmOZjorvtLQjjSzRkHB8ZlMYqSxGBvyjpUNu2FobKhn+ehBROoLeZQYXiXQ6pa1uba8ZB4SZTTfa4Hy2reWUh48Kz0WPp+WqBJf8TWZ7pA4aaL24wYmaHgaJpMoargB0cJGGpIC3OpJGfrzo1z3p87UWPHyc25t3fFsrtGrccjSY98HFRdQzm74X7E9jKxh0Vq9DQL5Xmf1QsEDbnIcVZ51q2wEyLxedPSBqhxa2mnHMzxrDaXwqELk7xfhbIxmgPf6+cDeUKu8YiX2nK4tMWpPjQZK4yo6ksqxDIQPvcIfUAQh/A/f346/TtHbw/e8IzABYNxGpSN54jyyjq8gdNbe68Cx+3DiKLIy8EnOo4kfE4TVgExYPN7UAkNdJQOtB310qLVSjXuaMnkD7nFBa0jEhJzJCWi8yLmKBDxjkA0hgwESkq4nhkJmfRFnSRylYoTWqMQyknZ0Ta6XowI+LlXqUddTEyUT9wdO9gG41s7xtdSPbKMBDYVcmcZcgL4Km4ntxzDD+ZFLK4UUXMsv5MixhPI7iGX6AVd0gRfZpK9osukyoq8DC99LbYojnEGgVxeaJXrBFrohIhZgC8isvm01v9urfNduKdGgn/qaKpEzCuCLHSMZNK6JB2YruAlhKiljA+cRVIJUtVRzz2O6XhFG5mLQGpPf/TCSU/1xjSwyDY2vmQkg3UR/j99YAik9JBF9YL4sHen1RKMSUpIkoL6TRewfxJUc3lSJfRET74g+pNK9IeIyJ+6CCqnSb6kkIyskBTwoyZrGK0iuqLT+ShEDnKimRHwAF4GE1WKIhTu9zlBgpygfZ85EzTYl3IKjAG0eVaYmG4xiyFs9bReLyoouKe0zyhiStboZRTiTaReJOBO6C4HGHlJB74O1LjlG7xLztda8o9BgJR0w55PjMbdEhVD1ojbw/0cv+MDDxsM27XLWK81pdxY941+K+6YzciWUwt2ORzv6erGQaxxKANuPu5rBOLpTovJYa1cSTdjkpjSm+EyhzbD0bwwcNTpxFGghHxMWTdlmTDEDZ2pOSWQa7leC4lFrPeluYt5rbDO5vXaaYUd5rfT5jhXT/q89VmoarnANHP9UqgpiwZjfM8xXi4uO7kSgjmH3XkN3i83vXAH4g98pcA7ySox0XCWEdYxK5RLj9mOTRJ1t+Lh0SgvUE36K+NQSwwSU0THEIR9oog71/n+wROI5RRrl+4YEuokBpxpdkmTgMUvSZ9hSckhCUkOBHbTXSSTO3QmiJe2F4jDTjMC2N0Tq+OAoy7qNNYuyeyLHFz3YmEtsMi68LBtWIW5YOMrygfHVGyvChY6IQ5ymmzBWYDBenEdwDzlWkkTGUVzeZ1hBQ1O9moC8jV2hmNGoGZE3Kac2ysCs6MJwyfVgwoLPB5HvlLrLaYgbrBoioOJ7b2RdJ+0BKNHpCaw3I5MSYGQOPJIk5zAmDuKqnaEpLEkqGFsBG6te7k7hZvWBZYcUxnoD86S0YP64zbmQh/cXZLahhhYO3wwFSy6LuDGzLjWSfXuioqFC9bBeQVzK3yvbS7TSZRAEJ1/ZR7zfaeQd5Uii4i85Kzha0tLtvcy7NB5ewRy3QGLgTyAxVbAN9k1FRMnA7qkSWQaMsBmgC54fUz54QjOv7PDR+BvsJ4Afj41Q5yUYBnUsUSTtF4FvjxN51seuQbUi0pgGl+xyX0Q6//MXtjJ9NGl/rV9R5ilf1s3MUWO+b0QYpGTdsDeZ04xoDDUEUVWS8YCuQF43eSa6qMNdL8a+iDt3No0kuqRFzaxJH3dVwmGJg9ES1IwqLEEIqjxQowkTIh8UEe4pUDHoP5O9eRffSn/QJisyXQk0R38fSe5QF9BgnWdY9iTzuAnRduA2q/5UpxoOqOfJBjXtUTxd9IXvpPPENJJGDlUVP1eGOP3+mf4bPeFxvNpXxL+QT4JP+znJelRa7/lmkB9d65okiZE0o/vQRzu8A4G56xiCQKcTSD5Kl2aI44GB6m4rPfyOkXvsYzZeiYWZzGAc+toCgsZpgcvt5j1LVjtIe9wXnEhLSuyOOzODXYP0qLvIvpwy/Eodf2gJlZCTSI3/Kpc4cTLpJN0WO5dMW2bFJtn/opE7OACj/nCLXawg5ZcfCm5JO/OA0lCmZDP+UW4UZ0ecvY9uDYsvZOMwZg9xIbAoswmMWN0LjRzQem9yqC0uRnfKCN2CkqHKnCbSLEKDUveuY6CYnmSFV7LubqgjIsRMBnh+kh09jR5dbmZxA4rg8i5DohDOgiXnf3T/RRgTOfl7q73yoBc94oSGZaGZYKVkfidjq5lj4lDiZ+yyI06KjtBIh7ds7Pi1nBZHR2LYtRgwyWb9Xk+rzFojZaIb0p2a9dMiI7kxQcFRBHdsyV6y1FPjvtSzu52f1Hz3C6zhL6gVS4QPLzWEep0W3b8mvDPEt/Kx+62qvpVlBINbu0g4YLD11TyvP2orvcGGQblbjcuE0yXufvACGVKX+FUStPILr1+HqNDvuJby1uJF4a4I1J/Gzc9tjwsChUPwgN3auXN7rYTVi4HiltriDAUnocFk5bHOABXxsMc6RCT1Oq9f0jAbX85gsvjkq36dXcw6PtdTDzZS+agCPvz9cJZHsIhV9A7Q7T+iKRt4Xir5Ax7B663vLSFcJSxtWQvM/yKljDeduOR3lf9dTev8WSTe0q4Z0iJGjqWvh8XileBi+Tvb4nPlecNEvp6q/x23wRj7/1tWf64k/LHeln/2HwCoAR4OjuvsgJecjiMgfcaNnWrvm78qIXlKLVdvyKPdtNjuO2FvA7b/PVd19Lzw+l5Dl7d3qwNM6dJ7Ef7RmRfPPCkfqf+bxpcf6hlNbXVpqbQK46uFhtg6QMeffbbHhtbN5A9/5/2ztbfemffyLbZucyBPyY7pg++WSwWKyD5sfybVgFUftdC+E2z8/XvGS1ELPwUAAA=</docZip>
</loteDistDFeInt>
```

É a primeira vez que lembro de ter visto um retorno diferente para um XML. Caso fosse uma simples correção, eu ficaria feliz em ajudar. Fico à disposição para qualquer dúvida. Obrigado!

**Comment by danilobreda** [comment]
Deve ser um bug na identificação do tipo retornado para passar as informações... vou verificar ainda hoje a noite.

XML Descoprimido... 
`<procEventoNFe versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><evento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID1101104320103275813900019555001000000102151966463501"><cOrgao>43</cOrgao><tpAmb>2</tpAmb><CNPJ>32758139000195</CNPJ><chNFe>43201032758139000195550010000001021519664635</chNFe><dhEvento>2020-10-28T15:09:54-03:00</dhEvento><tpEvento>110110</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Carta de Correção</descEvento><xCorrecao>Testando a Carta de Correção para a Manifestação do Destinatário.</xCorrecao><xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#ID1101104320103275813900019555001000000102151966463501"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>0ePQUmsB6IU3uvyalLP8C1/ZUw0=</DigestValue></Reference></SignedInfo><SignatureValue>tLnYt8FvO4uy22+UWKZzpjX2I0IcmrDH8NW80Lh/neT7+ZmfZc5Nd7xXlAcQfczyc09RNjjllWFfS7iS8vXECnyx+oiZ0A3aNo/pWeXKmTZZ8bwJ/NXlSOq+Vh4s+wZ1iKeZmLrggmp3lxL57PDp30uwkvnAzEypIDDBm/spJycShECympY4SlPZqIz+Jg+cjuaklfcqvqSZawuTtzLBDzJkhswuCcGyqL5HRAH0NCzeUZ3JJgFVp13iIjcc6onw65O1QJouvDWaci7QGSKYzPTuXpcDpYBqbMruWuKJxVPKBO1bkz9rU4yXvpOtKunFMz3TgQT/FE/9+eAVy11cAg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHijCCBXKgAwIBAgIUM6hAy5+qhsMu/LQKDajxQ2vUrTkwDQYJKoZIhvcNAQELBQAwejELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEeMBwGA1UEAxMVQUMgRElHSVRBTFNJR04gUkZCIEcyMB4XDTIwMDMwMjE2MjE1NFoXDTIxMDMwMjE2MjE1NFowgd0xCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMQswCQYDVQQIEwJSUzEXMBUGA1UEBxMOVmVuYW5jaW8gQWlyZXMxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05QSiBBMTEXMBUGA1UECxMOMTY4OTQ3ODIwMDAxOTAxKjAoBgNVBAMTIUQgQSBERSBCSVRURU5DT1VSVDozMjc1ODEzOTAwMDE5NTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMYPSEkDv5ZEAaTO772s/hqmDgESNmBt3XzMk8jTXQsMQ/qRh5BXmyJthTkvJu9wlPbtQgLhh1rDuFPOEUIflT5171dx0x+9q9yJ0WEFwv4kVtUSr8Zq8Vfpq5aERZctMaryLqm6fI/FWKrhI+zHt1/JDwUkBy7SbBdnElkCVuyX+/8yLYXE0jwVALMCMozmFdmFEii9WVEtIShRtRt7MlZA7HrYGkJUpZPYbbwUpaiofO8L+TOV+vgF/svIhYYoVXpTmF3hzkqo5JRpXGRsMh+I5qJU0H48xMqElkKJsS0GQZr5NWc4j5wE63ImLnGFllTG6J0zWrX/tBg6WKtQE1kCAwEAAaOCAqIwggKeMA4GA1UdDwEB/wQEAwIF4DBtBggrBgEFBQcBAQRhMF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cuZGlnaXRhbHNpZ25jZXJ0aWZpY2Fkb3JhLmNvbS5ici9yZXBvc2l0b3Jpby9yZmIvQUNESUdJVEFMU0lHTlJGQkcyLnA3YjAfBgNVHSMEGDAWgBTKT0MJ9kjgStVv5S1dh2upKY5HezBdBgNVHSAEVjBUMFIGBmBMAQIBLDBIMEYGCCsGAQUFBwIBFjpodHRwOi8vd3d3LmRpZ2l0YWxzaWduY2VydGlmaWNhZG9yYS5jb20uYnIvcmVwb3NpdG9yaW8vcmZiMAkGA1UdEwQCMAAwgbEGA1UdHwSBqTCBpjBXoFWgU4ZRaHR0cDovL3d3dy5kaWdpdGFsc2lnbmNlcnRpZmljYWRvcmEuY29tLmJyL3JlcG9zaXRvcmlvL3JmYi9BQ0RJR0lUQUxTSUdOUkZCRzIuY3JsMEugSaBHhkVodHRwOi8vd3d3LmRpZ2l0YWx0cnVzdC5jb20uYnIvcmVwb3NpdG9yaW8vcmZiL0FDRElHSVRBTFNJR05SRkJHMi5jcmwwgb4GA1UdEQSBtjCBs4EZZGlvcmdlbmVza3JlbWVyQGdtYWlsLmNvbaA4BgVgTAEDBKAvBC0wMjA1MTk2NjQ5MjgzOTI4MDkxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgKAYFYEwBAwKgHwQdRElMQ0VVIEFOVE9OSU8gREUgQklUVEVOQ09VUlSgGQYFYEwBAwOgEAQOMzI3NTgxMzkwMDAxOTWgFwYFYEwBAwegDgQMMDAwMDAwMDAwMDAwMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDANBgkqhkiG9w0BAQsFAAOCAgEAbQXuL93hKQpX7HR7m3qkR5aVnNpPNh0oZLYM2R0DyeoZE7fh6H/eKP6IiDRSRNyGPu5qhmpxwjDKfo9jmdghtA6MtB1f9bSb0lenQOQK4HdNmvum5+ng6B1ahX0zo2dpG0c3rIkXrIlowPyBB/nMo+J2i8Tcx/cHxtur4eOR505aykWMF3E8lYk3+Mu+MSxesWCU+YkfCWkcpCV/satam5s3irJcbzMSZeQZibr+T2CWXWhEnAdg1jPeUR6XfYAG5rhjcby1cBc1InPgOqOh5EweodGxerhB7xSSjWZU5nMZnB9qDjbrx5Nyr9OnjdjwCnO/N9jqnPSdt0rsLcZCETh8Il87P++t5/73r1gYQavatEi3zBXgdh2SNdPZNe4zVlLHrRnqaxXTooarnlDX3soMAJ07V1COf4wJ7AgPQJvRLwf6sx6jmAu9ZG/MX90bmQeeHzT7HWBihrGGz4l5VRIqyEMrmDb0mQmmjarex+k3yo6JvZe6NXEAq1Qxfz8x54K2pT9hiKIOvR8GfGM6dIY5HvWN0/iPy2EmrLkhzeUK+1w1YBUtHgKlc144z13i4Fsx7wKWDqqNleRel+2Fkg+72c4KiyoS3qEAvgz1mvpce6lP0eKIxZemv/93EaUlHREJ6DQ5JadkzDHsxbG+t9l8oeSiHEBQCywFDqL2Ses=</X509Certificate></X509Data></KeyInfo></Signature></evento><retEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento><tpAmb>2</tpAmb><verAplic>RS201905151543</verAplic><cOrgao>43</cOrgao><cStat>135</cStat><xMotivo>Evento registrado e vinculado a NF-e</xMotivo><chNFe>43201032758139000195550010000001021519664635</chNFe><tpEvento>110110</tpEvento><nSeqEvento>1</nSeqEvento><CNPJDest>93628154000103</CNPJDest><dhRegEvento>2020-10-28T15:09:57-03:00</dhRegEvento><nProt>143200000982226</nProt></infEvento></retEvento></procEventoNFe>`

**Comment by felixsevero** [comment]
Certo, fico à disposição para qualquer ajuda.

**Comment by danilobreda** [comment]
Verifiquei que existe uma possibilidade das classes na pasta [Shared.NFe.Classes/Servicos/DistribuicaoDFe/Schemas](https://github.com/ZeusAutomacao/DFe.NET/tree/master/Shared.NFe.Classes/Servicos/DistribuicaoDFe/Schemas) estar desatualizados...
Uma das classes é o **detEvento** que está desde 2018 desatualizado.

@marcosgerene @robertorp Preciso da ajuda de vcs nisso... qual é o manual que tem essas modificações? Ainda não sei arrumar essas questões.

**Comment by marcosgerene** [comment]
Aparentemente o problema está em NFe.Classes.Servicos.DistribuicaoDFe.Schemas.detEvento.
![image](https://user-images.githubusercontent.com/15945003/99098353-a73d7e00-25b7-11eb-9ac5-4f86f4901ba1.png)

Ela não contempla os campos de CCe (como acontece em NFe.Classes.Servicos.Evento.detEvento)
![image](https://user-images.githubusercontent.com/15945003/99098487-d05e0e80-25b7-11eb-822c-914495cbcdda.png)

Um teste simples seria tentar imprimir o evento retornado ([xml_retorno.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5538227/xml_retorno.zip)), na impressão temos sucesso.

Acredito que seja uma questão de fazer com que a primeira classe seja igual à segunda.

**Comment by marcosgerene** [comment]
@felixsevero 
Por favor, teste com o PR https://github.com/ZeusAutomacao/DFe.NET/pull/1196

**Comment by felixsevero** [comment]
@marcosgerene As informações para o evento da Carta de Correção parecem corretas.

![image](https://user-images.githubusercontent.com/23054347/99106092-731b8a80-25c2-11eb-990a-5ac666284e8c.png)

Vi que você adicionou vários outros campos, que estão nulos. Eu não encontrei muitos detalhes nas Notas Técnicas que utilizei, você acha que eles serão utilizados em algum momento?

**Comment by marcosgerene** [comment]
Sim, serão utilizados para outros tipo de evento.

O xml serealizado ignora os nulos nessa classe,ou seja, a carta vai ficar da forma que você precisa.

**Comment by felixsevero** [comment]
Sim, eu havia entendido essa parte, só não tinha visto esses campos nos eventos ainda. Mas, pelo que testei, me parece estar funcionando adequadamente.
