### ISSUE TITLE
Impressão CCE - Carta de Correção

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1194]
Ola amigos, haveria possibilidade ou se ja existe a impressao da Representação Gráfica de CCe. Obrigado

**Comment by sigridslima** [comment]
Encontrei o evento para impressão  Danfe.AppTeste, porem apresenta erro: Nehum objeto nfeProc encontrado no arquivo.

Foram gerados tres arquivos xml, não sei qual utilizar.

1-eve.xml
1-ped-eve.xml
1101102920111936464400019755001000000352139207225301-procEventoNFe.xml

//////
1-eve.xml

`<?xml version="1.0"?>
-<retEnvEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe">
<idLote>1</idLote>
<tpAmb>1</tpAmb>
<verAplic>SEFAZBA_NFENW_v7.0.3</verAplic>
<cOrgao>29</cOrgao>
<cStat>128</cStat>
<xMotivo>Lote de Evento Processado</xMotivo>
-<retEvento versao="1.00">
-<infEvento Id="ID129200003142234">
<tpAmb>1</tpAmb>
<verAplic>SEFAZBA_NFENW_v7.0.3</verAplic>
<cOrgao>29</cOrgao>
<cStat>135</cStat>
<xMotivo>Evento registrado e vinculado a NF-e</xMotivo>
<chNFe>29201119364644000197550010000003521392072253</chNFe>
<tpEvento>110110</tpEvento>
<xEvento>Carta de Correcao Registrada</xEvento>
<nSeqEvento>1</nSeqEvento>
<CNPJDest>23443865000128</CNPJDest>
<emailDest>egsuporte@hotmail.com</emailDest>
<dhRegEvento>2020-11-10T17:00:43-03:00</dhRegEvento>
<nProt>129200003142234</nProt>
</infEvento>
</retEvento>
</retEnvEvento>`

//////

1-ped-eve.xml

`<?xml version="1.0"?>
-<envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00">
<idLote>1</idLote>
-<evento versao="1.00">
-<infEvento Id="ID1101102920111936464400019755001000000352139207225301">
<cOrgao>29</cOrgao>
<tpAmb>1</tpAmb>
<CNPJ>19364644000197</CNPJ>
<chNFe>29201119364644000197550010000003521392072253</chNFe>
<dhEvento>2020-11-10T17:00:42-03:00</dhEvento>
<tpEvento>110110</tpEvento>
<nSeqEvento>1</nSeqEvento>
<verEvento>1.00</verEvento>
-<detEvento versao="1.00">
<descEvento>Carta de Correção</descEvento>
<xCorrecao>teste de cce vinculado a nfe</xCorrecao>
<xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso>
</detEvento>
</infEvento>
-<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
-<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
-<Reference URI="#ID1101102920111936464400019755001000000352139207225301">
-<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>JNF8KgG50RXIkG/h+H3aXhoUk5A=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>OLgQMqXRXbkBKZapwK8cdyRPyH04cYUaSxLV3T2srZ+AAUlzQTS0eQMytdcpLBgXyhyv3d+g9YFsffwENCEcv28JhMneqy2a5/UZN5fmNSMho6Zb9KJJGNToLpSgdMD1o+BfdvGOmNR83k00aykOUCn3BXiqpW3CAK3X8BS+1Ek04EaV25YK1YPtlRzpaAT5JwnLohoReSiV1n6+PjLNOgDwejdDmaJDFgmQ4snpylS6IYkJBWP9gKBb/Cbn9xy21suf6Ah63GBDRAWrdtMTI5TLWYnR1j1Q5P1DZVZQ7BF4w6vkUY4s4I08DCLPm5pH6eS8D382Y/Vq1SSNv2lwIQ==</SignatureValue>
-<KeyInfo>
-<X509Data><X509Certificate>MIIH3TCCBcWgAwIBAgIIRhxVMsWk8t0wDQYJKoZIhvcNAQELBQAwezELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEfMB0GA1UEAxMWQUMgQ09OU1VMVEkgQlJBU0lMIFJGQjAeFw0xOTEyMjcxNDAwMzhaFw0yMjEyMjcxNDAwMzhaMIH2MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDELMAkGA1UECBMCQkExEzARBgNVBAcTCklUQUdJTUlSSU0xNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05QSiBBMzEXMBUGA1UECxMOMDQ4MzA3NzcwMDAxMzQxRzBFBgNVBAMTPkNIQVZFUyBTT1VTQSBFWFRSQUNBTyBFIENPTUVSQ0lPIERFIFNBSUJSTyBMVERBOjE5MzY0NjQ0MDAwMTk3MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjZphZbQa30U7xSm5rn9C6/UywcQXTp2ExKSId3t2Igv7kGTb/cB5gYeFxtYrf5q5tVUkX0WdX/RIsDYBRYVHiRGndhSW1lmJetbGX5Ps6xRR0UJzCeS74AP3BAfSZPfbzwunTcq4wzfY8rtTlmNYLzO3h/zlaGRif9QXIc0PicqWfOUoFuoIhOc2Oh94dZ0ipIqn8WQrIFNFMCjfwuetA1usKbvz0kw5mlvceeNWKXD5oKWY77/3r+ZHdxEHcii2f0swVv7v/1/ZeeJbwWaUlTRWqKp9jvX2BThGwAgCGyemPJY/QMjHw0bHTpxVet8rxjgqV/EH3gwv3JY8Eq7PJQIDAQABo4IC5zCCAuMwHwYDVR0jBBgwFoAUrvGhcHYTavvnlHecMixXyxQ4Wd8wDgYDVR0PAQH/BAQDAgXgMIGABgNVHSAEeTB3MHUGBmBMAQIDPjBrMGkGCCsGAQUFBwIBFl1odHRwOi8vcmVwb3NpdG9yaW8uYWNjb25zdWx0aWJyYXNpbC5jb20uYnIvYWMtYWNjb25zdWx0aWJyYXNpbHJmYi9kcGMtYWNjb25zdWx0aWJyYXNpbHJmYi5wZGYwgeAGA1UdHwSB2DCB1TBooGagZIZiaHR0cDovL3JlcG9zaXRvcmlvLmFjY29uc3VsdGlicmFzaWwuY29tLmJyL2FjLWFjY29uc3VsdGlicmFzaWxyZmIvbGNyLWFjLWFjY29uc3VsdGlicmFzaWxyZmJ2NC5jcmwwaaBnoGWGY2h0dHA6Ly9yZXBvc2l0b3JpbzIuYWNjb25zdWx0aWJyYXNpbC5jb20uYnIvYWMtYWNjb25zdWx0aWJyYXNpbHJmYi9sY3ItYWMtYWNjb25zdWx0aWJyYXNpbHJmYnY0LmNybDB6BggrBgEFBQcBAQRuMGwwagYIKwYBBQUHMAKGXmh0dHA6Ly9yZXBvc2l0b3Jpby5hY2NvbnN1bHRpYnJhc2lsLmNvbS5ici9hYy1hY2NvbnN1bHRpYnJhc2lscmZiL2FjLWFjY29uc3VsdGlicmFzaWxyZmJ2NC5wN2Iwga4GA1UdEQSBpjCBo4EZQVJJU1RPTkZJTElUT0BIT1RNQUlMLkNPTaAYBgVgTAEDAqAPEw1BUklTVE9OIFNPVVNBoBkGBWBMAQMDoBATDjE5MzY0NjQ0MDAwMTk3oDgGBWBMAQMEoC8TLTI3MDMxOTQ0MDQ0NDg5Nzk1MDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMA0GCSqGSIb3DQEBCwUAA4ICAQCeUgBOQWIW/BGm9mwnxF1Bq2KK6Syo8OtDqudUkh3EaTcWmxZaA23jxgU7ezZ/Y0NZwYGSGvk4G668vxlN+H9G6MNAbfCNotB/lvRdqni+bdXdMybpbsNakGH5t+xZFhBINPEwVArZk8eYCRsMBbOfcN58dMxtLoDAX5g8cGau4t4GICCXJIQmKCOvIOlzxXpr9uiIwujl3XYgm+CHYnov50M7jfFtL4dc4KMcSPPTyrE7fD4rW+z9jx5jaj20D1B5fPMztpf8rMfzF+jXZPUzO7EkUxbTaICYqZrMPXIf/HsC9r373kKEPtkNNcJuKNDVIWp6a6+UQqp7gm+4TPGvF8mN0lmlQkqjefTINrHjLEgVfU9ZWJimuJqTio5FbYsMegR5hqiYZiFCfbUJcGfsJo07lvDSajCSM9FKLxw2gPZxx8tKMS59zO8XBOKFTrb9x0qlvlJZDKhrRYA4JYBFEJjhdBDr6RYDd8y1/8qQOxJQzOmMigiVqvs2BsVAeAC681yGWEV/D8rmq0sjYxjfUr1VsbRNntnUSfi7Urqf1nxja65XLkaqX/UzrYTR0i4/0XTdveu08mnBdC+F4Zx3hOR/2EAf6iRDgVCFuir1v8pYGQmqq1muglsv1POmMouZUnZNp12QsOVh3MM4CkpBCHOIo6p8frLy1Zkyzwy/xg==</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>
</evento>
</envEvento>
`
//////
Aguardo a colaboração.

**Comment by marcosgerene** [comment]
@sigridslima 

Por favor, olhe o Demo. Existe a impressão do CCE. Para imprimir a biblioteca precisa do XML do NFeProc (nfe completa) e do evento.

Basta olhar o demo, o código é extremamente simples.

[]'s

**Comment by danilobreda** [comment]
@sigridslima conseguiu resolver o problema?

**Comment by sigridslima** [comment]
Ola amigos, sim conseguir resolver. muito obrigado pela ajuda. Abraços
