### ISSUE TITLE
DACTE com NFe duplicada

### ISSUE THREAD

**Issue by mvtaraujo** [ZeusAutomacao/DFe.NET#1195]
Quando o CTe possui 3 documentos (NFe) o DACTE duplica uma das notas e acaba mostrando 4 documentos, porém no XML só tem 3.

Segue xml exemplo. 

No exemplo ele duplica o documento numero 17460 do lado direito

![Screenshot 2020-11-13 095052](https://user-images.githubusercontent.com/2230616/99074028-cd522680-2595-11eb-84d2-c560b48aadbe.png)

[35201104139851000251570010000003471000027895-procCTe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5536824/35201104139851000251570010000003471000027895-procCTe.zip)

**Comment by marcosgerene** [comment]
Por favor, teste com o commit https://github.com/ZeusAutomacao/DFe.NET/pull/1196/commits/a686ca7a6a9e5a60b81a7fee145814a4f457b48a

**Comment by mvtaraujo** [comment]
Deu certo sim. Obrigado!
