### ISSUE TITLE
NFe for .NET Standard

### ISSUE THREAD

**Issue by DSBRBrasil** [ZeusAutomacao/DFe.NET#1197]
Ola pessoal,
Ha algum tempo desenvolvi uma biblioteca filha do zeus, toda em .net standard.
A biblioteca é um novo conceito em relação ao programa de envio de notas (zeus) atual, colocando por exemplo um arquivo de configuraçoes para endereços de serviço além de geração de danfe em html (sem dependências)
Caso o Roberto ou Adenilton estiverem interessados podemos marcar uma call para lhes mostrar o programa.
Meu interesse está em expandir para mais modulos

Obrigado

**Comment by felixsevero** [comment]
Bom dia, você não gostaria de disponibilizar a biblioteca no Github? Acredito que o compartilhamento dos conhecimentos possa ser benéfico para ambos os projetos.

**Comment by DSBRBrasil** [comment]
Gostaria de ouvir também o Roberto e o Adenilton por gentilieza...O projeto já está escrito, e rodando em produção. E gostaria de ter mais informações dos dois, entende ?
Atenciosamente 

 

    On Thursday, November 19, 2020, 08:15:14 AM GMT-3, felixsevero <notifications@github.com> wrote:  
 
 


Bom dia, você não gostaria de disponibilizar a biblioteca no Github? Acredito que o compartilhamento dos conhecimentos possa ser benéfico para ambos os projetos.

**Comment by denernun** [comment]
De boa, espero que os dois respondam a mesma coisa: joga no github !
Não sei se você já conhecia o Zeus antes de iniciar sua lib, se sim,
deveria ter colocado seu esforço para melhorar o projeto Zeus, e não ter
criado algo novo, que faz exatamente a mesma coisa, e pelo visto, tem uma
ou outra funcionalidade diferente e só você está usando.
Por exemplo, como mencionado, o danfe em html sem dependências, não poderia
ter sido adicionado no Zeus ?

Enfim, minha opinião.

**Comment by robertorp** [comment]
O Zeus está evoluindo a cada dia um pouco, nunca parou de evoluir graças a comunidade, principalmente graças ao @danilobreda  é @marcosgerene  que são os principais colaboradores no momento do Zeus. 
Zeus está muito solido/seguro já. 

Qualquer um, literalmente qualquer um pode ficar livre para fazer um PR para ajudar na evolução do Zeus, que será analisado é aceito logo após a comunidade analisar.

**Comment by DSBRBrasil** [comment]
ok, obrigado
