### ISSUE TITLE
Disposto a ajudar

### ISSUE THREAD

**Issue by Roberiopraciano** [ZeusAutomacao/DFe.NET#12]
Boa noite amigo, parabens pelo projeto, vi suas justificativas no forum do acbr e concondo com todas, amo o delphi de coração, mas cada dia que passa a embarcadero me deixa mais preocupado com o futuro de minha pequena empresa, não tenho muita experiencia em .net mas tenho mudado pequenos projetos para c#, gostaria de engajar mais pessoas, pois acredito que muitos ainda nao mudaram para .net por conta do acbr, eu e alguns amigo e conhecido queremos , nem que seja aos pouco converter nossos projetos para .net, gostaria de saber de precisa de ajuda para alguma coisa, obg e parabens novamente

**Comment by adeniltonbs** [comment]
Muito obrigado pela prontidão em ajudar, pois toda ajuda é bem vinda. Se desejar ajudar, podes fazer das seguintes formas: 
- Por usar a biblioteca, testá-la e ajudar a resolver possíveis bugs;
- Por me ajudar a implementar o que ainda falta implementar, conforme mencionado nos issues desse projeto em: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues;
- Por ajudar em manter a biblioteca, me ajudando a implementar novas notas técnicas conforme sejam disponibilizadas pela SEFAZ.

Assim como você, há muitas pessoas percorrendo este caminho, e em breve teremos a gama completa de projetos para cobrirmos todos os componentes do ACBR.

**Comment by adeniltonbs** [comment]
Se desejar, posso te adicionar como colaborador do projeto, avise aqui por favor

**Comment by Roberiopraciano** [comment]
Opa cara, vou começar fazendo assim, vou testar o máximo que puder, e vou
pegar um programador que tenho aqui e vamos fazer um emissor gratuito
usando este projeto, e distribuir nas redes sociais, assim o negocio comeca
a pegar corpo o pessoal usar e pegar bugs, como saber pequenas empresas se
dividem entre fazer o novo, concertar o antigo, agradar clientes e so
depois sobra tempo pra estudar um pouco, mas vou te pertubar bastante
ainda, inclusive em implementar novas funcionalidades

Roberio Praciano

Em 7 de abril de 2015 08:26, Zeus Automação Comercial <
notifications@github.com> escreveu:

**Comment by adeniltonbs** [comment]
Ok, qualquer coisa posta aqui.

**Comment by Roberiopraciano** [comment]
posto sim já to fazendo algo acho que semana que vem tem algo, vou usar
sqllite

Roberio Praciano

2015-04-07 16:25 GMT-03:00 Zeus Automação Comercial <
notifications@github.com>:

**Comment by edulamy** [comment]
---

## Erro

## Conversão inválida de 'System.Int32' em 'NFe.Classes.Informacoes.Identificacao.Tipos.TipoAmbiente'.

## OK   

Após selecionar o arquivo XML para impressão, projeto NFe.Danfe.AppTeste.

Poderia orientar?

**Comment by adeniltonbs** [comment]
@edulamy Bom dia.
Estais a tentar imprimir o DANFE da NFCe ou da NFe?
Pode anexar aqui o XML?
