### ISSUE TITLE
Fastreport

### ISSUE THREAD

**Issue by marcelokrol** [ZeusAutomacao/DFe.NET#120]
Ola 
Gostei do seu projeto, achei bem estruturado e limpo, mais para que consiga compilar o mesmo é necessário o fastreport!

**Comment by adeniltonbs** [comment]
Bom dia marcelo, no momento realmente é necessário, mas não se preocupe, você pode instalar a versão de demonstração que não expira e a única limitação é uma marca d'água na visualização/impressão. Em breve vamos tentar desacoplar isso.
