### ISSUE TITLE
Erro em protocolo de serviço

### ISSUE THREAD

**Issue by daybsonrabelo** [ZeusAutomacao/DFe.NET#1203]
Olá pessoal, baixei o projeto para realizar alguns testes mas não estou conseguindo utiliza-lo, poderiam me ajudar?

Quando tento consultar pela chave por exemplo, recebo a mensagem: "The request was aborted: Could not create SSL/TLS secure channel" ou "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.". 
Já tentei com todas as opções disponíveis de protocolo de segurança mas não consegui.

OBS: Ambiente de Homologação, UF: MG

**Comment by eduprog** [comment]
Amigo se procurar aqui nas issues fechadas vai encontrar, este erro pode ser relacionado a n coisas, mas algumas delas é certificado vencido, conexão tls que deve ser 1.2 e o windows por padrão seta 1.3. 

Se for windows 10, verifique as opções de internet e veja no registro que ele costuma setar 1.3 e já tive problema com isto ok. 

Bom espero ter ajudado.

**Comment by alsantana** [comment]
Ola, boa tarde

Instalei os aplicativos para o uso do mouse e está tudo atualizado, mas infelizmente o problema de duplo clique continua

Feliz ano novo para todos

Atenciosamente

Sent from my iPhone
André Santana

On 30 Dec 2020, at 12:27, Eduardo Moreira <notifications@github.com> wrote:

﻿

Amigo se procurar aqui nas issues fechadas vai encontrar, este erro pode ser relacionado a n coisas, mas algumas delas é certificado vencido, conexão tls que deve ser 1.2 e o windows por padrão seta 1.3.

Se for windows 10, verifique as opções de internet e veja no registro que ele costuma setar 1.3 e já tive problema com isto ok.

Bom espero ter ajudado.

**Comment by daybsonrabelo** [comment]
> Amigo se procurar aqui nas issues fechadas vai encontrar, este erro pode ser relacionado a n coisas, mas algumas delas é certificado vencido, conexão tls que deve ser 1.2 e o windows por padrão seta 1.3.
> 
> Se for windows 10, verifique as opções de internet e veja no registro que ele costuma setar 1.3 e já tive problema com isto ok.
> 
> Bom espero ter ajudado.

Olá, olhei em outras issues mas continuo com o problema, tentei a solução do registro do Windows e setar manualmente o protocolo(System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;).

Verifiquei o certificado e está ok. Também verifiquei as opções da internet e aparentemente está ok.
![internet_options](https://user-images.githubusercontent.com/5963401/103369953-422be200-4aaa-11eb-9c38-db147c71c1ec.PNG)

**Comment by eduprog** [comment]
Amigo, no nosso suporte, já tivemos este erro em clientes e foi resolvido conforme esta resposta do [stackoverflow](https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel#:~:text=Another%20possible%20cause%20of%20the,willing%20and%20able%20to%20accept.)

Pode ter acontecido na hora da instalação do certificado. Espero que resolva, agora já parti 21! Sucesso. !!!

![image](https://user-images.githubusercontent.com/3284954/103374353-275f6a80-4ab6-11eb-8163-660a5ffdb9ca.png)

**Comment by adeniltonbs** [comment]
Boa tarde, para descartar problemas com o S.O, você pode tentar acessar o serviço web diretamente pelo Internet Explorer. Você vai encontrar os endereços dos serviços web para homologação em http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#MG. Depois de confirmar o certificado, o resultado no navegador será algo como
![image](https://user-images.githubusercontent.com/6733483/103380417-9b563e80-4ac7-11eb-9cf8-3fe9b16c73e5.png)

Obs: Nessa imagem consta o resultado do serviço NFeConsultaProtocolo4 para SE, no ambiente de homologação.

**Comment by eduprog** [comment]
Obrigado @adeniltonbs , eu não estou tendo problema algum não, já temos funcionando em vários clientes e tudo 100%, nosso amigo @daybsonrabelo que abriu a issue. Vamos ver se ele lê ai já resolve a parada. 

Vlw. Feliz ano novo. Que 21 seja mais leve! 

Que Deus Abenções a todos e aos seus. Paz, Saúde e Alegria, o resto a gente cria uns códigos, paga as contas e vê como fica. ;-)

**Comment by daybsonrabelo** [comment]
Olá pessoal, testei o link pelo navegador como sugerido(Produção e Homologação de MG) e não está funcionando aparentemente.
Eu não entendo muito bem de certificados(ou quase nada). Saberiam dizer se é possível emitir um certificado de testes(para CE por exemplo que vi que está funcionando) .

**Comment by adeniltonbs** [comment]
Bom dia @daybsonrabelo, você precisa adquirir um certificado A1 ou A3 válido. [Aqui](https://www.nfe.fazenda.gov.br/portal/perguntasFrequentes.aspx?tipoConteudo=k/E5BakB80o=) há algumas informações sobre o tipo de certificado requerido.
Não há certificado de testes, é usado um certificado válido no ambiente de testes da NF-e(homologação). Algumas empresas que vendem certificados para NF-e são [Certisign](https://loja.certisign.com.br/Certificados/nfe-2), [Serasa](https://serasa.certificadodigital.com.br/home/) e [Valid](https://www.validcertificadora.com.br/Certificado/NF-e.htm).

**Obs:** o certificado de NF-e também serve para NFC-e, MFD-e e CT-e

 Para maiores informações, sugiro consultar o contador de sua empresa.

**Comment by daybsonrabelo** [comment]
Olá pessoal, encontrei o problema.

No arquivo Enderecador.cs o endpoint está com https(de acordo com o portal da NFCE):
![nfce1](https://user-images.githubusercontent.com/5963401/103656091-ef897480-4f46-11eb-8148-2e0d240725a6.PNG)

Porém testando no navegador o mesmo não abre:
![nfce2](https://user-images.githubusercontent.com/5963401/103656269-2a8ba800-4f47-11eb-8aba-d822a3a5eece.PNG)

Mudando a url para http funciona corretamente:
![nfce3](https://user-images.githubusercontent.com/5963401/103656330-3a0af100-4f47-11eb-97a3-b0e9bcb3e98a.PNG)
![nfce4](https://user-images.githubusercontent.com/5963401/103656593-8ce4a880-4f47-11eb-84e8-8efcd99c1ea5.PNG)


Agradeço a atenção de todos.

**Comment by danilobreda** [comment]
Seguindo o http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/ e http://www.sped.fazenda.mg.gov.br/spedmg/nfe/webservices/ o correto é utilizar **https**, será que é por conta da falta de certificado não? Nunca vi serviço do governo utilizar **http**, pois não tem certificado nessa comunicação.
