### ISSUE TITLE
Rejeição (656): Consumo Indevido

### ISSUE THREAD

**Issue by casleandro** [ZeusAutomacao/DFe.NET#1204]
Olá pessoal, estou desenvolvendo o projeto e sempre a cada 2 consultas começa a apresentar a Rejeição (656): Consumo Indevido

Quando iniciei o projeto a alguns meses atrás não era apresentado porém já tem 1 semana que vem apresentando a todo momento.

Alguém sabe como solucionar?

**Comment by adeniltonbs** [comment]
Bom dia @casleandro, você vai encontrar os limites de uso do webservices na Nota [Técnica 2018.002 - v 1.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=NH9NBCgaOUs=). Aqui está um recorte falando dos limites para o serviço de consulta da situação da nota que vc mencionou:
![image](https://user-images.githubusercontent.com/6733483/103655140-9c62f200-4f45-11eb-81a3-b1d46a19dffb.png)

**Comment by casleandro** [comment]
Já fiz alguns procedimentos e ainda continuo tendo problema

Vou postar abaixo uma parte do código utilizado.

`RetornoNfeDistDFeInt retornoNFeDistDFe;
                int ultNSU = 0;
                int maxNSU = ultNSU;
                int iCount = 0;
                int loopLimit = 50; //Cada consulta possui 50 lotes que é o máximo permitido pela Receita

                //executa a busca de NFe em loop
                while (ultNSU <= maxNSU)
                {
                    iCount++;
                    if (iCount >= loopLimit)
                        break;
                    try
                    {
                        retornoNFeDistDFe = servicoNFe.NfeDistDFeInteresse(_configuracoes.EnderecoEmitente.UF.ToString(), cnpj, ultNSU: ultNSU.ToString());
                    }
                    catch (Exception ex)
                    {
                        throw new ArgumentException(ex.Message);
                    }

                    //RETORNANDO ALGUMAS INFORMAÇÕES
                    ultNSU = Convert.ToInt32(retornoNFeDistDFe.Retorno.ultNSU);
                    maxNSU = Convert.ToInt32(retornoNFeDistDFe.Retorno.maxNSU);
                    string motivo = retornoNFeDistDFe.Retorno.xMotivo;

                    //Criando um elemento e inserindo o retorno de todos os lotes
                    XElement elements = XElement.Parse(retornoNFeDistDFe.RetornoCompletoStr);
                    XNamespace df = elements.Name.Namespace;
                    var lote = elements.Element(df + "loteDistDFeInt");
                    if (lote == null)
                        continue;

                    //Criando o XML da nota e carregando separadamente
                    foreach (var nota in lote.Elements().ToList())
                    {
                        XmlDocument xmlCreate = new XmlDocument();
                        xmlCreate.LoadXml(Decompress(Convert.FromBase64String(nota.Value)));`

**Comment by felixsevero** [comment]
Cada consulta retornará, no máximo, 50 resultados. Você precisa salvar o `ultNSU` consultado, não podendo iniciar sempre no zero.

Supondo que o `maxNSU` seja 155:
1° consulta: `ultNSU` = 0 e `maxNSU` = 155, retornando 50 resultados
2° consulta: `ultNSU` = 50 e `maxNSU` = 155, retornando 50 resultados
3° consulta: `ultNSU` = 100 e `maxNSU` = 155, retornando 50 resultados
4° consulta: `ultNSU` = 150 e `maxNSU` = 155, retornando 5 resultados

**Comment by marcosgerene** [comment]
@casleandro 

https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636

```
public void CarregarNsu(long ultimoNsu)
        {

            try
            {
                EstadoAtual = $"Enviando solicitação";

                ZeusRetornoNfeDistDFeInt retornoDistribuicao;
                using (var _certificado = ZeusCertificado.ObterCertificado(ZeusConfiguracaoServico.Certificado))
                using (var _servico = new ZeusServicoNFe(ZeusConfiguracaoServico, _certificado))
                    retornoDistribuicao = _servico.NfeDistDFeInteresse(ufAutor: NfeHelper.Emitente.enderEmit.UF.ToString(), documento: NfeHelper.Emitente.CNPJ, ultNSU: ultimoNsu.ToString());

                EstadoAtual = $"Tratando retorno da solicitação";

                Funcoes.GravarLog($"[CarregarNsu]{Environment.NewLine}" +
                                  $"Envio: {retornoDistribuicao.EnvioStr}{Environment.NewLine}" +
                                  $"Retorno:{retornoDistribuicao.RetornoCompletoStr}{Environment.NewLine}");

                var loteResposta = retornoDistribuicao.Retorno.loteDistDFeInt;

                if (loteResposta == null)
                    throw new ArgumentException($"{retornoDistribuicao.Retorno.cStat} - {retornoDistribuicao.Retorno.xMotivo}");

                var nsus = new List<DfeNfeNsu>();

                using (var conexao = new Conexao())
                {
                    int _estado = 1;

                    foreach (var _zeusNsu in loteResposta.OrderBy(n => n.NSU))
                    {
                        EstadoAtual = $"Tratando retorno [{_estado++}/{loteResposta.Count()}]";

                        conexao.StartTransaction();

                        string xml = ZeusCompressao.Unzip(_zeusNsu.XmlNfe);

                        var nsu = new DfeNfeNsu()
                        {
                            IdEmpresa = Sessao.Current.Acesso.Empresa.Id,
                            Nsu = _zeusNsu.NSU,
                        };

                        if (_zeusNsu.NfeProc != null) //Tipo NFeProc grava o NSU já com os dados da NFe e o xml na base
                        {
                            nsu.DataHoraConsulta = _zeusNsu.NfeProc.NFe.infNFe.ide.dhSaiEnt ?? _zeusNsu.NfeProc.NFe.infNFe.ide.dhEmi;

                            nsu.IsNfe = true;
                            nsu.EmitenteCnpj = _zeusNsu.NfeProc.NFe.infNFe.emit.CNPJ ?? _zeusNsu.NfeProc.NFe.infNFe.emit.CPF;
                            nsu.EmienteRazaoSocial = _zeusNsu.NfeProc.NFe.infNFe.emit.xNome;
                            nsu.NfeChave = _zeusNsu.NfeProc.NFe.infNFe.Id.OnlyNumber();
                            nsu.NfeNumero = _zeusNsu.NfeProc.NFe.infNFe.ide.nNF;
                            nsu.NfeEmissao = _zeusNsu.NfeProc.NFe.infNFe.ide.dhEmi;
                            nsu.NfeValor = _zeusNsu.NfeProc.NFe.infNFe.total.ICMSTot.vNF;
                            nsu.NfeSituacao = DfeNsuSituacao.Transmitido;
                            nsu.Descricao = "NF-e";
                            new DfeNfeNsuDal(conexao).Salvar(nsu);

                            var dfexml = new DfeXml()
                            {
                                ChaveAcesso = nsu.NfeChave,
                                EmissaoPropria = false,
                                XmlContent = xml
                            };

                            new DfeXmlDal(conexao).Salvar(dfexml);

                            //Buscar NSUs anteriores pela chave de acesso e marcar todos como IsNfe false.                          
                            var nsusAntes = new DfeNfeNsuDal(conexao).Listar(chave: nsu.NfeChave, empresa: Sessao.Current.Acesso.Empresa).Where(x => x.Id != nsu.Id && x.IsNfe);
                            foreach (var _antes in nsusAntes)
                            {
                                _antes.IsNfe = false;
                                new DfeNfeNsuDal(conexao).Salvar(_antes);
                            }
                        }

                        else if (_zeusNsu.ProcEventoNFe != null) //Tipo ProcEventoNFe busca o nsu da nfe anterior e marca a mesma como cancelada (se o evento for do tipo cancelamento)
                        {
                            nsu.DataHoraConsulta = _zeusNsu.ProcEventoNFe.evento.infEvento.dhEvento;

                            nsu.IsNfe = false;
                            nsu.NfeChave = _zeusNsu.ProcEventoNFe.evento.infEvento.chNFe.OnlyNumber();
                            nsu.Descricao = "Evento de NF-e";
                            new DfeNfeNsuDal(conexao).Salvar(nsu);

                            var pantheraEvento = new DfeEvento()
                            {
                                ChaveEvento = _zeusNsu.ProcEventoNFe.evento.infEvento.Id.OnlyNumber(),
                                ChaveDfe = _zeusNsu.ProcEventoNFe.evento.infEvento.chNFe.OnlyNumber(),
                                TipoEvento = _zeusNsu.ProcEventoNFe.retEvento.infEvento.tpEvento,
                                DataHora = _zeusNsu.ProcEventoNFe.retEvento.infEvento.dhRegEvento,
                                Motivo = _zeusNsu.ProcEventoNFe.evento.infEvento.detEvento?.xJust ?? string.Empty
                            };
                            new DfeEventoDal(conexao).Salvar(pantheraEvento);

                            var dfexml = new DfeXml()
                            {
                                ChaveAcesso = _zeusNsu.ProcEventoNFe.evento.infEvento.Id.OnlyNumber(),
                                EmissaoPropria = false,
                                XmlContent = xml
                            };
                            new DfeXmlDal(conexao).Salvar(dfexml);

                            //Se o evento for de cancelamento, marca o evento anterior da NF-e com status cancelado
                            if (_zeusNsu.ProcEventoNFe.retEvento.infEvento.tpEvento != NfeHelper._EventoCancelamentoNFe)
                                continue;

                            //Buscar NSUs anteriores pela chave de acesso e marcar como cancelado
                            var nsusAntes = new DfeNfeNsuDal(conexao).Listar(chave: nsu.NfeChave, empresa: Sessao.Current.Acesso.Empresa).Where(x => x.Id != nsu.Id && x.IsNfe);
                            foreach (var _antes in nsusAntes)
                            {
                                _antes.NfeSituacao = DfeNsuSituacao.Cancelado;
                                new DfeNfeNsuDal(conexao).Salvar(_antes);
                            }
                        }

                        else if (_zeusNsu.ResEvento != null) //Tipo ResEvento - proximo ao ProcEventoNFe, mas com menos detalhes
                        {
                            nsu.DataHoraConsulta = _zeusNsu.ResEvento.dhEvento;
                            nsu.IsNfe = false;
                            nsu.NfeChave = _zeusNsu.ResEvento.chNFe.OnlyNumber();
                            nsu.Descricao = "Evento de NF-e (ResEvento)";
                            new DfeNfeNsuDal(conexao).Salvar(nsu);

                            string chaveEvento = $"{_zeusNsu.ResEvento.tpEvento}{nsu.NfeChave}{_zeusNsu.ResEvento.nSeqEvento:D2}";

                            //Se já existir o evento no banco, não sobreescrever
                            if (new DfeEventoDal(conexao).Carregar(chaveEvento) != null)
                                continue;

                            var pantheraEvento = new DfeEvento()
                            {
                                ChaveEvento = chaveEvento,
                                ChaveDfe = nsu.NfeChave,
                                TipoEvento = _zeusNsu.ResEvento.tpEvento.StrToLongDef(),
                                DataHora = _zeusNsu.ResEvento.dhRecbto,
                                Motivo = _zeusNsu.ResEvento.xEvento
                            };
                            new DfeEventoDal(conexao).Salvar(pantheraEvento);

                            var dfexml = new DfeXml()
                            {
                                ChaveAcesso = chaveEvento,
                                EmissaoPropria = false,
                                XmlContent = xml
                            };
                            new DfeXmlDal(conexao).Salvar(dfexml);

                            //Se o evento for de cancelamento, marca o evento anterior da NF-e com status cancelado
                            if (_zeusNsu.ResEvento.tpEvento.StrToLongDef() != NfeHelper._EventoCancelamentoNFe)
                                continue;

                            //Buscar NSUs anteriores pela chave de acesso e marcar como cancelado
                            var nsusAntes = new DfeNfeNsuDal(conexao).Listar(chave: nsu.NfeChave, empresa: Sessao.Current.Acesso.Empresa).Where(x => x.Id != nsu.Id && x.IsNfe);
                            foreach (var _antes in nsusAntes)
                            {
                                _antes.NfeSituacao = DfeNsuSituacao.Cancelado;
                                new DfeNfeNsuDal(conexao).Salvar(_antes);
                            }
                        }

                        else if (_zeusNsu.ResNFe != null)
                        {
                            nsu.DataHoraConsulta = _zeusNsu.ResNFe.dhEmi;
                            nsu.IsNfe = true;
                            nsu.EmitenteCnpj = _zeusNsu.ResNFe.CNPJ ?? _zeusNsu.ResNFe.CPF;
                            nsu.EmienteRazaoSocial = _zeusNsu.ResNFe.xNome;
                            nsu.NfeChave = _zeusNsu.ResNFe.chNFe.OnlyNumber();
                            nsu.NfeNumero = nsu.NfeChave.Length != 44 ? 0 : nsu.NfeChave.Substring(25, 9).StrToIntDef();
                            nsu.NfeEmissao = _zeusNsu.ResNFe.dhEmi;
                            nsu.NfeValor = _zeusNsu.ResNFe.vNF;
                            nsu.NfeSituacao = Convert.ToInt32(_zeusNsu.ResNFe.cSitNFe) == 101 ? DfeNsuSituacao.Cancelado : DfeNsuSituacao.Transmitido;
                            nsu.Descricao = "Res NF-e";
                            new DfeNfeNsuDal(conexao).Salvar(nsu);

                            var dfexml = new DfeXml()
                            {
                                ChaveAcesso = $"ResNFe_{nsu.NfeChave}", //Não salvar com a chave original, lá quero apenas o NFeProc
                                EmissaoPropria = false,
                                XmlContent = xml
                            };

                            new DfeXmlDal(conexao).Salvar(dfexml);
                        }

                        else
                            Funcoes.GravarLog($"[CarregarNsu]{Environment.NewLine}Tipo {_zeusNsu.schema} não tratado na consulta de NSUs");

                        conexao.Commit();
                    }//foreach 
                }//using conexao
            }//try
            catch (Exception ex)
            {
                EstadoAtual = $"Falha - {ex.Message}";
                Funcoes.GravarLog($"[CarregarNsu]{Environment.NewLine}{ex.Message}");
                throw;
            }
        }

   //A classe aonde salvo tudo.
    public sealed class DfeNfeNsu : ModelBase
    {
        public long Id { get; set; }
        public int IdEmpresa { get; set; }
        public long Nsu { get; set; }
        public DateTimeOffset DataHoraConsulta { get; set; }
        public bool IsNfe { get; set; }
        public string Descricao { get; set; }
        public string EmitenteCnpj { get; set; }
        public string EmienteRazaoSocial { get; set; }
        public string NfeChave { get; set; }
        public long? NfeNumero { get; set; }
        public DateTimeOffset? NfeEmissao { get; set; }
        public decimal? NfeValor { get; set; }
        public DfeNsuSituacao? NfeSituacao { get; set; }

        public List<DfeEvento> Eventos { get; set; }
        public List<DfeXml> Xmls { get; set; }


        public int? NfeSerie => NfeChave.Length != 44 ? (int?)null : Funcoes.StrToIntNull(NfeChave.Substring(22, 3));

        public DfeNfeNsu()
        {
            Id = 0;
            IdEmpresa = 0;
            Nsu = 0;
            DataHoraConsulta = DateTime.Now;
            IsNfe = false;
            Descricao = string.Empty;
            EmitenteCnpj = null;
            EmienteRazaoSocial = null;
            NfeChave = null;
            NfeNumero = null;
            NfeEmissao = null;
            NfeValor = null;
            NfeSituacao = null;

            Eventos = new List<DfeEvento>();
            Xmls = new List<DfeXml>();
        }

    }
```

Existe um erro clássico de que sempre deve-se pensar de 50 em 50 no  NSU... bem, as vezes retorna menos que 50, ja vi acontecer o que causaria um salto de sequência. Então sempre pegue o ultimo  passe novamente, esqueça a regra de 50, se vier 100 vc vai estar pronto assim como se vier 10.

![image](https://user-images.githubusercontent.com/15945003/105576961-57b4c480-5d55-11eb-8936-0db96dcc45f7.png)

**Comment by casleandro** [comment]
Então, já realizo essa consulta de 50 em 50, tem vezes que da certo e outras não.
Já coloquei condições como pode ver no código que postei uns dias atrás e ainda continua dando o mesmo

**Comment by leogregianin** [comment]
Bom dia, o erro de "Consumo Indevido" que ocorre pode não ser no seu código e sim, um outro serviço/software utilizando o mesmo certificado e consultando ou baixando as NF-es. Por exemplo, o software da contabilidade do seu cliente utilizando o mesmo serviço ao mesmo tempo que o seu software, a Receita irá identificar o consumo indevido.

**Comment by marcosgerene** [comment]
@casleandro 

Quando o consumo é muito grande ele vai barrar. Geralmente acontece comigo quando estou populando a tabela na primeira vez, cliente com um volume grande de entradas vai gerar várias requisições e a Sefaz vai te falar "calma ai campeão".

Quando implanto um cliente novo, minha solução é transformar isso num serviço e passar o dia todo buscando esses dados com solicitações mais espaçadas até atingir o real ultimo NSU. Depois disso, o próprio "dia-a-dia" acaba se encarregando de não deixar esse volume muito grande (mais que 3 ou solicitações).

Exemplo da minha tabela de NSU na base:

![image](https://user-images.githubusercontent.com/15945003/105852656-7f10c900-5fc3-11eb-8c48-95b0ad1a3ce6.png)


@leogregianin
>Bom dia, o erro de "Consumo Indevido" que ocorre pode não ser no seu código e sim, um outro serviço/software utilizando o mesmo certificado e consultando ou baixando as NF-es. Por exemplo, o software da contabilidade do seu cliente utilizando o mesmo serviço ao mesmo tempo que o seu software, a Receita irá identificar o consumo indevido.

Acredito que não, para mim tem mais a ver com volume de solicitações mesmo.

**Comment by rodrigosousa1** [comment]
Boa tarde, ultimamente tem acontecido isso comigo também, ainda não consegui resolver. Tenho usado a lógica de pegar o último NSU e adicionar +1 para realizar a próxima consulta, e até o mês passado estava funcionando normalmente as consultas sem bloqueio algum por parte do webservice. Ainda não fiz uma analise a fundo disso, mas o que eu percebi foi que só está sendo feito no máximo três requisições com sucesso, na quarta já é devolvido consumo indevido do webservice. Testei com mais de uma empresa e todas aconteceram a mesma coisa. A única que funcionou foi uma que realizou apenas três requisições para o webservice, e essa conseguiu pegar todos os documentos. 

> Quando implanto um cliente novo, minha solução é transformar isso num serviço e passar o dia todo buscando esses dados com solicitações mais espaçadas até atingir o real ultimo NSU. Depois disso, o próprio "dia-a-dia" acaba se encarregando de não deixar esse volume muito grande (mais que 3 ou solicitações).

A ideia é válida, porém para o meu caso, nosso sistema busca apenas com certificado A3, meio complexo e até inviável fazer isso, e também, geralmente os contadores querem esses documentos pra ontem.

Fiz um teste em outra aplicação (Fiscal.io) que se não me engano utiliza essa mesma Lib e eles conseguem baixar todos os documentos no mesmo momento, não da esse erro de consumo indevido.

**Comment by rodrigosousa1** [comment]
Bom dia, realizei uns testes hoje e percebi que não se pode usar o Ultimo NSU + 1 para realizar a próxima consulta, porque o próprio Webservice já faz esse processo. Removendo esse +1 eu consegui realizar a busca de todos os documentos da empresa quando informado NSU 0, não mais gerando o consumo indevido.

**Comment by felixsevero** [comment]
Bom dia, você quer dizer que está passando o último NSU sempre como zero?

**Comment by rodrigosousa1** [comment]
Não... Eu estou passando  exatamente o número retornado pelo webservice. Antes quando ia fazer a primeira consulta da empresa, era feito no máximo 3 consultas no webservice e o mesmo retornava consumo indevido, isso independentemente de NSU 0 ou não. Depende mais da quantidade de consultas que você faz na receita.

A regra que eu utilizava para próxima consulta era pegar o ultimo NSU retornado, adicionar +1 e então realizar a consulta, contudo fazer isso faz com que o webservice retorne consumo indevido na quarta consulta.
Removendo essa regra de adicionar +1 e passando exatamente o último NSU retornado resolveu meu problema. Fiz o teste aqui com algumas empresas e coloquei para buscar tudo dela (NSU 0), para uma empresa aqui no caso e consegui fazer 359 consultas no Webservice sem problema algum.

**Comment by felixsevero** [comment]
Eu verifiquei meu código e faço assim também. Tinha seguido o manual e essa deve ser a forma correta de implementar.

**Comment by rodrigosousa1** [comment]
Antes funcionava, acredito que essa mudança é recente.

**Comment by marcosgerene** [comment]
@rodrigosousa1 
>Não... Eu estou passando exatamente o número retornado pelo webservice. Antes quando ia fazer a primeira consulta da empresa, era feito no máximo 3 consultas no webservice e o mesmo retornava consumo indevido, isso independentemente de NSU 0 ou não. Depende mais da quantidade de consultas que você faz na receita.
>
>A regra que eu utilizava para próxima consulta era pegar o ultimo NSU retornado, adicionar +1 e então realizar a consulta, contudo fazer isso faz com que o webservice retorne consumo indevido na quarta consulta.
Removendo essa regra de adicionar +1 e passando exatamente o último NSU retornado resolveu meu problema. Fiz o teste aqui com algumas empresa e coloquei para buscar tudo dela (NSU), para uma empresa aqui no caso e consegui fazer 359 consultas no Webservice sem problema algum.

No código que enviei não mando ultimo +1, mas sim ultimo, mesmo assim "de vez em nunca" acontece aqui o problema, por isso preciso que o NSU chegue no "dia-a-dia" para funcionar. Na implantação de cliente de volume médio, lembrando que o NSU fica disponível por 6 meses, tenho na casa de 3.000 NSUs para a primeira carga, ou seja, na casa de 60 solicitações. 

Em 1 ou 2 horas consigo trazer o real ultimo NSU, quando o erro "some".

**Comment by rodrigosousa1** [comment]
@marcosgerene 
Sim eu entendi, eu faço dessa maneira também. Eu deixo o último NSU da empresa armazenado para sempre pegar o da última vez que foi consultado. No o exemplo que dei ai, para a primeira carga, de uma empresa aqui, eu fiz 359 consultas (cada consulta retorna 50, percorri um total de 17k de NSU), rodou sem problema algum. 

E eu fazia exatamente como em uma print que você mandou de uma conversa, após esse trecho:

> Existe um erro clássico de que sempre deve-se pensar de 50 em 50 no NSU... bem, as vezes retorna menos que 50, ja vi acontecer o que causaria um salto de sequência. Então sempre pegue o ultimo passe novamente, esqueça a regra de 50, se vier 100 vc vai estar pronto assim como se vier 10.

E isso estava fazendo ocorrer o consumo indevido.

**Comment by lucascborges** [comment]
Boa tarde, estou passando pelo mesmo a alguns dias, hoje tentei de toda forma, tinha em media 3 mil NSUs para baixar, agora a tarde coloquei um Thread.Sleep(10000) entre cada consulta e parece que resolveu, amanha vou tentar mudando para 5 segundos, nosso volume de documentos e eventos é enorme.

**Comment by marcosgerene** [comment]
@lucascborges 

Só a titulo de curiosidade, essa média de 3000 NSUs é a cada quanto tempo?

**Comment by lucascborges** [comment]
Pelo que notei, é diario, pois alem das NFS destinadas, a empresa tambem faz transporte. Entao tem as NFS onde ela é transportadora e os eventos Sobre CTE e MDFe. No inicio do dia de hoje, ajustei o ultNSU = maxNSU e agora a tarde tinha essa quantidade.

**Comment by marcosgerene** [comment]
@lucascborges 

Você é terceirizado ou é funcionário da empresa? Achei interessante o seu volume para estudo de caso.

**Comment by lucascborges** [comment]
Sou terceirizado, cuido do TI da empresa, e desenvolvi uma ferramenta para a integração com o TOTVS Protheus e eles são meu laboratorio.
