### ISSUE TITLE
Exceção ao imprimir NFCe

### ISSUE THREAD

**Issue by felixsevero** [ZeusAutomacao/DFe.NET#1205]
Boa tarde, estou utilizando o projeto NFe.Danfe.Nativo para a impressão de NFCe. Hoje obtive uma exceção ao utilizar a unidade de medida "Metro", cuja abreviação é "M".
Ao analisar, percebi um problema na seguinte linha:

https://github.com/ZeusAutomacao/DFe.NET/blob/1b202f7e3cedd826f36fb938124a2a9fb6d998a0/NFe.Danfe.Nativo/NFCe/DanfeNativoNfce.cs#L244

De acordo com a Tabela de Unidade de Medida Comercial, isso gerará uma exceção para o Metro (M) e o Quilate (K).

Caso concordem, eu posso criar um PR para corrigir isso.

**Comment by danilobreda** [comment]
Acredito que seja um bug mesmo @felixsevero , o Substring(0,2) irá gerar uma exceção... pois o tamanho é de 1 caracter apenas :D Acredito que da pra mata verificando o tamanho mínimo, se o tamanho do uCom for 1, fica (0, 1), senão continua como está (0, 2).

Fico no aguardo do PR! 
Agradeço muito a ajuda!

**Comment by danilobreda** [comment]
@felixsevero obrigado pela contribuição 👍
