### ISSUE TITLE
Manifestação de Destinatário não aparece no Portal da Nota Fiscal

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1207]
Ola amigos, estou com uma dúvida, estou conseguindo fazer a ciência e confirmação de operação da nfe, conclui com sucesso o evento registrado, porem quando vou no portal da nota fiscal ou no sitio das sefaz dos emitentes, não aparece no quadro de eventos e serviços, ja aguardei 24h para ve se houve algum atraso, mas nada, somente aparece o estatus que foi autorizado. Alguém pode me informar se isso esta acontecendo em nível nacional ou se é alguma dll ou schema do Zeus no meu sistema. Obrigado

**Comment by robertorp** [comment]
Pelo que você falou, ta parecendo que a sefaz está demorando

Teria que investigar melhor seu software, se poder postar algumas prints do passo a passo que faz é prints da parte do código fonte onde você preenche as informações do evento , de consulta manifestação etc.. tudo relacionado a manifestação, o máximo que conseguir disponibilizar de informações , assim talvez eu ou alguém da comunidade consegue identificar se tem algum problema ou não em seus fontes

Mas o Zeus eu sou suspeito de falar hehehe , mas tenho manifestação, é esta ok para meus clientes

**Comment by sigridslima** [comment]
Segue codigo:

public void manifestacao()
        {
            try
            {
                #region ManifestacaoDestinatario
                /* Justificativa = null*/

                //string justificativa = txtJutificativa.Text;

                //var idlote = Funcoes.InpuBox(this, "Manifestação Destinatário", "Identificador de controle do Lote de envio:");
                //if (string.IsNullOrEmpty(idlote)) throw new Exception("A Id do Lote deve ser informada!");

                if (txtLoteManifestacao.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("A Id do Lote deve ser informada!");
                }
                //var sequenciaEvento = Funcoes.InpuBox(this, "Manifestação Destinatário", "Número sequencial do evento:");
                //if (string.IsNullOrEmpty(sequenciaEvento)) throw new Exception("O número sequencial deve ser informado!");


                if (txtSequencial.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("O número sequencial deve ser informado!");
                }

                //var chave = Funcoes.InpuBox(this, "Manifestação Destinatário", "Chave da NFe:");
                //if (string.IsNullOrEmpty(chave)) throw new Exception("A Chave deve ser informada!");
                //if (chave.Length != 44) throw new Exception("Chave deve conter 44 caracteres!");

                if (txtCahveAcessoNota.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("A Chave deve ser informada!");
                }
                //var codigoEvento = Funcoes.InpuBox(this, "Manifestação Destinatário", "Código do Evento da Manifestação:");
                //if (string.IsNullOrEmpty(codigoEvento)) throw new Exception("O Código do Evento da Manifestação deve ser informado!");
                //if (codigoEvento.Length != 6) throw new Exception("O Código do Evento da Manifestação deve conter 6 caracteres!");

                if (txtCodigoEvento.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("O Código do Evento da Manifestação deve ser informado!");
                }
                //var cnpj = Funcoes.InpuBox(this, "Manifestação Destinatário", "CNPJ do destinatário da NFe:");
                //if (string.IsNullOrEmpty(cnpj)) throw new Exception("O CNPJ deve ser informado!");
                //if (cnpj.Length != 14) throw new Exception("O CNPJ deve conter 14 caracteres!");
                
                if (txtCPFeCNPJ.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("O CNPJ deve ser informado!");
                }

                var tipoEvento = (NFeTipoEvento)int.Parse(txtCodigoEvento.Text);
                //if (tipoEvento == NFeTipoEvento.TeMdOperacaoNaoRealizada)
                if (tipoEvento == NFeTipoEvento.TeMdOperacaoNaoRealizada)
                {
                    //justificativa = Funcoes.InpuBox(this, "Manifestação Destinatário", "Justificativa para a Operação Não Realizada");
                    //if (string.IsNullOrEmpty(justificativa)) throw new Exception("A justificativa deve ser informada!");

                    if (txtJutificativa.Text != "")
                    {
                        //MessageBox.Show("CNPJ do destinatário da NFe:");
                    }
                    else
                    {
                        MessageBox.Show("A justificativa deve ser informada!");
                    }
                }

                var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
                var retornoNFeDistDFe = servicoNFe.RecepcaoEventoManifestacaoDestinatario(int.Parse(txtLoteManifestacao.Text), int.Parse(txtSequencial.Text), txtCahveAcessoNota.Text, (NFeTipoEvento)int.Parse(txtCodigoEvento.Text), txtCPFeCNPJ.Text);

                TrataRetorno(retornoNFeDistDFe);

                #endregion
            }
            catch (ComunicacaoException ex)
            {
                MessageBox.Show(ex.Message, "Erro Comunicacao");
                lblEstatus.Text = "Não Validado";

            }
            catch (ValidacaoSchemaException ex)
            {
                MessageBox.Show(ex.Message, "Erro Schema");
                lblEstatus.Text = "Não Validado";
            }
            catch (Exception ex)
            {
                if (!string.IsNullOrEmpty(ex.Message))
                    MessageBox.Show(ex.Message, "Erro Geral");
                lblEstatus.Text = "Não Validado";
            }
        }

public void distribuicao()
        {

            try
            {
                #region NFeDistribuicaoDFe

                //var cnpj = Funcoes.InpuBox(this, "Consulta NFeDistribuicaoDFe", "CNPJ do destinatário da NFe:");
                //if (string.IsNullOrEmpty(cnpj)) throw new Exception("O CNPJ deve ser informado!");
                //if (cnpj.Length != 14) throw new Exception("O CNPJ deve conter 14 caracteres!");

                if (txtCPFeCNPJ.Text != "")
                {
                    //MessageBox.Show("CNPJ do destinatário da NFe:");
                }
                else
                {
                    MessageBox.Show("O CNPJ deve ser informado!");
                }
                //var nsu = Funcoes.InpuBox(this, "Consulta NFeDistribuicaoDFe", "Ultimo NSU Retornado");
                //if (string.IsNullOrEmpty(nsu))
                //    nsu = "0";

                //if (int.Parse(nsu) < 0) throw new Exception("NSU deve ser maior ou igual a 0");


                if (txtNSU.Text != "")
                {
                    //MessageBox.Show("Ultimo NSU Retornado");
                }
                else
                {
                    MessageBox.Show("NSU deve ser maior ou igual a 0");
                }
                //string chnfe = "";
                //if (string.IsNullOrEmpty(nsu) || int.Parse(nsu) <= 0)
                //    chnfe = Funcoes.InpuBox(this, "Consulta NFeDistribuicaoDFe", "Chave Eletrônica NFe");

                //if ((string.IsNullOrEmpty(nsu) || int.Parse(nsu) < 0) && string.IsNullOrEmpty(chnfe))
                //    throw new Exception("Último NSU ou Chave Eletrônica devem ser informados");

                if (txtCahveAcessoNota.Text != "")
                {
                    //MessageBox.Show("Chave Eletrônica NFe");
                }
                else
                {
                    MessageBox.Show("Chave Eletrônica devem ser informados");
                }

                var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
                var retornoNFeDistDFe = servicoNFe.NfeDistDFeInteresse(_configuracoes.EnderecoEmitente.UF.ToString(), txtCPFeCNPJ.Text, ultNSU: txtNSU.Text, chNFE: txtCahveAcessoNota.Text);

                TrataRetorno(retornoNFeDistDFe);

                #endregion
            }
            catch (ComunicacaoException ex)
            {
                MessageBox.Show(ex.Message, "Erro Comunicacao");
            }
            catch (ValidacaoSchemaException ex)
            {
                MessageBox.Show(ex.Message, "Erro Schema");
            }
            catch (Exception ex)
            {
                if (!string.IsNullOrEmpty(ex.Message))
                    MessageBox.Show(ex.Message, "Erro Geral");
            }
        }

**Comment by felixsevero** [comment]
Sobre consultar pelo navegador, tive um caso agora em dezembro onde o contador me passou que as notas fiscais, pelo menos da última semana, não estavam aparecendo, apesar de terem sido emitidas corretamente. Por ser uma infraestrutura assíncrona, pode ocorrer esses casos, não se preocupe. Se tiver certeza que foi autorizado pela Sefaz, mais cedo ou mais tarde irá aparecer.

**Comment by sigridslima** [comment]
E realmente foi efetuado o evento a nfe, gerou protocolo, porem ja tem mais de 48h que não aparece no site da sefaz.

**Comment by adeniltonbs** [comment]
Boa tarde @sigridslima, as partes de seu código que demonstram como está consumindo são:
```cs
 var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
            var retornoNFeDistDFe = servicoNFe.RecepcaoEventoManifestacaoDestinatario(int.Parse(txtLoteManifestacao.Text), int.Parse(txtSequencial.Text), txtCahveAcessoNota.Text, (NFeTipoEvento)int.Parse(txtCodigoEvento.Text), txtCPFeCNPJ.Text);
```
e

```cs
var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
            var retornoNFeDistDFe = servicoNFe.NfeDistDFeInteresse(_configuracoes.EnderecoEmitente.UF.ToString(), txtCPFeCNPJ.Text, ultNSU: txtNSU.Text, chNFE: txtCahveAcessoNota.Text);
``` 
O resto são detalhes de sua implementação.
Aparentemente tudo certo com a chamada dos métodos, você deve verificar o `cStat` e `xMotivo` do retorno `retEnvEvento` para ver se tudo ocorreu bem.

Infelizmente esse serviço é assim mesmo. Para mim esse é o padrão. Sempre leva mais de um dia para sincronizarem. E demora ainda mais no ambiente de homologação.

Ps: Não pude deixar de notar alguns problemas com seu código, espero que não seja de produção :)
Sugiro dar uma olhada no livro Clean Code do Robert C. Martin
https://medium.com/desenvolvendo-com-paixao/1-clean-code-o-que-%C3%A9-porque-usar-1e4f9f4454c6

**Comment by danilobreda** [comment]
Conseguiu resolver o problema @sigridslima ?

**Comment by danilobreda** [comment]
Fechado por falta de retorno do autor, caso necessário comente para eu reabrir a issue.
