### ISSUE TITLE
Dúvida - Tamanho PDF DANFE

### ISSUE THREAD

**Issue by CaioSantAnna** [ZeusAutomacao/DFe.NET#1208]
Boa tarde. 

Por favor, recentemente atualizei um projeto que fazia uso de uma versão do Zeus de 2019. Ai notei que a versão atual da aplicação de testes em .Net Core 3.1 NFe.Danfe.AppTeste.NetCore gera uma DANFE em PDF com uma qualidade superior à versão que a mesma aplicação em .Net Core 2.2 gerava em 2019.

O problema é que o tamanho dos PDFs mais do que triplicou na comparação de algumas notas que fiz aqui, e no meu cenário, esse aumento de tamanho é relevante.

Ai estava pesquisando por formas de reduzir isso e queria queria saber se no projeto existe alguma configuração ou recurso para reduzir o tamanho final dos PDFs, mesmo que eventualmente ao custo de qualidade da DANFE.

Muito obrigado.

**Comment by danilobreda** [comment]
Acredito que exista a propriedade **ImageDpi** na classe [PDFSimpleExport](https://github.com/FastReports/FastReport/blob/d433d505823e84140ad4458baff253a7a91811f4/Extras/OpenSource/FastReport.OpenSource.Export.PdfSimple/FastReport.OpenSource.Export.PdfSimple/PDFSimpleExport.Config.cs) do OpenFastReport que você pode modificar.
No Zeus para acessar o mesmo, você deve utilizar a classe [DanfeBase](https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Danfe.Fast.Standard/DanfeBase.cs) e acessar a propriedade Relatorio e criar um metodo proprio usando o mesmo exemplo de [ExportPDF](https://github.com/ZeusAutomacao/DFe.NET/blob/54dcca022534ac71599ca9ac88c61d795fb0c4f7/NFe.Danfe.Fast.Standard/DanfeBase.cs#L64) modificando essa propriedade ImageDpi na parte do  `Relatorio.Export(new PDFSimpleExport()/*aqui*/, outputStream);`
É apenas uma dedução e ainda não testei esse modelo, não utilizo o openfastreport para exportar em pdf, apenas para exportar em HTML. utilizo o [wkhtmltopdf ](https://github.com/fpanaccia/Wkhtmltopdf.NetCore) para converter meus HTMLs para PDF caso o usuário necessite. Isso por conta que antigamente (não sei se ainda persiste) o uso de memória para gerar um DANFE em pdf com o openfastreport era altíssimo para meu cenário em microservices.

**Comment by CaioSantAnna** [comment]
Muito obrigado pelas informações.
