### ISSUE TITLE
Como implantar a emissão para gás liquefeito (Código do Produto na ANP) *comb

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1209]
Ola amigos, estou com um cliente que emite nfe e nfc-e e gaz de cozinha, segundo a contabilidade o cfop que poderá se utilizado e o 5656, porem verifiquei que tem q informar o codigo ANP: 210203001 - Descrição: GASES LIQUEFEITO   DE PETRÓLEO - GLP.

Como posso acrescentar no xml.

<comb>
        <cProdANP>210203001</cProdANP>
        <UFCons>ES</UFCons>
 </comb> 

//Codigo:

protected virtual prod GetProduto(int i)
        {

            int zero = Int32.Parse(txtIdProdutoXml.Text);
            var p = new prod
            {
                cProd = txtIdProdutoXml.Text = zero.ToString("0000"),
                cEAN = "",
                xProd = txtProdutoXml.Text,
                NCM = txtNcmXml.Text,
                CFOP = Int32.Parse(txtCFOPXml.Text),
                uCom = txtUnidadeXml.Text,
                qCom = Decimal.Parse(txtQuantidadeXml.Text),
                vUnCom = Decimal.Parse(txtValorUnitarioXml.Text),
                vProd = Decimal.Parse(txtValorTotalXml.Text),
                vDesc = Decimal.Parse(txtValorDescontoXml.Text),
                cEANTrib = "",
                uTrib = txtUnidadeTribXml.Text,
                qTrib = Decimal.Parse(txtQuantidadeTribXml.Text),
                vUnTrib = Decimal.Parse(txtValorUnitarioTribXml.Text),              
                indTot = IndicadorTotal.ValorDoItemCompoeTotalNF

//aqui implemento do comb // ProdANP // UFCons
            };
            return p;
        }
 
Obrigado

**Comment by adeniltonbs** [comment]
Boa noite, use o atributo `ProdutoEspecifico` da classe prod. Ele irá aceitar qualquer um dos tipos `veicProd`, `med`, `arma` ou `comb`.
![image](https://user-images.githubusercontent.com/6733483/105112667-47c18a00-5aa2-11eb-91bb-5586ba3ff84a.png)
Adicionalmente dê uma olhada no [Anexo I - Leiaute e Regra de Validação - NF-e e NFC-e](http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=), página 24.

Exemplo hipotético:
```cs
  ProdutoEspecifico = new comb()
  {
      cProdANP = "210203001",
      descANP = "GASES LIQUEFEITO DE PETRÓLEO - GLP",
      UFCons = "ES"
  }
```

**Comment by sigridslima** [comment]
Obrigado, amigo deu certo.
