### ISSUE TITLE
Dois repositorios

### ISSUE THREAD

**Issue by marcelokrol** [ZeusAutomacao/DFe.NET#121]
Ola, obrigado pela resposta ao issue anterior, mais tenho mais uma duvida: observei que ali possui dois repositórios de códigos. Então a duvida: 
- Qual devo pegar pra utilizar?
- Qual a diferença entre cada um?

**Comment by adeniltonbs** [comment]
Use o branch master https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe.
O outro foi feito para implementar a impressão do DANFE da NFe, mas ainda não está pronto, e no momento, está defasado.

**Comment by marcelokrol** [comment]
Já que voce citou, estas bibliotecas comtemplam a NF-e em 100% ou somente a NFC-e

**Comment by robertorp** [comment]
NF-e é NFC-e se olhar https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/README.md
vai ver que tem algumas coisas que faltam mas nada impede o uso do que realmente é necessário

**Comment by leandrossantos** [comment]
@marcelokrol a parte de geração de XML e comunicação com WS está 100% para NFe e NFCe. A única coisa que não tem funcionando para NFe é a DANFe
