### ISSUE TITLE
erro ao gerar uma carta de correção no Net Core 3.2

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1210]
Fala Pessoal, 

Estou com um probleminha .
Ao enviar uma carta de correção no net core.
Sem comunicação com o serviço RecepcaoEventoCartaCorrecao:
The operation has timed out.
Segue a imagem do envio que estou fazendo.
![image](https://user-images.githubusercontent.com/71778467/105419836-1b327d00-5c1e-11eb-9ac1-4f6033a3ff61.png)

**Comment by marcosgerene** [comment]
@khaddmussistemas 

Você está recebendo um "timed out" do servidor. Manda o print das suas configurações ```configuracaoNFe```.

**Comment by khaddmussistemas** [comment]
Opa ! Bom dia, 

![image](https://user-images.githubusercontent.com/71778467/105487778-66d13f00-5c8f-11eb-8a25-62080f544723.png)

Segue a imagem da configuração.

**Comment by marcosgerene** [comment]
Seu timeout está em 3.000 milisegundos, ou seja, 3 segundos, muito baixo.

Seta para 30.000 (30 segundos) e tenta novamente

**Comment by khaddmussistemas** [comment]
Funcionou. obg marcos

Em sex., 22 de jan. de 2021 às 11:27, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:
