### ISSUE TITLE
DANFe NFCe Nativo (Problema com fonte)

### ISSUE THREAD

**Issue by felixsevero** [ZeusAutomacao/DFe.NET#1211]
Ao gerar o DANFe NFCe Nativo no Windows 7 como imagem, em qualquer formato, eu obtenho uma imagem cujo cabeçalho contendo as informações da empresa estão sendo colocadas sobre os produtos, como pode ser visto na imagem abaixo:

![NFCe](https://user-images.githubusercontent.com/23054347/105560519-bbf26c80-5cf2-11eb-809f-8c9bea12cc0a.jpeg)

Obs: Isso só acontece ao gerar como imagem, eu não tenho nenhum problema quando é impresso.

No Windows 10 eu percebi que isso não acontece, sendo a imagem gerada perfeitamente. Alguém já passou por isso?

**Comment by robertorp** [comment]
Verificou se as fontes estão instaladas corretamente no Windows 7? Talvez o windows 10 já tenha elas ou é mais fácil de instalar/aceitar.

**Comment by felixsevero** [comment]
No Windows 7 eu recebia o seguinte erro: `System.ArgumentException: Font 'Open Sans Condensed' does not support style 'Regular'`.
Então instalei e passei a utilizar a fonte `Ubuntu Condensed`, conforme visto em #487
Esqueci de fazer alguma coisa para resolver esse problema?

**Comment by felixsevero** [comment]
Por conta do seu comentário, resolvi testar outras fontes e, realmente, a geração da imagem muda totalmente de acordo com a fonte escolhida. Por exemplo, para a fonte `Roboto Condensed`:

![NFCe](https://user-images.githubusercontent.com/23054347/105568292-f8d05a80-5d16-11eb-8a22-5589495354e8.jpeg)

Já era esperado que a mudança da fonte causasse uma diferença tão grande na imagem?

**Comment by leandrossantos** [comment]
Bom dia pessoal, desculpa  minha ignorancia, mais procurei no projeto e não achei onde trocar a fonte, pois estou com o mesmo erro da fonte citado pelo colega @felixsevero

**Comment by felixsevero** [comment]
Bom dia @leandrossantos, você pode definir a fonte da seguinte forma:
`DanfeNativoNfce danfeNativoNfce = new DanfeNativoNfce(xml, configuracaoDanfeNfce, cIdToken, csc, font: "<NOME-DA-FONTE>");`

Lembrando que ela precisa estar instalada no computador.

**Comment by leandrossantos** [comment]
> Bom dia @leandrossantos, você pode definir a fonte da seguinte forma:
> `DanfeNativoNfce danfeNativoNfce = new DanfeNativoNfce(xml, configuracaoDanfeNfce, cIdToken, csc, font: "<NOME-DA-FONTE>");`
> 
> Lembrando que ela precisa estar instalada no computador.

valeu, fiz aqui e deu certinho.

**Comment by felixsevero** [comment]
Se souber de alguma fonte cuja imagem gerada fique perfeita, eu ficaria grato. Acabei não experimentando outras fontes até o momento.

**Comment by danilobreda** [comment]
@felixsevero poderia verificar se podemos fechar essa issue? Tive problemas na fonte em ambiente linux tambem principalmente na impressão do DANFE em fastreport, parece que a fonte infelizmente é um problema na maioria das impressões e em diferentes sistemas e versões de sistemas, infelizmente as vezes precisa ser feito um teste manual um por um.

**Comment by felixsevero** [comment]
@danilobreda acho que você está certo. Obrigado pelo comentário, vou fechar a issue.
