### ISSUE TITLE
Protocolo na Impressão

### ISSUE THREAD

**Issue by rhaelandrade** [ZeusAutomacao/DFe.NET#1212]
Boa Tarde
galera porque quando emito uma nota fiscal nfce em contingência e depois envio ela pra sefaz e vou reimprimi-la não aparece o numero do protocolo na impressão?.
estou usando a impressão do fastreport.

**Comment by marcosgerene** [comment]
@rhaelandrade

**Comment by marcosgerene** [comment]
Fechei sem querer, desculpe.

Sobre o protocolo, se voce passa ele, ele imprime sim. Poste um XML para que possamos entender.

**Comment by rhaelandrade** [comment]
Não imprimir não amigo já testei direto no fonte do Zeus pegue um xml de uma nfce que foi enviado em contingência é tente imprimir pra vc ver se o protocolo aparece na impressão

**Comment by marcosgerene** [comment]
@rhaelandrade 

Eu não uso a impressão do Zeus nos meus projetos para impressora térmica... posta seu XML aqui que vou tentar imprimir, se for o caso corrijo aqui e no projeto Esc-Pos caso esteja faltando também.
