### ISSUE TITLE
Erro de Assembly referenciado 

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#1218]
Ola 
Estou com o seguinte erro:

Lembrando que estou usando a versão 
![image](https://user-images.githubusercontent.com/26013017/107084112-624f6f00-67d5-11eb-8e86-2105eeef071e.png)

```
1>CSC : warning CS8002: Assembly referenciado "NFe.Classes, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
1>CSC : warning CS8002: Assembly referenciado "NFe.Utils, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
1>CSC : warning CS8002: Assembly referenciado "FastReport, Version=2018.1.9.0, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
1>CSC : warning CS8002: Assembly referenciado "DFe.Classes, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
1>CSC : warning CS8002: Assembly referenciado "NFe.Servicos, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
1>CSC : warning CS8002: Assembly referenciado "DFe.Utils, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null" não tem um nome forte.
```

Se alguem puder me ajudar obrigado.

**Comment by danilobreda** [comment]
Seu projeto deve estar **signed**, desabilite o checkbox da imagem a seguir (para mais detalhes cole o .csproj do seu projeto aqui, para eu verificar o que pode ser)
![image](https://user-images.githubusercontent.com/14843499/107107054-8333b680-680d-11eb-9822-5719e52494e8.png)

**Comment by ghost** [comment]
Bom dia, 
@danilobreda  está habilitado o signed e preciso que esteja habilitado. 

Att.

**Comment by danilobreda** [comment]
@fabiociaf achamos o problema, as DLLs do Zeus não são assinadas, todas as DLLs que voce usa em um aplicativo signed precisa ser signed.
Muitas bibliotecas também não são, algumas tem até um **nuget** separado com final _.Signed_ pra mostrar que é assinado... Acredito que você terá que pegar o projeto manualmente e assinar as DLLs manualmente, pesquisando um pouco você acha algo como esse link ["using unsigned assemblies in signed ones"](https://stackoverflow.com/questions/7977363/using-unsigned-assemblies-in-signed-ones).

**Comment by danilobreda** [comment]
Só para entender, existe muita discussão sobre esse assunto e a comunidade opensource tem sofrido muito com esse assunto e até mesmo corrido longe de "strongNames" ou "signed dlls" [aqui um link que fala sobre.](https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/)
@fabiociaf Poderia nos dizer o motivo de sua aplicação ser necessário estar habilitado o signed?

**Comment by ghost** [comment]
Entendo, bom @danilobreda  
Estamos tendo problemas com antivírus que esta detectando como vírus. 
Então foi solicitado para nos assinar o exe para eles poder liberar nosso sistema.

**Comment by danilobreda** [comment]
@fabiociaf aqui na empresa também tivemos esse mesmo problema, criamos um assinador de arquivo que assina nosso executável após o build e gerado o exe! 
Segue zip do projeto... acredito que irá te ajudar.
[SignFileDanilo.zip](https://github.com/ZeusAutomacao/DFe.NET/files/5954325/SignFileDanilo.zip)

**Comment by robertorp** [comment]
Talvez tem como eu colocar isso no projeto do Zeus, quando fizer o build do nuget pelo appveyor , eu coloco o appveyor pra executar o .exe do @danilobreda  pelo cmd

É possível executar ele por cmd @danilobreda ?

**Comment by danilobreda** [comment]
@robertorp acredito que esse executavel seja possivel executar pelo cmd sim! Porem não recomendo a gente usar isso em cima da biblioteca Zeus, pois acho que como é um dll acredito que não resolve o problema original que é a classe ter "strongNames" por ser "signed", que deve ser feito ao buildar o Zeus. 
Esse programa é apenas para assinar ".exe" com um certificado especifico.
Para resolver o problema original a gente deveria duplicar todos os projetos que temos, setar esse novos projetos como **signed** com **strongname** e todas as "dependencias" a terceiros(que não temos controle) deverá ser **signed** **tambem**... ai disponibilizar esse NUGET  a parte do que temos hoje. Esse processo acredito que é totalmente inviável e até mesmo impossível...
A pergunta do **porque ele precisa ser signed** a nossa DLL teve a resposta que **ele precisa assinar a aplicação EXE dele**, porem da **para assinar fora do ecosistema .NET e Visualstudio**, através do assinador que passei... 
Assim ele não precisa setar o projeto dele signed e vida que segue :D

@fabiociaf Sobre o assinador... Tem outros por ai com certeza... Até alguns próprios da microsoft... 
O que muda é o .EXE ter um certificado...
Se for em detalhes do certificado, fica como por exemplo a imagem a seguir... (exe do driver da nvidia)
![image](https://user-images.githubusercontent.com/14843499/107448011-8eddf080-6b1f-11eb-9bb4-ed6e68f67b79.png)

**Comment by danilobreda** [comment]
Opa achei esse carinha aqui... talvez seja mais seguro por vir da microsoft do que o meu feito no fundo de quintal haha [https://docs.microsoft.com/pt-br/dotnet/framework/tools/signtool-exe](https://docs.microsoft.com/pt-br/dotnet/framework/tools/signtool-exe)

Tem bastante conteudo sobre...
[https://www.google.com/search?&q=how+to+use+signtoll](https://www.google.com/search?&q=how+to+use+signtoll)

**Comment by ghost** [comment]
Bom dia, 
Obrigado @danilobreda  eu entendo os pontos colocado. 
Vou testar aqui!!!
Assinar de outra maneira. 
Que bom voce tambem passou por isso.

**Comment by danilobreda** [comment]
Acredito que o caso tenha sido resolvido @fabiociaf qualquer dúvida só entrar em contato!
