### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by Roberiopraciano** [ZeusAutomacao/DFe.NET#122]
por favor, alguem sabe a compatibilidade com xamarin?

**Comment by adeniltonbs** [comment]
Não sei te dizer, mas quando vc testar, se puder, coloque aqui os resultados.

**Comment by orochasamuel** [comment]
@Roberiopraciano eu também tenho interesse em utilizar a biblioteca (no futuro) para aplicações Xamarin, com relação à compatibilidade acho que é tranquilo, todavia, só testando mesmo para ter plena certeza.

Uma citação me chamou a atenção:

> And good news for all .NET geeks: you can really use all of your beloved and old-shoe technologies like C#, linq, Parallel, Generics etc. Say thanks to a Mono framework that made it possible.

Fonte: http://www.nexgendesign.com/7-reasons-xamarin-can-be-a-trouble
