### ISSUE TITLE
Seção de pagamento está como lista

### ISSUE THREAD

**Issue by sinfeadmin** [ZeusAutomacao/DFe.NET#1222]
Pessoal, a seção de pagamento (tag "pag") está como uma lista dentro da infNFe. Tem alguma razão para isso? Porque nas notas técnicas, ela tem um relacionamento de 1-1 com a tag pai (infNFe).

**Comment by danilobreda** [comment]
**Referente:**
Class [infnfe](https://github.com/ZeusAutomacao/DFe.NET/blob/master/Shared.NFe.Classes/Informacoes/infNFe.cs)
Class [pag](https://github.com/ZeusAutomacao/DFe.NET/blob/master/Shared.NFe.Classes/Informacoes/Pagamento/pag.cs)

**Segundo o manual** [6.00](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=)
(Versão não utilizada hoje)
![image](https://user-images.githubusercontent.com/14843499/108607240-f7d62b80-739d-11eb-9d82-a582109f61a1.png)

**Segundo a** [NT_2016_002_v1.61](https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=tW+YMyk/50s=)
(Atualização que modificou essa questão)
![image](https://user-images.githubusercontent.com/14843499/108607375-daee2800-739e-11eb-8fe8-f3d56ab3df5b.png)

Percebe-se que realmente antigamente o pag era de 0-100, e agora na verdade é apenas um e o detpag 1-100.

Acredito que a **List** é por conta de XMLs antigos com versões anteriores a NT 2016_002 , essa transição teve de ser bem tranquilo na época por isso se manteve da maneira que está hoje... ou seja é uma questão histórica.

**Comment by sinfeadmin** [comment]
Fala @danilobreda obrigado pela resposta.

Como é o procedimento para questões como essa? Mantemos o histórico ou atualizamos para a nova versão? Se for possível alterar para a nova versão (apenas uma "pag" ao invés de uma List<pag>), posso fazer numa boa.

Valeu!

**Comment by robertorp** [comment]
Foi mantido na época assim para ser compatível com 3.10 é 4.00 pois avia uma transição, ou seja deveria suportar tanto o 3.10 é 4.00 para ser uma transição mais tranquila, é , quando um cliente seu quiser imprimir um danfe 3.10 ele imprimiria também , hoje atualmente provavelmente se deletarmos não dará problemas , acho muito difícil achar um xml 3.10 por aí , mas.. para deletar teria que ajustar as impressões do Zeus também , ou seja algo um pouco trabalhoso , não é somente sumir o campo é ta de boa , precisa fazer uma testagem de impressões é ajustes. Nada muito difícil e nem muito fácil .

**Comment by robertorp** [comment]
> Fala @danilobreda obrigado pela resposta.
> 
> Como é o procedimento para questões como essa? Mantemos o histórico ou atualizamos para a nova versão? Se for possível alterar para a nova versão (apenas uma "pag" ao invés de uma List), posso fazer numa boa.
> 
> Valeu!

Você pode implementar já direto na versão 4.00 no seu sistema, que não tera problemas. 
Pra se ter uma ideia na época que fiz isso, eu tinha um flag no meu sistema, usar layout 4.00 , se marcasse usava ele se não marcasse usava o 3.10 , pois avia estados que estavam operando 4.00 é outros 3.10 , nunca dá certo de dizer vai funcionar tudo agora 4.00 , não é bem assim que funciona na vida real, agora na teoria funciona perfeito.

**Comment by sinfeadmin** [comment]
Fala @robertorp, sem problemas. Qualquer coisa deixamos do jeito que está no fork principal e eu trabalho com isso apenas no meu fork.

Melhor não alterar, pois pode destruir a compilação de alguém. ;-)

Obrigado pelas respostas.
