### ISSUE TITLE
Enum IndicadorIntermediador está fixo com 0 nos dois "XmlEnum"

### ISSUE THREAD

**Issue by RicardoSharp** [ZeusAutomacao/DFe.NET#1226]
Enum IndicadorIntermediador está fixo com 0 nos dois "XmlEnum"

**Comment by marcosgerene** [comment]
@RicardoSharp 

Obrigado por reportar a falha.

Não consegui identificar o problema, se puder ser mais específico de onde isso acontece, agradeço.

Declaração:

https://github.com/ZeusAutomacao/DFe.NET/blob/dab781c26b8ff6b52122a303e4f16a77ad3a3987/Shared.NFe.Classes/Informacoes/Identificacao/Tipos/ideTipos.cs#L433

Usos:

https://github.com/ZeusAutomacao/DFe.NET/blob/2110afcd014b408764fb1ae619c0d51a3c94b670/Shared.NFe.Classes/Informacoes/Identificacao/ide.cs#L208

https://github.com/ZeusAutomacao/DFe.NET/blob/24580f9a7438b9164d6d7daba3dd42c6881130b2/NFe.AppTeste/MainWindow.xaml.cs#L948

**Comment by marcosgerene** [comment]
Olhando no histórico do arquivo, encontrei esse comit: https://github.com/ZeusAutomacao/DFe.NET/commit/c03d4cf36810a774bbb113cbbef4ea2cfde05c59

O problema foi sanado pelo @robertorp.

Obrigado novamente.
