### ISSUE TITLE
CT-e

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#123]
Adenilton,

Você tem a intenção de expandir a biblioteca para CT-e? Atualmente sua necessidade e a dos colegas é somente para NF-e/NFC-e?

att,
Samuel Rocha

**Comment by orochasamuel** [comment]
Adenilton,

Qual ferramenta você utilizou para transformar os XSD em CS?

**Comment by adeniltonbs** [comment]
Olá Samuel, fiz as classes na mão, manual de um lado, visual studio de outro. Não gostei do resultado da ferramenta xsd.exe para gerar as classes.

Quanto ao CTe, no momento não tenho demanda por ele, mas seria bom ter na biblioteca essa funcionalidade. Caso deseje iniciar o projeto de CTe e precisar de alguma ajuda, só avisar.

**Comment by orochasamuel** [comment]
Eu também não gostei do resultado usando o xsd.exe. Achei a classe de resultado "suja".

Sobre o CTe, irei me organizar para começar a trabalhar nele já no próximo mês.

**Comment by marcosgerene** [comment]
@samuelroliveira 

Sobre o CTe, você tem alguma novidade?

**Comment by marcosgerene** [comment]
Obrigado @adeniltonbs,

Aguardo anciosamente, abraço
