### ISSUE TITLE
ProdutoEspecifico é lista

### ISSUE THREAD

**Issue by Vinicius-Ferreira-EM** [ZeusAutomacao/DFe.NET#1231]
Os "ProdutoEspecifico" podem conter mais de um item.

![image](https://user-images.githubusercontent.com/74794457/111167870-4b442f80-8580-11eb-9bde-b7eebda1a472.png)

**Comment by marcosgerene** [comment]
@Vinicius-Ferreira-EM 

https://github.com/ZeusAutomacao/DFe.NET/issues/356
https://github.com/ZeusAutomacao/DFe.NET/issues/1106

Isso é uma falha de projeto conhecida que ninguém arrumou por não usar em produção.

O @robertorp  ficou de ver algumas vezes, mas acabou focando em outras coisas, eu sempre falo "ah, tem aquilo" mas como não faz parte do meu dia a dia acabo não vendo.

Vou marcar todos os contribuidores nessa issue (me incluo nessa) e marcar como Bug, alguém vai acabar vendo (pode ser até eu mesmo se sobrar um tempo).

**Comment by Vinicius-Ferreira-EM** [comment]
Caso seja possível eu enviar um Pull request eu o farei.

**Comment by marcosgerene** [comment]
@Vinicius-Ferreira-EM 

Se funcionou bem com a serialização/desserialização não vejo porque não replicar isso. Abra a issue, se possível adicione um XML de teste, farei o possível para validar ainda essa semana.

Obrigado pela contribuição
