### ISSUE TITLE
Não foi possível carregar o tipo NFe.Classes.Informacoes.Identificacao.Tipos.IndicadorIntermediador do assembly NFe.Classes, Version=1.0.0.770, Culture=neutral, PublicKeyToken=null.

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1232]
Olá pessoal eu já atualizei os schemas e as dlls e mesmo assim permanece erro.
Alguma dica?

**Comment by robertorp** [comment]
tudo bom? está usando nuget ou arquivos? se for arquivos confere a versão no AssemblyInfo de todos eles, devem ser iguais para evitar esse erro. 

Agora a alternativa para correção dele também, vai no arquivo do projeto config é deleta a tag runtime (no nosso projeto é deletado mas não por causa do zeus é sim por causa do acbr.net ele tem varias dll que difere verões é pode ocasionar nesse erro aí)

**Comment by robertorp** [comment]
Vou fechar a issue, qualquer coisa basta responder aqui ou abrir uma nova issue.
