### ISSUE TITLE
Tipo 'http://www.portalfiscal.inf.br/nfe:TVerDistDFe' é não declarado ou não é um tipo simples.

### ISSUE THREAD

**Issue by willian-athenassistemas** [ZeusAutomacao/DFe.NET#1233]
Bom dia!

Estou iniciando a implementação do Zeus Automação no meu software, e o meu primeiro teste foi tentar montar a pesquisa de notas emitidas contra o CNPJ da empresa, porém quando executo o método NfeDistDFeInteresse tenho o seguinte retorno:

Tipo 'http://www.portalfiscal.inf.br/nfe:TVerDistDFe' é não declarado ou não é um tipo simples.

Alguém poderia me dar uma ajuda, me informar se falta informar alguma coisa nas configurações ou se falta algum schema?

Desde já agradeço.

**Comment by marcosgerene** [comment]
@WillianAthenas 

O parâmetro TVerDistDFe é definido pela configuração (classe ConfiguracaoServico) que você usa para fazer a solicitação do serviço pelo Zeus (classe ServicoNFe).

Essa configuração é passada no construtor da classe serviço.

![image](https://user-images.githubusercontent.com/15945003/111870430-77d2bf80-8963-11eb-8bce-a322afc00d25.png)

Exemplo de uso:
```
//usings...
using ZeusConfiguracao = NFe.Utils.ConfiguracaoServico;
using ZeusConfigCertificado = DFe.Utils.ConfiguracaoCertificado;
using ZeusCertificado = DFe.Utils.Assinatura.CertificadoDigital;
using ZeusRetornoNfeDistDFeInt = NFe.Servicos.Retorno.RetornoNfeDistDFeInt;
using ZeusServicoNFe = NFe.Servicos.ServicosNFe;

using ZeusTipoCertificado = DFe.Utils.TipoCertificado;
using ZeusAmbiente = DFe.Classes.Flags.TipoAmbiente;
using ZeusTipoEmissao = NFe.Classes.Informacoes.Identificacao.Tipos.TipoEmissao;
using ZeusVersaoServico = DFe.Classes.Flags.VersaoServico;


//atributos...
public ZeusConfiguracao ZeusConfiguracaoServico { get; private set; }

//... construtor
ctor()
{
	//...
	
	ZeusConfiguracaoServico = new ZeusConfiguracao()
	{
		Certificado = new ZeusConfigCertificado()
		{
			TipoCertificado = Emitente.DadosCertificado.Tipo == TipoCertificadoDigital.A1Arquivo ? ZeusTipoCertificado.A1ByteArray :
							  Emitente.DadosCertificado.Tipo == TipoCertificadoDigital.A1Repositorio ? ZeusTipoCertificado.A1Repositorio :
							  Emitente.DadosCertificado.Tipo == TipoCertificadoDigital.A3 ? ZeusTipoCertificado.A3 :
						      throw new NotImplementedException(),
			ManterDadosEmCache = false,
			Serial = Emitente.DadosCertificado.ExigeSerial ? Emitente.DadosCertificado.Serial : null,
			ArrayBytesArquivo = Emitente.DadosCertificado.ExigeArquivo ? Emitente.DadosCertificado.Arquivo : null,
#if NETFRAMEWORK
			Senha = Emitente.DadosCertificado.ExigeSenha ? Emitente.DadosCertificado.Senha : null
#endif
		},
		
		tpAmb = ConfiguracaoLocal.Current.ConfiguracaoDfe.AmbienteProducao ? ZeusAmbiente.Producao : ZeusAmbiente.Homologacao,
		cUF = NfeHelper.ToZeusUf(Emitente.EnderecoCidade.Uf),
		RemoverAcentos = true,
		SalvarXmlServicos = true,
		tpEmis = ZeusTipoEmissao.teNormal,
		ModeloDocumento = (ZeusModeloDocumento)Convert.ToInt32(Modelo),
		ProtocoloDeSeguranca = SecurityProtocolType.Tls12,
		DiretorioSchemas = Path.Combine(ConfiguracaoLocal.Current.ConfiguracaoDfe.PastaSchemas, "NFe"),
		DiretorioSalvarXml = path,
		TimeOut = ConfiguracaoLocal.Current.ConfiguracaoDfe.Timeout,
		ValidarCertificadoDoServidor = false,
		DefineVersaoServicosAutomaticamente = true,
		VersaoLayout = ZeusVersaoServico.Versao400,
	};
	
	//...
}

//consumo
ZeusRetornoNfeDistDFeInt retornoDistribuicao;
using (var _certificado = ZeusCertificado.ObterCertificado(ZeusConfiguracaoServico.Certificado))
using (var _servico = new ZeusServicoNFe(ZeusConfiguracaoServico, _certificado))
	retornoDistribuicao = _servico.NfeDistDFeInteresse(ufAutor: Emitente.EnderecoCidade.Uf.ToString(), documento: Emitente.Cnpj, ultNSU: ultimoNsu.ToString());
```

Foca principalmente nessas configs:
>DefineVersaoServicosAutomaticamente = true,
>VersaoLayout = ZeusVersaoServico.Versao400,


Feito isso, o Zeus internamente vai chamar a função VersaoServicoParaString() dentro de NfeDistDFeInteresse() para definir a versão do envio.
![image](https://user-images.githubusercontent.com/15945003/111870629-98e7e000-8964-11eb-8433-9e8932939147.png)

Repara nesses dois trechos de código:
linha 796: 
```
var versaoServico = ServicoNFe.NFeDistribuicaoDFe.VersaoServicoParaString(_cFgServico.VersaoNFeDistribuicaoDFe);
```

linhas 811 a 816:
```
var pedDistDFeInt = new distDFeInt
{
	versao = versaoServico, //aqui
	tpAmb = _cFgServico.tpAmb,
	cUFAutor = _cFgServico.cUF
};
``` 

Ou seja, com base na suas configurações ele pega a versão do serviço e passa para o objeto que vai ser serializar o xml de consumo ao webservice.

**Comment by willian-athenassistemas** [comment]
Boa tarde @marcosgeren, tudo bem?
Então, eu montei exatamente desta forma que passou e o retorno foi o mesmo.

**Comment by marcosgerene** [comment]
@WillianAthenas 

Acima eu te passei os caminhos que podem resolver o problema, ou seja, aonde atributo é preenchido, como ele é calculado, etc.

É dificil te responder o que está errado no processo, mas algo está. Nesse ponto só debugando.

Eu acredito fortemente não ser o Zeus porque eu e mais uma grande quantidade de pessoas usa em produção esse método, na minha visão é algo ai.

Baixa o fonte do Zeus, compila em DEBUG e faz o debug do método todo, tenta entender o porque está sendo preenchido de forma incorreta. 
Se tiver dificuldade com isso (debug da sua aplicação dentro do Zeus), ai acredito que você vai ter que buscar dentro da comunidade por um suporte pago.

**Comment by willian-athenassistemas** [comment]
Boa tarde @marcosgerene
De inicio pensei que estivesse fazendo algo de muito errado no código, porém utilizei o exemplo e deu o mesmo problema.
Outro detalhe é que em ambos os locais, a consulta de Status funciona perfeitamente.

![1](https://user-images.githubusercontent.com/25254071/112197604-a6aa9900-8be2-11eb-941a-d64f8934da40.PNG)
![2](https://user-images.githubusercontent.com/25254071/112197607-a7432f80-8be2-11eb-94e8-d303acd95bc0.PNG)
![3](https://user-images.githubusercontent.com/25254071/112197609-a7dbc600-8be2-11eb-9056-532649bb2cfd.PNG)
![4](https://user-images.githubusercontent.com/25254071/112197610-a8745c80-8be2-11eb-8952-473cb5f0aa1d.PNG)
![5](https://user-images.githubusercontent.com/25254071/112197612-a8745c80-8be2-11eb-911f-b14faa480994.PNG)

**Comment by marcosgerene** [comment]
@WillianAthenas 
>De inicio pensei que estivesse fazendo algo de muito errado no código, porém utilizei o exemplo e deu o mesmo problema.
Outro detalhe é que em ambos os locais, a consulta de Status funciona perfeitamente.

Na realidade a minha resposta seria uma cópia do que disse anteriormente:

>É dificil te responder o que está errado no processo, mas algo está. Nesse ponto só debugando.

>Baixa o fonte do Zeus, compila em DEBUG e faz o debug do método todo, tenta entender o porque está sendo preenchido de forma incorreta.
Se tiver dificuldade com isso (debug da sua aplicação dentro do Zeus), ai acredito que você vai ter que buscar dentro da comunidade por um suporte pago.

**Comment by willian-athenassistemas** [comment]
@marcosgerene o erro ocorre dentro do método NfeDistDFeInteresse.

var pedDistDFeInt = new distDFeInt
            {
                versao = versaoServico,
                tpAmb = _cFgServico.tpAmb,
                cUFAutor = _cFgServico.cUF
            };

Neste ponto a versão é preenchida corretamente, ou seja, 1.01

var xmlConsulta = pedDistDFeInt.ObterXmlString();
            Validador.Valida(ServicoNFe.NFeDistribuicaoDFe, _cFgServico.VersaoNFeDistribuicaoDFe, xmlConsulta, cfgServico: _cFgServico);
            var dadosConsulta = new XmlDocument();
            dadosConsulta.LoadXml(xmlConsulta);

A exceção ocorre quando ocorre a tentativa de validar a estrutura do xml da consulta utilizando o schema.

Abaixo o XML gerado para consulta:
![6](https://user-images.githubusercontent.com/25254071/112205682-6865a780-8beb-11eb-9aab-c8aac1c75eec.PNG)

**Comment by danilobreda** [comment]
Atualiza seus esquemas na ultima versão desse link: [schemas receita federal](https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=)
Se o problema aconteceu na hora de validar os schemas, e aqui pro pessoal funciona e a gente não disponibiliza os schemas por padrão aqui no Zeus, com certeza esse pode ser o problema... você deve estar utilizando uma versão diferente?

**Comment by marcosgerene** [comment]
@danilobreda 
Verdade!

**Comment by marcosgerene** [comment]
@danilobreda  Verdade! Manter o schemas atualizado é tão trivial que nem me toquei.

Excelente dica!

**Comment by willian-athenassistemas** [comment]
Bom dia @danilobreda tudo bom?
Anteriormente já havia feito a atualização, o meu primeiro palpite eram os Schemas também, más não funcionou da mesma forma.
Uma coisa que notei foi que nas versões anteriores o campo TVerDistDFe não era obrigatório, e na versão nova passou a ser. Outra coisa é que ele esta no corpo do XML e a biblioteca preenche na tag distDFeInt.

**Comment by danilobreda** [comment]
Vários lugares indicam o problema que levantei sobre os schemas, verifica novamente!
[http://www.flexdocs.com.br/suporte/knowledgebase.php?article=169](http://www.flexdocs.com.br/suporte/knowledgebase.php?article=169)

Aqui vai os schemas que utilizo, faz um teste com eles!
[Schemas.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6214064/Schemas.zip)

**Comment by willian-athenassistemas** [comment]
Bom dia @danilobreda
Com seus Schemas deu tudo certo, e olha que baixei tudo do site atualizados.

Más enfim, muito obrigado aos amigos que colaboraram em sanar o problema que tive.
