### ISSUE TITLE
The remote server returned an error: (403) Forbidden. Docker Linux.

### ISSUE THREAD

**Issue by ejafre** [ZeusAutomacao/DFe.NET#1235]
Olá pessoal, boa tarde! Depois de atualizar para a ultima versão comecei a ter um problema ao acessar os serviços da Nfe quando rodo a solução dentro de um container docker com linux: The remote server returned an error: (403) Forbidden.

Esse erro só ocorre com a solução rodando no docker. Fora dele funciona OK. Por acaso algum de vocês já teve esse problema?

Grato.

**Comment by robertorp** [comment]
tudo bom? Verifica o certificado digital seu se está tudo ok com ele

Verifica também a opção ValidarCertificadoDoServidor da configuração está como false, é protocolo de segurança está como tls12

**Comment by ejafre** [comment]
Olá Roberto, boa tarde! Obrigado pelo retorno. Na verdade descobri que o problema estava no certificado. Acabei criando vários containers para testar na AWS e no Azure que acabei esquecendo de atualizar o certificado neles... mas foi muito válida a sua resposta pois fui analisar o codigo e descobri que na nova versão (ou novas, pois fazia tempo que não atualizava) essa nova propriedade (ValidarCertificadoDoServidor) já faz oque eu tinha que fazer por fora para configurar o ServerCertificateValidationCallback.

[]'s
