### ISSUE TITLE
Erro ao ler Certificado Digital em projeto ASP NET CORE 3.1

### ISSUE THREAD

**Issue by dkraide** [ZeusAutomacao/DFe.NET#1237]
Oi pessoal, boa tarde !! Gostaria de uma ajuda de vocês... Desenvolvi um projeto web em asp net core pra emitir nf-e.. Só que to com problema com certificado digital, ele aparece o erro abaixo
![erro](https://user-images.githubusercontent.com/43674712/111823343-9b462d80-88c3-11eb-8b92-8816c4091799.png)

Eu ja tentei usar os dois métodos:
CertificadoDigitaoUtil.ObterDosBytes (salvando o certificado em bytes no bd)
e
CertificadoDigitaoUtil.ObterDoCaminho (salvando o certificado no wwwroot) do projeto

Quando rodo em localhost, ele funciona (pq o certificado ta instalano na minha maquina)... Mas quando dou deploy, ele não vai =(

**Comment by danilobreda** [comment]
Olá @dkraide , para aplicações web, recomendo você utilizar o método ObterDosBytes , e verificar se os bytes realmente estão sendo lidos do seu banco de dados e passados para a configuração. Recomendo vc ver o Lenght do byte se for um Array de bytes e caso for uma stream, ver a posição que essa Stream está, ela pode estar no final, ai é necessário dar um .Seek() nela.
Vou postar meu construtor da configuração +- para você ter uma ideia o que pode estar acontecendo, detalhe na parte do Certificado!
![image](https://user-images.githubusercontent.com/14843499/111858889-18e95800-891b-11eb-8997-ed92403727d4.png)

**Comment by dkraide** [comment]
Cara, muito obrigado !!! eu estava copiando o metodo que uso no windows forms.... por isso tava dando errado !! Agora deu certinho, valeuzao !! de vdd !!
