### ISSUE TITLE
Certificado - Dúvida com TipoCertificado.A1ByteArray

### ISSUE THREAD

**Issue by bilhega** [ZeusAutomacao/DFe.NET#1238]
Pessoal, boa tarde.

Utilizo o certificado via stream, e em computadores em que o usuário não possui certos privilégios, alguns erros são apresentados durante a construção do X509Certificate2, como por exemplo acesso negado.
Pesquisando um pouco, no arquivo [CertificadoDigitaoUtil.cs](https://github.com/ZeusAutomacao/DFe.NET/blob/19874879faffa09bacf2cc0b1a2b36ce3f054c44/DFe.Utils.Standard/CertificadoDigitaoUtil.cs) a construção utiliza o flag `X509KeyStorageFlags.MachineKeySet`, que requer privilégios do usuário durante o build da stream em certificado.
O mesmo ocorrem em ObterDoArrayBytes em [CertificadoDigital.cs](https://github.com/ZeusAutomacao/DFe.NET/blob/19874879faffa09bacf2cc0b1a2b36ce3f054c44/Shared.DFe.Utils/Assinatura/CertificadoDigital.cs), que utiliza apenas o flag `X509KeyStorageFlags.MachineKeySet`

Existe algum motivo para esta este construtor, quando vindo de bytearray, utilizar este flag ? O que, aparentemente, requer um maior nível de privilégios do usuário atual.

Utilizo o construtor do X509Certificate2 somente com as flags `X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable` em meus códigos, e desta maneira funciona sem que os usuários possuam níveis elevados de privilégios.

Obrigado.

**Comment by danilobreda** [comment]
Desculpe a demora na resposta, acredito que essas **flags** foram copiadas do método utilizado para certificado A3 na época de desenvolvimento. 
Não sei se é realmente necessário em algum caso o `509KeyStorageFlags.MachineKeySet` por isso não podemos retirar o mesmo por sistemas que atualmente estão funcionando parar de funcionar do nada. 
Acredito que o melhor caminho para você seja **setar privilégios no .exe ou pasta** do sistema ou mesmo criar um **método próprio** seu que não utilize o flag.

**Comment by bilhega** [comment]
Olá @danilobreda.
  
  Obrigado pelo retorno. Entendo sua preocupação, mas gostaria de alimentar esta conversa com algumas informações :

  -  Na documentação da Microsoft (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509keystorageflags?view=net-5.0) :
_MachineKeySet : Private keys are stored in the local computer store rather than the current user store_.  Pude perceber que esta flag faz com que os certificados sejam armazenados no LocalComputer, neste ponto já exigindo um certo nível de privilégios. ( Ps:  mesmo se utilizando `new X509Certificate2(arrayBytes ...` é gerado um arquivo temporário).
 
  O que gostaria de discutir é este ponto específico, em que como o certificado já esta disponível no array de bytes, seria mesmo necessário o mesmo ser submetido à uma nova validação de privilégios do usuário atual? Diferente da obtenção do certificados de outros locais.

  Atualmente, um workaround para este detalhe, esta sendo executar o aplicativo com direitos de administrador, mas é claro que isto não é uma boa pratica e em algumas circunstâncias não permitido pelos administradores de rede.

 **... ou mesmo criar um método próprio seu que não utilize o flag.**

   Aqui, não consegui visualizar uma forma já que, conheço somente o envio do certificado ao Zeus através do array de bytes.

   Desta maneira, em computadores em que não possuo autoridade para modificar arquivos e/ou privilégios, não consigo utilizar o aplicativo que utiliza o Zeus, devido à este detalhe no "rebuild" interno do certificado.
   Obrigado pela atenção.

**Comment by bilhega** [comment]
Olá @danilobreda.

Obrigado pelo retorno. Entendo sua posição e gostaria de alimentar esta conversa com algumas informações:

Nesta documentação da Microsoft sobre [armazenamento de chaves](https://docs.microsoft.com/en-us/windows/win32/seccng/key-storage-and-retrieval) pode-se identificar os diferentes comportamentos de como o `Microsoft Cryptographic API Cryptographic Service Provider key database`  armazenas as chaves, mesmo durante a criação de um objeto que lida com a mesma, como um `X509Certificate2`

Outra [referência](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509keystorageflags?view=net-5.0) do assunto na MS.

 Pude perceber que esta flag faz com que os certificados sejam armazenados no LocalComputer, neste ponto já exigindo um certo nível de privilégios. ( Ps: mesmo se utilizando `new X509Certificate2(arrayBytes ...` ).
O que gostaria de discutir é este ponto específico, em que como o certificado já esta disponível no array de bytes, seria mesmo necessário o mesmo ser submetido à uma nova validação de privilégios do usuário atual? Diferente da obtenção do certificados de outros locais.

> Acredito que o melhor caminho para você seja setar privilégios no .exe ou pasta do sistema ou mesmo criar um método próprio seu que não utilize o flag.

  Atualmente, um workaround esta sendo executar o aplicativo com direitos de administrador, mas é claro que isto não é uma boa pratica e em algumas circunstâncias não permitido pelos administradores de rede.

Ps: Também tentei com a forma do certificado em arquivo, mas o método também utiliza a flag MachineKeySet para o build em X509Certificate2.

  Desta maneira, em computadores em que não possuo autoridade para modificar arquivos e/ou privilégios, não consigo utilizar o aplicativo que utiliza o Zeus, devido à este detalhe no "rebuild" interno do certificado.
Obrigado pela atenção.

**Comment by danilobreda** [comment]
@bilhega obrigado pelos detalhes e esclarecimentos, vou analisar hoje essa questão e te retorno com novidades

**Comment by danilobreda** [comment]
Faz um tempo já, porem dei uma analisada legal, parece que o 509KeyStorageFlags poderiamos definir como uma configuração, isso resolveria seu problema e de muitos no futuro, sendo que hoje não posso mudar para  a flag MachineKeySet. 
Infelizmente não estou com tempo para a implementação do mesmo, vou deixar aberta a issue para verificar com o @marcosgerene  e o @robertorp  se o processo correto é esse mesmo.
Se você poder colaborar com um pullrequest agradeço.

**Comment by danilobreda** [comment]
Será feito na issue #1306
