### ISSUE TITLE
Receber o XML Mensagem de retorno NFCe Completa

### ISSUE THREAD

**Issue by renatosantoslw** [ZeusAutomacao/DFe.NET#1239]
retornoEnvio = servicoNFe.NFeAutorizacao()
retornoEnvio.RetornoStr

No modelo NFe 55 eu recebo a msg de retorno o XML completo. 
Como eu faço pra receber o retorno XML da NFCe completo tb? só vem uma mensagem de autorização

**Comment by felixsevero** [comment]
O retorno não é a nota completa, a qual você deve armazenar. Sem dúvida, você precisa usar o `nfeProc` para concatenar a `nfe` enviada com a autorização de uso.
Verifique no `AppTeste` a função `nfeProc`.

**Comment by robertorp** [comment]
> retornoEnvio = servicoNFe.NFeAutorizacao()
> retornoEnvio.RetornoStr
> 
> No modelo NFe 55 eu recebo a msg de retorno o XML completo.
> Como eu faço pra receber o retorno XML da NFCe completo tb? só vem uma mensagem de autorização

Exatamente do mesmo jeito da NF-e , é usado os mesmos métodos/retornos

**Comment by renatosantoslw** [comment]
consegui, obrigado.
