### ISSUE TITLE
idLote com 15 caracteres

### ISSUE THREAD

**Issue by vstiebe** [ZeusAutomacao/DFe.NET#1247]
Estou tentando migrar para o DFe.NET, contudo o campo idLote no meu código antigo utilizo os 15 caracteres disponíveis no XSD para este campo.

Nos métodos onde este campo é utilizado os parâmetros utilizam int (int32) ao invés de long (int64). Por exemplo o _RecepcaoEventoCancelamento_.

Existe alguma razão para isso? Ou um pull request com este ajuste seria aceito?

**Comment by adeniltonbs** [comment]
Boa tarde @vstiebe, realmente o campo idLote possui tamanho de quinze números, segundo o MOC 7.0.

Acredito que ninguém usou o tamanho todo desse campo até o momento, por que o MOC diz que esse campo é sequencial e auto incremental. É provável que utilizem como faço por aqui. 1, 2, 3...

Todavia o correto é esse campo estar como long para suportar o tamanho definido no MOC. Pode enviar o PR que será aceito. Note que esse campo se repete em algumas classes no projeto.

![image](https://user-images.githubusercontent.com/6733483/116300702-92bffd00-a775-11eb-9967-7bbf8fa9adc1.png)
