### ISSUE TITLE
Impressão de carta de correção Net Core 3.1

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1248]
Boa tarde, 

Gostaria de saber se é possivel emitir uma carta de correção usando o net core no zeus?
Grato !

**Comment by danilobreda** [comment]
Existe sim, o exemplo encontra-se [nesse link](https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Danfe.AppTeste.NetCore/Program.cs), o método que você irá utilizar é todos que tem o EVENTO, **Tanto carta de correção quanto cancelamento de nota fiscal é considerada um Evento**!
Então para imprimir a carta de correção ou o cancelamento, você precisa do xml original da nota fiscal + o xml do evento... com isso ele imprime o danfe do evento corretamente.

O frx para impressão do Evento se encontra [aqui](https://github.com/ZeusAutomacao/DFe.NET/tree/master/NFe.Danfe.Fast.Standard/NFe) O mesmo **frx** é utilizado tanto para cancelamento quanto para carta de correção.

**Comment by danilobreda** [comment]
Opa falei apenas da impressao... acredito que você tambem estava querendo sobre como emitir no SEFAZ! 
[Aqui está o link de um exemplo para .net Framework](https://github.com/ZeusAutomacao/DFe.NET/blob/de112f3ef17d5fd1d0f4f6b85978971ec23fd2fd/NFe.AppTeste/MainWindow.xaml.cs#L482), mas o mesmo processo é parecido para o .net core!
Infelizmente não temos um exemplo de cancelamento e carta de correção [no projeto exemplo do .net core](https://github.com/ZeusAutomacao/DFe.NET/tree/master/NFe.AppTeste.NetCore)

**Comment by khaddmussistemas** [comment]
Eu consegui imprimir a carta de correção e tbm o cancelamento pelo net
core.  Agora seria muito interessante se vcs mudasse essa descrição de
carta de correção para alguma outra coisa generica.Observer a imagem 01 e a
imagem 02 , ambos são eventos diferentes.
01 .
[image: image.png]
02 .
[image: image.png]
Grato!

Em qui., 29 de abr. de 2021 às 17:30, Danilo Breda ***@***.***>
escreveu:

**Comment by danilobreda** [comment]
@khaddmussistemas não consegui ver as imagens... acredito que por conta de vc ter enviado por email...
