### ISSUE TITLE
DANFE - Considerar tpImp = tiSimplificado

### ISSUE THREAD

**Issue by felipemarchi** [ZeusAutomacao/DFe.NET#1249]
Olá, alguém conhece algum arquivo de layout de DANFE como o [NFeRetrato.frx](https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Danfe.Fast/NFe/NFeRetrato.frx) que possibilite a impressão do modelo DANFE Simplificado?

**Comment by danilobreda** [comment]
Infelizmente não temos um modelo no Zeus para o DANFE simplificado...  O modelo é de design aberto pelo que entendi, no SEFAZ encontra-se a [Nota Técnica 2020.004 - v.1.00 - Publicada em 28/08/2020 - Divulga o formato da impressão do DANFE Simplificado](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=mMs1SVX51wc=)
Se poder contribuir com a gente elaborando esse DANFE simplificado agradecemos!, só mandar um pullrequest!

Ontem mesmo recebi uma encomenda do mercadolivre com um DANFE simplificado, e achei bem legal...
![image](https://user-images.githubusercontent.com/14843499/116611091-5c68b600-a90c-11eb-8d7d-a9121f10142a.png)

**Comment by marcosgerene** [comment]
@felipemarchi @danilobreda 
Estou completamente sem tempo, mas isso é interessante para um cliente novo (e-commerce), então provavalmente dentro uns 2 meses eu desenvolva algo nesse sentido.

A ideia no meu caso é fazer algo no padrão de tamanho das etiquetas do Sigep para não precisar ficar fazendo a troca de rolo de etiquetas.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/commit/79f600ac88c059255953b9eb7cb1a6846833307f

![image](https://user-images.githubusercontent.com/15945003/119839258-6a453300-beda-11eb-80d0-d0da087f0151.png)

**Comment by danilobreda** [comment]
Foi implementado DANFE simplificado tanto para .NET Framework quanto para .NET 5/core/standard.

**Comment by dnicolinisilva** [comment]
Olá, existe o NFePaisagem.frx ? se sim, onde posso fazer o download? Grato

**Comment by marcosgerene** [comment]
@dnicolinisilva 

Ainda não existe, mas em poucas horas é possível editar o Retrato do FastReports e criar o paisagem.

As outras opções (Fast open e HTML) me parecem um pouco mais trabalhoso.

**Comment by dnicolinisilva** [comment]
@marcosgerene 
OK, qual IDE posso usar pra editar o Retrato, se tiver o link do download me passa também, grato.

**Comment by dnicolinisilva** [comment]
@marcosgerene 
já pesquisei aqui e descobri que é o FastReports como voce mostrou no seu comentário, grato.
