### ISSUE TITLE
Erro Danfe NFC-e informando cnpj sem endereço

### ISSUE THREAD

**Issue by rodrigomartins50** [ZeusAutomacao/DFe.NET#125]
Bom dia galera, alguém já pasou por isso?

Estou  emitindo nfc-e em homologação, só que ao emitir uma nfc-e para um cnpj (99.999.999/0001-91) sem informar endereço, ele é validado pela sefaz, só que ao mandar visualizar o danfe aparece a seguinte msg de erro :

> txtDestEndereco: Error in expression: Format("{0:00000-000}", ToInt32([NFCe.NFe.infNFe.dest.enderDest.CEP] ) )

Para emitir uma nfc-e informando o endereço do destinatário só é permitido se a Indicação de Presença do mesmo for 4 (NFC-e em operação com entrega em domicílio).

**Comment by adeniltonbs** [comment]
Vou verificar e corrigir, assim que o fizer, posto aqui.

**Comment by adeniltonbs** [comment]
Erro corrigido no commit 14a7c587b6e54d39d9eff0956d3f39e0a76bf645
