### ISSUE TITLE
Erro ao dê serializar XML do  CarregarDeXmlString()

### ISSUE THREAD

**Issue by julioblanconeto** [ZeusAutomacao/DFe.NET#1252]
Ola, venho utilizando o Zeus a um tempo, porem me deparei com um erro, um tanto estranho.

Me utilizando da CarregarDeXmlString(xml) para dê serializar o XML 
>
>            try
>            {
>                _nfe = new NFe.Classes.nfeProc().CarregarDeXmlString(XmlNfe);
>            }
>            catch (Exception ex)
>            {
>                var ErrMessage = "Erro ao Deserializar XML da Nota Fiscal Eletrônica para Normalização.";               
>                await UpdateNfePendenteAsync(linha, true, $"{ErrMessage}({ex.Message})");
>                return;
>            }        
**_nfe = new NFe.Classes.nfeProc().CarregarDeXmlString(XmlNfe);**
porem no esta retornando erro, 
no **StackTrace**

>
>           at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
>           at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
>           at DFe.Utils.FuncoesXml.XmlStringParaClasse[T](String input)
>           at ExtNfeProc.CarregarDeXmlString(nfeProc nfeProc, String xmlString)
>           at XRP.EdocFacil.BusinessLogic.Services.NFeAsyncNormalizeXmlService.<NormalizeOneNfeXmlAsync>d__3.MoveNext() in C:\Users\Julio\Desktop\procfit\XRP\XRP.EdocFacil.BusinessLogic\Services\NFeAsyncNormalizeXmlService.cs:line 47

**Comment by robertorp** [comment]
teria como compartilhar o código ? o xml que esta dando erro tb

**Comment by robertorp** [comment]
somente o trecho de código , não é todo hehehe , somente o trecho do código onde vc seta o arquivo xml ou string xml , 
robertoalvespereira18@gmail.com

**Comment by robertorp** [comment]
certo, é o xml ? pega ele da string XmlNfe debugando

**Comment by julioblanconeto** [comment]
> certo, é o xml ? pega ele da string XmlNfe debugando

            public async Task NormalizeOneNfeXmlAsync(long RegistroNfe)
            {
            Nfe linha;
            try
            {
                linha = await _nfesService.GetNfeByRegistroAsync(_tenantDbContext, RegistroNfe);
            }
            catch (Exception ex)
            {
                throw;
            }
            string XmlNfe = linha.Xml;
            NFe.Classes.nfeProc _nfe;
            try
            {
                _nfe = new NFe.Classes.nfeProc().CarregarDeXmlString(XmlNfe);
            }
            catch (Exception ex)
            {
                var ErrMessage = "Erro ao Deserializar XML da Nota Fiscal Eletrônica para Normalização.";
                await UpdateNfePendenteAsync(linha, true, $"{ErrMessage}({ex.Message})");
                return;
            }

**Comment by robertorp** [comment]
quero o que tem dentro da variável o conteudo da XmlNfe depois de setado o valor da linha.Xml

**Comment by julioblanconeto** [comment]
enviei o conteúdo do xml por e-mail para você

**Comment by robertorp** [comment]
Não chegou, chegou algo diferente , acho que mandou errado

**Comment by julioblanconeto** [comment]
re enviei o email

**Comment by robertorp** [comment]
o xml está faltando partes deles, veja o final , se estiver enviando assim para o método ele realmente vai lançar exception

**Comment by julioblanconeto** [comment]
consegue me indicar exatamente onde se encontra o erro no xml pois não estou encontrando inclusive joguei https://codebeautify.org/xmlviewer ele ajusta direitinho tanto na parte de tree quanto no beautify

**Comment by SuportecTL** [comment]
Valida no https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx
