### ISSUE TITLE
Sigla da UF da consulta difere da UF do Web Service

### ISSUE THREAD

**Issue by marcelokrol** [ZeusAutomacao/DFe.NET#1253]
Sou do PR e ao tentar consultar um CNPJ de MG por exemplo obtenho cStat=265. Segue xml de retorno:
`<retConsCad versao="2.00" xmlns="http://www.portalfiscal.inf.br/nfe">
<infCons>
  <verAplic>PR-v4_7_26</verAplic> 
  <cStat>265</cStat> 
  <xMotivo>Sigla da UF da consulta difere da UF do Web Service. UF Sistema: 41, UF Recebida: MG</xMotivo> 
  <UF>MG</UF> 
  <CNPJ>08238299000390</CNPJ> 
  <dhCons>2021-05-19T21:02:03-03:00</dhCons> 
  <cUF>41</cUF> 
</infCons>
</retConsCad>`

As consultas com CNPJs do PR são efetuadas com sucesso.

**Comment by rpotalara** [comment]
Conforme testes, o problema ocorre no método:
```
        public static string ObterUrlServico(ServicoNFe servico, VersaoServico versaoServico, Estado estado, TipoAmbiente tipoAmbiente, ModeloDocumento modeloDocumento, TipoEmissao tipoEmissao)
        {
            var urls = ObterEnderecoServicosMaisRecentes(versaoServico, estado, tipoAmbiente, modeloDocumento, tipoEmissao).Where(n => n.ServicoNFe == servico)
                .Select(n => n.Url).ToList();

            if (!urls.Any())
                throw new Exception(Erro(servico, versaoServico, estado, tipoAmbiente, tipoEmissao, modeloDocumento));
            if (urls.Count > 1)
                throw new Exception("A função ObterUrlServico obteve mais de um resultado!");
            return urls.FirstOrDefault();
        }
```

Quando é configurado o serviço no parâmetros iniciais é informado o Estado ao qual se refere o contribuinte configurado e quando essa informação é passada para o método acima e o Estado de origem da consulta é diferente do Estado do IE, CNPJ consultado o problema ocorre. 
Exemplo, Contribuinte do Estado de **SP** consultando um CNPJ do Estado de **SP**, OK!
Exemplo, Contribuinte do Estado de **SP** consultando um CNPJ do Estado de**MG**, Erro 265 causado pelo retorno incorreto das url´s.

Nesse caso no parâmetro **estado** deveria ser o mesmo do Estado a quem pertence o IE, CNPJ que se deseja consultar.

**Comment by marcelokrol** [comment]
Previsão para correção?

**Comment by marcelokrol** [comment]
Nenhuma previsão para correção do problema?

**Comment by danilobreda** [comment]
@marcelokrol Estamos abertos para aceitar um pullrequest com a correção, infelizmente esse tipo de problema é muito complicado de esperar que alguém arrume por ser algo muito especifico para testar. Acredito que você seja a melhor pessoa para isso.

**Comment by danilobreda** [comment]
Foram feitos algumas melhorias nessa questão, por ser uma issue antiga vou fechar ela...  caso o problema persista estamos aqui :)
