### ISSUE TITLE
Rejeicao 464: Codigo de Hash no QR-Code difere do calculado

### ISSUE THREAD

**Issue by PetrarcaSoftware** [ZeusAutomacao/DFe.NET#1255]
Na SEFAZ-MG o NFCe autoriza normalmente, mas quando foi realizado testes com um certificado do Rio Grande do Sul a SEFAZ-RS critica:

Rejeicao 464: Codigo de Hash no QR-Code difere do calculado

**Comment by robertorp** [comment]
Você obteve o id é CSC da sefaz, talvez usou os de homologação em produção ou talvez ficou algum caractere faltando ou inválido
