### ISSUE TITLE
Rejeição 878: Endereço do site da UF da Consulta por chave de acesso diverge do previsto

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1258]
estou tentando fazer uma homologação em pernambuco mas esta me retornando esse erro. segue o xml gerado.
[NFe26210641730262000199650010000000011417302620.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6584639/NFe26210641730262000199650010000000011417302620.zip)

**Comment by ThalisonSantos** [comment]
Alguem?

**Comment by robertorp** [comment]
Boa tarde @ThalisonSantos , 
Me manda a parte do código onde você seta a tag `<infNFeSupl>`

**Comment by ThalisonSantos** [comment]
@robertorp bom dia.

`  infNFeSupl infNFeSupl = new infNFeSupl();

                infNFeSupl.qrCode = infNFeSupl.ObterUrlQrCode(_nfe, VersaoQrCode.QrCodeVersao2, oEmpresa.IDTOKEN, oEmpresa.CSC);
                infNFeSupl.urlChave = infNFeSupl.ObterUrl(CFGServico.tpAmb, CFGServico.cUF, TipoUrlConsultaPublica.UrlQrCode, CFGServico.VersaoNFeAutorizacao, VersaoQrCode.QrCodeVersao2);
`

**Comment by robertorp** [comment]
Bom dia 

```
var urlQrCode = nfezeus.infNFeSupl.ObterUrlQrCode(
                nfezeus,
                VersaoQrCode.QrCodeVersao2,
                emissorNfce.IdToken.ToString("D6"),
                emissorNfce.Csc);

            var urChave = nfezeus.infNFeSupl.ObterUrl(
                nfezeus.infNFe.ide.tpAmb,
                nfezeus.infNFe.ide.cUF,
                TipoUrlConsultaPublica.UrlConsulta,
                VersaoServico.Versao400,
                VersaoQrCode.QrCodeVersao2);
```

no `TipoUrlConsultaPublica.UrlConsulta` Obterurl você usou qrCode para urlChave , usa o tipo UrlConsulta é teste para nós vermos

**Comment by ThalisonSantos** [comment]
@robertorp blz vou testar e depois retorno aqui

**Comment by ThalisonSantos** [comment]
@robertorp Funcionou!! só não entendi pq em outros estados funcionava , mas de qualquer forma valeu pela ajuda

**Comment by robertorp** [comment]
> @robertorp Funcionou!! só não entendi pq em outros estados funcionava , mas de qualquer forma valeu pela ajuda

Apenas sorte de ser a mesma URL tanto pra qrcode quanto para consulta , mas que bom que funcionou , isso seria algo a ser melhorado no Zeus de alguma maneira , para não ter mais pessoas dando esse erro hehe
Eu que agradeço pela confiança !
