### ISSUE TITLE
Impressão do NFCE NET Core.

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1259]
Ao tentar imprimir a nfce no net core eu recebo essa mensagem

"NFCE ainda não implementado para .netstandard ou .netcore, apenas disponivel em .net framwork. Crie uma issue no nosso github para mais informações: https://github.com/ZeusAutomacao/DFe.NET"}

Existe alguma previssão de imprimir?

**Comment by marcosgerene** [comment]
No read-me do projeto existe um aviso desta impossibilidade

https://github.com/ZeusAutomacao/DFe.NET#impress%C3%A3o-netcorenetstandard

Lá também existe uma possibilidade de impressão de NFCe em .Net Core

https://github.com/marcosgerene/Gerene.DFe.EscPos

Quanto a previsão (da impressão em Fast Reports como em .Net Framework), antigamente eu praticamente mexia sozinho nas impressões, hoje tem mais gente mexendo, então não posso te informar se está no radar de algum dos outros colaboradores. Eu não tenho essa necessidade, então na meu radar não está.

Lembrando sempre que toda contribuição é bem vinda, se você puder ajudar com código ou patrocinar um dos devs para implementar, essa impressão será muito bem vinda. =)

**Comment by khaddmussistemas** [comment]
Como faço para contribuir? e se eu contribior vcs fazem essa implementação?
ou vc mesmo? cobraria quanto?

Em qui., 3 de jun. de 2021 às 18:22, Marcos Gerene F. Spirito <
***@***.***> escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 
Quando falei sobre contribuir era com código... se tem interesse nessa implementação e está disposto a patrocinar alguém, vou referenciar alguns devs que podem te ajudar. Eu, infelizmente (ou felizmente), estou sem tempo até para projetos pagos.

@danilobreda @robertorp @adrbarros

**Comment by khaddmussistemas** [comment]
NET core 3.1 não?

Em seg., 7 de jun. de 2021 às 14:02, Danilo Breda ***@***.***>
escreveu:

**Comment by marcosgerene** [comment]
@khaddmussistemas 

.Net Core subentende-se .Net Core 3.1

**Comment by khaddmussistemas** [comment]
o MEU projeto é net core 3.1 tomara que de certo, no aguardo


Em sex., 11 de jun. de 2021 às 20:53, Marcos Gerene F. Spirito <
***@***.***> escreveu:

**Comment by marcosgerene** [comment]
![image](https://user-images.githubusercontent.com/15945003/121791105-9e983f00-cbbc-11eb-85c4-27e410447927.png)

@khaddmussistemas sempre que falarem .Net Core para algo que vai/está sendo desenvolvido aqui entenda .Net 3.1, o 2.1 está "na porta" de ser descontinuado, os devs não fazem nada pensando nele aqui.

Isso se aplica para mim, @danilobreda ou @robertorp =)

**Comment by robertorp** [comment]
Vale ressaltar somente que as partes do .Net Standard estão em 2.0 ou seja é compatível com .net 3.1 , agora impressões não sei, ainda hoje não tenho aplicações em .Net Core , estou iniciando a transição para Web do meu sistema.

**Comment by arsantosdev** [comment]
Alguma novidade sobre o DANFE da NFCe em .Net Core?

@danilobreda

**Comment by junior176** [comment]
> Alguma novidade sobre o DANFE da NFCe em .Net Core?
> 
> @danilobreda

Anderson, eu implementei a impressão da NFCe em .Net Core no meu sistema, eu comentei no zeus a parte de imprimir 2 vias pois como vai gerar pdf, na hora de imprimir o usuario aqui já imprime direto duas vezes, e fiz umas alterações no .frx. Segue o arquivo. Não sei se tem algum lugar mais correto de propor essa mudança.

[NFCe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6984666/NFCe.zip)

**Comment by arsantosdev** [comment]
@junior176 

Você poderia submeter um PR com a sua implementação da impressão?

**Comment by figloalds** [comment]
> > Alguma novidade sobre o DANFE da NFCe em .Net Core?
> > @danilobreda
> 
> Anderson, eu implementei a impressão da NFCe em .Net Core no meu sistema, eu comentei no zeus a parte de imprimir 2 vias pois como vai gerar pdf, na hora de imprimir o usuario aqui já imprime direto duas vezes, e fiz umas alterações no .frx. Segue o arquivo. Não sei se tem algum lugar mais correto de propor essa mudança.
> 
> [NFCe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6984666/NFCe.zip)

Eu fiz a mesma coisa no meu sistema, mas gerando o PDF no Linux não sai os textos da DANFE (só as linhas), também mexi no FRX, corrigi erros de compilação que tava dando e mudei as fontes pra Open Sans, instalei as fontes OK no Linux e nada; No Windows funciona tranquilo, mesma base de código, ambos usando o Zeus.Standard

**Comment by danilobreda** [comment]
Infelizmente pessoal ainda não tive tempo de implementar essa questão... 
Estamos aceitando pullrequest para nos ajudar, todos podem contribuir 👍

**Comment by junior176** [comment]
Vou fazer um PR com a implementação da impressão.

**Comment by junior176** [comment]
Subi um PR como sugestão. Testei aqui na minha impressora térmica da Epson TM-T20X e imprimiu tudo corretamente o PDF gerado

**Comment by khaddmussistemas** [comment]
Assim que alguem atualizar no projeto atual , favor me informar . Grato.

Em seg., 16 de ago. de 2021 às 14:34, Juvenal Viana <
***@***.***> escreveu:

**Comment by danilobreda** [comment]
NFCE implementado para .NET Core & 5+ em #1280
