### ISSUE TITLE
VS2013

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#126]
Ola, bom dia
Consigo compilar o projeto utilizando o VS2013?

grd abs

**Comment by adeniltonbs** [comment]
Bom dia. Consegue sim.
Dê uma lida em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe e
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114
