### ISSUE TITLE
Ciência da Operação ou Confirmação da Operação

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [ZeusAutomacao/DFe.NET#1260]
Boa tarde, tudo bem ?
Me pediram para implantação de Ciências da operação e confirmação da operação para o destinatário, como eu posso implementar isso com o Zeus ?
Quais os métodos e informações que preciso para que o meu destinatário faça esse procedimento.
Agradeço a compreensão não sei se expliquei corretamente.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636

Postei praticamente todo o código necessário para fazer isso no comentário acima.

Lendo o tópico com atenção tem dicas bem interessantes minhas e de outros devs, acredito que vai sanar, se não todas, grande parte das suas dúvidas

**Comment by robertorp** [comment]
@EdsonRodrigoBA  conseguiu ?

**Comment by danilobreda** [comment]
Fechando issue por falta de retorno.
