### ISSUE TITLE
[Noticia] MDF-e Agora é Compatível com .Net Core !!! Todos modulos do Zeus são .NET Full Framework é .NetCore!!

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#1262]
MDF-e Agora é compatível com .net core !

NFC-e/NF-e é CT-e já estavam compativeis com .net core, 

Agora transformamos o MDF-e em .Net Core também!!! 

é sabe o que muda ? nada. Da mesma forma que programava no .net full framework vc desenvolve no .net core os mesmos métodos. Bastando apenas referenciar os projetos .net standard ! 

Para quem usa nuget isso é automático.  

aproveito para dizer que estou prestes a lançar um curso sobre implementação DFe.Net nf-e / nfc-e 
se tiver interesse https://docs.google.com/forms/d/15GsG4PpfSSsi2D6zVlH4eDwrUmIzEyXROQhLjim637k
ideal para quem não conhece nada do DFe.NET , bom para quem não conhece NF-e.NFC-e vai ajudar um pouco também, mas o foco do curso é DFe.NET NFe/NFC-e . Registre seu interesse, a primeira turma vai ser limitada!

**Comment by danilobreda** [comment]
vou fazer um novo após a #1341
