### ISSUE TITLE
Não consigo comunicar com o web services do AM (Amazonas)

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1264]
Ola boa noite a todos, essa semana me deparei com um novo cliente e primeiro no estado do Amazonas, porem sem sucesso na comunicação do web services, ate conseguir uma única vez depois sem sucesso, sempre retorna o erro: Solicitação anulada: Não foi possível criar um canal seguro para SSL/TLS.
Ja verifiquei os endereços e versoes dos servicos e estao todos corretos. Aguardo a ajuda dos amigos. Obrigado

**Comment by danilobreda** [comment]
@sigridslima pode nos informar o ambiente que está esse servidor? Linux, windows, qual versão etc? Também qual versão do Zeus você está utilizado, de qual data. 
Esse tipo de erro está ligado diretamente ao certificado, pode ser causado por certificado vencido ou mesmo problema no ambiente no qual o servidor que está tentando conectar não entende os pacotes de retorno ou de inicio de conexão segura.

Também pode ser causado por divergências entre o certificado e o cnpj da empresa.

**Comment by robertorp** [comment]
1- Também se possível verifique a validade do certificado digital usado 
2- Qual windows é? se For o 7 , amanhã posto uma possível solução aqui
3- Se for certificado A3 desinstale é instale o mesmo , verifica a configuração no Zeus se está setando como A3 é se possível coloque a senha no Zeus 
4- nas configurações do Zeus tem um atributo ValidarInformacoesCertificado (algo assim não lembro de cabeça) veja se ele está como false , se ele estiver como True ai vc vai ter que verificar as cadeias de certificado digital do computador do cliente 
5- Verifique se o protocolo de comunicação nas configuraçoes do Zeus está Tls 1.2 

Este erro infelizmente é o mais generico de todos , não tem como apontar X coisa somente com ele , devemos ir verificando todas possibilidades 
Então vamos passo a passo para chegar na solução

**Comment by sigridslima** [comment]
Ola amigos, obrigado pela atenção conseguir resolver o problema por parte, percebi que quando deixo a senha  salva do certificado, apresenta isso, então fiz o teste de sempre pedir a senha pelo software do certificado no caso meu token, isso so ocorreu nesse modelo de token especifico, ja no a1 e outros tipos de a3 pela leitora de cartão funciona normal com senha salva. Mas por enquanto foi sanado o problema por parte, mas desde de ja obrigado, abraços.

**Comment by robertorp** [comment]
Adiciona o Recurso no certificado digital "manteremchache" = true é testa novamente @sigridslima  
no meu caso foi isso que solucionou esse problema seu ai
