### ISSUE TITLE
Responsável técnico (infRespTec) (alguns estados)

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1265]
Ola amigos volto aqui ainda sem solução para meu problema, ja tinha aberto um outra discursão porem sem sucesso.
Me deparei com um cliente do AMAZONAS e é obrigatório informar o responsável técnico.
Tenho esse codigo, porem quando tento gerar o xml apresenta o erro.

![error](https://user-images.githubusercontent.com/21263061/122139703-f1bdfc00-ce1f-11eb-8c63-3141ccc1b4ca.png)

Meu codigo:

 protected virtual infRespTec InformacoesTecnico()
        {
            var t = new infRespTec
            {
                CNPJ = "00000000000",
                xContato = "nome",
                email = "emailResposavel@hotmail.com",
                fone = "000000000"
            };

            return t;
        }

//
infRespTec = InformacoesTecnico(),

Aguardo uma colaboração, obrigado

**Comment by robertorp** [comment]
Pode compartilhar o código onde converte seus objetos para Zeus? Pelo que vejo no erro, o responsavel tecnico eu acho que vc esta informando seus dados corretamente , cnpj , contato , email, fone mas... o erro diz que falta algo no produto 
tipo combustivel ou cana, ou exportação enfim ele ta dizendo que é um produto especifico tipo gás essas coisas

**Comment by adrbarros** [comment]
Uso esse código para o estado do PE

                        mNfe.infNFe.infRespTec = new Shared.NFe.Classes.Informacoes.InfRespTec.infRespTec
                        {
                            CNPJ = "11111111111111",
                            xContato = "RESPONSABEL TECNICO",
                            email = "email@email.com.br",
                            fone = "1636621234"
                        };

no Estado do PE, sem falhas

Conferir os Schemas, pra ver se estão atualizados

**Comment by sigridslima** [comment]
Ola, obrigado pela atenção, tive que baixar o pacote do zeus atualizado, o meu código alguns trechos estavam devassados. Obrigado
