### ISSUE TITLE
Erro ao Manifestação de Ciência - cStat 657 - Rejeicao: Código do Orgao diverge do orgao autorizador

### ISSUE THREAD

**Issue by victorperez2911** [ZeusAutomacao/DFe.NET#1268]
Boa Tarde Pessoal

Primeiramente, parabéns pelo projeto, ótima iniciativa para o Plataforma .NET.

Estou usando a biblioteca a um tempo para importar notas destinadas aos CNPJ's que usam o meu sistema, e tudo vinha funcionando como o esperado até então.

Porem, a pouco tempo incluímos um cliente do Estado do RS ao processo, e ao tentar manifestar ciência dos documentos destinados a esse CNPJ recebo a seguinte Rejeição.

cStatt 657 - Rejeicao: Código do Orgao diverge do orgao autorizador

Ao instanciar a classe que configura o "ServiceNFe" , uso como cUF o estado do CNPJ do Destinatário (ou seja, o CNPJ do cliente que usa o meu Sistema), e isso funcionou corretamente ate o momento, tendo problema somente nesse novo cliente do RS.

Após algumas leituras, não muito conclusivas, utilizei como teste a cUF 91 (Ambiente Nacional), e essa nota foi devidamente Manifestada.

Minha Duvida é.

Que valor devo passar no parâmetro cUF da classe 'ConfiguracaoServico' para construir uma instancia do 'ServicosNFe' antes de chamar o método 'RecepcaoEventoManifestacaoDestinatario()'  ?

Lógico, mantendo o processo de manifestação de ciência funcionando para os demais UF's (diferentes de RS).

Desde ja agradeço.

Victor Perez

**Comment by danilobreda** [comment]
A classe que pode estar dando problema é [essa aqui 'Shared.NFe.Utils/Enderecos/Enderecador.cs'](https://github.com/ZeusAutomacao/DFe.NET/blob/1977fa7c7099fd6656ca74fd1cc604ea13a4c1a7/Shared.NFe.Utils/Enderecos/Enderecador.cs). Acredito que o retorno dela está sendo incorreto na hora de pegar a URL do serviço... O que você conseguir ver ai sobre, ou usar essa classe com seus parâmetros para ver o retorno se está sendo a URL correta, me ajudaria. Não tenho muito conhecimento nessa área..

**Comment by victorperez2911** [comment]
Ola @danilobreda 

Analisando o código , a partir da dica que voce passou , encontrei dois pontos que preciso de ajuda para entender melhor.


Arquivo ServicosNFe.cs

![image](https://user-images.githubusercontent.com/11770654/123868322-e8e02680-d905-11eb-937c-673410baaa67.png)

note que, para a formação do PayLoad da requisição SOAP , para preencher a tag cOrgao, o código tem uma tratativa para que, quando o estado enviado pelo utilizador do biblioteca for RS, usar o proprio RS como cOrgao, porem, qualquer outro Estado, utilizar o código do ambiente nacional.

Porem, no processo de definição do endereço (Url) a ser enviado esse Payload, a biblioteca envia qualquer uma das requisições para o mesmo endereço (imagem abaixo).


Arquivo Enderecador.cs
![image](https://user-images.githubusercontent.com/11770654/123868733-791e6b80-d906-11eb-9878-3003c41dfea8.png)

Duvida.

O Comentário colocado pelo desenvolvedor foi
**//RS possui endereço próprio para manifestação do destinatário. Demais UFs usam o ambiente nacional**

Isso se mantem ? Ou seja, RS ainda conta com um endereço próprio para os eventos de Manifestação do Destinatário ?

Como posso confirmar essa informação ?


Victor Perez

**Comment by victorperez2911** [comment]
@danilobreda 

O que acha disso ?

Informação de 2013

![image](https://user-images.githubusercontent.com/11770654/123870594-e6330080-d908-11eb-824f-060698c6ebcc.png)

**Comment by victorperez2911** [comment]
Alterei meu código para que , liste as novas notas usando o config com cUF do destinatário da nota, porem, sempre manifestar usando o cUF 91 (Ambiente Nacional) inclusive para RS, e aparentemente esta funcionando.

**Comment by danilobreda** [comment]
> Isso se mantem ? Ou seja, RS ainda conta com um endereço próprio para os eventos de Manifestação do Destinatário ?

Seguindo [esse link](https://www.nfe.fazenda.gov.br/portal/webServices.aspx) o serviço NFeDistribuicaoDFe é apenas em AN (ambiente nacional)

**Comment by victorperez2911** [comment]
> > Isso se mantem ? Ou seja, RS ainda conta com um endereço próprio para os eventos de Manifestação do Destinatário ?
> 
> Seguindo [esse link](https://www.nfe.fazenda.gov.br/portal/webServices.aspx) o serviço NFeDistribuicaoDFe é apenas em AN (ambiente nacional)

Então podemos entender que a biblioteca precisa ser atualizada  ? 

Digo isso para o fato de que existe uma regra no arquivo ServicosNFe.cs (conforme mostrei acima) que ainda leva em consideração que o RS possui uma especificidade de cOrgao, o que você afirma que não existe mais.

E caso a resposta seja afirmativa, apenas alterar a linha 630 do arquivo citado de:

```cs
cOrgao = _cFgServico.cUF == Estado.RS ? _cFgServico.cUF : Estado.AN,
```
Para:

```cs
cOrgao =  Estado.AN,
```

Resolve o problema para os novos utilizadores da biblioteca  ?

Victor Perez

**Comment by danilobreda** [comment]
@victorperez2911 obrigado pela ajuda por identificar o problema, pode deixar que vamos resolver para futuros utilizadores não ter a mesma dor. Qualquer coisa estamos aqui 👍
