### ISSUE TITLE
erro 204

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#127]
Causa

Quando for emitida uma NF-e (modelo 55) ou NFC-e (modelo 65), com a mesma Chave de Acesso de uma NF-e já autorizada pela Sefaz, será retornado a rejeição "204 - Duplicidade de NF-e".

certo a causa está ai, ai queria saber se existe alguma maneira de baixar o xml? um unico xml especifico , através de consulta ou algo do tipo.

exemplo de problema.. o sistema fez um request para a sefaz e esta aguardando a resposta mas a internet caiu

a request foi feita so não tivemos resposta e a nota foi autorizada bom

como no meu sistema ela não foi atualizada.. mas na sefaz ja foi autorizada ele pega o mesmo número e quando envio para a sefaz ele me retorna que a mesma ja foi autorizada.. (sim ela realmente já foi autorizada..)

oque vocês fazem nessa situação?

**Comment by adeniltonbs** [comment]
O ideal é você armazenar o xml assinado antes de enviar este a SEFAZ.
É possível obter o xml da NFe através da chave, veja o consumo do serviço NfeDownloadNF implementando na biblioteca e demonstrado na aplicação de demonstração de uso.

**Comment by robertorp** [comment]
no meu caso o consumo do serviço de nfedownloadnf com uma nfc-e so que a nfce não tem destinatário , tem como?

pesquisando aqui pensei em fazer o seguinte, quando der o código 204 vou fazer uma consulta automaticamente da nfc-e (duro e que meu estado não tem consulta ainda tem o link somente) e retornar o protocolo para meu sistema

editado: erro meu a mesma consulta serve. hehe
