### ISSUE TITLE
Sem comunicação com o serviço NFeDistribuicaoDFe:\nAn error occurred while sending the request."

### ISSUE THREAD

**Issue by lucasnc** [ZeusAutomacao/DFe.NET#1270]
erro só acontece no servidor, em desenvolvimento funciona normalmente
TimeOut está como 60000
Protocolo de Segurança Tls1.2
Servidor é Windows Server 2019
Aplicação está no IIS
Certificado não está expirado

Alguem sabe o que pode ser?

**Comment by marcosgerene** [comment]
@lucasnc está faltando algumas informções no processo, então vou fazer algumas suposições:

- Se é um windows server vou supor que seu certificado é A1 (se não for, ai o problema é mais em baixo).
- Vou também supor que você via terminal service e que  o certificado está instalado no usuário do TS.

Partindo disso, faça um teste no internet explorer (não pode ser outro navegador) tentando acessar esta página: https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

Vai solicitar seu certificado e o resultado deve ser esse:

![image](https://user-images.githubusercontent.com/15945003/125660706-182e24ca-1d6e-473f-87f2-c9cf317cdb1e.png)

![image](https://user-images.githubusercontent.com/15945003/125660755-4746773a-a458-4334-bc33-9fb5c4a2b78f.png)

Se o resultado for igual acima, ótimo, temos que partir para seu código (difícil se funciona no ambiente de desenvolvimento) ou até mesmo algo no ambiente de produção bloqueando sua aplicação. Se o resultado não for esse, então estamos falando somente de ambiente de certificado, KB, firewall etc.

**Comment by lucasnc** [comment]
Acessei o link e o resultado foi exatamente o mesmo

Em desenvolvimento, usando o mesmo certificado não apresenta nenhum erro, os documentos são localizados.
Provavelmente é algo do servidor

**Comment by lucasnc** [comment]
> @lucasnc está faltando algumas informções no processo, então vou fazer algumas suposições:
> 
> * Se é um windows server vou supor que seu certificado é A1 (se não for, ai o problema é mais em baixo).
> * Vou também supor que você via terminal service e que  o certificado está instalado no usuário do TS.
> 
> Partindo disso, faça um teste no internet explorer (não pode ser outro navegador) tentando acessar esta página: https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx
> 
> Vai solicitar seu certificado e o resultado deve ser esse:
> 
> ![image](https://user-images.githubusercontent.com/15945003/125660706-182e24ca-1d6e-473f-87f2-c9cf317cdb1e.png)
> 
> ![image](https://user-images.githubusercontent.com/15945003/125660755-4746773a-a458-4334-bc33-9fb5c4a2b78f.png)
> 
> Se o resultado for igual acima, ótimo, temos que partir para seu código (difícil se funciona no ambiente de desenvolvimento) ou até mesmo algo no ambiente de produção bloqueando sua aplicação. Se o resultado não for esse, então estamos falando somente de ambiente de certificado, KB, firewall etc.

Acessei o link e o resultado foi exatamente o mesmo

Em desenvolvimento, usando o mesmo certificado não apresenta nenhum erro, os documentos são localizados.
Provavelmente é algo do servidor

**Comment by marcosgerene** [comment]
@lucasnc então pode ter algo no ambiente de produção bloqueando a aplicação, se o resultado do site acima (extritamente no Internet Explorer) foi de sucesso, na minha visão, o certificado está ok.

**Comment by lucasnc** [comment]
@marcosgerene a aplicação está em .net 5 poderia ser a causa do erro no servidor?

**Comment by danilobreda** [comment]
@lucasnc o erro específico está no InnerException  da exceção. Posta pra gente ai.
Também uso .net 5 e funciona 100%

**Comment by lucasnc** [comment]
@danilobreda aparentemente o InnerException ta null e o StackTrace é esse: 
NFe.Utils.Excecoes.ComunicacaoException: Sem comunicaÃƒÂ§ÃƒÂ£o com o serviÃƒÂ§o NFeDistribuicaoDFe:
An error occurred while sending the request.
   at NFe.Servicos.ServicosNFe.NfeDistDFeInteresse(String ufAutor, String documento, String ultNSU, String nSU, String chNFE)

A aplicação está rodando no IIS em uma VM na Azure
Como exatamente vc fez o deploy da sua aplicação? fez alguma configuração a mais?

**Comment by danilobreda** [comment]
@lucasnc Deveria ter InnerException...exemplo:

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a 
> receive. ---> System.IO.IOException: Unable to read data from the transport connection: An     
> established connection was aborted by the software in your host machine. ---> 
> System.Net.Sockets.SocketException: An established connection was aborted by the software in your 
> host machine
> at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags 
> socketFlags, AsyncCallback callback, Object state)
> at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback 
> callback, Object state)
>  --- End of inner exception stack trace ---
> at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
> at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
> at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
> --- End of inner exception stack trace ---
> at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
> at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
> --- End of inner exception stack trace --

Agora.. se local na sua maquina funciona, e no IIS não, então problema é no IIS mesmo! Sem detalhes a mais não vamos conseguir resolver.

**Comment by danilobreda** [comment]
Pode ser parecido com #1076

**Comment by lucasnc** [comment]
@danilobreda obrigado, dei uma olhada nas issues com problema parecido e pesquisando pelo problema achei uma resposta que funcionou e agora ta ok! 

fiz esse procedimento
https://pt.stackoverflow.com/a/406646
