### ISSUE TITLE
erro Danfe NFCe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1274]
[NFe27210804133549000105650010000335181041335490.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6934001/NFe27210804133549000105650010000335181041335490.zip)
precisei atualizar a vesrão do fast report e comecei a receber esse erro no danfe

txtProdutoDuasLinhasValorUnit: Error in expression: ([NFCe.NFe.infNFe.det.prod.vProd] - [NFCe.NFe.infNFe.det.prod.vDesc]) / [NFCe.NFe.infNFe.det.prod.qCom]

**Comment by danilobreda** [comment]
Não recomendo a mudança da versão do FastReport que o projeto Zeus Utiliza. Qual o motivo dessa mudança?

**Comment by ThalisonSantos** [comment]
@danilobreda eu atualizei pq estava implementando a impressão do Acbr Nfse e tinhas umas opções no report que só tinha na versão 2020/2021

**Comment by danilobreda** [comment]
@marcosgerene  @robertorp tem alguma ideia do fastreport?

**Comment by marcosgerene** [comment]
@danilobreda 

Não uso o Danfe NFCe em fast faz um tempo já. Essa expressão não deveria estar dentro de chaves?

Tipo:  [([NFCe.NFe.infNFe.det.prod.vProd] - [NFCe.NFe.infNFe.det.prod.vDesc]) / [NFCe.NFe.infNFe.det.prod.qCom]]

Estou dando um chute sem sequer ver o código, fast em impressora termica não deu certo pra mim quando o volume é muito grande

**Comment by danilobreda** [comment]
@ThalisonSantos não sabemos como resolver na versão sugerida, depois nos indique se ainda está com problemas **e como resolveu**, como o relatório funciona 100% na versão proposta vou fechar a issue.

**Comment by ThalisonSantos** [comment]
@danilobreda  eu cheguei a mexer no report pesquisei mas não descobri o que tem de errado, o problema só ocorre se as opções duas linhas estiver ativada e mostrar desconto no produto desativada, então eu ativei mostrar desconto no produto dessa forma ele não passa na linha que gera o erro

**Comment by danilobreda** [comment]
@ThalisonSantos blza vou verificar aqui com essas opções
