### ISSUE TITLE
Impressão MDFe

### ISSUE THREAD

**Issue by junior176** [ZeusAutomacao/DFe.NET#1277]
_De antemão, desculpe se estiver colocando no local errado, ainda estou aprendendo como funciona aqui._

Estou implementando o MDFe no meu sistema, utilizando o .Net Core, no meu caso, e estava testando a impressão e vi que o DAMDFe aparentemente não está no Layout proposto pelo manual.

Fiz algumas alterações no .frx utilizado para gerar para se adequar ao layout.
No caso, to referenciando nesse .frx as dll ".Standard", mas acredito que funcione normalmente pra quem não está utilizando, basta referenciar as dll sem o ".Standard"

Segue o arquivo .frx e um PDF que gerei de exemplo.

Obrigado.
[MDFe Exemplo.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/6984580/MDFe.Exemplo.pdf)
[MDFeRetrato.zip](https://github.com/ZeusAutomacao/DFe.NET/files/6984583/MDFeRetrato.zip)

**Comment by marcosgerene** [comment]
Achei bonita a sua impressão, a ponto de considerar usar ela na minha aplicação(uso uma versão que modifiquei do Zeus), mas não entendi o porque do layout atual não estar no padrão do manual.

Sobre sua mudança, abra um PR, não vou abrir para não "roubar" seu trabalho. No PR podemos debater melhor a mudança.

Obrigado pela contribuição

**Comment by junior176** [comment]
Que bom que gostou Marcos,
Ainda estou aprendendo como fazer um PR, mas vou tentar fazer isso durante o dia de hoje. Obrigado pelo feedback.

**Comment by junior176** [comment]
> Que bom que gostou Marcos,
> Ainda estou aprendendo como fazer um PR, mas vou tentar fazer isso durante o dia de hoje. Obrigado pelo feedback.

Fiz o Pull Request. Não sei se fiz da forma correta. Se puder conferir por favor, fico agradecido.

**Comment by danilobreda** [comment]
Estamos verificando internamente e vamos aprovar em breve.

**Comment by danilobreda** [comment]
Merged
