### ISSUE TITLE
Dúvida sobre o envio síncrono de NFC-e

### ISSUE THREAD

**Issue by caviunabruno** [ZeusAutomacao/DFe.NET#1278]
Bom dia pessoal, assumi recentemente o projeto de NFC-e aqui da empresa e me deparei com o CStat 452 recentemente pois estávamos enviando o lote com uma NFC-e somente em modo assíncrono.

A dúvida que me surgiu foi a seguinte: 
Na implementação que temos aqui do envio assíncrono, tratamos primeiro se o lote foi recebido ou está em processamento pra depois ver se foi aprovado ou não, devo fazer isso também para o envio síncrono? Minha dúvida maior é com relação ao CStat 105, isso ocorre com o envio síncrono?

**Comment by felixsevero** [comment]
Bom dia, até onde sei, cada UF tem autonomia para permitir ou não o envio síncrono, mas todas permitem o assíncrono. Eu utilizo o envio síncrono para o RS.
O CStat "105 - Lote em processamento" não ocorre para o envio síncrono. Você faz o envio do lote, que pode conter apenas um documento fiscal, e já recebe o retorno. Não há recibo, como ocorre com o envio síncrono.

**Comment by caviunabruno** [comment]
Obrigado pelos esclarecimentos!

**Comment by denernun** [comment]
@caviunabruno veja o link abaixo: 

Parece que na NT 2020.005 versão 1.10, o modo assíncrono será permitido apenas para lotes, se for apenas um documento, deverá enviar no modo "síncrono".

[https://www.projetoacbr.com.br/forum/topic/63432-modo-de-emiss%C3%A3o-ass%C3%ADncrono-n%C3%A3o-ser%C3%A1-mais-permitido-para-lotes-contendo-uma-%C3%BAnica-nfce/](https://www.projetoacbr.com.br/forum/topic/63432-modo-de-emiss%C3%A3o-ass%C3%ADncrono-n%C3%A3o-ser%C3%A1-mais-permitido-para-lotes-contendo-uma-%C3%BAnica-nfce/)
