### ISSUE TITLE
Visual 

### ISSUE THREAD

**Issue by acfarias** [ZeusAutomacao/DFe.NET#128]
Boa tarde Adenilton, primeiramente eu quero te parabenizar pelo excelente projeto! Porém tenho uma dificuldade com as telas do visual, baixei o projeto, compilei mais não existe um arquivo .exe. Estou fazendo algo errado?

**Comment by adeniltonbs** [comment]
Farias, para ter uma visão geral de como funciona o compilador do visual studio para c#, dê uma olhada em https://msdn.microsoft.com/en-us/library/cyz1h6zd.aspx.

Quanto à biblioteca, após compilar, dê uma olhada em \NFe.AppTeste\bin\Debug

**Comment by acfarias** [comment]
Amigo me desculpe, me expressei mal. No projeto que eu baixei não encontrei as telas como você colocou os prints, me desculpe, mais acho que estou fazendo algo errado...

**Comment by adeniltonbs** [comment]
Blz, 
As telas são da aplicação NFe.AppTeste que acompanha o projeto.
Veja os fontes dela em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste.
A tela principal que aparece nos prints em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe é exatamente https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.AppTeste/MainWindow.xaml
