### ISSUE TITLE
Campo nDraw

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#1282]
Olá!
O campo nDraw não é obrigatório, nem todas as importações trabalham com Drawback.

No arquivo NFe.Classes.Informacoes.Detalhe.DeclaracaoImportacao.adi.cs adicionar o seguinte código ao final do arquivo

        public bool ShouldSerializenDraw()
        {
            if (string.IsNullOrEmpty(nDraw))
            {
                return false;
            }
            else
            {
                return true;
            }
        }

Tentei fazer um pull request, mas não consegui, só deu acesso negado.

**Comment by danilobreda** [comment]
@marciojmuller estamos aceitando pullrequest se você conseguir nos ajudar te agradeço!

**Comment by marcosgerene** [comment]
Eu abro o PR.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/1293
