### ISSUE TITLE
Baixar todos os Eventos de uma NF-e

### ISSUE THREAD

**Issue by victorperez2911** [ZeusAutomacao/DFe.NET#1283]
Boa Tarde Galera.

Pessoal, dei uma olhada no aplicativo de exemplo e não consegui achar.

Tem como baixar todos os eventos de uma NF-e a partir da Chave ? (utilizando o certificado, é claro).

No método "NfeDistDFeInteresse", quando passo a chave como parâmetro, somente o NSU da nota em si é retornado pelo Componente.

Porem, preciso de todos os eventos da nota.

Isso é possível  com o DFe.NET ?

Victor Perez

**Comment by danilobreda** [comment]
@victorperez2911  conseguiu descobrir algo? É algo que é possivel mas o Zeus não implementa?

**Comment by marcosgerene** [comment]
@victorperez2911 @danilobreda 

Eu faço esse processo no meu sistema. Mas não tem como faze-lo pela nota, você deve baixar todos os NSUs, neles estarão as notas E eventos, ai internamente você faz suas ligações... eu devo ter compartilhado meu código de consumo do NfeDistDFeInteresse nas issues, é só dar uma procurada.

**Comment by denernun** [comment]
lembrando que a nota deve estar manifestada para ter o XML completo, e
nesse XML tem todos os eventos.

**Comment by victorperez2911** [comment]
> @victorperez2911 @danilobreda 
> 
> Eu faço esse processo no meu sistema. Mas não tem como faze-lo pela nota, você deve baixar todos os NSUs, neles estarão as notas E eventos, ai internamente você faz suas ligações... eu devo ter compartilhado meu código de consumo do NfeDistDFeInteresse nas issues, é só dar uma procurada.

Você está dizendo chamar o método NfeDistDFeInteresse com apenas o parâmetro de CNPJ? Isso faria com que todos os nsus dos últimos 3 meses fossem retornados, eh isso?

**Comment by marcosgerene** [comment]
@victorperez2911 sim e não.

Ele vai retornar um numero de NSUs, ai você passa novamente o ultimo que você tem e  assim vai... você vai ter que fazer várias requisições até chegar no mais atual e sempre vai ter que requisitar isso quando quiser informação.


https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636

Olhe o trecho "CarregarNSU".

**Comment by victorperez2911** [comment]
> @victorperez2911 sim e não.
> 
> Ele vai retornar um numero de NSUs, ai você passa novamente o ultimo que você tem e  assim vai... você vai ter que fazer várias requisições até chegar no mais atual e sempre vai ter que requisitar isso quando quiser informação.
> 
> 
> https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636
> 
> Olhe o trecho "CarregarNSU".
> 

Eu entendi,  e dessa maneira, dependendo do número de documentos que esse CNPJ for destinatário, o volume de dados que devem ser consumidos desnecessariamente torna a solução inviável.

Em resumo, a resposta é que não é possível.

Obrigado.

**Comment by marcosgerene** [comment]
@victorperez2911 

Entendo sua questão, mas essa issue vai ser usada posteriormente para sanar algumas dúvidas, então permita-me discrodar.

Em resumo sim, é possível, eu faço isso na minha aplicação com um marketplace de porte médio.  
Sim, o volume é grande, mas eu já uso o NSU para facilitar a entrada de nota fiscal eletrônica emitida por fornecedores, o que me "força" a fazer essas requisições. Sendo assim, torno essa opção que você está procurando totalmente viável já que tenho todos esses NSUs em mãos.

O problema que você está levantando é "eu quero fazer somente isso", o que até onde eu entendi, parace possível mas não viável. Num ambiente maior, onde você usa o NSU para mais finalidades (o que acredito ser um cenário plausível quando se trata de um ERP) a viabilidade é clara.

Bem, é isso, vou fechar a issue por entender que você atingiu a resposta procurada.

[]'s
