### ISSUE TITLE
Correção de rejeição 441

### ISSUE THREAD

**Issue by duduccosta** [ZeusAutomacao/DFe.NET#1285]
Boa tarde.

Estou tendo o erro 441de descrição no pagamento.
Atualizei meu repositório e teoricamente a classe detPag veio com o campo xPag.
Porém o xsd não está com ele, dando erro de validação.

Alguém tem o xsd da NFCe atualizado?

**Comment by Yamcol** [comment]
Os arquivos Schemas estão na solução. Estava ocorrendo o mesmo erro, então baixei a solução e substitui os arquivos e funcionou.

**Comment by danilobreda** [comment]
> 
> 
> Os arquivos Schemas estão na solução. Estava ocorrendo o mesmo erro, então baixei a solução e substitui os arquivos e funcionou.

os do zeus estavam dando erro ou o que voce baixou novo?
