### ISSUE TITLE
Gerar DANFE a partir de RDLC

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1286]
Ola tudo bem?

Gostaria de saber se posso usar a DLL para gerar o XML, armazenar os dados no banco de dados e gerar a DANFE a partir de um rdlc conectado ao banco de dados, ao invés de usar o FastReport.

Teria algum problema ou colocando o código de barras funciona normal?

Seria o mesmo caso pra NFe e NFCe, com o cupom..

Obrigado

**Comment by danilobreda** [comment]
> **Gostaria de saber se posso usar a DLL para gerar o XML, armazenar os dados no banco de dados**
Sim

> **e gerar a DANFE a partir de um rdlc conectado ao banco de dados, ao invés de usar o FastReport.**
Você é livre para implementar o que quiser, hoje disponibilizamos o DANFE apenas no FastReport.

> **Teria algum problema ou colocando o código de barras funciona normal?**
Não entendi essa pergunta... 

O Zeus é uma biblioteca [para ajudar na implementação de documentos fiscais](https://github.com/ZeusAutomacao/DFe.NET#o-que-a-biblioteca-faz) (emissão e impressão utilizando o FastReport). Ele não tem nenhuma recomendação ou exemplo de como salvar em um banco de dados por exemplo.
Você pode usar ele totalmente ou parcialmente.

**Comment by PedroCanizela** [comment]
> > **Gostaria de saber se posso usar a DLL para gerar o XML, armazenar os dados no banco de dados**
> 
> Sim
> 
> 
> 
> > **e gerar a DANFE a partir de um rdlc conectado ao banco de dados, ao invés de usar o FastReport.**
> 
> Você é livre para implementar o que quiser, hoje disponibilizamos o DANFE apenas no FastReport.
> 
> 
> 
> > **Teria algum problema ou colocando o código de barras funciona normal?**
> 
> Não entendi essa pergunta... 
> 
> 
> 
> O Zeus é uma biblioteca [para ajudar na implementação de documentos fiscais](https://github.com/ZeusAutomacao/DFe.NET#o-que-a-biblioteca-faz) (emissão e impressão utilizando o FastReport). Ele não tem nenhuma recomendação ou exemplo de como salvar em um banco de dados por exemplo.
> 
> Você pode usar ele totalmente ou parcialmente.
> 
> 
> 
> 

Ah tá joia, obrigado.
