### ISSUE TITLE
Validação para Schemas do MDFe

### ISSUE THREAD

**Issue by john182** [ZeusAutomacao/DFe.NET#1287]
![image](https://user-images.githubusercontent.com/10438644/134165629-97bd5707-ac1b-44b9-9147-298c727e161e.png)

Essa implementação ira gera um path invalido quando o mesmo não for executado em maquinas com o SO windows, sugiro usar o Path.DirectorySeparatorChar para ele pega o separado do sistema operacional

**Comment by john182** [comment]
Outro local tb que tem problema é esse trecho de código:

![image](https://user-images.githubusercontent.com/10438644/134210819-147cd30d-98ca-43f9-bf50-2a46650abc93.png)

**Comment by john182** [comment]
Dando uma pequisada
![image](https://user-images.githubusercontent.com/10438644/134226552-e4299db4-77a0-4197-b554-f4e6979eb7f1.png)

ou add cfg.Schemas.XmlResolver = new XmlUrlResolver(); como foi feito na NFe

https://github.com/dotnet/runtime/issues/42748

**Comment by danilobreda** [comment]
@john182 estamos aceitando **pullrequest**, se você poder fazer a modificação agradeço! Caso não consiga, vamos deixar aberto a issue até alguém conseguir implementar.

**Comment by williamoura** [comment]
Se puderem aprovar...Resolvido no PR
#1304

**Comment by danilobreda** [comment]
Acredito que tenha sido resolvido no PR, vou fechar a issue. Qualquer coisa só abrir outra issue.
