### ISSUE TITLE
Emissão NFA-e

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#1288]
Ola, boa tarde

Já uso a biblioteca para emissão de NFe e NFCe, surgiu uma duvida, consigo emitir NFA-e com ela?

grd abs

**Comment by danilobreda** [comment]
Até aonde eu sei, o Zeus não está preparados para emitir e não conheço nenhum caso. Principal diferença pelo que sei é a emissão através de CPF e não CNPJ.

**Comment by danilobreda** [comment]
Caso mais alguém tenha necessidade ou saiba implementar, não deixe de nos ajudar quanto a issue :)
