### ISSUE TITLE
quando emitir uma nfc-e offline

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#129]
O ideal e trocar a serie? ou não?

**Comment by adeniltonbs** [comment]
Bom dia roberto, dê uma olhada no manual "Manual de Especificações da Contingência Offline para NFC-e - versão 1.2", disponível em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=.

**Comment by robertorp** [comment]
Opá, vlw ajudo muito mais do que eu precisava.
