### ISSUE TITLE
Falha ao Utilizar o Servico NFE após o uso em Produção

### ISSUE THREAD

**Issue by Osnircamposbrusque** [ZeusAutomacao/DFe.NET#1290]
Bom dia, 

Estou tendo problemas com a conexão DFe ao utilizar o Serviço após já ter utilizado a NFe em produção.
"Erro Inesperado : Conexão Subjacente estava fechada."

a ) Tipo Ambiente = Homologação e não havia sido emitido nenhuma nota no cliente:
 Todas as funcionalidades estavam funcionando corretamente.
 
b ) Tipo Ambiente = Produção após já ter emitido uma nota no cliente..
Todas as funcionalidades também funcionam.

O problema ocorre quando tendo utilizar o Ambiente em Homologação porém após o Cliente já ter emitido notas, ou seja já ter utilizado ambiente em produção.

Como faço para utilizar o ambiente de Homologação mesmo que já tenha sido usado o ambiente de produção do cliente.

Att

Osnir

**Comment by danilobreda** [comment]
Acredito que seja um problema de implementação, pois não é comum esse tipo de problema. Quanto a definição de ambiente é setado na hora de configurar o Zeus.

**Comment by danilobreda** [comment]
Na maioria das vezes o certificado do cliente está vencido... esse tipo de erro é maioria isso...

**Comment by danilobreda** [comment]
Vou fechar a issue por falta de retorno.
