### ISSUE TITLE
Impressão de Danfe NFCe .Net Core

### ISSUE THREAD

**Issue by evertonbatini** [ZeusAutomacao/DFe.NET#1292]
A impressão de Danfe da NFCe .Net Core não está implementada correto?

Alguém está trabalhando nisso?

Não seria possível usar o Danfe do .Net mesmo, e implementar para exportar para pdf ?

**Comment by danilobreda** [comment]
Está sim, foi feito no #1280

**Comment by evertonbatini** [comment]
Obrigado!
