### ISSUE TITLE
Impressão Danfe NFCe com Marca D’água

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1295]
Ola tudo bem?

Alguém sabe se tem algum problema (Questão de alterar o layout exigido da Danfe) a Danfe da NFCe sair com a marca d'água demo version do Fast reports no cabeçalho?

Estou usando a versão demo, no momento não queria adquirir o fast report.

**Comment by marcosgerene** [comment]
@PedroCanizela 

Cara, sinceramente não gosto da ideia. Isso poderia ser interpretado de uma forma ruim pelo fiscal/cliente/etc... usa o Fast Reports OpenSource, tenho qse ctza que o @danilobreda implementou a impressão com o OpenSource, o que resolveria totalmente seu problema.

**Comment by PedroCanizela** [comment]
> @PedroCanizela 
> 
> 
> 
> Cara, sinceramente não gosto da ideia. Isso poderia ser interpretado de uma forma ruim pelo fiscal/cliente/etc... usa o Fast Reports OpenSource, tenho qse ctza que o @danilobreda implementou a impressão com o OpenSource, o que resolveria totalmente seu problema.
> 
> 
> 
> 

Ah entendi, eu dei uma olhada nos testes de impressão e Consegui alterar para o Open-source, deu certo, saiu a marca de impressão.

Muito obrigado
