### ISSUE TITLE
Sem comunicação com o serviço NfeStatusServico:\nThe SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by hdamasceno** [ZeusAutomacao/DFe.NET#1297]
Boa tarde,

Estou tentando colocar a emissão de NFCe em um servidor no Azure Functions e não consigo emitir NFCe e nem dar status de serviço quando o fonte da publicado no azure.

Localmente no meu pc está tudo OK, mas rodando na nuvem da azuer nao funciona.

Sempre tenho esse retorno de erro...

{
        "source": "NFe.Servicos.Standard",
        "targetSite": "",
        "message": "Sem comunicação com o serviço NfeStatusServico:\nThe SSL connection could not be established, see inner exception.",
        "stackTrace": "   at NFe.Servicos.ServicosNFe.NfeStatusServico()\r\n   at ZeusNFCe.ZeusNFCeController.StatusServico() in C:\\GIT\\....:line 142"
    }

Já instalei diversas cadeias de certificados no azure e mesmo assim não funciona....
Alguém já passou por isso para fazer uma api para emitir a NFCe ao invés do fonte estar no pc do cliente emissor?

**Comment by hdamasceno** [comment]
Testei com um máquina windows e teste com uma máquina linux e nada.
testei com SP, AM, RJ e MG e nada...

alguém já testou utilizando o componente em um serviço Azure Functions ?
Estou precisando mesmo resolver isso o quanto antes, para melhorar a performance de um app fiscal de mta intensidade de emissão simultânea...

**Comment by leandrovip** [comment]
Fala @hdamasceno, boa noite!

Rapaz, salvo engano já trocamos alguns emails há uns 10 anos sobre a homologação da buxa PAF-ECF rs! Bom saber que está na ativa!

Sobre seu problema, o certificado está instalado no servidor? A1? Quais cadeias tem instalado? .net 5?

[]´s

**Comment by hdamasceno** [comment]
fala, to lembrado!
Trocamos e-mail mesmo.

To na luta ainda meu amigo só que agora com NFCe, cara instalei todas as cadeias que encontrei na internet de MG e da Receita e etc.
Mas nada por decreto faz funcionar quando rodo a aplicação lá no Azure.
Esse erro é o mesmo tanto para o ZeusNFCe quanto para o que eu havia feito aqui na mão.

Os dois somente funcionam na minha máquina local, no Azure tá osso...

Certificados instalados:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/4733294/137514330-c25e2f03-1dfa-425a-9d8a-aebd6fe8b26e.png">

**Comment by leandrovip** [comment]
O certificado do cliente, propriamente dito, está consumindo como?

**Comment by hdamasceno** [comment]
Consegui fazer funcionar contratei o suporte do azure. Daí o rapaz lá da micro$oft configurou intermaente a aplicação para não validar o certificado da NFCe de MG...

daí funcionou perfeito

**Comment by JERIONINTELLIWAN** [comment]
@hdamasceno Tudo bem?  como resolveu estou tendo o mesmo problema em minha aplicação .net 9
