### ISSUE TITLE
Danfe no pacote do nuget

### ISSUE THREAD

**Issue by SuportecTL** [ZeusAutomacao/DFe.NET#1299]
Boa tarde, não estou encontrando as classes de impressão de DANFC-e no pacote do nuget, eles foram removidos mesmo? Tem alguma altenativa de se utilizar eles?

**Comment by marcosgerene** [comment]
As impressões em Fast Reports usam um componente externo (o Fast Reports rs) então não estão no nuget, somente baixando o fonte.

Especificamente para NFCe existe uma implementação minha para Esc-POS, funciona em .Net, .Net Standard e .Net Framework, mas é limitado a comunicação direta com a balança, ou seja, não gera PDFs.

**Comment by SuportecTL** [comment]
Entendi, obrigado pelo retorno. A impressão em si eu fiz uma implementação imprimindo via lib da elgin. O pdf eu estou gerando via API mesmo. No meu cenário não vou utilizar pdf sem ter conexão com a internet, então está resolvido.
