### ISSUE TITLE
Nome dos xmls salvos

### ISSUE THREAD

**Issue by weslley39** [ZeusAutomacao/DFe.NET#13]
Gostaria de saber se o nome dos xml's salvos, necessariamente necessitam estar com o numero do lote, pois eu modifiquei para usar o numero da nota fiscal, pode ocorrer algum problema com essa modificação ??

**Comment by adeniltonbs** [comment]
Nenhum, fica a seu critério. No aplicativo de exemplo o arquivo xml é salvo com a chave da Nfe, mas fique a vontade para usar como você achar que for melhor para seu caso.
Não há regras nos manuais que definam com que nome o xml deva ser armazenado/distribuído.
