### ISSUE TITLE
duvida sobre nf-e e status de funcionamento

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#130]
Quando temos algo errado com a sefaz, por exemplo o "status do serviço" esteja offline 
isso me impede de autorizar nf-e?

Pois temos vários status, "autorização" , "status do serviço" entre outros.

Bom no caso eu imaginei que seria assim se o "status do serviço" estiver offline ele não me impede de autorizar nf-e né?

Ou estou errado?

**Comment by adeniltonbs** [comment]
Está certo.
