### ISSUE TITLE
XML do retorno de cancelamento

### ISSUE THREAD

**Issue by rafatozzi** [ZeusAutomacao/DFe.NET#1300]
Bom dia.

Não estou conseguindo o xml do cancelamento, o método abaixo não funciona.

Obrigado

`````` cs
var retornoCancelamento = servicoNFe.RecepcaoEventoCancelamento(1 /*Id do Lote*/, sequenciaEvento, protocolo, chave, justificativa, cpfcnpj);

var retEventoRetorno = retornoCancelamento.Retorno.retEvento.FirstOrDefault();
if (retEventoRetorno == null)
    throw new Exception("Não foi possível obter o retorno do serviço de Cancelamento!");

if (retEventoRetorno.infEvento.cStat != 135) //Evento vinculado à nfe
    throw new Exception(retEventoRetorno.infEvento.xMotivo);

var xml = retornoCancelamento.ProcEventosNFe.FirstOrDefault().ObterXmlString();
```cs
``````

_Originally posted by @adeniltonbs in https://github.com/ZeusAutomacao/DFe.NET/issues/56#issuecomment-149201687_

**Comment by hdamasceno** [comment]
Boa tarde,

Estou tendo erro no cancelamento também.
Tanto em homologação quanto em produção, e testei nos estados de MG e SP nos dois deu o mesmo erro abaixo:

"source": "System.Security.Cryptography.Xml",
      "targetSite": "",
      "message": "Signing key is not loaded.",
      "stackTrace": "   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()\r\n   at NFe.Utils.Assinatura.Assinador.ObterAssinatura[T](T objeto, String id, X509Certificate2 certificadoDigital, Boolean manterDadosEmCache, String signatureMethod, String digestMethod, Boolean cfgServicoRemoverAcentos)\r\n   at NFe.Utils.Evento.Extevento.Assina(evento evento, X509Certificate2 certificadoDigital, String signatureMethodSignedXml, String digestMethodReference, Boolean removerAcentos)\r\n   at NFe.Servicos.ServicosNFe.RecepcaoEvento(Int32 idlote, List`1 eventos, ServicoNFe servicoEvento, VersaoServico versaoEvento)\r\n   at 

Status
Autorizacao
ConsultaPorChave
ConsultaPorRecibo
Inutilizacao

Estão funcionando normal sem o erro de certificado...

**Comment by rafatozzi** [comment]
> Boa tarde,
> 
> Estou tendo erro no cancelamento também. Tanto em homologação quanto em produção, e testei nos estados de MG e SP nos dois deu o mesmo erro abaixo:
> 
> "source": "System.Security.Cryptography.Xml", "targetSite": "", "message": "Signing key is not loaded.", "stackTrace": " at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()\r\n at NFe.Utils.Assinatura.Assinador.ObterAssinatura[T](T objeto, String id, X509Certificate2 certificadoDigital, Boolean manterDadosEmCache, String signatureMethod, String digestMethod, Boolean cfgServicoRemoverAcentos)\r\n at NFe.Utils.Evento.Extevento.Assina(evento evento, X509Certificate2 certificadoDigital, String signatureMethodSignedXml, String digestMethodReference, Boolean removerAcentos)\r\n at NFe.Servicos.ServicosNFe.RecepcaoEvento(Int32 idlote, List`1 eventos, ServicoNFe servicoEvento, VersaoServico versaoEvento)\r\n at
> 
> Status Autorizacao ConsultaPorChave ConsultaPorRecibo Inutilizacao
> 
> Estão funcionando normal sem o erro de certificado...

o código que postei funciona certinho o cancelamento com a acessão da parte: "var xml = retornoCancelamento.ProcEventosNFe.FirstOrDefault().ObterXmlString();"

do resto está rodando... Ambiente de Homologação em SP

**Comment by hdamasceno** [comment]
Comigo com o cancelamento tem dado esse erro ai..
Daí para não abrir outra issue sobre cancelamento aproveitei aqui a sua...

**Comment by hdamasceno** [comment]
> > Boa tarde,
> > Estou tendo erro no cancelamento também. Tanto em homologação quanto em produção, e testei nos estados de MG e SP nos dois deu o mesmo erro abaixo:
> > "source": "System.Security.Cryptography.Xml", "targetSite": "", "message": "Signing key is not loaded.", "stackTrace": " at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()\r\n at NFe.Utils.Assinatura.Assinador.ObterAssinatura[T](T objeto, String id, X509Certificate2 certificadoDigital, Boolean manterDadosEmCache, String signatureMethod, String digestMethod, Boolean cfgServicoRemoverAcentos)\r\n at NFe.Utils.Evento.Extevento.Assina(evento evento, X509Certificate2 certificadoDigital, String signatureMethodSignedXml, String digestMethodReference, Boolean removerAcentos)\r\n at NFe.Servicos.ServicosNFe.RecepcaoEvento(Int32 idlote, List`1 eventos, ServicoNFe servicoEvento, VersaoServico versaoEvento)\r\n at
> > Status Autorizacao ConsultaPorChave ConsultaPorRecibo Inutilizacao
> > Estão funcionando normal sem o erro de certificado...
> 
> o código que postei funciona certinho o cancelamento com a acessão da parte: "var xml = retornoCancelamento.ProcEventosNFe.FirstOrDefault().ObterXmlString();"
> 
> do resto está rodando... Ambiente de Homologação em SP

Meu código está exatamente igual ao seu...

**Comment by rafatozzi** [comment]
> > > Boa tarde,
> > > Estou tendo erro no cancelamento também. Tanto em homologação quanto em produção, e testei nos estados de MG e SP nos dois deu o mesmo erro abaixo:
> > > "source": "System.Security.Cryptography.Xml", "targetSite": "", "message": "Signing key is not loaded.", "stackTrace": " at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()\r\n at NFe.Utils.Assinatura.Assinador.ObterAssinatura[T](T objeto, String id, X509Certificate2 certificadoDigital, Boolean manterDadosEmCache, String signatureMethod, String digestMethod, Boolean cfgServicoRemoverAcentos)\r\n at NFe.Utils.Evento.Extevento.Assina(evento evento, X509Certificate2 certificadoDigital, String signatureMethodSignedXml, String digestMethodReference, Boolean removerAcentos)\r\n at NFe.Servicos.ServicosNFe.RecepcaoEvento(Int32 idlote, List`1 eventos, ServicoNFe servicoEvento, VersaoServico versaoEvento)\r\n at
> > > Status Autorizacao ConsultaPorChave ConsultaPorRecibo Inutilizacao
> > > Estão funcionando normal sem o erro de certificado...
> > 
> > 
> > o código que postei funciona certinho o cancelamento com a acessão da parte: "var xml = retornoCancelamento.ProcEventosNFe.FirstOrDefault().ObterXmlString();"
> > do resto está rodando... Ambiente de Homologação em SP
> 
> Meu código está exatamente igual ao seu...

Se puder poste seu código para poder dar uma olhada se vc deixou passar alguma coisa despercebido

**Comment by hdamasceno** [comment]
`
            string retornoCompletoStr = string.Empty;

            using (var servicoNFe = new ServicosNFe(_configuracoes.CfgServico))
            {
                var retornoConsulta = servicoNFe.RecepcaoEventoCancelamento
                    (
                        loteNumero,
                        eventoSequenciaNumero,
                        protocoloAutorizacaoNumero,
                        chaveAcesso,
                        justificativa,
                        emitenteCnpj
                    );

                eventoResposta = retornoConsulta;

                TrataRetorno(retornoConsulta);

                retornoCompletoStr = retornoConsulta.RetornoCompletoStr;
            }

            return retornoCompletoStr;
`

**Comment by rafatozzi** [comment]
> ` string retornoCompletoStr = string.Empty;
> 
> ```
>         using (var servicoNFe = new ServicosNFe(_configuracoes.CfgServico))
>         {
>             var retornoConsulta = servicoNFe.RecepcaoEventoCancelamento
>                 (
>                     loteNumero,
>                     eventoSequenciaNumero,
>                     protocoloAutorizacaoNumero,
>                     chaveAcesso,
>                     justificativa,
>                     emitenteCnpj
>                 );
> 
>             eventoResposta = retornoConsulta;
> 
>             TrataRetorno(retornoConsulta);
> 
>             retornoCompletoStr = retornoConsulta.RetornoCompletoStr;
>         }
> 
>         return retornoCompletoStr;
> ```
> 
> `

esse _configuracoes.CfgServico é o mesmo que para emitir a nota?

**Comment by hdamasceno** [comment]
sim, eu utilizo o mesmo factory para criar o serviço.
muito estranho...

Tá assim o componente de configuração..

`public ConfigurarApp(dynamic objetoConfiguracao)
        {
            CfgServico = ConfiguracaoServico.Instancia;

            CfgServico.tpAmb = TipoAmbiente.Producao;

            if (objetoConfiguracao.ambiente == "HOMOLOGACAO")
                CfgServico.tpAmb = TipoAmbiente.Homologacao;

            CfgServico.tpEmis = TipoEmissao.teNormal;
            CfgServico.cUF = DFe.Classes.Entidades.Estado.MG;

            CfgServico.ProtocoloDeSeguranca = SecurityProtocolType.Tls12;

            CfgServico.ModeloDocumento = ModeloDocumento.NFCe;
            CfgServico.RemoverAcentos = true;
            CfgServico.DefineVersaoServicosAutomaticamente = true;
            CfgServico.DiretorioSchemas = FuncoesEspeciais.ToString(objetoConfiguracao.schemasDir, false, false, true);
            CfgServico.TimeOut = 30000;

            Emitente = new emit();

            Emitente.CNAE = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.cnae);

            if (FuncoesEspeciais.ToString(objetoConfiguracao.emitente.regimeTributarioNome) == "SIMPLES NACIONAL")
                Emitente.CRT = CRT.SimplesNacional;
            else if (FuncoesEspeciais.ToString(objetoConfiguracao.emitente.regimeTributarioNome) == "SIMPLES NACIONAL EXCESSO")
                Emitente.CRT = CRT.SimplesNacionalExcessoSublimite;
            else if (FuncoesEspeciais.ToString(objetoConfiguracao.emitente.regimeTributarioNome) == "NORMAL")
                Emitente.CRT = CRT.RegimeNormal;
            else
                Emitente.CRT = CRT.SimplesNacional;

            Emitente.IE = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.inscricaoEstadual);
            Emitente.xFant = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.nomeFantasia);
            Emitente.xNome = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.razaoSocial);

            EnderecoEmitente = new enderEmit();

            EnderecoEmitente.CEP = FuncoesEspeciais.SomenteNumero(FuncoesEspeciais.ToString(objetoConfiguracao.emitente.cep));
            EnderecoEmitente.cMun = FuncoesEspeciais.ToInt(objetoConfiguracao.emitente.cidadeCodigoIbge);
            EnderecoEmitente.cPais = FuncoesEspeciais.ToInt(objetoConfiguracao.emitente.paisCodigoIgbge);
            EnderecoEmitente.fone = FuncoesEspeciais.ToInt(FuncoesEspeciais.SomenteNumero(FuncoesEspeciais.ToString(objetoConfiguracao.emitente.telefoneNumero)));
            EnderecoEmitente.nro = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.enderecoNumero);
            EnderecoEmitente.UF = DFe.Classes.Entidades.Estado.MG;

            EnderecoEmitente.xBairro = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.enderecoBairro);
            EnderecoEmitente.xCpl = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.enderecoComplemento);
            EnderecoEmitente.xLgr = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.enderecoLogradouro);
            EnderecoEmitente.xMun = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.cidadeNome);
            EnderecoEmitente.xPais = FuncoesEspeciais.ToString(objetoConfiguracao.emitente.paisNome);

            Emitente.enderEmit = EnderecoEmitente;

            ConfiguracaoCsc = new ConfiguracaoCsc
                (
                    FuncoesEspeciais.FormataTexto(FuncoesEspeciais.ToString(objetoConfiguracao.CSC_ID), "E", "0", 6), // 000001
                    FuncoesEspeciais.ToString(objetoConfiguracao.CSC)                                                 // GUID ou CSC Number ( text )
                );
        }`

**Comment by hdamasceno** [comment]
Testando em MG ok

**Comment by hdamasceno** [comment]
E o certificado estou usando assim:

`
public ZeusNFCeController(dynamic objetoConfiguracao, X509Certificate2 objetoCertificadoDigital)
        {
            _configuracoes = new ConfigurarApp(objetoConfiguracao);

            DefinirVersaoServicos();

            _configuracoes.CfgServico.Certificado.TipoCertificado = DFe.Utils.TipoCertificado.A1ByteArray;
            _configuracoes.CfgServico.Certificado.ArrayBytesArquivo = objetoCertificadoDigital.RawData;
        }
`

**Comment by hdamasceno** [comment]
Assim está funcionando para todos os serviços menos no de cancelamento...

**Comment by rafatozzi** [comment]
> E o certificado estou usando assim:
> 
> ` public ZeusNFCeController(dynamic objetoConfiguracao, X509Certificate2 objetoCertificadoDigital) { _configuracoes = new ConfigurarApp(objetoConfiguracao);
> 
> ```
>         DefinirVersaoServicos();
> 
>         _configuracoes.CfgServico.Certificado.TipoCertificado = DFe.Utils.TipoCertificado.A1ByteArray;
>         _configuracoes.CfgServico.Certificado.ArrayBytesArquivo = objetoCertificadoDigital.RawData;
>     }
> ```
> 
> `

a única diferença que tenho do seu é que não uso o A1ByteArray, uso o A1Arquivo

**Comment by hdamasceno** [comment]
> > E o certificado estou usando assim:
> > ` public ZeusNFCeController(dynamic objetoConfiguracao, X509Certificate2 objetoCertificadoDigital) { _configuracoes = new ConfigurarApp(objetoConfiguracao);
> > ```
> >         DefinirVersaoServicos();
> > 
> >         _configuracoes.CfgServico.Certificado.TipoCertificado = DFe.Utils.TipoCertificado.A1ByteArray;
> >         _configuracoes.CfgServico.Certificado.ArrayBytesArquivo = objetoCertificadoDigital.RawData;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> 
> a única diferença que tenho do seu é que não uso o A1ByteArray, uso o A1Arquivo

Vou testar aqui lendo do arquivo para ver se o que acontece...

**Comment by rafatozzi** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/185#issuecomment-243789231

este comentário fez abrir minha mente... pois eu tinha uma visão antiga de como prosseguir com eventos em notas fiscais.

deixarei aberto para continuar a dúvida do hdamasceno
