### ISSUE TITLE
NF Sincrono

### ISSUE THREAD

**Issue by vladimir01rj** [ZeusAutomacao/DFe.NET#1302]
Pessoal, estou tendo problemas com o envio de NFCe com o Zeus.
Sempre utilizei o método assincrono, mas preciso enviar no método Sincrono.
Alguém pode me ajudar com um passo a passo?

**Comment by felixsevero** [comment]
É só você alterar o `IndicadorSincronizacao` de `Assincrono` para `Sincrono`. Lembrando que para usar de forma síncrona, seu estado deve permitir esse modelo de envio, além de você poder enviar apenas uma nota fiscal por vez.

**Comment by vladimir01rj** [comment]
Olá, Felixsevero!
Já fiz essa alteração, mas não funciona. Acho q tem mais alterações por fazer e não é somente essa Mudança.

**Comment by felixsevero** [comment]
Para o envio síncrono, que eu lembre, é apenas isto. Se tiver algum problema mais específico, poste aqui que tentaremos ajudar.

**Comment by marcosgerene** [comment]
@vladimir01rj 

O envio sincrono só tem essa diferença. A mudança que você vai ter é no tratamento do retorno, no envio sincrono de nota fiscal única o protNFe (NFe.Classes.Protocolo.protNFe) vem direto no retorno ( NFe.Servicos.Retorno.RetornoNFeRetAutorizacao).

Exemplo: 
```
private const int statusRetornoRecibo = 104;
private const int maximoTentativasRecibo = 5;

//cenário: tenho a variável "retornoEnvio" do tipo NFe.Servicos.Retorno.RetornoNFeAutorizacao com a resposta da sefaz.

var protocolos = new List<NFe.Classes.Protocolo.protNFe>();

//Nota fiscal única emitida de forma SINCRONA retorna o protocolo da NFe
if (retornoEnvio?.Retorno?.protNFe != null)
{
	protocolos.Add(retornoEnvio?.Retorno?.protNFe);
}

//Caso não existe o protocolo preciso do número do recibo
else
{
	if (retornoEnvio?.Retorno?.infRec == null || retornoEnvio.Retorno.infRec.nRec.IsNull())
		throw new Exception("Não foi possível recuperar o número do recibo da emissão");
	
	NFe.Servicos.Retorno.RetornoNFeRetAutorizacao retornoRecibo = null;

	//consultando o recibo, obtenho a lista de protNFe de todas as notas do lote
	for (int tentativa = 0; tentativa < maximoTentativasRecibo; tentativa++)
	{
		System.Threading.Thread.Sleep(1000);

		using (var _certificado = DFe.Utils.Assinatura.CertificadoDigital.ObterCertificado(ZeusConfiguracaoServico.Certificado))
		using (var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusConfiguracaoServico, _certificado))
			retornoRecibo = servicoNfe.NFeRetAutorizacao(retornoEnvio.Retorno.infRec.nRec);

		if (retornoRecibo?.Retorno?.cStat == statusRetornoRecibo)
			break;
	}

	if (retornoRecibo?.Retorno?.protNFe == null)
		throw new Exception("Nenhum protocolo encontrado no recibo da NFe");

	protocolos.AddRange(retornoRecibo.Retorno.protNFe);
}


//confere em todos os protocolos o sucesso da emissão, algo que você já faz hoje com o envio assincrono
foreach (var protocolo in protocolos)
{
	//...
}
```


----


Edit: alguns estados não aceitam envio Sincrono, mesmo que você mande. Se não me engano, SP é um deles. Mesmo que envie Sincrono ele vai se comportar de forma Assincrona.

**Comment by danilobreda** [comment]
Vou fechar issue por falta de retorno.
