### ISSUE TITLE
Cancelamento de NFCe - Exception - "Signing key is not loaded."

### ISSUE THREAD

**Issue by hdamasceno** [ZeusAutomacao/DFe.NET#1305]
Estou usando o Zeus em produção em um servidor na Azure e toda vez que eu preciso cancelar uma NFCe obtenho essa exception da imagem abaixo:

![image](https://user-images.githubusercontent.com/4733294/141336677-2440b07f-47cc-4540-a3bf-fa669ff9c8f2.png)

Para esse mesmo certificado que eu não consigo cancelara NFCe (que o mesmo serviço acabou de transmitir normalmente segundos atrás) não consegue cancelar.
Preciso configurar alguma coisa diferente para fazer cancelamento de NFCe utilizando o Zeus?

**Comment by hdamasceno** [comment]
A consulta da chave funciona, mas o cancelamento nao...

![image](https://user-images.githubusercontent.com/4733294/141337939-ddedd442-421d-4872-8efe-0e1c33d112d3.png)

Cancelamento logo após a consulta por chave funcionar dando exception

![image](https://user-images.githubusercontent.com/4733294/141338105-604c5f43-662f-4504-86f3-d00fcde88b1d.png)

**Comment by hdamasceno** [comment]
Debug realizado em windows 10 com windows update em dia... em minha máquina desenvolvimento, dando o mesmo erro obtido no servidor azure...
Alguma dica de como resolver isso?

**Comment by danilobreda** [comment]
@hdamasceno conseguiu resolver? Acredito que o correto seria baixar o projeto do zeus, executar ele debugando com essas variáveis suas, e verificar aonde exatamente é o problema.

**Comment by hdamasceno** [comment]
Ainda não obtive sucesso, o estranho que o mesmo código para enviar uma NFCe está funcionando perfeitamente o cancelamento que deu isso.
Essa madrugada irei poder para o servidor daí, poderei fazer mais testes. Como meu volume de NFCe é intenso 5 min com o servidor fora gera muita contingência, daí isso dificulta ainda mais depurar esse tipo de problema.

**Comment by danilobreda** [comment]
Acredito que tenha sido resolvido, vou fechar a issue, qualquer coisa estamos aqui :)
