### ISSUE TITLE
Consulta por chave de acesso NFCe - MG -> Sem comunicação com o serviço

### ISSUE THREAD

**Issue by hdamasceno** [ZeusAutomacao/DFe.NET#1308]
Boa tarde,

Estou com problemas de consulta de chave de acesso de NFCe em MG desde o dia 04-11 quando o certificado do endpoint de minas foi modificado.
Já troquei o certificado no meu servidor na azure, mas mesmo assim do nada para de funcionar e começa a retornar essa mensagem de erro abaixo:

"Sem comunicação com o serviço NfeConsultaProtocolo:\nA connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:45.183.222.33]:443 (nfce.fazenda.mg.gov.br:443)

Alguém já passou por algo parecido?

**Comment by danilobreda** [comment]
Parece ser algo com timeout, quanto está seu timeout na configuration do zeus? tenta aumentar para 30s ou mais.

**Comment by hdamasceno** [comment]
Timeout está em 120 segundos.
Pesquisando localmente esta normal...

O muito estranho é que o serviço no azure inicia o dia perfeito e ao longo do dia vai caindo até parar de funcionar...
E no mesmo horário que não funciona no azure eu testo no meu pc localmente aqui e funciona perfeito...

No azure estou com planos em produção nível 1 e com nem 1% de uso do servidor, olhei os logs e nada indica um consumo elevado ou bloqueio de tráfego de rede.

O servidor no azure esta hospedado no Brasil tb,...

**Comment by matheusilva** [comment]
Aqui está retornando bastante esse erro, **possivelmente** é o servidor do gov que está com instabilidade. Porque tem horas que do nada volta a funcionar.

**Comment by hdamasceno** [comment]
show vlw!
