### ISSUE TITLE
Método NfeDistDFeInteresse não utilizando o argumento "ufAutor"

### ISSUE THREAD

**Issue by Gutochamp** [ZeusAutomacao/DFe.NET#1309]
Olá pessoal!
Estou enfrentando problemas de validação de schema ao buscar NF-e's pelo último NSU usando o método `NFe.Servicos.ServicosNFe.NfeDistDFeInteresse` quando configuro para usar os serviços do ambiente nacional (`_cFgServico.cUF==Estados.AN`).
Ao inspecionar o código-fonte do método, percebi que o argumento `ufAutor` não está sendo usado.
Tendo isso em mente, segue uma proposta de alteração nas linhas 825 a 830 e na linha 835.
![Proposta alteração Zeus NFe](https://user-images.githubusercontent.com/39731315/144061162-c384134b-13b4-479c-bed2-f7613b283925.png)
.

**Comment by victorperez2911** [comment]
Bom Dia @Gutochamp 

Acho que isso pode te ajudar

https://github.com/ZeusAutomacao/DFe.NET/issues/1268

**Comment by danilobreda** [comment]
Acredito que o problema tenha sido resolvido, estou fechando a issue. Qualquer coisa estamos aqui :)
