### ISSUE TITLE
NFS-e

### ISSUE THREAD

**Issue by luizgustavogp** [ZeusAutomacao/DFe.NET#131]
Olá pessoal, já existe algum projeto em andamento para NFS-e?
Caso não exista e eu queira adicionar no projeto existente o que vocês indicariam?
Criar um novo projeto na solution?
Modificar o existente?

Abraço e muito boa a iniciativa de compartilhar com a comunidade o projeto.
Obrigado!

**Comment by leandrossantos** [comment]
@luizgustavogp também estou precisando de NFSe e MDFe.
Eu acredito que seria bom ser em projetos diferentes. 
1 para cada situação.

O que me diz?

**Comment by orochasamuel** [comment]
Fala @luizgustavogp e @leandrossantos eu tenho a intenção de iniciar um projeto de NFSe. Podemos iniciar esse projeto juntos, o que acham?

A NFSe é um pouco mais complexa porque não é unificada e padronizada como a NFe. Cada prefeitura tem um layout para emissão da NFSe, o que podemos é incluir no projeto os layouts mais usados tais como, WebISS, Betha, ISSintel, GINFES, etc... 

[Mais detalhes...](https://g2kanfe.wordpress.com/2011/06/16/nf-e-e-nfs-e-entenda-as-diferencas-entre-as-notas-fiscais-eletronicas-de-produto-e-servicos/)

-- Samuel Rocha

**Comment by orochasamuel** [comment]
Sobre a MDFe... eu não conheço muito do projeto mas acredito que antes de ter o MDF é necessário incluir o CTe na biblioteca também, bem como o consumo dos serviços de consulta destinatário e distribuiçãoDfe. Com esses recursos na biblioteca acredito que poderia atender perfeitamente as necessidades (já é excelente a biblioteca mas ainda podemos fazer mais para melhora-la :D )

-- Samuel Rocha

**Comment by orochasamuel** [comment]
Eu também atuo no desenvolvimento de outra biblioteca, a [SPEDBr](http://samuelroliveira.github.io/SPEDBr/), para exportação dos arquivos eletrônicos das declarações contábeis/fiscais. Há pouco tempo iniciei esse projeto mas acredito que logo ele será de grande valia para a comunidade.

-- Samuel Rocha

**Comment by luizgustavogp** [comment]
Olá pessoal, eu animo a ajudar. Inicialmente eu estava precisando emitir para Belo Horizonte. O padrão seria a derivação ABRASF. Podemos incluir outros de acordo com o interesse de cada um.

Abraço!

**Comment by leandrossantos** [comment]
Estou dentro pessoal, de todos os projetos. NFSe, CTe, MDFe e SPED.

Sobre o MDFe até tentei iniciar aqui, mais não consegui criar as classes de comunicação com os WS. As url não querem funcionar no VS

**Comment by orochasamuel** [comment]
@luizgustavogp eu preciso para BH, SP e GO, todos eles são derivações do padrão ABRASF. Vamos nos falando para trabalharmos nesse projeto.

@leandrossantos fico grato em saber da sua disponibilidade. Vamos nos organizar para trabalharmos nesses projetos.

Abraços.

-- Samuel Rocha
