### ISSUE TITLE
Erro ao executar o Metodo signedXml.ComputeSignature();

### ISSUE THREAD

**Issue by JoaoSpagnol** [ZeusAutomacao/DFe.NET#1310]
Bom dia meus amigos eu peguei a o Projeto do Zeus , e estou consumindo as dll no meu projeto porem quando vou assinar o xml ele para neste metodo signedXml.ComputeSignature();
usando o projeto de teste do Zeus ele me abre uma caixa do certificado , quando anexo no meu projeto de teste ele nao faz isto , exite alguma coisa que precisa ser feito ?

**Comment by danilobreda** [comment]
Seu projeto de teste é qual versão do .NET?

**Comment by JoaoSpagnol** [comment]
esta numa unidade de teste na versao 4.5

**Comment by danilobreda** [comment]
Você configurou A3 na classe de config? tudo certinho?
Tenta efetuar o teste em um projeto windowsforms. Pois pode ser que rodando em uma "unidade de teste" não apareça a tela.

**Comment by JoaoSpagnol** [comment]
O meu a1

Em qui, 2 de dez de 2021 17:23, Danilo Breda ***@***.***>
escreveu:

**Comment by JoaoSpagnol** [comment]
As dlls nao roda lado servidor ?

**Comment by JoaoSpagnol** [comment]
bom dia Amigo Danilo eu fiz num projeto de windows forms e deu certo abriu a tela porque sera que na parte servidor nao esta dando certo  ?

**Comment by danilobreda** [comment]
A única maneira de rodar em lado de servidor é usando A1, você tem que colocar na configuração o certificado como dados binary e a senha. (Não é para aparecer a caixa de selecionar certificado pois esta rodando no lado servidor)
Caso você tenha A3, e o servidor for físico, ai você tem que espetar o pendrive do certificado no servidor que também funciona.

**Comment by JoaoSpagnol** [comment]
Danilo deixa eu ti fazer uma outra pergunta , é possivel de alguma forma meus dados dlls esta num servidor na nuvem e meu certificado A3 na minha maquina  local , é possivel fazer assim nossos dados estao num servidor nas nuvem e os usuario via ts usam este servidor

**Comment by danilobreda** [comment]
@JoaoSpagnol é possível apenas criando um "robozinho" que fica na maquina do cliente onde está o A3, e quando o usuário emite uma nota fiscal via nuvem, a núvem chama esse cliente de alguma maneira para assinar esse XML da nota fiscal e enviar ela... mas não recomendo, recomendo mesmo usar A1. E em alguns casos comprar o A1 pro cliente.
