### ISSUE TITLE
Impressão NFC-e (DanfeNativoNfce) com Acréscimos

### ISSUE THREAD

**Issue by guipiva-dev** [ZeusAutomacao/DFe.NET#1312]
Ao imprimir um NFC-e com produtos que possuem acréscimos, não está acumulando o valor dos acréscimos ao valor total para efetuar o cálculo do troco, conforme imagem abaixo...
![nfce](https://user-images.githubusercontent.com/4616111/145586237-70debdbc-1ff3-4735-bf2c-158769a6e569.jpg)

**Comment by danilobreda** [comment]
por ser um problema um pouco antigo, vou fechar a issue, o projeto é opensource, qualquer modificação feita por pullreques é bem vinda :)
