### ISSUE TITLE
UF Ceará - Alteração de URL's Para emissão de NF-e (Somente NF-e)

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#1314]
https://cfe.sefaz.ce.gov.br/mfe#/

Com isso fiz uma mudança nas urls do Enderecador.cs na parte de NF-e 

Quem quiser alterar para as novas URL's basta fazer esse código 
ele irá inicializar com novas URL's 
![image](https://user-images.githubusercontent.com/10251705/146817085-7bcb276d-9867-498f-bc63-9c8c1b5e48a2.png)

No seu sistema eu fiz uma configuração para setagem das novas URL's 
![image](https://user-images.githubusercontent.com/10251705/146817419-27e495af-8b64-4b04-853e-7f6a51da374e.png)

Verifico quando é NF-e o modelo documento 
Quando for NF-e eu seto as URLs do Ceará 

FactoryUrlCearaMudanca (está classe , está no pacote do Zeus , obviamente será deletada até 01/07/2022) , pois não haverá mais necessidade da mesma , até lá imagino eu que o Estado do Ceará já ativou definitivamente as novas URL's. 

A data limite do Estado conforme noticia que mandei é 

"A Secretaria da Fazenda do Ceará (Sefaz-CE) informa que, a partir do dia 10 de janeiro de 2022, às 9 horas, as Notas Fiscais Eletrônicas (NF-e) emitidas por contribuintes do Ceará passarão a ser autorizadas por meio da Sefaz Virtual do Rio Grande do Sul (SVRS)."

Observem que eles disseram "a partir do dia 10 de janeiro de 2022, às 9 horas," com isso já sabemos que não é certeza que realmente isso acontecerá no dia 10 ou as 9 da manhã enfim , por isso preferi fazer isso , pois cada pessoa implementa a UF do Ceará a URL a gosto. 

Obviamente quando ativarem a Produção do Estado do Ceará , irei atualizar as URLs todas do Estado do Ceará na classe FactoryURL que é a que o Zeus utiliza como default é imediatamente lançar uma versão nova das dlls no nuget. 

Mas como falei é melhor implementarem a chamada nova de acordo com suas necessidades é regras de negocio. 

Qualquer dúvida estou a disposição ;)

**Comment by DaniFTT** [comment]
Boa Tarde Roberto, tudo bom?

Fiquei com uma duvida sobre a implementação desse Método ConfiguraUrlsCeara. Aonde exatamente vc implementa esse método e o chama? e também de que pacote vem esse Método SessaoHelperFactory.

**Comment by marcosgerene** [comment]
@DaniFTT 

A explicação do @robertorp ficou um pouco confusa porque ele usou muito código do sistema dele para explicar uma unica linha do processo, eu e o @danilobreda  tivemos a mesma dúvida que você...

O código consiste em:
```
if (...) //se usar as novas dlls do CE
    ConfiguracaoUrls.FactoryUrl = Shared.NFe.Utils.Enderecos.NovasUrlsCeara.FactoryUrlCearaMudanca.CriaFactoryUrl();
```

Você deve executar ele no momento em que configura o Zeus na sua aplicação, antes de executar o método desejado (consulta, envio, cancelamento, etc).

**Comment by marcosgerene** [comment]
@DaniFTT 

O código consiste em:
```
if (...) //se usar as novas dlls do CE
    ConfiguracaoUrls.FactoryUrl = Shared.NFe.Utils.Enderecos.NovasUrlsCeara.FactoryUrlCearaMudanca.CriaFactoryUrl();
```

Você deve executar ele no momento em que configura o Zeus na sua aplicação, antes de executar o método desejado (consulta, envio, cancelamento, etc).

Um exemplo simplificado de uso:
```
public ConfiguracaoServico ZeusConfiguracao(ModeloDFe modeloDocto)
{
	var configuracao = new ConfiguracaoServico();
	configuracao.ProtocoloDeSeguranca = SecurityProtocolType.Tls12;
	
	... //demais configurações
	

	//aqui a mudança do CE
	if (...) //se usar as novas dlls do CE
		ConfiguracaoUrls.FactoryUrl = Shared.NFe.Utils.Enderecos.NovasUrlsCeara.FactoryUrlCearaMudanca.CriaFactoryUrl();

	return configuracao;
}

public void Emitir()
{
	var _configuracao = ZeusConfiguracao(gnfe.Modelo);
	
	... //processos que você faz antes de emitir como salvar xml, gerar chave etc
	
	 NFe.Servicos.Retorno.RetornoNFeAutorizacao retorno = null;

	using (var _certificado = CertificadoDigital.ObterCertificado(_configuracao.Certificado))
	using (var servicoNfe = new NFe.Servicos.ServicosNFe(_configuracao, _certificado))
		retorno = servicoNfe.NFeAutorizacao(1, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe>() { _nfe });
	
	string resposta = retorno.RetornoCompletoStr;
	
	... //tratamento do retorno
}
```

**Comment by khaddmussistemas** [comment]
tentei usar o exemplo mas está dando erro:
![image](https://user-images.githubusercontent.com/71778467/149863796-ff1f0862-ac87-4e5a-a39b-73edfc023228.png)

**Comment by vanderHobus** [comment]
@robertorp pensa em colocar como default essa configuração?
A Sefaz já passou a não aceitar mais a URL antiga. Essa nova configuração já passou a ser OBRIGATÓRIA.
Acredito que não há mais necessidade de fazer de forma opcional.

`Servico Paralisado sem Previsao  / Conforme comunicado NFe, utilizar o ambiente de homologacao da SVRS - https://www.sefaz.ce.gov.br/2021/11/30/comunicado-nfe-migracao-para-svrs/`

**Comment by victorperez2911** [comment]
Boa Tarde

Alguma novidade quanto a esse assunto ?

**Comment by robertorp** [comment]
Ta na hora já ne de colocar como default. Irei analisar é colocar o mais rapido possível como default, se alguém quiser ir na frente é já colocar pode ficar a vontade ! , vlw pelo tock !

**Comment by danilobreda** [comment]
@robertorp como ficou essa questão ja podemos finalizar essa issue?
