### ISSUE TITLE
Alteração de URL de consulta do QR-Code para Paraíba

### ISSUE THREAD

**Issue by manogold** [ZeusAutomacao/DFe.NET#1315]
Bom dia, pessoal. Venho abrir essa issue aqui porque as URLs de consulta do QR-Code para o estado da Paraíba foram alteradas desde 05/02/2020, tanto para produção quanto para homologação. E particularmente não vi nenhum comentário nesse sentido, então abri este. Segue os links diretamente do site da própria Sefaz-PB avisando a mudança, para efeito de informação:

[https://www.sefaz.pb.gov.br/info/documentos-fiscais/nfc-e](https://www.sefaz.pb.gov.br/info/documentos-fiscais/nfc-e)
[https://www.sefaz.pb.gov.br/view-docs?task=document.viewdoc&id=1382](https://www.sefaz.pb.gov.br/view-docs?task=document.viewdoc&id=1382)

Nós utilizamos a excelente biblioteca Zeus para fazer toda emissão de NFC-e e NF-e, e como temos clientes na Paraíba (somos de Pernambuco), estávamos com problemas em emitir NFC-e em ambiente de homologação para esse estado, pois com uma URL errada no QR-Code, ocorre a famosa _"Rejeição 395: Endereço do site da UF da Consulta via QR-Code diverge do previsto"_. 

Observei aqui github que as URLs da Paraíba (Homologação e Produção) ainda se encontram com as URLs antigas. Por isso, sugiro a correção dessas URLs na classe _**Shared.NFe.Utils\InformacoesSuplementares\ExtinfNFeSupl.cs**_, que é a classe onde ficam armazenadas as URLs para o QR-Code. Ao mesmo tempo sugiro realizar um pente fino para ver se todas as URLs dessa classe estão de acordo com as URLs disponibilizadas no site da encat para evitar possíveis problemas com outros estados:

[http://nfce.encat.org/desenvolvedor/qrcode/](http://nfce.encat.org/desenvolvedor/qrcode/)

Agradeço desde já pelo excelente trabalho de todos que mantém essa biblioteca.

**Comment by danilobreda** [comment]
Estamos aceitando contribuição dos usuários a fazer um pull request com as alterações observadas.
