### ISSUE TITLE
Validação de XML's com bandeira de cartão Alelo

### ISSUE THREAD

**Issue by andreluissousa** [ZeusAutomacao/DFe.NET#1316]
Referente aos tipos de bandeiras válidas, também consta o tipo 10 que é Alelo, porém, o zeus está retornando que esse tipo de bandeira é inválido.
![Screenshot_74](https://user-images.githubusercontent.com/35508787/148433684-e0730fa9-e2ce-42e1-a8aa-e80ddbf88fd9.png)

Segue link do portal nacional informando os tipos de pagamento e bandeiras válidas:
https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/NJarYc9nus=

[Tabela de bandeiras de cartão de crédito-débito (1).xlsx](https://github.com/ZeusAutomacao/DFe.NET/files/7824137/Tabela.de.bandeiras.de.cartao.de.credito-debito.1.xlsx)
[Tabela de meios de pagamento.xlsx](https://github.com/ZeusAutomacao/DFe.NET/files/7824164/Tabela.de.meios.de.pagamento.xlsx)

**Comment by wltjunior92** [comment]
Mesmo problema por aqui 🤔.

**Comment by luan-evangelista** [comment]
Mesmo por aqui também.

**Comment by adrbarros** [comment]
Aguardar o aceite do Pull-Request para esta correção.
#1317

**Comment by andreluissousa** [comment]
> Aguardar o aceite do Pull-Request para esta correção. #1317

Muito Obrigado!! 
Excelente!!
