### ISSUE TITLE
ERRO AO EMITIR NFE NO CEARA 

### ISSUE THREAD

**Issue by khaddmussistemas** [ZeusAutomacao/DFe.NET#1319]
Prezados, 

O ambiente e NET CORE 5 eu atualizei o zeus tanto pelo nuguet quanto por dlls  e os schemas tbm , mas não consigo emitir Nota fiscal no ceara no ambiente de produção
Se eu mudo o tipo de emissão para normal dar o erro
FALHA NA SOLICITAÇÃO COM STATUS 403
![image](https://user-images.githubusercontent.com/71778467/149847618-ba24c3e6-b4cc-47cb-bd37-b734da42e00d.png)
Se eu coloco o Tipo de Emissao para TeSVCRS 
![image](https://user-images.githubusercontent.com/71778467/149847813-906243fa-8a04-42c4-ac8c-4cb7c448fec6.png)

O erro é : Rejeição tipo de emissão 3 , 6 ou 7 so é valido nas contigencias SCAN/SVC

Ambos uso o protocolo Tls1.2

Conto com ajuda de vcs.

**Comment by danilobreda** [comment]
Foi verificado se o certificado está com data de validade no prazo?  403 sempre é isso...
Houve algumas mudanças no Ceara [https://github.com/ZeusAutomacao/DFe.NET/issues/1314](https://github.com/ZeusAutomacao/DFe.NET/issues/1314) recentemente, pode ter haver

**Comment by khaddmussistemas** [comment]
Sim segui a orientação da Issue e deu certo

Em ter., 18 de jan. de 2022 às 13:08, Danilo Breda ***@***.***>
escreveu:
