### ISSUE TITLE
IndicadorIss

### ISSUE THREAD

**Issue by juliolvfilho** [ZeusAutomacao/DFe.NET#132]
Olá @adeniltonbs,
primeiramente gostaria de agradecer sua valiosa contribuição à comunidade.

Talvez esteja faltando alguma configuração ou setar algum atributo no meu projeto mas creio que o atributo IndicadorIss em NFe.Classes.Informacoes.Detalhe.Tributacao.Municipal.ISSQN deva ser corrigido para indISS, pois ocorre erro na validação com os schemas.

Estou usando a versão da NFE 3.10

**Comment by adeniltonbs** [comment]
Você está certo, voou fazer a correção.
