### ISSUE TITLE
Erro ao Deserializar XML da Nota Fiscal Eletrônica para Normalização

### ISSUE THREAD

**Issue by RonanRocha** [ZeusAutomacao/DFe.NET#1321]
Fala galera tudo beleza ? estou com esse problema ao enviar uma nfc-e  no  modo síncrono no serviço de autorização no estado do RJ , algumas vezes funciona e outras vezes lança a exceção, alguém já pegou esse tipo de problema ? verifiquei o xml de envio no validador  da Sefaz do RS e estava válido.
 
[xml-envio.txt](https://github.com/ZeusAutomacao/DFe.NET/files/7941834/xml-envio.txt)
[stacktrace.txt](https://github.com/ZeusAutomacao/DFe.NET/files/7941845/stacktrace.txt)
[messagemretorno.txt](https://github.com/ZeusAutomacao/DFe.NET/files/7941854/messagemretorno.txt)

**Comment by marcosgerene** [comment]
Seu retorno diz que que não existe os campos de CST, vBC, pPIS na tag PISOutr. O mesmo vale para confins.

Entretanto no seu XML os campos existem. Provavelmente você esta mandando validar o arquivo de um jeito e tentando enviar de outro, basicamente o seu erro e o seu xml de envio não batem.

Poste o código de envio para que alguém da comunidade possa tentar te ajudar achar o motivo disso.

**Comment by RonanRocha** [comment]
@marcosgerene Muito obrigado pela rapidez na resposta !  esse é o fluxo até a chamada do serviço  

![1](https://user-images.githubusercontent.com/7989768/151218524-e14a6d3d-9425-4e3b-8188-d94f2665e725.PNG)

![2](https://user-images.githubusercontent.com/7989768/151218577-8cafd752-06a8-4e15-950d-8a1d66cc1a06.PNG)

![3](https://user-images.githubusercontent.com/7989768/151218705-a25da68f-0f3e-46ae-ad83-643da9130a4c.PNG)

![4](https://user-images.githubusercontent.com/7989768/151218718-4b4838b1-18ed-4696-930a-c304fe242592.PNG)

**Comment by marcosgerene** [comment]
@RonanRocha 

Em ```ObterNFeValidada()``` você passa sua nota fiscal pelos schemas, o que dispararia o erro que você relatou antes mesmo da tentativa do envio. Essa função é chamada em ```GerarNfe()``` onde você salva o XML em disco, me corrija se eu estiver errado, mas o xml salvo neste momento foi o que postou aqui.

Neste print não consegui entender muito bem o que faz a linha ```var (nfe, nfedata, xml) = ...```
https://user-images.githubusercontent.com/7989768/151218705-a25da68f-0f3e-46ae-ad83-643da9130a4c.PNG


Mas no final seu código que estava bom fica confuso, você tem o objeto do tipo NFe.Classes.NFe, mas usa elementos da sua entidade própria como numero, sendo que essa informação pode ser obtida de NFe.Classes.NFe....

Bom, faz o seguinte teste, na classe Enviar(), persiste em disco novamente o xml de NFe.Classes.NFe antes mesmo da primeira linha (var result = ...) e compara o xml que você salvou antes com este. Acredito que em algum momento do seu processo você está "modificando" essa classe e quebrando a emissão.

**Comment by RonanRocha** [comment]
@marcosgerene  Valeu pelas dicas, eu estava usando o o pacote do nuget e  não conseguia debugar, agora baixei do github e estou debugando e vi que o xml de envio realmente está diferente, vou fechar a issue. Muito obrigado mesmo.
