### ISSUE TITLE
Como faço para obter o xml da nfe assinada e com a tag protNFe

### ISSUE THREAD

**Issue by dagmarbezerra** [ZeusAutomacao/DFe.NET#1323]
Estou efetuando testes para começar a utilizar o Zeus na emissão das NFes no meu sistema, mas me deparei com uma dúvida.

Após transmitir uma nfe, obter o recibo e constatar que ela foi aceita, como faço para ter o xml da nfe completa, com a tag "Signature" e  a tag "protNFe" ?

**Comment by joaoroyosilva** [comment]
```csharp
var nfeproc = new nfeProc{
                            NFe = _nfe,
                            protNFe = retornoEnvio.Retorno.protNFe,
                            versao = retornoEnvio.Retorno.versao
                        };

                        Nfe.Xml = Converter.EncodeToBase64(FuncoesXml.ClasseParaXmlString(nfeproc));
```

_nfe é o objeto da NF-e gerada.
