### ISSUE TITLE
Cancelamento de NFCe dando erro apenas para ambiente Linux

### ISSUE THREAD

**Issue by GuiDev1994** [ZeusAutomacao/DFe.NET#1325]
Boa noite pessoal, primeira thread aqui desculpe, se eu não seguir algum protocolo corretamente.
Estou efetuando o cancelamento das notas fiscais NFCe's para teste e, em ambiente de desenvolvimento, pelo windows, ele lê a pasta de Schemas normalmente e efetua o cancelamento rapidamente, mas ao efetuar o cancelamento em minha API, já gera erro no XML. 
Segue abaixo o código e erro:

`        public invoice CancelInvoice(invoice invoice)
        {
            _utils = new NFeUtils(invoice.company);
            var _services = new ServicosNFe(_utils._configuration.CfgServico);

            var response = _services.RecepcaoEventoCancelamento(invoice.lot,
                                                                1,
                                                                invoice.protocol,
                                                                invoice.key,
                                                                "Cancelamento de nota fiscal venda n" + invoice.sale_id,
                                                                Utils.OnlyNumbers(invoice.company.company_invoice.cnpj));

            invoice.xml_return = response.RetornoStr;
            invoice.canceled = DateTime.Now;

            return invoice;
        }`       

`<retEnvEvento xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>0</idLote><tpAmb>2</tpAmb><verAplic>W-1.4.72</verAplic><cOrgao>31</cOrgao><cStat>215</cStat><xMotivo>Rejeição: Falha no schema XML</xMotivo></retEnvEvento>`

No Windows ele não gera esse erro, cancela direto.
Para envio funciona normalmente, meu problema é apenas no cancelamento da NFCe em Linux.
Subi minha aplicação como Net.Core em Docker, incluindo as pastas de certificados e Schemas, tanto que se eu não subisse corretamente nem emitir a nota ele não emitiria.

A versão que estou usando é a mais recente 1.0.0.1149.

**Comment by GuiDev1994** [comment]
Achei o erro pessoal, era a data e hora do meu servidor. 
Está assim no envio:
`<dhEvento>2022-02-10T01:19:38+00:00</dhEvento>`
Deveria estar assim:
`<dhEvento>2022-02-09T22:12:09-03:00</dhEvento>`

**Comment by danilobreda** [comment]
@guido2708 Qual estado era? Não era para ter acontecido esse problema...

**Comment by GuiDev1994** [comment]
> @guido2708 Qual estado era? Não era para ter acontecido esse problema...

@danilobreda beleza? O problema era a configuração do servidor Linux, tem que subir o Container definindo na variável ambiente o TimeZone daqui do Brasil.
O estado é MG.
Mas agora está funcionando corretamente, tudo graças à propriedade que colocaram de XML de envio, se não fosse isso eu ia ficar quebrando a cabeça aqui tentando entender o que estava acontecendo.
