### ISSUE TITLE
Homologação NFe - Serviço Paralisado sem Previsão

### ISSUE THREAD

**Issue by fabiojmdias** [ZeusAutomacao/DFe.NET#1326]
Estou com um problema ao tentar homologar a emissão da NFe na Sefaz de Mato Grosso (MT), onde está me retornando o erro: "
![xml](https://user-images.githubusercontent.com/53026849/153775013-67e8ba75-96a1-49b6-8320-a74f788350bb.PNG)
. Já atualizei os fontes do DFe.NET e o problema persiste. O estranho é que na homologação da NFCe eu consigo emitir normalmente.
Desculpe ter aberto uma issue para essa dúvida, mas não encontrei nenhum canal onde poderia tirar minhas dúvidas. Desde já, obrigado.

**Comment by danilobreda** [comment]
@fabiojmdias esta rejeição ocorre porque a SEFAZ está instável ou indisponível e não consegue processar a solicitação.
Nesse caso entre sempre no site da SEFAZ e verifique o status dos servidores deles...
Ainda acontece o problema?

**Comment by zcoderbusiness** [comment]
Olá @danilobreda, tudo certo contigo?

**Comment by fabiojmdias** [comment]
Olá @danilobreda, tudo certo? Essa rejeição estava ocorrendo desde o final de Janeiro e no status dos servidores estava constando tudo ok, por isso tomei a iniciativa de perguntar pra comunidade se mais alguém estava tendo esse problema. Neste meio tempo, também abri um chamado junto a Sefaz-MT e, aparentemente ontem eles resolveram a situação.

**Comment by robertorp** [comment]
Teria que dar uma verificada se existe alguma nota tecnica para esse estado de alteração de urls , se não tiver , então é problema local , poderia fazer isso para nós
