### ISSUE TITLE
MDFe

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#133]
Boa tarde colegas,

Gostaria de uma ajuda de vocês, pois não estou conseguindo aqui. Abaixo estão os links do webservices de MDFe, se alguém puder importá-las para uma aplicação em C# em agradeço. Só preciso dos webservices dentro do C#, o resto faço aqui.

MDFeRecepcao =  https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx
MDFeRetRecepcao = https://mdfe.svrs.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx
MDFeRecepcaoEvento  = https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx
MDFeConsulta = https://mdfe.svrs.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx
MDFeStatusServico = https://mdfe.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx
MDFeConsNaoEnc = https://mdfe.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx

**Comment by leandrossantos** [comment]
Ninguém ai que possa me ajudar???

**Comment by leandrossantos** [comment]
@adeniltonbs me ajuda ai, só preciso que seja importados os webservice, resto eu faço por aqui mesmo.

**Comment by adeniltonbs** [comment]
Para montar as classes, acesse essas urls adicionando, ao final de cada uma, o seguinte: ?WSDL.
Ex: https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx?WSDL 
Certifique-se que tenha um certificado instalado em seu pc, pois será necessário na hora de acessar a url.

Depois, o resultado vai ser algo parecido com:

![image](https://cloud.githubusercontent.com/assets/6733483/15440285/10cdd3c4-1eab-11e6-8929-b077a6f98961.png)
Esse xml contém as informações para consumo do serviço. 
Salve o xml, contendo todo o elemento "<wsdl>", em um arquivo .wsdl
Obs: Se abriu a url com o google chrorme, não salve a frase "This XML file does not appear to have any style information associated with it. The document tree is shown below." no arquivo.

Abra o Developer Command Prompt for Visual Studio e nele vá até o diretório onde está o arquivo .wsdl

Digite o comando wsdl arquivo.wsdl e a classe será gerada pra você.
Basta remover a sujeira e fazer algumas alterações que estará pronta para uso.

**Comment by leandrossantos** [comment]
Valeu @adeniltonbs obrigado mesmo, deu certinho.

**Comment by alsantana** [comment]
Olá @leandrossantos, vc tem algo sobre manifestação do destinatário?
Precisa de alguma ajuda?
grd abs
