### ISSUE TITLE
Alteração de URL de consulta a NFCe via QR-Code para Minas Gerais

### ISSUE THREAD

**Issue by WashingtonAutocom** [ZeusAutomacao/DFe.NET#1330]
Bom dia pessoal.

Abri essa issue para tratar da alteração da URL de consulta da NFCe via QRCode.
Conforme anunciado no site http://www.sped.fazenda.mg.gov.br/spedmg/nfce/, a nova URL já está ativa e a URL antiga será desativada a partir do dia 21/03 (segunda-feira).

Abaixo deixo o link onde é listado a relação dos Web Services de Minas Gerais:
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/

Portanto as URL ficaram da seguinte forma:
## Ambiente de Produção:
- Antiga (será descontinuada dia 20/3): 
URL: https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml
- Nova (única válida a partir de 21/3): 
URL: https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml

## Ambiente de Homologação:
- Antiga (será descontinuada dia 20/3): 
URL: https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml
- Nova (única válida a partir de 21/3): 
URL: https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml

**Comment by WashingtonAutocom** [comment]
Pessoal eu já tomei a iniciativa e realizei a modificação e também já criei o Pull Request #1331.
Caso tenha feito algo errado ou fora do padrão, por favor me informe que realizo os procedimentos corretos.

**Comment by LosDeveloper** [comment]
Alguem sabe me dizer se essa alteração ja está no NuGet?
Para homologação aqui ainda continua dando erro

**Comment by danilobreda** [comment]
@LosDeveloper já está no nuget **1.0.0.1159**

**Comment by WashingtonAutocom** [comment]
> Alguem sabe me dizer se essa alteração ja está no NuGet? Para homologação aqui ainda continua dando erro

@LosDeveloper.
Eu achei o problema, a sefaz decidiu trollar e não alterar a URL de Homologação, quando criei a issue e realizei a modificação no site onde tem os endereços do web services estava a mesma URL que a de Produção e com a mesma data de alteração, até coloquei no cabeçalho dessa issue. Porem depois a sefaz decide não alterar mais e complica para o nosso lado, mais já fiz a alteração novamente e já abri um novo Pull Request #1339.

Então @robertorp  e @danilobreda agora acredito que esteja tudo certo. 
Veremos se a sefaz não decidi alterar novamente.

**Comment by hdamasceno** [comment]
Boa noite acabei de testar o componente em MG atualizado com a versão do nuget e a URL do QRCode veio ainda a antiga.
Existe alguma coisa que tenha que ser feita no código para pegar a URL nova do QRCode ?

**Comment by hdamasceno** [comment]
Recebemos um comunicado da SEFAZ nos solicitando a alteração da URL com data limite hoje 31-05-2022...
