### ISSUE TITLE
Erro Danfe .Net Core: startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by dkraide** [ZeusAutomacao/DFe.NET#1332]
Pessoal, bom dia!! Estou tentando imprimir uma danfe, mas estou com erro apenas em uma nota fiscal... Alguém ja passou por esse erro ?
o objeto DanfeFrNfe é carregado normalmente. O erro está na função ExportarHtml();

![image](https://user-images.githubusercontent.com/43674712/156584909-1e65c37b-60f4-42c5-a713-dc19ab4aa975.png)

**Comment by dkraide** [comment]
segue o xml

[nfe.txt](https://github.com/ZeusAutomacao/DFe.NET/files/8178605/nfe.txt)

**Comment by marcosgerene** [comment]
@dkraide  Você usa Fast "full" ou open source?

**Comment by marcosgerene** [comment]
@dkraide 

Sua nota fiscal não é válida.

Dei um pretty print nela para ficar mais fácil a visualização e de cara falta o Id (chave de acesso)

![image](https://user-images.githubusercontent.com/15945003/167935944-e7b64738-1ba9-49fe-833e-1d89961a1bf9.png)

Usando um validador online:

![image](https://user-images.githubusercontent.com/15945003/167935796-98b11d37-4cae-4e65-a5ef-f143647a97b7.png)

**Comment by dkraide** [comment]
@marcosgerene 

Oi, bom dia!! Muito obrigado pelo feedback!! Realmente foi um erro interno, esse xml salvou sem o id, por isso o erro. Eu acabei não reparando de primeira,  mas agradeço a atenção!!
