### ISSUE TITLE
NfeDistDFeInteresse Rejeição 109: Serviço paralisado sem previsão

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#1333]
Olá pessoal, estou recebendo sempre esta mensagem, li que a receita fez um bloqueio desse serviço, alguma alternativa para baixar os XMLs das  notas ?

Verifiquei que alguns serviços pagos como fiscal.io sieg ainda continuam a funcionar.

**Comment by jairoamorin** [comment]
Boa tarde.  Vc pode utilizar a consulta pelo ultimo NSU para isso, após da ciencia na operação, o sefaz retorna o xml dentro do lote.

**Comment by danilobreda** [comment]
O Sefaz mudou algumas questões quanto a issue, estou fechando a issue por ser uma questão já entendi.
