### ISSUE TITLE
 servicoNFe.NFeAutorizacao não mapea protNFe

### ISSUE THREAD

**Issue by claytonduran** [ZeusAutomacao/DFe.NET#1334]
Bom dia  a todos!

O  retorno do servicoNFe.NFeAutorizacao traz o tipo retEnviNFe, que tem apenas a tag infRec , não mapeando a tag protNFe.Alguem sabe motivo do não mapeamento e como posso resolver essa questão?

Abraços,
Clayton

**Comment by claytonduran** [comment]
Essa questão acima que citei esta ocorrendo no ambiente de homologação que nao esta trazendo mapeada o retorno protNFe.

**Comment by adrbarros** [comment]
Bom vamos la: Se você estiver executando o método NFeAutorizacao de Forma Assincrona deve seguir os seguintes passos, após o Envio da NF-e
- NFeRetAutorizacao (Vai ter que fazer a chamada desse metodo, passando o numero do Recibo Retornado pelo NFeAutorizacao). Neste retorno vai saber se a Nota foi autorizada, rejeitada etc.
* Com a Nota Autorizada
- NfeConsultaProtocolo (Passando a Chave Eletronica da NFe Enviada)
*  Assim completando seu Objeto NFe
var nfeproc = new nfeProc
{
   NFe = nfe,
   protNFe = retornoConsultaProtocolo.Retorno.protNFe,
   versao = retornoConsultaProtocolo.Retorno.versao
};

**Comment by claytonduran** [comment]
Boa Tarde AdrBarros 
estamos utilizando de forma sincrona, ele retorna codigo 103 cstatus porem nao retorna nefproc , executando de forma sincrona era para retornar? 

Outro detalhe quando rodo metodo NFeRetAutorizacao  ele me retorna que "Serviço NfeInutilizacao, versão , não disponível para a UF SP, no ambiente de Homologação para emissão tipo Normal, documento: NF-e"

**Comment by danilobreda** [comment]
@claytonduran não recomendo forma **SÍNCRONA** pois está em **desuso**... vou utilizou a demo e debugou ele pra entender o processo? lá tem tudo que você precisa.

NFe.AppTeste: Projeto em WPF para demonstração de uso do NFe;
NFe.AppTeste.NetCore: Projeto em Console para demonstração de uso do NFe e NFCe em .NET5;

**Comment by adrbarros** [comment]
@claytonduran , bom dia, rapaz eu usei Envio Sincrono, poucas vezes, acho que só na Aplicação de Demonstração. Na meu Emissor de NF-e e NFC-e só uso envio Assincrono

**Comment by claytonduran** [comment]
Bom dia pessoal...agradeço todas dicas , realizei os procedimento indicado e deu certo estou conseguindo enviar e receber TDS dados.

Abraço a TDS muito obrigado pelo auxilio
