### ISSUE TITLE
Erro Inutilização NFE

### ISSUE THREAD

**Issue by claytonduran** [ZeusAutomacao/DFe.NET#1338]
Boa Tarde Pessoal 

Estou utilizando método de inutilização da NFe e esta dando este erro "System.Security.Cryptography.CryptographicException: 'Malformed reference element.'" , parece algo errado na assinatura ou certificado porem as demais  métodos esta funcionando normal, algum sugestão?

Obrigado novamente

**Comment by claytonduran** [comment]
Boa Tarde Pessoal

Estou utilizando método de inutilização da NFe e esta dando este erro "System.Security.Cryptography.CryptographicException: 'Malformed reference element.'" , parece algo errado na assinatura ou certificado porem as demais métodos esta funcionando normal, algum sugestão?

Obrigado novamente

**Comment by danilobreda** [comment]
Ainda está acontecendo o problema? Posta mais detalhes de código como você esta fazendo o processo de inutilizacao e configuracao do seu ambiente... Como é seu sistema se é web ou desktop, qual framework voce esta utilizando. Está usando nuget e/ou a ultima versão do Zeus?  
Fico no aguardo.
