### ISSUE TITLE
Retorno método Sincrono

### ISSUE THREAD

**Issue by gubarusco** [ZeusAutomacao/DFe.NET#134]
Boa tarde a todos!

Nós optamos por tratar a Autorização em modo síncrono, mas o retorno do servicoNFe.NFeAutorizacao traz o tipo retEnviNFe, que tem apenas a tag infRec (do modo assíncrono), não mapeando a tag protNFe (retornada no modo síncrono).

Eu até tentei fazer a conversão utilizando a classe retConReciNFe (retConsReciNFe().CarregarDeXmlString(retorno.RetornoCompletoStr), mas ele não consegue que a tag inicial do xml é diferente.

Alguém mais trabalha com o modo síncrono teve esse problema? Alguma dica?
Não queria reescrever uma classe para leitura do retorno completo.

Abraços,
Gustavo

**Comment by marciojmuller** [comment]
Olá!
fiz as seguintes modificações:

na classe NFe.Classes.Servicos.Recepcao.retEnviNFe adicionei no final:
        /// <summary>


        ///     ER08 - Protocolo de autorização ou denegação de uso da NF-e (vide item 4.2.2).
        ///     Informar se localizado  uma NF-e com cStat = 100 (uso autorizado) ou 110 (uso denegado).
        /// </summary>


        public protNFe protNFe { get; set; }

Podendo agora fazer o seguinte:
var retornoEnvio = this._servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { _NFe });

agora todo o protNFe está disponível:
retornoEnvio.Retorno.protNFe.infProt.cStat
.........

Abraços.
Márcio Müller

**Comment by gubarusco** [comment]
Como solução de contorno eu fiz isso também aqui.
Mas como estou usando apenas as dlls do projeto e não ter certeza se o que poderia impactar no restante das classes, eu criei uma nova classe no meu projeto.

Obrigado pelo retorno.

**Comment by adeniltonbs** [comment]
@marciojmuller Poderia fazer um pull request com essas alterações?
