### ISSUE TITLE
Novos Campos NT 2021.004

### ISSUE THREAD

**Issue by thiagocleite** [ZeusAutomacao/DFe.NET#1343]
Bom dia pessoal.

Recebi a noticia que o governo lançou uma nova nota técnica com adição de novos campos e regras de validação.
Dei uma olhada no projeto e não encontrei nenhum destes novos campos. Ex: (campo tpAto e grupo ObsItem)
Gostaria de saber se existe demanda pra atender estas mudanças ou se já foi feito e acabou que eu não estou localizando esses campos no projeto do Zeus.

Desde já agradeço.
Parabéns a equipe pelo projeto.

**Comment by marcosgerene** [comment]
@thiagocleite o projeto é amplamente utilizado, então, toda NT é implementada em algum momento.

Se você tem a necessidade dessa implementação com urgência e quiser fazer o PR, eu faço a análise e aceite.

**Comment by marcosgerene** [comment]
@danilobreda @robertorp eu faço.

**Comment by marcosgerene** [comment]
@thiagocleite 

Fiz a implementação. Por questões de QA não vou aceitar meu próprio PR.

Basta aguardar o @danilobreda ou @robertorp fazer aceite.

**Comment by thiagocleite** [comment]
Bom dia pessoal. 
Gostaria de solicitar se possível a inclusão da atualização do pacote nuget para que eu possa receber o novo codigo.
