### ISSUE TITLE
Consumo indevido

### ISSUE THREAD

**Issue by lisodecker** [ZeusAutomacao/DFe.NET#1349]
Estamos fazendo a consulta e recebendo consumo indevido. Não temos outros sistemas fazendo consultas. Enviamos NSU zerada e sempre retorna consumo indevido, mesmo aguardando 1h.
Estamos fazendo os testes diretamente pela aplicação Zeus, informando CNPJ, último NSU informando branco e Chave informado branco.

cStat 656
Rejeicao: Consumo Indevido (Deve ser aguardado 1 hora para efetuar nova solicitacao caso nao existam mais documentos a serem pesquisados. Tente apos 1 hora)

O que poderia ser? E qual a lógica que deve ser usada para fazer a implantação em novos clientes? 

Grato

**Comment by marcosgerene** [comment]
@lisodecker 

> Enviamos NSU zerada e sempre retorna consumo indevido, mesmo aguardando 1h.

Está aqui seu problema.

Você não pode buscar um NSU menor que o ultimo NSU retornado por eles, se buscar vai tomar consumo indevido, eu tive esse mesmo problema.

**Comment by lisodecker** [comment]
@marcosgerene 

já tentei informar e também ocorre.

por exemplo, acabei de fazer a consulta, informando CNPJ e ultNSU 3687
e me retornou a mensagem abaixo.

_**cStat: 656, xMotivo: Rejeicao: Consumo Indevido (Deve ser aguardado 1 hora para efetuar nova solicitacao caso nao existam mais documentos a serem pesquisados. Tente apos 1 hora), ultNSU: 3687**_

mas o que não entendi, é que com um outro cliente, já conseguimos trazer os ultimos 90 dias de nfe e eventos, tudo de uma vez, informando NSU zero.

confesso que estou perdido nessa lógica. tentamos de tudo já

**Comment by marcosgerene** [comment]
@lisodecker 

Você consegue trazer os ultimos 90 dias passando zero desde que seja a primeira vez, se tentar passar zero de novo no cliente que funciona vai ter a mesma experiência.

**Comment by lisodecker** [comment]
@marcosgerene 

se baixei tudo até hoje, digamos ultimo NSU foi 1000. se daqui a 3 dias eu fazer uma nova consulta (sem ter feito nenhuma nesse periodo), eu deveria enviar a consulta informando NSU 1000, certo?

eu tenho feito isso, porém tem retorna consumo indevido, avisando que ultimo NSU é 1200 (digamos)

**Comment by marcosgerene** [comment]
@lisodecker 

Então temos duas opções:
1. Outro agente consumindo.
2. Problemas na sefaz

**Comment by danilobreda** [comment]
Fechando issue por falta de retorno. Caso ainda estiver com o problema comente aqui. :)

**Comment by danilobreda** [comment]
- consNSU: consulta de uma nota fiscal específica através do NSU;
- consChNFe: consulta de uma nota fiscal específica através da sua chave de acesso;
- distNSU: consulta de um lote de notas a partir de um NSU específico.

Observação: Em quaisquer dos três tipos de consulta, quando o usuário receber a mensagem 656 – consumo indevido, deve aguardar 1hora. Se retomar a consulta antes de completar 1 (uma) hora, o tempo é zerado e a contagem reiniciará até completar 1hora.
