### ISSUE TITLE
Serviço RecepcaoEvento - AM

### ISSUE THREAD

**Issue by obogoni** [ZeusAutomacao/DFe.NET#135]
Olá 

Estava tendo problemas para utilizar o serviço RecepcaoEvento (NFC-e) do estado do Amazonas, verifiquei que na classe Enderecador o serviço estava configurado com a versão 3.10, troquei para 1.00 e funcionou perfeitamente. Se puder corrigir, agradeço desde já.

Abraços!

**Comment by brunominervino** [comment]
@OtavioBogoni Abre um pull request assim o @adeniltonbs analisa e aprova.
