### ISSUE TITLE
Implementação de Web Service de consulta pública do GTIN

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1353]
[Nota Técnica 2022.001 - v.1.00 - Publicada em 31/05/2022](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=WpIPyTpmMsM=)
Divulga especificação do Web Service de consulta pública do GTIN.

Agradecemos quem estiver disponível para contribuir.

**Comment by robertorp** [comment]
Iniciando isso agora...

**Comment by robertorp** [comment]
Recurso Adicionado: https://github.com/ZeusAutomacao/DFe.NET/commit/23bb515ffb39e6989aada0904421f909e52e5a78

**Comment by danilobreda** [comment]
@robertorp Parabéns pela implementação :)
