### ISSUE TITLE
Impressão Dacte e Danfe - padronização variável "Report"

### ISSUE THREAD

**Issue by EttorePaludeto** [ZeusAutomacao/DFe.NET#1359]
Fala ae galera, tudo bem com vcs?

No projeto do Dacte, a variável "Report" do pacote fastReport está como "_protected_".  No projeto Danfe é "_public_".

Gostaria de saber se pensam em tornar ambas "_public_".

Na minha aplicação, para o DANFE, consigo acessar a variável "relatório" e atribuir um "_MDIParent_" para o formulário de abertura. Já do DACTE não tenho o acesso a variável. Logo, fico restrito ao método "_Visualizar_()" que não contém esse implementação.

Novamente, parabéns pelo trabalho de vocês! É top demais esse projeto.

![image](https://user-images.githubusercontent.com/38463108/177616109-884d6e5c-5979-44a1-815a-47df77f479a5.png)

![image](https://user-images.githubusercontent.com/38463108/177617298-ecd74476-7f76-4233-b608-9b5f018e3376.png)

**Comment by danilobreda** [comment]
@EttorePaludeto Caso deseja fazer o pullrequest irei analisar e aceitar, a ideia é valida sim :)

**Comment by danilobreda** [comment]
Implementado :) Qualquer coisa estamos aqui
