### ISSUE TITLE
QrCode Sp

### ISSUE THREAD

**Issue by edenilsonbila** [ZeusAutomacao/DFe.NET#136]
Boa tarde, quando gera a tag InfSupl com o QrCode da esse erro na validação
SP
The 'http://www.portalfiscal.inf.br/nfe:qrCode' element is invalid - The value 'https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx?chNFe=35160521366504000108550010000000011000012341&nVersao=100&tpAmb=2&cDest=99999999000191&dhEmi=323031362d30352d32305431353a34353a34362d30333a3030&vNF=4.50&vICMS=0.00&digVal=473837596d4e546a486c744844496c41444c4e734e5535323462493d&cIdToken=&cHashQRCode=d844b6657220db066d7db1e75b002c7af9439f9b' is invalid according to its datatype 'String' - The Pattern constraint failed.

Pesquisei e não achei nada relativo, 

Se eu colo Url no navegador ele me retorna:

Modelo constante da Chave de Acesso do QR Code difere de 65 (NFC-e)

**Comment by orochasamuel** [comment]
@edenilsonbila essa chave de acesso está com modelo 55 (NF-e).

**Comment by adeniltonbs** [comment]
Está faltando o valor de cIdToken não?
