### ISSUE TITLE
Homologação NFe MT - O serviço NfeDistDFeInteresse

### ISSUE THREAD

**Issue by CleydersonPereira** [ZeusAutomacao/DFe.NET#1360]
Estou utilizando Zeus Automação, e ao realizar a consulta NfeDistDFeInteresse está retornando o seguinte erro a baixo :
'Type 'http://www.portalfiscal.inf.br/nfe:TVerDistDFe' is not declared, or is not a simple type.'

estou usando o schema distDFeInt_v1.01.xsd
Alguem sabe se ouve alguma alteração desse schema? ou uma forma de solucionar esse problema?

Verifiquei também que o ambiente de homologação está desatualizado conforme a publicação:
https://www.nfe.fazenda.gov.br/portal/informe.aspx?ehCTG=false&Informe=3ogS20ezQ/I=&AspxAutoDetectCookieSupport=1

Antigo
> https://hom.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

Novo
> https://hom1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

Desde já agradeço.

**Comment by danilobreda** [comment]
Obrigado pela contribuição :)
