### ISSUE TITLE
Monitorar nota emitida para meu CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [ZeusAutomacao/DFe.NET#1362]
Boa tarde pessoal,

Poderiam me indicar alguma lib/sdk que permita via meu certificado digital que eu monitore as notas fiscais emitidas para o meu CNPJ?

Gostaria de saber quando alguém emitir uma nota fiscal de venda para o meu cnpj. 

Pode ser em outra linguagem, não tem problemas. 

Agradeço desde já qualquer contribuição,

Hermes Alves

**Comment by felixsevero** [comment]
Boa tarde, acredito que o serviço de Distribuição de DFe te atenderia.
Dê uma olhada na documentação oficial da NFe e no AppTeste do Zeus para entender como funciona.
