### ISSUE TITLE
Enum CstPis

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1367]
no enumerator do CstPis  e CstCofins tem dois valores em Hexadecimal esta correto isso?

 [Description("Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação")]
        [XmlEnum("62")]
        pis62 = 62,
        [Description("Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno")]
        [XmlEnum("63")]
        pis63 = 0x3F,
        [Description("Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação")]
        [XmlEnum("64")]
        pis64 = 0x40,
        [Description("Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação")]
        [XmlEnum("65")]
        pis65 = 65,

**Comment by felixsevero** [comment]
O valor está correto, mas não é claro ao analisar o código. O melhor seria usar os valores decimais (63 e 64) e criar um PR.

**Comment by danilobreda** [comment]
O mesmo está no código fonte como "63" e "64", acredito que tenha acontecido algum tipo de conversão ao exercutar o GIT CLONE. Como o código está correto vou fechar a issue
