### ISSUE TITLE
Impossível conectar-se ao servidor remoto

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#137]
Olá, pessoal, desde ontem começou a dar erro erro na emissão das NFCe
Alguém já verificou ou passou por isso, li algumas coisas sobre aplicações bancarias que mudam o acesso e outras coisas de antivirus, firewall, tem algo a ver oque vocês acham ?

**Comment by adeniltonbs** [comment]
Você já tentou acessar a URL do webservice diretamente no navegador?

**Comment by marcosmarchiore** [comment]
![erro nfce](https://cloud.githubusercontent.com/assets/9381885/15637217/095a2002-25ea-11e6-9170-b906303a4bd5.png)
Sim, ele retorna corretamente pelo browser, já no aplicativo de teste quando clico em retornar o status vem esta resposta.

**Comment by adeniltonbs** [comment]
Qual uf?

**Comment by marcosmarchiore** [comment]
PR, anexei a imagem

**Comment by marcosmarchiore** [comment]
Atualizando mais testes que fiz, na imagem acima que postei, observem o seguinte, TimeOut 10000, quando coloco 1000 dá outro erro, "O tempo limite da operação foi atingido", quando mudo de produção para homologação, funciona.
Help de alguém sobre esta situação ?

**Comment by adeniltonbs** [comment]
Como está a situação do serviço nesse momento?
Aqui está funcionando pra mim
![image](https://cloud.githubusercontent.com/assets/6733483/15649115/6161e4be-2645-11e6-87a9-085f8d8ca8d9.png)

**Comment by marcosmarchiore** [comment]
Hoje pela manhã voltou ao normal, instabilidade não mostrada pelo painel deles.
