### ISSUE TITLE
Nfc-e Ceará

### ISSUE THREAD

**Issue by EduardoVazOliveira** [ZeusAutomacao/DFe.NET#1370]
Alguém emite Nfce pelo Dfe.NET para o estado do Ceará? 

Estou tentando emitir gera esse Exception "O servidor remoto retornou um erro: (500) Erro Interno do Servidor.".

Ultima versão Dfe.NET e Schemas atualizados.

**Comment by gubarusco** [comment]
Estou com o mesmo problema. Conferi os schemas e os endereços. Já foi resolvido?

**Comment by marcosgerene** [comment]
Em conversar internas o @robertorp disse que estava tratando disso, vou conferir com ele.

**Comment by robertorp** [comment]
Para uso imediato do Ceará podem usar na hora de instanciar a configuração do Zeus está linha de código 

`ConfiguracaoUrls.FactoryUrl = FactoryUrlCearaMudanca.CriaFactoryUrl();`

Por hora da para usar assim como no código que mandei. 

O motivo da implementação ser assim no inicio é porque o Ceará noticiou que iria mudar as URLs , mas não queria mudar de imediato no Zeus , pois talvez por algum motivo poderiam prolongar ou modificar algo no caminho. 
Ai ficou como algo Opcional a parte. 

Atualmente estou implementando o GTIN a consulta no Zeus, ao terminar irei ajustar isso para não precisar usar essa linha de código para adicionar as urls do Ceará.

**Comment by robertorp** [comment]
eu Utilizo assim no meu código do meu sistema 

```
var zCfg = new ConfiguracaoServico
            {
                cUF = estadoEmitente == Estado.RS && estado != null ? estado.Value : estadoEmitente,
                VersaoLayout = VersaoServico.Versao400,
                TimeOut = _timeOut == null ? 30000 : _timeOut.Milessegundos,
                tpEmis = _tipoEmissao.ToZeus(),
                ModeloDocumento = (ModeloDocumento) _emissor.Modelo,
                Certificado = _emissor.Certificado,
                tpAmb = (TipoAmbiente) _emissor.Ambiente,
                SalvarXmlServicos = true,
                DiretorioSchemas = Path.Combine(assembyPath, "Assets", "Schemas.Nfe"),
                DiretorioSalvarXml = Path.Combine(assembyPath, "XmlServicos"),
                ProtocoloDeSeguranca = _emissor.ProtocoloSeguranca.ToSecurityProtocol(),
                RemoverAcentos = true
            };


            if (!Directory.Exists(zCfg.DiretorioSalvarXml))
            {
                Directory.CreateDirectory(zCfg.DiretorioSalvarXml);
            }

            ConfiguraUrlsCeara(zCfg);
```

```
private static void ConfiguraUrlsCeara(ConfiguracaoServico zCfg)
        {
            if (zCfg.ModeloDocumento == ModeloDocumento.NFe)
            {
                ConfiguracaoUrls.FactoryUrl = FactoryUrlCearaMudanca.CriaFactoryUrl();
            }
        }
```

Na verdade vou até me corrigir, olhando os fontes do meu sistema , basta vocês utilizarem apenas para NFC-e sem esse flag já deve funcionar.  Pois utilizo um flag que altero urls somente quando for NF-e e não NFC-e. 

Se alguém poder me mandar como esta instanciando as configurações do Zeus , posso auxiliar, mas tem que mandar o código da instancia da configuração do Zeus

**Comment by robertorp** [comment]
Estou analisando isso agora. Para NFC-e.

**Comment by EduardoVazOliveira** [comment]
Mesmo colocando o Código:

ConfiguracaoUrls.FactoryUrl = FactoryUrlCearaMudanca.CriaFactoryUrl();

Só retorna esse erro: O servidor remoto retornou um erro: (500) Erro Interno do Servidor.


Oque notei CearaSVRS, não possui as Urls da Nfce do Ceará, apenas da Nfe.

**Comment by robertorp** [comment]
Certo , estou olhando isso já.

**Comment by robertorp** [comment]
![image](https://user-images.githubusercontent.com/10251705/196515154-7e10ee05-2571-4ba3-937a-762d009c4088.png)

Olhando Inicialmente as Urls estão tudo lá, mas não buscou endereço não sei o porque , estou analisando para sanar o problema.

**Comment by EduardoVazOliveira** [comment]
Aqui também está faltando um L:

![image](https://user-images.githubusercontent.com/19534443/196515937-475a780a-0ca5-45ca-b981-a5c624c6d791.png)

**Comment by robertorp** [comment]
Ahhhhhhhhhhhhhhhhh vou chorar heheh. 

Descobri o erro. (bom assim espero, peço por gentileza que faça o teste ai e se possível fazendo o humilde favor, nos dê um feedback) 

![image](https://user-images.githubusercontent.com/10251705/196517147-64f9848c-aa8c-49cd-a677-cb05b03c04c6.png)

Realmente para Versão do qrCode não tem a 1.00 , para falar a verdade não sei nem se existe. Vou procurar para ver se acho algo. 
Precisa Estar como Versão 2.00 no QrCode para NFc-e

**Comment by robertorp** [comment]
> Aqui também está faltando um L:
> 
> ![image](https://user-images.githubusercontent.com/19534443/196515937-475a780a-0ca5-45ca-b981-a5c624c6d791.png)

Irei corrigir essa Url

**Comment by EduardoVazOliveira** [comment]
No meu processo de emissão já passo para Nfce o padrão 2.0 para qrCode.

![image](https://user-images.githubusercontent.com/19534443/196518465-0b7af047-aa30-4cd7-ad83-43486c01cb81.png)

**Comment by robertorp** [comment]
![image](https://user-images.githubusercontent.com/10251705/196519836-6cd42246-087a-4130-8d7a-b9affbfcc635.png)
Olha como está no meu sistema, assim eu estranhei isso inicialmente, pois tenho clientes no Ceará que já utilizam é funciona normalmente.  

Utilize esse mesmo método, que vou verificar esse outro método ai 
ObterUrl

**Comment by robertorp** [comment]
No exemplo do aplicativo teste do zeus está assim e esta funcionando normalmente 
![image](https://user-images.githubusercontent.com/10251705/196520799-0c7360a2-6080-4611-9e67-fb0f283d96b3.png)

**Comment by robertorp** [comment]
utilizando o aplicativo do Zeus 
meu certificado / cnpj é goiás , então por isso da rejeição

![image](https://user-images.githubusercontent.com/10251705/196521771-6393c08e-f6d5-4b32-824b-2733a0f67555.png)

**Comment by EduardoVazOliveira** [comment]
Vou revisar aqui se encontro algo.

**Comment by danilobreda** [comment]
@EduardoVazOliveira ve se todos os arquivos e o nuget que lançamos hoje estao atualizados no seu software. Na maioria das vezes é isso.

**Comment by EduardoVazOliveira** [comment]
Obrigado pela ajuda pessoal, mas encontrei o problema:

Eu estava passando true no compactarMensagem, tenho outros clientes Nfce em vários estados todos eles vão de boa, mas no Ceará gera o erro, mudei para false consegui fazer a emissão.

![image](https://user-images.githubusercontent.com/19534443/196711536-351f736e-a467-4f9e-ad08-49067ccdd255.png)

Obrigado a todos.
