### ISSUE TITLE
NFE Produtos Especificos

### ISSUE THREAD

**Issue by algplau** [ZeusAutomacao/DFe.NET#1371]
Boa noite pessoal,

Desculpem minha falta de experiencia no assunto, mas ja vi que consigo usar os impostos pelas classes ICMSGeral e Basico.
Como faço para usar os produtos especificos ? 

Estou lembro os arquivos XML da NFe para mostrar na tela.

Grato

**Comment by algplau** [comment]
Alguem consegue me ajudar ?  Abraços

**Comment by danilobreda** [comment]
```
var p = new prod();

p.ProdutoEspecifico = new List<ProdutoEspecifico>
                {
                    new comb()
                    {
                        cProdANP = item.AnpCodigo,
                        descANP = item.AnpDescricao,
                        UFCons = item.AnpUfConsumo.ToString()
                    }
                };
```
esse é um exemplo de combustivel, mas ProdutoEspecifico pode ser armamento, medicamento, veículos etc

Recomendo entrar no nosso discord! https://discord.gg/EE4TGKAkkG
