### ISSUE TITLE
Download do XML sem Certificado Digital

### ISSUE THREAD

**Issue by lucasgsf** [ZeusAutomacao/DFe.NET#1372]
Boa tarde, 

Estou precisando apenas do XML da Nota Fiscal. Existe alguma maneira de baixá-lo sem um certificado digital? Caso não seja possível, é possível fazer o download com um certificado que não faça "parte" da NF? (Emitente, Destinatário, Transportador)?

Agredeço desde já! =)

**Comment by danilobreda** [comment]
Infelizmente não, talvez alguem possa te ajudar no grupo nosso do discord: https://discord.gg/EE4TGKAkkG
