### ISSUE TITLE
Erro no retorno do CTe

### ISSUE THREAD

**Issue by EddyLopes** [ZeusAutomacao/DFe.NET#1373]
peguei uma situação em meu sistema que estava faltando a inclusão de alguns CTes fui depurar para ver o que era e verifiquei que os ctes que não estavam entrando tinham a primeira linha diferente dos que funcionavam:

 
![image](https://user-images.githubusercontent.com/36602368/191965242-8f0c0e4c-c6b5-4aae-9822-42fd14fb7742.png)

fonte com o erro: 
projeto: CTe.Servicos, classe: ServicoCTeDistribuicaoDFe

parte com erro:  if (conteudo.StartsWith("<cteProc"))

if (retConsulta.loteDistDFeInt != null)
            {
                for (int i = 0; i < retConsulta.loteDistDFeInt.Length; i++)
                {
                    string conteudo = Compressao.Unzip(retConsulta.loteDistDFeInt[i].XmlNfe);
                    string chCTe = string.Empty;

                    if (conteudo.StartsWith("<cteProc"))
                    {
                        var retConteudo = FuncoesXml.XmlStringParaClasse<CTe.Classes.cteProc>(conteudo);
                        chCTe = retConteudo.protCTe.infProt.chCTe;
                    }
                    else if (conteudo.StartsWith("<procEventoCTe"))
                    {
                        var procEventoNFeConteudo = FuncoesXml.XmlStringParaClasse<Classes.Servicos.DistribuicaoDFe.Schemas.procEventoCTe>(conteudo);
                        chCTe = procEventoNFeConteudo.eventoCTe.infEvento.chCTe;
                    }

                    string[] schema = retConsulta.loteDistDFeInt[i].schema.Split('_');
                    if (chCTe == string.Empty)
                        chCTe = DateTime.Now.ParaDataHoraString() + "_SEMCHAVE";

                    SalvarArquivoXml(chCTe + "-" + schema[0] + ".xml", conteudo, configServico);
                }
            }

**Comment by danilobreda** [comment]
recomendo retirar essa linha usando .Replace(...,""), o xml do sefaz nao vem com ela porem alguns ERPs geram o XML com essa tag inicial, as vezes alguns estados em específicos...
