### ISSUE TITLE
Erro (403) Forbidden ao emitir para BA

### ISSUE THREAD

**Issue by DaniFTT** [ZeusAutomacao/DFe.NET#1374]
## Erro (403) Forbidden ao emitir para BA

Estamos tentando emitir NF-e para o estado da Bahia, tanto em produção quanto em homologação, e estamos recebendo o status 403 Forbidden como retorno. No site da Sefaz não encontrei nenhuma informação sobre isso, sabem o que pode ta acontecendo?

**Comment by ThalisonSantos** [comment]
esse erro geralmente acontece quando o certficado digital está vencido

**Comment by adeniltonbs** [comment]
Bom dia, para conhecimento, alguns de nossos clientes que usam certificados emitidos pela certificadora AC CONSULTI BRASIL RFB,na UF BA estão com esse problema desde a última quinta feira 20/10. Como a certificadora não resolveu até o momento, orientamos os clientes a adquirirem um certificado de outra certificadora e depois tentar resolver o problema com a AC CONSULTI.

![image](https://user-images.githubusercontent.com/6733483/197543968-b575361a-ef9d-419e-92c9-fd77fe6b8dc5.png)
