### ISSUE TITLE
Evento "110150" - Ator Interessado na NF-e

### ISSUE THREAD

**Issue by vanderHobus** [ZeusAutomacao/DFe.NET#1376]
Olá!

O evento "110150" - Ator Interessado na NF-e está disponível na NFe? O qual poderá enviar alteração de Transportadora a qualquer momento de uma NFe aprovada?

Olhando pelo source, localizei apenas a inclusão de 4 schemas, mas nada além disso. De início achei que seria a mesma implementação da manifestação de transporte, mas pelos testes não.

Alguém tem alguma luz?

**Comment by danilobreda** [comment]
Você teria a NT (nota técnica) do evento 110150? Acredito que o mesmo não tenha ainda sido implementado.
Acredito que seja essa nt certo? https://blog.tecnospeed.com.br/nota-tecnica-2020-007-da-nfe/

**Comment by vanderHobus** [comment]
> Você teria a NT (nota técnica) do evento 110150? Acredito que o mesmo não tenha ainda sido implementado. Acredito que seja essa nt certo? https://blog.tecnospeed.com.br/nota-tecnica-2020-007-da-nfe/

Perdão por ter esquecido de informar a NT.
É exatamente essa Danilo!
[NT 2020.007 v.1.21 - Publicada em 01/02/2022](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=I%20zlcbz4WXc=)

Pelo que vi bem por cima (pelo Schema da NT), é um evento bem padrão, que segue a lógica dos demais "NFeRecepcaoEvento4", onde devo informar o CPF/CNPJ da Transportadora com uma frase padrão no "xCondUso".

**Comment by MauricioSuporte** [comment]
Olá,

Agradecemos pela sua sugestão sobre a implementação do evento "Ator Interessado na NF-e - Transportador" conforme a [NT 2020.007](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=I%20zlcbz4WXc%3D).

Informamos que a tarefa para a implementação deste evento foi criada no backlog da Zeus. Assim que tivermos novidades, comunicaremos a todos.

Obrigado!

**Comment by MauricioSuporte** [comment]
Olá a todos,

Agradecemos pelas discussões e sugestões sobre a implementação do evento "110150 - Ator Interessado na NF-e". Gostaríamos de informar que essa feature já foi implementada e mergeada na branch master. Para mais detalhes, você pode consultar o PR relacionado: [#1564](https://github.com/ZeusAutomacao/DFe.NET/pull/1564).

Qualquer dúvida ou sugestão adicional é sempre bem-vinda.

Obrigado!
