### ISSUE TITLE
Problema no método NfeDistDFeInteresse

### ISSUE THREAD

**Issue by higorgoulart** [ZeusAutomacao/DFe.NET#1377]
Ao realizar alguns testes nesse método, me deparei com este erro: "Tipo 'http://www.portalfiscal.inf.br/nfe:TVerDistDFe' é não declarado ou não é um tipo simples." Gostaria de saber se isso é um problema relacionado a forma como eu utilizei ou não está funcionando mesmo.

![imagem_2022-10-26_104753758](https://user-images.githubusercontent.com/109246101/198043416-7aac42ae-1b3b-44aa-b902-1a611ba8c167.png)

Tentei fazer o download das três versões de schema disponíveis no site e o mesmo erro continua.

**Comment by danilobreda** [comment]
Qual .net vocês esta utilizando? A versão do Zeus é a ultima lançada no NUGET?

**Comment by higorgoulart** [comment]
.NETFramework 4.8 e Zeus.Net.NFe.NFCe 2022.10.19.1442.

**Comment by danilobreda** [comment]
Nas configurações tenta desabilitar validação de XML, e verifique se o mesmo acontece... caso não aconteça mais, quer dizer que os schemas XML estão desatualizados...
