### ISSUE TITLE
Homologação NFe - Atualização do endereço do serviço NFeRecepcaoEvento4

### ISSUE THREAD

**Issue by jonathandsantiago** [ZeusAutomacao/DFe.NET#1378]
Em analise verificamos que o endereço do webservice da sefaz de homologação para envio de recepção de evento para manifestação na versão 4, foi alterado para:
Recepção: https://hom1.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx
Recepção Manifesto destinatário: https://hom1.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx

**Comment by robertorp** [comment]
show, vlw ;)
