### ISSUE TITLE
Manifestação Destinatário

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#138]
Ola meu caro, boa tarde
Vc teria algo para realizar a manifestação do destinatário?
grd abs e fique com Deus

**Comment by adeniltonbs** [comment]
Me parece que o @leandrossantos está trabalhando nisso. Veja https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/133

**Comment by leandrossantos** [comment]
Oi @alsantana eu fiz a manifestação de destinatário fora do projeto do @adeniltonbs pois como não tinha ele na época acabei fazendo por minha conta. Agora estou fazendo uma DLL de MDFe que é a manifestação de documentos fiscais eletrônica.

**Comment by alsantana** [comment]
Muito bacana @leandrossantos, quando a DLL estiver pronta vc pode disponibilizar?
Se precisar de ajuda pode falar
grd abs
