### ISSUE TITLE
Consigo emitir nota em homologacao sem certificado digital

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1382]
Boa tarde

Gostaria de saber se Consigo emitir nota em homologacao sem certificado digital?

obrigado

**Comment by guidi** [comment]
Boa tarde, não consegue, o certificado é obrigatório, o que o pessoal geralmente faz é pegar certificado de algum cliente para usar.

**Comment by marcosgerene** [comment]
Não, para comunicação com o webservice o certificado é exigido.

**Comment by PedroCanizela** [comment]
> Boa tarde, não consegue, o certificado é obrigatório, o que o pessoal geralmente faz é pegar certificado de algum cliente para usar.

Muito obrigado

**Comment by PedroCanizela** [comment]
> Não, para comunicação com o webservice o certificado é exigido.

Muito obrigado
