### ISSUE TITLE
Consulta cnpj receita

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1383]
Boa tarde

Alguém conhece alguma dll pra consulta de cnpj na receita?

Eu tinha implementado uma porém agora não está mais funcionando, só retorna erro na leitura do captcha

**Comment by eduprog** [comment]
Uso a https://brasilapi.com.br pata todos estes serviços que ela se propõe e funciona 100%.

**Comment by arvanus** [comment]
https://www.receitaws.com.br/

**Comment by PedroCanizela** [comment]
> Uso a https://brasilapi.com.br pata todos estes serviços que ela se propõe e funciona 100%.

Muito obrigado

**Comment by PedroCanizela** [comment]
> https://www.receitaws.com.br/
> 
> 

Muito obrigado
