### ISSUE TITLE
Erro Na Duplicata 

### ISSUE THREAD

**Issue by JoaoSpagnol** [ZeusAutomacao/DFe.NET#1385]
Boa noite pessoal estou tentando seralizar o xml baixao  e sempre esta me retornando este erro
 O elemento 'dup' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'dVenc' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido.

algun de meus amigos passou por isto 
Segue xml 

<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
	<infNFe versao="4.00">
		<ide>
			<cUF>31</cUF>
			<cNF>4</cNF>
			<natOp>6108 VENDA DE MER ADQ REC D TERC</natOp>
			<mod>55</mod>
			<serie>1</serie>
			<nNF>229523</nNF>
			<dhEmi>2022-12-23T23:25:26+00:00</dhEmi>
			<dhSaiEnt>2022-12-23T23:25:26+00:00</dhSaiEnt>
			<tpNF>1</tpNF>
			<idDest>2</idDest>
			<cMunFG>3170701</cMunFG>
			<tpImp>2</tpImp>
			<tpEmis>1</tpEmis>
			<cDV>0</cDV>
			<tpAmb>2</tpAmb>
			<finNFe>1</finNFe>
			<indFinal>1</indFinal>
			<indPres>9</indPres>
			<indIntermed>0</indIntermed>
			<procEmi>1</procEmi>
			<verProc>7.3</verProc>
		</ide>
		<emit>
			<CNPJ>03945035000191</CNPJ>
			<xNome>Acacia Comercio de Medicamentos Eireli</xNome>
			<xFant>Acacia</xFant>
			<enderEmit>
				<xLgr>Av. Princesa Do Sul</xLgr>
				<nro>3303</nro>
				<xBairro>Jardim Andere</xBairro>
				<cMun>3170701</cMun>
				<xMun>Varginha</xMun>
				<UF>MG</UF>
				<CEP>37062180</CEP>
				<cPais>1058</cPais>
				<xPais>BRASIL</xPais>
			</enderEmit>
			<IE>7070884010016</IE>
			<CRT>3</CRT>
		</emit>
		<dest>
			<CNPJ>01576782000174</CNPJ>
			<xNome>MUNICIPIO DE PRATANIA</xNome>
			<enderDest>
				<xLgr>R FRANCISCO VIEIRA DA MAIA</xLgr>
				<nro>10</nro>
				<xBairro>N H PT1 ANGELIN PASCHOALINOTTE</xBairro>
				<cMun>3541059</cMun>
				<xMun>Pratania</xMun>
				<UF>SP</UF>
				<CEP>18660000</CEP>
				<cPais>1058</cPais>
				<xPais>BRASIL</xPais>
				<fone>001438448200</fone>
			</enderDest>
			<indIEDest>9</indIEDest>
			<email>almoxarifadosaude@pratania.sp.gov.br</email>
		</dest>
		<autXML>
			<CNPJ>86392529000113</CNPJ>
		</autXML>
		<autXML>
			<CNPJ>03659375000156</CNPJ>
		</autXML>
		<det nItem="1">
			<prod>
				<cProd>2933</cProd>
				<cEAN>7898123909446</cEAN>
				<xProd>TRAMADOL 50MG CX 500CPS (A2) (BLT C/10)</xProd>
				<NCM>30039049</NCM>
				<CEST>1300200</CEST>
				<CFOP>6108</CFOP>
				<uCom>CPS</uCom>
				<qCom>2000.0000</qCom>
				<vUnCom>0.0000000000</vUnCom>
				<vProd>468.00</vProd>
				<cEANTrib/>
				<uTrib>CPS</uTrib>
				<qTrib>2000.0000</qTrib>
				<vUnTrib>0.0000000000</vUnTrib>
				<indTot>0</indTot>
				<nItemPed>1</nItemPed>
				<rastro>
					<nLote>1220/22M</nLote>
					<qLote>2000.000</qLote>
					<dFab>2022-10-20</dFab>
					<dVal>2024-09-30</dVal>
				</rastro>
			</prod>
			<imposto>
				<vTotTrib>0.00</vTotTrib>
				<ICMS>
					<ICMS00>
						<orig>0</orig>
						<CST>00</CST>
						<modBC>3</modBC>
						<vBC>468.00</vBC>
						<pICMS>12.0000</pICMS>
						<vICMS>56.16</vICMS>
					</ICMS00>
				</ICMS>
				<PIS>
					<PISNT>
						<CST>04</CST>
					</PISNT>
				</PIS>
				<COFINS>
					<COFINSNT>
						<CST>04</CST>
					</COFINSNT>
				</COFINS>
				<ICMSUFDest>
					<vBCUFDest>468.00</vBCUFDest>
					<vBCFCPUFDest>468.00</vBCFCPUFDest>
					<pFCPUFDest>0.0000</pFCPUFDest>
					<pICMSUFDest>12.0000</pICMSUFDest>
					<pICMSInter>12.00</pICMSInter>
					<pICMSInterPart>100.0000</pICMSInterPart>
					<vFCPUFDest>0.00</vFCPUFDest>
					<vICMSUFDest>0.00</vICMSUFDest>
					<vICMSUFRemet>0.00</vICMSUFRemet>
				</ICMSUFDest>
			</imposto>
		</det>
		<total>
			<ICMSTot>
				<vBC>468.00</vBC>
				<vICMS>56.16</vICMS>
				<vICMSDeson>0.00</vICMSDeson>
				<vFCPUFDest>0.00</vFCPUFDest>
				<vICMSUFDest>0.00</vICMSUFDest>
				<vICMSUFRemet>0.00</vICMSUFRemet>
				<vFCP>0.00</vFCP>
				<vBCST>0.00</vBCST>
				<vST>0.00</vST>
				<vFCPST>0.00</vFCPST>
				<vFCPSTRet>0.00</vFCPSTRet>
				<vProd>468.00</vProd>
				<vFrete>0.00</vFrete>
				<vSeg>0.00</vSeg>
				<vDesc>0.00</vDesc>
				<vII>0.00</vII>
				<vIPI>0.00</vIPI>
				<vIPIDevol>0.00</vIPIDevol>
				<vPIS>0.00</vPIS>
				<vCOFINS>0.00</vCOFINS>
				<vOutro>0.00</vOutro>
				<vNF>468.00</vNF>
				<vTotTrib>0.00</vTotTrib>
			</ICMSTot>
		</total>
		<transp>
			<modFrete>0</modFrete>
			<transporta>
				<CNPJ>86392529000113</CNPJ>
				<xNome>SAL EXPRESS SOLUCOES LOG E TRANSP LTDA</xNome>
				<IE>7077389580047</IE>
				<xEnder>RUA JOSE RIBEIRO BUENO, 1069</xEnder>
				<xMun>VARGINHA</xMun>
				<UF>MG</UF>
			</transporta>
			<vol>
				<qVol>1</qVol>
				<pesoL>0.000</pesoL>
				<pesoB>0.000</pesoB>
			</vol>
		</transp>
		<cobr>
			<dup>
				<nDup>001</nDup>
				<vDup>468.00</vDup>
				<dVenc>2023-01-12</dVenc>
				<dVenc>2023-01-12</dVenc>
			</dup>
		</cobr>
		<pag>
			<detPag>
				<indPag>1</indPag>
				<tPag>15</tPag>
				<vPag>468.00</vPag>
			</detPag>
		</pag>
	</infNFe>
</NFe>

**Comment by marcosgerene** [comment]
@JoaoSpagnol 
Isso que você mandou não é um XML... anexa ele aqui zipado.

Sobre o erro, está sobrando ou faltando preencher algum campo na duplicata, vou te mandar o exemplo de uma NFe minha.

![image](https://user-images.githubusercontent.com/15945003/209556001-b8fcdb8a-b7d6-4acd-bb3d-d457e3aa6a8b.png)


Acredito que você não está preenchendo o nDup, que tem que ser 001,002,003, ... (não pode ser diferente disso).

**Comment by JoaoSpagnol** [comment]
Obrigado amigo @marcosgerene  eu vi qual era meu erro tinha um espaco no final da minha chave <dvenc>
