### ISSUE TITLE
CTe - Evento de Desacordo - Codificação para MT

### ISSUE THREAD

**Issue by LeoDWeber** [ZeusAutomacao/DFe.NET#1386]
Bom dia!

Estou tentando realizar a geração de um evento de desacordo de operação no CTe para o Estado de MT e tenho como devolutiva dele como "402 - Rejeicao : XML da area de dados com codificacao diferente de UTF-8.", pelo que pude verificar inclusive no repositório de fato esse estado é meio problemático com acentuação e neste evento existe a descrição fixa "Prestação do Serviço em Desacordo" em CTe.Classes.Servicos.Evento > evPrestDesacordo.

Notei que existe tratativa semelhante a este problema para a NFe porém nenhuma para CTe ainda no Estado de MT pelo que verifiquei.

Gostaria de saber se alguém implementou algo neste sentido? 
Do contrario ainda estou aprendendo Github mas vou tentar depois enviar um pull request com essa alteração.

**Comment by robertorp** [comment]
entendi, MT tem esse negocio mesmo , quer enviar o pullzinho para nós ?

**Comment by danilobreda** [comment]
@LeoDWeber conseguiu resolver esse problema?

**Comment by danilobreda** [comment]
Aceito e nuget saindo em alguns minutos :)

**Comment by danilobreda** [comment]
@LeoDWeber Obrigado pela contribuição, caso tenha algum problema estamos aqui!
