### ISSUE TITLE
processo de Envio de Nota 

### ISSUE THREAD

**Issue by JoaoSpagnol** [ZeusAutomacao/DFe.NET#1387]
Boa Tarde Qual seria o processo Correto de envio de Varias nfes num lote ? 

estou enviando as notas assinadas e estou reebendo oe erro abixo [Rejeição 215: Falha no schema XML]estou enviando 4 notas no mesmo lote assinadas as mesmas 
Estou tentando Enviar para UF 31 de MG 
Segue retronoStr
<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>14.4.94-MA1</verAplic><cStat>215</cStat><xMotivo>Rejeicao: Falha no esquema XML</xMotivo><cUF>31</cUF><dhRecbto>2023-01-02T17:32:03-03:00</dhRecbto><nRec>0</nRec><tMed>0</tMed></retEnviNFe>
Os Xml vou tentar colocar em anexo 
[Xml_Novos.zip](https://github.com/ZeusAutomacao/DFe.NET/files/10333422/Xml_Novos.zip)
[XMLS.zip](https://github.com/ZeusAutomacao/DFe.NET/files/10333427/XMLS.zip)
 Em Ano Coloquei os Lotes Gerados

**Comment by robertorp** [comment]
Conseguiu solucionar ?
