### ISSUE TITLE
Nuget Danfe

### ISSUE THREAD

**Issue by thiagovalim** [ZeusAutomacao/DFe.NET#1391]
Olá, estou gerando um pacote nuget dos arquivos do danfe .base e danfe.fast para utilizar na minha aplicação, só que estou tendo que copiar os arquivos .frx manualmente para minha aplicação. Existe alguma forma de fazer funcionar os arquivos  .frx direto do nuget? Eu adicionei ao nuget só que não funcionam, continuo precisando copiar manualmente os arquivos.

**Comment by thiagovalim** [comment]
Meu nuget

<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
	<metadata>
	  <id>thiago.NFe.Danfe</id>
	  <version>2023.02.03.2</version>
	  <title>Bredas.Danfe</title>
	  <authors>thiago</authors>
	  <owners>thiago</owners>
	  <description>Biblioteca para geração de Danfe da nf-e e nfc-e.</description>
	  <requireLicenseAcceptance>false</requireLicenseAcceptance>
	  <projectUrl>https://github.com/ZeusAutomacao/DFe.NET</projectUrl>
	  <iconUrl>https://avatars0.githubusercontent.com/u/32456879?s=200&amp;v=4</iconUrl>
	  <releaseNotes></releaseNotes>
	  <copyright>zeus</copyright>
	  <language>pt-BR</language>
	  <tags>nfc-e nf-e nfce nfe</tags>
	</metadata>
  <files>
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe.Danfe.Base.dll" target="lib\net462\NFe.Danfe.Base.dll" />
    <file src="..\DFe.NET\NFe.Danfe.Fast\bin\Release\net462\NFe.Danfe.Fast.dll" target="lib\net462\NFe.Danfe.Fast.dll" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeEvento.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeRetrato.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeSimplificado.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFCe\NFCe.frx" target="lib\net462\NFCe\NFCe.frx" />
  </files>
</package>

**Comment by thiagovalim** [comment]
Meu nuget

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
	<metadata>
	  <id>thiago.NFe.Danfe</id>
	  <version>2023.02.03.2</version>
	  <title>Bredas.Danfe</title>
	  <authors>thiago</authors>
	  <owners>thiago</owners>
	  <description>Biblioteca para geração de Danfe da nf-e e nfc-e.</description>
	  <requireLicenseAcceptance>false</requireLicenseAcceptance>
	  <projectUrl>https://github.com/ZeusAutomacao/DFe.NET</projectUrl>
	  <iconUrl>https://avatars0.githubusercontent.com/u/32456879?s=200&amp;v=4</iconUrl>
	  <releaseNotes></releaseNotes>
	  <copyright>zeus</copyright>
	  <language>pt-BR</language>
	  <tags>nfc-e nf-e nfce nfe</tags>
	</metadata>
  <files>
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe.Danfe.Base.dll" target="lib\net462\NFe.Danfe.Base.dll" />
    <file src="..\DFe.NET\NFe.Danfe.Fast\bin\Release\net462\NFe.Danfe.Fast.dll" target="lib\net462\NFe.Danfe.Fast.dll" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeEvento.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeRetrato.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFe\NFeRetrato.frx" target="lib\net462\NFe\NFeSimplificado.frx" />
    <file src="..\DFe.NET\NFe.Danfe.Base\bin\Release\net462\NFCe\NFCe.frx" target="lib\net462\NFCe\NFCe.frx" />
  </files>
</package>
```

**Comment by robertorp** [comment]
Talvez se você colocar eles dentro do projeto e fazer o load por dentro do projeto do frx , colocar como embbeded resource 
![image](https://user-images.githubusercontent.com/10251705/216589949-b74be1d5-7535-4f96-a145-6e4cc980e02a.png)

é possível fazer, no meu projeto os frx estão dentro do banco de dados no meu caso alguns pois cliente pode modificar é outros que não são modificaveis coloco dentro da dll

**Comment by thiagovalim** [comment]
vou tentar, mas daí provavelmente eu teria que alterar os fontes do componente do danfe para pegar o relatório direto do resource e não do disco, eu gostaria de manter os fontes originais e só gerar o nuget
