### ISSUE TITLE
Duvida Danfe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#1392]
no Danfe fast tem como imprimir no totalizador o valor do Difal?

**Comment by danilobreda** [comment]
O **Difal não se trata de um imposto, e seu cálculo não aparece na nota fiscal (xml)** por isso acredito que nao apareça no DANFE

**Comment by marcosgerene** [comment]
@ThalisonSantos 

Não existe lugar "certo" para se colocar o difal no Danfe no manual, logo fica à critério da SH faze-lo.

Já vi casoss onde coloca-se nas observações do contribuinte essa informação
