### ISSUE TITLE
Please enable REST support in WEB-INF/conf/axis2.xml and WEB-INF/web.xml

### ISSUE THREAD

**Issue by salesjuda** [ZeusAutomacao/DFe.NET#1393]
Olá pessoal, estou tendo esse problema ao tentar acessar o webservice da sefaz AM pelo navegador, já baixei e instalei todos os certificados que encontrei para baixar, instalei na pasta certificadora raiz, mesmo assim quando tento acessar novamente pelo navegador, seleciono o certificado digital e mesmo assim dá o erro. 
![image](https://user-images.githubusercontent.com/34510259/219703840-4ddad95e-8f66-468d-9b26-a24c973c687b.png)

**Comment by danilobreda** [comment]
tente colocar "?wsdl" no final
Não entendi muito o motivo de acessar pelo navegador, poderia nos dizer o porque?

**Comment by danilobreda** [comment]
Conseguiu resolver?

**Comment by salesjuda** [comment]
Olá, perdão a demora. Então, o motivo é testar justamente o webservice da sefaz de AM. geralmente acesso o webservice pelo link https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao4 para ver se vai dar ok ou algum erro.
