### ISSUE TITLE
Erro certificado digital - tipo de provedor invalido

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1394]
Ola, estou tentando emitir nfe com certificado a3 porem ele me tras a mensagem certificado nao encontrado

E quando tento com o a1 arquivo ele me tras a mensagem tipo de provedor invalido

Alguem sabe algo?

Obrigado

**Comment by danilobreda** [comment]
Precisamos de mais detalhes, esses erros não são comuns, alguma coisa com configuração está errado :/

**Comment by PedroCanizela** [comment]
> Precisamos de mais detalhes, esses erros não são comuns, alguma coisa com configuração está errado :/

Quando eu coloco o xml de configuracao do zeus ele gera sem erros, porem nao é valido a assinatura

Sem o xml ele me retorna esse erro

O atributo 'versao' é inválido - O valor '4.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerNFe' - Falha na restrição Pattern. O atributo 'versao' é inválido - O valor '4.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerNFe' - Falha na restrição Pattern. na linha 1 posição 57 em 
[Error] - O elemento 'ide' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'mod' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'indPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. O elemento 'ide' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'mod' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'indPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. na linha 1 posição 182 em 
[Error] - O elemento 'ICMSTot' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'vFCP' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'vBCST' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. O elemento 'ICMSTot' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'vFCP' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'vBCST' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. na linha 1 posição 2638 em 
[Error] - O elemento 'http://www.portalfiscal.inf.br/nfe:vDesc' é inválido - O valor '0.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TDec_1302Opc' - Falha na restrição Pattern. O elemento 'http://www.portalfiscal.inf.br/nfe:vDesc' é inválido - O valor '0.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TDec_1302Opc' - Falha na restrição Pattern. na linha 1 posição 3096 em 
[Error] - O elemento 'pag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'detPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'tPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. O elemento 'pag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'detPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'tPag' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'. na linha 1 posição 3276 em 
'

**Comment by marcosgerene** [comment]
O seu erro não tem ligação com o certificado. 

Seu XML está com dados mal informados/incorretos e os Schemas estão acusando erros. 

Seu XML tem várias falhas, cada um desses "[Error]" é um problema diferente. Se quiser ver de fomar mais clara caso a caso existem alguns validadores online onde você pode jogar seu xml e ir ajustando:

https://validador.nfe.tecnospeed.com.br/

https://www.sefaz.rs.gov.br/nfe/nfe-val.aspx


PS: anexe seu XML aqui caso, pode ser que alguém da comunidade possa te ajudar a apontar as falhas.

**Comment by PedroCanizela** [comment]
Muito obrigado, consegui resolver do certificado.

**Comment by PedroCanizela** [comment]
Era os erros do schema acredito, vou dar uma olhadinha no validador, muito obrigado
