### ISSUE TITLE
Xml retorno autorizado

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1395]
Ola estou tentando retornar o xml de retorno com o protocolo de autorização 

Mas ele somente me retorna um xml que o lote foi recebido com sucesso

Alguém sabe onde consigo o xml de retorno?

Obrigado

**Comment by marcosgerene** [comment]
> Ola estou tentando retornar o xml de retorno com o protocolo de autorização
> 
> Mas ele somente me retorna um xml que o lote foi recebido com sucesso
> 
> Alguém sabe onde consigo o xml de retorno?
> 
> Obrigado

@PedroCanizela você fez o envio de um lote de forma assíncrona. A sefaz vai retornar que o lote foi recebido e o número de protocolo do lote. Você deve consultar o lote com base no número de protocolo para validar o resultado do mesmo (sucesso, falha, motivo da falha, etc).

Exemplo de envio (o que você já está fazendo):
```
ZeusRetornoNFeAutorizacao retornoEnvio = null;

 using (var servicoNfe = new ZeusServicoNFe(ZeusConfiguracaoServico, _certificado))
	retornoEnvio = servicoNfe.NFeAutorizacao(idLote: 1,
						indSinc: nfes.Count == 1 ? ZeusIndicadorSincronizacao.Sincrono : ZeusIndicadorSincronizacao.Assincrono,
						nFes: nfes,
						compactarMensagem: Configuracao.Current.ConfiguracaoDfe.IsDfeCompactado);
```

O retorno, se assíncrono, vai ser um xml com o número do protocolo do lote, como você já viu.

Aqui está o próximo passo a ser dado (consulta do lote). Este código funciona para Sincrono e Assincrono.

```
var protocolos = new List<ZeusProtNFe>();

//Nota fiscal única emitida de forma SINCRONA retorna o protocolo da NFe
if (retornoEnvio?.Retorno?.protNFe != null)
{
	protocolos.Add(retornoEnvio?.Retorno?.protNFe);
}

//Caso não exista o protocolo preciso do número do recibo
else
{
	if (retornoEnvio?.Retorno?.infRec == null || retornoEnvio.Retorno.infRec.nRec.IsNull())
	{
		resposta = "Não foi possível recuperar o número do recibo da emissão";
		throw new Exception(resposta);
	}

	ZeusRetornoNFeRetAutorizacao retornoRecibo = null;

	//consultando o recibo, obtenho a lista de protNFe de todas as notas do lote
	#region Consulta o recibo do envio                
	for (int tentativa = 0; tentativa < maximoTentativasRecibo; tentativa++)
	{
		System.Threading.Thread.Sleep(1000);

        	using (var servicoNfe = new ZeusServicoNFe(ZeusConfiguracaoServico, _certificado))
			retornoRecibo = servicoNfe.NFeRetAutorizacao(retornoEnvio.Retorno.infRec.nRec);

		if (retornoRecibo?.Retorno?.cStat == statusRetornoRecibo)
			break;
	}

	if (retornoRecibo?.Retorno?.protNFe == null)
		throw new Exception("Nenhum protocolo encontrado no recibo da NFe");

	protocolos.AddRange(retornoRecibo.Retorno.protNFe);
	#endregion
}
```

Com isso tenho o retorno de todas as nfes do lote na listagem de protocolos, ai faço o tratamento de cada um deles.

Usings:
```
using ZeusRetornoNFeAutorizacao = NFe.Servicos.Retorno.RetornoNFeAutorizacao;
using ZeusServicoNFe = NFe.Servicos.ServicosNFe;
using ZeusIndicadorSincronizacao = NFe.Classes.Servicos.Tipos.IndicadorSincronizacao;
using ZeusProtNFe = NFe.Classes.Protocolo.protNFe;
using ZeusRetornoNFeRetAutorizacao = NFe.Servicos.Retorno.RetornoNFeRetAutorizacao;
```

**Comment by PedroCanizela** [comment]
Muito obrigado

Só uma duvida, para cada tratamento de nfe em qual classe consigo a nfe com xml protocolado?

**Comment by marcosgerene** [comment]
> Muito obrigado
> 
> Só uma duvida, para cada tratamento de nfe em qual classe consigo a nfe com xml protocolado?

Não entendi a pergunta.

**Comment by PedroCanizela** [comment]
> > Muito obrigado
> 
> > 
> 
> > Só uma duvida, para cada tratamento de nfe em qual classe consigo a nfe com xml protocolado?
> 
> 
> 
> Não entendi a pergunta.

Falo sobre como fazer o download do xml da nfe autorizado, com os dados de autorização e protocolo

**Comment by marcosgerene** [comment]
@PedroCanizela 
 
> Falo sobre como fazer o download do xml da nfe autorizado, com os dados de autorização e protocolo

Entendi, esse download via webservice não existe. 

O que você deve fazer é pegar o objeto NFe que foi criado para o envio e adicionar o protNFe que retornou da autorização. 
A soma do objeto NFe e protNFe é o objeto NfeProc, que é o xml que você está buscando.

Exemplo (continução do exemplo anterior).

```
using ZeusFuncoesXml = DFe.Utils.FuncoesXml;
using ZeusNFeProc = NFe.Classes.nfeProc;

//como visto no exemplo anterior, posso ter mais de um protocolo.
//"procotolos" é um objeto do tipo List<NFe.Classes.Protocolo.protNFe>
foreach (var protocolo in protocolos)
{
    //"nfes" é um objeto do tipo List<NFe.Classes.NFe> que foi preenchido para ser enviado no lote

    var nfe = nfes.Find(nf => nf.infNFe.Id.OnlyNumber() == protocolo.infProt.chNFe.OnlyNumber());

    var proc = new ZeusNFeProc()
    {
        NFe = nfe,
    };

    #region Sucesso
    //Se o resultado foi emitido, marca como sucesso e monta o nfeproc - aqui é o que você está procurando
    if (statusNfeEmitido.Contains(protocolo.infProt.cStat))
    {
        sucesso = true;

        proc.protNFe = protocolo;
        proc.versao = protocolo.versao;
    }
    #endregion


    //para recuperar o xml do procnfe utilize:
    /*
      string xml_nfeproc =  ZeusFuncoesXml.ClasseParaXmlString(proc)
    */
}
```

----

PS:

```
private readonly int[] statusNfeEmitido = { 100, 150 };
```

**Comment by PedroCanizela** [comment]
> @PedroCanizela 
> 
>  
> 
> > Falo sobre como fazer o download do xml da nfe autorizado, com os dados de autorização e protocolo
> 
> 
> 
> Entendi, esse download via webservice não existe. 
> 
> 
> 
> O que você deve fazer é pegar o objeto NFe que foi criado para o envio e adicionar o protNFe que retornou da autorização. 
> 
> A soma do objeto NFe e protNFe é o objeto NfeProc, que é o xml que você está buscando.
> 
> 
> 
> Exemplo (continução do exemplo anterior).
> 
> 
> 
> ```
> 
> using ZeusFuncoesXml = DFe.Utils.FuncoesXml;
> 
> using ZeusNFeProc = NFe.Classes.nfeProc;
> 
> 
> 
> //como visto no exemplo anterior, posso ter mais de um protocolo.
> 
> //"procotolos" é um objeto do tipo List<NFe.Classes.Protocolo.protNFe>
> 
> foreach (var protocolo in protocolos)
> 
> {
> 
>     //"nfes" é um objeto do tipo List<NFe.Classes.NFe> que foi preenchido para ser enviado no lote
> 
> 
> 
>     var nfe = nfes.Find(nf => nf.infNFe.Id.OnlyNumber() == protocolo.infProt.chNFe.OnlyNumber());
> 
> 
> 
>     var proc = new ZeusNFeProc()
> 
>     {
> 
>         NFe = nfe,
> 
>     };
> 
> 
> 
>     #region Sucesso
> 
>     //Se o resultado foi emitido, marca como sucesso e monta o nfeproc - aqui é o que você está procurando
> 
>     if (statusNfeEmitido.Contains(protocolo.infProt.cStat))
> 
>     {
> 
>         sucesso = true;
> 
> 
> 
>         proc.protNFe = protocolo;
> 
>         proc.versao = protocolo.versao;
> 
>     }
> 
>     #endregion
> 
> 
> 
> 
> 
>     //para recuperar o xml do procnfe utilize:
> 
>     /*
> 
>       string xml_nfeproc =  ZeusFuncoesXml.ClasseParaXmlString(proc)
> 
>     */
> 
> }
> 
> ```
> 
> 
> 
> ----
> 
> 
> 
> PS:
> 
> 
> 
> ```
> 
> private readonly int[] statusNfeEmitido = { 100, 150 };
> 
> ```
> 
> 
> 
> 

Muito obrigado
