### ISSUE TITLE
Xml nfe nao aparece cabecalho inicial

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1396]
Ola, estou gerando a nota, certificado esta ok, só alguns erros de validação, mas a nota esta gerando normal.

Porem ela nao gera o xml como é padrao:

Por exemplo ao inves de comecar com

<?xml version="1.0" encoding="UTF-8"?><nfeProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><NFe xmlns="http://www.portalfiscal.inf.br/nfe">

Ela começa com

<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="4.00"

Se alguem souber me ajude por favor

Obrigado

**Comment by danilobreda** [comment]
o xmlproc retornado pela receita federal nao vem com a tag` <?xml version="1.0" encoding="UTF-8"?>`
é só adicionar o <?xml version="1.0" encoding="UTF-8"?> ao retorno.
`var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + x.XmlProc`

**Comment by PedroCanizela** [comment]
> o xmlproc retornado pela receita federal nao vem com a tag` <?xml version="1.0" encoding="UTF-8"?>`
> 
> é só adicionar o <?xml version="1.0" encoding="UTF-8"?> ao retorno.
> 
> `var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + x.XmlProc`

Muito obrigado
