### ISSUE TITLE
Alteração de QRCode e a URL de consulta  - MG dia 24/02/2023

### ISSUE THREAD

**Issue by fabiohcnobre** [ZeusAutomacao/DFe.NET#1397]
A URL de consulta a NFCe via QRCode e a URL de consulta por chave (Portal) foram alteradas em homologação e produção.

A partir de 06/03/2023 só aceitaremos as url's abaixo:

PRODUÇÃO

Nova url de consulta via QRCode: 
https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml

Nova url de consulta via Portal:
https://portalsped.fazenda.mg.gov.br/portalnfce/

 

HOMOLOGAÇÃO

Nova url de consulta via Portal:
https://hportalsped.fazenda.mg.gov.br/portalnfce

Nova url de consulta via QRCode: 

https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml

 

Importante lembrar que as novas urls deverão ser utilizadas tanto no processo de consulta quanto de autorização.

 

24/02/2023

**Comment by duduccosta** [comment]
Acordei com esse problema.
Atualizando meu sistema agora..
Obrigado.

**Comment by fabiohcnobre** [comment]
Isso mesmo ja solicitei um PR para eles atualizar o zeus ainda hoje!

**Comment by marcosgerene** [comment]
PR aceito, acredito que o pacote nuget é automático.
