### ISSUE TITLE
Escrituração EFD

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#14]
Adenilton,

Existe necessidade de implementação da escrituração EFD em software? Como pode ser feita?

Obrigado desde já,
Roberto.

**Comment by adeniltonbs** [comment]
Não entendi o que você quis perguntar, reformule sua pergunta. 
Detalhe: Este projeto trata-se de uma biblioteca para emissão de NFe/NFC-e.

**Comment by robertocvsiqueira** [comment]
Adenilton,

Eu pensei que seria necessário a escrituração EFD na implementação da NFC-e, mas não é o caso. Me desculpe por ter me expressado mal. Vou continuar os testes com a sua biblioteca e te falo.

Obrigado mais uma vez,
Roberto.

**Comment by adeniltonbs** [comment]
Tranquilo, fique a vontade em perguntar. Boa tarde.

Em 8 de abril de 2015 14:50, Roberto Siqueira notifications@github.com
escreveu:

> Adenilton,
> 
> Eu pensei que seria necessário a escrituração EFD na implementação da
> NFC-e, mas não é o caso. Me desculpe por ter me expressado mal. Vou
> continuar os testes com a sua biblioteca e te falo.
> 
> Obrigado mais uma vez,
> Roberto.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/14#issuecomment-90986733
> .

## 

_ADENILTON Batista da Silva_
Fones:(79)3431-6392/3431-8381
Acesse www.zeusautomacao.com.br ou nosso Chat
http://www.zeusautomacao.com.br/suporte/chat.php?code=U0VSVkVSUEFHRQ__
 Online

**Comment by robertocvsiqueira** [comment]
Adenilton, boa tarde, tudo bem?

Acabamos por implementar uma solução de NFC-e de terceiros, por julgar que
o fornecedor de tal solução estava conosco há bastante tempo poderia
prestar um bom serviço como prestou na NF-e, porém essa implementação se
mostrou muito problemática. Estamos vendo para poder remigrar o nosso
código para voltar a usar sua dll e comandar a impressão do DANFe de NFC-e
para método da impressora Daruma, empresa essa que se mostrou de um
profissionalismo ímpar, nos auxiliando a configurar a impressora do cliente
e estamos muito satisfeitos com o trabalho deles.

A tendência é que voltemos a manter contato, e conto com a sua ajuda.

Obrigado e abrs,
Roberto.

Em 8 de abril de 2015 14:51, Zeus Automação Comercial <
notifications@github.com> escreveu:

**Comment by adeniltonbs** [comment]
Blz, qualquer dúvida pode abrir um novo issue em
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues

Em 22 de julho de 2015 12:58, Roberto Siqueira notifications@github.com
escreveu:

> Adenilton, boa tarde, tudo bem?
> 
> Acabamos por implementar uma solução de NFC-e de terceiros, por julgar que
> o fornecedor de tal solução estava conosco há bastante tempo poderia
> prestar um bom serviço como prestou na NF-e, porém essa implementação se
> mostrou muito problemática. Estamos vendo para poder remigrar o nosso
> código para voltar a usar sua dll e comandar a impressão do DANFe de NFC-e
> para método da impressora Daruma, empresa essa que se mostrou de um
> profissionalismo ímpar, nos auxiliando a configurar a impressora do cliente
> e estamos muito satisfeitos com o trabalho deles.
> 
> A tendência é que voltemos a manter contato, e conto com a sua ajuda.
> 
> Obrigado e abrs,
> Roberto.
> 
> Em 8 de abril de 2015 14:51, Zeus Automação Comercial <
> notifications@github.com> escreveu:
> 
> > Tranquilo, fique a vontade em perguntar. Boa tarde.
> > 
> > Em 8 de abril de 2015 14:50, Roberto Siqueira notifications@github.com
> > escreveu:
> > 
> > > Adenilton,
> > > 
> > > Eu pensei que seria necessário a escrituração EFD na implementação da
> > > NFC-e, mas não é o caso. Me desculpe por ter me expressado mal. Vou
> > > continuar os testes com a sua biblioteca e te falo.
> > > 
> > > Obrigado mais uma vez,
> > > Roberto.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/14#issuecomment-90986733
> > 
> > > .
> > 
> > ## 
> > 
> > _ADENILTON Batista da Silva_
> > Fones:(79)3431-6392/3431-8381
> > Acesse www.zeusautomacao.com.br ou nosso Chat
> > http://www.zeusautomacao.com.br/suporte/chat.php?code=U0VSVkVSUEFHRQ__
> > Online
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/14#issuecomment-90987032
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/14#issuecomment-123770136
> .

## 

_ADENILTON Batista da Silva_
Fones:(79)3431-6392/3431-8381
Acesse www.zeusautomacao.com.br ou nosso Chat
http://www.zeusautomacao.com.br/suporte/chat.php?code=U0VSVkVSUEFHRQ__
 Online
