### ISSUE TITLE
SAT NFCe

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1400]
Ola gostaria de saber como transmitir a nfce gerada pelo zeus por meio do sat

**Comment by danilobreda** [comment]
NFCe é algo diferente do SAT.
NFCE é para todo o Brasil, SAT apenas estado de SP e requer um aparelho pequeno ligado no computador.
Para SAT recomendo utilizar a biblioteca  [OpenAC.Net.Sat](https://github.com/OpenAC-Net/OpenAC.Net.Sat)

**Comment by PedroCanizela** [comment]
> NFCe é algo diferente do SAT.
> 
> NFCE é para todo o Brasil, SAT apenas estado de SP e requer um aparelho pequeno ligado no computador.
> 
> Para SAT recomendo utilizar a biblioteca  [OpenAC.Net.Sat](https://github.com/OpenAC-Net/OpenAC.Net.Sat)

Muito obrigado
