### ISSUE TITLE
Registro 0205 da EFD-ICMS/IPI

### ISSUE THREAD

**Issue by EduardoVazOliveira** [ZeusAutomacao/DFe.NET#1401]
Bom dia!

No registo 0205 

```
var reg0205 = new SpedBr.SpedFiscal.Bloco0.Registro0205();
reg0205.DescrAntItem = itemProduto.DescricaoAnterior - "COCO RALADO 250G";
reg0205.DtIni = itemProduto.Data;
reg0205.DtFin = itemProduto.DataFim.Value;
baseArquivo.Add(new BaseArquivoSped("0", reg0205.Reg, 3, baseArquivo.Count(), reg0205.EscreverCampos()));
```
reg0205.EscreverCampos() está retornado = "|0205||14032023|14032023||\r\n"

Não trazendo a descrição do produto, alguém já teve esse problema?

Usando o  reg0205.CodAntItem ele traz no registro normal.

Obrigado

**Comment by adrbarros** [comment]
@EduardoVazOliveira , ola!!!!
Bom creio que o Erro deve estar no Componente que vc usa para gerar o SPED ou no retorno da informação para seu Objeto ItemProduto (que pelo visto acima pode não ser, pois tem contatenação de String e se a DescricaoAnterior estivesse NULL seria disparado uma Exceção), creio que você deve abrir uma Issue no Repositório de onde vc baixou a Biblioteca para gerar o SPED. 
No meu caso eu uso: https://github.com/orochasamuel/fiscalbr-net
E não tenho nenhum tipo de problemas em gerar esse registro ou qualquer outro.

**Comment by orochasamuel** [comment]
Fala @EduardoVazOliveira blz?

Vi que você está usando a versão antiga da lib, antes de se chamar "FiscalBr" era "SpedBr", "SintegraBr", resolvi fazer a unificação em um lugar só.

Qualquer dúvida é só entrar em contato ou postar uma issue direto na página do projeto.

Para novas issues, [clique aqui](https://github.com/orochasamuel/fiscalbr-net/issues).

Vida longa e próspera 🖖

**Comment by danilobreda** [comment]
Acredito que esteja fora do escopo do Zeus, sendo relacionado mais a SPED https://github.com/orochasamuel/fiscalbr-net
Vou fechar a issue.
