### ISSUE TITLE
Transmissao NFCe

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1402]
Ola estou tentando transmitir a nfce para o sefaz mg, porem se coloco a configuração do zeus como NFe, ele transmite normal e me traz o erro de ser NFe ao inves de NFCe

Agora se transmito como NFCe, ele nao retorna, somente diz que esta sem comunicação

**Comment by marcelomera** [comment]
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/

Não sei se foi ajustado no projeto, mas a URL mudou.

**Comment by PedroCanizela** [comment]
> http://www.sped.fazenda.mg.gov.br/spedmg/nfce/
> 
> 
> 
> Não sei se foi ajustado no projeto, mas a URL mudou.

Obrigado

Sabe como posso substituir a antiga por essa url correta que me passou?
