### ISSUE TITLE
NFSe Nacional

### ISSUE THREAD

**Issue by junior176** [ZeusAutomacao/DFe.NET#1403]
Boa tarde,
Vi que está pra sair um projeto da NFSe Nacional.
Existe algum plano de desenvolver isso no Zeus?

Obrigado!

**Comment by marcosgerene** [comment]
Boa tarde,

Para NFS-e uso o projeto do OpenAC https://github.com/OpenAC-Net/OpenAC.Net.NFSe

Acredito que com a implementação o OpenAC implementar aqui também é dividir a comunidade sem necessidade.

**Comment by danilobreda** [comment]
Acredito que se for bem parecido com as implementações de NFe a base já esta pronta. É apenas alguns serviços/endpoint e entidades que referenciam o serviço a mais. Não sei o nível de relação com o SEFAZ, mas se for através deles, faz sentido sim a implementação aqui.

Sobre OpenAC, na minha opinião não será nada parecido com o que a biblioteca já tem...

Acredito que no final das contas vai valer quem for o primeiro a implementar mesmo! :)

**Comment by junior176** [comment]
Pesquisando mais sobre,
Acredito que a emissão deve seguir padrões semelhantes aos da NFe
https://www.gov.br/nfse/pt-br/documentacao-tecnica
Vou acompanhar como a sefaz vai lidar com isso e caso for eu to dentro para ajudar a desenvolver a funcionalidade aqui no zeus.

**Comment by viniciusverasdossantos** [comment]
Vai ser feito nesse projeto?

**Comment by danilobreda** [comment]
Segue projeto do NFSe Nacional:
https://github.com/OpenAC-Net/OpenAC.Net.NFSe.Nacional
