### ISSUE TITLE
Como calcular retencao e st do icms

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1404]
Ola gostaria de saber realizar os calculos de retencao e de st

**Comment by adrbarros** [comment]
Olá, creio que essa solução pode te ajudar: https://github.com/AutomacaoNet/MotorTributarioNet

Aconselho trocar uma idéia com algum Contador, para outras dúvidas referente a Cálculos de Tributação

**Comment by danilobreda** [comment]
@PedroCanizela o Zeus não efetua calculo de imposto, recomendo o canal do [discord ](https://discord.gg/EE4TGKAkkG)ou mesmo tirar dúvidas no projeto motortribuitarionet. Mas o mais recomendado é ajuda de um contador mesmo! Vou fechar a issue por enquanto.
