### ISSUE TITLE
Alterações da NT2023.001

### ISSUE THREAD

**Issue by willian0608** [ZeusAutomacao/DFe.NET#1405]
Boa tarde.

Como esta o suporte do Zeus para a referida NT?

A NT 2023.001 entra em vigor dia 30/03/2023 e pelo que vi, trás novos schemas, novos campos especificos para combustivel e principalmente novos CST, em especial o CST61.

**Comment by fabiohcnobre** [comment]
Pois eh não tem nada 
[Nota Técnica 2023.001 - v1.10 - Publicada em 10/03/2023](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=ZD9Zq9iCs8w=)
https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=ZD9Zq9iCs8w=

**Comment by danilobreda** [comment]
O Zeus é um projeto OpenSource ou seja, **é necessário a contribuição de todos para que ele fique cada vezes mais completo**. Problema urgentes são levados bem mais em conta por afetar a maioria das software houses, infelizmente essa NT é apenas sobre um nicho se não me engano, **venda de combustível.** 
Acredito que a maioria das pessoas que mais contribuem hoje no Zeus não vão ser afetados por essa NT, por isso não foi feito até agora nenhuma mudança.

Caso algum de vocês sejam afetados, fica aqui meu pedido de implementar a NT no Zeus e enviar para a gente via pullrequest, que será aceito, ajudando a todos!

**Comment by willian0608** [comment]
Sim, achei melhor perguntar pois o Zeus tem muitos forks, daqui a pouco já tem tb alguem trabalhando nisso. Mas caso alguem não se pronuncie vou estudar aqui e fazer o pull,

**Comment by danilobreda** [comment]
Não recomendo utilizar forks de terceiros, eu mesmo tenho um fork que utilizo na minha empresa para testes antes de enviar para o Zeus em si. Hoje o lançamento de um nuget do zeus acontece em minutos, inovamos bastante para entregar o mais rápido possível mudanças, pois todos nós entendemos que do outro lado tem o cliente que sempre está em apuros também 👍

**Comment by willian0608** [comment]
pr #1407

**Comment by danilobreda** [comment]
Nuget Lançado :)
Vou fechar a issue, qualquer coisa só abrir uma nova ou comentar nessa que reabro!
Obrigado pela contribuição :)
