### ISSUE TITLE
[Dúvida] Notas Destinadas

### ISSUE THREAD

**Issue by MatheusOliveira-dev** [ZeusAutomacao/DFe.NET#1406]
Olá, pessoal. Como vocês estão?

Dúvida besta de iniciante, mas qualquer orientação seria de grande auxílio.

Usando o método `NfeDistDFeInteresse` eu consigo obter o resumo das NF-e's emitidas contra o CNPJ do cliente. Tudo certo nessa parte. Utilizando o `UltNSU` certinho.

A dúvida é a seguinte:

Quando eu manifesto essas NF-e's resumidas, o Sefaz retornará ela completa em algum outro NSU maior, qual eu posso consultar nesse mesmo método `NfeDistDFeInteresse`?

Ou deve ser chamado algum outro método complementar apenas para visualizar a NF-e completa, com base na chave ou outro tipo de informação?

Dei uma olhada aqui: https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636 e consegui uma boa base de conhecimento (obrigado, marcosgerene). No entanto não sanou a dúvida por completo mencionada acima. 

Eu agradeço desde já a atenção de todos e peço desculpa pela dúvida de iniciante.

**Comment by felixsevero** [comment]
Bom dia, acho que já lhe respondi no Discord, mas vou adicionar a resposta aqui também.

Após você manifestar, o XML completo será retornado em algum momento futuro em outro NSU.
Você pode consultar pela chave de acesso caso não queira esperar, mas como não utilizo esse método não saberia dizer se o XML costuma estar disponível de imediato (acredito que mesmo que isso aconteça, não é uma garantia).

**Comment by MatheusOliveira-dev** [comment]
> Bom dia, acho que já lhe respondi no Discord, mas vou adicionar a resposta aqui também.
> 
> Após você manifestar, o XML completo será retornado em algum momento futuro em outro NSU. Você pode consultar pela chave de acesso caso não queira esperar, mas como não utilizo esse método não saberia dizer se o XML costuma estar disponível de imediato (acredito que mesmo que isso aconteça, não é uma garantia).

Muito obrigado pela retorno, foi de grande ajuda!
