### ISSUE TITLE
Projeto em asp.net

### ISSUE THREAD

**Issue by homerokzam** [ZeusAutomacao/DFe.NET#141]
Você ou alguém possui um projeto em asp.net utilizando esta biblioteca?

Parabéns adeniltonbs!

Obrigado.

**Comment by adeniltonbs** [comment]
Veja esse issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/95

**Comment by malkafly** [comment]
Eu comecei essa semana a implementar em asp.net MVC 4, quando tiver mais perto do redondinho, subirei no meu git como exemplo, e até pra deixar aberto a melhorias :D  mas @homerokzam funciona sim!

**Comment by adeniltonbs** [comment]
👍

**Comment by leandrossantos** [comment]
Bom dia, aproveitando esse issues, sabem me dizer se consigo usar o mesmo relatório do FastReports da NFCe na aplicação WEB ??

**Comment by adeniltonbs** [comment]
Acredito que sim, olhe a descrição do fastreports.net em https://www.fast-report.com/pt/product/fast-report-net/

**Comment by homerokzam** [comment]
Valeu @Malkafly !

Se eu puder ajudar! Estou tentando fazer funcionar também.

**Comment by leandrossantos** [comment]
Sim @adeniltonbs já havia visto isso, só perguntei pq vai que alguém alguém já fez esse procedimento. Pq surgiu a necessidade aqui de colocar a impressão numa aplicação WEB.

**Comment by leandrossantos** [comment]
@Malkafly como esta sua aplicação web com a biblioteca de NFe? Tem como disponibilizar um exemplo de como esta usando? E a impressão como esta fazendo?
