### ISSUE TITLE
Sistema Sincrono Estado de Sao Paulo

### ISSUE THREAD

**Issue by joaospagno2023** [ZeusAutomacao/DFe.NET#1411]
Boa noite  pessoal , estou enviando nota fiscal em modo homologação em moso sincrino porem quando facp esta requisição ele me retorna o numero de recibo para consulta lote , isto é normal acontecer isto , fiz o teste pelo sistema da zeus aqui mesmo do projeto e o mesmo erro aconteceu , exite alguma configuração que tenho que  fazer:
Obrigado

**Comment by robertorp** [comment]
Boa noite, se entendi bem você quer enviar em modo sincrono uma nf-e , isso ? Tenta esse parâmetro (coloca Sincrono)
![image](https://user-images.githubusercontent.com/10251705/235394198-5536b56e-6182-44a5-82fa-2113ae0ac1a8.png)

**Comment by joaospagno2023** [comment]
Olá amigo mesmo eu usando este método ele me retorna o recebido  para
consulta

Em dom., 30 de abr. de 2023 23:44, Roberto Alves Pereira <
***@***.***> escreveu:

**Comment by robertorp** [comment]
Boa tarde, copia o retorno para min cola ele aqui o xml

**Comment by joaospagno2023** [comment]
Olá amigo roberto estou usando mesmo exemplo do site vou colocar aqui já já
como eu fiz eu gerei e assinei o XML no Zeus e transmite pelo Zeus

Em seg., 1 de mai. de 2023 15:14, Roberto Alves Pereira <
***@***.***> escreveu:

> Boa tarde, copia o retorno para min cola ele aqui o xml
>

**Comment by robertorp** [comment]
Conseguiu ? Mas adiantando , quando é sincrono ele retorna o protocolo também no xml de retorno. 
Fico no aguardo ;)

**Comment by joaospagno2023** [comment]
Boa noite @robertorp  segue retorno para o estado de sp em modo sincrono 

<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><cStat>103</cStat><xMotivo>Lote recebido com sucesso</xMotivo><cUF>35</cUF><dhRecbto>2023-05-01T22:50:22-03:00</dhRecbto><infRec><nRec>351000174128278</nRec><tMed>1</tMed></infRec></retEnviNFe>

estou usando o metodo 
NFeAutorizacao e ele para sao paulo me retono o lote a ser consultado , uma pergunta e metodo sincrono nao deveria me retonar a nota fiscal ja com seu status

**Comment by leandrovip** [comment]
O modo síncrono não está disponível para os estados **SP, GO, BA**

_Obs: Só se isso foi alterado e não fiquei sabendo._

**Comment by joaospagno2023** [comment]
bom dia @leandrovip  vc tem esta doc que fala isto ?

**Comment by leandrovip** [comment]
> bom dia @leandrovip vc tem esta doc que fala isto ?

Da documentação oficial, não tenho. Mas em uma pesquisa simples no google se acha diversos foruns, como o do ACBr abaixo:

https://www.projetoacbr.com.br/forum/topic/57375-modo-de-envio-ass%C3%ADncrono-e-s%C3%ADncrono-por-modelo-df-e

**Comment by haroflow** [comment]
Só para complementar...

Há alguns dias (18/05) fiz testes do `IndicadorSincronizacao` para os estados de SP, GO e BA, em Homologação. Segue o resultado:

- BA = Mando Síncrono ele rejeita. Mando Assíncrono retorna Assíncrono.
- GO = Mando Síncrono retorna Síncrono. Mando Assíncrono retorna Assíncrono.
- SP = Mando Síncrono retorna Assíncrono. Mando Assíncrono retorna Assíncrono.

**Comment by danilobreda** [comment]
Acredito que foi resolvido que é um problema do estado aonde a nota está sendo enviada, e nao um bug do zeus, por isso vou fechar a issue, qualquer coisa estamos aqui!
