### ISSUE TITLE
Emissão NFe ERRO CST 500 de ICMS do simples nacional

### ISSUE THREAD

**Issue by claytonduran** [ZeusAutomacao/DFe.NET#1412]
Ao emitir uma NFe com CST 500 de ICMS do Simples Nacional esta me retornando um erro conforme abaixo:
0 - Erros na validação: Ocorreu o seguinte erro durante a validação XML: [Error] - The element 'ICMSSN500' in namespace 'http://www.portalfiscal.inf.br/nfe' has invalid child element 'pRedBCEfet' in namespace 'http://www.portalfiscal.inf.br/nfe'. List of possible elements expected: 'vFCPSTRet' in namespace 'http://www.portalfiscal.inf.br/nfe'. The element 'ICMSSN500' in namespace 'http://www.portalfiscal.inf.br/nfe' has invalid child element 'pRedBCEfet' in namespace 'http://www.portalfiscal.inf.

Pude notar que esta gerando TAGs que nem mesmo estou alimentando seus valores  na classe, porém quando é gerado o XML esta sendo adicionado estas TAGs, abaixo estão XML correto sem TAG e após o XML com TAGs geradas a mais.

Versão Zeus.Net.NFe.NFCe 2022.11.30.1842
Linguagem: C#
Agradeço Apoio para resolução desde erro.

XML Correto:

```
<ICMS>
   <ICMSSN500>
      <orig>0</orig>
      <CSOSN>500</CSOSN>
      <vBCSTRet>0.00</vBCSTRet>
      <pST>0.00</pST>
      <vICMSSubstituto>0.00</vICMSSubstituto>
      <vICMSSTRet>0.00</vICMSSTRet>
    </ICMSSN500>
</ICMS> 
```

XML Gerado errado:

```
<ICMS>
    <ICMSSN500>
          <orig>0</orig>
          <CSOSN>500</CSOSN>
          <vBCSTRet>0.0000</vBCSTRet>
          <pST>0</pST>
          <vICMSSubstituto>0</vICMSSubstituto>
          <vICMSSTRet>0</vICMSSTRet>
          <vBCFCPSTRet>0</vBCFCPSTRet>
          <pFCPSTRet>0</pFCPSTRet>
          <pRedBCEfet>0</pRedBCEfet>
          <vBCEfet>0</vBCEfet>
          <pICMSEfet>0</pICMSEfet>
          <vICMSEfet>0</vICMSEfet>
    </ICMSSN500>
</ICMS>
```

**Comment by adrbarros** [comment]
Exemplo de implementação, para mim aqui está normal. Gerando Corretamente.
Talvez você esteja colocando valores Zerados em Propriedades Nullable, assim, acaba gerando a Tag no Xml

![image](https://user-images.githubusercontent.com/15065213/235915157-4982c3ad-01ab-488a-9aea-a1dc68c04eef.png)

**Comment by claytonduran** [comment]
Perfeito problema resolvido.
Obrigado
