### ISSUE TITLE
Schemas Tcorgaoibge 

### ISSUE THREAD

**Issue by bruno-crr** [ZeusAutomacao/DFe.NET#1417]
Bom dia , será se alguém teria os schemas em produção pra compartilhar, os que eu uso estavam acusando erro ao enviar carta de correção e agora ao manifestar nota, os schemas que estou usando baixei no repositório da receita;

**Comment by danilobreda** [comment]
recomendo nosso discord para esse tipo de dúvida https://discord.gg/EE4TGKAkkG
