### ISSUE TITLE
Alterações na estrutura do ICMS53, NT 2023.001 v1.20

### ISSUE THREAD

**Issue by haroflow** [ZeusAutomacao/DFe.NET#1419]
Olá,

Estava adaptando nosso sistema para leitura das tags de ICMS 02/15/53/61 e notei diferenças entre o layout e o código do ICMS 53... parece que houve mudanças em Abril.

Nota Técnica 2023.001 - v1.20 - Publicada em 11/04/2023
`http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=sBgzpM0849E=`

Arquivo: `NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.ICMS53.cs`

Pelo que entendi:
- Removidos: `qBCMonoDif` e `adRemICMSDif`
- Adicionados: `qBCMono`, `adRemICMS`, `vICMSMonoOp` e `pDif`

Posso ajudar com PR mas precisaria de uma orientação de como são tratadas as remoções de campos.

**Comment by haroflow** [comment]
Uma outra observação... baixei o pacote de liberação dos schemas de 11/04, e lá os campos `qBCMonoDif` e `adRemICMSDif` ainda existem.

Esquema XML NF-e/NFC-e - Pacote de Liberação nº 9k (Novo leiaute da NF-e, NT 2023.001 v.1.20). Publicado em 11/04/2023
`http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=C9Qz1lqk6eo=`

**Comment by marcosgerene** [comment]
@haroflow 

A remoção dos campos provavelmente não será feita, uma vez que precisamos da compatibilidade com outras versões.

Adicionar os novos campos sempre é feito.

Vou tentar ler a NT e implementar no final de semana.

**Comment by marcosgerene** [comment]
Implementado no PR https://github.com/ZeusAutomacao/DFe.NET/pull/1421.

Não vou aceitar meu próprio PR. Adicionei o @danilobreda e o @robertorp como revisores. Se ninguém aceitar até na sexta-feira eu mesmo faço o aceite.
