### ISSUE TITLE
Status do Serviço

### ISSUE THREAD

**Issue by walfrido-oliveira** [ZeusAutomacao/DFe.NET#142]
Antes de mais nada. Parabéns pelo projeto!
Está me retornando um erro: "Tipo inválido especificado". Poderia me ajudar nesse erro?

**Comment by adeniltonbs** [comment]
Poderia nos dar mais detalhes? Onde ocorre o erro? Se for na aplicação de demonstração de uso, como esta está configurada?

**Comment by walfrido-oliveira** [comment]
Olá, conseguir solucionar o problema. O problema estava no certificado. A senha não deveria ser informada, pois trata-se de um certificado A1.

**Comment by adeniltonbs** [comment]
Ok @walfrido-oliveira. No entanto para certificado A1, você deve informar a senha, se desejar informar o arquivo do A1, ao invés de selecioná-lo no repositório do windows.

**Comment by walfrido-oliveira** [comment]
Correto. Muito obrigado!
