### ISSUE TITLE
NT2020.005_v1_21 - Novos Campos: indSomaPISST e indSomaCOFINSST

### ISSUE THREAD

**Issue by fpcpimenta** [ZeusAutomacao/DFe.NET#1428]
Temos essa configuração ou algum jeito de gerar essas TAGs(indSomaPISST e indSomaCOFINSST)?

**Comment by robertorp** [comment]
Poderia passar mais detalhes, onde ficam elas ? 
NT se possível ou se é algo padrão do XML qual pagina do manual de layout ?

**Comment by fpcpimenta** [comment]
NT2020.005_v1_21

**Comment by robertorp** [comment]
Manda o link na nf-e fazenda gov br , por favor tentei achar especificamente essa ai mas não consegui encontrar ela

**Comment by fpcpimenta** [comment]
https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=vcqS7b0oTnU=

**Comment by danilobreda** [comment]
[NT2020.005_v1_21](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=vcqS7b0oTnU=)
https://blog.tecnospeed.com.br/nota-tecnica-2020-005-nfe-nfce/
Os 2 campos não estão no Zeus. Não são campos obrigatórios por isso não foi necessário. Caso alguém tenha interesse em adicionar aceitamos pull request.
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/14843499/98330b13-0511-46bc-b1bd-dd6cd2b3c966)

**Comment by WalissonPires** [comment]
Adicionado no pull  request  #1455
