### ISSUE TITLE
Emissão em contingência

### ISSUE THREAD

**Issue by hbdbim** [ZeusAutomacao/DFe.NET#143]
Primeiramente nem sei como agradecer por disponibilizar a lib, me poupou um tempo imenso, muito obrigado mesmo. Se puder ajudar codificando algo só falar.

A ajuda que gostaria não é referente a lib e sim a regra de emissão, vê se pode me ajudar.

Supondo que estou sem internet e emita uma nota em contingência, qual procedimento que devo adotar para reenviar essa nota para a SEFAZ. Posso simplesmente ler o xml da nota em contingencia e reenviar com o tipo de emissão teOffLine mesmo ou devo fazer algum tipo de tratamento diferente?

Desde já obrigado.

**Comment by adeniltonbs** [comment]
Bom dia hbdbim, dê uma olhada no manual "Manual de Especificações da Contingência Offline para NFC-e - versão 1.2", disponível em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk= e no "Manual de Contingência da NF-e - Versão 1.01", disponível em http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=utnfBbrTewc=.

Posso simplesmente ler o xml da nota em contingencia e reenviar com o tipo de emissão teOffLine mesmo ou devo fazer algum tipo de tratamento diferente?
R: Você deve simplesmente ler o xml da nota em contingencia e reenviar com o tipo de emissão teOffLine.

Só tome cuidado com a NFCe que você tentou transmitir como normal, pois se ela estiver autorizada na SEFAZ e vc alterar os dados dela, depois vai ter rejeição por duplicidade com diferença na chave de acesso. Neste caso acredito que é melhor guardar essa NFCe do jeito que está pra quando cessar os problemas técnicos verificar se ela foi autorizada.
