### ISSUE TITLE
Erro Criptografia CTe e MDFe (Tipo Emissão Contingencia) Net 6.0

### ISSUE THREAD

**Issue by tiagovbp** [ZeusAutomacao/DFe.NET#1430]
Estou implementando tanto CTe como MDFe e ao tentar emitir notas em contingencia (homologação , nao cheguei a testar em produção ainda) apresentou os seguinte erro:

Emissão normal está funcionando normalmente..

O certificado usado é A1Arquivo.

Unable to cast object of type 'System.Security.Cryptography.RSACng' to type 'System.Security.Cryptography.RSACryptoServiceProvider'."

![DLL_1](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/5eccbd75-3d62-4c35-b0a1-b5d55961b9ac)
![DLL_2](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/3ede6a6a-c6ce-4c89-9e66-54b2997b1762)

Se alguem puder me ajudar e se ja teve algum problema do tipo...

**Comment by robertorp** [comment]
Pode passar mais detalhes do seu código ?

**Comment by tiagovbp** [comment]
Quais especificos? ai ja vejo aqui e mando..

**Comment by robertorp** [comment]
Criação da configuração antes de enviar o mdf-e ou o método que esteja usando

**Comment by tiagovbp** [comment]
Segue o da MDFe
![MDFe_Configuracao](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/555fbec1-bffc-4716-b093-7a6c6b6cc9f6)
![MDFe_Envio](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/b936c1f2-668c-408d-ac41-a0c4491f4590)

O erro acontece na MDFeRecepcao.

em MDFe.Classes.Extencoes.ExtMDFe.CreateSignaturePkcs1(X509Certificate2 certificado, Byte[] Value)
   em MDFe.Classes.Extencoes.ExtMDFe.QrCode(MDFe mdfe, X509Certificate2 certificadoDigital, Encoding encoding)
   em MDFe.Servicos.RecepcaoMDFe.ServicoMDFeRecepcao.MDFeRecepcao(Int64 lote, MDFe mdfe)
   em Module.PRSCloud.Core.Features.EmitirMDFeCommandHandler.<Handle>d__9.MoveNext() em C:\Users\tiago\source\repos\PRS-Cloud-Back\Module.PRSCloud.Core\Features\MDFe\EmitirMDFe\EmitirMDFeCommandHandler.cs:linha 571
   em WebApi.Behaviors.RequestValidationHandler`2.<Handle>d__2.MoveNext() em C:\Users\tiago\source\repos\PRS-Cloud-Back\WebApi\Behaviors\RequestValidationHandler.cs:linha 29
   em MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   em MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   em MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   em MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   em MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   em MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
   em Module.PRSCloud.Controllers.MDFeController.<Cadastrar>d__3.MoveNext() em C:\Users\tiago\source\repos\PRS-Cloud-Back\Module.PRSCloud\Controllers\MDFe\MDFeController.cs:linha 46
   em Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
   em System.Threading.Tasks.ValueTask`1.get_Result()
   em System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Awaited|12_0>d.MoveNext()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeNextActionFilterAsync>g__Awaited|10_0>d.MoveNext()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   em Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   em Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeInnerFilterAsync>g__Awaited|13_0>d.MoveNext()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Awaited|17_0>d.MoveNext()
   em Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Awaited|17_0>d.MoveNext()
   em Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext()
   em Application.Middleware.ExceptionMiddleware.<InvokeAsync>d__2.MoveNext() em C:\Users\tiago\source\repos\PRS-Cloud-Back\WebApi\Middleware\ExceptionMiddleware.cs:linha 22

**Comment by tiagovbp** [comment]
Para o CTe

![CTe_Configuracao](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/719a2817-88c9-41e6-b996-699132cbabc3)
![CTe_Envio](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/4bc70e22-3f3e-4012-a9c5-df4c6aa5c3be)

Erro que dá na requisição:
{
  "status": 500,
  "message": "Unable to cast object of type 'System.Security.Cryptography.RSACng' to type 'System.Security.Cryptography.RSACryptoServiceProvider'."

**Comment by tiagovbp** [comment]
para o CTe tipo emissão
   [XmlEnum("5")]
        teFSDA = 5,
e MDFe
        [XmlEnum("2")]
        Contingencia

**Comment by tiagovbp** [comment]
Consegui ajustar..
![alteracaoDLL](https://github.com/ZeusAutomacao/DFe.NET/assets/14102374/8a89cfe0-21da-4fc1-9d84-f1e0b7a16333)
Com essa alteração na primeira instrução, deu certo a emissao.. Algum responsavel poderia atualizar o Master e lançar uma atualização no nuget? 
Tanto para MDFe , como CTe por favor..

**Comment by tiagovbp** [comment]
Bom dia @robertorp  , poderia dar uma olhada nessa questão hoje ?

**Comment by danilobreda** [comment]
@tiagovbp aceitamos seu pull request, para colaborar com a mudança. Faça um fork do projeto, atualiza o codigo fonte com as novas mudanças usando git e depois no github faça um pull request do seu projeto para esse aqui. Ai a gente já analisa.

**Comment by tiagovbp** [comment]
Boa tarde @danilobreda , um amigo meu fez as mudanças tanto para CTe e MDFe, ele também fez uma outra no CTe. Ele está fazendo o pull request no momento..

**Comment by danilobreda** [comment]
@tiagovbp @lucasnc aceitei o pullrequest, parece que a solução se encaixa bem, qualquer coisa caso quebre alguém utilizando versões anteriores do .net (ex: 4.5.2) vou precisar colocar **#if** para na parte do algoritmo alterado de cryptography, mas acredito que por enquanto esta tudo certo.
Vou fechar a issue qualquer coisa só comentar aqui mesmo ou abrir uma nova issue.
Desculpe-nos pela demora com esse problema :/
