### ISSUE TITLE
NfeConsultaProtocolo MG retornando Erro não Catalogado

### ISSUE THREAD

**Issue by DaniFTT** [ZeusAutomacao/DFe.NET#1434]
## NfeConsultaProtocolo MG retornando Erro não Catalogado

Bom dia

Utilizo o serviço de NfeConsultaProtocolo, para o estado de MG, do qual sempre funcionou normalmente, poém recentemente foi emitido um aviso de que haveria mudanças no padrão SOAP: 

A partir do dia 03/07 (segunda-feira), seguindo o manual do contribuinte, não será mais aceito outro padrão diferente do SOAP Versão 1.2. É importante que todos se adequem a esta versão no prazo informado.

E desde então, sempre que tentamos realizar uma NfeConsultaProtocolo, é retornado o erro: 

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/64164438/4f8eac1e-0bd5-4398-b4e7-9dd949bdb373)

Configuramos o serviço da seguinte forma: 

     
```
             var config = new ConfiguracaoServico()
            {
                VersaoLayout = VersaoServico.Versao400,
                VersaoRecepcaoEventoCceCancelamento = VersaoServico.Versao400,
                VersaoRecepcaoEventoEpec = VersaoServico.Versao400,
                VersaoRecepcaoEventoManifestacaoDestinatario = VersaoServico.Versao400,
                VersaoNfeRecepcao = VersaoServico.Versao400,
                VersaoNfeRetRecepcao = VersaoServico.Versao400,
                VersaoNfeConsultaCadastro = VersaoServico.Versao400,
                VersaoNfeInutilizacao = VersaoServico.Versao400,
                VersaoNfeConsultaProtocolo = VersaoServico.Versao400,
                VersaoNfeStatusServico = VersaoServico.Versao400,
                VersaoNFeAutorizacao = VersaoServico.Versao400,
                VersaoNFeRetAutorizacao = VersaoServico.Versao400,
                VersaoNFeDistribuicaoDFe = VersaoServico.Versao400,
                VersaoNfeConsultaDest = VersaoServico.Versao400,
                VersaoNfeDownloadNF = VersaoServico.Versao400,
                VersaoNfceAministracaoCSC = VersaoServico.Versao400,

                ProtocoloDeSeguranca = System.Net.SecurityProtocolType.Tls12,
                DiretorioSchemas = HttpContext.Current.Server.MapPath("~/Services/Schemas"),

                cUF = estado,
                tpEmis = TipoEmissao.teNormal,
                ModeloDocumento = ModeloDocumento.NFe,
                TimeOut = 100000,
                tpAmb = TipoAmbiente.Producao
            };
```

Poderiam me ajudar no que poderia estar acontecendo?

**Comment by mvtaraujo** [comment]
A SEFAZ de MG esses dias está instável. Tem acontecido diversas rejeições desse tipo ou com rejeições que não condizem com o xml. A solução aqui tem sido emitir em contingência. 

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/2230616/dc9c9214-93b0-4214-aade-b224fc3a98b7)


Até amanhã está habilitado.
