### ISSUE TITLE
Nova Reforma Tributária

### ISSUE THREAD

**Issue by DSBRBrasil** [ZeusAutomacao/DFe.NET#1436]
Pessoal!!!
Ja pensaram em criar um comissão para planejar a nova versao do Zeus para atender à nova reforma tributária?
Como TODOS nós precisamos, então toda ajuda seria bem vinda...
Estou a disposição

**Comment by marcosgerene** [comment]
@DSBRBrasil 

Adicionei os commiters que lembro de cabeça aqui, se faltou alguém peço ao @danilobreda @robertorp ou @adeniltonbs adicionarem também.

Entretanto, vale lembrar que o texto ainda pode ser modificado e que sequer o MOC existe ainda.

Uma vez que o MOC existir, não vejo grandes problemas quanto ao Zeus, acredito que os maiores afetados serão os softwares emissores em si com suas regras. Exemplo: minha aplicação faz um inner join em DfeItem e DfeItemIcms, tenho que alterar isso uma vez que o ICMS não será mais obrigatório.

**Comment by DSBRBrasil** [comment]
> @DSBRBrasil
> 
> Adicionei os commiters que lembro de cabeça aqui, se faltou alguém peço ao @danilobreda @robertorp ou @adeniltonbs adicionarem também.
> 
> Entretanto, vale lembrar que o texto ainda pode ser modificado e que sequer o MOC existe ainda.
> 
> Uma vez que o MOC existir, não vejo grandes problemas quanto ao Zeus, acredito que os maiores afetados serão os softwares emissores em si com suas regras. Exemplo: minha aplicação faz um inner join em DfeItem e DfeItemIcms, tenho que alterar isso uma vez que o ICMS não será mais obrigatório.

Bôa, a idéia é formar grupos que possiblitem troca de informações e adequação às novas regras fiscais, de modo a sairmos na frente.

**Comment by MauricioSuporte** [comment]
Olá @DSBRBrasil,

A ideia de formar um grupo para planejar as adequações à nova reforma tributária é excelente e seria extremamente útil para garantir que o Zeus se mantenha atualizado e em conformidade com as novas regras fiscais. No entanto, como mencionado pelo @marcosgerene, o texto da reforma ainda está sujeito a modificações, e o MOC (Manual de Orientação do Contribuinte) ainda não foi publicado, o que limita qualquer planejamento detalhado neste momento.

Estamos atentos às mudanças e, assim que o MOC for disponibilizado, poderemos iniciar o processo de análise e adequação. Acredito que, como sugerido, a maior parte das alterações deverá ocorrer nos emissores e suas regras de negócio, enquanto o Zeus poderá ser ajustado conforme necessário.

A colaboração entre a comunidade será fundamental nesse processo, e estamos abertos a trocas de informações e sugestões assim que tivermos mais clareza sobre as novas exigências. Fique à vontade para participar e contribuir conforme o andamento da reforma!

Abraços!

**Comment by AgnaldoSilva0** [comment]
Olá,

Estarei encerrando esta Issue devido já ter chegado a uma conclusão do assunto proposto.

Agradeço a colaboração de todos os participantes da discussão.
