### ISSUE TITLE
Duvida sobre gerar Danfe em PDF

### ISSUE THREAD

**Issue by CorreaVictor** [ZeusAutomacao/DFe.NET#1438]
Olá, saudações! Estou implementando um método que realiza a geração do PDF da Danfe em byte[] com o OpenFastReport, utilizando o Zeus. Porém ao chegar no método "ExportarPdf", ocorre um exception:

_Segue imagem:_ 
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/139183397/ab27b7d9-3cec-4131-b5c3-6e4e3666b2a5)

Essas são as DLLs que tenha, instaladas com o Nugget: 

_Segue imagem: _
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/139183397/02cf27c4-3861-4437-8230-8a366c0fd2b8)

Estou utilizando para esse projeto o _.NET Core 3.1_

**Comment by robertorp** [comment]
Ele não encontrou a Dll NFe.Danfe.Base , essa dll não tem no nuget , está no projeto

**Comment by CorreaVictor** [comment]
Referenciando a Dll do projeto funcionou, obrigado.
