### ISSUE TITLE
NFe.Danfe.Fast.Skia versão Dlls e frx

### ISSUE THREAD

**Issue by DiegoMDS** [ZeusAutomacao/DFe.NET#1439]
Olá  @danilobreda não estou conseguindo rodar essa versão do Skia no linux, você  poderia verificar por favor se o arquivo FRX e DLL estão corretos?

Em outro ambiente separado que tenho o NET 6 o antigo projeto com a versão  sem ser do Skia está rodando normal.

Desde já obrigado.

**Comment by marcosgerene** [comment]
@DiegoMDS 

Não tenho certeza do que você está tentando fazer, mas você tem as dlls do Fast Skia ai né? O Fast Reports Skia é um componente fechado, diferente do FastReports.OpenSource. Só me confirma se você tem a ferramenta antes da gente dar continuidade.

**Comment by DiegoMDS** [comment]
Olá, @marcosgerene 
Eu uso atualmente a versão licenciada do Fastreports Core para NET 6 rodando no Ubuntu. Dai a Danfe e tudo maís está 100%, desejo atualizar  para o NET 7 e usar a versão Skia porque a versão que tenho não terá mais suporte.

Eu queria saber se essas Dlls do Fastreports Skia são trial ou estão corretas e se os arquivos de designer também? Porque antes de comprar a licença queria fazer testes e ver se está tudo estável quanto a versão do NET 6, mas o primeiro teste que tentei rodar no linux deu alguns erros.

**Comment by marcosgerene** [comment]
@DiegoMDS 

> Eu queria saber se essas Dlls do Fastreports Skia são trial ou estão corretas e se os arquivos de designer também?
As dlls que estão aqui não são do Skia e se forem são trial. Não podemos distribuir aqui as DLLs principais

> Eu uso atualmente a versão licenciada do Fastreports Core para NET 6 rodando no Ubuntu. Dai a Danfe e tudo maís está 100%, desejo atualizar para o NET 7 e usar a versão Skia porque a versão que tenho não terá mais suporte.

Eu uso a versão Skia aqui num docker rodando numa VM Ubuntu em .NET 7. Mas eu tenho pago anualmente pelo FastReports, sempre venho atualizando, não ssei da sua versão. O @danilobreda usa em .NET 7 em Linux também, se não me engano. Vou referenciar ele aqui.

**Comment by danilobreda** [comment]
a DLL que está no fastreport do skia não é a correta, é apenas um exemplo. Você deve utilizar sua dll paga do fastreport na versão skia para funcionar. E sim funciona tranquilamente.

**Comment by danilobreda** [comment]
Segue os pacotes que utilizo sendo o primeiro a versão paga e os outros opensource, no .NET 7 Asp net core,  docker: mcr.microsoft.com/dotnet/aspnet:7.0

        <PackageReference Include="FastReport.Core.Skia" Version="2023.1.8" /> 
        <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2.3" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.3" />

**Comment by DiegoMDS** [comment]
@danilobreda muito obrigado irmão 👏👏
