### ISSUE TITLE
erro rejeição 395

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#144]
Produção: http://nfe.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf

Homologação: http://homolog.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf​

Rejeição 395: Endereço do site da UF da Consulta via QR-Code diverge do previsto

estes são os links , quando clica neles , eles redirecionam para outro link

queria saber se mais alguém ta passando por isso?

Teste com o outro link que eles redirecionam e não funcinou também

**Comment by adeniltonbs** [comment]
Boa tarde @robertorp. Estava verificando o site da SEFAZ de Go (http://www.nfe.go.gov.br/post/ver/152753/projeto-nf-e) e não encontrei os endereços para consulta de QR-Code. 

Mas parece que o problema é no servidor de GO, veja esse post: http://www.projetoacbr.com.br/forum/topic/27667-n%C3%A3o-consigo-emitir-um-nfce-em-goi%C3%A1s/?page=2

**Comment by robertorp** [comment]
estou procurando algo relacionado a isso agora, enviei um email para eles, e eles disseram para estar olhando isso http://www.nfe.go.gov.br/post/ver/211866/como-resolver-o-erro:-server-returned-http-responde-code-415-ou-http-col-error:-415-unsupported-media-type

sabe me informar como seto isso ? não acho o content-type no objeto SoapHttpClientProtocol

edit: os endereços do qrcode eles me enviaram por email

**Comment by robertorp** [comment]
torquei a url de homologação 

no caso acho que tem que colocar a url de produção também 

https: elas estão com http somente.. 
aqui para min funcionou perfeitamente

**Comment by adeniltonbs** [comment]
Ok, vc colocou https ao invés de http nos endereços?
Depois da troca, o QR-Code impresso ficou funcionando?

**Comment by robertorp** [comment]
Sim, agora está emitindo em modo de homologação normalmente.. não testei para produção pois o certificado que tenho aqui e para uso somente de homologação

![danfe](https://cloud.githubusercontent.com/assets/10251705/16150277/9b7b6cd0-346c-11e6-973a-f86bac57c19e.png)

**Comment by adeniltonbs** [comment]
Ok, posso trocar no componente. Mas ainda há um problema. A url desse QR-Code é https://homolog.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf?chNFe=52160621025760000123650010000002221903046272&nVersao=100&tpAmb=2&dhEmi=323031362d30362d31375430393a31343a31392d30333a3030&vNF=0.50&vICMS=0.00&digVal=7a6870444c744f4f4a6c75332b664b4a54436b356e656f6b4368733d&cIdToken=000001&cHashQRCode=c5036dbb6484a37ece756cbdd8d11ee74fb48697. Note que ao tentar acessar a url é exigido um certificado, o que está em desacordo com o objetivo da consulta via QR-Code, onde o consumidor final deveria ter acesso livre à consulta.

Veja um exemplo de uma NFCe em homologação daqui da SEFAZ de SE: http://www.hom.nfe.se.gov.br/portal/consultarNFCe.jsp?chNFe=28160607703290000189650010000006631000000017&nVersao=100&tpAmb=2&dhEmi=323031362d30362d31365431363a31323a33372d30333a3030&vNF=1.00&vICMS=0.00&digVal=496c473353374546494b794447744e36657363575953654d5075303d&cIdToken=000003&cHashQRCode=4f37c3f32fa4a43e9d3d29a7ce2f7fb9e998dc0b

**Comment by adeniltonbs** [comment]
Acredito que o melhor caminho ainda é entrar em contato com a SEFAZ para resolver isso.

**Comment by adeniltonbs** [comment]
QR-Code do link de exemplo que te mandei:
![image](https://cloud.githubusercontent.com/assets/6733483/16150498/e09c835c-346d-11e6-8b76-6c86193f24db.png)

**Comment by robertorp** [comment]
Certo, vou estar entrando em contato com eles e vendo oque acontece. Talvez seja porque o projeto foi lançado em goiás no ultimo dia 14. Porque o componente ta gerando corretamente né

**Comment by adeniltonbs** [comment]
Isso. Você deve perguntar a eles qual url deve ser utilizada para consulta pública via QR-Code.

Se desejar falar com mais propriedade, veja as páginas 31 e 32 do manual Manual de Especificacoes Tecnicas do DANFE NFCeQRCode_Versao3_5 (http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=A3Bd/m6qGPM=). Note que o título do item 5.2 é: "Consulta Pública de NFC-e via QRCode". Então se a consulta é pública, não deveria pedir certificado.

**Comment by robertorp** [comment]
Certo, mandei um email para eles porque esta em contato atraves de email. Se os mesmo não responderem logo, ligo lá.
