### ISSUE TITLE
É possível que saia na Danfe uma tarja/marca d'água quando a nota for cancelada?

### ISSUE THREAD

**Issue by CorreaVictor** [ZeusAutomacao/DFe.NET#1442]
Saudação! Gostaria de saber se consigo configurar a geração da Danfe, NF-e ou NFc-e, para que quando ela já tiver sido cancelada sair uma tarja/marca d'água informado que a nota esta cancelada, (similar ao que acontece quando é homologação).

_Obs.: Ao carregar a configuração, quando a nota está cancelada, já estou informando o campo "DocumentoCancelado" como true._

**Comment by marcosgerene** [comment]
@CorreaVictor Sim, quando você informa DocumentoCancelado como true já sai essa informação, não?

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/15945003/6dbc0a8d-81ce-4ed2-8982-cf7a23cde32d)

Qual versão da impressão você está usando? consegue postar o seu pdf aqui?

**Comment by CorreaVictor** [comment]
Olá, boa tarde! Agradeço o retorno. Está funcionando corretamente. Eu não estava conseguindo somente no ambiente de  homologação, ao realizar a verificação do CSAT, não estava chegando o campo "DocumentoCancelado" nesse método, ajustei o if para verificar se  "DocumentoCancelado" é true e funcionou normalmente.
