### ISSUE TITLE
A Tag <med> não está sendo mapeada dentro de <prod>

### ISSUE THREAD

**Issue by PGama-Rodrigo** [ZeusAutomacao/DFe.NET#1444]
``` 
<prod>
	<cProd>xxx</cProd>
	<cEAN>XXXXXXXXXXXXX</cEAN>
	<xProd>XXXXXXXXXXXXX</xProd>
	<NCM>XXXXXXXX</NCM>
	<CFOP>XXXX</CFOP>
	<uCom>XX</uCom>
	<qCom>21.0000</qCom>
	<vUnCom>20.9914285714</vUnCom>
	<vProd>440.82</vProd>
	<cEANTrib>XXXXXXXXXXXXX</cEANTrib>
	<uTrib>XX</uTrib>
	<qTrib>21.0000</qTrib>
	<vUnTrib>20.9914285714</vUnTrib>
	<indTot>X</indTot>
	<xPed>XXXX</xPed>
	<nItemPed>3</nItemPed>
	<rastro>
		<nLote>XXX/XX</nLote>
		<qLote>21.000</qLote>
		<dFab>2023-05-26</dFab>
		<dVal>2025-05-30</dVal>
	</rastro>
	<med>
		<cProdANVISA>ISENTO</cProdANVISA>
		<xMotivoIsencao>PRODUTO NOTIFICAO SIMPLIFICADA</xMotivoIsencao>
		<vPMC>0.00</vPMC>
	</med>
</prod>
```

Estou com esse Produto no XML do meu cliente, mas eu não consigo acessar os dados da tag <med> dentro da tag <prod>, dentro do objeto `det`;

Está realmente faltando implementar?

**Comment by danilobreda** [comment]
Acredito que o tipo seja a lista de ProdutoEspecifico certo? No caso essa classe é abstrata, no caso vc precisa verificar se o tipo dela implementado é Med ou outra coisa, e ai sim converter 
Med med = produtoEspecifico as Med;

Acredito que vc pode verificar qual o tipo usando typeof() ou .GetType()
