### ISSUE TITLE
Ao criar objeto ICMS90, está atribuindo CST60

### ISSUE THREAD

**Issue by PGama-Rodrigo** [ZeusAutomacao/DFe.NET#1447]
Ao criar um objeto do tipo `NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.ICMS90()` dessa forma:

```
    var icms90 = new NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.ICMS90()
    {
        CST = NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.Tipos.Csticms.Cst90,
        orig = origem,
        modBC = NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.Tipos.DeterminacaoBaseIcms.DbiValorOperacao,
        vBC = item.BaseIcms,
        pRedBC = item.RedBaseIcms,
        pICMS = item.PercIcms,
        vICMS = item.ValorIcms,
        modBCST = NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.Tipos.DeterminacaoBaseIcmsSt.DbisMargemValorAgregado,
        pMVAST = item.MVA,
        pRedBCST = item.RedBaseIcmsST,
        vBCST = item.BaseIcmsST,
        pICMSST = item.PercIcmsST,
        vICMSST = item.ValorIcmsST
    };
``` 

Ao analisar o objeto icms90, o valor no atributo está como `NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.Tipos.Csticms.Cst60`;

Se após isso eu tento atribuir diretamente ao atributo o valor: `icms90.CST = NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.Tipos.Csticms.Cst90`, ele se mantém como Cst60.

Curiosamente, se eu atribuo o valor no QuickWatch, ele fica correto;

Desenvolvendo no Visual Studio 2019 versão 16.11.30, .NET Framework 4.8, e usando a versão do Zeus 2023.7.27.1505

**Comment by danilobreda** [comment]
Verifiquei e não encontrei o bug no código do Zeus.  Possivelmente é algum bug visual do visual studio... ou algo parecido. Caso fosse do código, a gente teria vários usuários reclamando que o ICMS esta errado, o que não procede :/ E consideramos um erro grave.
Mesmo assim obrigado pelo feedback.
