### ISSUE TITLE
Erro ao fazer o build

### ISSUE THREAD

**Issue by lastock** [ZeusAutomacao/DFe.NET#145]
Adenilton, baixei ontem seu código fonte para testar e ao compilar tive um erro no componente de impressão fastreport.

Severity    Code    Description Project File    Line    Suppression State
Error       Metadata file 'C:\Projects\NFe\Zeus.Net.NFe.NFCe-master\Zeus.Net.NFe.NFCe-master\Nfe.Impressao\bin\Debug\NFe.Impressao.dll' could not be found  NFe.AppTeste    C:\Projects\NFe\Zeus.Net.NFe.NFCe-master\Zeus.Net.NFe.NFCe-master\NFe.AppTeste\CSC  
Sabe onde posso encontrar esse assembly?

Obrigado,

Luis Alfredo
lastock@outlook.com.br
skipe: luisstockler
Facebook: Luis Alfredo Stockler Filho

**Comment by adeniltonbs** [comment]
Dê uma olhada nesse issue #102 e nesse aqui #69

**Comment by lastock** [comment]
Obrigado, baixei o aplicativo no site e quase compilou.
Tive que corrigir uma linha de código no arquivo DanfeFrNfce.cs na linha 49
mudei de  
//private readonly Import _relatorio;  
para  
private readonly FastReport.Report _relatorio;
Aí tudo funcionou...

Obrigado.

**Comment by lastock** [comment]
Tem alguma alternativa open source para o FastReport?

**Comment by adeniltonbs** [comment]
Certamente existe. Mas não há implementação em outra ferramenta para o DANFE no momento.
