### ISSUE TITLE
Inutilização de número de NFe pessoa física no Paraná

### ISSUE THREAD

**Issue by D13G0M1R4ND4** [ZeusAutomacao/DFe.NET#1452]
Boa tarde a todos, alguém sabe sobre a possibilidade da inutilização de número de NF emitida por pessoa física no paraná, se isso é possível de implantar ou se já existe essa opção no projeto?

**Comment by danilobreda** [comment]
Já tentou o próprio serviço de inutilização do sefaz? A biblioteca hoje tem implementado.
https://github.com/ZeusAutomacao/DFe.NET/blob/195b5b7c17fc17dd52e74de8f79aea22c15b1515/NFe.Servicos/ServicosNFe.cs#L287C16-L287C39

**Comment by adrbarros** [comment]
Boa tarde, me corrijam se estiver errado, mas, uma NF-e depois de Emitida, você só pode Cancelar a mesma em um determinado prazo, nesse caso a NF-e Emitida não pode ser Inutilizada.

**Comment by danilobreda** [comment]
Correto @adrbarros 
Vou fechar a issue qualquer coisa estamos a disposição.
