### ISSUE TITLE
Remover o FastReport do Projeto

### ISSUE THREAD

**Issue by carloscds** [ZeusAutomacao/DFe.NET#146]
Olá Adenilton,
Como sugestão, acho que você poderia remover o FastReport do Projeto e deixá0lo separado, pois é uma ferramenta paga e existem alternativas gratuitas para imprmir a NFe usando o XML já assinado. posso te ajudar neste processo, se quiser.

**Comment by robertorp** [comment]
Poderia postar uma alternativa já né

Bom venho do java.. conheço o iText ou em c# itextsharp somente uma ideia.. 
não uso o zeus para impressão do pdf porque sofri com problemas quando adicionava um cliente ai ja desisti logo de cara e passei a usar o acbrmonitor para impressões, mas como na empresa aqui estamos começando a adquirir revendedores concerteza iremos fazer impressão em cima do itextsharp e será open source.. mas ainda mais uns meses para iniciarmos.. prioridades a parte.
Se alguém iniciar o desenvolvimento de algo relacionado eu ajudo e so dizer a biblioteca que irá usar e começar a fazer , manda para min e que ajudo.

edit: tem essa também Gios Pdf.NET , enfim todas são na mão mas não exatamente na mão, pois todas tem recursos que já estão implementados ex.. grids que crescem e diminuim de acordo com o tamanho do pdf.. enfim.. sei lá.
Ou o desenho do danfe seria feito somente via string e depois passado para algo? me surgiu isso na mente também.
Bom acho que isso tem que ser pensado em como mandar a impressão para a impressora? Se Gerar um pdf posso mandar ele direto para a impressora? Sem ter que visualizar o mesmo?

**Comment by gubarusco** [comment]
Qual alternativa grátis para impressão da Danfe vc conhece?
Andei pesquisando mas não encontrei nada.

**Comment by leandrossantos** [comment]
Para NFe tem esse https://github.com/SilverCard/DanfeSharp

**Comment by robertorp** [comment]
Esse danfeSharp ja tem muito tempo que não recebe commit.. 
Agora o danfesharp do fork do https://github.com/ViniciusDeus/DanfeSharp/commits/master
recebeu em 2016

**Comment by adeniltonbs** [comment]
Bom dia @carloscds, sua sugestão é boa.
Mas o que o pessoal acha? No core da biblioteca não há dependência da biblioteca NFe.Impressao. Somente na aplicação de demonstração de uso ela é referenciada.

**Comment by lucas-explica** [comment]
Report Viewer não seria uma boa alternativa?

**Comment by carloscds** [comment]
@adeniltonbs Minha sugestão é criar um projeto separado para impressão.

**Comment by adeniltonbs** [comment]
@carloscds Vou remover a referência da bilbioteca NFe.Impressao e fazer uma aplicação de demonstração de uso do recurso de impressão em outra aplicação em uma solução diferente.

**Comment by carloscds** [comment]
@adeniltonbs Excelente!

**Comment by leandrossantos** [comment]
Acredito que para NFCe o que poderíamos ver é estudar uma forma de criar uma rotina de impressão toda na unha, para uma impressão modo texto mesmo, onde as próprias impressoras aceitam códigos para envio de imagens (logomarca) e o código para impressão do QRCode.

**Comment by carloscds** [comment]
@leandrossantos O ideal é fazer impressão gráfica, pois a codificação pode mudar de uma impressora para outra.
