### ISSUE TITLE
obsCont com erro - VERSÃO 2023.11.17.1655

### ISSUE THREAD

**Issue by 27177-Danielson** [ZeusAutomacao/DFe.NET#1461]
'NFe.Classes.Informacoes.Observacoes.obsCont' and 'NFe.Classes.Informacoes.Detalhe.Observacao.obsCont' both use the XML type name, 'obsCont', from namespace 'http://www.portalfiscal.inf.br/nfe'. Use XML attributes to specify a unique XML name and/or namespace for the type.

**Comment by marcosgerene** [comment]
@27177-Danielson 
Provalmente meu PR quebrou isso. 


Meu PR:  https://github.com/ZeusAutomacao/DFe.NET/pull/1460
A issue original: https://github.com/ZeusAutomacao/DFe.NET/issues/1459

**Comment by marcosgerene** [comment]
Estou dando revert no meu commit, fechando essa issue e reabrindo a issue original.
