### ISSUE TITLE
REJEIÇÃO 960 - Grupo de Tributaçao do ICMS monofasica sobre combustiveis

### ISSUE THREAD

**Issue by sigridslima** [ZeusAutomacao/DFe.NET#1463]
Olá, estou precisando de um norte dos amigos, pois esta apresentando a rejeição 960 referente a combustíveis, propriamente dito (GASES LIQUEFEITO DE PETRÓLEO - GLP), nao estou conseguindo parametrizar o ICMS61. Poderiam me ajudar por favor. obrigado

**Comment by sigridslima** [comment]
Ola, não me atentei devido a biblioteca estava desatualizada, porem nao estou conseguindo alterar a tag ICMS:

 ICMS61  

Se tiverem algum sugestao fica agradecido.

**Comment by leandrovip** [comment]
Qual a dúvida em específico? Chegou a ler a NT? 
Anexa o xml de como está preenchendo os campos.

[]´s

**Comment by sigridslima** [comment]
Ola, sim ja li a NT, porem estou com dificuldade em definir o icms61

//metodo
  protected virtual ICMSBasico ObterIcmsBasico(CRT crt)
        {
            var icmsGeral = new ICMS61
            {
                orig = OrigemMercadoria.OmNacional,
                CST = Csticms.Cst61,
                qBCMonoRet = 1,
                adRemICMSRet = 1,
                vICMSMonoRet = 18,
            };
            //erro nessa linha *nao contem definicao
return icmsGeral.ObterICMSBasico(crt);
        }

**Comment by danilobreda** [comment]
@sigridslima  Manda print pra gente do erro, fazendo favor.

**Comment by sigridslima** [comment]
![Captura de tela 2023-11-21 133352](https://github.com/ZeusAutomacao/DFe.NET/assets/21263061/45e2171d-ca88-4078-bd02-9206bac602db)

Estou chamando:    TipoICMS = ObterIcmsBasicoGas(crt),

**Comment by danilobreda** [comment]
trocar return icmsGeral.ObterICMSBasico(crt) por return icmsGeral;

O ICMS61 já é a definição de um objeto que implementa a interface IICMSBasico

**Comment by sigridslima** [comment]
Olá amigo apresentou esse erro de schema 
![IMG_6258](https://github.com/ZeusAutomacao/DFe.NET/assets/21263061/9590cd84-6420-46f1-9ed1-c909b6b95677)

**Comment by danilobreda** [comment]
@sigridslima atualize os schemas seu. esta antigo antes da NT, ou desabilite a validacao por schemas na configuração do zeus.

**Comment by sigridslima** [comment]
Deu certo amigo
