### ISSUE TITLE
Impressão com a impressora Tectoy Q4 em FastReport

### ISSUE THREAD

**Issue by manogold** [ZeusAutomacao/DFe.NET#1464]
Olá pessoal, sou desenvolvedor de uma empresa no ramo de automação aqui em PE e estamos utilizando o Zeus para emitir as NFC-e desde o início, que diga-se de passagem é fantástico. Estou enfrentando um dilema aqui para imprimir uma NFC-e via FastReports no Zeus para a impressora não-fiscal **Tectoy Q4** e gostaria de ver com os amigos aqui se seria possível uma luz para o que se segue:

Quando mandamos o documento para a impressora, ela imprime a NFC-e corretamente, mas não sei por qual motivo, essa impressora em especial está imprimindo **um espaço em branco relativamente grande** após o final da impressão e então ela efetua o corte, coisa que **não acontece com outras impressoras não-fiscais que trabalhamos** (Elgin, Daruma, Epson...). Ou seja, as outras impressoras detectam automaticamente o fim da impressão da última banda do report **(dbTextoRodape)** e cortam o papel de forma precisa. Porém, com essa impressora em particular, isso ocorre tanto se imprimir diretamente para a impressora quanto também mandar imprimir no modo de preview do report. Como era de se esperar, os clientes que investiram nesse equipamento estão muito insatisfeitos com isso, pois todos os nossos clientes são extremamente exigentes no quesito de "não quero gastar papel além do necessário". Só pra ter uma ideia, por causa disso, nós tivemos que adaptar o arquivo _NFCe.frx_ do Zeus aqui no FastReport Designer e reduzir para mais ou menos 50% do tamanho, utilizando a fonte Microsoft Sans Serif, que se mostrou muito legível, mesmo com tamanho bem pequeno (em algumas partes, usamos tamanho 6, outras vezes tamanho 7), pois o original do Zeus gasta "muito papel" na visão de nossos clientes...

No preview, dá pra ter uma noção clara de que sempre fica um espaço enorme em branco e achamos que seja isso que está fazendo essa impressora em particular imprimir o excesso do preview. Porém não conseguimos retirar isso no preview pra ver se resolve o problema para essa impressora.

Detalhe: comandos ESC/POS pra ela funcionam sem problemas (são exatamente os mesmos da Epson), então temos outros tipos de impressões tais como pedido, orçamento, leituras e fechamento de caixas que são impressos diretamente via código e ela imprime e corta corretamente via comandos ESC/POS. A impressão "Danfe Nativo NFC-e" do Zeus também imprime corretamente e corta o papel no local correto (estamos usando ela por enquanto nos clientes). O problema está com a impressão do FastReports, que nossos clientes estão acostumados e não faço ideia do que fazer para corrigir...

Algum de vocês passou por este problema com essa impressora em particular e pode nos ajudar? Muito obrigado desde já.

**Comment by adrbarros** [comment]
Bom não uso nenhuma ferramenta Reports Visual para impressão nesses tipos de Impressora (Acho que nunca usei), somente impresssão direta a partir das linguagens específicas de cada uma. Pelo Visto ESC/POS esta tranquilo.

Mesmo assim segue modelos de projetos para esse tipo de Impressora
https://github.com/marcosgerene/Gerene.DFe.EscPos
https://github.com/OpenAC-Net/OpenAC.Net.EscPos
https://github.com/leandrovip/Vip.Printer

**Comment by manogold** [comment]
Olá, @adrbarros, muito obrigado pelos links, o Vip.Printer já conheço (a impressão funciona bem nessa biblioteca também) pois usamos ela aqui pra alguns casos muito específicos de formatação dependendo do contexto, ela atende bem. As outras duas indicações que você postou eu particularmente não conhecia, me parecem excelentes, vou fazer uns testes com elas aqui.

Como falei mais acima, a impressão nativa feita pela classe _DanfeNativoNFe.cs_ do Zeus funciona bem para essa impressora, e por enquanto estamos usando ela para atender os nossos clientes. Mas, como o relatório é feito de modo muito manual, é bem trabalhoso de ajustar para ficar parecido com o nosso que é feito em cima da nossa _NFCe.frx_ modificada do Zeus onde conseguimos reduzir em quase 50%, pois tivemos que diminuir a impressão porque os clientes reclamam muito de gasto de papel. 

Por isso vim ver aqui se algum dos amigos tinha passado por este problema de imprimir na Tectoy Q4 via FastReports e se deparar com o espaço em branco que ela imprime após o documento, que até agora não consegui descobrir o motivo. Eu suspeito de que seja porque no preview do Danfe, é possível ver que ele cria um documento do tamanho do formulário onde tem um longo espaço em branco, e essa impressora não detecta o fim do documento corretamente como as outras, e então imprime esse espaço em branco. Já reinstalei várias vezes a impressora, ajustei os drivers, mexi em todas as configurações dela, mas não resolveu. Talvez retirando esse "espaço" em branco do preview resolva, mas ainda não consegui fazer isso.

Muito obrigado pelos links! Enfatizando mais uma vez pra quem tiver essa impressora, ESC/POS funciona normalmente a impressão. Apenas impressões pelo FastReport está com esse problema.

**Comment by manogold** [comment]
Caros amigos, acabei descobrindo aqui o problema da impressora **Tectoy Q4**, o motivo dela imprimir um espaço enorme em branco após o fim do documento! Foi meio que na tentativa e erro, pois testamos e alteramos quase todas as configurações da impressora no Windows, e nada parecia funcionar. Pesquisei muito no google sobre essa impressora, mas não obtive êxito, há muito pouco material sobre essa impressora ainda. Deixo então aqui a solução para que ninguém mais perca tempo precioso de desenvolvimento com algo simples (mas, até chegar a essa solução custou-me um bom tempo).

A solução:

- Instale a impressora normalmente como consta no manual, incluindo os drivers que a acompanham em um CD de acordo com o seu sistema operacional (no meu caso aqui, Windows 10);
- As configurações padrões do driver dela já satisfazem a impressão, então não é preciso alterar outras configurações mais avançadas. Basta apenas ir nas preferências de impressão dela, na aba "Geral", clicando no botão "Preferências" como mostrado abaixo:

![Tectoy Q4 - 1](https://github.com/ZeusAutomacao/DFe.NET/assets/59580255/f6eea742-6fa7-471e-a769-dd0061d78dd1)

- Feito isso, clique na aba "Papel/Qualidade" e perceba que por padrão, o esquema de cores dela vem marcado como "Cor". Basta apenas marcar a opção "Preto e branco", clicar em "Aplicar" e depois "OK":

![Tectoy Q4 - 2](https://github.com/ZeusAutomacao/DFe.NET/assets/59580255/52b39792-9f98-4ccc-8b04-830b51db4e45)

**Só isso já basta para ela imprimir um relatório feito em FastReports (no nosso caso, uma NFC-e) cortando o papel corretamente sem imprimir o espaço em branco que ela julgava necessário imprimir.** Fizemos alguns testes aqui na empresa de diversas formas e está funcionando bem, inclusive nos nossos clientes. Espero que possa ajudar alguém que tiver esse problema também.

Obrigado a todos!
