### ISSUE TITLE
Fala galera! Estou com essa reposta de erro aqui e não estou conseguindo resolver. Alguem pode me ajudar ?A conexao subjacente  estava fechada. Erro inesperado em um envio. Estou usando c# no Visual Studio 2015. 

### ISSUE THREAD

**Issue by vagnercardosomagalhaes** [ZeusAutomacao/DFe.NET#1466]
O erro acontece qdo chega na parte -> string json = client.DownloadString(url);

Public static Empresa ObterCnpj(string cnpj)
{
  string url = "https://www.receitaws.com.br/v1/cnpj/" + cnpj;
  WebClient client = new WebClient();
  Client.Encoding = Encoding.UTF8;
  string json = client.DownloadString(url);
  var empresa = JsonConvert.DeserializeObject<Empresa>(json);
  return empresa;

}

**Comment by danilobreda** [comment]
Esse serviço não faz parte da biblioteca DFe.Net. Recomendo buscar ajuda em canais sobre .NET
