### ISSUE TITLE
Simples Nacional com CST 61

### ISSUE THREAD

**Issue by joanvitor** [ZeusAutomacao/DFe.NET#1467]
Tentando emitir uma nota fiscal com o Regime de tributação "Simples Nacional", para a situaçaõ tributária referente a CST 61 (Tributação monofásica sobre combustíveis cobrada anteriormente), a biblioteca DFe.NET, como visto na imagem abaixo, não está suportando a emissão de uma nota, pois não há o caso de CST 61 para o regime simples nacional.

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/38784623/5f9aa0f3-7ab6-40c7-b5b6-a30f53563366)

Sendo assim, por não suportar o Simples Nacional para CST 61, é lançada a exceção:

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/38784623/8104f01e-27c6-4d80-8257-2ac4d2382f38)

Então, eu gostaria de saber como está sendo feita a emissão da nota fiscal com o regime de "Simples Nacional" e para a CST 61. 

Além disso, vi que a classe ICMSGeral não contém os campos qBCMonoRet, adRemICMSRet e vICMSMonoRet. Seguiram um outro padrão para esse caso?

**Comment by robertorp** [comment]
Boa tarde, tudo bom? 
Você pode fazer um pull com alterações para funcionar ? 
Aqui até utilizo o Zeus para emissão com 61 mas não utilizo esses métodos por isso não passei por essa situação

**Comment by andrebts** [comment]
Implementação realizada no [PR 1489](https://github.com/ZeusAutomacao/DFe.NET/pull/1489)
