### ISSUE TITLE
NF-e Impressão e Salvar XML autorizado

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#147]
Ola @adeniltonbs boa tarde, 

Por favor vc pode colocar um exemplo de impressão do Danfe da NF-e, envio por e-mail e como faço para salvar o XML autorizado?

grd abs meu caro

**Comment by robertorp** [comment]
Lendo seu post lembrei que fiz uma implementação de envio por e-mail mas o @adeniltonbs  disse somente que iria ver, e nunca mais olhou hahaha não recusou nem aceitou deve ter esquecido ou sei lá.

NF-e até onde sei não tem implementado ainda, pelo menos na versão que estou usando.
O xml salvar ele tem a opção la no exemplo já implementada e funional.

**Comment by alsantana** [comment]
Olá @robertorp vc pode me ajudar como faço para pegar o xml autorizado, depois de consultar o lote?

Com relação a impressão vc teria o trecho de código para realizar a msm?

grd abs

**Comment by robertorp** [comment]
Impressão estou usando o acbrmonitor para fazer no caso eu obtenho o xml e envio para o acbrmonitor e pego o pdf que o acbrmonitor gera.

agora sobre o componente Zeus,

ele tem essa linha de código (numero da linha aproximadamente 355)

`var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List<Classes.NFe> {_nfe, nfe2}, false/*Envia a mensagem compactada para a SEFAZ*/);`

no meu caso o código está alterado por isso tenho duas nfe (_nfe é nfe2)

o xmlAutorizado eu pego o XmlAssinado e adiciono os dados da autorização no mesmo.

```
var zeus = new NFe.Classes.NFe().CarregarDeXmlString(XmlAssinado);
            var nfeProc = new nfeProc();
            nfeProc.NFe = zeus;
            nfeProc.protNFe = new protNFe();
            nfeProc.versao = Versao.GetString();
            nfeProc.protNFe.versao = Versao.GetString();

            nfeProc.protNFe.infProt = new infProt();
            nfeProc.protNFe.infProt.dhRecbto = recebimento;
            nfeProc.protNFe.infProt.tpAmb = TipoAmbiente.ToZeus();
            nfeProc.protNFe.infProt.verAplic = VersaoAplicativoAutorizacao;
            nfeProc.protNFe.infProt.chNFe = Chave;
            nfeProc.protNFe.infProt.digVal = DigestValue;
            nfeProc.protNFe.infProt.cStat = CodigoAutorizacao;
            nfeProc.protNFe.infProt.nProt = Protocolo;

            XmlAutorizado = nfeProc.ObterXmlString();
```

logo depois de ter o XmlAutorizado eu pego o mesmo e envio para o acbrmonitor usando o comando 

NFe.ImprimirDANFEPDF se não me engano o unico parametro e o caminho do xml.. no caso você escolhe salvar o xml em algum local no disco ou então usa as classes de stream do c# para salvar na memoria (ele vai tipo simular que esta salvando no disco) e passa o caminho para o monitor e ele imprimira

**Comment by adeniltonbs** [comment]
Bom dia @alsantana.
Atualize sua cópia da biblioteca e verifique os botões "DANFE NFCe Normal" e "DANFE NFCe Cont. Offline" para impressão do DANFE utilizando o FastReports; o botão "Enviar Email" para envio de e-mail; e, finalmente, os botões "Criar e Salvar XML 3.0" e "Criar e Enviar 3.0" para criar, enviar, obter o XML autorizado e salvar.

![image](https://cloud.githubusercontent.com/assets/6733483/16356766/3ea1d388-3aba-11e6-9ef4-2f4ac360c595.png)

Quanto a este último recurso "salvar o XML autorizado" recomendo que você salve o xml do objeto nfeProc. Para tanto, veja o procedimento do botão "Adicionar proc ao XML".

**Comment by adeniltonbs** [comment]
Obs: Note que o retorno do método ServicosNFe.NFeAutorizacao tem uma propriedade "EnvioStr". Quando a NFe/NFCe é autorizada, é o xml contido nessa propriedade que é autorizado pela SEFAZ
Esse xml pode ser parte do xml que você vai persistir. A outra parte é o objeto protNFe que é devolvido pelo método ServicosNFe.NFeRetAutorizacao.

Outra alternativa, se você já tem o objeto NFe que foi autorizado em memória, então você pode, depois de chamar o método NFeRetAutorizacao e armazenar em memória seu resultado, criar um objeto nfeProc da seguinte forma:

``` cs
var retornoAutorizacao = servicoNFe.NFeRetAutorizacao(recibo);
var protNfeRetorno = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();
if (protNfeRetorno == null) {
    tenta_retransmitir_a_nfe;
    return; 
}
if (protNfeRetorno.infProt.cStat == 100 | protNfeRetorno.infProt.cStat == 150) //100 = Autorizada, 150 = Autorizado o uso da NF-e, autorização concedida fora de prazo
var nfeproc = new nfeProc { NFe = nfe, protNFe = protNfeRetorno, versao = retornoAutorizacao.Retorno.versao };
nfeproc.SalvarArquivoXml(caminho_nome_do_arquivo);
```

**Comment by alsantana** [comment]
Olá @adeniltonbs e @robertorp  mto obrigado pela ajuda, fiz as modificações e ficou bem bacana.

@adeniltonbs, por favor tem como tirar mais uma dúvida, hoje na biblioteca não tem como imprimir o Danfe para NF-e, somente para NFC-e correto?

grd abs

**Comment by adeniltonbs** [comment]
Isso. No momento só está implementada a impressão do DANFE da NFCe. A impressão da NFe foi iniciada aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/Danfe_NFe. Alguém havia prometido dar prosseguimento, mas acredito que não teve tempo de fazê-lo.
