### ISSUE TITLE
Internal Server Error CTe 4.0

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#1471]
Foi verificado que ao emitir CT-e v4 para UF PR estava retornando Internal server error, verificado que o problema esta sendo o envio do SoapAction, o problema esta sendo na class CteRecepcaoSincronoV4, metodo CTeRecepcaoSincV4, esta passando o TipoEvento invalido, teria que ser TipoEvento.CTeRecepcaoV4.

**Comment by danilobreda** [comment]
@flavionootech se conseguir resolver pra gente pode fazer um pullrequest que aceitamos com urgencia!

**Comment by flavionootech** [comment]
Feito, teria previsao de disponibilizar no nuget

**Comment by marcosgerene** [comment]
PR: https://github.com/ZeusAutomacao/DFe.NET/pull/1472 aceito.

Nuget é automático, em poucos minutos está disponível.

**Comment by flavionootech** [comment]
Resolvido
