### ISSUE TITLE
Acessar valor do ICMS ST do item para impressão no danfe fast report

### ISSUE THREAD

**Issue by WendelProfox** [ZeusAutomacao/DFe.NET#1478]
Boa tarde!
Primeiramente gostaria de parabenizar à esta comunidade do Dfe.NET.
Apesar de ser novo por aqui, vi que é um projeto sensacional!
Instalei pelo nuget para fazer alguns testes e tentei ajustar o leiaute do danfe no fast report, tendo como base o NFeRetrato.frx.
Vi o código no fast e tentei ajustar conforme o padrão já existente e vi que alguns campos são acessados via métodos definidos na classe Extensions do namespace NFe.Classes.Informacoes.Detalhe.Tributacao. 
ex: prodICMSCell.Text = FormatNumber(icmsBasico.GetIcmsValue(), 2);
Acontece que não existe nesta classe um metodo que retorne o valor do ICMS ST do item, apesar de existir um que retorno a base do ST.
Minhas dúvidas são:
1) Existe outra forma de acessar esta informação de dentro do fast report?
2) Se não tem, é possível criar um novo método na classe Extensions para tornar o campo acessível?
Acredito que seria acrescentar algo como:
         public static decimal GetIcmsStValue(this ICMS
Basico icms) {
            return GetPropDecimalValue(icms, "vICMSST");
        }

Atenciosamente,
Wendel 

![geticms](https://github.com/ZeusAutomacao/DFe.NET/assets/84038355/b2a4f7f0-edb5-48cd-aaaa-0521876b5527)

**Comment by danilobreda** [comment]
Não entendi muito bem, qual seria o objetivo principal mostrar vICMSST no Danfe??

**Comment by WendelProfox** [comment]
Sim, o objetivo é mostrar o vICMSST do item no danfe.
Como pode ser visto no print, atualmente existe um método GetIcmsValue para obter o valor do ICMS, mas não existe um método para obter o valor do ICMSST.

**Comment by danilobreda** [comment]
Caso for necessário criar o método estamos aceitando pullrequest para disponibilizasr essa tag no relatório, porem acredito que o mesmo terá de ser alterado.
