### ISSUE TITLE
NFC-e em contingência - Assinatura difere do calculado

### ISSUE THREAD

**Issue by AcciolyDSI** [ZeusAutomacao/DFe.NET#148]
Olá Adenilton, primeiramente parabens pelo projeto, muito bem estruturado.

Estou implementando a contigência off-line da NFC-e, o processo que faço é gerar o xml, assino, incluo QrCode, valido, e uso o método de extensão SalvarArquivoXml para salvar o xml em disco.
Para carregar o arquivo xml uso o método de extensão CarregarDeArquivoXml(path);
carrego no objeto NFe e uso o método servicoNFe.NFeAutorizacao(lote, IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe> { nfe });
Ta voltando com Rejeição Assinatura 297 - Rejeição: Assinatura difere do calculado.

Esse mesmo arquivo eu consigo enviar pelo Unimake, que é outro projeto open source, 
e esse mesmo arquivo se eu assinar novamente e enviar vai normal.

Só que pelo manual, eu não posso mais modificar o xml com uma nova assinatura, isso vai invalidar
o danfe anteriormente impresso, e consequentemente se o consumidor for consultar, não vai achar o cupom dele na Sefaz.

Onde estou errando?

Abraços

**Comment by adeniltonbs** [comment]
Bom dia @AcciolyDSI.
Atualize sua cópia da biblioteca para o commit mais recente: 2bfba029f6133c80348472f2f5fa864333a90ddd.

Abaixo segue o roteiro para emitir uma NFCe em contingência utilizando a aplicação de demonstração que acompanha a bilbioteca:
Na aplicação de demonstração, uma vez configurada, utilize os seguintes passos para trabalhar com a NFCe offline:
1. Na guia "Geral", altere a Forma de emissão para "NFC-e Offline"
   ![image](https://cloud.githubusercontent.com/assets/6733483/16357090/f450ecc0-3ac2-11e6-9a83-5e33de32243f.png)
2. Clique no botão "Criar e Salvar XML 3.0" e salve o XML e um diretório;
3. Clique no botão "DANFE NFCe Cont. Offline", escolha o XML e imprima;
4. Clique no botão "Carregar XML e Enviar", escolha o XML e envie. Salve o número do recibo;
5. Clique no botão "Consultar Recibo Lote 3.0", informe o número do recibo e o retorno foi NFe autorizada.
   Resultado:
   ![image](https://cloud.githubusercontent.com/assets/6733483/16357165/6bd90104-3ac5-11e6-93d2-1f52d13a4508.png)

**Comment by AcciolyDSI** [comment]
Olá Adenilton, muito obrigado pelo retorno, vou fazer os ajustes, mais uma vez, muito obrigado.
Abraços
