### ISSUE TITLE
Datas de Notas Técnicas (próxima 01/04/2024 PRODUÇÃO)

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1484]
- NT2023.004 **01/04/2024** (v1.1) - CPF, Dados Novos Forma Pagamento, indDeduzDeson **[IMPLEMENTADO PARCIALMENTE]**  #1483 #1481
- NT2016.003 **01/04/2024** (v3.7) - Novos NCMs Congelados e Produtos Quimicos Específicos **[NÃO IMPLEMENTADO]**
- NT2019.001 **01/04/2024** (v1.6) - Regras novas de SC, novas regras CST51 e inclusão de campos para as informações do crédito presumido **[JÁ IMPLEMENTADO #1486]**  
- NT2023.005 24/06/2024 (v1.0) - Implantação do evento de Insucesso na Entrega da NF-e  **[NÃO IMPLEMENTADO]**
- NT2023.007 03/06/2024 (v1.3) - Melhorias na documentação de coisas internas (nada interessante até aonde entendi) 
- NT2023.001 02/09/2024 (v1.3) - Implantação de novo grupo de validação de códigos GTIN – Grupo III  

**Estamos aceitando contribuições e melhorias no Zeus DFe.Net para adequação com NTs;**

**Comment by lucasmoraes804** [comment]
Olá @danilobreda, criei um PR #1486 da NT2019.001
