### ISSUE TITLE
Geração de NFS-e padrão nacional

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#1488]
Agora possuimos um padrão nacional para emissão de NFS-e, seria interessante possuirmos esta funcionalidade no projeto

**Comment by marcosgerene** [comment]
@flavionootech 

Existe uma iniciativa opensource em CSharp do grupo OpenAC:
https://github.com/OpenAC-Net/OpenAC.Net.NFSe.Nacional

Obviamente se você (ou alguém da comunidade ou algum dos outros mantenedores) quiser implementar e submeter para análise, acho uma discussão válida.

Entretanto, (minha opinião exclusiva, não represento os outros mantenedores) não vejo o porque implementar aqui.
