### ISSUE TITLE
NFe em lote

### ISSUE THREAD

**Issue by brunominervino** [ZeusAutomacao/DFe.NET#149]
@adeniltonbs primeiramente obrigado por disponibilizar essa biblioteca gratuita.
Estou acompanhando à algum tempo porém não pude testar até o momento porque estou sem o certificado digital, e como não trabalho voltado a essa área (ainda), não adquiri.

Bom, eu gostaria de saber se com a sua biblioteca é possível puxar NFe em lote, caso não, se é possível tal consulta em algum link específico.

Agradeço desde já, abs.

**Comment by adeniltonbs** [comment]
Bom dia @brunominervino,
Não entendi muito bem o que você quis dizer. Lote de NFe é um conjunto de NFes emitidas de uma vez. A biblioteca tem suporte ao envio de NFe em lote, assim como estabelece o manual.

Acredito que você está querendo falar sobre o download de NFe. Se for isso, o download, por determinação da SEFAZ, só pode ser feito pelo emitente, pelo destinatário, ou por outro ente autorizado previamente na NFe. Em todo caso é requerido uso de certificado. A SEFAZ também tem acesso ao xml :)

**Comment by brunominervino** [comment]
@adeniltonbs seria isso mesmo, eu com o certificado consigo fazer download de todas as NFe's do emitente através do SEFAZ?

**Comment by adeniltonbs** [comment]
Pode fazer o downlod, mas não de "Todas as NFe's". Veja o Manual de Orientação do Contribuinte [http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=](url), páginas 124-129. 
Note que a bilbioteca Zeus.Net.NFe.NFCe implementa o consumo desse serviço. Há um exemplo de uso na aplicação de demonstração de Uso, botão "Download NFe".

**Comment by brunominervino** [comment]
@adeniltonbs muito obrigado.
