### ISSUE TITLE
Alteracao do endereco do qrcode rio de janeiro

### ISSUE THREAD

**Issue by ricardopdv** [ZeusAutomacao/DFe.NET#1490]
Ola, tem um aviso no site https://portal.fazenda.rj.gov.br/dfe/ dizendo que a url do qrcode foi alterada para
https://consultadfe.fazenda.rj.gov.br/consultaNFCe/QRCode a partir de 19/12/2023

Poderiam verificar, obrigado.

**Comment by marcosgerene** [comment]
A classe que define essas URLs é essa:

https://github.com/ZeusAutomacao/DFe.NET/blob/257663da6b3089442d9c7f82d94544d392338f7e/NFe.Utils/InformacoesSuplementares/ExtinfNFeSupl.cs

Eu particularmente uso o arquivo "ACBrNFeServicos.ini" do ACBr para consultar as URLs quando necessário..

Abri o PR: https://github.com/ZeusAutomacao/DFe.NET/pull/1491

Aguardo sua contribuição em uma próxima oportunidade =)

**Comment by danilobreda** [comment]
Finalizado pelo pullrequest. @ricardopdv já esta no nuget! qualquer coisa só criar uma issue nova :)
