### ISSUE TITLE
Integração com solution C#

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#15]
Adenilton,

Eu tenho um solution em C# com 3 projetos (camadas) e gostaria de integrar a parte de NFC-e do Zeus nele. Como posso fazer?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
Comece por estudar a aplicação de demonstração incluída na biblioteca. A aplicação de demonstração contém exemplos de uso de cada serviço da NFe/NFCe. Caso tenha uma dúvida mais específica poste aqui.

**Comment by robertocvsiqueira** [comment]
Sim, mas no sentido de instanciar as classes e usar as funcionalidades de NFC-e na minha aplicação que dll's possso referenciar nela? Ou vou ter que incluir os projetos do Zeus na solution?

**Comment by adeniltonbs** [comment]
Você pode fazer as duas coisas, referenciar as dlls ou referenciar os projetos na sua aplicação.
Roberto, recomendo você dar uma olhada no manual do Visual Studio em https://msdn.microsoft.com/en-us/library/h8w79z10.aspx

Aqui também mostra como lidar com referências no visual studio:
https://msdn.microsoft.com/pt-br/library/wkze6zky.aspx

Se quiser referenciar apenas as dlls, compile a solução, conforme as "Instruções para compilar a solução", descritas na página principal desse projeto.

De qualquer forma, estude a aplicação de demonstração.

**Comment by robertocvsiqueira** [comment]
Já estudei a aplicação de demonstração e já sei como usar o Visual Studio. A minha dúvida era se eu podia só referenciando as dlls poderia fazer uso das funcionalidades dae NFC-e. Se pode, então, quais as dlls que eu referencio no meu projeto?

**Comment by adeniltonbs** [comment]
Então Roberto, na aplicação de demonstração, em referências, indica que a aplicação usa os seguintes projetos: NFe.Classes, NFe.Servicos e NFe.Utils. Se você compilar a solução irá obter estas dlls, daí basta referenciar estas três no seu projeto.

No visual Studio, tanto faz se você faz referência aos projetos ou às dlls, por isso disse pra você verificar a aplicação de demonstração. A única diferença se fizer referência ao projeto é a maior facilidade no debug e ter acesso ao fonte para detectar/corrigir erros.

Ao observar as referências do projeto de demonstração a única dedução que podemos fazer é:  Se a aplicação de demonstração faz  referencia a estes três projetos (NFe.Classes, NFe.Servicos e NFe.Utils), logo em minha aplicação vou fazer referência a estes três projetos (NFe.Classes, NFe.Servicos e NFe.Utils) ou a estas três dlls (NFe.Classes.dll, NFe.Servicos.dll e NFe.Utils.dll).

**Comment by robertocvsiqueira** [comment]
Ok, Adenilton, vou fazer os testes aqui e te falo. Obrigado!

**Comment by MoacirCarlos** [comment]
Ótima ideia... gerar as dlls e referencia-las, com isso, quando tiver manutenções para fazer em seu módulo de NF-e você envia apenas as dll atualizadas para o cliente, sem necessidade de compilar o projeto inteiro e gerar outra tag.

**Comment by robertocvsiqueira** [comment]
Isso mesmo! Vai ficar bem mais prático.

**Comment by integrasys** [comment]
Olá, 
eu baixei o projeto e achei muitio interessante... só fiquei com uma duvida... ele está Imprimindo a DANFE?

**Comment by apbertoletti** [comment]
Boa tarde pessoal, td bem?

Permita-me reabrir esta issue, visto que estou com uma duvida relacionada por aqui.

Já li a conversa de vocês, mas ainda não encontrei algo que resolvesse o problema... segue alguns pontos do meu contexto:

**P1)** Uso a IDE Visual Studio 2017 Professional
**P2)** Tenho uma Solution com vários projetos, todos eles versionados no TFS
**P3)** Temos um time de 3 desenvolvedores aqui, onde de tempos em tempos, todos baixam a ultima versão completa dos fontes do nosso sistema em suas máquinas, para darem continuidade nos trabalhos
**P4)** Pretendo contribuir no código do Zeus (com correções e melhorias), subindo novos PRs
**P5)** Obviamente, antes de subir os PRs, pretendo fazer os testes locais no meu sistema, debugando inclusive as chamadas internas no código Zeus
**P6)** Tenho consciência de que o intervalo de tempo entre submeter um novo PR. e este avaliado, aceito e publicado no Nuget, nem sempre é suficiente para cumprir certas emergências e "incêndios" fiscais que ocorrem nos clientes. Nestes casos, precisarei "queimar etapas", ou seja, liberar os ajustes aos meus clientes, para só depois retomar o fluxo de subir um novo PR para comunidade.

Enfim, alguém ai com contexto parecido, possa dar algumas dicas de como eu poderia configurar meu ambiente para tal? (pastas, referencia entre projetos, TFS + Git na mesma solução, ... etc)

Já testei algumas alternativas aqui, mas nenhuma com sucesso.

Obrigado

**Comment by adeniltonbs** [comment]
Boa tarde @apbertoletti 
Meu uso aqui é exatamente dessa forma. Nesse caso, não faço referência às bibliotecas do projeto disponíveis no Nuget. Em vez disso, adiciono os projetos da biblioteca à minha solução e faço referência dessas bibliotecas aos projetos que as utilizam.

Exemplo:
![image](https://user-images.githubusercontent.com/6733483/41434305-a5a2a580-6ff1-11e8-9067-5687298a299b.png)

**Comment by apbertoletti** [comment]
Boa tarde @adeniltonbs, obrigado pelo feedback. 

Duas duvidas sobre o seu contexto:

1) Pelo que observo no print, me parece que os projetos que do Zeus ficaram fora do seu controlador de versão, confere? Neste caso, como é que outros membros do seu time terão acesso a estes projetos do Zeus

2) Quando você precisa fazer correções ou melhorias no código fonte do Zeus, vc faz ai por dentro da sua solução mesmo? Depois faz o Commit e Push no GitHub por fora da sua solução?

Obrigado

André

**Comment by alexsandro-xpt** [comment]
Porque vocês não usam o Nuget?

**Comment by apbertoletti** [comment]
Sim @alexsandro-xpt , 

Eu estou usando o Nuget, mas preciso mudar de estratégia, visto que ele dificulta alguns pontos do meu contexto, tais como P5 e P6 que mencionei acima.

> P5) Obviamente, antes de subir os PRs, pretendo fazer os testes locais no meu sistema, debugando inclusive as chamadas internas no código Zeus
> P6) Tenho consciência de que o intervalo de tempo entre submeter um novo PR. e este avaliado, aceito e publicado no Nuget, nem sempre é suficiente para cumprir certas emergências e "incêndios" fiscais que ocorrem nos clientes. Nestes casos, precisarei "queimar etapas", ou seja, liberar os ajustes aos meus clientes, para só depois retomar o fluxo de subir um novo PR para comunidade.

**Comment by robertorp** [comment]
Utilizo nuget. 
Motivo, tudo oque vem no master inicialmente esta sujeito a dar um errinho, uso nuget pois pessoas que usam o master diretamente já testaram antes de lançar no nuget obviamente. 
Em compensação quem usa o master usa as coisas antes. Mas em contra partida esta sujeito a mais bugs do que o nuget.

**Comment by adeniltonbs** [comment]
@apbertoletti 
> Pelo que observo no print, me parece que os projetos que do Zeus ficaram fora do seu controlador de versão, confere? 

Sim
> Neste caso, como é que outros membros do seu time terão acesso a estes projetos do Zeus?

Nesse caso você faz um fork da biblioteca DFe.NET e aponta o repositório no seu PC para esse fork e não para a branch master em https://github.com/ZeusAutomacao/DFe.NET/

> Quando você precisa fazer correções ou melhorias no código fonte do Zeus, vc faz ai por dentro da sua solução mesmo? Depois faz o Commit e Push no GitHub por fora da sua solução?

Tanto faz, pode ser de dentro de seu projeto mesmo, uma vez que cada um vai estar em um repositório diferente do git. Depois basta ir no diretório da biblioteca DFe.NET e fazer o commit e push. Quando achar que suas alterações estão prontas para subir para o repositório oficial, você envia um Pull Request.

**Comment by apbertoletti** [comment]
@adeniltonbs 

> Pelo que observo no print, me parece que os projetos que do Zeus ficaram fora do seu controlador de versão, confere?
> Sim

Mas neste caso, como é que outros membros do seu time terão acesso a estes projetos do Zeus que ficam dentro da sua solution, já que eles estão fora do source control?

**Comment by adeniltonbs** [comment]
@apbertoletti 
> Mas neste caso, como é que outros membros do seu time terão acesso a estes projetos do Zeus que ficam dentro da sua solution, já que eles estão fora do source control?

1 - A cópia da biblioteca na unidade de armazenamento do PC dos demais desenvolvedores apontará para seu fork da biblioteca;
2 - Basta você orientar os demais desenvolvedores a manter a pasta com a biblioteca numa mesma estrutura de diretório **relativa**. 

**Exemplo**: Vamos supor que seu projeto esteja em c:\projetos\emissor_de_nfe e seu fork da biblioteca esteja em c:\bibliotecas\DFe.NET
O arquivo .sln de seu projeto ficará mais ou menos assim:

```
...
Project("{CHAVE}") = "MeuProjeto", "MeuProjeto\MeuProjeto.csproj", "{CHAVE}"
EndProject
....
Project("{CHAVE}") = "NFe.Classes", "..\..\bibliotecas\DFe.NET\NFe.Classes\NFe.Classes.csproj", "{chave}"
EndProject

```
Assim os demais desenvolvedores só precisam deixar a biblioteca num diretório ..\..\bibliotecas, não importando a estrutura hierárquica de pastas antes disso.

Pode ser mais fácil ainda se deixar tanto a pasta que contém sua solução como a pasta que contém a biblioteca num mesmo diretório em comum.

**Comment by apbertoletti** [comment]
Muito obrigado @adeniltonbs ,

Vou aplicar suas dicas aqui e devolvo um feedback pra dizer como ficou.

Abraços
