### ISSUE TITLE
nProt ao consultar NFe autorizada não vem preenchida

### ISSUE THREAD

**Issue by rodrigoCpPro** [ZeusAutomacao/DFe.NET#1501]
Ao realizar a emissão com sucesso em ambiente de homologação atualmente, o campo `protNfe.infNfe.nProt` não retorna preenchido pelo Zeus. Acredito que isso pode ser um possível bug, segue imagem referente do que estou fazendo atualmente, para buscar a tag protNfe.

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/106621634/30d0bfdb-41af-4204-86f1-f5621ad0e1b4)

**Comment by marcosgerene** [comment]
Posta o XML de retorno da sefaz, por favor.

**Comment by rodrigoCpPro** [comment]
@marcosgerene boa tarde, a issue será fechada, descobri que o protocolo só é enviado quando a nota fiscal é autorizada, e percebi que o xml estava retornando uma rejeição devido o cnpj do emitente estar em desacordo com o certificado, obrigado desde ja.
