### ISSUE TITLE
Impressão Danfe NF-e com tag rastro

### ISSUE THREAD

**Issue by developexi** [ZeusAutomacao/DFe.NET#1502]
A tag rastro é utilizada em controle de medicamentos ou produtos por lotes. Mesmo colocando um xml que tenha Tag Rastro o fastReport não aceito, foi colcoado na arvore onde ele busca o xml, mas a principio o componente não tem mapeado, e assume o padrão do xml novamente.
Exemplo:
https://prnt.sc/mVZ1XOzN0DAV

Esses dados devem sair na impressao do Danfe, abaixo da descrição.

**Comment by danilobreda** [comment]
Existe algum exemplo de DANFE com esse modelo? ou no manual do próprio DANFE existe alguma explicação sobre isso?

Faço essa pergunta pois quando não é algo PADRONIZADO pela sefaz, deixamos o desenvolvedor realizar a modificação da maneira que ele achar melhor do DANFE. Não definimos nenhum padrão que não seja do SEFAZ.

**Comment by developexi** [comment]
Danilo, nosso time encontrou a forma de fazermos no FRX.
Segue o passo para comunidade. 
https://prnt.sc/tRfqGF5V44K_
Depois só chamar os campos. Exemplo: NFe.NFe.infNFe.det.prod.rastro.qLote
