### ISSUE TITLE
Eventos NFe - Erro Desserialização

### ISSUE THREAD

**Issue by EttorePaludeto** [ZeusAutomacao/DFe.NET#1503]
Fala ae rapazeada, blz?

Estava gerando relatórios PDF dos eventos da NFe e me deparei com bug na desserialização de dois eventos novos
Resolvi exatamente esse problema #1254  
Então, tomei a liberdade de mexer o código e testar. Como por milagre, rodou...
Basicamente, adicionei esses 2 tipos novos no enum NFeTipoEvento.

O que eu posso fazer pra ajudar? Compartilho essa alteração para vocês testarem?
OBS.: sou uma anta em tecnologia. 
Abrax galera.

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/38463108/38b19363-4c42-40bf-8389-11c18875f455)

**Comment by marcosgerene** [comment]
@EttorePaludeto 

Como voce fez a correção, por padrão eu peço um PR para "te dar o crédito".

Se tiver alguma dificuldade em faze-lo, eu faço direto o commit aqui e so menciono que foi você quem postou a solução.

---

Abri o PR #1504 

Por padrão quando eu abro o PR eu procuro não aceitar eu mesmo por questão de validação mínima. Basta aguardar o @danilobreda ou @robertorp validar e aceitar.

**Comment by EttorePaludeto** [comment]
> @EttorePaludeto
> 
> Como voce fez a correção, por padrão eu peço um PR para "te dar o crédito".
> 
> Se tiver alguma dificuldade em faze-lo, eu faço direto o commit aqui e so menciono que foi você quem postou a solução.
> 
> Abri o PR #1504
> 
> Por padrão quando eu abro o PR eu procuro não aceitar eu mesmo por questão de validação mínima. Basta aguardar o @danilobreda ou @robertorp validar e aceitar.

O que for mais fácil pra vcs meus caros!
O crédito é todo de vocês...são top demais!!!
