### ISSUE TITLE
 DECLARAÇÃO DOS MANTENEDORES A COMUNIDADE "ZEUS"

### ISSUE THREAD

**Issue by danilobreda** [ZeusAutomacao/DFe.NET#1508]
[ DECLARAÇÃO DE DESLIGAMENTO DOS MANTENEDORES A COMUNIDADE -> https://github.com/Hercules-NET/ZeusFiscal/issues/1](https://github.com/Hercules-NET/ZeusFiscal/issues/1)

Fork realizado em https://github.com/Hercules-NET/ZeusFiscal

**Comment by adeniltonbs** [comment]
Boa tarde, tudo bem fazer um fork, a licença o permite. Grande parte do sucesso da lib se deve a vocês. 
Chamo sua atenção para três itens apenas: 
1 - Não fiquei sem responder a um mês como vc sugeriu em https://github.com/Hercules-NET/ZeusFiscal/issues/1, foi enviada uma mensagem no dia 02/04, que foi respondida no dia 07/04.  Ocorre que entre os dias 29/03 - 05/04 estive de férias com minha família;
2 - Sobre a colaboração da Zeus, mesmo sem eu estar enviando código na minha conta do gitHub, ela continuou por meio de colaboradores aqui da empresa, pois a medida que o negócio foi crescendo, não pude continuar codando como antes, mas o time o fez, especificamente no grupo de projetos relacionado à emissão de NFe-NFCe;
3 - O Roberto está como administrador do projeto e tem acesso a gerenciar a SECRET do nuget. Esse acesso poderia ser concedido a mais pessoas. 

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/6733483/113e8887-a678-40ae-8c75-26cbea84825c)
