### ISSUE TITLE
Geração NFC-e de serviços para Brasília - DF

### ISSUE THREAD

**Issue by dongustavosccp** [ZeusAutomacao/DFe.NET#151]
Boa Tarde,
Gostaria de saber o passo a passo para a geração da NFCe para brasília de notas de serviço utilizando a dll, quais funções eu devo invocar e quais parâmetros passar para essas funções.

Agradeço desde já.

**Comment by leandrossantos** [comment]
Olá @dongustavosccp nota de serviços é NFSe que é direto com a prefeitura municipal que adota o provedor que ela "escolher". Esse componente aqui do @adeniltonbs é somente para NFe e NFCe, que são nota de produtos.

Espero ter esclarecido sua dúvida.

**Comment by dongustavosccp** [comment]
Olá @leandrossantos , para Brasilía a emissão de nota de serviços é realizada pela NFC-e pois brasília não tem prefeitura, então o envio é pela SEFAZ DF como nota fiscal eletrônica, muda pois tem de ser tributada pelo ISSQN, e eu gostaria de saber o passo a passo para a geração da NFCe utilizando a dll pelo meu software, como eu envio o xml ou se envio parâmetros para alguma função,se eu realizo a assinatura ou a dll realiza , o envio da nota e o retorno da mesma.

Abraços e obrigado pela atenção.

**Comment by leandrossantos** [comment]
Então se pode ser enviado o serviço na NFCe ai, então é só informar as tag referente ao serviço, e para o emitente tem que informar o CNAE e a Inscrição Municipal.
A DLL é completa faz tudo, gera XML, assina, valida, transmite, consulta, cancela, enfim. faz todos os procedimentos.

Pega a parte que gera o XML ai no exemplo que vai junto e troca a parte do imposto onde gera ICMS para gerar o ISSQN. Basicamente é isso. Só não sei se na NFCe vai aceitar, talvez seja necessário ser uma NFe. A chamada NFe conjugada.

**Comment by dongustavosccp** [comment]
@leandrossantos correto, e para eu integrar ao meu sistema, se eu gerar a xml a dll faz o restante do processamento?

**Comment by dongustavosccp** [comment]
eu gostaria de saber as funções que eu utilizo para realizar o envio, e a impressão do cupom.

A aplicação de testes está completa porém eu apenas utilizarei a DLL no meu sistema e eu gostaria de sanar as duvidas quanto ao processo de emissão e retorno da NFCe, irei listar alguns pontos:

1 - Como eu informo para a DLL a sefaz de destino;
2 - Como eu passo o certificado digital para a DLL ;
3 - Enviando o XML pronto a DLL se encarrega do processamento e impressão do cupom, ou eu devo chamar as funções que realizam a impressão ;

basicamente é isso e parabéns pelo projeto.

**Comment by adeniltonbs** [comment]
Boa tarde @dongustavosccp,
Dê uma olhada no código dos botões "Criar e Enviar 3.0", "Carregar XML e Enviar" e "DANFE NFCe Normal" da aplicação de demonstração de uso.

Sendo mais específico, quanto as suas perguntas:
1 - Como eu informo para a DLL a sefaz de destino?
R: Você precisa ter uma instância da classe ConfiguracaoServico. Note que no exemplo dos botões "Criar e Enviar 3.0", "Carregar XML e Enviar", uma instância dessa classe é passada como parâmetro para o construtor da classe ServicosNFe. Você informa a UF de destino na propriedade cUF da classe ConfiguracaoServico.

``` cs
        /// <summary>
        ///     Estado de destino do webservice
        /// </summary>
        public Estado cUF { get; set; }
```

2 - Como eu passo o certificado digital para a DLL?
R: Na mesma classe ConfiguracaoServico, propriedade Certificado. Note, na aplicação de demonstração, a guia "Certificado". Dê atenção aos Bindings no xaml.
![image](https://cloud.githubusercontent.com/assets/6733483/16467886/c0425238-3e1f-11e6-89b6-f96f22595a09.png)

3 - Enviando o XML pronto a DLL se encarrega do processamento e impressão do cupom, ou eu devo chamar as funções que realizam a impressão?
R: O método de "envio" (servicoNFe.NFeAutorizacao), apenas consome o serviço NFeAutorizacao. A impressão é feita pela biblioteca NFe.Impressao. Felizmente a aplicação de demonstração de uso mostra como realizar a impressão de um xml já autorizado. Você pode ver o código do botão "DANFE NFCe Normal".

**Comment by adeniltonbs** [comment]
Talvez esse issue possa te ajudar: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114

**Comment by dongustavosccp** [comment]
@adeniltonbs obrigado pela pronta resposta.
