### ISSUE TITLE
Tag Id em infNFe com problemas

### ISSUE THREAD

**Issue by saulogpacifico** [ZeusAutomacao/DFe.NET#1511]
Pessoal, estou com um problema meio estranho. Uma nota emitida pelo componente do Zeus, no momento que vou imprimir o DANFE (Fast) a chave de acesso corta alguns números. Pensei que pudesse ser meu sistema com algum erro, então, testei a impressão do DANFE via XML diretamente no app de testes da solução do Zeus e a impressão permaneceu cortada. Quando eu testei a impressão pelo app que gera o DANFE em HTML a impressão da chave de acesso saiu correta.

Fui analisar o XML diretamente da Sefaz e compará-lo com o XML gerado pelo Zeus e percebi uma ligeira diferença:

XML SEFAZ:
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/73799866/89998380-ebf2-4021-a603-f1d1fb80b199)

XML ZEUS:
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/73799866/621c7462-1c8a-4737-8aa5-886fb795fda9)

Logo, constatei que o "corte" dos números da chave de acesso é referente a chamada do método `Substring` no trecho `var chave = Substring(((String)Report.GetColumnValue("NFe.NFe.infNFe.Id")), 3);` conforme a imagem abaixo

Trecho de código do arquivo NFeRetrato.frx:
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/73799866/c935d5c2-3817-4a57-881d-1ebc8ae53207)

Daí a minha dúvida, por qual motivo faltou "NFe" antes do início da chave de acesso na tag "infNFe"? Lembrando que esse foi um problema pontual, não ocorreu em outras notas.

**Comment by danilobreda** [comment]
Talvez você não esteja recebendo respostas pois a comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/ 
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Verifiquei algumas classes que manipulam essa tag, mas não encontrei nada de anormal. Parece ser um problema pontual como você citou, e até o momento, não recebemos outros relatos semelhantes.

Se o problema ainda persiste em outros casos, e puder fornecer mais detalhes sobre o que aconteceu, ou se essa nota tem alguma particularidade em comparação a outras, isso nos ajudaria bastante a identificar o problema. Infelizmente, como é algo raro e não temos mais informações, fica difícil encontrar a causa exata.

Agradeço pela sua compreensão e colaboração!
