### ISSUE TITLE
 Csosn400

### ISSUE THREAD

**Issue by zeusvb** [ZeusAutomacao/DFe.NET#1516]
Pessoal não sei se passou batido ou foi proposital mais não existe a classe  Csosn400.

**Comment by danilobreda** [comment]
Talvez você não esteja recebendo respostas pois a comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

A classe mencionada não existe porque o CSOSN 400 utiliza as mesmas tags do CSOSN 102. No MOC da SEFAZ, é especificado que, ao informar o CSOSN 400, deve-se usar o campo ICMSSN102. Por isso, não há necessidade de criar um comportamento específico para o CSOSN 400.

![image](https://github.com/user-attachments/assets/a5fdfa90-40d5-4ba3-a357-166bcd265ce8)

Qualquer dúvida, só falar.
