### ISSUE TITLE
Validação XML Autorizacao xCampo

### ISSUE THREAD

**Issue by hbdbim** [ZeusAutomacao/DFe.NET#152]
Quando preenchido as lista obsCont e obsFisco da classe infAdic ao validar contra o schema estava retornando invalido.
Correção anotar xmlattribute nos campos xCampo:
public class obsCont
    {
        /// <summary>

        ///     Z05 - Identificação do campo
        /// </summary>

        [XmlAttribute]
        public string xCampo { get; set; }

```
    /// <summary>
    ///     Z06 - Conteúdo do campo
    /// </summary>
    public string xTexto { get; set; }
}
```

public class obsFisco
    {
        /// <summary>

        ///     Z08 - Identificação do campo
        /// </summary>

        [XmlAttribute]
        public string xCampo { get; set; }

```
    /// <summary>
    ///     Z09 - Conteúdo do campo
    /// </summary>
    public string xTexto { get; set; }
}
```

**Comment by adeniltonbs** [comment]
@hbdbim poderia fazer um pull request com a sugestão?

**Comment by hbdbim** [comment]
PULL  REQUEST #153
