### ISSUE TITLE
Retorno cancelamento e carta correcao

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1520]
Oi bom dia. Alguem sabe como tratar o retorno do evendo de cancelamento, carta de correcao

Pra retornar o  xml, chave e protocolo do evento

**Comment by danilobreda** [comment]
Talvez você não esteja recebendo respostas pois a comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Notei que já conseguiu esclarecer sua dúvida. Assim, estarei fechando essa issue.

Qualquer dúvida, só falar. 😉
