### ISSUE TITLE
GetTotal

### ISSUE THREAD

**Issue by PedroCanizela** [ZeusAutomacao/DFe.NET#1521]
Ola uma duvida para todos os tipos cst ou csosn eu preciso declarar no metodo ou posso totalizar de uma maneira geral

            foreach (var produto in produtos)
            {
                if (produto.imposto.IPI != null && produto.imposto.IPI.TipoIPI.GetType() == typeof(IPITrib))
                    icmsTot.vIPI = icmsTot.vIPI + ((IPITrib)produto.imposto.IPI.TipoIPI).vIPI ?? 0;
                if (produto.imposto.ICMS.TipoICMS.GetType() == typeof(ICMS00))
                {
                    icmsTot.vBC = icmsTot.vBC + ((ICMS00)produto.imposto.ICMS.TipoICMS).vBC;
                    icmsTot.vICMS = icmsTot.vICMS + ((ICMS00)produto.imposto.ICMS.TipoICMS).vICMS;
                }
                if (produto.imposto.ICMS.TipoICMS.GetType() == typeof(ICMS20))
                {
                    icmsTot.vBC = icmsTot.vBC + ((ICMS20)produto.imposto.ICMS.TipoICMS).vBC;
                    icmsTot.vICMS = icmsTot.vICMS + ((ICMS20)produto.imposto.ICMS.TipoICMS).vICMS;
                }
                //Outros Ifs aqui, caso vá usar as classes ICMS00, ICMS10 para totalizar
            }

**Comment by danilobreda** [comment]
Talvez você não esteja recebendo respostas pois a comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Notei que já conseguiu esclarecer sua dúvida. Assim, estarei fechando essa issue.

Qualquer dúvida, só falar. 😉
