### ISSUE TITLE
MDF-e Recepção Sincrona NT2024.001

### ISSUE THREAD

**Issue by marcianobandeira** [ZeusAutomacao/DFe.NET#1526]
Boa tarde, alguem sabe se o MDF-e já está com a opção de envio de forma síncrona?
Atualmente, ao tentar enviar de forma assíncrona recebo a seguinte mensagem:
996 Rejeição: Serviço de recepção de lotes desativado (NT2024.001). Migrar para recepção sincrona!

**Comment by adeniltonbs** [comment]
Boa noite, a implementação da NT2024.001 será integrada após a finalização de https://github.com/ZeusAutomacao/DFe.NET/pull/1519, em revisão no momento.

**Comment by marcianobandeira** [comment]
Show, obrigado

**Comment by adeniltonbs** [comment]
PR #1519 finalizado e NT2024.001 implementada no PR #1515.
