### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by lucasfecap** [ZeusAutomacao/DFe.NET#154]
Opa tudo bem, estou com um pequeno problema.. 

Error   3   Metadata file 'C:\Users\lucas\Desktop\ZEUS NFE\Zeus.Net.NFe.NFCe-master\NFe.Servicos\bin\Debug\NFe.Servicos.dll' could not be found C:\Users\lucas\Desktop\ZEUS NFE\Zeus.Net.NFe.NFCe-master\NFe.AppTeste\CSC   NFe.AppTeste

Error   1   Unexpected character '$'    C:\Users\lucas\Desktop\ZEUS NFE\Zeus.Net.NFe.NFCe-master\NFe.Servicos\ServicosNFe.cs    112 21  NFe.Servicos

Error   2   Unexpected character '$'    C:\Users\lucas\Desktop\ZEUS NFE\Zeus.Net.NFe.NFCe-master\NFe.Servicos\ServicosNFe.cs    152 41  NFe.Servicos

VS 2013 Ultimate

**Comment by adeniltonbs** [comment]
Alteração feita no commit 67ada7f740d43f9d8e79f5d0b66be4551a749d87. Favor atualize os fontes e tente novamente.

**Comment by lucasfecap** [comment]
Opa Adenilton, sou o programador.looko do Forum Acbr que te mandei msg.. eu acabei de baixar o link do git que você enviou..

**Comment by adeniltonbs** [comment]
Percebi :)

**Comment by lucasfecap** [comment]
Então o que você subiu já nao esta atualizado?? o problema do Fast Report resolvi add as references só que sobraram esses 3 probleminhas rsrs

**Comment by adeniltonbs** [comment]
Então, enviei um commit 67ada7f740d43f9d8e79f5d0b66be4551a749d87 resolvendo esse caso informado nesse issue. Atualizou os fontes novamente?

**Comment by lucasfecap** [comment]
Opa Adenilton, desculpe!! 
Agora foi!! muito obrigado viu!!

**Comment by adeniltonbs** [comment]
Por nada, qualquer coisa abra um issue.
