### ISSUE TITLE
Desoneracao ST ICMSGeral

### ISSUE THREAD

**Issue by ricardopdv** [ZeusAutomacao/DFe.NET#1543]
pessoal, tranquilo ?
vi tags em um xml que nao estao no ICMSGeral.
sao as vICMSStDeson, motDesICMSST
poderiam verificar ? ou coloco e faco um PR ?

**Comment by Valmir-Cunha** [comment]
Boa tarde, @ricardopdv .

Esses campos estão presentes nas classes dos ICMS específicos para cada CST que os utilizam. No entanto, caso queira realizar a adição e abrir um PR com essas informações, fique à vontade. Isso facilitará a conversão do ICMSGeral para as classes específicas que utilizam essas tags.

**Comment by danilobreda** [comment]
@ricardopdv  Talvez você não saiba mas a comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

Adicionei as tags no ICMSGeral, nuget liberado.

**Comment by ricardopdv** [comment]
opa! nao sabia. vou fazer os testes. obrigado pelo retorno.

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Será adicionado os campos mencionados, obrigado por reportar.
Também estamos ajustando o Nuget para ser liberado em breve.

Agradeço pela sua colaboração! 😉
