### ISSUE TITLE
Mensagem "DEMO VERSION" no topo do layout da danfe do MDFE ao imprimir

### ISSUE THREAD

**Issue by ElaineZago** [ZeusAutomacao/DFe.NET#1544]
Bom dia!
Está aparecendo a mensagem de DEMO VERSION no topo da impressão da danfe do MDFE e eu gostaria de saber como remover, por favor.
Segue a imagem anexo do exemplo mencionado.
Obrigada!

![image](https://github.com/user-attachments/assets/18549f6f-9b2c-4120-9fba-d2bd72638291)

**Comment by AgnaldoSilva0** [comment]
Boa tarde, @ElaineZago, tudo bem?

Normalmente, essa mensagem é exibida em ambientes de produção quando não há uma licença do FastReport. Atualmente, a aplicação de teste da biblioteca usa o projeto do FastReport, que exige uma licença para uso.

No entanto, a biblioteca possui o OpenFast, um projeto de código aberto que você pode encontrar em MDFe.Damdfe.OpenFast. Você pode ajustar seu projeto para usar o OpenFast, evitando assim problemas com a mensagem de licença. 😄

Caso não queira usar o OpenFast, tem a opção também de adquirir as DLL's do FastReport, onde você terá as DLL's de impressão com licença.

**Comment by andrebts** [comment]
O issue será fechado uma vez que este é o comportamento correto da biblioteca e opções para atender a necessidade foram propostas.
