### ISSUE TITLE
Atualização do pacote Nuget Zeus.NFe.NFCe para refletir os novos tipos de pagamento PIX

### ISSUE THREAD

**Issue by cleberferretti** [ZeusAutomacao/DFe.NET#1546]
Olá!
A versão 2024.3.1.1550 do pacote Nuget Zeus.NFe.NFCe não contém os novos tipos de pagamento PIX (dinâmico e estático).
Eu vi que o código fonte já foi ajustado.
Qual a previsão para a publicação de uma nova versão atualizada do pacote nuget Zeus.NFe.NFCe?

**Comment by danilobreda** [comment]
A comunidade realizou um fork https://github.com/Hercules-NET/ZeusFiscal/
Segue comunicado: https://github.com/Hercules-NET/ZeusFiscal/issues/1

O nuget utilizado é [Hercules.NET.Nfe.Nfce](https://www.nuget.org/packages/Hercules.NET.Nfe.Nfce/)

**Comment by marcianobandeira** [comment]
@danilobreda boa noite.. esse fork Hércules vai substituir o projeto atual? Ou serão dois projetos a partir de agora, cada um caminhando para seu lado?

**Comment by danilobreda** [comment]
@marcianobandeira A comunidade que decide e vai para onde achar mais conveniente.

**Comment by marcianobandeira** [comment]
Perfeito, obrigado @danilobreda

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

O NuGet do Zeus DFe.NET está passando por ajustes e estará disponível em breve.
Notificaremos assim que estiver liberado.

Agradeço pela sua compreensão! 😉
