### ISSUE TITLE
Problema com Manifestação Ciência da Operação

### ISSUE THREAD

**Issue by andresitesSP** [ZeusAutomacao/DFe.NET#1547]
Estou tentando fazer RecepcaoEventoManifestacaoDestinatario , mas o método dá erro Serviço RecepcaoEventoManifestacaoDestinatario, versão 1.00, não disponível para a UF AN, no ambiente de Homologação para emissão tipo , documento: !'
Estou seguindo o exemplo de console app para .net core 6.

Tentei com outros estados e ambiente de homologação e testes.
Talvez falte algo na configuração. No exemplo não achei o 'config.xml'
Se alguém puder ajudar, agradeceria demais!
Meu código 
`string chave = "a chave";
var cert = new X509Certificate2("caminho", "senha");
using (var servicoNFe = new ServicosNFe(_configuracoes.CfgServico, cert))
{

    var retornoManifestacao = servicoNFe.RecepcaoEventoManifestacaoDestinatario(idlote: 1,
                                                                            sequenciaEvento: 1,
                                                                            chavesNFe: new string[] { chave },
                                                                            nFeTipoEventoManifestacaoDestinatario: NFeTipoEvento.TeMdCienciaDaOperacao,
                                                                            cpfcnpj: "05831108000220",
                                                                            justificativa: null
                                                                            );

    Console.WriteLine($"Retorno da manifestação: {retornoManifestacao.RetornoStr}");
}`

**Comment by elieltonbitencourt** [comment]
Adicione no seu "_configuracoes.CfgServico" o modelo e tipo emissão:
_configuracoes.CfgServico.ModeloDocumento = ModeloDocumento.NFe; // aqui o modelo do documento que voce está buscando
_configuracoes.CfgServico.tpEmis = TipoEmissao.teNormal;

**Comment by andresitesSP** [comment]
> Adicione no seu "_configuracoes.CfgServico" o modelo e tipo emissão: _configuracoes.CfgServico.ModeloDocumento = ModeloDocumento.NFe; // aqui o modelo do documento que voce está buscando _configuracoes.CfgServico.tpEmis = TipoEmissao.teNormal;

Muito obrigado pela resposta. Agora deu esse erro:
RecepcaoEvento 1.0 não está implementado para .net standard, apenas .net framework'

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem? @andresitesSP 

Você conseguiu resolver? Ou ainda está passando pelo problema?

**Comment by andresitesSP** [comment]
Oi, já consegui, obrigado
________________________________
De: Agnaldo Silva ***@***.***>
Enviado: terça-feira, 10 de setembro de 2024 19:03
Para: ZeusAutomacao/DFe.NET ***@***.***>
Cc: andresitesSP ***@***.***>; Mention ***@***.***>
Assunto: Re: [ZeusAutomacao/DFe.NET] Problema com Manifestação Ciência da Operação (Issue #1547)


Olá, tudo bem? @andresitesSP<https://github.com/andresitesSP>

Você conseguiu resolver? Ou ainda está passando pelo problema?

**Comment by AgnaldoSilva0** [comment]
Nós que agradecemos, e desculpa a demora para um retorno, qualquer dúvida, só falar.  😉
