### ISSUE TITLE
Sem comunicação com serviço de distribuição e manifestação

### ISSUE THREAD

**Issue by D13G0M1R4ND4** [ZeusAutomacao/DFe.NET#1549]
Bom dia pessoal, todos bem?

Estou com o erro da imagem ao tentar consultar ou manifestar destinatário, mais alguém com esse erro por ai?
Poderiam me ajudar a entender o que pode estar acontecendo?
![Captura de tela 2024-08-08 084137](https://github.com/user-attachments/assets/b06ded09-f896-4a20-9534-393bf9a5aed7)

**Comment by adeniltonbs** [comment]
Bom dia @D13G0M1R4ND4, esse serviço está instável recentemente. Infelizmente ele não fica sendo monitorado em https://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=0.00&tipoConteudo=P2c98tUpxrI=. Mas uma forma de verificar se ele está funcionando, é tentar acessar o serviço diretamente no navegador, pelo link do serviço `NFeDistribuicaoDFe`, disponível em:
**Ambiente de homologação:** https://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=OUC/YVNWZfo=
**Ambiente de produção:** https://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=OUC/YVNWZfo=

Ao acessar o link do serviço e informar o certificado, caso o serviço esteja funcionando, o resultado deve semelhante à imagem abaixo:
![image](https://github.com/user-attachments/assets/2052c554-be0e-48c6-976f-4b9120d8046f)


Uma outra opção é aumentar um pouco o timeout, conforme opção indicada na aplicação de demonstração:
![image](https://github.com/user-attachments/assets/70838320-6203-4c79-8aaf-59743b008c77)

**Comment by D13G0M1R4ND4** [comment]
@adeniltonbs muito obrigado pela dica, alterar o TimeOut funcionou aqui pra mim!
