### ISSUE TITLE
jcsjp

### ISSUE THREAD

**Issue by jcsjp** [ZeusAutomacao/DFe.NET#155]
Adenilton

Aqui apresenta erro ao compilar o projeto, só gera a Nfe.Classes.dll e apresenta erros.

Error   4   The name 'nameof' does not exist in the current context C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\Auxiliar.cs   104 59  NFe.Utils
Error   5   Invalid expression term '.' C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\Email\EmailBuilder.cs 140 32  NFe.Utils
Error   6   Syntax error, ':' expected  C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\Email\EmailBuilder.cs 140 33  NFe.Utils
Error   7   Invalid expression term '.' C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\Email\EmailBuilder.cs 145 33  NFe.Utils
Error   8   Syntax error, ':' expected  C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\Email\EmailBuilder.cs 145 34  NFe.Utils
Error   9   Metadata file 'C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\bin\Debug\NFe.Utils.dll' could not be found    C:\Zeus.Net.NFe.NFCe-master\NFe.Servicos\CSC    NFe.Servicos
Error   10  Metadata file 'C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\bin\Debug\NFe.Utils.dll' could not be found    C:\Zeus.Net.NFe.NFCe-master\Nfe.Impressao\CSC   NFe.Impressao
Error   11  Metadata file 'C:\Zeus.Net.NFe.NFCe-master\Nfe.Impressao\bin\Debug\NFe.Impressao.dll' could not be found    C:\Zeus.Net.NFe.NFCe-master\NFe.AppTeste\CSC    NFe.AppTeste
Error   12  Metadata file 'C:\Zeus.Net.NFe.NFCe-master\NFe.Servicos\bin\Debug\NFe.Servicos.dll' could not be found  C:\Zeus.Net.NFe.NFCe-master\NFe.AppTeste\CSC    NFe.AppTeste
Error   13  Metadata file 'C:\Zeus.Net.NFe.NFCe-master\NFe.Utils\bin\Debug\NFe.Utils.dll' could not be found    C:\Zeus.Net.NFe.NFCe-master\NFe.AppTeste\CSC    NFe.AppTeste

**Comment by adeniltonbs** [comment]
Provavelmente vc está usando o Visual Studio 2013, certo?
Se sim, atualize seus fontes, note que foram feitos dois commits hj que corrigem esses erros para essa versão do VS (na verdade a versão do c# :)).

**Comment by jcsjp** [comment]
Obrigado
Deu certo

**Comment by jcsjp** [comment]
Boa tarde
Consegui gerar as Dlls.
Gostaria de saber a respeito da do uso  da NFe Zeus em meu sistema, se posso homologar aqui no meu estado, se depende de alguma autorização para isso, por causa dos direitos de propriedade. 

```
Em Quinta-feira, 30 de Junho de 2016 15:07, Zeus Automação Comercial <notifications@github.com> escreveu:
```

 Provavelmente vc está usando o Visual Studio 2013, certo?
Se sim, atualize seus fontes, note que foram feitos dois commits hj que corrigem esses erros para essa versão do VS (na verdade a versão do c# :)).—

**Comment by adeniltonbs** [comment]
Fique a vontade para usar a biblioteca, inclusive em software proprietário.
Veja na descrição do projeto que a biblioteca 

> Está licenciada sobre a LGPL.

Veja mais sobre esse tipo de licença em https://pt.wikipedia.org/wiki/GNU_Lesser_General_Public_License

**Comment by jcsjp** [comment]
Ok, muito obrigado pela atenção. 

```
Em Sexta-feira, 1 de Julho de 2016 15:43, Zeus Automação Comercial <notifications@github.com> escreveu:
```

 Fique a vontade para usar a biblioteca, inclusive em software proprietário.
Veja na descrição do projeto que a biblioteca 
Está licenciada sobre a LGPL.
Veja mais sobre esse tipo de licença em https://pt.wikipedia.org/wiki/GNU_Lesser_General_Public_License—

**Comment by adeniltonbs** [comment]
@jcsjp Suas mensagens estão ficando repetidas. Acredito que deve estar respondendo diretamente do e-mail. Se for esse o caso, evite fazer isso. Responda aqui, diretamente no git.
