### ISSUE TITLE
Erro ao transmitir nfce em contingencia estadao SP

### ISSUE THREAD

**Issue by LosDeveloper** [ZeusAutomacao/DFe.NET#1551]
**Rejeição: Parâmetro do QR-Code divergente da Nota Fiscal (digVal)**
O estado de SP tb aceita contingencia ofline desde o mes passado, mas tenho essa rejeição acima qdo tento autorizar a nfce q foi feita em contingencia. Alguem pode me ajudar

ATENÇÃO - UTILIZAÇÃO DO SAT E NFC-e
O Artigo 25 da  [Portaria CAT-147/2012](https://legislacao.fazenda.sp.gov.br/Paginas/pcat1472012.aspx) foi revogado e, portanto, não se torna mais obrigatório ao contribuinte possuir um SAT reserva Ativo. O contribuinte, nesses casos, poderá optar em ter um SAT reserva Ativo ou utilizar a NFC-e ou a ​NF-e.

Com a revogação da [Portaria CAT-12/2015](https://legislacao.fazenda.sp.gov.br/Paginas/pcat122015.aspx) pela [Portaria SRE-40/2024](https://legislacao.fazenda.sp.gov.br/Paginas/Portaria-SRE-40-de-2024.aspx) não se faz mais necessário ter um SAT Ativo para credenciamento na NFC-e. 

Em caso de falha na internet, que inviabilize a autorização da NFC-e,  o contribuinte poderá:

a. utilizar uma segunda internet cabeada;

b. utilizar uma rede móvel (ancoragem com smartphone);

c. gerar um CF-e-SAT por meio de equipamento SAT;

d. gerar uma NFC-e offline nos termos da [Portaria SRE-40/2024](https://legislacao.fazenda.sp.gov.br/Paginas/Portaria-SRE-40-de-2024.aspx)​​.

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Notei que já conseguiu esclarecer sua dúvida. Assim, estarei fechando essa issue.

Qualquer dúvida, só falar. 😉
