### ISSUE TITLE
ICMSGeral CST inconsistente

### ISSUE THREAD

**Issue by gustavo-campos** [ZeusAutomacao/DFe.NET#1556]
Quando o xml da nota não tem a tag cst preenchida, o campo CST da classe ICMSGeral está retornando o valor Cst00, e isso esta gerando inconsistência, deveria ser um valor que não foi preenchido CstUndefined exemplo pois o valor Cst00 é uma opção, teria como realizar essa modificação?

**Comment by AgnaldoSilva0** [comment]
Olá, tudo bem?

Se entendi corretamente, acredito que esse comportamento ocorre porque, quando o valor não é informado, o enumerador retorna o valor padrão. Concordo que é essencial garantir que os campos obrigatórios sejam preenchidos corretamente pelo emissor. Contudo, tenho algumas preocupações quanto à inserção de valores indefinidos em campos obrigatórios.

Isso porque alguns softwares podem estar programados para utilizar o valor padrão, como a CST00, em determinadas situações. Alterar esse comportamento poderia gerar problemas de compatibilidade, além de potencialmente causar falhas em sistemas que dependem dessa lógica.

De qualquer forma, vou aguardar a resposta de outras pessoas para que possamos analisar melhor a viabilidade dessa mudança.

Muito obrigado pela observação e sugestão!

**Comment by gustavo-campos** [comment]
Olá, tudo e com vc?
entendo a sua preocupação, poderia então ter uma flag booleano para identificar se o campo estava ou não preenchido no xml, com isso consigo realizar a validação do meu lado do sistema, onde posso verificar se o valor foi preenchido pelo zeus ou não, teria como?

**Comment by MauricioSuporte** [comment]
Olá, tudo bem?

Analisando o seu issue, o comportamento descrito parece estar relacionado ao comportamento padrão do enumerador quando a tag CST não está preenchida no XML. Concordo com o que o Agnaldo comentou anteriormente: definir valores indefinidos em campos obrigatórios pode trazer impactos significativos para outros usuários da biblioteca, uma vez que alguns sistemas podem depender da lógica atual.

Entendo a sua necessidade de identificar se o campo foi ou não preenchido no XML, e uma possível solução seria implementar a flag booleana, conforme sugerido. Essa abordagem poderia permitir que você controle a lógica do seu lado, sem alterar o comportamento padrão da biblioteca para todos os usuários.

Se você acredita que essa mudança seria benéfica, você pode implementar a modificação necessária e enviar um PR (Pull Request) para análise. Assim, poderemos discutir a inclusão da funcionalidade de uma maneira que beneficie todos.

Muito obrigado por levantar esse ponto!
