### ISSUE TITLE
Probleminha

### ISSUE THREAD

**Issue by lucasfecap** [ZeusAutomacao/DFe.NET#156]
Opa Adenilton tranquilo? estou com um probleminha na hora de criar e enviar e na hora de criar e salvar a nota nfe 3.10.. estou utilizando o NET Framework 4.5..

Print Screen: http://i1368.photobucket.com/albums/ag170/lucasfecap/PRINTSCREEN_zpsg6yg0b3b.jpg

**Comment by adeniltonbs** [comment]
Aparentemente você não preencheu todas as informações necessárias. Por exemplo, no erro informado está faltando o Identificador do CSC e o CSC. Veja o issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114, no trecho

> Aqui  cabe explicação a respeito do "Identificador do CSC:" e do "CSC". Estas informações são obtidas junto à Secretaria da Fazenda de seu Estado. Algumas Sefazes disponibilizam esta informação em seu portal em área restritiva, que pode ser acessada usando o certificado da empresa. Mais esclarecimentos, consulte o contador.
> Obs: 
> Estes dois campos são usados na montagem do Qr-Code do DANFE da NFCe;
> A biblioteca não tem suporte ao DANFE da NFe até o presente momento;

**Comment by adeniltonbs** [comment]
Por favor, anexe o xml que estais a tentar enviar.
Na aplicação de demonstração de uso, esse xml fica na guia "Envio".
![image](https://cloud.githubusercontent.com/assets/6733483/16524721/8b7a1598-3f7f-11e6-8f98-c5ada15021bc.png)

**Comment by lucasfecap** [comment]
Adenilton, segue o xml da nfe.
https://mega.nz/#!txA0iCDb!X1O5DejU_kIXlRtJ91dfSjGgxFCOu7pDFFVgDzwOiPQ

**Comment by adeniltonbs** [comment]
Cara o xml que você me enviou não é o mesmo do erro da imagem.

**Comment by adeniltonbs** [comment]
Deixa o xml da NFe pra lá, mande por favor o xml de configuração da aplicação de demonstração. Fica no diretório .exe da aplicação com o nome "configuracao.xml"

**Comment by adeniltonbs** [comment]
Pode mandar em private, se desejar

**Comment by lucasfecap** [comment]
Então adenilton testei aqui em Carregar XML e Enviar e ele foi com sucesso aparentemente, retornou mensagens de sucesso..

**Comment by leandrossantos** [comment]
Para consultas no ambiente de homologação o link é http://hom.nfe.fazenda.gov.br/portal/principal.aspx

**Comment by lucasfecap** [comment]
Muito Obrigado!! deu certinho carregando e enviando o xml.. já a opção do Criar/Enviar 3.0 não obtive sucesso.. a configuracao.xml está com tudo certinho..

**Comment by adeniltonbs** [comment]
A biblioteca é completamente funcional, como diz na descrição, cria/envia/cancela/inutiliza/etc... Para te ajudarmos, por favor nos envie detalhes do problema que vc está tendo. Também sugiro dar uma lida com calma no [ Manual de Orientação do Contribuinte](http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=)

**Comment by lucasfecap** [comment]
Opa Adenilton, vou dar uma olhada com calma mesmo no Manual..
Muito obrigado!
