### ISSUE TITLE
Evento código 110115

### ISSUE THREAD

**Issue by Joao-SouzaDev** [ZeusAutomacao/DFe.NET#1563]
Olá,

Gostaria de sabe se o Evento 110115 (evInclusaoDFeMDFe) já esta disponível no repositório, pois estou analisando e não encontrei o uso do schema necessário.

Alguém sabe me dizer?

**Comment by Valmir-Cunha** [comment]
Olá,  
Verifique se o evento seria o representado pela classe `MDFeEvIncDFeMDFe` em `MDFe.Classes.Informacoes.Evento.CorpoEvento`.

Caso esteja buscando os schemas, eles estão disponível em `MDFe.AppTeste`.

**Comment by Joao-SouzaDev** [comment]
Achei aqui, muito obrigado.
