### ISSUE TITLE
Certificado A1

### ISSUE THREAD

**Issue by homerokzam** [ZeusAutomacao/DFe.NET#157]
Alguém sabe se eu pessoa física consigo um certificado A1? Ou se existe um certificado genérico para teste?

Obrigado.

**Comment by adeniltonbs** [comment]
http://www.nfe.fazenda.gov.br/portal/perguntasFrequentes.aspx?tipoConteudo=k/E5BakB80o=

Veja onde diz:
O e-CPF pode ser usado como certificado digital para a NF-e? E o e-CNPJ?

O certificado digital a ser utilizado deverá ser de pessoa jurídica, do tipo A1 ou A3. O e-CPF não pode ser utilizado para a NF-e; já o e-CNPJ pode, no entanto não é o mais indicado.
