### ISSUE TITLE
Preenchimento

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#158]
Boa noite,
Venho do Delphi, mais precisamente do Delphi 7 e até então utilizo componentes do ACBr. Preencho impostos (como o Cofins que é mais simples e usarei de exemplo) passando o Cst, Base, aliquota, etc.

Estudei o AppTeste na questão do preenchimento dos campos e a melhor forma que encontrei de preencher o Cofins foi esta:

[getcofins.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/362704/getcofins.txt)

Eu a considero um tanto quanto extensa... existe alguma forma melhor de preenchimento?

PS: Minha classe Cofins tem Cst, Base e Aliquota e é o que guardo no banco de dados, no caso estou preenchendo o componente partindo da minha classe.

[]'s

**Comment by adeniltonbs** [comment]
Para diminuir, só usando o default dentro do switch, onde o número de casos for maior.

Ademais, observe o seguinte:
Na construção desta biblioteca houve a preocupação que cada elemento fosse o mais próximo possível do manual de orientação do contribuinte.
Por exemplo, na seção de tributação de COFINS do manual, você encontra que essa tributação pode ser dos tipos: COFINSAliq, COFINSQtde, COFINSNT e COFINSOutr. Cada tipo tem campos específicos. Nesta biblioteca isso fica transparente para Vc. Mas se olhares no ACBR verás que há um só tipo chamado "COFINS" e este possui os atributos de todos os tipos mencionados acima. Um pouco confuso na minha opinião. 

Embora esta última abordagem seja, aparentemente, mais simples de usar, induz o desenvolvedor a erros.

**Comment by marcosgerene** [comment]
Boa tarde @adeniltonbs,

Concordo com seu ponto de vista, a questão levantada não era sobre uma possível mudança na estrutura, eu ainda engatinho no C# estou no meu primeiro grande projeto, mesmo que quisesse não teria como opinar.

A questão era simplesmente uma dúvida de preenchimento mesmo, eu queria saber apenas se eu não estava fazendo de uma forma "primitiva de mais".

Obrigado pela ajuda.

PS: Hoje o que você utiliza para a impressão do Danfe em A4?

**Comment by adeniltonbs** [comment]
Uso essa biblioteca em produção somente para NFCe no momento. A impressão A4 foi iniciada em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/Danfe_NFe mas está carecendo de voluntários no momento. O pessoal utiliza um modelo feito no crystal reports (https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/101)

**Comment by marcosgerene** [comment]
Obrigado pela ajuda @adeniltonbs
