### ISSUE TITLE
Duvida tributação nfc-e somente simples nacional

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#159]
http://www.fazenda.rj.gov.br/sefaz/content/conn/UCMServer/path/Contribution%20Folders/site_fazenda/informacao/sistemaseletronicos/nfce/Preenchimento_NFC-e.pdf?lve

De acordo com o manual de RJ no caso lá e somente
102, 300 e 500

queria saber se a mesma regra se aplica a todos estados? somente simples nacional.

**Comment by orochasamuel** [comment]
@robertorp acho que todos os estados irão adotar essa forma. A Nfc-e é uma operação a consumidor final por isso as combinações de cfop e cst/csosn serão mais restritas.
102 - usado para vendas tributadas com icms normal.
300 - usado no caso de ter algum benefício ou amparo em lei para imunidade.
500 - usado em vendas de aguas, cervejas e outros produtos do regime da substituição tributária.

Att,
Samuel Rocha
Analista Fiscal

**Comment by mvidaldev** [comment]
vale lembrar que alguns contadores estão querendo obrigar os softwares a destacar no XML o codigo PIS/Cofins para tributação monofásica de bebidas codigo 04
99% dos softwares que eu encontro por ai sai no 49 mesmo mudando para 04.

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Sun, 17 Jul 2016 17:20:29 -0700

**Comment by orochasamuel** [comment]
@brasvidal a forma como você citou é a correta. A maioria registra como 49 pois é um código genérico e não exige detalhamento. Quem registra dessa forma deve ser em operações do SIMPLES NACIONAL.

Empresas do REGIME NORMAL, tributadas pelo Lucro Presumo ou Lucro Real tem que fazer com o 04 pois no PVA da EFD Contribuições já obriga detalhar quais NCMs/Produtos estão sendo informados.

**Comment by robertorp** [comment]
Obrigado a todos
