### ISSUE TITLE
Nfe sem Autorização de uso da SEFAZ

### ISSUE THREAD

**Issue by dzfweb** [ZeusAutomacao/DFe.NET#16]
Olá Adenilton,

uma duvida, Consegui emitir a nfe, transmitir e foi autorizada. Consigo consultar pela chave na sefaz.
Porem ao tentar gerar a danfe pelo XML retornado gerado eu obtenho a informação:

Nfe sem Autorização de uso da SEFAZ

Pesquisei na net e vi que isso ocorre quando eu tento gerar o DANFE com um xml sem protocolo de autorização.

Por que esta ocorrendo isso?

Obrigado novamente.

**Comment by weslley39** [comment]
Quando autorizado o uso da NFe, use o método NfeConsultaProtocolo, passando a chave da NFe, pegue o elemento RetornoCompletoStr.
Em seguida, pegue a string e transforme em objeto usando:

```
var protNFe = FuncoesXml.XmlStringParaClasse<retConsSitNFe>(<<RetornoCompletoStr>>).protNFe;
```

Agora é so "montar" o objeto de NFe autorizada.

```
 var nfeproc = new nfeProc
            {
                NFe = "string da nfe",
                protNFe = protNFe, 
                versao = "versao da nota"
            };
```

Para salvar em xml, vc pode usar o metodo:

```
nfeproc.SalvarArquivoXml("caminho completo onde quer salvar.xml")
```

**Comment by adeniltonbs** [comment]
Isso mesmo, você pode fazer desta forma. Para facilitar, no aplicativo de demonstração tem um exemplo com essa situação.
Dê uma verificada no método do botão "Adicionar nfeProc ao XML", que carrega um xml assinado, consulta pela chave, e monta o objeto "nfeproc", que é o objeto que você vai usar para exportar o XML a ser usado na impressão do DANFE.

Note que você também pode montar o objeto nfeproc a partir do resultado do serviço "NFeRetAutorizacao" (usando o recibo de entrega do lote),  já que este devolve uma Lista de  "protNFe".

Neste caso, se você transmitiu o lote, poderá montar um objeto do tipo "nfeproc" para cada item da lista de  "protNFe".

Para obter a lista de  "protNFe" a partir do serviço "NFeRetAutorizacao" faça: 

``` cs
...
var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
var protNFes = servicoNFe.NFeRetAutorizacao(numero_do_recibo_do_lote).Retorno.protNFe;
foreach (var _protNFe in protNFes)
{
    var nfeproc = new nfeProc { NFe = nfe, protNFe = _protNFe, versao = _protNFe.versao };
    FuncoesXml.ClasseParaArquivoXml(nfeproc, caminho_e_nome_do_arquivo);
}
```

**Comment by dzfweb** [comment]
Certo, muito obrigado pelo retorno, vou testar seguindo a orientação de vocês.

**Comment by dzfweb** [comment]
deu certo pessoal, passando só pra agradecer novamente. Pode fechar o topico.
