### ISSUE TITLE
Modelo Papel A4  - DANFE

### ISSUE THREAD

**Issue by sharpcomputing** [ZeusAutomacao/DFe.NET#160]
Boa noite, 

Com o que é oferecido atualmente, é possivel exportar o PDF da danfe para papel A4?

No código baixado só consegui exportar para ECF. 

Abraços

**Comment by adeniltonbs** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/158

**Comment by leandrossantos** [comment]
@sharpcomputing atualmente o projeto só tem impressão e exportação para a DANFe da NFCe no modelo para mini-impressoras. Para outros formatos e a DANFe da NFe ainda não foi implementado.
