### ISSUE TITLE
Impostos necessários Nfc-e

### ISSUE THREAD

**Issue by wellyngtond2** [ZeusAutomacao/DFe.NET#161]
Olá amigos,
Tenho um software porém não fiscal, é do ramo gastronômico,
gostaria de implantar a nfc-e nele, gostaria de saber quais cadastro de imposto irei precisar,
ex.: quais impostos vão no cadastro de produto etc... gostaria de começar a fazer esses cadastros para 
poder informa-los no lançamento da nfc-e. Espero que fui claro na minha dúvida no mais obrigado.

**Comment by robertorp** [comment]
Talvez ajude

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/159

**Comment by adeniltonbs** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki/Nunca-emiti-uma-NF,-meu-sistema-n%C3%A3o-tem-isso.-Preciso-implantar-NFe-e-agora%3F
