### ISSUE TITLE
impressão de danfe offline uma ou duas vias?

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#162]
Seguinte, estou com uma duvida enquanto aos danfes offline

preciso imprimir uma ou duas vias? 

se duas vias..
tem que especificar se e via cliente e via estabelecimento ? ou somente imprimo duas e pronto

no caso pensei em deixar de imprimir a segunda se precisar de duas, e deixa como relatorio o cara precisou ele tira tudo atravez de um relatorio no sistema

**Comment by adeniltonbs** [comment]
A página 7 do [Manual de Especificações da Contingência Offline para NFC-e - versão 1.2](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=qBEPLOBzMGs=) fala sobre isso.

> No caso de emissão em contingência, é obrigatória a impressão do Detalhe da Venda e
> do DANFE NFC-e, sendo que, nesta hipótese, deverá ser impressa uma segunda via do
> DANFE NFC-e que deverá permanecer a disposição do Fisco no estabelecimento até que
> tenha sido transmitida e autorizada a respectiva NFC-e emitida em contingência. Esta
> obrigação poderá, a critério da Unidade Federada, ser dispensada.
> Esta segunda via deverá estar identificada como “Via do Estabelecimento” conforme
> modelo constante da figura 6 a seguir. Alternativamente a impressão da segunda via do
> DANFE NFC-e quando de emissão em contingência, o contribuinte poderá optar pela
> guarda eletrônica do respectivo arquivo XML da NFC-e.

**Comment by robertorp** [comment]
obrigado.
