### ISSUE TITLE
Adicionar pacote para o .net core

### ISSUE THREAD

**Issue by kidchenko** [ZeusAutomacao/DFe.NET#163]
Olá boa noite, por favor, gostaria de saber se existe intenção de fazer o pacote compatível com o .netcore.

Abraços.

**Comment by adeniltonbs** [comment]
Ainda não parei pra dar uma olhada no  .netcore. Se desejar podes contribuir com código. Seja bem vindo.

**Comment by kidchenko** [comment]
@adeniltonbs no momento estou pesquisando como usar o pacote em uma app .net core, assim que tiver a solução posto aqui, também estou avaliando o esforço pra fazer a migração.

Abraços, espero contribuir sim :)
