### ISSUE TITLE
Implementações futuras

### ISSUE THREAD

**Issue by VanderneySouza** [ZeusAutomacao/DFe.NET#164]
Boa tarde,

Estou analisando o projeto que você implementou e lhe dou parabéns.
Ficou muito bem organizado e de fácil compreensão.

Você tem a intenção de implementar outros serviços como o MDF-e, CT-e entre outros já existente?

Atenciosamente,
Vanderney Souza

**Comment by leandrossantos** [comment]
@VanderneySouza bom dia, eu cheguei até a iniciar esses dois projetos separados, mais por falta de tempo não pude dar continuidade ainda. No momento o que fiz foi apenas gerar as classes de conexão com os WS. Falta todo o restante.

**Comment by adeniltonbs** [comment]
Sim, temos essa intenção. No momento não temos prazo pra isso. Também vai depender da ajuda do pessoal da comunidade. Problema é o tempo como disse o @leandrossantos.
