### ISSUE TITLE
Integração com sistemas fora do .NET framework

### ISSUE THREAD

**Issue by AndrewsFB** [ZeusAutomacao/DFe.NET#165]
Projeto exemplar! muito caprichado.

Estou analisando a viabilidade de portar o emissor de NF-e da empresa aqui para esta biblioteca. Infelizmente trabalhamos com uma tecnologia legada que não suporta recursos da plataforma .NET. Criei um fork para desenvolver uma ideia de como integrar com o Zeus usando um app de linha de comando por baixo dos panos (NFe.Integracao).

A principio pensei em criar os xml´s no sistema legado e importa-los no Zeus. Deixando ele responsável pela comunicação com a SEFAZ.

Alguém tem uma ideia/recurso mais viável para fazer essa integração?

**Comment by marciojmuller** [comment]
Olá!
Estava com o mesmo problema e o que fiz foi criar um emissor de NFe que envia as notas pra mim, fiz então uma aplicação em .Net com o Zeus que monitora um banco de dados ou uma pasta para pegar arquivos, depende do tipo de integração que está disposto a fazer, com os dados da nota, então esta aplicação emite a nota e retorna para a outra aplicação que não suporta .Net o resultado, via banco de dados ou arquivo.

Não criei os XMLs no outro sistema, apenas enviei os dados da nota para esta integração e fiz a aplicação em .NET gerar a nota com o Zeus.

**Comment by AndrewsFB** [comment]
Pensei nisso também. O problema de vigiar uma pasta ou banco de dados é a dependência de uma estrutura externa.

Exemplo: (erp <-> bd_do_erp) ----> (zeus <-> bd_ou_pasta_do_zeus_com_estrutura_intermediaria)

Tenho quatro variáveis ai, sendo que se uma mudar todas as outras terão que ser ajustadas para continuar a suportar o processo.

O ideal seria usar uma estrutura (xml da nfe?) padronizada dentro do próprio Zeus. Assim me preocupo apenas com o lado esquerdo da equação. 
Algo do tipo: ( erp <-> bd_do_erp) ----> zeus

Outro problema é manter um serviço rodando em segundo plano para vigiar a estrutura, o defender tem feito estragos sérios nesse tipo de aplicativo nas versões mais recentes do windows. Por isso optei por uma linha de comando que é executada somente no momento da emissão.

O lance é que gostaria de fazer algo facilmente portável pois temos a intenção de recriar nosso erp numa plataforma mais recente em breve. Isso pode me dar muito ou pouco trabalho no futuro, tudo depende da decisão de agora.

Inicialmente criei um builder que desserializa o xml no formato das classes do Zeus. Sendo elas padronizadas no layout da sefaz. Fazendo assim qualquer um mexe. O único pré-requisito seria conhecer o manual da nfe para formar as strings com xml no projeto que estiver consumindo o Zeus.
