### ISSUE TITLE
Mudança na URL de Consulta SEFAZ-GO (NFC-e)

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#166]
http://www.nfe.go.gov.br/post/ver/213515/alteracao-na-url-de-consulta-nfc-e

Alteração na URL de Consulta NFC-e19/07/2016 15h13 - Atualizado em 19/07/2016 15h20
A SEFAZ/GO informa que será alterada a URL do site de Consulta NFC-e em homologação e produção para as seguintes URLs:

Homologação: http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe

Produção: http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe

Em homologação a consulta estará disponível a partir do dia 25/07 e em produção dia 01/08.

Durante esse período a SEFAZ/GO irá retirar a validação da NF-e da URL do QR Code até os emissores se adequarem.

No dia 01/08/2016 a validação será novamente estabelecida.

As empresas que não se adequarem terão suas NFC-e rejeitadas pela seguinte regra de validação:

Rejeição 395: Endereço do site da UF da Consulta via QR-Code diverge do previsto.

**Comment by adeniltonbs** [comment]
Que prazo bom hein. 19/07/2016 - 01/08/2016.
