### ISSUE TITLE
Portável?

### ISSUE THREAD

**Issue by matheusssilva** [ZeusAutomacao/DFe.NET#167]
Será possível portá-la para linux com .net Core ou Mono?

**Comment by adeniltonbs** [comment]
@matheusssilva Terás que pesquisar se essas plataformas suportam as referências desta biblioteca.

**Comment by kidchenko** [comment]
@matheusssilva  @adeniltonbs eu abri uma issue #163 sobre usar esse nuget no .core estou avaliando/pesquisando como fazer isso, posso ajudar na portabilidade atualmente trabalho com .net core desde o beta4 quando ainda era dnx, acho que podemos fazer a migração o que acham?

**Comment by adeniltonbs** [comment]
É uma boa ideia. Como não conheço a fundo o projeto .NET core, sabes me informar se todas as funcionalidades da biblioteca podem ser portadas para esta plataforma, para depois serem reutilizadas em aplicações .NET framework? Ex: acesso a certificados A1/A3,
