### ISSUE TITLE
Retorno Transmissão e Salvar NFes

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#168]
Boa noite a todos,

Transmiti hoje as minhas primeira NFs (ainda em homologação), a parte de montar a NFe, transmitir e afins está pronta, mas estou com algumas dúvidas/problemas para pegar o retorno.
1. Existe alguma forma de salvar a nota transmitida de forma individual e não o lote?
2. Ao transmitir, quando pego o retorno com o status teria como o retorno ser "acoplado" ao NFe (tag protNFe no próprio xml, se quiser posto um exemplo para poder explicar melhor)?
3. Setei as opções SalvarXmlServicos para true e preenchi a propriedade DiretorioSalvarXml, porém meus xmls não salvaram (fiz o teste com o AppTeste e salvou), o que faltou preencher pra salvar os xmls?

Obrigado, Marcos Gerene

**Comment by adeniltonbs** [comment]
1 - Existe: As classes NFe e nfeProc possuem as extensões: CarregarDeArquivoXml, ObterXmlString, CarregarDeXmlString e SalvarArquivoXml. Há um exemplo de como salvar o xml de um único objeto NFe na aplicação de demonstração, botão "Criar e Salvar XML 3.0";

2 - A resposta é não e sim. Nenhum dos serviços da NFe retornam o status acolado à NFe. Você pode conferir isso no [Manual de Orientação do Contribuinte - versão 6.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=). Mas a aplicação de demonstração provê um exemplo de como você pode acoplar o objeto nfeProc, a partir do objeto protNFe que é retornado pelos serviços NfeConsultaProtocolo e NFeRetAutorizacao, a um objeto NFe e depois salvar o xml do objeto nfeProc(ideal para persistência). Veja o código do botão "Adicionar proc ao XML" e esse issue 
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/147;

3 - A configuração para salvar os xmls é essa mesma. Debuge e verifique se o objeto ConfiguracaoServico que você está passando para o construtor do objeto ServicosNFe realmente está configurado para isso. Vá na classe ServicosNFe e note que todos os serviços invocam o método SalvarArquivoXml da mesma classe. Debuge esse método para conferir o que está acontecendo.

**Comment by marcosgerene** [comment]
Bom dia @adeniltonbs ,

Então no meu caso as 3 perguntas serão resolvidas somente criando o nfeproc e salvando ele... 

Olhando a insue #147 montei este código:

`var _nfe = GNFe2ZeusNFe(gnfe);
_nfe.Assina();

var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusNFe.ZeusConfig);
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe>() { _nfe });
var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
var _nfeproc = new NFe.Classes.nfeProc() { NFe = _nfe, protNFe = retornoAutorizacao.Retorno.protNFe.FirstOrDefault() };
`

Está certo esta forma para pegar o nfeproc no ato da transmissão?

**Comment by adeniltonbs** [comment]
Sim está certo, desde que você envie apenas uma nota no lote.

**Comment by adeniltonbs** [comment]
retornoAutorizacao.Retorno.protNFe pode conter até 50 itens (pág. 36 do [Manual de Orientação do Contribuinte - versão 6.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=). Cada item refere-se a uma NFe do lote (pode ser enviada até 50 NFe de uma vez em um único lote). Mas nesse caso, como você informou apenas uma nota no lote, o primeiro retorno será sempre referente a única nfe do lote. Note, no entanto, que a lista retornoAutorizacao.Retorno.protNFe pode vir vazia, se houver falha na comunicação com o webservice.

**Comment by marcosgerene** [comment]
var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);

Aqui aonde pede o recibo devo informar desta forma mesmo? somente o numero do recibo ou devo dar mais informações?

**Comment by adeniltonbs** [comment]
Não entendi. 

```
public RetornoNFeRetAutorizacao NFeRetAutorizacao(string recibo)
```

Esse é o método certo?
Veja que só tem um parâmetro, o número do recibo. Esse serviço precisa de pouca coisa, Dê uma olhada na página 35, item 4.2.1 Leiaute Mensagem de Entrada, do [Manual de Orientação do Contribuinte - versão 6.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=) que vais entender por que só precisa de um parâmetro.

**Comment by marcosgerene** [comment]
@adeniltonbs, deu certo, consegui pegar o retorno, muito obrigado pela ajuda, abraço
