### ISSUE TITLE
WebService Homologação NFCE Amazonas

### ISSUE THREAD

**Issue by SilverioMiranda** [ZeusAutomacao/DFe.NET#17]
Me parece que os webservices pra NF-e e NFC-e serão os mesmos, estou certo?

Então, o ambiente de homologação na NFC-e do AM é diferente da NF-e, qual é a melhor solução para adicionar este endereço?

Obrigado

**Comment by adeniltonbs** [comment]
Desculpa a demora, os endereços para emissão de NFCe para a SEFAZ AM são os descritos neste link? http://portalnfce.sefaz.am.gov.br/desenvolvedor/ambiente-de-homologacao-para-desenvolvedores/

Pelo que vi os endereços para o ambiente de produção também são diferentes.

Vou precisar adicionar estes endereços na biblioteca, se quiseres ajudar, as urls dos webservices ficam no pacote "NFe.Servicos", classe DefinicaoWsdl.

**Comment by adeniltonbs** [comment]
Já estou vendo isso aqui, e também vou atualizar as urls do RS que foram alteradas em 08/04/2015.
Assim que concluir aviso neste post.

**Comment by SilverioMiranda** [comment]
Eu já tinha começado a fazer a mudança alguns dias atrás só não acabei

Da uma olhada na definição DefinicaoWsdlCampos em https://github.com/MirandaBrazil/Zeus.Net.NFe.NFCe/blob/master/NFe.Servicos/DefinicaoWSDL.cs e me fala se quer seguir este caminho. Daí por padrão vai ser NF-e nos parâmetros e ir modificando as classes para poder tratar a NFC-e

Vlw

**Comment by adeniltonbs** [comment]
Adicionadas urls do estado de AM e dos demais estados que possuem URLs distintas para NFe e NFCe. Veja o commit c7705a8ac7d33ad7f63090b986eb28afb86515a2 feito em 04/05/2015.
