### ISSUE TITLE
Serviço de Consulta da Relação de Documentos Destinados

### ISSUE THREAD

**Issue by ernanisp** [ZeusAutomacao/DFe.NET#171]
Bom dia, 

Estou começando a desenvolver e me surgiu uma duvida sobre o capitulo 4.11 Web Service – NfeConsultaDest do manual de desenvolvimento de pesquisar as notas fiscais emitidas para o cpnj e das autorização da mesmas. Tem alguma funcionalidade já desenvolvida pra isso, ou posso desenvolver a funcionalidade e compartilhar com a comunidade eu fiquei meio perdido, se puderem me ajudar eu agradeço muito.

**Comment by adeniltonbs** [comment]
Ainda foi implementado. Está no TODO do README.md deste projeto. Seja bem vindo e fique a vontade para implementar na biblioteca, caso deseje.

Caso deseje implementar, certifique-se de seguir o modelo dos demais webservices e também de documentar as classes e atributos. Após isso só fazer um pull request.

Qualquer dúvida só perguntar.

**Comment by ernanisp** [comment]
Bom dia Adenilton, poderia adicionar no skype para trocar uma ideia, ernanisp@hotmail.com. Gostaria de contribuir com a ferramenta.

**Comment by adeniltonbs** [comment]
Adicionado
