### ISSUE TITLE
Certificado A1 e arquivo .pfx

### ISSUE THREAD

**Issue by devanirgrazino** [ZeusAutomacao/DFe.NET#172]
Senhores, boa tarde.

Eu estou com uma dúvida em relação a utilização do certificado em uma aplicação WEB.

O certificado A1, arquivo .pfx, deverá ser instalado na máquina do usuário que consumirá meu sistema WEB ou o arquivo de certificado deverá ser instalado no servidor WEB da aplicação?

Alguém consegue me ajudar?

Obrigado.

**Comment by rftd** [comment]
O certificado tem que estar no servidor.

**Comment by devanirgrazino** [comment]
Rafael, obrigado pela resposta.

Eu tenho mais dúvidas, no caso, se eu tiver 3 clientes eu tenho que instalar os 3 certificados no servidor certo!?

1 - Estes certificados podem ser do tipo A1 ?
2 - No caso, como eu conseguiria identificar na minha aplicação qual certificado pertence a qual cliente? Existe identificador nestes arquivos?

Desculpe esse tipo de pergunta, mas sou realmente leigo no assunto.

Obrigado.

**Comment by leandrossantos** [comment]
@devanirgrazino o que vc tem que fazer é subir os arquivos pfx dos certificados para uma pasta no servidor web, e então setar o certificado no caminho.

**Comment by devanirgrazino** [comment]
Amigos, bom dia.

Eu entendi agora e agradeço a ajuda de vocês, porém agora tenho outra dúvida.

Em SP teremos que integrar nossos sistemas com o SAT e como eu não entendi muito bem ainda como funciona esse tal de SAT, eu gostaria de saber se os amigos já sabem como eu posso integrar um sistema WEB com esse modem SAT ou se não existe possibilidade.

Obrigado.

**Comment by rftd** [comment]
O Sat funciona por USB.
Você teria que criar um programa/servidor para ficar comunicando com a aplicação web.

**Comment by devanirgrazino** [comment]
Seria mais ou menos como ter um programa client/server, instalado na máquina do meu usuário e este programa além de se comunicar com o SAT efetuar a comunicação com minha aplicação WEB também, passando algo do tipo, SAT já enviado e tals.

Esse é o caminho?

**Comment by rftd** [comment]
sim

**Comment by devanirgrazino** [comment]
Legal amigo, muito obrigado pela ajuda.

**Comment by rftd** [comment]
Lembrando que o sat pode funcionar com mais de 1 estação, mas você teria que efetuar os controles de transação, afinal o sat só processa uma transação por vez.
