### ISSUE TITLE
Emitente sem IE

### ISSUE THREAD

**Issue by francofs** [ZeusAutomacao/DFe.NET#173]
Olá Adenilton, parabéns pelo projeto. Bem completo e fácil de utilizar.

Estou com uma dúvida. Eu possuo certificado digital da minha empresa que é isenta de IE, pois não realiza vendas, apenas presta serviços.

Dessa forma não consigo testar o ambiente de homologação porque ele não aceita deixar o campo IE vazio. Dei uma procurada nas NTs, mas não consegui achar um meio de emitir uma nota em homologação sem informar uma IE válida.

É possível?

**Comment by guidi** [comment]
Minha empresa também é prestadora de serviço, use o webservice do Amazonas pra testar que funciona normal em homologação.

**Comment by francofs** [comment]
Obrigado guidi, vou tentar. Abraços

**Comment by adeniltonbs** [comment]
No manual de orientação do contribuinte, para o campo IE do grupo emit (Emitente) há o seguinte:

> Informar somente os algarismos, sem os caracteres de
> formatação (ponto, barra, hífen, etc.).
> Na emissão de NF-e Avulsa pode ser informado o literal
> “ISENTO” para os contribuintes do ICMS isentos de inscrição no
> Cadastro de Contribuintes de ICMS.

**Comment by francofs** [comment]
Uhhmmm, eu tentei informando ISENTO e não deu certo. Preciso ver como é emitir nota avulsa, ainda não tentei.

**Comment by adeniltonbs** [comment]
Tem um detalhe: Se sua empresa é somente prestadora de serviço então, de acordo com a UF, ela pode não ser autorizada a emitir NFe. 

Veja a regra de validação U01-20 do manual de orientação:
![image](https://cloud.githubusercontent.com/assets/6733483/17554087/981b9766-5edf-11e6-932f-3ab15d1f1276.png)

**Comment by francofs** [comment]
Exatamente, por isso é complicado simular a implementação. Tentei várias formas no ambiente de homologação, sem sucesso. Queria saber se tem alguma combinação de parâmetros que fosse possível para fazer em homologação. Vou tentar do AM como o amigo sugeriu, já que as outras tentativas com varias pesquisas em NTs não deram certo.

**Comment by francofs** [comment]
Confirmo que conseguir emitir NFe utilizando UF autorizadora do Amazonas :)
