### ISSUE TITLE
Dúvida - [Off-Topic]

### ISSUE THREAD

**Issue by DSBRBrasil** [ZeusAutomacao/DFe.NET#174]
Olá Adenilton,
Gostaria de colaborar com o projeto, mas preciso entendê-lo, é possível obter de você?
Me chamo Valnei e juntamente com mais 2 analistas estamos trabalhando em melhorias numa aplicação comercial aqui em Salvador  e optamos por fazê-lo usando o seu projeto.
Desculpa por mandar esta solicitação por essa sessão, mas não conseguimos acha-lo em outro canal.

Valnei

**Comment by adeniltonbs** [comment]
Me add no skype adenilton.bs@gmail.com

**Comment by francofs** [comment]
Chamei

**Comment by DSBRBrasil** [comment]
Adenilton,Adicionado !!! quando podemos conversar ?! Atenciosamente 

```
  From: Zeus Automação Comercial <notifications@github.com>
```

 To: adeniltonbs/Zeus.Net.NFe.NFCe Zeus.Net.NFe.NFCe@noreply.github.com 
Cc: DevSysBrasil v_marinpietri@yahoo.com.br; Author author@noreply.github.com
 Sent: Wednesday, August 10, 2016 9:43 AM
 Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Dúvida - [Off-Topic](#174)

Me add no skype adenilton.bs@gmail.com—

**Comment by adeniltonbs** [comment]
Não apareceu aqui :) qual o seu skype? Me envie por e-mail (adenilton.bs@gmail.com) se desejar.

**Comment by DSBRBrasil** [comment]
Adeniton,È v_marinpietri@yahoo.com.br
 
Atenciosamente 

```
  From: Zeus Automação Comercial <notifications@github.com>
```

 To: adeniltonbs/Zeus.Net.NFe.NFCe Zeus.Net.NFe.NFCe@noreply.github.com 
Cc: DevSysBrasil v_marinpietri@yahoo.com.br; Author author@noreply.github.com
 Sent: Wednesday, August 10, 2016 10:17 AM
 Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Dúvida - [Off-Topic](#174)

Não apareceu aqui :) qual o seu skype? Me envie por e-mail (adenilton.bs@gmail.com) se desejar.—

**Comment by ernanisp** [comment]
Estou também numa fase de estudo para melhoria da ferramenta, não poderia ser criado um grupo para discutir isso e ter um melhor desenvolvimento?

**Comment by adeniltonbs** [comment]
@ernanisp tem skype?

**Comment by adeniltonbs** [comment]
https://join.skype.com/CJbtNPlvbycL

**Comment by ernanisp** [comment]
Tenho sim Adenilton, meu skype é ernanisp@hotmail.com, neste momento estou criando a estrutura de classes para a funcionalidade do metodo 'nfeConsultaNFDest', vamos fazer a ferramenta crescer e ser boa para todos envolvidos. Adiciona no skype.

**Comment by andersons** [comment]
Olá, sou o Anderson.

Tenho interesse em conhecer o projeto e participar. Sou Analista .NET e resido em Salvador-BA. Estou  estudando desenvolver uma ferramenta comercial e este escopo de NFe será otimo.

E-mail / Skype: andersonfsa@live.com

Abraços.

**Comment by DSBRBrasil** [comment]
Ja esta no grupo skype? Atenciosamente 

```
  From: Anderson <notifications@github.com>
```

 To: adeniltonbs/Zeus.Net.NFe.NFCe Zeus.Net.NFe.NFCe@noreply.github.com 
Cc: DevSysBrasil v_marinpietri@yahoo.com.br; Author author@noreply.github.com
 Sent: Saturday, September 3, 2016 7:22 PM
 Subject: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Dúvida - [Off-Topic](#174)

Olá, sou o Anderson.Tenho interesse em conhecer o projeto e participar. Sou Analista .NET e resido em Salvador-BA. Estou estudando desenvolver uma ferramenta comercial e este escopo de NFe será otimo.E-mail / Skype: andersonfsa@live.comAbraços.—

**Comment by jeisonmp** [comment]
Olá Adenilton,

Estou utilizando este projeto no meu PDV e estou fazendo algumas alterações para poder tratar a contingência offline da NFC-e no meu PDV.

Como posso contribuir no projeto?

Meu skype é jeisonmp.

Abraços!
