### ISSUE TITLE
Impressão

### ISSUE THREAD

**Issue by francofs** [ZeusAutomacao/DFe.NET#175]
Pretendo implementar impressão A4 sem dependências, utilizando totalmente o framework .net, tem alguma preferência estrutural?

**Comment by willianas1** [comment]
Eu fiz um componente que recebe um XML e uma Imagem e exibe o DANFE,
funciona de forma totalmente independente.

Assim que tiver um tempo devo disponibilizar pra comunidade.

Fiz utilizando o ReportView do próprio .Net.

## 

Saudações,

_Willian Santos_
Analista de Sistemas | Instrutor de TI
+55 84 98818-6602 <%2B55%2084%208818-6602>

_Ajudemos a poupar papel. Realmente necessita imprimir este e-mail?_

Em 10 de agosto de 2016 09:34, francofs notifications@github.com escreveu:

**Comment by adeniltonbs** [comment]
Estou fazendo algumas alterações no projeto pra ficar mais fácil acoplar relatórios de outros fornecedores. Daqui a pouco envio.

**Comment by adeniltonbs** [comment]
Pronto, terminei a refatoração em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe.DANFE.

Para implementar uma nova opção de impressão, crie uma nova biblioteca na solução, faça referência à biblioteca NFe.Danfe.Base e implemente a interface IDanfe.

**Comment by francofs** [comment]
Maravilha, obrigado.

**Comment by pennellarodrigo** [comment]
@francofs você já implementou a impressão em A4 da danfe da NFe? tenho interesse em colaborar caso ainda esteja em desenvolvimento.

**Comment by adeniltonbs** [comment]
Implementei parte dela. Falta colocar o restante dos campos. Seja bem vindo ao projeto. Caso deseje colaborar faça um fork na biblioteca e depois um pull request.
