### ISSUE TITLE
Gerar nf-e sem transportadora mas com volumes

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#176]
Gerar nf-e sem transportadora mas com volumes, tem como?
alguém sabe informar?

**Comment by adeniltonbs** [comment]
Pelo que consta nas páginas 234-235 do manual de integração do contribuinte, sim é possível.
Lá o grupo "transp" é obrigatório, mas a informação da transportadora, assim como o volume, são opcionais.

**Comment by robertorp** [comment]
Sim sim implementei aqui

vlw
