### ISSUE TITLE
Dúvida sobre emitir NFe

### ISSUE THREAD

**Issue by parg-programador** [ZeusAutomacao/DFe.NET#177]
Boa tarde pessoal, eu sou novo no C# e fiquei os últimos dois dias procurando um projeto que permitisse emitir NFe no modelo 55, minha dúvida é o seguinte o **Zeus.Net.NFe.NFCe** permite que eu crie uma NFe do zero? Incluindo produtos e adicionando as devidas tributações, dados da transportadora, assinar o xml e validar e depois liberar para uso?

> Eu vi  que ainda está em desenvolvimento a DANFE do modelo 55, mas vocês que tem mais experiência recomendam que eu use o **Zeus.Net.NFe.NFCe** para um projeto de um ERP interno de uma empresa de pequeno porte?

**Comment by francofs** [comment]
Bom dia Pablo,

É exatamente isso que estou fazendo. Ele permite tudo isso, e o layout da
DANFE estou desenvolvendo eu mesmo, o restante a biblioteca implementa
praticamente tudo.

Inclusive, depois de implementar a DANFE vou disponiblizar aqui.

2016-08-18 10:56 GMT-03:00 Pablo Alexander notifications@github.com:

**Comment by parg-programador** [comment]
Mas você me recomenda já gerar os xml's usando a biblioteca para um ambiente de produção? Estou no final do projeto do ERP interno da empresa e somente está faltando nota fiscal.

**Comment by francofs** [comment]
Recomendo sim.

Inclusive, o pacote tem uma aplicação de testes que você pode usar pra
simular uma emissão de nota no ambiente de homologação da receita e
posteriormente em produção. Bem simples de usar.

2016-08-18 11:41 GMT-03:00 Pablo Alexander notifications@github.com:

**Comment by parg-programador** [comment]
Vou começar a estudar a biblioteca a fundo para integrar ele ao sistema.
