### ISSUE TITLE
Transformar em Web Service

### ISSUE THREAD

**Issue by bfguimaraes** [ZeusAutomacao/DFe.NET#178]
Eu gostaria de criar um Web Service a partir dele, porém a implementação tem muitas dependências de Windows Forms o que deixa um pouco confuso na hora de transporta a linguagem de plataforma, vocês tem planos futuros para desenvolvimento da ferramenta em formato Web Service?

**Comment by francofs** [comment]
@bfguimaraes,

O adenilton poderá te explicar melhor, mas o sistema não possui dependência
direta com Windows Forms (até porque a aplicação de teste é WPF).

Os módulos que realmente realizam o trabalho de elaboração e transmissão da
ds NFe's não tem dependência com a camada de apresentação (WPF).

A parte de UI é um projeto de testes a parte e não é dependência do
restante do sistema.

2016-08-18 17:31 GMT-03:00 bfguimaraes notifications@github.com:

**Comment by willianas1** [comment]
Basta Vc usar as DLLs da NFe no seu WebServiçe, fazendo a interface em um
projeto separado.

## 

Saudações,

_Willian Santos_
Analista de Sistemas | Instrutor de TI
+55 84 98818-6602 <%2B55%2084%208818-6602>

_Ajudemos a poupar papel. Realmente necessita imprimir este e-mail?_

Em 19 de agosto de 2016 08:00, francofs notifications@github.com escreveu:

**Comment by nfceinteligente** [comment]
https://www.nuget.org/packages/Zeus.Net.NFe.NFCe/ 
Basta referenciar pelo nuget

Defina WebService? Recentemente estou estudando muito o WCF do C#  para fazer algo assim, no caso seria minha aplicação fazendo request no servidor e o servidor trataria de comunicar com a sefaz. (á ideia inicial minha é essa não quer dizer que sera assim enfim)

**Comment by bfguimaraes** [comment]
@nfceinteligente é exatamente isso que gostaria de fazer!

**Comment by homerokzam** [comment]
Segue, em anexo, exemplo (extraído do próprio projeto teste da biblioteca) em asp.net, com um controller chamado EmitirNFCe para que seja usando em projetos futuros. Deve-se restaurar todos pacotes NuGet (pois os mesmos não estão no arquivo anexo). O certificado digital A1 deve estar no diretório App_Data. Atentar para o fato de preencher as seguintes variáveis da classe NFCe do pacote TesteNFCe.Helpers: _cnpj, _ie, _razaoSocial, _fantasia, _cep, _codigoUF, _uf, _bairro, _municipio, _logradouro, _nro, _complemento, _consumidorCPF, _consumidorEmail e _pwd.

Espero que ajude!

[TesteNFCe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/454129/TesteNFCe.zip)

**Comment by bfguimaraes** [comment]
@homerokzam você pode me adicionar no skype: bferreiraguimaraes pra gente trocar uma ideia?

**Comment by brunobertechini** [comment]
Posso ajudar. Também estou fazendo via webservice (WebApi na verdade) utilizando conceitos SOA/Microservice

Bruno

**Comment by bfguimaraes** [comment]
@brunobertechini me add no skype, bferreiraguimaraes
