### ISSUE TITLE
DÚVIDA - Links dos WebServices?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#179]
Bom dia.

Primeiramente gostaria de parabeniza-los pela iniciativa de tal projeto.
Estou estudando o mesmo, mas estou com umas dúvidas quanto aos links de WebServices tanto de Produção quanto de Homologação da SEFAZ: aonde os mesmos estão definidos?

Obrigado.

**Comment by adeniltonbs** [comment]
Aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Servicos/Enderecador.cs
