### ISSUE TITLE
Recebimento de nota de compra

### ISSUE THREAD

**Issue by gercenio** [ZeusAutomacao/DFe.NET#180]
Pessoal talvez não seja o foco do projeto porem como um pode ajudar o outro tenho uma duvida alguém conhece uma solução que realize o manifesto de notas ou seja que acesse o ambiente nacional e baixe todas as notas emitidas contra um CNPJ ? isso em C#

**Comment by orochasamuel** [comment]
@gercenio o recebimento de notas de compra é feito ao consumir um webservice da SEFAZ.

O WebService antigo era o ConsultaNFeDest. Ele foi descontinuado para utilização do DistribuicaoDFe.

Acredito que os nomes sejam estes, não consultei as notas técnicas para lhe passar essa informação.

Eu tenho uma solução mas é usado o ConsultaDest. Também necessito fazer a atualização para o novo WebService.

**Comment by gercenio** [comment]
@samuelroliveira Tudo bem?, bom maravilha entendi bom se for possível poderia te ajudar neste processo de atualização e assim quem sabe disponibilizar para todos mais essa opção que eu acredito que agrega e muito para os demais desenvolvedores pode ser ?
