### ISSUE TITLE
SPED / EFD

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#181]
Boa tarde Srs.

Mais uma vez quero parabenizar pelo excelente projeto.

Gostaria de saber se algum dos Srs. tem informação de algum projeto semelhante a esse para a geração de EFD (Escrituração Fiscal Digital).

Já estou usando o Zeus para emissão de NFe, vou implementar agora a NFCe.

Em seguida vou precisar gerar o EFD, e como os prazos são extremamente curtos, um componente dessa qualidade ajudaria bastante.

Obrigado a todos.

**Comment by leandrossantos** [comment]
Oi @willianas1 existe um projeto em andamento do colega @samuelroliveira.

O link para o projeto é esse: [https://github.com/samuelroliveira/SPEDBr](https://github.com/samuelroliveira/SPEDBr)

**Comment by orochasamuel** [comment]
Boa tarde,

Pesquise pelo SPEDBr no Github mesmo.

-----Mensagem Original-----
De: "willianas1" notifications@github.com
Enviada em: ‎25/‎08/‎2016 15:16
Para: "adeniltonbs/Zeus.Net.NFe.NFCe" Zeus.Net.NFe.NFCe@noreply.github.com
Assunto: [adeniltonbs/Zeus.Net.NFe.NFCe] SPED / EFD (#181)

Boa tarde Srs.
Mais uma vez quero parabenizar pelo excelente projeto.
Gostaria de saber se algum dos Srs. tem informação de algum projeto semelhante a esse para a geração de EFD (Escrituração Fiscal Digital).
Já estou usando o Zeus para emissão de NFe, vou implementar agora a NFCe.
Em seguida vou precisar gerar o EFD, e como os prazos são extremamente curtos, um componente dessa qualidade ajudaria bastante.
Obrigado a todos.

**Comment by orochasamuel** [comment]
O @leandrossantos foi mais rápido. kkk

O projeto do SPED está em andamento.

Há também um projeto para geração do Sintegra. O link é: https://github.com/samuelroliveira/SINTEGRABr

Att,
Samuel Rocha

**Comment by leandrossantos** [comment]
@samuelroliveira e ai colega, mais alguma novidade no projeto SPED ??

**Comment by adeniltonbs** [comment]
Já deu uma olhada no AbcrFramewok.net?

**Comment by orochasamuel** [comment]
@leandrossantos estarei dando uma adiantada no projeto nesse restante de mês.

Estarei mapeando os registros do SPED Fiscal e EFD Contribuições relativos à notas fiscais, cupons, notas de frete e demais registros necessários ao ramo de comércio.

Qualquer dúvida é só postar lá nos issues do projeto.

**Comment by willianas1** [comment]
Vlw Pessoal.

Vou acompanhar o projeto do Samuel, devo precisar para o incio de 2017.

Em relação ao AcBR, o projeto .NET parece que anda um pouco de lado,
acredito que não tenha "engrenado" como ocorreu com o Delphi.

Dei uma olhada no site mais não achei documentação nem nada que fale oq o
projeto "oferece".

## 

Saudações,

_Willian Santos_
Analista de Sistemas | Instrutor de TI
+55 84 98818-6602 <%2B55%2084%208818-6602>

_Ajudemos a poupar papel. Realmente necessita imprimir este e-mail?_

Em 26 de agosto de 2016 10:25, Samuel Rocha notifications@github.com
escreveu:
