### ISSUE TITLE
Publicada versão 1.41 da NT2015/002

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#183]
- WebServiceConsulta Situação
- Enquadramento Legal IPI / ICMS
- Alterações em Regras de Validação
- NFC-e: Venda de Combustível para Consumidor Final
- Campo do QR-Code
- Formas de Pagamento

Detalhes em: http://www.spedbrasil.net/forum/topics/nf-e-aten-o-publicada-vers-o-1-41-da-nt2015-002-contendo-ajustes

**Comment by robertorp** [comment]
existe essa outra issue para a mesma finalidade, muito obrigado! https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/292
