### ISSUE TITLE
Adaptação para ASP. MVc

### ISSUE THREAD

**Issue by andersongrazina** [ZeusAutomacao/DFe.NET#184]
Estou utilizando as dlls do Zeus para adaptar o código para ASP.MVC e estou com um problema... Quando tento assinar o xml, dá o seguinte erro:

ArgumentNullException was caught... Valor não pode ser nulo.

Nome do parametro: input...

Não sei o que está acontecendo, pois estou utilizando o mesmo arquivo de conf e xml, que testei no projeto original e lá funcionou normal)

**Comment by leandrossantos** [comment]
@andernoia conseguiu resolver o seu problema?

**Comment by andersongrazina** [comment]
sim. Faltava configurar melhor o arquivo de configuração e salvar o arquivo temporário.

**Comment by leandrossantos** [comment]
Como fez a DANFe? Estou com um projeto para NFe Web mais estou problemas com a questão da DANFe

**Comment by andersongrazina** [comment]
Ainda não mexi com DANFE, só assinar, enviar e tratar o retorno... Mas parece que existe um projeto de DANFE baseado no Uninfe com todas as classes necessárias.(Um amigo me disse que encontrou)

**Comment by leandrossantos** [comment]
Então @andernoia o unico projeto que achei foi esse [https://github.com/SilverCard/DanfeSharp](https://github.com/SilverCard/DanfeSharp) acredito que dê para usar ele, não testei ainda.
