### ISSUE TITLE
NFe.Classes.nfeProc - Obter status atualizado na consulta/cancelamento

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#185]
Boa tarde a todos,

Guardo os xmls da NFe no meu banco de dados. O problema é que quando cancelo uma NFe o status do xml que estava no banco continua como 100. Alguns componentes de emissão (ACBr) atualizam o xml do nfeProc com alguns dados do retorno da consulta. Resolvi implementar isto "na unha", porém surgiram 3 problemas/dúvidas

1- Esta forma é a melhor para se fazer no caso da consulta? Como preencher o dhRecbto (se é que devo mudar)?

> var servicoNFe = new NFe.Servicos.ServicosNFe(_config);
> var retorno = servicoNFe.NfeConsultaProtocolo(chave);
> var nfeProc = new NFe.Classes.nfeProc();
> nfeProc.NFe = new NFe.Classes.NFe().CarregarDeXmlString(meu_xml);
> nfeProc.versao = retorno.Retorno.protNFe.versao;
> nfeProc.protNFe = retorno.Retorno.protNFe;
> if retorno.Retorno.cStat != 100)
> {
>     nfeProc.protNFe.infProt.cStat = retorno.Retorno.cStat;
>     nfeProc.protNFe.infProt.xMotivo = retorno.Retorno.xMotivo;
>      nfeProc.protNFe.infProt.dhRecbto = ????
> }
> string novo_xml = nfeProc.ObterXmlString();

2- No caso do cancelamento, como devo fazer para atualizar isto (levando em consideração que eu já tenha o xml do nfeproc salvo, só precisando alterar) ? Assim?

> var retornoCancelamento = servicoNFe.RecepcaoEventoCancelamento( ... );
> var nfeProc = new NFe.Classes.nfeProc().CarregarDeXmlString(meu_xml);
> nfeProc.protNFe.infProt.cStat = retornoCancelamento.Retorno.retEvento.FirstOrDefault().infEvento.cStat;
> nfeProc.protNFe.infProt.xMotivo = retornoCancelamento.Retorno.retEvento.FirstOrDefault().infEvento.xMotivo;
> nfeProc.protNFe.infProt.dhRecbto = retornoCancelamento.Retorno.retEvento.FirstOrDefault().infEvento.dhRegEvento, nfeProc.protNFe.infProt.dhRecbto;
> string novo_xml = nfeProc.ObterXmlString();

3- Esta é uma duvida mais geral que surgiu conforme fui tentando me virar: No caso de uma NFe com mais de um evento registrado (ex: CCe e depois cancelamento) o "procEventoNFe.FirstOrDefault()" do retorno da consulta viria com o CCe ou com o cancelamento? como funciona essa ordem?

PS: Analisando um pouco melhor o fonte do ACBr (venho do Delphi, então acabo usando o que tenho lá como base) notei que eles usam os dados de uma tag "infCanc" que vem no cancelamento para alterar essas informações, porém esta tag não está implementada no componente (apesar de vir no xml de retorno da consulta).

![canc](https://cloud.githubusercontent.com/assets/15945003/18125735/271c4bda-6f4e-11e6-97c3-7c2015345348.png)

Obrigado, abraços

**Comment by adeniltonbs** [comment]
@marcosgerene, Penso que essa não é a melhor abordagem para esse caso. O XML que foi autorizado deve permanecer intacto. O que você deveria fazer é armazenar o xml dos eventos, incluindo o evento de cancelamento.

Essa abordagem ainda presente no ACBR de modificar o xml da NFe Cancelada vem da época que não existia evento de cancelamento. O cancelamento alterava a própria NFe.

**Comment by marcosgerene** [comment]
Boa tarde @adeniltonbs ,

Obrigado pela resposta, pois bem, acho que vou fazer o que disse, ai na exportação dos XMLs para o escritório ou no envio via e-mail mando o evento de cancelamento junto.

Agora sobre a tag **retCancNFe**, existe alguma forma de ser "capturado"?
E sobre a questão de número 3, como posso ver se entre os eventos existe algum em específico? FindAll na lista de eventos?

Obrigado, Marcos

**Comment by adeniltonbs** [comment]
Sobre a tag retCancNFe acho que hoje em dia o serviço NfeConsulta2 não retorna mais essa tag.
veja a imagem da consulta de uma NFe cancelada abaixo:
![image](https://cloud.githubusercontent.com/assets/6733483/18142201/dcb0c072-6f92-11e6-84d1-8a36d21a429b.png)

Em lugar dela, é devolvido uma lista de procEventoNFe.

Sobre a questão número 3, observe no manual de orientação do contribuinte, que cada evento tem um código específico que o diferencia. Este código deve ser enviado no campo tpEvento e é devolvido em um campo com o mesmo nome. 
- 110111: Cancelamento
- 110110: CCe
- 110140: “EPEC”

### Eventos de manifestação do destinatário
- 210200: Confirmação da Operação
- 210210: Ciência da Emissão
- 210220: Desconhecimento da Operação
- 210240: Operação não Realizada

Outra coisa, se houver evento de cancelamento, não haverá CCe depois dele. Talvez possa ter eventos de manifestação (não tenho certeza).

**Comment by marcosgerene** [comment]
Boa tarde,

Obrigado pelos esclarecimentos.

> Sobre a questão número 3, observe no manual de orientação do contribuinte, que cada evento tem um código específico que o diferencia. Este código deve ser enviado no campo tpEvento e é devolvido em um campo com o mesmo nome. 
> 110111: Cancelamento
> 110110: CCe
> 110140: “EPEC”

Sobre esta questão, o "FirstOrDefault" vai retornar o evento mais novo ou mais velho? Devo ordernar o evento por data para ter certeza de qual o mais novo (ou mais velho)?

Ex: No caso de CCe poderiam retornar diversos eventos (pelo menos acho que sim), porém somente a ultima carta importa (foi só um exemplo, não veio mais nada na minha cabeça).

**Comment by adeniltonbs** [comment]
O Manual de orientação não informa se retEnvEvento.retEvento é ordenado por algum critério. Se houverem Cartas de correção na lista de procEventoNFe, (há a possibilidade de haver até 20 por nota - ver página 41 do manual), a CCe válida será a de maior nSeqEvento. Logo você pode ordenar por nSeqEvento descendente e usar o FirstOrDefault caso só queira a mais recente (e válida).

Já no caso do evento de cancelamento haverá somente 1. Você o identificará pelo tpEvento.

**Comment by marcosgerene** [comment]
Boa noite @adeniltonbs ,

Obrigado pela ajuda, acredito que o que tinha para ser abordado nesta insue foi resolvido, em caso de novas dúvidas abro uma nova insue.

Abraço
