### ISSUE TITLE
Erro ao Gerar XML

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#186]
Boa tarde pessoal.
Estou adaptando o projeto para pegar os dados de minha base para gerar o XML, mas assim que entra na função 'ClasseParaXmlString' da-se o erro na linha 'ser.Serialize(memory, objeto);' = "There was an error generating the XML document".
O que pode ser?

Obrigado.

**Comment by adeniltonbs** [comment]
Poderia dar uma olhada no manual de orientação e na aplicação de testes no método MainWindow.GetNf se vc deixou algum campo obrigatório sem informar.

**Comment by FabioHenriqueMF** [comment]
Eu simplesmente substitui os campo que já existiam pelos  da minha base.

**Comment by adeniltonbs** [comment]
Essa mensagem é muito genérica. Acho que ninguém vai conseguir te ajudar somente com essa informação. Veja se isto te ajuda https://msdn.microsoft.com/en-us/library/aa302290.aspx?f=255&MSPPError=-2147217396
