### ISSUE TITLE
[NFC-e] Cancelamento - Versao incorreta

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#187]
Boa noite @adeniltonbs.

Estou tendo o mesmo problema das Insues https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/47 e https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/85.

No meu caso é para SP e ambiente de homologação.

Abraços

**Comment by adeniltonbs** [comment]
Bom dia @marcosgerene. na biblioteca, na classe NFe.Servicos.Enderecador a versão do serviço RecepcaoEvento para NFCe, em homologação de SP, é definida como 3.10, conforme consta em http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/URLWebServices.aspx 

Veja o recorte do site:
![image](https://cloud.githubusercontent.com/assets/6733483/18248311/c189cb4a-734d-11e6-9bdd-b9757851ae07.png)

Se for possível, poderia confirmar com a SEFAZ qual a versão correta para esse serviço e sugerir corrigirem no site?

**Comment by marcosgerene** [comment]
Bom dia @adeniltonbs,

Entrei em contato com o Sefaz, te aviso assim que receber uma resposta

Abraços

**Comment by adeniltonbs** [comment]
Se for o mesmo caso de outras SEFAZes deve ser 1.0 a versão do serviço recepcaoevento. Mas deviam informar correto no site. Poderia testar com 1.0, alterando lá na classe?

**Comment by marcosgerene** [comment]
Boa tarde @adeniltonbs ,

> Resposta da Mensagem 7090286
> 
> Prezado,
> 
> A versão dos eventos é diferente da versão da NFC-e. Os eventos devem ter o atributo versão igual a 1.00, conforme schema.
> 
> Agradecemos seu contato no "Fale Conosco" da Secretaria da Fazenda.
> 
> Sua opinião é muito importante para nós. Por gentileza, clique no link abaixo e opine sobre este e-mail:
> 
> Pesquisa de Satisfação
> 
> Atenciosamente,
> 
> Secretaria da Fazenda do Estado de São Paulo
> 
> Mensagem Original:
> 
> Informações técnicas
> 
> Bom dia,
> 
> Estou recebendo o seguinte retorno ao tentar cancelar uma nfce (homologação):
> 
> O atributo 'versao' é inválido - O valor '3.10' é invalido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerEnvEvento'
> 
> Segundo está descrito nessa página: http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/URLWebServices.aspx a versão é sim a 3.10. Poderiam me informar a versão correta ou alterar na página e me dar um retorno?
> 
> Obrigado

Abraços

**Comment by adeniltonbs** [comment]
Correção enviada no commit 826111550779ee0676637f5d7748a2f23fab9356.

**Comment by marcosgerene** [comment]
@adeniltonbs ,

Uso o nuget. Já está disponível?

**Comment by adeniltonbs** [comment]
Ainda n.

**Comment by adeniltonbs** [comment]
Liberada versão mais recente no nuget. https://www.nuget.org/packages/Zeus.Net.NFe.NFCe/
