### ISSUE TITLE
Base da Dados ???

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#188]
Boa tarde.

Qual seria a melhor alternativa para salvar os dados de Emitente, Clientes, Produtos, Transportadoras e NFe fora SGBD?
SqLite por exemplo?

Obrigado.

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF a resposta a essa pergunta é subjetiva e está fora do escopo dessa biblioteca. Isso vai depender da arquitetura de seu sistema/plataforma de destino/familiaridade com o SGDB, volume de dados/disponibilidade/volume de transações, etc.
