### ISSUE TITLE
Tag <orig>  do ICMS do item não atualiza

### ISSUE THREAD

**Issue by brendonbribeiro** [ZeusAutomacao/DFe.NET#189]
A função NFe.Utils.NFe.ExtNFe.CarregarDeXmlString(NFe.Classes.NFe nfe, string xml), não está trazendo a origem de mercadoria informada no xml. Testado usando diversos tipos de ICMS, e o mesmo acontece pra todos.

`<ICMS>
<ICMS00><orig>2</orig><CST>00</CST> <modBC>3</modBC> <vBC>0.00</vBC><pICMS>0.0000</pICMS> <vICMS>0.00</vICMS> </ICMS00></ICMS>`

**Comment by adeniltonbs** [comment]
Não detectado. 
Alterei o método NFe.AppTeste.MainWindow.CarregaArquivoNfe para carregar uma string de XML de NFe autorizada. 

Conforme imagens abaixo, podes notar que a tag orig foi carregada corretamente.

![image](https://cloud.githubusercontent.com/assets/6733483/18350331/cf39b9ac-75ab-11e6-8410-208be6c19ed8.png)

![image](https://cloud.githubusercontent.com/assets/6733483/18350237/62a834b2-75ab-11e6-9d5c-db945afd3c89.png)

Pergunta: A string com XML que vc utilizou foi validada para garantir que atende o formato determinado pela SEFAZ?
Se não, valide-o aqui https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx? para verificar se ele está correto.

**Comment by brendonbribeiro** [comment]
Problema estava realmente relacionado a validação do XML. O framework está OK.
