### ISSUE TITLE
Imprime Danfe?

### ISSUE THREAD

**Issue by integrasys** [ZeusAutomacao/DFe.NET#19]
Olá,
eu baixei o projeto e achei muitio interessante... só fiquei com uma duvida... ele está Imprimindo a DANFE?

**Comment by weslley39** [comment]
Essa é uma das funcionalidades que irão ser desenvolvidas. Mas por hora, ainda não tem

**Comment by adeniltonbs** [comment]
Isso mesmo, por hora, se sua aplicação for desktop, recomendo usar o AcbrNfeMonitor para esta funcionalidade, apenas.

**Comment by adeniltonbs** [comment]
Implementada impressão do DANFE  da NFCe em 09/09/2015.
