### ISSUE TITLE
NFC-e, para o Estado do Pará (PA)

### ISSUE THREAD

**Issue by adrbarros** [ZeusAutomacao/DFe.NET#192]
Na classe Enderecador.cs (NFe.Servicos), na lista de Estados -> svrsEstadosDemaisServicos, está faltando o Estado do PA.

Estado.PA, //Somente NFCe. PA usa o SVAN para NFe. Rev: 09/09/2015

igual ao Maranhão e o Piauí

Abraços

**Comment by hardzork** [comment]
@adrbarros, eu adicionei o Estado.PA na lista svrsEstadosDemaisServicos, porém, quando eu envio e consulto, recebo uma rejeição: cStat: 226, xMotivo: Rejeicao: Codigo da UF do Emitente diverge da UF autorizadora.

Como consigo resolver isso? sendo que o emitente usa o codigo 15 (PARÁ) e a autorizadora é 43 (RS).

Alguma luz?

**Comment by adrbarros** [comment]
Tem mais uma implementação que esqueci de comentar:
Analise a nfenfce_para02 (Ajustar [na region SVRS] Homologação e Produção).

![nfenfce_para01](https://cloud.githubusercontent.com/assets/15065213/18488009/ee9ba3d4-79cd-11e6-8afc-817eeb9eeca0.png)
![nfenfce_para02](https://cloud.githubusercontent.com/assets/15065213/18488010/ee9c3b46-79cd-11e6-9be6-272b6b5e4dcc.png)

**Comment by hardzork** [comment]
@adrbarros, resolvido!

**Comment by adeniltonbs** [comment]
Boa tarde @adrbarros. Poderia compartilhar a alteração com a comunidade por meio de um fork > pull request?

**Comment by adrbarros** [comment]
Ajuda, fiz um Fork, agora uma duvida:
- Como faço para faz um Pull ou Merge das alterações feitas na Master adeniltonbs/Zeus.Net.NFe.NFCe para a minha master no meu Fork criado?

**Comment by adeniltonbs** [comment]
Assim: http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/
