### ISSUE TITLE
CT-e

### ISSUE THREAD

**Issue by andersongrazina** [ZeusAutomacao/DFe.NET#193]
Olá, verifiquei que vocês estavam pensando em implementar o CT-e ao Zeus. Gostaria de saber se essa intenção se permaneceu e se já existe algo sobre, pois precisarei de algo deste gênero.

Obrigado desde já!

**Comment by robertorp** [comment]
Aqui na empresa onde trabalho, vamos começar a desenvolver uma biblioteca para CT-e/MDF-e (Tentamos comprar mas.. não estamos achando). Inclusive se vocês souberem dos detalhes do CT-e/MDF-e podemos trocar informações/ideias para o desenvolvimento da mesma. Disponibilizando a biblioteca para CT-e/MDF-e.

**Comment by andersongrazina** [comment]
Então... Aqui logo precisarei também de uma biblioteca para trabalhá-la em Asp Mvc e não encontrei nada ainda... Achando eu faço questão de mandar ou postar ela do github para ajudar em novos projetos.

**Comment by adeniltonbs** [comment]
@andernoia Assim que o @ernanisp terminar a implementação de distribuição Dfe e manifesto do destinatário, vou alterar a estrutura do projeto para contemplar CT-e e MDF-e, também pretendo colaborar com código nessas duas implementações.

**Comment by andersongrazina** [comment]
💃

**Comment by marcosgerene** [comment]
Olhem o https://github.com/ACBrNet/ACBr.Net.CTe do @rftd

**Comment by robertorp** [comment]
Implementado
