### ISSUE TITLE
Impressão NFCe - Alterações no leiaute

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#195]
Saiu um atualização do Manual DANFE-NFC-e e QR Code versão 4.0

Segue o link [http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=8Ih3K2kRyWY=](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=8Ih3K2kRyWY=)

**Comment by adeniltonbs** [comment]
Vi aqui, vlw. Analisando as alterações...
