### ISSUE TITLE
Impressao danfe NFCe - Epson TM 20

### ISSUE THREAD

**Issue by dimasskt** [ZeusAutomacao/DFe.NET#196]
Boa Tarde, 
Muito legal o projeto, foi o único que encontrei na internet e está bem organizado, parabéns.

Estou tentando imprimir a DANFE De uma NFCe pelo app de teste da danfe. está montando certinho no fastreport, mas quando mando para impressora sai todo desconfigurado e sem qrcode
![img_20160913_135157454](https://cloud.githubusercontent.com/assets/3641761/18483300/cc1397a4-79b9-11e6-86c4-393a14fe1c3c.jpg)

**Comment by adeniltonbs** [comment]
@dimasskt uso aqui na TM20 sai correto. Vc tem que usar o driver para spooler.

**Comment by adeniltonbs** [comment]
Utilizo esse driver https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=5133&pcat=3&pid=37 aqui e funciona perfeitamente.

Por favor instale esse driver, faça o teste novamente e poste aqui o resultado.

**Comment by dimasskt** [comment]
Perfeito Adenilton, funcionou :)

Muito obrigado pela ajuda!

**Comment by dimasskt** [comment]
Fui a pesquisa e agora está claro para mim o que é o driver spooler

Caso alguém mais precise, segue:
Bematech (Ainda não testei): http://partners.bematech.com.br/suporte-e-recursos/paginas/DetalhesDownload.aspx?ID=195
