### ISSUE TITLE
Cancelamento, Rejeição valor da assinatura (signaturevalue) difere do valor calculado

### ISSUE THREAD

**Issue by edenilsonbila** [ZeusAutomacao/DFe.NET#198]
Boa noite, Estou tendo o seguinte problema, Sempre que envio uma nota de Cancelamento me retorna essa rejeição, Ja removi certificado, Validei caracteres, Reiniciei a maquina, Reinstalei java, Coloquei permissoes no java fiz de tudo possivel e esse erro nao me deixa dormir.. Desconfio ser algo na assinatura ou envio do xml.. Engraçado é que o envio da nota normal vai tranquilo, só o cancelamento que me retorna esta rejeição..
Gostaria de ajuda de vocês se alguem ja passou isso, ou se eh algum detalhe na aplicação estou usando o AppTeste de vocês mesmo.. Fico agradecido desde já.

**Comment by adeniltonbs** [comment]
@edenilsonbila estranho, nunca passei por esse problema com a biblioteca. Alguém já? Seu certificado é A1 ou A3? Se for A3, já testou com outros serviços (ou sites do governo que pedem o certificado) pra ver se está ok?

**Comment by jrssantos** [comment]
Boa noite! Pelo que tenho percebido em vários fóruns, desde o dia 15/09 surgiu um problema na SEFAZ SP no ambiente de homologação para as operações de cancelamento e CCe (eventos). Não sei se nas outras UFs o problema também está ocorrendo, mas SP com certeza.

**Comment by edenilsonbila** [comment]
Eu testei com os dois A1 e A3 os dois não funcionam, Todas as outras operações de NFe funcionam normal somento o cancelamento que não, Acredito ser problema no sefaz sp de homologação mesmo, Se vocês puderem testar para mim nestas condições Hom Sp cancelamento so para eu poder dar uma certeza para o cliente. Eu fico agradecido, pois aqui eu ja fiz todos os testes possíveis mas sem sucesso

**Comment by adeniltonbs** [comment]
@edenilsonbila Confirmado problema aqui, embora eu esteja em SE, o webservice apresentou o mesmo problema, quando deveria apenas reclamar da UF.

![image](https://cloud.githubusercontent.com/assets/6733483/18661586/db6c9bfa-7eec-11e6-8a50-f112ce84d496.png)

Tem como vc contatar a SEFAZ?

**Comment by edenilsonbila** [comment]
@adeniltonbs Eu mandei um E-mail para eles ontem, e me deram a seguinte resposta:
![814 nao lidos - edenilsonbila - yahoo mail - google chrome](https://cloud.githubusercontent.com/assets/15230217/18682324/2cb53594-7f42-11e6-9bd4-f2cd5896a623.jpg)
O que é estranho pois estava funcionando, e não vi erro algum na assinatura do XML e testei com o a Biblioteca de vocês e com a do Uninfe e retorna o mesmo erro, o que não ocorre em Produção que utiliza o mesmo método. Ainda acredito ser erro deles la.
