### ISSUE TITLE
Microservice SOA/NServiceBus para NFe

### ISSUE THREAD

**Issue by brunobertechini** [ZeusAutomacao/DFe.NET#199]
Olá e parabéns pela iniciativa.

Cheguei neste github pelo link [http://www.projetoacbr.com.br/forum/topic/18937-melhor-solucao-para-emissao-de-nfenfce-com-c/](url) .

Estou iniciando uma integração desta library em um projeto grande utilizando conceitos de SOA e Microservice com NServiceBus.

Existe interesse em colaboração para adequar uma versão nos padrões SOA/Microservice ? Eu quero dizer ter um microservice standalone possivel de deploy em docker/containers/azure usando esta biblioteca?

Bruno

**Comment by adeniltonbs** [comment]
Seria um projeto adicional, semelhante ao https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.Integracao? Poderia detalhar melhor o que tem em mente para esse SOA? Assim talvez alguém queira colaborar nesse projeto.

**Comment by brunobertechini** [comment]
Olá

Meu propósito é poder desenvolver um microservice autonomo que possa ser usado para emissao de NFe.

Vou primeiro entender a biblioteca em uso normal (Web) e então posto aqui novidades.

Alguma sugestão para onde começar (documentação)  para utilizar em um projeto AspNet Web C# ?

Bruno
