### ISSUE TITLE
Erro ao tentar enviar NFC-e

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#20]
Adenilton, bom dia,

Ao tentar enviar uma NFC-e para teste em homologação deu o erro que envio anexo. Também mando as imagens das minhas configurações. Você poderia me ajudar?

Agradeço desde já,
Roberto.

![confignfcews](https://cloud.githubusercontent.com/assets/11814082/7565231/caf1e3da-f7c4-11e4-9110-dd342a510ced.png)
![confignfcegeral](https://cloud.githubusercontent.com/assets/11814082/7565232/caf26dd2-f7c4-11e4-8f10-aebdbecec3e9.png)
![erronfce](https://cloud.githubusercontent.com/assets/11814082/7565233/caf7153a-f7c4-11e4-89ea-7be5fcc82228.png)

**Comment by adeniltonbs** [comment]
Roberto, a mensagem diz que o serviço NfeRecepção não está disponível para o estado do RJ, e é isso mesmo, se você olhar na relação de serviços web em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#SVRS vai perceber que esse serviço foi removido para o estado do RJ, que usa a "
Sefaz Virtual Rio Grande do Sul - (SVRS)". E mesmo quando ele estava disponível, a versão desse serviço era 2.0 e não 3.10.

Use o serviço NFeAutorizacao que já está implementado na biblioteca e a forma de uso dele é praticamente igual ao serviço NfeRecepção. No próprio aplicativo de demonstração já tem uma demonstração de uso desse serviço, no botão "Criar e Enviar 3.0".

**Comment by adeniltonbs** [comment]
Atualize a sua versão da biblioteca para o commit a9fea68decc5378b15e97b95400676ec04d66631.

**Comment by robertocvsiqueira** [comment]
Adenilton, boa noite,

Tentei mudar as dlls referenciadas na minha aplicação e agora dá o seguinte erro ao tentar salvar as configurações:

![image](https://cloud.githubusercontent.com/assets/11814082/7667989/bd25055c-fbf7-11e4-8017-0cc9f8ed7be1.png)

E dá o seguinte erro ao tentar consultar o status do serviço. Quais configurações devo usar para acessar homologação? Não funciona a 3.10? Tem que ser a RS, versão 2.00?

![image](https://cloud.githubusercontent.com/assets/11814082/7667992/ed493fc8-fbf7-11e4-9f96-5b4d87a044f7.png)

**Comment by adeniltonbs** [comment]
Ok Roberto, entendi o que aconteceu. Basta vc definir um valor para a propriedade ModeloDocumento, da classe ConfiguracaoServico, que pode ser Nfe ou Nfce. Está propriedade foi adicionada recentemente pois alguns estados estão com a url diferente para Nfce. Ah é a biblioteca funciona para todos os estados na versão 3.10

**Comment by adeniltonbs** [comment]
Atualize sua biblioteca com a versão mais recente e verifique que no aplicativo de demonstração, na aba geral, tem uma nova opção para escolha do tipo de documento:

![alt tag](http://s29.postimg.org/qasdez9ev/687474703a2f2f7777772e7a6575736175746f6d6163616f.png)

**Comment by adeniltonbs** [comment]
Conseguiu consumir os serviços do RS?

**Comment by robertocvsiqueira** [comment]
Vou atualizar a biblioteca e fazer os testes somente hoje, aí te dou um retorno.

**Comment by SilverioMiranda** [comment]
Alguém tem um certificado A1 válido pra usar no webservice do RS?

**Comment by adeniltonbs** [comment]
Roberto, conseguiu resolver seu problema?

**Comment by robertocvsiqueira** [comment]
Adenilton, consegui sim. já estou gerando a NF-e. O que estou aprendendo ainda é gerar o conteúdo do QR-Code para o DANFe.

**Comment by robertocvsiqueira** [comment]
Muito obrigado

**Comment by adeniltonbs** [comment]
Por nada, qualquer coisa poste aqui. vou fechar esse issue.

**Comment by robertocvsiqueira** [comment]
Adenilton,

Me lembrei que preciso consultar o protocolo e gerar o arquivo ProcNFe equivalente. Ao consultar o protocolo a SEFAZ informa que a chave passada não existe. Tem algo faltando?

![image](https://cloud.githubusercontent.com/assets/11814082/7775908/712ecf08-008d-11e5-8319-2fee32c0e835.png)

**Comment by adeniltonbs** [comment]
Roberto, o fato da nota não constar na SEFAZ, indica que sua nota não foi autorizada pela sefaz. Armazene o recibo de envio do lote (retornoEnvio.Retorno.infRec.nRec) e use o serviço NFeRetAutorizacao para saber se as notas do lote foram autorizadas. Use o seguinte caminho do retorno de autorização (retornoRecibo.Retorno.cStat).

Na aplicação de demonstração tem um exemplo de uso deste serviço, no botão "Consultar Recibo Lote 3.0".

Obs: consulte no manual os códigos de cStat deste serviço que indicam que a nota foi autorizada.
