### ISSUE TITLE
Impressão de DANFe com problemas

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#200]
Adenilton, boa tarde,

Tentei usar a funcionalidade do DANFe e o cliente relatou os seguintes problemas. Gostaria da sua ajuda:

1- Esta imprimindo duas linhas no topo da nota:

```
a - uma linha que não da para identificar o que está impresso.

b - uma linha impressa as letras MF
```

2- Esta capando 1 caracter a esquerda em todas as linhas.

3- Esta imprimindo a palavra NOTA FIS na descrição do produto.

4- Ao final da impressão ele está ejetando cerca de 12 cm de fita.

Segue arquivo em PDF ilustrando a impressão.

Obrigado,
Roberto.

[nota4.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/480982/nota4.pdf)

**Comment by leandrossantos** [comment]
@robertocvsiqueira você instalou as fontes que acompanham o projeto?

**Comment by robertocvsiqueira** [comment]
Sim, instalei todas e atualizei todas as referências na minha aplicação.

**Comment by leandrossantos** [comment]
@robertocvsiqueira as fontes vc instalou no cliente também?

**Comment by adeniltonbs** [comment]
@robertocvsiqueira 
Como o pessoal já comentou, instale as fontes no PC.
1 - Faça um teste no seu PC, enviando a impressão para uma impressora PDF, como Foxit Reader PDF Printer, por exemplo.
2 - Você também pode pedir para visualizar o relatório, no seu ambiente de testes para ver se está tudo ok;
3 - A biblioteca tem opção de configurar a margem esquerda, já que algumas impressoras térmicas possui margem de segurança abaixo de 4,5 mm (valor padrão da margem esquerda na biblioteca);
4 - Envie um PDF gerado corretamente para a impressora do cliente e veja se ela imprime conforme o PDF. Algumas impressoras térmicas não tem suporte adequado a impressão via spooler.
5 - Ao escolher imprimir o item em uma única linha, o nome do produto realmente é cortado. Caso queira imprimir mais caracteres no nome do produto, opte por usar duas linhas por item. 
6 - Impressão testada e funcionando 100% nas impressoras Bematech MP-4200, Daruma DR700 e Epson TM-81 e TM-20.

**Comment by robertocvsiqueira** [comment]
Adenilto, bom dia,
Vou verificar essas questões.

Mais algumas dúvidas:
- Por que o nome do produto sai "NOTA FISCAL" em vez do nome do produto correto?
- Com relação à margem superior, como posso configurá-la, já que a primeira linha da NFC-e está sendo cortada?
- Com relação ao papel, como posso configurar via aplicação, já que ele está carregando 12 cm de fita em branco após o fim da impressão?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira a impressão pra mim, nas impressoras citadas, inclusive nos clientes, sai conforme a imagem https://camo.githubusercontent.com/6a143d81febb04b654a9ab9638bbe19df8ec6b6d/687474703a2f2f7777772e7a6575736175746f6d6163616f2e636f6d2e62722f696d6167656e732f6769742f31312e6a7067

**Comment by adeniltonbs** [comment]
Você mesmo pode conferir o designer do relatório na biblioteca. O arquivo do relatório do DANFE é https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Danfe.Fast/NFCe/NFCe.frx

Baixe a versão demo do fastreports, abra o designer, visualize o DANFE e veja se há algo errado pra ti. Pra mim aparece tudo certinho aqui,

Na aplicação NFe.Danfe.AppTeste, classe MainWindow.cs, no método BtnNfceDanfe_Click, comente a linha danfe.Visualizar(); e descomente a linha danfe.ExibirDesign();.

O resultado deve ser esse:

![image](https://cloud.githubusercontent.com/assets/6733483/18666565/dfe9eac8-7f02-11e6-9815-4988dfd00449.png)

Em seguida, clique em Report > Preview
![image](https://cloud.githubusercontent.com/assets/6733483/18666574/eee130ea-7f02-11e6-9229-9729d2f1b6f9.png)

![image](https://cloud.githubusercontent.com/assets/6733483/18666602/1f0ad190-7f03-11e6-9493-6cff666ed066.png)

Note que na imagem acima, na pré-visualização, a depender do número de produtos, é exibido um espaço em branco até o final da página. Isso é normal já que o tamanho pré-definido em design é para A4,, no entanto, a impressão termina ao final do qr-code. A impressora térmica deve ser capaz de cortar ao final do documento, logo após o qr-code.  (Assim que chegar na empresa, vou fazer um novo teste da impressora térmica que tenho a disposição e anexo aqui a foto).
No caso do produto "NOTA FISCAL", minha NFCe foi emitida em ambiente de homologação e, para este caso, o nome do primeiro produto deve ir como "NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL". Mas isso a biblioteca não coloca sozinha, seu ERP tem que mandar para o xml essa informação. A biblioteca de impressão imprime conforme vem no XML.

![image](https://cloud.githubusercontent.com/assets/6733483/18667093/7b54fc1c-7f05-11e6-9aef-257956c85994.png)

Pergunta: Qual a marca/modelo da impressora do cliente, onde o problema ocorre?
A impressora possui suporte completo a impressão via spooler?
Ela imprime corretamente, por exemplo, um documento do word com imagens, ou a página de teste do windows?

**Comment by robertocvsiqueira** [comment]
Adenilton,

Marca/Modelo: Elgin i9
Aparentemente possui suporte a spooler.
Não testei outros documentos que não fossem a NFC-e.

Ainda me restam algumas dúvidas:
- O logo no começo da impressão é obrigatório? Sem ele, a impressão do nome fantasia fica prejudicada?
- Notei que na foto de impressão que você enviou constam os produtos listados corretamente e nenhum figurando como "NOTA FISCAL EMITIDA...", apesar da impressão em si ter sido efetuada em ambiente de homologação, conforme figura na própria impressão.

Att,
Roberto.

**Comment by robertocvsiqueira** [comment]
Uma outra dúvida: o picote presumo que ocorra ao fim do documento. Não teria como dimensionar o tamanho da impressão pois acho que o tamanho do papel gasto está fixo e muito maior do que a impressão da NFC-e propriamente dita?

**Comment by adeniltonbs** [comment]
> O logo no começo da impressão é obrigatório? Sem ele, a impressão do nome fantasia fica prejudicada?

Veja as imagens abaixo:

**Visualização e impressão COM logo:**
![image](https://cloud.githubusercontent.com/assets/6733483/18669028/53586532-7f0f-11e6-9b66-c71669944971.png)

![image](https://cloud.githubusercontent.com/assets/6733483/18669035/5851107a-7f0f-11e6-81cd-1d96b1aceb7f.png)

**Visualização e impressão SEM logo:**
![image](https://cloud.githubusercontent.com/assets/6733483/18669045/657e4e3e-7f0f-11e6-942e-2f4c4bb13be4.png)

![image](https://cloud.githubusercontent.com/assets/6733483/18669048/7021546c-7f0f-11e6-951b-91ec2a00404d.png)

> Notei que na foto de impressão que você enviou constam os produtos listados corretamente e nenhum figurando como "NOTA FISCAL EMITIDA...", apesar da impressão em si ter sido efetuada em ambiente de homologação, conforme figura na própria impressão.

Observe a data destes DANFEs: 
![image](https://cloud.githubusercontent.com/assets/6733483/18669524/d5f22a26-7f11-11e6-8f0c-e3d2108b4b30.png)
Nesta data a NT 2015.002 ainda não vigorava, e, portanto, a regra I04-10 também não.

Veja a regra na NT 2015.002 que entrou em vigor em 01/12/2015:
![image](https://cloud.githubusercontent.com/assets/6733483/18669604/22dbb3d4-7f12-11e6-982a-0a6ee3935b2d.png)

> Uma outra dúvida: o picote presumo que ocorra ao fim do documento. Não teria como dimensionar o tamanho da impressão pois acho que o tamanho do papel gasto está fixo e muito maior do que a impressão da NFC-e propriamente dita?

Conforme vc pode observar nas imagens anexadas, o espaço que sobre no visualizador do Fast reports não indica que a impressão vá ocorrer até o final. Na hora da impressão, o final do documento é justamente após a impressão do qr-code.

**Comment by robertocvsiqueira** [comment]
Então se eu der um comando ESC POS de picote, irá funcionar logo após o QR-Code? O que eu devo fazer para que o Logo não apareça? Somente setar o parâmetro como null resolve a questão?

**Comment by francofs** [comment]
Aproveitando esse tópico, a dúvida é: por acaso precisa de licença esse
fast reports? Estou implementando a DANFE A4 utilizando (System.Drawing e
System.Drawing.Printing), que com certeza é mais trabalhoso, mas não
precisa de nenhum componente, nem tem questões de licensa.

2016-09-20 9:17 GMT-03:00 Roberto Siqueira notifications@github.com:

**Comment by adeniltonbs** [comment]
@robertocvsiqueira 

> Então se eu der um comando ESC POS de picote, irá funcionar logo após o QR-Code? 

Estamos falando de impressão via spooler certo?

> O que eu devo fazer para que o Logo não apareça? Somente setar o parâmetro como null resolve a questão?

Na aplicação de demonstração do DANFE, olhe o código quando a logo não é informada.

@francofs 

> Aproveitando esse tópico, a dúvida é: por acaso precisa de licença esse
> fast reports?

Sim, o fast reports é uma solução proprietária. Se usares a versão demo ele vai deixar imprimir, mas vai colocar uma marca d'água.

**Comment by francofs** [comment]
Certo, então assim que tiver desenvolvido tanto A4 quanto o formato NFCe,
disponibilizo, pois daí ninguém mais vai precisar de licensa :)

2016-09-20 9:46 GMT-03:00 Zeus Automação Comercial <notifications@github.com

**Comment by robertocvsiqueira** [comment]
Sim, estamos falando de spooler. A única dúvida que eu tenho agora é quanto ao picote.

**Comment by leandrossantos** [comment]
@robertocvsiqueira a parte do corte do papel eu sempre configuro direto nas propriedades da própria impressora.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira Te perguntei isso por que a impressora instalada para uso via spooler, deve ter a opção de picote nas preferências dela. Você não precisa mandar comandos ESC POS para isso. 

Além disso a impressão do DANFE feita pela biblioteca usa spooler, o que é incompatível com ESC POS que é impressão direta na porta da impressora.

**Comment by adeniltonbs** [comment]
No caso da epson e da bematech, por exemplo, posso escolher, nas preferências de impressão, entre mandar o picote ao final da página ou do documento.

**Comment by robertocvsiqueira** [comment]
Adenilton, continuamos a ter problema com o picote...Eu mando um comando ESC POS de picote e ele não ocorre...Talvez por uma incompatibilidade com o formato de impressão sendo utilizado, não sei...Enfim, preciso de ideias para ver o que tá acontecendo...

**Comment by robertocvsiqueira** [comment]
Consegui implementar o picote, mas ele continua carregando papel a mais antes do picote...Vou atualizar as dlls, se não resolver, não sei o que está acontecendo...

**Comment by adeniltonbs** [comment]
Configurou a impressora para picotar ao final do documento e ao final da página para ver a diferença entre os dois casos?

**Comment by robertocvsiqueira** [comment]
Não encontrei essa configuração, nem no utilitário da impressora nem nas configurações via Windows

**Comment by adeniltonbs** [comment]
Ok, talvez sua impressora não deixe vc escolher cortar ao final do documento.

A solução pra isso é definir, no relatório do fast, a página como unlimitedheight = true. No entanto não o fiz assim desde o princípio, pois embora a visualização fique ok, a impressão sai cortada, Abri um tópico no forum do fastreports pra ver se obtenho retorno de como resolver isso.

Vc pode acompanhar em https://www.fast-report.com/en/forum/index.php?showtopic=13723

**Comment by robertocvsiqueira** [comment]
Adenilton, bom dia,

Atualizei as referências às bibliotecas, cujas pastas estão referenciadas na minha aplicação como seguem:

D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Classes\bin\Debug\NFe.Classes.dll
D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Danfe.Base\bin\Debug\NFe.Danfe.Base.dll
D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Danfe.Fast\bin\Debug\NFe.Danfe.Fast.dll
D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Servicos\bin\Debug\NFe.Servicos.dll
D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Utils\bin\Debug\NFe.Utils.dll
D:\Projetos\ONI4\Zeus.Net.NFe.NFCe-master\NFe.Wsdl\bin\Debug\NFe.Wsdl.dll

Aqui está o método da impressão:

```
    private void ImprimeDANFeGenerico(string arquivoXML)
    {
        _configuracoes.ConfiguracaoDanfeNfce.MargemEsquerda = 6;
        _configuracoes.ConfiguracaoDanfeNfce.Logomarca = null;

        if (_configuracoes.CfgServico.tpEmis == TipoEmissao.teNormal)
        {
            var proc = new nfeProc().CarregarDeArquivoXml(arquivoXML);
            var danfe = new DanfeFrNfce(proc, _configuracoes.ConfiguracaoDanfeNfce, _configuracoes.IdToken, _configuracoes.CSC);
            danfe.Imprimir(false, _configuracoes.TipoImpressora);
        }
        else
        {
            var nfe = new NFe.Classes.NFe().CarregarDeArquivoXml(arquivoXML);
            var danfe = new DanfeFrNfce(nfe, _configuracoes.ConfiguracaoDanfeNfce, _configuracoes.IdToken, _configuracoes.CSC);
            danfe.Imprimir(false, _configuracoes.TipoImpressora);
        }

        EscPos esc = new EscPos();

        esc.CutPaper(_configuracoes.TipoImpressora);

    }
```

Agora não imprime nada. Será que fiz algo errado ao referenciar as dll's? 

Obrigado,
Roberto.

**Comment by robertocvsiqueira** [comment]
Adenilton, bom dia,

Voltou a imprimir, o erro estava no nome da impressora sendo referenciado.

Mas continua o problema do picote, está carregando papel demais antes do picote....

**Comment by robertocvsiqueira** [comment]
Adenilton, acabei de tentar a mudança de parâmetro recomendada, sem sucesso....

**Comment by robertocvsiqueira** [comment]
Não sei mais por onde ir, é o único problema que falta para ser solucionado, a questão do picote....

**Comment by robertocvsiqueira** [comment]
Adenilton,

Alguma luz? O cliente está me pressionando por uma solução. Só falta a questão do complicador da ejeção de papel antes do picote.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira, como o pessoal do fastreports não se manifestou, implementei via código a definição do tamanho da página. Atualize sua biblioteca até o commit https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/commit/5457229439dcc90f20c39bd5574d7887b60ca115 e tente novamente.

**Comment by robertocvsiqueira** [comment]
Obrigado mesmo, Adenilton! Vou testar e te falo.

**Comment by robertocvsiqueira** [comment]
Adenilton, ainda não fiz o teste. Só por curiosidade, como vc implementou essa definição do tamanho da página?

**Comment by robertocvsiqueira** [comment]
Amigo, nada feito...Continua o problema do picote após a carga de papel na impressora...Elgin I9...Nunca pensei que uma só impressora me desse tanto trabalho...

**Comment by mvidaldev** [comment]
Já conferiu versão do firmware da impressora? Habilitou corte após o fim da impressão via gerenciador de impressão?!

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Tue, 27 Sep 2016 05:06:50 -0700

**Comment by robertocvsiqueira** [comment]
A única coisa que não fiz foi verificar o firmware. Tem uma opção de atualizar...Posso ver...Quando tiver acesso à máquina do cliente...

Quanto à opção de picote, não há na impressora em específico...Pelo menos procurei por todos os lugares e não encontrei...ElginUtility e configurações da impressora por Windows...

**Comment by robertocvsiqueira** [comment]
Não teria como implementar o picote no próprio relatório, via algum comando?

**Comment by mvidaldev** [comment]
Acho que não vai anexo no email.

Segue o endereço pra baixar
http://www.casters.com.br/downloads/PacoteElgin.rar

---

From: marcosvidal@outlook.comTo: reply@reply.github.com
Subject: RE: [adeniltonbs/Zeus.Net.NFe.NFCe] Impressão de DANFe com problemas (#200)
Date: Tue, 27 Sep 2016 09:31:39 -0300

Segue anexo arquivos, desinstala tudo de elgin se possivel com o REVO UNNINSTALLER, instala o elgin utilities que esta no pacote, dentro tem uma pasta com o firmware e um manual de como fazer a atualização do mesmo.
Instale usando ESTE driver do pacote, que é o mais atual.

No mais não tem erro, muita gente tem problema semelhante, 

Eu sou autorizado bematech/Elgin aqui na região de Foz do Iguaçu.

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Tue, 27 Sep 2016 05:24:02 -0700

**Comment by adeniltonbs** [comment]
@robertocvsiqueira o que fiz foi habilitar a impressão em doublepass (passo duplo). No primeiro passo é calculado a altura de cada banda. No segundo passo, com base nessa altura, é definida a altura do relatório. O fastreports tem uma propriedade para fazer isso automaticamente "unlimitedheight", no entanto a propriedade afeta somente a visualização do relatório, deixando a impressão com uma margem extra abaixo. Definindo manualmente o tamanho do papel, tanto a visualização como a impressão saem sem a margem extra embaixo.

Por favor, teste a atualização que fiz, imprimindo em pdf e verás a diferença entre a abordagem anterior.
Vou anexar aqui imagens do resultado

**Comment by adeniltonbs** [comment]
> Não teria como implementar o picote no próprio relatório, via algum comando?

Somente implementando a impressão em ESC-POS ou em outra linguagem específica da impressora.

**Comment by robertocvsiqueira** [comment]
Vou tentar anexar o resultado da impressão em PDF aqui.

**Comment by robertocvsiqueira** [comment]
Adenilton,

Segue o PDF que imprimi agora:

[TesteDANFE.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/495730/TesteDANFE.pdf)

**Comment by robertocvsiqueira** [comment]
Pelo menos visualmente ele não tem nenhuma diferença do impresso antes da mudança de controle de tamanho de página.

**Comment by robertocvsiqueira** [comment]
Ao amigo que enviou o pacote de instalação, obrigado! Vou tentar instalá-lo no cliente à tarde.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira Vc atualizou sua biblioteca?
Abaixo está o resultado do teste aqui:
![image](https://cloud.githubusercontent.com/assets/6733483/18878448/f893b5dc-84a6-11e6-8bda-c945e3b1b9f7.png)

[danfe.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/495823/danfe.pdf)

**Comment by adeniltonbs** [comment]
Adicionei no projeto NFe.Danfe.Fast, classe ConfiguracaoDanfeNfce, opção para definir o modo de impressão. Valores possíveis: MultiplasPaginas ou UnicaPagina. O valor padrão é MultiplasPaginas, que era o comportamento anterior da biblioteca.

Commit: b789c86883ba18c1db0fdc10ad3e5f37bafdaa74

**Comment by robertocvsiqueira** [comment]
Adenilton, finalmente a impressão saiu correta. Obrigado! Só mais um detalhe: temos demanda de mais dois relatórios: o pedido (que tem uma parte dos dados da NFC-e) e o controle interno (com uma parte dos dados do pedido). Posso colocar em um novo commit mais dois .frx relativos a essas demandas?

**Comment by adeniltonbs** [comment]
@robertocvsiqueira Que bom que deu certo. Quanto aos relatórios, obrigado pela disposição em colaborar, mas acredito que não fazem parte do escopo deste projeto.
