### ISSUE TITLE
[Duvidas]

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#203]
Bom dia.
No cancelamento da NFe o que seira os seguintes campos, preciso informa-los?
*Identificador de controle do Lote de envio,
*Número sequencial do evento,
*Protocolo de Autorização da NFe.

Lembrando que vou cancelar 1 NFe por vez.

Obrigado.

**Comment by leandrossantos** [comment]
@FabioHenriqueMF 
Eu uso da seguinte maneira:
*Identificador de controle do Lote de envio, = Uso o numero da NFe
*Número sequencial do evento, = 1
*Protocolo de Autorização da NFe. = É o número do protocolo de autorização da NFe que você consegue pela consulta da chave de acesso. o nProt
