### ISSUE TITLE
Carta de Correção

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#204]
Olá, boa tarde

Estou adicionando a carta de correção ao sistema e esta apresentando a seguinte mensagem 

![image](https://cloud.githubusercontent.com/assets/16413266/18795860/ed396d74-819c-11e6-801b-40025d79da9d.png)

Por favor, consegue me ajudar?

Desde já agradeço

**Comment by alsantana** [comment]
O xml gerado foi esse

<evento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" versao="1.00">
  <infEvento Id="ID1101103316081138583600017855099000000002100000002901" xmlns="http://www.portalfiscal.inf.br/nfe">
    <cOrgao>33</cOrgao>
    <tpAmb>2</tpAmb>
    <CNPJ>00984902000100</CNPJ>
    <chNFe>33160811385836000178550990000000021000000029</chNFe>
    <dhEvento>2016-09-23T14:50:28-03:00</dhEvento>
    <tpEvento>110110</tpEvento>
    <nSeqEvento>1</nSeqEvento>
    <verEvento>1.00</verEvento>
    <detEvento versao="1.00">
      <descEvento>Carta de Correção</descEvento>
      <xJust />
      <xCorrecao>ERRO DE EMISSAO - TESTE CARTA CORRECAO</xCorrecao>
      <xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso>
    </detEvento>
  </infEvento>
</evento>

**Comment by alsantana** [comment]
Parte do xml gerado foi esse

[CCe.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/490336/CCe.txt)

**Comment by marcosgerene** [comment]
Se abrir o cce vai ver que existe um elemento xJust ali que está sobrando....  Olha um xml que foi validado:

`<infEvento Id="ID11011Removido01">
<cOrgao>35</cOrgao>
<tpAmb>2</tpAmb>
<CNPJ>Removido </CNPJ>
<chNFe>Removido </chNFe>
<dhEvento>2016-08-31T22:33:38-03:00</dhEvento>
<tpEvento>110110</tpEvento>
<nSeqEvento>1</nSeqEvento>
<verEvento>1.00</verEvento>
<detEvento versao="1.00">
<descEvento>Carta de Correção</descEvento>
<xCorrecao>minha carta de correção teste</xCorrecao>
<xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso>
</detEvento>
</infEvento>`

Provavelmente você está passando a propriedade xJust como vazio, tenta não informar ou informa null...

Abraços, bom final de semana

**Comment by alsantana** [comment]
Ola meu caro, boa tarde

Nas propriedades não tem a propriedade xjust pata a carta de correção, o código que estou utilizando está abaixo.

grd abs

```
`Dim nfeConfiguracao As ConfiguracaoServico = ConfiguracaoServico.Instancia
    nfeConfiguracao.tpAmb = sqlConfiguracao!cfgNFeAmbiente.ToString
    nfeConfiguracao.tpEmis = sqlConfiguracao!cfgNFeEmissao.ToString
    nfeConfiguracao.ModeloDocumento = sqlConfiguracao!cfgNFeTipoDocumento.ToString
    nfeConfiguracao.Certificado.Serial = sqlConfiguracao!cfgNFeCertificado.ToString
    nfeConfiguracao.cUF = sqlConfiguracao!ufID.ToString
    nfeConfiguracao.VersaoRecepcaoEventoCceCancelamento = sqlConfiguracao!cfgNFeRecepcaoEventoVersao.ToString
    nfeConfiguracao.SalvarXmlServicos = True
    nfeConfiguracao.DiretorioSchemas = String.Format("{0}\SCHEMAS\", My.Application.Info.DirectoryPath)
    nfeConfiguracao.DiretorioSalvarXml = String.Format("{0}\XML\", My.Application.Info.DirectoryPath)
    nfeConfiguracao.TimeOut = (Convert.ToInt32(sqlConfiguracao!cfgNFeTimeout.ToString) * 1000)

Dim nfeServicos As New ServicosNFe(nfeConfiguracao)
Dim nfeRetornoCCE As RetornoRecepcaoEvento = nfeServicos.RecepcaoEventoCartaCorrecao(Integer.Parse(txtLote.Text), 1, txtNFe.Text, txtCorrecao.Text, txtCPFCNPJ.Text)
```

**Comment by marcosgerene** [comment]
Boa tarde,
Dei update hoje no nuget, o meu código estava ok, agora estou tendo o mesmo problema relatado pelo colega acima.

**Comment by adeniltonbs** [comment]
@marcosgerene vou verificar...

**Comment by robertorp** [comment]
Para o xJust não aparecer na carta correção tem que alterar o código do Zeus

![servicosnfe cs](https://cloud.githubusercontent.com/assets/10251705/18811613/7496ebb2-828c-11e6-9333-79c451fb4ec5.png)

Arquivo ServicosNFe.cs observem que adicionei 

`var detEvento = new detEvento { versao = versaoServico, xCorrecao = correcao, xJust = null};`

xJust = null

xml gerado depois disso, veio sem a tag "xJust" 

@adeniltonbs

**Comment by adeniltonbs** [comment]
Corrigido no commit 8b9d9459a6de585a14ade85ed314af3478599ce7 e no pull request https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/206

**Comment by robertorp** [comment]
Feito correção no nuget.

**Comment by alsantana** [comment]
Olá, boa tarde
Funcionou sem problemas
Agradeço a tds pela ajuda fiquem com Deus
