### ISSUE TITLE
NVE 

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#207]
@adeniltonbs dê uma olhada no link abaixo, é sobre a forma de uso da tag NVE nos produtos, como poderemos fazer para usar no componente?

[http://www.flexdocs.com.br/guiaNFe/gerarNFe.detalhe.pro.NVE.html](http://www.flexdocs.com.br/guiaNFe/gerarNFe.detalhe.pro.NVE.html)

**Comment by robertorp** [comment]
Já tem no componente, aparentemente está errada porque e aceito de 0-8 
Página 196 
![nve](https://cloud.githubusercontent.com/assets/10251705/18858109/16344ece-8440-11e6-9812-7c609cb2c5e2.png)

![aceitaumsoh](https://cloud.githubusercontent.com/assets/10251705/18858119/2d4a892a-8440-11e6-8d7b-7ef5a956239f.png)

aparentemente no Zeus aceita somente um.

Acredito eu que se alterar para um 

public List<string> NVE {get; set;}

e instanciar o mesmo no construtor , bom ai e testar para saber se vai funcionar

**Comment by leandrossantos** [comment]
@robertorp se você ver no link que passei ele acaba não sendo um list mesmo mais sim um campo que pode se repetir em até 8 vezes.

**Comment by robertorp** [comment]
Certo, mas tem que ser um campo que repete 8 vezes? ou poderia ser uma lista? 
digo porque nesse tempo fiz uma alteração no componente somente para teste e gerei o o xml

![scxml](https://cloud.githubusercontent.com/assets/10251705/18858490/d0519c6a-8442-11e6-8507-7b9aca7d3b22.png)

exemplo de como seria o uso
![usonve](https://cloud.githubusercontent.com/assets/10251705/18858508/eadacf20-8442-11e6-921d-175189067642.png)

**Comment by leandrossantos** [comment]
opa, se gerou assim e deu certo. Então manda pra o @adeniltonbs como fez para ele atualizar no componente.
