### ISSUE TITLE
Esquemas

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#21]
Adenilton, boa tarde...

Muito boa a sua iniciativa... o codigo esta bem escrito...

executei a aplicação para ve o funcionamento....

subiu exceção em relação aos esquemas...

Onde estão esses esquemas???

terei que baixar no site da fazenda?

**Comment by adeniltonbs** [comment]
Estão em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste/Schemas

**Comment by celinolimac** [comment]
Otimo Adenilton, obrigado pelo help...
a biblioteca está muito boa

**Comment by majurr** [comment]
Saudações.

Adenilton, tenho um cliente com um sistema ERP em c# web. O mesmo está
necessitando integrar NFe e NFCe, estado Bahia, no sistema atual.

Gostaria de ajuda nesse procedimento e estou procurando alguém que queira
receber como freela para me ajudar no serviço. Tem interesse ou indica
alguém?

PS: Gostaria de aproveitar a sua ótima biblioteca e já tentar desenvolver o
que falta, como impressão de Danfe, por exemplo.

Aguardo retorno.

_Cordialmente,_

_Mário Nascimento Júnior_
_Tel.: 71 8823-3292 | 71 9188-6879_
_Sistemas de Informação - UNIFACS_

2015-06-26 21:18 GMT-03:00 Zeus Automação Comercial <
notifications@github.com>:

**Comment by willianas1** [comment]
Ótimo projeto, já baixei e no próximo mês estarei implementando a NF-e no meu sistema, espero que tudo corra bem. Qualquer duvida recorro aos senhores.

Parabéns Adenilton, sua iniciativa merece ser divulgada amplamente.

**Comment by adeniltonbs** [comment]
Márcio, não conheço nenhum freelancer no momento. Se desejar colaborar, só me avisar que posso te adicionar como colaborador aqui no git.

**Comment by marcosmarchiore** [comment]
Olá, Adenilton, fiz o download da app e compilei com o vs 2010, não houve mensagens de erro, executo e preencho os dados e peço para salvar, vem ai um erro que atraves de debug constatei que e e na serialize
arquivo funcoesXml.cs na linha com o comando abaixo:

 ser.Serialize(memory, objeto); 

observei que e a parte de geração do xml para gravação.

Você teria o arquivo de configuração para verificar se a falta do mesmo causa este erro.

**Comment by adeniltonbs** [comment]
marcos, testei aqui novamente a biblioteca, executando o aplicativo de teste sem o arquivo de configuração e não ocorre erros.

Se você deixar de configurar algo nas guias do aplicativo de Teste e tentar salvar as configurações, irás receber uma mensagem como esta: 

![image](https://cloud.githubusercontent.com/assets/6733483/8501673/ec2b6a66-217d-11e5-9c2e-46c028690f87.png)

Não tenho como garantir que funcione no VS2010, pois a biblioteca foi desenvolvida com o Visual Studio Community 2013.

Sugiro instalar o Visual Studio Community 2013 e realizar os testes. Qualquer coisa poste aqui.
Obs: Se o assunto não tiver relação com o issue em questão aqui no git, abra um novo issue.

**Comment by marcosmarchiore** [comment]
![image](https://cloud.githubusercontent.com/assets/9381885/8523325/17a4d9c6-23cb-11e5-8df0-c9dc7574e5db.png)

Segue o erro.

**Comment by marcosmarchiore** [comment]
VS 2010, 2013 e 2015 RC Visual Studio

**Comment by adeniltonbs** [comment]
Desculpa a demora. Neste caso, basta alterar o CRT para outro valor e depois voltar para SimplesNacional e salvar. Vou resolver esse problema no app de teste.

**Comment by celinolimac** [comment]
Adenilton, não tem o esquema do  downloadNFe_v9.99.xsd  disponivel nao????

obrigado!!!

**Comment by marcosmarchiore** [comment]
Ok, obrigado a você pelo trabalho, estou em fase de implantação e testes mas já consegui emitir a NFC-e e NF-e agora estou trabalhando para emissão do DANFE PDF para os modelos de impressoras disponiveis, se alguem souber de algo para facilitar este trabalho ou queira disponibilizar, estamos aqui, vou trabalhando e terminando também vou disponibilizar Ok.

**Comment by adeniltonbs** [comment]
celino esse v9.99 é hipotético e deve ser substituído pela versão em vigor, que neste caso é v1.00. Logo, utilize o schema https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.AppTeste/Schemas/downloadNFe_v1.00.xsd

**Comment by adeniltonbs** [comment]
marcosmarchiore, eu utilizo aqui, por enquanto, o ACBRNFeMonitor, que tem função para gerar o pdf, passando para ele o xml.

**Comment by celinolimac** [comment]
show adenilton, blz... mas no seguinte endereço: http://www.nfe.fazenda.gov.br/portal/webservices.aspx
para o meu caso:

NfeDownloadNF   2.00 / 3.10 https://nfe.sefaz.ce.gov.br/nfe2/services/NfeDownloadNF?wsdl

**Comment by adeniltonbs** [comment]
Celinho, eu só encontrei esse esquema para o serviço de download, mas é bom tu dar uma olhada lá no portal da nfe se há outros

**Comment by celinolimac** [comment]
blz Adenilton,

apontando para 1.0

tenho isso:
la no wsdl
no nfeDadosMsg.innerXml = "<downloadNfe versao=\"1.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><tpAmb>1</tpAmb><xServ>DOWNLOAD NFE</xServ><CNPJ>01585692000140</CNPJ><chNFe>23150404849244000102550010000002191434408027</chNFe></downloadNfe>"

e meu retorno é "1CE_NFe_V3.10.0.15239Rejeicao: Cabecalho - Versao do arquivo XML nao suportada2015-07-08T17:02:14"

**Comment by celinolimac** [comment]
blz Adenilton,

apontando para 1.0

tenho isso:
la no wsdl
no nfeDadosMsg.innerXml = "<downloadNfe versao=\"1.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><tpAmb>1</tpAmb><xServ>DOWNLOAD NFE</xServ><CNPJ>01585692000140</CNPJ><chNFe>23150404849244000102550010000002191434408027</chNFe></downloadNfe>"

e meu retorno é "1CE_NFe_V3.10.0.15239Rejeicao: Cabecalho - Versao do arquivo XML nao suportada2015-07-08T17:02:14"

**Comment by celinolimac** [comment]
blz Adenilton,

apontando para 1.0

tenho isso:
la no wsdl
no nfeDadosMsg.innerXml = "<downloadNfe versao=\"1.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><tpAmb>1</tpAmb><xServ>DOWNLOAD NFE</xServ><CNPJ>01585692000140</CNPJ><chNFe>23150404849244000102550010000002191434408027</chNFe></downloadNfe>"

e meu retorno é "1CE_NFe_V3.10.0.15239Rejeicao: Cabecalho - Versao do arquivo XML nao suportada2015-07-08T17:02:14"

**Comment by celinolimac** [comment]
Adenilton,

apontando para 1.00 tenho o seguinte cenario:

no WSDL do nfeDownload q criei

em nfeDadosMsg.innerXml = "<downloadNfe versao=\"1.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><tpAmb>1</tpAmb><xServ>DOWNLOAD NFE</xServ><CNPJ>01585692000140</CNPJ><chNFe>23150404849244000102550010000002191434408027</chNFe></downloadNfe>"


e tenho o seguinte retorno do WS

"1CE_NFe_V3.10.0.15239Rejeicao: Cabecalho - Versao do arquivo XML nao suportada2015-07-08T17:02:14"

**Comment by celinolimac** [comment]
Adenilton,

apontando para 1.00 tenho o seguinte cenario:

no WSDL do nfeDownload q criei

em nfeDadosMsg.innerXml = "<--downloadNfe versao=\"1.00\" xmlns=\"http://www.portalfiscal.inf.br/nfe\"><--tpAmb>1<--/tpAmb><--xServ>DOWNLOAD NFE<--/xServ><--CNPJ>01585692000140<--/CNPJ><--chNFe>23150404849244000102550010000002191434408027<--/chNFe><--/downloadNfe>"

PS. coloquei os comentarios nas tags aqui no post pois o github estava ocultando o conteudo das tags, favor desconsiderar "<-->"

e tenho o seguinte retorno do WS

"1CE_NFe_V3.10.0.15239Rejeicao: Cabecalho - Versao do arquivo XML nao suportada2015-07-08T17:02:14"

**Comment by adeniltonbs** [comment]
Nem sempre o nome do schema está relacionado com a versão do serviço rodando em determinado servidor. Por exemplo, considere o schema para validação do evento EPEC (eventoEPEC_v0.01.xsd). Embora o sufixo do nome dele seja 0.01, não quer dizer que se refere a um serviço na versão 0.01.

Outra coisa, o schema serve somente para nós podermos validar a mensagem de envio, antes de enviá-la, possibilitando assim que tenhamos parte das regras no lado do cliente. Desta forma podemos economizar a banda de dados, uma vez que se o xml não passar pelo schema, tampouco passará pelo servidor da sefaz. Então fique a vontade, por exemplo, de fazer seus testes sem sujeitar o xml a um schema.

**Comment by celinolimac** [comment]
blz foi isso que fiz... pulei  a parte da validacao e fui direto para os passos seguintes...
cheguei na parte do WSDL e indiquei o invoke e tive o retorno que indiquei no post anterior da rejeição do cabeçalho.

Vou continuar tentando...
obrigado e quando conseguir implementar essa funcionalidade passo pra vc ve se add no projeto...

**Comment by adeniltonbs** [comment]
Outra coisa, se você abrir o schema downloadNFe_v1.00.xsd vai ver que ele aponta para outro schema chamado leiauteDownloadNFe_v1.00.xsd que por sua vez aponta para o schema tiposBasico_v1.03.xsd e abaixo segue a validação para a tag versao:

```
<xs:simpleType name="TVerAplic">
    <xs:annotation>
        <xs:documentation>Tipo Versão do Aplicativo</xs:documentation>
    </xs:annotation>
    <xs:restriction base="nfe:TString">
        <xs:minLength value="1"/>
        <xs:maxLength value="20"/>
    </xs:restriction>
</xs:simpleType>
```

O campo versao somente valida o tamanho da string que deve ser de 1 a 20

E por fim o schema tiposBasico_v1.03.xsd é usado por outros schemas utilizados em serviços com versões maiores que 1.00

**Comment by adeniltonbs** [comment]
blz

**Comment by adeniltonbs** [comment]
Se não conseguir me avisa. depois vou dar uma olhada nesse serviço. Boa noite

**Comment by adeniltonbs** [comment]
Ah na mensagem que vc manda por servidor, independente do nome do schema, você tem que mandar a versao aceita pela SEFAZ em questão, então troque versao="1.00" por versao="2.00" ou versao="3.10"

**Comment by celinolimac** [comment]
Blz, ja fiz isso

**Comment by adeniltonbs** [comment]
celino, implementei o consumo do serviço de NfeDownloadNF. Testado para o Ambiente Nacional - (AN).

**Comment by celinolimac** [comment]
poxa adenilton...q legal... hoje ainda n mexi no projeto... fiquei naquela do cabeçalho

Mas ja vou ve agora a tarde...

jaja puxo o ultimo commit.... e ve como ficou.... valewww

**Comment by celinolimac** [comment]
Boa tarde Adenilton, vi aqui como ficou...

show viu... com as definicoes wsdl consegui tambem testar com o AN no teste que eu tinha iniciado ontem...

Não tive a mesma sensibilidade que vc para rodar na 1.00... estava tentando sempre a 2.00 e a 3.10

valew de mais...

Agora tanto a versao que eu tinha implementado, como a que esta nesse ultimo commit temos aquele retorno que citei da rejeição do cabeçalho... isso apontei no caso para o CE... no AN blz..

Lembra q te falei adenilton, que eu tava pensando numa forma de fazer parecido como a
sefaz, de o cara passar a chave e retornar todas as informações da nota... sendo que no manual do contribuinte nao tem nenhum WS para isso como vc mesmo disse e te perguntei se era possivel com o downloadNfe e depois montar esses dados....

O problema nisso é que a utilização do download so vai servir por 30 dias ne da autorização da nota?... e a solicitação para o destinatario... dai ja foge da proposta...

Com a sua experiencia vc nunca viu, ouviu se tem como fazer isso num aplicação propria, sem ser pelo portal da fazenda??? Sei nem se e possivel.. enfim...

valew.... :-)

**Comment by adeniltonbs** [comment]
Isso mesmo celino, não há nenhum ws e nem previsão para um que faça isso.
Quanto ao serviço de download é exatamente como descreveu, só dá pra baixar por 30 dias após a emissão, pelo destinatário (o serviço vai checar se o cnpj base do certificado é igual ao cnpj base do destinatário da nfe, cuja chave foi passada como parâmetro) e se houver um evento de manifestação do destinatário.

Pela minha experiência a melhor solução para trabalhar com um aplicativo emissor de nfe/nfce é armazenar o xml no banco.

Se você realmente precisar acessar as informações da nfe somente pela chave, a única forma será montar um aplicativo com um webbrowser apontando para o site de consulta completa da nfe, pegar o  containner com o captcha, a textbox da chave e o botão de consulta, e assim que o usuário digitar o captcha e a chave, você envia a solicitação para o site e daí pega o html gerado pelo site e trata para montar de forma reversa o xml. Esse aplicativo aqui faz isso: http://fsist.blogspot.com.br/2012/10/download-da-xml-da-nota-fiscal.html

O problema dessa abordagem é que o xml que você montar não vai ter nenhuma credibilidade e seu programa vai quebrar toda vez que a sefaz alterar o layout do site.

**Comment by celinolimac** [comment]
entendi perfeitamente...
talvez 
essa estrategia não seja a melhor no momento...

Valew viu Adenilton pela consultoria.. rsssss

Continuar os trabalhos..
abraço

**Comment by xtsolucoes** [comment]
Ola boa tarde estou tentando localizar esta pasta de schemas. Será que tem que baixar da receita ?
![screen shot 2015-09-25 at 6 27 36 pm](https://cloud.githubusercontent.com/assets/11356150/10112639/3125356c-63b3-11e5-9517-6bdc2d37fab5.png)

**Comment by adeniltonbs** [comment]
Os esquemas se encontram em
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste/Schemas
Em 25/09/2015 18:29, "xtsolucoes" notifications@github.com escreveu:

**Comment by xtsolucoes** [comment]
Ok Muito obrigado. so mais uma duvida tem algum manual de configuração ?

**Comment by xtsolucoes** [comment]
Na verdade queria fazer a homologação pelo AM bfce é possivel  ?

**Comment by jonathanMarquesCosta** [comment]
b n nb nb nm

**Comment by ghost** [comment]
Boa tarde, baixei o fonte e executei conforme instruções, porém está apresentando uns erros de referência na dll de Nfe.Utils. 

Existe também outro erro na impressão, na referencia ao FastReport.

Estou enviando abaixo o print, há alguma maneira de corrigir isso ?
Desde já, agradeço pela atenção e ajuda.

![capturar](https://cloud.githubusercontent.com/assets/13037360/15832492/d8d9acc6-2bf8-11e6-8eec-641fd7be41fc.PNG)

![capturar](https://cloud.githubusercontent.com/assets/13037360/15833160/e4380fd8-2bfb-11e6-988d-2417dbfe2d14.PNG)

**Comment by adeniltonbs** [comment]
@jonathanMarquesCosta dê uma olhada neste issue: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/69

Duas dicas: 
1 - Você pode pesquisar issues em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues;
2 - Não escreva uma mensagem em um issue antigo, ao invés disso, abra um novo.
