### ISSUE TITLE
Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA

### ISSUE THREAD

**Issue by thiagotargus** [ZeusAutomacao/DFe.NET#214]
Boa noite,

Comecei a receber essa rejeição hoje (29/09/2016) no ambiente de homologação, aparentemente é uma regra de validação que vai iniciar em produção no dia (03/04/2017). 
Tem haver com a sequencia de escape da UrlQrCode que atualmente o componente gera `&amp;` onde deve ser apenas &, para separar os parâmetros.
- No QR-Code de uma NFC-e, todos os parâmetros devem ser separados pelo caractere e-comercial (&).

**Comment by adeniltonbs** [comment]
Boa noite, @thiagotargus chegou a ver o commit 837dd5490731c44d0d2d84c5f7e75750d6612978 e posteriores?

Baixe a versão mais recente da biblioteca por aqui, e teste novamente.

**Comment by vasisti** [comment]
Ola Adenilton saudações,
nesta ultima atualização  da biblioteca apos o uso do CDATA, as notas estao enviando normalmente (PR), mas não estou conseguindo validar o arquivo no validador da sefaz RS, e nem editar o arquivo em editores de XML. obs: ja atualizei o commit da resposta anterior, ok, Abraços.

**Comment by adeniltonbs** [comment]
Poderia nos enviar o xml gerado para conferirmos o que há de errado nele?

**Comment by adeniltonbs** [comment]
A título de curiosidade, validei o XML anexado no site https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx e validou normalmente.

Note a imagem dele no notepad++
![image](https://cloud.githubusercontent.com/assets/6733483/19036862/25943b8c-8949-11e6-981d-dbb394595493.png)

[28160907703290000189650010000009331000000015-NFe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/506160/28160907703290000189650010000009331000000015-NFe.zip)

**Comment by vasisti** [comment]
Ola Adenilton boa tarde, depois que te relatei o erro verifiquei que o arquivo estava sem a tag CDATA, ou seja, a biblioteca quando gera o arquivo de envio (1-env-lot) gera normalmente com o CDATA, mas na rotina de (Adicionar proc ao XML) o arquivo perde o CDATA. gerando o erro que relatei.

obs: no metodo fiz a seguinte alteracao e deu certo, verifique e valide, ok abraços.

```
    private void BtnAdicionaNfeproc_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            var arquivoXml = Funcoes.BuscarArquivoXml();
            var nfe = new Classes.NFe().CarregarDeArquivoXml(arquivoXml);
            var chave = nfe.infNFe.Id.Substring(3);

            if (string.IsNullOrEmpty(chave)) throw new Exception("A Chave da NFe não foi encontrada no arquivo!");
            if (chave.Length != 44) throw new Exception("Chave deve conter 44 caracteres!");

            var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
            var retornoConsulta = servicoNFe.NfeConsultaProtocolo(chave);
            TrataRetorno(retornoConsulta);

        //alterei aqui
```

   nfe.infNFeSupl.qrCode = new XCData(nfe.infNFeSupl.qrCode).ToString();

```
            var nfeproc = new nfeProc
            {
                NFe = nfe,
                protNFe = retornoConsulta.Retorno.protNFe,
                versao = retornoConsulta.Retorno.versao
            };
            var novoArquivo = Path.GetDirectoryName(arquivoXml) + @"\" + nfeproc.protNFe.infProt.chNFe +
                              "-procNfe.xml";
            FuncoesXml.ClasseParaArquivoXml(nfeproc, novoArquivo);
            Funcoes.Mensagem("Arquivo salvo em " + novoArquivo, "Atenção", MessageBoxButton.OK);
        }
        catch (Exception ex)
        {
            if (!string.IsNullOrEmpty(ex.Message))
                Funcoes.Mensagem(ex.Message, "Erro", MessageBoxButton.OK);
        }
    }
```

---

De: Zeus Automação Comercial notifications@github.com
Enviado: segunda-feira, 3 de outubro de 2016 09:10:10
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: vasisti; Comment
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA (#214)

A título de curiosidade, validei o XML anexado no site https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx e validou normalmente.

Note a imagem dele no notepad++
[image]https://cloud.githubusercontent.com/assets/6733483/19036862/25943b8c-8949-11e6-981d-dbb394595493.png

##

**Comment by adeniltonbs** [comment]
@vasisti Boa tarde,
Vi sua dica, mas fiquei pensando: Em quais outros pontos alguém mais iria precisar serializar o atributo qrCode como CDATA?

Para resolver isso de uma vez, refatorei conforme commit f49dc799046be6f737ed01ac5d8052d63d2ea2bc, movendo a responsabilidade pela serialização do atributo qrCode no formato CDATA, para a própria classe infNFeSupl. Já testei aqui em algumas situações. Por favor teste seus casos de uso, e qualquer coisa, reporte.

No aguardo, e obr pela colaboração.

**Comment by vasisti** [comment]
Ola Adenilton, saudações.
conforme o email anterior fiz aqui os testes e deu tudo certo, ok.
obrigado,
abraços

Valdir

---

De: Zeus Automação Comercial notifications@github.com
Enviado: terça-feira, 4 de outubro de 2016 16:46:09
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: vasisti; Mention
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA (#214)

@vasistihttps://github.com/vasisti Boa tarde,
Vi sua dica, mas fiquei pensando: Em quais outros pontos alguém mais iria precisar serializar o atributo qrCode como CDATA?

Para resolver isso de uma vez, refatorei conforme commit f49dc79https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/commit/f49dc799046be6f737ed01ac5d8052d63d2ea2bc, movendo a responsabilidade pela serialização do atributo no formato CDATA, para a própria classe infNFeSupl. Já testei aqui em algumas situações. Por favor teste seus casos de uso, e qualquer coisa, reporte.

No aguardo, e obr pela colaboração.

##
