### ISSUE TITLE
Erro no documento XML

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#217]
Adenilton, bom dia,

Atualizei as dlls com a última versão que contempla a parte de Serialização do QrCode a cargo do InfNFeSupl, baixando o ZIP para minha máquina, abrindo o projeto, compilando-o e automaticamente atualizou as referências na minha aplicação, já que suas referências apontam para as dlls compiladas no projeto. Porém quando fui testar no cliente ocorreu um erro: "Erro no documento XML (1, 1660)", sem mais detalhes. O que pode ter ocorrido? Estava funcionando antes da inclusão de validação do QrCode da SEFAZ.

Obrigado desde já,
Roberto.

**Comment by robertocvsiqueira** [comment]
Descobri onde era o erro. A Razão Social do cliente tem um "&" e acarretou o erro no arquivo configuracao.xml. Como posso tratar isso?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira Corrigindo...

**Comment by robertocvsiqueira** [comment]
Mas não é permitido o "&" na Razão Social?

**Comment by adeniltonbs** [comment]
Sim é permitido, mas tem que ser enviado com escape (& amp;).
Tinha alterado a biblioteca para, no momento da serialização, substituir os caracteres de escape pelo literal, por conta do qrCode que não aceita mais caracteres de escape.

O que fiz nesse commit, foi deixar os escapes no XML, e não enviá-los somente no qrCode.
