### ISSUE TITLE
A conexão subjacente estava fechada

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#219]
Bom dia a todos,

Ontem demonstrando o sistema para um parceiro esbarrei num erro que nunca havia acontecido:

"A conexão subjacente estava fechada: Erro inesperado em um envio."

Voltei para casa, e pesquisando vi que a **Flexdocs** relatava o mesmo problema e que fizeram algo que sanou o problema, e que o problema estava relacionado ao certificado digital.

Pois bem, utilizando outro certificado (A3) o problema "sumiu", logo o problema seria no certificado, mas o estranho é que uso este mesmo certificado (A1) para testes faz uns 40 dias e ele está válido.
O problema não é do componente, pois uso o nuget para referenciar, ainda estou na compilação 205 (bem para trás das novas compilações) e uso esta versão com este certificado por um tempo já.

Testando o certificado problemático (A1) tentando fazer o download de um XML no site da receita, funcionou perfeitamente, o problema ocorre com esse certificado e no sistema.

Vou tentar achar outro certificado A1 para ter certeza que o problema está nesse certificado e não no modelo (o A3 funcionou perfeitamente). O engraçado é que o XML é assinado normalmente, o erro acontece ao consumir o WS.

O erro acontece na linha destacada (breakpoint):

![codigo](https://cloud.githubusercontent.com/assets/15945003/19212887/f3112c7c-8d32-11e6-9204-0c60693b191e.png)

O exception:

![erro](https://cloud.githubusercontent.com/assets/15945003/19212890/0e04895c-8d33-11e6-983b-a5cc123c005e.png)

PS: Tentei isto: http://demeter-net.blogspot.com.br/2011/06/nfe-20-conexao-subjacente-estava.html mas não obtive sucesso.

Quanto ao link do Flexdocs: http://www.flexdocs.com.br/guiaNFe/FAQ.conexao.html

Em outro componente: http://nf-eletronica.com/blog/?cat=110

Ps2: a UF é SP.

Abraços e bom final de semana a todos

---

**UPDATE**: Acabei de testar com outro certificado A1 e o problema se repetiu.

---

**UPDATE 2:** o problema também ocorre no app teste com a versão mais atual do componente

![appteste](https://cloud.githubusercontent.com/assets/15945003/19213149/d7126f02-8d39-11e6-8b31-7dde50739b4b.png)

---
## **UPDATE 3:** Testando em uma máquina virtual com windows 7 recebi o mesmo erro.

**Update 4:** Instalei o emissor gratuito e fiz o teste do certificado... funcionou...

![emissorsefaz](https://cloud.githubusercontent.com/assets/15945003/19213551/290111c8-8d45-11e6-9236-e3484880086a.png)

---

**Update 5:** Testando na minha máquina com o ACBr demo obtive a mesma resposta (10029).

---

**Update 6 (e último):** Testei o sistema em uma máquina nova com windows 7 completamente virgem de sistema (nunca foi usado para emitir uma NFe) e o problema se repetiu.

---

Considerações finais: O sistema estava funcionando e não foi alterado, testei em 2 SOs, em 2 máquinas e em 2 provedores de internet diferentes.
No emissor gratuito funciona, no sistema não. Esgotei meus testes, aguardo um apoio da comunidade para passar um posicionamento para o cliente.

**Comment by marcosgerene** [comment]
Solução: mudei o ambiente no cliente de **HOMOLOGAÇÃO** para **PRODUÇÃO** para fazer um teste e o erro mudou para  "_Não foi possível criar um canal seguro para SSL/TLS_".

Então adicionei as seguintes linhas antes de fazer a requisição:

```
                ServicePointManager.Expect100Continue = true;
                ServicePointManager.CheckCertificateRevocationList = false;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
```

Resultado: funcionou.

Conclusão: Meu teste no emissor gratuito foi em ambiente de produção, por isso obtive sucesso, bastou alterar o ambiente que o erro foi sanado, logo o problema acima está do lado do WS (homologação).

Abraços

**Comment by rftd** [comment]
Marcos este erro geralmente é associado também a falta do certificado do raiz no computador.

**Comment by marcosgerene** [comment]
@rftd 
Boa tarde,

A qual dos erros se refere? o primeiro ou o segundo (SSL)?

Desculpa, não compreendi, pode me explicar rapidamente o que seria esse "certificado na raiz do computador"? É uma aplicação winforms e o certificado aparece instalado no IE, não especificamente neste caso (aonde acredito ser o WS), o que mais eu poderia verificar?

PS: As configurações do IE (TLS, SLL, checar se está revogado e afins) eu aproveitei "o embalo" para deixar o cliente configurar diretamente via sistema, quero que a configuração dependa o mínimo de fontes externas.

abraço

**Comment by leandrossantos** [comment]
@marcosgerene tem como mandar um print de onde vc colocou:

> ```
>             ServicePointManager.Expect100Continue = true;
>             ServicePointManager.CheckCertificateRevocationList = false;
>             ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
> ```

E você disse que funcionou ai.

**Comment by marcosgerene** [comment]
Bom dia @leandrossantos ,

Antes de começar a preencher o objeto NFe, eu chamo uma função minha "Configurar Componente", ela seta todas as informações, desde o PATH até as versões dos protocolos.

Joguei essas linhas nesta função...
`        public static void ConfigurarComponente(GCore.ModeloDFe modeloDocto)
        {
            ServicePointManager.Expect100Continue = ConfigLocal.Expect100Continue;
            ServicePointManager.CheckCertificateRevocationList = ConfigLocal.CheckCertificateRevocationList;
            if (ConfigLocal.ForcarSSL)
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;

```
        Emitente = new NFe.Classes.Informacoes.Emitente.emit();
        ....
```

}
`

**Comment by andreraujo** [comment]
BOAS PESSOAL.... PARA RESOLVER ESSE PROBLEMA TEM Q SETAR O PROTOCOLO DE SEGURANÇA PARA: "TIs" , na aba configuração WebService.
Porem gostaria de saber para q serve esse protocolo, visto q é a primeira vez q me deparo  com esse atributo, já q na NFe não verifico se tem q ser protocolo de segurança SSI3 ou TIs. Desde já agradeço, abc a todos os desvenvolvedores sofredores...
