### ISSUE TITLE
Pesquisa por chave - Dados da NFE

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#22]
Adenilton, na biblioteca existe a (consulta) recuperação os dados da nfe pela chave de acesso???

ao executar a função da biblioteca "consultar pela chave" ele consulta a situacao da nfe pela chave...

Se vc poder me colocar como colaborador será otimo... 

obrigado!

**Comment by adeniltonbs** [comment]
celino, já te adicionei como colaborador.
Quanto a sua pergunta o mais correto seria: O projeto da NFe provê um serviço que eu possa usar para recuperar os dados da nfe passando a chave de acesso?

Resposta: Não

O serviço nfeConsultaNF2 só devolve as informações constantes no layout retConsSitNFe_v2.01.xsd.
Veja a página 55 do Manual de Orientação Contribuinte v 6.00 - Minuta.

Agora se o contribuinte for emitente/destinatário da nota, ou se seu CPF/CNPJ estiver incluído na lista de entes autorizados a fazer download daquele XML em específico (tag GA01 - autXML), ele poderá consumir o serviço NfeDownloadNF e fazer download do xml da nota e dos eventos relacionados a ela. Note porém que esta biblioteca ainda não implementou o consumo do serviço NfeDownloadNF, conforme TODO em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe.

**Comment by celinolimac** [comment]
Bom dia Adenilton, obrigado por adicionar e pelo retorno..

Então tentarei colaborar com isso, pois estou precisando dessa funcionalidade.
Quaisquer novidade entro em contato.

Obrigado

**Comment by adeniltonbs** [comment]
Por nada, mas celino, acho que você não entendeu o que eu quis dizer.
Não é a biblioteca que não tem essa funcionalidade, é o projeto nacional da NFe que não implementou nenhum webservice com essa funcionalidade.

Só para te situar, deixe eu te perguntar: Qual o serviço descrito no manual da NFe ou em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs= que contém essa funcionalidade?

**Comment by celinolimac** [comment]
Isso mesmo Adenilton, mas o que quis dizer foi o seguinte...
quando consultamos a NFE no site da fazenda... passamos a chave e logo ele nos retorna as informações da nota... logo imaginei que na bilblioteca teria ja essa funcionalidade... então vc me respondeu que eu precisaria de "NfeDownloadNF" (se o contribuinte for emitente/destinatário da nota, ou se seu CPF/CNPJ estiver incluído na lista de entes autorizados a fazer download do XML)... então por exemplo, aqui para o CE: NfeDownloadNF 2.00 / 3.10 https://nfe.sefaz.ce.gov.br/nfe2/services/NfeDownloadNF?wsdl

isso me retornaria o que preciso não?

Outra, testando a biblioteca me deparei com a seguinte situação, quando executo o "CadConsultaCadastro2"... passando os dados necessarios, passo por exemplo um CNPJ de um emitente e o retorno do invoke do "consultaCadastro2" até indica retornar um objeto, porem esse sempre vem nulo... penso q seja algo no WS...

**Comment by viniguerrero** [comment]
Boa Tarde Adenilton, tudo certo?

Sou iniciante nos processos fiscais, mas trabalho com C#.
Saberia me dizer se consigo aproveitar o módulo do Zeus para geração do XML de um CTe?
E como posso testar a validade desse XML que seria gerado?
Tenho encontrado certa dificuldade em utilizar os xsds do governo, pois não soube montar exatamente o xml da maneira que é pedido...
Seria possível aproveitar o Zeus para um projeto TMS? Gerarando um conhecimento de transporte rodoviário?

Desde já, obrigado!

**Comment by adeniltonbs** [comment]
Ok celino, com o serviço NfeDownloadNF irás ter acesso ao xml da NFe. Por sua vez você poderá carregar este xml direto na classe da biblioteca para ler os dados facilmente.

Quanto ao serviço CadConsultaCadastro2 vi aqui que o soap action e o result deste webservice para o estado do CE são diferentes. Provavelmente vou ter que usar WebRequest para consumir este serviço para todos os Estados. Assim que tiver um tempinho faço essa alteração. Se você já estiver precisando consumir este serviço altere sua classe CadConsultaCadastro2 para:

``` cs
[WebServiceBinding(Name = "CadConsultaCadastro2Soap12", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
public class CadConsultaCadastro2 : SoapHttpClientProtocol, INfeServico
{
    public CadConsultaCadastro2(string url, X509Certificate certificado, int timeOut)
    {
        SoapVersion = SoapProtocolVersion.Soap12;
        Url = url;
        Timeout = timeOut;
        ClientCertificates.Add(certificado);
    }

    [XmlAttribute(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
    public nfeCabecMsg nfeCabecMsg { get; set; }

    [SoapHeader("nfeCabecMsg", Direction = SoapHeaderDirection.InOut)]
    [SoapDocumentMethod("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2/consultaCadastro2", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Bare
        )]
    [WebMethod(MessageName = "consultaCadastro2")]
    [return: XmlElement("cadConsultaCadastro2Result", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")]
    public XmlNode Execute([XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")] XmlNode nfeDadosMsg)
    {
        var results = Invoke("consultaCadastro2", new object[] {nfeDadosMsg});
        return ((XmlNode) (results[0]));
    }
}
```

**Comment by adeniltonbs** [comment]
viniguerrero, esta biblioteca é para geração de NFe/NFCe. Ela não irá gerar o xml do CTe. O que você pode fazer é observar como ela funciona para você montar a sua biblioteca para CTe.

Obs: Caso tenha uma dúvida não relacionada com o issue em aberto, abra um novo.
Obs2: Caso deseje, poderá colaborar para implementar o CTe nesta biblioteca e compartilhar com os demais.

**Comment by celinolimac** [comment]
Show Adenilton, deu certo mesmo... valew

**Comment by willianas1** [comment]
Bom dia Adenilton,

Seu projeto é fantástico, vejo em pouco tempo ele se tornando referencia para desenvolvedores .Net, assim como o AcBr é para Delphi.

**Comment by adeniltonbs** [comment]
Obrigado pelo apoio.

**Comment by adeniltonbs** [comment]
celino, as alterações para estado do CE foram incluídas no commit f581d5e65102bbf3dd726a7fa7dae49241ae14c9.
