### ISSUE TITLE
Passo a Passo para Homologacao de NFe

### ISSUE THREAD

**Issue by brunobertechini** [ZeusAutomacao/DFe.NET#220]
Olá 

Gostaria de saber se alguém que já usa a biblioteca tem um passo a passo resumido de como testar a homologacao usando o app de teste para que eu possa entender o fluxo e implementar a emissao usando esta biblioteca.

Pretendo emitir apenas NFe.

Bruno

**Comment by adeniltonbs** [comment]
Boa tarde, dê uma olhada em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114

**Comment by brunobertechini** [comment]
Valeu

Estudando ja ;)

Bruno

**Comment by brunobertechini** [comment]
Olá vi na #114 o seguinte:

Obs: 
Estes dois campos são usados na montagem do Qr-Code do DANFE da NFCe;
A biblioteca não tem suporte ao DANFE da NFe até o presente momento;

Isto ainda procede? Não consigo gerar a DANFE para impressão da NFe ?

Bruno

**Comment by brunobertechini** [comment]
Alguma novidade?

**Comment by robertorp** [comment]
Os últimos commits da biblioteca teve mudanças no Danfe da nf-e, teste eles.

**Comment by marcosgerene** [comment]
@brunobertechini 

A impressão da DANFE na orientação RETRATO em FAST REPORTS está ok, eu uso em produção, só precisaria que subissem pro nuget (separado do principal para não depender do fast reports).

A impressão da DANFCe na impressora térmica também está ok e também em fastreports.

O componente **ainda** não imprime eventos (ex; carta de correção), não imprime a NFe Paisagem  e nem a nfce em A4 (retrato ou paisagem).

**Comment by adeniltonbs** [comment]
@brunobertechini 

- Impressão de carta de correção Ok;

Ainda falta NFe paisagem e NFCe A4 (retrato ou paisagem).
