### ISSUE TITLE
Certificado para Homologação Publico?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#221]
Bom dia pessoal.

Por acaso existe algum certificado publico para homologação disponibilizado pela SEFAZ ou outro órgão?

**Comment by rftd** [comment]
Não você precisa usar o seu certificado ou o do cliente para fazer os testes.

**Comment by francofs** [comment]
Apenas para complementar a experiência, o ideal é que use um certificado
com registro de IE no estado que você está emitindo nota.

O Estado AM aceita emitentes sem IE, porém se tentar emitir uma nota em SP
não vai conseguir se sua empresa não tiver IE, aí no caso só com o
certificado do cliente mesmo. Além disso SP é bem mais rigoroso nas
validações. Não sei quanto aos outros estados.

On Tue, Oct 11, 2016 at 11:15 AM, Rafael Teno Dias <notifications@github.com
