### ISSUE TITLE
RetAutorização + Duvidas Retorno do envio da NFe

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#223]
Boa tarde pessoal.
Tenho algumas dúvidas a respeito do Retorno apos enviar uma NFe a SEFAZ
A sequencia Lógica dos métodos seria(?????):

(1°) var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe> { _nfe }, true/_Envia a mensagem compactada para a SEFAZ_/);

(2°) var retornoRecibo = servicoNFe.NFeRetAutorizacao(recibo); (duvida "recibo" é o xml da NFe???, outra: qual a finalidade deste metodo, apenas o retorna o protocolo?????)

(3°) var retornoConsulta = servicoNFe.NfeConsultaProtocolo(chave);

Obrigado pela colaboração.

**Comment by adeniltonbs** [comment]
Boa tarde @FabioHenriqueMF 

**Se você for consumir o serviço de forma assíncrona, vide o manual de orientação, então a sequência é:**

``` cs
(1°) var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List { _nfe }, true/Envia a mensagem compactada para a SEFAZ/);

(2°) var retornoRecibo = servicoNFe.NFeRetAutorizacao(recibo); 
```

**Se você for consumir o serviço de forma síncrona, então basta:** 

``` cs
var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List { _nfe }, true/Envia a mensagem compactada para a SEFAZ/);
```

**"recibo" é o xml da NFe???**
Não. Recibo é um código gerado pelo serviço NFeAutorizacao, quando consumido de forma assíncrona, para que você possa depois consultar o resultado do processamento da NFe enviada.

**qual a finalidade deste metodo(NFeRetAutorizacao), apenas o retorna o protocolo?????**
Não. Retorna o resultado do processamento do serviço NFeAutorizacao, quando este for consumido de forma assíncrona.

Dê uma olhada no manual de orientação em http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=.

Leia a descrição desses serviços, que entenderás melhor a utilidade deles. A descrição não é extensa.
