### ISSUE TITLE
Aceitar certificado digital A1 em base64

### ISSUE THREAD

**Issue by gubarusco** [ZeusAutomacao/DFe.NET#224]
Boa tarde pessoal!

Eu vi no to do list da biblioteca para passa a aceitar o certificado digital em base64. Eu acredito que vou precisar disso.
Tem alguém desenvolvendo já ou eu poderia implementar?
Adenilton, como posso entrar em contato com você para entender melhor qual é essa necessidade?

Abraços
Gustavo

**Comment by luiszimmermann** [comment]
Acredito que eu esteja fazendo isso... no momento ainda em fase de testes, já fiz um fork e farei um pull request quando estiver testado o suficiente.

**Comment by adeniltonbs** [comment]
@ernanisp está desenvolvendo essa rotina. 
Grupo [Skype](https://join.skype.com/CJbtNPlvbycL) para discussão de desenvolvimento.

**Comment by adeniltonbs** [comment]
Opa o @luiszimmermann tb ^^

**Comment by gubarusco** [comment]
Vou entrar no grupo para discussão.

Abraços
