### ISSUE TITLE
Dúvida rápida de tributação NFC-e

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#225]
Posso ter um sistema somente com os csosn

102 - 300 - 500 ? (o sistema não teria PIS.. etc..)

Digo não daria mais opção nem uma para o cliente, isso seria correto?
(clientes ultra pequenos os menores bem simples que usam apenas um pc e vendem ai 500-1200 por dia)

Sistema não teria muita coisa, algo do tipo cadastro de produto/cliente simplificado, controle de estoque fim do sistema, (entrada poderia colocar somente uma importação de alteração dos produtos, basicamente importaria o xml nfe pra dentro do sistema alterando somente o estoque mais nada).

**Comment by orochasamuel** [comment]
@robertorp mesmo que a movimentação do cliente seja pequena ainda deve-se conter no sistema os dados mais básicos relativos a escrita fiscal. Infelizmente isso é chato.

Imagino que seu cliente seja obrigado à transmissão do Sintegra. Logo, a relação CFOPxCSTxALIQUOTA deve estar da forma correta para geração do arquivo.

Os lançamentos de entrada das notas DEVEM SEMPRE serem feitos com enfoque no comprador/declarante (na empresa que compra ou está transmitindo alguma declaração para a RFB/SEFAZ).

Exemplo:
Seu cliente recebe uma nota com suco em lata de determinado fornecedor com os seguintes dados:
CFOP 5.102
CST 000 - Tributado integralmente

ENTRADA - Caso seja mercadoria para revenda:
CFOP 1.102
CST 000 - Tributado integralmente

ENTRADA - Caso seja mercadoria para consumo interno ou uso próprio:
CFOP 1.556
CST 090 - Outras

Há muitos casos em que o empresário usa a mercadoria para consumo interno e não lança corretamente no sistema muito menos informa o escritório contábil, logo a escrita contábil/fiscal não irá ficar legal.

É interessante também, por menor que seja o sistema ou a empresa cliente, controlar valores por centro de custo. Isso fornece uma visão diferente na gestão.

Edit
O cenário citado acima serve para as entradas de notas. Em resposta a sua dúvida, pode sim funcionar somente com o CSOSN (Código de Situação da Operação pelo Simples Nacional) mas, se você "travar" o sistema somente com essas situações tributárias e se um dia seu cliente sair ou for excluído do regime do Simples as NFC-e e quaisquer outros documentos gerados pelo sistema serão inidôneos.

Abraços.

Att,
Samuel Oliveira
Analista Fiscal

**Comment by robertorp** [comment]
Interessante, ouvi falar (talvez você saiba) que o novo simples nacional (supersimples) iria gerar speed fiscal, não me aprofundei para saber disso e dizer é verdade. hehe se você saber e poder informar seria de grande ajuda eheh

**Comment by orochasamuel** [comment]
@robertorp essa história é um pouco antiga mas ainda tem muita gente que tem dúvidas.

As pequenas empresas - na sua maioria enquadradas no Simples Nacional - não estão obrigadas devido a complexidade na preparação dessas informações, como é um regime diferenciado para recolhimento dos impostos é também um regime diferenciado na hora de informar para o governo.

Não acredito que isso vá acontecer tão cedo, o impacto seria grande e iria onerar muito a vida das empresas.

Mas estou procurando sempre me atualizar, qualquer novidade irei postar aqui.

Abraços.

Att,
Samuel Rocha
Analista Fiscal
