### ISSUE TITLE
Time Out?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#226]
Bom dia Galera.
Ao tentar enviar a NFe recebi o seguinte erro:
"The operation has time out"

**Comment by luiszimmermann** [comment]
Verifique o status do endereço do SEFAZ está online e se a sua máquina/servidor tem acesso livre para o endereço pela internet

**Comment by FabioHenriqueMF** [comment]
Desculpe minha ignorância, mas qual endereço do SEFAZ?

**Comment by luiszimmermann** [comment]
Isso depende do estado do emissor da NF-e e do tipo de operação. Dentro do Zeus em NFe.Servicos/Enderecador.cs você consegue ver todos os endereços por ele utilizados

**Comment by robertorp** [comment]
No componente tem a definição do TimeOut no projeto exemplo o padrão dele é 3000 que equivale a 3 segundos. (Ultima vez que vi o projeto exemplo era isso) 
Aumente o somente para tentar transmitir (aumente para 60000)

**Comment by FabioHenriqueMF** [comment]
Muito obrigado aumentei para 5 e deu.
