### ISSUE TITLE
Erro ao cancelar NFC-e

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#228]
Adenilton, bom dia,

Está dando o erro em anexo em um cliente que está tentando cancelar uma NFC-e. Alguma pista do que possa estar errado? Dlls estão atualizadas no referido cliente.

Obrigado,
Roberto.
![errocanc](https://cloud.githubusercontent.com/assets/11814082/19645311/d8562a84-99d2-11e6-8704-2be400093852.png)

**Comment by adeniltonbs** [comment]
Segundo o portal da NFe, http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#SVRS, a autorizadora SVRS, que a UF do RJ utiliza, não possui serviços com versão 2.0. Configure a versão do serviço VersaoRecepcaoEventoCceCancelamento para 1.0, conforme o link acima.
