### ISSUE TITLE
[DÚVIDA] NFeProc????

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#229]
Boa tarde pessoa.
Ainda estou estudando o projeto, que por sinal está muito bom, mas ainda não entendi qual a Função do NFeProc.
Outra dúvida é com relação aos processos de Transmissão e retorno, estou fazendo direito?(abaixo)

`// 1° Cria Instância do Serviço
                var servicoNFe = new ServicosNFe(SistemaConfigDAL.ConfigServ);
                //2° Envia NFe
                var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe> { _nfe }, true/_Envia a mensagem compactada para a SEFAZ_/);
                if(retornoEnvio.Retorno.infRec.nRec == null)
                {
                    return;
                }
                //3° Recebe o Retorno do Processamento da NFe
                var retornoAutorizacao = servicoNFe.NFeRetAutorizacao(retornoEnvio.Retorno.infRec.nRec);
                // 4° Pega  o 1° Número de Protocoloo
                var protNfeRetorno = retornoAutorizacao.Retorno.protNFe.FirstOrDefault();
                // 5° Se não existir tentar Retransmitir NFe
                if (protNfeRetorno == null)
                {
                    //tenta_retransmitir_a_nfe;
                    return;
                }
                // 6° Se Status do Retorno for 
                //100 = Autorizada ou 150 = Autorizado o uso da NF-e, autorização concedida fora de prazo
                //Cria NFeProc
                if (protNfeRetorno.infProt.cStat == 100 | protNfeRetorno.infProt.cStat == 150) //100 = Autorizada, 150 = Autorizado o uso da NF-e, autorização concedida fora de prazo
                {
                    objNFeDAL.AtualizaSituacaoNFe(_nfe.infNFe, "AUT", protNfeRetorno.infProt.nProt);

```
                var nfeproc = new nfeProc();
                nfeproc.NFe = _nfe;
                nfeproc.protNFe = protNfeRetorno;
                nfeproc.versao = retornoAutorizacao.Retorno.versao;
                nfeproc.SalvarArquivoXml(SistemaConfigDAL.ConfigServ.DiretorioSalvarXml + "\\teste");`
```

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Boa tarde. Desculpa a demora em responder-te. Se sua dúvida ainda persiste, você pode dar uma olhada no [manual de orientação do contribuinte, versão 6.0](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=), páginas 28-40, que descreve bem a mecânica dos serviços de envio/recepção da NFe.

> Ainda estou estudando o projeto, que por sinal está muito bom, mas ainda não entendi qual a Função do NFeProc.

O grupo nfeProc, conforme a página 181 do manual, contém um objeto NFe e um objeto protNfe (resultado do processamento da NFe pela SEFAZ). Então esse objeto é perfeito para serializar e armazenar o XML de NFe. Inclusive as SEFAZes distribuem o XML com esse objeto serializado.

> Outra dúvida é com relação aos processos de Transmissão e retorno, estou fazendo direito?(abaixo)

Está correto para transmissão assíncrona. Note que algumas SEFAZes permite que vc consuma o serviço NfeAutorizacao de forma síncrona. Nessa modalidade é dispensado o consumo do serviço NFeRetAutorizacao, uma vez que o próprio NfeAutorizacao já retorna o resultado do processamento.
Bom pelo que percebi, esse procedimento é apenas um rascunho certo? Falta alguns tratamentos como tratamento de erros, armazenar o recibo, o XML, etc.

**Comment by FabioHenriqueMF** [comment]
muito obrigado @adeniltonbs, sim é um rascunho que vou trabalhar em cima, mas muito obrigado
