### ISSUE TITLE
NFE sincrono

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#23]
Adenilton, 

cara para o envio sincrono é praticamente a mesma coisa do assincrono com uso da bilbioteca????

so modificar para o "IndicadorSincronizacao.Sincrono"?

**Comment by adeniltonbs** [comment]
celino, o envio síncrono ainda não foi implementado na biblioteca, conforme consta no TODO em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe. Não basta trocar a tag indSinc para IndicadorSincronizacao.Sincrono, pois o retorno do serviço será completamente diferente, e é necessário implementar o tratamento para este caso.

Note algumas diferenças do envio síncrono para o assíncrono descritas no manual, na descrição de uso da tag indSinc da classe enviNFe:

0=Não.
1=Empresa solicita processamento síncrono do
Lote de NF-e (sem a geração de Recibo para
consulta futura);
Nota: O processamento síncrono do Lote
corresponde a entrega da resposta do
processamento das NF-e do Lote, sem a geração
de um Recibo de Lote para consulta futura. A
resposta de forma síncrona pela SEFAZ
Autorizadora só ocorrerá se:
- a empresa solicitar e constar unicamente uma NFe no Lote;
- a SEFAZ Autorizadora implementar o
  processamento síncrono para a resposta do Lote de
  NF-e.

Então podemos notar as seguintes diferenças:
1 - O serviço não retorna o recibo;
2 - O serviço terá um retorno equivalente ao serviço retConsReciNFe;
3 - Não será possível enviar mais de uma NFe por lote;
4 - A sefaz autorizadora tem que disponibilizar essa modalidade de envio.

Para implementar o consumo do serviço síncrono tem que levar em conta essas coisas. Pretendo implementar em breve.

**Comment by kleberns** [comment]
Ola pessoal !

Eu vi que voces falam sobre NFe e no caso da NFCe:
1) tem o envio sincrono ? (Ou NFCe é só sincrono ?)

att.
Nogueira

**Comment by adeniltonbs** [comment]
Os serviços são os mesmos para NFe e para NFCe, mas cada SEFAZ pode escolher aceitar ou não o envio síncrono.

A diferença entre NFe e NFCe está em alguns itens do layoute, mas recomendo você dar uma lida no Manual de Orientação do Contribuinte - versão 6.00 - Minuta, que pode ser encontrado em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=.

Na página 29 desse manual descreve o consumo do serviço NfeAutorizacao em modo sincrono.
