### ISSUE TITLE
Projeto no nuget

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#230]
Bom dia,

```
   O projeto está sendo atualizado no nuget?
```

**Comment by adeniltonbs** [comment]
Bom dia
Está sim, note que a última atualização foi dia 07/10
http://www.nuget.org/packages/Zeus.Net.NFe.NFCe/

**Comment by robertorp** [comment]
As vezes aguardo uns dias para atualizar.
13:30 da tarde atualizo o mesmo. (hoje).

edit// Atualizado nuget com os commits mais atuais.
