### ISSUE TITLE
Carta de Correção - sequenciaEvento

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#232]
Boa tarde pessoal.
O que se refere a sequenciaEvento na carta de correção?

**Comment by robertorp** [comment]
Um exemplo seria você mandar varias cartas de correção no mesmo tempo (uma lista em uma unica request) 

sequenciaEvento 1 = Carta correção 1
sequenciaEvento 2 = Carta correção 2

obs: Não sei se é possível mandar mais de uma carta correção no mesmo tempo. Eu acho que é isso pelo que li no manual pode ser que entendi errado rsrs

**Comment by leandrossantos** [comment]
@FabioHenriqueMF  na verdade a sequenciaEvento serve para informar qual é o sequencial da carta que esta vinculando a chave de acesso informada, é aceito até 20 cartas de correção por chave, sendo que só tem validade a última enviada.

**Comment by FabioHenriqueMF** [comment]
Então não posso mandar por exemplo fixo "1"? Por que se mandar mais uma carta de correção "teoricamente" já existirá?

**Comment by leandrossantos** [comment]
@FabioHenriqueMF  o correto é você ter um controle dessa sequencia.

**Comment by FabioHenriqueMF** [comment]
Hum certo ok vlwsss
