### ISSUE TITLE
Dúvida na construção da <Signature> e <infNFeSupl>

### ISSUE THREAD

**Issue by jeisonmp** [ZeusAutomacao/DFe.NET#233]
Boa tarde!
Primeiramente gostaria de parabenizar pelo excelente trabalho de todos os participantes do projeto.

Gostaria de utilizar o sistema e consequentemente poder contribuir também.

Estou com uma dúvida na preparação das tags <infNFeSupl> e <Signature>. Como devo realizar o preenchimento destas informações no arquivo xml?

Muito obrigado!

**Comment by leandrossantos** [comment]
Boa tarde @jeisonmp , ao fazer a assinatura da NFe/NFCe o próprio componente já cira essas tags. No caso da <infNFeSupl> o componente verifica que se é NFCe então cria a tag.

Dê uma olhada/estudada na aplicação de exemplo que acompanha o componente que você vai ver certinho o funcionamento do componente.

**Comment by jeisonmp** [comment]
Olá Leandro, 

Muito obrigado pela informação!

Abraços!
