### ISSUE TITLE
Nota não existe no SEFAZ

### ISSUE THREAD

**Issue by jeisonmp** [ZeusAutomacao/DFe.NET#234]
Boa noite,

Está faltando algum detalhe para enviar as notas.

Segui todos os passos do método do App de teste, "Criar e enviar 3.0", estou criando apenas 1 nota no lote. Estou usando o método NFeAutorizacao, enviando no modo síncrono e no ambiente homologação. Eu recebo o retorno "Lote processado", mas a nota não é publicada no SEFAZ.
Eu ainda realizo a consulta usando o método "NFeConsultaProtocolo" e recebo o retorno "Rejeicao: NF-e nao consta na base de dados da SEFAZ". Também procuro a nota pelo ID direto no SEFAZ e a nota não existe, tanto em produção quanto em homologação.

O que estou fazendo errado?

Obrigado!

**Comment by marcosgerene** [comment]
Bom dia, o lote pode estar processado mas não necessariamente a nota ter sido aceita/transmitida, pode existir algum problema no preenchimento que passou pelos schemas.

Monitore a pasta que você selecionou para salvar os XMLs e veja qual o ultimo arquivo "-pro-rec.xml" salvo, lá terá o retorno real do que está acontecendo.

Sobre a forma de envio, se não me engano o envio sincrono ainda não foi implementado, se foi não sei como usa-lo, mas no envio assincrono para pegar o retorno real e ver o status do envio eu faço isso:

```

ZeusNFe.ZeusConfig.tpEmis = ZeusNFe.ZeusTipoEmissao(gnfe.FormaEmissao);
var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusNFe.ZeusConfig);
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });

if (!string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec))
{
    var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
    var prot = retornoAutorizacao.Retorno.protNFe.OrderByDescending(p => p.infProt.dhRecbto).FirstOrDefault();
    if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))
    {
        var _nfeproc = new NFe.Classes.nfeProc() { versao = _nfe.infNFe.versao, NFe = _nfe, protNFe = prot };
        _nfeproc.SalvarArquivoXml(GArquivos.CombinarDiretorio(ZeusNFe.ZeusConfig.DiretorioSalvarXml, _nfe.infNFe.Id + ".xml"));
        resposta = prot.infProt.xMotivo;
        if (!new NFeDAO().SaveXML(gnfe.ChaveAcesso, _nfeproc.ObterXmlString()))
            return false;
        return new NFeDAO().Transmitir(gnfe);
    }
    else
        resposta = prot.infProt.xMotivo;        
}
else
    resposta = retorno.RetornoStr;
```

Obs: Esta classe statica "ZeusNFe" é minha de configuração, ela não existe no componente, pode ignorar
Obs2: Essas classes DAO salvam coisas no banco basicamente, pode ignorar também.

**Comment by jeisonmp** [comment]
Funcionou!
Quando inseri o método de retorno da autorização, eu pude ver o que estava errado no meu documento.

Muito obrigado!

**Comment by adeniltonbs** [comment]
@marcosgerene Só pra conhecimento: o envio síncrono já está disponível da biblioteca. Há algumas diferenças em relação ao consumo de forma assíncrona: 
- No envio síncrono, um objeto protNFe (com o resultado do processamento do lote) é retornado pelo serviço NFeAutorizacao, e, neste caso, não é necessário consumir o serviço NFeRetAutorizacao.
- O recibo não é retornado nessa modalidade, já que não há necessidade de consumir o serviço NFeRetAutorizacao;

Há um exemplo de como consumir o serviço NFeAutorizacao de forma síncrona na aplicação de testes (NFe.AppTeste), classe MainWindow, método BtnCriareEnviar3_Click.

**Comment by marcosgerene** [comment]
@adeniltonbs ,

O envio sincrono funciona para qualquer UF?

**Comment by adeniltonbs** [comment]
@marcosgerene, pelo que consta na página 29 do manual de orientação do contribuinte, cada SEFAZ tem autonomia para decidir isso. Veja abaixo:

> Nota: O processamento síncrono do Lote
> corresponde a entrega da resposta do
> processamento das NF-e do Lote, sem a geração
> de um Recibo de Lote para consulta futura. A
> resposta de forma síncrona pela SEFAZ
> Autorizadora só ocorrerá se:
> - a empresa solicitar e constar unicamente uma NFe no Lote;
> - a SEFAZ Autorizadora implementar o
>   processamento síncrono para a resposta do Lote de
>   NF-e.
