### ISSUE TITLE
Envio Sincrono

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#235]
Boa noite @adeniltonbs,

Em outro post vc me disse sobre o envio sincrono, mas meu retorno no envio sincrono está sendo como lote processado, e eu teria que tratar como como o assincrono, se não o protnfe vem nulo,

![protnfe](https://cloud.githubusercontent.com/assets/15945003/19990605/1bf63914-a216-11e6-8f9c-efc743518a79.png)

![retorno](https://cloud.githubusercontent.com/assets/15945003/19990617/23b9c68e-a216-11e6-8236-5ffe592d66d7.png)

Att

**Comment by gubarusco** [comment]
Bom dia Marcos,

Eu tive esse problema em SP. Pelos meus testes e algumas pesquisas ele não
trabalha em modo síncrono. Mesmo que você mande nessa opção ele te devolve
em assíncrono, ou seja, vem o nro do recibo e o status de Lote Recebido,
sendo necessário uma nova consulta para pegar a situação do lote.

Abraços

Em 3 de novembro de 2016 22:37, Marcos Gerene notifications@github.com
escreveu:

**Comment by marcosgerene** [comment]
@gubarusco,

Bom dia, sou de SP mesmo, obrigado pela dica.

Abraços
