### ISSUE TITLE
Transmitir Assincrono - Referencia de objeto não definida

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#236]
#Bom dia,

Algumas vezes ao tentar transmitir recebo o erro de objeto nulo (Referencia de objeto não definida), mas nunca consigo reproduzir o erro, sempre que debugo passa, e o erro acontece de forma aleatória, não importa o cliente, produto, valor, nada...

Segue meu código aonde o erro acontece:

```
ZeusNFe.ZeusConfig.tpEmis = ZeusNFe.ZeusTipoEmissao(gnfe.FormaEmissao);
var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusNFe.ZeusConfig);
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });
if (!string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec))
{
    var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
    var prot = retornoAutorizacao.Retorno.protNFe.OrderByDescending(p => p.infProt.dhRecbto).FirstOrDefault();
    if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))
    {
        var _nfeproc = new NFe.Classes.nfeProc() { versao = _nfe.infNFe.versao, NFe = _nfe, protNFe = prot };
        _nfeproc.SalvarArquivoXml(GArquivos.CombinarDiretorio(ZeusNFe.ZeusConfig.DiretorioSalvarXml, $"{_nfe.infNFe.Id}.xml"));
        resposta = prot.infProt.xMotivo;
        if (!new NFeDAO().SaveXML(gnfe.ChaveAcesso, _nfeproc.ObterXmlString()))
            return false;
        return new NFeDAO().Transmitir(gnfe);
    }
    else
        resposta = prot.infProt.xMotivo;                 
}
else
    resposta = retorno.RetornoStr;
```

Alguém pode me dar uma dica, eu ate chutaria o tempo de resposta do servidor pois debugando teoricamente dou mais tempo para o retorno, mas não saberia como tratar isso.

______

Update 1: Uma nfe na mesma maquina, mesmo produto, mesmo cliente, no 3G deu o erro, no wifi foi, acredito que tenha algo a ver com a conexão com a internet, alguém sabe se preciso somente aumentar o timedout?

Obrigado, Marcos

**Comment by adeniltonbs** [comment]
@marcosgerene, seu objeto retorno.Retorno, retornoAutorizacao.Retorno e retornoAutorizacao.Retorno.protNFe podem vir nulos se houver problemas na comunicação. Em vez de aumentar o tempo, você poderia criar um mecanismo de retentar X vezes caso isso ocorra. Também seria interessante o usuário decidir isso, juntamente com o tempo de timeout.

**Comment by marcosgerene** [comment]
Bom dia @adeniltonbs 

Como eu poderia retentar sem reenviar a nfe? 

Todas as vezes a nota está transmitida, é só consultar, eu até pensei em implementar uma "auto-consulta" no caso de erro no retorno, mas em notas cujo o erro não são esse vai causar um consumo indevido...

Pode me dar um exemplo em código de como retentar?

Obrigado

**Comment by adeniltonbs** [comment]
Acredito que sejam bem poucos os casos onde esse objeto venha nulo. Certamente vai depender da estabilidade da internet. Então fazer uma consulta somente para esses casos não vai ser consumo indevido. Consumo indevido seria se para toda NFe que você tentasse emitir, consumisse o serviço de consulta.

Isto posto, a primeira coisa a fazer é colocar as chamadas aos serviços em try/except.
Depois disso, quando receber o retorno nulo para o serviço NFeAutorizacao, por exemplo, você pode fazer duas coisas:

**1 - Tentar enviar novamente. Neste caso, o resultado será o seguinte:** 
1.1 - Se a transmissão anterior foi bem sucedida, apenas houve falha na obtenção do retorno e a nova tentativa será rejeitada por duplicidade, mas sem diferença na chave de acesso. Você então pode fazer uma consulta para obter as informações da autorização (protNFe);
1.2 - Se a transmissão anterior NÃO foi bem sucedida, a nota será transmitida desta vez e basta obter o protNFe.
1.3 - Se não conseguir obter o retorno em 1.1 ou 1.2, tentar novamente o passo 1 até esgotar o número de tentativas.

**2 - Efetuar uma consulta. Neste caso o resultado será o seguinte:**
2.1 - Se a transmissão anterior foi bem sucedida, você obterá as informações da autorização (protNFe);
2.2 - Se a transmissão anterior NÃO foi bem sucedida, tentar o passo 1.

**Comment by marcosgerene** [comment]
Boa noite @adeniltonbs ,

Não entendi a 1.1, se eu tiver um erro de duplicidade terei o numero do recibo mesmo assim?

Sobre efetuar a consulta, me pareceu a solução mais lógica, meu bloco de transmissão já recebe o tratamento de um try catch, o meu medo é refazer a tentativa sempre, mesmo quando o erro não for ligado a falha no retorno em si, como eu poderia identificar que o erro foi justamente no retorno?

Sim, acontece somente em internet de pior qualidade, já averiguei isso. 

Todavia, eu tenho um sistema que consiste basicamente um emissor de NFe de baixissimo custo, voltado justamente para quem precisa substituir o emissor gratuito e isto faz com que o sistema rode justamente aonde a estrutura do cliente é de baixa qualidade...

Obrigado pela força, sou muito fã do seu projeto e pretendo usa-lo em larga escala...

**Comment by adeniltonbs** [comment]
> Não entendi a 1.1, se eu tiver um erro de duplicidade terei o numero do recibo mesmo assim?

Não terás o número do recibo, mas se receber o erro código 204, quer dizer que a NFe já está autorizada, vide página 130 do manual de orientação. Coloquei as duas opções pra vc decidir. Por exemplo, se na maioria dos casos que você recebe o objeto nulo a nfe não tiver sido autorizada, então a solução 1 será o menor caminho. Agora se na maioria dos casos a NFe já tiver sido autorizada, use a solução 2.

**Comment by marcosgerene** [comment]
> Não terás o número do recibo, mas se receber o erro código 204, quer dizer que a NFe já está autorizada, vide página 130 do manual de orientação. Coloquei as duas opções pra vc decidir. Por exemplo, se na maioria dos casos que você recebe o objeto nulo a nfe não tiver sido autorizada, então a solução 1 será o menor caminho. Agora se na maioria dos casos a NFe já tiver sido autorizada, use a solução 2.

Sim, na esmagadora maioria das vezes a solução é só consultar, estou pensando em verificar se objeto é nulo, neste caso o objeto nulo vai ser o retorno.Retorno? 

Segue como estou pensando em tratar, veja se está correto, por favor:

```
ZeusNFe.ZeusConfig.tpEmis = ZeusNFe.ZeusTipoEmissao(gnfe.FormaEmissao);
var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusNFe.ZeusConfig);
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });
if (retorno.Retorno == null)
{
    //Consultar a NFe pela Chave...
       return;
}

if (!string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec))
{
    var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
    var prot = retornoAutorizacao.Retorno.protNFe.OrderByDescending(p => p.infProt.dhRecbto).FirstOrDefault();
    if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))
    {
        var _nfeproc = new NFe.Classes.nfeProc() { versao = _nfe.infNFe.versao, NFe = _nfe, protNFe = prot };
            _nfeproc.SalvarArquivoXml(GArquivos.CombinarDiretorio(ZeusNFe.ZeusConfig.DiretorioSalvarXml, $"{_nfe.infNFe.Id}.xml"));
        resposta = prot.infProt.xMotivo;
        if (!new NFeDAO().SaveXML(gnfe.ChaveAcesso, _nfeproc.ObterXmlString()))
            return false;
        return new NFeDAO().Transmitir(gnfe);
    }
    else
        resposta = prot.infProt.xMotivo;
}
    else
        resposta = retorno.RetornoStr;
}
```

---

**Update 1**: Mudei o código para:

```
ZeusNFe.ZeusConfig.tpEmis = ZeusNFe.ZeusTipoEmissao(gnfe.FormaEmissao);
var servicoNfe = new NFe.Servicos.ServicosNFe(ZeusNFe.ZeusConfig);
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });
if (retorno.Retorno == null)
{
    NFeBO.Consultar(gnfe, ref resposta);
    return gnfe.Status == StatusNF.Transmitida;
}

if (!string.IsNullOrEmpty(retorno.Retorno.infRec?.nRec))
{
    var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
    if (retornoAutorizacao?.Retorno == null)
    {
        NFeBO.Consultar(gnfe, ref resposta);
        return gnfe.Status == StatusNF.Transmitida;
    }

    var prot = retornoAutorizacao.Retorno.protNFe.OrderByDescending(p => p.infProt.dhRecbto).FirstOrDefault();
    if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))
    {
        var _nfeproc = new NFe.Classes.nfeProc() { versao = _nfe.infNFe.versao, NFe = _nfe, protNFe = prot };
        _nfeproc.SalvarArquivoXml(GArquivos.CombinarDiretorio(ZeusNFe.ZeusConfig.DiretorioSalvarXml, $"{_nfe.infNFe.Id}.xml"));
        resposta = prot.infProt.xMotivo;
        if (!new NFeDAO().SaveXML(gnfe.ChaveAcesso, _nfeproc.ObterXmlString()))
            return false;
        return new NFeDAO().Transmitir(gnfe);
    }
    else
        resposta = prot.infProt.xMotivo;
}
else
    resposta = retorno.RetornoStr;
```

Consegui fazer o erro acontecer com o 3G com sinal ruim, porém não entrou em nenhum dos dois IFs... 

Logo em seguida emiti outra NFe identica e o erro não ocorreu... não consigo saber aonde devo tratar o problema

---

**Update 2**: Fiz um log e identifiquei a linha aonde acontece o erro:
`if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))`

---

**Update 3:** O `retornoAutorizacao.Retorno.protNFe` tem no count 0 protocolos, então o prot vem null.

![erro](https://cloud.githubusercontent.com/assets/15945003/20171142/7faa8dca-a716-11e6-8671-0c5e7e6ff208.png)

Resolvi da seguinte forma:

```
 var retornoAutorizacao = servicoNfe.NFeRetAutorizacao(retorno.Retorno.infRec.nRec);
if (retornoAutorizacao.Retorno.protNFe.Count == 0)
    return NFeBO.Consultar(gnfe, ref resposta) == StatusNF.Transmitida;

var prot = retornoAutorizacao.Retorno.protNFe.OrderByDescending(p => p.infProt.dhRecbto).FirstOrDefault();   
if (new List<int> { 100, 150 }.Contains(prot.infProt.cStat))
{
    var _nfeproc = new NFe.Classes.nfeProc() { versao = _nfe.infNFe.versao, NFe = _nfe, protNFe = prot };
    _nfeproc.SalvarArquivoXml(GArquivos.CombinarDiretorio(ZeusNFe.ZeusConfig.DiretorioSalvarXml, $"{_nfe.infNFe.Id}.xml"));
    resposta = prot.infProt.xMotivo;
    if (!new NFeDAO().SaveXML(gnfe.ChaveAcesso, _nfeproc.ObterXmlString()))
        return false;
    return new NFeDAO().Transmitir(gnfe);
}
else
    resposta = prot.infProt.xMotivo;

```
