### ISSUE TITLE
Dúvida sobre campos balsa e vagao na classe reboque

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#237]
Bom dia,

Está correto os campos balsa e vagao estarem dentro da classe reboque sendo que eles são filhos do grupo X01 e não do X22?.

Obrigado.

**Comment by adeniltonbs** [comment]
Obrigado por reportar.

**Comment by claytonduran** [comment]
Boa Tarde pessoal estou gerando XML com estes campos balsa e vagao dentro reboque sendo que eles são filhos do grupo X01 porem  ao gerar o assinado esse campos são retirados do XML, alguém já teve este erro?

Obrigado
