### ISSUE TITLE
Documentação 

### ISSUE THREAD

**Issue by wellyngtond2** [ZeusAutomacao/DFe.NET#24]
Olá por favor, não teria uma documentação funcional da parte de interface mesmo, dai eu implementaria no meu projeto. obrigado!

**Comment by adeniltonbs** [comment]
Bom dia wellyngton, a biblioteca não possui documentação no momento, mas se você der uma olhada, perceberás que todas as classes da biblioteca estão com suas propriedades/métodos comentadas no formato xml, gerando uma documentação do código. Também a existência de uma aplicação demonstrando o consumo de todos os recursos da biblioteca não seria o bastante para você conseguir implementar o uso da biblioteca na sua aplicação? Outra coisa, se você observar, o evento onclick de cada botão da aplicação de demonstração, verás que tem bem pouco código e há comentários onde achei necessário explicar melhor o uso. Recomendo que você tente implementar e poste aqui eventuais dúvidas. Note que o projeto ACBR também não possui documentação atualmente, apenas um aplicativo de demonstração como o desta biblioteca, no entanto é utilizado por milhares de desenvolvedores no nosso país. Por último, precisamos de colaboradores e sinta-se a vontade para contribuir com a documentação.

**Comment by wellyngtond2** [comment]
Bom dia,
Eu até executei a aplicação, porém não sei em qual ordem executar as mesmas ex:Criar NFE>Assinar>etc...qual seria a ordem dos processos?Outra dúvida, no caso da nfc-e no nome de quem eu irei emitir(cliente no caso) quais os dados obrigatórios do cliente.abraços!

Date: Mon, 20 Jul 2015 05:43:32 -0700

**Comment by adeniltonbs** [comment]
Em se tratando da NFe, a ordem é Assinar > validar > transmitir. Depois pode cancelar ou enviar uma carta de correção. 

Para emitir a NFe e a NFCe em testes, você precisa de um certificado digital.

Que dados são válidos para informar na NFe e na NFCe você encontra no manual da NFe que pode ser encontrado em: http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=

Use a versão 6.0 - minuta.

Leia o manual para os serviços que você deseja consumir. Depois que você conhecer as regras da NFe e o fluxo de operação descritos no manual, verás que a biblioteca reflete exatamente o que é descrito no manual.

**Comment by wellyngtond2** [comment]
Muito obrigado amigo,
você ja esta fazendo mais do que deve por me,obrigado mesmo!

Date: Mon, 20 Jul 2015 08:07:05 -0700
