### ISSUE TITLE
Impressão DANFE NFE

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#241]
Boa noite @adeniltonbs ,

Notei agora lendo o wiki do projeto na parte de implementações isto:

> Implementar impressão do DANFE de NFe (modelo 55) (implementado, falta testar somente);

Gostaria de saber como anda, e se pode liberar nem que seja um .zip da versão beta para que possamos testar, no meu caso só falta isso para acabar de vez a minha dependência do Lazarus...

Obrigado, abraço

**Comment by leandrossantos** [comment]
@marcosgerene boa noite, até onde eu sei a impressão já esta até implementada no componente, mais fiz uns testes aqui e o arquivo NFe.frx ainda precisa de alguns ajustes.

**Comment by marcosgerene** [comment]
Pode me mandar um exemplo do código para impressão? 

Uso o nuget e tenho a versão paga do Fast Reports

---

**Update 1**: Fiz vários ajustes, por favor testem com calma, os testes que fiz estavam ok...

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/243

**Comment by jeisonmp** [comment]
Olá, eu estou implementando uma versão melhorada do DANFe , se quiser posso disponibilizar.

**Comment by marcosgerene** [comment]
@jeisonmp

Fiz um pull request com ajustes para funcionar a versão atual, exatamente o que está melhorando?

**Comment by marcosgerene** [comment]
Corrigi o que estava bugando e fiz pequenas melhorias no que já existia, mandei um pull request (https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/243) e adicionei algumas coisas como a tag "NFe Cancelada" que não existia, passou nos meus testes aqui, vou por em produção para poder remover o Lazarus de vez do meu projeto

**Comment by adeniltonbs** [comment]
@marcosgerene Opa, vou aceitar seu pull request. Obrigado pela contribuição.

**Comment by leandrossantos** [comment]
@marcosgerene  e @adeniltonbs  uma sugestão para a questão da impressão da DANFe de NFe, acredito que o nome do arquivo deva ser alterado para NFeRetrato.frx pois futuramente pode surgir a necessidade de criar a DANFe no formato paisagem, eu mesmo tenho clientes que usam nesse formato que nesse caso estou usando o unidanfe para esses clientes pela falta do relatório na minha aplicação.

Bem é essa minha sugestão!

**Comment by adeniltonbs** [comment]
@leandrossantos Boa sugestão Leandro.
