### ISSUE TITLE
Implementar MDFe na biblioteca

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#244]
Sendo feito por @robertorp

**Comment by leandrossantos** [comment]
@adeniltonbs  opa que notícia boa

**Comment by robertorp** [comment]
Concluído
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/248

**Comment by leandrossantos** [comment]
@robertorp valeu colega. agora é só aguardar o @adeniltonbs conferir e dar um merge para que todos possamos testar também.

**Comment by marcosgerene** [comment]
@adeniltonbs e @robertorp ,

Está em produção aqui comigo já, acredito que a insue pode ser fechada, o que vem agora são ajustes.

Abraços
