### ISSUE TITLE
Implementar recursos básicos do CTe

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#245]
A ser feito por @robertorp

**Comment by leandrossantos** [comment]
@adeniltonbs  opa que noticia boa. Se precisar das classes de montagem do XML e as classes de WS acredito que já estou com praticamente todas prontas. Qualquer coisa me chama no skype que envio elas.

**Comment by adeniltonbs** [comment]
Opa blz. Vou ver com o @robertorp como está a implementação dele, qualquer coisa te aviso.

**Comment by marcosgerene** [comment]
O @rftd ja esta com o CTE ja avançado, pelo que eu to vendo muita gente está fazendo separado...  seria interessante unir esforços...

https://github.com/ACBrNet/ACBr.Net.CTe

**Comment by leandrossantos** [comment]
@marcosgerene eu baixei o projeto do @rftd mais achei ele um pouco complicado de entender. As classes de montagem do XML eu já conclui praticamente todas elas, as classes de comunicação com WS também estão todas prontas, segui o mesmo conceito que o @adeniltonbs  fez na Zeus até a parte estrutural está bem parecida então estou achando bem mais organizada e estruturada.

**Comment by marcosgerene** [comment]
@leandrossantos, entendi, não tiro sua razão, só acho que daqui alguns dias teremos dois projetos prontos e a comunidade dividida em dois, serão dois projetos para manter (corrigir bugs, implementar melhorias...), dois projetos precisando da impressão (que sempre fica para trás)....

Não é uma crítica, infelizmente ainda me falta conhecimento (e tempo pois conhecimento se adquire com dedicação) para ajudar firmemente qualquer um dos dois, hoje só posso dar pitaco e sugerir pequenos ajutes como o ultimo pull request que fiz aqui ou os que fiz no AcbrSat...

Na minha opinião se você tem as classes quase prontas e a comunicação pronta e o @rftd está construindo as classes de comunicação, se um dos dois partisse para o outro projeto ajudar na impressão, ou a concluir o que está em andamento teriamos um projeto mais forte, este é o conceito de comunidade, são várias pessoas juntas, foi isso que fez o ACBr ser o que é no mundo do ObjectPascal (Delphi/Lazarus).

Vale lembrar que eu "entrei" no mundo do C#.Net faz menos de um ano, nesse tempo eu passei de "vou ter que usar o Lazarus para documentos fiscais" para projetos excelentes como o ACBrSat e o ZeusNFe...

Por favor, espero que nenhum dos dois me entendam mal, eu sou MUITO fã do trabalho do @adeniltonbs (NFe) e do @rftd (Sat), são projetos grandes que eles fizeram e entregaram "de mão beijada" para a comunidade, espero em breve ter a mesma capacidade para tal...


Abraço

**Comment by marcosgerene** [comment]
Boa tarde galera, a quantas anda essa implementação?

**Comment by robertorp** [comment]
Boa tarde, assim fiquei no aguardo de uma pessoa que tinha me dito que estava fazendo já.
Como a pessoa não manifestou mais, e agora teve procura, vou estar implementado a partir de amanhã 10/01/2017 , todos dias na parte da noite vou mexer um pouco. 
Vai ser assim, vou criar um branch com base no master, fazer um pull request e vou atualizando o pull request com o passar do tempo.

**Comment by robertorp** [comment]
https://github.com/robertorp/Zeus.Net.NFe.NFCe/tree/zeus-ct-e

Vou refatorar ele, mas.. se estiver esperando algo pra próxima semana acho que não sai, acho que vai aí nada nada duas semanas para deixar ele redondo. E lembrando, recursos básicos somente, o xml provavelmente não vai estar completão mas vai emitir para simples nacional. (O mesmo esta em produção no sistema aqui)

**Comment by marcosgerene** [comment]
@robertorp ,

Na verdade ja implementei em Lazarus, não tenho pressa alguma, só perguntei porque estava parado e se tivesse como ter em C# nativo eu não teria mais nada em Lazarus.

Entretanto, no meu caso não daria, tenho clientes que são lucro presumido, farei como no MDFe, assim que você soltar a base eu faço alguns ajustes e proponho algumas mudanças

Abraços

**Comment by robertorp** [comment]
já peguei alguns feedback de pessoas que já utilizam o CT-e e esta tudo OK.
