### ISSUE TITLE
Refatorar solução para comportar as demais soluções fiscais eletrônicas (Ct-e, MDF-e e NFS-e)

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#247]

**Comment by leandrossantos** [comment]
@adeniltonbs desse jeito pode renomear o projeto para **Zeus.Net.DFe** rsrs

**Comment by robertorp** [comment]
Inicio - https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/332  

Estou querendo fazer da seguinte maneira, irei passar tudo aos poucos, quero desenvolver o CT-e já em cima da unificação

- primeiro dei inicio nas classes de assinatura. FEITO.

- segundo depois desse pull se aceito, vou unificar a assinatura (é o mesmo código da nf-e para mdf-e é ct-e) / Trabalhar nisso hoje FEITO
- terceiro CertificadoDigital (essa vai dar um pouco de trabalho por causa das ultimas mudanças nela, tem que pensar uma maneira para unificar) https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/347 FEITO
- quarto FuncoesXML https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/357 FEITO

Se tiver mais alguma que da para unificar e só ir adicionando aqui
