### ISSUE TITLE
[Impressão] Acessador do objeto

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#249]
Bom dia,

Estou tentando a uma hora resolver um problema com a impressão mas não estou tendo sucesso, esbarro nesse erro e não sei como resolver...

![cst](https://cloud.githubusercontent.com/assets/15945003/20343708/9cd4e2aa-abd6-11e6-9fc8-e399d31a8cb5.png)

O XML ainda não está transmitido, então fiz a seguinte alteração no DEMO:

```
var arquivoXml = Funcoes.BuscarArquivoXml();
if (string.IsNullOrEmpty(arquivoXml))
    return;
nfeProc proc = null;
try
{
    proc = new nfeProc().CarregarDeArquivoXml(arquivoXml);
}
catch
{
    proc = new nfeProc() { NFe = new Classes.NFe().CarregarDeArquivoXml(arquivoXml) };
}


if (proc.NFe.infNFe.ide.mod != ModeloDocumento.NFe)
    throw new Exception("O XML informado não é um NFe!");

#endregion

#region Abre a visualização do relatório para impressão
var danfe = new DanfeFrNfe(proc, new ConfiguracaoDanfeNfe(_configuracoes.ConfiguracaoDanfeNfce.Logomarca, false, false));
danfe.Visualizar();
//danfe.Imprimir();
//danfe.ExibirDesign();
//danfe.ExportarPdf(@"d:\teste.pdf");

#endregion
```

Estava funcionando a impressão normalmente até que testei com CSTs diferentes e notei algo... Quando uso CSTs do mesmo grupo (ex: 40 e 41) funciona normalmente, mas CSTs de grupos diferentes o primeiro grupo apresenta o erro acima.

--------------------

Exemplo 1: (NFe com 3 produtos do grupo 00)
CST
000
400
000

Exemplo 2: (NFe com 2 produtos do grupo 00 e um produto 20)
CST
erro
erro
020

Exemplo 3: (Intercalado 2 grupos-> 00,20,00 ):
CST
000
erro
000

Exemplo 3: (Intercalado 2 grupos-> 00,20,00,20 ):
erro
020
erro
020

------------------

**Conclusão:** Só está convertendo corretamente o grupo do icms do ultimo item e infelizmente não sei como corrigir...

PS: O mesmo ocorre com CSON (Simples Nacional)

**Comment by adeniltonbs** [comment]
Poderia encaminhar o xml?

**Comment by marcosgerene** [comment]
Claro... pode ser via e-mail?

**Comment by marcosgerene** [comment]
[xmls.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/594506/xmls.zip)

**Comment by adeniltonbs** [comment]
Correção enviada.

**Comment by marcosgerene** [comment]
Boa @adeniltonbs , pode liberar no nuget?
