### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Eloisio** [ZeusAutomacao/DFe.NET#25]
Amigos , To achando muito legal o codigo mas para meu primeiro teste tudo dá timeout e não comunica com cefaz
pode me ajudar?

**Comment by adeniltonbs** [comment]
Qual o serviço que vc tentou usar e de qual SEFAZ?
Você verificou se a SEFAZ está com o serviço disponível em http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx?versao=0.00&tipoConteudo=Skeuqr8PQBY=?

**Comment by Eloisio** [comment]
Cara eu pisei na bola , mas está funcionando agora vou adaptar no meu app
valeu

**Comment by adeniltonbs** [comment]
Blz, qualquer dúvida abra um novo issue.
