### ISSUE TITLE
[DÚVIDA] Contingência NFe

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#250]
Por favor alguém poderia de maneira ampla me orientar com respeito a contingência da NFe?
Já li no manual a existem 4 tipos:
FS - Contingência com uso do Formulário de Segurança;
FS-DA - Contingência com uso do Formulário de Segurança para impressão de Documento Auxiliar do Documento Fiscal eletrônico;
SCAN – Sistema de Contingência do Ambiente Nacional ;
DPEC – Declaração Prévia de Emissão em Contingência ;
Não sei ao certo qual deles usar.
A minha empresa Imprime as NFe em contingencia em papel Timbrado.
Alguém poderia me orientar?

**Comment by leandrossantos** [comment]
@FabioHenriqueMF a contigencia do papel timbrado que você esta dizendo é a FS-DA lembrando que tem que imprimir 2 vias, 1 para o emitente e outra para o destinatário.

**Comment by FabioHenriqueMF** [comment]
Opa muito obrigado @leandrossantos.
A impressão neste papel não esta implementada no projeto não né?

**Comment by FabioHenriqueMF** [comment]
Desculpa @leandrossantos, não é papel timbrado, é papel moeda. Continua sendo FS-DA?

**Comment by leandrossantos** [comment]
@FabioHenriqueMF isso mesmo, FS-DA é no formulário em papel moeda.

**Comment by FabioHenriqueMF** [comment]
Mais uma dúvida @leandrossantos.
Estou lendo o manual e pelo que entendi se for usar a FS-DA vou imprimir a DANFE normalmente só que no meu papel moeda. Sem alterações?

**Comment by leandrossantos** [comment]
Quando é contingencia FS-DA precisa tem a chave de acesso adicional veja no manual páginas 158 e 159 o tópico **7.9.2 Emissão da NF-e em Contingência com Impressão do DANFE em Formulário de Segurança**

**Comment by FabioHenriqueMF** [comment]
Ok muito obrigado pela paciência @leandrossantos.

**Comment by FabioHenriqueMF** [comment]
Desculpe abrir novamente este issue mas tenho mais uma dúvida @leandrossantos.
No caso  de contingencia, eu devo gerar uma nova chave de acesso para a nota quando for transmiti-la?
Por que a chave é composta de vários itens, um deles e o tipo de emissão, e se tratando de contingencia, eu devo mudar o tipo de emissão para 5, no meu caso FS-DA.
Agora estou na dúvida.

**Comment by leandrossantos** [comment]
@FabioHenriqueMF a contigencia FS-DA funciona assim, você gera o XML e assina ele informando que esta usando a contigencia FS-DA, a partir do XML assinado você gera a DANFe para impressão no formulario de segurança em papel moeda, lembrando que tem que ser 2 vias, 1 para o Remetente e outra para o Destinatário. Quando a internet voltar por exemplo, basta mudar o componente para o tipo de emissão Normal e pegar o XML assinado e enviar ele.
