### ISSUE TITLE
IndicadorIss - ISSQN

### ISSUE THREAD

**Issue by drromanzini** [ZeusAutomacao/DFe.NET#251]
Bom dia @adeniltonbs ,
Primeiramente já peço desculpas por estar reabrindo uma Issues que já existia.
Contudo estou com o projeto atualizado (via NuGet Packages)  e a rejeição do esquema do atributo IndicadorIss em NFe.Classes.Informacoes.Detalhe.Tributacao.Municipal.ISSQN ainda não está gerando como indISS.
Também reparei que os impostos de PIS e COFINS estão gerando antes do imposto de ISSQN no XML o que ocorre também falha no schema.

Desde já agradeço muita a sua atenção e a sua contribuição a comunidade.
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/132

**Comment by robertorp** [comment]
Realmente existe correção para isso? Digo irei atualizar o nuget, mas a issue 132 é de maio, então eu acho que a reais possibilidades de não ter essa correção ainda. Boma não ser que esteja nos últimos commits. 
Obs: a versão dele e equivalente a quantidade de commits v1.0.1.229 em outras palavras o nuget ate o momento está no 229 commit.

edit: nuget atualizado.

**Comment by drromanzini** [comment]
Boa tarde @robertorp 
Acabei de atualizar o nuget para a versão 1.0.1.241, contudo o problema persiste.
Existe alguma outra forma de modificar o arquivo do xml antes de assinar/validar/enviar o mesmo?
Agradeço a sua atenção.
Obrigado.

**Comment by drromanzini** [comment]
Boa tarde!
Acabei arrumando manualmente nos fontes, compilando as dll's e removendo o projeto a través do Nuget.

Ajustei os fontes:

**NFe.Classes - Informacoes - Detalhe - Tributacao - Municipal - ISSQN.cs**
De:
public IndicadorISS IndicadorISS { get; set; }
Para:
public IndicadorISS indISS { get; set; }

**NFe.Classes - Informacoes - Detalhe - Tributacao - impostos.cs**
Apenas coloquei a propriedade ISSQN logo após da vTotTrib:
public class imposto
    {
        private decimal? _vTotTrib;
        public decimal? vTotTrib
        {
            get { return _vTotTrib.Arredondar(2); }
            set { _vTotTrib = value.Arredondar(2); }
        }
        public ISSQN ISSQN { get; set; }
......

**Comment by robertorp** [comment]
Poderia fazer um pull com as modificações?

**Comment by drromanzini** [comment]
Posso sim. Mas desculpe a ignorância, como eu faço para fazer o pull?

**Comment by robertorp** [comment]
http://www.raphaelfabeni.com.br/atualizando-seu-fork/

Logo depois que executar os passos deste tutorial, é so fazer um git push origin seubranch (por padrão é master) 

Ai depois é so abrir um pull request no repositório.

Tente seguir esse tutorial
