### ISSUE TITLE
[DÚVIDA] - Validação NF-e

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#253]
Boa tarde.
Desculpe a ignorância, mas a validação do projeto ZEUS não tem nada haver com a Validação da NF-e antes de ser assinada pelo Emissor da SEFAZ?

**Comment by marcosgerene** [comment]
Boa tarde,

A validação é feita em cima dos schemas da NFe, o projeto nada mais faz do que submeter o xml gerado para validação.

Qual exatamente é sua dificuldade? O que não está validando?

**Comment by robertorp** [comment]
Bom mesmo era se desse conta de implementar o máximo possível de validações locais.
Digo bom para NFC-e Offline.

Att,
Roberto Alves
http://sistemafusion.com.br/

**Comment by marcosgerene** [comment]
@fabiohenriquemf, a ideia do @robertorp é interessante, mas... 

As validações que o componente fizer "por conta própria" podem afetar casos específicos, e gerar problemas fiscais, e validar coisas como se o cnpj é válido, ou se o valor dos itens batem com o da nota, na minha visão é algo que o sistema tem que fazer, baseado nas regras de. negócio do mesmo. 

Nesse caso tenha uma camada no seu próprio sistema, tipo NFeBO para fazer alguns cálculos automáticos e as validações que achar necessário, é mais seguro do que implementar algo assim em um componente, o componente funciona exatamente como deveria, preeche ele, gera o xml sem qualquer alteração do foi preenchido. 

espero ter ajudado, abraço

**Comment by adeniltonbs** [comment]
@robertorp Note que antes de emitir uma NFCe offline, vc deve assinar o xml é submete-lo a validação contra os schemas.

**Comment by robertorp** [comment]
Sim, no meu caso uso a validação de regras do acbr monitor, foi somente uma sugestão.

**Comment by adeniltonbs** [comment]
Vou colocar como sugestão, no backlog. O detalhe é que as validações precisariam ser revisadas a cada alteração/laçamento de nota técnica. Atualmente acompanho alterações na estrutura do projeto, e não nas regras de validação.
