### ISSUE TITLE
Impressão danfe nfc-e 

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#256]
foi testar uma impressão (aqui na empresa atualmente usamos o ACBR para impressões) 
e queria passar o nfc-e para a impressão do danfe zeus
mas oque acontece quando imprimo um danfe nfc-e com o componente de impressão do zeus

ele me imprimiu faltando os ultimos 3 dígitos do cnpj do emitente
é somente 8 dígitos da chave , oque poderia ser isso?

Impressora usada, Daruma DR 800

Xml usado anexado

**Comment by leandrossantos** [comment]
@robertorp você instalou as fontes que estão indo junto com o componente, pode ser isso.

**Comment by robertorp** [comment]
@leandrossantos era isso mesmo , hehe obrigado!
Você pode me informar se tem alguma maneira de instalar as fontes via command line?

edit: achei já a solução http://stackoverflow.com/questions/17566943/install-a-font-with-several-styles-in-inno-setup

obrigado pela atenção.
