### ISSUE TITLE
XML com retorno

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#26]
Adenilton, boa tarde, tudo bem?

Tem como eu de alguma forma capturar um XML completo incluindo o protNFE, como abaixo?

Obrigado,
Roberto.

<?xml version="1.0" encoding="UTF-8"?><nfeProc versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="3.10" Id="NFe43150703900932000189650010000000371000000373"><ide><cUF>43</cUF><cNF>00000037</cNF><natOp>VENDA</natOp><indPag>0</indPag><mod>65</mod><serie>1</serie><nNF>37</nNF><dhEmi>2015-07-21T17:36:32-03:00</dhEmi><tpNF>1</tpNF><idDest>1</idDest><cMunFG>4310207</cMunFG><tpImp>4</tpImp><tpEmis>1</tpEmis><cDV>3</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>ACBrNFe2</verProc></ide><emit><CNPJ>03900932000189</CNPJ><xNome>IOLANDA DE OLIVEIRA PASTORELLO</xNome><xFant>IJUIPAR</xFant><enderEmit><xLgr>AV CORONEL DICO</xLgr><nro>1347</nro><xBairro>CENTRO</xBairro><cMun>4310207</cMun><xMun>IJUI</xMun><UF>RS</UF><CEP>98700000</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>05533326524</fone></enderEmit><IE>0650116780</IE><CRT>1</CRT></emit><det nItem="1"><prod><cProd>1</cProd><cEAN/><xProd>Diversos</xProd><NCM>39269090</NCM><CFOP>5101</CFOP><uCom>UN</uCom><qCom>1.0000</qCom><vUnCom>1.0000000000</vUnCom><vProd>1.00</vProd><cEANTrib/><uTrib>UN</uTrib><qTrib>1.0000</qTrib><vUnTrib>1.0000000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMSSN500><orig>0</orig><CSOSN>500</CSOSN></ICMSSN500></ICMS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>1.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>1.00</vNF></ICMSTot></total><transp><modFrete>9</modFrete></transp><pag><tPag>01</tPag><vPag>1.00</vPag></pag></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe43150703900932000189650010000000371000000373"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>zhLujeAkQ0FO36Oz6gqTxgzCRyg=</DigestValue></Reference></SignedInfo><SignatureValue>mCFFIesTZJGRuddumIL2+0rQv/PKK5awbwOfa9HXQFn64G+MUcfq1AMHO6THBG5x0y7ifTN7j3HMj7o0sfu0J4dNeVqdOs8Qa2ZMy9c3cj8bNL1mpb76yk+NUweI/rQFeOGxSol9ge2BSvLZh59ep/s4kqTAkF2Vm5ZXVja4AzIZUZbBVrJvrL4/TdauW0fQg6RnD1xfZCjjuEUAe4WBUrV3vAP1t1w87BW/MeisjYiVxx6sRJh+oDRDy8z77MntUMsjlAKvrHB+Opmg4mdDnAabjMgpx4WTsCAiw2cep7LXHgaKgeQO5LH2QSJJNFv7YLAIx8mr/qQwoB/4HP+zvg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH9TCCBd2gAwIBAgIIUaBSvp8/O2kwDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEXMBUGA1UEAxMOQUMgU0FGRVdFQiBSRkIwHhcNMTUwNzA2MTExOTAzWhcNMTgwNzA2MTExOTAzWjCB3TELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxCzAJBgNVBAgTAlJTMQ0wCwYDVQQHEwRJSlVJMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEogQTMxEjAQBgNVBAsTCUFSIEZVVFVSQTE5MDcGA1UEAxMwSU9MQU5EQSBERSBPTElWRUlSQSBQQVNUT1JFTExPIE1FOjAzOTAwOTMyMDAwMTg5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzA+7EXJEoJPbzdnTTPZ7oir+CfuCWsTxxFH3dAaNnJU5VRQ7df/cgsqeLsThpdgHHJ4PzZ8EvOCorZ38NEvgQn+osB/0jKJ1Rchb/DoCjfRLijJFSzN1OLGfQFP/r0+4tLE7GiCEkoYP5tVhAqsfGoJKKRZx17ty++YeVP65iWwlQb1NoTjk7bpjExPrbV+rxo5PDTgz3DsFjC1vs70eeGhyIwtFuqYg+9iKipbGmPP4WaOz+f/c/IjFt7N+80nd/MT+y+Yr/y/y8fYQJj6BwtYaTq8uqixwXWvmyyGZJSht7rlrkQLgHwB1zX/bjkn9aKqQM/iag6trB3/dCWZmaQIDAQABo4IDIDCCAxwwHwYDVR0jBBgwFoAU30VPT8fh3DjMSgwg5/jpWa0fXmEwDgYDVR0PAQH/BAQDAgXgMGkGA1UdIARiMGAwXgYGYEwBAgMwMFQwUgYIKwYBBQUHAgEWRmh0dHA6Ly9yZXBvc2l0b3Jpby5hY3NhZmV3ZWIuY29tLmJyL2FjLXNhZmV3ZWJyZmIvZHBjLWFjc2FmZXdlYnJmYi5wZGYwgf8GA1UdHwSB9zCB9DBPoE2gS4ZJaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9sY3ItYWMtc2FmZXdlYnJmYnYyLmNybDBQoE6gTIZKaHR0cDovL3JlcG9zaXRvcmlvMi5hY3NhZmV3ZWIuY29tLmJyL2FjLXNhZmV3ZWJyZmIvbGNyLWFjLXNhZmV3ZWJyZmJ2Mi5jcmwwT6BNoEuGSWh0dHA6Ly9hY3JlcG9zaXRvcmlvLmljcGJyYXNpbC5nb3YuYnIvbGNyL1NBRkVXRUIvbGNyLWFjLXNhZmV3ZWJyZmJ2Mi5jcmwwgYsGCCsGAQUFBwEBBH8wfTBRBggrBgEFBQcwAoZFaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9hYy1zYWZld2VicmZidjIucDdiMCgGCCsGAQUFBzABhhxodHRwOi8vb2NzcC5hY3NhZmV3ZWIuY29tLmJyMIHDBgNVHREEgbswgbiBGElPTEFOREFCT0hOQFRFUlJBLkNPTS5CUqApBgVgTAEDAqAgEx5JT0xBTkRBIERFIE9MSVZFSVJBIFBBU1RPUkVMTE+gGQYFYEwBAwOgEBMOMDM5MDA5MzIwMDAxODmgPQYFYEwBAwSgNBMyMDQwMzE5Njc0NzE3NzE2MDAwMDAwMDAwMDAwMDAwMDAwMDAxMDQ5MDA1NTcxU1NQUlOgFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA8y5YAXl3YkRWL/qA3NdkA9JLTNPXTAemtIvq866Wy8sqLB95x5l9S31c+g1ebd4VbQRSmWjeFUyYbx/QkX0GRfOL3erTxO/BDQSofjAiFOfVOPSfKGs+VfiwKC+SQW7GfkISv80CWCk3bcYIIBZo4cSU9y8dlg5qjQYN8oJRU+i2t9I0L89CRVJyLZKWhjEizfjfoS/WOVljXIpYSviiJbvEmgck2L+sA188+uq4fanFlZ5wbAzQJQ/uCnZBikq0G4Ef65MBF71k8Lq0Vrrg9DF+bIc6PAgdgNtZiFZfBoQBX4GgfcqbgHjBTxueQH2t++bAMuj+dSE7G8qO7Q8dZb6WZwtiSpLKciiy1gqnlPtLky3gwanLVQ0xEGHiYdT5PNu4ssj/EgQGI6+UGLsgXZVGAKmLdRe+MnDJEokkOIwlVZQHUmIRAuU5TAuTcNlBLg4ie2YxXPhfN/bQlAQIoZDXNnMcyedBe6T+TYvS1T0DXxEP6qYHTQige9F9BnV4IArhiMK0YjHzYYRFgYZw7J0qLrY30ZBbwPd1a61QS1/jzsgNxWny1zZCYsOOxqzD8M2qEfCGTEQCkRV53SlmTDbZEQp1MzfM6PB6XF1FiD4Fe3BjzmY3Ug/lnVwBbpYVUKBvqlfo/VQC3bPVFtOSpiAGMz0F13sOx27XJif2iew==</X509Certificate></X509Data></KeyInfo></Signature></NFe><protNFe versao="3.10"><infProt><tpAmb>1</tpAmb><verAplic>RS201411131054</verAplic><chNFe>43150703900932000189650010000000371000000373</chNFe><dhRecbto>2015-07-21T17:36:33-03:00</dhRecbto><nProt>143150049381614</nProt><digVal>zhLujeAkQ0FO36Oz6gqTxgzCRyg=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso da NF-e</xMotivo></infProt></protNFe></nfeProc>

**Comment by robertocvsiqueira** [comment]
Melhor explicando, capturar o XML após o envio e autorização do mesmo.

**Comment by robertocvsiqueira** [comment]
O método "BtnAdicionaNFeProc" serve para NFC-e também? Acho que me atenderia.

**Comment by robertocvsiqueira** [comment]
Acho que consegui. Quando terminar o teste te retorno.

**Comment by adeniltonbs** [comment]
Desculpa a demora, sim, o método "BtnAdicionaNFeProc" serve para NFC-e também. Bata usá-lo para adicionar o nfeproc ao xml que vc acabou de autorizar, para armazenar o xml completo com o nfeproc.

Se você olhar no manual verás que há pouca diferença entre NFe e NFCe e que ambos compartilham a mesma estrutura de xml, exceto por algumas tags que são exclusivas para NFe ou para a NFCe.

**Comment by willianas1** [comment]
Estava com essa mesma duvida. :)

Mais uma vez parabéns Adenilton, trabalho excepcional.
