### ISSUE TITLE
[DÚVIDA] Importação do TXT NF-e Pipes?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#262]
Bom dia Pessoal.
Li diversas vezes o manual de **[Emissor_NF-e]_Manual_de_layout_TXT-NF-e_v3.10.1**, mas o mesmo não é muito claro com relação aos pipes de campos finais não obrigatórios no arquivo TXT.
Gostaria de saber se devo informar todos os Pipes( "|" ) no arquivo TXT da NF-e, mesmo o campo sendo opcional ou não. Ex:
Tenho o grupo B (Ident. NF-e) no arquivo.
B|cUF|cNF|natOp|indPag|mod|serie|nNF|dhEmi| ... |xJust|
O campos xJust é opcional, então poderei inibir o pipe do mesmo?
Ou devo colocar o Pipe mas vazio?
B|SP|123|5401|1|1|0|123|2016-11-25| ... ||
B|SP|123|5401|1|1|0|123|2016-11-25| 
Se é que vocês me entendem...

**Comment by guidi** [comment]
@FabioHenriqueMF você deve informar todas as posições, nos campos que não existe informação você informa o pipe vazio.

**Comment by FabioHenriqueMF** [comment]
Fiz um teste no emissor da SEFAZ e nao informei os pipes Finais de um grupo. Ex o I e ele aceitou

**Comment by guidi** [comment]
Show, não sabia que funcionava sem também, aqui coloco todos os pipes.
