### ISSUE TITLE
[DÚVIDA] DANFE A4 NF-e - Soluções?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#264]
Bom dia pessoal alguém recomendaria o ReportViewer para desenvolver a DANDE Da NF-e?
Ou teria outra maneira mais prática para tal?
Tenho uma base da dados, imprimo a partir dela ou do XML?
Se alguém souber de soluções openSource em C# dá um toque.

**Comment by francofs** [comment]
Fabio,

Já tenho isso pronto no meu projeto. Tá nativo .Net, mas tô sem tempo de
portar pro projeto Zeus.

De qualquer maneira, você precisa usar o XML para fazer a impressão por
diversos fatores.

2016-11-29 9:40 GMT-02:00 FabioHenriqueMF <notifications@github.com>:

**Comment by FabioHenriqueMF** [comment]
francofs Quanto a imprimir por meio do XML não terá problema visto que salvo os XML autorizados na base.
Essa solução sua, você vai disponibilizar?

**Comment by francofs** [comment]
Vou sim Fabio, assim que arrumar um tempinho.

2016-11-29 9:49 GMT-02:00 FabioHenriqueMF <notifications@github.com>:

**Comment by FabioHenriqueMF** [comment]
Voce usa o ReportViewer?

**Comment by francofs** [comment]
Não, uso nenhum componente. A impressão é feita através de um objeto que
fica em System.Drawing.Printing.PrintDocument.

Para visualização eu uso o System.Windows.Forms.PrintPreviewControl, que é
um componente de visualização que consome o PrintDocument para visualizar a
impressão no WindowsForms.

Para outras plataformas o mesmo algoritmo de impressão pode ser usado para
fazer o output em outros formatos, como Imagem, PDF, etc, nenhum componente
específico de visualização é necessário. Caso esteja fazendo em Web
recomendo integrar com algum outro componente que seja mais aderentes ao
padrões de desenvolvimento Web.

**Comment by FabioHenriqueMF** [comment]
Não,estou fazendo para desktop mesmo. Se voce, permitir claro, disponibilizar a solução para impressão da DANFE a partir do XML para adapta-la ficaria muito grato.

**Comment by francofs** [comment]
Posso diponibilizar sim, vou tentar fazer isso hoje.

**Comment by FabioHenriqueMF** [comment]
Opa muito obrigado. Fico no aguardo.

**Comment by francofs** [comment]
Vamos lá Fábio, se conseguir ajudar a colocar no projeto agradeço, to realmente sem tempo. Estou pra variar varando a noite no trabalho.

Alguns pontos:

1 - Você provavelmente vai ter que refatorar, coloquei o código de impressão na classe de Nfe, o ideal é estar em outra classe e receber a classe de Nfe para imprimir. Eu tinha criado um projeto novo de impressão, mas não sei quando vou subir, talvez você possa fazer isso.

2 - Existem algums parâmetros adicionais a passar, como data e número do protocolo de autorização que não estão presentes no original.

3 - Tem um projeto auxiliar para desenhar o código de barras, vai ter que colocar lá.

4 - Tem alguns casos que não estão cobertos, como marca d'água para NF-e "sem valor fiscal"

5 - Remova o namespace DomainModel, é do meu projeto.

[nfe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/620406/nfe.zip)


Qualquer dúvida me chama.

**Comment by FabioHenriqueMF** [comment]
Muito obrigado francofs, vou fazer o que puder para cooperar, também estou varando noites no serviço, pra variar. Te dou um toque se precisar de qualquer coisa.

**Comment by francofs** [comment]
Eu que agradeço, to enrolando pra colocar isso no projeto.

**Comment by FabioHenriqueMF** [comment]
francofs bom dia, voce já realizou algum teste com essa solução, se sim tem a DANFE para poder dar uma olhada?

**Comment by francofs** [comment]
Já sim, está rodando em produção. Veja uma que emiti em homolg SP:

[Nfe.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/621631/Nfe.pdf)

Repare que está sem borda à esquerda. Isso porque na impressora do cliente estava cortando, pois não tive tempo de trabalhar as configurações de margem da impressora. No caso resolvia para ficar impressa centralizada. Tem que tentar dar uma brincada em PrinterSettings e QueryPageSettings para ajustar melhor.

**Comment by FabioHenriqueMF** [comment]
Hum ok, vou ser bem sincero, minha vontade de ajudar é maior que meus conhecimento em c# pois isso estou meio perdido kkk

**Comment by francofs** [comment]
Rs, normal, apesar que no cas NF-e, é mais conhecimento em GDI+ que a
linguagem em si.

GDI+ é uma biblioteca poderosa e complexa de desenho. São API's nativas do
Windows que a plataforma .Net encapsula sob o namespace System.Drawing.

Seria interessante você dar uma olhada em algum artigo, está em inglês:
https://www.codeproject.com/articles/1355/professional-c-graphics-with-gdi

Qualquer coisa se não estiver confortável com o inglês tem bastante
tutorial por aí. Como você vai observar é uma API multi-propósito de
desenho.

**Comment by FabioHenriqueMF** [comment]
ok franco muito obrigado, vou ver o que posso fazer

**Comment by FabioHenriqueMF** [comment]
Mais uma duvida franco: ExtendedGraphics?

**Comment by francofs** [comment]
É uma extensão do tipo Nativo Graphics, uso ele pra desenhar o retângulo
com pontas arredondadas. Só tem esses métodos auxiliares
DrawRoundedRectangle, nada além disso. Ele ainda usa o Graphics nativo para
desenhar.

**Comment by FabioHenriqueMF** [comment]
Desculpe mais uma vez minha ignorância, mas como posso usa-la?

**Comment by francofs** [comment]
Putz cara foi mal, esqueci de incluir a classe:

[ExtendedGraphics.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/621853/ExtendedGraphics.zip)

**Comment by FabioHenriqueMF** [comment]
vlwssss

**Comment by FabioHenriqueMF** [comment]
mano mals ai mais uma: MilimetersToHundredthOfInch?

**Comment by FabioHenriqueMF** [comment]
francofs ainda não entendi como faço a impressão, voce pode me explicar a ordem de metodos?
PrintDanfe?
_printDocument_QueryPageSettings?
_printDocument_PrintPage?

**Comment by francofs** [comment]
ops, é um metodo de extensão, mas pode usar de qualquer forma.

/// <summary>
        /// Converts milimiters to hundredths of an inch.
        /// </summary>
        /// <param name="milimiters">The number of milimeters to
convert.</param>
        /// <returns>The value in hundredths of an inch unit.</returns>
        public static int MilimetersToHundredthOfInch(this int milimiters)
        {
            return (int)Math.Round(milimiters * 3.94);
        }

**Comment by francofs** [comment]
Vamos lá,

PrintDanfe chama o Print() do objeto _printDocument.

O método Print do PrintDocument, que é nativo .net dispara os eventos de
impressão:

1 - Antes da impressão de cada página o evento QueryPageSettings é
disparado para eventual configurações de layout da página. É onde eu
configuro dimensões e margem da página.
2 - Após isso, o evento PrintPage é disparado.

A chamada para esses dois métodos não é visível pois é interna do
PrintDocument, por isso são manipuladores de eventos (event handler), assim
como o clique de um botão, por exemplo.

Esses dois eventos são disparados na impressão de todas as páginas. Como
sei que vai ter mais páginas? Através dos cálculos de quantidade de itens.
Se houver mais páginas, no final do PrintPage eu digo: e.HasMorePages =
true.

Esse último é que sinaliza o PrintDocument para chamar o PrintPage
novamente.

**Comment by FabioHenriqueMF** [comment]
ok e o PrintDanfe?

**Comment by francofs** [comment]
Como eu falei, o PrintDanfe é o meu método que chama o Print do
printDocument, antes de chamar o PrintDocument faz algumas parmetrizações
para que a impressão ocorra corretamente.

É o PrintDanfe que sua aplicação vai chamar quando quiser visualizar ou
imprimir o documento.

**Comment by FabioHenriqueMF** [comment]
ok franco, obrigado pela sua paciencia.
Só mais uma duvida com relação ao parametro que recebe o PrintDanfe :PrinterSettings printerSettings?

**Comment by francofs** [comment]
Imagina.

PrinterSettings são as informações da impressora. Por exemplo, aquela
janela que seleciona impressora (PrintDialog) retorna um objeto desse. Que
determina para onde vai a impressão.

**Comment by adrbarros** [comment]
Dêem uma olhada em: https://github.com/SilverCard/DanfeSharp
onde a partir de um XML, ele gera um PDF e abre no Browser padrão.

**Comment by francofs** [comment]
Boa Adriano,

Ajuda a nossa implementação, só não me atende porque uso aplicação desktop
e tenho outros casos de uso o qual o formato PDF não atende. Mas pode
ajudar como guia em alguns casos.

**Comment by FabioHenriqueMF** [comment]
opa franco bele.
Estou com um baita problema.
no PrintPreviewDialog como eu controlo o evento do click em print?
Gostaria de que o mesmo chamasse o PrintDialog para selecionar a impressora.
Estou fazendo, quero fazer, assim:
o cara clica em pre-visualizar a danfe daí mostra a danfe no PrintPreviewDialog.
caso o cara click no print ai abro o PrintDialog para seleção da impressora.
Mas não esta andando...

**Comment by francofs** [comment]
Então eu na verdade não uso o PrintPreviewDialog. Eu crio meu próprio From
e coloco o PrintPreviewControl nele. Assim tenho mais controle sobre o
comportamento.

No método PrintDanfe, um dos parâmetro é "callPrint". Quando ele é true,
você envia para impressora, quando ele é false, o método Print não é
chamado, então apenas utilizo o retorno (PrintDocument) que é utilizado
para renderizar no controle.

2016-12-01 19:32 GMT-02:00 FabioHenriqueMF <notifications@github.com>:

**Comment by FabioHenriqueMF** [comment]
É estou tentando criar esse form, mas e os controles de imprimir, zom...?

**Comment by francofs** [comment]
Os controles você pode fazer como preferir. Um botão, caixa de texto, etc.
Exemplo:

`
private void tsbPrint_Click(object sender, EventArgs e)
        {
            _Nfe.PrintDanfe(_NfePrinterSettings, _Nfe.AccessKey,
_Nfe.Authorization, _Nfe.Date, true, _Nfe.Status);
        }

private void btnPaginaAnterior_Click(object sender, EventArgs e)
        {
            if (ppcNfe.StartPage == 0)
                return;

            ppcNfe.StartPage--;
            tslPages.Text = string.Format("Página {0} de {1}",
ppcNfe.StartPage + 1, _BusNfe.GetTotalPages());
        }

        private void btnProximaPagina_Click(object sender, EventArgs e)
        {
            ppcNfe.StartPage++;
            tslPages.Text = string.Format("Página {0} de {1}",
ppcNfe.StartPage + 1, _BusNfe.GetTotalPages());
        }

        private void txtZoom_TextChanged(object sender, EventArgs e)
        {
              ppcNfe.Zoom = double.Parse(txtZoom.Text) / 100;
        }
`

**Comment by FabioHenriqueMF** [comment]
franco é possível salvar o conteúdo do printPreviewControl para PDF? Ou tenho que chamar o PrintDialog e selecionar o PDFCreator por exemplo?

**Comment by francofs** [comment]
Existem diversas maneiras de fazer o PDF, uma delas é imprimir para PDF (a
mais simples). No caso teria que ver alguma implementação para transformar
em PDF, mas é possível sim. Precisa dar uma procurada.
