### ISSUE TITLE
[DÚVIDA] Integração com outras linguagens (Python, NodeJS, C/C++, Delphi ...)

### ISSUE THREAD

**Issue by silvioprog** [ZeusAutomacao/DFe.NET#265]
Olá,

Primeiramente, parabéns a todos pelo projeto, tenho observado que ele tem seguido as atualizações do governo e isso é realmente muito importante! :-)

Então, minha dúvida é sobre integrá-lo com outras linguagens. Como sou bastante novato no projeto ainda não consegui absorver o que ele exporta nas DLLs. Caso sejam funções, structs e enums, a integração com outras linguagens é tranquilamente possível. Caso contrário, seria interessante pensar nessa possibilidade, pois como ele é bastante promissor, a integração com outras linguagens o tornaria ainda mais popular. Imaginem o pessoal do Python e do NodeJS aderindo ao projeto ...

Aqui na empresa nós temos um ERP escrito em Delphi e no momento é inviável portá-lo para outra linguagem como por exemplo C#. No entanto, caso a lib Zeus NF* exporte suas funções na DLL, criar um header Pascal para consumi-la é extremamente simples, e esse header poderia ser distribuído junto com o Zeus, possivelmente numa pasta "Bindings". Vários outros projetos escritos em C/C++/C# seguem essa abordagem, a libCURL é um bom exemplo disso. Demais bindings (para Python, JS, C/C++ etc.) seriam adicionados posteriormente.

O que vocês acham dessa ideia? Caso estejam de acordo, me proponho a escrever o header para Delphi e já oferecendo suporte também para o Free Pascal, possibilitando uma integração com Linux assim que o Zeus compilar as .SOs Unix.

Abração!

**Comment by agostinhovitorio** [comment]
Olá, como você está afirmando, também sou muito novo na área de programação, pois venho de outra área, a de humanas, mas, a parte analítica da mesma (filosofia da ciência). Então, estou tentando incrementar uma API, onde preciso separar o tempo de espera num call center pela URA do tempo de atendimento de um agente físico, entende! E como programo em Python também, fiquei pensando se não poderia integrar o NodeJs com o mesmo! Se começarem, estarei aqui para aprender e aplicar, ok! Abraços
