### ISSUE TITLE
[DÚVIDA] Impressão de NF-e de venda de veículos.

### ISSUE THREAD

**Issue by wikermoura** [ZeusAutomacao/DFe.NET#271]
Bom dia pessoal, sou novo no projeto e estou tentando imprimir a DANFE usando o Zeus, estou com um problema na emissão da nota de venda do veículo que, apesar de "todos os dados no xml", a danfe não é impressa com os dados do produto especifico. No xml esta esta forma:
<det nItem="1">
<prod>
<cProd>9</cProd>
<cEAN/>
<xProd>Corsa</xProd>
<NCM>87651313</NCM>
<CEST>0100100</CEST>
<CFOP>5403</CFOP>
<uCom>59</uCom>
<qCom>1.0000</qCom>
<vUnCom>18000.0000000000</vUnCom>
<vProd>18000.00</vProd>
<cEANTrib/>
<uTrib>59</uTrib>
<qTrib>1.0000</qTrib>
<vUnTrib>18000.0000000000</vUnTrib>
<indTot>1</indTot>
<nItemPed>0</nItemPed>
<veicProd>
<tpOp>0</tpOp>
<chassi>321651321GF5R6515</chassi>
<cCor>1</cCor>
<xCor>CINZA ESPACIAL</xCor>
<pot>150</pot>
<cilin>125</cilin>
<pesoL>650.000</pesoL>
<pesoB>750.000</pesoB>
<nSerie>NORMAL</nSerie>
<tpComb>12</tpComb>
<nMotor>213546812132546846512</nMotor>
<CMT>125.0000</CMT>
<dist>0000</dist>
<anoMod>2010</anoMod>
<anoFab>2010</anoFab>
<tpPint>5</tpPint>
<tpVeic>6</tpVeic>
<espVeic>1</espVeic>
<VIN>N</VIN>
<condVeic>1</condVeic>
<cMod>1</cMod>
<cCorDENATRAN>5</cCorDENATRAN>
<lota>4</lota>
<tpRest>0</tpRest>
</veicProd>
</prod>
<imposto>
<vTotTrib>18000.00</vTotTrib>
<ICMS>
<ICMSSN102>
<orig>0</orig>
<CSOSN>102</CSOSN>
</ICMSSN102>
</ICMS>
<IPI>
<cEnq>999</cEnq>
<IPITrib>
<CST>99</CST>
<vBC>0.00</vBC>
<pIPI>0.0000</pIPI>
<vIPI>0.00</vIPI>
</IPITrib>
</IPI>
<PIS>
<PISOutr>
<CST>99</CST>
<vBC>0.00</vBC>
<pPIS>0.0000</pPIS>
<vPIS>0.00</vPIS>
</PISOutr>
</PIS>
<COFINS>
<COFINSOutr>
<CST>99</CST>
<vBC>0.00</vBC>
<pCOFINS>0.0000</pCOFINS>
<vCOFINS>0.00</vCOFINS>
</COFINSOutr>
</COFINS>
</imposto>
</det>

Porém na impressão só mostra os dados principais do produto. Preciso que imprima todos os itens do produto especifico. Alguém pode me ajudar por favor ?

**Comment by adeniltonbs** [comment]
Boa noite @wikermoura, a impressão desses dados não está disponível no DANFE.  Chegou a verificar no [Manual de Orientação do Contribuinte - versão 6.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=) se é possível adicionar esses campos no DANFE?

**Comment by wikermoura** [comment]
Boa noite @adeniltonbs, em primeiro lugar eu gostaria de parabenizar pelo seu trabalho. Acompanho a pouco tudo o que vocês estão fazendo, mas admiro o que fazem. Na verdade eu já vi sim, e quando se vai emitir uma NF-e de veículos novos, todos os campos acima, são obrigatórios. Caso não esteja desta forma o DENATRAN/DETRAN não aceitam a nota. 
No arquivo da DANFE em fastreport, será deverá conter os campos de produtos específicos. Atualmente só tem dados de produtos relacionados a remedios.
Eu gostaria de ajudar no projeto, mas não entendi no fastreport como posso fazer para adicionar tais campos.

**Comment by adeniltonbs** [comment]
@wikermoura Boa tarde,
Para editar o designer do relatório no fast, o meio mais prático é:
Na aplicação NFe.Danfe.AppTeste, classe MainWindow, método BtnNfeDanfeA4_Click, comente a linha 

`danfe.Visualizar();`
e descomente a linha:
`danfe.ExibirDesign();`

Execute a aplicação, clique no botão "DANFE NFe A4" 
![image](https://cloud.githubusercontent.com/assets/6733483/20979268/0dfa7e12-bc8b-11e6-8e7c-3e98c462b182.png)
Selecione o XML que contém os dados em questão. Em seguida, o designer do fast reports será aberto, daí podes adicionar/alterar/remover campos.

Outra forma, é, depois de instalar o FastReport.Net (https://www.fast-report.com/pt/download/public_download/FRNetDemo.msi), abrir a aplicação "Report Designer" e a partir dele, abrir o arquivo NFe.Danfe.Fast\NFe\NFeRetrato.frx

**Comment by wikermoura** [comment]
@adeniltonbs, muito obrigado. Deu certo, fiz a alteração e agora a nota esta saindo correta para quando venda de veículos novos.

**Comment by adeniltonbs** [comment]
@wikermoura Se desejar, podes compartilhar sua alteração com a comunidade, fazendo um pull request.

**Comment by leandrosantoslss** [comment]
> @adeniltonbs, muito obrigado. Deu certo, fiz a alteração e agora a nota esta saindo correta para quando venda de veículos novos.

@wikermoura  consegue compartilhar o arquivo FRX que você alterou para sair os dados de veículo, estou batendo aqui já tem uns 3 dias e ainda não consegui.
