### ISSUE TITLE
Danfe A4 - Fast Reports

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#273]
@adeniltonbs,

Uso a impressão da Danfe em A4 em FastReports em produção em alguns clientes a algum tempo já, pode alterar o to do para implementado que já está em produção.

Abraços

**Comment by adeniltonbs** [comment]
Feito.

**Comment by acggermed** [comment]
olá amigo Marcos... por favor passa pra mim a solução de impressão NFe e NFCe pelo FastReport...
Outra coisa: Essa ferramenta é free? como adiquirir?

grato

**Comment by guidi** [comment]
@acggermed dá uma olhada na aplicação exemplo da biblioteca lá tem como fazer a impressão do danfe de NFCe e NFe.

**Comment by marcosgerene** [comment]
@acggermed,

Baixa os fontes do projeto, hoje tem já a impressão do NFCe, NFe e já tem um pull pra MDFe, porém todos são em FastReports.

O FastReports não é free, a licença custa em torno de R$ 1.000,00 para um usuário winforms (meu caso), mas para mim foi a unica ferramenta de relatórios que realmente atendeu todas minhas expectativas com o C# (vim do Delphi).

Abraços
