### ISSUE TITLE
Erro ao solicitar Status do Serviço

### ISSUE THREAD

**Issue by JohnSalazar** [ZeusAutomacao/DFe.NET#274]
Bom dia,

Estou testando a NFe em ambiente de Homologação.

Quando escolho a opção Status do Serviço ou até mesmo Criar e Enviar 3.0 apresenta o erro: "Erro ao criar o Proxy Web especificado na seção de configuração 'system.net/defaultProxy'".

Para teste estou utilizando a função Status do Serviço

É gerado corretamente o xml de requisição, conforme abaixo:

`<consStatServ versao="3.10"><tpAmb>2</tpAmb><cUF>53</cUF><xServ>STATUS</xServ></consStatServ>`

O erro apresenta na seguinte função:

var results = Invoke("nfeStatusServicoNF2", new object[] {nfeDadosMsg});

Aparentemente o nfeDadosMsg é carregado corretamente.

As versões de cada serviço estão todas marcadas para 3.1, em exceção somente: NfeRecepcao e NfeRetRecepcao. Já coloquei estas para 3.1 e também apresenta o mesmo erro.

O esse erro pode ser o endereço do ws incorreto?

Obrigado.

**Comment by adeniltonbs** [comment]
DF certo?
Testei aqui nos dois ambientes com a aplicação NFe.AppTeste e funcionou normalmente:

![1](https://cloud.githubusercontent.com/assets/6733483/20942434/23340b24-bbda-11e6-8970-4c2e578ea5ac.png)

![2](https://cloud.githubusercontent.com/assets/6733483/20942441/26b3da4a-bbda-11e6-9703-8a04696e316d.png)

Dica: Tente acessar a url do serviço diretamente no navegador.

**Comment by JohnSalazar** [comment]
Olá adeniltonbs,

Testei a url pelo navegador como você me orientou e funcionou. Porém no visual studio não funciona.

Estou utilizando o VS 2015 Community Update 3, será que é incompatível?

Obrigado.

![erro](https://cloud.githubusercontent.com/assets/16736914/20945148/3db72810-bbed-11e6-97dd-2fd9410ea66a.png)

**Comment by adeniltonbs** [comment]
Existe um servidor proxy intermediando a comunicação https://support.microsoft.com/pt-br/kb/318140?
O erro descrito foi apresentado na aplicação de demonstração de uso da biblioteca?

**Comment by JohnSalazar** [comment]
Boa noite adeniltonbs,

Li o artigo da Microsoft que você mandou, e não encontrei em toda a solução os arquivos machine.config ou web.config. Percebi que a versão do framework que estão usando é a 4.0. Identifiquei que um arquivo chamado SYSTEM.NET.HTTP não tinha no framework da máquina, copiei do framework 4.5 e mesmo assim não resolveu.

Identifiquei no erro, uma chamada não bem sucedida de um arquivo chamado RASAPI32.DLL(encontra-se em windows\system32), na minha máquina está na versão 10.0.14393.0, procurei na internet um hotfix da microsoft para ele, porém não existe para windows 10. Está em anexo a imagem

O erro descrito está na aplicação de demonstração. Está rodando em Windows 10 Pro 64 bits, VS Studio 2015 Community.

E toda vez que abro a solução, apresenta uma mensagem de aviso. Está em anexo a imagem

Obrigado.
![aviso](https://cloud.githubusercontent.com/assets/16736914/20985835/4815c274-bcad-11e6-82d9-9d7d753c1095.png)
![erro](https://cloud.githubusercontent.com/assets/16736914/20985836/481d7c26-bcad-11e6-8395-20853d2c9551.png)

**Comment by adeniltonbs** [comment]
Desculpa a demora, mas conseguiu resolver o problema?

**Comment by JohnSalazar** [comment]
Problema resolvido. Obrigado
