### ISSUE TITLE
[Urgente] - Exception of type 'NFe.Utils.Exceptions.ValidationException' was thrown

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#275]
Ao tentar transmitir meu xml recebo o seguinte erro:

o XML não chega a ser assinado, vou tentar ver aonde o erro acontece

--------

O erro ocorre aqui:
```
NFe.Utils.Validacao.Validador.Valida(NFe.Classes.Servicos.Tipos.ServicoNFe.NFeAutorizacao,`
                                                             NFe.Classes.Servicos.Tipos.VersaoServico.ve310,
                                                             _nfe.ObterXmlString(),
                                                             false);

```

O XML chega a ser assinado:

[xml_assinado.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/636938/xml_assinado.zip)

**Comment by adeniltonbs** [comment]
Atualize sua biblioteca. Fiz um commit nesse ponto hj

**Comment by marcosgerene** [comment]
Boa @adeniltonbs , valeu
