### ISSUE TITLE
[DÚVIDA] Nota Importação erro de transmissão

### ISSUE THREAD

**Issue by IsraelCamilo** [ZeusAutomacao/DFe.NET#276]
Olá,
Estou tendo um problema com a nota de importação, não transmite com o XML gerado, o mesmo XML é transmitido via Emissor. Segue o problema:
O elemento 'adi' incompleto.
No xml está completo.

**Comment by adeniltonbs** [comment]
Resolvido em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/302
