### ISSUE TITLE
Assinatura da NFe

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#279]
Olá!
Verifiquei que quando utilizo o método NFe.Utils.Assinatura.ObterAssinatura() o sistema carrega toda vez o certificado digital novamente, e no caso de utilizar o certificado do tipo A3 demora um tempo até que a leitora responda.

Ao alterar o código da seguinte forma o sistema carrega apenas uma vez o certificado, tornando a assinatura da NFe muito mais rápida:

Perceba que adicionei uma propriedade na classe NFe.Utils.ConfiguracaoCertificado

`

        [XmlIgnore]
        public System.Security.Cryptography.X509Certificates.X509Certificate2 CertificadoCarregado { get; set; }`

e alterei o método ObterAssinatura

`

            System.Security.Cryptography.X509Certificates.X509Certificate2 certificado = null;

            if (ConfiguracaoServico.Instancia.Certificado.CertificadoCarregado != null)
            {
                certificado = ConfiguracaoServico.Instancia.Certificado.CertificadoCarregado;
            }
            else
            {
                certificado = string.IsNullOrEmpty(ConfiguracaoServico.Instancia.Certificado.Arquivo)
                    ? CertificadoDigital.ObterDoRepositorio(ConfiguracaoServico.Instancia.Certificado.Serial, ConfiguracaoServico.Instancia.Certificado.Senha)
                    : CertificadoDigital.ObterDeArquivo(ConfiguracaoServico.Instancia.Certificado.Arquivo, ConfiguracaoServico.Instancia.Certificado.Senha);

                ConfiguracaoServico.Instancia.Certificado.CertificadoCarregado = certificado;
            }`

Se não interferir em nenhum outro processo acredito que desta forma o método ficaria melhor.
Fiz alguns testes aqui e não tive nenhum problema.

Márcio Müller

**Comment by guidi** [comment]
Acho que vale subir um pull com a alteração :)

**Comment by leandrossantos** [comment]
@marciojmuller no caso do certificado A3 e a senha/PIN definida nas configurações do componente, essa alteração que você fez aceita a senha também ou o usuário terá que informar a senha/PIN na primeira vez que chamar o certificado?

**Comment by francofs** [comment]
Eu fiz um pull request que não precisa digitar nunca a senha do A3, uma vez
configurada. Não sei se entrou. Hoje você precisa digitar? Comigo, sempre
preciso digitar antes de implementar minha solução

2016-12-08 11:46 GMT-02:00 leandrossantos <notifications@github.com>:

**Comment by marciojmuller** [comment]
Quando você configura a senha na aplicação não pede a senha/PIN, nunca pediu depois de ter configurado uma vez

**Comment by francofs** [comment]
Uhhm, talvez seja meu Windows 10. Alguém já testou?

**Comment by marciojmuller** [comment]
Utilizo o windows 10 aqui e não pede, você configurou a senha na aplicação?

**Comment by francofs** [comment]
Configurei, sempre que inicio a aplicação pede o PIN, minha solução foi
utlizar P/Invoke pra setar a senha. Não sei se é a configuração de
segurança da maquina (dentro de dominio corporativo)

**Comment by leandrossantos** [comment]
@marciojmuller da um pull request dessa alteração que você fez ai então e @adeniltonbs se possível da um merge com essa alteração do @marciojmuller para testarmos o certificado A3 e ver se o problema do SSL/TLS foi solucionado de vez. Então se tiver dado tudo ok acredito que possa cancelar o pull request do @francofs

**Comment by marciojmuller** [comment]
Sobre SSL/TLS tive problemas em clientes e encontrei esse link:
http://tdn.totvs.com/pages/releaseview.action;jsessionid=09E10C09BB89521051135024D9191E6F?pageId=173081905

Resolveu o problema.

**Comment by leandrossantos** [comment]
@marciojmuller  a questão do SSL/TLS comigo aconteceu o seguinte, criei uma aplicação monitor que fica no systray, então ela faz uma verificação no DistribuicaoDFe de 3 em 3 minutos, o que acontece é que assim que faz essa consulta e o retorno vem com notas eu gero o XML ou faço o download do mesmo e então depois de algumas consultas ou downloads da o erro de SSL/TLS, essa parte que você passou no link já foi vista e está tudo certo. Por isso que quero testar essa sua nova implementação para ver se resolve. Lembrando que o erro de SSL/TLS só acontece quando a senha/PIN do certificado A3 esta definida nas configurações, se eu retirar a senha das configurações para o usuário informar o problema não acontece.

**Comment by marciojmuller** [comment]
não tem um tempo mínimo que pode ficar dando loop nos web services?
pelo que encontrei o mínimo é 3 minutos, já tentou operar a sua aplicação com 4 ou 5 minutos de intervalo entre as consultas?
pode ser que o web service não está aceitando suas consultas.

**Comment by leandrossantos** [comment]
@marciojmuller a questão é como te falei, se eu retiro a senha da configuração e deixo para o usuário informar funciona sem problema, mais se defino a senha para não ter intervenção do usuário acontece o problema do SSL/TLS

**Comment by marcosgerene** [comment]
@leandrossantos Estou com EXATAMENTE o mesmo "sintoma".
