### ISSUE TITLE
Serviço nfeRecepcao

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#28]
Boa noite amigo..

De ante mão, parabéns pelo trabalho.
Estou testando seu app e estou maravilhado. No entanto, está ocorrendo uma situação quando selecione o UF 'RS', e clico em 'Criar e Enviar 2.0' ele me apresenta um erro.

Mensagem: Que não está disponível no modo homologação para emissão do tipo normal para o estado RS.

É algo que preciso recompilar a solução, algum parâmetro, ou de fato é algo a ser desenvolvido mesmo?

Obrigado.
Darlan Hendges.

**Comment by adeniltonbs** [comment]
Bom dia darlanhendges, se você olhar no site da NFe, em relação de serviços web - Produção(http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#RS) e homologação(http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#RS), verás que o estado do RS já não tem mais os serviços de recepção e autorização na versão 2.0, somente na versão 3.0. Para você consumir corretamente os serviços, deve estar atento a isto, pois cada estado tem suas próprias versões dos serviços.

**Comment by darlanhendges** [comment]
Obrigado pelo retorno!

Sem delongas afirmo que sou iniciando na parte de nfe, e encontrei algumas dificuldades.

Sua framework veio ao encontro de minha necessidade. Se um dia tiveres um tempo para fazer um vídeo de como utilizar, com suas palavras acredito que vamos atingir ainda mais desenvolvedores para colaborar com o projeto!

Conte comigo!
Abraço
