### ISSUE TITLE
[DÚVIDA] Como obter o Protocolo da Carta de Correção?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#282]
Boa tarde.
Não estou conseguindo obter o protocolo da carta de correção.
Pelo que entendi o mesmo deveria estar na classe retEvento>  infEventoRet > nProt.

**Comment by marciojmuller** [comment]
Olá!
var retornoCartaCorrecao = servicoNFe.RecepcaoEventoCartaCorrecao(Convert.ToInt32(idlote), Convert.ToInt16(sequenciaEvento), chave, correcao, cpfcnpj);
string protocolo = retornoCartaCorrecao.Retorno.retEvento[0].infEvento.nProt;

Repare que o retEvento é uma lista de eventos.


Márcio Müller

**Comment by FabioHenriqueMF** [comment]
muito obrigado marciojmuller . Só mais uma dúvida com relação a lista:
isso quer dizer que posso realizar vários eventos ao mesmo tempo, e a sefaz me retorno todos juntos?

**Comment by marciojmuller** [comment]
já que ele retorna uma lista, acredito que sim.....mas nunca testei isso.

**Comment by FabioHenriqueMF** [comment]
ok muito obrigado
