### ISSUE TITLE
[DÚVIDA] Validar Schema TXT NF-e?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#283]
Boa tarde.
Por acaso existe alguma maneira de validar Schema de arquivos TXT da NF-e assim como validamos os Schemas de XML?

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Não. Também no momento a biblioteca não suporta aquivos TXT da NF-e. Somente XML mesmo.
