### ISSUE TITLE
Adicionar produtos

### ISSUE THREAD

**Issue by crzcrazycrz** [ZeusAutomacao/DFe.NET#284]
Existe um Form exemplo para preencher a nfe adicionar produtos etc?

Grato

**Comment by adeniltonbs** [comment]
@crzcrazycrz Sim. Veja a aplicação de demonstração de uso da biblioteca na solução, NFe.AppTeste. https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste
