### ISSUE TITLE
Gerar XML de NFC-e a partir da Chave de Acesso

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#286]
Adenilton, boa tarde,

Existe a possibilidade de pela dll gerar um XML de NFC-e a partir da chave de acesso da mesma?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
@robertocvsiqueira Refazendo sua pergunta: Existe algum webservice que disponibilize o XML da NFCe a partir da chave de acesso da mesma?
Resposta: Não. No entanto algumas SEFAZes disponibilizam em seu portal, opção para baixar o XML de NFCe's emitidos em determinado período.

Se for NFe, a resposta é sim.
No caso da NFe, depois de enviar uma manifestação do destinatário (Serviço RecepcaoEvento – Manifestação do Destinatário) para a NFe emitida por terceiros, você poderá baixar o XML através do serviço NfeDownloadNF.
