### ISSUE TITLE
[DÚVIDA] Situação Tributário ICMS 10, 40 e 90 (2 casos ???)

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#287]
Boa tarde pessoas.
Seguinte, estive observando que a Situação tributário do ICMS para o regime Tributação Normal existem 2 casos para os códigos 10, 40 e 90.
Considerando que na minha base eu guardo apenas o Código da Situação Tributário (ex: 90) como poderei diferenciar os casos(??????):
"10 - Tributada e com cobrança do ICMS por ST";
"10 - Tributada e com cobrança do ICMS por ST (com partilha do ICMS entre a UF de origem e a UF de destino ou a UF definida na legislação)";

"41 - Não tributada";
"41 - Não tributada (ICMSST devido para a UF de destino, nas operações interestaduais de produtos que tiveram retenção antecipada de ICMS por ST na UF do remetente)";

"90 - Outras (com partilha do ICMS entre a UF de origem e a UF de destino ou a UF definida na legislação)";
"90 - Outras";

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Pois é, mande um 👎  pra o pessoal do governo. Neste caso, @FabioHenriqueMF, fica claro que a CST não é uma chave candidata.
