### ISSUE TITLE
Endereço NFC-e RJ

### ISSUE THREAD

**Issue by SilverioMiranda** [ZeusAutomacao/DFe.NET#29]
Qual o tipo de ambiente para emitir NFC-e para o RJ?

Eu não encontrei no DefiniçãoWSDL os endereços que constam no site da sefaz do rj

RecepcaoEvento  1.00    https://nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
NfeInutilizacao 2.00 / 3.10 https://nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
NfeConsultaProtocolo    2.00 / 3.10 https://nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
NfeStatusServico    2.00 / 3.10 https://nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
NFeAutorizacao  3.10    https://nfe.sefazvirtual.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx
NFeRetAutorizacao   3.10    https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx

Ambiente de Homologação (Testes) - http://hom.nfe.fazenda.gov.br/portal/

Serviço    Versão     URL
RecepcaoEvento  1.00    https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
NfeInutilizacao 2.00 / 3.10     https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
NfeConsultaProtocolo    2.00 / 3.10 https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
NfeStatusServico    2.00 / 3.10 https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
NFeAutorizacao  3.10    https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx
NFeRetAutorizacao   3.10    https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx

Alguma dica?
Obrigado

**Comment by adeniltonbs** [comment]
MirandaBrazil, note que a SEFAZ do RJ usa os endereços da Sefaz Virtual do RS.
Esses endereços que você me passou, são os ANTIGOS endereços da Sefaz Virtual do RS, que serão desativados em breve. Certamente a página da NFCe da SEFAZ do RJ ainda não foi atualizada, verifique com eles.

Eu fiz o último levantamento das UFs que disponibilizaram urls diferentes para NFCe, até 04/05/2015 e etá então as seguintes UFs haviam feito isso: SVRS, AM, MT, PR, RS e SP.

Note que a SVRS agora tem endereços para NFCe separados e possuem o seguinte formato: https://nfce-homologacao.svrs.rs.gov.br/ws/... e https://nfce.svrs.rs.gov.br/ws/...

**Comment by SilverioMiranda** [comment]
Desculpe demorar pra responder, o email da sefaz foi esse :

Prezado, 

Veja orientação no Portal NFCe  na opção Perguntas Frequentes -item 8.

Dai vi que a versão html está desatualizada e os endereços certos são os do pdf que são os que você informou.

O meu problema era a IE que estava errada. Sugiro que você coloque um aviso pra quem é novo no ambiente da NF-e que verifique o retorno da NF depois de enviar o lote pra confirmar se ta tudo certo, vi que outros também estão tendo esse problema.

Obrigado
