### ISSUE TITLE
Implementar impressão do DANFE de NFCe A4

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#291]

**Comment by juhpetri** [comment]
Boa tarde @adeniltonbs, gostaria de tirar uma duvida sobre a impressão do Danfe.
O Zeus so faz a impressão de XML da NFCe protocolado?
Como posso fazer em caso de contingencia onde o XML so vai estar assinado?
Me desculpe se estiver sendo ignorante, como comecei a pouco tempo usar o Zeus ainda tenho algumas duvidas

**Comment by adeniltonbs** [comment]
@juhpetri Boa noite. Faz a impressão do DANFE da NFCe com protocolo e contingência (sem o protocolo, objeto NFe somente). Na aplicação de demonstração de uso "NFe.Danfe.AppTeste" tem um exemplo para cada caso.

![image](https://cloud.githubusercontent.com/assets/6733483/21328997/399629ca-c615-11e6-81be-757dd502f3a3.png)

Sempre que tiver uma dúvida, o melhor é abrir um novo issue, em vez de aproveitar um já existente.
![image](https://cloud.githubusercontent.com/assets/6733483/21329058/79638f70-c615-11e6-8f14-7d917afce9ef.png)
