### ISSUE TITLE
Implementar impressão do DANFE sem dependências de bibliotecas de terceiros

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#294]

**Comment by jvretamero** [comment]
Neste caso, seria usado o [PrintDocument](https://msdn.microsoft.com/en-us/library/system.drawing.printing.printdocument(v=vs.110).aspx)?

**Comment by edsonfast** [comment]
Poderia utilizar o PDFClown igual o projeto https://github.com/SilverCard/DanfeSharp

**Comment by jvretamero** [comment]
A issue é justamente pra não depender de terceiros, vamos aguardar se o
pessoal aprova.
