### ISSUE TITLE
[DÚVIDA] IdEstrangeiro

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#299]
Boa tarde pessoal.
Segundo o manual da SEFAZ se operação com Exterior tenho que informar o código do estrangeiro ou apenas informar a tag idEstrangeiro, vazia. Mas como faço visto que ao serealizar o XML, se a tag estiver vazia, ele traz apenas "/idEstrangeiro>" ?

**Comment by adeniltonbs** [comment]
Desculpa a demora.
Sua dúvida já foi sanada?
Dica: Veja se é o caso de incluir o padrão ShouldSerialize na classe dest, para o atributo idEstrangeiro.

**Comment by FabioHenriqueMF** [comment]
Opa adenilson ja corrigi sim obrigado
