### ISSUE TITLE
Pis/Cofins e etc

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#30]
Boa tarde.

Fugindo da parte técnica:

Na parte de detalhamento da Nfe, especificamente falando do objeto Imposto, aqueles dados que você colocou no app de teste, seria os dados padrões ? Ou altera para cada empresa ?

  COFINS = new COFINS { TipoCOFINS = new COFINSOutr { CST = CSTCOFINS.cofins99, pCOFINS = 0, vBC = 0, vCOFINS = 0 } },
                    PIS = new PIS { TipoPIS = new PISOutr { CST = CSTPIS.pis99, pPIS = 0, vBC = 0, vPIS = 0 } }

det.imposto.IPI = new IPI() { cEnq = "999", TipoIPI = new IPITrib() { CST = CSTIPI.ipi00, pIPI = 5, vBC = 1, vIPI = 0.05m } };

Preciso alterar algo nesses campos, ou são padrões ?

Desculpe pela falta de conhecimento, estou entrando devagar nessa parte. 

Obs: Já consegui gerar notas no ambiente de homologação. 
Mas antes fazer uma pergunta besta, do que fazer algo pior.

Caso não saiba, pode me encaminhar algum lugar para que eu possa ler sobre o assunto?

Obrigado.
Darlan.

**Comment by adeniltonbs** [comment]
É bom você dar uma olhada no manual a NFe para se situar melhor. Confira o Manual de Orientação do Contribuinte - versão 6.00 - Minuta, que você pode encontrar aqui http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=.

Só pra te adiantar, a tributação na NFe está para o produto e não para a nota e muito menos para a Empresa. Assim em uma NFe, cada produto pode ter uma tributação diferente.
