### ISSUE TITLE
[MDFe] - Problemas

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#303]
Problemas/Ajustes identificados na minha implementação do Zeus MDFe:

**1. UfDestino nas configurações.**
A uf definida é do EMITENTE e não de destino nas configurações, tanto que se preenche o campo cUF do ide, e segundo a página 98 do manual: "Código da UF do emitente do MDF-e ".

***2. Primeira letra maiuscula***
Aqui pode ser desconsiderado, mas para seguir os padrões do manual e do próprio Zeus para NFe seria interessante usar a primeira letra minuscula nas propriedades, ex: cMDF e não CMDF.

***3. Namespace***
Não consigo entender porque existe 2 namespaces "MDFe" e "ManifestoDocumentoFiscalEletronico".

***4. Salvar em disco***
Na função "SalvarXmlEmDisco" seria interessante permitir passar o caminho completo ou usar o padrão.

***5. DFe.Utils, MDFe.Utils e NFe.Utils***
Seria bem interessante um refatoring no projeto para usar o DFe para o que for comum entre os documentos ou separar de vez NFe e MDFe e outros que vierem, alem de corrigir o namespace como está no ítem 3.

***6. CMDFe***
O código da MDFe está como numérico mas ele exige 8 dígitos, logo deveria ser um string, no meu caso eu usp o código o mesmo número do MDFe com zeros a esquerda, visualmente na pasta dos arquivos fica mais fácil encontrar o arquivo visto que ignorando o ultimo dígito temos o número do documento.

--------------

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300 - 1,4 e 6 ajustados.

**Comment by robertorp** [comment]
Realmente hehe ficou estranho Destino, melhor colocar emitente mesmo. Somente opinião minha.

Agora sobre letras maiúscula e minusculas, quando fiz , fiz assim somente para seguir padrões mesmo de programação. E se observar também nas classes segui esse padrão MDFeEmit
se seguir o padrão do Zeus teria que colocar somente "emit" 
não coloquei assim porque acredito eu que poderiam ocorrer casos no qual você digitaria emit.. e a IDE sugeria o NF-e é MDF-e e posteriormente CT-e que poderia ter o "emit" também.

Do que depender de min a questão do UfDestino pode corrigir para UfEmitente.

Obrigado.

**Comment by marcosgerene** [comment]
@robertorp ainda estou implementando, não cheguei sequer a gerar o XML, é que eu "acustumei' com o ZeusNFe e NFCe então ao usar o ZeusMDe esperava ter o mesmo padrão, como disse anteriormente vou fazer mais considerações, ao terminar de implementar ai sim abro uma nova insue em cima desta para discutir mudanças ou até mesmo propor algo

Abraços

**Comment by marcosgerene** [comment]
So uma questão, está em produção o MDFe?

**Comment by robertorp** [comment]
Está sim em produção, o sistema e este 
http://sistemafusion.com.br/

Temos em produção o CT-e e MDF-e (o CT-e não coloquei aqui ainda, porque não to tendo tempo é conversei com uma pessoa daqui que disse que tava fazendo um CT-e para cá ai resolvi aguardar.. mas.. logo logo vou desacoplar o CT-e do projeto para cá)

Utilizamos o ZeusNFe para NFE é NFC-e 
é agora MDF-e

**Comment by marcosgerene** [comment]
Bom dia @robertorp ,

Adicionei ao meu pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300 que já estava aberto as correções para 1,4 e 6.

Aberta nova insue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/308 para discutir os outros 3 pontos.

**Comment by adeniltonbs** [comment]
@marcosgerene Vendo suas modificações, percebi que no arquivo NFCE.frx, a fonte "Open Sans Condensed Light" foi substituída pela fonte "Microsoft Sans Serif", em diversos componentes. Essa alteração faz parte das suas implementações?
