### ISSUE TITLE
[MDFe] - Nota Fiscal A1

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#304]
Boa tarde,

Desenvolvendo o MDFe, estava usando como base o manual e o emisso gratuíto e esbarrei em um problema.
O Manual do MDFe não diz nada sobre nota fiscal do modelo A1 (papel), porém no emissor gratuíto existe essa opção e inclusive ele gera o XML (não cheguei a transmitir) com esses dados.

O emissor: 
![emissor](https://cloud.githubusercontent.com/assets/15945003/21506715/82b9dda0-cc59-11e6-957c-3973aba67fd9.png)

Xml gerado pelo emissor:
![xml_emissor](https://cloud.githubusercontent.com/assets/15945003/21506726/9dafb0c6-cc59-11e6-9725-fca39de2cdd6.png)

Buscando na internet acabei "caindo" no flexdoc:
http://www.flexdocs.com.br/guiamdfe/gerarMDFe.infDoc.html
![flexdoc](https://cloud.githubusercontent.com/assets/15945003/21506748/c1be896a-cc59-11e6-8739-acc391f29772.png)

-------------

Entretanto, na classe do projeto temos isto:
![classe](https://cloud.githubusercontent.com/assets/15945003/21506760/d0845dc6-cc59-11e6-8fba-eb1edde17286.png)

Resolvi buscar no manual: https://mdfe-portal.sefaz.rs.gov.br/Site/Documentos (primeiro link) e realmente não achei nada referente a nota A1 (a estrutura começa na página 100).

Alguma luz sobre isto @robertorp ?

**Comment by robertorp** [comment]
Edit: Desde os primeiros schemas tem NF lá. (versão 1 da mdf-e)
Nesta NT tem a menção do campo em si MDFe_Nota_Tecnica_2013_002.pdf
Outras NT posteriores já mostram o campo.
O engraçado e que na 3.0 já não mostra mais. É nos schemas não tem também.

Fica assim: se quiser posso colocar para você, ou se preferir você mesmo coloca tanto faz para min. Somente agora agora não posso colocar pois estou ocupado passando treinamentos para algumas revendas. (to dizendo isso porque o treinamento é para uma revenda que conseguimos em São Paulo para CT-e é MDF-e) já temos ela em produção em GO é RN.

**Comment by marcosgerene** [comment]
Bom dia @robertorp ,

Não há necessidade de colocar, provavelmente caiu.

Abraços
