### ISSUE TITLE
Correções DANFE NFe e criação de impressão dos eventos

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#306]
Boa tarde @adeniltonbs ,

Fiz as seguintes correções abaixo:

-Correções DANFE NFe - Preenchimento de campos, alinhamentos,  acrescentei impressão das fatura/duplicatas e o nome do desenvolvedor no rodapé.
-Criação de impressão dos eventos (Cancelamento e CCe) - Foi modificada a classe DanfeFrNfe.cs

Não fiz um pull request pois não estou usando o git ainda mas upei os arquivos no dropbox caso tenham interesse.

[Link Dropbox](https://www.dropbox.com/s/w5azh9bbu556yvd/NFe.rar?dl=0)

**Comment by marcosgerene** [comment]
Fiz algumas pequenas correções, mas no meu caso são micro ajustes, se quiser mesclar com os seus e subir tudo junto seria interessante:

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300

**Comment by marcosgerene** [comment]
Bom dia @andersonbrv ,

Vou adicionar suas implentações no meu pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300

Muito obrigado pela colaboração

**Comment by marcosgerene** [comment]
Pode fechar a insue @adeniltonbs
