### ISSUE TITLE
[DUVIDA] Timeout nos serviços 

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#307]
Gente Sempre ao usar um serviço pela primeira vez encontro o erro de timeout. Lembrando que não configuro a senha do certificado. Alguém sabe o porquê?

**Comment by robertorp** [comment]
Configura a propriedade Timeout com um valor maior exemplo..
Timeout = 60000;
O padrão do zeus-nfe é 3000 (appteste)

**Comment by FabioHenriqueMF** [comment]
Opa roberto não acredito que seja a propriedade TimeOut, aliás já alterei ela para 6000.
Esse erro acontece apenas na primeira vez que utilizo um serviço, de "Consultar status do Serviço" por exemplo, mas na segunda vez seleciono o certificado ponho a senha e dá certo normalmente...
Sabe do que se trata?

**Comment by adeniltonbs** [comment]
EM "mas na segunda vez seleciono o certificado ponho a senha e dá certo normalmente...".
Pergunta: Na primeira tentativa, a senha do certificado é solicitada?

**Comment by FabioHenriqueMF** [comment]
Sim é solicitada

**Comment by adeniltonbs** [comment]
E mesmo assim ocorre timeout?

Já tentou acessar a url do serviço diretamente pelo IE, pra ver se o erro não está sendo causado por algum problema de internet/firewall?

**Comment by homerokzam** [comment]
@adeniltonbs ,

Como acesso a url do serviço? Fica em que classe?

Obrigado.

**Comment by adeniltonbs** [comment]
Veja a url diretamente no portal da NFe em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=

Se for NFCe, procure o portal para sua UF. Ex: em SE o portal é http://www.nfce.se.gov.br/
