### ISSUE TITLE
[MDFe] - Ajustes

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#308]
Esta insue se refere à: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/303

**1. UfDestino nas configurações.** -> OK em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300
A uf definida é do EMITENTE e não de destino nas configurações, tanto que se preenche o campo cUF do ide, e segundo a página 98 do manual: "Código da UF do emitente do MDF-e ".

***2. Primeira letra maiuscula***
Aqui pode ser desconsiderado, mas para seguir os padrões do manual e do próprio Zeus para NFe seria interessante usar a primeira letra minuscula nas propriedades, ex: cMDF e não CMDF.

***3. Namespace***
Não consigo entender porque existe 2 namespaces "MDFe" e "ManifestoDocumentoFiscalEletronico".

***4. Salvar em disco*** -> OK em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300
Na função "SalvarXmlEmDisco" seria interessante permitir passar o caminho completo ou usar o padrão.

***5. DFe.Utils, MDFe.Utils e NFe.Utils***
Seria bem interessante um refatoring no projeto para usar o DFe para o que for comum entre os documentos ou separar de vez NFe e MDFe e outros que vierem, alem de corrigir o namespace como está no ítem 3.

***6. CMDFe*** -> OK em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/300
O código da MDFe está como numérico mas ele exige 8 dígitos, logo deveria ser um string, no meu caso eu usp o código o mesmo número do MDFe com zeros a esquerda, visualmente na pasta dos arquivos fica mais fácil encontrar o arquivo visto que ignorando o ultimo dígito temos o número do documento.

-----------------------------

O objetivo desta insue é discutir os ítens 2, 3 e 5.

**Comment by robertorp** [comment]
5. Fiz pensando na unificação já, MDF.Utils tem coisas que não é comum entre os dois projetos. Já o DFe.Utils tem coisas comuns entre os dois projetos NF-e/CT-e (exemplo geração de chave é a mesma, algumas funções de xml , todos eu dei um contrl c é v do projeto Zeus)

**Comment by robertorp** [comment]
Depois que o @adeniltonbs aprovar seus pull vou correr atrás da alteração do namespace do mdfe.classes colocar ele igual os outros, também vou começar a unificar os projetos bem devagar, vai ser assim mudo o código do nf-e de geração de chave.. faço um pull , ao aceitar unifico outra coisa. Processo devagar para não ter erros.

**Comment by marcosgerene** [comment]
Estou fazendo o **3** e a impressão do MDFe

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/332 Faz parte do 3 mas.. qualquer coisa do somente um close rsrs

**Comment by marcosgerene** [comment]
Eu te mando o zip agora então ja feito o 3, ou vc mesmo pode fazer, é dar um replace all e ajustar 2 classes que referenciam diretamente o tipo MDFe,mudei em 5 minutos. 

Vou focar ja na impressão do MDFe enquanto você muda o nome ManifestoDocumentoFiscalEletronico para MDFe. 

Abraço

**Comment by marcosgerene** [comment]
3 e 5 Ok.

2. Deacartado por enquanto
