### ISSUE TITLE
[DÚVIDA] Carta de Correção pede 2 vezes o certificado

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#309]
Mais alguém está com esse problema?
Evento Carta de Correção pede 2 vezes o certificado.

**Comment by robertorp** [comment]
Poderia postar um pedaço do seu código que faz o envio da CCe somente para nos analisar ?

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Boa tarde. Bem observado. No caso do NFe é compreensível que o certificado seja acessado duas vezes. Uma para assinatura do XML e outra para comunicação com a SEFAZ, afinal você pode querer fazer uma das etapas apenas. No caso da carta de correção e inutilização, não tem por que alguém querer somente assinar a solicitação, por isso, vou alterar a biblioteca para acessar o certificado uma única vez, para esses dois serviços.

**Comment by FabioHenriqueMF** [comment]
Muito obrigado Adenilson fico aguardando a correção obrigado. 👍😀

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Já havia sido enviada para o git, antes de sua resposta acima. rsrs.

**Comment by FabioHenriqueMF** [comment]
☺😄👍
