### ISSUE TITLE
NFC-e não aparece no site da Receita

### ISSUE THREAD

**Issue by amiltonmorais** [ZeusAutomacao/DFe.NET#31]
Boa tarde Adenilton

Primeiramente gostaria de parabenizar por este trabalho maravilho que tem a humildade de compartilhar com todos. Sou novato em neste tipo de programação de sistema, mais no que poder ajudar estarei a disposição.

Eu fiz um teste com a NF-e funcionou tudo ok, mais ao fazer teste com NFC-e o lote foi enviado com sucesso mais a nota nao aparece no site da receita.
a chave gerada foi:  35150810484333000197650010000000251000000018
o WebService de consulta foi : https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaPublica.aspx

Tem alguma coisa que precisa fazer?

Segue os dados de retorno

versao = 3.10
tpAmb = taHomologacao
verAplic = SP_NFCE_PL_008
cStat = 103
xMotivo = Lote recebido com Sucesso
cUF = SP
dhRecbto = 03/08/2015 15:45:00
infRec = NFe.Classes.Servicos.Recepcao.infRec

**Comment by adeniltonbs** [comment]
Verifiquei em http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/URLWebServices.aspx se eles haviam mudado os endereços dos serviços e pelo que consta os endereços são os mesmos utilizados pela biblioteca na classe NFe.Servicos.DefinicaoWSDL.

Você chegou a consumir o serviço NFeRetAutorizacao ou NfeConsultaProtocolo para ver o retorno?

Aqui em SE a sefaz tinha deixado a página de consulta pela chave desatualizada, consultando nos endereços antigos, tive que mandar um e-mail para eles corrigirem.

**Comment by amiltonmorais** [comment]
Oi Adenilton

Consegui enviar a nf.  35150810484333000197650010000000011000000016
Oque estava dando erro era o código do município do destinatário ( cMun = 2802908), estava tentado vender para outro estado, mudei para um do mesmo estado e funcionou;

Ai me surgiu uma duvida, e seu o cliente tiver viajando e comprar em outro estado, como funcionaria?
Toda venda sera obrigado a cadastrar o consumidor?

Desculpa esta fazendo esta pergunta.

**Comment by adeniltonbs** [comment]
No manual da NFe versão 6.0, página 193, seção E. "Identificação do Destinatário da Nota Fiscal eletrônica" mostra que o preenchimento do grupo "dest" (Identificação do Destinatário da NF-e) é de preenchimento obrigatório somente para NFe. Para NFCe é opcional. E pela sua mensagem anterior me parece que vc está falando de NFCe. Lembre-se a NFCe substitui o cupom fiscal, e para ele vale as mesmas regras do cupom.O cupom fiscal é um documento para venda de mercadorias a consumidor final, dentro do Estado. No entanto a NFCe é menos restritiva em alguns pontos, a depender da SEFAZ. Leia como estão as regras no portal da NFCe do estado para qual deseja emitir NFCe.

**Comment by amiltonmorais** [comment]
Entendi, muito obrigado pela ajuda.
