### ISSUE TITLE
[DÚVIDA] Donwload XML NFe - Converter gZip

### ISSUE THREAD

**Issue by francofs** [ZeusAutomacao/DFe.NET#310]
Não encontrei nenhum método já implementado que converta o formato gZip compactado para texto XML do download de NF-e. Já está implementado em algum lugar da biblioteca?

**Comment by adeniltonbs** [comment]
@francofs Boa tarde,

A classe que contém métodos para compressão/descompressão é NFe.Utils.Compressao

Nela vais encontrar os métodos Zip e Unzip. 

O serviço, NfeDistDFeInteresse, por exemplo, usa o método Unzip da classe acima, para descompactar o XML dos documentos recebidos.

**Comment by francofs** [comment]
Boa tarde Adenilton, obrigado pelo toque.

**Comment by alsantana** [comment]
Olá @adeniltonbs, boa tarde

Fazendo a descompactação ele retorno para um string o conteudo de cada NF-e localizada, no projeto tem alguma função para capturar esse retorno descompactado direto na classe como carregarxmldastring?

grd abs
