### ISSUE TITLE
[NOTÍCIA] Sefaz-MA atualiza e disponibiliza emissor gratuito de NF-e cedido pela SEFAZ-SP

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#311]
Ja leram a nova... http://portal.sefaz.ma.gov.br/portalsefaz/jsp/noticia/noticia.jsf?codigo=4093

**Comment by adeniltonbs** [comment]
👍

**Comment by robertorp** [comment]
Hmm, se carregasse o site para min ver rsrs

edit: aee abriu rsrs

**Comment by FabioHenriqueMF** [comment]
![image](https://cloud.githubusercontent.com/assets/21219148/21577378/8b1779b0-cf3f-11e6-8652-090d9f74a798.png)

**Comment by robertorp** [comment]
@FabioHenriqueMF 

boa!
