### ISSUE TITLE
[DUVIDA] erro 203 emissor não autorizado porem está autorizado

### ISSUE THREAD

**Issue by ffranzes** [ZeusAutomacao/DFe.NET#313]
Boa tarde, primeiramente gostaria de agradecer por disponibilizar a biblioteca, estou utilizando a mesma para emitir NFC-e no estado do rio de janeiro, implementei o codigo, que esta gerando o arquivo xml e enviando ao servidor normalmente porem estou recebendo o seguinte retorno: erro 203 emissor não autorizado porem entrando no site do sefaz encontro a informação de autorizado e inclusive possuo o CSC. Pode me dar alguma luz de onde possivelmente está o problema? obrigado.

em anexo o xml de envio e de retorno.

![sem titulo](https://cloud.githubusercontent.com/assets/11863920/21581534/2561723c-d01c-11e6-8b5c-f43534f56e85.jpg)
[23-rec - Copia.xml.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/680020/23-rec.-.Copia.xml.txt)
[23-env-lot - Copia.xml.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/680021/23-env-lot.-.Copia.xml.txt)

Obrigado.

**Comment by robertorp** [comment]
Eu acho que o melhor caminho e você ligar na Sefaz. Obs: ali tá escrito que não está habilitado para nfc-e.

**Comment by ffranzes** [comment]
onde está escrito?
Legenda:
simbolo vermelho = não liberado para emissão de NFC-e
porem em baixo todos estão com o simbolo verde... eu sinceramente não sei mais onde procurar... enviando em homologação vai, mas em produção não vai... em anexo envio em homologação
[28-rec.xml.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/680095/28-rec.xml.txt)
[28-env-lot.xml.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/680096/28-env-lot.xml.txt)

**Comment by ffranzes** [comment]
Resolvido: achei em 

Importante: O contribuinte estará apto a emitir a NF-e, após o prazo de até 24h do
deferimento do Contribuinte na ARE VIRTUAL.
> https://www.sefaz.pe.gov.br/Servicos/nota-fiscal-eletronica/Guias%20e%20Procedimentos/NF-e%20%20Guia%20De%20Procedimentos%20(05-08-2015).pdf

após 24horas foi o xml foi aceito e o erro parou de acontecer.
