### ISSUE TITLE
[Dúvida] Bematech 2500th + NFCe + FastReport

### ISSUE THREAD

**Issue by ffranzes** [ZeusAutomacao/DFe.NET#315]
Pessoal, boa tarde, alguém já conseguiu imprimir uma NFCe pelo FastReport gerado no APP teste na impressora Bematech 2500th? creio que o problema não esteja na biblioteca mas nos drivers (ou a falta deles) na maquina alvo. A questão é que já reinstalei varias vezes (os drivers de algumas versoes), e o driver Spooler (1394146486-Impressora_MP-2500TH_Driver_04_Win_BemaSetup_MP4K_v4.2.3) tambem não resolveu. Alguem passou por algum problema parecido? Agradeço a resposta.

**Comment by robertorp** [comment]
Já tentou imprimir através de um bloco de notas? Geralmente faço esse teste antes

**Comment by adrbarros** [comment]
Comigo esta imprimindo normalmente, graças a Deus, porque também tive o mesmo problema com a impressora trabalhando na porta USB, e só resolveu formatando a maquina

**Comment by ffranzes** [comment]
Consegui resolver pessoal, para quem interessar solução para a impressora para mim foi, instalar os drivers disponiveis na bematech 1394146486-Impressora_MP-2500TH_Driver_02_Win_BemaUni_setup_v2.0.8._x86[1] e o driver spooler 1394146486-Impressora_MP-2500TH_Driver_04_Win_BemaSetup_MP4K_v4.2.3[2] , porem so isso n bastou, precisei baixar uma versao do software de usuario versão 2.7.0 (que tive que procurar na web, e so funcionou especificamente com essa versão), e durante a instalação do mesmo, ele sugeriu a atualização do driver, ai passou a funcionar.
em anexo resultado... confirmando entao Bematech 2500 TH funcionando file.

![img_2676](https://cloud.githubusercontent.com/assets/11863920/21620699/c240fb88-d1dc-11e6-828f-8862f3305bd7.JPG)
