### ISSUE TITLE
Erro em cancelamento

### ISSUE THREAD

**Issue by andersonpda** [ZeusAutomacao/DFe.NET#317]
Estou tentando cancelar nota em homologação está dando seguinte erro de SLL/TLS.
![untitled](https://cloud.githubusercontent.com/assets/3709304/21632028/1da7055c-d229-11e6-8813-3ed201477792.png)

**Comment by adeniltonbs** [comment]
Tente acessar a url do serviço diretamente no navegador, e selecione o certificado. Se o erro ocorrer, o problema pode estar no certificado ou no serviço de cancelamento dessa SEFAZ. Se não ocorrer no navegador, pode ser que a SEFAZ tenha mudado o protocolo de segurança. Assim, na aplicação de teste da biblioteca, mude o protocolo de segurança, na opção abaixo:
![image](https://cloud.githubusercontent.com/assets/6733483/21642613/431a4dc4-d262-11e6-8a8a-18ef516086a7.png)

**Comment by andersonpda** [comment]
ja tinha testado com 2 protocolos e deu o mesmo erro.
Acessei também pelo navegador onde mesmo me pediu p selecionar certificado e carregou normalmente.

Testei envio de NFe e foi normal, autorizou certinho, somente cancelamento não está acontecendo.

![image](https://cloud.githubusercontent.com/assets/3709304/21644652/a1039e78-d275-11e6-9216-362aec9f7ed9.png)

**Comment by andersonpda** [comment]
@adeniltonbs descobri o que era, o método assinador no cancelamento estava efetuando um .reset() logo após assinar o XML, vi que classe NFeServicos possui implementa método Dispose() que tmb está fazendo um .reset() para certificado, seria correto manter apenas nessa classe o reset() ?.

**Comment by adeniltonbs** [comment]
Entendi. Vou encaminhar uma correção.

**Comment by adeniltonbs** [comment]
Correção enviada. Poderia testar e informar se o problema foi resolvido?

**Comment by andersonpda** [comment]
sim, consegui fazer sem erro agora.
