### ISSUE TITLE
[NUGET] NFe - Erro The underlying connection was closed ao emitir nota nas versões 406 e 380

### ISSUE THREAD

**Issue by douglasPinheiro** [ZeusAutomacao/DFe.NET#318]
Nas versões do pacote nuget 1.0.1.406 e 1.0.1.380 quando eu tento emitir uma nota atravez do método NFeAutorizacao, recebo a seguinte exception:

Falha na rede internet:
The underlying connection was closed: An unexpected error occurred on a receive.

Obs: até a versão1.0.1.357 a emissão estava funcionando, mas atualizei porque estava tendo outro problema, que eu creio que foi corrigido na nova versão

**Comment by robertorp** [comment]
Máximo que posso fazer é atualizar o nuget novamente , confira a versão das DLLs todas elas devem estar na mesma versão

**Comment by robertorp** [comment]
Quando chegar na cidade estarei atualizando ela para os últimos commits

**Comment by douglasPinheiro** [comment]
Elas estão todas na mesma versão

**Comment by robertorp** [comment]
Então se você voltar para o commits número 406 do Zeus ele tá com erro também, pode ser que já foi corrigido nos mais atuais , chegando em casa eu atualizo as DLLs do nuget.

**Comment by robertorp** [comment]
Eu lendo sobre o erro também achei isso.

Obs: a DLL foi atualizada.

http://stackoverflow.com/questions/21728773/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receiv

**Comment by douglasPinheiro** [comment]
Ja tinha testado essa solução e não funcionou, continua com o mesmo erro.
Ha e atualizar o pacote para o 417 tambem não funcionou.

**Comment by robertorp** [comment]
Olha testei aqui agora com a DLL simplesmente eu deletei as referencias do APP teste.. e adicionei as DLL do nuget lá (adicionei referencia para o nuget)

Mandei um cria e envia 3.0

codigo do app teste

`var numero = Funcoes.InpuBox(this, "Criar e Enviar NFe", "Número da Nota:");
                if (string.IsNullOrEmpty(numero)) throw new Exception("O Número deve ser informado!");

                var lote = Funcoes.InpuBox(this, "Criar e Enviar NFe", "Id do Lote:");
                if (string.IsNullOrEmpty(lote)) throw new Exception("A Id do lote deve ser informada!");

                _nfe = GetNf(Convert.ToInt32(numero), _configuracoes.CfgServico.ModeloDocumento,
                    _configuracoes.CfgServico.VersaoNFeAutorizacao);
                _nfe.Assina(); //não precisa validar aqui, pois o lote será validado em ServicosNFe.NFeAutorizacao
                //A URL do QR-Code deve ser gerada em um objeto nfe já assinado, pois na URL vai o DigestValue que é gerado por ocasião da assinatura
                //_nfe.infNFeSupl = new infNFeSupl() { qrCode = _nfe.infNFeSupl.ObterUrlQrCode(_nfe, _configuracoes.ConfiguracaoCsc.CIdToken, _configuracoes.ConfiguracaoCsc.Csc) }; //Define a URL do QR-Code.
                var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);
                var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List<Classes.NFe> {_nfe}, false/*Envia a mensagem compactada para a SEFAZ*/);
                //Para consumir o serviço de forma síncrona, use a linha abaixo:
                //var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Sincrono, new List<Classes.NFe> { _nfe }, true/*Envia a mensagem compactada para a SEFAZ*/);

                TrataRetorno(retornoEnvio);`


ele enviou e retornou.. 
preciso de mais detalhes do seu envio para testar e chegar no mesmo erro

xml de envio é retorno da consulta recibo 
[xml envio e retorno consulta recibo.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/687320/xml.envio.e.retorno.consulta.recibo.txt)

servidor de homologação/goiás

edit: Se você ta dando erro, outros estão também, e ninguém reclamou ainda isso é oque torna seu erro estranho o nuget não é somente você que atualiza, se você olhar lá vai ver que tem muitos downloads nas versões e ninguém reclamou alem de você. Logo diante disso minha suspeita e que o erro ta somente no seu código (não to afirmando e somente uma suspeita). Lembrando que acabei de usar o app teste do Zeus.. eu deletei as referencias dele e fiz uma referencia pelo nuget ou seja.. utilizei as DLL's do nuget e emitiu. O código de emissão esta ai.

edit2: utilizei tls

**Comment by douglasPinheiro** [comment]
Desculpa, foi erro meu, eu tinha esquecido de definir o protocolo de segurança na configuração do serviço.
E como até o pacote versao 1.0.1.357 nao precisava eu não tinha esse problema, definindo o protocolo de segurança como tls funcionou corretamente.
Obrigado!
