### ISSUE TITLE
Usar a DLL com Visual Basic 6

### ISSUE THREAD

**Issue by SistemaRural** [ZeusAutomacao/DFe.NET#320]
olá Adenilton, bom dia!

Essa sua DLL, eu consigo utilizar ela com VB6?

Valdiney

**Comment by adeniltonbs** [comment]
@SistemaRural A biblioteca foi desenvolvida para .NET, logo não funcionará no VB6. No entanto você poderá integrar sua aplicação com a biblioteca usando o facade https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.Integracao.

**Comment by SistemaRural** [comment]
Adenilton, não entendi sobre o facade....se puder explicar melhor sobre essa biblioteca.

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Integracao/Program.cs

Linha 260 inicia o help da aplicação

![helpaplicacao](https://cloud.githubusercontent.com/assets/10251705/21947961/3197cfbc-d9cf-11e6-9fb2-81585877859c.png)
