### ISSUE TITLE
[DUVIDA] Exceções para erros de Certificados? The request failed with HTTP status 403: Forbidden

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#321]
Boa tarde galera.
Estava fazendo apenas um teste utilizando um certificado não válido (alterei o sistema para demostrar todos os certificado, até os expirados) e tentei transmitir uma NF-e. Porem ele entrou na exceção (cono já esperado) "WebException" criando a Exceção "ComunicacaoException" com o erro abaixo:

![image](https://cloud.githubusercontent.com/assets/21219148/21688522/53bc8d66-d354-11e6-9615-e12609b2fb39.png)

Porem o erro The request failed with HTTP status 403: Forbidden se refere a um erro de autenticidade de certificado e não de Comunicação.
Ou estou enganado?

**Comment by andrebts** [comment]
Boa tarde Fabio.
O erro 403 se encaixa na categoria de comunicação, como pode ser amplamente verificado facilmente na internet. O erro aconteceu, provavelmente, poque o certificado não válido utilizado no teste tentou acessar algum recurso da Sefaz e por sua vez este não foi permitido. A Sefaz, assim, retornou esse erro. Não é um erro de autenticidade, pois o certificado, embora não mais válido, é fidedigno às regras da legislação regulatória.

**Comment by adeniltonbs** [comment]
Complementando, o problema nesse caso @FabioHenriqueMF é que se o webservice estiver off ou retornar problema qualquer de comunicação, como o que você reportou, o .NET vai devolver ambos como WebException. Nesse caso a biblioteca traduz todo WebException para ComunicacaoException. Só daria para fazer algo diferente disso se fosse tratada a string do erro.

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF Dê uma olhada no commit 1329fc0e1ab43fbc7783ab983e4c47d0f0f01e4d.
