### ISSUE TITLE
[SUGESTÃO] Substituir DateTime.Now por parâmetros

### ISSUE THREAD

**Issue by krgm03** [ZeusAutomacao/DFe.NET#322]
Boa tarde!

Quero deixar uma sugestão diante de um problema que enfrentei. Há dentro de alguns métodos a requisição de DateTime.Now e isso pode ser um problema em alguns casos. Por exemplo no meu aplicativo que fica hospedado no Azure ou AWS o usuário quem define sua localização(Fuso Horário). Portanto devo passar a data e hora atuais de acordo com o que usuário definiu e não posso chamar DateTime.Now. Para resolver bastaria ter um parâmetro no método para qual iremos passar o valor. 
A sugestão é a troca de todos os DateTime.Now...

Na oportunidade gostaria de saber como posso entrar no skype do grupo

Obrigado

**Comment by francofs** [comment]
Sugestão, coloque a chave no seu web.config:

<add key="WEBSITE_TIME_ZONE" value="E. South America Standard Time" />

Isso resolveria a questão de timezone da aplicação azure, com o horário de
Brasília. Se você precisa lidar com múltiplos timezones, aí realmente a
solução é ser parametrizado para que você possa trabalhar com UTC.

2017-01-05 17:34 GMT-02:00 Kleber Martins <notifications@github.com>:

**Comment by krgm03** [comment]
Boa tarde, a sugestão 'coloque a chave no seu web.config' realmente não funciona para o meu caso

Fica a sugestão para futuras versões
