### ISSUE TITLE
[URGENTE] - Certificado A1

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#326]
Estou com o seguinte problema com o certificado A1:

A cadeia de caracteres não estava em um formato incorreto.

Exatamente assim, escrito inclusive de forma equivocada (não estava incorreto).

Até então estava funcionando, não sei dizer em qual versão parou, mas não consigo mais fazer rodar aqui

**Comment by marcosgerene** [comment]
Fiz um teste na minha máquina com outro A1 e no método assinar recebo "Tipo inválido especificado."

**Comment by ydmeira** [comment]
Verifica se você não está passando a senha do certificado como parâmetro. No A1 a senha não deve ser passada, caso seja um certificado instalado.

**Comment by marcosgerene** [comment]
O problema do meu teste Tipo inválido especificado resolveu tirando a senha, entretanto o problema no cliente continuou

**Comment by marcosgerene** [comment]
Deu certo, o problema era uma string em branco que eu tentei convert para long sem try catch, tive que pegar o banco do cliente para testar, o certificado A1 não tinha nada a ver com a história, somente aconteceu de eu não conseguir enviar do meu PC por causa dele e meu cliente ter A1 também.
