### ISSUE TITLE
Classe NFe - XmlRoot

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#33]
Bom dia Adenilton,
Estou gerando uma nfc-e e o arquivo xml é recebido com sucesso, mas na consulta ele da o seguinte erro: Falha no schema XML. org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 6; cvc-elt.1: Cannot find the declaration of element 'NFe'. ao observar o arquivo a tag NFe esta sem a declaracao: http://www.portalfiscal.inf.br/nfe. O XmlRoot esta declarado normalmente na classe mas nao gera no arquivo.

**Comment by adeniltonbs** [comment]
Não detectei o problema aqui.
Testei no aplicativo de demonstração que acompanha a biblioteca, utilizando o ambiente de homologação da SEFAZ Virtual do RS.

Segue a tela:
![image](https://cloud.githubusercontent.com/assets/6733483/9261172/a9d12e64-41e2-11e5-93b0-2d271b87e62e.png)

Dica: Teste este recurso no aplicativo que acompanha a biblioteca, e se o erro ocorrer, por favor detalhe melhor como ele aconteceu (a UF, o ambiente e a chave da NFe) para eu poder te ajudar.

**Comment by vasisti** [comment]
Ola Adenilton, boa noite, grato pelo retorno.
Eu baixei o projeto atualizado e gerei novamente a NFc-e mas ainda nao deu certo, a tag NFe ainda sem a declaração conforme descrito acima. Estou usando o Web Service do PR, no ambiente de Homologação, segue a chave: NFe28150822354114000172650010000001001000012340
segue algumas imagens:
Sem mais Valdir, abraços.
![image](https://cloud.githubusercontent.com/assets/10574426/9265193/4e463368-4206-11e5-9a58-88f9db93fb8b.png)

![image](https://cloud.githubusercontent.com/assets/10574426/9265199/6881d7e6-4206-11e5-8df5-8d8101f58111.png)

![image](https://cloud.githubusercontent.com/assets/10574426/9265200/7769ee9c-4206-11e5-9c7b-254a944b4fe0.png)

![image](https://cloud.githubusercontent.com/assets/10574426/9265204/85710a52-4206-11e5-89ec-06ce57b88ba9.png)

![image](https://cloud.githubusercontent.com/assets/10574426/9265207/94361834-4206-11e5-8d48-57b8b91eaf31.png)

**Comment by adeniltonbs** [comment]
Desculpa a demora, mas estive muito ocupado esses dias.
Testei o caso que você relatou utilizando a SEFAZ do PR e constatei o problema que você relatou.
O problema não está acontecendo por conta da ausência do xmlns no grupo NFe, e sim por que a SEFAZ do PR, não sei por que cargas d'água, está validando o lote com o schema nfe_v3.10.xsd ao invés de usarem o schema enviNFe_v3.10.xsd. Eles deveriam perceber que você está enviando um lote, detectando a presença do grupo enviNFe no XML e validar o xml com o schema correto como todas as outras SEFAZes fazem. Para vc poder ter certeza que não há nada de errado com o XML gerado pela bibioteca, pegue o xml de envio, conforme imagem abaixo e submeta-o à validação em https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx

Recomendo você entrar em contato com a SEFAZ do PR pelos telefones informados em http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97.

Eu mesmo já tive problemas com a SEFAZ de SE e eles resolveram prontamente.

Se quiser reproduzir o erro, tente validar o xml de envio de lote com o schema nfe_v3.10.xsd que você vai ver o mesmo problema.

Quaisquer dúvidas poste aqui.

![image](https://cloud.githubusercontent.com/assets/6733483/9348496/31c82604-460e-11e5-8ddb-7eb75483d9b4.png)

**Comment by fbichara** [comment]
Olá pessoal,

Eu tive o mesmo problema e resolveu colocando no xml de envio (autorização) o namespace na tag Nfe.

De:
NFe

Para:
NFe xmlns="http://www.portalfiscal.inf.br/nfe" 

Apesar de dar o erro quando fazemos a consulta (motivo), a origem é no envio da autorização.

Até agora só o PR exigiu isso, mas só testei no RJ por enquanto.

Abs,
Fernando

**Comment by adeniltonbs** [comment]
fermaster, mesmo assim é estranho o fato de você enviar o xml  `<enviNFe>` com o namespace "http://www.portalfiscal.inf.br/nfe" e a SEFAZ exigir que você informe o mesmo namespace nos elementos `<NFe>`.

Só faz sentido ter mais de um namespace no xml se determinada classe em específico tem sua estrutura definida em outro namespace. Como isso não ocorre no grupo `<NFe>` que possui o mesmo namespace de `<enviNFe>` ("http://www.portalfiscal.inf.br/nfe"), o namespace para `<NFe>` não deve ser informado.

Você pode obter mais informações sobre namespaces em xml aqui: http://www.w3schools.com/xml/xml_namespaces.asp

Para resumir, se o namespace é definido no elemento root do xml, ele só será definido em algum elemento filho se este tiver um namespace diferente do root. Veja o exemplo do elemento `<Signature>`, que possui um namespace diferente: "http://www.w3.org/2000/09/xmldsig#" e por isso é informado no elemento `<Signature>`.

Para mim esse erro só deveria ocorrer se a SEFAZ estiver tentando validar o xml enviNFe com o schema nfe_vX.XX.xsd

**Comment by fsbflavio** [comment]
adeniltonbs

Primeiramente parabéns pelo projeto! :D, pretendo implementar as impressões no Cristal e espero poder contribuir de alguma forma.

Quanto ao problema acima

Tentei o contato com a sefaz-pr mas não é fácil passar abrir um chamado direto a área técnica.. :|

fermaster,

o que vc fez foi simplesmente colocar o namespace?

disso:
<textarea><enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>10</idLote><indSinc>0</indSinc><NFe><infNFe versao="3.10" Id="NFe28150908337259000134550010000000101000012348"><ide><</textarea>

para isso:
<textarea><enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>10</idLote><indSinc>0</indSinc><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="3.10" Id="NFe28150908337259000134550010000000101000012348"><ide><</textarea>

?

Obrigado!

**Comment by vasisti** [comment]
Ola, sobre a duvida acima, resolvi no caso da sefaz do PR, Na classe NFE.Servicos, no Metodo NFeAutorizacao coloquei a sequinte linha:

/****************
            xmlEnvio = xmlEnvio.Replace("<NFe>", "<NFe xmlns=\"http://www.portalfiscal.inf.br/nfe\">");
/*****************
            Validador.Valida(ServicoNFe.NFeAutorizacao, TipoRecepcaoEvento.Nenhum, _cFgServico.VersaoNFeAutorizacao, xmlEnvio);
            var dadosEnvio = new XmlDocument();
            dadosEnvio.LoadXml(xmlEnvio);
dai a nota foi autorizada sem problemas.
Abraços
Valdir

**Comment by vasisti** [comment]
enviando uma imagem: para melhor visualizacao:
![sem titulo](https://cloud.githubusercontent.com/assets/10574426/9794856/e3ff4e26-57c3-11e5-9493-609ef22c362d.png)

**Comment by adeniltonbs** [comment]
Com base na sugestão de vasisti, vou subir a seguinte alteração, no método NFeAutorizacao, para a biblioteca:

Trocando o trecho:

``` cs
var xmlEnvio = pedEnvio.ObterXmlString();
Validador.Valida(ServicoNFe.NFeAutorizacao, TipoRecepcaoEvento.Nenhum, _cFgServico.VersaoNFeAutorizacao, xmlEnvio);
```

Para:

``` cs
var xmlEnvio = pedEnvio.ObterXmlString();
if (_cFgServico.cUF == Estado.PR) //Caso o lote seja enviado para o PR, colocar o namespace nos elementos <NFe> do lote, pois o serviço do PR o exige, conforme https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/33
xmlEnvio = xmlEnvio.Replace("<NFe>", "<NFe xmlns=\"http://www.portalfiscal.inf.br/nfe\">");
Validador.Valida(ServicoNFe.NFeAutorizacao, TipoRecepcaoEvento.Nenhum, _cFgServico.VersaoNFeAutorizacao, xmlEnvio);
```

**Comment by adeniltonbs** [comment]
Pronto, sugestão incluída no commit 1cfa54626c7347a6c4bcd77db3de698afb57258c.
Favor testar fsbflavio.

**Comment by fsbflavio** [comment]
Perfeito, deu certo :D 

vlw vasisti!

blz adeniltonbs!

**Comment by adeniltonbs** [comment]
Ok, vou fechar o issue.
