### ISSUE TITLE
Impressão MDFe

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#335]
Gostaria de desenvolver a impressão do MDFe mas não sei como registrar o objeto mdfe no fast report, alguém pode me dar o arquivo .frx somente com o xml já "registrado" para eu montar o layout?

Abraços

**Comment by robertorp** [comment]
Somente uma ideia, nunca mexi no fastreports por motivos de falta de conhecimento hehe, digo falta de conhecimento nessa mesma questão sua do post.. conectar na base de dados vai.. agora fazer um objeto virar o dados.. não saquei nada hehe, então a ideia é poderia ter um tutorial aqui mesmo

**Comment by rftd** [comment]
Basta instancia uma classe Report do FastReport e adicionar um DataSource e depois chamar o designer. 
Ex.: 
Report.RegisterData(new[] { mdfe }, "MDFe");
Report.Design();

**Comment by marcosgerene** [comment]
@rftd ,

Obrigado pela dica!

**Comment by marcosgerene** [comment]
Boa noite @rftd, @robertorp e @adeniltonbs ,

Segue projeto atual, analisem o PDF por favor e me digam se está dentro das normas.

[MDFeRetrato.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/703908/MDFeRetrato.zip)


Abraços

**Comment by robertorp** [comment]
se tiver mais de um município?

obs: não sou experiente com o fastreports então vejo somente o pdf

**Comment by marcosgerene** [comment]
O municipio é o detalhe, o que ta em baixo são subreports, vai imprimir o outro municipio com seus documentos em baixo

PS: Removi o pdf porque havia informações minhas e do cliente.

**Comment by marcosgerene** [comment]
@robertorp ,

Segue em anexo os fontes com o nome Manifesto... trocado para MDFe e a impressão em frx, so tem um projetinho mdfe.damdfe.fast com uma tela e um botão teria que fazer as configs e tal, mas não sei se no seu projeto de refatoring está a junção da parte de impressão.

Obs: a impressão já usa o namespace alterado para MDFe.

[zeus_mdfe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/703943/zeus_mdfe.zip)

Estou no aguardo de você liberar o refatoring da junção dos projetos e as classes do CTe (precisa da junção antes para não alterar o namespace) para fazer a impressão do CTe e eventos, assim teremos o componente para NFCe, NFe, CTe e MDFe atendendo tudo, inclusive impressão dos documentos.

Abraço

**Comment by robertorp** [comment]
@adeniltonbs  teria como olhar os commit que eu fizer juntando os projetos? Para nos estarmos colocando isso o mais rápido possivel

@marcosgerene  Unica coisa que fiz ainda refatorando foi isso https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/332

Quero fazer um pull de cada vez para facilitar para o @adeniltonbs  a conferência do mesmo.
Ai fico na pendencia de espera do mesmo

**Comment by marcosgerene** [comment]
Sem crise, assim que tiver no jeito ja faço a impressão do CTe, vamos eliminar as dependências externas para impressão!

**Comment by marcosgerene** [comment]
@robertorp ,

Vi que fez o pull da mudança de nomes, você vai unificar algo nas configurações da impressão?

Aguardo a resposta para já soltar a classe do fast e a impressão em si do MDFe.

Abraço

**Comment by robertorp** [comment]
Assim no meu ponto de vista eu acho que pode deixar as impressões individual de cada projeto, mas vocês decidem a melhor forma que acharem. Porque impressão seria tipo parâmetro tamanho de fonte, qual fonte usar por ai eu imagino. Então pode soltar a classe do fast report em impressão não vou mexer, somente irei fazer update se vocês pedirem na parte de impressão.

**Comment by marcosgerene** [comment]
Bom dia @robertorp ,

Estou sem meu celular hoje, vou ter que correr na cidade vizinha para arrumar. Ainda essa semana faço o projeto classe base e o .fast se for o caso.

O que eu estava pensando era em juntar o base da impressão para coisas como logotipo, impressora, se vai mostrar o preview, etc não ser duplicado, mas não é nada de outro mundo,  o jeito que a comunidade achar melhor ta valendo.

Abraços

**Comment by marcosgerene** [comment]
Boa noite @robertorp,

Segue a impressão em retrato com os 3 projetos (base, fast e appteste)

[impressao_mdfe..zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/706972/impressao_mdfe.zip)

Ja criei as propriedades Cancelado, Encerrado e Desenvolvedor mas ainda não fiz no desing, mas isso é coisa rápida.

Sobre o que disse antes, fazendo as classes achei que juntar pelo menos a base das impressões seria interessante, documento cancelado, logomarca, etc serão usados para tudo.

Bem, de qualquer forma segue separado para analise e commit, não vou fazer o pull pq não sei no que você mexeu, então com isso você pode tester já com suas modificações.

Abraços

**Comment by marcosgerene** [comment]
@robertorp pegou os projetos acima?

**Comment by robertorp** [comment]
@marcosgerene Opá, ainda não ontem não mexi no projeto. Hoje mexo, quer que faça pull dele hoje? Se quiser pode fazer também porque oque mexi no projeto até agora ta tudo no repositório principal, eu espero o @adeniltonbs aceitar o pull de boa

**Comment by marcosgerene** [comment]
Pode dar o commit, não tenho pressa, só perguntei pq vi outros posts seus e não tinha respondido aqui ai estranhei.

Abraços
