### ISSUE TITLE
NFCe Offline

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#336]
Como funciona a emissão offline do nfce? qual a forma de enviar no componente?

**Comment by robertorp** [comment]
Troca o tipo emissão, tpEmis para offline `TipoEmissao.teOffLine;`
ide.dhCont data em que entrou em contingência
ide.xJust Justificativa por ter entrado em contingência

Manda emitir que o componente irá emitir offline 

Ao emitir NFC-e offline você não pode alterar valores, e nada que envolva a alteração da chave de acesso.
Motivo o cliente pega uma NFC-e offline ele já esta com a chave de acesso, quando o cliente acessar a chave na sefaz ele vai desejar achar ela lá, se não achar o estabelecimento esta sujeito a multa ou sei lá oque a sefaz aplica sobre o estabelecimento.

Um dia liguei na sefaz de goiás e perguntei oque faria se um cliente ficasse sem transmitir as NFc-e offline dentro do prazo vigente (24 horas aqui em goiás), eles me disseram que o cliente deveria resolver isso junto a sefaz (o pior e que me falaram que deveriam ir pessoalmente)

Na internet quando foi fazer o meu achei em muitos lugares que eles recomendavam mudar a serie para emitir em offline para ter menos riscos de dar duplicidade de nfc-e (nunca deve dar)

Dica: já que tem essas regras da sefaz de 24 horas, no meu sistema é automático o envio, se tiver alguma nfc-e offline na minha base que não foi transmitida, com uma thread eu envio todo e mando feedback para o cliente sobre o envio. (Tenho um botão para envio manual também)

**Comment by marcosgerene** [comment]
@robertorp ,

Vou começar só agora a implementação, como posso testar se devo tentar offline ou se o erro foi por falta de conexão?

**Comment by robertorp** [comment]
Olha, aqui na nossa aplicação nos não testamos, não deixamos isso automático, mas acho que no appexemplo do zeus tem uma exception pra isso (eu acho que vi uns dias atrás isso em alguma issue)

Agora aqui no nosso sistema funciona assim, o cliente tenta emitir não consegue, não consegue (mando exception dizendo que o problema talvez pode ser na rede/internet/sefaz/certificado)
 
Ou seja.. temos o problema pode ser rede/internet/SEFAZ/certificado 

Logo então mando somente a mensagem, no nosso sistema aqui temos uma opção que fica no lugar do menufiscal das ecf.. "Entrar em contingência" lá o cliente define o motivo e fecha a tela.. todas próximas nfc-e que ele emitir vai sem em modo contingência offline.

Se o cliente fechar o sistema e no outro dia abrir o sistema, na hora que ele efetuar o login o sistema emite um aviso para ele dizendo que está em contingência (Adicionei o aviso para que o mesmo não esqueça de transmitir as nfc-e offline)

A transmissão de nfc-e offline no sistema nosso e feito de duas maneiras, a primeira e quando ele retira da contingência o sistema tenta fazer o envio das nfc-e de 15 em 15 minutos , se conseguiu fazer tudo o sistema manda um aviso igual o do github no canto la em cima (faço um ícone de sino) o cliente clica lá,  abre um dialog com a mensagem do sistema "20 NFC-e Offline foram transmitidas para a sefaz com sucesso" 

Ou se der erro.. "NFC-e com erro: Rejeição bla bla bla bla"

A segunda opção e um botão perto do botão de entrar em contingência, Sincronizar NFC-e offline..
o força a execução da rotina de 15 em 15 minutos.. (a mesma rotina)

Aqui decidimos deixar manual por hora, motivo o cliente deve saber oque ta ocorrendo, o cliente deve saber quando ta em contingência e quando não está (nos pensamos assim quando fizemos assim)

Mas vai de local para local de pensamento para pensamento hehe

**Comment by marcosgerene** [comment]
No meu caso se trata de um PDV de supermercado, e para piorar a situação tem casos em que a emissão é centralizada em um servidor, ou seja, o PDV requisita, entra numa fila de processamento e o servidor retorna após processado.

-----------

Ja iniciei o tratamento, peguei o exception, o que muda na emissão offline? Quando tento pegar este retorno:

```
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });
```

Ele retorna a mesma excessao da nfce com emissão normal

O xml: 
[nfe_off_validado.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/735712/nfe_off_validado.zip)

-----------
Cheguei a seguinte conclusão:

caso da emissão offline eu não devo "transmitir offline". mas somente assinar e imprimir, ao voltar a comunicação com o sefaz ai sim transmito.

Entretanto isto não bate com o que você disse @robertorp 

> Troca o tipo emissão, tpEmis para offline TipoEmissao.teOffLine;
>ide.dhCont data em que entrou em contingência
>ide.xJust Justificativa por ter entrado em contingência
> ***Manda emitir que o componente irá emitir offline***

Eu devo ou não mandar transmitir/emitir?

----------

A resposta está aqui: www.projetoacbr.com.br/forum/topic/16267-nfce-e-conting%C3%AAncia-off-line/?do=findComment&comment=101069

Esta é a conclusão final:
>caso da emissão offline eu não devo "transmitir offline". mas somente assinar e imprimir, ao voltar a >comunicação com o sefaz ai sim transmito.

Obrigado e abraços

**Comment by marcosgerene** [comment]
Ja iniciei o tratamento, peguei o exception, o que muda na emissão offline? Quando tento pegar este retorno:

```
var retorno = servicoNfe.NFeAutorizacao(lote, NFe.Classes.Servicos.Tipos.IndicadorSincronizacao.Assincrono, new List<NFe.Classes.NFe>() { _nfe });
```

Ele retorna a mesma excessao da nfce com emissão normal
