### ISSUE TITLE
Falha ao Transmitir NFe

### ISSUE THREAD

**Issue by AllanDavini** [ZeusAutomacao/DFe.NET#338]
Após atualizar o projeto para a ultima versão do zeus ao tentar transmitir uma venda recebo o seguinte erro..

Falha na rede internet:
A conexão subjacente estava fechada: Erro inesperado em um recebimento.

Algum possível motivo ou solução ?

**Comment by marcosgerene** [comment]
Defina o protocolo de envio, tenta com SSL3

**Comment by adeniltonbs** [comment]
@AllanDavini Conseguiu resolver?

**Comment by AllanDavini** [comment]
Acabei de conseguir, muito obrigado! @marcosgerene @adeniltonbs
