### ISSUE TITLE
using no FastReports

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#339]
Estou desenvolvendo a impressão para MDFe, esbarrei agora nas usings, coloco a using mas recebo "O nome de namespace "MDFe" não pode ser encontrado. Precisa de uma diretiva using ou de uma referencia assembly?"

Como proceder?

**Comment by rftd** [comment]
Tem que referencia as dlls no report para usar ela la dentro.
La no seletor de componente do designer vai em report e la em referenced assemblies e adicione os nomes das assembles la precisa ser todas inclusives as dependencias da assembluy referenciada.

**Comment by marcosgerene** [comment]
aonde ? 
![menu](https://cloud.githubusercontent.com/assets/15945003/21906357/c7ebfbe6-d8e9-11e6-8103-7891bcd09175.png)

**Comment by marcosgerene** [comment]
Achei, quando eu crescer quero ser igual você =D

**Comment by marcosgerene** [comment]
![atual](https://cloud.githubusercontent.com/assets/15945003/21906525/6511ca36-d8ea-11e6-8634-4bbe72c6a841.png)

Tamo evoluindo!
