### ISSUE TITLE
Classe NFe - XmlRoot

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#34]
Ola adenilton boa noite, eu fiz varios testes mas realmente o xml gera sem o atributo na tag NFe, eu te enviei as telas para analise.
exemplo:
erro:<NFe><infNFe versao="3.10".....
um xml normal:<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="3.10".......
obs: gerei um xml e coloquei o atributo manualmente e enviei o arquivo e o lote foi aceito e autorizada normalmente.
sem mais. grato
Valdir.

**Comment by adeniltonbs** [comment]
Desculpa a demora, mas estive muito ocupado esses dias.
Testei o caso que você relatou utilizando a SEFAZ do PR e constatei o problema que você relatou.
O problema não está acontecendo por conta da ausência do xmlns no grupo NFe, e sim por que a SEFAZ do PR, não sei por que cargas d'água, está validando o lote com o schema nfe_v3.10.xsd ao invés de usarem o schema enviNFe_v3.10.xsd. Eles deveriam perceber que você está enviando um lote, detectando a presença do grupo enviNFe no XML e validar o xml com o schema correto como todas as outras SEFAZes fazem. Para vc poder ter certeza que não há nada de errado com o XML gerado pela bibioteca, pegue o xml de envio, conforme imagem abaixo e submeta-o à validação em https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx

Recomendo você entrar em contato com a SEFAZ do PR pelos telefones informados em http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97.

Eu mesmo já tive problemas com a SEFAZ de SE e eles resolveram prontamente.

Se quiser reproduzir o erro, tente validar o xml de envio de lote com o schema nfe_v3.10.xsd que você vai ver o mesmo problema.

Quaisquer dúvidas poste aqui.

![image](https://cloud.githubusercontent.com/assets/6733483/9348496/31c82604-460e-11e5-8ddb-7eb75483d9b4.png)
