### ISSUE TITLE
Emissão NFCe assíncrona

### ISSUE THREAD

**Issue by guidi** [ZeusAutomacao/DFe.NET#345]
Amigos, boa noite,

a minha questão é apenas uma dúvida e não um erro, como os amigos estão tratando a questão da verificação de autorização na emissão de NFCe de forma assíncrona? 

Estou pensando em depois de enviar, fazer um loop de no máximo 5 segundos consultando o protocolo para saber se ela foi autorizada, não sei se essa alternativa é a mais otimizada, se possível gostaria de sugestões e desde já agradeço pela ajuda.

**Comment by francofs** [comment]
O serviço que retorna o protocolo também retorna o tempo médio de retorno
do processamento. Você pode usar esse retorno para consultar a resposta.
Faça um loop baseado nesse parâmetro.

2017-01-16 18:43 GMT-02:00 Vanderson Guidi <notifications@github.com>:

**Comment by robertorp** [comment]
Não rola de emitir síncrono não ? Aqui usamos assim na nfc-e, até hoje não tivemos problemas.

**Comment by guidi** [comment]
@robertorp tentei mudar pra envio síncrono mas está acontecendo um erro que parece o do #134 

`<retConsReciNFe xmlns='http://www.portalfiscal.inf.br/nfe'>` não era esperado.

**Comment by guidi** [comment]
@francofs  legal, não sabia dessa possibilidade, obrigado pelo aviso.

**Comment by guidi** [comment]
Adotei uma solução baseada na sugestão do @francofs, loop com tempo médio + 2, obrigado pela ajuda.

**Comment by marcosgerene** [comment]
@guidi pode postar um pedaço do código para que eu possa estudar e implementar também? 

Obrigado

**Comment by guidi** [comment]
@marcosgerene desculpe pela demora, segue o código abaixo, usei como referência o tempo médio conforme citado pelo @francofs  e uma opção de configuração do meu sistema onde o cliente configura o número maximo de tentativas.

```
            var tempo = 0;
            var maximoTentativas = ConfiguracaoNFCe.NumeroMaximoTentativasEnvio;
            var contadorTentativas = 0;

            if (retornoEnvio.Retorno.infRec != null)
            {
                tempo = retornoEnvio.Retorno.infRec.tMed + 2;
            }

            var startTime = DateTime.UtcNow;

            RetornoNfeConsultaProtocolo retornoConsulta = null;

            //Consulta pelo protocolo até obter os dados da autorização
            while (DateTime.UtcNow - startTime < TimeSpan.FromSeconds(tempo) || contadorTentativas < maximoTentativas)
            {
                retornoConsulta = servicoNFe.NfeConsultaProtocolo(Sessao.Instance.VendaAtual.ChaveAcesso + Sessao.Instance.VendaAtual.DigitoChaveAcesso);
                contadorTentativas++;

                if (retornoConsulta.Retorno.protNFe != null)
                {
                    break;
                }
            }

            //217 = NF-e não consta na base, em teoria o loop acima neste caso não teria enviado a nfce
            if (retornoConsulta.Retorno.cStat == 217)
            {
                SalvarLogETentarReenvio(_nfe);
            }
            else
            {
                if (retornoConsulta.Retorno.protNFe != null)
                {
                    //100 = Autorizada, 150 = Autorizado o uso da NF-e, autorização concedida fora de prazo
                    if (retornoConsulta.Retorno.protNFe.infProt.cStat == 100 | retornoConsulta.Retorno.protNFe.infProt.cStat == 150)
                    {
                        var nfeproc = new nfeProc { NFe = _nfe, protNFe = retornoConsulta.Retorno.protNFe, versao = retornoConsulta.Retorno.versao };
                        nfeproc.SalvarArquivoXml(nomeArquivoXml);
                    }
                    else
                    {
                        _nfe.SalvarArquivoXml(nomeArquivoXml);
                    }
                }
            }
```

**Comment by marcosgerene** [comment]
Obrigado
