### ISSUE TITLE
Erro qrCode

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#346]
olá amigo. por favor me orienta qual biblioteca baixar e como atualiza-la aqui, porque não sei mexer com isso ainda... estou apanhando com esse erro ao validar o NFCe:

chNFe=28170110209247000176650010000000031000012346&nVersao=100&tpAmb=2&dhEmi=323031372d30312d31375431333a31373a31332d30323a3030&vNF=300.00&vICMS=0.00&digVal=4d713447554e696f353354324f69646e35524c4a2f35596c6f6d673d&cIdToken=DB0C20CD-811B-4109-BD0C-07382DEE5494&cHashQRCode=e028204a74d7c9e4afff973224aa1f20a0b1f68b' é inválido dependendo do tipo de dados 'String' - Falha na restrição Pattern.

no aguardo, 

grato

**Comment by robertorp** [comment]
Não entendi bem a pergunta, como assim qual biblioteca baixar? Temos no nuget se for isso https://www.nuget.org/packages/Zeus.Net.NFe.NFCe/ para NFCe e NFe

O erro aí pode ser o cIdToken bom eu acho que é pois se não me engano o cIdToken é algo +- assim 000001 (coloquei o 1 para exemplificar)

**Comment by acggermed** [comment]
olá robertorp. o adeniltonbs para baixar a versão mais recente da biblioteca por aqui, e teste novamente.
veja onde: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/214

**Comment by acggermed** [comment]
alias meu csctoken tem dois criados: 000001 e 000002... pode ter haver tb sobre o erro?

**Comment by robertorp** [comment]
Olha como esta o cIdToken gerado seu IdToken=DB0C20CD-811B-4109-BD0C-07382DEE5494

edit: a referencia do nuget esta atualizada, uso ela em meu projeto

**Comment by acggermed** [comment]
sim.. está errado?
é o numero que foi gerado pra mim

**Comment by acggermed** [comment]
amigo me da esse auxilio.. o que tenho que editar, o que está errado? o que atualizo em meu projeto?

**Comment by robertorp** [comment]
https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=jKHRw%20g4V%20E=
Página 15

**Comment by acggermed** [comment]
mas todo esse tratamento a biblioteca NFCe não faz? eu apenas estou informando os dados para a biblioteca... agora sobre o dódigo do CSC eu gerei o mesmo no site portal da NFCe.. informando o cnpj ele mesmo me gera o código e senha que por sinal é 000001 e 000002

**Comment by acggermed** [comment]
lendo o manual que mandou o link, fala exatamente isso sobre o CSC, gerei pelo site da secretaria da fazenda...

**Comment by acggermed** [comment]
e quanto a resposta do adeniltonbs sobre atualizar a dll que resolveria o problema? mencionando que é problema no CDATA...

**Comment by acggermed** [comment]
Olá amigo. Esse código gerei no site da secretaria da fazenda... ele me gera esse numero grande:

DB0C20CD-811B-4109-BD0C-07382DEE5494

e

000001

 

Não é isso? Qual seria o código correto? Como gero ele? Nesse próprio manual que mandou no outro e-mail

fala sobre gerar esses códigos...

 

att,

 

Antonio Carlos Gois

Analista de Sistemas

(11) 98507-7460

www.germed.com.br

LogosGermedAcg

 

De: Roberto Alves Pereira [mailto:notifications@github.com] 
Enviada em: terça-feira, 17 de janeiro de 2017 15:54
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: acggermed; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro qrCode (#346)

 

Olha como esta o cIdToken gerado seu IdToken=DB0C20CD-811B-4109-BD0C-07382DEE5494

**Comment by robertorp** [comment]
Tenta inverter.. colocar o IdToken=000001 é CSC = DB0C20CD-811B-4109-BD0C-07382DEE5494

**Comment by acggermed** [comment]
Neste manual na página 17 fala justamente sobre esse código CSC e 6 digitos para identificação.

Me fala no que estou erraando por favor.

 

att,

 

Antonio Carlos Gois

Analista de Sistemas

(11) 98507-7460

www.germed.com.br

LogosGermedAcg

 

De: Roberto Alves Pereira [mailto:notifications@github.com] 
Enviada em: terça-feira, 17 de janeiro de 2017 16:03
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: acggermed; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro qrCode (#346)

 

https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=jKHRw%20g4V%20E=
Página 15

**Comment by acggermed** [comment]
olá amigo roberto... agora andou a validação, porém acusou esse erro: xMotivo1 = 
Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA
que é justamente o que o adeniltonbs comentou... pode me orientar agora nessa parte?
desde já muito grato pela atenção...

**Comment by robertorp** [comment]
O componente já faz isso internamente na hora da conversão de classes para xml 

Observe a classe: 
![aaaaaa](https://cloud.githubusercontent.com/assets/10251705/22037124/2c8b02c6-dcdd-11e6-8b63-57f38bbd3dd5.png)

Na hora que ele for converter de classe para xml ele vai passar por essas linhas ai de código e adicionar o CDATA

xml que acabei de gerar com minha aplicação
[xml teste.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/712164/xml.teste.txt)

**Comment by acggermed** [comment]
então amigo. acredito que tenho que atualizar a dll, pois o meu da esse erro. pode me orientar qual arquivo atualizar?

grato novamente

**Comment by acggermed** [comment]
olá amigo... acabei de observar e no meu fonte não contém a mesma rotina que vc mandou... está assim:
namespace NFe.Classes
{
    public class infNFeSupl
    {
        /// <summary>
        /// ZX02 - Texto com o QR-Code impresso no DANFE NFC-e
        /// </summary>
        public string qrCode { get; set; }
    }
}
