### ISSUE TITLE
Impressão Danfe (NFe e NFCe)

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#348]
olá amigos. diante de muitas dicas, alguém poderia informar o que seria mais rápido e eficiente para impressão das NFes? se fala sobre fastreport e outras saidas... por favor alguém poderia esclarecer o que seria mais viavel?

grato

**Comment by marcosgerene** [comment]
EU comprei o fastreports para meus relatórios do sistema e na comunidade encontrei varias pessoas que fizeram o mesmo então foi uma saida super produtiva, comparado à outras ferramentas como o DevExpress é ABSURDAMENTE mais barato e é eficiente.

Quanto a impressão do NFe/NFCe, ATUALMENTE o sistema ja faz em produção com o fastrepots, outra solução que não seja ele seria usar o acbrmonitor somente para imprimir os arquivos, passaria a depender de mais uma aplicação, mas não teria este custo.

Falando de mim, eu compraria novamente o FastReports, até agora me atendeu bem

**Comment by krgm03** [comment]
Aqui temos a licença do DevExpress. Está quase pronto e iremos disponibilizar.

O DevExpress Reporting com todos os recursos custa atualmente $599,99 - https://www.devexpress.com/Subscriptions/Reporting/
O FastReports com recursos compatíveis/parecidos custa atualmente $699,00 - https://www.fast-report.com/pt/buy/#!/.Net (MS Visual Studio)/FastReport.Net/yes&/Enterprise/

Apesar de termos usado muito pouco o Fastreports, notamos que também é bem completa e muito parecida com a do DevExpress

Na nossa opinião vale a pena o investimento

**Comment by marcosgerene** [comment]
Então eu comi bronha na época que comprei, lembro que o DevExpress era algo absurdo, e com isso acabei indo pro FastReports que para mim era uma mão na roda porque já havia usado no Delphi a anos luz atrás então tinha alguma base de conhecimento.

E eu paguei US$ 299,00 porque era só para winforms

Obrigado pela informação @krgm03, abraços

**Comment by rftd** [comment]
DevExpress na parte de Report é bem inferior ao FastReport

**Comment by francofs** [comment]
Acho só complicado ter uma ferramenta de report paga em um projeto open
source. O ideal é termos algo nativo ou também open source no projeto.

Eu desenvolvi DANFE A4 nativa. Mas precisa de adaptações. Infelizmente
estou sem tempo para colocar no projeto. Mas agradeceria se alguém
colocasse.

Disponibilizei para o outro Fábio na issue
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/264

2017-01-19 9:28 GMT-02:00 Marcos Gerene <notifications@github.com>:

**Comment by rftd** [comment]
Pessoalmente não vejo nada de errado, pois eu acredito que cada pessoa deva usar uma ferramenta de report para seu projeto.
Eu acho que o projeto deve sim ter uma forma de impressão mas como exemplo para que as pessoas implemente na sua ferramenta de uso e se a mesma quiser contribuir e adicionar o sources ao projeto melhor ainda.

**Comment by francofs** [comment]
Não disse que era errado, mas ter uma ferramente paga como principal fonte
para ter uma solução completa, creio que seja longe do ideal,
principalmente por ser open source e pelo fato de a impressão fazer parte
da solução, ela não é simplesmente uma ferramenta de report. Sem ela a
solução não está completa.

De qualquer maneira, como já havia mencionado, disponibilizei o source na
issue para implementação nativa da impressão. Apenas DANFE NF-e A4
infelizmente.

2017-01-19 9:57 GMT-02:00 Rafael Teno Dias <notifications@github.com>:

**Comment by robertorp** [comment]
As licenças do fastreport servem para revendas?

Digo, aqui somos uma empresa com varias revendas no Brasil ai oque acontece hoje usando o acbr somente para impressões, mas queremos implementar o nosso próprio (vamos fazer isso mas não é o momento certo ainda)  , ai oque acontece nos não temos clientes finais. Quem tem são nossas revendas nossos parceiros. Logo então queria saber se eu comprar uma licença do FastReport posso distribuir a dll licenciada para as revendas? Somente quero que não apareça a marca lá DEMO VERSION

**Comment by rftd** [comment]
A revenda usa seu software então pode usar normalmente, só não poderia se você vende-se o source do seu software pois ai cada um precisaria de sua licença.

**Comment by homerokzam** [comment]
@marcosgerene e/ou @krgm03 

Vocês implementaram alguma coisa usando o reports do DevExpress e que possam compartilhar? Eu tenho esta licença e gostaria de usar o DevExpress. Como estou hospedando minha solução no Azure não estou conseguindo usar o nativo (DanfeNativoNfce), pois precisa de uma impressora configurada.

Obrigado.

**Comment by krgm03** [comment]
Estamos concluindo....Assim que estiver pronto iremos compartilhar sim
No máximo até início do próximo mês

Em 16 de fev de 2017 09:00, "homerokzam" <notifications@github.com>
escreveu:

@marcosgerene <https://github.com/marcosgerene> e/ou @krgm03
<https://github.com/krgm03>

Vocês implementaram alguma coisa usando o reports do DevExpress e que
possam compartilhar? Eu tenho esta licença e gostaria de usar o DevExpress.
Como estou hospedando minha solução no Azure não estou conseguindo usar o
nativo (DanfeNativoNfce), pois precisa de uma impressora configurada.

Obrigado.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/348#issuecomment-280300340>,
or mute the thread

**Comment by homerokzam** [comment]
@krgm03 Obrigado!
