### ISSUE TITLE
Consulta Recibo Lote

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#349]
Pessoal, algum de vcs ao realizar essa operação consultar recibo lote 3.0 no app de teste ta tendo o retorno de falha no schema.

verificando o xml enviado para o webservice e validando tenho o seguinte resultado:

http://www.portalfiscal.inf.br/nfe:nRec' element is invalid - The value '440' is invalid according to its datatype 'http://www.portalfiscal.inf.br/nfe:TRec

Alguém passou por isso?

**Comment by adeniltonbs** [comment]
@celinolimac Funcionava e parou? qual UF/ambiente/modelo?

**Comment by celinolimac** [comment]
adenilton, funcionava de boa, algumas versões atrás... Porém depois que atualizei o fonte obtive esse erro ao consultar o o lote depois de processado....   ambiente de homologação, SP, NF

**Comment by adeniltonbs** [comment]
Bom dia, tem como passar o XML do pedido de consulta?

Outra coisa, o número do recibo retornado pela SEFAZ contém 15 dígitos. No seu caso estais a passar o valor "440" como número de recibo do lote. Esse realmente foi o número do recibo retornado pela SEFAZ.

Fiz um teste com essa SEFAZ, veja o resultado e o número do recibo abaixo:
![image](https://cloud.githubusercontent.com/assets/6733483/22247749/2042b080-e21a-11e6-8323-efced1347be6.png)

**Comment by celinolimac** [comment]
Boa tarde Adenilton... deu certo aqui... realmente vacilei na hora de passar NRecibo, tava passando o campo errado devido uma mudança em campo do DB... valew mesmo!
