### ISSUE TITLE
Envio sincrono nfe

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#35]
Boa tarde.

Grande Adenilton, sobre a implementação que está por vir, conforme seu todo, a funcionalidade de envio sincrono da nfe,  você tem ideia de quando vai estar pronto?

Digo isso pq já estou usando a framework e está muito boa. E com esse recurso seria ainda melhor.

Grande abraço!
Darlan.

**Comment by adeniltonbs** [comment]
Em novembro irei implementar a NT2015/002, nesta ocasião também implementarei o envio síncrono.

**Comment by willianas1** [comment]
Estou ansioso por essa atualização, parabéns Adenilton.

**Comment by darlanhendges** [comment]
Ok!...

Obrigado meu veio.
