### ISSUE TITLE
Erro ModeloDocumento

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#350]
olá amigos. atualizei as dlls, porém estou apanhando nesse erro aqui:
                cUF = (Estado)Enum.Parse(typeof(Estado), vpEmitUF, true), //Estado.SP,
                DiretorioSalvarXml = Server.MapPath(DirXml),
                DiretorioSchemas = Server.MapPath(DirXsd),
                ModeloDocumento = ModeloDocumento.NFe,

alguém pode me auxiliar com alguma dica? sou iniciante

grato a todos

**Comment by marcosgerene** [comment]
O modelo do documento antes estava na NFe.Classes.Tipos.Informação, agora está em DFe.Classes.Entidades.

Tenta adicionar este namespace aos usings

```
using DFe.Classes.Entidades;
```

**Comment by acggermed** [comment]
olá marcos. grato pela atenção... adicionei no using desta mesma forma, mas consta em cor cinza, veja anexo... me da um help de como solucionar.. grato mais uma vez...

![using](https://cloud.githubusercontent.com/assets/25176656/22070357/d9f7db64-dd82-11e6-8dd7-82ae285f92a3.jpg)

**Comment by marcosgerene** [comment]
Então não é a referencia ao estado o problema. Em que linha exatamente ocorre e qual o erro?

**Comment by acggermed** [comment]
olá amigo nesta linha: ModeloDocumento = ModeloDocumento.NFe,

**Comment by marcosgerene** [comment]
O primeiro "ModeloDocumento" antes do = é uma variável sua, uma configuração do sistema, o que? pode me mandar um print?

De qualquer forma a propriedade "ModeloDocumento" também foi removida de onde tava e passada para DFe.Classes.Flags.

Tenta assim:
```
ModeloDocumento = DFe.Classes.Flags.ModeloDocumento.NFe;
```

Se não der, manda um print igual fez acima do código que está inserido esta linha

**Comment by acggermed** [comment]
olá amigo... veja as duas imagens... uma é o ModeloDocumento
a outra é ConfiguracaoServico()
![configuracaoservico](https://cloud.githubusercontent.com/assets/25176656/22082527/42d3858a-ddaf-11e6-9d43-c46adcec5a50.jpg)
![modelodocumento](https://cloud.githubusercontent.com/assets/25176656/22082526/42cc78a8-ddaf-11e6-9db7-42333dde69c5.jpg)

**Comment by marcosgerene** [comment]
A sua versão ainda não foi alterada, provavelmente usa nuget, esquece tudo que eu disse antes e vamos começar do zero.

Continuando, o seu código me parece correto se considerada a sua versão, seu problema está na forma como está escrevendo, o compilador está reconhecendo o ModeloDocumento antes do igual como o tipo e não como a propriedade do objeto que está preenchendo.

Comenta esta linha e antes do return coloca:

```
configuracoes.ModeloDocumento = ModeloDocumento.NFCe;
```

Se isto funcionar o meu "chute" de que o compilador está "se confundindo" se confirma, se não funcionar, ai o buraco é mais em baixo.

Abraços
