### ISSUE TITLE
Erro: CDATA

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#351]
olá caros amigos. por favor alguém de me da a dica como solucionar esse erro?
xMotivo1 = Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA

isso ao fazer a homologação da NFCe... sou leigo ainda, e preciso de orientações de vcs do
grupo para andar...

grato

**Comment by adeniltonbs** [comment]
@acggermed o QR-Code já é enviado como CDATA há algum tempo. Estais a utilizar a versão mais recente da biblioteca?

**Comment by acggermed** [comment]
olá amigo... estou tentando atualizar, só que está dando muito erro... mudou muita coisa em ralação as dlls que tenho aqui... por isso to recorrendo a vcs com urgencia...

**Comment by acggermed** [comment]
já incorporei as dlls novas no meu projeto.. estou ajustando os erros e apanhando bastante

**Comment by acggermed** [comment]
veja alguns erros que ocorrem com a dll atual o qual funcionava perfeitamente na dll antiga e estou apanhando para resolver. me da a dica por favor... grato
![erro2](https://cloud.githubusercontent.com/assets/25176656/22119299/3be453d6-de62-11e6-938d-2fda129f50f8.jpg)
![configuracaoservico](https://cloud.githubusercontent.com/assets/25176656/22119310/42469720-de62-11e6-92ca-64f392f3d69b.jpg)

**Comment by acggermed** [comment]
esquece a primeira imagem.. a que funcionava é essa aqui:
![erro2](https://cloud.githubusercontent.com/assets/25176656/22119502/03a53926-de63-11e6-9155-5a461903a1f9.jpg)

**Comment by acggermed** [comment]
olha outro caso que to apanhando tb...

![erro3](https://cloud.githubusercontent.com/assets/25176656/22119623/72b2d710-de63-11e6-94b1-36ffdc076e27.jpg)
