### ISSUE TITLE
Duvida enquanto a opção de zip da NFeAutorizacao

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#352]
Toda vez que vou testar o app eu me deparo com o seguinte erro
ele converte nessa linha com sucesso 

`var xmlCompactado = Convert.ToBase64String(Compressao.Zip(xmlEnvio));`

ate ai tudo bem

quando executa a linha 

`retorno = ws.ExecuteZip(xmlCompactado);`

o retorno vem como null 

debugando a aplicação cheguei aqui na NfeAutorizacao.cs

`var results = Invoke("nfeAutorizacaoLoteZip", new object[] {nfeDadosMsgZip});
            return ((XmlNode) (results[0]));`

ele da results{objects[1]} ou seja tem um objeto...

Mas quando clico pra ver oque temos dentro me deparo com "null"

código do método

`[SoapHeader("nfeCabecMsg", Direction = SoapHeaderDirection.InOut)]
        [SoapDocumentMethod("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/nfeAutorizacaoLoteZip", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Bare)]
        [WebMethod(MessageName = "nfeAutorizacaoLoteZip")]
        [return: XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
        public XmlNode ExecuteZip([XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")] string nfeDadosMsgZip)
        {
            var results = Invoke("nfeAutorizacaoLoteZip", new object[] {nfeDadosMsgZip});
            return ((XmlNode) (results[0]));
        }`

observação: não sei se esse serviço varia de estado para estado
sou de Goiás

**Comment by adeniltonbs** [comment]
@robertorp
Talvez o serviço NFeAutorizacao de GO não aceite o xml compactado. No manual não informa se essa é uma configuração de cada UF. Alguém conseguiu enviar uma NF-e compactada para GO?
