### ISSUE TITLE
HELP amigos

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#354]
prezados amigos. por favor me deem o esclarecimento necessario...
Com as dlls (Zeus) que um companheiro me passou tempo atrás estava homologado aqui a NFe e acabando de homologar a NFCe... porém esbarrei no erro do crCode.
Achei essa postagem aqui: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/214
então segundo o adeiltonbs baixei seus Codes e fui migrar meu sistema com as dlls dele que me parecem recentes... ai que começou minha luta...
estou observando que mudou muita coisa em relação ao que eu já havia homologado.

então minha pergunta seria: essas dlls são as mais recentes? porque tanta mudança nas classes, rotinas, funções? por onde posso caminhar?

por favor alguém me dê uma luz, porque fiquei assustado agora e não sei se continuo com a versão que vinha utilizando, ou se começo tudo de novo...

Não deixem de me esclarecer, preciso urgente... desde já grato a todos...

**Comment by marcosgerene** [comment]
1- Use as novas versões, o projeto constantemente vem corringindo bugs e aperfeiçoando suas rotinas
2 - Se não vai fazer download do fonte, referencie as dlls via nuget, é mais prático do que baixar as dlls e referenciar
3 - O componente até um tempo atrás atendia apenas NFe e NFCe, atualmente já tende MDFe e está começando o desenvolvimento do CT-e, para melhorar a estrutura e reaproveitar o que é igual entre os projetos (assinatura, enums, etc) está ocorrendo um refactoring no projeto, por isso vem ocorrendo e ainda vai ocorrer por um tempo um número expressivo de mudanças.

Não se assuste, quando comecei a usar a biblioteca tinhamos em torno de 30/40 pessoas marcando com a estrela e meia duzia de forks, hoje só em forks são 120, a comunidade já tem um corpo e vem crescendo, tanto que dentro do github só fica atrás da maior de Java e por pouco (pela ultima vez que vi).

Abraços

**Comment by acggermed** [comment]
grato amigo... como seria a atualização das dlls via nuget? e qual link para baixar as dlls full sempre que são atualizadas?

**Comment by acggermed** [comment]
seria aqui no Code? são todas dlls atualizadas sempre?

**Comment by marcosgerene** [comment]
Você usa qual versão do visual studio?

https://www.nuget.org/packages/Zeus.Net.NFe.NFCe/

**Comment by acggermed** [comment]
VS2015 amigo

**Comment by adeniltonbs** [comment]
@acggermed 
Você pode:
1 - Usar os fontes aqui do repositório direto no seu projeto. Assim você vai sempre ter a versão mais recente. Para isso, use um cliente git, como o Team Explorer, tortoise git, etc;
2 - Utilize o nuget para baixar/atualizar os pacotes.

**Comment by acggermed** [comment]
xi... perdoe minha ignorancia... mas essas linguagens pra mim são desconhecidas no momento.. nem imagino como utilizar essas ferramentas para abrir do repositório.. e nem como utilizar o nugtet

**Comment by robertorp** [comment]
Se você pesquisar um pouco na internet irá achar muito conteúdo sobre como utilizar o nuget/git

https://www.youtube.com/watch?v=TK7zQfyQZMI

Também existem cursos pagos por ai. É bem simples.
