### ISSUE TITLE
Produto específico - Medicamentos e Armamento

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#356]
No caso dos produtos específicos, mais precisamente medicamentos e armamento, segundo o manual posso ter de 1 a 500 ocorrências, mas no componente não sei como informar em forma de lista pois o produto especifico esta como objeto unico.

Como proceder?

**Comment by marcosgerene** [comment]
Ninguém?

**Comment by robertorp** [comment]
Talvez tenham feito errado por engano, isso aconteceu uns tempos atrás com o NVE (não tenho certeza se era essa tag mesmo), podia ter umas 8 ocorrências se não me engano, ai alterei os fontes e fiz um pull

**Comment by marcosgerene** [comment]
@robertorp , obrigado pela resposta.

Neste caso, levando em consideração que está herdando de produto específico, como posso fazer ser lista via codigo?

Este caso acontece com medicamentos e armamentos

**Comment by robertorp** [comment]
No MDF-e tenho esse código (lembrando que no mdf-e e sempre um único objeto e não varia de listas)

![mdfe](https://cloud.githubusercontent.com/assets/10251705/22247402/c8e290c4-e220-11e6-9844-e209fd562f6a.png)

Pode criar um objeto para produto específico
Talvez daria certo algo com TinyType 

no caso do MDF-e todo mundo herda de uma classe abstract ..

estou somente deduzindo que poderia dar certo, não sei na pratica

**Comment by marcosgerene** [comment]
O código da NFe esta igual o seu informado acima, mas falta conhecimento técnico para eu implementar ou propor algo, só sei apontar que está errado.

Vou deixar a insue aberta para alguém propor uma solução, no meu caso eu só uso combustiveis que se trata de um objeto apenas então está ok

**Comment by robertorp** [comment]
Eu acho que se colocar somente o tipo como object... já funcionaria.. mas.. ai perderíamos o conhecimento  do autocomplete

object = new List<med>();

**Comment by robertorp** [comment]
Pode transformar produtoespecifico em uma interface talvez, ai cria uma classe com o nome de ListMed , a classe vai extender List<med> e implementar o produtoespecifico 

e acima do produtoespecifo colocar [XmlElement("veicProd", typeof(veicProd))]
        [XmlElement("med", typeof(List<med>))]
        [XmlElement("arma", typeof(arma))]
        [XmlElement("comb", typeof(comb))]

no caso receberia um ListMed que nada mais é que uma lista de "med"
