### ISSUE TITLE
Assinatura

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#358]
bom dia amigos. alguém por favor me orienta quais dados colocar para assinatura do certificado digital?
terei as duas situações, com o A3 e A1 (.pfx)...
ObterAssinatura<T>(T objeto, string id, X509Certificate2 certificadoDigital = null)
por favor me esclarecam que tipo de informação coloca ai para que funcione de acordo com os dois certificados... 

grato

**Comment by douglasPinheiro** [comment]
Coloca a configuração do certificado na classe ConfiguracaoServico que por sinal usa o padrão singleton, dentro dela tem uma propriedade chamada Certificado da classe ConfiguracaoCertificado, na qual voce coloca o endereço do certificado "Caso quiser usar o arquivo pfx por exemplo", ou o serial, caso for um A3.

Depois é so passar a instancia da classe ConfiguracaoServico para a classe ServicosNFe, onde ficam as funções que interagem com o sefaz.

Fiz assim com meu projeto e funcionou

**Comment by acggermed** [comment]
olá amigo... perdoa o abuso, sou iniciante nisso tudo.. por favor coloca aqui pra mim o caminho disso tudo, não consegui achar ConfiguracaoCertificado.. aqui: NFe.Utils.ConfiguracaoServico. só me mostra a opção de Instancia...

**Comment by guidi** [comment]
@acggermed você não tem experiência com c#? pra mim a melhor ajuda foi a aplicação de exemplo, lá já mostra como fazer as coisas principais com a biblioteca.

**Comment by acggermed** [comment]
olá amigo, justamente estou fazendo essas perguntas porque disse anteriormente que sou iniciante... porém eu tinha toda funcionalidade normal com a dll mais antiga, e como mudou tudo estou sofrendo bastante para ajustar... preciso de auxilio de vcs feras... grato

**Comment by adeniltonbs** [comment]
Boa tarde. Aqui mostra como usar a app de teste pra usar pfx e A3. https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114
