### ISSUE TITLE
DESATIVAÇÃO EM 01/OUT/2015 DO AMBIENTE DE AUTORIZAÇÃO DE DOCUMENTOS  FISCAIS ELETRÔNICOS (NF-e, NFC-e, CT-e e MDF-e)

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#36]
Boa tarde.

Já está sabendo dessas novidades do Sefaz.. ???
Pelo que entendi, falando por cima, é a troca dos links dos webservices, correto ?

Grande abraço.

**Comment by adeniltonbs** [comment]
Sim, as alterações necessárias já foram providenciadas em 4 de maio deste ano, conforme commit c7705a8ac7d33ad7f63090b986eb28afb86515a2.

**Comment by darlanhendges** [comment]
Beleza...

Obrigado.
