### ISSUE TITLE
Produto específico - Papel imune

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#360]
Boa tarde a todos,

Como devo referenciar o numero do recopi no papel imune nos produtos especificos?

**Comment by robertorp** [comment]
Isso é uma melhoria visto que esta errado se comparado com o xml.

**Comment by robertorp** [comment]
vai entrar aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503
