### ISSUE TITLE
DANFE - Informações Complementares e Reservado ao Fisco

### ISSUE THREAD

**Issue by krgm03** [ZeusAutomacao/DFe.NET#361]
Boa tarde

No Manual de Orientação consta

"
7.1.6 Informações Complementares
Deverá conter todas as Informações Adicionais da NF-e incluídas nas TAGs infAdFisco e infCpl, ficando facultada a impressão das informações adicionais contidas nas TAGs obsCont. Na hipótese de insuficiência de espaço no quadro de “informações complementares”, a impressão destas deverá ser continuada no verso ou na folha seguinte, neste mesmo quadro ou no quadro “Dados dos Produtos/Serviços”.
7.1.7 Reservado ao Fisco
O contribuinte não deverá preencher este quadro, sendo seu preenchimento de uso exclusivo do fisco. Em caso de utilização de formulário de segurança provido de estampa fiscal, esse quadro não estará presente.
"

Na minha interpretação o quadro 'Informações Complementares' deve ser composto pela concatenação das tags infAdFisco e infCpl e facultativamente da tag obsCont
Já o quadro 'Reservado ao Fisco' tem o preenchimento de uso exclusivo do fisco

Na DANFE do projeto, implementada com o fastreport, o quadro 'Informações Complementares' é preenchido com a tag infCpl   e o quadro 'Reservado ao Fisco' é preenchido com a tag infAdFisco

Aparentemente a implementação não segue o manual. Mas como posso estar equivocado gostaria de discutir o assunto com alguém que possa ter tido as mesmas dúvidas

Desde já agradeço

**Comment by adeniltonbs** [comment]
@krgm03 Você está certo. A correção já foi feita. Obrigado.

**Comment by krgm03** [comment]
Nós que agradecemos!
