### ISSUE TITLE
Erros na dll

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#362]
olá amigos. preciso de um auxilio de vcs. vejam:
ao ajustar minha aplicação para a dll atualizada, ocorre estes erros nestes momentos:

1)  public static Classes.NFe Valida(this Classes.NFe nfe)
nesta classe da erro na linha abaixo:   {"A cadeia de caracteres de entrada não estava em um formato correto."}
var versao = (Decimal.Parse(nfe.infNFe.versao, CultureInfo.InvariantCulture));

alterei a mesma para: var versao = (Decimal.Parse(nfe.infNFe.versao.ToString().Replace("ve", ""), CultureInfo.InvariantCulture));

dando o replace para tirar "ve" da versão qdevido a mesma ser decimal...

2) public static Classes.NFe Assina(this Classes.NFe nfe)
nesta classe tb da erro na linha abaixo:   {"A cadeia de caracteres de entrada não estava em um formato correto."}

var versao = (decimal.Parse(nfeLocal.infNFe.versao, CultureInfo.InvariantCulture));

alterei a mesma para: var versao = (Decimal.Parse(nfeLocal.infNFe.versao.ToString().Replace("ve", ""), CultureInfo.InvariantCulture));

dando o replace para tirar "ve" da versão qdevido a mesma ser decimal...

passou desses erros, mas agora acusa o erro:
{"Erros na validação:\n O atributo 'versao' é inválido - O valor 've310' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerNFe' - Falha na restrição Pattern."}

preciso de alguma orientação de vcs para andar com essa situação

grato

**Comment by adeniltonbs** [comment]
Boa tarde. Deu uma olhada na aplicação de demonstração de uso? O problema ainda continua?

**Comment by acggermed** [comment]
Olá amigo. Eu me envolvi com as dlls novas, esqueci a antiga, e estou nos finalmentes parece...

até agora ta dando certo graças a DEUS...

 

 

Antonio Carlos Gois

Analista de Sistemas

(11) 98507-7460

www.germed.com.br

LogosGermedAcg

 

De: Zeus Automação Comercial [mailto:notifications@github.com] 
Enviada em: quinta-feira, 26 de janeiro de 2017 16:54
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: acggermed; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erros na dll (#362)

 

Boa tarde. Deu uma olhada na aplicação de demonstração de uso? O problema ainda continua?
