### ISSUE TITLE
Sem comunicação com o serviço NfeStatusServico

### ISSUE THREAD

**Issue by homerokzam** [ZeusAutomacao/DFe.NET#363]
Estou tentando verificar o status do serviço da UF: DF, porém sempre retorna o erro "Sem comunicação com o serviço NfeStatusServico".

Tenho acesso total à internet, inclusive desliguei o firewall.

Obrigado pela atenção.
Homero

**Comment by JohnSalazar** [comment]
@homerokzam confirme as configurações de WebService do app.Teste.NFe de acordo com a imagem em anexo e teste o serviço.

![webservice](https://cloud.githubusercontent.com/assets/16736914/22169795/3f1ad320-df5e-11e6-820e-8b3bb611a171.png)

**Comment by homerokzam** [comment]
@JohnSalazar Obrigado pela ajuda. Vi que agora tem o atributo: protocolo de segurança. Fiz a atribuição de Ssl3 e funcionou.

Obrigado.

**Comment by homerokzam** [comment]
No meu computador já está funcionando, porém quando faço o deploy para o Azure, continuo com o problema de "Sem comunicação ...".

Obrigado.

**Comment by robertorp** [comment]
@homerokzam  ainda esta com o problema?

edit: não se se tem algo a ver mas nessa issue estavam passando por problemas também parecido com o seu https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/408
