### ISSUE TITLE
[Nuget] Impressão

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#368]
Boa noite @adeniltonbs e @robertorp,

Seria possivel disponibilizar a impressão da NFe/NFCe e do MDFe via nuget (mas em "pacote" separado, lógico)?

**Comment by robertorp** [comment]
Uma vez perguntei sobre isso, mas me falaram que tinha que ver sobre a licença do fastreport se poderia empacotar assim ou se somente empacotaria sem as dll do fast, enfim tem que ver certinho isso como seria
