### ISSUE TITLE
Dúvida - Fast Report

### ISSUE THREAD

**Issue by SilverioMiranda** [ZeusAutomacao/DFe.NET#37]
Obrigado por ter implementado a impressão do danfe, só que eu tenho uma dúvida

O Fast Report é esse aqui ? https://www.fast-report.com/pt/product/fast-report-net/
Se for outro, qual é?
Tem como imprimir esta imagem gerada em impressora não fiscal? Se sim qual você recomendaria

Você comprou ele diretamente deste site? 299 dólares?

Muito obrigado :)

**Comment by adeniltonbs** [comment]
[1] O Fast Reports é esse gerenciador de relatórios do link https://www.fast-report.com/pt/product/fast-report-net/;
[2] A impressora térmica não fiscal imprime exatamente o que você vê na tela (só que monocromático);
[3] Epson, Bematech, Elgin, etc. Aqui trabalhamos com uma Epson TM 81.

[4] Compramos diretamente no site, você pode ver as opções aqui: https://www.fast-report.com/pt/fast-report-net-editions-compare.

Atualizei a página principal https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe e adicionei uma foto do DANFE impresso.

**Comment by adeniltonbs** [comment]
Se desejar uma opção gratuita você pode tentar fazer o relatório em crystal reports for visual studio ou RDLC. A biblioteca NFe.Impressao já foi montada prevendo relatórios de outros gerenciadores.

Implementei em fast pois já usávamos aqui na Empresa em Delphi, e o licenciamos para .net.

**Comment by vasisti** [comment]
Ola Adenilton boa tarde. 
Estou com uma duvida quanto a emissao da danfe NFce em OffLine-(Contingencia)..
Quando na transmissao da Nfe nao houver acesso á internet, entao é gerado em contingencia, certo, e como fica a impressao da danfe? só de dará apos a transmissao quando voltar a internet e a transmissao da mesma?
sem mais grato.
Valdir

**Comment by adeniltonbs** [comment]
Neste caso, você imprime o DANFE em contingência e depois transmite a NFCe para a SEFAZ. No entanto há mais coisas envolvidas. Consulte o Manual de Especificações da Contingência Offline para NFC-e - versão 1.2 que pode ser obtido aqui http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=

**Comment by vasisti** [comment]
Bom dia Adenilton, grato pelo retorno. No caso do Sistema Zeus a impressao em contingencia não esta implementada certo?

**Comment by adeniltonbs** [comment]
Você quis perguntar se a biblioteca para emissão de NFCe já tem suporte a impressão de NFCe em contingência?

Se foi isso que entendi, sim a impressão da NFCe em contingência já está implementada.

**Comment by leandrossantos** [comment]
Adenilton, tem previsão para liberação da DANFe para NFe modelo 55 ??

**Comment by adeniltonbs** [comment]
No momento não.

**Comment by leandrossantos** [comment]
Eu tentei converter a DANFe feita no FastReports que vem no projeto acbr em Delphi, mais na conversão acaba não convertendo tudo, fica algumas partes sem converter, faturas e produtos por exemplo.

**Comment by adeniltonbs** [comment]
É verdade, tem que ajustar manualmente muita coisa. Mas adianta um pouco o trabalho.

**Comment by leandrossantos** [comment]
Se quiser te passo os arquivos convertidos para frx para você poder implementar eles no componentes. Só me passar um email para leandro@rondosoft.com.br que eu te retorno com eles.

**Comment by vasisti** [comment]
Adenilton, boa noite,
tenho duvida quanto á emissao da danfe em contingencia (OffLine),
quando eu envio a nfe e nao tem internet, entao é gerado o arquivo (1-env-lot.xml) como (OffLine), 
neste momento eu nao consigo imprimir a danfe? ou so imprime
depois que a nfe é autorizada (procNfe)?
sem mais Grato 
Valdir

**Comment by adeniltonbs** [comment]
Bom dia vasisti, o DANFE em contingência pode ser impresso da seguinte forma:

``` cs
var nfe = new Classes.NFe().CarregarDeArquivoXml(Caminho_do_arquivo_XML);
var danfe = new DanfeFrNfce(new nfeProc() { NFe = nfe }, new ConfiguracaoDanfeNfce(NfceDetalheVendaNormal.UmaLinha, NfceDetalheVendaContigencia.UmaLinha, "00001", "XXXXXXXXXXXXXXXXXXXXXXXXXX", null/*Logomarca em byte[]*/));
danfe.Visualizar();
//danfe.Imprimir();
//danfe.ExibirDesign();
```

Note que o objeto nfeProc é apenas um objeto que contém um NFe e um protNFe, conforme o manual de especificações da NFe. No caso acima, o que fiz foi criar o objeto nfeProc sem o protNFe e o passei no parâmetro do construtor da classe DanfeFrNfce que já contém os mecanismos para tratar a impressão em contingência Offline.

Mas visando facilitar o uso da biblioteca eu fiz as seguintes alterações no commit 814370c46afb08ced595ac06389f5edd70c20fca:
- Unificadas algumas funções do aplicativo de demonstração para NFe e NFCe, bastando definir o documento na guia "Geral", na opção "Selecione o Tipo de Documento";
- Adicionado novo construtor da classe DanfeFrNfce que aceita um objeto NFe como parâmetro em lugar do objeto nfeProc, facilitando a impressão do DANFE da NFCe em contigência Offline;
- Trocada fonte de dados para obtenção da Chave da NFCe de protNFe.infProt.chNFe para NFe.infNFe.Id. Visando possibilitar a impressão da Chave mesmo em contigência, quando não há o registro de protNfe.

**Comment by adeniltonbs** [comment]
Veja as novas telas do aplicativo de demonstração em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe. Note que adicionei um botão chamado DANFE NFCe Cont. Offline. Neste botão contém o código de exemplo para impressão do DANFE da NFCe em contingência Offline.

**Comment by adeniltonbs** [comment]
leandrossantos, eu já dei uma olhada no arquivo frx obtido a partir do DANFE do ACBR. Pelo que vi é praticamente fazer do zero. Estou envolvido em uma demanda por esses dias, mas assim que tiver um tempo ponho a mão na massa. Qualquer ajuda é bem vinda, claro.

**Comment by leandrossantos** [comment]
beleza adeniltonbs, vou ver aqui o que consigo lhe ajudar com isso. voltando a falar da DANFE da NFCe, fiz os testes aqui com as impressoras Bematech MP-4200 e Daruma DR700.
Resultado dos testes:
Bematech a impressão sai 100%, nenhum problema no leiaute.
Daruma, a impressão sai, mais o problema está na fonte. pode-se dizer que sai praticamente ilegível.

**Comment by adeniltonbs** [comment]
A impressora imprime corretamente outras coisas via spooler? Se você mandar uma impressão a partir do word, por exemplo, usando as fontes times news roman ou Arial tamanho 6 e 8 sai legível?

Tem algumas impressoras que a impressão via spooler é terrível, só prestando para imprimir via dll do fabricante.

Aqui testei Nas Epsons modelo TM-81 e TM-20 e a impressão nelas também é perfeita.

**Comment by leandrossantos** [comment]
Impressões de outros sistemas sai normal, até a página de testes do windows sai beleza, acredito que seja as fontes que estão sendo usadas. Já pensou em usar a Courier New ou Sans Serif ?

**Comment by adeniltonbs** [comment]
Estranho isso, pois a Open Sans utilizada é da família da Sans. O detalhe é que as fontes utilizadas precisam ser condensadas, por isso e por conta da boa legibilidade delas, utilizei essas duas fontes (Open Sans Condensed e Ubuntu Condensed).

Você poderia testar imprimir um documento do word, por exemplo, com um texto abaixo do outro, com as duas fontes condensadas citadas acima e com a Microsoft Sans Serif e a Courier New.

Veja a imagem  abaixo:
![image](https://cloud.githubusercontent.com/assets/6733483/10138622/c8a41286-65d5-11e5-84bb-9fcc29ce78f5.png)

**Comment by adeniltonbs** [comment]
Se imprimir normalmente com essas fontes a partir do word em tamanho 6 e 8, deve imprimir normalmente a partir do fast reports. Você também pode tentar ajustar a qualidade de impressão nas opções de impressão da Daruma.

**Comment by leandrossantos** [comment]
Valeu adeniltonbs, nem lembrei de ver essa questão da qualidade da impressão, apenas instalei o driver da daruma e já fui testar, era esse bendito mesmo, instalou e deixou como qualidade rascunho, ninguém merece, rsrs. Alterei para qualidade Normal e a impressão ficou 100%.
Já pode por ai, impressoras Bematech e Daruma funcionando a impressão 100%.
Value pela ajuda.

**Comment by adeniltonbs** [comment]
Que bom, qualquer coisa entre em contato.

**Comment by leandrossantos** [comment]
Agora a luta será com a DANFe da NFe, rsrs

**Comment by adeniltonbs** [comment]
Se você quiser começar a fazer, me avise que lhe mostro como é fácil usar um objeto como fonte de dados no fast para .net. daí é só sair arrastando os campos e formatando.

**Comment by leandrossantos** [comment]
Se puder, quero sim. como podemos combinar para você me mostrar, tem skype?

**Comment by mvidaldev** [comment]
Desculpa me meter, mas, não seria mais interessante utilizar as fontes do google? Elas são livres e tem um padrão bem legal.
Inclusive com tamanho travado tipo as fixed sys.

Date: Mon, 28 Sep 2015 07:23:09 -0700

**Comment by adeniltonbs** [comment]
Isso mesmo brasvidal, o problema do leandro era a qualidade de impressão. Leandro, meu skype é adenilton.bs
