### ISSUE TITLE
mdfe impressão

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#371]
Não existe a possibilidade de ter uma marca d'agua com Cancelada não?
Estou perguntando somente porque estes dias tive requisições de clientes que queriam visualizar NF-e canceladas 

a mdf-e daqui mostra se ta cancelada? fiz uns testes aqui mas não vi nada de diferente da autorizada somente a observação com mdf-e em homologação

**Comment by marcosgerene** [comment]
Sim, existe, eu mandei um pull e foi aceito.

No XML não existe diferença pois o cstat não deve ser alterado então em ambos os casos (cancelada ou transmitida) vai estar como autorizada, neste caso existe um atributo na classe de configurações DocumentoCancelado, se você setar ele pra true vai aparecer no meio da impressão "Documento Cancelado", o mesmo vale pro atribuo DocumentoEncerrado.

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/365

Este pull já foi aceito, atualiza seus fontes ai... abraços

**Comment by robertorp** [comment]
Ah sim, muito obrigado hehe e porque vamos começar a usar o mdf-e do Zeus (usavamos o AcbrMonitor para isso e queremos retirar ele de dependência pois são 7mb + no instalador)

**Comment by marcosgerene** [comment]
Eu também tinha muitas dependências, hoje uso apenas boleto e CTe, o boleto tentei usar o BoletNet mas achei muito inferior ao ACBr então acredito que não vou sair tão cedo dos boletos.

De resto, MDFe, NFe, NFCe s SAT eu já "me livrei" do ACBr rsrs

PS: Obviamente o me livrei é uma bricandeira, o ACBr é um projeto fenomenal, uso o ACBrFramework ainda, mas ai é algo "quase nativo" e não uma dependência completamente externa =)
