### ISSUE TITLE
Numeração da NFCe para PDVs

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#372]
Boa tarde,

A minha dúvida é mais conceitual do que qualquer outra coisa, vamos ao estudo de caso:

Imaginemos um supermercado com vários PDVs (se quiserem um número exato pode-se imaginar 6). Estruturalmente falando não é viável que os PDVs acessem diretamente o banco de dados do servidor, mas sim tenham uma estrutura independente, já que o volume em supermercados costuma ser muito alto e em caso de quedas na estrutura principal (rede, banco de dados e afins) as vendas nos PDVs não podem sequer imaginar parar, tanto que em cada PDV é aconselhável existir um no-break próprio além do gerador do mercado.

Feita a introdução e pensando na estrutura existente, aqui em São Paulo com o SAT, se tivermos um SAT para cada caixa ou até mesmo um "processador de SAT",não teremos problemas pois a auto-numeração do mesmo é feita pelo próprio aparelho. Entretanto neste mês apareceram alguns clientes do Ceará/Rio Grande do Norte que emitem a NFCe e isto gerou um "problema" principalmente na parte de numeração.

---------------
Como tratar essa numeração para vários caixas em paralelo, com banco de dados em paralelo emitindo de forma simultânea sem que os números se choquem?
---------------

Eis as soluções que me vieram a cabeça de imediato:

**1. Reservar pequenas faixas de numeração:**

Reservar para cada caixa 100 números em sequencia, ao atingir o mínimo de 20 números disponíveis, assim que tiver conexão com o servidor disponibilizar mais 80 (ou o restante para 100),

tendo sempre entre 20 e 100 números disponíveis para uso no caixa e somente se a numeração zerar "travar" o PDV até conseguir reservar uma nova faixa.

**Vantagens**: Não necessita recuperar a próxima numeração com frequência, evita duplicar os números;

**Desvantagens**: Em períodos muito longos sem conexão com o servidor (dias) este número vai acabar e o pdv vai travar, e se aumentar muito a numeração teremos um buraco ainda maior para inutilzar ao final de cada mês.

**2. Utilizar séries diferentes:**

Cada caixa usaria uma série para emitir o NFCe,ou seja, o PDV 1 vai ter usar a série 1, o PDV 2 usa a série 2 e assim por diante.

**Vantagens**: Seria este o ambiente perfeito.

**Desvantagens**: Acredito que isto não seja permitido.

**3. Buscar sempre a próxima numeração no PDV**

Neste caso a ideia de uma estrutura independente no PDV é abandonada.

**Vantagens**: O genator daria conta de tudo sem o menor esforço;

**Desvantagens**: Este ambiente é utópico se pensando em supermercados;

-------------
Eu gostaria de saber dos amigos se alguém já passa por algo assim como foi a solução encontrada e dicas de como resolver este impasse.

Abraços

**Comment by adeniltonbs** [comment]
Use a opção 2, é permitido e o recomendado pela SEFAZ

**Comment by orochasamuel** [comment]
Boa tarde pessoal, tudo na paz?

Eu vi sua postagem @marcosgerene e não pude deixar de passar aqui para contribuir, o que o @adeniltonbs disse é a melhor opção mesmo.
No momento lhe falo como analista fiscal/tributário atuante na área, não como desenvolvedor. Tivemos um caso semelhando em que um cliente contratou um sistema para emitir as NFCe dele e surgiu essa dúvida, **fizemos esta mesma recomendação, utilizar uma série para cada PDV**.
O contador em questão só deve estar à par da situação, pois deve preencher o **RUDFTO - Registro de Utilização de Documentos Fiscais e Termo de Ocorrência**, nele o contador expressa a necessidade e comunica à SEFAZ o uso de séries simultâneas e após a assinatura do delegado fiscal na petição, fica aprovado o uso. Este é o modo correto de se fazer o uso de várias séries de forma que evite futuros transtornos com a SEFAZ e até evita futuros esclarecimentos.

Abraços.
Samuel Oliveira
Analista Fiscal

**Comment by marcosgerene** [comment]
@adeniltonbs e @samuelroliveira,

Muito obrigado pela ajuda de ambos, principalmente ao amigo @samuelroliveira pela pequena aula tributária, rs.

Este post fiz também no ACBr e obtive a mesma resposta do Daniel Simões (fundador do ACBr).

www.projetoacbr.com.br/forum/topic/34908-numera%C3%A7%C3%A3o-da-nfce/?do=findComment&comment=228536

Abraços e obrigado
