### ISSUE TITLE
Onde consigo um certificado digital pra testar a aplicação?

### ISSUE THREAD

**Issue by alexsandro-xpt** [ZeusAutomacao/DFe.NET#373]
Eu como desenvolvedor, como faço pra testar?

**Comment by guidi** [comment]
A pouco tempo atrás antes de mudar minha empresa para ME eu era cadastrado como MEI e usava meu certificado digital A1 e o ambiente de homologação do Amazonas para fazer testes.

**Comment by robertorp** [comment]
Comece dando uma olhada aqui >>> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki

Lembrando que você tem que ter um certificado A1 ou A3 para emitir nf-e , você pode pedir emprestado para algum conhecido e emitir em homologação. Se não tiver conhecido com isso então vai ter que $$$$$. Valores? Variam de local para local imagino eu.. mas certificado A1 você compra ai por uns 200 ou 200 e poucos (pagamento anual). Se for Certificado A3 imagino que sai por uns quase 400 dependendo da região que você estiver (renovação somente depois de três anos).

**Comment by alexsandro-xpt** [comment]
Obrigado @robertorp o complicado de pegar emprestado é que a empresa não pode emprestar porque afinal ela usa toda hora. Todo mundo/empresa que conheço tem o certificado A3.

A unica maneira que eu to vendo é pedir alguma empresa pra comprar um outro novo certificado.
