### ISSUE TITLE
SAT SP

### ISSUE THREAD

**Issue by denernun** [ZeusAutomacao/DFe.NET#374]
Existe alguém fazendo algo para emissão do SAT para SP ? Hoje utilizo Delphi e ACBr, mas estamos migrando para web e mobile, mas esse esquema de ter o SAT é um complicador.

**Comment by robertorp** [comment]
Eai @denernun  tudo bem? O componente Zeus em si não tem nada para SAT atualmente.
Mas tem esse aqui https://github.com/ACBrNet/ACBr.Net.Sat, olha quando eu desenvolver o SAT para o meu sistema tudo indica que usarei ele.  E feito em c#. Não sei te falar enquanto a compatibilidade com xamarin se por acaso for utilizar.

**Comment by marcosgerene** [comment]
@denernun e @robertorp 

No meu caso uso winforms e utilizo a ferramenta citada acima e me atende. Quanto ao SAT, ***até aonde eu conheço*** não existe nada que possa ser feito de forma mobile/web, pois tudo depende da comunicação com o aparelho (físico conectado via usb) que é feito através de uma dll win32 disponibilizada pelas fabricantes, ou seja, pelo menos um programinha systray teria que rodar em um pc windows para tal.

O que poderia ser feito é um esquema "cliente/servidor" aonde o web/mobile geraria os XMLs e um programinha desktop organizasse em fila e enviasse par ao SAT fazer o processamento.

**Comment by denernun** [comment]
Olá @robertorp e @marcosgerene Acho que o caminho será esse mesmo, jogar um serviço local para o envio do SAT. Obrigado pela resposta. E parabéns a todos os envolvidos no projeto, espero poder contribuir de alguma forma.
