### ISSUE TITLE
Impressão nativa erro na fonte ou.. falta alguma fonte para instalar

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#375]
![erro](https://cloud.githubusercontent.com/assets/10251705/22518404/9c57e40e-e893-11e6-9c57-39734657f767.png)

no windows 10 funcionou perfeito, o erro ocorreu quando coloquei no windows 7 para testar 

Bom, no meu caso como estava querendo lançar release logo eu alterei a font usada para Ubuntu Condensed, mas.. não fico perfeito igual o outro rsrs da a impressão que esta bagunçado

**Comment by francofs** [comment]
Provavelmente versão da fonte instalada, um tem outro não tem o estilo

2017-02-01 15:34 GMT-02:00 Roberto Alves Pereira <notifications@github.com>:

**Comment by robertorp** [comment]
@francofs  eu testei instalar essas font aqui e não deu certo -> https://www.fontsquirrel.com/fonts/open-sans-condensed

to fazendo uns testes aqui 


impressão com font "Ubuntu Condensed" rsrs 
![impressaonativa](https://cloud.githubusercontent.com/assets/10251705/22519001/f08f843a-e895-11e6-9899-329c5ce361f4.png)

**Comment by FabioRoesler** [comment]
Olá amigos. A fonte que instalei foi a OpenSans-CondBold, que esta dentro da pasta NFe.Danfe.Base\Fontes.
O logotipo dimensionei para Larg 2,6 cm x Alt 1,1 cm.

**Comment by robertorp** [comment]
Fiz um update na impressão nativa, vlw!

**Comment by ffranzes** [comment]
Estou com esse erro tb, onde posso mudar a fonte?

**Comment by robertorp** [comment]
Dentro dos fontes do zeus tem as fontes.. 
basta instalar elas no windows teu clicando duas vezes.

**Comment by ffranzes** [comment]
Aconteceu o seguinte to mudando da fast para a nativa, e o pc é o 7 que está dando aquele erro da fonte. ate achei a configuração lá, mudei para "Ubuntu Condensed", porem o PDF gerado esta saindo em branco... Onde posso estar errando? alguma dica ? o XML gerou ok tudo certo
