### ISSUE TITLE
Arquivo Enderecador.cs não existe

### ISSUE THREAD

**Issue by SilverioMiranda** [ZeusAutomacao/DFe.NET#38]
Boa tarde Adenilton,

No seu ultimo commit parece estar faltando o arquivo Enderecador.cs

Obrigado :)

**Comment by adeniltonbs** [comment]
Vou checar.

**Comment by adeniltonbs** [comment]
Pronto, enviei

**Comment by SilverioMiranda** [comment]
Obrigado
