### ISSUE TITLE
dlls Fastreport

### ISSUE THREAD

**Issue by acggermed** [ZeusAutomacao/DFe.NET#381]
bom dia amigos. estou imprimindo NFe e NFCe legal, porém como demonstratção.

Tenho o Fastreport Full, e colei as dlls de mesmo nome na pasta do projeto para substituição, e ocorre
o seguinte erro:
{"Não foi possível carregar arquivo ou assembly 'FastReport, Version=2017.1.17.0, Culture=neutral, PublicKeyToken=db7268063aef458c' ou uma de suas dependências. A definição do manifesto do assembly localizado não corresponde à referência do assembly. (Exceção de HRESULT: 0x80131040)":"FastReport, Version=2017.1.17.0, Culture=neutral, PublicKeyToken=db7268063aef458c"}

como resolvo isso? o que é necessário fazer para registrar minhas dlls corretas?

aguardo, Antonio Carlos

**Comment by marcosgerene** [comment]
A versão do fast reports que você tem é qual?

Você ainda tem acesso à atualizações do Fast?

**Comment by marcosgerene** [comment]
A versão do fast reports que você tem é qual?

Você ainda tem acesso à atualizações do Fast?

**Comment by guidi** [comment]
Conflito de versão, exclua as referências das DLL do fast reports do projeto e inclua novamente apontando para as suas DLL.

**Comment by acggermed** [comment]
olá amigos... não estou conseguindo resolver sobre esse conflito das dlls... já removi do projeto e adicionar as referencias das mesmas.. mas não elimina o erro... alguém poderia me orientar?

Nossa to cansado, luta para chegar até aqui.. agora que está imprimindo aprece isso...

aguardo algum amigo responder com mais esclarecimento

**Comment by marcosgerene** [comment]
A questão é a seguinte: seu projeto já está ligada a uma versão mais recente do FastReports, tive este mesmo problema que você e não consegui resolver somente falando o que o @guidi falou, tive que baixar a nova versão do FastReport e reinstalar ele, a minha sorte é que eu comprei a menos de 1 ano, logo ainda posso baixar novas versões sem custo.
