### ISSUE TITLE
Impressão NFCe Nativo

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#382]
Olá!
Estava tentando utilizar este método e quando fui tentar imprimir apareceu um erro dizendo "A fonte Open Sans Condenced não da suporte ao estilo Regular".
Tem alguma fonte específica que devo instalar?
Podem me enviar o link para download da fonte, ou me indicar em que diretório do Zeus está a fonte?

Obrigado.
Márcio Müller

**Comment by robertorp** [comment]
Eai tudo bom?

Comigo deu esse mesmo problema, ai fiz um pull alterando algumas coisas na impressão.

Segue como ficou agora 
![impressao nativa](https://cloud.githubusercontent.com/assets/10251705/22829132/26b21c28-ef88-11e6-96f3-c13fd4f028c5.png)

O ultimo parâmetro é a font que deseja usar. Bom eu uso essa da imagem pois o mesmo esta no projeto do zeus.

**Comment by marciojmuller** [comment]
Era isso mesmo, obrigado.

**Comment by marciojmuller** [comment]
Testei a impressão na Bematech MP-4200 TH e Epson TM-T20 e deu tudo certo, alias muito bonita a impressão, parabéns a quem fez =D .
Quando fui testar a impressão na Daruma DR800 o cabeçalho ficou por cima da listagem dos itens, como segue na foto.
Alguém passou por isso e conseguiu resolver?

![whatsapp image 2017-02-10 at 15 35 58](https://cloud.githubusercontent.com/assets/15123523/22839650/7367c5c6-efb1-11e6-851b-b00d6f371a21.jpeg)

**Comment by robertorp** [comment]
Sua daruma está configurada corretamente? porque é estranho funcionar em outros modelos e na daruma não funcionar, no final das contas as posições são feitas com X é Y 
Digo toda vez que eu mexo com Daruma dr800 eu tenho que configurar ele para imprimir normal (retirar do rascunho) aqui. (antes usava o acbr monitor, agora to usando este também)

**Comment by marciojmuller** [comment]
Ummmmm não configurei nada no spooler dela...deve ser isso então, vou verificar e tentar novamente.
Valeu pela dica.

**Comment by marciojmuller** [comment]
Era esse o problema mesmo, só troquei o modo de impressão de rascunho para normal que imprimiu corretamente.

Obrigado.
