### ISSUE TITLE
Problema ao utilizar DanfeNativoNfce

### ISSUE THREAD

**Issue by homerokzam** [ZeusAutomacao/DFe.NET#383]
Alguém já conseguiu usar a class DanfeNativoNfce?

@adeniltonbs 

O que você acha de tornar o método DanfeNativoNfce.GerarNfCe protected para que possamos sobrescrever a classe DanfeNativoNfce e chamar esse método?

Obrigado.

**Comment by robertorp** [comment]
Aqui eu uso ela em produção, se observar também tem um pull request para ela para redimensionamento automático de logo. 

Mas qual seria o problema?

**Comment by homerokzam** [comment]
Estou tentando usar em um projeto de NFCe e asp.net. Está dando erro na linha:

textoProtocoloAutorizacao.Append(_proc.protNFe.infProt.nProt);

A variável _proc está null.

Outra coisa, eu não consigo fazer funcionar porque solicita uma impressora. Você usa em um projeto asp.net?

**Comment by robertorp** [comment]
Não uso em asp.net, mas isso pode ser adaptado para funcionar sem impressora e imprimir uma imagem ou sei lá enfim tem que ter a ideia de como seria o uso em asp.net para ver como funcionaria em ambas plataformas. (Estou vendo os códigos agora)

**Comment by robertorp** [comment]
Agora voltando no erro, se sua nfc-e está autorizada como normal porque ela não tem protocolo?
Digo aqui no código ta assim

![protocolo](https://cloud.githubusercontent.com/assets/10251705/23023297/fb9c8c7c-f43b-11e6-8c3d-240f1d4bc7ce.png)

edit: quando e emitido em contingência ai sim você não tem protocolo

**Comment by homerokzam** [comment]
Será que é por se tratar de ambiente de homologação?


Conseguiu colocar para funcionar no asp.net. Copie a classe e contornei o problema do protocolo, por enquanto. E estou gerando um bitmap com o fundo branco.

Se você participar do desenvolvimento da biblioteca e puder colocar essa função, ok!

Obrigado.

public class DanfeJPEG
{
    public DanfeJPEG(string xml, ConfiguracaoDanfeNfce configuracaoDanfe, string cIdToken, string csc, decimal troco = 0, decimal totalPago = 0, string font = null)
    {
      Inicializa(xml, configuracaoDanfe, cIdToken, csc, troco, totalPago, font);
    }

    public void GerarJPEG(string filename)
    {
      Bitmap bmp = new Bitmap(500, 1000);
      Graphics g = Graphics.FromImage(bmp);
      g.Clear(Color.White);
      this.GerarNfCe(g);

      bmp.Save(filename, ImageFormat.Jpeg);
    }

    private string _cIdToken;
    private string _csc;
    private NFeZeus _nfe;
    private nfeProc _proc;
    private decimal _troco;
    private Image _logo;
    private decimal _totalPago;


....



}

**Comment by robertorp** [comment]
Não é por se tratar de ambiente de homologação
O negocio é porque você não montou o xml de Autorizacao
Este xml você pega o retorno do envio e monta ele na mão o componente não oferece nada para isso ainda. (Na minha opinião deveria ter hehe)

Por isso não tem o proc , porque você não montou o xml de autorizacao quando recebeu a resposta da autorização da sefaz.

**Comment by homerokzam** [comment]
@robertorp 

Entendi. Irei verificar como fazer isso. Você tem algum exemplo?

Obrigado.

**Comment by robertorp** [comment]
![autorizado](https://cloud.githubusercontent.com/assets/10251705/23031508/5a9208bc-f458-11e6-8d91-e66719379c46.png)

informações do objeto nfeproc são retornados pela sefaz

Olha essa foto para exemplo e oque tenho implementado aqui no sistema.
