### ISSUE TITLE
[MDFe] - Valor da Carga

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#384]
[mdfe_assinado.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/781015/mdfe_assinado.zip)

Ao enviar este mdfe recebo o seguinte erro:

> Erros da validação : The 'http://www.portalfiscal.inf.br/mdfe:vCarga' element is invalid - The value '41009.2' >is invalid according to its datatype 'http://www.portalfiscal.inf.br/mdfe:TDec_1302' - The Pattern constraint >failed.

**Comment by robertorp** [comment]
Boa tarde, no erro diz que '41009.2' é invalido pois realmente é invalido já no xml seu está com 41009.21
Ai fiz um teste em minha aplicação

[transmitido.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/781069/transmitido.zip)
transmiti e foi tudo ok... chegou o mesmo valor digitado chegou no xml e foi transmitido

**Comment by marcosgerene** [comment]
Eu substitui .2 por. 21 e deu certo, mas tava sem o 1 tava 41009.2 no xml

**Comment by robertorp** [comment]
Oque acha da biblioteca formatar esses valores automaticamente?

**Comment by marcosgerene** [comment]
seria excelente, porque se eu passo um decimal pro componente, como isso poderia ser formatado do lado do developer?

como funciona o NFe hoje? o NFe funciona normalmente, seria interessante seguir um padrão

**Comment by robertorp** [comment]
Sim, vou modificar a mdf-e para seguir o mesmo padrão, acabei de verificar na nf-e e usa arredondamento onde tem valores decimais 

`public decimal vICMS
        {
            get { return _vIcms.Arredondar(2); }
            set { _vIcms = value.Arredondar(2); }
        }`
