### ISSUE TITLE
[DÚVIDA] Métodos de chamadas WebService congelam a aplicação - Threads

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#385]
Boa tarde galera.

Todos os métodos de chamadas dos WebServices congelam a aplicação. Teria como se fazer uma thread para que uma barra de status, por exemplo, não travasse, mas demostrasse para o usuário que a NF-e está sendo transmitida,por exemplo?

**Comment by robertorp** [comment]
No caso acho que isso é individual. Você deve implementar essa parte. Mas seria interessante se tivessem os dois métodos um Assíncrono é outro Síncrono.

**Comment by FabioHenriqueMF** [comment]
ou teria outra maneira de não travar a aplicação?

**Comment by guidi** [comment]
Acredito que essa parte deveria ser tratada pelo desenvolvedor que está consumindo a biblioteca.

**Comment by robertorp** [comment]
.net 4.5 você pode usar algo +- assim...  aqui uso assim minha aplicação é desktop wpf.


private async Task TransmitenNFe()
{
    await Task.Run( () =>
    {
        // processo nf-e 
    });
}

**Comment by FabioHenriqueMF** [comment]
certo, mas e os processos que a biblioteca hoje realiza, não tem que virar async  também?
