### ISSUE TITLE
Entender um pouco mais de NfeConsulta2 Protocolo

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#386]
Bom oque quero e entender um pouco mais sobre os retornos relevantes dele que realmente são tratados no sistema.

217 NF-e não ta na base de dados da Sefaz

100 NF-e transmitida com sucesso 

204 Chave idêntica a uma que já foi emitida e autorizada pela Sefaz

509 Duplicidade de NF-e com diferença na chave de acesso.

Existe uma de notas denegadas que esqueci qual é , 
que inclusive ele autoriza a NF-e correto? mas ta denegada. Bom se alguém poder explicar
melhor como funciona essa. E qual a melhor maneira de resolver esse caso.

**Comment by adrbarros** [comment]
Nota fiscal denegada. Hoje para sanar esse problema utilizamos um serviço de saneamento de cadastro de clientes e fornecedores, assim no momento da emissão de uma NFe é verificado se o CNPJ dos destinatários estão habilitados perante a Receita Federal e Sintegra.

Texto retirado de um site:
A denegação da NF-e é o processo em que a Secretaria de Fazenda não autoriza que a operação à qual a nota se refere seja realizada. Uma vez denegada, a numeração da nota não pode mais ser utilizada. É como se a nota tivesse tido validade jurídica, mas o Fisco entendeu que ela não está apta a acobertar a operação a que se refere. Além do impacto para o negócio, a empresa se mantém obrigada a guardar os arquivos XML das notas denegadas pelo prazo decadencial.
No momento em que o emissor tenta autorizar a NF-e, o Fisco do emitente fará as verificações usuais do processo de autorização e, somente no momento final, fará a crítica para saber se a nota é passível ou não de denegação. Se houver alguma irregularidade no cadastro do destinatário, a Secretaria da Fazenda informará a denegação da nota, inviabilizando a operação.
Quais os riscos de operar com cadastros inconsistentes?
Operar com fornecedores ou clientes inaptos perante a Receita Federal, ou inabilitados no Sintegra, pode ocasionar a devolução de créditos de impostos, e multas por lançamento de créditos inválidos. Além disso, as empresas podem incorrer em falhas nas obrigações acessórias, também passíveis de multas e outras sansões legais pelo Fisco.
Nem é preciso mencionar que um cadastro inconsistente vai gerar inúmeros transtornos na retificação EFD ICMS/IPI, EFD Contribuições e ECD, na validação dos arquivos enviados, no estouro do prazo legal para cumprimento das obrigações e em prejuízos financeiros com processos de denúncia voluntária, custo de advogados, multas do Fisco, etc.
Além de tudo isso, é bom lembrar que a Certificação Digital que dá validade jurídica aos arquivos enviados para o SPED torna-se a assinatura das eventuais irregularidades cometidas, muitas vezes por desconhecimento do risco pelo contribuinte. Por isso, é fundamental se assegurar de que todos os cadastros de clientes e fornecedores estejam aptos a serem lançados no sistema.
Como garantir a consistência cadastral?
Se você possui dois ou três fornecedores, e meia dúzia de clientes, até consegue fazer o saneamento cadastral de forma manual. Mas empresas com centenas de clientes e fornecedores não podem perder tempo com isso, e nem se dar ao luxo de ter seus documentos legais denegados a todo momento.
Por este motivo, milhares de empresas no país já adotam o Saneamento de Cadastro Cliente e Fornecedores oferecido pela IOB. Simples, rápido e seguro, o SCF da IOB é a garantia de atualização e complementação de informações cadastrais das empresas, através de consultas aos sites da RFB e Sintegra.
No SCF são pesquisados os dados cadastrais atualizados e a idoneidade do cadastrado junto aos órgãos consultados. Além disso, a solução identifica o regime tributário do contribuinte, e os fornecedores obrigados à emissão de NF-e.
