### ISSUE TITLE
Lote NFe.

### ISSUE THREAD

**Issue by raul1934** [ZeusAutomacao/DFe.NET#388]
Bom dia, o que seria o campo idLote?

**Comment by nelsonasousa** [comment]
Eu sou novo aqui mas, esse não seria o número do lote no caso de enviar várias Nfes?.
Eu informo inclusive qdo do envio de NFe única.

**Comment by raul1934** [comment]
Desculpe a ignorância, mais de onde vem esse numero?

**Comment by raul1934** [comment]
Consegui achar.
![image](https://cloud.githubusercontent.com/assets/16276131/23899766/262181f6-0895-11e7-908f-a93084dd480b.png)
