### ISSUE TITLE
Consulta Cadastro - nao catalogado

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#39]
Bom dia adenilton,

vc ja viu o seguinte erro quando consultamos o consulta cadastro? de Erro nao catalogado...

uso o o cnpj 01.441.646/0001-77 para o estado do CE

obrigado

**Comment by celinolimac** [comment]
adenillton, vi aqui aqui q e manutenção  em homologação.. produção ta de boa.. valew

**Comment by adeniltonbs** [comment]
Ok, celino. Eu ia dar uma olhada agora.
