### ISSUE TITLE
CTe - Impressão em Fast Reports

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#392]
Boa noite,

Estou com 2 problemas:
1. O método cteProc.CarregarDeArquivoXml() não está funcionando mas consegui contornar da seguinte forma:
> cteProc = FuncoesXml.ArquivoXmlParaClasse<CTeProc>(xml);

2. Estou registrando os dados do objeto assim como fiz com o MDFeRetrato mas não estou tendo sucesso pois o objeto CTe  dentro do cteProc aparece sem o infCTe.
`using CTeProc = CTe.Classes.cteProc;`

![objeto](https://cloud.githubusercontent.com/assets/15945003/24476966/b082778e-14ab-11e7-9458-a16c41381fdb.png)
![fastreports](https://cloud.githubusercontent.com/assets/15945003/24476974/b7570ea8-14ab-11e7-92b9-af9d7f5b7bea.png)

**Comment by robertorp** [comment]
@marcosgerene  aqui somente alterei o método que carrega o xml e funcionou 
editado: levando em consideração que deve carregar as configurações antes, pois dentro dos objetos a uso delas para definição do que sera executado... exemplo 
na data de emissão no (ide) tem um proxy que tem um if se versão3 faz dada com utc... se versão2 faz data sem utc
![marcosgenere](https://cloud.githubusercontent.com/assets/10251705/24480007/92a9523e-14b8-11e7-983b-5e3e6d60f619.png)

**Comment by marcosgerene** [comment]
![cteproc](https://cloud.githubusercontent.com/assets/15945003/24582705/cfdfc246-170b-11e7-864c-a51f21494d44.png)

Fiz alguns ajutes no cteProc para ficar igual ao MDFeProc que deu certo e mesmo assim não apareceu no FastReports... no objeto carrega certinho mas não aparece a tag infCTe no Fast...

Salva a gente @rftd rs

--------

PS: Criei vergonha na cara e "aprendi" a mexer no github pelo visual studio.. me aguardem agora... rsrs

**Comment by robertorp** [comment]
Obrigado pela contribuição!
