### ISSUE TITLE
Avanço de numeração da NFC-e / NF-e e outros documentos

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#397]
Como vocês avançam essa numeração?

Abri o tópico somente para nos vermos a melhor forma de efetuar isso visando a minimização de erros de duplicidade ou o pulo de alguma numeração.

Hoje no meu sistema e assim

NF-e/CT-e/MDF-e -> ao abrir salvar os dados iniciais de uma nota eu adiciono a numeração da mesma já.
Quando for transmitir se der duplicidade então eu tenho uma opção de (button) para alocar próximo número  e tentar novamente. Se pular um numero valido, bom já era já foi.. não tem volta. (Oque me leva a inutilizar o número que foi pulado)

NFC-e -> Ao abrir uma venda no sistema e adicionado a numeração da mesma, ao tentar transmitir se der duplicidade já era. (Unica possibilidade de dar duplicidade é na hora da implantação do sistema que o cliente deve passar o número da ultima NFC-e emitida por ele... se o cliente passar errado o cara que ta implantando o sistema irá identificar o erro e logicamente ele deve e irá ajustar o erro.)

editado:
problema na NFC-e .. Cliente abre uma venda.. e cancela.. bau bau numeração (somente inutilizando tb) venda que não foi transmitida 

Ai queria saber qual a melhor forma de conduzir isso. Oque vocês indicam para fazer, para evitar duplicidades e inutilizações.

Lembrando que NF-e/MDF-e/CT-e existe concorrência ou seja.. três pcs emitindo esses documentos no mesmo tempo com a mesma série. 
Já o NFC-e não tem problema de concorrência. Pois cada terminal NFC-e tem sua série própria.

**Comment by marcosgerene** [comment]
Boa tarde,

Eu controlo via Generator (uso Firebird), crio generators, crio eles dessa forma: gera_id_empresa_modelo_serie
ex: gera_id_1_55_1
     gera_id_1_65_1

Quando vou fazer uma nova nota eu incremento no generator  e recupero o valor incrementado em uma variável. 
Ex: select gen_id(gera_id_55_1, 1) from rdb$database;

Quando o usuario cancela (aborta a operação e não cancela a nota) eu volto a numeração (se não existir uma nova nota ja criada entre ele "requisitar" o novo numero e salvar a nota).

Só acontece de pular numero se tiver dois usuarios emitindo ao mesmo tempo e o primeiro que requisitou um numero abortar (não posso voltar a numeração visto que o o outro já requisitou), isso é bem raro e mesmo assim eu permito que o usuário ajuste de forma manual o generator para "aproveitar" este numero.

Abraços

**Comment by jeisonmp** [comment]
Abra uma transação amigo, se falhar, a transação cancela tudo que foi feito. Isso se chama atomicidade. Abraços!
