### ISSUE TITLE
Ajustes - CTe

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#399]
Boa noite,

Estou implementando o CTe, vou abrir a insue aqui só para não esquecer de abrir depois e ir anotando o que eu encontrar de inconsistencia

```CTe.Classes.Informacoes.infCTeNormal.docAnt```

Aqui o objeto "emiDocAnt" deveria ser uma lista de emissores não deveria?
![emitdoc](https://cloud.githubusercontent.com/assets/15945003/24593033/7be2e9a8-17f5-11e7-9001-f678352faeff.png)

```CTe.Classes.Informacoes.Identificacao.enderToma```

Aqui cMun e CEP não deveriam ser long ao invés de string para manter o padrão?

-------

PS: Ainda estou implementando, se surgir mais alguma observação edito aqui

**Comment by robertorp** [comment]
Vou estar ajustando isso mais anoite. Somente ir postando que os ajustes vão aparecer =)

**Comment by marcosgerene** [comment]
@robertorp 

Provavelmente eu mesmo farei o PR, pode deixar... eu estou fazendo várias coisas ao mesmo tempo, hoje por exemplo nem mexi com o CTe, assim que eu terminar mando o pull pra análise.

Abraços

**Comment by robertorp** [comment]
beleza, porque ai foco mais na mdf-e 3.0

edit: mas qualquer coisa se você não fizer eu faço, obrigado

**Comment by marcosgerene** [comment]
```CTe.Classes.Informacoes.infCTeNormal.infCarga```

![atual](https://cloud.githubusercontent.com/assets/15945003/24670346/0a4d2e52-1944-11e7-9406-352b8d01aa01.png)

As informações da carga não tem os grupos infDoc e docAnt em nenhuma das duas versões.

![manual](https://cloud.githubusercontent.com/assets/15945003/24670353/0dff9832-1944-11e7-9256-361cd5695154.png)

**Comment by robertorp** [comment]
Agora são três versões, temos o CTeOs no final do 3.0 você vera ele, e ele muda o layout bastante do 2.0 ou 3.0 

no caso vamos dizer que temos duas verões do CTe 3.0

**Comment by marcosgerene** [comment]
Entendi, vou dar um UNDO aqui então...

**Comment by robertorp** [comment]
Uma outra observação que tinha me esquecido

No layout 3.0 pode ter atributos obrigatórios
No layout 3.0 OS esses atributos não existem 

Logo então deixei os atributos opcionais por isso

**Comment by vasisti** [comment]
Ola Roberto tudo bem, estou tendo este erro ao gerar CTeOS.

 An unhandled exception of type 'System.Exception' occurred in CTe.Utils.dll

Additional information: Erros da validação : The 'http://www.portalfiscal.inf.br/cte:mod' element is invalid - The value '67' is invalid according to its datatype 'http://www.portalfiscal.inf.br/cte:TModCT' - The Enumeration constraint failed.

tem alguma ideia do que pode ser?

**Comment by robertorp** [comment]
Não temos nada ainda garantido para CTeOS, precisaria de uma revisão de tudo. E testes.

**Comment by marcosgerene** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/502

**Comment by mvtaraujo** [comment]
Pessoal sou novo aqui no projeto, gostaria de saber se alguem está emitindo CTeOS pelo Zeus?

**Comment by marcosgerene** [comment]
@mvtaraujo por favor abra uma nova issue para sua questão.
