### ISSUE TITLE
Implementar impressão de Danfes

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#4]

**Comment by robertocvsiqueira** [comment]
Adenilton,

Você sabe de alguma dll que imprima em PDF o DANFe da NFC-e a partir do XML?

Obrigado desde já,
Roberto.

**Comment by robertocvsiqueira** [comment]
Já descobri como fazer. Vou usar o rdlc do Visual Studio mesmo. Obrigado!

**Comment by MoacirCarlos** [comment]
Roberto,

Se conseguir uma solução poderia dar o caminho das pedras?

Obrigado.

**Comment by SilverioMiranda** [comment]
Porque não usar a dll do fabricante, Daruma, Bematech, etc.. e gerar o comprovante na mão? É muito mais simples que querer gerar relatório em outro programa depois enviar. E sem contar que essas impressoras para impressão Spooler ficam com qualidade inferior

**Comment by MoacirCarlos** [comment]
Miranda,

Para no NFC-e eu concordo com você, a daruma fornece uma dll muito boa para interagir com as impressoras, porém para NF-e não existem soluções report para abrir o XML e gerar o DANFE.

**Comment by adeniltonbs** [comment]
Você pode usar o ACBrNFeMonitor para isso. Por enquanto estou usando ele, em breve devo adicionar o suporte a impressão direto na biblioteca.

**Comment by robertocvsiqueira** [comment]
É possível usar o ACBRMonitor para imprimir DANFe de NFC-e?

**Comment by adeniltonbs** [comment]
É sim, baixe a versão mais recente e veja que na aba "DANFe/DACTe/DAMDFe", tem uma sub-aba chamada NFC-e.

**Comment by adeniltonbs** [comment]
This issue was moved to ZeusAutomacao/DFe.NET#4

**Comment by adeniltonbs** [comment]
This issue was moved to ZeusAutomacao/DFe.NET#4
