### ISSUE TITLE
Ajuste Ortográfico - Extenção -> Extensão

### ISSUE THREAD

**Issue by alexmurari** [ZeusAutomacao/DFe.NET#401]
Olá,
algumas classes/pastas do projeto estão com ortografia errônea.

A correta ortografia de "extenção" é "extensão".

Se achar mais alguma postarei aqui.

Obrigado pelo excelente, projeto.  :)

Att.

**Comment by robertorp** [comment]
fiz uma correção aqui, https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/402

Obrigado pela contribuição!

Qualquer coisa abra essa ou uma nova issue novamente
