### ISSUE TITLE
CTe - Pegar retorno

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#406]
Boa noite a todos,

No MDFe, em MDFe.Servicos.RetRecepcaoMDFe.ServicoMDFeRetRecepcao consigo pegar o recibo de pelo numero, no CTe não achei nada disso, somente no WSDL e a forma que pega o recibo não é com o número do recibo do envio, acredito estar fora dos padrões se estiver implementado e infelizmente não consegui achar...

**Comment by robertorp** [comment]
Bom dia,
 O serviço de Recepção (pagina 34 do manual 3.00), ele retorna 
o recibo (retEnviCTe)

CTe.Classes.Servicos.Recepcao.retEnviCte : RetornoBase {
...
}

A classe ServicoCTeRecepcao faz o envio do CT-e (Lote de CT-e) 
e retorna os recibos.

Na pagina do manual 3.00 74 temos o CteRetRecepcao

Com layout de entrada
versao
tpAmp
nRec (numero do recibo retornado pelo CteRecepcao)

que retorna o objeto CTe.Classes.Servicos.Recepcao.Retorno.retConsReciCTe

para fazer a consulta do Recibo do lote enviado usar a classe 
CTe.Servicos.ConsultaRecibo.ConsultaReciboServico (numero do recibo no construtor)
