### ISSUE TITLE
A solicitação anulada, não foi possível estabelecer um canal seguro para SSL/TLS

### ISSUE THREAD

**Issue by juhpetri** [ZeusAutomacao/DFe.NET#408]
Boa tarde @adeniltonbs !

Estou usando o Zeus na minha aplicação e estou tendo algumas situações que não consegui solucionar, e gostaria de saber se já se deparou com algo do tipo.

Baixei o projeto Zeus e compilei, a partir dai peguei as dll geradas e adicionei ao meu projeto.

Ao compilar meu projeto, consigo autorizar nfce/nfe assim como consumir todos os recursos do aplicativo,
inclusive debugar os processos realizados pelo zeus.

Minha aplicação é via WebApi e ao publicar (IIS) para teste o sistema não consegue acessar essas dll o que me retorna o erro relatado , inclusive quando chamo a rotina de autorização, a exception `System.Exception: System.Net.WebException: A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.    em NFe.Servicos.ServicosNFe.NFeAutorizacao`

`// esse é o modo como eu chamo o servico
 var autorizacao = servicoNFe.NFeAutorizacao(dto.IdLote, IndicadorSincronizacao.Sincrono, new List<Z.NFe> { _nfe });`

Descobri que nem acessa a dll da seguinte forma, peguei meu projeto e coloquei no computador que estava dando o problema e com as dlls que foi publicado.

Abri meu projeto no visual studio e o projeto do zeus, fiz o mesmo processo e fui comparando todos os atributos dos objetos, no Zeus conseguir entrar no servico de autorizacao, porem no meu projeto não acessou, assim peguei as dll que eu estava usando no zeus e coloquei no meu projeto, ai sim consegui acessar, peguei essas mesmas dlls e tentei publicar em uma nova versão sem rodar pelo visual studio e o erro retornou, já encontrou algo parecido, já tentei todas alternativas que imaginei mas não consegui nenhum sucesso.

Fico no aguardo, atenciosamente!

**Comment by rftd** [comment]
Falta a cadeia de certificados no servidor onde esta o IIS, sem a cadeia de certificados o certificado não é considerado valido por isto da este erro, maioria do erro deste tipo é validação do certificado que deu errado.
Para corrigir basta instalar a mesma na maquina do servidor.

**Comment by juhpetri** [comment]
Os certificados estão todos corretos, foram todos conferidos e adicionado via console {Windows + R = > mmc} a lista de certificados confiáveis, o problema realmente é no acesso a dll, visto que pela propria aplicação do Zeus não tenho nenhum problema ao gerar nfe/nfce, mas quando adiciono as dll como referencia no meu projeto as mesmas não ficam acessíveis

**Comment by rftd** [comment]
Então você não instalou os certificados no usuario do IIS e a dll não esta achando eles.

**Comment by robertorp** [comment]
Conseguiu resolver? E bom sabermos para termos na base de conhecimento.
Não posso ajudar pois nunca mexi com servidor IIS profissionalmente, somente algumas brincadeiras (estudo).

**Comment by juhpetri** [comment]
Consegui resolver sim, é permissão as pastas onde ficam localizados os arquivos de certificados criptografados. existem duas alternativas: 
a primeira funcionou no Windows Server:
```
 - abrir uma janela do Prompt de Comando, como Administrador
 - CD pra pasta C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\
 - DIR /A (para listar os arquivos)
 - Dar permissão pra conta do IIS, para os certificados necessários, usando icacls
icacls C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\d6d986f09a1ee04e24c949879fdb506c_8b2019ec-d7f9-4197-8270-f325c1323044 /grant "IIS AppPool\DefaultAppPool":R
arquivo processado: C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\d6d986f09a1ee04e24c949879fdb506c_8b2019ec-d7f9-4197-8270-f325c1323044
Processados com sucesso 1 arquivos; falha no processamento de 0 arquivos

Esse comando dá permissão de leitura à conta "IIS AppPool\DefaultAppPool" para o arquivo especificado. O ideal é ver quais arquivos existem na pasta, e após adicionar o certificado na conta do computador, ver qual arquivo foi adicionado, e dar permissão apenas neste. Eu não encontrei outra forma de saber qual arquivo pertence a qual certificado.
```
A segunda e que funcionou pra mim que estou usando o Windows 10 foi braçal:
```
Acessar o seguinte diretório:
C:\ProgramData\Microsoft\Crypto\RSA\
Adicionar os usuários do IIS a permissão da pasta "MachineKeys" e dar permissão de leitura.
```
Feito isso consegui usar o sistema normalmente.

**Comment by robertorp** [comment]
Que bom que resolveu! Obrigado! Vou fechar a issue, qualquer coisa reabra ela ou abra uma nova. obrigado

**Comment by dalpogetto** [comment]
@juhpetri Boa noite, não consigo utilizar a sua solução para dar permissão nas pastas e usuários do IIS.
Tanto a opção 1 quanto a opção 2 estão dando **ACESSO NEGADO**.
Nao consigo dar permissão de leitura, e meu usuário é administrador.
Alguma ideia pra me ajudar ?

**Comment by juhpetri** [comment]
Bom dia! @dalpogetto , sugiro então realizar este procedimento manualmente, e não pelo MSDOS.
Acesse a pasta e verifique qual o proprietario da mesma, se não for o administrador altere.

Adicione o usuário Todos e de permissão total, assim irá reclamar alguns certificados com "Acesso negado", porém o certificado instalado por vc passará a ter a permissão.

Verifique também se quando instala o certificado digital, o mesmo é reconhecido no "Certificados" em Opções da internet, se não for, será necessário algumas configurações adicionais

**Comment by dalpogetto** [comment]
@juhpetri juhpetri Fiz todos os procedimentos, mas nao funciona a consulta pra minas Gerais.
Os certificados aparecem na lista de certificados, Coloquei a permissao TODOS para a pasta MachineKeys.
Se puder me dar uma luz agradeceria muito.

**Lista de Certificados**
![certificados](https://user-images.githubusercontent.com/31019857/30354701-6b1a0f72-9804-11e7-9df6-b62b9b34b92e.JPG)

**Consulta Cadastro MG (Nao funfa por causa dos certificados)**
![consultacadmg](https://user-images.githubusercontent.com/31019857/30354703-6b1e4024-9804-11e7-9567-24893b72262c.JPG)

**Consulta Cadastro SP (Funciona perfeitamente, mas nao usa os certificados)**
![consultacadsp](https://user-images.githubusercontent.com/31019857/30354702-6b1a9032-9804-11e7-90fa-6075518491be.JPG)

**Permissoes na Pasta**
![machinekeystodos](https://user-images.githubusercontent.com/31019857/30354704-6b436796-9804-11e7-8df8-0923dff98303.JPG)

**Comment by leandrossantos** [comment]
@dalpogetto acredito que você tenha instalados os certificados de MG na pasta errada o correto seria na pasta "Autoridades de Certificados de raiz Confiáveis"

Veja na imagem abaixo.

http://prntscr.com/gkgkq8

**Comment by dalpogetto** [comment]
@leandrossantos Cara NEM acredito que funcionou. Me tirou um peso das costas. Muito obrigado a todos e desculpa o incomodo.

**Comment by juhpetri** [comment]
Que bom que deu certo. qualquer coisa avise por favor.
