### ISSUE TITLE
Uso da lib

### ISSUE THREAD

**Issue by faelmg18** [ZeusAutomacao/DFe.NET#409]
Pessoal boa tarde! fiz o download da biblioteca e executei a aplicação teste, porem não está gerando a nota. p erro que da na hora de fazer a consulta pela opção  Status do serviço é : não disponível para UF MG no ambiente de homologação. O erro é mostrado pra qualquer estado ou para qualquer ambiente tanto de homologação ou produção. Será que alguém pode me ajudar? Valeu

**Comment by robertorp** [comment]
Boa tarde, Muda a versão do serviço para a versão aceita pelo seu UF.

**Comment by robertorp** [comment]
@faelmg18  Deu tudo certo?

**Comment by robertorp** [comment]
Qualquer coisa re-abra a mesma ou crie uma nova. Obrigado.

**Comment by faelmg18** [comment]
Então, na verdade não funcionou, mais vimos que o que realmente precisamos e gerar uma NF-e pelo que vi a lib não tem. Mais mesmo assim obrigado pelo help.

**Comment by adeniltonbs** [comment]
@faelmg18 Bom dia, conforme o @robertorp mencionou, você tem que configurar a aplicação de demonstração de uso da biblioteca, conforme as versões disponíveis para sua UF.

A biblioteca funciona para UF's de todo o país. 

Dê uma olhada nos serviços e versões disponíveis para MG em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#MG (produção) e http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#MG (homologação)

Ex:
![image](https://cloud.githubusercontent.com/assets/6733483/25388131/4e1a9146-29a3-11e7-9140-80f6256c63d4.png)

Depois de configurado, olhe o resultado da consulta do status do serviço para essa UF:
![image](https://cloud.githubusercontent.com/assets/6733483/25388171/72081ab0-29a3-11e7-87c7-88ca8c384984.png)

**Comment by adeniltonbs** [comment]
Para configuração da aplicação de demonstração de uso, dê uma olhada nesse tutorial:  https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114

Mais informações em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki

**Comment by faelmg18** [comment]
cara top, valeu de mais pela ajuda!!!

**Comment by BrianLima** [comment]
Infelizmente durante a mudança do repositório suas Gists acabaram se perdendo :(
