### ISSUE TITLE
Função RecepcaoEventoManifestacaoDestinatario receber uma lista de chaveNFe.

### ISSUE THREAD

**Issue by joaoluizsouza** [ZeusAutomacao/DFe.NET#411]
Namespace: NFe.Servicos
Classe: ServicosNFe
Metodo: RecepcaoEventoManifestacaoDestinatario

Possibilidade de fazer a manifestação de varias notas de uma vez. O servico aceita até 20 eventos.

**Comment by joaoluizsouza** [comment]
Posso fazer a alteração??
Preciso passar uma lista de (int sequenciaEvento, string chaveNFe, TipoEventoManifestacaoDestinatario tipoEventoManifestacaoDestinatario) onde posso cria uma classe com esses atributos?

**Comment by robertorp** [comment]
Não seria melhor criar outro método para isso não? Pois temos desenvolvedores que já usam esse método, basicamente você reaproveitaria bastante coisa do método atual criando algum método e classe para oque der para reaproveitar.

**Comment by joaoluizsouza** [comment]
A ideia é essa mesmo! A duvida é: eu crio um método com uma lista de chaveNFe e todas tem que ser do mesmo tipo TipoEventoManifestacaoDestinatario ou cria uma classe com as propriedades que preciso. Caso precise de criar está classe onde é o melhor lugar ?
