### ISSUE TITLE
[NFe.AppTeste] - Potencial falha no produto

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#412]
Olá,
estou estudando o componente para utilizá-lo em um desenvolvimento próprio.
Identifiquei uma potencial falha em NFe.AppTeste no método GetIdentificacao neste passo cUF = estado.SiglaParaEstado(_configuracoes.Emitente.enderEmit.UF), o enderEmit está nulo apesar de _configuracoes.EnderecoEmitente não ser nulo.
Entendo que o arquivo MainWindow.xmal.cs deve está sendo usando somente neste namespace para testes. Entretanto, fiquei receoso se essa referência entre Emitente e EnderecoEmitente  não esteja sendo feita corretamente no core do componente.

**Comment by robertorp** [comment]
Essa configurações e somente do appTeste se tiver alguma falha é somente no app testes
Irei analisar o mesmo se possivel me diga os passos para chegar no nulo aqui

**Comment by Guaze** [comment]
Por exemplo, btn  "Criar e Enviar 2.0" .
- Pede número da nota;
- Pede Id lote;
- Depois GetNf();
- GetInf();
. . .
- GetIdentificacao();

No passo, cUF = estado.SiglaParaEstado(_configuracoes.Emitente.enderEmit.UF) neste momento enderEmit está nulo.

**Comment by robertorp** [comment]
você cadastrou os dados no appTeste? Digo preencheu eles?
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/114

**Comment by Guaze** [comment]
Acredito que a falha está no loading do arquivo configução.xml para montar o objeto emit e enderEmit que não está os correlacionando.

**Comment by robertorp** [comment]
Domingo\Sábado agora vejo isso.

**Comment by Guaze** [comment]
Encontrei o problema do exemplo em NFe.AppTeste.

Está nessa parte do código.

protected virtual infNFe GetInf(int numero, ModeloDocumento modelo, VersaoServico versao)
        {
            var infNFe = new infNFe
            {
                versao = versao.VersaoServicoParaString(),
                ide = GetIdentificacao(numero, modelo, versao),
                emit = GetEmitente(),
                dest = GetDestinatario(versao, modelo),
                transp = GetTransporte()
            };

É só inverte a posição do "ide" com "emit" porque o bind de "enderEmit" é feito aqui.

protected virtual emit GetEmitente()
        {
            var emit = _configuracoes.Emitente; // new emit
            //{
            //    //CPF = "80365027553",
            //    CNPJ = "32876302000114",
            //    xNome = "FIOLUX COMERCIAL LTDA",
            //    xFant = "FIOLUX COMERCIAL LTDA",
            //    IE = "270844821",
            //};
            emit.enderEmit = GetEnderecoEmitente();
            return emit;
        }

Aí da erro neste linha "ide = GetIdentificacao(numero, modelo, versao),".
