### ISSUE TITLE
Novas versões

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#413]
Olá pessoal,

Acabei de baixar via Nuget este componente para o meu projeto.
As novas versões devo sempre esperar via Nuget? ou há um repositório em algum lugar?

**Comment by robertorp** [comment]
@Guaze  Boa noite,
Eu uso as do nuget e mantenho o nuget do projeto. Ou seja não precisa se preocupar sempre vai ta atualizado ok

**Comment by Guaze** [comment]
Obrigado!!
