### ISSUE TITLE
Como começar . . . .

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#414]
No exemplo em NFe.AppTeste tem a classe ConfiguracaoApp que pertence exatamente a class library de teste, ou seja, não faz parte do conteúdo que baixei do Nuget.
Como devo começar o uso do componente?

**Comment by robertorp** [comment]
Bom dia @Guaze, 
comece pelo Wiki do projeto https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki aqui tem informações de como começar com o Zeus.

Editado: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/409 essa issue ajuda a iniciar também

**Comment by Guaze** [comment]
Ok. Obrigado!
