### ISSUE TITLE
Versão Nuget incompatibilidade com exemplo

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#415]
A versão disponibilizada no Nuget (1.01.510) é incompatível com o exemplo da class library NFe.AppTeste porque a class ConfiguracaoApp.cs utiliza a class ConfiguracaoDanfeNfce.cs que pertence a class library NFe.Danfe.Base; e esta não está presente no conteúdo do Nuget.

**Comment by robertorp** [comment]
Bom dia @Guaze,
nada relacionado a impressão existe no nuget do projeto hoje,
somente emissão de documentos, já ouve outros pedidos para ter as impressões no nuget, mas ai temos questões de saber mais detalhadamente sobre o licenciamento do fastreports se podemos disponibilizar, e mesmo assim tem questões de referencias a dll do fastreports se disponibilizarmos quando você baixar via nuget e mandar imprimir vai aparecer DEMO na folha, enfim e algo que tem que ser melhor pensado.

**Comment by Guaze** [comment]
Como as pessoas que usam esse componente fazem para emitir as NFCe nos software desenvolvidos por elas utilizando este?

**Comment by robertorp** [comment]
Sua issue aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/414 de como começar vai ajudar a você a emitir NFC-e ou NF-e , pesquise nas issues também mais pessoas tiveram essa mesma duvida.

**Comment by Guaze** [comment]
Ok. Obrigado!
