### ISSUE TITLE
Problema ao implementar WEBSERVICE de NFCe do MS - The underlying connection was closed: Could not estabilish trust relationship for the SSL/tls secure chanel

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#420]
Estou tentando implementar a NFCe com o serviço do MS e está dando problema  na consulta de status tanto nfe como NFCe. Dá a impressão que é problema no certificado aqui da sefaz MS.

"The underlying connection was closed: Could not estabilish trust relationship for the SSL/tls secure chanel."

vejam o erro do crome o o https do endereço.
![salvar_url_ms](https://cloud.githubusercontent.com/assets/7529472/25535796/bc461588-2c0e-11e7-9743-c76a201862d2.PNG)

**Comment by robertorp** [comment]
Oque vc faz para chegar nesse erro? Digo os passos ?

**Comment by rcoproc** [comment]
+ou- na linha 480 do Enderecador.cs

Acrescentei estas linhas(region NFE) para testes com a homologação , ai na hora de consulta o status do MS é que dá o problema.:

foreach (var emissao in emissaoComum)
            {
                #region NFE
                if (emissao != TipoEmissao.teEPEC)
                    endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve100, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/RecepcaoEvento"));
                endServico.Add(new EnderecoServico(ServicoNFe.NfeRecepcao, VersaoServico.ve200, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRecepcao2"));
                    versaoDoisETres.Select(versao => new EnderecoServico(ServicoNFe.NfeStatusServico, versao, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2")));
                endServico.Add(new EnderecoServico(ServicoNFe.NFeAutorizacao, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeAutorizacao"));
                endServico.Add(new EnderecoServico(ServicoNFe.NFeRetAutorizacao, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetAutorizacao"));
                #endregion
                #region NFCe
                endServico.Add(new EnderecoServico(ServicoNFe.NFeAutorizacao, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeAutorizacao?wsdl"));
                endServico.Add(new EnderecoServico(ServicoNFe.NFeRetAutorizacao, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetAutorizacao?wsdl"));
                endServico.Add(new EnderecoServico(ServicoNFe.NfeInutilizacao, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://nfe.fazenda.ms.gov.br/producao/services2/NfeConsulta2?wsdl"));
                endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/RecepcaoEvento?wsdl"));
                endServico.Add(new EnderecoServico(ServicoNFe.NfeStatusServico, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2?wsdl"));
                endServico.Add(new EnderecoServico(ServicoNFe.NfeConsultaProtocolo, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MS, ModeloDocumento.NFCe, "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2?wsdl"));
                #endregion
            }

**Comment by robertorp** [comment]
Esse codigo de NFC-e para MS ? você adicionou ele né? Não estou achando ele no master, e inclusive tem um pull sobre isso https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/422 que estou analisando junto com o @marcosgerene  ele esta com cliente no MS vou esperar um feedback dele sobre o cliente se esta tudo ok e aceitar o pull 

Mas o problema então e na nf-e correto?
Nf-e os links já estavam lá, porque teve que adicionar? MS tem os de produção e homologação nf-e

olha essa print

![nfe](https://cloud.githubusercontent.com/assets/10251705/25598353/e7812f00-2eaa-11e7-9f4e-644b9eead4e2.png)

**Comment by adeniltonbs** [comment]
A descrição completa do erro é: 
A conexão subjacente estava fechada: Não foi possível estabelecer relação de confiança para o canal seguro de SSL/TLS. 
O certificado remoto é inválido, de acordo com o procedimento de validação.

Veja também o issue #421 

Acredito que o problema é no ambiente de homologação dessa SEFAZ. Seria possível entrar em contato com eles?

**Comment by rcoproc** [comment]
Achei o problem Adenilton

http://www.nfe.ms.gov.br/atualizacao-da-cadeia-certificadora-em-ambiente-de-homologacao-da-nf-e-da-sefaz-ms/

Tem que instalar estes certificados da cadeia certificadora do ambiente de homologação .

Instalado como Trusted Root Certificateds ai deu certo a chamada.

Obrigado e parabéns.

**Comment by adeniltonbs** [comment]
Por nada.

**Comment by marcosgerene** [comment]
@rcoproc não consegui resolver esse problema, instalei a cadeia do IE, esta la mas o erro de ssl/tls persiste

--------

***Update:*** Problema resolvido, não sigam os passos apresentados simplesmente, importe também o certificado para raiz confiáveis de forma manual:

![image](https://cloud.githubusercontent.com/assets/15945003/25632970/e7366a5a-2f4b-11e7-97a5-1f59edad523e.png)
