### ISSUE TITLE
[MS] - Versões e protocolo

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#421]
Boa noite a todos,

Estou com problemas para emitir NFCe no estado do MS, as versões dos serviços estão confusas, diz que não pode ser 3.10, mas se mudo diz que a versão não pode ter o novo valor.

Serviço NFeAutorizacao:

> Serviço NFeAutorizacao, versão 3.10, não disponível para a UF MS, no ambiente de Produção para emissão tipo Normal, documento: NFC-e

> Erros na validação: O atributo 'versao' é inválido - O valor '2.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerNFe' - Falha na restrição Pattern.

>Erros na validação: O atributo 'versao' é inválido - O valor '1.00' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerNFe' - Falha na restrição Pattern.

---------------------

NfeConsultaProtocolo

> Serviço NfeConsultaProtocolo, versão 3.10, não disponível para a UF MS, no ambiente de Produção para emissão tipo Normal, documento: NFC-e!

> Serviço NfeConsultaProtocolo, versão 2.01, não disponível para a UF MS, no ambiente de Produção para emissão tipo Normal, documento: NFC-e!

>Serviço NfeConsultaProtocolo, versão 1.00, não disponível para a UF MS, no ambiente de Produção para emissão tipo Normal, documento: NFC-e!

**Comment by marcosgerene** [comment]
@adeniltonbs e @robertorp 

Acredito que o problema seja na classe Enderecador que diz que o MS ainda não implementou NFCe.

Segue Urls

http://www.nfce.ms.gov.br/urls-webservices/

**Comment by marcosgerene** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/422

**Comment by leandrossantos** [comment]
@marcosgerene estou precisando falar com vc no skype, já te add, aceita ai para conversarmos, meu id é leandro.rondosoft

**Comment by marcosgerene** [comment]
@leandrossantos uso mt pouco o Skype, me manda um e-mail pra mgf.spirito@gmail.com que te passo meu whatsapp

**Comment by rcoproc** [comment]
Marcos, nestes commits dos endereços que vc subiu só tem o documento do tipo NFe e NFCe não funciona aqui no MS ????

Estou com uma mensagem deste tipo(no webservice de consulta status do MS):

"The underlying connection was closed: Could not estabilish trust relationship for the SSL/TLS secure
chanel"

**Comment by adeniltonbs** [comment]
@rcoproc Aparentemente o problema é no serviço de homologação. Testei o de produção e está funcionando normalmente.

Seria bom confirmar com a SEFAZ se o ambiente de homologação está funcionando.

![image](https://cloud.githubusercontent.com/assets/6733483/25623107/bfafb94c-2f2c-11e7-8b54-0512d14e22c4.png)

![image](https://cloud.githubusercontent.com/assets/6733483/25623009/8f5b155c-2f2c-11e7-8f7b-4ab00316a239.png)

**Comment by robertorp** [comment]
Merge feito com o objetivo de resolver. https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/422
Qualquer coisa e somente reabrir ou criar uma nova issue.
