### ISSUE TITLE
Propriedade da classe Detalhe

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#424]
Estou com problemas para identificar a aplicabilidade de cada propriedade.
Estou seguindo o código fonte de exemplo.

protected virtual prod GetProduto(int i, ItemVenda item)
        {
            var p = new prod
            {
                cProd = i.ToString().PadLeft(5, '0'),
                cEAN = item.GTIN,
                xProd = item.Descricao,
                NCM = item.NCM,
                CFOP = 5102,
                uCom = item.UnidadeMedida.Descricao,
                qCom = item.Quantidade,
                vUnCom = item.PrecoUnitario,
                vProd = item.SubTotal,
                vDesc = item.Desconto,
                cEANTrib = item.GTIN,
                uTrib = "UNID",
                qTrib = 1,
                vUnTrib = 1,
                indTot = IndicadorTotal.ValorDoItemCompoeTotalNF,
                //NVE = {"AA0001", "AB0002", "AC0002"},
                CEST = item.CEST,

                //ProdutoEspecifico = new arma
                //{
                //    tpArma = TipoArma.UsoPermitido,
                //    nSerie = "123456",
                //    nCano = "123456",
                //    descr = "TESTE DE ARMA"
                //}
            };

            return p;
        }

**Comment by robertorp** [comment]
Leu a documentação da nf-e? Lá você tera mais detalhes com cada propriedade.

**Comment by Guaze** [comment]
Agradeço o retorno. Há em algum lugar aqui essa documentação ?

**Comment by robertorp** [comment]
Comece lendo isso e lendo oque é indicado https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki/Nunca-emiti-uma-NF,-meu-sistema-n%C3%A3o-tem-isso.-Preciso-implantar-NFe-e-agora%3F
