### ISSUE TITLE
Please enable REST support in WEB-INF/conf/axis2.xml and WEB-INF/web.xml

### ISSUE THREAD

**Issue by Jariuul** [ZeusAutomacao/DFe.NET#427]
Estou com este problema quando tento fazer qualquer operação (Status Serviço, Enviar Lote, Consultar Lote, etc) somente no estado de AMAZONAS (AM):
"A conexão subjacente estava fechada: Não foi possível estabelecer relação de confiança para o canalseguro de SSL/TLS."

na classe Enderecador está o comentário nos endereços WebServices:
"//Este endereço não possui suporte a REST, de modo que não é possível obter o endpoint reference (EPR)  do webservice. Entrar em contato com a SEFAZ AM"

Essa mensagem do título aparece quando tento acessar o endereço do serviço direto pelo navegador.

Alguém já conseguiu resolver o problema??

**Comment by adeniltonbs** [comment]
@Jariuul Você precisa fazer a atualização das cadeias de certificação digital conforme consta no site da SEFAZ/AM http://www.sefaz.am.gov.br/noticias/noticia.asp?codnoticia=18328. Nesta página há um [link](http://www.iti.gov.br/icp-brasil/navegadores/188-atualizacao/4527-internet-explorer) com um tutorial passo a passo de como instalar as cadeias no local correto (nesse caso em  "Autoridade de Certificação Raiz Confiáveis").

Veja o antes e o depois de atualizar as cadeias de certificado para essa SEFAZ:

## Antes - Homologação
![image](https://cloud.githubusercontent.com/assets/6733483/25820380/77883114-3407-11e7-9e5b-f2fcacfeaa4b.png)

## Antes - Produção
![image](https://cloud.githubusercontent.com/assets/6733483/25820414/8d933224-3407-11e7-9128-c9b70ce759c8.png)

## Depois - Homologação
![image](https://cloud.githubusercontent.com/assets/6733483/25820427/959b5a14-3407-11e7-84fd-e08713c341c2.png)

## Depois - Produção
![image](https://cloud.githubusercontent.com/assets/6733483/25820423/914fceae-3407-11e7-8dec-d187d413371c.png)

**Comment by Jariuul** [comment]
OK, agora funcionou!!!
Estava com problema esses três estados: AM, BA e MS, agora estão todos OK.
Já tinha feito a instalação de dezenas certificados, porém, não estava usando a pasta "Autoridade de Certificação Raiz Confiáveis" que fez toda diferença.
Muitíssimo obrigado!!!
