### ISSUE TITLE
Erro SSL/TLS com certificado A3

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#428]
Bom dia,

O problema relatado diversas vezes com o certificado A3 persiste aqui comigo, e só é resolvido quando fecho a aplicação... todas as opções disponiveis como cache ou limpar a instancia foram tentadas mas o problema persiste em vários clientes (não em todos, mas em vários).

Alguém conseguiu resolver isto definitivamente?

**Comment by adeniltonbs** [comment]
O erro só ocorre comigo caso o cliente utilize mais de uma aplicação acessando o certificado A3 ao mesmo tempo.

**Comment by marcosgerene** [comment]
Estou orientando clientes de NFCe com volume de notas maior a usar certificado A1 por enquanto.

Não há o que eu possa fazer via sistema? eu sempre tenho que fechar e reabrir o executável para voltar a funcionar, nada pode ser feito via código para ter de novo a "preferencia" nesse caso então?

**Comment by robertorp** [comment]
No meu caso não passo por esse problema, pra falar que nunca passei, passei uma unica vez eu inseri a senha do certificado A3 e funcionou normalmente nunca mais deu nada nem sei se foi coincidência. Testa por a senha do A3 porque ai o zeus vai injetar a senha nem vai pedir a primeira Dialog do dia.

**Comment by marcosgerene** [comment]
@robertorp por padrão sempre oriento a por a senha, mas testei já das duas formas, inclusive remover o cartão e inserir novamente quando o erro ocorre, mas não obtive sucesso

**Comment by rcoproc** [comment]
Marcos .. qual o problema deste certificado A3 seu ? tem a mensagem de  erro ??? tivemos um aqui em nosso sistema que pegamos pelo log do windows, talvez seja o mesmo. No nosso caso aconteceu pela instalação errada de um setup das dlls do A3.

**Comment by marcosgerene** [comment]
@rcoproc 
Não sei especificar o problema, ocorre em vários clientes mas não em todos, ainda não consegui encontrar um ponto de convergência entre os problemas, deixar com ou sem senha pre-definida, mudar a criptografia, usar cache, limpar o cache, limpar a instancia das configurações, já fiz tudo que estava ao meu alcance, mas o problema só se resolver ao fechar e reabrir o sistema.

Para clientes com NFCe com alto volume de documentos fiscais eu simplesmente orientei usar A1 e "desisti" de achar uma solução do problema.

Sobre o que o @adeniltonbs disse, eu ate tentei procurar algo que pudesse estar usando o certificado em paralelo, mas aparentemente nada, o engraçado é que o caso ocorre também em clientes que usavam anteriormente o emissor gratuíto do SEFAZ e no emissor gratuito eu posso fazer o teste que for, SEMPRE vai dar certo, NUNCA ocorre o erro do ssl/tls

**Comment by robertorp** [comment]
Redundância de tópico vou fechar o do link https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/222

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/519
