### ISSUE TITLE
Pergunta: numeração de NFC-es

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#43]
Adenilton, 

Uma perguntinha, pode parecer boba: a numeração de NFC-e em homologação é distinta da numeração de NFC-e em Produção para um mesmo CNPJ emitente? Posso usar uma numeração de 1 a 10 em homologação e depois ao acertar o sistema, usar a mesma numeração de 1 a 10 em produção?

Obrigado,
Roberto.

**Comment by leandrossantos** [comment]
Oi Roberto.
Respondendo sua pergunta, sim, são numerações distintas. Pode usar a mesma numeração em ambientes diferentes.
