### ISSUE TITLE
Calculo de vTotTrib da classe imposto.

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#431]
Boa noite,

Estou acompanhando o exemplo de NFe.AppTeste e deparei com este trecho de código.

protected virtual det GetDetalhe(int i, CRT crt, ModeloDocumento modelo)
        {
            var det = new det
            {
                nItem = i + 1,
                prod = GetProduto(i + 1),
                imposto = new imposto
                {
                    vTotTrib = 0.17m,
                    ICMS = new ICMS
                    {
                        TipoICMS =
                            crt == CRT.SimplesNacional
                                ? InformarCSOSN(Csosnicms.Csosn102)
                                : InformarICMS(Csticms.Cst00, VersaoServico.ve310)
                    },

Onde  vTotTrib = 0.17m está fixo.

Gostaria de saber como realizo o cálculo para um empresa no simples nacional que utiliza somente o CSOSN 102 (CFOP 5102) e 500 (CFOP 5405).

**Comment by marcosgerene** [comment]
Bom dia,

Este valor fixo (0.17m) é somente um exemplo de como preencher o campo.

Recomenda-se que os calculos sejam feitos com base no NCM do produto usando as tabelas disponibilizadas pelo IBPT (https://ibpt.com.br/).

Deve-se utilizar a tabela do estado do EMITENTE (ex: eu sou de SP e emito uma NFe para MG então devo usar a tabela de SP).

O valor utilizado deve ser o valor do item [(quantidade x valor) + acrescimo - desconto] multiplicado pela soma das aliquotas correspondentes àquele NCM para aquela operação, ou seja, quando exportação usar a aliquota de exportação, no resto das operações a soma das aliquotas nacional, estadual e municipal.

A forma mais simples de se obter a tabela na minha opnião é baixando o fonte do ACBr, elas se encontram na pasta ..\ACBr\Exemplos\ACBrTCP\ACBrIBPTax\tabela\

Att, Marcos

**Comment by Guaze** [comment]
Baixei o código-fonte do ACBR e obtive a planilha. Obrigado!

**Comment by Guaze** [comment]
Identifiquei NCM repetido na planilha do RJ  e nesta observação vi que a informação "ex" que tem um incremento. O que devo fazer neste caso ?

select *
from ncm x,
(
SELECT 
a.NCM_CD_NCM
FROM NCM a
group by a.NCM_CD_NCM
having count(*)> 1
order by 1 asc
) t
where x.NCM_CD_NCM = t.NCM_CD_NCM
order by x.NCM_CD_NCM

*Importei a planilha para o meu banco de dados.
<img width="669" alt="capturar" src="https://cloud.githubusercontent.com/assets/28018162/26037305/f0512df8-38c6-11e7-9dbf-a496e94841ee.PNG">

**Comment by marcosgerene** [comment]
Boa noite @Guaze 

Pesquisando rapidamente no Bing:
>https://www.bing.com/search?q=ncm+ex+ibpt&qs=n&form=QBRE&sp=-1&pq=ncm+ex+ibpt&sc=8-7&sk=&cvid=9E38DF00AAB241D8ABD213A356723800

O quarto resultado:
>https://regys.com.br/entendendo-nova-tabela-ibpt-e-o-atendendo-mudancas-da-lei-12-741-2012/#.WRjCaMZv-00

O trecho que realmente interessa:
>ex: Exceção do TIPI, deve ser utilizado com conjunto com o código NCM para encontra corretamente a >alíquota a ser utilizada.

Bom temos a seguinte resposta, trata-se da exceção do TIPI.

Agora pesquisando de forma mais direcionada: https://www.bing.com/search?q=Exce%C3%A7%C3%A3o+do+TIPI&pc=MOZI&form=MOZLBR

O primeiro link da busca responde em cheio sua questão: https://regys.com.br/para-que-serve-o-campo-de-excecao-na-tabela-do-ibpt/#.WRjDSMZv-00

Como eu aplicaria isso no sistema?

Criaria um campo com o código de exceção no cadastro do produto, quando vazio pegava o NCM 'puro", quando preenchido pegava o ncm e a EX.

Att, Marcos

**Comment by Guaze** [comment]
Agradeço o retorno!!! Já introduzi ao produto estas modificações.
