### ISSUE TITLE
Assinar Projetos

### ISSUE THREAD

**Issue by thiagovalim** [ZeusAutomacao/DFe.NET#435]
Criar certificado de teste para assinar projetos, pois quem utiliza projetos que já são assinados precisam criar um certificado e assinar todos os projetos do zeus nfc, facilitando assim o uso para quem usa projetos assinados (com strong name).

**Comment by robertorp** [comment]
Essa assinatura seria oque? E para oque serve?

**Comment by thiagovalim** [comment]
Serve para proteger os arquivos do projeto contra alterações indesejadas (ex: um software malicioso ou alguém alterar uma das dlls do projeto) e também para identificar a empresa desenvolvedora. Pode ser feito através da aba assinaturas nas opções do projeto, no caso do zeus como é um projeto aberto pode ser feito com um certificado temporário criado na própria aba assinaturas, quando você possui um software assinado todas as dlls do projeto tem que estar assinadas garantindo assim a integradade de todo o software, por isso quem utiliza a assinatura no seu projeto também só pode utilizar dlls assinadas (com strong name), no meu caso toda vez que eu baixo o projeto do zeus eu tenho que adicionar a assinatura em todos os projetos do zeus para que eu possa utilizar, até mesmo se eu tentar utilizar o pacote nuget eu teria que assina-lo primeiro o que dá bastante trabalho para fazer todas as vezes que eu atualizar.

**Comment by robertorp** [comment]
Poderia me passar algum artigo que fala sobre o assunto de como fazer? Ai posso estar vendo isso.

**Comment by thiagovalim** [comment]
Boa tarde robertorp, segue alguns artigos.

https://msdn.microsoft.com/pt-br/library/ms247123(v=vs.110).aspx

http://www.macoratti.net/vbn5_asa.htm

https://qualidadeeti.wordpress.com/2014/06/27/almassinatura-digital-de-softwares-assinatura-digital-de-cdigo-x-assinatura-com-nomes-fortes/
