### ISSUE TITLE
Senha Certificado

### ISSUE THREAD

**Issue by jtvb** [ZeusAutomacao/DFe.NET#44]
Boa Tarde Amigo,
Primeiro parabens pelo projeto estou realizando alguns testes es esta excelente...
Pergunta é possível informar a senha no certificado A3. Estou procurando e não estou conseguindo encontrar ou ainda não tem esta opção?

**Comment by adeniltonbs** [comment]
Boa tarde, a biblioteca não tem uma opção para armazenar a senha do certificado, no entanto, ao utilizar a biblioteca irás perceber que a senha do certificado A3 será solicitada apenas na primeira requisição após iniciar uma nova instância de sua aplicação.

Para certificados A1, é necessário apenas informar o nº de série do certificado.

**Comment by jtvb** [comment]
É realmente eu vi aqui, porem estou trabalhando no código para tentar enviar a senha junto pelo motivo que o cliente irá ter o certificado A3  e fica meio enviável ele ter que inserir a senha mesmo sendo apenas 1 vez pelo motivo do servidor não esta próximo dele...

Caso eu consiga algo eu coloco aqui para você, se caso tiver uma solução me avisa vlw...

**Comment by adeniltonbs** [comment]
Ok

**Comment by rftd** [comment]
```
   public static X509Certificate2 SelecionarCertificado(string caminho, string senha)
    {
        if (!File.Exists(caminho))
        {
            throw new Exception("Arquivo do Certificado digital não encontrado");
        }

        var cert = new X509Certificate2(caminho, senha, X509KeyStorageFlags.MachineKeySet);
        return cert;
    }
```

**Comment by jtvb** [comment]
Amigo segue um código que conseguir realizar a consulta enviando a senha para o Certificado A3.

```
        SecureString _senhaCertificado = new SecureString();
        String CertificadoSenha = "1234";
        char[] passPhrase = CertificadoSenha.ToCharArray();

        for (int i = 0; i < passPhrase.Length; i++)
        {
            _senhaCertificado.AppendChar(passPhrase[i]);
        }

        X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
        store.Open(OpenFlags.MaxAllowed);

        // PROCURA PELO NUMERO SERIAL DO CERTIFICADO
        var foundCerts = store.Certificates.Find(X509FindType.FindBySerialNumber,                  numeroSerial.ToUpper(), true);
        if (foundCerts.Count == 0)
            throw new Exception(String.Format("Certificado digital nº {0} não encontrado!", numeroSerial.ToUpper()));

        var certForSigning = foundCerts[0];
        store.Close();

        // take private key
        var privateKey = certForSigning.PrivateKey as RSACryptoServiceProvider;

        // make new CSP parameters based on parameters from current private key but throw in password
        CspParameters cspParameters = new CspParameters(privateKey.CspKeyContainerInfo.ProviderType,
            privateKey.CspKeyContainerInfo.ProviderName,
            privateKey.CspKeyContainerInfo.KeyContainerName,
            null,
            _senhaCertificado);

        // make RSA crypto provider based on given CSP parameters
        var rsaCsp = new RSACryptoServiceProvider(cspParameters);

        // set modified RSA crypto provider back
        certForSigning.PrivateKey = rsaCsp;

        //return certForSigning;
        if (certForSigning == null)
        {
            throw new Exception(String.Format("Certificado digital nº {0} não encontrado!", numeroSerial.ToUpper()));
        }
        return certForSigning;
```

Segue a fonte da consulta

http://stackoverflow.com/questions/28772599/x509certificate2-access-to-a-private-key-into-a-security-token

**Comment by adeniltonbs** [comment]
Obrigado pela colaboração de todos, as alterações solicitadas foram incluídas no commit d457b807fef0e15ffd12f63fde15919522f8674e.

A aplicação de demonstração foi modificada para utilizar as classes refatoradas, aceitar certificado a partir do arquivo/senha e informar a senha para certificados A3.

jtvb por favor poderia testar a informação de senha para o certificado A3, visto que não tenho um certificado A3 em mãos no momento.

Quaisquer dúvidas só perguntar!

**Comment by jtvb** [comment]
Ok vou testar agora a tarde e lhe respondo...

**Comment by jtvb** [comment]
Adenilton,

Realizei os testes aqui e estava apresentando um erro no momento que era informado a senha msg: ACESSO NEGADO, verifiquei o código é somente alterei o modo de abertura para seleção do certificado colocando 

store.Open(OpenFlags.MaxAllowed);

Após esta alteração funcionou normalmente.

**Comment by adeniltonbs** [comment]
Pronto jtvb, pode confirmar se está tudo certo agora?

Se desejar subir algum código diretamente no projeto aqui no git, é bem fácil. O próprio visual studio tem integração com o Git-Hub. Depois posso pegar seu código e fazer um merge.

**Comment by jtvb** [comment]
Adenilton,

Teste realizado e funcionando...

Já baixei direto pelo Visual Studio ...

Pergunta vi que você esta usando o FastReport você teria o instalador dele ou o link para baixar tentei aqui porem sem sucesso. Estou tendo que desabilitar as linhas de chamadas.

Abraço

**Comment by adeniltonbs** [comment]
Você pode baixar a versão de demonstração (FastReport.Net for .Net 4.0) em: https://www.fast-report.com/pt/download/fast-report-net/

A versão de demonstração não expira, apenas exibe uma marca d'água na impressão.
