### ISSUE TITLE
Erro ao emitir NFCe

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#443]
Adenilton, boa tarde,

Estou com um problema com a emissão de NFC-e, está apresentando a rejeição em anexo, Em anexo os arquivo gerados também. Se puder me ajudar a elucidar o problema, agradeço.

Abrs,
Roberto.
![img-20170516-wa0000](https://cloud.githubusercontent.com/assets/11814082/26116014/1c292404-3a38-11e7-8df0-646797991a40.jpg)

[NFCe_QrCode_Erro.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1005113/NFCe_QrCode_Erro.zip)

**Comment by robertorp** [comment]
Seu CSC esta correto?

**Comment by robertocvsiqueira** [comment]
Creio que sim. Ele extrai do arquivo de configuração que o usuário da empresa emitente preencheu e o sistema gravou.

**Comment by robertorp** [comment]
Eu to imaginando que talvez possa ser lá, olha isso http://tsdn.tecnospeed.com.br/base-de-conhecimento/post/rejeicao-464-codigo-de-hash-no-qr-code-difere-do-calculado porque o resto aparentemente.. na minha visão não achei erro pode ser que alguém ache algo que eu não vi hehe
Geralmente quando dão esse erro as pessoas procuram nos mas sempre é idToken errado no seu caso ta os 6 digitos.. então presumindo que é 000001 ta certo. Mas vai saber né, enfim se possivel de uma conferida nesse CSC é IdToken e observe se estão no mesmo ambiente que o sistema esta configurado ou seja... CSC e IdToken de produção.. emissão em produção... 
 CSC e IdToken de homologação.. emissão em homologação...

**Comment by robertorp** [comment]
Encontrou Solução amigo?

**Comment by robertocvsiqueira** [comment]
Caros,

Acabei de contactar o cliente, que encontrou uma solução, realmente se tratava do CSC/IdToken incorreto.

Obrigado,
Roberto.
