### ISSUE TITLE
Dúvida sobre novas validações do QRCODE( CSC, valor do pagto , número da chave)

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#446]
Agora está sendo validado um monte de coisa no qrCode, além da NF , tem os dados do emissor, valor da 

nota , valor do pagto  e o CSC.

Antes não tinha tudo isto , ou engano meu ???

**Comment by onlyAJV** [comment]
Também tenho tal questionamento. Como fica a validação e o que deve ser modificado no software para adequar tal funcionalidade.

**Comment by robertorp** [comment]
vocês conseguiram resolver isso?

**Comment by onlyAJV** [comment]
Não, amigo não consegui...
