### ISSUE TITLE
Dúvida SVC-RS e SVC-AN, quando utilizar e como fica a volta para o meu estado?

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#447]
Alguém sabe me dizer quando deveremos utilizar os webservices  SVC-RS, e SVC-AN ??

e se mandar por lá como fica a volta para o meu estado , MS ???

Atte.

Ricardo

**Comment by robertorp** [comment]
Você utiliza eles quando o servidor do seu estado para de funcionar por algum motivo (que seja uma manutenção preventiva, que seja porque ou um erro etc..) 

Não precisa retornar nada para MS.
