### ISSUE TITLE
Múltiplos emitentes

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#448]
Olá!
Para integrar o Zeus com o ERP que desenvolvo fiz um sistema separado que recebe solicitações do ERP para emitir a NFe.
Me surgiu uma dúvida de como reagir no caso do ERP ter múltiplos emitentes e hora emitir NFe para uma empresa, hora pra outra empresa, com CNPJs e certificados diferentes.
Então pensei em ter um List<ConfiguracaoApp> contendo as configurações de cada emitente.

Mas me deparei com ConfiguracaoServico.Instancia, sendo ela static quando eu configuro os dados do primeiro emitente irá popular com os dados dele, mas quando configuro com os dados do segundo emitente as configurações do primeiro emitente se perdem.

No Zeus tem alguma maneira de fazer esta configuração e eu não estou encontrando ou teria que implementar esta funcionalidade?

**Comment by robertorp** [comment]
Tem que implementar essa funcionalidade, nunca foi pensado assim. No caso envolveria ate o cadastro do emitente teria. Bom são N coisas ai para tratar.

**Comment by marciojmuller** [comment]
Mas já chegou a passar por este problema e conseguiu resolver de outra forma?

**Comment by robertorp** [comment]
Aqui no nosso sistema ele e multiempresa para emissão de documentos fiscais 
nos instanciamos tudo do 0 toda vez que for emitir.. mas não tem concorrência se por acaso algum dia tiver concorrência vai dar esse mesmo erro seu ai.
Unica coisa que ajustei no Zeus estes dias para trás e o cache do certificado digital, se você observar a classe de CertificadoDigital ira ver que o cache dele é multi empresa ou multicertificado digital bastando apenas passar o CacheId na classe ConfiguracaoCertificado.

Então resumindo se seu problema for concorrência ai você vai ter que ajustar o Zeus ou esperar um ajuste futuro vier ou fazer uma pilha no seu erp e ir executando um por um criando toda vez uma nova classe ConfiguracaoServico do 0 (e oque citei no meu erp eu crio ela toda vez do zero).

**Comment by marciojmuller** [comment]
Bom então a melhor forma é utilizar o ConfiguracaoServico.LimparInstancia() e carregar tudo novamente.
Vou criar na minha aplicação uma classe para carregar as informações dos emitentes e quando precisar utilizar carrego elas para o ConfiguracaoServico, visto que são muitas alterações para se fazer no Zeus.
Agora observando a situação melhor acho que estas alterações até sairiam do escopo do Zeus, que a meu ver é de apenas de emitir a NFe, não gerenciar os emitentes.
