### ISSUE TITLE
Cancelamento NFC-e

### ISSUE THREAD

**Issue by rodrigofornasier** [ZeusAutomacao/DFe.NET#449]
Adenilton bom dia.

Quero implementar o cancelamento de NFC-e, porém não achei nenhum exemplo de código.
Poderia me passar um link do exemplo ?

Grato

**Comment by robertorp** [comment]
Mesma coisa da NF-e somente o muda tipo documento

**Comment by rodrigofornasier** [comment]
Eu não achei exemplo deste código. Gostaria de ver um modelo pra tentar entender como funciona. Teria algum exemplo ?

**Comment by robertorp** [comment]
Tente cancelar uma NFC-e no appTeste, lembrando que mude de NF-e para NFC-e o uso. Informe os dados que o app Teste Pede

edit: e o mesmo método para cancelar ambos, você so tem que alterar o uso do componente para NFCe

**Comment by rodrigofornasier** [comment]
Ja enetendi, fiz exatamente isso. O que ainda não consegui entender foi o que é o Id do Lote. Como eu pego essa informação ?

**Comment by rodrigofornasier** [comment]
Última dúvida. O parâmetro sequenciaEvento que deve ser passado, é o sequencial do cupom ? se não é poderia me explicar o que seria ?

**Comment by robertorp** [comment]
Não e sequencia do cupom não.

SequencialEvento cada evento executado você incrementa +1 
ele e individual por nota fiscal ou seja todas notas fiscais começam do 1

Vamos supor que você vai fazer uma carta correção

Adiciona SequencialEvento = 1

você quer fazer outra carta correção para a mesma nota

Adiciona SequencialEvento = 2

**Comment by rodrigofornasier** [comment]
Entendi, é para cada Nota ? Ou este sequencial é para todas operações ? Tipo, começa no 1, eu emiti uma nota vai pro 2, cancelei, vai pro 3 e assim sucessivamente... ou ... por tipo de evento ? cancelamento, vai ser sempre 1, pois nao pode cancelar 2 vezes e etc... Não sei se me fiz entender...

**Comment by robertorp** [comment]
E para cada nota.. se existisse método para cancelar a mesma nota duas vezes você usaria 1 e depois 2
Carta correção 1 e depois 2
Outro evento? 1 e depois 2

edit: cancelamento e sempre 1 bom pelo menos nunca passei por algum motivo que fosse cancelar duas vezes, não duvido de nada da sefaz

**Comment by rodrigofornasier** [comment]
Perfeito. Obrigado !

**Comment by robertorp** [comment]
Precisando, crie quantas issues precisar pois quanto mais, mais conhecimento acumulado, obrigado
