### ISSUE TITLE
Erro 297: Assinatura difere do calculado [Resolvido]

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#45]
Bom dia Amigo!

Em primeiro lugar parabéns pela inciativa, o projeto é de grande ajuda.

Após atualizar a versão para funcionar nos novos web services do SVRS, minha aplicação começou a rejeitar as NFC-e enviadas. Sempre ocorre o mesmo erro: 297 - Assinatura difere do calculado.

Você poderia me informa se está com algum erro na aplicação?

Obrigado.

**Comment by adeniltonbs** [comment]
Você está usando certificado A1 ou A3?

**Comment by adeniltonbs** [comment]
Esse erro acontece se a assinatura do XML estiver errada.

**Comment by ghost** [comment]
O certificado digital é do tipo A1.

Já procurei por caracteres em branco e por caracteres especia, porém não tem nada assim no XML. O problema pode ser no certificado digital?

**Comment by adeniltonbs** [comment]
Vou fazer alguns testes aqui. Para qual UF vc está emitindo?

**Comment by ghost** [comment]
Muito obrigado. 
Estou emitindo para o Piauí (PI) e Mato Grosso (MT)

**Comment by rftd** [comment]
Este erro ocorre tbm se depois de assinada a nota ela for modificada, pois para validar a assinatura é gerada outra com o conteudo do xml e comparada a do xml com a gerada.

**Comment by ghost** [comment]
Minha unica alteração no seu código fonte foi nos web services do Sefaz Virtual do Rio Grande do Sul, que mudaram a partir de 1 de Outubro de 2015

**Comment by ghost** [comment]
Olá Rafael,

Obrigado pela dica. Acredito que isso não esteja acontecendo, mas vou realizar alguns testes e verificar

**Comment by adeniltonbs** [comment]
Isso mesmo Rafel, bem lembrado, Estou implementando a NT2015/002 e NT2015/003 para poder fazer os testes em homologação, pois entraram em vigor neste ambiente ontem.

**Comment by ghost** [comment]
Estava realizando os testes no ambiente de homologação, porém vi que existem essas novas normal em vigor. Tentei realizar o envio no ambiente de produção dos dois estados (Piauí e Mato Grosso), mas o erro continua.

Vou realizar testes em outros estados, pois na versão mais antiga está operando normalmente no Rio de Janeiro e Rondônia.

De qualquer forma, muito obrigado pela ajuda até o momento.

**Comment by ghost** [comment]
Olá Rafael  e Adenilton, muito obrigado pela ajuda.

O erro estava acontecendo pois, como o Rafael comentou, o XML estava sendo alterado depois de assinado. Foi apenas na questão das casas decimais dos produtos e totais.

Muito obrigado pela ajuda dos dois!
