### ISSUE TITLE
Como chamar a impressão da NFCe após a  autorização ?

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#450]
Já tenho a NFce gerada , enviada e autorizada.

Como é que eu faço a impressão automática após esta autorização ???

Tenho que baixar algum XML novamente da receita já com o código de autorização ???

para poder imprimir ??? a impressão do exemplo de hoje só pega de arquivo físico . vejam
`#region Carrega um XML com nfeProc para a variável

                var arquivoXml = Funcoes.BuscarArquivoXml();
                if (string.IsNullOrEmpty(arquivoXml))
                    return;
                var proc = new nfeProc().CarregarDeArquivoXml(arquivoXml);
                if (proc.NFe.infNFe.ide.mod != ModeloDocumento.NFCe)
                    throw new Exception("O XML informado não é um NFCe!");

                #endregion

                #region Exibe a NFe no webbrowser (não é ncessário fazer isso em seu sistema!)

                _nfe = proc.NFe;

                ExibeNfe();

                #endregion

                #region Abre a visualização do relatório para impressão

                var danfe = new DanfeFrNfce(proc, _configuracoes.ConfiguracaoDanfeNfce);
                danfe.Visualizar();`

**Comment by Guaze** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/485

**Comment by Guaze** [comment]
Fiz esse código ontem!!!

if (MetroFramework.MetroMessageBox.Show(this, string.Format("Deseja emitir o cupom ?"), this.TitleMessage, MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        string diretorio = utils.CriarDiretorioNFCe(
                            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),
                            Venda.Data);

                        if (protNFe != null & protNFe.infProt.cStat.Equals(100))
                        {
                            nfeProc = new NFe.Classes.nfeProc();
                            nfeProc.NFe = nfe;
                            nfeProc.protNFe = protNFe;

                            //Salvando o xml localmente
                            nfeProc.SalvarArquivoXml(diretorio + this.Venda.ChaveAcesso + "-nfe.xml");
                        }
                        else
                        {
                            //Houve algum problema com a nota ao enviar para Receita Federal
                            nfe.infNFe.ide.tpEmis = NFe.Classes.Informacoes.Identificacao.Tipos.TipoEmissao.teOffLine;

                            //Salvando o xml localmente
                            nfe.SalvarArquivoXml(diretorio + this.Venda.ChaveAcesso + "-nfe.xml");
                        }

                        nfceUtilities.ImprimirNFCe(nfeProc != null ?
                                                    nfeProc.ObterXmlString()
                                                    : nfe.ObterXmlString(), 0, 0);
                    }

public void ImprimirNFCe(string arquivo, decimal troco, decimal totalPago)
        {
           NFe.Danfe.Nativo.NFCe.DanfeNativoNfce  impr = new NFe.Danfe.Nativo.NFCe.DanfeNativoNfce(
               arquivo,
               configurationNFCe.ConfiguracaoDanfeNfce,
               configurationNFCe.ConfiguracaoCsc.CIdToken,
               configurationNFCe.ConfiguracaoCsc.Csc,
               troco,
               totalPago/*, "Arial Black"*/);

            impr.Imprimir(nomeImpressora: "HP Photosmart D110 series");
        }

**Comment by Guaze** [comment]
Só deveria está gravando o XML independente da vontade de imprimir. Só que já era tarde aí fiquei com preguiça. Irei ajustar isso!

:smile:
