### ISSUE TITLE
NFe de serviços ISSQN

### ISSUE THREAD

**Issue by ivaldojunior** [ZeusAutomacao/DFe.NET#451]
Fala pessoal, boa tarde.

Estou tentando imprimir uma NFe de serviços e está aparecendo este erro:

Erros na validação:
O elemento 'imposto' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' apresenta elemento filho 'ISSQN' no espaço para nome 'http://www.portalfiscal.inf.br/nfe' inválido. Lista de possíveis elementos esperados: 'IPI, II, PIS, PISST, COFINS, COFINSST, ICMSUFDest' no espaço para nome 'http://www.portalfiscal.inf.br/nfe'.

Alguém pode me auxiliar? Alguém já emite NFe de serviços e poderia me mandar um exemplo?

Muito obrigado.

**Comment by leandrossantos** [comment]
@ivaldojunior , boa tarde.

Você gerou uma NFe com Serviços, foi isso?
Porque se for a NFSe, nota fiscal de serviço eletrônica, o Zeus não contempla.

**Comment by ivaldojunior** [comment]
boa tarde,  estou tentando emitir uma NFe com serviços.

o erro é este atualmente:

Falha de Esquema: O elemento pai: 'total' não estava esperando o elemento 'ISSQNtot'. O elemento esperado é: 'ICMSTot'.
Obrigado

**Comment by robertorp** [comment]
Então esta faltando preencher estas tags


nf-e de serviço e correto? pois tem a nfs-e ou nota de serviço da prefeitura
