### ISSUE TITLE
Impressão da DANFE por contigência é só quando não tenho internet ou somente quando a receita muda lá ??

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#452]
As minhas NFCes online estão OK, agora quero tratar as offlines(contingência).

Quando devo mudar para offline ??? só quando não tenho internet local , ou quando a receita muda lá o status dela ??? ou nos dois casos ???

E quando devo tratar novamente para pegar os protocolos ao voltar para online ???

Alguém entendem bem este fluxo e poderia me orientar melhor ???

Obrigado a todos.

**Comment by robertorp** [comment]
Seguinte, você passa a emitir nfc-e offline quando não tem como emitir mais online. Causas prováveis, o cliente ficou sem internet por motivo de redes local ou motivo de provedor ou falta de pagamento enfim.. são N causas somente nisso, outras causas a Sefaz parou por algum motivo. 

Logico se o cliente brincar de mentir para a sefaz e passar a emitir nfc-e offline sem parar e a sefaz por algum motivo perceber, o cliente tera uma punição qual e a punição? Bom imagino eu que fica sem emitir nfc-e durante X horas.

Meu cliente emitiu 200 nfc-e offline e não tenho como enviar elas dentro do prazo esperado oque eu faço?
Liga na sefaz. Sem enviar você não vai poder ficar, mas passou do prazo e com a Sefaz pra frente.
