### ISSUE TITLE
Pode-se usar a versão 4.0 dos schemas na versão atual da biblioteca?

### ISSUE THREAD

**Issue by CalegariElizangela** [ZeusAutomacao/DFe.NET#453]

**Comment by robertorp** [comment]
Teria que implementar tudo , com certeza vai dar erro na validação dos schemas. A versão 4 ainda não foi implementada no Zeus. Sim sera implementada. Quando? Bom somos uma comunidade logo então não posso confirmar que sera hoje, nem amanhã, se alguém aparecer com alguma implementação perfeito! Se ninguém aparecer com alguma implementação ai vão ter que aguardar um prazo. E tem mais a ativação das webservices de homologação e desativação do de produção 3.1 ainda temos quase 1 ano. Logo então leva eu a pensar que não tem que afobar.

**Comment by CalegariElizangela** [comment]
Entendi @robertorp. Então vc acha que compensa eu me basear nesta versão atual e já implementar a versão 4.0 ? Os webServices já estão funcionando pra versão mais nova?

**Comment by leandrossantos** [comment]
@LiCalegari pelo que sei os webservices (url) da versão 4.0 ainda não foram disponibilizados.

**Comment by robertorp** [comment]
Os webservices não estão funcionando para a versão nova ainda.

Pagina 8 para prazos 
Nota Técnica 2016.002 - v 1.20
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=20k0jfiSgtk= 

Acho que pode implementar na versão atual, no final das contas serão ajustes que você vai fazer de uma versão para a outra. (Bom eu acho bem simples fazer isso)

**Comment by CalegariElizangela** [comment]
Beleza então pessoal, vou implementar a 3.1.
 Muito Obrigada pelas rápidas respostas!

**Comment by rftd** [comment]
MS já está em funcionamento a versão 4 a 1 mês

**Comment by leandrossantos** [comment]
Verdade, MS já passou os links dos WS da versão 4.0

Vejam no link abaixo.
[http://www.nfe.ms.gov.br/publicada-a-versao-1-10-em-abril-de-2017-da-nota-tecnica-nt-2016-002-que-trata-da-alteracao-do-leiaute-da-nf-e-da-versao-3-10-para-a-versao-4-00/](http://www.nfe.ms.gov.br/publicada-a-versao-1-10-em-abril-de-2017-da-nota-tecnica-nt-2016-002-que-trata-da-alteracao-do-leiaute-da-nf-e-da-versao-3-10-para-a-versao-4-00/)
