### ISSUE TITLE
Implementando biblioteca Zeus em MVC

### ISSUE THREAD

**Issue by CalegariElizangela** [ZeusAutomacao/DFe.NET#454]
Comecei a implementar a NF-e aqui, porém nunca trabalhei com nada relacionado. Então importei via nuget a biblioteca Zeus.NFe.NFCe e como primeiro passo estou tentando chamar a consulta do Status do Serviço. Ai vem a "pergunta de principiante": 

Terei eu que implementar na mão a classe ServicosNFe e todas as outras classes que não foram instanciadas na instalação da biblioteca?
Eu tentei usar o código igual do exemplo, mas não tem tudo o que preciso, teria que criar na mão?

            using (var servicoNFe = new ServicosNFe(_configuracoes.CfgServico))
            {
                var retornoStatus = servicoNFe.NfeStatusServico();
                TrataRetorno(retornoStatus);
            }

**Comment by robertorp** [comment]
Ao app teste tem uma classe exemplo de instanciação do da parte _configuracoes.CfgServico

no caso CfgServico você deve instanciar ela com os parâmetros relacionados que você utiliza

Se você é iniciante de tudo no mundo de NF-e 

Leia: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki aqui temos um conteúdo básico para iniciantes com a biblioteca, recomendo que leia o manual também: http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=

O App exemplo está em WPF mas.. serve de base para web também, as dll do Zeus nem uma faz referencia a algo especifico de desktop ou seja e independente de plataforma web/desktop ambas irão funcionar.

**Comment by robertorp** [comment]
Temos também o grupo do skype com muitos programadores ativos https://join.skype.com/CJbtNPlvbycL
