### ISSUE TITLE
Assinatura de NFe

### ISSUE THREAD

**Issue by felipedrumond** [ZeusAutomacao/DFe.NET#455]
Olá @adeniltonbs, como vai?!
Estou testando seu repo no intuito de criar um de emissão de NFe/NFCe onde o client não tenha que conhecer o serviço. Para tanto, o client deverá enviar todos os dados usando o design pattern DTO e então consumir seu serviço, informando inclusive o certificado. Me deparei com algo que poderia ser melhorado a fim de ajudar o pessoal que está implementando a nota fiscal eletrônica: atualmente o _NFe.Utils.Assinatura.Assinador.ObterAssinatura_ só recebe um X509Certificate2 (e quando null, utiliza o _Singleton ConfiguracaoServico.Instancia.Certificado_). No meu caso, eu desejo utilizar n certificados (tenho mais de um), então ao invés de usar o singleton, eu deverei enviar o X509Certificate2. No entanto, o método _NFe.Utils.Classes.NFe.Assina_ só recebe a NFe, não permitindo enviar também o certificado a ser utilizado. Consequentemente, ao chamar _Assinador.ObterAssinatura_, não é possível enviar o certificado também, obrigando o método a usar o singleton.

Se não existe um meio de enviar a NF e também o X509Certificate2 para obter a Assinatura sem ter que editar seu projeto, fica aqui a recomendação. Se existe, poderia por favor me indicar?

**Comment by marciojmuller** [comment]
Olá!
Não é só assinar a NFe, teria que enviar todas as configurações do sistema, devido um emitente poder ser de um estado e outro emitente ser de outro estado.
É mais fácil você implementar uma aplicação que salve todas estas configurações e quando precisar usar o emitente 1 carregar o emissor com os dados e configurações dele, quando precisar utilizar o emissor 2 carregar as configurações no emissor novamente.
Deixe carregadas as configurações em classes do Zeus e quando precisar utilizar apenas informe as variáveis.

Como no exemplo do Zeus tem a classe ConfiguracaoApp, tenha uma lista de quantas forem necessárias para os seus emitentes.

**Comment by robertorp** [comment]
Isso esta sendo feito aqui. Uma forma diferente sem static para manipular as configurações do Zeus.
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503
