### ISSUE TITLE
namespace na tag CTe

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#456]
Ola Adenilton boa tarde, estou homologando o CTe e conforme na homologacao da NFCe estou com o mesmo problema relatado e corrigido em: ("https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/33"), para o estado do PR.  Voce teria como corrigir no codigo a mesma solução para o Projeto CTe?  usei assim: " xml.Replace("<CTe>", "<CTe xmlns=\"http://www.portalfiscal.inf.br/cte\">");" sem mais, grato.
[issue.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1042775/issue.txt)

**Comment by robertorp** [comment]
xml.Replace("empty", "TAG")

tem que ser realmente empty lá? 
Em qual WebService? Autorização?

**Comment by vasisti** [comment]
Ola Roberto tudo bem, vou passar a mensagem por aqui completa segue:


Ola Adenilton boa tarde, estou homologando o CTe e conforme na homologacao da NFCe estou com o mesmo problema relatado e corrigido em: ("https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/33"), para o estado do PR.  Voce teria como corrigir no codigo a mesma solução para o Projeto CTe?  usei assim: " xml.Replace("<CTe>", "<CTe xmlns=\"http://www.portalfiscal.inf.br/cte\">");" sem mais, grato.


estou usando a versao 3.00 mas na 2.00 tambem é o mesmo.

sem mais. Valdir

________________________________
De: Roberto Alves Pereira <notifications@github.com>
Enviado: quarta-feira, 31 de maio de 2017 17:07:33
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: vasisti; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] namespace na tag CTe (#456)


xml.Replace("empty", "TAG")

tem que ser realmente empty lá?
Em qual WebService? Autorização?

**Comment by vasisti** [comment]
nao é empty,  xml.Replace("CTe", "<"CTe xmlns="http://www.portalfiscal.inf.br/cte\">");"
versao 3.00

**Comment by robertorp** [comment]
Irei ajustar isso hoje ainda

**Comment by vasisti** [comment]
Roberto bom dia , Obrigado a atenção, abraços.

________________________________
De: Roberto Alves Pereira <notifications@github.com>
Enviado: quinta-feira, 1 de junho de 2017 10:35:22
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: vasisti; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] namespace na tag CTe (#456)


Irei ajustar isso hoje ainda

**Comment by robertorp** [comment]
Confira se deu certo
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/457

**Comment by vasisti** [comment]
Ola Roberto boa noite, eu testei a implementacao e deu certo, obrigado pela correcao, abracos.
