### ISSUE TITLE
REENVIO de notas após OFFLINE, muda algo nas tags do xml ??

### ISSUE THREAD

**Issue by rcoproc** [ZeusAutomacao/DFe.NET#458]
Se eu guardo o xml de  impressão offline da NFCe e

eu a reenvio dá como cStat 103 , lote recebido com sucesso, me dá até o recibo , mas quando consulto a NFCe ela não está na base da receita vejam: Retorno do re-envio.
```
<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
<tpAmb>2</tpAmb>
<verAplic>MS.SPRINGS-201606010</verAplic>
<cStat>103</cStat>
<xMotivo>Lote recebido com sucesso</xMotivo>
<cUF>50</cUF>
<dhRecbto>2017-06-02T04:15:47-04:00</dhRecbto>
<infRec>
<nRec>500170000114570</nRec>
<tMed>1</tMed>
</infRec>
</retEnviNFe>
```

E aqui embaixo o retorno da consulta da chave na receita. Será que é porque não adicionei os procs/URL code durante o reenvio ????

```
versao = 3.10
tpAmb = taHomologacao
verAplic = MS.SPRINGS-201606010
cStat = 217
xMotivo = Rejeicao: NF-e nao consta na base de dados da SEFAZ
cUF = MS
chNFe = 50170608040168000132650010000006839000006831
protNFe = 
procEventoNFe = System.Collections.Generic.List`1[NFe.Classes.Servicos.Consulta.procEventoNFe]
```

**Comment by adrbarros** [comment]
Na aplicação de teste (NFe.AppTeste)

Você tem uma boa parte da codificação comentada.
Existe 2 formas para envio de NFe/NFCe:
* Assincrona (Chamada Padrão) - onde você envia o XML e tem o retorno citado acima >Lote recebido com sucesso<
Porém creio que essa chamada somente diz q você enviou e se houve algum erro no seu XML, na hora de consultar o retorno da: Rejeicao: NF-e nao consta na base de dados da SEFAZ

*Sincrona - você manda o arquivo e se houver alguma rejeição já tem o retorno no ato do envio

Em poucas palavras é isso.

var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Assincrono, new List<Classes.NFe> {_nfe}, false/*Envia a mensagem compactada para a SEFAZ*/);
//Para consumir o serviço de forma síncrona, use a linha abaixo:
var retornoEnvio = servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Sincrono, new List<Classes.NFe> { _nfe }, true/*Envia a mensagem compactada para a SEFAZ*/);

**Comment by adrbarros** [comment]
Ahhh, nas tags muda sim 
Tipo de Emissão (tpEmis = 9)
Justificativa na emissão offline (xJust)
Data Contingencia (dhCont)

**Comment by rcoproc** [comment]
Adriano , era isto mesmo .. vc matou na mosca.. 

Era o tipo de envio .. estava Assincrono e eu não estava fazendo correto.

Mudei para sincrono o reenvio e coloquei as tags xJust e dhCont.

Valeu cara obrigado e parabéns.. fica ai a dica para a galera.

Deu certo tudo funcionando agora de boa.

Atte.

Ricardo Oliveira
