### ISSUE TITLE
Requisição com certificado A3

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#46]
Boa tarde Adenilton e pessoal

cara você ja se deparou com um erro quando o certificado é do tipo A3 e quanto faz a consulta
na sefaz sob a seguinte exceção:

"the underlying connection was closed an unexpected error occurred on a send".

Quando seleciono certificado A1 da certo, porém quando A3 sobe essa exceção.

**Comment by adeniltonbs** [comment]
celino, nunca vi essa exceção por aqui.
Você pode fazer os seguintes testes:
1 - Tente acessar a url do webservice em questão, utilizando o certificado A3 que apresentou problemas.
Obs: se o webservice for da NFe, você poderá encontrar a url em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=. Para NFCe, procure a url no site da SEFAZ;

2 - Se o teste 1 der certo, confira se a url utilizada na biblioteca está correta;
3 - Se o teste 1 não der certo, redefina as configurações avançadas do internet explorer e teste novamente.

Pela minha experiência se você não conseguir acessar a url do webservice diretamente no internet explorer, utilizando o certificado, tampouco conseguirá consumir o serviço por meio de outro aplicativo.

4 - Teste o certificado em outro PC.

**Comment by celinolimac** [comment]
Valew Adenilton pela resposta...

Cara, na biblioteca antes desse último commit que tem a opção da senha do certificado... em que momento era solicitado o PIN do certificado se ele fosse A3? No App teste, por Exemplo ao colocarmos o token(A3) na maquina e ao buscar o certificado e selecionar ele nos disponíveis ele vai pedir a senha se for a3?

Obg

**Comment by adeniltonbs** [comment]
celino, a forma como o PIN é solicitado não foi alterada neste commit em relação ao commit anterior.

o PIN era e continua a ser solicitado na hora de consumir um serviço pela primeira vez para uma determinada instância de sua aplicação. 
Roteiro de exemplo: 
1 - Abra a aplicação NFe.AppTeste com todas as configurações definidas, inclusive o nº de série do certificado A3, somente deixe a senha do certificado em branco;
2 - Clique no botão Status do Serviço (Neste momento será solicitado o PIN);
3 - Clique novamente no botão Status do serviço, e verás que o PIN não é solicitado na segunda vez. Isso ocorre por que o windows mantém o PIN no cache associado a uma determinada instância da aplicação.

O que foi incluído nos commits recentes foi a opção de você informar o arquivo/senha do certificado A1 e a senha do certificado A3, para este último possibilitando o usuário de não ter que ficar digitando o PIN pelo menos uma vez quando ele abrir o programa.

Ainda é possível usar o certificado A3, sem passar a senha armazenada, deixando para o usuário digitar o PIN, bastando para isso você não informar a senha na função CertificadoDigital.ObterDoRepositorio(string numeroSerial, string senha = null).

Enquanto a função CertificadoDigital.ObterDoRepositorio() serve apenas para abrir a UI do windows responsável por exibir a lista de certificados e devolver o objeto X509Certificate2 com os dados do certificado selecionado na lista.

**Comment by celinolimac** [comment]
Obg pelo retorno adenilton... Bom dia...

Vou realizar esses testes.. E passo o resultado.. So vou poder fazer na segunda, pois o a3 eh num cliente nosso e não tenho esse certificado agora no momento... So a1... Mas segunda acesso la e vejo... Obg pelo help.. Valew

**Comment by celinolimac** [comment]
Bom dia Adenilton, deu certo realizar os testes no A3... obrigado pelas dicas.

**Comment by adeniltonbs** [comment]
Por nada, que bom que deu tudo certo.
