### ISSUE TITLE
O que acham da ideia de um Software Open-Source?

### ISSUE THREAD

**Issue by nfceinteligente** [ZeusAutomacao/DFe.NET#462]
https://docs.google.com/forms/d/e/1FAIpQLScNWLIOqdC0X6SYLiqol3qx0odk8TgNh7XsCzb0Px7LEexxVA/viewform

Oque acham de um software livre?
Digo não e qualquer software e claro, "qualquer" temos o emissor gratuito que já faz isso.

Seria realmente um ERP para o varejo no geral
Supermercados
Perfumaria
Açougue
Joalherias
Oficinas
Etc..

Com uma interface amigável e totalmente open-source.
Com muitos relatórios e possibilidade de adicionar mais sempre.
Quem iria decidir oque seria desenvolvido?
Através de votações com a comunidade.

No lugar de você gastar horas e horas desenvolvendo algo porque não utilizar um open-source né?
Ou talvez se você for se arriscar no mercado de automação comercial você pode iniciar vendendo um software com o custo beneficio bom ne? Melhor ainda se for grátis hehe.

Se poderem responder agradeço. 

Peço aos administradores para deixar pelo menos uma semana. Obrigado.
O software seria concorrente dos softwares atualmente pagos, algo bonito e eficiente, mais de um banco de dados poderia ser utilizado por ele.

**Comment by marcosgerene** [comment]
O sebrae ja faz isso, não sei se é open-source mais é gratuito, pesquisa ai Marketup.

E mais, para arquivos fiscais como SAT, MFe etc é necessario uma empresa com CNAE de desenvolvedor para assinar o software, quem vai fazer isso?

Se for mesmo um ERP e eu quiser participar da comunidade isso vai de encontro ao meu interesse pois estou alimentando o concorrente, isso poderia custar meu emprego se eu for funcionário ou meus clientes se for patrão, então antes de propor o produto deve-se pensar no negócio, como ganhar dinheiro com isso? manutenção? suporte? doação? Por mais que eu ame o que eu faço, eu só trabalho por paixão quando meus boletos estão pagos.

Se você gosta da ideia inicie um projeto aqui no github mesmo, abra o fonte dele e com o tempo interessados vão aparecer e te ajudar, divulgar assim como está fazendo além de não ser eficaz faz uma ideia que pode ser legal se bem trabalhada parecer boba.

Att, Marcos

**Comment by marcosgerene** [comment]
Existem alternativas gratuitas como o MarketUp.

A ideia de monetização é péssima... ou você não faz ideia do que ta falando ou tem alguém por trás bancando isso.

**Comment by marcosgerene** [comment]
https://marketup.com/

http://erplitefree.com.br/home/

https://www.sistemagratis.com.br/

https://www.programanex.com.br/controle-de-vendas

Além de existir muita coisa no "mercado de gratuitos" (o que exige um belo investimento em marketing para tornar a ideia competitiva), vi o seu link e a ideia para monetização é no mínimo "bizarra".
