### ISSUE TITLE
Servico Paralisado sem Previsao

### ISSUE THREAD

**Issue by moises77pereira** [ZeusAutomacao/DFe.NET#463]
Alguém está enfrentando este problema?
Sefaz RJ não consigo fazer download XML.

**Comment by adrbarros** [comment]
Aqui em SP também não estou conseguindo, mesma mensagem recebida da SEFAZ

**Comment by marcosgerene** [comment]
O webservice foi desativado.

http://www.projetoacbr.com.br/forum/topic/37052-nfedownloadnfe-erro-servico-paralisado-sem-previsao/

Agora como usar o método DistribuicaoDFe no componente do Zeus não sei... @robertorp  ou @adeniltonbs  podem responder melhor

**Comment by adeniltonbs** [comment]
Para fazer download do XML você precisa: 1 - Manifestar o documento; 2 - Consumir o serviço NFeDistribuicaoDFe.

Na aplicação de demonstração de uso mostra um exemplo de como consumir ambos serviços. Veja a imagem abaixo:
![image](https://user-images.githubusercontent.com/6733483/27001939-e3d38428-4dab-11e7-85f4-4b0c01ff2b25.png)

Mais informações na [Nota Técnica 2014.002 - v1.02b](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=s/plBMpQotg=)

**Comment by mauriciopfl** [comment]
Estou com problema de comunicação no servidor de MG
"A conexão subjacente estava fechada: Não foi possível estabelecer relação de confiança para o canal seguro de SSL/TLS."

Até para enviar as NFe's será necessário utilizar o tal do NFeDistribuicaoDFe? Como utilizar este serviço? O que muda no envio do NFe?

**Comment by marcosgerene** [comment]
@adeniltonbs

No ACBr para Pascal, existe DistribuicaoDFePorChaveNFe que consome o DistribuicaoDFe passando a chave da NFe que é desejada também pro webservice... como faria isso no Zeus?

------

*Edit:* Os schemas que estão no acbr tem uma versão v1.01 do distDFeInt que permite a busca pela chave, os schemas do Zeus não, acredito que os schemas estejam defasados.

Abraços

**Comment by orochasamuel** [comment]
Fala pessoal, tudo na paz?

Estou fazendo adaptações em um sistema para comportar a nova rotina pela Distribuição DF-e e me esbarrei em um erro.

### Imagem 1 - Exception ao converter XML string para Classe [nfeProc ](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Classes/Servicos/DistribuicaoDFe/Schemas/nfeProc.cs)
![image](https://user-images.githubusercontent.com/15462690/27049451-c3699bba-4f85-11e7-92e4-b083d023bb87.png)

Acontece quando eu tento converter o XML de um nfeProc para classe. Já no caso do resNFe, por exemplo, funciona normal.

### Imagem 2 - Classe [nfeProc ](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Classes/Servicos/DistribuicaoDFe/Schemas/nfeProc.cs)
![image](https://user-images.githubusercontent.com/15462690/27049515-fc43659c-4f85-11e7-931f-3624a168cf7c.png)

*Estou utilizando a versão 1.0.1.518 do pacote Nuget do Zeus.

Se alguém puder me auxiliar serei grato.

Abraços.

**Comment by adeniltonbs** [comment]
@mauriciopfl Veja esse issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/469

Dica: É preferível abrir um novo issue quando for tratar de um assunto diferente.

**Comment by adeniltonbs** [comment]
@marcosgerene O serviço para consulta pela chave, foi liberado em abril, se não me engano. Vou colocar na lista de coisas a fazer e assim que tiver um tempinho implemento-o. Nesses quinze dias começo a implementação do layout 4.0, também farei isso.

**Comment by adeniltonbs** [comment]
@samuelroliveira é possível nos enviar o XML? 

Você pode anexar um arquivo no na conversa, clicando na opção "selecting item" ou CTRL+V, conforme dica abaixo:
![image](https://user-images.githubusercontent.com/6733483/27080895-5cf4b1aa-5014-11e7-9e71-c9a4ef095fae.png)

**Comment by adrbarros** [comment]
Bom dia, para resolver seu problema no momento, tente fazer assim:

var procNFeConteudo = new NFe.Classes.NFe().CarregarDeXmlString(conteudo);

**Comment by adrbarros** [comment]
Correção
                            var procNFeConteudo = new NFe.Classes.nfeProc().CarregarDeXmlString(conteudo);
                            if (procNFeConteudo != null)
                                chaveNFe = procNFeConteudo.protNFe.infProt.chNFe;

**Comment by moises77pereira** [comment]
Eu implementei desta forma me tirar do sufoco:
criei um método para recepção de chaveDistribuição. Desta forma eu consegui baixar o xml.
Obs.: Não é o correto pois está fora do padrão do projeto, o correto é implementar como adeniltonbs menconou na Issue #470 

/// <summary>
        /// Serviço destinado à distribuição de informações resumidas e documentos fiscais eletrônicos de interesse de um ator, seja este pessoa física ou jurídica.
        /// </summary>
        /// <param name="ufAutor">Código da UF do Autor</param>
        /// <param name="documento">CNPJ/CPF do interessado no DF-e</param>
        /// <param name="chave">Chave XML a ser baixado</param>
        /// <returns>Retorna um objeto da classe RetornoNfeDistDFeInt com os documentos de interesse do CNPJ/CPF pesquisado</returns>
        public RetornoNfeDistDFeInt DistribuicaoDFePorChaveNFe(string ufAutor, string documento, string chave)
        {
            var versaoServico =
                ServicoNFe.NFeDistribuicaoDFe.VersaoServicoParaString(_cFgServico.VersaoNFeDistribuicaoDFe);

            #region Cria o objeto wdsl para consulta

            var ws = CriarServico(ServicoNFe.NFeDistribuicaoDFe);

            ws.nfeCabecMsg = new nfeCabecMsg
            {
                cUF = _cFgServico.cUF,
                versaoDados = "1.01"
            };

            #endregion

            #region Cria o objeto distDFeInt

            var pedDistDFeInt = new distDFeInt
            {
                versao = "1.01",//versaoServico,
                tpAmb = _cFgServico.tpAmb,
                cUFAutor = _cFgServico.cUF,
                consChNFe = new consChNFe { chNFe = chave }

            };

            if (documento.Length == 11)
                pedDistDFeInt.CPF = documento;
            if (documento.Length > 11)
                pedDistDFeInt.CNPJ = documento;

            #endregion

            #region Valida, Envia os dados e obtém a resposta

            var xmlConsulta = pedDistDFeInt.ObterXmlString();
            //Validador.Valida(ServicoNFe.NFeDistribuicaoDFe, _cFgServico.VersaoNFeDistribuicaoDFe, xmlConsulta);
            var dadosConsulta = new XmlDocument();
            dadosConsulta.LoadXml(xmlConsulta);

            //SalvarArquivoXml(DateTime.Now.ParaDataHoraString() + "-ped-DistDFeInt.xml", xmlConsulta);

            XmlNode retorno;
            try
            {
                retorno = ws.Execute(dadosConsulta);
            }
            catch (WebException ex)
            {
                throw FabricaComunicacaoException.ObterException(ServicoNFe.NFeDistribuicaoDFe, ex);
            }

            var retornoXmlString = retorno.OuterXml;
            retDistDFeInt retConsulta = null;
            try
            {
                retConsulta = new retDistDFeInt().CarregarDeXmlString(retornoXmlString);
            }
            catch
            {
            }

            //SalvarArquivoXml(DateTime.Now.ParaDataHoraString() + "-distDFeInt.xml", retornoXmlString);

            #region Obtém um retDistDFeInt de cada evento e salva em arquivo
            string xmlRetorno = string.Empty;
            if (retConsulta != null)
            {
                if (retConsulta.loteDistDFeInt != null)
                {
                    for (int i = 0; i < retConsulta.loteDistDFeInt.Length; i++)
                    {

                        string conteudo = Compressao.Unzip(retConsulta.loteDistDFeInt[i].XmlNfe);
                        string chNFe = string.Empty;

                        if (conteudo.StartsWith("<nfeProc "))
                        {
                            SalvarArquivoXml(chave + "-NFe.xml", conteudo);
                        }
                    }
                }
            }

            #endregion

            return new RetornoNfeDistDFeInt(pedDistDFeInt.ObterXmlString(), retConsulta.ObterXmlString(),
                retornoXmlString, retConsulta);

            #endregion
        }

**Comment by orochasamuel** [comment]
@adeniltonbs testei da forma como o @adrbarros citou e deu certo.

Estou anexando um dos XML da nfeProc. Acredito que seja alguma inconsistência no schema.
[588-nfeProc.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1080807/588-nfeProc.zip)

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/430 implementado download pelo Distribuição
