### ISSUE TITLE
Envio de NF, dúvidas.

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#468]
Premissas:
- Tenho um token válido;
- Estou apontando para o ambiente de homologação;
- tenho um CSC de "testes";
- Está gerando estes dois arquivos.

<img width="497" alt="capturar" src="https://user-images.githubusercontent.com/28018162/27014146-d9458010-4ec8-11e7-9d31-b7ee840f99fc.PNG">

1) Porque da necessidade do "Id do lote" para o envio de uma única nota fiscal?

2) A url do QrCode está dando "NFC-e não localizada", porque?

**Comment by Guaze** [comment]
Exemplo QrCode: http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?chNFe=33170609283537000180650010000000861000000865&nVersao=100&tpAmb=2&dhEmi=323031372d30362d31315431393a31333a30372d30333a3030&vNF=3.29&vICMS=0.00&digVal=316a4e465a6d5834544e525764434f78464a43797751324c6a64633d&cIdToken=000001&cHashQRCode=392bc6da2da524ce17d4ed4db106b22315c6994c

o XML que retorna no exemplo de envio de nfce  (criar e enviar 3) não tem essa marcação.

<img width="503" alt="capturar" src="https://user-images.githubusercontent.com/28018162/27015026-dfd147ea-4eda-11e7-94cf-8a71a20c80be.PNG">

**Comment by robertorp** [comment]
Toda NF-e enviada Síncrona ou Assíncrona e com lote no Zeus, e so olhar o método 

RetornoNFeAutorizacao NFeAutorizacao(int idLote, IndicadorSincronizacao indSinc, List<Classes.NFe> nFes,
            bool compactarMensagem = false)

Sempre tem lote é uma lista de objetos, Zeus se encarrega de criar para você o lote, independente se e assíncrono ou síncrono. Também pode ficar a vontade para criar um método que não precise do lote, se a Sefaz aceitar.

Agora sobre a duvida do qrcode não entendi, poderia especificar ela melhor

**Comment by Guaze** [comment]
Boa tarde, agradeço o retorno.

Desta vez tentarei ser mais claro na minha dúvida.

Estou trabalhando na construção de sistema extremamente customizado para o negócio da família. Tenho como referência o sistema usado atualmente.

Neste momento, estou na parte de enviar as notas fiscais e por isso, que estou utilizando o Zeus para me auxiliar nesta etapa do projeto.

O arquivo .xml que o sistema gera segue ao modelo abaixo.
[arquivo2.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1078467/arquivo2.pdf)

Muito semelhante que eu consegui gerar com o Zeus.
[arquivo3.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1078470/arquivo3.pdf)

Exceto por essa diferença.
<img width="503" alt="27015026-dfd147ea-4eda-11e7-94cf-8a71a20c80be" src="https://user-images.githubusercontent.com/28018162/27194469-071a9382-51d9-11e7-86a5-426d6a410e2e.PNG">

Por isso, que eu perguntei se o "Id do lote" fazia alguma diferença. Aproveitando o explicado anteriormente sobre o assunto: Como o componente Zeus trata do "Id do lote" sozinho? Li que a entrega síncrona só pode ser utilizada para enviar uma NF pro vez, logo poderia utilizar o o número da nota fiscal com lote.

A segunda questão é o: QrCode. Fiz as configurações que entendi ser necessárias conforme o exemplo.
E que levou a criação desta url para o ambiente de homologação.
 http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?chNFe=33170609283537000180650010000000861000000865&nVersao=100&tpAmb=2&dhEmi=323031372d30362d31315431393a31333a30372d30333a3030&vNF=3.29&vICMS=0.00&digVal=316a4e465a6d5834544e525764434f78464a43797751324c6a64633d&cIdToken=000001&cHashQRCode=392bc6da2da524ce17d4ed4db106b22315c6994c

Só que quando a utilizo aparece a mensagem no browser "nfce não localizada", ou seja, ainda há alguma inconformidade que não consegui entender.

Apesar de a nota fiscal ter "ido e voltado".
<img width="497" alt="27014146-d9458010-4ec8-11e7-9d31-b7ee840f99fc" src="https://user-images.githubusercontent.com/28018162/27194729-1325155c-51da-11e7-95fa-323fa33babb7.PNG">


Não consegui ter certeza do meu desenvolvimento.

**Comment by adeniltonbs** [comment]
**> Como o componente Zeus trata do "Id do lote" sozinho?** 

Olhe o que o manual fala sobre a Id do Lote:
![image](https://user-images.githubusercontent.com/6733483/27225301-ed6784c6-526f-11e7-9031-a37e5e304274.png)

Conforme consta no manual, a Id do lote é de responsabilidade do contribuinte, então a biblioteca Zeus não trata ou gera essa Id, ela simplesmente a pede como parâmetro para o método de envio. Essa Id deve ser gerenciada pelo domínio de sua aplicação, assim como o número e série da nota, e não pela biblioteca. 

Veja a assinatura do método de envio:
![image](https://user-images.githubusercontent.com/6733483/27225386-3f551cc6-5270-11e7-8c01-e1dc0e272f55.png)

Para mais detalhes consulte a documentação da NFe e o código por trás do botão "Criar e enviar 3.0" da aplicação de demonstração de uso:
![image](https://user-images.githubusercontent.com/6733483/27225449-8fabb3a6-5270-11e7-87d2-d5706656d9fb.png)

No projeto da NF-e é possível enviar uma única nota sem informar o lote? Sim, é possível. Mas a biblioteca Zeus não implementou nenhum método para isso no momento, dependendo assim da informação de um lote para envio. Agora se sua aplicação não vai enviar mais de uma nota por vez, então não se preocupe com essa Id, apenas informe ali qualquer coisa como um valor autoincremento e não terá problemas, já que cada nfe enviada gera um recibo (no modo assíncrono) e no modo síncrono você já recebe o retorno do processamento e ainda que dê erro, você pode consultar pela chave depois.

**> Só que quando a utilizo aparece a mensagem no browser "nfce não localizada", ou seja, ainda há alguma inconformidade que não consegui entender.**

Você chegou a transmitir essa NFCe com chave = 33170609283537000180650010000000861000000865? No site da SEFAZ RJ informa que essa NFCe não existe, veja:
![image](https://user-images.githubusercontent.com/6733483/27225642-81ece13a-5271-11e7-9fd3-fd396d0f3ffb.png)

**Comment by Guaze** [comment]
Bom dia,

Problema resolvido.

A causa principal era o cEAN inválido que eu estava enviado. Depois de colocar um válido funcionou.

Para o ambiente de homologação  tive que ajusta a descrição do 1° item para funcionar. "NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL".
