### ISSUE TITLE
Erro de TSL/SSL Transport depois de atualização de cadeias de certificados pela SEFAZ MG

### ISSUE THREAD

**Issue by Juniornativa** [ZeusAutomacao/DFe.NET#469]
Olá pessoa! Após uma atualização da cadeia de certificados na SEFAZ MG, ao enviar uma nota está dando um erro falando que não foi possível estabelecer uma conexão segura TSL/SSL, oque pode ter acontecido? Onde ficam as configurações de SSL/TSL na framework? Mesmo instalando o novo certificado no windows esta dando esse erro, o sistema é web e funciona com os certificados A1 onde o aplicativo realiza a leitura do certificado com a senha para realizar a assinatura.
Valeu gente!

**Comment by adeniltonbs** [comment]
Com esse certificado, você consegue acessar pelo navegador as [urls](http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#MG) dos serviços para MG normalmente?

Tentou mudar o protocolo de segurança?

![image](https://user-images.githubusercontent.com/6733483/27080432-3bbf2148-5012-11e7-9f49-c5422fb00dff.png)

**Comment by robertorp** [comment]
Quando acontece qualquer erro que envolva certificado digital, na empresa aqui costumamos usar isso também https://serasa.certificadodigital.com.br/teste/  , acho ele mais garantido que acessar um webservice da sefaz

**Comment by mauriciopfl** [comment]
Estou com o mesmo problema, em um ambiente totalmente configurado, já testei em outros computadores e o resultado é o mesmo. 
**Ontem no horário das 10:00 ás 13:00 voltou a funcionar normalmente e depois parou novamente.**
O servidor de homologação funciona corretamente, porém o de produção apresenta esta mensagem ai. Engraçado é que no site de disponibilidade dos servidores não apresenta a falha.
O que pode estar acontecendo?

**Comment by robertorp** [comment]
@mauriciopfl Muda o protocolo de comunicação para o de produção e testa

**Comment by mauriciopfl** [comment]
@robertorp já tentei, o erro persiste:

![image](https://user-images.githubusercontent.com/12702629/27082270-80dc6f6c-501a-11e7-84ef-beadb3c14a1d.png)

![image](https://user-images.githubusercontent.com/12702629/27082282-8e5957ae-501a-11e7-93ce-4f0c46ff1145.png)

Em homologação está OK! Funciona normalmente:
![image](https://user-images.githubusercontent.com/12702629/27082314-a606e6aa-501a-11e7-97b7-c6a0c355b5c3.png)





O mais engraçado é que ontem das 10:00 ás 13:00 voltou a funcionar normalmente, depois parou :(
Estou utilizando certificados A1, estava funcionando normalmente até quinta-feira passada: 08/06/17.
Os certificados de SP A1 também, estão OK, funcionando normalmente, apenas MG está com este problema.


Realizei o teste do certificado também:

![image](https://user-images.githubusercontent.com/12702629/27082510-80199dce-501b-11e7-8ee1-01c94f42fe22.png)

SP está normal:

![image](https://user-images.githubusercontent.com/12702629/27082534-944fef96-501b-11e7-83fe-a6a7d6a67c34.png)


Quando vocês fazem o teste de "Status do Serviço" para servidor de MG o resultado é qual? Poderiam compartilhar?

**Comment by mauriciopfl** [comment]
O mais engraçado é que ontem das 10:00 ás 13:00 voltou a funcionar normalmente, depois parou :(

**Comment by lucascborges** [comment]
Voce já instalou a nova hierarquia de certificados? Não estou usando a biblioteca para autorizar porem utilizando ACBR tive problemas, resolvi instalando a hierarquia, segue link:
https://www.certisign.com.br/atendimento-suporte/downloads/hierarquias/icp-brasil/nf-e

**Comment by adrianormp** [comment]
Tive o mesmo problema. Basta atualizar as novas cadeias do certificado no link: http://portalnfe.fazenda.mg.gov.br/download.html

**Comment by mauriciopfl** [comment]
@ryok21 Obrigado pela atenção! Sim. Na verdade o Zeus localiza o arquivo A1 diretamente no diretório.  Não influencia o certificado estar instalado ou não na maquina. Mesmo assim eu fiz a instalação dos certificados. Não funciona.
Funcionou perfeitamente por 8 meses e meio, agora começou com este problema sem explicação nenhuma, e é apenas no servidor de **produção de MG**. 
Segunda-feira (12/06/17) por um período voltou ao normal, porém agora parou novamente.
Já pesquisei nos sites da SEFAZ e não encontrei nenhuma notificação de modificações nos serviços. Quando consulta a disponibilidade no site da receita: https://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx
Mostra que está OK os serviços.

Então já estou sem ideia do que pode ser.
Alguém poderia fazer o teste de disponibilize nos servidores MG pelo Zeus e postar o print com os resultados por favor?

**Comment by mauriciopfl** [comment]
@adrianormp como faço isso?

**Comment by mauriciopfl** [comment]
Utilizando o Formato A1 o Zeus localiza o arquivo do certificado diretamente no diretório. Como faço pra atualizar essa cadeia de certificados?

**Comment by Juniornativa** [comment]
Ainda também estou com o mesmo problema,

Em 14 de junho de 2017 10:01, Maurício Pereira Filho <
notifications@github.com> escreveu:

**Comment by rodrigordi** [comment]
Você precisa validar o certificado do servidor ? No meu projeto eu configurei para não validar o certificado e configurei os protocolos também.

![image](https://user-images.githubusercontent.com/1608626/27136159-ec085ce8-50f0-11e7-869a-9c1709d84371.png)

Lembrando que SEFAZ/MG não aceita SSLv3.

![image](https://user-images.githubusercontent.com/1608626/27136230-2d2a9402-50f1-11e7-941f-f12668e5a723.png)

Você pode baixar a nova cadeia de certificados e instalar na maquina também.

![image](https://user-images.githubusercontent.com/1608626/27136281-4dec0090-50f1-11e7-847f-f5af3e586f9a.png)

Cada uma nas respectivas pastas do repositorio do windows.

![image](https://user-images.githubusercontent.com/1608626/27136328-7278a580-50f1-11e7-85b5-c7ea61ae3c18.png)

**Comment by mauriciopfl** [comment]
@rodrigordi obrigado pelo retorno. Onde vc configurou esse ServerCertificateValidationCallback? Não encontrei no projeto...
Outra coisa, o certificado é um arquivo .pfx, ou seja, ele nem entra na lista de cadeia de certificado Windows, entra?

**Comment by rodrigordi** [comment]
@mauriciopfl eu ainda não olhei esse projeto aqui não. mas o servicepointmanager é uma classe static q voce pode setar em qq lugar do codigo. de preferencia antes de chamar o webservice.

quanto ao certificado : arquivo pfx é certificado com o par de chaves (privada e publica). a sefaz disponibiliza somente as chaves publicas. 

clica no link : http://portalnfe.fazenda.mg.gov.br/downloads/cadeia_certificacao_SEF_MG.zip
![image](https://user-images.githubusercontent.com/1608626/27136985-1150dbb8-50f3-11e7-8952-f2105f4b880b.png)

clica em cada arquivo .cer : chave publica.
![image](https://user-images.githubusercontent.com/1608626/27137020-2818e9d0-50f3-11e7-8575-c0547dae02b7.png)

depois clica em instalar certificado. repita para todos os certificados.

quando voce abrir o certificado da sefaz/mg (o mais baixo da cadeia) ele deverá ficar assim : 
![image](https://user-images.githubusercontent.com/1608626/27137080-592ce8dc-50f3-11e7-8b40-06ccf329cca6.png)

Se tiver algum X vermelho é pq deu ruim no caminho.

**Comment by mauriciopfl** [comment]
@rodrigordi MUITOOO OBRIGADO..  deu certo!! eu já havia instalado os certificados públicos, porém nos caminhos errados., utilizando o exemplo no seu post deu certo, bastava instalar nos diretórios corretos mesmo.

![image](https://user-images.githubusercontent.com/12702629/27137232-c03505c8-50f3-11e7-84f7-8a2ca1992773.png)


Agradeço a paciência e contribuição de todos.

Abraços

**Comment by rodrigordi** [comment]
joia! só fechar .

**Comment by Juniornativa** [comment]
Olá, pessoal! Esta cadeia de certificados é necessária mesmo quando o
certificado para emissão da nota for A1 em arquivo? Onde é passado apenas o
caminho do certificado e a senha sem a necessidade de ser instalado ? Meu
sistema é web e cada cliente tem um certificado A1 em arquivo diferente,
então para assinar o sistema busca o arquivo certificado e a senha e
realiza a assinatura. Não está dando certo para mim, funcionava normalmente
antes. Em qual diretórios devo instalar todos estes certificados? No
"Autoridades de Certificação Raiz Confiáveis" ?

Desde já agradeço.

2017-06-14 11:32 GMT-03:00 RODRIGO <notifications@github.com>:

**Comment by Juniornativa** [comment]
Gente, já deu certo graças a Deus. Eu estava instalando o certificado com conta de usuário, ai reinstalei como conta do computador atual, ai funcionou legal. Valeu pela ajuda pessoal! Abraços
