### ISSUE TITLE
Erro Cancelamento de NFC-e

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#47]
Bom dia!

Estou com erro ao realizar o cancelamento de uma NFC-e para o estado do Mato Grosso (MT).
No validador do Zeus tenho o seguinte retorno:
Erros da validação : O atributo 'versao' é inválido - O valor '3.10' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerEnvEvento' - Falha na restrição Pattern.

Estou usando a versão 3.10 do Recepção Evento.

Você poderia me orientar a encontrar esse erro? Se poderia ser na versão errado do XSD, ou qualquer outra informação que estou passando.

Muito obrigado!

**Comment by leandrossantos** [comment]
Oi Pedro, boa tarde. Tentou alterar a versão do RecepcaoEvento para 1.00, tenta isso.

**Comment by ghost** [comment]
Olá Leandro,

Realizei esse teste, porem também ocorre erro. Mas esse erro é diferente, pq ele não encontra versão 1.00 para esse web service, já que no código está fixo como 3.10.

**Comment by ghost** [comment]
Quando colo a versão 1.00 aparece:
Serviço RecepcaoEvento, versão 1.00, não disponível para a UF MT, no ambiente de Produção para emissão tipo Normal, documento: NFC-e!

**Comment by ghost** [comment]
Consegui resolver o problema alterando a classe Enderecador no projeto NFe.Servicos.
Na linha do mato grosso, do ambiente de produção e homologação ajustei de ve310 para ve100

endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve100, TipoAmbiente.taProducao, emissao, Estado.MT, ModeloDocumento.NFCe, "https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento?wsdl"));

Adenilton, você poderia confirmar se estava errado mesmo? pois na ve310 não funciona, apenas na ve100.

Obrigado.

**Comment by adeniltonbs** [comment]
Estou viajando, assim que chegar verifico

**Comment by adeniltonbs** [comment]
Ok, vou alterar a versão do serviço RecepcaoEvento para MT, documento do tipo NFCe de 3.10 para 1.00, no entanto gostaria de sua ajuda para definir as versões corretas para cada serviço de NFCe para essa UF, haja vista que eles não publicaram essa informação em https://www.sefaz.mt.gov.br/portal/nfce/?pg=cGdJbmZvcm1hY2Fv.

Ajudaria se o pessoal da SEFAZ fosse mais organizado e publicasse essas informações no mesmo molde em que é publicado no portal nacional (http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#MT)

**Comment by ghost** [comment]
Olá Adenilton, desculpe a demora!

Muito obrigado pelas alterações. 
Claro, vou realizar os testes nos outros serviços e te passa a versão correta de cada um.

Sim, infelizmente eu também busquei essa informação mas não encontrei. Sobre a NF-e em alguns estados já em bem difícil, agora a NFC-e, que é nova ainda, é mais difícil ainda.

**Comment by ghost** [comment]
Olá Adenilton, desculpe a demora!

Confirmei todas as versões e está correto. Todas são a versão 3.10 e apenas o RecepcaoEvento  é 1.00 mesmo, para o estado do Mato Grosso.

Obrigado pela ajuda.

**Comment by adeniltonbs** [comment]
Obrigado por verificar.

**Comment by bematechjundiai** [comment]
Bom dia estou com um problema na hora de realizar um cancelamento de um XML do AM ocorre o erro 99990 alguem sabe me informar o motivo desse erro?

Obrigado
