### ISSUE TITLE
Implementar mudanças promovidas na versão 1.02 e 1.02b da NT 2014/002 em relação ao Web Service de Distribuição de DF-e

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#470]
Entre as alterações previstas na NT estão:

## 1.02
- Inclusão para distribuição dos Eventos: Registro de Passagem, Pedido de Prorrogação/Cancelamento do prazo de suspensão do ICMS nas remessas enviadas para industrialização e os demais Eventos de Resposta do Fisco;
- Possibilidade de consulta ao Web Service para uma chave de acesso de NF-e informada;
- Distribuição do Evento de Cancelamento para o destinatário independente de sua manifestação;

## 1.02b
Inclusão para distribuição dos Eventos de Averbação.

**Comment by adrbarros** [comment]
Tem um pull request meu:
Redimensionamento no tamanho do campo quantidade. (NFeRetrato) #430

Onde tem um implementação para:
Ajustes no método NfeDistDFeInteresse da classe ServicosNFe para fazer a execução do método com a opção para informar Chave Eletrônica. Atualização dos schemas [PL_NFeDistDFe_102]

Não sei porque, mas tentei criar um novo pull request comente com essa implementação, mas acabou sendo redirecionado junto com o #430
