### ISSUE TITLE
Implementar alterações promovidas pela Nota Técnica 2016.002 (layout 4.0 da NFe)

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#471]

**Comment by robertorp** [comment]
@adeniltonbs  pretende começar as alterações quando? Digo aqui fiz a consulta status na nf-e 4.0 já. Funcionou na versão .net 4, não sei se é porque ta no começo e pode ser um bug da sefaz.

Pull com consulta status -> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/482

Podemos dividir o trabalho para andar mais rápido.

**Comment by rodrigordi** [comment]
O framework está influenciando na versao do TLS ?

**Comment by robertorp** [comment]
@rodrigordi Então cara, não entendi o porque funcionou. Coloquei somente TLS e funcionou em homologação. Acho que é bug da sefaz de goiás, ate porque no modo de homologação você pode enviar para as webservice 3.1 que da rejeição (rejeição da versão 4.0). Pra min a sefaz de goiás ta muito bagunçada. Por exemplo se um cliente meu der algum piti de xml e tal, como vou testar em homologação sendo que não tenho 3.1 mais? 
Talvez daqui uns dias tudo normalize por aqui.

**Comment by adeniltonbs** [comment]
@robertorp Semana que vem pego o projeto pra começar a alterar para 4.0. Tava pensando a respeito e acho que o maior desafio vai ser manter as duas versões em funcionamento, no modelo atual.

**Comment by robertorp** [comment]
implementando aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503

**Comment by adeniltonbs** [comment]
Será fechado para ser fragmentado em issues mais específicos.
