### ISSUE TITLE
Donwload XML NFe - Distribuicao DF-e

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#472]
Olá @adeniltonbs , boa tarde

Fazendo a descompactação do retorno da RetornoNfeDistDFeInt depois de descompactar ele retoana para uma string o conteudo de cada NF-e localizada. 
No projeto tem alguma função para capturar esse retorno descompactado direto na classe como carregarxmldastring?

 #grd abs

**Comment by orochasamuel** [comment]
@alsantana nesse link, na linha 808 está o método de Distribuição.

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/blob/master/NFe.Servicos/ServicosNFe.cs

Na linha 877 ele transforma o retorno no objeto real, acredito que aqui você encontre um exemplo do que deseja.

**Comment by alsantana** [comment]
Olá @samuelroliveira mto obrigado pela dica
consegui resolver
grd abs

**Comment by alsantana** [comment]
@samuelroliveira e @adeniltonbs 
Estou tentando fazer o download da NF-e consultando uma NSU especifica e está retornando o seguinte erro.

![image](https://user-images.githubusercontent.com/16413266/27236482-9580bd78-529b-11e7-8a1f-bd77c8a6c57a.png)

Em anexo está o xml que está indo na consulta.

[dfe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1081440/dfe.zip)

**Comment by orochasamuel** [comment]
@alsantana a nota que você está tentando baixar já foi manifestada com ciência da operação?

Sem esse processo antes você não consegue baixar. E posso estar equivocado ao dizer isso mas, acho que o schema usado está desatualizado.

EDIT: @alsantana como você está fazendo a consulta do documento fiscal?

**Comment by alsantana** [comment]
Ola meu caro, bom dia
Fiz a atualização dos schemas e continua o problema, a NF-e que estou testando fiz a manifestação sem problemas.
Vc poderia me mandar os schemas que vc está utilizando?
grd abs

**Comment by orochasamuel** [comment]
@alsantana estou usando os mesmos que já vem no projeto, mas se eu não estiver enganado teve um colega que fez um comentário em uma issue sobre schemas novos.

No meu sistema eu não faço uso do download individual, primeiro o usuário "lista" todas as notas, manifesta todas elas com ciência, e faz o download de todas de uma vez. Caso alguma nota seja indevida, o usuário manifesta como Desconhecimento ou Operação não Realizada.

Espero ter ajudado. Abraços.

EDIT: Esqueci de anexar os  schemas. --' | [Schemas.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1085983/Schemas.zip) |

**Comment by alsantana** [comment]
Olá @samuelroliveira e @adeniltonbs , bom dia
Consegui resolver fazendo um ajuste na função `NfeDistDFeInteresse(string ufAutor, string documento, string ultNSU, string nSU = "0")`

Segue abaixo o ajuste que realizei.

`            var pedDistDFeInt = new distDFeInt
            {
                versao = versaoServico,
                tpAmb = _cFgServico.tpAmb,
                cUFAutor = _cFgServico.cUF,
                //distNSU = new distNSU {ultNSU = ultNSU.PadLeft(15, '0')}

            };

            if (documento.Length == 11)
                pedDistDFeInt.CPF = documento;
            if (documento.Length > 11)
                pedDistDFeInt.CNPJ = documento;
            if (!string.IsNullOrEmpty(ultNSU))
                pedDistDFeInt.distNSU = new distNSU {ultNSU = ultNSU.PadLeft(15, '0')};
            if (!string.IsNullOrEmpty(nSU))
                pedDistDFeInt.consNSU = new consNSU {NSU = nSU.PadLeft(15, '0')};
`

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/430

**Comment by orochasamuel** [comment]
Fala pessoal, tudo na paz?

Fiz uns testes na lib para fazer o download pela Chave de Acesso e me deparei com um erro.

### Erro
![image](https://user-images.githubusercontent.com/15462690/30254211-648bcf78-966b-11e7-9c64-c69da920a454.png)


### Origem do erro (janela à direita)
![image](https://user-images.githubusercontent.com/15462690/30254157-c03ecb1e-966a-11e7-80b9-c7a06cbce40c.png)

Fiz a inclusão de uma linha para obter o XML da nfeProc direto mas quando tento usar o schema dentro da pasta de DistribuiçãoDFe obtenho o erro mas, se usar a classe nfeProc da raiz da pasta NFe.Classes funciona.

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira Crie uma nova issue para isso, para melhor discutirmos esse erro. Obrigado
