### ISSUE TITLE
[DÚVIDA] nItemPed por ser opcional não deveria ser Nullable?

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#473]
Bom dia pessoal.
Estou com essa dúvida:
prod.nItemPed não deveria ser anulável visto que é um numérico opcional segundo o manual.
Por que se não quero informa-lo ele vem zero, visto que e é do tipo integer.
Alguma sugestão?

**Comment by robertorp** [comment]
![npeditem](https://user-images.githubusercontent.com/10251705/27350694-6a5d0d2a-55d1-11e7-9bec-01fddcab2df8.png)

Aparentemente esta correto, sua versão esta atualizada?

**Comment by FabioHenriqueMF** [comment]
@robertorp  realmente minha versão estava desatualizada.
Obrigado.
