### ISSUE TITLE
Grupo ObsCont com Problemas.

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#474]
Boa tarde Adenilton e Programadores do projeto...
Fuim hoje implementar o campo obscont dentro de infAdic
e percebi que a DLL está tratando o campo xCampo como uma propriedade e não como um atributo
resumindo pra ficar mais claro... ao invés de sair assim

<obsCont xCampo="Pedido">
    <xTexto>123456</xTexto>
</obsCont>
está saindo assim
<obsCont>
    <xCampo>Pedido</xCampo>
    <xTexto>123456</xTexto>
</obsCont>

Se puderem dar uma olhada agradeço desde já...
e Obrigado pela atenção e pelo excelente trabalho...
Se for o caso de sair uma correção, se é que é passivo disso, se for possivel atualizar o NUGET agradeço desde já.

**Comment by robertorp** [comment]
Faz o passo a passo no app exemplo para nos analisar. E Mostra para nos no xml/projeto como deveria ficar.

**Comment by guimagcpd** [comment]
no app faço assim

dim observacoes As New List(Of obsCont)
Dim obs As obsCont

Dim infAdic = New infAdic()
infNFe.infAdic = infAdic

obs.xCampo = "teste1"
obs.xTexto = "obs1"
observacoes.Add(obs)

infNFe.infAdic.obsCont = observacoes

era pra sair assim.
<infAdic>
     <obsCont xCampo="RESPONSAVEL">
          <xTexto>OBAMA</xTexto>
     </obsCont>
     <obsCont xCampo="NOTA FISCAL">
          <xTexto>NOTA FISCAL GERADA COM SUCESSO</xTexto>
     </obsCont>
</infAdic>

e quando gero o XML ta saindo assim

<infAdic>
     <obsCont>
          <xCampo>RESPONSAVEL</xCampo>
          <xTexto>OBAMA</xTexto>
     </obsCont>
      <obsCont>
          <xCampo>NOTA FISCAL</xCampo>
          <xTexto>NOTA FISCAL GERADA COM SUCESSO</xTexto>
     </obsCont>
</infAdic>

**Comment by adrbarros** [comment]
Classes obsCont e obsFisco:

a propriedade de q ser um Atributo:
[XmlAttribute]
public string xCampo { get; set; }

**Comment by guimagcpd** [comment]
acredito que seja isso mesmo, tem que fazer a alteração na DLL e também no pacote nuget para que todos fiquem com essa adaptação / correção...
desde ja agradeço o retorno de vcs...
e aguardo correção...
até.

**Comment by robertorp** [comment]
Lhe peço para dar um feedback. As alterações foram aplicadas. (O mesmo ocorre com o CT-e mas no ct-e já estava correto)

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/476

edit: atualização do nuget apos o feedback se esta ok
