### ISSUE TITLE
ICMS - Tributação

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#48]
Boa noite Adenilton.

Sobre a parte de tributação informada dos produtos na geração do xml que será enviado ao sefaz para autorização, vi que criaste um enum, conforme abaixo:

Arquivo: ICMSTipos.cs
 public enum Csosnicms
    {
        [XmlEnum("101")] Csosn101 = 101,
        [XmlEnum("102")] Csosn102 = 102,
        [XmlEnum("103")] Csosn103 = 103,
        [XmlEnum("201")] Csosn201 = 201,
        [XmlEnum("202")] Csosn202 = 202,
        [XmlEnum("203")] Csosn203 = 203,
        [XmlEnum("300")] Csosn300 = 300,
        [XmlEnum("400")] Csosn400 = 400,
        [XmlEnum("500")] Csosn500 = 500,
        [XmlEnum("900")] Csosn900 = 900
    }

Disto isto, durante a montagem da nota informamos qual o tipo de ICMS. Exemplo:

Csosn101: return new ICMSSN101 { CSOSN = Csosnicms.Csosn101, orig = origem };

Algumas operações não estão implementadas, tais como:

Na parte do Simples:
- ICMSSN103
- ICMSSN203
- ICMSSN300
- ICMSSN400

E no lucro:
- ICMS30
- ICMS40
- ICMS41
- ICMS50

Confere, ou estou falando besteira ?
Pensei em estar me passando em algo. Ou de fato não é utilizado essas que citei acima ?
Moro no RS.

Obrigado,
Darlan Hendges.

**Comment by adeniltonbs** [comment]
Vou verificar assim que retornar de viagem

**Comment by marciojmuller** [comment]
Olá!
Na verdade quando você gerar o XML as tags do 40 41 e 50 devem gerar apenas a ICMS40 
o mesmo caso as 102, 103, 300 e 400 que geram somente a ICMSSN102

**Comment by darlanhendges** [comment]
Boa noite Marcio,

antes de mais nada obrigado pela ajuda.

Falando um pouco mais na prática, quer dizer que:

Se escolhido 103 = return new ICMSSN102 { CSOSN = Csosnicms.Csosn102, orig = origem };

E a mesma regra se aplica para as outras situações que comentaste, correto ?

Ou entendi errado ?

Obrigado.

**Comment by marciojmuller** [comment]
Olá!
Não, fica preenchido assim:
Se escolhido 103 = return new ICMSSN102 { CSOSN = Csosnicms.Csosn103, orig = origem };

exemplo:
ICMSSN102/CSOSN= 102
ICMSSN102/CSOSN= 103
ICMSSN102/CSOSN= 300
ICMSSN102/CSOSN= 400

ICMSSN202/CSOSN= 202
ICMSSN202/CSOSN= 203

..... e assim por diante nos outros casos que são assim.

**Comment by darlanhendges** [comment]
Bá tchê!
Bem certinho.

Obrigado pela ajuda Marcio.
