### ISSUE TITLE
Erro ao carregar xml e enviar - Nfe.AppTeste

### ISSUE THREAD

**Issue by felipelatini** [ZeusAutomacao/DFe.NET#480]
Bom dia,
Sou novo no forum muito obrigado quem puder ajudar. Estou implementando o Zeus no meu sistema.
Montei um xml no qual esta assinando e validando pelo método de exemplo do Zeus.
Só que quando vai enviar está dando a mgs:
'A solicitação foi anulada: Não possível criar um canal seguro para SSL/TLS.'
Estou utilizando A1.

**Comment by adeniltonbs** [comment]
Bom dia,
Com seu certificado, você consegue acessar normalmente as urls dos webservices para sua UF, no mesmo ambiente que usou na biblioteca?

**Comment by robertorp** [comment]
Verifique na sua Sefaz se não atualizou para uma nova raiz de certificados, a raiz V5.

Varias Sefaz no Brasil fez essa atualização e esta dando exatamente esse erro.

Exemplo: http://www.nfe.go.gov.br/post/ver/221980/novo-certificado:-problemas-de-acesso-ao-servico-nf-e-na-sefaz-go
