### ISSUE TITLE
[DÚVIDA] ComunicacaoException implementar de WebException

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#484]
A classe ComunicacaoException não deveria implementar de WebException ao invés de Exception?
Dessa forma teríamos acesso ao status da exceção.

**Comment by adeniltonbs** [comment]
@FabioHenriqueMF, sim é uma boa ideia. Vou marcar essa issue pra fazer.

**Comment by marleynoleto** [comment]
@adeniltonbs tudo bem? Estou tentando testar o componente para cancelar uma nf-e em goiás, no entanto está ocorrendo erro de timeout de comunicação. Excedeu o tempo limite. Já aumentei o tempo para mais de 10000 e continua. Pode me ajudar?
