### ISSUE TITLE
[Emissão de NFCe]: Dicas de impressão

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#485]
Boa noite,

Solicito dicas de como realizar a impressão da NFCe uma vez enviadas para a RF.

**Comment by robertorp** [comment]
Tem os app exemplos para isso

![danfe nativo](https://user-images.githubusercontent.com/10251705/27933726-016921dc-6279-11e7-98bd-0387c55a5e8e.png)

um app
![danfe nativo2 png](https://user-images.githubusercontent.com/10251705/27933779-3513d798-6279-11e7-9316-57168ede3c9b.png)

Não tem erro. E somente estudar os fontes.

**Comment by robertorp** [comment]
@Guaze  eai tudo bom? Deu conta?

**Comment by Guaze** [comment]
Agradeço o retorno.

Irei testar neste fim de semana.

**Comment by Guaze** [comment]
Este exemplo está somente no código fonte? ou também no conteúdo do Nuget?

**Comment by marcosgerene** [comment]
somente no fonte

**Comment by robertorp** [comment]
Se precisar de alguma ajuda me add no skype: robertoalves18@hotmail.com
Sempre que poder ajudo com alguns pedaços de códigos do meu erp.

**Comment by Guaze** [comment]
Estou vendo aqui que o exemplo está cortando e sobrepondo muitas informações isso já no visualizar.

**Comment by Guaze** [comment]
Estou pensando em utilizar os relatórios nativos do VS2015. Porque a escolha do FastReport?

**Comment by robertorp** [comment]
@Guaze  A escolha do FastReport foi somente porque a comunidade ofereceu. Oque a comunidade oferece e bem vindo. Por exemplo temos impressões nativas de NFC-e é com FastReport. Agora se você tiver interesse em fazer o danfe no relatório nativo do VS e quiser fazer um pull sera muito bem vindo.

**Comment by Guaze** [comment]
Certo. Estou avaliando o código do exemplo e observei que a nota esta cortando várias informações.

<img width="306" alt="capturar" src="https://user-images.githubusercontent.com/28018162/28045714-27c2ebee-65b5-11e7-992e-d4758178002b.PNG">

Fica assim só no visualizar mas imprime direito? há uma nova versão com a formatação mais ajustada?

**Comment by robertorp** [comment]
@Guaze  Não utilizo a Impressão da NFC-e do FAST logo então não sei, mas seguindo a logica ele vai cortar.

Utilizo a impressão nativa, na impressão nativa. Testa ela também, lembrando que a impressão nativa não tem dependências nem uma de libs pagas. (Impressão nativa fica no appTesteNF-e, opção DANFE NFCE NATIVO)

**Comment by Guaze** [comment]
Agradeço a ajuda. Irei testar essa opção.

**Comment by Guaze** [comment]
O que significa ser TipoEmissao.teNormal contra TipoEmissao.teOffLine pergunto porque eu configurei a minha aplicação para enviar normal e assim fiz para a receita; recebi o status 100 no retorno.
Caso não tivesse ido com sucesso, eu deveria ter trocado a TipoEmissao "na mão" ? Para dizer que ainda não foi.

Essa pergunta veio a partir do teste de emissão de cupom. Acompanhando o código fonte. cheguei neste ponto.

 private void CarregarXml(string xml)
        {
            try
            {
                nfeProc proc = new procNFe().nfeProc.CarregarDeXmlString(xml);
                _proc = proc;
                _nfe = _proc.NFe;
            }
            catch (Exception)
            {
                try
                {
                    NFeZeus nfe = new NFeZeus().CarregarDeXmlString(xml);
                    _nfe = nfe;
                }
                catch (Exception)
                {
                    throw new ArgumentException(
                        "Ei! Verifique se seu xml está correto, pois identificamos uma falha ao tentar carregar ele.");
                }
            }
        }

E o meu arquivo sempre carrega como se fosse um objeto "NFeZeus". Só que quando chega neste ponto.

if (_nfe.infNFe.ide.tpEmis == TipoEmissao.teNormal)
            {
                StringBuilder textoProtocoloAutorizacao = new StringBuilder("Protocolo de autorização: ");
                textoProtocoloAutorizacao.Append(_proc.protNFe.infProt.nProt);
                AdicionarTexto protocoloAutorizacao = new AdicionarTexto(g, textoProtocoloAutorizacao.ToString(), 7);
                int protocoloAutorizacaoX = (larguraLinha - protocoloAutorizacao.Medida.Largura)/2;
                protocoloAutorizacao.Desenhar(protocoloAutorizacaoX, _y);
                _y += protocoloAutorizacao.Medida.Altura;


                StringBuilder textoDataAutorizacao = new StringBuilder("Data de autorização ");
                textoDataAutorizacao.Append(_proc.protNFe.infProt.dhRecbto.ToString("G"));
                AdicionarTexto dataAutorizacao = new AdicionarTexto(g, textoDataAutorizacao.ToString(), 7);
                int dataAutorizacaoX = (larguraLinha - dataAutorizacao.Medida.Largura)/2;
                dataAutorizacao.Desenhar(dataAutorizacaoX, _y);
                _y += dataAutorizacao.Medida.Altura;
            }

Cai em contradição o que eu fiz. Defini como emissão normal mas o meu xml não carrega como nfeProc mas como NFeZeus.

**Comment by robertorp** [comment]
Anexa o xml aqui para eu estar analisando.

Mas a diferença de Normal para Offline e:

Normal : Você transmitiu uma nfc-e com sucesso na sefaz, a sefaz esta funcionando normalmente.

Offline : Aqui entra vários motivos vou citar oque é para ser mais comum entre todos
1º : A sefaz por algum motivo saio do ar, o cliente seu não pode parar de vender, você define o TipoEmissao das NFC-es que forem emitidas para offline e ele continua vendendo normalmente.. lembrando que o contribuiente tem apenas 24 horas para transmitir todas nfc-es emitidas offline. Mas roberto ele não conseguiu emitir eai? Se vira uauau liga na sefaz do seu estado para saber oque ocorre rsrsrs (sério a sefaz de goiás me disse se não me engano que o contribuinente deveria ir na delegacia fiscal e bla bla bla)
2º : O cliente esta sem internet.. ele não pode parar de emitir , define para Offline e começa a emitir.

Observação Importante: Quem controla o envio das NFC-es offline? O sistema que você fez. Ou seja você vai ter que controlar isso.

**Comment by Guaze** [comment]
O xml que tenho aqui é de uma que não foi com sucesso porque parece que a número da nota + série já existia em ambiente de homologação na RF. 

[xml - hmg - n enviado.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1137595/xml.-.hmg.-.n.enviado.pdf)

Quando estava de posse dos arquivo não vi nenhuma diferença. Estou tentando recuperar o xml do que eu enviei. eu tenho a chave de acesso aqui.

**Comment by robertorp** [comment]
@Guaze  a impressão da nfc-e somente deve ocorrer quando a NFC-e for transmitida com sucesso. Diferente disso pode ter certeza que ira dar erros. 
Por exemplo ai esta faltando tags de procNfe ele é do tipo normal ele devera ter a procNfe. 

Já o offline não precisa. Tente definir esse xml para offline (tpEmis = 9) e seleciona o xml novamente.
Agora NFC-e autorizada com sucesso você precisa do procNFe

![tpemis](https://user-images.githubusercontent.com/10251705/28048895-3e153248-65ca-11e7-96e4-2aaa6f18afad.png)


edit: montagem do procNfe
Hoje o zeus não faz a montagem. Você deve fazer ela.

![nfeproc](https://user-images.githubusercontent.com/10251705/28049017-ea070888-65ca-11e7-8cf0-e9bab7ce04d5.png)

**Comment by Guaze** [comment]
Então eu cheguei a enviar com sucesso a nfce em ambiente de homologação.

<img width="381" alt="capturar" src="https://user-images.githubusercontent.com/28018162/28049137-b3d241d2-65cb-11e7-9600-0a04ee639993.PNG">

So que comparando com um arquivo válido enviado pelo o sistema que utilizamos atualmente percebi algumas diferenças.

Se um arquivo de produção do sistema atual.

[xml producao do sistema atual.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1137639/xml.producao.do.sistema.atual.pdf)

neste arquivo tem um conjunto de tag's final.

**Comment by Guaze** [comment]
Neste arquivo do sistema atual tem a tal tag "nfeProc" que faria o loading corretamente. Só que no xml que foi e voltou usando Zeus mesmo dando status 100 (sucesso) o xml não gerou essa tag.

**Comment by robertorp** [comment]
Nos post que editei acima, mostra como gerar a tag

**Comment by Guaze** [comment]
Foi o mesmo problema que eu observei em outro tópico só que passo batido pelo fato de ter conseguindo enviar.

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/468

Que não gera essa marcação mais externa com isso, não faz o loading corretamente mesmo enviando com sucesso para a RF.

**Comment by robertorp** [comment]
Apos a geração deu tudo certo @Guaze ?

edit: Criei essa issue para melhorar a lib nesse ponto. https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/491

**Comment by robertorp** [comment]
@Guaze  Fechei a issue. Qualquer coisa crie uma nova ou reabra a mesma.

**Comment by Guaze** [comment]
A classe de impressão não está no conteúdo do Nuget?

DanfeNativoNfce impr = new DanfeNativoNfce(arquivo,
                    _configuracoes.ConfiguracaoDanfeNfce, 
                    _configuracoes.ConfiguracaoCsc.CIdToken, 
                    _configuracoes.ConfiguracaoCsc.Csc,
                    0 /*troco*//*, "Arial Black"*/);

**Comment by Guaze** [comment]
Realizei um build na class library correspondente e peguei as dll e adicionei manualmente no meu projeto. Existe alguma forma de emitir uma nota tipo "orçamento"?

**Comment by robertorp** [comment]
Orçamento não. Pelo menos no nativo.

Assim tem como se você gerar as tags manualmente exemplo tags fake..

colocaria uma chave fake, autorização fake enfim.. tudo fake.

**Comment by Guaze** [comment]
OK. Obrigado.
