### ISSUE TITLE
Erro: A fonte 'Open Sans Condensed' não dá suporte ao estilo 'Regular'

### ISSUE THREAD

**Issue by thiagovalim** [ZeusAutomacao/DFe.NET#487]
Olá amigos, eu estou obtendo este erro em vários computadores com windows 7 na impressão do danfe nativo. Eu já tentei reinstalar as fontes e não resolveu o problema. Também notei que a fonte 'Open Sans Condensed' não tem o estilo 'regular' realmente. Vocês poderiam me ajudar a resolver este problema. A minha versão é a mais recente do projeto e este problema não acontece em computadores com windows 10.

**Comment by robertorp** [comment]
Veja se isso ajuda https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/375

**Comment by robertorp** [comment]
Veja esta outra issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/382

edit: joga isso na pesquisa de issues "is:issue is:closed open sans "

**Comment by thiagovalim** [comment]
Obrigado robertop, pelo que eu entendi a solução é trocar a fonte pela 'Ubuntu Condensed'?

**Comment by robertorp** [comment]
A minha no meu caso foi essa. Acho que isso vai de cada Sistema operacional. Comigo deu exatamente isso no windows 7. Agora você ta com a lib atualizada?

**Comment by thiagovalim** [comment]
obrigado amigo, a solução para mim também foi trocar a fonte.

**Comment by robertorp** [comment]
Perfeito então, qualquer coisa re-abra a issue ou abra uma nova. Obrigado!
