### ISSUE TITLE
A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS - NOVAMENTE

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#488]
![image](https://user-images.githubusercontent.com/21219148/27930056-a300c4e0-626b-11e7-9155-27a98413a925.png)

Galera novamente este problema está acontecendo comigo.
E o pior que mesmo acessando a url no navegador, seleciono o certificado ponho a senha e dá isso ai na imagem...
alguem sabe o que pode ser?

**Comment by robertorp** [comment]
Clica no ir para a nfe.sefaz aqui em goiás ta assim tem muito tempo.

**Comment by robertorp** [comment]
@FabioHenriqueMF  Veja isso também https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/480

**Comment by robertorp** [comment]
@FabioHenriqueMF  eai? continua?

**Comment by FabioHenriqueMF** [comment]
Sim continua. O problema é que até em SP que não houve atualização de cadeia de certificados da esse problema.

**Comment by marcosgerene** [comment]
@FabioHenriqueMF sou de SP e meus clientes não relataram nenhum problema no sistema até agora

**Comment by FabioHenriqueMF** [comment]
@marcosgerene com certeza é problema de certificado mau instalado. 
Acabei de testar em outra maquina e deu certo.
Vou reinstala-lo e verifica e avisar. vlwsss

**Comment by FabioHenriqueMF** [comment]
é realmente @marcosgerene o problema estava ocorrendo somente em uma máquina. 
Mas estou me deparando agora com outro problema: sempre na primeira vez que vou usar qualquer método do WS - consultar situação da nota, status do serviço, envio do lote... - sempre dá na primeira vez "O tempo na solicitação foi atingido" e depois quando uso novamente o método WS dá certo. Sabe me dizer o que pode ser? Lembrando quena minha aplicação só pede o certificado a primeira vez, solicita a senha e guardo o mesmo em um objeto para as demais consultas WS.

**Comment by marcosgerene** [comment]
O time out não foi configurado ou está muito pequeno, eu uso entre 30000 e 60000 aqui, lembrando que o tempo é em milisegundos

**Comment by FabioHenriqueMF** [comment]
@marcosgerene  não acho que seja time out ,por que só dá na primeira vez que us o ws, na segundo logo em seguida dá certo, e outra meu timeout tá em 6 segundos já...

**Comment by marcosgerene** [comment]
@FabioHenriqueMF, eu disse 60 segundos e não 6... tentou mudar a criptografia? Ao invés de SSL3 pra TLS12 ou vice-versa?

**Comment by FabioHenriqueMF** [comment]
@marcosgerene 60 não é muita coisa não?

**Comment by marcosgerene** [comment]
Meu software é desktop, logo pra mim não é problema esse tempo pois não esta centralizado em um servidor web meu.

**Comment by robertorp** [comment]
@FabioHenriqueMF Deu certo?

**Comment by FabioHenriqueMF** [comment]
@robertorp marromeno, esse problema é esporádico, mesmo aumentando o timeout de vez em quando acontece...

**Comment by robertorp** [comment]
@FabioHenriqueMF  você faz acesso externo do certificado digital? Digo comigo não existe esse problema. Nunca da comigo literalmente. Oque imagino é algum acesso externo alguma outra aplicação que esta acessando ele.

**Comment by FabioHenriqueMF** [comment]
então @robertorp  a unica "coisa" que acessa ele é quando pede a senha, abre aquela caixinha que acredito eu que seja da certificadora entende? somente isso...

**Comment by robertorp** [comment]
@FabioHenriqueMF  isso não e para ser um problema. Tente setar a senha do certificado A3 direto na aplicação sua e veja se continua com esse problema. Oque vc usa no zeus? emissão normal? Distribuição?

**Comment by FabioHenriqueMF** [comment]
normal

**Comment by rodrigordi** [comment]
@FabioHenriqueMF , estou com um problema parecido com esse usando A3 token Gd burti + windows 10. No cliente acontece assim: primeira tentativa de conexão da erro de TLS/SSL. Na segunda tentativa, conecta normal. Todas as tentativas de uso do certificado para assinatura resultam em falha.

**Comment by robertorp** [comment]
Verifica a cadeia de certificado se esta tudo ok

**Comment by robertorp** [comment]
@FabioHenriqueMF  esta tudo ok já?

**Comment by dalpogetto** [comment]
![erro_1](https://user-images.githubusercontent.com/31019857/29294176-72fb8064-8124-11e7-9df4-92a97ec97f9f.JPG)
![erro_2](https://user-images.githubusercontent.com/31019857/29294177-730169c0-8124-11e7-8838-cf8815aabfc3.JPG)

Boa noite pessoal, alguem poderia me ajudar.
Nao consigo utilizar os servicos para MG. Ja instalei os certificados com a nova cadeia, como mostrado na tela. Nao sei mais o q fazer.  
Mensagem persiste: A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.

Obs: Aparentemente para os demais estados funciona normalmente.

Alguem poderia me dar uma luz, por favor ?

Obrigado

**Comment by robertorp** [comment]
@dalpogetto 

1º - Verifique se sua cadeia de certificado esta devidamente atualizada (a sefaz de mg não sei se disponibilizou mas baixamos um .exe da certisign.com.br que atualizava os protocolos)
2º - Protocolo de Segurança TLS

Passei pelo menos problema a poucos dias com alguns clientes de MG, minha solução foi essa que citei.

**Comment by dalpogetto** [comment]
@robertorp Muito obrigado pela pronta resposta. O problema todo estava no protocolo de Seguranca TLS.

**Comment by dalpogetto** [comment]
@robertorp  Poderia me dar mais uma luz ? 
Fiz um projeto em ASPNET para consulta de cadastro sefaz. 
Com as cadeias de certificado instaladas, protocolo de seguranca setado TLS, e rodando com IIS Express que vem no Visual Studio 2015 tudo funciona perfeitamente. 

Após publicar o projeto no IIS 10 do Windows 10, as consultas para MG pararam de funcionar, como se os certificados de MG nao estivessem instalados. Para consultas de outros estados funciona perfeitamente. 
Se puder me ajudar, agradeceria muito.

Obrigado 



![consulta_mg](https://user-images.githubusercontent.com/31019857/29390873-a55453e6-82c9-11e7-902b-d0770b6754ae.JPG)
![consulta_sp](https://user-images.githubusercontent.com/31019857/29390874-a55605a6-82c9-11e7-9a05-9bb2904dec64.JPG)

**Comment by rftd** [comment]
Checa se os certificados estão instalados para o usuário do IIS.

**Comment by dalpogetto** [comment]
Não faço idéia de como se verifica ou se instala o certificado para um usuario especifico. Vou dar uma busca no google. Valeu !

**Comment by robertorp** [comment]
Adiciona permissão no IIS

Leia estas duas issues voltadas para IIS. 

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/408

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/91

@dalpogetto
