### ISSUE TITLE
NFeAutorizacao com Erro ao emitir

### ISSUE THREAD

**Issue by andersonpda** [ZeusAutomacao/DFe.NET#489]
estava utilizando emissão normalmente até ontem, dai passou emitir esse erro:

The underlying connection was closed: An unexpected error occurred on a send.
-> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
- >An existing connection was forcibly closed by the remote host

**Comment by robertorp** [comment]
A lib uso no dia a dia com mais de 500 clientes hoje e não esta dando erro. (Estou usando o nuget mais atualizado). Isso ai não tem nada a ver com oque você fez não? Tentou emitir com o AppTeste para ver se o mesmo erro ocorre? Quais os passos no AppTeste para ocorrer o erro?

**Comment by robertorp** [comment]
@andersonpda Solucionou o problema?

**Comment by andersonpda** [comment]
sim, na vdd foi problema no sefaz geral que se deu na sexta feira pelo que intendi, outros amigos q tem emissão tiveram mesmo problema de conexão
