### ISSUE TITLE
ERRO nillable

### ISSUE THREAD

**Issue by darlanhendges** [ZeusAutomacao/DFe.NET#49]
Durante o processo de montagem está me dando o seguinte erro:

Se o atributo 'nillable' for falso no esquema, o atributo 'xsi:nil' não deverá estar presente na instância.

Tentei outro site de validação, como http://validadornfe.tecnospeed.com.br/, e me mostrou o seguinte erro:

Falha de Esquema: O atributo xsi:nil no elemento '{http://www.portalfiscal.inf.br/nfe}pRedBCST' é inválido.
Falha de Esquema: Campo 'pRedBCST' possui valor inválido: ''. Campo deve estar de acordo com a regra: 0.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(.[0-9]{2,4})?.

Xml montado para envio ao sefaz:

<?xml version="1.0" encoding="utf-8" ?>
<enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
  <idLote>1</idLote>
  <indSinc>0</indSinc>
  <NFe>
    <infNFe versao="3.10" Id="NFe43151010415625000178550010000000411000000416">
      <ide>
        <cUF>43</cUF>
        <cNF>00000041</cNF>
        <natOp>VENDA</natOp>
        <indPag>2</indPag>
        <mod>55</mod>
        <serie>1</serie>
        <nNF>41</nNF>
        <dhEmi>2015-10-11T15:58:28-03:00</dhEmi>
        <dhSaiEnt>2015-10-11T15:58:28-03:00</dhSaiEnt>
        <tpNF>1</tpNF>
        <idDest>1</idDest>
        <cMunFG>4314902</cMunFG>
        <tpImp>1</tpImp>
        <tpEmis>1</tpEmis>
        <cDV>6</cDV>
        <tpAmb>2</tpAmb>
        <finNFe>1</finNFe>
        <indFinal>1</indFinal>
        <indPres>1</indPres>
        <procEmi>0</procEmi>
        <verProc>3.000</verProc>
      </ide>
      <emit>
        <CNPJ>10415625000178</CNPJ>
        <xNome>COOPROFAR COOPERATIVA DE PRODUTOS FARMACEUTICOS</xNome>
        <xFant>COOPROFAR</xFant>
        <enderEmit>
          <xLgr>Rua Plinio Kroef</xLgr>
          <nro>980</nro>
          <xCpl>predio azul</xCpl>
          <xBairro>Rubem Berta</xBairro>
          <cMun>4314902</cMun>
          <xMun>Porto Alegre</xMun>
          <UF>RS</UF>
          <CEP>91150170</CEP>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
          <fone>5133493100</fone>
        </enderEmit>
        <IE>963363069</IE>
        <CRT>3</CRT>
      </emit>
      <dest>
        <CNPJ>07750733000192</CNPJ>
        <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
        <enderDest>
          <xLgr>RUA DR EMILIO ATALIBA FINGER</xLgr>
          <nro>63</nro>
          <xBairro>COLINA SORRISO</xBairro>
          <cMun>4305108</cMun>
          <xMun>Caxias do Sul</xMun>
          <UF>RS</UF>
          <CEP>91150170</CEP>
          <cPais>1058</cPais>
          <xPais>BRASIL</xPais>
        </enderDest>
        <indIEDest>9</indIEDest>
        <email>farmacesa@farmacesacaxias.com.</email>
      </dest>
      <det nItem="4">
        <prod>
          <cProd>20723</cProd>
          <cEAN>7898950876140</cEAN>
          <xProd>Cera Dep. Hortela Depile Plus 140gr</xProd>
          <NCM>94038100</NCM>
          <CFOP>5102</CFOP>
          <uCom>UNID</uCom>
          <qCom>10.0000</qCom>
          <vUnCom>3.39</vUnCom>
          <vProd>33.90</vProd>
          <cEANTrib>7898950876140</cEANTrib>
          <uTrib>UNID</uTrib>
          <qTrib>10.0000</qTrib>
          <vUnTrib>3.3900000000</vUnTrib>
          <indTot>1</indTot>
          <nItemPed>0</nItemPed>
        </prod>
        <imposto>
          <vTotTrib>0.18</vTotTrib>
          <ICMS>
            <ICMS10>
              <orig>0</orig>
              <CST>10</CST>
              <modBC>3</modBC>
              <vBC>10.00</vBC>
              <pICMS>18.0000</pICMS>
              <vICMS>0.18</vICMS>
              <modBCST>0</modBCST>
              <pRedBCST p8:nil="true" xmlns:p8="http://www.w3.org/2001/XMLSchema-instance" />
              <vBCST>0</vBCST>
              <pICMSST>0</pICMSST>
              <vICMSST>0</vICMSST>
            </ICMS10>
          </ICMS>
          <IPI>
            <cEnq>999</cEnq>
            <IPITrib>
              <CST>00</CST>
              <vBC>1.00</vBC>
              <pIPI>5.0000</pIPI>
              <vIPI>0.05</vIPI>
            </IPITrib>
          </IPI>
          <PIS>
            <PISOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pPIS>0.0000</pPIS>
              <vPIS>0.00</vPIS>
            </PISOutr>
          </PIS>
          <COFINS>
            <COFINSOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pCOFINS>0.0000</pCOFINS>
              <vCOFINS>0.00</vCOFINS>
            </COFINSOutr>
          </COFINS>
        </imposto>
      </det>
      <det nItem="5">
        <prod>
          <cProd>20728</cProd>
          <cEAN>7899083110040</cEAN>
          <xProd>Esm Top Beauty Base Branca com Queratina</xProd>
          <NCM>33043000</NCM>
          <CFOP>5102</CFOP>
          <uCom>UNID</uCom>
          <qCom>30.0000</qCom>
          <vUnCom>3.70</vUnCom>
          <vProd>111.00</vProd>
          <cEANTrib>7899083110040</cEANTrib>
          <uTrib>UNID</uTrib>
          <qTrib>30.0000</qTrib>
          <vUnTrib>3.7000000000</vUnTrib>
          <indTot>1</indTot>
          <nItemPed>0</nItemPed>
        </prod>
        <imposto>
          <vTotTrib>0.18</vTotTrib>
          <ICMS>
            <ICMS10>
              <orig>0</orig>
              <CST>10</CST>
              <modBC>3</modBC>
              <vBC>10.00</vBC>
              <pICMS>18.0000</pICMS>
              <vICMS>0.18</vICMS>
              <modBCST>0</modBCST>
              <pRedBCST p8:nil="true" xmlns:p8="http://www.w3.org/2001/XMLSchema-instance" />
              <vBCST>0</vBCST>
              <pICMSST>0</pICMSST>
              <vICMSST>0</vICMSST>
            </ICMS10>
          </ICMS>
          <IPI>
            <cEnq>999</cEnq>
            <IPITrib>
              <CST>00</CST>
              <vBC>1.00</vBC>
              <pIPI>5.0000</pIPI>
              <vIPI>0.05</vIPI>
            </IPITrib>
          </IPI>
          <PIS>
            <PISOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pPIS>0.0000</pPIS>
              <vPIS>0.00</vPIS>
            </PISOutr>
          </PIS>
          <COFINS>
            <COFINSOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pCOFINS>0.0000</pCOFINS>
              <vCOFINS>0.00</vCOFINS>
            </COFINSOutr>
          </COFINS>
        </imposto>
      </det>
      <det nItem="6">
        <prod>
          <cProd>20734</cProd>
          <cEAN>7899083110064</cEAN>
          <xProd>Esm Top Beauty Base Amarga</xProd>
          <NCM>33043000</NCM>
          <CFOP>5102</CFOP>
          <uCom>UNID</uCom>
          <qCom>15.0000</qCom>
          <vUnCom>3.70</vUnCom>
          <vProd>55.50</vProd>
          <cEANTrib>7899083110064</cEANTrib>
          <uTrib>UNID</uTrib>
          <qTrib>15.0000</qTrib>
          <vUnTrib>3.7000000000</vUnTrib>
          <indTot>1</indTot>
          <nItemPed>0</nItemPed>
        </prod>
        <imposto>
          <vTotTrib>0.18</vTotTrib>
          <ICMS>
            <ICMS10>
              <orig>0</orig>
              <CST>10</CST>
              <modBC>3</modBC>
              <vBC>10.00</vBC>
              <pICMS>18.0000</pICMS>
              <vICMS>0.18</vICMS>
              <modBCST>0</modBCST>
              <pRedBCST p8:nil="true" xmlns:p8="http://www.w3.org/2001/XMLSchema-instance" />
              <vBCST>0</vBCST>
              <pICMSST>0</pICMSST>
              <vICMSST>0</vICMSST>
            </ICMS10>
          </ICMS>
          <IPI>
            <cEnq>999</cEnq>
            <IPITrib>
              <CST>00</CST>
              <vBC>1.00</vBC>
              <pIPI>5.0000</pIPI>
              <vIPI>0.05</vIPI>
            </IPITrib>
          </IPI>
          <PIS>
            <PISOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pPIS>0.0000</pPIS>
              <vPIS>0.00</vPIS>
            </PISOutr>
          </PIS>
          <COFINS>
            <COFINSOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pCOFINS>0.0000</pCOFINS>
              <vCOFINS>0.00</vCOFINS>
            </COFINSOutr>
          </COFINS>
        </imposto>
      </det>
      <det nItem="7">
        <prod>
          <cProd>20731</cProd>
          <cEAN>7898950876331</cEAN>
          <xProd>Cera Dep. Canela Depile Plus 620gr.</xProd>
          <NCM>33043000</NCM>
          <CFOP>5102</CFOP>
          <uCom>UNID</uCom>
          <qCom>25.0000</qCom>
          <vUnCom>7.80</vUnCom>
          <vProd>195.00</vProd>
          <cEANTrib>7898950876331</cEANTrib>
          <uTrib>UNID</uTrib>
          <qTrib>25.0000</qTrib>
          <vUnTrib>7.8000000000</vUnTrib>
          <indTot>1</indTot>
          <nItemPed>0</nItemPed>
        </prod>
        <imposto>
          <vTotTrib>0.18</vTotTrib>
          <ICMS>
            <ICMS10>
              <orig>0</orig>
              <CST>10</CST>
              <modBC>3</modBC>
              <vBC>10.00</vBC>
              <pICMS>18.0000</pICMS>
              <vICMS>0.18</vICMS>
              <modBCST>0</modBCST>
              <pRedBCST p8:nil="true" xmlns:p8="http://www.w3.org/2001/XMLSchema-instance" />
              <vBCST>0</vBCST>
              <pICMSST>0</pICMSST>
              <vICMSST>0</vICMSST>
            </ICMS10>
          </ICMS>
          <IPI>
            <cEnq>999</cEnq>
            <IPITrib>
              <CST>00</CST>
              <vBC>1.00</vBC>
              <pIPI>5.0000</pIPI>
              <vIPI>0.05</vIPI>
            </IPITrib>
          </IPI>
          <PIS>
            <PISOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pPIS>0.0000</pPIS>
              <vPIS>0.00</vPIS>
            </PISOutr>
          </PIS>
          <COFINS>
            <COFINSOutr>
              <CST>99</CST>
              <vBC>0.00</vBC>
              <pCOFINS>0.0000</pCOFINS>
              <vCOFINS>0.00</vCOFINS>
            </COFINSOutr>
          </COFINS>
        </imposto>
      </det>
      <total>
        <ICMSTot>
          <vBC>40.00</vBC>
          <vICMS>0.72</vICMS>
          <vICMSDeson>0.00</vICMSDeson>
          <vBCST>0</vBCST>
          <vST>0</vST>
          <vProd>395.40</vProd>
          <vFrete>0</vFrete>
          <vSeg>0</vSeg>
          <vDesc>0.00</vDesc>
          <vII>0</vII>
          <vIPI>0.20</vIPI>
          <vPIS>0</vPIS>
          <vCOFINS>0</vCOFINS>
          <vOutro>0</vOutro>
          <vNF>395.40</vNF>
          <vTotTrib>0.72</vTotTrib>
        </ICMSTot>
      </total>
      <transp>
        <modFrete>0</modFrete>
      </transp>
      <cobr>
        <fat>
          <nFat>41</nFat>
          <vLiq>469.40</vLiq>
        </fat>
      </cobr>
    </infNFe>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
      <SignedInfo>
        <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
        <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
        <Reference URI="#NFe43151010415625000178550010000000411000000416">
          <Transforms>
            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
          </Transforms>
          <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
          <DigestValue>QSNu3At7Bwyd8HHrwCNzve1s6rs=</DigestValue>
        </Reference>
      </SignedInfo>
      <SignatureValue>amTJGcI5vuGkh6Q7a9wjLGEo/6LDgAwdpBSFbmrOKnd4/KLZezlEXifpddvCdQOeadDcPhYRQBkmUXLjOFeHmtE9Q8F0/6wG6NTk1Nz2wSqX7EXLKGJoHOFTk0h8LCE7YB66kL8Jk9eSTz3SFKhGNozSK975lrvdgjk4K1JfG/BuyhhPPPz5KNq3HxeDoYcTAYLYIq7Oa4TCenzMzR/5ZGwsnsrwaqOhGIR7lhi0FsNAakAsCT9+drmkdFLl5GPBTlb+IRoXj4szFUxwmpEWeXIUiBQXqsijsN5bbK8zrzG6OlkqykP8rTNI0JePmki+ibzRVhyXHtiuPYGCIQQT9A==</SignatureValue>
      <KeyInfo>
        <X509Data>
          <X509Certificate>MIIIAzCCBeugAwIBAgIIeX1/YT2S8wswDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNTA2MTUxNDQyMDBaFw0xNjA2MTQxNDQyMDBaMIH2MQswCQYDVQQGEwJCUjELMAkGA1UECBMCUlMxFTATBgNVBAcTDFBPUlRPIEFMRUdSRTETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLEw1SRkIgZS1DTlBKIEExMRMwEQYDVQQLEwpBUiBTQUZFV0VCMUkwRwYDVQQDE0BDT09QUk9GQVIgQ09PUEVSQVRJVkEgREUgUFJPRFVUT1MgRkFSTUFDRVVUSUNPUyBMOjEwNDE1NjI1MDAwMTc4MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAojt4f72EntXueUk5EOTsGKP1BZdmi2tdchyhiclZNxXRYxNu0gQhrN92hdjVK17jCACMD/FRjATb+HWq6WaigrB3bm4Cyw7Mm3kXWyPGpd33oo1eW37xju6Q3KrrpJM2TdL61RwHfwxOGaHHuTiRz1hP+JIbeorOTWIE3RleY7QI6hFq6qzKBHtAsu1m/nEKx58IigkVTOeQsr63Vymw6DxPidRXmNbUQ7kRWom2mBl+vI0BdV3PQnefHxSewzidRGyQRempTYANfxDqahR1phADBgUyCgINTBu2zK5Z3R86PJWNnRSXGnW0ZwHhBzgJIYaP+AOBo66Ktlnekj98NwIDAQABo4IDEzCCAw8wgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUFBzAChjxodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2FyZmJ2Mi5wN2IwPQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvc2VyYXNhcmZidjIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBSyoMQ9Rp58yIVsCB4QMpRlRnBBczBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5wZGYwgfMGA1UdHwSB6zCB6DBKoEigRoZEaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwRKBCoECGPmh0dHA6Ly9sY3IuY2VydGlmaWNhZG9zLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMFSgUqBQhk5odHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2VyYXNhL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBrAYDVR0RBIGkMIGhgRhDVEJNQVJUSU5TQ09OVEBHTUFJTC5DT02gFwYFYEwBAwKgDhMMV0lMU09OIEdBTExJoBkGBWBMAQMDoBATDjEwNDE1NjI1MDAwMTc4oDgGBWBMAQMEoC8TLTE0MDgxOTUxMTYzMTUxMDMwNDkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBAFYHyR6S9HoCzHB3+dskSb+pK4kA+W6ygS8gzzIP4MEWdRg/zYnM5BPIIgCbvtnPdSl/IEJ1M26e5HFpLIqr38SLhxa1vrBU07j6e7pI2hCN4mcSlXndYGUxEFOXjhDFSxZInQlUiHsRhqefr9frvR+Zu1m+wPfh4X+GDmASrNBlDjgoncYCcmABFDC5UFP8dVx8kGhCrBqOhzQV+4RZqh3sKe+NcsDqy9VJU2IZuia2EOCgufhLCtnld8kjA37XyEDuVcB/itUKDP3v1Dn9uQ98qYMB48MVdQfGKuA+GjIlrY/KSbzxFU1XZyv0V5OsU9kINiTLzEw6Hp+HTXVBlgsJtoOhNICfYD0YOKaTZA27N2G54hnD4IM4rjcE2lnNWb3uDZjG24GiBSvztTvLLookmRn3f9pjVqg0Eu/ISmf9ajzMDlv7sIHy8yVJpaKEqPsVd8PEImzGgR9Bqnj8x2sCYXCGv5a1PTf1OFyNg9m1NfHozKQwE1bbOZJStv77GW3w+HY9AlPdeUr97sKScUVEVjieui9gvyT5x5XdDxIlBTm8W2dS+buZ0EgpXW2k6eyaPlTZiGzadSxQ0JahWM1vKIQiWGdkA5rr96NOmT9vfR/l2i9ZHBuZ+endDRdxFz9adIf3X1wxLMnahV+l0Wx6LfSNVKX0jXPdr0CwD/Cz</X509Certificate>
        </X509Data>
      </KeyInfo>
    </Signature>
  </NFe>
</enviNFe>

Alguem consegue me dar uma luz?
Grande abs

**Comment by adeniltonbs** [comment]
Para a CST de ICMS informada, o campo pRedBCST(percentual de redução da base do ICMS substituto) é de preenchimento obrigatório. Caso não tenha valor para ele, informe 0

**Comment by darlanhendges** [comment]
Obrigado pela ajuda.....

**Comment by alansousa** [comment]
tive esse problema com esse campo tambem é resolvi assim:

o problema desse campo é que o método  
`public bool ShouldSerializepRedBCSTT()
        {
            return pRedBCST.HasValue;
        }`
está com um T a mais no final aí ele serializa o objeto mesmo sem valor.

é só tirar o T, pra ficar ShouldSerialize + nome da propriedade:
`public bool ShouldSerializepRedBCST()
        {
            return pRedBCST.HasValue;
        }`
