### ISSUE TITLE
Criar um método que já retorne o nfeProc

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#491]
Criar um método que já retorne o nfeProc

O método teria que verificar se a nfe foi autorizada com sucesso.

**Comment by Guaze** [comment]
Só tenho acesso ao token nos finais de semana para testar. Enquanto isso, irei preparar o código-fonte para tal.

**Comment by robertorp** [comment]
@Guaze  Ainda não criei o método. Mas irei criar o mesmo. Provavelmente crio ele no fim de semana.

**Comment by Guaze** [comment]
Quando falei que iria testar seria com a aquele código que você colocou no questionamento anterior. Óbvio que irei utilizar o novo método quando este estiver incorporado ao componente.
