### ISSUE TITLE
Como incluir várias notas em um mesmo lote?

### ISSUE THREAD

**Issue by Phakos** [ZeusAutomacao/DFe.NET#493]
Olá amigos, bom dia.
Antes de mais nada, parabéns pelo projeto.
Fiz o download da biblioteca, venho testando e conseguindo êxito em todos os testes.
Configurações: OK
Enviar uma nota: OK
Cancelar: OK
Carta de Correção: OK
Mas preciso testar o envio de várias notas em um único lote e não consigo fazer isso no App de Teste.
Procurei por todos os Issues (abertos e fechados) e não vi nenhuma referência de como fazer.
Alguém poderia me ajudar?

Desde já agradeço muito.

**Comment by robertorp** [comment]
![screen-10 14 19 12 07 2017](https://user-images.githubusercontent.com/10251705/28119364-01baa284-66eb-11e7-8758-f71082e69c02.png)

@Phakos  Observe que no app teste nos enviamos uma List<NFe>

Ou seja.. passa 2,3,4,5,6,7, N Nf-es

Logicamente respeitando o limite das nf-es

Manual_de_Orientacao_Contribuinte_v_6.00.pdf Página 29
![limite](https://user-images.githubusercontent.com/10251705/28119478-65231842-66eb-11e7-8810-ae11c50c9d7a.png)

O zeus não trata esse limite para você, você deve tratar isso em sua aplicação

edit: existe um limite em tamanho de kpbs 500kb também.

**Comment by Phakos** [comment]
Ok, acho que entendi.
Na aplicação eu devo passar para a List o caminho do XML de cada Nota. Isso mesmo?

**Comment by robertorp** [comment]
@Phakos  você passa varios objetos nfe dentro do list observa a primeira imagem new List<Classes.NFe> {_nfe}

Nessa linha você passa List<Classes.NFe> {_nfe1, _nfe2}

Agora como você vai carregar o objeto _nfe1 é _nfe2 , ai e lógica sua. 
Aqui na empresa salvamos xmls no banco de dados, buscamos ele e carregamos os objetos.

**Comment by Phakos** [comment]
@robertorp Muito obrigado pela disposição e ajuda. Entendi. Valeu e muito obrigado por enquanto !!!

**Comment by robertorp** [comment]
@Phakos Qualquer coisa abra uma issue que podendo nos vamos nos ajudando sempre.
Poderia dar close na issue? Obrigado
