### ISSUE TITLE
Verão 4.0 da NFe

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#495]
Boa tarde a todos, 
Adenilton, você mais ou menos tem uma previsão de quando terá as classes prontas para começar a testar a versão 4.0, visto que já tem alguns estados que liberaram tanto para homologação quanto para produção os WS ...
Se tiver pelo menos as Classes com as novas mudanças ja é um grande passo deixar isso pronto dentro dos ERPs né, assim quando soltarem os WS é só testarmos,.
Desde já agradeço... Muito obrigado.

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/482 Existe esse pull.
Somente não fiz o resto ainda, porque o @adeniltonbs  não disse nada ainda.

**Comment by guimagcpd** [comment]
Obrigado pela resposta Roberto...
Estou com essa dúvida, porque ja existem vários estados que estão funcionando já os ws na versão de homologação. e para não tumultuar para ultima hora ja entrei em contato com vocês para ter um posicionamento de quando mais ou menos aproximadamente esta nova versão estara disponível pelo Nuget...
qualquer novidade se puder informar agradeço desde já...
Muito obrigado pela iniciativa de vocês... parabéns.

**Comment by robertorp** [comment]
Blz, Assim, se o @adeniltonbs  não implementar nos próximos 45 dias eu dou um jeito =)

**Comment by guimagcpd** [comment]
Roberto bom dia...
Alguma notícia da versão ? ainda não vi nenhuma novidade aqui, mais pode ser que exista em segundo plano, por isso da pergunta...
Agradeço a atenção...

**Comment by alexsandro-xpt** [comment]
Tambem gostaria de saber...

**Comment by guimagcpd** [comment]
To bastante preocupado ja... 
mais vamos aguardar o Roberto ou o Adenilton, que são os salvadores do projeto ...
dependemos deles. até...

**Comment by robertorp** [comment]
Talvez encurto o prazo pra alguns dias pois já ate fiz um pull request , so não terminei a implementação pois o @adeniltonbs  mostrou interesse em fazer. Vamos ver oque ocorre. Se ate segunda não surgir novidades nem uma do @adeniltonbs  eu inicio a implementação.

**Comment by guimagcpd** [comment]
Muito Obrigado pela notícia, ja da um conforto pra quem aguarda essa implementação...
Ficamos no aguardo de novidades... desde ja agradeço sua atenção.

**Comment by adeniltonbs** [comment]
@guimagcpd boa tarde. Vou implementar sim. Nós utilizamos a biblioteca em nossas aplicações :). Na verdade já era pra ter feito essa semana, mas infelizmente tive uns contra-tempos.

@robertorp Obrigado pela disponibilidade desde já.

**Comment by guimagcpd** [comment]
Eu Agradeço muito mesmo... esse projeto sem dúvidas salva muitos programadores.. Obrigado a vocês.

**Comment by rodrigordi** [comment]
Conta comigo nesse ai. Já tem as urls e o XSD mapeado ? Eu crio as classes usando o xsd.exe, mas to pensando em comparar as PLs e fazer na mão mesmo.

**Comment by robertorp** [comment]
@rodrigordi  add eu no skype para trocarmos umas ideias robertoalves18@hotmail.com
