### ISSUE TITLE
Pis/Cofins Como é calculado o mesmo? Para NF-e Simples Nacional Somente.

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#496]
Pis/Cofins Como é calculado o mesmo? Para NF-e Simples Nacional Somente.

Posso apenas jogar o preço do produto * alíquota?

Ou jogo a base de calculo seria a mesma que a de ICMS?

Exemplo

NF-e
Produto 1
Valor: 1374,53
Percentual Pis = 0,65
Percentual Cofins = 3%
Frete: 20,00
Desconto Condicional: 88,22
Outras Despesas: 20.44

Minha base de cálculo seria: 
BaseCalculo = Valor + Frete + Desconto Condicional + Outras Despesas 
1.503,19 = 1374,53 + 20,00 + 88,22 + 20.44

ValorPis = BaseCalculo * (Percentual Pis/100)
9,7707035 = 1503,19*(0,65/100)

ValorCofins = BaseCalculo * (Percentual Cofins/100)
45,0957 = 1503,19*(3/100)

E se tivesse redução/Ipi entraria?
Aliás, Frete, Desconto, Outras despesas entram?

Enfim qual a base de calculo para Pis/Cofins PARA SIMPLES NACIONAL para uma unica NF-e com um único item dentro dela.

edit: nos resultados aplicaria um arrendondamento ou truncamento? Digo se o contador exigir enviar.. pois poderia enviar Outros 99/49/07 ou sei lá algum isento mas.. se algum contador pedir algo que exige calculo deixo pronto para ele

**Comment by orochasamuel** [comment]
Fala @robertorp, tudo na paz?
Talvez eu possa lhe ajudar com essa dúvida de tributação, vamos lá...

> Posso apenas jogar o preço do produto * alíquota?
**> Resposta 1: Não. A forma de cálculo no Simples Nacional é diferente. Esse caso é aplicado quando é Lucro Presumido ou Lucro Real.**

> Ou jogo a base de calculo seria a mesma que a de ICMS?
**> Resposta 2: Cada Estado possui uma legislação própria. Via de regra, as informações que estiverem no [Manual da EFD ICMS/IPI](http://sped.rfb.gov.br/estatico/55/84F292AA956E838ED01DB91A8D4C6ECD9E53C8/GUIA%20PR%c3%81TICO%20DA%20EFD%20-%20Vers%c3%a3o%202.0.20.pdf) são válidas em âmbito nacional, a menos que a SEFAZ do Estado tenha algum tratamento muito específico, e terá manuais e leis para orientar sobre o caso. Na página 67 do Manual 2.0.20 está discriminado como deve ser a formação do valor para base de cálculo:**

>Campo 05 (VL_OPR) - Preenchimento: 
Na combinação de CST_ICMS, CFOP e ALIQ_ICMS, informar neste campo o
valor das mercadorias somadas aos valores de fretes, seguros e outras despesas acessórias e os valores de ICMS_ST e IPI (somente quando o IPI está destacado na NF), subtraído o desconto incondicional. 
Validação: 
O somatório dos valores deste campo deve, em princípio, corresponder ao valor total do documento informado no registro C100. Na ocorrência de divergência entre os valores será emitida uma “Advertência” pelo PVA-EFD-ICMS/IPI, o que não impedirá a assinatura e transmissão do arquivo.
Campo 06 (VL_BC_ICMS) - Preenchimento: 
informar a base de cálculo do ICMS, referente à combinação dos campos
CST_ICMS, CFOP e ALIQ_ICMS deste registro.
Validação: 
o valor constante neste campo deve corresponder à soma dos valores do Campo VL_BC_ICMS dos registros C170 (itens), se existirem, que possuam a mesma combinação de CST, CFOP e Alíquota deste registro.
Fonte: [Manual da EFD ICMS/IPI](http://sped.rfb.gov.br/estatico/55/84F292AA956E838ED01DB91A8D4C6ECD9E53C8/GUIA%20PR%c3%81TICO%20DA%20EFD%20-%20Vers%c3%a3o%202.0.20.pdf)

Sabendo que as despesas e os fretes devem ser rateados nos itens da NF-e no ato de emissão no seu sistema e irão compor o valor total e a base de cálculo é certo afirmar que o mesmo resultado será aplicado no caso do PIS/Pasep e da COFINS:

> _(Palavras minhas)_ O fato gerador do PIS/Pasep e da COFINS é o faturamento e, o faturamento deve ser entendido como “o total das receitas auferidas pela pessoa jurídica” incluindo as receitas não-operacionais, exceto as decorrentes da venda do ativo imobilizado e permanente, as receitas de todos os grupos de contas do resultado são tributadas.
Fonte: [Coletânea sobre PIS/COFINS da RFB](http://www.receita.fazenda.gov.br/publico/Legislacao/Coletanea/ColetaneaPISCofins.pdf)

O IPI não entra porque já é um tributo, se considerasse o IPI ao calcular PIS e COFINS seria bitributação.

Agora vamos lá, a real dúvida é como calcular no caso do Simples Nacional (que não tem nada de simples), **você terá que utilizar uma tabela intermediária para ver qual alíquota será aplicada sobre a faixa de faturamento da empresa**.

A Lei Complementar nº 123 de 2006 - e as leis seguintes - instituiu as faixas de receita e para cada faixa há uma alíquota diferente. Neste caso não tem como correr, você terá que controlar a evolução da receita dentro do seu sistema para saber qual % aplicar. Cá entre nós, se a Receita tivesse disponibilizado um webservice que retornasse essas informações do Simples seria uma maravilha. O Perguntas e Respostas no site do Simples pode lhe ajudar com várias dúvidas também.
Fonte: [Lei Complementar 123](http://www.planalto.gov.br/ccivil_03/leis/LCP/Lcp123.htm)

Exemplo:
Tenho uma empresa de **comércio**, e tenho uma **média de faturamento anual** entre $ 360 mil e $ 540 mil.

Comércio: Será calculado com as alíquotas do Anexo I do Simples Nacional.
Média de faturamento de $ 360 mil a $ 540 mil:
![image](https://user-images.githubusercontent.com/15462690/28241734-437ef8c8-6970-11e7-9fd7-75958fc733de.png)

> edit: nos resultados aplicaria um arrendondamento ou truncamento? Digo se o contador exigir enviar.. pois poderia enviar Outros 99/49/07 ou sei lá algum isento mas.. se algum contador pedir algo que exige calculo deixo pronto para ele

Eu particularmente sempre recomendo arredondar, a maioria dos contadores pedem indicadores genéricos mas se você não souber o que colocar use as CSTs gerais (49/99), sempre outras entradas ou outras saídas. A questão do cálculo pronto depende do produto/serviço, da operação (se é venda, transferência, prestação de serviços com retenção ou não) e se há algum "benefício" fiscal para reduzir ou isentar o valor. Deixa o cliente/contador parametrizar o produto/serviço, é o cliente/contador que tem saber como se calcula o imposto não o programador.

Enfim... deu chão. --'

Espero ter ajudado.
Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira  boa vlw, mas tipo vejo sistemas emitindo nf-e ninguém usa esses dados da tabela do simples nacional , vejo somente calculando normal , mesmo para envio de uma unica nf-e simples nacional. O que me diz?

Por exemplo em meu sistema não temos muitas coisas, não temos lançamento em outras despesas, seguro enfim.. não existe campos assim lá. Existe o preço/Desconto/Frete (lembrando que desconto é frete pode aparecer em determinados casos e determinados não podem aparecer)

Hoje nos calculamos tudo normal. Afinal no final das contas, isso não vale nada porque e calculado em cima dessa tabela ai o imposto a pagar do cliente nosso. A não ser que eu esteja sendo equivocado e claro hehe, não entendo muito de tributação.

**Comment by orochasamuel** [comment]
@robertorp realmente é isso mesmo, no final das contas o que vale é a tabela mas essa informação da alíquota no sistema é útil quando você vai emitir uma NF-e contra outra pessoa jurídica e tem que sair o imposto na nota, no caso do simples vai aparecer no rodapé.
Já vi em alguns sistemas esse controle de alíquota interna pois depois o sistema gera a guia de imposto. Até hoje não descobri como, mas a guia saia com o valor já calculado, e batia.

No seu caso, pode usar os indicadores genéricos e deixar sem alíquota (se a transmissão da NF-e for permitida). A única chatice é o cliente ligar avisando que emitiu uma nota sem o destaque do imposto e a nota não foi aceita pelo cliente/fornecedor dele.

**Comment by robertorp** [comment]
Obrigado @samuelrochaoliveira  de grande ajuda hehehe meu negocio e que estou construindo algo .net para cálculos tributários. 

https://github.com/AutomacaoNet/MotorTributarioNet
