### ISSUE TITLE
Certificado A3 e Zeus aberto... e agora?

### ISSUE THREAD

**Issue by LuisPatroni** [ZeusAutomacao/DFe.NET#497]
Pessoal,

Dúvidas básicas...
Estou com o cartão do Certificado A3 plugado em minha máquina e com o Zeus aberto.
O que faço? Como configuro? Tem um passo-a-passo?

Já enrosquei na configuração de Número de Série, Arquivo e  Senha...

Agradeço a ajuda.

**Comment by robertorp** [comment]
o cartão do certificado esta funcionando perfeitamente? Digo instalou o driver?

faz o teste https://serasa.certificadodigital.com.br/teste/ 

edit: Vamos ir conversando aqui

**Comment by robertorp** [comment]
@LuisPatroni  Deu conta?

**Comment by LuisPatroni** [comment]
Amigo, desisti temporariamente.

Comecei errado comprando o A3 e vou retomar isso em outra oportunidade.

Tenho poucas NFs ainda.

Obrigado.


Luis Patroni
 *+55 4**4 99921.9134*
<http://www.eklesia.com.br>


2017-07-26 0:12 GMT-03:00 Roberto Alves Pereira <notifications@github.com>:

**Comment by robertorp** [comment]
@LuisPatroni  na verdade, você pode construir um monitor para utilizar o A3 a unica coisa que o monitor ira fazer é consultar uma webservice verificar se tem NF-e para ser emitida, se tiver, o monitor transmite e manda para a sua base de dados via webservice

**Comment by LuisPatroni** [comment]
Hmmm... é um caminho.

Cheguei a baixar o Zeus NFe.sln

Sigo por ali. O que vc recomenda?

Agradeço a ajuda.


Luis Patroni
 *+55 4**4 99921.9134*
<http://www.eklesia.com.br>


Em 26 de julho de 2017 08:55, Roberto Alves Pereira <
notifications@github.com> escreveu:

**Comment by robertorp** [comment]
1 - Crie um projeto
2 - O projeto vai ser somente um monitor que vai monitorar uma url que retorna uma lista de objetos com ID e XML , você persistira em um banco de dados local um sqllite da vida ou sei lá oque vc preferir até mesmo arquivos serve
3 - Apos o monitor enviar e autorizar o xml você envia ele de volta para seu erp via outra url 

Bom acho que é isso basicamente

**Comment by robertorp** [comment]
Tem skype? Se vc disponibilizar urls de obter xml é envio de xml posso estar ajudando a implementar, somente não vai ser agora

robertoalves18@hotmail.com

**Comment by LuisPatroni** [comment]
Olá Roberto.

Desde já agradeço pela ajuda.

Meu Skype é: luis.patroni

Quando vc puder.

Obrigado mais uma vez.



Luis Patroni
 *+55 4**4 99921.9134*
<http://www.eklesia.com.br>


2017-07-26 9:16 GMT-03:00 Roberto Alves Pereira <notifications@github.com>:
