### ISSUE TITLE
Rejeição 767: Dicas

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#498]
Bom dia,

Realizei o envio de um NF para  RF e recebi esta rejeição de retorno.

http://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-767-nfc-e-com-somat%C3%B3rio-dos-pagamentos-diferente-do-total-da-nota-fiscal-como-resolver-181.html

Entendi qual era o problema. Mas não faz muito sentido.

Faço uma venda de 10$ (valor do produto) e a pessoa me paga com 50$ (forma de pagamento) logo, tenho um troco 40$(troco).

Há alguma maneira da formação do .xml informar o troco ? (não sei se é o caminho)

Qual seria a melhor prática neste caso.

**Comment by robertorp** [comment]
No layout 3.1 não tem como informar o troco. Ou seja você adiciona somente os 10.
No layout 4.0 tem sim troco. Zeus terá o layout 4.0 daqui no máximo 3 meses.

**Comment by Guaze** [comment]
Vamos um exemplo hipotético:
venda 35$
forma de pagamento
cheque 30$
dinheiro 20$

troco 15$

Como definir a forma de pagamento para evitar o erro?

Entendo que, por hora, teria que fazer uma "gambiarra" dizendo que o forma de pagamento é dinheiro, por exemplo, colocar o valor da venda ignorando as reais formas de pagamento.

**Comment by robertorp** [comment]
[xml exemplo nfce pagamentos.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1152485/xml.exemplo.nfce.pagamentos.txt)

Olha o xml que acabei de gerar

**Comment by Guaze** [comment]
Eu já entendi que vnf deve ser igual a soma vpag. Isso já está bem claro para mim.

A questão é que normalmente o vpag é maior q vnf.

por exemplo,

produto 10$ (vnf)

aí a pessoa lhe dá uma nota de 50$ (vpag)

No seu sistema você vai registrar um pagamento de 50$ para uma venda de 10$ com um troco de 40$.

Só que para enviar para a receita temos que realizar um manipulação na informação modo tal que o vpag seja igual ao vnf para não dá erro no envio.

Ou seja, vou encaminhar uma informação não condizente como o que você tem registrado no seu sistema.

Fica estranho no seu sistema ter um vpag 50$ só que no xml da RF ter um vpag 10$.

**Comment by robertorp** [comment]
Exatamente. Agora no próximo layout temos a tag troco.

**Comment by Guaze** [comment]
Fiz uns testes aqui no sistema existente. ele corta a sobra (troco) nas formas de pagamento. Pensei que fosse na última forma de pagamento.
Só que fiz três formas de pagamento: dinheiro, cartão crédito, cartão débito nesta ordem. Mesmo assim ele cortou do dinheiro.
