### ISSUE TITLE
Uma pequena solução para Complexidades Tributárias 

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#499]
https://github.com/AutomacaoNet/MotorTributarioNet

Oque é?

Apenas uma pequena lib para cálculos tributários. 
Icms, IcmsST, IPI, Pis/Cofins, Difal, Credito Icms

Esta com vários testes unitários para conferencias dos cálculos. 
Ahh Roberto Esta faltando o calculo do imposto X porque isso e isso. Abra uma issue explicando como funciona e garanto que vou pesquisar e correr atrás para adicionar na lib ou ate você mesmo faça um pull.

Estude os testes e não tem erro hehe.
Abra uma issue lá e respondo com o maior prazer ou pergunte no grupo do skype do zeus.

**Comment by renanaragao** [comment]
Boa tarde, estava pensando em implementar essas funcionalidades direto no Zeus. Poderíamos até utilizar o que vc já fez.

**Comment by marcosgerene** [comment]
Comentário do @MurariAlex em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/537#issuecomment-332297542

>Fugiria do escopo do projeto.
>A premissa deste projeto é manipular apenas a montagem/envio/impressão de documentos fiscais.
>
>Incluir manipulação dos dados que compõem um documento fiscal é uma coisa completamente >diferente e configuraria um sistema ERP/retaguarda/caixa/automação comercial.
>
>Fora que calcular tributos já é complicado por si só, tendo em vista que cada estado tem sua lei e seus >métodos de cálculos, alíquotas, etc..

**Comment by robertorp** [comment]
a solução está aí galera , top viu ;) 
uso em meu sistema.
