### ISSUE TITLE
[qrCode] Botao Criar e Salvar XML 3.0

### ISSUE THREAD

**Issue by khflab** [ZeusAutomacao/DFe.NET#50]
Acabei de baixar e fiz toda configuração, então cliquei em Criar e Salvar XML 3.0 e o seguinte erro apareceu:

![problema_zeus](https://cloud.githubusercontent.com/assets/2036324/10466682/ec14da0a-71cb-11e5-9db0-37cdb6b65fad.png)

Algo com o qrCode!

**Comment by adeniltonbs** [comment]
Nas configurações vc informou a id do token?
Nas mensagem de erro note que o parâmetro cIdToken está vazio.

**Comment by adeniltonbs** [comment]
No aplicativo de demonstração, na guia DANFE informe o identificador do CSC.

**Comment by khflab** [comment]
Verdade, não informei. Vou preencher, é que eu não sei os campos obrigatórios. Obrigado!

**Comment by khflab** [comment]
Era isso, o CSC não estava informado mesmo. Abraços.
