### ISSUE TITLE
Possibilidade de abrir XML no formato UTF8

### ISSUE THREAD

**Issue by rondosoftlss** [ZeusAutomacao/DFe.NET#500]
Tem como por a possibilidade de abrir o XML da NFe no formato UTF8, temos uns "abençoados" de uns clientes que insistem em colocar Ç no campo de observações da nota e querem que saia a Ç

**Comment by robertorp** [comment]
Vou adicionar como melhorias, para quando formos obter o XML de cada classe podermos escolher o formado.

**Comment by rondosoftlss** [comment]
@robertorp alguma novidade sobre essa melhoria, já tenho alguns clientes me cobrando sobre isso já, pois querem usar caracteres especiais na NFe deles.

**Comment by marcosgerene** [comment]
@rondosoftlss o projeto é open source, nada impede que você colabore com suas necessidades ou até mesmo faça um fork e implemente o que precisa somente para você.

**Comment by rondosoftlss** [comment]
@marcosgerene sei que o projeto é open source, o problema é que tenho pouco conhecimento em C#, por isso que conversei com o @robertorp e ele me pediu para abrir um issue

**Comment by marcosgerene** [comment]
@rondosoftlss

>alguma novidade sobre essa melhoria, já tenho alguns clientes me cobrando sobre isso já, pois querem >usar caracteres especiais na NFe deles.

Soa como cobrança.

O projeto tem 160 forks, tirando o @robertorp que é o maior contribuidor do projeto hoje, o resto da comunidade (me incluo nisso) colabora apenas com sua necessidade do dia a dia, ex: eu precisava tirar o CTe de vez do lazarus (usava acbr), fiz as impressões e vários ajustes, se amanhã você quiser usar CTe e imprimir usando fast reports, esta MINHA necessidade vai LHE ajudar. Eu poderia ter feito essas implementações somente para meu uso, mas eu disponibilizo porque pode te ajudar, como você disponibiliza algo que pode me ajudar, é assim que uma comunidade **open source** funciona, e isso só tem força porque a recíproca é verdadeira.

Se você precisa de algo que a comunidade não sentiu necessidade ainda, você pode fazer e disponibilizar. 

Como reportou que não tem habilidades técnicas para tal, você solicitar como você já fez e aguardar (sem fazer cobranças) ou propor para alguém que consiga fazer uma monetização (patrocínio).

Se o seu comentário parasse em "_alguma novidade sobre essa melhoria_?" estaria tudo ok, você só está perguntando.

Agora " _já tenho alguns clientes me cobrando sobre isso já, pois querem usar caracteres especiais na NFe deles._" soa como rude.

**Comment by rodrigordi** [comment]
Oi Pessoal! 

ainda não consegui ter tempo para ver o projeto de voces, mas adianto que já estão de parabens!
Comecei um projeto como esse em 2009. primeira leva depois do piloto da nfe. meus parabens mesmo.

Espero poder ajudar a voces em casos pontuais como esse.
Eu não uso o projeto de voces, pois já tenho o meu conector.

Enfim, pelo o que eu entendi do problema, o @rondosoftlss  não consegue colocar textos com Ç. 

É isso ? 

@rondosoftlss , você pode dar mais detalhes? o que acontece quando o texto tem Ç ?

**Comment by rondosoftlss** [comment]
@marcosgerene peço desculpas da forma que me expressei. 

@rodrigordi o meu problema é que tenho alguns clientes "abençoados" que querem usar Ç, a parte de geração e transmissão blz, funciona tudo certo, o problema só da na hora de imprimir, pesquisando vi que tem uma forma de resolver isso que é carregar o XML no formato UTF8 mais como tenho pouco conhecimento de C# não consegui descobrir como fazer isso na biblioteca Zeus, então fui conversar com o @robertorp  e o mesmo pediu para eu abrir essa issue que ele iria implementar essa melhoria na biblioteca.

**Comment by rodrigordi** [comment]
@rondosoftlss , então seu problema é somente na impressão do DANFe ?

**Comment by rondosoftlss** [comment]
@rodrigordi, sim, não carrega o XML.

Se puder me ajudar, passa seu skype que conversamos por lá.

**Comment by marcosgerene** [comment]
@rondosoftlss estamos falando de NFe ou NFCe? Estamos falando da impressão dentro do projeto ou exeterna?

**Comment by rondosoftlss** [comment]
@marcosgerene impressão de NFe usando a rotina do Zeus mesmo com FastReports.
Vou anexar o XML aqui para vocês verem e entenderem o que estou dizendo.

[31170722584036000100550010000014861388606231-procNfe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1194360/31170722584036000100550010000014861388606231-procNfe.zip)

**Comment by marcosgerene** [comment]
@rondosoftlss eu removo os acentos do meu sistema antes de emitir, na verdade, tiro de todo e qualquer documento fiscal pq sempre tirei mesmo, nem sabia que este problema existia... vou fazer um teste, se for ajuste simples no .frx eu posto ele ajustado aqui.

**Comment by marcosgerene** [comment]
@rondosoftlss eu removo os acentos do meu sistema antes de emitir, na verdade, tiro de todo e qualquer documento fiscal pq sempre tirei mesmo, nem sabia que este problema existia... vou fazer um teste, se for ajuste simples no .frx eu posto ele ajustado aqui.

**Comment by rondosoftlss** [comment]
@marcosgerene concordo com você em retirar os acentos, mais a questão é que estou com uns abençoados que insistem que querem a acentuação, então foi por isso que acabei pesquisando e vi que tem como apenas informando que o formato é UTF8 só falta entender onde é isso, rs

**Comment by marcosgerene** [comment]
@rondosoftlss e @rodrigordi o problema não esta na impressão, ocorre na função _**CarregarDeArquivoXml()**_

Não tem nada a ver com a impressão em si, mas sim com o fato do componente não conseguir ler esse xml para deserealizar e transformar nos objetos.

Vou fazer mais alguns testes para ver se tem alguma solução paliativa.

**Comment by rodrigordi** [comment]
@marcosgerene se for na hora de DEserializar pode ser mais simples de resolver. vou procurar essa funcao aqui nos fontes e avaliar se algo pode ser feito. 👍

**Comment by rodrigordi** [comment]
@marcosgerene o problema seria aqui ?

![image](https://user-images.githubusercontent.com/1608626/28881577-f891a1e0-777e-11e7-9cbf-3269833ea386.png)

Não tem enconding.

**Comment by rodrigordi** [comment]
@marcosgerene não consigo testar aqui ainda pq não tenho ambiente montado.
se for possivel, depois teste assim. acho que resolveria.

precisa ver se não vai dar problema na transmissao e diferenca na assinatura.

public static T XmlStringParaClasse<T>(string input) where T : class
        {
            var ser = XmlSerializer.FromTypes(new[] { typeof(T) })[0];

            var xmlBytes = Encoding.UTF8.GetBytes(input);
            var ms = new MemoryStream(xmlBytes);
            return (T)ser.Deserialize(ms);

            //using (var sr = new StringReader(input))
            //    return (T) ser.Deserialize(sr);
        }

![image](https://user-images.githubusercontent.com/1608626/28881769-97272442-777f-11e7-8651-d0c2b7e6df13.png)

**Comment by marcosgerene** [comment]
@rodrigordi estou testando algumas possibilidades, mas já adianto que não tem nada a ver com o que propôs, em 20 min apresento algo, nao pode ser mais que isso, porque vou num cliente agora as 13:30

**Comment by marcosgerene** [comment]
@rondosoftlss está aqui sua solução:

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/502/commits/1805fc38ea9c907ffae28f77b329e2f3927acfb1

utilize assim:
```
var stream = new StreamReader(arquivoXml, Encoding.GetEncoding("ISO-8859-1"));
var proc = new nfeProc().CarregardeStream(stream);
```

Resultado:
![image](https://user-images.githubusercontent.com/15945003/28883336-6ef1921e-7784-11e7-9fa8-8fba849d08d9.png)

**Comment by rodrigordi** [comment]
Obrigado pela dica @marcosgerene. Eu fui no escuro com muita vontade de ajudar.

Coloquei o projeto para rodar aqui na minha máquina.

Havia entendido que o problema era quando carregava da string para o objeto. Mas agora dei uma lida no projeto, eu vi onde estava levantando a exception. O XDocument estava levantando exception ao ler o arquivo do @rondosoftlss no disco sem usar Encoding.

Comigo funcionou. Valeu.

**Comment by rondosoftlss** [comment]
@marcosgerene valeu meu amigo. agradeço muito.

Fiz o teste aqui e deu certinho. Valeu.

**Comment by marcosgerene** [comment]
@rondosoftlss por favor feche a insue se o seu problema foi sanado.
