### ISSUE TITLE
Passo a passo

### ISSUE THREAD

**Issue by jfmgalvao** [ZeusAutomacao/DFe.NET#506]
Olá pessoal, eu nunca emitir nenhuma nota, mas gostaria de saber  como eu faço para emitir uma NFCe, nota fiscal do consumidor.

existe algum tutorial de como fazer isso ?

**Comment by robertorp** [comment]
Talvez essas issues possam ajudar 
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/93
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/414
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/454
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/468
Se pesquisar, acha até mais conteúdo já pronto para sua questão.
