### ISSUE TITLE
Download NFe

### ISSUE THREAD

**Issue by cecon** [ZeusAutomacao/DFe.NET#507]
Ola pessoal, não estou conseguindo fazer o download .
Retorno "Servico Paralisado sem Previsao"

**Comment by robertorp** [comment]
Serviço de Download foi desativo. 

Dentro deste pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/430 tem uma nova implementação atraves da manifestação destinatário, vou estar analisando o pull e efetuando o merge/ ajustes se precisar no final de semana.
