### ISSUE TITLE
Enviar xml

### ISSUE THREAD

**Issue by jfmgalvao** [ZeusAutomacao/DFe.NET#508]
olá pessoal, eu sou novato nessa area e estou com muita dificuldade de me comunicar com a sefaz. eu montei o xml dessa forma,
string xmlConteudo = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>" 
                                + "<consStatServ versao=\"3.10\" xmlns=\"http://www.portalfiscal.inf.br/nfe/">" 
                                + "<tpAmb>2</tpAmb>"
                                + "<cUF>26</cUF>" 
                                + "<xServ>STATUS</xServ>" 
                                + "</consStatServ>";

        XmlDocument doc = new XmlDocument();
        doc.PreserveWhitespace = true;
        doc.LoadXml(xmlConteudo);

        XmlNode xmlDados = null;
        xmlDados = doc.DocumentElement;

        nfeCabecMsg nfeCabecalho = new nfeCabecMsg();
        nfeCabecalho.cUF = "26";
        nfeCabecalho.versaoDados = "3.10";

        NfeStatusServico2SoapClient nfceStatusServico = new NfeStatusServico2SoapClient();
        X509Certificate2 certificado = new X509Certificate2(_path, Utility.Decrypt(_psw));

        EndpointAddress endereco = new EndpointAddress(_urlStatusNFCe);
        nfceStatusServico.Endpoint.Address = endereco;
        nfceStatusServico.ClientCredentials.ClientCertificate.Certificate = certificado;
        var resp = nfceStatusServico.nfeStatusServicoNF2(ref cab, doc);
como eu envio esse xml para sefaz para pegar a mensgem de retorno.

se alguem puder me ajudar, desde já fico muito grato.

**Comment by robertorp** [comment]
Framework Zeus é para abstrair isso. Baixa o repositório em sua maquina e siga os exemplos.

**Comment by jfmgalvao** [comment]
@robertorp, mas o estou com o codigo na minha maquina só não estou conseguindo entender, o que eu vou utilizar para enviar ou ate mesmo montar o xml pelo framework.

**Comment by robertorp** [comment]
O Xml o framework monta, entra no método de criar e enviar nota, você vai ver lá dentro a criação de uma nota exemplo e o envio da mesma.

edit: no caso da consulta status, ele não tem parâmetro nem um. E somente carregar as configurações e consultar o status.

**Comment by jfmgalvao** [comment]
@robertorp, eu vou precisar mudar algo daquele exemplo, para enviar nfce(nota fiscal do consumidor) ?

**Comment by robertorp** [comment]
Leia a Wiki https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki
No exemplo temos parâmetros NFC-e/NF-e 
Tente usar os parâmetros da NFC-e.
Lembrando que no caso de NFC-e você deve informar o idToken é o CSC

**Comment by jfmgalvao** [comment]
o que é o idToken e o CSC ?

**Comment by marcosgerene** [comment]
@jfmgalvao 

> o que é o idToken e o CSC ?

Amigo, acredito que suas dúvidas são muito mais teóricas do que técnicas nesse primeiro momento, seria interessante você dar uma lida no manual do NFCe antes de começar a desenvolver pois se não vai quebrar a cara e bastante quando o seu projeto já tiver pronto por falta de conhecimento (passei por isso em um projeto em Delphi a alguns anos).


Sobre sua dúvida:

CSC =  Código de Segurança do Contribuinte.

Google, primeiro resultado: http://br.sageone.com/2016/09/29/codigo-de-seguranca-do-contribuinte/

IdToken é o ID do seu CSC, você pode ter mais que um CSC.

**Comment by alexsandro-xpt** [comment]
@jfmgalvao Você já tem o certificado?

**Comment by jfmgalvao** [comment]
@alexsandro-xpt eu tenho o certificado do tipo A1. seria só esse ??

**Comment by marcosgerene** [comment]
@jfmgalvao Sim, pode ser A1 ou A3, tanto faz.

Com o certificado você deve gerar o CSC de homologação, realizar a implementação e testar o seu software.

Depois gerar o CSC de produção e por pra rodar pra valer

A NFCe não exige homologação, logo a sua responsabilidade com testes é maior ainda

**Comment by jfmgalvao** [comment]
@marcosgerene onde eu gero o csc ?

**Comment by jfmgalvao** [comment]
@marcosgerene  nessa linha, Emitente = new emit { CPF = "", CRT = CRT.SimplesNacional };, eu substituo pelo cnpj da empresa que vai emitir a nota ??

**Comment by marcosgerene** [comment]
@jfmgalvao 

> onde eu gero o csc ?

Você leu o que eu disse anteriormente? rs

> Google, primeiro resultado: http://br.sageone.com/2016/09/29/codigo-de-seguranca-do-contribuinte/

O CSC deve ser gerado no site da sefaz do estado do emitente. De onde o emitente é (UF)?

------

> nessa linha, Emitente = new emit { CPF = "", CRT = CRT.SimplesNacional };, eu substituo pelo cnpj da >empresa que vai emitir a nota ??

```
var emitente = new emit();
emit.AtributoA = valorA;
emit.AtributoB = valorB;
emit.AtributoC = valorC;

Emitente = emitente;
```

Eu implementaria assim, preenchendo os atributos que lhe são necessários.

**Comment by jfmgalvao** [comment]
@marcosgerene eu posso te manda um email para você me ajudar ??

**Comment by marcosgerene** [comment]
@jfmgalvao 

> eu posso te manda um email para você me ajudar ??

Se você me mandar um e-mail e mais gente precisar da mesma coisa no futuro ninguém vai ter essa informação. As insues que você viu aqui ate agora e que podem ter te dado alguma luz tem justamente esse motivo para estar ai, o conhecimento deve ser compartilhado.

**Comment by robertorp** [comment]
@jfmgalvao  conseguiu ?

**Comment by jfmgalvao** [comment]
@robertorp  não tentei pelo excutavel com meu certificado, nem por la foi.
