### ISSUE TITLE
Importação e envio de XML

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#51]
Olá Adenilton!
Estou fazendo testes gerando uma NFCe OffLine para depois enviar.
Passos que fiz usando a sua AppTeste:
-Passo 1: Criar e Salvar XML 3.0
-Passo 2: Criar e Enviar 3.0
-Passo 3: Consultar Recibo Lote 3.0

Ao consultar o status da NF me retornou "Rejeicao: Falha no reconhecimento da autoria ou integridade do arquivo digital".

Verifiquei que no XML gerado pelo passo 1 os valores das tags ICMSTot/vBC eram 0.00, mas o XML do passo 2 o valor era simplesmente 0, causando erro de assinatura por ter mudado os valores.

O que é necessário para corrigir este problema?

Obrigado,
Márcio Müller

**Comment by marciojmuller** [comment]
Bom após umas 20 tentativas =D, alterei na classe ICMSTot os metodos gets das propriedades para, como no exemplo: 
        public decimal vICMS
        {
            get { return Valor.Arredondar(_vIcms, 2); }
            set { _vIcms = Valor.Arredondar(value, 2); }
        }
e então a nota foi aprovada.

Márcio Müller

**Comment by adeniltonbs** [comment]
Ok, vou fazer essas alterações na biblioteca. Obrigado por reportar. Desculpa não ter respondido a mensagem, é que estava viajando. Retornei hj.
