### ISSUE TITLE
Converter TXT da NFe para XML

### ISSUE THREAD

**Issue by rafaelsgripp** [ZeusAutomacao/DFe.NET#513]
Estou tendo a necessidade de converter os arquivos TXT da NF-e que são importados pelo emissor da SEFAZ diretamente no XML da NF-e para depois assinar e transmitir para a SEFAZ. Existe essa funcionalidade na Zeus.Net?

**Comment by marcosgerene** [comment]
@rafaelsgripp não, porém sinta-se a vontade para implementar e enviar um PR
