### ISSUE TITLE
Falha no reconhecimento da autoria ou integridade do arquivo digital.

### ISSUE THREAD

**Issue by AcciolyDSI** [ZeusAutomacao/DFe.NET#514]
Olá, na SEFAZ do estado da Bahia, começou a gerar esse erro na emissão da NF-e **Falha no reconhecimento da autoria ou integridade do arquivo digital. p**

Fiz o teste de validação do xml no site https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx, e lá esta tudo ok.

Na aplicação de teste, apenas mudando para NFC-e, o xml é autorizado, mas quando mudo para NF-e, a contece esse erro, trocando apenas o emitente, para outro emitente do estado de São Paulo, a nota é autorizada, já verifiquei o cadastro do emitente e não vi nada de errado, não tem acentos nada. Comecei a desconfiar do certificado A1, mas o mesmo certificado é usado para emissão da NFC-e que não tem problema algum. 

Alguém teria alguma dica?, seria um problema da SEFAZ?, ou do cadastro do cliente na SEFAZ, pois esse problema só esta acontecendo nesse estado.

Abraços

**Comment by adeniltonbs** [comment]
>  Comecei a desconfiar do certificado A1, mas o mesmo certificado é usado para emissão da NFC-e que não tem problema algum.

A emissão de NFC-e e de NF-e são feitos em endereços separados, então o problema realmente pode ocorrer em um e em outro não.

Quanto a validação em [SEFAZ RS](https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx), foi com o XML já assinado?

Você pode testar a emissão com o emissor gratuito, disponibilizado pela SEFAZ, daí vai tirar a dúvida se o problema está em algo da biblioteca. O emissor pode ser baixado em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=Jd9VnWmU9wY=

**Comment by AcciolyDSI** [comment]
Oi Adenilton, obrigado pelo retorno, a validação foi com o xml assinado. 

Mas deixa eu te falar, acabou de normalizar, era algo na SEFAZ/BA.

O pior foi a perca de tempo procurando por um erro que na verdade não existia.

É triste depender desses ambientes e não ter a informação da parte deles, quando ocorre um problema.

De qualquer forma, muito obrigado pelo retorno Adenilton, vida longa e saúde e paz a todos.

Abraços

Accioly
