### ISSUE TITLE
Multithread NFe

### ISSUE THREAD

**Issue by bruno-alencar** [ZeusAutomacao/DFe.NET#515]
Bom dia a todos!

Gostaria de verificar com vocês, se é possível realizar um pull request para fazer uma alteração na classe ConfiguracaoServico. Hoje ela está de forma estática, que impossibilita o uso de multithread e de multiempresa.

Desde já agradeço.

**Comment by robertorp** [comment]
@bruno-alencar  faça o pull request, e vamos ver como fica.

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/519

Veja isso também, pode ser que o multithread de algum problema em alguns casos bem específicos.

**Comment by bruno-alencar** [comment]
@robertorp provavelmente o problema seja pelo uso da forma estática da classe de configuração. Talvez essa implementação possa ajudar.

**Comment by marcosgerene** [comment]
@bruno-alencar está se referindo a #519?

> @robertorp provavelmente o problema seja pelo uso da forma estática da classe de configuração. >Talvez essa implementação possa ajudar.

**Comment by alexsandro-xpt** [comment]
Conseguiram aplicar @bruno-alencar ?

**Comment by bruno-alencar** [comment]
@marcosgerene Isso. Não é certeza, mas talvez a implementação de multithread ajude neste problema.
@alexsandro-xpt Fiz a implementação, estamos validando agora.

**Comment by robertorp** [comment]
Está sendo feito por @bruno-alencar .
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/522
