### ISSUE TITLE
RetornoNFeAutorizacao - ServicosNFe.NFeAutorizacao

### ISSUE THREAD

**Issue by krgm03** [ZeusAutomacao/DFe.NET#516]
Bom dia

No método ServicosNFe.NFeAutorizacao é realizado um 'Replace' caso a UF seja PR conforme mostra o trecho abaixo
...
var xmlEnvio = pedEnvio.ObterXmlString();
if (_cFgServico.cUF == Estado.PR)
   //Caso o lote seja enviado para o PR, colocar o namespace nos elementos <NFe> do lote, pois....
   xmlEnvio = xmlEnvio.Replace("<NFe>", "<NFe xmlns=\"http://www.portalfiscal.inf.br/nfe\">");
...

Mas no retorno do método o valor que pode ter sofrido o 'Replace' não é retornado conforme mostra o trecho abaixo
...
return new RetornoNFeAutorizacao(pedEnvio.ObterXmlString(), retEnvio.ObterXmlString(), retornoXmlString, retEnvio);
...

Há algum motivo para estar dessa maneira ou deveria estar retornando o valor que pode sofrer Replace?

Obrigado!

**Comment by robertorp** [comment]
Nunca tinha visto isso hehe. 
Você poderia tentar fazer somente um load do xml de envio com  o replace aplicado? Se funcionar certinho faço o ajuste ou ate mesmo você pode fazer o ajuste e mandar um pull (imagino eu que irá funcionar corretamente mas, sempre é bom testar, pois o projeto carece de testes)

**Comment by krgm03** [comment]
É apenas um detalhe mesmo
Como estamos pegando o retorno para salvar os arquivos e deixando 'SalvarXmlServicos' desabilitado, queremos que o conteúdo que iremos salvar seja igual ao conteúdo que o zeus salvaria

Em NFeAutorizacao é passado o conteúdo de 'xmlEnvio' que pode ter sofrido o replace conforme trecho abaixo
SalvarArquivoXml(idLote + "-env-lot.xml", xmlEnvio);

Mas retorna o conteúdo de 'pedEnvio.ObterXmlString()' conforme o trecho abaixo
return new RetornoNFeAutorizacao(pedEnvio.ObterXmlString(), retEnvio.ObterXmlString(), retornoXmlString, retEnvio);

Portanto bastaria retornar 'xmlEnvio' ao invés de 'pedEnvio.ObterXmlString()'

Obrigado
