### ISSUE TITLE
Sugestão desacoplar gravação de 'XML servicos'

### ISSUE THREAD

**Issue by krgm03** [ZeusAutomacao/DFe.NET#517]
Boa tarde

É bem interessante poder habilitar 'SalvarXmlServicos' para a gravação dos xmls

Mas pode haver a necessidade de gravar os xmls em outro local como por exemplo num 'Blob Storage' ou num banco nosql...

A sugestão seria poder implementar uma Interface/Contrato que seria chamada dentro do método 'SalvarArquivoXml'. Assim cada um implementaria o contrato para realizar a gravação/persistência da maneira que for mais conveniente

Trecho abaixo apenas para exemplificar o contrato que haveria e que seria implementado por cada um de acordo com sua necessidade
public interface IRepositorioXmlServicos
{
        bool Salvar(string nome, string xmlConteudo);
}

Aqui por enquanto iremos desabilitar 'SalvarXmlServicos', pegar o retorno dos métodos e gravar no nosso armazenamento que não será em pastas do projeto

**Comment by robertorp** [comment]
Você pode pegar o retorno e salvar ele onde quiser.

Gostei da ideia sua. Na refatoração que estou fazendo aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503 pensei em colocar eventos, você implementa o evento e faz oque quiser com ele. Exemplo: AntesEnviarLoteHandler, AntesAssinarNFe.. e teria os Depois Também

edit: implemente isso para nos vermos como fica também a sua ideia.

**Comment by krgm03** [comment]
"Você pode pegar o retorno e salvar ele onde quiser."
Sim, estamos fazendo isso

Eventos seria bacana também

Vou implementar sim

Obrigado
