### ISSUE TITLE
Zeus funciona no estado de goiás certinho?

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#52]
Zeus funciona no estado de goiás certinho?
nfc-e e nf-e (go, tem testes, produção não)

**Comment by adeniltonbs** [comment]
Pelo que vi em (http://aplicacao.sefaz.go.gov.br/index.php/post/ver/200095/sefaz-disponibiliza-teste-para-nfc-e) a SEFAZ de GO utiliza as mesmas urls para NFe e para NFCe, portanto a biblioteca é para estar pronta para esse estado. Até mesmo quando eles entrarem em produção, se utilizarem as mesmas urls, já estará pronto.

Por favor faça os testes no aplicativo de demonstração e poste o resultado aqui.

**Comment by robertorp** [comment]
Segunda-feira sem falta, estarei testando e postando o resultado.

**Comment by robertorp** [comment]
chefe, testei aqui, agora não sei se e erro ou se algo que estou fazendo errado mas toda vez que vou consultar pela chave (no exemplo)
ele me retorna somente 

Rejeição: Código da UF do Emitente diverge da UF autorizadora

**Comment by adeniltonbs** [comment]
Está usando o certificado de uma empresa de GO?

**Comment by robertorp** [comment]
Sim, emitido por uma empresa filial nossa de goiás mesmo,
ate então estou debugando o código para entender o mesmo nessa parte

**Comment by adeniltonbs** [comment]
Por favor me envie o xml de envio e o de retorno para eu dar uma olhada

**Comment by robertorp** [comment]
a chave CSC foi emitida aqui, http://www.hom.nfe.se.gov.br/portal/portalNoticias.jsp?jsp=barra-menu/servicos/manutencaoCSC.htm

**Comment by adeniltonbs** [comment]
pela mensagem da SEFAZ você está enviando o código da UF diferente de 52, se você puder, poste o xml de envio que posso dar uma olhada.

Para obter o xml de envio, ative a opção da biblioteca para salvar o xml de cada mensagem enviada e retornada para a SEFAZ.

**Comment by robertorp** [comment]
https://www.dropbox.com/s/zprr6yyicer26hv/xml%20envio.xml?dl=0

**Comment by robertorp** [comment]
Se poder me dizer uma possível causa para eu estar correndo atrás disso, pq acima você disse algo relacionado a certificado

**Comment by marciojmuller** [comment]
Olá!
28151021025760000123650010000000011000012349
Se está tentando enviar nota para GO o estado deve ser 52 não 28.

Verifique que no inicio da chave de acesso que esta tentando consultar está 28.

**Comment by robertorp** [comment]
Muito obrigado! agora deu um outro erro o de token pq preciso de um token para GO, mas o erro é pq  na MainWindow.xaml.cs no método 
protected virtual ide GetIdentificacao(int numero, ModeloDocumento modelo, VersaoServico versao)

está setado Estado.SE , foi somente trocar para GO e zerou,

obs: se você souber como adquirir o CSC para GO ou como posso gerar ele, e poder me dar o caminho das pedras agradeço!

muito obrigado!

**Comment by adeniltonbs** [comment]
roberto, recomendo entrar em contato com a SEFAZ de GO, pois até agora eles não publicaram quase nada no site.
