### ISSUE TITLE
Erro ao gerar documento XML

### ISSUE THREAD

**Issue by mhermanet** [ZeusAutomacao/DFe.NET#520]
Ola,

estou tentando criar e enviar uma nota 3.0 mas nao hora de assinar o documento, aparece essa mensagem de erro. Me parece ser algum problema pra serializar o objeto NFe.

Saberiam do dizer do que se trata? a principio configurei as informacoes do emitente e destinatario. Falta alguma coisa sera?

Estou usando o visual studio professional 2012 compilando no .Net 4.0.

agradeço a ajuda.
ate mais.

**Comment by robertorp** [comment]
poste a expection e inner expection enfim o erro completo para nos

edit: o xml também

**Comment by mhermanet** [comment]
achei o erro.....estava faltando o campo CRT nas informaçoes do emitente. Preenchi e enviou pra homologaçao.

agradeço a atençao.
ate mais.

**Comment by robertorp** [comment]
@mhermanet  obrigado pelo retorno, que bom que tudo deu certo. 
Qualquer coisa abre issue viu. 
Quanto mais issue nos tiver é mais documento a ser pesquisado pelos usuários da lib.
