### ISSUE TITLE
Erro: 412 Precondition Failed

### ISSUE THREAD

**Issue by WilliamSantosSilva** [ZeusAutomacao/DFe.NET#523]
Estou tentando emitir NF de produto e estou tendo esse erro, alguem poderia me ajudar ?

412 - Precondition set by the client failed when evaluated on the Web server.
The request was not completed due to preconditions that are set in the request header. Preconditions prevent the requested method from being applied to a resource other than the one intended. An example of a precondition is testing for expired content in the page cache of the client.

**Comment by robertorp** [comment]
qual serviço esta utilizado?
qual a versão?
qual estado uf?
esta acontecendo no app teste?

**Comment by WilliamSantosSilva** [comment]
qual serviço esta utilizado?

Emissão NFE


qual a versão?

Acho que 3.0


qual estado uf?

SP


esta acontecendo no app teste?

Esta acontecendo no meu sistema de emissão, mudei de servidor e estou tentando no mabiente de homologação e na minha maquina está dando timeout e no server esse erro.


Att,


"Nada é pra sempre, nem mesmo nossos problemas." (Charles Chaplin)

William Santos Silva I Analista Programador .NET
Cel:     +55 (11) 96347-2683
Skype: william_santos_silva1


"O verdadeiro Heroismo consiste em persistir por mais um momento quando tudo parece perdido. "


________________________________
De: Roberto Alves Pereira <notifications@github.com>
Enviado: segunda-feira, 11 de setembro de 2017 15:35:12
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: WilliamSantosSilva; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro: 412 Precondition Failed (#523)


qual serviço esta utilizado?
qual a versão?
qual estado uf?
esta acontecendo no app teste?

**Comment by robertorp** [comment]
Tenta trocar o protocolo de comunicação

**Comment by WilliamSantosSilva** [comment]
Como assim ?




Att,


"Nada é pra sempre, nem mesmo nossos problemas." (Charles Chaplin)

William Santos Silva I Analista Programador .NET
Cel:     +55 (11) 96347-2683
Skype: william_santos_silva1


"O verdadeiro Heroismo consiste em persistir por mais um momento quando tudo parece perdido. "


________________________________
De: Roberto Alves Pereira <notifications@github.com>
Enviado: terça-feira, 12 de setembro de 2017 00:45:18
Para: adeniltonbs/Zeus.Net.NFe.NFCe
Cc: WilliamSantosSilva; Author
Assunto: Re: [adeniltonbs/Zeus.Net.NFe.NFCe] Erro: 412 Precondition Failed (#523)


Tenta trocar o protocolo de comunicação

**Comment by robertorp** [comment]
No app teste tem protocolo de comunicação troque ele

**Comment by robertorp** [comment]
@WilliamSantosSilva Deu certo?
