### ISSUE TITLE
DanfeNativoNfce

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#524]
Olá!
Fazendo testes aqui verifiquei que ao informar um endereço muito grande, com número e complemento acaba cortando o telefone, visto que sai da página.
Teria como fazer uma quebra de linha quando acontece este tipo de problema?

Ex.: AV EDUARDO PRADO 1234, LOJA 999, AUXILIADORA, PORTO ALEGRE, RS - FONE:515555555

Obrigado.

**Comment by robertorp** [comment]
Poderia fazer um pull pra nos? *-* iria achar tão legal ;)
Mas se não fizer vou fazer isso mas, sem data prevista hehe vou adicionar como bug a corrigir.

**Comment by Guaze** [comment]
Peguei essa dll um tempo atrás para realizar impressão. Existiam uns problemas de formatação.

Peguei o código fonte e fiz um versão de orçamento ajustando os problemas que eu havia identificado.

Danfe nativo
![img_2361](https://user-images.githubusercontent.com/28018162/30748394-8ebd0cac-9f86-11e7-8a9b-39f76f1b933f.JPG)

-EAN sobrepõe a descrição do produto;
- label de qtde e un juntas;
- informações do nata, série, . . . ultrapassam o limite desejado. 
Minha versão (para orçamento)
![img_2362](https://user-images.githubusercontent.com/28018162/30748416-a0abd5b0-9f86-11e7-821f-b16faa2f22d2.JPG)

**Comment by fatechbr** [comment]
Galera, sou novo no hithub, desenvolvi uma solução nativa de de impressão de Dante e do relatório da nfc-e como faço para que meu projeto seja absorvido pelo seus? Ou seja unificar projeto?

**Comment by fatechbr** [comment]
Ops github
