### ISSUE TITLE
Consulta Cadastro RJ

### ISSUE THREAD

**Issue by dalpogetto** [ZeusAutomacao/DFe.NET#525]
Bom dia amigos,
A Consulta Cadastro para o RJ não está funcionando, ou melhor, ela existe ?

Quanto tento realizar uma consulta recebo a seguinte mensagem:

**Erro: Serviço NfeConsultaCadastro, versão 2.00, não disponível para a UF RJ, no ambiente de Produção para emissão tipo Normal, documento: NF-e!**

Já tentei trocar a versao pela 1.00 e pela 3.10, mesma mensagem de erro.

Obrigado pela ajuda.

**Comment by robertorp** [comment]
RJ utiliza o servidor SVRS
NfeConsultaCadastro 2.00 https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx

Nos fontes do zeus está assim 

endServico.Add(new EnderecoServico(ServicoNFe.NfeConsultaProtocolo, VersaoServico.ve310, TipoAmbiente.taProducao, emissao, estado, ModeloDocumento.NFe, "https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx"));

Bom poderia verificar alguma nt que diz que é 310?

Vou fazer essa verificação mas, somente no fim de semana. 
Obrigado
