### ISSUE TITLE
Duvida Nota Devolução

### ISSUE THREAD

**Issue by FabioRoesler** [ZeusAutomacao/DFe.NET#527]
Ola pessoal.
Estou com duvida de como acrescentar a chave da nota referenciada em uma nota de devolução. Segue como estou tentando fazer:
            ....
            ide.finNFe = NFe.Classes.Informacoes.Identificacao.Tipos.FinalidadeNFe.fnDevolucao;
            ide.NFref = new List<NFe.Classes.Informacoes.Identificacao.NFref>();

Ficarei grato se alguém puder me dar uma mão.

**Comment by robertorp** [comment]
Basicamente se faz isso 
```
NFref = GetDocumentosReferenciados(nfe)
private static List<NFref> GetDocumentosReferenciados(Nfeletronica nfe)
        {
            if (!nfe.Referencias.Any() && !nfe.ReferenciasCf.Any())
                return null;

            var zref = new List<NFref>();

            nfe.Referencias.ForEach(r => zref.Add(CriaReferenciaNfZeus(r)));
            nfe.ReferenciasCf.ForEach(r => zref.Add(CriaReferenciaCfZeus(r)));

            return zref;
        }
```

Isso é um código meu implementado aqui do sistema.
Para receber maiores detalhes preciso de mais informações se você esta sofrendo alguma rejeição
se possível passar o xml completo que esta dando erro.

**Comment by FabioRoesler** [comment]
Deu certo Roberto!

Muito obrigado!
Qualquer duvida que surgir novamente informo.
