### ISSUE TITLE
Problema estranho

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#528]
[33170911385836000178550990000000601000000605.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1307490/33170911385836000178550990000000601000000605.zip)
Olá, boa tarde
Em alguma situações que ainda não consegui identificar, quando estou testando NF-e aparece essa mensagem 

![image](https://user-images.githubusercontent.com/16413266/30498569-9f1b9996-9a2d-11e7-809a-58a341f3a255.png)

Olhando o xml percebi que nos impostos PIS e COFINS está gerando com a sequencia errada, já olhei e ainda não consegui achar, por favor alguem teve esse tipo de situação que possa me ajudar.

Estou utilizando os ultimos schemas disponiveis no projeto.

Em anexo esta o xml de exemplo.

Desde já agradeço
[33170911385836000178550990000000601000000605.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1307491/33170911385836000178550990000000601000000605.zip)

**Comment by robertorp** [comment]
Conseguiu arrumar? 
Você utiliza nuget ou direto o projeto?

**Comment by alsantana** [comment]
Ola meu amigo @robertorp nao consegui achar ainda o problema, pelo que percebi ele acontece quando assina a nota (pq nesse momento acontece a validação), somente com produtos q tenham PISOutr e CofinsOutr, mas o pior de tudo é a intermitencia, tem hora que funciona sem problema nenhum.

Utilizo o projeto
grd abs

**Comment by robertorp** [comment]
Se esta determinado nas classes para gerar o XML de uma maneira ele não vai gerar o xml de outra. 
Tenta colocar o atributo Order nos xmls 

[XmlElement("nomeatrributo", Order = 1)]
[XmlElement("nomeatrributo", Order = 2)]
[XmlElement("nomeatrributo", Order = 3)]
etc..

**Comment by alsantana** [comment]
Ola @robertorp , boa tarde
Vc poderia me ajudar onde devo realizar essa alteração?
grd abs
