### ISSUE TITLE
Rejeicao: Operacao Interna e UF de destino diferente da UF do emitente

### ISSUE THREAD

**Issue by xtsolucoes** [ZeusAutomacao/DFe.NET#53]
Ola boa tarde estou testando o Zeus com o SEFAZ do AM, estou fazendo o teste de envio ele retorna que foi recebido mais ao consulta pelo codigo do Recido ele retorna isto:
Rejeicao: Operacao Interna e UF de destino diferente da UF do emitente

**Comment by darlanhendges** [comment]
Boa noite.

Não sou um expert amigo, no entanto estava tentando ler a respeito.

Leia sobre isso acho que pode ajuda:
http://rejeicao.com.br/nfe-rejeicao-773/

Mas principalmente na parte:

"Caso o a UF do destinatário esteja Correta e você está enfrentando essa rejeição, provavelmente o campo de “Identificação do local de destino da operação” (idDest) esteja errado.
O idDest deve ser preenchido da seguinte maneira:

1 = Operação interna ( Notas para dentro do Estado );
2 = Operação interestadual ( Notas para fora do Estado);
3 = Operação com exterior (Notas para fora do país) ."

Abs

**Comment by xtsolucoes** [comment]
Opa muito obrigado deu certo.
