### ISSUE TITLE
Tem como contribuir para o projeto sem ter certificado A1 ou A3?

### ISSUE THREAD

**Issue by alexsandro-xpt** [ZeusAutomacao/DFe.NET#531]
Algum fallback pra comunicar com os WS da receita em ambiente de teste ou algo assim?

**Comment by marcosgerene** [comment]
Bom dia,

Sem o certificado você não vai conseguir fazer qualquer operação de consumo do webservice (envio, consulta, cancelamento, etc). Entretanto pode ajudar a mapear as classes, ajudar na manutenção das impressões, etc.

Atualmente o componente utiliza o FastReports para impressão do CTe, MDFe e NFe em A4, a única impressão que tem em Fast e nativo é a do NFCe, implementar uma das impressões em forma nativa seria uma ótima forma de contribuir sem necessitar do certificado.

PS: O FastReports é um componente pago, eu implementei a impressão do CTe e do MDFe nele pois é absurdamente mais simples e eu utilizo o componente no meu dia a dia e tem mais gente aqui que utiliza, mas nativo é nativo.

Att, Marcos
