### ISSUE TITLE
Erro ao enviar duas notas em seguida

### ISSUE THREAD

**Issue by Guaze** [ZeusAutomacao/DFe.NET#532]
Estou obtendo este erro ao enviar duas notas seguidas.

faço uma venda >> envio >> ok

faço uma venda >> envio >> erro abaixo
![erro](https://user-images.githubusercontent.com/28018162/30776093-afef9bba-a076-11e7-959e-ad394629c884.JPG)

fecho o sistema e abro novamente; consegue enviar.

**Comment by Guaze** [comment]
Complementando . . . o problema ocorre ao assinar a nfe.

**Comment by robertorp** [comment]
Esta parecendo que ele esta inserindo dois certificados digitais com o mesmo id (estou presumindo somente, pois é um dicionario  onde é armazenado os certificados digitais em cache, e é feito uma busca do mesmo antes de adicionar)
Teria como postar pedaços do seu código ?
O código de envio (se isso for envio) é da parte em que você cria as configurações do certificado digital

**Comment by Guaze** [comment]
public NFe.Classes.NFe GerarNFCe(Venda venda)
        {
            try
            {
                this.vendaAtual = venda;

                //Gerar a nota fiscal.
                NFe.Classes.NFe nfe = GetNFCe();

                //Não precisa validar aqui, pois o lote será validado em ServicosNFe.NFeAutorizacao.
                nfe.Assina();

                if (nfe.infNFe.ide.mod == DFe.Classes.Flags.ModeloDocumento.NFCe)
                {
                    //A URL do QR-Code deve ser gerada em um objeto nfe já assinado, pois na URL vai o DigestValue que é gerado por ocasião da assinatura
                    //Define a URL do QR-Code.
                    nfe.infNFeSupl = new NFe.Classes.infNFeSupl() { qrCode = nfe.infNFeSupl.ObterUrlQrCode(nfe, this.ConfiguracaoCsc.CIdToken, this.ConfiguracaoCsc.Csc) };
                }

                return nfe;
            }
            catch (Exception erro)
            {
                throw new BusinessException(erro.Message);
            }
        }

**Comment by Guaze** [comment]
//Gerar a nota fiscal.
                            nfe = nfceUtilities.GerarNFCe(this.Venda);

                            //Enviando a NFCe para Receita Federal
                            NFe.Servicos.Retorno.RetornoNFeAutorizacao retornoEnvio = nfceUtilities.EnviarNFCe(this.Venda.Lote, nfe);
                            protNFe = retornoEnvio.Retorno.protNFe;

                            //Atualizando a venda com as informações da Receita Federal
                            bp.UpdateInforReceitaFederal(
                                this.Venda,
                                nfe.infNFe.Id.Substring(3),
                                protNFe.infProt.cStat
                                );

                            //Criar diretório para armazenar XML
                            string diretorio = utils.CriarDiretorioNFCe(
                                    Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),
                                    Venda.Data);

                            if (protNFe != null && protNFe.infProt.cStat.Equals(100))
                            {
                                nfeProc = new NFe.Classes.nfeProc();
                                nfeProc.NFe = nfe;
                                nfeProc.protNFe = protNFe;

                                //Salvando o xml localmente
                                nfeProc.SalvarArquivoXml(diretorio + this.Venda.ChaveAcesso + "-nfe.xml");
                            }

**Comment by Guaze** [comment]
public NFe.Classes.NFe GerarNFCe(Venda venda)
        {
            try
            {
                this.vendaAtual = venda;

                //Gerar a nota fiscal.
                NFe.Classes.NFe nfe = GetNFCe();

                //Não precisa validar aqui, pois o lote será validado em ServicosNFe.NFeAutorizacao.
                nfe.Assina();

                if (nfe.infNFe.ide.mod == DFe.Classes.Flags.ModeloDocumento.NFCe)
                {
                    //A URL do QR-Code deve ser gerada em um objeto nfe já assinado, pois na URL vai o DigestValue que é gerado por ocasião da assinatura
                    //Define a URL do QR-Code.
                    nfe.infNFeSupl = new NFe.Classes.infNFeSupl() { qrCode = nfe.infNFeSupl.ObterUrlQrCode(nfe, this.ConfiguracaoCsc.CIdToken, this.ConfiguracaoCsc.Csc) };
                }

                return nfe;
            }
            catch (Exception erro)
            {
                throw new BusinessException(erro.Message);
            }
        }
[classe.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1326788/classe.pdf)

A minha "classe" para fazer interface com Zeus.

**Comment by Guaze** [comment]
Parte do xml de configuração.

![xml](https://user-images.githubusercontent.com/28018162/30776442-dcfcc97e-a07c-11e7-905e-7f689a814a81.JPG)

**Comment by Guaze** [comment]
Você falou de cache; logo lembrei desta configuração ai "ManterDadosEmCache".

Coloquei ela para "false" e consegui fazer dois envios em seguida.

Para que serve manter em cache?

**Comment by robertorp** [comment]
Vou analisar e fazer testes no Zeus, terminando retorno aqui
Mas manter em cache serve para não fazer load do certificado digital todo segundo, no caso é mais util para certificado digital A3, pois o mesmo sempre tem uma demorinha para carregar, ele já fica carregado em memoria somente faz um certificado.Reset(). Ele não recria o certificado digital do 0 em memoria.

**Comment by Guaze** [comment]
Beleza. fico no aguardo mas, por hora, deixar "false" funcionou.

**Comment by Guaze** [comment]
Com "false" e uso continuo começa a dá erro de ". . .  abrir canal seguro . . .". Tenho que reiniciar a aplicação para voltar a funcionar.

**Comment by robertorp** [comment]
manda print do erro novo para nos, isso ta parecendo outro erro pelo que vc descreveu

**Comment by Guaze** [comment]
Boa noite Roberto,

Ainda não tive a possibilidade de ir lá no comércio; e também de ficar de posse do token para simular o erro em casa.

Estou trabalhando em funcionalidades essenciais para o sistema (aproveitando as férias para isso)

Sem falta irei amanhã lá para obter a imagem do erro.

Mas o erro é relacionado a alguma coisa em abrir o canal de comunicação. Deve ser para instanciar o serviço.

A proposito, aconteceu o que você disse. Ficou mais lento o envio para a receita federal (tirei o token do cache) .

**Comment by Guaze** [comment]
Segue a imagem do erro!!!

![img_2390 1](https://user-images.githubusercontent.com/28018162/30868974-64cd824a-a2b6-11e7-9cf3-e685f55620d0.JPG)

**Comment by robertorp** [comment]
você adiciona a senha do certificado digital nas configs? se não tenta adicionar. 
existe alguma coisa acessando o certificado digital a3 , sem ser o sistema?
Comigo somente acontece o erro quando acesso o certificado digital de outro lugar.
Me manda o código de envio do xml para a sefaz. O código no qual vc manda autorizar.

**Comment by Guaze** [comment]
A senha já está no arquivo de configuração.

A aplicação anterior ainda está instalada na máquina (ela usa o certificado). Só que ela pede a senha para realizar a primeira iteração com a SEFAZ. A aplicação esta fechada!!!

Código:

        public NFe.Servicos.Retorno.RetornoNFeAutorizacao EnviarNFCe(int lote, NFe.Classes.NFe nfe)
        {
            try
            {
                //Carregando os serviços
                var servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico);

                //Enviando a NFCe para Receita Federal                                                                                                                                
                return servicoNFe.NFeAutorizacao(lote, IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { nfe }, true);
            }
            catch (Exception erro)
            {
                throw new BusinessException(erro.Message);
            }
        }

**Comment by marcosgerene** [comment]
@Guaze https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/519

**Comment by robertorp** [comment]
@Guaze  me add no skype para posteriormente eu fazer um acesso remoto em sua maquina
robertoalves18@hotmail.com

Porque eu o @adeniltonbs , @adrbarros  e uns outros não temos esse problema. Então vamos ver se acho algo no seu código. Ou se alteramos algumas configs.

Se possivel pegar o token do cliente num domingo da vida.

**Comment by Guaze** [comment]
Eu aviso quando estiver com o token em casa.

Resumindo o meu problema  "ManterDadosEmCache" 
Em = true.
"Já foi adicionado um item com a mesma chave"
(já no segundo envio)
Enquanto = false.
"A solicitação foi anulada: não foi possível criar uma canal seguro para ssl/tls"
(com o uso continuo)

- - - - - - -

Acho que acabei de descobrir a causa do problema. (tenho que testar)

Tenho um "formVenda" que chama o "formPagamento" que se comunica com a RF.

Quando a venda é encerrada com sucesso no formPagamento; eu faço um .close() nele.

Só que conforme a literatura diz .close() o deixa na memoria ainda (até um certo tempo) e tem como recuperar, ou seja, o meu objeto que que atua com Zeus para se comunicar com a RF também estará em memória porque ele é instanciado neste formulário.

Se eu trocar por .dispose() o formPagamento é eliminado da memória logo, o objeto vai junto.

o que acham?

@marcosgerene , @robertorp

**Comment by marcosgerene** [comment]
@Guaze o problema é resolvido simplesmente trocando o protocolo de comunicação (ServicePointManager.SecurityProtocol) eu "resolvi" o problema simplesmente tentando de novo com outro protocolo quando o erro acontecia.

Mas respondendo sua pergunta, sim, liberar da memoria vai melhorar e muito o problema, mas nao sanar completamente, pelo menos este foi meu caso.

**Comment by Guaze** [comment]
Acabei de realizar esta mudança no código fonte.

                using (FormPagamento form = new FormPagamento(this.Venda))
                {
                    form.ShowDialog(this);

                    if (form.VendaConcluida)
                    {
                        vendaConcluida = form.VendaConcluida;
                        ultimoMovimento = form.UltimoMovimento;
                    }
                }

                if (vendaConcluida)
                {
                    this.UltimoMovimento = ultimoMovimento;

                    this.InicializarForm();
                }

                //FormPagamento form = new FormPagamento(this.Venda);

                //form.ShowDialog(this);

                //if (form.VendaConcluida)
                //{
                //    this.UltimoMovimento = form.UltimoMovimento;

                //    this.InicializarForm();
                //}

**Comment by Guaze** [comment]
Boa noite @marcosgerene  e @adeniltonbs ,

Troquei a forma de instanciar o serviço e o problema de envio aparentemente diminui a frequência. Aproveitei que a classe é IDisposable fiz uso do using.

//Carregando os serviços
var servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico);

//Enviando a NFCe para Receita Federal                                                                                                                                return servicoNFe.NFeAutorizacao(lote, IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { nfe }, true);

Por:

//Carregando os serviços
                using (var servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico))
                {
                    //Enviando a NFCe para Receita Federal                                                                                                                                
                    return servicoNFe.NFeAutorizacao(lote, IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { nfe }, true);
                }

**Comment by robertorp** [comment]
@Guaze vai nos informando sobre isso, pois como disse em minha aplicação meus problemas com esse erro é zero.
Negocio é temos que verificar todos seu processo de montagem do zeus e envio do mesmo. Algo bem detalhado também. Esse erro pelo que vi é algo complexo de ser resolvido, mas ainda no meu ver e algo de implementação para implementação. Se vc me add no skype podemos trocar ideias melhores sobre ele. Tentar fazer o seu sistema dar certo mas vou quer algo detalhado da sua implementação do zeus do inicio até o fim. 

edit: já que usa o zeus e não o nuget melhor ainda, podemos fazer alterações na parte de assinatura, pois a minha assinatura do sistema não utilizo a do zeus ela é diferente, vou postar aqui como esta no meu sistema 
edit2: a minha assinatura foi retirada do zeus, mas a muitas versões antigas atrás.

**Comment by Guaze** [comment]
Estou com o token aqui agora em casa.

**Comment by robertorp** [comment]
Vamos lá por onde começo a emissão no meu emissor.
```
private EmissaoNfe CriaOuRecuperaEmissao()
        {
            if (_ultimaEmissao?.Finalizada == false)
                return _ultimaEmissao;

            var contingencia = GetContingenciaSeExistir(_nfe);
            var emissornfe = new EmissorNfe(_sessaoFactory);

            if (contingencia?.EstaAberta == true)
                emissornfe.AtivarContingencia(contingencia);

            _ultimaEmissao = emissornfe.Emitir(_nfe);

            return _ultimaEmissao;
        }
```

observe no código o "emitir" vamos ver oque tem la dentro agora

```
public EmissaoNfe Emitir(Nfeletronica nfe)
        {
            if (PossuiEmissaoPendente(nfe))
            {
                throw new InvalidOperationException("Não foi possivel emitir a NF-e, possui emissão pendente");
            }

            var emissor = nfe.Emitente.EmissorFiscal;

            var tipoEmissao = _contingenciaAtiva?.TipoEmissao ?? TipoEmissao.Normal;
            var certificado = CertificadoDigitalFactory.Cria(emissor, true);
            var cfgZeus = new ConfiguracaoZeusBuilder(emissor.EmissorFiscalNfe, tipoEmissao).GetConfiguracao();

            if (!nfe.PoussiNumeroAlocado())
            {
                _reservador.ReservarNumero(nfe);
            }

            nfe.PrepararParaEmissao(_sessaoFactory);

            var componentesChave = new ComponentesChaveNfe(nfe, tipoEmissao);
            var chave = ChaveSefazHelper.GerarChave(componentesChave);
            var ambiente = emissor.EmissorFiscalNfe.Ambiente;

            var emissao = new EmissaoNfe(nfe, emissor, ambiente, chave);

            if (_contingenciaAtiva != null)
            {
                emissao.DefinirContingencia(_contingenciaAtiva);
            }

            var zeusNfeAssinado = AssinadorNfe.Assina(nfe, emissao, certificado, _sessaoFactory);

            var versao = ServicoNFe.NFeAutorizacao.VersaoServicoParaString(cfgZeus.VersaoNFeAutorizacao);
            var assincrono = IndicadorSincronizacao.Assincrono;
            var notas = new List<ZeusNfe> {zeusNfeAssinado};

            var envio = new enviNFe3(versao, 1, assincrono, notas);
            var xmlEnvio = envio.ObterXmlString();

            ThrowExceptionSeXmlInvalido(xmlEnvio, cfgZeus);

            using (var sessao = _sessaoFactory.CriaSessao())
            {
                emissao.XmlEnvio = xmlEnvio;

                var repositorio = new RepositorioNfe(sessao);
                repositorio.Persistir(emissao);
            }

            return emissao;
        }
```

veja que salvo o xml de envio assinado no banco de dados (isso é uma maneira pessoal minha, salvo um historico de todas tentativas do cliente de enviar NF-e)
veja também que tenho uma classe propria de assinatura , vamos tentar pegar por ela, vc não ira utilizar a assinatura do zeus, utilize algo por fora como essa classe minha

```

public static class AssinadorNfe
    {
        public static ZeusNfe Assina(Nfeletronica nfe, EmissaoNfe emissao, X509Certificate2 certificado, ISessaoFactory sessaoFactory)
        {
            var reference = new Reference {Uri = $"#{emissao.TagId}"};
            var nfezeus = nfe.ToZeus(emissao, sessaoFactory);

            AlteraNomeDestinatarioDoXmlSeHomologacao(nfezeus, emissao.Ambiente);

            var documento = new XmlDocument {PreserveWhitespace = true};
            documento.LoadXml(FuncoesXml.ClasseParaXmlString(nfezeus));
            var docXml = new SignedXml(documento) {SigningKey = certificado.PrivateKey};

            // adicionando EnvelopedSignatureTransform a referencia
            var envelopedSigntature = new XmlDsigEnvelopedSignatureTransform();
            reference.AddTransform(envelopedSigntature);

            var c14Transform = new XmlDsigC14NTransform();
            reference.AddTransform(c14Transform);

            docXml.AddReference(reference);

            // carrega o certificado em KeyInfoX509Data para adicionar a KeyInfo
            var keyInfo = new KeyInfo();
            keyInfo.AddClause(new KeyInfoX509Data(certificado));

            docXml.KeyInfo = keyInfo;
            docXml.ComputeSignature();

            //// recuperando a representacao do XML assinado
            var xmlDigitalSignature = docXml.GetXml();
            var assinatura = FuncoesXml.XmlStringParaClasse<ZeusSignature>(xmlDigitalSignature.OuterXml);
            nfezeus.Signature = assinatura;

            return nfezeus;
        }

        private static void AlteraNomeDestinatarioDoXmlSeHomologacao(ZeusNfe nfezeus, TipoAmbiente tipoAmbiente)
        {
            if (tipoAmbiente == TipoAmbiente.Producao)
                return;

            nfezeus.infNFe.dest.xNome = "NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL";
        }
```

nesse ponto vc já deve ter visto que vai ter que trocar manualmente os dados do emissornf-e para seu objeto 

faça algo similar no seu sistema, e teste para nos vermos

**Comment by marcosgerene** [comment]
> Boa noite @marcosgerene e @adeniltonbs ,
>
>Troquei a forma de instanciar o serviço e o problema de envio aparentemente diminui a frequência. >Aproveitei que a classe é IDisposable fiz uso do using.
>
>//Carregando os serviços
>var servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico);
>
>//Enviando a NFCe para Receita Federal return servicoNFe.NFeAutorizacao(lote, >IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { nfe }, true);
>
>Por:
>
>//Carregando os serviços
>using (var servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico))
>{
>//Enviando a NFCe para Receita Federal
>return servicoNFe.NFeAutorizacao(lote, IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { >nfe }, true);
>}

O **using** não chama o _Dispose()_ em caso de _exception_.

Eu te aconselharia a fazer da seguinte forma:

```
NFe.Servicos.ServicosNFe servicoNFe;
try
{
   servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico);
   ...   
}
catch
{
   if (servicoNFe != null)
   {
      servicoNFe.Dispose();
      servicoNFe = null;
   }
   throw;
}
```

**Comment by rftd** [comment]
Não esta correto sua informação @marcosgerene ele só não chama o dispose se o erro ocorrer no  constructor da classe se ocorrer dentro do bloco ele funciona como um try finally e chama sim sempre o dispose.

**Comment by rftd** [comment]
Outra coisa que esqueci de falar no seu codigo você não trata o excption então não precisa ser um catch pode ser um finally que vai funcionar do mesmo jeito. ficando assim

> NFe.Servicos.ServicosNFe servicoNFe;
> try
> {
>    servicoNFe = new NFe.Servicos.ServicosNFe(this.CfgServico);
>    ...   
> }
> finally
> {
>    if (servicoNFe != null)
>    {
>       servicoNFe.Dispose();
>       servicoNFe = null;
>    }
> }

**Comment by Guaze** [comment]
Utilizando o using a frequência do erro diminui mas ocorre é o meu catch acabou sendo acionado.

Ontem fiquei até tarde da noite debugando com Roberto e encontramos uma possível solução.

Deixamos o token em cache e fizemos um pequeno ajuste no xml de configuração.

Instalei a pouco a nova versão no comércio.

Em breve, terei resultados.

**Comment by Guaze** [comment]
O sistema está em uso contínuo por 1 hora.
Só uma vez que a nota foi emitida em contingência.
Então enviei novamente, sem fechar o sistema; funcionou. Neste caso, acho que foi timeout.

**Comment by robertorp** [comment]
Boa, deve ter sido timeout, porque do jeito que ta sua implementação, você teria que fechar o sistema e abrir novamente, igual o meu.

**Comment by marcosgerene** [comment]
**Errata:**
@Guaze  passei a manhã fora, agora que eu percebi que coloquei o destrutor no catch e nao no finally, mas a resposta do nosso amigo @rftd  já corrige e melhora minha informação.

**Comment by Guaze** [comment]
Estou agora aqui no comércio e encontrei somente duas notas em contingência. Com isso, foram 3 notas ao longo dia. Não tive que reiniciar a aplicação para fazer o reenvio. Logo, acredito, que o problema está solucionado.
Fazendo uma conta rápida aqui deve ter umas 50 vendas realizadas sem reiniciar a aplicação.

**Comment by Guaze** [comment]
@marcosgerene não foi necessário a solução indicada por @rftd . Foi só implementar corretamente o cache que não tive mais problemas.

**Comment by marcosgerene** [comment]
@Guaze excelente, por favor marque a issue como resolvida

**Comment by robertorp** [comment]
Somente para deixar a resolução registrada aqui

Ativamos o cache do zeus

O zeus na configuração de certificado digital (classe ConfiguracaoCertificado) setar um CacheId NÃO ESQUEÇAM DO CacheId. Ativar o ManterDadosEmCache = true

O cacheId tem que ser uníco e sempre o mesmo para cada certificado digital lembre-se disso!

Feito isso na aplicação do @Guaze  Funcionou perfeitamente, sem maiores problemas.
