### ISSUE TITLE
Implementar impressões em Crystal Reports

### ISSUE THREAD

**Issue by alexmurari** [ZeusAutomacao/DFe.NET#533]
Estava analisando a emissão de DANFE NFE/NFCE, etc., e me perguntei porque ao invés do Fast Reports (que é pago), e da versão nativa (que é demasiadamente complicada) nós não usamos o SAP Crystal Reports para implementar essas impressões.

Ele é [gratuito](https://blogs.sap.com/2010/04/19/crystal-reports-for-visual-studio-2010-licensing/) e já possuí [integragação com Visual Studio 2017](https://wiki.scn.sap.com/wiki/display/BOBJ/Crystal+Reports%2C+Developer+for+Visual+Studio+Downloads) e não é complicado de trabalhar. Só precisa do runtime instalado na máquina cliente que vai emitir os relatórios.

O que vocês acham? Compensa os esforço?

**Comment by robertorp** [comment]
Bom dia, nos temos as implementações FAST é Nativo mas não quer dizer que são padrão, temos somente estas pois foram oque contribuíram, se alguém surgir e implementar uma no Crystal Reports, nos aceitaremos a mesma também. Ai ficaria a critério de quem usar a lib escolher a que melhor lhe agrade.  Enfim oque quis dizer e que se tiver algum pull com cristal reports aceitaremos. 

Se você entende de Crystal reports e quiser fazer o pull, fique a vontade que vou aceitar feliz da vida =D

edit: Somente o crystal 2010 que é grátis?

**Comment by marcosgerene** [comment]
@MurariAlex a implementação em Fast dá-se unicamente por comodidade.

Eu uso o FastReports no meu dia a dia e não tinha nenhuma impressão do MDFe e do CTe do componente, o pessoal tinha que recorrer ao ACBr ou outra componente para imprimir, eu implementei na ferramenta que eu uso no dia a dia para minha empresa e compartilhei com a comunidade.

Se você usa o Crystal e se sente confortável para implementar e disponibilizar, será muito bem vindo

**Comment by alexmurari** [comment]
@robertorp Não, todos são gratuitos, é que só achei o artigo do 2010.

Adicionem a tag "melhoria" a este issue, por favor, assim que conseguir um tempo (não será tão em breve) eu implementarei em CR.

**Comment by fatechbr** [comment]
Galera, sou novo no github, desenvolvi uma solução nativa de de impressão de Dante e do relatório da nfc-e como faço para que meu projeto seja absorvido pelo seus? Ou seja unificar projeto?

**Comment by robertorp** [comment]
Por favor, vamos focar somente na issue que você criou vi que fez varias postagens em varias issues com o mesmo assunto https://github.com/ZeusAutomacao/DFe.NET/issues/624

**Comment by marcosgerene** [comment]
@MurariAlex 
A issue está aberta a muito tempo e com o FastReports agora sendo open source acredito que não faça mais sentido, em todo caso sinta-se a vontade para abrir outra issue caso sinta a necessidade.
