### ISSUE TITLE
Cálculos no Zeus

### ISSUE THREAD

**Issue by renanaragao** [ZeusAutomacao/DFe.NET#537]
Boa tarde,

Estou querendo utilizar o Zeus no meu projeto, e me pergunto o por que ele não faz os cálculos, já que ele possui todas as informações necessárias?

**Comment by alexmurari** [comment]
Fugiria do escopo do projeto.
A premissa deste projeto é manipular apenas a montagem/envio/impressão de documentos fiscais.

Incluir manipulação dos dados que compõem um documento fiscal é uma coisa completamente diferente e configuraria um sistema ERP/retaguarda/caixa/automação comercial.

Fora que calcular tributos já é complicado por si só, tendo em vista que cada estado tem sua lei e seus métodos de cálculos, alíquotas, etc..

**Comment by marcosgerene** [comment]
@renanaragao talvez o projeto do @robertorp possa te ajudar: https://github.com/AutomacaoNet/MotorTributarioNet

Quanto a implementar no componente a resposta do @MurariAlex acredito que basta.

Abraço

**Comment by renanaragao** [comment]
Entendi
