### ISSUE TITLE
Erro: "Object reference not set to an instance of an object" ao selecionar o certificado

### ISSUE THREAD

**Issue by solimarleo** [ZeusAutomacao/DFe.NET#538]
Olá Adenilton!
Acabamos de fazer a integração do ZeusNfe com nosso sistema e os testes nas estações de desenvolvimento funcionaram perfeitamente. Nas estações utilizamos um certificado A1. Quando atualizamos as dlls no servidor de um cliente para os testes finais, recebemos a mensagem de erro citada no título deste post. Para ter certeza se o problema era na integração ou em outra ponto, enviamos o NFe.AppTeste.exe com as dll´s e configurações para o servidor do cliente para teste. Ao realizar o teste, logo ao abrir o AppTeste aparece a mensagem: "There is an error in a XML document (1,1288)
![image](https://user-images.githubusercontent.com/30938799/30882310-eb2a3ffe-a2de-11e7-8af7-3a69ee7761f8.png)

Clicamos em OK e selecionamos o certificado (que no cliente é A3). Ao selecionar, recebemos a segunda mensagem de erro informada no título deste post: "Object reference not set to an instance of an object"
![image](https://user-images.githubusercontent.com/30938799/30882415-3a4c4a28-a2df-11e7-95c0-7b280e87eb44.png)

Tem alguma orientação que possa nos ajudar a solucionar o problema?

**Comment by robertorp** [comment]
preencheu as informações do app teste toda?
veja nosso wiki lá tem o basicão de por onde começar.

**Comment by solimarleo** [comment]
Opa Roberto! Já estamos usando o teste há algum tempo sem problemas. O problema ocorre só no cliente. Vou resumir o ocorrido pra reforçar o entendimento:
1 - Fizemos a integração do ZeusNFe com nosso sistema;
2 - Foram feitos diversos testes com o AppTeste e tb pelo nosso sistema já integrado, funcionando sem problemas;
3 - Os testes foram realizados em nossos notebooks de desenvolvimento;
4 - Para os teste utilizamos certificado A1;
5 - Nos testes no servidor do cliente foi utilizado certificado A3;
6 - O erro ocorre tanto no uso da dll pelo sistema quanto no AppTeste.
Se precisar de mais alguma informação é só falar.

**Comment by robertorp** [comment]
O app teste eu entendo que deve ter algum bug de referencia null , principalmente no emitente na hora do load , agora sua aplicação não sei..
Aqui quando passo por algo assim primeira coisa que faço e pegar o banco de dados do cliente, porque isso pode ser algo na sua aplicação, e não no zeus em si. Pois se vc não passou algo é logico que vai dar isso.

**Comment by solimarleo** [comment]
Hum... blz! Então o foco é procurar alguma referência que não esteja sendo passada. O que me estranha é que tanto no AppTeste quanto na nossa aplicação tb dá. Estou achando que pode ser algo relacionado ao certificado A3, talvez não esteja conseguindo carregar as informações. Vou fazer uns testes aqui e retorno. Por enquanto obrigado!
PS.: A propósito: tem alguém que dê suporte ao ZeusNFe? Contrato ou algo assim.

**Comment by robertorp** [comment]
@solimarleo 
podemos combinar algo se quiser somente add robertoalves18@hotmail.com ou mande um email para robertoalvespereira18@gmail.com

O app teste esta com uns paus na hora de carregar algumas informações se não me engano, sempre a primeira vez ele da alguma coisa relacionada ao emitente, mas essa parte de carregamento de informações em teoria e para ser individual de pessoa para pessoa ou aplicação para aplicação, por exemplo aqui na empresa nos carregamos tudo do nosso banco de dados, não salvamos arquivos.

**Comment by robertorp** [comment]
@solimarleo deu certo?

**Comment by solimarleo** [comment]
Ei  Roberto!

Deu certo sim. Conseguimos identificar o erro e ajustar o que precisávamos.
Estamos pensando em utilizar o Zeus pra nota 4.0.

Att.,

Solimar

Em 1 de out de 2017 8:28 PM, "Roberto Alves Pereira" <
notifications@github.com> escreveu:

@solimarleo <https://github.com/solimarleo> deu certo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/538#issuecomment-333414595>,
or mute the thread

**Comment by robertorp** [comment]
Opá, que bom! O Zeus hoje não tem suporte para NF-e 4.0 até o momento, se quiser fazer um pull fique a vontade, aceitarei ele rindo de alegria =) 
Agora existe esse pull que to desenvolvendo ainda, nele so falta fazer o layout novo , estava analisando e não são muitas mudanças assim. Mas, pode ser que demore um pouco ainda sair nesse pull meu. https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503  bom, uma vantagem é que esta ficando compativel com .net standard, e a desvantagem e que isso me fez demorar um pouco no desenvolvimento do mesmo, é também ouve gigantes mudanças nele. Se quiser fique a vontade para me ajudar a terminar ele logo  OU se preferir faça o mesmo aqui no master. 

edit: se um dia precisar de alguma consultoria estou disponível. 

Obrigado @solimarleo
