### ISSUE TITLE
Logomarca na NF-e dimensão e tamanho

### ISSUE THREAD

**Issue by ffranzes** [ZeusAutomacao/DFe.NET#54]
Primeiramente, gostaria de agradecer pela iniciativa do projeto. Estava pesquisando pela internet sobre a melhor dimensão para a logomarca que é inserida na DANFE, e ate o momento não encontrei nada sobre a dimensão da imagem na função que a carrega (confesso tambem que não pude me aprofundar muito em minha investigação na parte da tarde). Pesquisando pela internet encontrei o valor 339x114 http://www.gestortotal.com.br/emissor-nfe/como-colocar-logomarca-empresa-no-danfe-nfe , porem no manual da nfe não consta esses valores como pode ver aqui: http://www.projetoacbr.com.br/forum/topic/8333-quais-as-propor%C3%A7%C3%B5es-em-pixels-do-logo-da-danfe/ e ai surgiu a duvida. como você procedeu?
outra questão tambem é que parece que existe uma restrição para o tamanho que é de 100kb porem a mesma não encontrei no manual da NFe. sabe se existe?

**Comment by adeniltonbs** [comment]
Bom dia, quanto às suas dúvidas vamos lá.
P: Qual o tamanho que a logomarca deve ter no DANFE da NFCe?
R: O "Manual de Especificacoes Tecnicas do DANFE NFC e QRCode_Versao 3.3" não determina o tamanho da logo, apenas que sua presença no DANFE é opcional. Portanto cada um pode definir o tamanho que assim desejar.
O tamanho que coloquei foi com base no DANFE de algumas NFCes de outras empresas que vi. Mas se o tamanho atual está sendo um problema, podemos adicionar na biblioteca parâmetros para setar o tamanho em CM da logomarca.

Esse tamanho que você encontrou, é a exigência apenas daquele software em questão.

P: Existe um tamanho definido para a imagem da logo?
R: NÃO, pois a logo não vai no xml.
Mais uma vez essa limitação no tamanho é algo particular daquele software em questão.
