### ISSUE TITLE
Soap + .net core alguém conhece algum bom artigo?

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#542]
Bom estou querendo portar a lib para ela ficar funcionando tanto no .net framework é .net core , mas não entendo muito de .net core e o negocio pega somente na parte de transmissão, a unica coisa que não foi portado automático para .net core foi a parte de soap. 

Alguém sabe de algum bom artigo? Obrigado. 
Ps: perguntei por aqui porque talvez seja mais rápido eu aprender por aqui.

**Comment by orochasamuel** [comment]
Talvez o segundo link ajude, o primeiro apresenta apenas que a MS ainda não tinha planos de "portar" SOAP, agora já é possível trabalhar com várias libs.

PUBLICAÇÃO
28/02/2016    | https://stackoverflow.com/questions/35682728/soap-in-net-core
25/09/2017    | https://stackify.com/soap-net-core/

**Comment by robertorp** [comment]
ok, vlw, fechei o topico pq pensei que tava postando no lugar totalmente errado, desculpem hehe
mas estou vendo um curso já de soap a risca , nunca quis aprender a fundo isso. Agora vou aprender a fundo aproveitar a oportunidade, e implementar o máximo possível na unha.

**Comment by rftd** [comment]
https://github.com/danimaribeiro/NFSe.Net/blob/master/NFSE.Net/Implementacoes/Betha.cs

Um exemplo de soap na unha

**Comment by rftd** [comment]
tem o cliente WCF também ele foi portado para o .net core so não sei como está.

https://github.com/dotnet/wcf/releases
