### ISSUE TITLE
297 - Rejeicao: Assinatura difere do calculado

### ISSUE THREAD

**Issue by italodeverdade** [ZeusAutomacao/DFe.NET#543]
Estou com um problema ao enviar o meu XML para a autorização de forma Síncrona, quando eu faço o envio, recebo a resposta "297 - Rejeicao: Assinatura difere do calculo", pesquisei pelo possível problema e não consegui resolver o mesmo. Eis que tenho as possibilidades:
- Após assinado eu estou criando a QRCode e modificando o XML, li que modificar o xml pode alterar isso. pode ser isso?
- Eu já coloquei o XML no validador e está tudo correto, sem caracteres especiais "quebrando" o meu XML;
- Estou assinando com um certificado A1, mas que não tem cadastrado no estado (PI), apenas inscrição municipal. Só que se fosse isso, o erro seria outro (CNPJ/Contribuinte não cadastrado na UF).

Alguém pode me ajudar?

**Comment by guidi** [comment]
Bom dia, o XML não pode ser alterado depois de assinado, possivelmente este é o causador do erro de assinatura.

**Comment by robertorp** [comment]
Manda seu xml para analisar.
Se for NFC-e pode ser idtoken errado ou CSC errado.
O idToken deve ter 6 digitos ex: 000001 
já o CSC cada sefaz gera ele de tamanhos diferentes.

é lembre idToken para produção , serve somente para servidores de produção!
idToken para homologação, serve somente para servidores de homologação!

@guidi  Na NFC-e a tag infNFeSupl e adicionada depois de assinado o documento que contem informações do qrcode.

**Comment by italodeverdade** [comment]
Esse é o XML que tento enviar @robertorp 

[1-env-lot.xml.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1367094/1-env-lot.xml.zip)

**Comment by domicioam** [comment]
> Após assinado eu estou criando a QRCode e modificando o XML, li que modificar o xml pode alterar isso. pode ser isso?

Exato, a assinatura é calculada tendo o xml como base. Quando você envia a nota, a receita calcular a assinatura do lado deles também.

**Comment by robertorp** [comment]
Seguinte poste seu código de emissão da mesma. E as configurações quando são carregadas.

**Comment by robertorp** [comment]
Solucionou o problema?

**Comment by italodeverdade** [comment]
Infelizmente não, estava aguardando um cliente emitir ou certificado para realizar os testes. Estou tentando criar uma outra solução que faça a mesma assinatura agora.

**Comment by robertorp** [comment]
Passa o códio que você gera o XML, e envia para a sefaz

**Comment by italodeverdade** [comment]
Consegui resolver o problema. A questão era o arquivo XML em si, ele estava sendo utilizado com whitespaces na hora da assinatura e quando enviado estava sem. O problema foi corrigido aqui ;)
