### ISSUE TITLE
Versões do Zeus, bom como a maioria já sabem tem uma refatoração em andamento.

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#544]
Agora vem o problema, vou postar a situação atual da refatoração, basicamente falta refatorar o projeto NF-e ele todo praticamente, digamos que 90% dele ainda precisa ser refatorado. Como todos nos trabalhamos não temos 100% do tempo disponível para isso, exemplo eu tenho CT-e OS para implementar. 

Estou aqui achando que o caminho melhor no momento, e continuar com a refatoração, mas não agora talvez, mas teremos essa refatoração estou somente adiando ela. Eu acho que vou dar prioridade para a NF4 no projeto Zeus na versão atual. 

edit: irei adicionar somente NF4 no projeto atual, quem quiser CT-e OS pegue a refatoração.

Oque acham?

**Comment by robertorp** [comment]
Refatoração em curso aqui https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503

**Comment by leandrossantos** [comment]
@robertorp concordo você, primeiro acertar o projeto com a NFe4 e depois que estiver tudo OK refatorar ela.

Tem meu apoio.

**Comment by vander911** [comment]
Não sou usuário Zeus ainda, apenas acompanho as discussões para ficar bem iterado quando começar a fazer uso.

Acho interessante continuar com a refatoração. Alias, se jogá-la sempre pra frente, pode entrar num ciclo vicioso (pelo menos comigo às vezes acaba ficando assim hehehe).

Apenas uma sugestão: Pelo que entendi no Skype, você disse que a previsão de finalização da refatoração seja até fim de ano, certo?
Se for isso mesmo, eu diria que nem a NF4 teria grande urgência no projeto atual, tendo em vista que a obrigatoriedade entrará apenas em Abril...
Corrija-me se estiver equivocado.

**Comment by rtt3r** [comment]
Essa refatoração possui alguma especificação? Gostaria de colaborar, pois acho que isso tem grande importância.
