### ISSUE TITLE
Duvida tag <infCpl> NFe/NFCe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#547]
É possível inserir quebra de linha nesse campo? quando usávamos uma aplicação em delphi com acbr era possível fazer isso mas no zeus sempre que tento da rejeição.

**Comment by marcosgerene** [comment]
@ThalisonSantos anexe aqui um xml que você utiliza quebra de linha para que possamos analisar em conjunto.

Todavia, até aonde vai meu conhecimento o campo não permite quebra de linha isso é regra dos schemas não do componente, logo o ACBr também segue ela, se ele permite pular linha deve ter algum tratamento na impressão... mas posso estar enganado, estou te falando sem ter o manual em mãos para consultar.

**Comment by robertorp** [comment]
Não pode ter quebra de linhas, o ACBr tem algum tratamento com certeza. Como disse @marcosgerene pega um xml para nos estarmos analisando e vemos oque ele faz. @ThalisonSantos

**Comment by ThalisonSantos** [comment]
verifiquei no xml gerado pelo acbr e realmente esta continuo mas no danfe sai quebrado esta em anexo danfe e o xml zipado

<infAdic>
<infCpl>DOCUMENTO EMITIDO POR ME OU EPP OPTANTE PELO SIMPLES NACIONAL;SUBSTITUICAO TRIBUTARIA CONF. DECRETO N 28.816 DE 10/01/2006 E DECRETO N 28.247/2005;Portador : CARTEIRA;Num Ped : 1299;Cod Vend : 1;;; ;PEDIDO: 8486 OBRA:14 CONNECTION WORK AND LIFE;LOCAL DE ENTREGA: AV. GUSTAVO PAIVA,S/N- CRUZ DAS ALMAS MACEIO-AL.</infCpl>
</infAdic>

[DANFEACBR.pdf](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1360109/DANFEACBR.pdf)
[27160835741859000136550010000012731000012730-nfe.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1360116/27160835741859000136550010000012731000012730-nfe.zip)

**Comment by robertorp** [comment]
";" não aparecem no danfe ele define a quebra de linha na impressão

edit: adicionar label de melhoria
edit2: se quiser pode fazer um pull hehe, negocio agora é aguardar os pull =D, lembrando que o mesmo devera ser feito nos outros documentos ou seja irei fechar essa issue quando tiver em todos documentos. Obrigado

**Comment by ThalisonSantos** [comment]
ok valeu

**Comment by marcosgerene** [comment]
@ThalisonSantos a melhoria é interessante, vou marcar aqui na minha to do list para fazer isto na impressão da NFe.

**Comment by marcosgerene** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/546/commits/e482388fa7245612bc8251eb275ef4dbca111d1e

**Comment by ThalisonSantos** [comment]
pessoal obrigado pelo suporte vocês são 10!!!

**Comment by marcosgerene** [comment]
@ThalisonSantos por favor feche a issue

**Comment by JoaoSpagnol** [comment]
bom dia meus amigos esta solução foi implementada ?

**Comment by ThalisonSantos** [comment]
@JoaoSpagnol sim, no danfe em fast colocando ; no texto considera um quebra de linha
