### ISSUE TITLE
Erro Impressão IPI

### ISSUE THREAD

**Issue by guimoraesal** [ZeusAutomacao/DFe.NET#548]
Na impressão da NF-e, quando temos produtos com IPI, caso o último item não tenha destaque do IPI (IPINT), nenhum dos items destacam o tributo na impressão, alguém já verificou isto?

Exemplo:

Item 1 - Produto x - IPI 5%
Item 2 - Produto y - IPI 0

Na impressão os dois saem 0, mas no xml está normal. #

**Comment by marcosgerene** [comment]
Anexe o xml à issue, sem ele não é possível sequer iniciar o teste

**Comment by guimoraesal** [comment]
[35171000221619000126550010000006051100830600.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1363632/35171000221619000126550010000006051100830600.zip)


Segue anexo.
Estou anexando também uma imagem, para que possam entender melhor o problema.

![impresso](https://user-images.githubusercontent.com/32579159/31293366-57b14a98-aaad-11e7-8dfe-191e4e61fea7.jpg)

**Comment by guimoraesal** [comment]
Pessoal, encontrei uma solução para o meu problema.

Bom, acontece que o fastreport não conseguia interpretar o tipo do objeto, pois o ultimo tipo era IPINT, ou seja, não destacava os campos necessários (caia direto na exception). Pois bem, o que tive de fazer foi alterar na impressão para identificar o tipo do objeto e destacar os campos.

![code](https://user-images.githubusercontent.com/32579159/31340512-c391c32e-acdc-11e7-961e-3409e6d364d7.jpg)

`try { 
        IPITrib ipiTrib = (IPITrib)Report.GetColumnValue("NFe.NFe.infNFe.det.imposto.IPI.TipoIPI");

        Text154.Text = FormatNumber(ipiTrib.vIPI,2);
        Text165.Text = FormatNumber(ipiTrib.pIPI,2);
      } 
      catch {
        Text154.Text = FormatNumber(0,2);
        Text165.Text = FormatNumber(0,2);       
      };`

O que fiz no trecho acima foi verificar se o objeto é do tipo IPITrib, caso contrário uma exception será lançada. Não fiz mais nenhum tratamento, apenas atribui o valor 0 para os textbox quando o tipo não for IPITrib.

Resultado.

![erro](https://user-images.githubusercontent.com/32579159/31341524-1672da4e-ace0-11e7-8b50-b1a5be9e6e7b.jpg)

**Comment by marcosgerene** [comment]
@guimoraesal Boa tarde, me desculpe, esses dias foi pauleira, tive que implementar promoção de produtos pra mercado e carga para balança de sexta pra segunda-feira.

Bem, mande um pull request com suas alterações par que possamos testar.

Sobre o IPI acredito que poucas pessoas usem ou até mesmo ninguém use,por isso o erro nunca foi reportado. Eu mesmo não tenho clientes do tipo industria, e as que tenho são Simples nacional, ou seja, ninguém dos meus clientes tem IPI.

Abraço e obrigado

**Comment by guimoraesal** [comment]
@marcosgerene 

Pois é, talvez ninguém tenha percebido o problema devido ao tipo da empresa que atendem, eu atendo muita indústria, mas mesmo assim o erro foi reportado por um cliente da área de varejo, que precisava fazer uma nota de devolução e necessitava destacar o IPI na nota.

Comecei a utilizar o projeto a alguns meses, mas já trabalho com NF-e desde o início, utilizo somente a parte da impressão. De qualquer forma, fica aqui a minha contribuição para este problema, visto que pode acontecer com qualquer um, já que o destaque não é só obrigatório para industria (dependendo do caso).

Um abraço a todos.

obs: Estou anexando o frx da impressão para que possam analisar. Fiz muitas alterações para adequar as minhas necessidades, mas que podem suprir as necessidades de todos.

[NFeRetrato.zip](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1369236/NFeRetrato.zip)

**Comment by marcosgerene** [comment]
@guimoraesal pode me detalhar o que foi alterado?

**Comment by guimoraesal** [comment]
Realizei alterações na impressão, visando melhorar a estética final do impresso (ajuste de altura e largura das colunas, a fim de deixar todas elas uniformes). 

Adicionei no canhoto os dados do destinatário, valor da nota, emissão.

Neste impresso removi a parte do ISSQN, que no meu caso, não se encaixa para nenhuma aplicação, visto que a maioria das cidades possuem um sistema próprio de emissão da nota fiscal de serviço.

Corrigi algumas questões no valor unitário do produto, onde o valor saia sempre com duas casas decimais. Fiz de forma que ele possa identificar a quantidade de casas que o campo possui (que podem chegar a 10).

Correção da descrição do nome do produto, que aceita nomes maiores, além das observações do produto, que não era informado na impressão (realizei a união entre as informações dos dois campos, dando uma quebra de linha para a observação).

Removi a formatação em R$ dos campos dos produtos, para ter mais espaço, quando os valores são muito grandes.

Removi o KG do peso bruto e peso líquido, pois pode ser Toneladas ou qualquer outra unidade de transporte, e isto influencia muito quando uma fiscalização realiza uma parada a um transportador.

Correção do IPI (destacado nesta issue).

Anexo: a diferença entre os modelos.

[Modelo que disponibilizei](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1369365/Teste.2.pdf)

[Modelo Original](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/1369366/Teste.pdf)

Estas alterações que realizei são apenas algumas mudanças nas quais eu já fazia uso com outro modelo de impressão.

**Comment by marcosgerene** [comment]
No teste 2 some a chave, e sai a marcação "NFe sem autorização bla bla bla"... 

Eu baixei seu xml e peguei uma extension disponibilizada pelo @rftd, vou ajustar o ipi pra corrigir o bug, depois vemos com mais calma as outras alterações

**Comment by guimoraesal** [comment]
Sim, não tem chave pois não é um XML autorizado, e sim um XML apenas gerado para teste (também estou com um modelo mais antigo).

Sobre as outras alterações, é como disse anteriormente, fiz elas para sanar as minhas necessidades, mas é importante que analisem elas com mais calma para que possam identificar se ela será útil para todos.

Um abraço.

**Comment by marcosgerene** [comment]
Obrigado pela colaboração @guimoraesal, mesmo que suas alterações não sejam utilizadas o simples fato de apontar um bug já faz o projeto crescer.

Abraço

**Comment by marcosgerene** [comment]
Bom dia @guimoraesal,

Olhando rapidamente seu projeto eu encontrei algumas inconsistências (como o código de barras) e acredito que a melhor abordagem para a impressão dos campos referentes ao ISSQN deva ser opcional e não removida de vez.

Como você mesmo disse você ajustou para suas necessidades, mas não atenderiam as de outros que ainda usam o ISSQN por exemplo.

Obrigado por reportar o bug, mandei um pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/550 somente para corrigir o bug reportado.

Att, Marcos

PS: Eu não sou o "dono" do projeto, logo você também pode mandar um pull com suas alterações, eu só mandei um corrigindo o bug porque também tenho interesse no funcionamento do Danfe em Fast

**Comment by guimoraesal** [comment]
Bom dia @marcosgerene 

Perfeito, de fato não podemos remover o ISSQN do impresso, visto que alguém ainda pode usar, mas o ideal é que ele fosse opcional, pois alguns estados podem exigir que o mesmo não seja destacado na impressão. 

Não vou realizar um pull com as alterações que fiz, pois na minha visão, elas foram "agressivas" e podem  influenciar no contexto geral de todos.

Agora o que me deixou preocupado foi a questão da inconsistências do código de barras que você apontou, o que estaria errado?

Abraços.

**Comment by marcosgerene** [comment]
@guimoraesal o danfe que voce mandou via pdf esta sem código de barras.

Outra coisa, eu por exemplo mostro uma pré-visualização antes de transmitir a nfe pro meu cliente confirmar os dados ali aonde fica o protocolo existe a mensagem "NFe sem autorização pela sefaz..." para ele não imprimir isto antes de transmitir, na sua versão não tinha isso.

Não cheguei a ver se sua versão está implementando a quebra de linha, que foi implementada junto com a mensagem citada acima...

Eu acredito que você tenha usado como base para alterar uma versão mais antiga da atual...

Abraço, Marcos

**Comment by guimoraesal** [comment]
@marcosgerene 
Acho que quando você está se referindo ao código de barras é ao protocolo de autorização de uso, que de fato está em branco no meu caso. Vou fazer a implementação para deixar a informação "NFe sem autorização de uso pela SEFAZ". 

No meu software deixo opcional a pré-visualização da NF-e, mas destaco no campo reservado ao fisco como homologação, a fim de invalidar a impressão, caso alguém tente utilizar para outros fins (gero um xml em homologação para realizar a pré-visualização).

De fato, utilizei uma versão mais antiga, e fui ajustando para chegar neste modelo que postei.
