### ISSUE TITLE
Escolha de certificado

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#55]
Adenilton, boa noite,

Como posso fazer para que na minha aplicação não apareça a janela de escolha de certificado, cada vez que emito uma NFC-E?

Obrigado,
Roberto.

**Comment by adeniltonbs** [comment]
Você deve estar chamando o método CertificadoDigital.ObterDoRepositorio(). Note na classe CertificadoDigital o comentário para este método: "Exibe a lista de certificados instalados no PC e devolve o certificado selecionado".

Verifique a aplicação de demonstração, pois esse método acima deve ser usado apenas no momento em que for configurar o certificado a ser usado na aplicação.

Para consumir os serviços, basta armazenar o serial do certificado, e opcionalmente a senha (em se tratando de A3), nas propriedades da classe singleton ConfiguracaoServico.Instancia.ConfiguracaoCertificado.

Espero ter ajudado.
