### ISSUE TITLE
Erro ao transmitir NF

### ISSUE THREAD

**Issue by WilliamSantosSilva** [ZeusAutomacao/DFe.NET#551]
Boa tarde 

Atualmente estou tento problema ao transmitir a NF de importação, ele informa que a UF do destinatário está errado e não é do Brasil, e que a versão que uso "3.1" está diferente e que deveria ser "3.2".

Alguem teve esse problema e poderia me ajudar nisso ?

**Comment by robertorp** [comment]
Poste mais detalhes do erro, mostre ele para nos e se possível poste um pouco de código se você achar que e necessário para melhor analise.

**Comment by WilliamSantosSilva** [comment]
Esse foi o erro que está dando.

Sendo que como UF está EX que quer dizer exterior, esse problema começou do nada.

![image](https://user-images.githubusercontent.com/16545379/31406791-fa5dc752-add8-11e7-8697-5a5772b10313.png)

**Comment by marcosgerene** [comment]
@WilliamSantosSilva não entendi muito bem, você gerou o xml com o componente e tentou emitir pelo emissor gratuito, é isso?

**Comment by WilliamSantosSilva** [comment]
Sim

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by robertorp** [comment]
Poste o xml para nos analisar.

**Comment by marcosgerene** [comment]
@WilliamSantosSilva mas porque está emitindo pelo emissor gratuito ao invés de consumir o webservice com o componente?

**Comment by WilliamSantosSilva** [comment]
Pq estou tento problema de arredondamento de valor

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by marcosgerene** [comment]
O arredondamento ocorre antes mesmo de criar o XML, voce teria que corrigir o valor no emissor gratuito.

O arredondamento só  acontece algo tiver que ser arredondado, se você passar o valor já truncado/arredondado de forma diferente o componente não vai "desarredondar/destruncar".

Ex: 1,554 * 22,90 = 35,5866, se você passar este valor "35,5866" para o componente ele vai arredondar para 35,59, agora se você passar 35,58 já truncado o arredondamento não vai ocorrer.

**Comment by WilliamSantosSilva** [comment]
Manjei, mas nesse caso ele teria que manter esse valor.

Nota de importação é chata e não aceita arredondamento

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by marcosgerene** [comment]
@WilliamSantosSilva é só você passar o valor que deseja, leia com atenção o que eu disse:

>O arredondamento só acontece algo tiver que ser arredondado, se você passar o valor já truncado/arredondado de forma diferente o componente não vai "desarredondar/destruncar".
>
>Ex: 1,554 * 22,90 = 35,5866, se você passar este valor "35,5866" para o componente ele vai arredondar para 35,59, agora se você passar 35,58 já truncado o arredondamento não vai ocorrer.

**Comment by robertorp** [comment]
@WilliamSantosSilva  tudo bom? 

Resolveu o problema?
