### ISSUE TITLE
A partir do dia 16/10/2017 vou aceitar esse pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/539

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#552]
Bom se você não tem tratamento para para os números decimais da NF-e/NFC-e 
Trate de fazer isso a biblioteca não fará o suporte para arrendondamento/truncamento mais. (Nunca teve truncamento)

Enfim isso e algo pessoal de cada aplicação. 
Por mais que NT's dizem para arrendondar quem deve fazer isso e você dono do AC. 
Futuramente poderemos discutir mais abertamente isso, quando a biblioteca crescer mais e a comunidade da mesma.

Obrigado pela atenção.

**Comment by marcosgerene** [comment]
@robertorp seria interessante listar aqui quais os campos que eram arredondados e não serão mais para facilitar a vida de quem tiver que alterar o software, a unica forma que vi ate agora seria analisando o pull enviado.

**Comment by marcosgerene** [comment]
Falei besteira no tópico anterior, acredito que devemos repensar nisso...

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/536#issuecomment-335763771
