### ISSUE TITLE
[HELP] A chave de assinatura não está carregada.

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#553]
Olá a todos,

Estou tentando emitir uma NFC-e no ambiente de Homologação da SEFAZ/GO e me deparei com a seguinte mensagem: "A chave de assinatura não está carregada."

![image](https://user-images.githubusercontent.com/15462690/31438930-a122bd54-ae60-11e7-8f69-f8ffa8636329.png)

@robertorp você também utiliza a lib para consumir os serviços da SEFAZ/GO neh? Já passou por isso?

Agradeço a atenção.

PS: Já tentei alternar entre SSL/TLS, acredito que seja relativo à assinatura do documento. Mas essa expressão em específico não consta em nenhuma parte do código.

**Comment by marcosgerene** [comment]
Bom dia @samuelrochaoliveira 

Posta um print também da aba certificado, por favor.

Ou melhor, confere se o certificado foi preenchido da forma correta e se o mesmo esta instalado (e operacional se for A3).

**Comment by orochasamuel** [comment]
Descobri, tentei acessar direto no site da SEFAZ/GO, o certificado não aparecia na listagem.

Fiz a instalação da nova cadeira, citada no issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/480 pelo @robertorp, reiniciei o VS e passou dessa parte. Agora me deparei com outra situação, irei abrir outra issue para tratar.

@marcosgerene conferi tudo certinho, mas aqui vai o print.

![image](https://user-images.githubusercontent.com/15462690/31439969-9b2492f2-ae64-11e7-9a73-1254c29e8072.png)

Obrigado.
