### ISSUE TITLE
[DÚVIDA] Posso NÃO usar Mensagem Compactada?

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#555]
Alguém sabe dizer caso a aplicação NÃO envie as notas de forma compacta se pode ocorrer algum tipo de penalidade? Como um delay para envio ou bloqueio mesmo e ter que esperar determinado tempo para consumir novamente os serviços?

Na issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/554 relatei que consegui enviar a NFCe somente quando não estava compactada a mensagem. 

Entendo que o recomendado seja usar de forma compacta mas, no meu cenário o volume esperado para emissões diárias é algo em torno de 350 a 900 documentos, claro que o tamanho de cada documento varia todavia o máximo de produtos por documento será de 15 a 20, não passará disso, pelo menos por enquanto.

Agradeço a atenção.

**Comment by robertorp** [comment]
Bom, em goiás não funciona. Não sei porque, nunca peguei para pesquisar e nem nada. Sou de goiás. Aqui envio sem compactar, na verdade em todos estados que atuo ate hoje, enviamos sem compactar. Nunca sofremos penalidades.

**Comment by orochasamuel** [comment]
Obrigado pela pronta resposta @robertorp.
