### ISSUE TITLE
CTeOS

### ISSUE THREAD

**Issue by mvtaraujo** [ZeusAutomacao/DFe.NET#556]
Bom dia pessoal, sou novo aqui no projeto e gostaria de saber se alguém já está trabalhando com o CTeOS.

Tenho um cliente que trabalha com transporte de passageiros no estado de MG e o mesmo está obrigado a utilizar o CTeOS a partir do dia 02/10/2017. 

Só queria saber se já está totalmente desenvolvido aqui pelo Zeus.

Obrigado

**Comment by robertorp** [comment]
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/503 neste branch esta implementado já. E funciona com .net standard e .net 4.5

edit: estou utilizando ele já. Para CT-e.

**Comment by mvtaraujo** [comment]
@robertorp obrigado pelo retorno. Desculpe minha estupidez, como eu disse antes, sou novo por aqui. Não só no projeto Zeus como no GitHub também. 

Quando você diz que essa branch ja esta implementado, pra eu utilizar ela especificamente tem algum caminho, ou eu baixando o ultimo commit ela já está incluída?

"edit: estou utilizando ele já. Para CT-e." 
     pra CT-e normal também já estou utilizando, pra CTeOS você já utiliza tb?

**Comment by robertorp** [comment]
E somente baixar desse link https://github.com/robertorp/Zeus.Net.NFe.NFCe/tree/Refatoracao_Hard mandar compilar o projeto DFe 

la tem o appTeste para CT-e e inclusive tem uma emissão de CT-eOS teste 

observação1: Não temos disponivel impressão de CT-e OS! no caso aconselho que você implemente ou utilize o framework ACBR Monitor para impressão.
observação2: Existem dois projetos DFe e DFeStandard a diferença e que o DFe e para .net framework e o outro como o proprio nome diz para Standard.

**Comment by mvtaraujo** [comment]
Ótimo, vou testar aqui. Muito Obrigado

**Comment by mvtaraujo** [comment]
Deu tudo certo @robertorp . Muito obrigado pela ajuda. Excelente trabalho.
