### ISSUE TITLE
Problemas com a DLL FastReport

### ISSUE THREAD

**Issue by allanRnobre** [ZeusAutomacao/DFe.NET#557]
Oi, estou tentando fazer a impressão do Danfe e fica me acusando o seguinte erro:
System.IO.FileNotFoundException: 'Não foi possível carregar arquivo ou assembly 'FastReport, Version=2017.1.17.0, Culture=neutral, PublicKeyToken=db7e5ce63278458c' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.'

não consigo encontrar essa versão do FastReport como faço?? Alguém teria o link para me passar?

**Comment by marcosgerene** [comment]
Este é um problema do componente que já entramos em discussão algumas vezes.

O componente não deveria referenciar a dll ou ate mesmo subir elas, deveria ser algo como faz o ACBr.Net.Sat, ele pede referencia mas sem especificar qual dll em si, no caso cada um usa sua versão.


Respondendo sua pergunta: a unica solução QUE EU CONHEÇO é você baixar o fonte, ir nas referencias do projeto remover a referencia aos dlls, apagar os dlls da pasta do projeto e referenciar as dlls que voce usa manualmente.

----

Vou enviar um pull que faça o mesmo que faz no ACBr.Net.Sat para que os moderadores possam analisar.

**Comment by robertorp** [comment]
Retira as dll do Zeus e coloque as suas dll.

**Comment by marcosgerene** [comment]
@robertorp 
Tem que excluir da pasta dll também além de referenciar as dele, aqui só dá certo assim

**Comment by robertorp** [comment]
Caso não esteja resolvido favor abrir novamente a issue.

**Comment by pedrosegolin** [comment]
Olá, boa tarde! Estou enfrentando um problema muito parecido se não igual.
Tenho minhas dlls e substitui para remover a marca d'agua, No AppTeste do Danfe funciona normalmente, porém em minha aplicação tenho o erro:

Não foi possível carregar arquivo ou assembly 'FastReport' ou uma de suas dependências. Não foi possível verificar a assinatura de nome forte. Talvez o assembly tenha sido violado ou assinado com atraso, porém não totalmente assinado com a chave privada correta. (Exceção de HRESULT: 0x80131045)

**Comment by rftd** [comment]
Este erro é quando a dll foi crackeada e perdeu sua signature.

**Comment by pedrosegolin** [comment]
@rftd Obrigado pela informação. Alguém possui alguma DLL compatível com a versão atual para disponibilizar?

**Comment by marcosgerene** [comment]
@pedrosegolin amigo, as dlls do fast reports não são baratas. A versão mais simples (somente desktop) custam na casa de US$399. Duvido muito que alguém esteja disposto a disponibilizar isso sem custo.

E se você procura uma "versão alternativa" acredito que não seja este o local adequado para pedir, acredito que quem vive de vender software não tem interesse algum em disponibilizar software "crakeado".

**Comment by vigomarcelo** [comment]
1.clique direito sobre projeto FastReport no Visual Studio
2.selecione Propriedades no menu de contexto
3.vá para a guia Assinatura
4.desmarque Assinar o assembly

**Comment by PauloZier** [comment]
Fala pessoal blz ?

Estou com esse problema aqui tbm, eu devo excluir as dlls do projeto mas como repor as mesmas de maneira correta ?

**Comment by marcosgerene** [comment]
@PauloZier remova as do projeto, remova as referencias à elas e referencie as suas.

**Comment by PauloZier** [comment]
Olá tudo bem?

Estou trabalhando em um projeto aonde precisamos utilizar o zeus, tem
alguma documentação ou algo específico para que eu possa estudar sobre?

Desde já muito obrigado.

**Comment by marcosgerene** [comment]
@PauloZier para novas perguntas abra uma issue
