### ISSUE TITLE
[FEATURE] Visualização em HTML

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#558]
Olá pessoal,

Alguém já cogitou fazer a visualização da NF-e/NFC-e em HTML? Caso não, eu tenho interesse em fazê-lo.

@adeniltonbs, você e o @robertorp juntamente com o @marcosgerene são os que vejo tendo maior participação no projeto, algum de vocês tem tal necessidade ou pretendem incluir no projeto?

Agradeço a atenção.

**Comment by alexsandro-xpt** [comment]
Seria bem interessante isto mesmo.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira eu particularmente não uso hoje, minha aplicação que usa o NFe roda somente em ambiente desktop, nenhuma das minhas aplicações web usam (ainda) nfe.

Entretanto como disse o amigo @alexsandro-xpt é bem interessante isso, acredito que só tem a contribuir e a longo prazo eu até usaria em algum projeto em asp.net mvc que exigisse NFe.

Tem meu apoio e estou disposto a ajudar no que for possível dentro de minhas limitações

**Comment by orochasamuel** [comment]
Perfeito!!
Irei providenciar e retorno com uma resposta, @marcosgerene adicione um label para feature ou enhancement e me vincule a este issue, por favor.

PS: Vou fechar o issue e reabro na resposta.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira eu não sou collaborator apenas contributor, não tenho acesso a estes recursos, acredito que o @robertorp possa fazer isto pra gente.

Abraço
