### ISSUE TITLE
XML de cancelamento

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#56]
Boa Noite,

Estou precisando salvar o XML de cancelamento da NFe, porem estou em duvida de como fazer isso.

O Xml que salvo é o que envio para realizar o cancelamento, correto?

Caso esteja correto, como faço para adicionar a Tag <retEvento> no fim do XML?

Obrigado pela atenção, o projeto é fantástico... Parabéns...

**Comment by willianas1** [comment]
A Tag que me refiro é a "retEvento".

**Comment by adeniltonbs** [comment]
O que é importante para você obter e armazenar no caso do evento de cancelamento é o xml do grupo procEventoNFe, pois ele já contém o próprio evento que foi enviado na tag <evento> e o retorno deste na tag <retEvento>.

Note na aplicação de demonstração, no procedimento BtnCancelarNFe_Click da classe MainWindow, que o cancelamento é feito utilizando o método servicoNFe.RecepcaoEventoCancelamento, cujo retorno é um objeto do tipo RetornoRecepcaoEvento que contém um objeto do tipo retEnvEvento e uma lista de procEventoNFe (para os casos onde mais de um evento tenha sido enviado num único lote).

**Comment by adeniltonbs** [comment]
Exemplo para obter o xml do retorno do evento (para o caso de ter enviado um único evento no lote):

`````` cs
var retornoCancelamento = servicoNFe.RecepcaoEventoCancelamento(1 /*Id do Lote*/, sequenciaEvento, protocolo, chave, justificativa, cpfcnpj);

var retEventoRetorno = retornoCancelamento.Retorno.retEvento.FirstOrDefault();
if (retEventoRetorno == null)
    throw new Exception("Não foi possível obter o retorno do serviço de Cancelamento!");

if (retEventoRetorno.infEvento.cStat != 135) //Evento vinculado à nfe
    throw new Exception(retEventoRetorno.infEvento.xMotivo);

var xml = retornoCancelamento.ProcEventosNFe.FirstOrDefault().ObterXmlString();
```cs
``````

**Comment by willianas1** [comment]
Funcionou perfeitamente, obrigado.
