### ISSUE TITLE
Separar projeto de impressão 3rd

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#560]
Boa tarde a todos,

O Fast Reports é pago, eu tenho a versão X, o Zé a Y, o João a Z. Se a gente fica mantendo uma versão da dll no projeto a única forma de não ter conflitos é cada um baixar o fonte e ficar apagando a dll da pasta e  trocar a referencia na mão.

Isto já causou problemas para mim e vem causando pra mais gente(https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/557).

Eu mandei um pull (https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/559) somente removendo as dlls, mas acredito que a solução seria separar a impressão de terceiros do projeto "principal", ou seja, deixar aqui somente as impressões que forem NATIVAS (hoje somente o NFCe tem essa opção) e acredito que teremos algo para o NFe também (https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/558).

Att, Marcos

**Comment by fatechbr** [comment]
Galera, sou novo no github, desenvolvi uma solução nativa de de impressão de Dante e do relatório da nfc-e como faço para que meu projeto seja absorvido pelo seus? Ou seja unificar projeto?
