### ISSUE TITLE
Puxão de orelha

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#561]
Bom dia a todos,

Em um dos PRs anteriores foi implantado o certificado via array de bytes.

Bem, até ai tudo bem, mas qual implementou mexeu no enum e ao invés de adicionar no final fez isto:
![image](https://user-images.githubusercontent.com/15945003/31716779-19f64dc2-b3e8-11e7-9718-ff1f66eb1830.png)

Ou seja, mudou o numeral do A3 de 2 para 3, algo que não deveria ser feito pois pode haver mais gente (como foi meu caso) que estava convertendo dois arrays usando o integer correspondente.

Peço aos colaboradores que façam o possível para não quebrar a compatibilidade com códigos anteriores, ou se quebrarem avisar que isto será feito, pois se eu não mexo no meu software e atualizar o componente causa uma quebra no funcionamento isto é danoso.

Att, Marcos

**Comment by robertorp** [comment]
Correção aplicada no pull https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/pull/562 

Bom aos que utilizem nuget não precisam se preocupar não tem esses commits o nuget esta 100% OK.
