### ISSUE TITLE
[DÚVIDA] NFC-e em Contigência

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#563]
Olá pessoal,

Alguém já passou por uma situação onde a NFC-e foi registrada como Contingência e não foi transmitida no prazo de 24 horas (em Goiás são 24hrs, para outros estados cada um regulamenta da forma que quiser), o cliente teve que pedir autorização na SEFAZ ou conseguiu transmitir normalmente?

O caso é o seguinte, uma NFC-e que foi registrada em 02/10/2017 e o cliente não transmitiu, só agora ele notou. E quando tento transmitir a mensagem retornada é "Rejeição: NFC-e com Data-Hora de emissão atrasada.".

A SEFAZ de minha cidade já fechou e não consegui essa resposta ainda. @robertorp já passou por isso?

Agradeço a atenção.
Att,
Samuel Oliveira

**Comment by leandrossantos** [comment]
@samuelrochaoliveira acredito que possa ser por causa do horário de verão, pois o xml gerado deve esta com -03:00 e agora com o horário de verão tem que esta -02:00

**Comment by robertorp** [comment]
@samuelrochaoliveira  Seguinte, moro em goiás mas quando lançaram a nfc-e aqui em goiás eu liguei lá justamente com essa duvida. 
Me responderam assim: Procure a delegacia fiscal mais próxima.

Oque recomendo e, ligar na Sefaz, muito provavelmente eles vão dizer para procurar a delegacia fiscal, ir ate a mesma e solucionar juntamente com eles. No caso a questão é, o seu cliente tem que correr atrás disso. Infelizmente a solução e essa.

Sobre o horário de verão esta dando problemas mesmo mas, isso diverge porque o servidor da Sefaz pode estar em horário diferente do estado local, como o windows atualiza sozinho a hora, se estiver uma hora para frente do servidor da Sefaz não ira emitir.  Mas não e o caso do @samuelrochaoliveira  pois a mesma foi emitida 02/10/2017.

**Comment by adrbarros** [comment]
@samuelrochaoliveira Primeiramente, já ocorreu esse erro comigo, quando percebi não tinha setados o TipoEmissao = 9 e as tags da Contingência dhCont e xJust se não me engano. Realmente o prazo é 24h para ser considerado como Autorizado o uso da NFe, quando passar de 24h vem considerado como Autorizado o uso da NFe, fora do prazo.

Já auxiliei clientes na envio das contingências de NFCe com mais de 30 dias nos Estados do PA e AP.
Tenho também clientes no SP (utilizando NFCe e SAT),  MA, RN, PE, e em todos esses estados já enviaram as contingências após 24h. Até agora com NFCe não tive problemas com emissões e evio.
