### ISSUE TITLE
Erro envio NFCe

### ISSUE THREAD

**Issue by reislanes** [ZeusAutomacao/DFe.NET#564]
Estou fazendo teste de implementação em um sistema da empresa. Quando tento fazer o envio, recebo o seguinte erro de retorno:

System.Exception: Serviço NFeAutorizacao, versão 3.10, não disponível para a UF PA, no ambiente de Produção para emissão tipo Normal, documento: !

Se eu gerar o xml e usar a opção Carregar Xml e enviar no Aplicativo de teste NFe ele faz o envio normalmente. 

Alguma luz sobre este problema?

No meu sistema estou usando o pacote do nuget

**Comment by robertorp** [comment]
Cole o código onde você cria as configurações do Zeus aqui para nos analisar.

**Comment by reislanes** [comment]
Private Sub Config()
        confNfe.CfgServico.DiretorioSchemas = Application.StartupPath & "\Schemas"
        confNfe.CfgServico.Certificado = carrega_conf_certificado()
        confNfe.CfgServico.cUF = Estado.PA
        confNfe.CfgServico.ProtocoloDeSeguranca = Net.SecurityProtocolType.Tls
        confNfe.CfgServico.tpAmb = Informacoes.Identificacao.Tipos.TipoAmbiente.taProducao
        confNfe.CfgServico.tpEmis = TipoEmissao.teNormal
        confNfe.CfgServico.VersaoNFeAutorizacao = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeConsultaCadastro = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeConsultaDest = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeConsultaProtocolo = VersaoServico.ve310
        confNfe.CfgServico.VersaoNFeDistribuicaoDFe = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeDownloadNF = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeInutilizacao = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeRecepcao = VersaoServico.ve310
        confNfe.CfgServico.VersaoNFeRetAutorizacao = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeRetRecepcao = VersaoServico.ve310
        confNfe.CfgServico.VersaoNfeStatusServico = VersaoServico.ve310
        confNfe.CfgServico.VersaoRecepcaoEventoCceCancelamento = VersaoServico.ve310
        confNfe.CfgServico.VersaoRecepcaoEventoEpec = VersaoServico.ve310
        confNfe.CfgServico.VersaoRecepcaoEventoManifestacaoDestinatario = VersaoServico.ve310
        confNfe.CfgServico.TimeOut = 3000
End sub

**Comment by reislanes** [comment]
![image](https://user-images.githubusercontent.com/23508596/31818938-0dcfe444-b579-11e7-8698-11e81d717e38.png)
No programa de testes, o config está assim também

**Comment by reislanes** [comment]
<?xml version="1.0"?>

-<NFe xmlns="http://www.portalfiscal.inf.br/nfe">


-<infNFe Id="NFe15171034600882000148650010000026961000012343" versao="3.10">


-<ide>

<cUF>15</cUF>

<cNF>00001234</cNF>

<natOp>VENDA</natOp>

<indPag>0</indPag>

<mod>65</mod>

<serie>1</serie>

<nNF>2696</nNF>

<dhEmi>2017-10-20T09:00:54-03:00</dhEmi>

<tpNF>1</tpNF>

<idDest>1</idDest>

<cMunFG>1501402</cMunFG>

<tpImp>4</tpImp>

<tpEmis>1</tpEmis>

<cDV>3</cDV>

<tpAmb>1</tpAmb>

<finNFe>1</finNFe>

<indFinal>1</indFinal>

<indPres>1</indPres>

<procEmi>0</procEmi>

<verProc>3.000</verProc>

</ide>


-<emit>

<CNPJ>34600882000148</CNPJ>

<xNome>Taveira e Oliveira Ltda</xNome>

<xFant>Óticas Ana Maria</xFant>


-<enderEmit>

<xLgr>TV Padre Eutiquio</xLgr>

<nro>1367</nro>

<xBairro>Batista Campos</xBairro>

<cMun>1501402</cMun>

<xMun>Belém</xMun>

<UF>PA</UF>

<CEP>66060230</CEP>

<cPais>1058</cPais>

<xPais>Brasil</xPais>

<fone>9140098621</fone>

</enderEmit>

<IE>151449767</IE>

<CRT>3</CRT>

</emit>


-<dest>

<CPF>51702452204</CPF>

<xNome>Ernani dos Reis Lanes</xNome>


-<enderDest>

<xLgr>Av. Gov. José Malcher</xLgr>

<nro>2141</nro>

<xBairro>Nazaré</xBairro>

<cMun>1501402</cMun>

<xMun>BELÉM</xMun>

<UF>PA</UF>

<CEP>66060230</CEP>

<cPais>1058</cPais>

<xPais>BRASIL</xPais>

</enderDest>

<indIEDest>9</indIEDest>

</dest>


-<det nItem="1">


-<prod>

<cProd>61159</cProd>

<cEAN/>

<xProd>ARMACAO GUTTIER 1526-54-2880</xProd>

<NCM>90031100</NCM>

<CFOP>5102</CFOP>

<uCom>UNID</uCom>

<qCom>1.0000</qCom>

<vUnCom>178.0000000000</vUnCom>

<vProd>178.00</vProd>

<cEANTrib/>

<uTrib>UNID</uTrib>

<qTrib>1.0000</qTrib>

<vUnTrib>178.0000000000</vUnTrib>

<indTot>1</indTot>

</prod>


-<imposto>

<vTotTrib>60.73</vTotTrib>


-<ICMS>


-<ICMS00>

<orig>0</orig>

<CST>00</CST>

<modBC>3</modBC>

<vBC>178.00</vBC>

<pICMS>17.0000</pICMS>

<vICMS>30.26</vICMS>

</ICMS00>

</ICMS>


-<PIS>


-<PISAliq>

<CST>01</CST>

<vBC>178.00</vBC>

<pPIS>0.6500</pPIS>

<vPIS>1.16</vPIS>

</PISAliq>

</PIS>


-<COFINS>


-<COFINSAliq>

<CST>01</CST>

<vBC>178.00</vBC>

<pCOFINS>3.0000</pCOFINS>

<vCOFINS>5.34</vCOFINS>

</COFINSAliq>

</COFINS>

</imposto>

</det>


-<total>


-<ICMSTot>

<vBC>178.00</vBC>

<vICMS>30.26</vICMS>

<vICMSDeson>0.00</vICMSDeson>

<vBCST>0.00</vBCST>

<vST>0.00</vST>

<vProd>178.00</vProd>

<vFrete>0.00</vFrete>

<vSeg>0.00</vSeg>

<vDesc>0.00</vDesc>

<vII>0.00</vII>

<vIPI>0.00</vIPI>

<vPIS>1.16</vPIS>

<vCOFINS>5.34</vCOFINS>

<vOutro>0.00</vOutro>

<vNF>178.00</vNF>

<vTotTrib>60.73</vTotTrib>

</ICMSTot>

</total>


-<transp>

<modFrete>9</modFrete>

</transp>


-<pag>

<tPag>01</tPag>

<vPag>178.00</vPag>

</pag>

</infNFe>


-<infNFeSupl>


-<qrCode>

-<![CDATA[https://appnfc.sefa.pa.gov.br/portal-homologacao/view/consultas/nfce/nfceForm.seam?chNFe=15171034600882000148650010000026961000012343&nVersao=100&tpAmb=1&cDest=51702452204&dhEmi=323031372d31302d32305430393a30303a35342d30333a3030&vNF=178.00&vICMS=30.26&digVal=31444d7378414c416454764969537268753563626b546f437871513d&cIdToken=000001&cHashQRCode=44a9b4a9e1b7796ec02f7c008e644fd2a4afb36f]]>
</qrCode>

</infNFeSupl>


-<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">


-<SignedInfo>

<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>

<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>


-<Reference URI="#NFe15171034600882000148650010000026961000012343">


-<Transforms>

<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>

<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>

</Transforms>

<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>

<DigestValue>1DMsxALAdTvIiSrhu5cbkToCxqQ=</DigestValue>

</Reference>

</SignedInfo>

<SignatureValue>cGMMhgx51XlL2erLoEU1QcS5f0EeDbq2CoSxoYE65bFG/8D5Dr7g31FZr7nre6VjN4+3XRpuuVeNV+w4WjNT5zrWqCVNYj1iiWRn6TsKYkewfDjksS431ieaErbWJlPv1rDhxaC5IGwm5mFh6tl5zRo2KaeBfWh+rSTr9lrtFpSwG4WzMouiOHSIMmcgUaaLJn8kQWhts6TscryKBkdluyTWFuYoCe2yZRy92CmUo8tIVy5e5ocJp0e7x/WYRFqfSPzT71cd0nFaInfEmppXq04TZN8oVu9N1FdcuJfqdRQFoGB2LfsrKZhi9r2NAD1NlLlmqb/r6DxYtCDQSRDOfg==</SignatureValue>


-<KeyInfo>


-<X509Data>

<X509Certificate>MIIHyjCCBbKgAwIBAgIIPgUWEgVmXE4wDQYJKoZIhvcNAQELBQAwgYkxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTQwMgYDVQQLEytBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhIHYyMRIwEAYDVQQLEwlBQyBTT0xVVEkxGzAZBgNVBAMTEkFDIFNPTFVUSSBNdWx0aXBsYTAeFw0xNjEyMDYxNDM3MzVaFw0xNzEyMDYxMDI3MDBaMIHWMQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE0MDIGA1UECxMrQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFJhaXogQnJhc2lsZWlyYSB2MjESMBAGA1UECxMJQUMgU09MVVRJMRswGQYDVQQLExJBQyBTT0xVVEkgTXVsdGlwbGExGjAYBgNVBAsTEUNlcnRpZmljYWRvIFBKIEExMS8wLQYDVQQDDCZUQVZFSVJBICYgT0xJVkVJUkEgTFREQTozNDYwMDg4MjAwMDE0ODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMOyv7JKjRL55aR7rblj8OTyW/ua8+QyvSaoKtP4un7jF6LMyJyt4ERlP3oK6xwPFRN4IrpH4zPmMeRcMi9qcbTLyhb+tyXqCPQAHJRqCQ8cuGmF6Qw5ZjhaybTR+bfkDM8xzBSJ4udcEhh+m5J3Y0f1uP3r8VVHm0hFzxtmtW/rvtzMHjV0H4tB+AdQr1q0X0f/Jtf8tfEAIA2j2fh3vubqATxGeIRCHvIcwvCgS9jZ0zIdPep6QEyLXAfJjp7YVd/UFkjeXqAL3s3gjDEVyfa57z0hglqArQy2jjnxHcjBgYb9dLGTIOgzGintNULkMHdaUhWcdlGl3JK1iNGDW3ECAwEAAaOCAuUwggLhMFQGCCsGAQUFBwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL2NjZC5hY3NvbHV0aS5jb20uYnIvbGNyL2FjLXNvbHV0aS1tdWx0aXBsYS12MS5wN2IwHQYDVR0OBBYEFE8Hrp3btVgsH07aWruPk14yT0FcMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUNa4xFPZe0npPWP40qBpnlwrEmwcwXgYDVR0gBFcwVTBTBgZgTAECASYwSTBHBggrBgEFBQcCARY7aHR0cHM6Ly9jY2QuYWNzb2x1dGkuY29tLmJyL2RvY3MvZHBjLWFjLXNvbHV0aS1tdWx0aXBsYS5wZGYwgd4GA1UdHwSB1jCB0zA+oDygOoY4aHR0cDovL2NjZC5hY3NvbHV0aS5jb20uYnIvbGNyL2FjLXNvbHV0aS1tdWx0aXBsYS12MS5jcmwwP6A9oDuGOWh0dHA6Ly9jY2QyLmFjc29sdXRpLmNvbS5ici9sY3IvYWMtc29sdXRpLW11bHRpcGxhLXYxLmNybDBQoE6gTIZKaHR0cDovL3JlcG9zaXRvcmlvLmljcGJyYXNpbC5nb3YuYnIvbGNyL0FDU09MVVRJL2FjLXNvbHV0aS1tdWx0aXBsYS12MS5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBzQYDVR0RBIHFMIHCgSdsaWxpYW4uZmluYW5jZWlyb0BvdGljYXNhbmFtYXJpYS5uZXQuYnKgJQYFYEwBAwKgHBMaQU5UT05JTyBUQVZFSVJBIERPUyBTQU5UT1OgGQYFYEwBAwOgEBMOMzQ2MDA4ODIwMDAxNDigPAYFYEwBAwSgMxMxMTIxMDE5NDkwNDI1ODM5ODI2ODAwMDAwMDAwMDAwMDAwMDAwMDAzNDIzODI3UENQQaAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBAGJm+G2EcKu9jfncan2aqgGathuFXLlcLlhpCPHNEO45SDUXRi25RyT5inZ5yVQxlUH7c9wuWwebKvzO2q4C7Teb2eKlBUihY08Nl0o7hBi56G/8tA4fUZZu1QjErgb3EdXnq42QvhaKyfR0vGJ1u4Q61tB8WvqyG4YBbdBKUgJL2lr6hzPDoZjUSBPMklT/TadQ3oK50AuRDi72WL4icItiuOvuqgztGX2Soic6AAhqZ6AxCwvB/juu93VxIXRnec2a9KW23HXpYCJOTxO9znZkv72uf9IRMKC1rIHZ6AR0eeF48yuyZFRLGnk3zgnWePp6yfKmmZ2Po8HNldbzu6kv7bP8BnHQUwgtPGB1sZPN/9s5Rki0oQvCuHdnfQQQkC8xovMeySI47M+J7dkSRpkpPwQO+RhT5zJAFuRbyyRRmZv5MLLaijIvv35t8jCXeU6aENeXlrXlmQQUu6wAkLlZbiQRHQ6+bh+Pq0eeuJT8tvw4QzphctROi0U6lxzRiF/LAkepUH7QARb6zjl+bqr+5nDdXqK/l+6xC1Vvj2OUIt3I4YnEuwU1B5TnQZ8+xDtlcOvJcsB73NFAaTm1qHFRJfTcpiycFYkiK7p4GZKcOVOZ3WmwcxhWwNjz1lmMsAIerxvyNeJ78ixy9A6RPzn4aepCj/V4W/C8QfrfS7zG</X509Certificate>

</X509Data>

</KeyInfo>

</Signature>

</NFe>

XML da NFCe

**Comment by robertorp** [comment]
@reislanes  resolveu o problema? Teste novamente nos dois protocolos se não resolveu

**Comment by reislanes** [comment]
Como estou com muita urgência pra emitir NFCe, estou usando o Zeus pra gerar o xml e o envio, retorno e impressão estou usando o UniNfe e Unidanfe. Assim que tiver um tempo vou revisar novamente.

**Comment by robertorp** [comment]
OK irei fechar a issue! Obrigado!

**Comment by reislanes** [comment]
Tem como reabrir a issue pra ver se alguém consegue me dar uma luz?

**Comment by marcosgerene** [comment]
@reislanes abra outra issue, acredito que é melhor do que alongar a discussão

**Comment by orochasamuel** [comment]
@reislanes observe o seguinte na mensagem de erro:

> System.Exception: Serviço NFeAutorizacao, versão 3.10, não disponível para a UF PA, no ambiente de Produção para emissão tipo Normal, documento: ! (mas qual documento??)

Você não setou o documento default na emissão ao criar a config.

**Faça esse teste e nos deixe saber se foi realmente isso que resolveu.**

Abraços.
