### ISSUE TITLE
A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS

### ISSUE THREAD

**Issue by mvtaraujo** [ZeusAutomacao/DFe.NET#565]
Ola pessoal
 
Sei que ja foram abertas 2 issues pra esse assunto, mais não consegui descobrir o meu problema.
 
Meu problema está nessa mensagem:
“A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS”
 
Antes de utilizar o Zeus eu utilizava as DLL’s de um outro fornecedor. Esse problema aparecia quando a cadeia de certificados do cliente estava desatualizada ou com algum problema.
 
No zeus consigo emitir CTe, MDFe, NFCe e CTEOS normalmente, mais se eu ficar um tempo com meu software aberto e for transmitir novamente ele dá essa mensagem. E só resolve se eu fechar o sistema e abrir de novo.
 
Alguma ideia do que pode ser?
 
Tentei configurar tipo de protocolo, mais percebi que só é setável em NFe e NFce.
 
Minha aplicação é feita em WPF com C#
 
Obrigado pela atenção

**Comment by robertorp** [comment]
Configure o cache do Zeus e Configure para ele setar a senha do certificado A3 e seu problema sera sanado.

Essa issue pode ajudar https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/532

O protocolo e setavel a qualquer momento, você pode fazer isso manualmente.
Bastando setar o enum dessa constante antes de cada operação no Zeus dentro de sua aplicação.
`ServicePointManager.SecurityProtocol = Enum`
Esse SecurityProtocol e do proprio .net framework.

Se tiver duvidas enquanto a isso, faz igual o amigo da issue, me add no skype que ajudo você um dia fora do expediente de trabalho.

**Comment by marcosgerene** [comment]
@mvtaraujo 
Eu tenho o mesmo problema em diversos clientes desde que comecei a usar o Zeus. A solução que achei depois de quebrar muito a cabeça foi TROCAR o protocolo toda vez que o erro aparecia e tentar novamente de forma silenciosa.

Como eu faço: se o retorno da nfe conter a string "SSL" e não retornar um protocolo, ou seja não foi transmitida eu troco o **ServicePointManager.SecurityProtocol** para outro e tento novamente de forma silenciosa para o usuario (tento apenas mais uma vez).

Como as vezes um cliente emite várias notas sem fechar o sistema eu crio um array de valores para este enum e confome vou trocando vou tirando do array, quando usei todos recoloco eles e começo novamente, é uma gambiarra enorme, mas somente isso resolveu meu problema.

Sobre o erro: isto só acontece com certificados A3 e não acontece em todas as máquinas mas ainda não consegui achar uma relação entre esses PCs aonde o erro acontece, pois já vi no win 7, 8, 8.1 e 10, 32 e 64 bits.

PS: Como aqui em São Paulo para cupom fiscal usa-se o SAT e não o NFCe, pequenas empresas dificilmente usam certificado A1. O @robertorp é de GO lá usa-se a NFCe, e como a NFCe exige certificado digital provavelmente lá predomine o A1 e não o A3 como aqui,

PS2: Segundo o @rftd este problema está relacionado ao Framework e não ao Zeus, a origem do problema ainda é desconhecida pelo menos pra mim, mas trocar o protocolo e tentar novamente resolve meu problema (e acredito que o seu também).

Att, Marcos

**Comment by mvtaraujo** [comment]
oi pessoal, muito obrigado pelo retorno. vou fazer testes e falo aqui pra vc's o que deu. Essa semana está bem puxado e nao sei que dia vai dar tempo... mais uma hora consigo hehe.

Abs

**Comment by robertorp** [comment]
@mvtaraujo  eai arrumou?

**Comment by mvtaraujo** [comment]
@robertorp resolvi mudar toda a implementação já pro Zeus refatoração que vc me passou.

Finalizando agora eu percebi que mudou a parte de manter dados em cache do certificado, e nao estou conseguindo implementá-lo. Sem pre dá o erro de Referencia nao definida.

O erro acontece na classe ControleCache, no método ExecutaCache().


    public class ControleCache
    {
        private DFeConfig Config { get; set; }
        private CertificadoDigital CertificadoDigital { get; set; }

        public ControleCache(DFeConfig config, CertificadoDigital certificadoDigital)
        {
            Config = config;
            CertificadoDigital = certificadoDigital;
        }

        public CertificadoDigital ExecutaCache()
        {
            var certificadoDigital =
                Config.ProxyCacheCertificadoDigital.BuscarPorCnpjEmitente(Config.CnpjEmitente);

            if (certificadoDigital != null)
            {
                return certificadoDigital;
            }

            Config.ProxyCacheCertificadoDigital.Adicionar(Config.CnpjEmitente, CertificadoDigital);

            return CertificadoDigital;
        }
    }

Na classe CacheCertificadoDigital o objeto Cache abaixo sempre está nulo:
private static IDictionary<string, CertificadoDigital> Cache { get; set; }

Não sei se estou deixando alguma coisa passar, por enquanto apenas setei o parametro IsEfetuarCacheCertificadoDigital = true;

**Comment by mvtaraujo** [comment]
Alguma sugestão @robertorp ?

**Comment by robertorp** [comment]
Manda o erro imagem do erro

**Comment by leochg2021** [comment]
O mesmo erro aparece no meu e ja tentei varias alternativas e nada deu certo se alguem puder ajudar, agradeço...

fatal: An error occurred while sending the request.
fatal: A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/leochg2021/worksgit01.git/'

**Comment by jmartinsss** [comment]
> 

Estou com o mesmo problema quando tento fazer login com o token no git bash! Não sei mais oque fazer

**Comment by wesjx** [comment]
Ola, conseguiu resolver?

**Comment by wesjx** [comment]
Ola, eu estava com esse mesmo problema, quando vc colocar (git remote add origin) esse comando invés de colar o link HTTPS cola o SSH.
