### ISSUE TITLE
WS homologação MT

### ISSUE THREAD

**Issue by jonasscalar** [ZeusAutomacao/DFe.NET#569]
Buenas, estou testando o Zeus, muito legal, ai fiz um loop para status de todos estados e em homologação de MT nao encontrou o 3.10
Meu código:
.......
`var cert = CertificadoDigital.ObterCertificado(configuracaoCertificado);
            c.Certificado.Serial = cert.SerialNumber;

            for (int i = 0; i < 2; i++)
            {
                if (i == 0)
                {
                    c.tpAmb = NFe.Classes.Informacoes.Identificacao.Tipos.TipoAmbiente.taProducao;
                }
                else
                {
                    c.tpAmb = NFe.Classes.Informacoes.Identificacao.Tipos.TipoAmbiente.taHomologacao;
                }
                
                foreach (DFe.Classes.Entidades.Estado uf in Enum.GetValues(typeof(DFe.Classes.Entidades.Estado)))
                {
                    c.cUF = uf;
                    if (c.cUF.ToString() != "AN" && c.cUF.ToString() != "EX")
                    {
                        var s = new ServicosNFe(c);
                        var retornoStatus = s.NfeStatusServico();
                        Console.WriteLine(c.tpAmb.ToString() + " - " +  c.cUF.ToString() + " - " + retornoStatus.Retorno.xMotivo);
                        s.Dispose();
                    }
                }
                
            }`

ai adicionei na linha 541 de class EnderecoServico o MT e deu certo:
`endServico.Add(new EnderecoServico(ServicoNFe.NfeStatusServico, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl"));`

**Comment by marcosgerene** [comment]
Bom dia,

Pelo que entendi o MT não estava nos endereços de homologação, é isso?

Por favor mande um PR e obrigado pela contribuição

**Comment by robertorp** [comment]
Vou verificar, aguardar ate domingo, qualquer coisa se eu não lembrar da um alô aqui, ou faça um pull request. Se não fizer vou fazer no domingo.
