### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by jtvb** [ZeusAutomacao/DFe.NET#57]
Adenilton boa tarde,
Esse erro ocorre na emissão, estranho que consigo emitir diversas nfce porem depois de um tempo
ele apresenta esse erro. Você já passou por este erro?

**Comment by jtvb** [comment]
Pelo que vi aparentemente ja existe um canal seguro e o sistema esta tentando criar um novo e não consegue acessar o certificado...

**Comment by adeniltonbs** [comment]
Bom dia jtvb, 
Testei aqui utilizando certificado A1 e A3 e não consegui identificar o problema relatado.
Utilizamos a biblioteca em produção em clientes com A1 e A3 e eles não tiveram esse problema, mas acredito que o erro mencionado está relacionado ao certificado. 

Você poderia testar, fora da biblioteca, se o certificado está funcionando corretamente?

Por exemplo, você poderia tentar acessar uma das urls dos serviços web disponíveis em http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=, utilizando o internet explorer.

Outra coisa que você pode fazer é baixar o ACBRNFeMonitor e testar se as requisições utilizando seu certificado está funcionando normalmente nele.

Eu vi esse erro essa semana aqui, quando tentava emitir uma NFCe remotamente no cliente utilizando a área de trabalho remota do windows, pois esta capturava o certificado do cliente para a minha máquina e o certificado sumia da máquina do cliente (olhando no administrador de token).

Por último, você encontrou alguma parte do código que seja suspeita de "ja existe um canal seguro e o sistema esta tentando criar um novo e não consegue acessar o certificado"?

**Comment by jtvb** [comment]
Bom dia,
Estou analisando aqui a url abre normalmente com o meu certificado pede senha normal.
Dentro os testes o problema somente ocorre quando eu declaro a senha para o certificado ele funciona normalmente porem após algum tempo ocioso ele aparece esta mensagem.

Quando eu insiro a senha manualmente não apresenta esta mensagem funcionando perfeitamente.

Em resumo pelo que vi o método para informar a senha pelo que parece espira a senha após um determinado tempo. Quando eu fecho a aplicação e abro novamente ele volta a funcionar e depois de um tempo apresenta este erro.

Estou analisando para ver se consigo uma solução e lhe aviso.

**Comment by adeniltonbs** [comment]
Hum interessante...
Vou pesquisar aqui sobre esse comportamento quando a senha é salva, de fato não estou usando esse recurso no ambiente de produção.

Por curiosidade, desmarcou no gerenciador de dispositivos do windows, para os dispositivos USB, a opção de gerenciamento de energia, para que o windows não desligue as USBs após algum tempo de ociosidade?

![image](https://cloud.githubusercontent.com/assets/6733483/10640853/00a41892-77ed-11e5-8bb9-6da749f0fd2a.png)

**Comment by jtvb** [comment]
Vi as configurações estão todas corretas não esta com controle de energia, até mesmo porque quando é inserida a senha manualmente funciona.

Realizei algumas pesquisas e vi a propriedade CryptoKeySecurity no CspParameters aparentemente
é este parâmetro que informa o tipo da chave de segurança. Porem ainda não conseguir que funcione corretamente.

**Comment by adeniltonbs** [comment]
Alguma novidade sobre este caso?

**Comment by vasisti** [comment]
Ola pessoal boa noite, hoje me deparei com esse problema(Could not create SSL/TLS secure channel), no meu caso o cliente esta usando um certificado tipo token (certisign), fiz testes e percebi que neste caso o token foi renovado e quando voce visualizava o certificado no internet explorer estava aparecendo os dois certificados o vencido e o renovado, parece coisa boba, mas quando eu excluia o antigo o sistema passava a autorizar as notas normalmente, so que quando tirava o token e colocava ele voltava o cert. antigo. Entao liguei no suporte da certisign e pelo admijnistrador do token da pra excluir o certificado antigo. Ai voltou a funcionar normalmente. Abraços, Valdir

**Comment by jtvb** [comment]
Ola adeniltonbs,
Estive ausente do projeto... bom referente a este caso tive que retirar o envio da senha para o certificado. e o usuario informar a senha ao iniciar o sistema não conseguir deixar a senha pré configurada para o certificado A3. Vi o comentário do vasisti mas na minha apenas a aparece 1 certificado. vou realizar testes no certificado A1 acredito que nao tenha este problema mas se alguem tiver alguma solução agradeço Abrs...

**Comment by leandrossantos** [comment]
também estou tendo o mesmo problema com certificados A1 no servidor de MT

**Comment by marciojmuller** [comment]
Olá!
Estava com este problema e ao instalar o certificado A1 na máquina o problema parrou. Acredito que o que faltava era a cadeia de certificados, visto que para o windows de versões antigas os certificados emitidos no brasil não são reconhecidos como seguros.
