### ISSUE TITLE
Ver Notas Emitidas para o meu CNPJ

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#571]
Vi que alguns sistemas possuem a função ver as notas e emitidas para um CNPJ especifico e depois manifestar e fazer download se for o caso tipo monitor de notas do Fsist.com.br no Zeus tem alguma opção especifica de ver as notas dessa maneira?

**Comment by orochasamuel** [comment]
Não. A biblioteca Zeus fornece essas funções de forma "crua", ou seja, o tratamento do retorno quem faz é você.
O Zeus manifesta, baixa, retorna lista de documentos consultados mas você tem que tratar a informação para apresentar ao usuário.

**Comment by ThalisonSantos** [comment]
@samuelrochaoliveira  certo mais pelo o que vi o zeus só faz isso consultando mediante chave ou nsu dessa forma eu não vejo as emissões as quais eu não tenho ciência

**Comment by orochasamuel** [comment]
Justamente, a chave e / ou o NSU são o ponto de partida para acionar os eventos. Se precisar de ajuda com o desenvolvimento de tal ferramenta entre em contato comigo por e-mail.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira eu também tenho interesse na funcionalidade do @ThalisonSantos, se não for contra seus interesses e você puder dar o "caminho das pedras", nem precisa de código, apenas explicar rapidamente quais são as rotinas para isto eu (nós) ficaria(mos) muito gratos.

**Comment by ThalisonSantos** [comment]
@samuelrochaoliveira  @marcosgerene  seria muito bom inclusive para colocar no zeus

**Comment by marcosgerene** [comment]
@ThalisonSantos acredito que não. Acontece muita essa confusão, mas na minha visão o Zeus deve se ater apenas a gerar o XML e consumir o WebService, até os projetos de impressão devem ser separados, caso contrário vamos criar um monstro de Frankstein.

Pelo comentário do @samuelrochaoliveira o procedimento consiste em utilizar vários recursos da NFe (que o Zeus já implementa) juntos para ir recuperando cada arquivo como um "quebra cabeça".

Espero que tenha entendido minha opinião sobre isto.

**Comment by orochasamuel** [comment]
Concordo com sua visão @marcosgerene, o grau de responsabilidade da biblioteca com a geração, validação, transmissão e demais funções relativas ao XML já são uma carga muito grande, se incluir coisa demais é perigoso perder a essência do real propósito da ferramenta.

Eu fiz uma aplicação para consumir a consulta, manifestação e download das NF-e, é uma versão melhorada de uma primeira versão que fiz em 2012 quando ainda era usado o WS DownloadNFe, nele segui basicamente estes passos:

1 - Faço a consulta de DFe pelo NSU, caso não tenha feito nenhuma consulta eu seto 0 (zero), caso já tenha feito eu obtenho o último NSU consultado, gravo o último NSU retornado e o NSU máximo, e vou repetindo a consulta até não ter mais lotes disponíveis.
2 - Gravo a consulta no banco com todas as chaves e NSUs, só chave e NSU e os dados do lote.
3 - Após isso, em loop eu manifesto como ciência e baixo todas as notas, chave por chave, desserializo, e gravo os dados que preciso na base de dados.
4 - Depois que já tenho a nota salva, se surgir algum evento novo referente àquela chave eu só incluo na lista de eventos.
5 - A consulta retroage 90 dias mas, sempre recomendo não deixar passar de 1 semana senão a consulta fica demorada e é melhor o cliente acompanhar e saber o que é devido e o que não é com a maior brevidade possível.

Os passos básicos são esses, acredito não ter esquecido de nada. Caso tenha alguma dúvida, ficarei feliz em poder ajudar.

Abraços.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira me perdoe a ignorância, vou te dar um estudo de caso e ver se o que você disse se encaixa nisso.

>Um mercadinho minusculo no estado do RN (a +3000 kms daqui) pega com um cartão de apresentação da minha empresa (aonde tem o meu CNPJ) pegou meus dados num SINTEGRA da vida e toda vez que eles precisam emitir uma nota "pra fechar o mês" ele emite pro meu CNPJ.
>
>Esta minha empresa tem um faturamento muito pequeno, vamos por um valor de 10k/mês e essas notas desse mercadinho chegam a 15k em um mês, ou seja teoricamente eu tenho um faturamento menor do que deveria ter.

Bem, partindo disso eu preciso tomar uma atitude como acionar este mercadinho judicialmente, mas pra eu ter ciência de que isto está acontecendo eu preciso antes saber que esses documentos fiscais existem.

Como fazer isso, partindo do pré-suposto que eu não tenho NENHUMA informação, somente meu CNPJ e meu certificado.

Pelo que li do que você falou, no passo 1
> 1 - Faço a consulta de DFe pelo NSU, caso não tenha feito nenhuma consulta eu seto 0 (zero), caso já tenha feito eu obtenho o último NSU consultado, gravo o último NSU retornado e o NSU máximo, e vou repetindo a consulta até não ter mais lotes disponíveis.

Esta busca com o NSU zero retornaria todas as chaves que "mencionam" meu CNPJ? seria isso?

Como eu disse anteriormente eu nunca fiz este processo, então está um pouco nebuloso na minha cabeça.

Obrigado pela disposição em ajudar

**Comment by orochasamuel** [comment]
É exatamente este o caso @marcosgerene.

> Como fazer isso, partindo do pré-suposto que eu não tenho NENHUMA informação, somente meu CNPJ e meu certificado.

Reply: Você não tem nenhuma informação até efetuar a consulta. Vide abaixo.

> Esta busca com o NSU zero retornaria todas as chaves que "mencionam" meu CNPJ? seria isso?

Reply: Isso. Se você informar NSU zero, ele faz a busca com um range de data maior, se o NSU do último documento do lote retornado for o 120, por exemplo, mas nesse lote você tiver a informação de que o NSU Máximo é 346, você deve continuar a busca do 120 até chegar no 346 e obter os documentos restantes.

Se informar algum NSU a busca já parte deste número. Cada lote retorna um máximo de 50 documentos, podem ser notas e/ou eventos juntos, por isso eu desserializo e só trago os dados das notas, que são o que ME interessa.

A manifestação do destinatário nasceu primariamente com esta finalidade mas atualmente o fisco já está incorporando isso nas suas rotinas de auditoria e fiscalização, é de suma importância essa consulta para evitar situações desagradáveis como essa que você descreveu. Parti para a abordagem do software pois no meu escritório já tive 2 clientes com esse problema. ¬¬ 

Abraços.

**Comment by marcosgerene** [comment]
Excelente explicação @samuelrochaoliveira, acredito que eu tenha entendido o processo.

Estou com a corda no pescoço aqui, mas nos próximos 20 dias tento fazer algo nesse sentido.

Mais uma vez obrigado,

Marcos

**Comment by orochasamuel** [comment]
Fico feliz que possa ter ajudado @marcosgerene.

@ThalisonSantos ficou alguma dúvida?

Caso não, efetue o fechamento da issue, por favor.

**Comment by robertorp** [comment]
Pelo que entendi, manifestar e assim, mando NSU = 0
ele vai pegar um tanto X 120 e retornar o range máximo tb
ai depois mando outra 120 ele vai pegar o maximo que conseguir exemplo 240
ai mando 240 ele vai pegar ate a 300 

e isso?

existe alguma maneira de fazer pesquisa com data? exemplo: ultimos X dias?

**Comment by ThalisonSantos** [comment]
@samuelrochaoliveira  entendi sim foi uma ótima explicação, mas também queria saber sobre a pergunta do @robertorp

**Comment by orochasamuel** [comment]
Isso mesmo @robertorp. Pesquisa com data não é possível, o critério de busca deve ser preciso, por isso só aceita Chave de Acesso ou NSU.

**Comment by robertorp** [comment]
@samuelrochaoliveira  mas enquanto a parte de 

Pelo que entendi, manifestar e assim, mando NSU = 0
ele vai pegar um tanto X 120 e retornar o range máximo tb
ai depois mando outra 120 ele vai pegar o maximo que conseguir exemplo 240
ai mando 240 ele vai pegar ate a 300

e isso?

e isso mesmo?

**Comment by orochasamuel** [comment]
Sim sim, é exatamente isso.

**Comment by robertorp** [comment]
obrigado

**Comment by orochasamuel** [comment]
@ThalisonSantos você tem interesse em uma aplicação de consulte as notas e manifeste já pronta?

Caso tenha me envie um e-mail que podemos tratar do assunto.

Abraços.

**Comment by ThalisonSantos** [comment]
@samuelrochaoliveira se possível

**Comment by homerokzam** [comment]
Alguma novidade / solução em relação a essa consulta?

**Comment by marcosgerene** [comment]
@homerokzam 

Não entendi sua dúvida, pode ser mais específico?

**Comment by homerokzam** [comment]
Gostaria de saber como faço para recuperar todas as NFe e NFCe emitidas para o CNPJ do certificado A1 em um determinado período de tempo (data inicial e data final).

Pelo que pude verificar, existe o NfeDistDFeInteresse que talvez faça essa consulta, mas não estou entendendo como. Por isso gostaria de saber se existe alguma novidade com relação a pergunta "Ver Notas Emitidas para o meu CNPJ" desta "Issue".

**Comment by marcosgerene** [comment]
@homerokzam entendi melhor agora, alguns pontos.

Não existe essa funcionalidade para NFCe;

Não existe a busca via data inicial/final, deve-se usar um sequencial do NSU (iniciando em 0 caso não tenha feito a busca);

Não existe/vai existir novidades/soluções porque o "problema" não existe... basta usar a estrutura NfeDistDFeInteresse de forma ordenada, é algo que você implementa na sua aplicação, não é algo relacionado ao projeto (Zeus) em si.

Tenho um exemplo de uso aqui: https://github.com/ZeusAutomacao/DFe.NET/issues/1140#issuecomment-664592636
