### ISSUE TITLE
[QUESTION] Curso Online

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#573]
@adeniltonbs boa noite, tudo bem?

Recebi a oportunidade de ministrar um curso sobre desenvolvimento de aplicações com tratamento de informações fiscais e um dos módulos trata de NF-e, gostaria de saber se posso mencionar a biblioteca Zeus e mostrar a aplicabilidade e funcionamento?

Agradeço pela atenção.

Abraços.

**Comment by adeniltonbs** [comment]
Pode sim @samuelrochaoliveira.

**Comment by orochasamuel** [comment]
Obrigado.

Ótimo final de semana.

Abraços.
