### ISSUE TITLE
Atualização Nuget 

### ISSUE THREAD

**Issue by uberlei** [ZeusAutomacao/DFe.NET#574]
Gostaria de saber quando as alterações vão estar disponíveis no nuget pois estou precisando o certificado em bytes grato

**Comment by AutomacaoNet** [comment]
Vou atualizar hoje para você. E que geralmente deixo acumular algumas atualizações para gerar versões. 

@uberlei 

Obrigado!

obs: falei da conta errada hehe, by @robertorp

**Comment by robertorp** [comment]
Deixar a issue aberta para min lembrar anoite.

**Comment by uberlei** [comment]
Muito obrigado.

**Comment by robertorp** [comment]
Atualizado já. Aparentemente o repositório foi movido também fique atento.
