### ISSUE TITLE
Problema Download NFe

### ISSUE THREAD

**Issue by ThomasEA** [ZeusAutomacao/DFe.NET#575]
Gostaria de saber se mais alguém está enfrentando problema ao realizar o download de XML de NFe.
Após informar o CNPJ e a chave de acesso corretas, obtenho como resposta:

`versao = 1.00
tpAmb = taHomologacao
verAplic = AN.DownNF_2.1.2
cStat = 109
xMotivo = Servico Paralisado sem Previsao
dhResp = 06/11/2017 18:05:40
retNFe = System.Collections.Generic.List1[NFe.Classes.Servicos.Download.retNFe]`

Pesquisei sobre o erro e as soluções que encontrei envolvem entrar em contato com a SEFAZ. É isso mesmo?

**Comment by robertorp** [comment]
Este serviço não tem mais disponível, você deve utilizar o Manifestação e posteriormente um Distribuição para download das NF-e

**Comment by orochasamuel** [comment]
@ThomasEA veja esses issues https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/568 e https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/571

São os mais recentes sobre este assunto.

Abraços.

**Comment by ThomasEA** [comment]
Ok. Obrigado a todos pelo auxílio.
Abraços.
