### ISSUE TITLE
Eliminar o uso de variáveis no SOAP Header (Área de Cabeçalho) na requisição enviada para todos os Web Services com versão 4.0

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#577]

**Comment by robertorp** [comment]
Foi somente feito uma compatibilidade para isso na versão atualmente ate o momento. Marcado como [Obsolete] o atributo o mesmo não sera preenchido na versão 4.00 já em outras versões ele será preenchido. Acredito eu que seja uma melhor abordagem ate o momento, pois não podemos perder a compatibilidade com versões anteriores.
