### ISSUE TITLE
Download XML Nfce

### ISSUE THREAD

**Issue by uberlei** [ZeusAutomacao/DFe.NET#587]
É possível baixar os xml de nfce emitidos contra meu cnpj?

**Comment by orochasamuel** [comment]
@uberlei o NFCe (Nota Fiscal do Consumidor Eletrônica) foi criado para suprir as emissões de documento  quando o destinatário é consumidor final, ou seja, em sua maioria contra pessoa física mas também podem acontecer casos que será emitido contra pessoa jurídica (CNPJ).

A SEFAZ não oferece um serviço para baixar NFCe contra CNPJ pois perante a Legislação Estadual do ICMS não é permitido o aproveitamento de crédito, isso quer dizer que, ao pé da lei não é possível comprar e revender uma mercadoria que foi registrada em uma NFCe. Se sua intenção for essa, o correto é solicitar uma NFe (Nota Fiscal Eletrônica) pois todas as informações e dados de ICMS podem ser detalhados no documento.

Abraços.

**Comment by uberlei** [comment]
Na vdd tive um problema na empresa e foi perdido alguns xml's queria baixar novamente da receita os xmls q minha empresa emitiu. Mas grato pela reposta.

**Comment by orochasamuel** [comment]
Nesse caso você só pode baixar um por um, manualmente. Pelo menos no estado de Goiás a Sefaz dispõe deste serviço. Se eu não me engano, no endereço: nfce.go.gov.br
É repetitivo e moroso, por isso é altamente recomendado manter cópias em outras bases caso tal infortúnio ocorra.
Eu uso integração direta com dropbox e "subo" todos os documentos para uma conta. Assim tenho acesso online e nos sistemas que fornecem esse tipo de integração fica mais fácil. :D

Abraços.

**Comment by orochasamuel** [comment]
@uberlei pode fechar essa issue, por favor?
