### ISSUE TITLE
Verificar melhor abordagem(custom attributes ou shouldserialize pattern) para separar as propriedades que devem ser serializadas somente nos Layouts 3.1 ou 4.0

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#589]

**Comment by orochasamuel** [comment]
Me corrijam se eu estiver errado mas acredito que o melhor seria usar custom attributes.

https://stackoverflow.com/questions/40211364/serialize-custom-attribute-values

No projeto do SPEDBr eu uso custom attributes em larga escala. A manipulação é facilitada. Mas, não sei dizer a respeito de performance, não no momento.

Abraços.
