### ISSUE TITLE
vIPI não salva como decimal

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#59]
Bom dia, 

Estou passando por uma situação curiosa. 

No método "NFeAutorizacao" da classe "ServicosNFe", quando executo o "pedEnvio.ObterXmlString()", ele serializa o objeto NFe e o campo vIPI vem no xml dessa forma "0", porem todos os outros campos vem "0,00", como decimal.

Até ai tudo bem, envio o XML e o mesmo é autorizado, porem ao adicionar a tag de protocolo de autorização e serializar o objeto em XML para salvar o mesmo, o campo vIPI que era "0" passa a ser "0,00", ficando diferente do que foi assinado e enviado a SEFAZ.

Dessa forma o meu xml não bate com a assinatura.

Resumindo, quando Serializo o objeto "enviNFe3" para enviar o campo vIPI fica como "0", depois de autorizar, adicionar o protocolo e serializar novamente o "nfeProc", para salvar o XML o campo vIPI vem como "0,00".

Alguém tem alguma ideia do que pode estar ocorrendo?

Obrigado.

**Comment by marciojmuller** [comment]
Olá!
Passei por esse problema esses dias. Corrigi adicionando o método Valor.Arredondar() no get da propriedade:

public decimal vICMS
{
get { return Valor.Arredondar(_vIcms, 2); }
set { _vIcms = Valor.Arredondar(value, 2); }
}

Márcio Müller

**Comment by willianas1** [comment]
Bacana, teria que ver o o Adenilton, para ele colocar no código e disponibilizar, estou deixando meu código igual ao do repositório, para não ter problema de conflitos nas próximas atualizações.

Outro ponto seria ver o porque está ocorrendo isso somente com esse campo, talvez o problema esteja nos schemas, não sei.

Apesar de funcionar essa solução é um paleativo, pq o problema ainda vai estar lá.

Mais valeu pela dica, vou ter que ajustar aqui, pois os clientes estão salvando os XMLs errados.

Obrigado.

**Comment by marciojmuller** [comment]
Sim, falei com ele já, mas não foi só este campo, tive problemas com outros também.
Acredito que ele deve ter colocado na lista para desenvolvimento.

Márcio Müller

**Comment by SilverioMiranda** [comment]
Vai ter que mudar todas as propriedades para retornar o valor com as duas casas decimais usando a função Valor.Arredondar()

O exemplo :

```
decimal teste = 1;
decimal teste2 = 1.0m;
string teste3 = teste2.ToString();
decimal teste4 = Convert.ToDecimal(teste3);
decimal teste5 = 100.01m;
string teste6 = "1";
decimal teste7 = Convert.ToDecimal(teste6);

Debug.WriteLine(string.Format("Teste 1 : {0}", teste));
Debug.WriteLine(string.Format("Teste 2 : {0}", teste2));
Debug.WriteLine(string.Format("Teste 3 : {0}", teste3));
Debug.WriteLine(string.Format("Teste 4 : {0}", teste4));
Debug.WriteLine(string.Format("Teste 5 : {0}", teste5));
Debug.WriteLine(string.Format("Teste 6 : {0}", teste6));
Debug.WriteLine(string.Format("Teste 7 : {0}", teste7));
```

Resultado : 

```
Teste 1 : 1
Teste 2 : 1,0
Teste 3 : 1,0
Teste 4 : 1,0
Teste 5 : 100,01
Teste 6 : 1
Teste 7 : 1
```

Vocês poderiam informar mais quais campos apresentam o erro para eu poder corrigir e enviar aqui no github?

**Comment by marciojmuller** [comment]
Adicionei o método em todos os campos da classe NFe.Classes.Informacoes.Total.ICMSTot, não tive problemas com outros campos até agora.

**Comment by willianas1** [comment]
Até agora só tive problema com esse campo.

**Comment by adeniltonbs** [comment]
Ok, obr a todos.
Aceitei as alterações de Miranda no código principal.
