### ISSUE TITLE
Crédito Outogrado previsto no coonvênio 106/96 e corresponde ao percentual de 20% CT-e

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#591]
Bom na página 165 do manual de ct-e 3.0 tenho a seguinte TAG

ICMS60
vCred -> Preencher somente quando o transportador substituído, for optante pelo crédito outorgado previsto no Convênio 106/96 e corresponde ao percentual de 20% do valor do ICMS ST retido.

Pelo que andei lendo e assim

Bom dia.

A questão do lançamento do crédito presumido nos serviços de transporte, não é complexa. Trata-se de uma operação simples, mas, diante do que dispõe as normas tributárias, causa uma certa dúvida quanto à aplicação prática.

Vejamos:

No caso do referido crédito de 20%, fora os requisitos burocráticos que a transportadora deve segui para seu enquadramento, a coisa é bem simples.

Vamos supor que em um transporte, a transportadora cobrou R$ 5.000,00 para a prestação do serviço. Imaginemos que seja uma alíquota modal de 18,00% em uma determinada unidade da federação, então passamos ao cálculo.

R$ 5.000,00 x 18,00% = R$ 900,00 que é o ICMS supostamente devido pela transportadora ao Estado,  esta é a parte geral.

De posse desta informação, é hora de alimentar as tags do xml do CT-e. No caso de redução CST 020 e do referido crédito, CST 060 e CST 090.

Destaque-se que,  para saber qual tag alimentar, é importante que se analise a situação tributária em si.

No exemplo de R$ 5.000,00 x 18,00% = R$ 900,00, o valor do crédito recai sobre 900, então o crédito será de R$ 180,00, e o valor efetivamente devido será de R$ 720,00. Diante disso é só informar os respectivos valores nas referidas tags do XML que devem estar previstas no guia de integração.

Creio que seja isso.

fonte: https://www.projetoacbr.com.br/forum/topic/38213-cr%C3%A9dito-presumido-de-20-no-ct-e-convenio-10696-ricms/?tab=comments#comment-251316

**Comment by orochasamuel** [comment]
@robertorp o que me chamou mais a atenção foi sua citação:

> ICMS60
vCred -> Preencher somente quando o **transportador substituído**, for optante pelo crédito outorgado previsto no Convênio 106/96 e corresponde ao percentual de 20% do valor do ICMS ST retido.

Se é substituído não paga o imposto, já foi pago e retido na fonte.

O material base para esse issue encontra-se em: https://www.confaz.fazenda.gov.br/legislacao/convenios/1996/cv106_96

Lembrando que o uso do crédito presumido é opcional.

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira 
Na tag do xml do ct-e oque preencher? 
Digo exemplo: valor ICMS = 1000
vCred = 200

coloco no Valor ICMS 1000 ou 800? 

Eu li esse material ai e na Cláusula primeira tem "do valor do ICMS devido na prestação" ou seja sempre sera com base no valor do ICMS ne? 

Andei lendo googlando por ai e me deparei que existem também restrições enquanto ao CST 20 no caso a tag pRedBC, assim pelo que vi no CT-e as vezes a redução não e aplicada na Base de Calculo e sim no vICMS, realmente e possível isso? porque ate o nome da tag já diz para oque serve.

**Comment by orochasamuel** [comment]
> Na tag do xml do ct-e oque preencher?
Digo exemplo: valor ICMS = 1000
vCred = 200

A TAG vCred serve para informar o real valor do crédito, como você mesmo disse. No caso, os $ 200,00.

> Eu li esse material ai e na Cláusula primeira tem "do valor do ICMS devido na prestação" ou seja sempre sera com base no valor do ICMS ne?

Exato. Sempre será calculado sobre o valor base do ICMS, o layout do CT-e comporta todas as informações necessárias. Quando um material legislativo traz o descritivo "do valor devido na prestação" quer dizer somente que aquela operação tem sim uma incidência e você deve saber qual o imposto ou quais variáveis irão afetar o valor final. Exemplo: No caso de transporte - que é o cenário que estamos tratando - se houver algum valor de pedágio no decorrer do transporte, ele deve ser incluído na base de calculo do imposto. Claro, deve-se observar as exigências em cada Legislação Estadual mas este pode ser um exemplo para elucidar o que citei mais acima.

> Andei lendo googlando por ai e me deparei que existem também restrições enquanto ao CST 20 no caso a tag pRedBC, assim pelo que vi no CT-e as vezes a redução não e aplicada na Base de Calculo e sim no vICMS, realmente e possível isso? porque ate o nome da tag já diz para oque serve.

O uso da CST 020 está restrito ao atendimento de algumas condições, dependendo de qual benefício a empresa utilizar para redução do imposto. Pode ser exigido um Acordo/Convênio/TARE(Termo de Acordo de Regime Especial), que, caso aprovado pela SEFAZ poderá ser praticado. Outra exigência da CST 020 é a posse da inscrição estadual.

Mas respondendo a sua pergunta, o descritivo da CST 20 é "com redução de base de calculo", então nenhuma redução pode ser aplicada diretamente no imposto se usada essa CST. Não tenho certeza mas creio que nenhuma redução possa ser aplicada diretamente no imposto.

--------------------------------------------------------------------------------------

O que eu lhe recomendo nessa situação é fazer uma consulta formal na SEFAZ a respeito do uso da CST 090. Na página 166 do Manual do CT-e 3.0 consta o detalhamento do ICMS 90.

Nesta TAG é possível informar o percentual de redução da base de cálculo (os 20%), o valor da base de cálculo, a alíquota aplicada para a operação, o VALOR CHEIO do ICMS (sem a redução), e o valor do crédito presumido.

Acredito que com esta TAG você consiga prestar todas as informações necessárias sem problemas na validação do XML.

Abraços.

**Comment by robertorp** [comment]
> Se é substituído não paga o imposto, já foi pago e retido na fonte. 

> 

Blz, concordo plenamente mas pensando agora, eu lembrei que na tag ICMS60 - página 165 do manual CT-e 3.0
lá existe a tag vCred também como seria adicionado essa tag? Isso deu um nó na minha cabeça.

**Comment by orochasamuel** [comment]
@robertorp desculpe, acho que agora entendi sua dúvida.

Vamos lá..
No caso do CST 060 a TAG vCred pode ou não possuir valor, no caso de ser informado o valor o transportador deve fazer uso da redução prevista no Convênio 106/96, e deve fazer uso em todos os estabelecimentos no território nacional. Sendo este o seu cenário e usando de exemplo os valores que você citou no primeiro comentário, deve-se tratar da seguinte maneira:

### Cenário Proposto
A operação será tributada pela substituição sob a CST 060 (a responsabilidade do recolhimento do ICMS é do tomador ou terceiro)

Valor do Serviço de Transporte = $ 5.000,00
Base de cálculo para efeito do ICMS = $ 5.000,00 (levando em conta que não exista nenhum alterador de valor, tais como: seguro, juros, desconto concedidos sob condição)
Alíquota incidente sobre a operação = 18%
Valor do ICMS devido = $ 900,00

Base de cálculo do crédito presumido = $ 900,00
Alíquota do crédito presumido = 20%
Valor do crédito presumido = $ 180,00

Valor FINAL do ICMS a ser repassado para o fisco estadual = $ 720,00 ( $ 900,00 - $ 180,00)
*Lembrando que tal responsabilidade é do tomador ou terceiro, referido no documento fiscal.

### Preenchimento das TAGs do CT-e

Conforme pág. 165 do Manual do CT-e 3.0.

Campo 209 - CST = 60
Campo 210 - vBCSTRet = $ 5.000,00
Campo 211 - vICMSSTRet = $ 900,00 (campo 210 x campo 212)
Campo 212 - pICMSSTRet = 18%
**Campo 213 - vCred = $ 180,00**

Acredito que agora conseguimos elucidar melhor.

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira  Muito obrigado pela ajuda, foi de gigante ajuda hehe.

**Comment by orochasamuel** [comment]
Estamos aqui pra isso amigo. o/

Uma mão lava a outra.

Abraços.
