### ISSUE TITLE
Não é possível gerar o PDF de XML de CTe

### ISSUE THREAD

**Issue by LucasFarley** [ZeusAutomacao/DFe.NET#592]
Quando um XML de CTe tem a tag **compl** conforme exemplo abaixo o relatório [DACTE] do FastReport não consegue gerar o PDF.

```
<compl>
<xObs>NF CONFERIDA POR QUANTIDADE E REFERENCIA | EMPRESA OPTANTE DO SIMPLES NACIONAL |</xObs>
<ObsCont xCampo="OBSERVACAO">
<xTexto>NF CONFERIDA POR QUANTIDADE E REFERENCIA | EMPRESA OPTANTE DO SIMPLES NACIONAL |</xTexto>
</ObsCont>
</compl>
```

**Comment by marcosgerene** [comment]
Por favor anexe o XML e a mensagem de erro, obrigado

**Comment by marcosgerene** [comment]
Fiz um testa aqui e o problema está no subreport que exibe o ObsCont mas o Fast não da nenhum retorno, apenas trava e fecha, ai fica complicado de entender o motivo...

**Comment by LucasFarley** [comment]
@marcosgerene, realmente é complicado identificar o problema... Para identificar que era estes campos eu tive que ir removendo os campos do report e testando a impressão.
Acredito que o problema esteja relacionado a questão do campo ObsCont ter múltiplos registros.
Não sou especialista no FastReport.  Porém este erro impacta seriamente na visualização dos PDF's de  CTe.

Caso precise de ajuda, me disponho a ajudar nos testes.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/593

Removi os dois subreports e solucionei "na unha"

![image](https://user-images.githubusercontent.com/15945003/32688706-1bfcfbf6-c6bd-11e7-9362-c1eb5012d6da.png)

Caso isto resolva seu problema, por favor feche a issue.

**Comment by LucasFarley** [comment]
@marcosgerene, funcionou... Você é o cara...
