### ISSUE TITLE
Erro ao Visualizar CTe - Error in expression: cteProc.CTe.infCte0.receb.IE

### ISSUE THREAD

**Issue by LucasFarley** [ZeusAutomacao/DFe.NET#594]
Ao tentar visualizar o CTe em anexo aparece a seguinte mensagem [Text127: Error in expression: cteProc.CTe.infCte0.receb.IE - ]

[35170913479424000122570010000620681336542203.xml.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1464023/35170913479424000122570010000620681336542203.xml.zip)

Este XML é valido e aprovado na SEFAZ.

**Comment by marcosgerene** [comment]
@LucasFarley Este erro é simples, provavelmente alguém (bem possível que seja eu rs) bateu um 0 depois do infCte ali...

Enviei um pull request corrigindo o problema.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/595

**Comment by LucasFarley** [comment]
@marcosgerene, não estou conseguindo pegar esta correção não sincronização com o GitHub

**Comment by LucasFarley** [comment]
Testei a alteração e funcionou. Mais uma vez obrigado.
