### ISSUE TITLE
Consultar NFCe

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#596]
Boa tarde Pessoal, 

Estou precisando consultar algumas notas para obter o XML e ler os itens.

Com base nisso tenho algumas perguntas, e gostaria de saber se o projeto contempla essas funcionalidades.

1. Tenho como, pela chave da NFCe, baixar o XML?
2. Caso positivo, preciso um certificado pra isso?

Obrigado antecipadamente a todos.

**Comment by facilita-tecnologia** [comment]
Boa Noite, você não consegue obter o XML de uma NFC-e somente da NF-e

Caso queira baixar o XML da NF-e a biblioteca dispõe de recursos, nesse caso necessita do certificado digital.

**Comment by facilita-tecnologia** [comment]
da uma lida na issue #587
