### ISSUE TITLE
Tributação 60 CT-e 3.00/ Calculo utilizado seria o mesmo de substituição normalmente?

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#597]
Página 165 do manual CT-e 3.00 temos a seguinte TAG 60

![ct-e 3 00 tributacao](https://user-images.githubusercontent.com/10251705/32721528-e615ce0e-c84d-11e7-896b-a82a07dcc66e.png)

Oque quero e entender como fazer o calculo 60
Seria um calculo normalmente de substituição tributaria? Tipo esse http://www.nomus.com.br/blog-industrial/2015/09/como-calcular-a-substituicao-tributaria-do-icms-em-uma-industria-de-manufatura/

Ou no meu sistema simplesmente posso colocar o campo 
vBCSTRet * pICMSSTRet = vICMSSTRet 

No caso o sistema pegaria o valor total do serviço do CT-e e jogaria em vBCSTRet 
usuário digitaria o pICMSSTRet 
usuário digitaria o vCred

e assim faria o calculo 

vBCSTRet * pICMSSTRet = vICMSSTRet 
e depois calcularia o vCred

Seria algo assim? ou algo assim http://www.nomus.com.br/blog-industrial/2015/09/como-calcular-a-substituicao-tributaria-do-icms-em-uma-industria-de-manufatura/

**Comment by orochasamuel** [comment]
@robertorp a substituição tributária no CT-e significa mais um indicador de quem deve pagar o imposto do que uma particularidade no cálculo mesmo.

Se fosse uma NF-e vendendo produtos/mercadorias, esse link que você anexou seria útil.

Já no caso do frete, seria um cálculo "cru" mesmo.

> Ou no meu sistema simplesmente posso colocar o campo
vBCSTRet * pICMSSTRet = vICMSSTRet

> No caso o sistema pegaria o valor total do serviço do CT-e e jogaria em vBCSTRet
usuário digitaria o pICMSSTRet
usuário digitaria o vCred

> e assim faria o calculo

> vBCSTRet * pICMSSTRet = vICMSSTRet
e depois calcularia o vCred

Cálculo:
Base de Cálculo x Percentual Imposto = Imposto
Imposto x 20% (crédito presumido) = vCred

---------------------------------------------------------------------------------------

Na dúvida a respeito dos valores de frete, use a Tabela com Valores Referenciais (Pauta). O Estado de Goiás disponibiliza uma:

Acesse [SEFAZ/GO](http://www.sefaz.go.gov.br/) > Serviços > Item 24 - Pauta de valores referenciais do ICMS > Outras Pautas > Selecione um dos grupos de transporte.

Outra informação, com as alterações trazidas pela IN 1303/16 é possível "dispensar" o tomador do serviço do pagamento. Vide mais detalhes [aqui](http://www.goiasagora.go.gov.br/mudam-regras-para-substituicao-tributaria-de-servico-de-frete/).

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira  obrigado, fiz uns ajustes na minha lib para eu utilizar no meu CT-e Regime normal hehe https://github.com/automacaonet/MotorTributarioNet 

Obrigado pela ajuda @samuelrochaoliveira  você e foda em tributação hehe

**Comment by orochasamuel** [comment]
Que nada @robertorp, tem muito chão ainda pra rodar.

Mas estou aí pra isso. o/

Abraços.

**Comment by orochasamuel** [comment]
Até hoje não conhecia ninguém que usava os serviços do SAC Fiscal.

Os caras tiveram uma boa sacada. Tem demanda ^^
