### ISSUE TITLE
Alterar requerimento do .NET Framework de 4.0 para 4.5.2

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#599]

**Comment by robertorp** [comment]
Isso da problemas com Windows 7 vai ter que instalar algum service pack, nos da empresa aqui tentamos subir nosso sistema para a versão 4.6.x tivemos que instalar em alguns windows 7 um service pack especifico e isso gerou suporte. Foi onde desistimos e voltamos nosso sistema para a versão 4.5.2.

Essa e nossa experiência que passamos.

**Comment by adeniltonbs** [comment]
Aparentemente a versão 4.7.1 não é compatível com o Windows Vista e o Windows 8, se comparada com a versão 4.5.2, vide https://www.microsoft.com/pt-br/download/details.aspx?id=42642 e https://www.microsoft.com/pt-br/download/details.aspx?id=56116.

Posso deixar a versão 4.5.2, se acharem que possuem muitos clientes com essas versões do Windows.

**Comment by leandrossantos** [comment]
@adeniltonbs acredito que o melhor é deixar na 4.5.2 mesmo, pois ainda tem muita gente usando Windows 7, principalmente por causa de hardware e também ainda tem muita gente que prefere usar o Windows 7.

**Comment by marcosgerene** [comment]
@adeniltonbs faço parte do time que prefere a 4.5.2.

Meu sistema roda na 4.6.1,  mudara para a 4.6.2 já seria um parto...

**Comment by orochasamuel** [comment]
Segue a vida mesmo como está. Se algum dia o projeto for migrado para NET Standard aí cada um escolhe qual será o framework target.

**Comment by rftd** [comment]
com a vinda da NFe 4 precisa migrar no minimo para o framework 4.5 eu acho mais do que suficiente.

**Comment by eduprog** [comment]
Hoje em dia temos clientes que ainda rodam Xp. Eu também voto em deixar na 4.5.x para que não tenhamos dores de cabeça e na prática não muda muita coisa como bem ponderado peloa demais.

**Comment by rftd** [comment]
@eduprog Seus clientes que rodam XP precisam mudar pois o ultimo framework a rodar no xp é o 4.
4.5 + so win vista para frente.

**Comment by eduprog** [comment]
Sim, isto ja foi providenciado. Como a maioria deles é MG estamos migrando gradualmente. Falar com cliente que tem de gastar ele sempre fica chateado!!! Mas todo mundo vai para no mínimo w7.

**Comment by rftd** [comment]
Windwos 7 com sp1 roda basicamente todos os frameworks menos o 4.7 +
Otima pagina para ser ter salvo.
https://msdn.microsoft.com/pt-br/library/8z6watww(v=vs.110).aspx
