### ISSUE TITLE
NFCe RJ

### ISSUE THREAD

**Issue by jtvb** [ZeusAutomacao/DFe.NET#60]
Boa tarde,

Estou tentando emitir uma nfce no estado do rio e esta me retornando a seguinte mensagem

FALHA NO SCHEMA XML DO LOTE

segue o xml detalhe validei no validador RS e foi certinho...

<enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>21</idLote><indSinc>1</indSinc><NFe><infNFe versao="3.10" Id="NFe33151023331284000102650010000000011000000216"><ide><cUF>33</cUF><cNF>00000021</cNF><natOp>VENDA</natOp><indPag>0</indPag><mod>65</mod><serie>1</serie><nNF>1</nNF><dhEmi>2015-10-27T16:16:39-02:00</dhEmi><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3306305</cMunFG><tpImp>4</tpImp><tpEmis>1</tpEmis><cDV>6</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>3.000</verProc></ide><emit><CNPJ>23331284000102</CNPJ><xNome>JF &amp; DELICIOUS FOOD LTDA ME</xNome><xFant>LE PETIT VOLTA REDONDA</xFant><enderEmit><xLgr>RUA BRAS MAGALDI FERNANDES</xLgr><nro>300</nro><xCpl>SUBSOLO STAND M199</xCpl><xBairro>VILA SANTA CECILIA</xBairro><cMun>3306305</cMun><xMun>VOLTA REDONDA</xMun><UF>RJ</UF><CEP>27260315</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>24999066914</fone></enderEmit><IE>87017680</IE><CRT>1</CRT></emit><dest><CPF>18276680836</CPF><xNome>NAO INFORMADO</xNome><indIEDest>9</indIEDest></dest><det nItem="1"><prod><cProd>1</cProd><cEAN /><xProd>AGURA COPO</xProd><NCM>22011000</NCM><CFOP>5102</CFOP><uCom>UN</uCom><qCom>1.0000</qCom><vUnCom>1.0000000000</vUnCom><vProd>1.00</vProd><cEANTrib /><uTrib>UN</uTrib><qTrib>1.0000</qTrib><vUnTrib>1.0000000000</vUnTrib><indTot>1</indTot><nItemPed>1</nItemPed></prod><imposto><vTotTrib>0.18</vTotTrib><ICMS><ICMSSN102><orig>0</orig><CSOSN>102</CSOSN></ICMSSN102></ICMS><PIS><PISOutr><CST>99</CST><vBC>1.00</vBC><pPIS>0.6500</pPIS><vPIS>0.01</vPIS></PISOutr></PIS><COFINS><COFINSOutr><CST>99</CST><vBC>1.00</vBC><pCOFINS>3.0000</pCOFINS><vCOFINS>0.03</vCOFINS></COFINSOutr></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>1.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.01</vPIS><vCOFINS>0.03</vCOFINS><vOutro>0.00</vOutro><vNF>1.00</vNF><vTotTrib>0.18</vTotTrib></ICMSTot></total><transp><modFrete>9</modFrete></transp><pag><tPag>01</tPag><vPag>1.00</vPag></pag><infAdic><infCpl>Balcao Ctrl: 1 \n\r Garcom Web vr 2.0 www.garcomweb.com.br \n\r *Valor aproximado dos tributos dos itens \n\r Trib aprox R$: 0,18 Federal e 0,00 Estadual \n\r Fonte: IBPT/FECOMERCIO RJ 5oi7eW \n\r Valor aproximado dos tributos deste cupom R$ 0,18(18,00%) \n\r (conforme Lei Fed. 12.741/2012)</infCpl></infAdic></infNFe><infNFeSupl><qrCode>http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?chNFe=33151023331284000102650010000000011000000216&amp;nVersao=100&amp;tpAmb=1&amp;cDest=18276680836&amp;dhEmi=323031352d31302d32375431363a31363a33392d30323a3030&amp;vNF=1.00&amp;vICMS=0.00&amp;digVal=655a376d4363387565554132656f4363376574554e6872724855633d&amp;cIdToken=000001&amp;cHashQRCode=e587d7951f99281dfc216d78097d3e4224867956</qrCode></infNFeSupl><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#NFe33151023331284000102650010000000011000000216"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>eZ7mCc8ueUA2eoCc7etUNhrrHUc=</DigestValue></Reference></SignedInfo><SignatureValue>m9JXcx2rg+daxyryfy4aEHv75NHu4YJIRjyd9W88ABbsyESK5TYhHdsPPoDDZK35nulh3fVT12+u7xj8gCru3fT0miLceKWnBPaP6MXJtxZgn7MIQLtGm9oWRvf10MNCacgi47T1FL5ngqIKo85O/b4rme5SPycvoKrfi/B7hkjs58YhY+X5EV+Rr4EuG+ojGmSgGQ7UfWLfDTFN40/+zkIAQY/lBt18dBCbPFHa7ltPw4Ekx6EGv/8HFJGOLi/aFuz7YqubOva+T6I8E8OZ1ZWIOwKb+EsbU/2FdR1CCX367hR+y6h4zauBLQDVqSZWwB8ZW0g3f8Mdybx6E1SLPw==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH8jCCBdqgAwIBAgIIRdBqn+KzWjkwDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEXMBUGA1UEAxMOQUMgU0FGRVdFQiBSRkIwHhcNMTUxMDEzMTQwMDAwWhcNMTgxMDEzMTQwMDAwWjCB3zELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxCzAJBgNVBAgTAlJKMRYwFAYDVQQHEw1WT0xUQSBSRURPTkRBMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEogQTMxDzANBgNVBAsTBkFSIE9ORTE1MDMGA1UEAxMsSkYgRSBGIERFTElDSU9VUyBGT09EIExUREEgTUU6MjMzMzEyODQwMDAxMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3fYRBOcZ8gQmnPFV425QryB/MiuPLeM/YsxC3kBp4cNEpt2zd/F8eyVQog5B+kfB9gcf34JekKFQXvldZAlrZkCm8g3eFu0oUhpAhESDwiIVXQnpCjOjS2dItjNGiXyli0qcnoPUmpqzC0/5ZOpRs7wXpnmqfYhA93QmFCuQfYc0Z5ifLNXxGKzGRGko5JkX7qM9luvr7NavQBbxqK4zFAvtmTpAwtJ5z67iFK18jzGbj0/S8P+BM9jzGb+GTvPcgAQDDfZGK+Jqsis7z93Q7YrKzxt4R2N1ttQ4zoeZaPaMEK5J2fTMRVah1HHStq9rvAOVPVfB2Zm4+YH/LAqUDAgMBAAGjggMbMIIDFzAfBgNVHSMEGDAWgBTfRU9Px+HcOMxKDCDn+OlZrR9eYTAOBgNVHQ8BAf8EBAMCBeAwaQYDVR0gBGIwYDBeBgZgTAECAzAwVDBSBggrBgEFBQcCARZGaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9kcGMtYWNzYWZld2VicmZiLnBkZjCB/wYDVR0fBIH3MIH0ME+gTaBLhklodHRwOi8vcmVwb3NpdG9yaW8uYWNzYWZld2ViLmNvbS5ici9hYy1zYWZld2VicmZiL2xjci1hYy1zYWZld2VicmZidjIuY3JsMFCgTqBMhkpodHRwOi8vcmVwb3NpdG9yaW8yLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9sY3ItYWMtc2FmZXdlYnJmYnYyLmNybDBPoE2gS4ZJaHR0cDovL2FjcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU0FGRVdFQi9sY3ItYWMtc2FmZXdlYnJmYnYyLmNybDCBiwYIKwYBBQUHAQEEfzB9MFEGCCsGAQUFBzAChkVodHRwOi8vcmVwb3NpdG9yaW8uYWNzYWZld2ViLmNvbS5ici9hYy1zYWZld2VicmZiL2FjLXNhZmV3ZWJyZmJ2Mi5wN2IwKAYIKwYBBQUHMAGGHGh0dHA6Ly9vY3NwLmFjc2FmZXdlYi5jb20uYnIwgb4GA1UdEQSBtjCBs4EZRkVSTkFORE8uQ1I3MDcwQEdNQUlMLkNPTaAoBgVgTAEDAqAfEx1GRVJOQU5ETyBDQUpBWkVJUkEgREUgUkVaRU5ERaAZBgVgTAEDA6AQEw4yMzMzMTI4NDAwMDEwMqA4BgVgTAEDBKAvEy0xMDA2MTk3MDA0MTc1Mjc0NzA3MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAv5UGNNffN/3qUgmIc0X+tznxyFHqFMFGXAwvT/83zk6njtR+mdo98KktL0OUiwOd4tuCzaYj1P0PCCGRPKoxVfENGeSMpLyJuXrM76mJvo1AdLsBmpaZ8j6CZ/6Ev7Ydl6LnJp5GDrp+UjSa/iiJvP934qQ+jS+3qiZ9Q9BOSZ+WoQzK12eeBvxGdVpGP3EpsfI4S9Kq1q8ExpnVTVvJFxY0p/mwaqrRCQN8z5hRfiF5JB3Py9PPZT90eBgEecBdd9K6PwSA4MDFD1kOfHga61aWabbtYsVcxvImm3D85uzdaJPqTgOkJ97lPDhL2jziwMIcCh47tCcETxsD22VCmNIPNtM8yjc7cbvA5uHcgB3QAPQRmHBToRGkgeviD5TDdn98VImFBDQPNN/9LgQ5UwfGBj0ZqJX4SSNPPqrqnoVnH3q5rt4oxFyHKmfafwKBvWZ0k6hUTaTi0quuDG394v1VbdGOvHY+4Q6mSy4wbCfQWDNZ0qask1RaeheJLow9pPlnbH+wya6DQCPTdMzUNgjMpUwrzA5FeqpoaxLBYXpD4X1Uyj19rt07WZg86ZpS62vn48Cw/h+DR/HTS+kHH5V7kT+owhFrnvPJ43btgT4vElHDMaPWGt8OKliG9GWnwtdrRVdEihlbkaPK/IrBRyADqlCzPP64LtWrSlB2mUg==</X509Certificate></X509Data></KeyInfo></Signature></NFe></enviNFe>

Poderia me ajudar
Abraço...

**Comment by jtvb** [comment]
Segue o anexo

http://186.230.37.137/garcomweb/atualizacao/xml.xml

**Comment by jtvb** [comment]
Reparei que após a Tag SignedInfo esta com um enter talvez seja isso o problema segue a imagem

http://186.230.37.137/garcomweb/atualizacao/imagem.png

**Comment by adeniltonbs** [comment]
Pode ser que o Rio ainda não tenha adicionado suporte a nt2015.002, tente mandar sem o grupo infNFeSupl.

**Comment by jtvb** [comment]
Cara PARABÉNS nem tinha pensado nisso... retirei a tag e funcionou....

**Comment by leandrossantos** [comment]
Como a NT 2015/002 foi prorrogada para 01/12/2015, então pode ser que tenha estados que não implementaram a nova regra.
