### ISSUE TITLE
Adicionar proc ao XML em produção

### ISSUE THREAD

**Issue by rezendeneto** [ZeusAutomacao/DFe.NET#600]
Estou tendo um problema com a aplicação de teste (NFe.AppTeste) na hora de adicionar o proc ao XML no ambiente de produção.

Ocorre a seguinte exceção:

![c__users_antonio rezende_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_948faedd-8ca9-4cd8-b5be-c1660c6670b2](https://user-images.githubusercontent.com/607961/33090965-e03ab6f8-cedc-11e7-98ef-e693af95698b.jpg)

Alguém já passou por algo parecido?

**Comment by orochasamuel** [comment]
Muda o protocolo de segurança e tenta novamente.

**Comment by rezendeneto** [comment]
Já tentei com diferentes protocolos de segurança mas não tive nenhum resultado.

**Comment by robertorp** [comment]
http://www.robertorp.com.br/2017/10/erro-comun-no-framework-zeusnetnfenfce.html
Tente essas opções uma outra opção e usar um delegate

ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

**Comment by robertorp** [comment]
Conseguiu?

**Comment by rezendeneto** [comment]
@robertorp consegui sim, usei o delegate e funcionou!

Ontém logo depois que eu tentei eu tinha escrito aqui que deu certo. Por algum motivo não funcionou, talvez na hora eu tenha tido problema com a internet e achei que tinha comentado e fechado esse ticket.

Obrigado e um abraço.
