### ISSUE TITLE
Estado não homologado pelo sistema para utilização da SEFAZ

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#601]
Fomos emitir para o RIO grande do SUL e deu esse erro de retorno.

Enfim.. queria saber se alguém já passou por isso e como solucionou?

**Comment by orochasamuel** [comment]
@robertorp você já emitia antes ou esta foi a primeira tentativa?

Se foi a primeira tentativa verifique se a empresa está cadastrada na SEFAZ para emissão da NFe/NFCe.

Algumas SEFAZ tem procedimentos diferentes para homologação dos docume tos fiscais.

**Comment by FabioRoesler** [comment]
Estranho... Utilizo a biblioteca aqui no RS e nunca tive problemas. Talvez seja alguma configuração.

**Comment by robertorp** [comment]
Bom saber, vamos verificar e deixo um feedback aqui

**Comment by robertorp** [comment]
Descobri aqui, nos fizemos algo diferente no nosso erp ai não estavamos setando as versões nem nada para o Zeus , na verdade nosso sistema aqui e um misto de Zeus e implementação própria hehe, ali tem um tiquim de Zeus ali tem outro tiquim nosso.. ate mesmo dentro de proprios métodos temos isso. Vamos dizer que são coisas que sentimos falta no Zeus e fizemos próprio mas coisas bem especificas para nos aqui.
