### ISSUE TITLE
Autorização NFCE  em PE

### ISSUE THREAD

**Issue by felipepimentel** [ZeusAutomacao/DFe.NET#602]
Boa tarde, 

Já emito algumas notas em São Paulo. Ao tentar, emitir em PE (Modificando apenas a UF), obtive o seguinte erro: 

"Serviço NFEAutorização, Versão 3.10, não disponível para a UF PE, no ambiente de Produção para emissão tipo Normal, documento NFC-e".

Alguém já passou por isso?

**Comment by orochasamuel** [comment]
No ambiente de homologação funciona?

**Comment by felipepimentel** [comment]
@samuelrochaoliveira Abri o AppTeste do Zeus para validar. Percebi que todos os serviços em PE, seja em homologação ou produção, retorna o mesmo problema. Como mostra imagem: 

![image](https://user-images.githubusercontent.com/191153/33172825-c8db9fec-d038-11e7-97df-6a5f7ef3653f.png)

**Comment by rftd** [comment]
Este erro é que as URL para NFCe para este estado não existe no código fonte do Zeus, tem que ser adicionadas.

**Comment by felipepimentel** [comment]
Perfeito @rftd . Irei verificar essa alteração. Sabe informar se o fato de PE utilizar NFCE da SVRS pode influenciar em algo desse resultado?

**Comment by rftd** [comment]
se você verificar no codigo tem outros estados usando o webservice do RS também é so fazer igual eles
Ex.: RJ

**Comment by felipepimentel** [comment]
Perfeito @rftd!!!

**Comment by adeniltonbs** [comment]
@felipepimentel. Emissão de NFCe para PE foi adicionada no commit 624d6ca.

Veja imagem abaixo:
![image](https://user-images.githubusercontent.com/6733483/33484349-9ee8d602-d680-11e7-9704-ce8ffe3e6c8b.png)
