### ISSUE TITLE
Adicionar campos na impressão do DANFE [Fast]

### ISSUE THREAD

**Issue by lehfrz** [ZeusAutomacao/DFe.NET#604]
Boa noite, sou novo no C#, e gostaria de uma ajudinha...
Estou utilizando o Danfe Fast, e gostaria de saber como eu posso fazer para adicionar campos que não estou contidos no XML da NF-e.
Por exemplo preciso colocar a referencia de fornecedor e a marca nos itens da tag [det]...
Alguém pode me dar uma direção?

**Comment by rftd** [comment]
A Danfe não pode conter nada que não esteja no xml no seu layout.
Para adicionar mais informações a descrição do produto use a Tag infAdProd que o mesmo devera aparecer na impressão.

**Comment by lehfrz** [comment]
Obrigado pelo retorno!
