### ISSUE TITLE
The underlying connection was closed

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#605]
![whatsapp image 2017-11-29 at 08 40 34](https://user-images.githubusercontent.com/15945003/33372910-c630811a-d4e6-11e7-8ee7-76ff8e59748d.jpeg)

Estou recebendo este problema em um cliente específico a 2 dias, isto está ocorrendo nas duas máquinas do cliente. Tentei trocar a versão do .Net da 4.6.1 instalada para a  4.7.1 (mais atual), tentei instalar todas as cadeias de certificado possíveis, etc.

O certificado é A3, se eu plugo ele na minha máquina mesmo estando na rede do cliente o mesmo funciona normalmnete, na máquina do cliente não.

Removi a senha que estava pré configurada no sistema para acessar o certificado A3 e ao tentar **CONSULTAR** notei que o certificado não chega a pedir a senha.

O emissor gratuito do Sefaz funciona.

**Comment by adeniltonbs** [comment]
Boa tarde @marcosgerene.
Seu problema parece está relacionado ao protocolo de segurança aceito pelo webservice. Já tentou configurar a conexão para usar TLS 1.2? 
Obs: Se já estiver com TLS 1.2, tente mudar para outras versões ou para SSL3

A classe NFe.Utils.ConfiguracaoServico tem uma propriedade chamada ProtocoloDeSeguranca que especifica qual protocolo de segurança que deve ser utilizado no consumo dos webservices. Na aplicação de exemplo, é possível definir o protocolo a ser utilizado, na aba "WebService", conforme imagem abaixo:
![image](https://user-images.githubusercontent.com/6733483/33389324-41ceb0a6-d511-11e7-83a4-e8aa1855eb2b.png)

Veja esses tópicos:
https://stackoverflow.com/questions/30664566/authentication-failed-because-remote-party-has-closed-the-transport-stream

https://stackoverflow.com/questions/35621686/authentication-failed-because-the-remote-party-has-closed-the-transport-stream-e

**Comment by marcosgerene** [comment]
@adeniltonbs tentei mudar para todas as opções existentes, ssl3, tls, tls1.1 tls 1.2 e aquela opção que usam todos ao mesmo tempo.

O que mais me intriga ter começado de uma hora para outro 2 pcs de um cliente e em outro PC de outro cliente, enquanto os outros clientes estão trabalhando sem dificuldade.

**Comment by adeniltonbs** [comment]
Outro dia tive problemas com alguns clientes onde as aplicações .NET tinham seu tráfego redirecionados para um IP da nova Zelândia. O problema ocorreu em alguns clientes que possuíam um determinado modelo de roteador D-Link. Foi chato para descobrir por que o erro indicava aparentemente uma negação por parte do servidor remoto(que acreditávamos ser a SEFAZ).

Se for esse o caso, podes fazer o seguinte teste:
Peça para o cliente desligar a internet dele e conectar o PC na NET 4G, por exemplo.
Daí teste a aplicação. Se funcionar normalmente, o problema está no roteador ou no provedor dele.

Nos casos desses clientes, resetamos o roteador, atualizamos o firmware e mudamos a senha.

Descobrimos que mesmo antes de resetar o roteador, atualizar e etc, se desmarcássemos as configurações da LAN do internet explorer "Detectar automaticamente as configurações", tudo voltava a funcionar normalmente.

![image](https://user-images.githubusercontent.com/6733483/33430523-8d701d4e-d5af-11e7-922b-d0efbab1ddae.png)

**Comment by marcosgerene** [comment]
@adeniltonbs acredito não estar relacionado a rede pois me conectei na rede do cliente com meu computador e consegui fazer o processo normalmente, na verdade acredito que tenha alguma configuração no computador em si.

Tem como eu fazer algum teste no computador específico para saber qual rota ele está usando neste caso?

**Comment by adeniltonbs** [comment]
@marcosgerene Tem sim, use o Microsoft TCPView. Pode ser baixado aqui: https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview

Veja o resultado com a aplicação de testes do projeto:
![image](https://user-images.githubusercontent.com/6733483/33431558-8f8bf158-d5b3-11e7-84eb-4ac6c2b9676a.png)

**Comment by marcosgerene** [comment]
Boa tarde @adeniltonbs, baixei o programa, fiz um teste na minha máquina e tive um resultado igual ao seu.

Até ai beleza, a questão agora é como fazer com o cliente? este TCP View vai acusar algum erro? ele vai mostrar um Remote Adress diferente? como devo interpretar isto?

Provavelmente hoje eu esteja com a máquina do cliente em mãos após as 17h, efetuarei alguns testes na minha rede, como eu disse anteriormente minha máquina funciona na rede deles, preciso ver se máquina deles funciona na minha rede.

**Comment by marcosgerene** [comment]
@adeniltonbs acabei de ter a confirmação que o problema está na maquina do cliente, em outra maquina do mesmo cliente, o mesmo sistema na mesma rede funcionou, isto é um ponto positivo, vou testar esse pc aqui hoje, levando em consideração isto, qual dica poderia me dar a mais?

**Comment by adeniltonbs** [comment]
> Até ai beleza, a questão agora é como fazer com o cliente? este TCP View vai acusar algum erro? ele vai mostrar um Remote Adress diferente? como devo interpretar isto?

Se o TCPView mostrar um endereço diferente quer dizer que tem algo no PC redirecionando as conexões para outro lugar. Daí é remover o(s) vírus ou formatar.

Outra coisa que podes fazer é ver com o cliente a partir de quando parou de funcionar e daí ver se programas foram instalados ou o Windows foi atualizado num período imediatamente anterior. Se for esse o caso, restaurar o Windows para um ponto antes do problema começar pode ser uma opção.

**Comment by marcosgerene** [comment]
Testei agora com o ACBRCTe_Demo e recebi o erro 12157, isto é bom porque mostra que o erro não é no .Net. 

E a grande vantagem é que o ACBr tem um forum grande, da para pesquisar melhor a origem do erro em portugues e voltado para DFes.

Outra coisa, tentei acessar a url do webservice pelo IE, ele pede o certificado mas não pede a senha e já cai na página de erro

**Comment by marcosgerene** [comment]
Fiz tudo e mais um pouco do que tinha disponivel na internet para ser feito nestes casos e não deu certo, vou solicitar ao cliente que formate o computador.

Obrigado @adeniltonbs

**Comment by rodrigordi** [comment]
@marcosgerene , essa maquina que está com problema tem qual .net instalado ? Qaundo eu fiz um projeto CTe 3.00 para um cliente meu, eu coloquei que só ia aceitar TLS1.2, ai não conectava por nada. Dai, mudei para SSL3, mesma coisa. por fim, eu parei de setar o ServiceManager, e funcionou na máquina que estava dando problema. Na minha maquina (win10) e na maquina do Dev do cliente (win 10), funcionava de qq jeito. O problema sempre acontecia na maquina do faturamento (win 7) que tinha um .NET diferente do nosso. O problema da NFe 4.00 que só funcionará com TLS 1.2. O Cte 3.00 ainda funciona com SSL.

Será que voce consegue comentar a linha que configura o ServiceManager e tentar rodar nessa máquina com problema ? 

Abraços.

**Comment by marcosgerene** [comment]
@rodrigordi infelizmente não tenho mais acesso à máquina, mas acredito que não seja algo que eu esteja fazendo ao setar o protocolo, pois nem o IE acessa, chega a pedir para selecionar o certificado, mas quando escolho o certificado aparece a falha direto, nem a senha pede...

**Comment by rodrigordi** [comment]
No meu caso o IE tbm não funcionava. E funcionava via chrome.

**Comment by marcosgerene** [comment]
Hoje ao devolver a máquina paro o cliente e avisar que a mesma deveria ser formatada, resolvi fazer um ultimo teste pelo IE novamente... e funcionou...

Entrei no sistema, setei SSL3 algo que eu ja havia feito antes) e funcionou normalmente... fiz várias coisas, desde reabilitar o firewall, colocar o sistema nas exclusões do Kaspersky, mudar a versão do .net, alterar o dns, restaurar as configs do IE e nada funcionava, hoje funcionou.

Acredito que algo que eu fiz e não reiniciei para testar solucionou o problema, mas fiz tantas coisas que não consigo documentar... 

Obrigado a todos pela ajuda, principalmente ao Sr. @adeniltonbs
