### ISSUE TITLE
Ipi Devolução

### ISSUE THREAD

**Issue by AllanDavini** [ZeusAutomacao/DFe.NET#606]
Boa Tarde,

Estou com uma dúvida quanto a uma nota de devolução cujo é necessário destacar o IPI, na documentação diz para destacar no campo vIpiDevol, este campo não consta no projeto? ou eu estou utilizando de maneira errada ?

Obrigado.

**Comment by adeniltonbs** [comment]
Bom dia @AllanDavini 
O campo "vIpiDevol" se encontra na classe https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Classes/Informacoes/Detalhe/IPIDevolvido.cs

**Comment by AllanDavini** [comment]
Obrigado.
