### ISSUE TITLE
ConfiguracaoServico > Instancia() - Porquê singleton?

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#607]
Olá @adeniltonbs / @robertorp .
Como vão?

Estou criando um microservice ASP.NET, que irá receber chamadas HTTP solicitando emissão de notas fiscais.
O ambiente será concorrente, e poderão ser solicitadas a emissão de inúmeras notas simultaneamente.

Mas me deparei com um problema:
A classe ConfiguracaoServico usa o pattern [ **singleton** ]. O que impede a criação de várias instâncias, em ambiente concorrente.
Então fiquei curioso, é mesmo necessário o uso desse pattern?

Achei curioso também o uso da palavra-chave volatile, na [ **_instancia** ]. O **volatile** torna a _instancia thread safe?

```csharp
public sealed class ConfiguracaoServico : IDisposable
    {
        private static volatile ConfiguracaoServico _instancia;
        
```

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira  tudo bom? 
Nos tivemos um pull que você escolhe se quiser utilizar singleton.. bom da para usar em ser singleton, agora não podemos mudar de um minuto para o outro essa estrutura para não quebrar as aplicações que já existem. Mas de uma analisada no pull https://github.com/ZeusAutomacao/DFe.NET/pull/522

atualização da issue: existe dois testes de unidade que exemplificam isso

**Comment by adeniltonbs** [comment]
@samuelrochaoliveira Na época que fiz a biblioteca não previ seu cenário de uso. Na verdade a aplicação que temos aqui não vai por esse caminho. 
Já que não tinha em mente o uso em thread para multiempresas, fazia mais sentido a configuração ser singleton. Aliás, num cenário de uso para única empresa não via sentido permitir mais de uma instância da configuração.

O singleton foi implementado de forma a ser thread safe, conforme documentação da msdn (https://msdn.microsoft.com/en-us/library/ff650316.aspx).

**Comment by orochasamuel** [comment]
Bom dia, obrigado pelas respostas. o/

**Comment by orochasamuel** [comment]
Apenas uma [documentação](http://csharpindepth.com/articles/general/singleton.aspx) extra.
