### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by f103mirage** [ZeusAutomacao/DFe.NET#610]
Bom dia,

meu programa está rodando perfeitamente com o Zeus.Net. Só que estou com problema de Memory Leak...  

no início do dia é tranquilo.. mas no final do dia o processo já está consumindo mais de 2GB de memória RAM.... estou utilizando o USING apenas no ServicosNFe, q eh disposable..

já fiz uns testes e o problema no memory leak está acontecendo nesse trecho:

            try
            {
                CfgServico.tpEmis = emissaoTipo;

                _nfe = montaNfce(movid, proximoNumeroNFCe(movid), CfgServico.ModeloDocumento, CfgServico.VersaoNFeAutorizacao);
                _nfe.Assina();
                _nfe.infNFeSupl = new infNFeSupl() { qrCode = _nfe.infNFeSupl.ObterUrlQrCode(_nfe, configuracaoCsc.CIdToken, configuracaoCsc.Csc) };
                _nfe.SalvarArquivoXml(diretorioMesAtual + _nfe.infNFe.Id + ".xml");
                associaMovid(movid, proximoNumeroNFCe(movid), _nfe.infNFe.Id, emissaoTipo);

                retorno = true;
            }
            catch (Exception ex)
            {
                retorno = false;
                clsLog.inserir(ex.Message);
                MessageBox.Show(ex.Message, "Gerenciador NFC-e", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.ServiceNotification); 
            }

alguma sugestão? obrigado

abraço,

**Comment by marcosgerene** [comment]
@f103mirage Qual seu volume de nfe diário? Rodo a biblioteca em PDV de supermercado com NFCe, emito por volta de 200 nfces/dia/pdv em máquinas fraquíssimas, rodando inclusive com TEF junto e não tenho problemas com Memory Leak... acredito que o problema esteja na aplicação e não na biblioteca.

1. O que faz esse "associaMovid"?
2. O que faz esse "clsLog.inserir(";

Já tentou chamar um GC.Collect após emitir o DFe?

**Comment by f103mirage** [comment]
Marcos,

rodei o Performance Profiler do Visual Studio 2015 e não apontou nenhum problema no meu código... Apontou problema nos seguintes métodos externos (Zeus.Net)... 

DFe.Utils.FuncoesXml::ClasseParaXmlString
DFe.Utils.FuncoesXml::XmlStringParaClasse
NFe.Danfe.Nativo.NFCe.DanfeNativoNfce::CarregarXml

não está liberando memória RAM ao final da NFC-e... minhas máquinas são potentes, tem 16GB de RAM... a cada nova NFC-e está aumentando em média 20MB de RAM e não libera.. aí no final do dia alcança 2GB fácil... o sistema não fica lento nem nada.. mas essa performance não está ok... mesmo numa máquina potente era pro programa não usar mais de 100MB....

só fui perceber pq meu sistema gera vários alertas de comportanto estranho, performance, etc...

fico no aguardo... abraço...

![02](https://user-images.githubusercontent.com/34276801/33622830-11727e6e-d9d6-11e7-921b-4e03cfc56aa3.png)
![01](https://user-images.githubusercontent.com/34276801/33622826-0dc5d040-d9d6-11e7-8dcc-8b9f38f74cdd.png)

**Comment by f103mirage** [comment]
no próprio site da microsoft tem a descrição do problema e como corrigi-lo... se puderem avisar aqui quando sair a correção pra esse bug, ficaria agradecido..

abraço

![03](https://user-images.githubusercontent.com/34276801/33623915-c23fd81a-d9d9-11e7-9363-ef8b25f98309.png)

**Comment by marcosgerene** [comment]
@f103mirage interessante, até então eu não tinha ciência disto, vivendo e aprendendo...

Acredito não devo sofrer por isso porque chamo um GC.Collect() após a emissão do documento, como faço tudo de forma sincrona (não tenho threads para emissão nos pdvs, somente para carga) posso lançar mão deste recurso.

Acredito que o @adeniltonbs ou o @robertorp podem responder sua questão melhor... ou se você mesmo pode propor uma solução abrindo uma pull request.

Abraços

**Comment by robertorp** [comment]
Fim de semana vou verificar isso! mas por favor alguém poste algo aqui no fim de semana para eu me lembrar. Obrigado. (se eu não lembrar vou lembrar, se eu lembrar bom vou lembrar)

**Comment by robertorp** [comment]
Poderia testar para nós? 

@f103mirage 

[FuncoesXml.txt](https://github.com/ZeusAutomacao/DFe.NET/files/1545937/FuncoesXml.txt)

**Comment by f103mirage** [comment]
Boa noite Roberto,


até terça-feira tô enrolado.. Mas na quarta devo testar e te aviso... Mas pelo que vi do código agora vai ficar 100%... o ideal era armazenar em cache mesmo...


Abraço e obrigado...


________________________________
De: Roberto Alves Pereira <notifications@github.com>
Enviado: domingo, 10 de dezembro de 2017 16:43
Para: ZeusAutomacao/DFe.NET
Cc: f103mirage; Mention
Assunto: Re: [ZeusAutomacao/DFe.NET] Memory Leak (#610)


Poderia testar para nós?
FuncoesXml.txt<https://github.com/ZeusAutomacao/DFe.NET/files/1545937/FuncoesXml.txt>

**Comment by robertorp** [comment]
blz, amanhã vou subir ele para o repositório também.

adicionado cache já, agora vou somente aguardar um feedback seu @f103mirage , obrigado

**Comment by robertorp** [comment]
Somente deixando um feedback aqui, no grupo do skype uma pessoa fez a mesma reclamação atualizou os fontes e disse estar perfeito.

**Comment by f103mirage** [comment]
excelente.. parabéns pelo projeto

**Comment by f103mirage** [comment]
acabei de fazer alguns testes... várias NFC-e emitidas e programa não usou mais que 50mb de RAM em momento algum... :)

problema resolvido

**Comment by robertorp** [comment]
@f103mirage  Somente uma questão, pois vi que algumas pessoas não deram o problema e já outras deram, Teu sistema era desktop ou web? As que deram no geral não utilizavam nfc-e utilizavam alguma outra rotina envolvendo serialização de xml enfim e somente pra saber mesmo. Se poder me dizer e claro.

Obrigado.

**Comment by f103mirage** [comment]
opa roberto... 

desktop... .net framework 4.5.. máquinas com windows 7 e windows 10...

**Comment by jvretamero** [comment]
@robertorp, apenas para contribuir com um relato meu, e que provavelmente é uma situação próxima do @f103mirage:

Nossa equipe passou por um problema similar, onde geramos lotes de CTes de uma só vez, porém a criação do `XmlSerializer` é muito pesada, e como consta na documentação, assemblies são gerados e nunca liberados.

Passamos a criar o `XmlSerializer` apenas 1 vez durante o processo e o problema foi resolvido.

Acredito que a situação do @f103mirage também seja devido à frequência de execução da serialização.

E obrigado pela correção, ficou até melhor do que a solução que implantamos.
