### ISSUE TITLE
[DÚVIDA] CPF na NFC-e/ou não?

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#614]
Pessoal,

Quando é uma emissão de NFC-e e o consumidor não solicita a identificação com CPF o que informar? 999.999.999-99?

O que vocês estão informando? Ou simplesmente não informada nada?

Abraços.

**Comment by leandrossantos** [comment]
Basta não montar o bloco dest, monta o XML sem o bloco dest

---

Atenciosamente,


*Leandro Santos*

2017-12-12 15:40 GMT-04:00 Samuel Rocha de Oliveira <
notifications@github.com>:

**Comment by orochasamuel** [comment]
Obrigado @leandrossantos.
