### ISSUE TITLE
Erro : A senha de rede especificada não esta correta

### ISSUE THREAD

**Issue by davidrock** [ZeusAutomacao/DFe.NET#615]
Quando eu clico em "Criar e Enviar 3.0", preencho o numero da Nota e o Id do Lote, ele me retorna essa mensagem. Que "senha de rede" é essa ??
Tbm tentei ir no "Criar e Enviar 2.0" mas a aplicação parou de responder.

**Comment by facilita-tecnologia** [comment]
Boa noite Davi,

Manda um print da sua tela de configuração.

Outra pergunta qual tipo de certificado digital você esta utilizando A1 ou A3?

se for A1 configure o app teste para utilizar o certificado instalado no repositório do Windows nesse caso não precisa informar a senha.
