### ISSUE TITLE
Problema manter dados em cache

### ISSUE THREAD

**Issue by FabioRoesler** [ZeusAutomacao/DFe.NET#616]
Boa tarde
Este final de semana, atualizei as dll's do meu sistema, baixando a ultima versão do Zeus.
Porem agora quando deixo setado como 'true' a opção de manter dados em cache me ocorre o erro "Ja foi adicionado um item com a mesma chave.". Este erro sempre ocorre depois que ja emiti um cupom. Quando desmarco esta opção consigo emitir todos cupons sem problemas.
Será que mudou alguma coisa, porque sempre utilizei com a opção marcada e nunca tive problemas.
Se alguém tiver uma luz agradeço.

**Comment by robertorp** [comment]
Poste a parte do código seu em que vc cria a config do zeus para min estar analisado.

**Comment by FabioRoesler** [comment]
//Trecho do código de configuração do app
    public class ConfiguracaoApp
    {
        private ConfiguracaoServico _cfgServico;

        public ConfiguracaoApp()
        {
            CfgServico = ConfiguracaoServico.Instancia;
            CfgServico.tpAmb = TipoAmbiente.taHomologacao;
            CfgServico.tpEmis = TipoEmissao.teNormal;
            Emitente = new emit { CPF = "", CRT = CRT.SimplesNacional };
            EnderecoEmitente = new enderEmit();
            ConfiguracaoEmail = new ConfiguracaoEmail("email@dominio.com", "senha", "Envio de NFE", "", "smtp.dominio.com", 587, true, true);
            ConfiguracaoCsc = new ConfiguracaoCsc("0", "2", NfceDetalheVendaContigencia.UmaLinha, "", "");
        }

        public ConfiguracaoServico CfgServico
        {
            get
            {
                Funcoes.CopiarPropriedades(_cfgServico, ConfiguracaoServico.Instancia);
                return _cfgServico;
            }
            set
            {
                _cfgServico = value;
                Funcoes.CopiarPropriedades(value, ConfiguracaoServico.Instancia);
            }
        }

        public emit Emitente { get; set; }
        public enderEmit EnderecoEmitente { get; set; }
        public ConfiguracaoEmail ConfiguracaoEmail { get; set; }
        public ConfiguracaoCsc ConfiguracaoCsc { get; set; }
    }

// Aqui é onde carrego a configuração antes de emitir um cupom
        private void CarregarConfiguracao()
        {
            var path = @"Caminho do xml de configuração";
            if (!File.Exists(ArquivoConfiguracao))
            {
                _configuracoes = new ConfiguracaoApp();
            }
            else
            {
                _configuracoes = DFe.Utils.FuncoesXml.ArquivoXmlParaClasse<ConfiguracaoApp>(ArquivoConfiguracao);
            }
        }

//Parte do xml de configuração
![image](https://user-images.githubusercontent.com/24945244/34363070-e930f1a2-ea5f-11e7-94bc-65294893a250.png)

**Comment by robertorp** [comment]
tem um atributo novo <CacheId></CacheId> ou alguma coisa assim adiciona ele com um id unico para seu certificado digital <CacheId>333</CacheId>

**Comment by robertorp** [comment]
atributo = tag CacheId

edit: dentro da tag Certificado

**Comment by FabioRoesler** [comment]
Deu certo Roberto!
Valeu a ajuda, segue abaixo como ficou o arquivo de configuração!
![image](https://user-images.githubusercontent.com/24945244/34394524-f1d875be-eb40-11e7-9ab3-7a432cf3646a.png)
