### ISSUE TITLE
NFe se torna inválida após aplicação de ObterUrlQrCode()

### ISSUE THREAD

**Issue by davidrock** [ZeusAutomacao/DFe.NET#617]
Olá amigos, estou com um problema muito estranho aqui.
Após preencher a nota, executo o método Valida() para Validar a nota e fica tudo OK, porém após aplicar o UrlQrCode a nota se torna Invalida.

![image](https://user-images.githubusercontent.com/19226926/34426558-164fbcf2-ec1f-11e7-9aa2-40c2e704710d.png)

Fiz um teste com um outro xml de uma nota VALIDA que foi enviada com sucesso pelo sistema de um amigo, importei no NFe.AppTeste e tentei enviar, recebi o mesmo erro:

![image](https://user-images.githubusercontent.com/19226926/34426617-8795c35c-ec1f-11e7-9956-99be370a378a.png)

Alguém já passou por isso?

**Comment by davidrock** [comment]
O problema eram os Schemas, baixei novamente de outro lugar, substituí e funcionou

**Comment by robertorp** [comment]
Poderia disponibilizar os schemas para nos?
