### ISSUE TITLE
[CTe] ProxyCEP para a classe enderToma

### ISSUE THREAD

**Issue by jvretamero** [ZeusAutomacao/DFe.NET#618]
Em todas as classes de endereço o CEP é do tipo `long`. Mas somente a classe `enderToma` não faz uso do `ProxyCEP` para formatação dos 8 dígitos do CEP.

O que acham de colocar o `ProxyCEP` nesta classe?

Esta propriedade é interessante para manter a consistência com as outras classes de endereço e também com o schema.

*Obs:* Se necessário, posso fazer o **PR**.

**Comment by robertorp** [comment]
Fique a vontade para fazer o pull analisarei o mais rápido possível. Ultimamente estava ocupado na NFe4 agora estou tranquilo enquanto a isso.

**Comment by jvretamero** [comment]
Beleza, logo faço o PR.
