### ISSUE TITLE
Emissão em Contingência desde 30/12/2017

### ISSUE THREAD

**Issue by adrbarros** [ZeusAutomacao/DFe.NET#619]
Bom dia alguém com esse problema:
No dia 30/12/2017 por volta das 10h00, todas as emissões NFC-e (Produção) dos clientes que tenho no RN, MA, PA (que utilizam a SEFAZ do RS) estão saindo em contingências.

Erro acontece na Autorização (Exceção de Comunicação por tempo excedido), mesmo aumentando o timeout para 1min ainda acontece a mesma exceção

No portal deles constam que os serviços estão todos OK

Em Ambiente Homologação está OK.

**Comment by marcosgerene** [comment]
Enfrentei o mesmo problema no sábado (31/12) no mesmo horário, mas normalizou no sábado mesmo no final da tarde
