### ISSUE TITLE
NFe Dlls versão

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#620]
a versão das dll no pacote nuget não estão sendo atualizados

**Comment by robertorp** [comment]
O ultimo commit foi feito a 20 dias, a ultima versão do nuget foi feita a 20 dias

**Comment by ThalisonSantos** [comment]
sim eu sei mas, se vc verificar onde instala as versões nuget as dlls da ultima versão do nuget tem a mesma versão da anterior

**Comment by robertorp** [comment]
não temos controle hoje de versionamento da DLL em si nos assemblys

**Comment by ThalisonSantos** [comment]
@robertorp  eu uso o installshield LE para criar instalador para minha aplicação e se as versões ficarem igual o instalador não atualiza os arquivos

**Comment by robertorp** [comment]
Bom e algo a se pensar o controle das dll. Vou ver aqui com carinho, mas quero algo meio automático ou algo que barre o lançamento forçando eu a lembrar da versão da DLL

**Comment by ThalisonSantos** [comment]
@robertorp  eu não tenho projeto de bibliotecas mas creio que o próprio visual studio tenha soluções para isso

**Comment by ThalisonSantos** [comment]
@robertorp pesquisando na net encontrei esse tópico que resolve o problema de versionamento, da uma olhada
http://www.andrealveslima.com.br/blog/index.php/2016/11/23/como-incrementar-o-numero-da-versao-automaticamente-no-visual-studio/

**Comment by robertorp** [comment]
ok analisando aqui 
  
Achei bacana, mas ainda sim temos um problema concorrência, todos aqui vão fazer push e verões anteriores e posteriores conflitando sempre. Mas vou dar uma pesquisada se existe alguma maneira de resolver isso. (Não testei só disse isso com base no que li)

**Comment by alexsandro-xpt** [comment]
Sei que controlar versionamento é um negocio complicado pelo menos para o VS.
Já tentaram via XML através dos arquivos .config do Nuget?

**Comment by robertorp** [comment]
Na verdade quero algo que o proprio appveyor faça. Quando gerar build ele se vira. Vou ver isso.

**Comment by ThalisonSantos** [comment]
@robertorp  nesse tópico tem uma extensão que faz isso automaticamente você decide qual o parâmetro e toda build ele vai incrementar.

**Comment by acgfbr** [comment]
Eu uso esse aqui no trabalho:
 [DllImport("wininet.dll")]
        private extern static bool InternetGetConnectedState(out int Description, int ReservedValue);

        public static bool CheckForInternetConnection()
        {
            int Desc;
            return InternetGetConnectedState(out Desc, 0);
        }


Ele usa uma dll do própio windows pra verificar, o CheckForInternetConnection retorna true se tiver internet e false caso não consiga conectar em nada.

**Comment by robertorp** [comment]
Vou estar atualizando as dll sempre que for lançar versão. Todas DLL terão a mesma versão ou seja.. sempre que lançar um release vai ter uma versão nova na dll acompanhando a versão do nuget.
