### ISSUE TITLE
ConsultaProtocolo versão 3.10 Erro: Server was unable to process request. object reference not set to an instance of an object

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#623]
Bom dia.
Desde ontem a partir das 16 horas todos os meus clientes estão recebendo o erro na requisição:
_Server was unable to process request. object reference not set to an instance of an object_
estou usando a versão 3, ainda não atualizei para a versão 4.
Alguém sabe do que se trata?

**Comment by robertorp** [comment]
Não tem versão 4 no Zeus ainda.
Isso pode ser algo seu não digo um erro seu de logica? Aqui tenho mais de 400 clientes finais utilizando o zeus e não tem reclamações.

**Comment by rodrigordi** [comment]
tem um problema na SEFAZ-SP para versão 3.10. corrigiram producao agora a pouco. em homologacao ainda existe. estava acontecendo no serviço consultaprotocolo.

**Comment by FabioHenriqueMF** [comment]
isso mesmo @rodrigordi . o problema estava em produção e homologação no consulta protocolo
agora estou testando em homologação e ainda continua

**Comment by rodrigordi** [comment]
@FabioHenriqueMF , eu fiz contato com a sefaz sp hoje. eles foram bem rapidos para resolver o problema da produção. não sei quanto tempo vai levar para resolver em homologação. mas o problema é na sefaz.

![image](https://user-images.githubusercontent.com/1608626/34738477-410a0d18-f560-11e7-83e6-b580d38a71d1.png)

**Comment by robertorp** [comment]
Fico indignado como conseguem errar com esse tipo de coisas, isso são milhões e milhões em impostos, sera que só tem 2 desenvolvedores tomando conta disso? Enfim não e o caso mas e um descaso.

**Comment by FabioHenriqueMF** [comment]
Realmente é uma vergonha.  Atendimento deles é péssimo.  Sempre empurrando pros sistemas nossos. SEFAZ é um descaso total mesmo.

**Comment by rodrigordi** [comment]
voce fez o que ? ligou no 0800 ?

**Comment by FabioHenriqueMF** [comment]
Liguei, passei e-mail.  Fiz tudo menos trabalhar em paz hoje

**Comment by rodrigordi** [comment]
eu mandei email e foi até rápido. mas foi tenso pracaramba. quando é problema na produção, vem todo mundo em cópia nos emails. fiquei de 13:30 até as 17:30 olhando isso.

**Comment by robertorp** [comment]
Hmm, Mas tiveram final feliz?

**Comment by rodrigordi** [comment]
Somente em produção. Agora tem dois times tentando fazer testes diferentes em homologação e ainda tem o problema. O jeito mais fácil de entrar em contato com a sefaz-sp é via fale conosco no portal. Colocar problemas tecnicos, informar a url do problema, mensagem de envio, mensagem de retorno. Quanto mais gente falando a mesma coisa, mais rapido eles devem verificar. Ou nao. :/

**Comment by FabioHenriqueMF** [comment]
esses caras são muito lerdos man, liguei ontem diversas vezes, uns falam que tava normal, outros falam que havia chamados técnicos. Realmente estamos sozinhos nesse sentido, e pior que dependemos 100% deles

**Comment by rodrigordi** [comment]
abre um chamado aqui : https://www.fazenda.sp.gov.br/email/default_nfe.asp, coloca problema tecnico e deixa eles responderem. voce fez isso ? acho que quanto mais gente reclamando disso, mais rapido eles vao precisar resolver.

**Comment by rodrigordi** [comment]
problema parece que foi resolvido. já consigo receber os 217 em homologacao.
