### ISSUE TITLE
Problemas com o MT - Cancelamento

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#625]
Bom dia, hoje percebi que ao tentar cancelar uma nota no MT no ambiente de HOMOLOGAÇÃO tive um problema dizendo que não está disponível o serviço, porem fui tentar cancelar em ambiente de produção e obtive o mesmo problema conforme segue print.

Ah outro detalhe... o conteúdo disponibilizado nos pacotes nuget, não são os mesmos do conteúdo compilado pelo projeto baixado (ou seja), quando baixamos o projeto, o resultado é um ao pegar as DLLs compiladas, e quando pegamos o pacote nuget é outro, com varios bugs.

![image](https://user-images.githubusercontent.com/11932503/34906370-230cc61e-f84b-11e7-9c15-a26a3e3af338.png)

**Comment by robertorp** [comment]
Correção => https://github.com/ZeusAutomacao/DFe.NET/pull/626
Faça o teste por favor
