### ISSUE TITLE
Versão 4.0

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#628]
Olá Boa tarde,

Primeiramente parabéns pela iniciativa do projeto! Gostaria de saber se já estão implementando a versão 4 da NFe e se sim, se tem alguma previsão para estar no repositório.

Att,
Guilherme

**Comment by eduprog** [comment]
Amigo, acho este pull responde sua pergunta.
#503
https://github.com/ZeusAutomacao/DFe.NET/pull/503

**Comment by robertorp** [comment]
Zeus vai ter duas verões. 
Essa que o @eduprog  postou e a atual vai continuar também com nfe4. 
As duas versões serão mantidas por um tempo determinado apos terminarmos. 
E sim vai ter nfe4.0

**Comment by gui-abrantes** [comment]
certo, obrigado...então vc´s irão iniciar tb um novo projeto?? se sim, vale a pena esperar pelo novo projeto, ou não tem uma expectativa ainda para ou outro projeto?

**Comment by robertorp** [comment]
Não vale a pena esperar o novo.. pode ser que demore um pouco mais que o antigo. 
Quando o novo ficar pronto vamos dar prazos grandes e generosos mantendo duas versões.
