### ISSUE TITLE
A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS.

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#629]
Olá boa tarde,

Baixei os fontes pra testar, estou executando o Nfe.AppTest, e por enquanto estou executando somente o status serviço. Mas dá seguinte mensagem de erro: "A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS."

-Meu certificado (A1) não está vencido;
-A cadeia raiz de certificado, no meu caso de MG (baixei lá da SEFAZ de MG) está instalada;
-Já tentei pelo arquivo e pelo número de série;
-Meu computador é Win10 atualizado;
-Todos os dados do emitente estão completos e corretos;

Tem alguma outra coisa que possa fazer?

Att,
Guilherme

**Comment by robertorp** [comment]
Troca o protocolo de comunicação

**Comment by gui-abrantes** [comment]
Esqueci de falar que tava usando o SSL3, desculpe...
Mas quando troco pra TLS, a mensagem muda:

A conexão subjacente estava fechada: Não foi possível estabelecer relação de confiança para o canal seguro de SSL/TLS.

**Comment by robertorp** [comment]
E os outros protocolos? Pois já passei por casos em que o SSL3 e TLS 1.2 não funcionavam mas o TLS 1.1 funcionou. (se me perguntar como respondo: cara sefaz sendo sefaz, nada de anormal)

edit: https://serasa.certificadodigital.com.br/teste/ teste o certificado digital também
edit2: talvez tenha algo aqui também http://www.robertorp.com.br/2017/10/erro-comun-no-framework-zeusnetnfenfce.html

**Comment by FelipeSpinelli** [comment]
Eu tive o mesmo problema e a solução pra mim foi importar a cadeia raiz de certificado. Eu posso te enviar quando eu chegar em casa. Mas, tenta importar ao invés de instalar, pra mim funcionou.

**Comment by robertorp** [comment]
@gui-abrantes  solucionou? se sim qual foi a solução utilizada por você ?

**Comment by gui-abrantes** [comment]
oi @robertorp desculpe de não ter dado o retorno! Cara, to batalhando aqui ainda, nao sei o que é...fiz o que @FelipeSpinelli falou...mas mesmo assim nada! Não tem como eu testar meu certificado como vc falou, pq o meu é A1, e estive olhando aqui, somente nos estados CE, PE, SP, PR, MT funcionam! O meu q é MG e os outros estados dá a mesma msg.

*Lembrando que já instalei (e também importei) a cadeia raiz para o meu estado que é disponibilizado na SEFAZ do meu estado.

Obrigado.

**Comment by robertorp** [comment]
MG tivemos problemas aqui com uma revenda era somente atualizar cadeia de certificado. E geralmente nos instalamos o certificado digital na maquina e utilizamos ele através do repositório. Acho que já passei por problemas de protocolo de comunicação também, você esta instalando corretamente as cadeias de certificado digital? Tem esse detalhe também e não e somente importar em qualquer lugar tem o local.

**Comment by gui-abrantes** [comment]
Testei de duas formas buscando o arquivo, e buscando através do numero de serie dele (repositório)! Sobre as cadeias eu instalei as disponíveis na propria SEFAZ (uma delas é raiz v5) não deu certo! Instalei a v2 disponivel no site do serasa!
Não contentando fiz o mesmo processo em casa....deu a mesma coisa! Pois fiquei com medo de ser alguma coisa da rede aqui da empresa!

**Comment by robertorp** [comment]
Sabado dia 27 depois das 11 da manhã se quiser pode entrar em contato comigo, skype: robertoalves18@hotmail.com posso estar fazendo um acesso remoto para verificar. Pois esse caso seu e novidade para min não funcionar com os métodos casuais que vejo aqui.

**Comment by gui-abrantes** [comment]
Oi @robertorp bom dia!

Então consegui finalmente descobrir o erro aqui! É o seguinte, quando instalei o certificado raiz v5 (que é o que minas gerais exige) ele caiu no repositorio de "Autoridades de Certificação Intermediária", pra mim tudo bem, pq geralmente a gente vai no automático, rsrsr! Mas depois de tanto sofrer, criei um projetinho e fui tentar adicionar uma Referencia de Serviço bem básico em cima do webservice de consulta status, daí ele me deu o erro que o certificado "AC Certisign Multipla SSL" não tinha escolhido como confiável, só daí eu atentei que o raiz dele era o v5 e não v2!
Importei novamente para dentro do repositório de "Autoridade de Certificação Raiz Confiáveis" e funcionou....pelo menos agora está comunicando!

Muito obrigado pelo empenho em tentar me ajudar! Agora vou dá uma estuda no projeto de vc´s pq sou ainda meio novo em webservice e certificados! E estou no aguardo ansioso pelo 4.0, pq aqui na empresa existe um já rodando 3.10 que outro desenvolvedor fez....mas já está meio difícil em dar manutenção, por isso que proponho em achar um projeto como esse onde todo mundo colabora!

Att,
Guilherme

**Comment by robertorp** [comment]
@gui-abrantes bom dia, perfeito que tenha funcionando. Qualquer coisa so ir abrindo issues e nos vamos tentando resolver na medida do possível.
