### ISSUE TITLE
NF-e 4 .00 NT_2016_002_v1.42 - alteração do prazo

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#630]
Boa tarde galera, acho que ja devem saber, mas pra quem não sabe o prazo de desativação da versão 3.10 foi adiado para 02/07/2018 conforme a NF 1.42.
Aproveitando pra perguntar se já possuem algum exemplo do método de Consulta Status Serviço por ex. para a versão 4,pois eu o fiz alterando os atributos mas o retorno está vindo vazio. (Alterei o protocolo para TSL 1.2 conforme a NF) ??/?

**Comment by adeniltonbs** [comment]
@robertorp está fazendo em https://github.com/robertorp/Zeus.Net.NFe.NFCe/tree/NFe4
