### ISSUE TITLE
WebServices 4.00

### ISSUE THREAD

**Issue by andersonssa** [ZeusAutomacao/DFe.NET#631]
Olá,

gostaria primeiro de parabenizar a inciativa da Zeus Automaçao, este projeto tem sido de grande utilidade para mim. Em segundo, gostaria de entender como voces descobrem aqueles namespaces que voces criam os servicos, aqueles namespaces do webbinding

**[System.Web.Services.WebServiceBindingAttribute(Name = "NFeStatusServico4Service", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4")]**

saber que o cabeçalho na versão 4.00 nao está mais sendo usado.
[Obsolete("Não é mais utilizado na nf-e 4.0")]
 **public nfeCabecMsg nfeCabecMsg { get; set; }**

retorno e metodo
[return:
 **System.Xml.Serialization.XmlElementAttribute("nfeResultMsg", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4")]
[System.Web.Services.WebMethod(MessageName = "nfeStatusServicoNF")]**

já tentei entender de muitas formas, talvez as palavras da minhas pesquisas nao estejam batendo para encontrar algo que ajude. De qualquer forma, se puderem esclarecer minha dúvida, agradeço desde já.

Atenciosamente, Anderson Machado

**Comment by robertorp** [comment]
Eu faço assim, baixo o wsdl e digito no Developer CMD do VS studio wsdl nomedoarquivo.wsdl 
com esse comando ele gera um arquivo de coomunicação com a sefaz (arquivos que forma gerados olha os wsdl do ct-e ou mdf-e eles foram gerados..) atravez disso pego os dados que estão la dentro e crio uma classe nova no Zeus NF-e seguindo o padrão dele.
