### ISSUE TITLE
Listar várias NFe em um grid

### ISSUE THREAD

**Issue by andersonssa** [ZeusAutomacao/DFe.NET#632]
Pessoal,

gostaria de saber como faço para poder listar todas ou as mais recentes nfe de um CNPJ em um grid e sair baixando a que eu escolher. Qual funçao eu devo utilizar para realizar essa listagem? Vi isso em um vídeo no youtube para VB, mas utilizaram uma biblioteca e nao tive acesso a quais metodos e url's que foram utilizadas.

Podem ajudar com isso? Desde já, agradeço a atençao de todos.

**Comment by robertorp** [comment]
No projeto NF-e e possível você somente visualizar todos os xmls emitidos nos ultimos 90 dias contra um CNPJ especifico. 

Ex: Você tem um CNPJ XXXX um fornecedor seu com CNPJ BBBB emite 20 NF-e para você no Cnpj XXXX ou seja...

Você é o destinatário

bom você sendo o destinatário e tendo o seu certificado digital e possível você manifestar as nf-e, após a manifestação e possível você baixar com a distribuição.

**Comment by andersonssa** [comment]
Seriam quais webservices necessários para isso? Vi em alguns comentarios que os webservices de manifesto ja foram desativados e que tem sido utilizado os do Ambiente Nacional.
A ideia é essa mesmo de listar as notas e baixar as que foram emitidas por meus fornecedores para mim.

**Comment by robertorp** [comment]
Manifestação Destinatário não esta desativo. 
Desativo foi Download NF-e esse se vc tentar ele esta desativo, ainda existe o método no Zeus, mas sera removido em uma oportunidade, por hora na verdade somente deixo o método lá porque não confio nas Sefazes, para elas voltarem tal serviço basta eles darem uma loucura.

**Comment by andersonssa** [comment]
E seriam quais webservices necessários para isso? Listar e Baixar, ou seriam Manifestar e Baixar(com a distribuiçao) ?

**Comment by robertorp** [comment]
Exatamente.. você manifesta as nf-e com ciencia da operação (ciencia da operação = vc confirma para a sefaz X nf-e foi emitida contra seu cnpj) e depois baixa utilizando nfe distribuição pela chave.

**Comment by andersonssa** [comment]
Ate onde e informaçao chegou para mim, nao precisa manifestar uma nota para poder baixar-la.
Sei que pela 
NFeDistribuicaoDFe | 1.00 | https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx

NfeDownloadNF | 2.00 / 3.10 | https://www.nfe.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx


por esses enderecos sei que iremos conseguir baixar informando a chave. Mas e para listar todas as nfe emitidas para mim nos ultimos 90 dias como voce falou, qual o webservice para isso?

**Comment by robertorp** [comment]
Faz um distribuição ai passando 0 no NSU, e ele listara as notas mas com menas informações não são notas completas, acho que chave e mais alguma informação poucas. Zipadas, ou seja você tem que descompactar elas também.

Bom precisa sim fazer manifestação. Teste ai.
NfeDownloadNF foi desativo. Se não foi então bom como disse não duvido de nada se tratando das sefazes.

**Comment by andersonssa** [comment]
Ok sobre o NfeDownloadNF, mas como estamos utilizando a versao 3.1 nao irá impactar no envio do xml?
Outra, quando vamos na Nfe Distribuiçao DFe colocamos o CNPJ, passamos 0 no NSU mas mesmo assim ele pede uma chave de acesso. E mesmo depois de colocar a chave dá o erro "Referencia de objeto nao definida para a instancia..."

**Comment by robertorp** [comment]
não coloca a chave de acesso.. isso e somente um appTeste.. deixa ele em branco

**Comment by andersonssa** [comment]
ja fiz isso e também da o mesmo erro.

**Comment by andersonssa** [comment]
pode me passar seu skype para nos falarmos?

**Comment by robertorp** [comment]
manda print, pois antes de dizer para você fiz o teste aqui e esta funcionando, me diz exatamente os passos que fez, skype: robertoalves18@hotmail.com

**Comment by orochasamuel** [comment]
@andersonssa talvez essas issues possam te ajudar:
https://github.com/ZeusAutomacao/DFe.NET/issues/568 - Explicação c/ Exemplo de Código fornecido pelo @marcosgerene 
https://github.com/ZeusAutomacao/DFe.NET/issues/571 - Explicação teórica e mapeamento do passo a passo com resolução de dúvidas
https://github.com/ZeusAutomacao/DFe.NET/issues/587 - Explicação sobre a NÃO possibilidade de baixar NFC-e
