### ISSUE TITLE
NFe/NFCe - Falha ao enviar NFCe EPEC 

### ISSUE THREAD

**Issue by Bertoncini** [ZeusAutomacao/DFe.NET#634]
Bom dia,

Estou utilizando a aplicação de teste para realizar o envio de EPEC porem a mesma só esta funcionando em NFE.

Após olhar as NT e o próprio fonte do Zeus, notei o seguinte aviso.
 /*Atenção: 
        NT2014_001_v1.00_Evento_EPEC e NT2014.003_v1.00 mostram que os campos abaixo pertencem a detEvento, no entanto o Schema XML do serviço AN está informado que os campos estão em detEvento/dest 
*/

Após o fato analisei os arquivos da NT e realmente tem diferença no envio de EPEC para NFE e NFCE

NFE deve ser informado os campos vNF vICMS e vST dentro da tag detEvento/dest
NFCe deve ser informado os campos vNF vICMS dentro da tag detEvento, o campo vST não é informado quando for NFCe.

Realizei as alterações e pela aplicação de teste foi enviado com sucesso em ambos modelos.

Quero que me confirmem se tem algum problema em subir essas alterações.

**Comment by robertorp** [comment]
Não tem problema, suba elas para serem analisadas, todo pull e bem vindo.
