### ISSUE TITLE
System.ArgumentException: 'O caminho tem um formato inválido.' ao criar ServicosNFe.

### ISSUE THREAD

**Issue by levi-rocha** [ZeusAutomacao/DFe.NET#637]
![errozeus](https://user-images.githubusercontent.com/8838006/35528123-a09fc960-050b-11e8-921c-2a0562ad66f1.png)

**Comment by robertorp** [comment]
Me diz oque você fez para dar esse erro, o cenário do erro. Quero fazer uns tentes antes simular o erro.

**Comment by levi-rocha** [comment]
O objetivo era consultar nota com chave.

O erro aconteceu primeiramente usando o pacote de nfe no nuget. Removi o pacote e referenciei os projetos diretamente pra debugar.

O erro acontece na hora da criação do ServicosNFe, quando o
```csharp 
Assembly.GetExecutingAssembly().Location
```
retorna uma string vazia.

Criei um PR ( #638 ) com uma mudança que resolveu o problema.

**Comment by robertorp** [comment]
Que tipo de aplicação executou para dar esse erro? Porque aqui não consigo fazer ele dar o erro

**Comment by levi-rocha** [comment]
WPF - .NET v4.5.2

**Comment by robertorp** [comment]
Não consegui simular o problema.
