### ISSUE TITLE
[DÚVIDA] - Versão do XML no construtor das classes

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#641]
Não seria interessante mandarmos a versão do XML como parâmetro nos contrutores das classes? Pelo menos nas classes que possuem novos campos ou que deixaram de te-los na versão 4.00 como por exemplo a propriedade **indPag** da classe **ide**? Dessa forma na serealização serealizamos apenas as propriedades da versão do XML em questão ao inves de fazer apenas um HasValue seja por meio do ShouldSerialize ou Specified.
Faz algum sentido?

**Comment by robertorp** [comment]
Quais seriam os ganhos para nós isso traria uma melhor performance?
Assim ainda tem uma questão, se você não gera com ShouldSerialize ou Specified ele gera uma tag nil ou null algo assim não recordo bem. Qual a melhor abordagem para nos retirar essa tag também?

**Comment by FabioHenriqueMF** [comment]
Então @robertorp  essa é a questão, vai ter que usar ou ShouldSerialize ou Specified para isso.  Acredito que o ganho é que vai ficar explícito que determinadas propriedades só serão serealizadas em determinadas versões.

**Comment by rodrigordi** [comment]
Como ficou na alteração das classes : o projeto tem classes distintas NFe da versão 3.10 e da versão 4.00 ?

**Comment by brunocasarotti** [comment]
Recentemente comecei a usar esse projeto para poder ler NFs em nosso sistema e ao ver essa thread gostaria de deixar meus comentários. Eu acredito que é interessante expor a versão no construtor da classe apenas quando for criar uma NF programaticamente, ajudaria muito o desenvolvedor, poderia ser um enum por exemplo. Já no caso de ler um arquivo xml, seria legal existir um parser interno que fosse capaz de identificar qual versão da NF esta sendo construída.

**Comment by scalarerp** [comment]
Esta questão do ShouldSerialize  para geração do XML eu acho importante, Tem previsão para implantação disso?

**Comment by robertorp** [comment]
@rodrigordi  São as mesmas classes

@scalarerp estou aberto a ideias, por hora não tem nada planejado para isso

**Comment by scalarerp** [comment]
Obrigado, vou explicar melhor, estou migrando toda minha aplicação para utilizar este código.
Ao gerar o XML e validar acontecem erros como elementos vazios.
Estou explicando bem para que outros também possam entender, desculpe.
Por exemplo: emit Xfant utilizava assim;
        public string xFant { get; set; }
        public bool ShouldSerializexFant()
        {
            return !(xFant == null || xFant == string.Empty);
        }
E se preencho a classe no DFE ZEUS o XML gera com a tag vazia assim: xFant />
Isso causa erro na validação.
Pensando que varios poderão usar estas classes desta mesma forma isso teria que funcionar certinho não acha?
Qua sugere?
Observei que já há vários campos assim(corretos) como por exemplo dest:IEDest

**Comment by scalarerp** [comment]
Se puder corrigir pelo menos estes casos que tenho problema seria muito legal, Obrigado e parabéns.
Ai tem a lista das alterações que fiz.
https://gist.github.com/scalarerp/6c482a5ee568f83175db47d9fe5d52d0
