### ISSUE TITLE
INTEGRA COM MINHA APLICAÇÃO

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [ZeusAutomacao/DFe.NET#642]
Estou iniciando os estudos sobre automação comercial, pretendo desenvolver um sistema de frente de caixa que emita nfe e nfc-e, quais os passos para da continuidade nos estudos ?
O que preciso para usa essa biblioteca em nas telas do meu sistema ?

**Comment by robertorp** [comment]
Bom, primeiramente estude a aplicação teste de nf-e/nfc-e que tem no repositório obviamente lendo o manual da sefaz. 

Você tera que entender de tributação e cálculos.  Para sua sorte tenho uma lib que faz isso para você https://github.com/automacaonet/MotorTributarioNet Mas.. e altamente recomendável que se entenda dos cálculos. 

Manual nf-e/nfc-e http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=

**Comment by EdsonRodrigoBA** [comment]
Eu baixei aqui o projeto executei o NFE.APP mais tipo não sei o que fazer, como seria cria uma tela de faturamento e transmitir a nota, eu não entendo nada de automação mais quero desenvolver um software, programo em c#, .. Desse projeto terei que usar essas telas que já vem nele ?

**Comment by orochasamuel** [comment]
Não não Edson, vc usa o exemplo dos códigos e adapta a sua necessidade. Se
vc quiser me manda um e-mail que a gente combina e eu te ajudo.

Em 1 de fev de 2018 10:28 PM, "Edson Rodrigo" <notifications@github.com>
escreveu:

**Comment by EdsonRodrigoBA** [comment]
Entende cara, eu posso pega esse projeto e adapta as minhas necessidades , vou estuda a fundo os códigos para enteder como funcionar, eu sempre fiz sistemas bem básico mesmo, mais agora estou na curiosidade de trabalha com essa parte de automação, mais confessor que estou muito perdido..

**Comment by orochasamuel** [comment]
Acontece... No começo é assim mesmo.

Em 1 de fev de 2018 10:37 PM, "Edson Rodrigo" <notifications@github.com>
escreveu:

**Comment by robertorp** [comment]
skype: robertoalves18@hotmail.com
vamos marcar um dia para eu apresentar minha aplicação para você, e você terá uma noção do tamanho do mundo de automação no Brasil e de suas complexidades.

**Comment by orochasamuel** [comment]
@robertorp já tem um tempo que eu queria te perguntar isso mas sempre me esquecia, resolvi aproveitar o gancho desta issue.

Na sua aplicação você tem algum tipo de integração com cartão de crédito? Para quando o cliente pagar em cartão de crédito/débito já emitir a nota fiscal.

@marcosgerene você utiliza?

Abraços.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira  não faço nada automatizado nesse sentido, deixo por conta do usuário

**Comment by robertorp** [comment]
Na sua aplicação você tem algum tipo de integração com cartão de crédito? Para quando o cliente pagar em cartão de crédito/débito já emitir a nota fiscal.

@samuelrochaoliveira  tenho não, mas já pensei em integrar pag seguro ou alguma coisa do gênero na aplicação, somente não sei se e viável algo assim ainda.

**Comment by marcosgerene** [comment]
@robertorp e @samuelrochaoliveira mas qual a ideia por trás disso? como vou emitir a nota para cartão sem saber os itens? a ideia é relacionar a venda ao pagamento? Mas ai o cliente sonegaria o que não foi feito via cartão e o problema passaria a ser nosso por "colaborar" fazendo o sistema emitir somente o que é em cartão? estou confuso quanto a funcionalidade

**Comment by orochasamuel** [comment]
@robertorp,

> @samuelrochaoliveira tenho não, mas já pensei em integrar pag seguro ou alguma coisa do gênero na aplicação, somente não sei se e viável algo assim ainda.

Aqui no Git mesmo tem várias libs e APIs para integrações deste sentido. A complicação deste tipo de implementação é o grau de informações a mais que deverão ser salvas no banco de dados e muitos usuários nem usam o recurso, por isso quero fazê-lo em minha aplicação como um módulo extra pago a parte.

Estou querendo integrar com a Cielo.

**Comment by orochasamuel** [comment]
@marcosgerene,

> @robertorp e @samuelrochaoliveira mas qual a ideia por trás disso? como vou emitir a nota para cartão sem saber os itens? a ideia é relacionar a venda ao pagamento? Mas ai o cliente sonegaria o que não foi feito via cartão e o problema passaria a ser nosso por "colaborar" fazendo o sistema emitir somente o que é em cartão? estou confuso quanto a funcionalidade

**Do ponto de vista comercial**

Agilidade no checkout. Em muitas empresas primeiro é feito o pagamento em cartão para após emitir a nota fiscal no sistema.

**Do ponto de vista de gestão**

Economia de tempo, neste caso não precisaria ler os extratos para lançar no financeiro ou mesmo efetuar lançamentos manuais e possibilitaria um visão em tempo real das movimentações.

**Do ponto de vista contábil/fiscal**

Economiza tempo para o(a) contador(a)/contabilidade caso exista uma exportação ou integração das informações no layout do sistema de gestão contábil. E previne receitas/vendas "confessadas" de não serem consideradas no fechamento mensal.

-------

A transação com o cartão seria "atrelada" à venda, naturalmente você saberia quais itens compõem aquela operação. Um sistema de gestão com esse recurso teria uma cara mais aparente de ERP. A possibilidade de sonegação é sempre uma realidade.

A minha realidade como contador e desenvolvedor de sistemas é um conflito constante, pois o cliente sempre pede para "esquecer" alguns valores na hora de emitir a movimentação diária/mensal de notas, do ponto de vista contábil isso traz vários problemas, alguns a curto prazo outros a longo prazo.

Começo muitas empresas que NÃO registram mais que 30% das vendas em dinheiro em nota fiscal. As vendas em cartão DEVEM TODAS serem registradas, nesse caso o sistema já deveria emitir no ato da venda, pois isentaria o contador de pedir toda a movimentação de cartões e emitir as notas fiscais.

A maior dificuldade no setor contábil é a obtenção de informações, algumas pessoas não se sentem seguras de fornecer extratos bancários, relatórios de vendas de cartão e outros valores relevantes para obtenção de balanço contábil confiável.

PS: Quanto a "colaboração" com sonegação, a responsabilidade de uso do sistema é do licenciado/usuário, você oferece o recurso, treina mas não responde pelo uso.

Abraços.

**Comment by ncmdeveloper** [comment]
Boa Tarde
Pessoal sempre tente ficar fora da parte de implementação de nfe.
só que agora tenho cliente exigindo a implementação da nfe, e não tenho mais como fugir.
baixei o modulo Zeus.Net.NFe.NFCe no NuGet do visual studio 2017 .
Agora não sei qual referencias usar.
Alguém te exemplo ou tutoria?

Agradeço a ajuda.

**Comment by robertorp** [comment]
@ncmdeveloper  crie uma issue por favor.
