### ISSUE TITLE
Additional information: 'Element' é uma expressão XmlNodeType inválida

### ISSUE THREAD

**Issue by SergioLessa** [ZeusAutomacao/DFe.NET#644]
Bom dia, Estou testando a versão 4,0 da nfce, estou conseguindo enviar sem problemas, quando tento importar a string xml da nfeproc sempre recebo o erro Additional information: 'Element' é uma expressão XmlNodeType inválida na teg infNFeSupl urlChave

![image](https://user-images.githubusercontent.com/5527498/35913563-3ecf8f62-0be7-11e8-8247-12e1f960767f.png)

[XMLTeste.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1702853/XMLTeste.zip)

**Comment by robertorp** [comment]
Solucionou o problema?
