### ISSUE TITLE
Nível de integração necessário para a tag "tpIntegra".

### ISSUE THREAD

**Issue by AndrewsFB** [ZeusAutomacao/DFe.NET#646]
Saudações!

Integrando o Zeus ao sistema daqui tive uma dúvida básica. O preenchimento das formas de pagamento exige algumas informações de cartão de crédito quando este for o caso escolhido. Entre essas informações está a tag "cAut" que guarda o número de autorização da transação no cartão de crédito.

A dúvida é a seguinte: Se eu colocar o tpIntegra = 1 posso simplesmente ter um campo digitável para informar o cAut, ou, tenho que ter um TEF funcionando?

Estou usando o projeto NFe.Integração.

**Comment by glaubermarcelino-zz** [comment]
Somente se usa tpIntegra =1 se seu sistema for realmente integrado a maquineta de cartão mais nada te impede de digitar essa informação.
Mais se for PÓS você não necessita informar esses dados e o tpIntegra deve ser igual a 2.
Mais alguns estados obrigam essa informação

**Comment by AndrewsFB** [comment]
Essa é justamente minha dúvida. Para evitar rejeições em estados que não permitem, planejo usar o "tpintegra=1" mesmo sem ter a integração com a maquineta.

Meu medo é arrumar briga com algum auditor por causa disso.

**Comment by robertorp** [comment]
Eu colocaria uma configuração para isso. Um bool e zerou =D 
Aqui hoje atualmente não temos isso e somente 2. 
Único estado que tem opção para digitar os dados e no Ceará, mas lá não e nfc-e e sim MF-e.

**Comment by AndrewsFB** [comment]
Falou ta falado @robertop!!

Essa será a prerrogativa mesmo. Valeu!
