### ISSUE TITLE
DANFE "nativo" para NF-e

### ISSUE THREAD

**Issue by AndrewsFB** [ZeusAutomacao/DFe.NET#647]
Saudações meus caros!

Existe intenção/projeto de desenvolver a impressão do DANFE em modo nativo (sem o fast reports)?

Estou avaliando a possibilidade de usar aqui na empresa a solução proposta neste repositório:
https://github.com/SilverCard/DanfeSharp

O que acham de trazer isso para o Zeus? Acham viável?

Em caso afirmativo irei fazer uma contribuição nesse sentido.

**Comment by gblmarquez** [comment]
@AndrewsFB 

Aqui estamos usando um fork desse projeto também, porém ele não é "nativo" pois usa a biblioteca chamada "PDF Clown". O projeto é excelente e foi muito bem construído, possibilitando que com nada de esforço conectamos nosso projeto a ele.

Porém já estamos sofrendo, pois essa biblioteca "PDF Clown" é antiga e não tem ou terá suporte as versões de .NET Standard, pelo menos é o que pesquisamos.

O caminho, seria juntar forças para migrar esse projeto para usar uma biblioteca, com suporte a mais 

O que acha der unirmos forças?

**Comment by AndrewsFB** [comment]
@gblmarquez 

Qual seria a biblioteca? Tem alguma em mente?

**Comment by gblmarquez** [comment]
@AndrewsFB, estamos analisando usar essa biblioteca, [itext-7](https://www.nuget.org/packages/itext7) ela é das antigas e está sempre atualizada e já tem suporte ao .NET Standard 1.6. O único problema é licenciamento

O que acha?

**Comment by AndrewsFB** [comment]
@gblmarquez

O projeto já possui um danfe criado com o fast reports onde temos que nos preocupar com licenciamento... 

Ao meu ver o ideal seria usar uma 100% open source.

**Comment by gblmarquez** [comment]
@AndrewsFB 
você conhece algum que é 100% open-source?

**Comment by AndrewsFB** [comment]
@gblmarquez

Somente o PDF Clown e o PDF Sharp mesmo. Também tem o Graphics do "System.Drawing", mas, esse eu já acho forçação de barra rs

Vou dar uma navegada aqui e ver se acho algo. Você tem algo pronto no IText-7 já?

**Comment by marcosgerene** [comment]
Existe um port na licença LGPL v2 do iTextSharp para .netCore, mas sinceramente não sei se funciona, como funciona e nem nada do tipo: https://github.com/VahidN/iTextSharp.LGPLv2.Core

**Comment by gblmarquez** [comment]
@AndrewsFB @marcosgerene 

Acredito que as opções são esses, o desafio é ter alguma confiança nos projetos.

@AndrewsFB 
Não temos nada pronto ou encaminhado, estamos decidindo pelo framework.

Do lado de vocês o que usariam? 
iTextSharp (LGPL) (https://github.com/VahidN/iTextSharp.LGPLv2.Core)
PDFSharp Fork (MIT) (https://github.com/Didstopia/PDFSharp)

Alguma outra opção?

**Comment by AndrewsFB** [comment]
@gblmarquez

Pelo que vi aqui as duas entram no mesmo barco do PDFClown. Não está se falando muito nelas.
Pela ligação com o IText, o ITextSharp me parece "levemente mais confiável".

Olhando de fora parece que todas tem o mesmo nível de maturidade. Quais problemas estão enfrentando exatamente com o projeto do DanfeSharp?

**Comment by gblmarquez** [comment]
@AndrewsFB 
Não temos suporte ao .NET Standard.

**Comment by AndrewsFB** [comment]
@gblmarquez

Creio que nenhuma das bibliotecas que citamos terá...
Pra ter esse suporte sem obrigar o uso de licenças comerciais só fazendo uso do "System.Drawing" na unha mesmo. Não tenho experiência com ele ainda.

**Comment by gblmarquez** [comment]
@AndrewsFB 
ainda assim o System.Drawing não gera PDF, ele não é solução.

**Comment by rftd** [comment]
Tem engine open-source 
https://github.com/majorsilence/My-FyiReporting

e também tem o ReportViewer da propria microsoft.
http://www.macoratti.net/17/02/rpv_vs17.htm

**Comment by AndrewsFB** [comment]
Se não me falha a memória já usei o "System.Drawing" para um pequeno relatório. Corro dele, muito braçal rs

Já usei o report viewer também. É bem funcional. Só nunca entendi porque não liberam o recurso pra justificar texto nele. 

Topam fazer uma tentativa no report viewer? Para compatibilidade provavelmente deve ser o investimento mais seguro.

**Comment by rodrigordi** [comment]
@AndrewsFB o ReportViewer tinha uma questão de segurança para gerar o PDF em algumas hospedagens (inclusive no Azure). Eu tentei fazer na epoca do vs 2010 mas tinha tantos datasources que meu notebook na epoca travava. E como eu ja tinha um projeto de danfe feito em delphi usando crystal reports, acabei usando ele por anos. Agora migramos para o danfe sharp, mas ainda quero achar outra solução.

Um amigo me falou que ia fazer em HTML mesmo, mas não falou quando. HTML seria uma opção ? Eu acho que seria muito trabalhoso para setar o tamanho dos campos. Mas rodaria em qq ambiente.
Se não me engano, o Boleto.Net gera o boleto usando HTML.

O que voces acham ?

**Comment by AndrewsFB** [comment]
@rodrigordi 

Também é uma boa! Trabalho dessa forma nos meus projetos em php.

**Comment by gblmarquez** [comment]
@AndrewsFB @rodrigordi 
Acredito que o HTML será um bom inicio :) e já apoia a comunidade. Depois podemos usar uma lib para converter o HTML para PDF.

**Comment by crx-master** [comment]
Esse assunto evoluiu? Vou automatizar a geração do PDF para nossa empresa e vou também enviar automaticamente para impressão.

**Comment by marcosgerene** [comment]
@crx-master não, até agora impressão da NFe, CTe e MDFe somente via Fast Reports

**Comment by alexsandro-xpt** [comment]
HTML so vejo um problema é paginação quando houver e se houver.

**Comment by crx-master** [comment]
eu já tinha geração e impressão automática em meu sistema usando XPS, mas não estou muito a fim de atualizar a solução

daria para resolver com HTML inclusive paginação... mas creio que o melhor é fazer o fork de algum projeto que não se parta do zero

pensei em migrar o [DanfeSharp](https://github.com/SilverCard/DanfeSharp) que vocês falaram há uns meses atrás para o [PDFSharp](http://www.pdfsharp.net) que é licença MIT

**Comment by leandrormd** [comment]
Boa noite, sei que estou chegando um pouco atrasado, e ainda não olhei o codigo para ver como esta a geração do DANFe, mas eu tenho uma versão desenvolvida em itextsharp, se ainda tiver interesse, podemos tentar colocar no projeto

**Comment by marcosgerene** [comment]
@leandrormd é interessante sim, como você gera hoje o arquivo? seraliza o xml? você vai portar a sua solução para as classes do Zeus?

Se abrir uma PR para isso terei o prazer de colaborar

**Comment by felixsevero** [comment]
@leandrormd Opa, o iTextSharp não está descontinuado, tendo o iText7 como substituto?
Esse iText7, apesar de estar no Github, me parece que a licença não permite o uso comercial.

**Comment by eduprog** [comment]
Verdade, eu usava iTextSharp e parei de usar por causa da licença, apesar de estar no github e funcionar 100% ele não é free. Se for usar comercialmente tem de comprar a licença. ok. 

Veja no final da página no gitHub.

**AGPL is a free / open source software license.**
**This doesn't mean the software is gratis!**

ou seja:

```
A AGPL é uma licença de software gratuita / de código aberto.
Isso não significa que o software é grátis!
```

**Comment by leandrormd** [comment]
Seralizo o xml.

Entendo quanto a licença, mas a minha ideia seria ter mais uma opção  para gera o DANFE.

**Comment by gblmarquez** [comment]
Pessoal temos um repositório com um versão modificada do DanfeSharp, usando a biblioteca PDF Clown. 

Até o momento tem funcionado super bem e até no .NET Core.

https://github.com/nfe/DanfeSharp

Espero que ajude.

**Comment by marcosgerene** [comment]
A opção open source do Fast Reports acabou de adicionar suporte a exportar para PDF... só falta direct print... acho que a ideia do Danfe nativo vai morrer para simplesmente migrar do fast reports pago para o fast reports open source...

**Comment by robertorp** [comment]
to achando a mesma coisa que o @marcosgerene  heheh

**Comment by robertorp** [comment]
já tem outra issue falando do fastreport opensource vamos continuar lá.

**Comment by eltonramos** [comment]
Pessoal, DanfeSharp funcionou bem para gerar pdf a partir do XML.
Porem tenho alguns XMLs com caracter especial que dá problema.
e Também XML com varias danfe. Sabem me dizer se existe algo que corrija isso?

**Comment by robertorp** [comment]
https://github.com/Laranjeiras/Zion.NFe.Danfe

feito com base no danfesharp , é um fork dele , talvez atenda você @eltonramos 
No repositório nosso também tem um em HTML muito bom !

**Comment by marcosgerene** [comment]
@eltonramos 

Muitas coisas mudaram dessa issue para cá.

Graças a contribuição do @DSBRBrasil agora temos o danfe em html puro! Acredito que seja a melhor alternativa possível quando se pensa em algo nativo. Seria possível até mesmo pensar em usar uma biblioteca que converta html em pdf e pronto, problema resolvido.

**Comment by eltonramos** [comment]
Realmente eu testei ele.
Porém o problema de tratar xml com caracter especial não resolveu.
[image: image.png]

[image: image.png]
att

Elton Ramos
(16) 99203-5401


Em ter., 27 de jun. de 2023 às 09:10, Roberto Alves Pereira <
***@***.***> escreveu:

**Comment by robertorp** [comment]
abra uma issue com seu xml que está imprimindo errado , explicando o que está acontecendo , quanto mais detalhes tiver melhor para nós analisar

**Comment by DSBRBrasil** [comment]
> @eltonramos
> 
> Muitas coisas mudaram dessa issue para cá.
> 
> Graças a contribuição do @DSBRBrasil agora temos o danfe em html puro! Acredito que seja a melhor alternativa possível quando se pensa em algo nativo. Seria possível até mesmo pensar em usar uma biblioteca que converta html em pdf e pronto, problema resolvido.

Ja tenho também, ja ja posto outro PR com essa funcionalidade
