### ISSUE TITLE
Duvida MDFe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#648]
Sempre que uso um serviço duas vezes gera essa exceção, o que pode ser?
{"Já foi adicionado um item com a mesma chave."}

**Comment by robertorp** [comment]
Manda um caso de uso que gera esse erro, passo a passo no appteste de mdf-e

**Comment by ThalisonSantos** [comment]
@robertorp não testei pelo appteste estou implementando Mdfe pelo Nuget na minha aplicação e isso ocorreu com servicoStatusServico.MDFeStatusServico()

**Comment by robertorp** [comment]
ahh sim, acho que já sei oque é, seguinte você utiliza o appteste um XML igual ne?
se sim define na tag certificado 
uma nova tag chamada < CacheId > 838383 < / CacheId > coloca um id

**Comment by ThalisonSantos** [comment]
@robertorp  o XML que vc fala é o de configuração? se for eu não o uso

**Comment by ThalisonSantos** [comment]
@robertorp Entendi Valeu!!

**Comment by robertorp** [comment]
Ok! precisando crie issues a vontade.
