### ISSUE TITLE
verificar data de validade do certificado digital

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#649]
oque acham de uma validação opcional para verificar data de validade do certificado digital, se o mesmo estiver vencido lançar uma exception?

**Comment by marcosgerene** [comment]
Sou contra. Isto é responsabilidade do software não do componente, o Zeus deve limitar-se a gerar, assinare transmitir o XML (e imprimir o DFe), qualquer coisa fora desse escopo descaracteriza o projeto e aumenta sua complexidade.

**Comment by adrbarros** [comment]
Concordo com @marcosgerene

**Comment by robertorp** [comment]
Pensei nisso já, vou criar uma lib no nuget para isso separadamente do Zeus. Quando tiver pronta disponibilizo no grupo do skype.

**Comment by orochasamuel** [comment]
@robertorp eu criei uma lib para trabalhar algumas informações com Certificação Digital, se você quiser e, achar interessante, podemos colocar tudo na mesma lib.

https://github.com/samuelrochaoliveira/CertificateAgent.NET

```cs
        public static bool IsValid(this X509Certificate2 @this)
        {
            return Convert.ToDateTime(@this.GetExpirationDateString()) > DateTime.Now;
        }
```
