### ISSUE TITLE
Situação Atual (Eventos Vinculados e números de Protocolos) ?

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#65]
Olá Adenilton,

Sabe me dizer onde consigo a informação da situação da NF-e na biblioteca?

![image](https://cloud.githubusercontent.com/assets/15462690/10855218/84f86f30-7f27-11e5-9649-e2409c41f96e.png)

**Comment by adeniltonbs** [comment]
Dê uma olhada na aplicação de exemplo, botão "Consultar pela Chave"

**Comment by orochasamuel** [comment]
Consegui encontrar, obrigado pela resposta rápida.
