### ISSUE TITLE
Homologação NFe 4.00 para SEFAZ MT

### ISSUE THREAD

**Issue by rodrigordi** [ZeusAutomacao/DFe.NET#651]
Encontrei uma diferença no SOAP Response da SEFAZ MT em homologação para urls de NFe 4.00. Como a NT propoe que todos os autorizadores devem usar o mesmo nome de função, eu havia tratado isso com uma unica classe para cada tipo de serviço (alterando apenas a url) para todas os autorizadores. Com essa pequena diferença, eu criei um conjunto de classes para SEFAZ-MT e fiz um HACK no código para tratar essa diferença. Essa diferença afetou esse projeto também ?

**Comment by hbdbim** [comment]
Esta biblioteca esta emitindo em NFCe 4.00, não testei a NFe 4.00, qual a diferença no response ?

**Comment by rodrigordi** [comment]
Era uma diferença na capitulação das funções do ws mas já foi resolvido. vou fechar o issue.
