### ISSUE TITLE
Criar uma classe para controlar as versões dos serviços

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#652]
Com o passar do tempo no repositório verifiquei que existe uma possibilidade media de uma pessoa setar um serviço na versão errada no framework.

Serviços a serem configurados hoje no Zeus.

![servicos](https://user-images.githubusercontent.com/10251705/36387954-2bc89ea4-1579-11e8-9014-a48d7e52b68b.png)

Ex: Existem estados  que o serviço X em homologação e versão 3.1 e em produção é 1.00 

Diante disso o legal era ter uma classe que faz isso automaticamente, a pessoa ter somente o trabalho de setar Versão 3.10 ou Versão 4.00 e a classe já criar essas versões todas para você automaticamente.

Na verdade não vejo nem objetivo de existir tal configuração no Zeus, somente não sugiro para deletar essa configuração para não quebrar oque já existe.  Para min a configuração deveria se resumir em simplicidade LayoutVersao = 3.1 ou 4.0 , automaticamente ele pegaria internamente tudo oque precisa para executar nas respectivas versões e organizaria.

**Comment by rodrigordi** [comment]
Acredito que teria que ter uma versão corrente para NFe (3.10 ou 4.00) e outra para eventos (1.00).
