### ISSUE TITLE
Erro Validação MDFe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#653]
ao tentar validar um mdfe informando o campo dhIniViagem retorna esse erro de validação:

http://www.portalfiscal.inf.br/mdfe:dhIniViagem' é inválido - O valor '2018-02-19T16:26:19' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/mdfe:TDateTimeUTC' - Falha na restrição Pattern.

alguém já passou por esse erro?

**Comment by robertorp** [comment]
Poste o xml para nós analisar.

**Comment by ThalisonSantos** [comment]
<?xml version="1.0"?>
<MDFe xmlns="http://www.portalfiscal.inf.br/mdfe">
<infMDFe Id="MDFe27180213459146000141580010000000011717248489" versao="3.00">
<ide>
<cUF>27</cUF>
<tpAmb>2</tpAmb>
<tpEmit>2</tpEmit>
<mod>58</mod>
<serie>1</serie>
<nMDF>1</nMDF>
<cMDF>71724848</cMDF>
<cDV>9</cDV>
<modal>1</modal>
<dhEmi>2018-02-19T16:26:29-03:00</dhEmi>
<tpEmis>1</tpEmis>
<procEmi>0</procEmi>
<verProc>1.1.94.0219</verProc>
<UFIni>AL</UFIni>
<UFFim>BA</UFFim>
<infMunCarrega>
<cMunCarrega>2704302</cMunCarrega>
<xMunCarrega>MACEIÓ</xMunCarrega>
</infMunCarrega>
<infPercurso>
<UFPer>SE</UFPer>
</infPercurso>
<dhIniViagem>2018-02-19T16:26:19</dhIniViagem>
</ide>
<emit>
<CNPJ>13459146000141</CNPJ>
<IE>242456154</IE>
<xNome>INTEGRASYS TECNOLOGIA</xNome>
<xFant>INTEGRASYS TECNOLOGIA</xFant>
<enderEmit>
<xLgr>RUA 10 DE NOVEMBRO</xLgr>
<nro>271</nro>
<xBairro>PITANGUINHA</xBairro>
<cMun>2704302</cMun>
<xMun>MACEIÓ</xMun>
<CEP>57025260</CEP>
<UF>AL</UF>
<fone>8299999999</fone>
<email>integrasys@hotmail.com</email>
</enderEmit>
</emit>
<infModal versaoModal="3.00">
<rodo>
<veicTracao>
<placa>NMC3005</placa>
<RENAVAM>00167291165</RENAVAM>
<tara>3500</tara>
<condutor>
<xNome>ASTOLFO DA SILVA SAURO</xNome>
<CPF>09987489698</CPF>
</condutor>
<tpRod>05</tpRod>
<tpCar>02</tpCar>
<UF>GO</UF>
</veicTracao>
</rodo>
</infModal>
<infDoc>
<infMunDescarga>
<cMunDescarga>2900207</cMunDescarga>
<xMunDescarga>ABARÉ</xMunDescarga>
<infNFe>
<chNFe>27171035559384000161550010000000601000000609</chNFe>
</infNFe>
<infNFe>
<chNFe>27180135559384000161550010000000631000000638</chNFe>
</infNFe>
</infMunDescarga>
</infDoc>
<tot>
<qNFe>2</qNFe>
<vCarga>1459.85</vCarga>
<cUnid>01</cUnid>
<qCarga>1500.0000</qCarga>
</tot>
<infAdic/>
</infMDFe>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#MDFe27180213459146000141580010000000011717248489">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>PNmFPIAQtF2ddBluDCmYGbvniKI=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>i0/MOh91aTqSRHodbwJCNTVoODRhokuIO89l/S7VLYlkQxa4ESdKb0whH4fHpklfq8OK8PNPy/hp2pIUhjJQGrmLivNKm3UazJjp+DZU+LVq3AeXPKyJ/sMc3Qvl8TXI0oyclt+dKeOCnlGIHnv51ec5kXB/Mp7thBLZXYb779SQJEfyOaN7Ybota3y8jveE3eOvDZpiJabSuJ8nj0VrV1VztPTTWgjw/ZUgDXaPHBz68YoUC4l5/E08i9KYQkd9GavyK9vwlP5ttcWEI6TVP7zKt2nZs+3BA2WgHSNJLr2rhlqZeO/mGEDqOYJaXB4H8lBqM5iPlQmhUU0dXwQfhA==</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>MIIHuDCCBaCgAwIBAgIIKgQMVw0hqOEwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxNjA0BgNVBAsMLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAwwQQUMgU0VSQVNBIFJGQiB2NTAeFw0xNzExMTQxOTE3MDBaFw0xODExMTQxOTE3MDBaMIHvMQswCQYDVQQGEwJCUjELMAkGA1UECAwCQUwxDzANBgNVBAcMBk1BQ0VJTzETMBEGA1UECgwKSUNQLUJyYXNpbDE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLDA1SRkIgZS1DTlBKIEExMRIwEAYDVQQLDAlBUiBTRVJBU0ExSTBHBgNVBAMMQENMViBDT01FUkNJTyBWQVJFSklTVEEgREUgQVJUSUdPUyBERSBGRVNUQVMgRSBQQVA6MTM0NTkxNDYwMDAxNDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCN+eETMx4oDwnjV/qcIAEWuJZYSPlGCZ5coDsf/7L5Tc6tqXRc++c1SOZCLxG+TuLh8UsexLh+pWGwDsxDG0TSWrFwiwda9V9yxzyiy5n+2b8u6GXPnSY5fWN5gmT2yWju7RMKKn7K/t+PkzWxuDtPqvPliaza5Wz+qnGVEKGEmRw84PgoNGnleRMGhE2141hHdMGW0w3GbI+G4NGTGcrP+UT1h0Zk6zCSixmWzxVqLKRORZv+ZH6wMIYknbKalF1VQ7DnzYjdmtP9vx7skAZrUPLrLKY6driTqCDWLWVaNW3chq/SjOyoPfiO1TRUkQ2fphxQFV82GMerGmDL4EU5AgMBAAGjggLPMIICyzAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFOzxQVFXqOY66V6zoCL5CIq1OoePMIGZBggrBgEFBQcBAQSBjDCBiTBIBggrBgEFBQcwAoY8aHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL2NhZGVpYXMvc2VyYXNhcmZidjUucDdiMD0GCCsGAQUFBzABhjFodHRwOi8vb2NzcC5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3NlcmFzYXJmYnY1MIG+BgNVHREEgbYwgbOBHUNPTVBSQVMtUExBU1RQRVNUQE9VVExPT0suQ09NoB8GBWBMAQMCoBYTFExVQ0lBTkEgRkVMSVggQkFSUk9ToBkGBWBMAQMDoBATDjEzNDU5MTQ2MDAwMTQxoD0GBWBMAQMEoDQTMjMwMDgxOTc2OTg1OTM2ODQ0OTEwMDAwMDAwMDAwMDAwMjAwMjAwMTE3OTkwNFNTUEFMoBcGBWBMAQMHoA4TDDAwMDAwMDAwMDAwMDBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5wZGYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGdBgNVHR8EgZUwgZIwSqBIoEaGRGh0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjUuY3JsMESgQqBAhj5odHRwOi8vbGNyLmNlcnRpZmljYWRvcy5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnY1LmNybDAOBgNVHQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQELBQADggIBABWP+AJS/kPN7EizRi/u60P8ecEHtJMoc7zHik3KJsQD+W44OdG59byPh0PuBTcxILOhWoLOB/TgJeW8x+m8VtpxOqfQdMeosh49RCHSbF+aruSW6xXK/CO7iVCo9LFr3visQXLxQSUSZ7ktFIWe6vxIuPxiFMwZ3crKzu1nrdcYFHXfvS6BEjBPe8o+hBQEeeCrhjGvrRLSCHuvrv+naNKbj57Hpw+ZPmRtjv/IER1DK1sZDvFJHa3Q5J0I8xPgsqEYWL4OZ9zp9PtGR21AIETfRDznBmiC6VwRr93iti8qEkKYzqFL9NfxeREQCTdlSwzCdJ9id92+wMsIpQfcb71+0v73047Vg17duDTwF+zRL23Ggf+weMEaMyOnLn7lSUKFlNVZUo5uwGSDcqjJjOw6nWx6cR+4EVhoDrmW+FZyPjnf2w4sxSDdoCqCFV6NCRgLxMgr2hrGLM1czmsujfQIt56Jx1uJZ61UcwmS6GGOrvGtspdJdXsFkxzy07qSHUlfe87DqGMSgXAhKcdcWODWXPcvuoJvkADQx5jdQhM1iXM/44OerPynhEVP1wNpBBCK713aWWVlwf6wVcvweK/z1XYFPLThf/UEoWEBBKGvugSKbjIblvVTqWgC05+pw8EZWagmSAbQM8O5MmtAm9HneTVRfFDIRkv+yugZl66F</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>
</MDFe>

**Comment by ThalisonSantos** [comment]
@robertorp  ta ai
[27180213459146000141580010000000011717248489.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1738085/27180213459146000141580010000000011717248489.zip)

**Comment by robertorp** [comment]
@ThalisonSantos  está utilizando nuget ou fontes?


edit: corrigido no repositório, atualização do nuget sai hoje lá pelas meia noite!

**Comment by ThalisonSantos** [comment]
@robertorp blz vou atualizar e testar

edit meia noite era de ontem ou de hoje?

**Comment by ThalisonSantos** [comment]
@robertorp atualizei via nuget e o erro persiste

**Comment by ThalisonSantos** [comment]
@robertorp corrigido valeu pela ajuda mais uma vez

**Comment by robertorp** [comment]
blz, nuget foi atualizado. 
obrigado. precisando abra issues
