### ISSUE TITLE
XML da NFe sem xmlns="http://www.portalfiscal.inf.br/nfe"

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#66]
Bom dia,

Percebi que as Tags <NFe> e <protNFe> não estão sengo gerada com o elemento xmlns="http://www.portalfiscal.inf.br/nfe".

Baixei o XML da nota gerada no site da sefaz e o mesmo está com as Tags assim: 
<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
<protNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="3.10">

Já o que o sistema gera está assim:
<NFe>
<protNFe versao="3.10">

Isso pode ocasionar algum problema?

**Comment by willianas1** [comment]
O Git ocultou as tags, segue novamente.

Baixei o XML da nota gerada no site da sefaz e o mesmo está com as Tags assim: 
< NFe xmlns="http://www.portalfiscal.inf.br/nfe" >
< protNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="3.10">

Já o que o sistema gera está assim:
< NFe >
< protNFe versao="3.10">

Isso pode ocasionar algum problema?

**Comment by orochasamuel** [comment]
Veja o Manual de Orientação do Contribuinte v.6.00 na página 16, segue o link do documento:
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=9hd38oni4Nc=

No site da NF-e há um documento com recomendações e analises de ocorrências que "atrapalhavam" os processos e que podem ser melhorados, o link do documento segue abaixo:

Consumo Indevido
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=IjF66WihatE=

*Obs: O trecho que trata do namespace no XML está nas páginas 10 e 11.

**Comment by adeniltonbs** [comment]
Williams, verifique minha reposta sobre a duplicidade do namespace xmlns em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/33.

Como verá, não faz sentido repetir o xmlns

**Comment by willianas1** [comment]
Blz então, era só uma duvida mesmo. Pois quando fui comparar achei essa
diferença.

Obrigado pelo retorno.

Em 1 de novembro de 2015 14:16, Zeus Automação Comercial <
notifications@github.com> escreveu:

> Williams, verifique minha reposta sobre a duplicidade do namespace xmlns
> em #33 https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/33.
> 
> Como verá, não faz sentido repetir o xmlns
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/66#issuecomment-152846689
> .

## 

Willian Santos
Analista de Sistemas | Instrutor de TI

##  (84) 8818-6602

Use Windows 8 ® - Ele foi Reimaginado pra Você ®
