### ISSUE TITLE
[Download NFe] - Nenhum documento localizado

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#660]
Boa tarde,

Em algumas notas quando tento fazer download recebo o retorno "Nenhum documento localizado", como o exemplo baixo:

```
Envio:

<?xml version="1.0"?>
<distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01">
	<tpAmb>1</tpAmb>
	<cUFAutor>24</cUFAutor>
	<CNPJ>07648362000132</CNPJ>
	<consChNFe>
		<chNFe>24180207555419000159550010010648804509469373</chNFe>
	</consChNFe>
</distDFeInt>


===========================================================================

Retorno:

<?xml version="1.0"?>
<retDistDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01">
	<tpAmb>1</tpAmb>
	<verAplic>1.1.9</verAplic>
	<cStat>137</cStat>
	<xMotivo>Nenhum documento localizado</xMotivo>
	<dhResp>2018-02-28T17:53:16-03:00</dhResp>
	<ultNSU>0</ultNSU>
	<maxNSU>0</maxNSU>
</retDistDFeInt>
```

Entretanto esta nota existe sim, consegui inclusive fazer a manifestação da ciência da operação para baixar e também consigo baixar direto do site da SEFAZ (com o certificado, claro).

Alguém pode me dar uma luz sobre isso?

---

Postado também em: https://www.projetoacbr.com.br/forum/topic/41833-download-nfe-nenhum-documento-localizado/

**Comment by moises77pereira** [comment]
Estou com esse mesmo problema. Alguém sabe informar se existe outro webservice que não seja o DFE para fazer o download? Ou é somente por este mesmo?

**Comment by orochasamuel** [comment]
É só esse WebService, já tentou baixar novamente @marcosgerene ? A diferença de tempo na tentativa de download para a manifestação foi de 25 minutos, era para ter dado certo mas, em alguns estados tem uma TAG que é obrigatória para conseguir baixar o documento futuramente, não me recordo qual TAG agora.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira em alguns casos consigo baixar logo após manifestar... Não entendi o que você quis dizer com essas TAGs, pode me explicar?

**Comment by orochasamuel** [comment]
@marcosgerene no aplicativo gratuito da SEFAZ/SP para emissão existia uma aba "Autorização Download", se fosse informado algum CNPJ além dos já informados destinatário/emitente era possível baixar o documento. Por exemplo, se informar o número do CNPJ do escritório contábil, com o certificado digital do contador é possível baixar. (Acredito que esse não seja o seu caso mas, que fique a caráter informativo)

![image](https://user-images.githubusercontent.com/15462690/36955896-ed930b24-2009-11e8-9eb5-938e7d892844.png)
*Ilustração

Agora... se você está usando o certificado da própria empresa é muito estranho. Experimente fazer a consulta pelo número do NSU e veja se assim o documento vem na resposta. No meu sistema eu só faço a consulta por NSU e nunca tive esse problema.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira estou tentando fazer o download como DESTINATÁRIO, ou seja, teóricamente sou um CNPJ autorizado.

Eu faço a busca dos NSUs que retorna as chaves, ai com uma chave aleatória qualquer tento fazer o download (como se fosse o usuário dando entrada em uma nota ainda não lançada), na tentativa do download pela chave recebo este retorno.

**Comment by orochasamuel** [comment]
@marcosgerene mas você manifesta todas as notas antes de baixar? Ou pelo dá Ciência da Operação?

**Comment by marcosgerene** [comment]
@samuelrochaoliveira chamo o evento **RecepcaoEventoManifestacaoDestinatario** passando o tipo **TipoEventoManifestacaoDestinatario.TeMdCienciaDaEmissao** antes de tentar o download.

Esta nota específica, se consultar a chave, verá que está manifestada a mais de 15 minutos antes de tentar o download

**Comment by orochasamuel** [comment]
@marcosgerene experimenta consultar e baixar usando o seguinte método:

```cs

// Get response from SEFAZ WS
var response = servicoNFe.NfeDistDFeInteresse(companyEstate, companyCnpj, lastNsu.ToString());

// Veja se no objeto response.Retorno.loteDistDFeInt há algum item.

```

No lugar do último NSU passe a chave de acesso como parâmetro.

**Comment by orochasamuel** [comment]
@marcosgerene Conseguiu?

**Comment by marcosgerene** [comment]
@samuelrochaoliveira estou meio apertado com SPEDs aqui, acredito que consigo testar ainda hoje e te dou um retorno

**Comment by marcosgerene** [comment]
@samuelrochaoliveira quando tento da forma como disse recebo o retorno abaixo:

```
Erros na validação:
 O elemento 'http://www.portalfiscal.inf.br/nfe:ultNSU' é inválido - O valor '24180206990440000110550010001735731001735732' é inválido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TNSU' - Falha na restrição Pattern.
```

**Comment by orochasamuel** [comment]
@marcosgerene você está tentando passar a Chave de Acesso no lugar do NSU como parâmetro.

Veja a assinatura do método, tem possibilidade de colocar NSU e Chave de Acesso.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira eu fiz o que voce falou no post anterior rapaz... olha bem o xml que eu postei antes, fica claro que meu código estava sendo informado corretamente... =D

**Comment by marcosgerene** [comment]
@samuelrochaoliveira eu fiz o que voce falou no post anterior rapaz... olha bem o xml que eu postei antes, fica claro que meu código estava sendo informado corretamente... =D

**Comment by orochasamuel** [comment]
Como a assinatura do método aceita `nullable` no último NSU, NSU, Chave de Acesso você deve alternar entre a assinatura que quer utilizar. Como lhe falei, no meu caso eu uso a consulta pelo último NSU, já dou Ciência da Operação e já baixo as notas, depois o usuário pode confirmar ou recusar a nota.

Vide assinatura do método, proveniente do próprio DFe.NET:
![image](https://user-images.githubusercontent.com/15462690/37078126-c2fffb6a-21bc-11e8-884a-611221497d3e.png)
Espero ter ajudado. o/

**Comment by valentimmx** [comment]
@osamueloliveira

Você pode me ajudar com a questão de baixar o Arquivo de Distribuição aqui?

Eu emiti com sucesso uma NFe e agora to chamando o método **NfeDistDFeInteresse** porém me retorna "Rejeicao: NF-e indisponivel para o emitente".

Pelo que voce falou, eu EMITENTE tenho que manifestar tambem a NF antes de baixa-la, ou só consigo fazer isso após a manifestação do DESTINATARIO?

**Comment by orochasamuel** [comment]
Renan se você estiver tentando baixar uma nota que você mesmo emitiu não irá funcionar pois é dever do emitente arquivar o XML do documento fiscal. Você só consegue baixar notas de outras empresas.
