### ISSUE TITLE
Assinatura - Auxílio com novo método

### ISSUE THREAD

**Issue by Phakos** [ZeusAutomacao/DFe.NET#661]
Pessoal, bom dia.

Retomei um projeto que vinha usando a versão anterior da biblioteca de assinatura do Zeus.
Atualizando o projeto com a nova Biblioteca do Zeus surgiu uma pequena dúvida/dificuldade e preciso da ajuda de vocês.

Ao usar o App Teste e assinar um XML ele retorna na tela o XML completo (já assinado). 
Mas quando uso apenas a classe Assinatura, ele me retorna apenas a TAG assinada e não todo o XML com a TAG de assinatura.
 
Ou seja, não estou tendo problemas com a assinatura, está tudo ok. A minha dificuldade está no retorno da assinatura. Quem vem só uma parte do XML.

Em que momento a TAG de assinatura é incorporada ao XML ? No App de Teste acontece automaticamente. Ou eu preciso fazer isso manualmente ? (Juntar o XML com a TAG Assinada).

Grato pelo projeto e ajuda de vocês.

Att,

Lima

**Comment by robertorp** [comment]
E somente você utilizar como esta no appTeste

```_nfe.Assina();```

Dentro do método .Assina()

nas ultimas 3 linhas você vai ver quando ele adiciona no objeto a assinatura.

```
var assinatura = Assinador.ObterAssinatura(nfeLocal, nfeLocal.infNFe.Id, cfgServico);
            nfeLocal.Signature = assinatura;
            return nfeLocal;
```

Poste mais detalhes do seu código de como ele esta implementado, onde ele assina, onde ele retorna o xml, poste o xml que esta gerando enfim poste mais detalhes para nós analisar.

**Comment by Phakos** [comment]
Olá Roberto, fiz uma pequena alteração e estou usando essa Classe.

O retorno dessa Classe volta pra mim só a parte assinada e não o XML todo.

public static SignatureZeus ObterAssinatura (NFeZeus objeto, string id, X509Certificate2 certificadoDigital, bool manterDadosEmCache = false)
        {
            var objetoLocal = objeto;
            if (id == null)
                throw new Exception("Não é possível assinar um objeto evento sem sua respectiva Id!");

            try
            {
                var documento = new XmlDocument { PreserveWhitespace = true };
                documento.LoadXml(FuncoesXml.ClasseParaXmlString(objetoLocal));
                var docXml = new SignedXml(documento) { SigningKey = certificadoDigital.PrivateKey };
                var reference = new Reference { Uri = "#" + id };

                // adicionando EnvelopedSignatureTransform a referencia
                var envelopedSigntature = new XmlDsigEnvelopedSignatureTransform();
                reference.AddTransform(envelopedSigntature);

                var c14Transform = new XmlDsigC14NTransform();
                reference.AddTransform(c14Transform);

                docXml.AddReference(reference);

                // carrega o certificado em KeyInfoX509Data para adicionar a KeyInfo
                var keyInfo = new KeyInfo();
                keyInfo.AddClause(new KeyInfoX509Data(certificadoDigital));

                docXml.KeyInfo = keyInfo;
                docXml.ComputeSignature();

                //// recuperando a representação do XML assinado
                var xmlDigitalSignature = docXml.GetXml();
                var assinatura = FuncoesXml.XmlStringParaClasse<SignatureZeus>(xmlDigitalSignature.OuterXml);
                return assinatura;
            }
            finally
            {
                //Se não mantém os dados do certificado em cache e o certificado não foi passado por parâmetro(isto é, ele foi criado dentro deste método), 
                //então libera o certificado, chamando o método reset.
                if (!manterDadosEmCache & certificadoDigital == null)
                    certificadoDigital.Reset();
            }

        }

**Comment by Phakos** [comment]
Lembrando que minha aplicação não é feita em C# mas eu faço a Build e uso as Dlls. Até a forma de assinatura "antiga" estava tudo ok, Assinatura, Validação, Envio e etc. Só agora que me deparei com está pequena dificuldade.

**Comment by robertorp** [comment]
@Phakos nem sei que versão vc usava hehe mas deve ser muito antiga mesmo. 
Hoje o zeus retorna o objeto já com a assinatura. 
O ruim de vc alterar um código vc mesmo e que vc perde atualizações ou é totalmente obrigado a ver oque nos alteramos. Seria interessante vc usar o zeus normalmente mas.. gosto seu hehe 
Qualquer coisa so chamar.
