### ISSUE TITLE
Dúvida NFe grupo Icms geral

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#662]
como faço para informa os campos pFCP e vFCP em ICMS usando o método obterIcmsBasico(crt) ?

**Comment by robertorp** [comment]
como assim? basta vc usar eles normalmente.. todos eles tem {get; set;}

**Comment by ThalisonSantos** [comment]
@robertorp  eu instancio a classe IcmsGeral e lá não tem esses campos

**Comment by ThalisonSantos** [comment]
@robertorp 
exemplo eu uso a classe IcmsGeral para passar o ICMS e depois uso o método obterIcmsbasico para gerar o grupo de ICMS conforme o cst que eu passei mas, em ICMS geral não tem os campos pFCP e vFCP esses campos só aparecem se vc usar a classe icms00 ou semelhante

**Comment by robertorp** [comment]
Vou analisar isso.

**Comment by apbertoletti** [comment]
Olá pessoal, 

Pelo que reparei no código recente da classe ICMSGeral, estas propriedades faltantes já estão criadas e disponíveis para uso, conforme podem notar no print abaixo:

![6-27-2018 11-16-41 pm](https://user-images.githubusercontent.com/6843493/42009371-632acfba-7a60-11e8-9e17-866603d75670.png)

Sendo assim, acho que podemos fechar esta issue.

Abraços
