### ISSUE TITLE
Erro Impressão Danfe Fast NFe 4.00

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#663]
quando tento imprimir um nfe 4.0 gera um exceção {"Referência de objeto não definida para uma instância de um objeto."}, mas na 3.10 imprimi normalmente

**Comment by robertorp** [comment]
Impressões não estão preparadas para 4.0 
ainda

**Comment by ThalisonSantos** [comment]
@robertorp  tem previsão quando estará tudo pronto para nfe 4.0?

**Comment by robertorp** [comment]
Ainda não. Mas garanto que sera antes de lançar nf-e 4.0 tem muita gente que usa a impressão do Zeus. Não e meu caso ainda. Mas vamos passar para a impressão do Zeus assim que adquirirmos licença do fast report.

Se quiser me fornecer uma licença do fast report (no meu nome) para livre uso implemento, agora se quiser também pode esperar alguém implementar ou ate mesmo eu so que no momento certo, oque não e o caso hoje.

**Comment by marcosgerene** [comment]
@ThalisonSantos poste o XML da nota que apresenta este erro para que eu possa analisar.

Ainda não migrei para a versão 4.0 da NFe, então não notei nenhuma anomalia no Danfe.

**Comment by ThalisonSantos** [comment]
@marcosgerene 

<?xml version="1.0"?>
<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
<NFe>
<infNFe versao="4.00" Id="NFe27180313459146000141550010000000661000000661">
<ide>
<cUF>27</cUF>
<cNF>00000066</cNF>
<natOp>UF-VENDA MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS</natOp>
<mod>55</mod>
<serie>1</serie>
<nNF>66</nNF>
<dhEmi>2018-03-06T08:03:42-03:00</dhEmi>
<tpNF>1</tpNF>
<idDest>2</idDest>
<cMunFG>2704302</cMunFG>
<tpImp>1</tpImp>
<tpEmis>1</tpEmis>
<cDV>1</cDV>
<tpAmb>2</tpAmb>
<finNFe>1</finNFe>
<indFinal>1</indFinal>
<indPres>1</indPres>
<procEmi>0</procEmi>
<verProc>1.1.114.0306</verProc>
</ide>
<emit>
<CNPJ>13459146000141</CNPJ>
<xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
<xFant>INTEGRASYS TECNOLOGIA</xFant>
<enderEmit>
<xLgr>RUA 10 DE NOVEMBRO</xLgr>
<nro>271</nro>
<xBairro>PITANGUINHA</xBairro>
<cMun>2704302</cMun>
<xMun>2704302</xMun>
<UF>AL</UF>
<CEP>57025260</CEP>
<cPais>1058</cPais>
<xPais>BRASIL</xPais>
<fone>8299999999</fone>
</enderEmit>
<IE>242456154</IE>
<CRT>3</CRT>
</emit>
<dest>
<CNPJ>48076228000191</CNPJ>
<xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
<enderDest>
<xLgr>R VINTE E CINCO DE MARCO,864</xLgr>
<nro>0</nro>
<xCpl>872</xCpl>
<xBairro>MERCADO</xBairro>
<cMun>3550308</cMun>
<xMun>SÃO PAULO</xMun>
<UF>SP</UF>
<CEP>01017040</CEP>
<cPais>1058</cPais>
<xPais>Brasil</xPais>
</enderDest>
<indIEDest>1</indIEDest>
<IE>109667825118</IE>
</dest>
<det nItem="1">
<prod>
<cProd>174</cProd>
<cEAN/>
<xProd>PAPEL SUZANO REPORT PREMIUM</xProd>
<NCM>48025610</NCM>
<CFOP>6102</CFOP>
<uCom>UN</uCom>
<qCom>9.0000</qCom>
<vUnCom>23.0000000000</vUnCom>
<vProd>207.00</vProd>
<cEANTrib/>
<uTrib>UN</uTrib>
<qTrib>9.0000</qTrib>
<vUnTrib>23.0000000000</vUnTrib>
<indTot>1</indTot>
<nItemPed>2</nItemPed>
</prod>
<imposto>
<vTotTrib>29.64</vTotTrib>
<ICMS>
<ICMS00>
<orig>0</orig>
<CST>00</CST>
<modBC>3</modBC>
<vBC>207.00</vBC>
<pICMS>12.0000</pICMS>
<vICMS>24.84</vICMS>
</ICMS00>
</ICMS>
<PIS>
<PISAliq>
<CST>01</CST>
<vBC>207.00</vBC>
<pPIS>5.0000</pPIS>
<vPIS>10.35</vPIS>
</PISAliq>
</PIS>
<COFINS>
<COFINSAliq>
<CST>01</CST>
<vBC>207.00</vBC>
<pCOFINS>15.0000</pCOFINS>
<vCOFINS>31.05</vCOFINS>
</COFINSAliq>
</COFINS>
</imposto>
</det>
<det nItem="2">
<prod>
<cProd>114</cProd>
<cEAN/>
<xProd>CADERNO TILIBRA 10 MATERIAS</xProd>
<NCM>19053100</NCM>
<CEST>1705300</CEST>
<CFOP>6403</CFOP>
<uCom>UN</uCom>
<qCom>9.0000</qCom>
<vUnCom>14.9000000000</vUnCom>
<vProd>134.10</vProd>
<cEANTrib/>
<uTrib>UN</uTrib>
<qTrib>9.0000</qTrib>
<vUnTrib>14.9000000000</vUnTrib>
<indTot>1</indTot>
<nItemPed>3</nItemPed>
</prod>
<imposto>
<vTotTrib>18.04</vTotTrib>
<ICMS>
<ICMS60>
<orig>0</orig>
<CST>60</CST>
</ICMS60>
</ICMS>
<PIS>
<PISAliq>
<CST>01</CST>
<vBC>0.00</vBC>
<pPIS>5.0000</pPIS>
<vPIS>0.00</vPIS>
</PISAliq>
</PIS>
<COFINS>
<COFINSAliq>
<CST>01</CST>
<vBC>0.00</vBC>
<pCOFINS>15.0000</pCOFINS>
<vCOFINS>0.00</vCOFINS>
</COFINSAliq>
</COFINS>
</imposto>
</det>
<total>
<ICMSTot>
<vBC>207.00</vBC>
<vICMS>24.84</vICMS>
<vICMSDeson>0.00</vICMSDeson>
<vFCPUFDest>0.00</vFCPUFDest>
<vFCP>0.00</vFCP>
<vBCST>0.00</vBCST>
<vST>0.00</vST>
<vFCPST>0.00</vFCPST>
<vFCPSTRet>0.00</vFCPSTRet>
<vProd>341.10</vProd>
<vFrete>0.00</vFrete>
<vSeg>0.00</vSeg>
<vDesc>0.00</vDesc>
<vII>0.00</vII>
<vIPI>0.00</vIPI>
<vIPIDevol>0.00</vIPIDevol>
<vPIS>10.35</vPIS>
<vCOFINS>31.05</vCOFINS>
<vOutro>0.00</vOutro>
<vNF>341.10</vNF>
<vTotTrib>47.68</vTotTrib>
</ICMSTot>
</total>
<transp>
<modFrete>0</modFrete>
<vol>
<qVol>0</qVol>
<nVol>0</nVol>
<pesoL>0.000</pesoL>
<pesoB>0.000</pesoB>
</vol>
</transp>
<cobr>
<dup>
<nDup>001270</nDup>
<dVenc>2018-01-18</dVenc>
<vDup>416.10</vDup>
</dup>
</cobr>
<pag>
<detPag>
<tPag>14</tPag>
<vPag>341.10</vPag>
</detPag>
</pag>
<infAdic>
<infCpl>teste de texto;será que funcionou</infCpl>
</infAdic>
</infNFe>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe27180313459146000141550010000000661000000661">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>uN5WCf2OMVg9qNCuUMonbT1MVFo=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>BRBN9etIz6UZBfuOQwtxZPOQxon0guJu7jtoKdSNFDSahG9239GnQPHm0u7SGw3GChxRz9fd/d3fyYn0ujjq3CRsPKMnSVThUsSfMcx7CnaaKvKrv0xseZSewVqp6jkOvZZ/0AKDGcPg0QF04635/AlAHHPVSfBotEkQidyd9S2EzI/P4Tj3nMSGNJaZV6iY3s4A6LU+weB7UWAcOXZg2c51nIr/kdpbkqRxiS53K55Qa3qTSXCRoaOkMNmVwtl8ff/3/QwaRnijIuGM5Hhg0OEwL9kvaAULambNSbraC+djZmQMoDkhfV97Mc0Eg71W5SxOUGiArZKi1OFFaXNLKA==</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>MIIHuDCCBaCgAwIBAgIIKgQMVw0hqOEwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxNjA0BgNVBAsMLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAwwQQUMgU0VSQVNBIFJGQiB2NTAeFw0xNzExMTQxOTE3MDBaFw0xODExMTQxOTE3MDBaMIHvMQswCQYDVQQGEwJCUjELMAkGA1UECAwCQUwxDzANBgNVBAcMBk1BQ0VJTzETMBEGA1UECgwKSUNQLUJyYXNpbDE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLDA1SRkIgZS1DTlBKIEExMRIwEAYDVQQLDAlBUiBTRVJBU0ExSTBHBgNVBAMMQENMViBDT01FUkNJTyBWQVJFSklTVEEgREUgQVJUSUdPUyBERSBGRVNUQVMgRSBQQVA6MTM0NTkxNDYwMDAxNDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCN+eETMx4oDwnjV/qcIAEWuJZYSPlGCZ5coDsf/7L5Tc6tqXRc++c1SOZCLxG+TuLh8UsexLh+pWGwDsxDG0TSWrFwiwda9V9yxzyiy5n+2b8u6GXPnSY5fWN5gmT2yWju7RMKKn7K/t+PkzWxuDtPqvPliaza5Wz+qnGVEKGEmRw84PgoNGnleRMGhE2141hHdMGW0w3GbI+G4NGTGcrP+UT1h0Zk6zCSixmWzxVqLKRORZv+ZH6wMIYknbKalF1VQ7DnzYjdmtP9vx7skAZrUPLrLKY6driTqCDWLWVaNW3chq/SjOyoPfiO1TRUkQ2fphxQFV82GMerGmDL4EU5AgMBAAGjggLPMIICyzAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFOzxQVFXqOY66V6zoCL5CIq1OoePMIGZBggrBgEFBQcBAQSBjDCBiTBIBggrBgEFBQcwAoY8aHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL2NhZGVpYXMvc2VyYXNhcmZidjUucDdiMD0GCCsGAQUFBzABhjFodHRwOi8vb2NzcC5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3NlcmFzYXJmYnY1MIG+BgNVHREEgbYwgbOBHUNPTVBSQVMtUExBU1RQRVNUQE9VVExPT0suQ09NoB8GBWBMAQMCoBYTFExVQ0lBTkEgRkVMSVggQkFSUk9ToBkGBWBMAQMDoBATDjEzNDU5MTQ2MDAwMTQxoD0GBWBMAQMEoDQTMjMwMDgxOTc2OTg1OTM2ODQ0OTEwMDAwMDAwMDAwMDAwMjAwMjAwMTE3OTkwNFNTUEFMoBcGBWBMAQMHoA4TDDAwMDAwMDAwMDAwMDBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5wZGYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGdBgNVHR8EgZUwgZIwSqBIoEaGRGh0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjUuY3JsMESgQqBAhj5odHRwOi8vbGNyLmNlcnRpZmljYWRvcy5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnY1LmNybDAOBgNVHQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQELBQADggIBABWP+AJS/kPN7EizRi/u60P8ecEHtJMoc7zHik3KJsQD+W44OdG59byPh0PuBTcxILOhWoLOB/TgJeW8x+m8VtpxOqfQdMeosh49RCHSbF+aruSW6xXK/CO7iVCo9LFr3visQXLxQSUSZ7ktFIWe6vxIuPxiFMwZ3crKzu1nrdcYFHXfvS6BEjBPe8o+hBQEeeCrhjGvrRLSCHuvrv+naNKbj57Hpw+ZPmRtjv/IER1DK1sZDvFJHa3Q5J0I8xPgsqEYWL4OZ9zp9PtGR21AIETfRDznBmiC6VwRr93iti8qEkKYzqFL9NfxeREQCTdlSwzCdJ9id92+wMsIpQfcb71+0v73047Vg17duDTwF+zRL23Ggf+weMEaMyOnLn7lSUKFlNVZUo5uwGSDcqjJjOw6nWx6cR+4EVhoDrmW+FZyPjnf2w4sxSDdoCqCFV6NCRgLxMgr2hrGLM1czmsujfQIt56Jx1uJZ61UcwmS6GGOrvGtspdJdXsFkxzy07qSHUlfe87DqGMSgXAhKcdcWODWXPcvuoJvkADQx5jdQhM1iXM/44OerPynhEVP1wNpBBCK713aWWVlwf6wVcvweK/z1XYFPLThf/UEoWEBBKGvugSKbjIblvVTqWgC05+pw8EZWagmSAbQM8O5MmtAm9HneTVRfFDIRkv+yugZl66F</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>
</NFe>
<protNFe versao="4.00">
<infProt>
<tpAmb>2</tpAmb>
<verAplic>SVRS201802051034</verAplic>
<chNFe>27180313459146000141550010000000661000000661</chNFe>
<dhRecbto>2018-03-06T08:03:54-03:00</dhRecbto>
<digVal>uN5WCf2OMVg9qNCuUMonbT1MVFo=</digVal>
<cStat>203</cStat>
<xMotivo>Rejeicao: Emissor nao habilitado para emissao da NF-e</xMotivo>
</infProt>
</protNFe>
</nfeProc>

**Comment by ThalisonSantos** [comment]
@marcosgerene  esta ai 
[NFe27180313459146000141550010000000661000000661.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1784696/NFe27180313459146000141550010000000661000000661.zip)

**Comment by robertorp** [comment]
Estou presumindo que solucionaram. Caso contrario re-abra a issue.

**Comment by marcosgerene** [comment]
@robertorp Sim, com o xml informado deu certo, e pelas mudanças que a NFe 4.0 faz, suponho que não tenha nenhuma outra mudança alem desta.
