### ISSUE TITLE
Dúvida campo DhSaiEnt em NfeIde

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#665]
esse campo não deveria poder se nulo ou vazio?

**Comment by robertorp** [comment]
Correção aplicada.

https://github.com/ZeusAutomacao/DFe.NET/pull/667

**Comment by ThalisonSantos** [comment]
@robertorp quando estará disponível no nuget?

**Comment by robertorp** [comment]
Até amanhã as 1 da tarde qualquer hora nesse intervalo.
