### ISSUE TITLE
[Off-Topic] e-Financeira

### ISSUE THREAD

**Issue by willianas1** [ZeusAutomacao/DFe.NET#666]
Bom dia Pessoal, 

Sei que não é o foco do projeto, mais alguém já desenvolveu/desenvolve a solução e-Financeira da Receita Federal em C#?

Link do projeto: http://sped.rfb.gov.br/projeto/show/1179

**Comment by robertorp** [comment]
Qual o objetivo desse projeto? Digo o eFinanceira

**Comment by willianas1** [comment]
Olá Roberto,

Se trata de mais um "braço" do projeto SPED, voltado para instituições
financeiras, casas de câmbio, etc.

Uma estrutura bem parecida com o projeto NFE inclusive.

--
Saudações,

*Willian Santos*
Analista de Sistemas | Instrutor de TI
+55 84 98818-6602 <%2B55%2084%208818-6602>

2018-03-06 15:15 GMT-03:00 Roberto Alves Pereira <notifications@github.com>:

**Comment by robertorp** [comment]
Vi aqui, se quiser você pode me pagar para eu estar adicionando no projeto e implementando para você a parte de webservices do e-Financeira.
