### ISSUE TITLE
Versionamento das DLLs

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#671]
Bom dia pessoal alguma novidade com relação ao versionamento das bibliotecas?

**Comment by robertorp** [comment]
acabei de subir uma versão nova com a versão alterada dos assemblys, por hora esta tudo manual, toda vez que me esquecer abra uma issue e subo novamente alterado a versão dos assemblys.

**Comment by ThalisonSantos** [comment]
@robertorp  existe uma extensão do Visual Studio chamada automatic version creio que os ajudaria bastante

**Comment by robertorp** [comment]
@ThalisonSantos até tentei usar o mesmo, mas vendo aqui não tem como eu controlar o versionamento de forma eficiente. Se eu quiser realmente automatizar o versionamento vou ter que preparar um jenkins ou algo do genero para isso. O proprio jenkins faria o versionamento ele comitaria no repositório a versão.
