### ISSUE TITLE
Assinador, assinando com DigestMethod diferente!

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#673]
Boa tarde senhores,

Estou implementando a classe de vc´s, e estou me deparando com o seguinte erro ao assinar:
"Algoritmo Inválido Especificado"

Meu projeto é em VB.NET, e percebi debugando que usando o mesmo certificado dentro do método ObterAssinatura na classe Assinador, a variável reference fica com a propriedade DigestMethod: 
"http://www.w3.org/2001/04/xmlenc#sha256"

E quando eu testo pelo AppTeste do Projeto de vc´s, assina direitim, porém percebo que no mesmo método ObterAssinatura na classe Assinador, a variável reference fica com a propriedade DigestMethod: 
"http://www.w3.org/2000/09/xmldsig#sha1"

O erro dá em  
docXml.ComputeSignature();

Dúvida:
Tem q configurar algo que está passando batido??

Desde já agradeço.

Att,
Guilherme

**Comment by rftd** [comment]
A classe não assina em SHA256 e sim em SHA1 para assinar em SHA256 precisaria de alguns ajustes.

**Comment by gui-abrantes** [comment]
@rftd, então, mas eu quero q assina é em sha1 mesmo! Mas não sei pq cargas d'agua quando uso no meu projeto ela tá tentando assinar em sha256! Isso eu usando o mesmo certificado! Gostaria de saber se é alguma configuração ou propriedade q estou esquecendo!

**Comment by rftd** [comment]
você deve estar mudando algo que ele so usa sha256 se você informar este digest.

**Comment by gui-abrantes** [comment]
Bom dia senhores,

Venho dar uma resposta para ajudar outras pessoas que venham a deparar com tal erro.

Consegui descobrir o q era. É que eu uso o framework 4.7.1, e a partir desta versão o valor default da propriedade DigestMethod passou a ser SHA256, causando o erro.

Basta adicionar uma configuração no app.config, forçando tal propriedade a ser SHA1. Segue o link para maiores informações:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7-4.7.1

Att,
Guilherme

**Comment by rodrigordi** [comment]
Bom dia @gui-abrantes , sua dica é excelente! parabéns! será que teria como fazer a configuração via codigo ?

**Comment by gui-abrantes** [comment]
oi @rodrigordi,

Pra quem usa certificados que utilizam somente o SHA256, nunca me deparei ainda, no caso eu acho q teria q adicionar um parâmetro, que seja opcional para manter compatibilidade, passando o digestmethod e levando até o método _ObterAssinatura_ na classe _Assinador_, para assinar com a propriedade desejada!

**Comment by robertorp** [comment]
Poderia implementar para nós? e fazer um pull

**Comment by rodrigordi** [comment]
Observando a classe SignedXML do .NET Core (https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs) podemos ver que ele tem os DigVal definidos em constantes. 

Então eu alterei o código para 
var reference = new Reference { Uri = "#" + id };
reference.DigestMethod = "http://www.w3.org/2001/04/xmlenc#sha256";

E obtive a assinatura :
<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><DigestValue>M1KnaDQk+ZPwqJXEfLUlEJM4pQ3F5z6PxmOhSTxlFBA=</DigestValue>

E usando : 
reference.DigestMethod = "http://www.w3.org/2000/09/xmldsig#sha1";

obtive a assinatura
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>pObHmOb+bceWd49DCaxH7sv/kuM=</DigestValue>

Esse valor é válido pq fiz o calculo tbm usando :
 SHA1 HashAlg = SHA1.Create();
byte[] hash = HashAlg.ComputeHash(Encoding.UTF8.GetBytes(c14n));
var stHash = Convert.ToBase64String(hash);

Você conseguiria tirar a alteração do app.config e alterar o código para ver se esse código resolveria o problema ?

https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Utils/Assinatura/Assinador.cs linha 81

**Comment by rftd** [comment]
é so setar o tipo de assinatura que você quer no xml na hora de formar as informações de assinatura no reference como o rapaz acima postou

           var signedDocument = new SignedXml(doc)
            {
                SigningKey = certificado.PrivateKey,
                KeyInfo = keyInfo,
                SignedInfo =
                {
                    SignatureMethod = "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
                }
            };
           var reference = new Reference
            {
                Uri = uri,
                DigestMethod = "http://www.w3.org/2000/09/xmldsig#sha1"
            };

**Comment by rodrigordi** [comment]
Como o padrão da NFe é sha1, acho que poderia deixar a definição do digestmethod explicita como @rftd falou. não precisaria colocar parametro para usar sha256.

**Comment by robertorp** [comment]
NF-e CT-e CT-e OS, MDF-e, NFC-e todos são sha1

**Comment by rftd** [comment]
Sim SHA256 é eSocial e Reinf.

**Comment by rodrigordi** [comment]
@rftd , você tem o manual do E-social que fala sobre assinatura usando SHA256 ? Eu vi no manual do reinf falando que é sha256, mas no do eSocial eu não achei.

**Comment by rftd** [comment]
é no manual do desenvolvedor no fim da pagina de downloads da documentação

http://portal.esocial.gov.br/manuais/manualorientacaodesenvolvedoresocialv1-6-3.pdf

**Comment by rodrigordi** [comment]
Obrigado @rftd 

5. Função criptográfica assimétrica: RSA (http://www.w3.org/2001/04/xmldsigmore#rsa-sha256)
6. Função de message digest: SHA-256.
(http://www.w3.org/2001/04/xmlenc#sha256)
