### ISSUE TITLE
qrCode Invalido PR

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#68]
Ola Adenilton boa noite, 
estou tendo um problema no envio para sefaz do PR, quando eu altero o estado do Emitende para PR dá o seguinte erro:
Erros da validação : O elemento 'http://www.portalfiscal.inf.br/nfe:qrCode' é inválido - O valor 'www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?chNFe=41151102610949000139650010000000101000012340&nVersao=100&tpAmb=2&cDest=99999999000191&dhEmi=323031352d31312d30355430303a35303a33332d30323a3030&vNF=0.90&vICMS=0.00&digVal=507a37556969487647484476773434686e6e743472305679466b493d&cIdToken=000001&cHashQRCode=5d4f8282053a3e10f0faf6b818b54bec577765d1' é inválido dependendo do tipo de dados 'String' - Falha na restrição Pattern.

o mesmo nao acontece para  o estado  SE. como no projeto.

**Comment by vasisti** [comment]
Desculpe, eu quis dizer Identificação e não emitente. (ide)

**Comment by adeniltonbs** [comment]
Aparentemente a montagem do QR-Code está correta e de acordo com o manual.
O erro é durante a validação local ou é retornado pela SEFAZ como motivo de rejeição?
Outra obs. Consultando o site da SEFAZ do PR em http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97, vi que no exemplo de url para o QR-Code em "Nota 4", eles informam o campo "cIdToken" sem os zeros à esquerda. Isso é uma definição dessa SEFAZ? ou o exemplo deles está errado?

**Comment by adeniltonbs** [comment]
Detalhe, no Manual de Padrões Padrões Técnicos do DANFE-NFC-e e QR Code, o campo cIdToken aparece com os zeros a esquerda para deixar a string com tamanho = 6

**Comment by vasisti** [comment]
Ola adenilton, boa noite e grato pelo retorno, conforme sua observacao o erro esta dando na validacao. fiz alguns testes conforme a "Nota 4" que vc passou o erro esta na url do qrcode na classe endereçadorDanfeNfce como segue:
                new EnderecoNfceDanfe(Estado.PR, TipoAmbiente.taHomologacao, TipoUrlDanfeNfce.UrlQrCode, "www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe"),

esta faltando o http:// antes do www, assim gerando o erro. 

alguma solução/sugestao para acrescentar na url?
sem mais, abraços.
Valdir

**Comment by adeniltonbs** [comment]
Posso acrescentar, no entanto a informação do endereço de consulta do QR-Code sem o protocolo "http..." foi obtido no próprio site da sefaz do PR, conforme vc pode ver em http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97.

Você tem como testar se colocando o http funciona corretamente, ou confirmar com a SEFAZ se a informação do site está incorreta?

**Comment by vasisti** [comment]
Ola Adenilton boa tarde, quanto ao seu retorno eu fiz o teste e colocando o protocolo "http;//"
funciona prefeitamente. 
Agora temos outro problema, fis varios teste e não consegui entender, veja:

agora esta dando a rejeição: 
397 - Parâmetro do QR-Code divergente da Nota Fiscal. (vICMS)
percebi que a url do qrcode é gerado assim no projeto:

no xml de envio.
<qrCode>http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?

chNFe=41151102610949000139650010000000101000012340&amp;nVersao=100&amp;tpAmb=2&amp;cDest=99999999000191&amp;dhEmi=323031352d31312d30385431383

a31383a34312d30323a3030&amp;vNF=0.90&amp;vICMS=0.00&amp;digVal=6c4c7850534b67527932574755706a354c7041746f482b73756d6b3d&amp;cIdToken=000001&a

mp;cHashQRCode=d9191716aa9664f037c592578fa539730604bd88</qrCode>

note que o campo vICMS=0.00 esta assim formatado, certo, percebi que na tag do xml de envio esta assim veja:
<total>
<ICMSTot>
<vICMS>0</vICMS>

fiz o valor ficar assim:
<vICMS>0.00</vICMS>
como na url do qrcode,

ai passou a me retornar a rejeição:
464 = Codigo de Hash no QR-Code difere do calculado

obs: percebi que no xml esta gerando esta caracteres "&amp" na url do qrCode.
 grato  Valdir.

**Comment by adeniltonbs** [comment]
Então o site da SEFAZ está errado (mais uma vez^^)
Por curiosidade, qual a CST do ICMS que você utilizou no teste?

Obs: esse "&amp" é o caractere "&", conhecido como "ampersand", gravado como "&amp" e renderizado como "&". Veja mais sobre em https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references.

**Comment by vasisti** [comment]
Ola adenilton boa tarde, grato o retorno, estou usando o cst 102, o mesmo que esta no exemplo, apenas alterei o ncm pois esta invalido na validacao da sefaz.
ok.

**Comment by adeniltonbs** [comment]
Desculpa a demora vasisti, vou fazer os testes e alterações necessárias neste e em outros campos decimais para que isso não mais ocorra. Tão logo fizer, posto aqui.

**Comment by luanfranco** [comment]
Olá Adenilton,
Estou com o mesmo problema que o @vasisti relatou inicialmente.
Já adicionei o "http://" na URL mas mesmo assim não está funcionando.
Alguma sugestão?
Obrigado!

**Comment by mvidaldev** [comment]
Sefaz do RS está parado. 

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Fri, 5 Feb 2016 04:59:45 -0800

**Comment by prandini** [comment]
Na URL tem que conter o "https" como descrito na regra REGEX do arquivo "leiauteNFe_v3.10.xsd" ... aqui tive o mesmo problema e ajustei  a url iniciando com "https"

**Comment by prandini** [comment]
@vasisti conseguiu resolver este problema com o calculo do Hash do QRCode no PR?

**Comment by mvidaldev** [comment]
Coloca o CSC correto que resolve

Marcos VidalAnalista de SistemasCasters Automação Comercial
(45)3523-6012
(45)9903-6551

Date: Wed, 13 Apr 2016 12:07:37 -0700

**Comment by jefersoncarlos1** [comment]
pessoal, boa noite! 

Estou encontrando o mesmo problema para envido de NFCe para o estado do PARANÁ..
Alguém sabe como resolver o problema?

**Comment by vasisti** [comment]
Ola Pessoal, comigo esta tudo ok com o hash do QRCode no PR.

**Comment by prandini** [comment]
@brasvidal Obrigado pela resposta! Vou testar aqui, estou usando valores dos quais vi que poderia ser usado para ambiente de homologação; Identificador: 00001, CSC: 1234567890.

@vasisti Obrigado também pela resposta! Mas como você fez para contornar este erro? mais acima neste tópico você chegou a falar que estava parado neste erro também.

Obrigado! Quando realizar os teste com o CSC irei informar se deu tudo certo!

**Comment by mvidaldev** [comment]
Atualize também a pasta schemas...

www.casters.com.br/schemas.rar

Marcos VidalAnalista de SistemasCasters Automação Comercial

Date: Wed, 13 Apr 2016 18:04:09 -0700
