### ISSUE TITLE
dhEmi no xml de Evento

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#682]
Boa tarde,

Estou testando tanto o cancelamento quanto o CCe no Zeus pelo app de teste da NFe do proprio projeto, mas percebi que está gerando a tag dhEmi no xml, quando nao deveria estar!
Estou esquecendo de configurar algo?

Att,
Guilherme

**Comment by marcosgerene** [comment]
@gui-abrantes você usa o projeto via Nuget?

Eu corrigi isso recentemente neste pull https://github.com/ZeusAutomacao/DFe.NET/pull/680

Não sei se o @robertorp já subiu para o Nuget, mas se usa, atualize e teste, se não usa, basta atualizar que vai funcionar.

**Comment by gui-abrantes** [comment]
não uso pelo git mesmo.....mas pelo q vi faz, somente 11 dias desse pull....acho q atualizei antes disso vou atualizar novamente.... obrigado @marcosgerene

**Comment by robertorp** [comment]
@gui-abrantes  Deu certo?
Vou fazer o nuget hehe a versão que esta no nuget hoje esta totalmente funcional, sempre procuro esperar alguns dias antes de lançar no nuget.
Procuro deixar o nuget bem estável.

**Comment by gui-abrantes** [comment]
deu certo sim @robertorp, meu repositorio que estava desatualizado! valeu demais...
