### ISSUE TITLE
Problema com Estrutura do XML

### ISSUE THREAD

**Issue by DiegoPhillipe** [ZeusAutomacao/DFe.NET#684]
Prezados,

Estou com o mesmo problema da ISSUE 528 (https://github.com/ZeusAutomacao/DFe.NET/issues/528). Alguém sabe como resolver?

**Comment by marcosgerene** [comment]
@DiegoPhillipe anexe o xml que não foi validado.

**Comment by DiegoPhillipe** [comment]
Segue xml em anexo. 
O problema é que a tag "orig" do icms00 está sendo montada na estrutura incorreta e não sei como consertar isso.

[xmlEnvio.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1881232/xmlEnvio.zip)

**Comment by marcosgerene** [comment]
Não vi problemas na estrutura, e importei o XML e validei pelo DEMO e obtive sucesso.

![image](https://user-images.githubusercontent.com/15945003/38393985-2203c9d6-3903-11e8-8a0e-bd662b44bb3d.png)

Poderia testar por favor com o fonte atualizado? Caso o erro se repita, simule o erro no Demo e envie o passo a passo de como faze-lo.

----------

Testei aqui localmente emitindo uma nota com o fonte atualizado e repare nas estruturas:
Sua nfe:
![image](https://user-images.githubusercontent.com/15945003/38394622-97743dfc-3905-11e8-8bd5-cfd810c91738.png)

A minha:
![image](https://user-images.githubusercontent.com/15945003/38394633-a46762f0-3905-11e8-932f-9cfe19a6cf14.png)

 [nfe_autorizada.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1882015/nfe_autorizada.zip)

Repare que a posição do CST e da orig muda nas duas notas. Confira se o seu fonte está atualizado, caso não esteja atualize.

PS: eu preencho a nfe desta forma:
```
var icms00 = new NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.ICMS00();
icms00.orig = ZeusOrigemMercadoria(_prod.Origem);
icms00.CST = ZeusCstICms(item.Icms.Cst.ToString().StrToIntDef());
icms00.modBC = _modBc;
icms00.vBC = item.Icms.Base;
icms00.pICMS = item.Icms.Aliquota;
icms00.vICMS = item.IcmsValor;
```

**Comment by marcosgerene** [comment]
@DiegoPhillipe deu certo? por favor dê um feedback e caso esteja ok feche a issue.

**Comment by DiegoPhillipe** [comment]
Deu certo. Para corrigir o problema tive que colocar o order em cada atributo. 

Ex: [XmlElement("nomeatrributo", Order = 1)]

**Comment by marcosgerene** [comment]
@DiegoPhillipe então está errado, ordenar os atributos para serealizar o xml é função do componente, não do ERP.

Me passe o trecho de código que você alterou.

Mas de qualquer forma, o componente está funcional, eu e mais uma boa galera usa em produção numa quantidade considerável de clientes.

**Comment by DiegoPhillipe** [comment]
Segue classe alterada em anexo.
[ICMS00.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1907379/ICMS00.zip)

OBS: Estou usando a versão 4.0 do .Net Framework, pode ser uma das causas do problema?

**Comment by marcosgerene** [comment]
@DiegoPhillipe tenho conhecimento do pessoal que a 4.5.2 e eu uso a 4.6.x e 4.7.x, da 4.0 não conheço


Vou analisar seu arquivo aqui, dou um retorno ate o fim da tarde.

**Comment by rftd** [comment]
Não tem diferença neste caso entre a 4 e a 4.5.2.
Sobre o atributo order ele é necessário quando os elementos devem ficar em uma determinada ordem, sem ele os elementos são gerados na ordem que são declarados na classe.

**Comment by rodrigordi** [comment]
@marcosgerene 

Será que essa ordem de preenchimento faz diferença ?

var icms00 = new NFe.Classes.Informacoes.Detalhe.Tributacao.Estadual.ICMS00();
icms00.orig = ZeusOrigemMercadoria(_prod.Origem);
icms00.CST = ZeusCstICms(item.Icms.Cst.ToString().StrToIntDef());
icms00.modBC = _modBc;
icms00.vBC = item.Icms.Base;
icms00.pICMS = item.Icms.Aliquota;
icms00.vICMS = item.IcmsValor;

**Comment by DiegoPhillipe** [comment]
@rodrigordi 

Estou preenchendo exatamente nessa ordem.

**Comment by rodrigordi** [comment]
@DiegoPhillipe realmente isso não faz sentido 😄 
Fiz até um teste fora do Zeus mesmo, fazendo serialização.

![image](https://user-images.githubusercontent.com/1608626/38749895-8cea617a-3f29-11e8-9d77-ad6db0739c64.png)

**Comment by DiegoPhillipe** [comment]
@rodrigordi E o maior problema é que não ocorre todo momento.

**Comment by rodrigordi** [comment]
@DiegoPhillipe  qual função que voce usa para serializar ?

**Comment by marcosgerene** [comment]
Eu vi o arquivo que você enviou e adicionei ao meu pull atual... o que você fez "força"a ordenação, se tiver um problema como o relatado vai sanar, e se não houver problemas, bem, mal não vai fazer a alteração.

https://github.com/ZeusAutomacao/DFe.NET/pull/688/commits/21e97c426372a021dc3e98f705e314a817754d02

**Comment by DiegoPhillipe** [comment]
@marcosgerene Segue em anexo as demais classes de ICMS alteradas.
[ICMS.zip](https://github.com/ZeusAutomacao/DFe.NET/files/1915303/ICMS.zip)

**Comment by marcosgerene** [comment]
@DiegoPhillipe o arquivo que você enviou ai numa pagina 404.

Por favor envie a sugestão em forma de Pull request

**Comment by DiegoPhillipe** [comment]
@marcosgerene Enviado.

**Comment by robertorp** [comment]
Problemas foram resolvidos?

**Comment by DiegoPhillipe** [comment]
Sim.

2018-04-24 14:24 GMT-03:00 Roberto Alves Pereira <notifications@github.com>:

**Comment by robertorp** [comment]
ok, obrigado, vou fechar a issue.

**Comment by DiegoPhillipe** [comment]
Ok

Em ter, 24 de abr de 2018 às 14:26, Roberto Alves Pereira <
notifications@github.com> escreveu:
