### ISSUE TITLE
Erro FastReports

### ISSUE THREAD

**Issue by jeffersonfd** [ZeusAutomacao/DFe.NET#69]
Adenilton, bom dia...

Estou tendo problemas com o código em relação ao FastReports:

Erro    4   The type or namespace name 'FastReport' could not be found (are you missing a using directive or an assembly reference?)

Não possuo o FastReports instalado na máquina, quando tento fazer o download da versão demo no site informado também não está sendo possível baixar o instalador. Alguma sugestão de como eu posso conseguir o instalador?

**Comment by adeniltonbs** [comment]
Bom dia jefferson, acabei de testar o link de download do fast report demo "https://www.fast-report.com/pt/product/fast-report-net/", citado na página inicial desta biblioteca e consegui baixar normalmente.

Quando você acessar o link, clique na opção download:
![image](https://cloud.githubusercontent.com/assets/6733483/10969736/fe9d39d0-83a8-11e5-958d-34349e70bbd6.png)

Depois, na próxima página, clique no link FastReports.net
![image](https://cloud.githubusercontent.com/assets/6733483/10969769/1970bd04-83a9-11e5-94ae-137172ffd6fe.png)

Obs: o Demo do fast reports não expira, e é completamente funcional. A única limitação dele é colocar uma marca d'água na impressão.

**Comment by jeffersonfd** [comment]
Adenilton, realmente o link está funcionando.
O problema estava nas configurações de segurança aqui da empresa, o link para download acabou caindo nas regras do firewall.

Agradeço muitíssimo pela ajuda.
