### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#693]
Olá!
Estou carregando XMLs de notas para o meu sistema utilizando o método DFe.Utils.FuncoesXml.ArquivoXmlParaClasse[T](String arquivo).
Derrepente lá pelas tantas, depois de uns 1500 arquivos, surge esta mensagem System.OutOfMemoryException.
Verifiquei no Gerenciador de Tarefas do Windows e a memória ocupada pelo meu aplicativo é por volta de 8k.
Na nota que aconteceu este problema pelos meus testes tem apenas um item.

Segue o Trace:
System.OutOfMemoryException was caught
  HResult=-2147024882
  Message=Exceção do tipo 'System.OutOfMemoryException' foi acionada.
  Source=mscorlib
  StackTrace:
       em System.Reflection.Emit.TypeBuilder.SetMethodIL(RuntimeModule module, Int32 tk, Boolean isInitLocals, Byte[] body, Int32 bodyLength, Byte[] LocalSig, Int32 sigLength, Int32 maxStackSize, ExceptionHandler[] exceptions, Int32 numExceptions, Int32[] tokenFixups, Int32 numTokenFixups)
       em System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
       em System.Reflection.Emit.TypeBuilder.CreateType()
       em System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(String[] methods, XmlMapping[] xmlMappings, Type[] types)
       em System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence)
       em System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
       em System.Xml.Serialization.XmlSerializer.FromMappings(XmlMapping[] mappings, Type type)
       em System.Xml.Serialization.XmlSerializer.FromTypes(Type[] types)
       em DFe.Utils.FuncoesXml.ArquivoXmlParaClasse[T](String arquivo)

Se eu finalizar a aplicação e iniciar novamente o sistema importa a nota normalmente, até chegar lá pelos 1500 arquivos novamente e trava dando a mesma mensagem.

Alguém já teve este problema ou sabe como resolver isso?

**Comment by ricardopdv** [comment]
já atualizou ? porque esse problema acontecia comigo e foi resolvido

**Comment by marciojmuller** [comment]
Não atualizei, vou tentar amanhã isso então.

**Comment by robertorp** [comment]
Bom dia, atualizou? oque aconteceu?

**Comment by marciojmuller** [comment]
Olá!
Atualizei as DLLs agora a pouco, o problema continua.
