### ISSUE TITLE
Sem comunicação com o serviço

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#696]
após atualizar a versão do zeus.nfe/nfce da erro em todos os serviços da o seguinte erro:
"Sem comunicação com o serviço NFeAutorizacao: conexão subjacente estava fechada: Erro inesperado em um recebimento."
o erro também ocorre em outros serviços como consulta status.

**Comment by robertorp** [comment]
aqui esta normal, estou usando o mais atual nuget.

pesquisa um pouco sobe o erro, acho que tem bastante conteúdo aqui já sobre o mesmo.

**Comment by ThalisonSantos** [comment]
estava usando normal pela manhã depois que atualizei começou esse problema.

Edit: vou pesquisar

**Comment by ThalisonSantos** [comment]
@robertorp  consegui resolver valeu
