### ISSUE TITLE
importar xml e popular um datagridview

### ISSUE THREAD

**Issue by NILTONMOREIRA** [ZeusAutomacao/DFe.NET#697]
Bom dia, onde encontro a classe onde eu possa importar o xml e popular na datagridview. ?

**Comment by robertorp** [comment]
Não tem nada relacionado diretamente a um datagridview aqui. 
Isso e algo individual.

**Comment by NILTONMOREIRA** [comment]
ok, entendi, qual é a classe possa fazer leitura do xml da NFe  nesse projeto ?

**Comment by marcosgerene** [comment]
Bom dia,

A datagridview aceita List<T> como source, tanto no wpf quanto no winforms. Neste caso, basta ter um objeto de nfe ou nfeproc, para isto no demo tem exemplos de como carregar um xml para consultar, como carregar um xml para imprimir, etc, logo bastaria ver no demo como carregar o xml em memória e jogar ele num List<nfeproc>. Segue um exemplo:

```
var notas = new List<nfeproc>();
while (...)
{
	nfeProc proc = null;
	try
	{
		proc = new nfeProc().CarregarDeArquivoXml(arquivoXml);
	}
	catch //Carregar NFe ainda não transmitida à sefaz, como uma pré-visualização.
	{
		proc = new nfeProc() { NFe = new Classes.NFe().CarregarDeArquivoXml(arquivoXml), protNFe = new Classes.Protocolo.protNFe() };
	}
	notas.Add(proc);
}

minhaGrid.DataSource = notas;
```

[]'s

**Comment by NILTONMOREIRA** [comment]
marcosgerene, isso, esse é o caminho que preciso.. daqui a pouco retorno se funcionou ..

obrigado pelo retorno..

**Comment by marcosgerene** [comment]
@NILTONMOREIRA deste ponto que te mandei em diante é programação da sua ferramenta, não mais do componente em si.

Se sua dúvida foi sanada, feche a issue.
