### ISSUE TITLE
Recuperar XML NFC-e

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#70]
Adenilton, bom dia,

No caso de perda de XML da NFC-e (ProcNFe) como faço para recuperar (ou recompor) o mesmo?

Agradeço desde já, 
Roberto.

**Comment by adeniltonbs** [comment]
Desculpa a demora, no caso da perda do XML da NFCe, não há como recuperá-lo, pois o serviço NfeDownloadNF das SEFAZes aceitam apenas documentos modelo 55 (NFe).

Que eu saiba, em relação a NFCe, a única coisa que você pode recuperar é o objeto protNFe, através do serviço NfeConsultaProtocolo.

Agora se você tem os dados da NFCe armazenados no banco de dados, poderá recriar o objeto NFe e gerar novamente o nfeProc com esse objeto e o protNFe retornado pela SEFAZ. No entanto é melhor salvar em algum lugar o xml que foi autorizado pela SEFAZ, juntamente com o protNFe.

Se tiver dúvidas de como fazer isso, veja o botão "Adicionar proc ao XML" da aplicação de demonstração.

**Comment by adeniltonbs** [comment]
Resposta da Receita Federal para seu caso:
http://www.nfe.fazenda.gov.br/portal/perguntasFrequentes.aspx?tipoConteudo=lWG+ydeHRQg=
