### ISSUE TITLE
PROBLEMA NA SEFAZ, OQUE FAZER

### ISSUE THREAD

**Issue by hbdbim** [ZeusAutomacao/DFe.NET#700]
O SEFAZ do Amazonas esta retornando em homologação para NFCe 4.00 o seguinte xml

[RETORNO NFCe 4.00](https://drive.google.com/file/d/1Q8mV4xP7P5JwDKmXINjwoYR4SzKaOCBu/view)

Note o campo dhRecbto está com valor errado (2018-04-23T11:40:13-04:00-04:00), tem o fuso horario duas vezes.

Para a NFCe 3.10 o seguinte xml

[RETORNO NFCe 3.10](https://drive.google.com/file/d/1BGI3v6OBdrVqqt6QpQ7cM5RhL9aWldf1/view?usp=sharing)

A tag do retorno `<retConsReciNFe>` esta errada deveria ser `<retEnviNFe>` (retorna assim quando rejeição por nota duplicada ).

Como faço pra reportar esses problemas para a SEFAZ, alguém tem ideia ?

[]´s

**Comment by rodrigordi** [comment]
opa. voce vai ter que tentar entrar em contato com a SEFAZ AM que tem autorizador próprio. Eu tentei pegar no site mas acabou de sair do ar.

http://sistemas.sefaz.am.gov.br/nfeweb/portal/index.do

**Comment by hbdbim** [comment]
Mandei um email para nfe@sefaz.am.gov.br, esperar e ver se respondem.

**Comment by hbdbim** [comment]
Sefez AM já esta me respondendo, já resolveram o problema com dhRecbto, agora estão verificando o problema com a chamada compactada, segue e-mail resposta do sefaz.

> Prezados,
> 
> Iremos corrigir a tag dhRecbto.Nos envie o XML compactado que está dando erro.
> 
> O erro da versão 3.10, já temos conhecimento, mas como a versão 3.10 vai ser descontinuada em breve, não iremos alterar, pois irá afetar muitos contribuintes que já estão operando.
> 
> Att:
>

**Comment by robertorp** [comment]
solucionou o problema?
