### ISSUE TITLE
Problemas Relatados Versão 4.0

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#702]
Bom dia.
Recentemente fui iniciar testes na versão 4.0 e tive alguns problemas.
vou relaciona-los abaixo

No mato grosso a NFC-e retorna sempre o ERRO 404 como nos navegadores. 
Not Found (404) 

URL Paraíba NFC-e 4.0
esta sendo passado isso
https://www6.receita.pb.gov.br/atf/seg/SEGf_AcessarFuncao.jsp?cdFuncao
porem no site [(http://nfce.encat.org/desenvolvedor/qrcode/ )]
não é este para versão 4.0

Outros testes e erros
--------------------------------------------------------------------------------
Status serviço 
--------------------------------------------------------------------------------
Homologação = 4.0 MT            ok
Produção = 4.0 MT               reference object not stance object

--------------------------------------------------------------------------------
Carta de Correção
--------------------------------------------------------------------------------
Homologação = 4.0 MT             ok
Produção = 4.0 MT                Serviço RecepcaoEventoCartaCorrecao, versão 4.00, não disponível para a UF MT, no ambiente de Produção para emissão tipo Normal, documento: NF-e!  

--------------------------------------------------------------------------------
Inutilizacao
--------------------------------------------------------------------------------

Homologação = 4.0 BA             Server did not recognize the value of HTTP Header SOAPAction: http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao/nfeInutilizacaoNF.
Homologação = 4.0 BA             Server did not recognize the value of HTTP Header SOAPAction: http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao/nfeInutilizacaoNF.

Homologação = 4.0 PR             reference object
Produção = 4.0 PR                reference object

Homologação = 4.0 RO             Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2/nfeInutilizacaoNF2' was not recognized.
Produção = 4.0 RO                Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2/nfeInutilizacaoNF2' was not recognized.

**Comment by robertorp** [comment]
Se possível vá postando eles todos que você testar e achar, logo estarei corrigindo, estou implementando aqui a nf-e 4.00 e nfc-e 4.00 e nosso sistema e para o Brasil todo ou seja, ate daqui poucos dias estarei corrigindo tudo oque houver, obrigado.

**Comment by hbdbim** [comment]
A Sefaz MT esta muito confusa com suas URL´s, e pelo que entendi em contato com eles ainda não tem url de produção para NFCe.
segue resposta do [atendimento.ti@sefaz.mt.gov.br](mailto:atendimento.ti@sefaz.mt.gov.br)

> Boa tarde,
> Segue abaixo a informação solicitada.
>  
> são da NF-e. A NFC-e na versão 4.00 só está disponível em homologação. Segue a URL da NFC-e de homologação:
>  
>  
> NFeAutorizacao 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao4?wsdl
> NFeRetAutorizacao 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao4?wsdl
> NfeInutilizacao 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao4?wsdl
> NfeConsultaProtocolo 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeConsulta4?wsdl
> NfeStatusServico 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico4?wsdl
> RecepcaoEvento 4.00 - https://homologacao.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4?wsdl
>  
>  
> Att,
>  
> Fernanda Martins Bezerra
> Gerência de Serviços de Suporte e Atendimento em TI
> Secretaria de Estado de Fazenda de Mato Grosso
> GSTI/COTI/SAAF/SEFAZ
> Fone: (65) 3617-2340
> E-mail: atendimento.ti@sefaz.mt.gov.br
>

**Comment by robertorp** [comment]
url Mato grosso fiz uma correção, vou postando oque corrigi aqui editando essa resposta

quando finalizar faço push de tudo e gero nuget


nfce paraíba corrigido

publicado no nuget... daqui 30 minutos ou 2 horas ele aparece na lista
