### ISSUE TITLE
NFCe v4.00 está funcional?

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#704]
o que devo colocar no campo urlChave?

**Comment by robertorp** [comment]
No app exemplo do zeus NFeTeste  Linha 322

temos o seguinte

```
if (_nfe.infNFe.ide.mod == ModeloDocumento.NFCe &&
                    _configuracoes.CfgServico.VersaoNFeAutorizacao == VersaoServico.ve400)
                {
                    _nfe.infNFeSupl = new infNFeSupl();
                    _nfe.infNFeSupl.urlChave = _nfe.infNFeSupl.ObterUrl(_configuracoes.CfgServico.tpAmb, _configuracoes.CfgServico.cUF, TipoUrlConsultaPublica.UrlQrCode);
                }
```

**Comment by ThalisonSantos** [comment]
@robertorp gera uma exceção esse método:
Não foi possível obter o Endereço para consulta da NFCe através do site, para o Estado AL, ambiente: Homologação

**Comment by robertorp** [comment]
Especifique os passos utilizados para obter essa exception ai para min

**Comment by ThalisonSantos** [comment]
@robertorp a única diferença ai foi que eu passei a versão do serviço com 4.00

**Comment by ThalisonSantos** [comment]
@robertorp  consegui resolver é só não passar a versão do serviço que não causa exceção

**Comment by robertorp** [comment]
@ThalisonSantos  poderia mandar uma print do app teste na parte de configuração de urls de como fica quando da o erro, para eu simular o mesmo aqui? 
e uma print do código dando o erro (código digitado para dar o erro)

**Comment by ThalisonSantos** [comment]
@robertorp já consegui resolver no método obterUrl se vc passa a versão do serviço = 4.00 ele gera essa exceção, se não informar nada não da erro.
estava dessa forma : infNFeSupl.urlChave = infNFeSupl.ObterUrl(CFGServico.tpAmb, CFGServico.cUF, TipoUrlConsultaPublica.UrlQrCode, CFGServico.VersaoNFeAutorizacao);

**Comment by robertorp** [comment]
Ajustei isso já. 
Pode passar a versão 4 agora que ele vai obter a url corretamente.
