### ISSUE TITLE
Como tratar assembly não assinado?

### ISSUE THREAD

**Issue by nelsonasousa** [ZeusAutomacao/DFe.NET#705]
Olá,
Sou novato no uso do github e gostaria de saber como tratam a questão de assinatura dos assemblies.
Inseri as dlls do Zeus em meu projeto e tenho recebido a mensagem de erro de que as mesmas não têm os assemblies assinados.
Acontece também se utilizo as dlls via Nuget.

**Comment by facilita-tecnologia** [comment]
Boa Tarde, abre o seu Visual Studio, Vai na propriedade do seu projeto 

Vai Ter as opções 

- Aplicativo
- Build
- Eventos de Build

etc

la pra nona Opção vai ter uma opção chamada Assinatura

Desmarca tudo salva e tenta rodar o projeto pra ver se vai solucionar.

**Comment by nelsonasousa** [comment]
Mas aí a instalação via Clickonce vai ser prejudicada, não vai não?
