### ISSUE TITLE
Problema na conexão

### ISSUE THREAD

**Issue by maiconkamiya** [ZeusAutomacao/DFe.NET#706]
Conexão subjacente estava fechada: Não foi possível estabelecer relação de confiança para o canal seguro de SSL/TLS

**Comment by eduprog** [comment]
No grupo skype do zeus, tinha uma pessoa com o mesmo problema e resolveu com este link:
https://pt.stackoverflow.com/questions/224841/falha-httpwebrequest

```System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;```

**Comment by rodrigordi** [comment]
Nos cenarios que eu tive com windows 7, precisa estar todo atualizado e com .net 4.5.2 ou superior. Se o problema com certificados servidores da sefaz, os mesmos devem estar instados no repositório do windows nas pastas root ca e intermediate ca.

**Comment by robertorp** [comment]
@maiconkamiya 
conseguiu? 
http://www.robertorp.com.br/2017/10/erro-comun-no-framework-zeusnetnfenfce.html

**Comment by robertorp** [comment]
sem resposta do autor

**Comment by maiconkamiya** [comment]
Consegui resolver. Tive que instalar a cadeia de certificado raiz
