### ISSUE TITLE
NfeDistDFeInteresse - Falha ao retornar documento

### ISSUE THREAD

**Issue by ricardopdv** [ZeusAutomacao/DFe.NET#707]
Quando tento retornar uma Nfe pela chave e a mesma está cancelada, o SEFAZ retorna o erro : 653 - Nfe Cancelada, porem o Zeus tenta carregar o XML e retorna um exception. estou acertando a rotina aqui na minha versao mas acredito que tenha que ser colocada no Zeus.

Retorno:
`<retDistDFeInt xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" versao="1.01" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>1.1.9</verAplic><cStat>653</cStat><xMotivo>Rejeicao: NF-e Cancelada, arquivo indisponivel para download</xMotivo><dhResp>2018-05-01T22:06:45-03:00</dhResp></retDistDFeInt>`

Classe : ServicosNFe
Função : NfeDistDFeInteresse
Linha : var retConsulta = new retDistDFeInt().CarregarDeXmlString(retornoXmlString);

Não vem informações de NSU, ultNSU e lote. Dá erro na hora de deserializar. 

O que fazer ?

**Comment by robertorp** [comment]
Vamos ter que analisar o processo que vc fez.
Poderia descrever ele detalhadamente para estarmos analisando o mesmo de melhor maneira.

**Comment by ricardopdv** [comment]
Entao Roberto acho que detalhei bastante o problema. Só nao sei o que fazer pois nao domino o xml serializer. Eu recebo o lote de distribuicao com as notas e eventos normalmente. apos a ciencia da emissao, tento baixar um documento pela chave so que esse documento esta cancelado. o sefaz esta retornando o xml acima descrito com o cstat = 653. no xml nao existem todos os campos do retdistdfeint como os que mencionei. nessa situacao esses campos deveriam ser ignorados na desserializacao. so nao sei qual atributo usar no campo para ignorar os campos faltantes.

**Comment by ricardopdv** [comment]
isso acontece quando a situacao da nfe no resevento esta 3 - nota cancelada
