### ISSUE TITLE
Nota Técnica 2016.002 - v 1.50

### ISSUE THREAD

**Issue by DiegoPhillipe** [ZeusAutomacao/DFe.NET#708]
Pessoal, Bom dia

Tem alguma previsão para implementação das alterações da Nota Técnica 2016.002 - v 1.50?

**Comment by marcosgerene** [comment]
Ainda não vi ninguém falar sobre isso. Sinta-se a vontade para implementar e enviar um PR. Caso vá fazer a implementação avise a comunidade para que não haja várias pessoas fazendo ao mesmo tempo, mas sim uma união de esforços.

**Comment by rodrigordi** [comment]
Já tem as classes do 4.00 ? Eu fiz em outro projeto e foi simples. 

motDesICMS : incluir nova opcao 90 - Solicitado pelo Fisco para ICMS 40,41,50
ICMSUFDest : pFCPUFDest é opcional e alterado o tipo para TDec_0302a04
ICMSUFDest : vFCPUFDest é opcional e alterado o tipo para TDec_0302a04
NFe.InfNFe.Pag.DetPag : incluir novo campo opcional indPag
NFe.InfNFe.Supl : QRCode com nova "pattern" para aceitar url versão 2.00
NFe.InfNFe.Det.Imposto.ISSQN : incluido o tipo de serviço 17.25

TDec_0304Max100 : "pattern" alterada
TDec_0302a04Max100 : "pattern" alterada

**Comment by DiegoPhillipe** [comment]
@rodrigordi Rodrigo, já tem as classes sim. Teria como disponibilizar as alterações ou solicitar um pull?

**Comment by rodrigordi** [comment]
@DiegoPhillipe não fiz nesse projeto. Fiz em outro que mantenho.

No projeto, o MotivoDesoneracaoIcms é o mesmo para os ICMS : 40, 30, 90, 20, 70. Na SEFAZ a alteração seria apenas no 40. Coloca para todos ou cria um novo enum ?

![image](https://user-images.githubusercontent.com/1608626/39543009-72edb4d8-4e20-11e8-9bc1-db489ac08038.png)

**Comment by DiegoPhillipe** [comment]
@rodrigordi Rodrigo, acredito que pode colocar para todos pois não haverá impacto.

**Comment by robertorp** [comment]
Amanhã vou estar fazendo as alterações no zeus, estou implementado nfe4 aqui em minha aplicação, somente vou conferir as alteração da NT 2016.002 1.50 e implementar as mesmas no Zeus antes de colocar em minha aplicação.

**Comment by DiegoPhillipe** [comment]
@robertorp Blz Roberto.

**Comment by robertorp** [comment]
Feito a implementação já.
Faltando apenas a conferencia da parte do qrcode.
@DiegoPhillipe  poderia conferir se o qrcode esta sendo gerado corretamente? 
https://github.com/ZeusAutomacao/DFe.NET/pull/710

**Comment by DiegoPhillipe** [comment]
@robertorp Irei conferir agora e lhe confirmo.

**Comment by DiegoPhillipe** [comment]
@robertorp O qrcode não está sendo gerado corretamente seguindo os parâmetros do Manual de Especificações Técnicas do DANFE NFC-e QR_Code - versão 5.0. Além disso, não tem implementação para diferenciar o qrcode no ambiente Online e Contingência.

**Comment by DiegoPhillipe** [comment]
@robertorp O qrCode não está sendo gerado corretamente conforme versão 2.0.

**Comment by DiegoPhillipe** [comment]
@robertorp Você irá implementar essa parte do qrcode?

**Comment by robertorp** [comment]
@DiegoPhillipe  So não vou implementar se alguém manifestar interesse em implementar antes hehe.

**Comment by robertorp** [comment]
alguns assuntos relacionados a qrcode que estou lendo, se houver algo mais e poder informando, para eu estar lendo

**Comment by DiegoPhillipe** [comment]
@robertorp Desculpa a demora. Segue link para acesso ao manual de orientações do QrCode 5.0:

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=/xyXbAFZ71k=

**Comment by robertorp** [comment]
![image](https://user-images.githubusercontent.com/10251705/39884020-e65d6406-545e-11e8-9b10-5b90de792f76.png)
Vou aguardar ate a data da liberação de homologação, e de acordo com a NT vai ser valido tanto versão 1.00 e versão 2.00 do qrcode até a data 01/10/2018
