### ISSUE TITLE
Erro no QRCode na versão reduzida NFC-e

### ISSUE THREAD

**Issue by srwil** [ZeusAutomacao/DFe.NET#709]
Quando mando gerar/imprimir a NFC-e reduzida o valor do QR Code é sempre:

`http://www.hom.nfe.se.gov.br/portal/consultarNFCe.jsp?chNFe=28170107703290000189650010000013761000000351&nVersao=100&tpAmb=2&cDest=99999999000191&dhEmi=323031372d30312d30395431353a35333a35312d30333a3030&vNF=7.65&vICMS=1.38&digVal=6b31414c6745487445686c634558754c7846504d446530774339513d&cIdToken=000003&cHashQRCode=78068664e1b2862a078564332508ea6f964cb93c`

Com o mesmo xml na versão normal a url  é gerada corretamente!

**Comment by marcosgerene** [comment]
Por favor anexe o xml da NFCe e o pdf gerado pelas 2 versões.

**Comment by srwil** [comment]
Não precisa de um xml especifico, qualquer um que for gerado e impresso com QR Code lateral, o QR Code sai fixo!

**Comment by marcosgerene** [comment]
Eu não utilizo meu sistema na versão 4.00 da NFe ainda, por favor anexe um xml para que eu possa testar ou infelizmente vamos depender de outra pessoa que também use o Fast para te ajudar.

**Comment by srwil** [comment]
Não tive autorização para postar o XML

**Comment by marcosgerene** [comment]
@srwil se qualquer xml acontece o mesmo erro basta emitir um em homologação e postar... eu nao tenho como fazer aqui porque meu sistema ainda nao ta pronto pra nfce 4.0

**Comment by srwil** [comment]
Em anexo!

[26180505068001000191650010000010009000012342.txt](https://github.com/ZeusAutomacao/DFe.NET/files/1979810/26180505068001000191650010000010009000012342.txt)

![normal 2](https://user-images.githubusercontent.com/38052991/39701933-692531f8-51d9-11e8-94ac-e859c5620e86.png)

![lateral 2](https://user-images.githubusercontent.com/38052991/39701940-6b196b00-51d9-11e8-8e23-eeb339227dee.png)

**Comment by marcosgerene** [comment]
@srwil corrigido em https://github.com/ZeusAutomacao/DFe.NET/pull/712

Por favor teste e dê um feedback, caso seu problema tenha sido resolvido feche a issue.

**Comment by marcosgerene** [comment]
Corrigido em https://github.com/ZeusAutomacao/DFe.NET/pull/712

**Comment by srwil** [comment]
QRCode sendo gerado corretamente, obrigado!
