### ISSUE TITLE
erro ao enviar email

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#718]
alguns clientes tenho recebido essa exceção ao enviar uma nfe por email, alguém passou pro esse problema?

System.Net.Mail.SmtpException: Falha ao enviar email. ---> System.IO.IOException: Não é possível ler os dados da conexão de transporte: Foi forçado o cancelamento de uma conexão existente pelo host remoto. ---> System.Net.Sockets.SocketException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
   em System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   em System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   em System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   em System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- Fim do rastreamento de pilha de exceções internas ---

**Comment by robertorp** [comment]
Seu email e senha estão corretos?
se for gmail se não me engano em segurança na sua conta vc deve liberar algo.

enfim

que e-mail esta usando?  gmail, hotmail, algum próprio de vocês?

**Comment by ThalisonSantos** [comment]
@robertorp aconteceu com o gmail e o outlook , o mais estranho é que com o gmail ele envia algumas notas e depois começa da esse erro

**Comment by robertorp** [comment]
tanto hotmail como gmail e outros, dependendo da quantidade de envios eles bloqueiam o envio, imagino eu que e causado o bloqueio pois imaginam ser span talvez.

Entra no hotmail la deve ter informações que causam o bloqueio talvez.

**Comment by robertorp** [comment]
Vou considerar a issue como resolvida, se não tiver resolvido com a dica que dei acima me diz.
