### ISSUE TITLE
Partilha de ICMS

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#72]
Olá Adenilton,

Sabe informar se é obrigatório tambem para os optantes do simples a questão da partilha do ICMS entre os estados???

NT 2015.003
Entra em vigor em em janeiro de 2016...
e estou por fora disso :-(.

**Comment by adeniltonbs** [comment]
celino, olhando a NT 2015.003, o grupo "ICMSUFDest" terá como elemento pai o grupo "imposto" (M01), isso quer dizer que tecnicamente essas informações poderão ser preenchidas por qualquer tipo de empresa (Normal, Simples e Simples - Excesso de sublimite).

Agora como o grupo "ICMSUFDest" é opcional, não sei dizer se vai ser obrigatório para simples. A única coisa que o manual diz é "Grupo a ser informado nas vendas interestaduais para consumidor final, não contribuinte do ICMS".

Recomendo entrares em contato com um contador para ver isso.

**Comment by celinolimac** [comment]
Obrigado pelo retorno Adenilton, vou verificar sim com o contador.. obrigado!
