### ISSUE TITLE
[REPETIDO] System.OutOfMemoryException

### ISSUE THREAD

**Issue by marciojmuller** [ZeusAutomacao/DFe.NET#723]
Olá!
Não consegui reabrir a issue #693 então estou abrindo outra.
Atualizei as DLLs da biblioteca, mas o problema continua.
Simplesmente recebendo arquivos de notas, quando chega em uns 1500 arquivos acontece esta exceção System.OutOfMemoryException.
Verifiquei no Gerenciador de Tarefas do Windows e a memória ocupada pelo meu aplicativo é por volta de 8k.

Segue o Trace:
System.OutOfMemoryException was caught
HResult=-2147024882
Message=Exceção do tipo 'System.OutOfMemoryException' foi acionada.
Source=mscorlib
StackTrace:
em System.Reflection.Emit.TypeBuilder.SetMethodIL(RuntimeModule module, Int32 tk, Boolean isInitLocals, Byte[] body, Int32 bodyLength, Byte[] LocalSig, Int32 sigLength, Int32 maxStackSize, ExceptionHandler[] exceptions, Int32 numExceptions, Int32[] tokenFixups, Int32 numTokenFixups)
em System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
em System.Reflection.Emit.TypeBuilder.CreateType()
em System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(String[] methods, XmlMapping[] xmlMappings, Type[] types)
em System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence)
em System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
em System.Xml.Serialization.XmlSerializer.FromMappings(XmlMapping[] mappings, Type type)
em System.Xml.Serialization.XmlSerializer.FromTypes(Type[] types)
em DFe.Utils.FuncoesXml.ArquivoXmlParaClasse[T](String arquivo)

Se eu finalizar a minha aplicação e iniciar novamente a aplicação importa a nota normalmente, até chegar lá pelos 1500 arquivos novamente e trava dando a mesma mensagem.

Para não me acontecer este problema por enquanto quando chega em 500 notas eu fiz um procedimento para fechar a aplicação e abri-la novamente, mas queria ver uma forma de não ter que ficar fechando a aplicação toda hora.

Alguém sabe uma forma de resolver este problema?

**Comment by robertorp** [comment]
Poderia enviar o trecho de código do seu sistema que faz isso? para eu estar simulando algo parecido aqui no meu computador.

**Comment by marciojmuller** [comment]
DirectoryInfo pasta = new DirectoryInfo(this.DiretorioRecebimento);
FileInfo[] arquivos = pasta.GetFiles().Take(30).ToArray();

foreach (var arquivo in arquivos)
{
	string arqNFe = this.DiretorioRecebimento + "\\" + arquivo.Name;

	try
	{
		NFe.Classes.nfeProc proc = null;

		try
		{
			proc = DFe.Utils.FuncoesXml.ArquivoXmlParaClasse<NFe.Classes.nfeProc>(arqNFe);
		}
		catch (Exception)
		{
		}

		if (proc == null)
		{
			if (arquivo.Name.Split('-').Last() == "procNFe.xml")
			{
				proc = DFe.Utils.FuncoesXml.ArquivoXmlParaClasse<NFe.Classes.nfeProc>(arqNFe);
			}
		}

		if (proc != null)
		{
			//NFe.Classes.nfeProc proc = DFe.Utils.FuncoesXml.ArquivoXmlParaClasse<NFe.Classes.nfeProc>(arqNFe);
			//carregar para a NFeNota
			Classes.NFeNota nota = new Classes.NFeNota();
			nota.LeituraNFe(proc);

			if (nota.SalvarCompleta(this.Conexao))
			{
				File.Move(arqNFe, this.DiretorioNotas + @"\Enviadas\Aprovadas\" + arquivo.Name);
			}
		}
	}
	catch (Exception ex)
	{
		Tools.Log.SalvarLog("Salvando as Notas", ex.Message);

		File.Move(arqNFe, this.DiretorioRecebimentoProblemas + "\\" + arquivo.Name);
	}
}

**Comment by marciojmuller** [comment]
Verifiquei que teve a #610 que foi melhorado este método.
Nos PDVs, que cada um emite cerca de 400 NFCes por dia, não acontece este problema, mesmo com os computadores bem ruins.
Tenho um concentrador destas notas, que recebe dos PDVs e fica no servidor, este concentrador tem a função de buscar as notas dos PDVs e inserir no banco de dados do ERP, e como os supermercados e lojas tem vários PDVs quando este concentrador chega lá pelas notas 1400, 1500 aparece esta exceção 'System.OutOfMemoryException'

**Comment by robertorp** [comment]
Ate então a unica reclamação disso sobre isso foi somente essa issue depois dela não teve outra. Vou concluir que não temos mais esse problema. Bom pelo menos comigo nunca aconteceu.
