### ISSUE TITLE
ENUMS COM NUMERAÇÕES DIFERENTES DA DOCUMENTAÇÃO

### ISSUE THREAD

**Issue by LHBertoni** [ZeusAutomacao/DFe.NET#728]
Gostaria de propor uma alteração das numerações de alguns enum para adequação dos mesmos com a NFe.

Alguns ENUM apresenta numeração totalmente diferente da NFe, dependendo de como a pessoa estruturou o sistema e/ou banco, var ter dificuldade no preenchimento da classe da NFe na Zeus e terá um processamento dobrado (Mesmo não sendo muito significativo em alguns casos).

Pode ocorrer alguns problemas com isso, como por exemplo as pessoas que já utilizam se adequar novamente.

**Comment by robertorp** [comment]
De exemplos de que você quer fazer

qual enum ? qual a mudança ?
enfim faça um exemplo de código aqui para nós

mas já adianto, meio difícil, pois muitas pessoas já utilizam o mesmo uma mudança assim não e agradável e quebraria muito sistema, então já adianto a possibilidade são poucas de acontecer por causa desse motivo.

**Comment by LHBertoni** [comment]
@robertorp 

Entendo perfeitamente que muitas pessoas já utilizam.
Eu mesmo utiliza a um bom tempo a biblioteca e agora nas ultimas atualizações para a NFe 4.0 tivemos problema pela adição de algumas opções, como exemplo o campo modFrete.

```
public enum ModalidadeFrete
    {
        mfContaEmitenteOumfContaRemetente = 0,
        mfContaDestinatario = 1,
        mfContaTerceiros = 2,
        mfProprioContaRemente = 3,
        mfProprioContaDestinatario = 4,
        mfSemFrete = 5
    }
```

Pois anteriormente o era definido `mfSemFrete = 3`.

Mas poderia ser dessa forma


```
public enum ModalidadeFrete
    {
        mfContaEmitenteOumfContaRemetente = 0,
        mfContaDestinatario = 1,
        mfContaTerceiros = 2,
        mfProprioContaRemente = 3,
        mfProprioContaDestinatario = 4,
        mfSemFrete = 9
    }
```

Pois o modo sem frete na documentação da nota apresenta código 9 e permaneceu o mesmo, em nenhuma quebra de combatibilidade.

Outro exemple:

```

    /// <summary>
    ///     <para>01=Dinheiro</para>
    ///     <para>02=Cheque</para>
    ///     <para>03=Cartão de Crédito</para>
    ///     <para>04=Cartão de Débito</para>
    ///     <para>05=Crédito Loja</para>
    ///     <para>10=Vale Alimentação</para>
    ///     <para>11=Vale Refeição</para>
    ///     <para>12=Vale Presente</para>
    ///     <para>13=Vale Combustível</para>
    ///     <para>14=Duplicata Mercantil (versão 4.00)</para>
    ///     <para>15=Boleto Bancário (versão 4.00)</para>
    ///     <para>90=Sem pagamento (versão 4.00)</para>
    ///     <para>99=Outros</para>
    /// </summary>
    public enum FormaPagamento
    {
        [Description("Dinheiro")] [XmlEnum("01")] fpDinheiro,

        [Description("Cheque")] [XmlEnum("02")] fpCheque,

        [Description("Cartão de Crédito")] [XmlEnum("03")] fpCartaoCredito,

        [Description("Cartão de Débito")] [XmlEnum("04")] fpCartaoDebito,

        [Description("Crédito Loja")] [XmlEnum("05")] fpCreditoLoja,

        [Description("Vale Alimentação")] [XmlEnum("10")] fpValeAlimentacao,

        [Description("Vale Refeição")] [XmlEnum("11")] fpValeRefeicao,

        [Description("Vale Presente")] [XmlEnum("12")] fpValePresente,

        [Description("Vale Combustível")] [XmlEnum("13")] fpValeCombustivel,

        /// <summary>
        /// Foi excluido pela NT 2016. 002 v1.50
        /// Continuara aqui pois a mesma alguém já pode ter utilizado
        /// Foi excluido pela NT 2016. 002 v1.50, Continua pois a mesma pode ter sido utilizada já
        /// </summary>
        [Description("Duplicata Mercantil")] [XmlEnum("14")] fpDuplicataMercantil, // VERSÃO 4.00

        [Description("Boleto Bancário")] [XmlEnum("15")] fpBoletoBancario, // VERSÃO 4.00

        [Description("Sem pagamento")] [XmlEnum("90")] fpSemPagamento, // VERSÃO 4.00

        [Description("Outros")] [XmlEnum("99")] fpOutro
    }
```

Por que não?

```

    /// <summary>
    ///     <para>01=Dinheiro</para>
    ///     <para>02=Cheque</para>
    ///     <para>03=Cartão de Crédito</para>
    ///     <para>04=Cartão de Débito</para>
    ///     <para>05=Crédito Loja</para>
    ///     <para>10=Vale Alimentação</para>
    ///     <para>11=Vale Refeição</para>
    ///     <para>12=Vale Presente</para>
    ///     <para>13=Vale Combustível</para>
    ///     <para>14=Duplicata Mercantil (versão 4.00)</para>
    ///     <para>15=Boleto Bancário (versão 4.00)</para>
    ///     <para>90=Sem pagamento (versão 4.00)</para>
    ///     <para>99=Outros</para>
    /// </summary>
    public enum FormaPagamento
    {
        [Description("Dinheiro")] [XmlEnum("01")] Dinheiro = 1,

        [Description("Cheque")] [XmlEnum("02")] fpCheque = 2,

        [Description("Cartão de Crédito")] [XmlEnum("03")] fpCartaoCredito = 3,

        [Description("Cartão de Débito")] [XmlEnum("04")] fpCartaoDebito = 4,

        [Description("Crédito Loja")] [XmlEnum("05")] fpCreditoLoja = 5,

        [Description("Vale Alimentação")] [XmlEnum("10")] fpValeAlimentacao = 10,

        [Description("Vale Refeição")] [XmlEnum("11")] fpValeRefeicao = 11,

        [Description("Vale Presente")] [XmlEnum("12")] fpValePresente = 12,

        [Description("Vale Combustível")] [XmlEnum("13")] fpValeCombustivel = 13,

        /// <summary>
        /// Foi excluido pela NT 2016. 002 v1.50
        /// Continuara aqui pois a mesma alguém já pode ter utilizado
        /// Foi excluido pela NT 2016. 002 v1.50, Continua pois a mesma pode ter sido utilizada já
        /// </summary>
        [Description("Duplicata Mercantil")] [XmlEnum("14")] fpDuplicataMercantil = 15, // VERSÃO 4.00

        [Description("Boleto Bancário")] [XmlEnum("15")] fpBoletoBancario = 15, // VERSÃO 4.00

        [Description("Sem pagamento")] [XmlEnum("90")] fpSemPagamento = 90, // VERSÃO 4.00

        [Description("Outros")] [XmlEnum("99")] fpOutro = 99
    }
```

Entendo perfeitamente que mudanças na estrutura do projeto, no nível que o projeto está e a quantidade de pessoas que utilizam pode tornar essas mudanças inviáveis.

Agradeço pela atenção e principalmente pelo projeto.

**Comment by nelsonasousa** [comment]
Eu por aqui fiz o propósito de adaptar totalmente as nomenclaturas, tanto no meu sistema como no banco de dados, aos nomes usados na NFe. Isso vale também para os Enuns.
Que dá trabalho, isso é certo, dá mesmo!
Mas acho que está compensando na hora de efetuar as mudanças que sempre ocorrem nos layouts, fica mais fácil encontrar onde e o porque das "coisas" na hora de desenvolver.

**Comment by robertorp** [comment]
Gostei bastante da sugestão, mas ainda temos o problema de estudar questões de compatibilidade talvez, podemos deixar para uma mudança de versão maior do Zeus, exemplo quando tivermos uma versão 2.0.0.0 da DLL ai sim podemos aplicar tais mudanças, mas hoje no momento com a correria que está de layout 4.00 complica, muita gente nesse exato momento passando aplicações para a versão 4.00

Enfim vamos deixar aqui em aberto esta issue para uma versão maior do Zeus

**Comment by scalarerp** [comment]
Ajuda ai para o pessoal, estou implementando aqui:

Extensions para passar STRINGS para os Enums

https://gist.github.com/scalarerp/8524b1e26493f2558ec7f3352b8b73bc

**Comment by apbertoletti** [comment]
Olá pessoal, 

Gostei das extensões propostas pelo @scalarerp 

O que vcs acham de incorporamos ela no Zeus? 

Pois tb estou tendo dificuldade com os enums fora da documentação oficial por aqui.

@robertorp , o que seria exatamente o Zeus 2.0 ?

Abraços

**Comment by robertorp** [comment]
o objetivo e passar um código e retornar o enum correspondente?
Tem que ser bem pensado essa proposta das extensions, porque oh @scalarerp  disse passar strings mas tem um ai que passa int  `public static ModalidadeFrete ToModalidadeFrete(this int value)`
o ideal e criar uma outra issue para isso ser discutido.

Zeus 2.0 e uma versão com alterações que terão maiores possibilidades de quebrar aplicações existentes. 
A proposta inicial da issue, se fizer ela, pode ter certeza que tem muita gente usando os enums do Zeus do jeito que está e salvando no banco de dados. Ou seja, em outras palavras vai quebrar aplicações por ai, tem que ser feito com mais cuidado isso. Muito mais cuidado. E ter uma espécie de canal para avisar a todos das mudanças.

**Comment by nelsonasousa** [comment]
Eu uso as enuns do Zeus. Salvo no Banco apenas os valores interiros.
A única coisa de gostaria de ver alterado são as descrições dos enuns. 
Algo mais amigável que possa ser populado direto numa combobox para o usuário.

**Comment by rodrigordi** [comment]
Pessoal, não seria melhor criar atributes nos enumerados  ? Assim um enum pode ter seu valor inteiro referente sua posicao dentro do enum e no atribute voce define um valor string para ele. E com duas funcoes voce consegue buscar o valor string e buscar o enum pelo valor string. 

Se quiser usar o int : faz casting e se quiser usar o nome do enum, faz parser de string.

**Comment by orochasamuel** [comment]
Fala pessoal, o que acham dessa proposta? Eu uso no [SPEDBr](https://github.com/AOPack/SPEDBr.NET).

```cs

        // MODO DE USO

        public static string IdentifyEnumValueByType(Type type, object valueOfType)
        {
            if (type == typeof(IndCodMod))
                return ((IndCodMod)valueOfType).ToDefaultValue();
        }

        // MÉTODOS DE EXTENSÃO      

        // This extension method is broken out so you can use a similar pattern with 
        // other MetaData elements in the future. This is your base method for each.
        private static T GetAttribute<T>(this Enum value) where T : Attribute
        {
            var type = value.GetType();
            var memberInfo = type.GetMember(value.ToString());
            var attributes = memberInfo[0].GetCustomAttributes(typeof (T), false);
            return (T) attributes[0];
        }

        // This method creates a specific call to the above method, requesting the
        // Description MetaData attribute.
        public static string ToDefaultValue(this Enum value)
        {
            var attribute = value.GetAttribute<DefaultValueAttribute>();
            return attribute == null ? value.ToStringSafe() : attribute.Value.ToStringSafe();
        }

        // MAPEAMENTO DO ENUM

    public enum IndCodMod
    {
        /// <summary>
        /// Nota Fiscal
        /// </summary>
        [DefaultValue("01")] Mod1Ou1A,

        /// <summary>
        /// Nota Fiscal Avulsa
        /// </summary>
        [DefaultValue("1B")] Mod1B,

        /// <summary>
        /// Nota Fiscal de Venda a Consumidor
        /// </summary>
        [DefaultValue("02")] Mod02,

        /// <summary>
        /// Cupom Fiscal
        /// </summary>
        [DefaultValue("2D")] Mod2D,

         /// <summary>
        /// Nota Fiscal Eletrônica - NF-e
        /// </summary>
        [DefaultValue("55")] Mod55,

        /// <summary>
        /// Conhecimento de Transporte Eletrônico - CT-e
        /// </summary>
        [DefaultValue("57")] Mod57,

        /// <summary>
        /// Cupom Fiscal Eletrônico - CF-e (SAT)
        /// </summary>
        [DefaultValue("59")] Mod59,

        /// <summary>
        /// Cupom Fiscal Eletrônico - CF-e (ECF)
        /// </summary>
        [DefaultValue("60")] Mod60,

        /// <summary>
        /// Nota Fiscal Eletrônica p/ Consumidor Final - NFC-e
        /// </summary>
        [DefaultValue("65")] Mod65,

        /// <summary>
        /// Conhecimento de Transporte Eletrônico - CT-e (OS)
        /// </summary>
        [DefaultValue("67")] Mod67
    }

```

**Comment by rodrigordi** [comment]
@samuelrochaoliveira isso isso isso... e dá para colocar mais uma propriedade no atributo com a descrição da posição do enum para apresentar em dropdown por exemplo. seria o valor que voce colocou no summary

**Comment by orochasamuel** [comment]
É só usar o `Attribute Description` então.

**Comment by apbertoletti** [comment]
Essa abordagem não quebraria o código de quem já está usando sem ela, confere?

**Comment by orochasamuel** [comment]
Não, não quebraria e sim, confere. Claro que, o código está da forma que uso no meu cenário, para portar para o DFe.NET teria que incluir a `[Description]` e `[XmlEnum]` e retornar o valor desejado fazendo a leitura com `Reflection`. Para quem quer usar essa notação para preencher listas como Combobox pode usar o exemplo do link a seguir https://stackoverflow.com/questions/801029/how-to-get-all-values-of-an-enum/801058#801058.

**Comment by apbertoletti** [comment]
Encontrei uma issue interessante sobre o assunto (#561)

@marcosgerene , vc tem alguma consideração a fazer aqui?

**Comment by scalarerp** [comment]
Padrao do uninfe é legal:


`public int AmbienteCodigo { get; set; }

(TipoAmbiente)Empresas.Configuracoes[emp].AmbienteCodigo

public enum TipoAmbiente
    {
        [Description("Produção")]
        taProducao = 1,

        [Description("Homologação")]
        taHomologacao = 2
    }`

**Comment by Laranjeiras** [comment]
Realmente seria muito útil padronizar o valor do enum com o valor do XML, ficaria mais fácil o entendimento, e a usabilidade.

**Comment by marcosgerene** [comment]
>Encontrei uma issue interessante sobre o assunto (#561)
>
>@marcosgerene , vc tem alguma consideração a fazer aqui?

@apbertoletti Vi somente agora sua citação.

Hoje isso não me afeta mais porque não faço mais conversões implícitas convertendo de integer, mas concordo que padronizar o código de forma similar ao manual seja a melhor abordagem.
