### ISSUE TITLE
Impressão de Danfe Nativo com mais de 50 itens

### ISSUE THREAD

**Issue by DiegoPhillipe** [ZeusAutomacao/DFe.NET#729]
Estou imprimindo a Danfe NFCe com mais de 50 itens porém não imprime todo o conteúdo, cortando no tamanho máximo da página. Alguém já passou por essa situação e sabe como resolver?

**Comment by adrbarros** [comment]
Bom caso você esteja fazendo a impressão via PrintDocument, altere o tamanho do papel nas propriedades da impressora para 80mm X 3278mm (Elgin I7, I9, Epson TMT20 já possuem esses tamanhos configurados para uso, cado for Bematech você tem que customizar)

**Comment by DiegoPhillipe** [comment]
@adrbarros teria como fazer essa configuração via código?

**Comment by adrbarros** [comment]
Deve ter sim, pois, nunca parei para analisar isso, porém até o momento resolvo isso mexendo das propriedades da impressora.

Mas sinta-se a vontade para ver e analisar essa questão de resolver isso via código

Obs.: se fizer a impressão via FastReport, não há falhas na impressão.

**Comment by marcosgerene** [comment]
A resposta do @adrbarros resolve o problema inclusive para o FastReports.

**Comment by marcosgerene** [comment]
![image](https://user-images.githubusercontent.com/15945003/44207776-bb724680-a134-11e8-9968-ce6833f8c121.png)

https://github.com/ACBrNet/ACBr.Net.Sat/issues/66

**Comment by suporte-kontacto** [comment]
Bom dia, alguém tem alguma solução pra Daruma dr800?

**Comment by adrbarros** [comment]
Bom dia, vamos la:
https://github.com/leandrovip/Vip.Printer
https://github.com/adrbarros/Gerene.DFe.EscPos (Utiliza a Lib acima)

E também você pode usar o ACBrPosPrinter
