### ISSUE TITLE
Troco na DANFE

### ISSUE THREAD

**Issue by diegolocatelli89** [ZeusAutomacao/DFe.NET#73]
Boa tarde pessoal,
primeiramente gostaria de parabenizar o Adenilton pelo projeto, que está sendo de grande utilidade.
Só estou com um "probleminha", eu preciso fazer com que o troco apareça na DANFE, alguém teria alguma sugestão?

Obs.: Estou usando o unidanfe.

Obrigado!

**Comment by orochasamuel** [comment]
Olá Diego,

No XML deverá constar somente o valor líquido, ou seja, se na sua operação você vendeu:

Total do produtos: R$ 49,00

Valor Pago: R$ 50,00

Troco: R$ 1,00

O valor a ser informado no arquivo XML deverá ser os R$ 49,00.

Há um esclarecimento sobre isto da SEFAZ/AM dizendo o seguinte:

"No xml deve constar apenas o valor líquido recebido.
No entanto, no DANFE NFC-e, segundo o manual de especificações técnicas do DANFE NFC-e e QR Code (versão 3.1), o troco está entre as informações mínimas dos totalizadores, portanto de implementação obrigatória.
Atenciosamente,

Equipe SEFAZ"

Eu entendo, a partir destas informações, que o troco é uma informação gerenciável no DANFE da NFC-e, todavia, no próprio XML deverá existir somente a real informação da operação visto que o XML é o arquivo verídico para auditoria, consultas e documento que contém valor fiscal perante o fisco, seja estadual ou federal.

Espero ter ajudado.

Samuel Rocha
Analista Fiscal

**Comment by adeniltonbs** [comment]
Interessante Samuel, mas tenho uma dúvida.
O Manual de Especificações Técnicas do DANFE NFC-e e QR Code que devemos seguir não é o divulgado aqui http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk= Cuja versão atual é 3.4?

No "Manual de Especificações Técnicas do DANFE NFC-e e QR Code - versão 3.4", disponibilizado no link acima não relaciona o "Troco" como informação possível de ser adicionada no DANFE da NFCe, além disso, na página 3 esclarece o seguinte:
- A impressão do DANFE NFC-e é efetuada diretamente pelo Aplicativo do
  contribuinte em impressora comum (não fiscal), com base nas informações do
  arquivo eletrônico XML da NFC-e;
- No DANFE NFC-e não devem ser inseridas informações que não constem do
  respectivo arquivo eletrônico XML da NFC-e, exceto o protocolo de autorização
  da NFCe;

O entendimento de que o troco não consta no XML e, portanto, NÃO deve ser impresso está correta?

**Comment by leandrossantos** [comment]
Concordo com o que o Adenilton falou, se não tem no XML então não precisa imprimir. O que pode fazer é jogar a mensagem de troco os OBS da NFCe

**Comment by leandrossantos** [comment]
Adenilton, falando em impressão da NFCe, sobre a impressão do desconto do item que te passei, conseguiu fazer já?

**Comment by orochasamuel** [comment]
Olá estimados colegas,

Realmente Adenilton, eu não posso discordar do entendimento extraído mediante a análise do Manual disponibilizado pela Receita.

Mas o esclarecimento que eu queria passar era exatamente a conclusão que o Leandro encontrou.

Se o conteúdo do XML não pode conter informações "não obrigatórias" isso elimina a possibilidade de personalizar as informações da DANFE, concorda? Logo, eu entendo que a observação poderá ser aproveitada para esse tipo de informação.

O trecho citado no meu outro post foi um esclarecimento da SEFAZ do AMAZONAS, cada SEFAZ pode obrigar ou facultar as informações, logo, o esclarecimento deles pode divergir do Fisco para qual está se implementando na aplicação.

Espero ter ajudado.

Samuel Rocha
Analista Fiscal

[EDITADO]
Adenilton, o Manual v. 3.1 não está mais disponível para download na nfe.fazenda.gov, todavia, ainda é possível encontrá-lo em outros endereços:
http://tecnospeed.com.br/downloads/publico/Manual_DANFE_NFC_QRCode_vs_3_1.pdf

Nesta versão específica a informação do troco é mencionada, vide item 2.1.2 na página 4.

**Comment by diegolocatelli89** [comment]
Bom dia, 
Pessoal obrigado pela atenção.
Um outro aplicativo emissor de NFC-e joga a informação do troco nas informações adicionais. 
Desta forma:
-<infAdic>
      -<obsCont xCampo="Troco">
            <xTexto>0.00</xTexto>
      </obsCont>
</infAdic>
Eu até poderia fazer assim também, mas ai vem outro problema. Acredito que o unidanfe não interprete isto. hahaha

Abraço.

**Comment by diegolocatelli89** [comment]
diegolocatelli89 commented just now
Bom dia, 
Pessoal obrigado pela atenção.
Um outro aplicativo emissor de NFC-e joga a informação do troco nas informações adicionais. 
Desta forma:
[infAdic]
------[obsCont xCampo="Troco"]
------------[xTexto]0.00[/xTexto]
------[/obsCont]
[/infAdic]
Eu até poderia fazer assim também, mas ai vem outro problema. Acredito que o unidanfe não interprete isto. hahaha

Abraço.

**Comment by orochasamuel** [comment]
Diego,

Se eu não me engano no Unidanfe tem como personalizar o documento, posso estar equivocado mas, creio que tenha como sim.

**Comment by adeniltonbs** [comment]
Acredito que ele imprima a observação da NFe.
Então acho que a idéia do que foi abordado aqui neste issue é que você deve colocar o troco como uma informação adicional da NFe. Mais precisamente na tag infAdic.infCpl.

Acho uma boa ideia programares teu aplicativo para imprimir essa observação como "Troco: XX,XX" na primeira linha da observação. Se o usuário digitar alguma informação adicional, você empurra a informação digitada pelo usuário para baixo.

**Comment by adeniltonbs** [comment]
Acabei de enviar um commit 42f8db7a667224132a6da9e1f3f8867a1d43c1b4 com exemplo de envio e impressão do troco no caso do DANFE. e sugestão para diegolocatelli89: Você pode usar a impressão do DANFE da NFCe diretamente da biblioteca.

**Comment by diegolocatelli89** [comment]
Opa, vou dar uma olhada.
Obrigado Adenilton.

**Comment by adeniltonbs** [comment]
leandrossantos vou implementar a impressão do desconto dos itens. No entanto o que você acha?
Eu penso que só compensa colocar o desconto do item quando a impressão dos produtos for feita em duas linhas, haja vista que devem entrar dois campos novos: Valor bruto e valor do desconto. Acredito que não dá pra colocar na impressão do produto em única linha. Aguardo feedback.

**Comment by leandrossantos** [comment]
Adenilton, acredito que pode ser da mesma forma que funciona nas ECF, segue imagem de exemplo abaixo.

![cupom_ecf_desconto](https://cloud.githubusercontent.com/assets/6373944/11338191/12b1424e-91c9-11e5-9500-615222957543.JPG)

**Comment by adeniltonbs** [comment]
Ok, vou implementar. Sem o acréscimo é claro :).

**Comment by adeniltonbs** [comment]
Implementando o desconto do item no DANFE segundo a sugestão de leandro, no commit 42f8db7a667224132a6da9e1f3f8867a1d43c1b4.

Foi adicionado na aplicação de demonstração, guia DANFE, o checkbox "Imprimir desconto do item", para que seja possível escolher se o desconto vai ser impresso ou não.
No caso do desconto não ser impresso, o valor unitário e o total será líquido.
