### ISSUE TITLE
Distribuição CTe

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#731]
Olá, Boa Noite,

Pelo que vi vc´s têm a Distribuição NFe! Está funcionando, direitinho?

Procurei na solução sobre Distribuição CTe, e consegui apenas encontrar uma referência em um Enum dentro de Serviços, mas que não tem referência nenhuma, minha dúvida é o seguinte:
Não tem distribuição CTe? Ou se tiver, onde está e se possível mandar um exemplo para eu poder dar uma olhada.

Att,
Guilherme

**Comment by robertorp** [comment]
Tem um pull que estou analisando, vou dar prioridade para ele amanhã e já libero

**Comment by gui-abrantes** [comment]
Uma pergunta meio que fora do escopo, somente pra confirmar....não existe manifestação de CT-e não né!? Na qual, por exemplo o destinatário, desconheça a operação, ou até mesmo manifeste a operação! Igual ocorre no serviço da NF-e

**Comment by robertorp** [comment]
Existe .. mas não aceitei o Merge ainda olha nos pull

**Comment by robertorp** [comment]
foi liberdo já o ct-e distribuição
