### ISSUE TITLE
Consulta Protocolo 4.0

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#737]
Ola saudacoes, estou enviando uma nfce e quando vou realizar a consulta pela chave esta me retornando essa rejeicao:

cStat = 878
Endereco do site da UF da Consulta por chave de acesso diverge do previsto. [URL correta:http://www.fazenda.pr.gov.br]

na versao 3.10 esta normal

**Comment by robertorp** [comment]
Qual estado?
Vou arrumar.. 
na nfc-e 4 você deve enviar a tag 

```
_nfe.infNFeSupl.urlChave = _nfe.infNFeSupl.ObterUrl(_configuracoes.CfgServico.tpAmb, _configuracoes.CfgServico.cUF, TipoUrlConsultaPublica.UrlQrCode);
```

esta enviando ela?

Se sim coloque o resultado aqui da busca da url

**Comment by robertorp** [comment]
Corrigido o erro, de uma conferida novamente.. mudança 
no lugar do TipoUrlConsultaPublica.UrlQrCode passe a UrlConsulta

```
_nfe.infNFeSupl.urlChave = _nfe.infNFeSupl.ObterUrl(_configuracoes.CfgServico.tpAmb, _configuracoes.CfgServico.cUF, TipoUrlConsultaPublica.UrlConsulta);
```

**Comment by vasisti** [comment]
Ola Paulo boa tarde, fiz a alteracao conforme acima, mas o status 878 continua. Endereco do site da UF da Consulta por chave de acesso diverge do previsto. [URL correta:http://www.fazenda.pr.gov.br].
Meu Estado e o Parana. 
O arquivo envia normalmente. Lote recebido com sucesso. mas nao consulta.
segue aqui a busca da URL:
http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?chNFe=41180509464428000160650010000000071000012346&nVersao=100&tpAmb=2&cDest=99999999000191&dhEmi=323031382d30352d32305431353a32363a32322d30333a3030&vNF=5.00&vICMS=0.00&digVal=3063754e394d744f7744706f56784870764b59304148675a6570383d&cIdToken=000001&cHashQRCode=a050c64b5cb69e1786e8688eec233f0a48283973

segue o xml de envio anexo
[envio_Parana.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2020554/envio_Parana.zip)

**Comment by vasisti** [comment]
Ola Roberto boa noite, verificando melhor, esta acontecendo o seguinte:
os metodos (ObterUrl e ObterUrlQrCode) estao setando a versao 3.10, entao a url esta trazendo com a URL da 3.10.
entao setei manualmente para 4.00 e autorizou e normalmente.

(3.10)
http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?chNFe=41180520821785000170650010000000301000012353&nVersao=100&tpAmb=2&dhEmi=323031382d30352d32335432333a32383a34392d30333a3030&vNF=1.00&vICMS=0.00&digVal=4f6d4d50474351327154677a3868482b35715452674e38712b76773d&cIdToken=000001&cHashQRCode=44d9072b7cefe74d1c5409ff621042f867e63dae

(4.00)
http://www.fazenda.pr.gov.br/nfce/qrcode/?chNFe=41180520821785000170650010000000301000012353&nVersao=100&tpAmb=2&dhEmi=323031382d30352d32335432333a33313a31342d30333a3030&vNF=1.00&vICMS=0.00&digVal=4869622b7a4875694b7a5038347a5a2f5a663061325246434e51453d&cIdToken=000001&cHashQRCode=c9f6580ea2ef800e8aa5ca1cfd663af807c4628c

**Comment by robertorp** [comment]
O padrão é 3.10 pois muitas pessoas já utilizam o Zeus, não podia simplesmente deixar quebrar para quem utiliza o mesmo. Tenho uma certa preocupação com usuários que já usam, tento implementar de uma maneira que minimiza o impacto de uma versão para outra da NF-e.
