### ISSUE TITLE
Validação NCM

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#74]
Adenilton,

Como você trata a validação da NCM? Você tem algum serviço de terceiros para verificar antes de emitir a nota ou você deixa a cargo do cliente para atualizar as NCM?

Samuel Rocha
Analista Fiscal

**Comment by adeniltonbs** [comment]
Nosso sistema possui uma tabela de NCMs que é atualizada pelo webservice da receita. O mesmo webservice que o "Programa Validador do SPED Fiscal" utiliza. Dessa forma o cliente não tem como colocar um NCM errado nos produtos.

**Comment by orochasamuel** [comment]
Obrigado pelo breve retorno.

Você poderia me informar o link de contratação desse webservice? Acredito que seja pago.

**Comment by adeniltonbs** [comment]
o webservice é público, aqui está o endereço: http://www.sped.fazenda.gov.br/spedtabelas/WsConsulta/WsConsulta.asmx

**Comment by orochasamuel** [comment]
Obrigado.

**Comment by leandrossantos** [comment]
Adenilton, poderia nos ajudar ai e passar como deve ser a chamada desse webservice, pois vi que pede um código do sistema.

**Comment by orochasamuel** [comment]
Adenilton,

Você sabe me informar qual o código do sistema para consulta da NCM? Eu pesquisei e encontrei os seguintes códigos:

'spedfiscal';
'spedPiscofins';
'spedcontabil'; e
'spedecf';

Entre as tabelas consultando pelo código 'spedfiscal' encontrei somente o código do gênero do produto, que são somente os 2 primeiros dígitos da NCM/SH.

[EDITADO]
Eu vi que existem várias tabelas, específicas dos Estados, acredito que o NCM deveria estar entre as tabelas globais.
Acredito que o link a seguir é a representação visual das informações consultadas via WebService:
http://www.sped.fazenda.gov.br/spedtabelas/AppConsulta/publico/aspx/ConsultaTabelasExternas.aspx?CodSistema=SpedFiscal

PS: Dá uma olhada nesse link aqui Leandro.

**Comment by adeniltonbs** [comment]
Ops desculpa, realmente não obtemos os NCMs daí, mas sim as naturezas da receita para EFD Contribuições. No entanto nestas duas urls poderás consultar o NCM:
http://investexportbrasil.dpr.gov.br/NCM/frmPesquisaNCMFull.aspx e http://www4.receita.fazenda.gov.br/simulador/.

Infelizmente não dá pra baixar uma tabela em formato que seja de fácil importação para uma tabela.

**Comment by orochasamuel** [comment]
Entendi,

O que eu procurava mesmo era um meio de integração direta com WebService, no site do IBPT tem como baixar uma planilha com todas as NCMs e alíquotas de imposto:
https://deolhonoimposto.ibpt.org.br/

Eu conheço essa a um tempo, mas a consulta direta seria o ideal.

**Comment by leandrossantos** [comment]
Então o melhor jeito é baixar a tabela no site https://deolhonoimposto.ibpt.org.br/ que já tem até as alíquotas de cada NCM

**Comment by orochasamuel** [comment]
Ops, pessoal acabei de entrar no site e eles tem uma novidade.

Agora é possível automatizar as atualizações.

Entra lá Leandro que você verá toda a documentação.

**Comment by MoacirCarlos** [comment]
http://iws.ibpt.org.br/Help

Sugiro que faça o cadastro.

**Comment by orochasamuel** [comment]
Usando o IBPT, pelo menos comigo o token está expirado, nenhum consulta funciona à API.

**Comment by orochasamuel** [comment]
Alguém utiliza a consulta das NCMs de outro lugar? Grátis ou pago?

**Comment by leandrossantos** [comment]
Já viram essa lista http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=oqXtmaR10bY=
que colocaram no portal da NFe

**Comment by orochasamuel** [comment]
A questão da NCM é bem chata mesmo, não tem nenhum lugar (não que eu tenha encontrado) para verificar a "validade" da NCM antes de enviar a NF-e.
