### ISSUE TITLE
Uma pequena ajuda no "caminho das pedras"...

### ISSUE THREAD

**Issue by nelsonasousa** [ZeusAutomacao/DFe.NET#740]
Pessoal,
Estou migrando do Acbr para o Zeus pelo fato de utilizar a mesma ferramenta de programação do Zeus, ou seja, o c#.
A geração do XML, o envio do mesmo e retorno da autorização eu já consegui.
Só que, por estar acostumado com o ACBr, que me entregava o XML e o PDF junto com a autorização de uso, eu fiquei meio perdido. Na pasta configurada, estão 2 XMls (o de envio do lote e o de retorno).
O XML "final" ou seja, assinado, autorizado e protocolado, o que deve ser arquivado, como eu obtenho?

**Comment by robertorp** [comment]
@nelsonasousa 
Vamos lá hehe
```
private void CriarXmlNotaAutorizada(EmissaoNfe emissao)
        {
            try
            {
                var xmlHelper = new XmlHelper(emissao.XmlAutorizacao);
                var status = xmlHelper.GetValueFromElement("cStat", "infProt").GetValueOrDefault<int>();
                var verAplic = xmlHelper.GetValueFromElement("verAplic", "infProt").GetValueOrDefault<string>();
                var xMotivo = xmlHelper.GetValueFromElement("xMotivo", "infProt").GetValueOrDefault<string>();

                var envNfe = FuncoesXml.XmlStringParaClasse<enviNFe3>(emissao.XmlEnvio);
                var nfe = envNfe.NFe.FirstOrDefault();

                var nfeProc = new nfeProc
                {
                    versao = emissao.VersaoDocumento,
                    NFe = nfe,
                    protNFe = new protNFe
                    {
                        infProt = new infProt
                        {
                            tpAmb = emissao.Ambiente.ToZeus(),
                            chNFe = Chave.Chave,
                            dhRecbto = emissao.GetDataRecebimento(),
                            nProt = emissao.GetProtocolo(),
                            digVal = emissao.GetDigestValue(),
                            cStat = status,
                            verAplic = verAplic,
                            xMotivo = xMotivo
                        }
                    }
                };

                XmlAutorizado = FuncoesXml.ClasseParaXmlString(nfeProc);
            }
            catch (System.Exception ex)
            {
                throw new InvalidOperationException("Falha ao criar XML da Nota Autorizada: " + ex.Message, ex);
            }
        }
```

Segue minha implementação para você ter um exemplo de implementação

**Comment by nelsonasousa** [comment]
Eu acabei chegando mais ou menos numa conclusão parecida...rsrsrsrs.
Só que peguei direto do retorno, será que é o correto?

>  var nfeproc = new nfeProc
                            {
                                NFe = _nfe,
                                protNFe = retornoEnvio.Retorno.protNFe,
                                versao = retornoEnvio.Retorno.versao
                            };
                            if (nfeproc.protNFe != null)
                            {
                                var novoArquivo = NgGlobais.PubPastaSistema + @"\Dados\NFe\" +
                              $"{DateTime.Today:yyyyMM}" + @"\" + nfeproc.protNFe.infProt.chNFe +
                                                  "-Nfe.xml";
                                FuncoesXml.ClasseParaArquivoXml(nfeproc, novoArquivo);
                                nota.ANFeArquivo = novoArquivo;
                            }

**Comment by robertorp** [comment]
e direto do retorno mesmo, o negocio e que no meu sistema eu salvo o retorno em uma tabela do banco de dados
e depois posteriormente eu monto o nfeproc

**Comment by nelsonasousa** [comment]
Valeu amigão!!
Agora tô dando uma "lustrada" no NFCe, qqer coisa dou o grito!!

**Comment by robertorp** [comment]
blz, se tiver sido resolvido , feche a issue 
obrigado! precisando sempre poste uma issue
