### ISSUE TITLE
NFCe 4.00 MS - URL incorreta

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#742]
Estou recebendo este retorno na emissão da NFCe no MS em produção para NFe 4.00

> *Rejeiçao: Endereço do site da UF para a consulta por chave de acesso difere do previsto.*

Posto uma atualização em breve.

**Comment by robertorp** [comment]
Talvez ajude: https://github.com/ZeusAutomacao/DFe.NET/issues/737

**Comment by marcosgerene** [comment]
@robertorp 
Eu ainda não tive tempo de ir atrás disso com calma, mas só tenho um cliente no MS que emite nfce, como ainda tenho prazo voltei ele pra NFe 4.00, assim que eu conseguir mando um PR

**Comment by rftd** [comment]
http://www.nfce.ms.gov.br/2018/05/23/novas-urls-de-webservices-da-nfc-e-para-versao-4-0-em-ambiente-de-homologacao/

**Comment by marcosgerene** [comment]
>@robertorp
Eu ainda não tive tempo de ir atrás disso com calma, mas só tenho um cliente no MS que emite nfce, como ainda tenho prazo voltei ele pra NFe 4.00, assim que eu conseguir mando um PR

Cara, voltei meus clientes pro 3.10, assim que der pra respirar eu mando um PR, acredito que só na próxima semana, preciso testar, pra isso preciso de certificado, etc.

**Comment by marcosgerene** [comment]
Ainda não tive tempo de testar o PR #748, mas peguei a informação do .ini do ACBr, assim que eu tiver certeza (testar no cliente) aceito o PR e fecho a issue.

**Comment by marcosgerene** [comment]
Mesmo com o URL correto não funcionou. Não sei se eles estão validando o QrCode ja em 2.0, sinceramente não faz muito sentido pra mim, como tenho prazo eu vou deixar para mexer neste cliente mais pra frente e focar em outras pendências.
