### ISSUE TITLE
Falha na emissão de NFe no AppTeste

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#743]
Olá pessoal, td bem?

Fiz um fork hoje do Zeus para iniciar os testes e estudos, quando fui emitir a primeira NFe de testes, ela está sendo rejeitada pela seguinte motivo:

 <cStat>902</cStat> 
 <xMotivo>Rejeição: Valor Liquido da Fatura difere do Valor Original menos o Valor do Desconto</xMotivo> 

Segue o print do erro:

![image](https://user-images.githubusercontent.com/6843493/40501577-ac7bc48e-5f5e-11e8-9e98-98063cb2218e.png)

Isso seria um bug mesmo do AppTeste ou será que configurei algo errado durante a emissão?

**Comment by apbertoletti** [comment]
Pessoal, 

Pela analise que fiz aqui no código, pude notar que trata-se de um bug sim, visto que esta uma regra recente da SEFAZ, que surge junto com a NT 2016.002 versão 1.50, de 26/04/2018.

@robertorp, posso corrigir e submeter o PR?

Abraços

**Comment by robertorp** [comment]
Corrige sim, e manda o PR ;)

**Comment by apbertoletti** [comment]
@robertorp , fiz a correção aqui e agora o arquivo está passando na validação (vide abaixo)

[789-env-lot.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2036928/789-env-lot.txt)

Porém, quando consulto o recibo do lote, o problema original ainda persiste, veja:

![image](https://user-images.githubusercontent.com/6843493/40511065-f86acfb4-5f74-11e8-86fd-2b4b56abd706.png)

Alguma pista do que falta?

**Comment by apbertoletti** [comment]
Esquece!

Lendo melhor a mensagem de erro, consegui perceber a sutileza e encontrar o problema.

Faltava preencher a tag do Valor Original da Fatura.

Vou submeter o PR em seguida.

**Comment by apbertoletti** [comment]
@robertorp , existe alguma boa prática de PR no projeto Zeus?

Submeto ele na branch master mesmo?

**Comment by robertorp** [comment]
Na branch master mesmo.
So fazer, seguindo a linha existente.

**Comment by apbertoletti** [comment]
#746

**Comment by robertorp** [comment]
Ok obrigado!
