### ISSUE TITLE
Forma de Pagamento

### ISSUE THREAD

**Issue by AcciolyDSI** [ZeusAutomacao/DFe.NET#759]
Olá a todos.

Como vocês estão fazendo quando a forma de pagamento é parcelada no boleto? 

Na versão 3.10 era possível fazer isso, informando o valor das parcelas e respectivo vencimento, inclusive
essa técnica é legal pois facilita o lançamento no contas a pagar quando vc importa o xml.

A única maneira que vi foi usando duplicata mercantil, pois é a única que possibilita informar a data, mas ela não é mais válida.

A Sefaz não facilitou nada nesse sentido, como vocês estao fazendo?

Abraços

**Comment by nelsonasousa** [comment]
Eu por aqui, coloquei uma aba na tela de importação do xml com um grid que carrego com as parcelas.
O usuário informa a qtde de parcelas escolhendo uma condição de pagamento numa combobox.
No validate da combo eu carrego o grid, e, efetuo eventuais ajustes nas parcelas direto no grid.
Pelo menos até os "iluminados" da SEFAZ conseguirem descobrir a diferença entre FORMA de PAGTO e CONDIÇÃO de PAGTO

**Comment by AcciolyDSI** [comment]
É uma solução também, não é prática, mas resolve. Antes era perfeito, se o xml viesse com a informação de pagamento e sua respectivas parcelas o sistema meu aqui já lançava tudo automaticamente sem interferência do usuário. Esperar pra ver como vai ficar esse negocio. 

Abraços
