### ISSUE TITLE
XML validação Pegar valor do imposto.ICMS ?

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#760]
Ola, estou lendo um XML já pronto e necessito ler o conteudo que tem no node imposto
Lá temos o ICMS, dentro dele pode haver variações dos tipos como ICMS40 ICMS60 sempre com um destes tipos, dentro do tipo há conteudos como CST qual e a classe que consigo ler esta informação, pois tentei utilizar a NFe.Classes.Informacoes.Detalhe e criei uma .det, nesta det.imposto.ICMS, ai e que complica pois dai fica só o TipoICMS e estou preso ai, como faço para verificar quais os tipos e como posso acessar os valores ?
Desde já agradeço a atenção.

**Comment by marcosgerene** [comment]
Boa noite,
Existem exemplos aqui de como fazer isso verifcando o tipo de variavel, ex:
```
if (...TipoICMS is ICMS40)
{
    ....
}
```

É uma forma válida, mas se você reparar, na impressão do DANFe em FastReports existe uma conversão do TipoICMS para **ICMSGeral**, esta classe ICMSGeral tem todas as propriedades possíveis para o ICSM o que facilita e muito sua vida.

Ex 
```
ICMSBasico icmsBasico = (ICMSBasico) meuobjetoNFe..infNFe.det.imposto.ICMS.TipoICMS;
ICMSGeral icmsGeral = new ICMSGeral(icmsBasico); 

var cst = icmsGeral.CST;
var base = icmsGeral.vBC;
....

```

**Comment by marcosgerene** [comment]
Pela falta de feedback vou considerar o tópico como resolvido, caso ainda persista a dúvida reabra a issue

**Comment by marcosmarchiore** [comment]
Resolveu meu problema com o acesso aos dados do ICMS perfeitamente como necessitava, desculpe a demora para o feedback pois ainda estou testando outras funcionalidades, Obrigado.
