### ISSUE TITLE
CTe - Desacordo da Operação

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#763]
Bom dia senhores,

Não consegui achar o evento de "Desacordo da Operação do CTe". Gostaria de confirmar se não está implementado. Se não estiver, tem alguém que tá desenvolvendo ou pretende? Se não, se for bem vindo ao projeto, posso tentar ajudar, mas só q ainda irá levar um tempinho pois tenho que implementar ainda a Distribuição do CT-e no meu ERP, somente depois q chegar lá, se ninguém ainda tiver feito, posso quebrar a cabeça um pokinho pra fazer em cima dos padrões de vc´s!

Obrigado.
Att.
Guilherme

**Comment by robertorp** [comment]
Opá tudo bom @gui-abrantes ?
Não tem no projeto e não tem ninguém implementando.

Pode implementar que será muito bem vindo para agregar o projeto ;)

**Comment by gui-abrantes** [comment]
Esqueci de comentar aqui pra marcar, mas tá lá no pull essa implementação!
