### ISSUE TITLE
NFC-e Minas Gerais

### ISSUE THREAD

**Issue by jamessp2014** [ZeusAutomacao/DFe.NET#765]
Pessoal boa tarde,
Andei pesquisando e vi que Minas Gerais aderiu a NFC-e alguém já conseguiu
realizar a implantação ?
Não conseguir ver nada no site da receita de minas segue o link:
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/

Somente a informação do NFC-e nada de cadastro etc...
Abraço a todos.

**Comment by robertorp** [comment]
Bom não sou do estado de MG e não sei como anda a implementação lá. 
Mas pensando que talvez isso ajude você, em teoria já tem servidor de homologação para nfc-e e produção em MG 

uma foto de uma consulta status do Zeus DFe.Net 

![image](https://user-images.githubusercontent.com/10251705/41125211-232d437a-6a7a-11e8-860d-a7516cc40dc8.png)

A consulta status esta em produção, testei em homologação e o resultado foi o mesmo

http://www.sped.fazenda.mg.gov.br/spedmg/noticias/NFC-e-Emissao-de-NFC-e-em-Minas-Gerais-para-o-comercio-varejista/

**Comment by jamessp2014** [comment]
Olá Roberto,
Obrigado pelo retorno, o estranho é que no portal guia NFC-e não tem ou pelo menos não encontrei
nada para o cadastro e geração do CSC e sua chave.

**Comment by eduprog** [comment]
Sou de Minas, e temos um bom contato com a SEFAZ daqui, o que já nos foi passado nos bastidores é que o Estado não tem orçamento para colocar o projeto em produção ou mesmo homologação neste ano. 
Ano de eleição e verba curta. Portanto esperamos ansiosamente pela resposta deles, pois hoje a maioria de nossos 90% de nossos clientes são em Minas Gerais e hoje atendemos com PAF-ECF. 

Mas com certeza, eles devem fazer como são paulo, dar um bom tempo para eliminar o ECF em si, pois o lobby dos grandes player de ECF ainda é grande e Minas está firme no ECF. 

Por um lado não somente o lobby em si, mas que grande parte do estado ainda hoje, pois um estado com deste tamanho, temos vários cantos do estado com um faturamento alto devido a agronegócios, mas com internet de péssima qualidade, querendo ou não tudo isto pesa na hora de colocar um projeto deste em prática. 

Enfim, é isto que temos, o site nem atualizado para tirar as datas de previsão foi.... 

Parado total....

**Comment by AndrewsFB** [comment]
As coisas aqui em MG andam a passos de tartaruga. Ainda tem muito chão para que o NFC-e se torne algo viável aqui. Infelizmente...

É possível usar o servidor de homologação para fazer testes, porém, conseguir aplicar isso em produção tendo o aval do estado deve demorar um bocado ainda.

**Comment by jamessp2014** [comment]
É pessoal obrigado pelo retorno estou com um cliente de São Paulo e esta abrindo uma filial em Minas.
Não tenho a homologação no PAF-ECF e hoje é meio inviável esta homologação.
Vamos ter que aguardar...

**Comment by eduprog** [comment]
Tem notícia fresca ai, mas somente segundo semestre: Veja no link
http://www.fazenda.mg.gov.br/noticias/2018.06.08_NFCE.html - Não é muita coisa:


**SEF/MG prevê implantação da NFC-e para o início de 2019**


**A Secretaria de Estado de Fazenda está finalizando a contratação necessária para adequação da área de Tecnologia da Informação (TI) a fim de viabilizar a emissão de Nota Fiscal do Consumidor Eletrônica (NFC-e) em Minas Gerais.**

**A estimativa da SEF/MG é que no segundo semestre de 2018 seja possível dar início à homologação da funcionalidade e, na sequência, colocar em prática um piloto com algumas empresas. Concluído o piloto, será possível agregar, gradativamente, contribuintes voluntários.**

**A legislação com o cronograma de obrigatoriedade será publicada também no próximo semestre, com previsão de início em 2019.**
