### ISSUE TITLE
Erro de WebService Consulta de Protocolo em ambiente de homologação. Basta ajustar o webservice correto.

### ISSUE THREAD

**Issue by fabiohcnobre** [ZeusAutomacao/DFe.NET#767]
Ola, verifiquei que esta errado o ws no enderecador.

Esta aassim no Enderecador -> endServico.Add(new EnderecoServico(ServicoNFe.NfeConsultaProtocolo, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MG, ModeloDocumento.NFe, "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsulta4"));

O correto e https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4

Por favor gostaria do ajuste. 

Att
Fabio

**Comment by robertorp** [comment]
Vou ajustar aqui e lançar no nuget. 

Correção aplicada no repositório.
https://github.com/ZeusAutomacao/DFe.NET/pull/769

Aguarde o nuget mais um pouco.

**Comment by robertorp** [comment]
![image](https://user-images.githubusercontent.com/10251705/41290699-0b7c8e40-6e24-11e8-9968-033650a074d2.png)

Nuget publicado com a correção, agora e somente esperar o próprio nuget liberar.
