### ISSUE TITLE
Duvida NFe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#768]
Qual evento o NFe.Danfe.App.Teste imprime na botão Evento Nfe?

**Comment by fabiohcnobre** [comment]
Imprime a NF-e no FastReport

Da uma olhada no evendo 
btnEventoNFe_Click
no link > 
https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Danfe.AppTeste/MainWindow.xaml.cs

NFe.Danfe.AppTeste: Projeto em WPF para demonstração de uso da impressão da NFe e NFCe (A NFe e NFCe estão disponíveis em FastReport.Net¹.
As dlls do FastReport.Net disponibilizadas na biblioteca são da versão de demonstração do mesmo. A versão de demonstração coloca uma marca d'água "DEMO VERSION" na impressão do relatório. Se você possui licença FastReport.Net, substitua as dlls do FastReport.Net nos projetos NFe.Danfe.Fast\Dll, CTe.Dacte.Fast\DLLs e MDFe.Damdfe.Fast\Dlls pelas dlls de sua versão licenciada, antes de compilar sua aplicação para distribuição.

Conhece nosso grupo no Skype ?
https://join.skype.com/CJbtNPlvbycL

**Comment by ThalisonSantos** [comment]
@fabiohcnobre pensei que era para imprimir a carta de correção já que vi o report dela no projeto

**Comment by fabiohcnobre** [comment]
Na verdade se voce dar um xml de carta de correção ele vai imprimir tambem. O evento de acordo com o seu xml.

**Comment by ThalisonSantos** [comment]
@fabiohcnobre eu vi aqui precisa selecionar os dois xml's para imprimir. valeu pela ajuda
