### ISSUE TITLE
Salvar eventos NFe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#771]
Pessoal há alguma maneira salvar a carta de correção em um diretório diferente dos outros eventos da nfe?
Vi que no acbr é possível selecionar um diretório para cada evento.

**Comment by robertorp** [comment]
No zeus ainda não tem nada do tipo. 
Pensei em fazer algo no futuro eventos e uma ext do zeus em outro repositorio que faça esse trabalho para você. Mas ainda e somente pensamento nada concreto.
Minha opinião salve os xmls em banco de dados.

**Comment by ThalisonSantos** [comment]
@robertorp  ok então, obrigado!
