### ISSUE TITLE
Problema Danfe NFe Fast

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#772]
[NFeFsist27180610628539000143550010000300571000300574.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2095200/NFeFsist27180610628539000143550010000300571000300574.pdf)
[NFeZeus27180610628539000143550010000300571000300574.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2095201/NFeZeus27180610628539000143550010000300571000300574.pdf)

Não tinha notado isso mas um cliente imprimiu uma nota com 87 itens no danfe fast do zeus a ordem dos itens saiu diferente do xml, alguém já teve este problema?

Edit: anexei o danfe do zeus e do site Fsist para comparação. obs. o correto é o do fsist.

**Comment by marcosgerene** [comment]
O Danfe do Fast até aonde eu lembro não orderna, ele chama "do jeito que foi", no projeto Danfe.Fast é enviado  o objeto do NFe como um array[], ou seja, não são enviados os itens "diretamente", tenho que ver se tem algum tipo de ordenação no .Frx, mas acho que não, se não tiver acredito que a solução seria antes de passar a NFe no método "RegisterData" ordernar os ítens.... preciso dar uma estudada nisso, mas to na correria aqui, assim que sobrar um tempo mando um PR.

**Comment by ThalisonSantos** [comment]
@marcosgerene imagino que deveria ser ordenado de acordo com o xml da nota pq lá fica ordenado pela tag nItem

**Comment by marcosgerene** [comment]
@ThalisonSantos vou mandar um PR aqui, você puxa ele e testa ai.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/774

**Comment by ThalisonSantos** [comment]
@marcosgerene fiz o teste e a ordem continuou da mesma forma só diminuiu o número de páginas de 3 para 2. vou anexar xml.

[NFe27180610628539000143550010000300571000300574.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2102149/NFe27180610628539000143550010000300571000300574.zip)

**Comment by marcosgerene** [comment]
@ThalisonSantos cara, eu testei aqui e está certo sim com o PR meu, por favor, baixe o fonte do meu repo e testa com ele, funcionou sim...

[teste.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2103287/teste.pdf)

Está na mesma ordem do XML

**Comment by ThalisonSantos** [comment]
@marcosgerene agora sim na medida, valeu mesmo muito obrigado!
