### ISSUE TITLE
Ausência dos métodos ObterPISBasico e ObterCOFINSBasico 

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#773]
Bom dia pessoal, td bem?

Estou usando o método ObterICMSBasico() da classe ICMSGeral para montar o conjunto de tags necessária deste grupo de impostos conforme a CST do item.

Porém, não encontrei no Zeus os mesmos métodos relativos a outros impostos, ou seja, ObterPISBasico(), ObterCOFINSBasico(), etc...

**Pergunta 1:** existe algum motivo técnico deste outros métodos não terem sido implementados?

**Pergunta 2:** tem alguém já trabalhando pra implementar isso? Senão eu poderia faze-los por aqui...

Abraços

**Comment by robertorp** [comment]
Não que eu saiba, implemente e iriei analisar o pull 

e quiser aproveitar e já incrementar no icms básico os fcps da vida

**Comment by apbertoletti** [comment]
Seria este?

#662

**Comment by robertorp** [comment]
Sim

**Comment by ThalisonSantos** [comment]
@robertorp essas alterações já estão disponíveis na versão do nuget?

**Comment by robertorp** [comment]
@ThalisonSantos  falar a verdade não lembro mas acho que sim. Teste e deixe um feedbak para nos aqui. 
Vlw

@apbertoletti  Obrigado pela contribuição!

**Comment by ThalisonSantos** [comment]
@robertorp baixei a ultima versão e não apareceu

**Comment by apbertoletti** [comment]
@ThalisonSantos , como vc fez pra testar a existência deste métodos ai?

Repare no que próprio projeto do AppTeste tem um exemplo de como utiliza-los.

![6-28-2018 4-17-57 pm](https://user-images.githubusercontent.com/6843493/42055921-0771bc62-7aef-11e8-9747-fb5333f4906f.png)

**Comment by ThalisonSantos** [comment]
@apbertoletti eu tentei usar as classes pisgeral e cofinsgeral mas não apareceram. Eu uso a versão do nuget e não as fontes do projeto

**Comment by robertorp** [comment]
Vou verificar isso aqui, e posto novamente o nuget se for preciso.

**Comment by apbertoletti** [comment]
> @apbertoletti eu tentei usar as classes pisgeral e cofinsgeral mas não apareceram. Eu uso a versão do nuget e não as fontes do projeto

@ThalisonSantos , o jeito de usar é o consumir este novo método é o mesmo, seja pelo Nuget ou direto pelo fonte do Zeus. Acabei de fazer um teste disso aqui, via Zeus (nuget), veja:

![6-28-2018 4-53-30 pm](https://user-images.githubusercontent.com/6843493/42057661-77f8c656-7af4-11e8-9314-f84f7ac1bfee.png)

**Comment by ThalisonSantos** [comment]
@apbertoletti realmente faltava um using em tributação federal por isso não estava aparecendo pra mim

**Comment by apbertoletti** [comment]
Boa!

CTRL + . sempre dá uma luz nestas horas ;)

**Comment by robertorp** [comment]
Ou.. Resharper fazer uma propaganda para eles.

Resharper e muito bom ;) 
Uso e pago 50 temers todo mês e sou feliz. 
Você digita e ele já imediatamente te sugere o uso de namespaces. Faz muitas outras coisas também.
