### ISSUE TITLE
Rejeição 878, Oque fazer no PR ?

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#775]
Pessoal, estou com um problema, retorno 103 e rejeição 878, endereço incorreto, alguém pode me dar um norte sobre o assunto, e a primeira vez que tentei usar a DFe.NET e estou tendo esta dificuldade, sinceramente o projeto e bem estruturado e simples de entender mas neste quesito não consegui lidar com a situação, se os amigos puderem com sua extrema experiencia me auxiliar neste pequeno contratempo fico agradecido.
Obrigado (Amém)!

**Comment by marcosgerene** [comment]
Bom dia,

Vamos primeiro traduzir sua pergunta:
Retorno 103: Lote processado.
Rejeição 878: Endereço do site da UF da Consulta por chave de acesso diverge do previsto.

Supondo que o que eu disse está correto:

O primeiro retorno (103) significa que a Sefaz recebeu sua solicitação e processou ela, ou seja, comunicação com o webservice está ok.

A rejeição significa uma falha no preenchimento da NFe, provavelmente na tag urlConsulta (acredito que estamos falando sobre NFCe). Neste caso anexe o XML aqui para analisarmos, de duas uma, ou a UF sua realmente está com a url incorreta na biblioteca ou você não preencheu corretamente a tag, com o XML conseguiremos ter essa informação de forma mais clara.

Att, Marcos

**Comment by marcosmarchiore** [comment]
Olá Marcos, sua analise está correta, primeiramente e NFCe sim, segundo o QRCode gerado pela biblioteca para o PR e o seguinte com a versão 4.00.

<qrCode><![CDATA[http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?chNFe=41180607742425000115650010000000071002356733&nVersao=100&tpAmb=1&dhEmi=323031382d30362d31335432333a31333a35382d30333a3030&vNF=0.06&vICMS=0.00&digVal=776e462f4634454c567451646672596643555348504c2b716a6a6f3d&cIdToken=000001&cHashQRCode=33f03ccff589cb9b4694e6815516e5bac434667c]]></qrCode><urlChave>http://www.fazenda.pr.gov.br/</urlChave>

Nestes site  http://nfce.encat.org/desenvolvedor/qrcode/
Informa o valor de: 

Paraná | 
URL QRCODE NFCe 3.10 -http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?URL da versão 3.10 continua ativa, até o encerramento dessa versão.
URL QRCODE NFCe 4.00 – http://www.fazenda.pr.gov.br/nfce/qrcode?



[XMLTESTE (2).zip](https://github.com/ZeusAutomacao/DFe.NET/files/2103368/XMLTESTE.2.zip)

**Comment by marcosgerene** [comment]
Urls segundo o ACBr:

**Produçao:
URL-QRCode=http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe
URL-ConsultaNFCe=http://www.fazenda.pr.gov.br/
URL-QRCode_2.00=http://www.fazenda.pr.gov.br/nfce/qrcode
URL-ConsultaNFCe_2.00=http://www.fazenda.pr.gov.br/nfce/consulta
URL-QRCode_1.00=http://www.fazenda.pr.gov.br/nfce/qrcode/
URL-ConsultaNFCe_1.00=http://www.fazenda.pr.gov.br**

Homologação:
URL-QRCode=http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe
URL-ConsultaNFCe=http://www.fazenda.pr.gov.br/
URL-QRCode_2.00=http://www.fazenda.pr.gov.br/nfce/qrcode
URL-ConsultaNFCe_2.00=http://www.fazenda.pr.gov.br/nfce/consulta
URL-QRCode_1.00=http://www.fazenda.pr.gov.br/nfce/qrcode/
URL-ConsultaNFCe_1.00=http://www.fazenda.pr.gov.br


Seu xmL:
```
<infNFeSupl>
<qrCode>
<![CDATA[
http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?chNFe=41180607742425000115650010000000071002356733&nVersao=100&tpAmb=1&dhEmi=323031382d30362d31335432333a31333a35382d30333a3030&vNF=0.06&vICMS=0.00&digVal=776e462f4634454c567451646672596643555348504c2b716a6a6f3d&cIdToken=000001&cHashQRCode=33f03ccff589cb9b4694e6815516e5bac434667c
]]>
</qrCode>
<urlChave>http://www.fazenda.pr.gov.br/</urlChave>
</infNFeSupl>
```

A URL de consulta que você utiliza no QrCode não me parece estar correta, provavelmente ao chamar a função da biblioteca para montar a URL você passou a versão 3.10 como parâmetro e não a 4.00.

Olha um trecho do meu código:
![image](https://user-images.githubusercontent.com/15945003/41429248-ea7f23f4-6fe2-11e8-991b-510d9c657ea0.png)

Em ambas as funções o parâmetro **versaoServico** deve receber o mesmo valor da versão da NFe, neste caso seu **NFe.Classes.Servicos.Tipos.VersaoServico.ve400**.

**Comment by marcosmarchiore** [comment]
Marcos, Obrigado pela atenção primeiramente, sua analise está correta, como eu peguei o código da aplicação de teste a qual chama a função infNFeSupl.ObterUrl( ...... ) com os parametros e no exemplo não está passando o ultimo parametro que e a versão não estava sendo passado e no código da função se não passado ele assume a versão 3.10, acredito que sejá interessante retirar esse default ou mesmo colocar para a versão 4.00 que e a atual.
Agradeço novamente e considero o problema totalmente resolvido.
