### ISSUE TITLE
Idéias: Preenchimento NF-e, NFC-e, CT-e, etc...

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#777]
Olá pessoal,

Como hoje aqui vc´s facilitam a vida do usuário para emitir um documento fiscal? Como preencher CST, CFOP, Aliquotas...etc!

É por meio de cadastro de tipos de operação, ou por meio de parametros, exemplo: Emitente da UF tal para destino da UF tal, vou usar CFOP tal, com aliquota tal...e assim por diante.

O que vc´s fazem para facilitar a vida dos usuários, para preencher o mínimo de informações possíveis?

**Comment by robertorp** [comment]
Você diz telas em questão e tudo mais?

**Comment by gui-abrantes** [comment]
tinha até esquecido....rsrs! bom dia @robertorp, é mais ou menos isso, mas não o desenho da tela em si (claro se quiser expor, será muito bem vindo, rsrs), mas eu queria saber mais os preenchimentos, por exemplo dos tributos. Ex.: o usuario num fica colocando a aliquota do ICMS toda vez que lança um novo item na Nota, por exemplo a empresa aqui onde trabalho, coloca tipo um perfil na hora de lançar um item, (Ex. de MG pra SP, no CFOP 6104, do grupo do produto "ROUPAS", com o grupo do destinatário "GRUPO DE CLIENTES ESPECIAIS", daí cadastra as alíquotas, o CST ou CSOSN, PIS/COFINS....e por aí vai) e  preenche automático os campos do Item da Nota, quando o item que for lançado comtemple esses parametros (perfil).

Eu to fazendo uma nova NFe do zero, pra mim mesmo, projeto particular meu, e num sei se essa é a melhor abordagem, queria às vezes fazer uma coisa mais simples porém que atende os clientes. E como a gente fica meio sem idéia por ser uma coisa nova querendo fazer melhor, eu tava buscando dicas da turma aqui.

Att,
Guilherme
