### ISSUE TITLE
Preenchimento da tag <pag>

### ISSUE THREAD

**Issue by AndrewsFB** [ZeusAutomacao/DFe.NET#778]
Saudações sres!

Gostaria de pedir um conselho a todos sobre o preenchimento das informações de pagamento na NFe. Até a versão 3.10 não tínhamos que enviar tal informação.

Estou enfrentando um dilema no que diz respeito a clientes de autopeças que controlam o contas a receber de produtos e serviços de forma unificada. Tendo seus recebimentos somando os dois. Como se daria o preenchimento numa situação dessas dado que o valor dos recebimentos não fechará com o valor total dos produtos (por causa dos serviços).

Estou tentando chegar numa solução o menos drástica possível, mas, não vejo outra além de separar o contas a receber...

**Comment by apbertoletti** [comment]
@AndrewsFB ,  td bem?

Uma pergunta de cunho fiscal antes: no município do seu cliente é permitido emitir um NFe com produtos + serviços juntos no mesmo documento?

**Comment by AndrewsFB** [comment]
Permite não...

**Comment by apbertoletti** [comment]
Certo, então é igual aqui....

Por questões contábeis não pudemos mais juntar o receber desta tipo de operação (produtos + serviços) numa unica fatura. Tivemos que separar isso...

Sendo assim, nas tags do pagamento da NFe irão somente os recebimentos provenientes de produtos, batendo assim com os totais esperados.

**Comment by AndrewsFB** [comment]
Essa tem sido a resposta geral @apbertoletti.
Estou com um pouco de dificuldade de adotar isso por causa do impacto que causará em alguns clientes.
Mas se não tem jeito, fazer o que né rs

Muito obrigado pela consultoria :D !

**Comment by apbertoletti** [comment]
Realmente,

Para alguns clientes aqui isso terá um impacto na despesas inclusive, visto que terão que emitir dois boletos, um pra serviços e outro pra produtos, e pagar duas vezes a tarifa de emissão dos mesmo. Complicado né?

Mas enfim, se souber de alguma solução melhor, compartilhemos.,,
