### ISSUE TITLE
Publicada versão 1.60 da NT 2016.002 e pacote de schemas XML correspondente

### ISSUE THREAD

**Issue by rodrigordi** [ZeusAutomacao/DFe.NET#779]
A versão 1.60 da NT 2016.002 posterga o prazo de desativação da versão 3.10 em 30 dias, define novos prazos para validação do QR-Code da NFC-e, entre outras alterações

**Comment by robertorp** [comment]
<h1>RESUMO NT 2016.002 VERSÃO 1.60</h1>

<b>Novo prazo para Desativação da versão anterior da NF-e 3.10 => 02/08/2018 página 12 da NT</b>

<b>Alterações no layout da versão 1.60 => página 12</b>
- o prazo para implantação das alterações trazidas pela versão 1.60 desta NT é: 
- ambiente de Homologação (ambiente de teste das empresas): 02/07/2018
- ambiente de Produção: 09/07/2018

<b>Em relação a NFC-e => página 13</b>
- A DESATIVAÇÃO DA NFC-e continua em 01/10/2018

<i>O que muda são os prazos para qrCode 2.00</i>

- a partir de 02/07/2018 e aceita NFC-e na versão 4.00 com leiaute do QR-CODE na versão 1.00 é versão 2.00
- a partir de 09/07/2018 e aceita NFC-e na versão 4.00 com o leiaute do QR-CODE na versão 1.00 é versão 2.00
- desativação da versão 1.00 do QR-CODE em produção => 01/10/2018

<b>Vamos a algumas dicas
- somente será aceito o TSL 1.2 na versão 4.00
- algumas versões do Windows não tem TSL 1.2 por mais que apareça a opção lá ele não tem!! Por incrível que pareça é serio. E recomendável que atualize o Windows. 
- comigo aconteceu somente com Windows 7. </b>

<b>ALTERAÇÕES DE LAYOUT DA VERSÃO 1.51 PARA A VERSÃO 1.60</b>
- dentro da tag prod temos <b>cBenef</b> foi alterado o tamanho aceitado de 10 para 8,10 ou seja.. e aceito os tamanhos 8 ou 10.

- Criado novo grupo opcional dentro do CST 60 e CST 500 com campos relativos a dados para cálculo da restituição ou complemento da ST.

- pRedBCEfet
- vBCEfet
- pICMSEfet
- vICMSEfet

![image](https://user-images.githubusercontent.com/10251705/41561691-fab52dc2-7320-11e8-9801-0510a2d4c80d.png)

- Incluída na coluna de observação do campo Número de parcela (tag:nDup, id:Y08), orientação quanto ao correto preenchimento do campo.
- Incluída na coluna de observação do campo Data de vencimento (tag: dVenc, id:Y09), orientação quanto ao correto preenchimento do campo.

![image](https://user-images.githubusercontent.com/10251705/41561967-a5c7fdf2-7321-11e8-9fec-4292c2b2bcad.png)

<b> algumas observações enquanto a validações da Sefaz </b>
![image](https://user-images.githubusercontent.com/10251705/41562148-26797ee4-7322-11e8-8bcf-345bcb75fde6.png)
indFinal = 1: Consumidor final (sefaz so me fode)

![image](https://user-images.githubusercontent.com/10251705/41562273-803391d6-7322-11e8-8782-0eaa0761f8ab.png)

<i><b>algumas pessoas se depararam com essas validações, teve mudanças viu!</b></i>
![image](https://user-images.githubusercontent.com/10251705/41562340-aa18552c-7322-11e8-8c01-8803515d4422.png)

<i><b>observem bem essa rejeição para não errar</b></i>
![image](https://user-images.githubusercontent.com/10251705/41562434-f7d0b084-7322-11e8-8469-4ba90cc0fb15.png)


<i><b>Vamos ver se eles excluem o campo de verdade agora ne?</b></i>
![image](https://user-images.githubusercontent.com/10251705/41562482-295e6ca4-7323-11e8-97d1-7c83d511763c.png)

<i><b>Lembre-se não se aplica a nota fiscal de DEVOLUÇÃO e nota fiscal de AJUSTE colocar como meio de pagamento 90 (SEM PAGAMENTO)</b></i>
![image](https://user-images.githubusercontent.com/10251705/41562581-72e3f754-7323-11e8-8a53-fc2df0d4df6c.png)

<i><b>fiquem esperto com o if ou switch case ou sei la oque vocês usam ein</b></i>
![image](https://user-images.githubusercontent.com/10251705/41562673-b8521da2-7323-11e8-857b-50e4585c5cf9.png)

<b>a partir da página 66 até a 72 existem varias regras sobre o qrcode com N datas diferentes de vigor! se quiser ler leia! e se for ler leia tudo! vá além da página 72 kkk</b>

**Comment by rodrigordi** [comment]
@robertorp windows 7 só se estiver totalmente atualizado e com .net 4.6.2 instalado. foi o unico jeito que consegui fazer funcionar.

**Comment by robertorp** [comment]
Não cheguei a observar se tinha instalado o .net 4.6.2. Mas show de bola. Essa atualização ta pegando nós de jeito mesmo rsrs.

**Comment by marcosgerene** [comment]
@rodrigordi a instalação do .net 4.6.2 basta ou é necessário mesmo assim rodar o windows update? detalha um pouco mais isso, por favor, me interessei

**Comment by rodrigordi** [comment]
@marcosgerene tive que atualizar o windows todo. só o .net não resolveu. peguei maquina aqui que tinha mais de 2 anos sem update.

**Comment by rftd** [comment]
Só atualizar o Windows resolve, o .net framework usa dll do Windows tanto se setar tls 1.2 no .net 4 funciona desde que tenha o .net 4.5 já.

**Comment by rodrigordi** [comment]
Então deve ser .net 4.5.2 e windows 7 atualizado para o TLS.
E o .net 4.6.2 para e-social para funcionar com sha256.
Valeu @rftd

**Comment by rftd** [comment]
Vamos la 
TLS 1.2 - Windows 7 SP1 ou Windows Server 2008 R2 atualizados e .Net 4.5.
SHA256 - .Net 4.5, mas precisa criar uma classe, 4.6.2 não precisa.

**Comment by rodrigordi** [comment]
@rftd compartilha essa classe ai. Eu tive que migrar meu projeto do esocial para 4.6.2. Com essa classe eu consigo continuar usando o 4.5.2 ?

**Comment by rftd** [comment]
https://github.com/ACBrNet/ACBr.Net.DFe.Core/blob/master/src/ACBr.Net.DFe.Core/Cryptography/RSAPKCS1SHA256SignatureDescription.cs

ai é so registrar 

`CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");`
