### ISSUE TITLE
Versão do Web Service Recepção Evento Paraná

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#78]
Olá Adenilton, bom dia!

Realizando alguns testes em um cliente meu no Paraná, constatei que a versão do web service Recepção Evento não é 3.10 e sim 1.00.

endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve100, TipoAmbiente.taProducao, emissao, Estado.PR, ModeloDocumento.NFCe, "https://nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento"));

Apenas para você poder alterar ai e quem sabe ajudar outros que possam ter o mesmo problema.

Obrigado!

**Comment by adeniltonbs** [comment]
Obr pelo aviso. O acerto foi feito no commit 1ea01c34310af09d0cd6040837f9d9d3996f6ca1.
Teria como avisar a SEFAZ do PR para indicar a versão de cada webservice nesta url?
http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97

**Comment by ghost** [comment]
Olá Adenilton!

Obrigado pela correção.
Infelizmente eu já fiz essa solicitação a alguns meses atras, porém não me retornaram.
De qualquer forma, tento novamente contato lá.

Obrigado!
