### ISSUE TITLE
Controle de qualidade (QA) no código do Zeus

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#780]
Olá pessoal, td bem?

Mantenedores e colaborados do Zeus, vocês costumam implementar testes automatizados pra garantir uma minimo de testabilidade nas rotinas do componente? Ou estão fazendo este controle de qualidade de alguma outra forma?

Reparei que existe poucos testes automatizados (só 1 na vdd) no master do projeto... estou pensando em subir mais alguns no próximo PR, td bem por vocês? Alguém tem mais alguns ai pra contribuir?

@robertorp , você sabe me dizer se vocês costumam rodar a suite de testes automatizado da solução a fim de verificar se nada foi quebrado? E em que momentos costumam rodar eles?

Valeu pessoal, vamos nos falando...

Abraços

André

**Comment by marcosgerene** [comment]
Rapaz, infelizmente a esmagadora maioria das minhas alterações eu tenho que fazer no quente, são coisas pontuais como formatação de um número, ajustes na impressão, entre outros que dificilmente são previsíveis em testes automatizados.

As alterações fora disso acabo testando localmente "na unha", uso o projeto praticamente desde o início dele, então "por experiência" acabo tendo uma noção do que pode ser afetado pelo meu código, mas geralmente espero alguém testar meu PR mesmo assim, hoje tenho permissão para escrever no projeto, mas procuro nunca aceitar meus PRs, sempre deixo para outros testarem, salvo casos específicos como correções de bugs pontuais.

Resumindo: nada automatizado.

**Comment by robertorp** [comment]
@apbertoletti  fique a vontade para fazer os testes, realmente precisa de testes, mas hoje não tem como você mesmo viu. 

como o próprio @marcosgerene  falou, meus testes são baixando fork por fork e testando funcionalidades, e algumas coisas como já tenho noção do fonte do Zeus, já sei dizer se vai dar erro ou não.

os testes são rodados toda vez aqui https://ci.appveyor.com/project/adeniltonbs/zeus-net-nfe-nfce/branch/master
