### ISSUE TITLE
Obter Certificado (Desktop App, Windows Service e ASP IIS)

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#781]
Estou com uma situação que vou repassar para vocês.
Fiz uma aplicação C# .Net 
Em modo debug no meu equipamento retorna o certificado corretamente, agora se eu publicar ela no meu computador mesmo não consegue mais ler o certificado, a principio tentei verificar direito de usuario do IIS como o IUSR ou ainda o usuário que configurei para acesso a aplicação no IIS o qual tem direito a ler o certificado, outro detalhe e que o certificado está instalado para o usuario e também para o equipamento, eu tenho outra solução em C# que a um tempo atras tive problemas e acabei modificando o projeto para conseguir ler a informação do certificado mas acabei tendo que modificar algumas classes do DFe.NET e não e oque gostaria de fazer pois isso vai me atrapalhar em futuras atualização da biblioteca, 
Há algum parametro que passei despercebido para tratar essa situação, para completar, já utilizei a forma do certificado como arquivo e como byte array.

**Comment by fatechbr** [comment]
Olá amigo, eu uso o certificado a1 em bytes, e funciona normalmente, uma vez tive um problema parecido, eu fiz um sistema de log em arquivo txt e fui traqueando até descobrir o local exato, e loguei tb o erro... espero ter ajudado

**Comment by marcosmarchiore** [comment]
Olá @faironsp sua aplicação e ASP C#, qual a versão do seu IIS, pois eu consegui identificar algumas coisas aqui, não sei o porque até sobre algumas, mas como comentei anteriormente a mudança de comportamento da versão em DEBUG e diferente da versão em produção pois em DEBUG o sistema operacional utiliza o certificado instalado no meu usuário, já na versão em produção o usuário e outro, ou o IUSR ou o usuário que dei direito a executar o aplicativo no IIS, sendo assim fica difícil realmente saber qual o detalhe que há de diferente.
Observei que quando utilizo a certificado com leitura pelo DFe.NET observei que ele pega a chave primaria, que no meu usuário funciona, já em produção não, na minha aplicação observei que não pega a chave primaria, desta forma funciona em ambas as situações, só que na minha solução na hora de assinar tenho que dai sim colocar a chave primaria, pois sem ela não assina, como comentei, até está funcionando da forma que fiz, o grande problema e que tive que alterar funções da DFe.NET e não gostaria de fazer isso, acredito que haja um norte para que possa solucionar esta situação sem ter que modificar as rotinas da DFe.NET.
Caso haja alguma luz ai no final fico agradecido a todos que possam colaborar.

**Comment by dennyphilipp** [comment]
Também estou com um problema parecido, porem retorna um erro na hora de assinar o xml "System.Security.Cryptography.CryptographicException: 'Algoritmo inválido especificado." em proc.NFe.Assina(Configuracao);
Fiz todos os testes usando Console Application e funcionou a autorização e cancelamento da NFe.
Agora passei para minha aplicação Web e fica dando esse erro.

**Edit**
**Descobri o meu problema**, a versão do .NET Framework da minha aplicação Web estava em 4.7.1, precisei baixar para 4.6.2 para funcionar e conseguir assinar o xml com o certificado A1.

**Comment by robertorp** [comment]
@marcosmarchiore  resolveu o problema?
Acho que tem algumas issues no repositório sobre o assunto. 
Mas se bem me recordo elas envolviam liberar permissão no ISS, bom pelo que observei aqui não e seu caso né.

**Comment by marcosmarchiore** [comment]
@robertorp eu tive que alterar o código do DFe.Net para poder resolver o problema aqui com a leitura do certificado através de uma rotina minha, não e oque eu queria pois toda vez que precisar atualizar a biblioteca vou ter que ficar mudando na mão aqui, se necessário posso postar a minha rotina para que isso possa ser implementado através de parametro, também tive que fazer a instalação do certificado e dar direitos através de aplicativo da microsoft o winhttpcertcfg.exe com as seguintes rotinas.

Ferramenta.
https://docs.microsoft.com/pt-br/windows/desktop/WinHttp/winhttpcertcfg-exe--a-certificate-configuration-tool

winhttpcertcfg -i PFXFile -c LOCAL_MACHINE\Root -a nomedousuario -p PFXPassword
winhttpcertcfg -i PFXFile -c LOCAL_MACHINE\My -a nomedousuario -p PFXPassword

No meu caso, coloquei, Todos, IUSR e o meu usuário.

Mesmo efetuando a instalação fiz o direito

winhttpcertcfg -g -c LOCAL_MACHINE\My -s “nome do certificado” -a “Everyone”
winhttpcertcfg -g -c LOCAL_MACHINE\Root -s “nome do certificado” -a “Everyone”

Everyone ai e o usuario Ok.

Depois de efetuar estes passo o certificado começou a ser reconhecido.

**Comment by AcciolyDSI** [comment]
Minha aplicação é baseada em uma WEB API, então para certificado A1, o usuário faz o upload do arquivo .pfx e blz funciona tranquilo. Já para o certificado A3 eu criei um monitor que fica instalado na máquina do cliente onde está o certificado, seja cartão ou token, e quando o usuário gera uma nota na minha aplicação que fica na nuvem, o sistema gera o xml e envia para o monitor que recebe, valida, assina e devolve o xml autorizado, ou devolve as mensagens de erros se a operação não foi um sucesso. Para comunicação entre  a API e o monitor utilizei o signalr para manter a conexão entre os dois, e para que a operação seja em tempo real. Resumindo, acho que vc deveria seguir algo semelhante, porque se vc resolver colocar sua aplicação na nuvem será muito mais dificil fazer o que vc esta fazendo, ainda mais quando envolve varios clientes com ambientes distintos, a dor será intensa.

**Comment by vitoresan** [comment]
@faironsp será que poderia mostrar como fez o consumo do certificado por arrayBytes?

`        private ConfiguracaoCertificado RetornarConfiguracoesCertificado() => new ConfiguracaoCertificado
        {
            TipoCertificado = TipoCertificado.A1Arquivo,
            ArrayBytesArquivo = _arrayBytesArquivo,
            Senha = _senhaCertificado,
        };

fiz desta forma e esta retornando certificado não localizado.`
