### ISSUE TITLE
Divergência na tag <pag> entre o manual da NFe e o Zeus

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#786]
Olá pessoal, 

Reparei aqui que a cardinalidade da tag < pag > (ID=YA01) está no Zeus está divergente com o Manual da SEFAZ. Isso foi intencional ou acidental?

![6-25-2018 5-38-37 pm](https://user-images.githubusercontent.com/6843493/41875528-7a7fe72e-78a1-11e8-9ab8-7fff45336118.png)

Abraços!

**Comment by robertorp** [comment]
Estou emitindo NFC-e normalmente utilizando a mesma. 
Mas, antes de mexer aí tem que verificar o manual 3.10 da NF-e 
Pois o mesmo matem e vai continuar mantendo compatibilidade com a nfe 3.10 por um longo tempo mesmo depois da inativação do servidor. Pois você pode precisar acessar alguma nota do seu cliente em algum momento e a versão dela ser 3.10.

Não olhei o manual 3.10 mas me lembro de ter feito pensando nisso, quando fiz nfe 4.00

editado: adicionado imagem manual 3.10
![image](https://user-images.githubusercontent.com/10251705/41876159-527680ba-78a3-11e8-958d-500e118563ee.png)

**Comment by apbertoletti** [comment]
Entendido @robertorp , 

valeu!
