### ISSUE TITLE
Sem comunicação com o serviço NFeAutorizacao: The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by devfabricioalmeida** [ZeusAutomacao/DFe.NET#788]
Estou tentando enviar uma NF-e na versão 4.0 e está me retornando essa exceção abaixo. Já fiz atualização do Framework e das cadeias do certificado, e mesmo assim está continua dando mesmo problema.
`Sem comunicação com o serviço NFeAutorizacao:
The underlying connection was closed: An unexpected error occurred on a send.
   at System.Web.Services.Protocols.WebClientProtocol.GetWebResponse(WebRequest request)
   at System.Web.Services.Protocols.HttpWebClientProtocol.GetWebResponse(WebRequest request)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at NFe.Wsdl.Autorizacao.NFeAutorizacao4.Execute(XmlNode nfeDadosMsg)`

**Comment by guidi** [comment]
Qual protocolo está configurado?

**Comment by devfabricioalmeida** [comment]
Temamos com todos e com cada um individualmente.
Atualmente está assim:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

**Comment by guidi** [comment]
Estranho, aqui para NFe 4.0 estamos usando assim.

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;

**Comment by devfabricioalmeida** [comment]
Tentamos dessa forma e não deu certo. Estamos tendo esse nos WebServices do SVRS e AN.

**Comment by devGustavoFerreira** [comment]
Estou tendo o mesmo problema ao consumir o WebService de autorização no estado do RJ (que também usa o SVRS). Estou tendo esse problema em um terminal com Windows 7 SP1, em outro terminal com Windows 10 Pro funciona normalmente.

Configurado da seguinte maneira: 
ServicePointManager.SecurityProtocol =  SecurityProtocolType.Tls12;

**Comment by marcosgerene** [comment]
@devGustavoFerreira 
>Estou tendo o mesmo problema ao consumir o WebService de autorização no estado do RJ (que
>também usa o SVRS). Estou tendo esse problema em um terminal com Windows 7 SP1, em outro
>terminal com Windows 10 Pro funciona normalmente.
>Configurado da seguinte maneira:
>ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Veja se o windows está atualizado, o Windows 7 depende de alguns KBs para ter o TLS 1.2.

Tem mais detalhes nas respostas da issue https://github.com/ZeusAutomacao/DFe.NET/issues/779

**Comment by robertorp** [comment]
Como o @marcosgerene  falou, tem que atualizar o windows 7, eu falo atualizar, porque não achei quais pacotes realmente vão solucionar o problema. 

E o protocolo tem que ser TSL 1.2 para nf-e 4.00

**Comment by devGustavoFerreira** [comment]
Pesquisei aqui e também não encontrei as atualizações específicas. Rodei o windows update e tem 136 atualizações. Quando terminar eu posto aqui se funcionou.

**Comment by marcosgerene** [comment]
@devGustavoFerreira 

>Pesquisei aqui e também não encontrei as atualizações específicas. Rodei o windows update e tem 136 atualizações. Quando terminar eu posto aqui se funcionou.

infelizmente o pessoal acaba desativando atualização do windows ou pra não ficar "atrapalhando" ou porque é windows não é original, ai quando precisa de algo é dessa forma, perde um dia atualizando.

**Comment by devfabricioalmeida** [comment]
Funcionou depois que fiz a atualização completa do Windows 7 conforme vocês sugeriram. Agradeço pela ajuda de vocês!

**Comment by orochasamuel** [comment]
> Como o @marcosgerene falou, tem que atualizar o windows 7, eu falo atualizar, porque não achei quais pacotes realmente vão solucionar o problema.

Tutorial:
https://support.microsoft.com/pt-br/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

Catálogo de Atualizações:
http://www.catalog.update.microsoft.com/search.aspx?q=kb3140245

 ---------------------

![image](https://user-images.githubusercontent.com/15462690/43295963-cfbf37ae-911e-11e8-87b7-0e9ef5f92bd4.png)
Fonte: https://support.microsoft.com/pt-br/help/4040243/how-to-enable-tls-1-2-for-configuration-manager

**Ainda não testei para ter certeza de que funcionará somente com esse pacote, se alguém puder fazê-lo e confirmar. o/**

**Comment by GuilhermeAlmeida94** [comment]
Não funcionou comigo.

**Comment by robertorp** [comment]
@Guiphb 
Atualize o windows, coloque nfe 4.00
TLS 1.2 
Verifique certificados digitais.
Verifique cadeias de certificado.
Única coisa que é garantida o framework não tem erro em relação a comunicação com a sefaz. Uso o mesmo em mais de 600 clientes, para emissão de NF-e/CT-e/CT-eOS (nesse branch não tem CT-e OS mas tem um branch que tem, vou passar o CT-e OS para esse branch tb)
MDF-e

e toda vez que me acontece qualquer erro de comunicação com a sefaz pode saber que e algo que citei acima.
"Atualize o windows, coloque nfe 4.00
TLS 1.2 
Verifique certificados digitais.
Verifique cadeias de certificado."

Observação meu sistema funciona com framework .net 4.5.2 por motivos de não querer atualizar windows 7 para um service pack especifico.

**Comment by ivanslater** [comment]
Galera, estou com o mesmo problema no Win 2012 Server, rodando em FW 4.5.1... vocês conseguiram resolver?

**Comment by orochasamuel** [comment]
@ivanslater usa o [IISCrypto ](https://www.nartac.com/Products/IISCrypto/) para verificar se o TLS 1.2 está ativo na máquina.

**Comment by ivanslater** [comment]
Na maquina de DEV deu certo, rodei ele, habilitei o TLS12 e emitiu a NF sem problemas, o ruim é que em PROD não vou poder rodar e nem conseguir que alguem rode.. área de segurança é dura na queda. A NFe só vai rodar com o TLS12 habilitado? Vocês sabem como habilitar na mão?

**Comment by ivanslater** [comment]
Resolvido. Só defini o targetFramework="4.6" no web.config e pronto, a partir do 4.6 o suporte a TLS 1.2 é nativo, não precisamos mexer em nada no servidor.

**Comment by oggbarcelos** [comment]
Pra registrar, aumentar o timeout pode resolver também:

`
ConfiguracaoServico.Instancia.TimeOut = 6000;
`
