### ISSUE TITLE
Problemas ao Assinar XML de NFCe

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#79]
Adenilton, estou atualizando meus códigos e agora estou tendo um problema ao assinar um XML de NFCe já com a tag tpIntegra. Segue o XML em anexo para que possa me ajudar.

PS: Troquei a extensão para TXT para aceitar anexar aqui.

[NFe11151184588540000128650010000101161981262314.txt](https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/files/43391/NFe11151184588540000128650010000101161981262314.txt)

**Comment by adeniltonbs** [comment]
Corrigido no commit d17119d4db3e8f68ba13aa368ccf710c0e1aeaa8.
