### ISSUE TITLE
Sobre a forma de pagamento Duplicata Mercantil

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#790]
Pessoal, td bem?

Baseado no desenrolar das conversas na issue #728 , estive implementando aqui o preenchimento de um comboBox em tela, basado nos valores do Enum da Forma de Pagamento. 

Porém notei que o elemento Duplicata Mercantil, por ainda estar presente neste Enum, acabava aparecendo também no comboBox. podendo causar uma escolha errada por parte do usuário, visto que esta forma de pagamento já não é mais aceita pela SEFAZ (NT 2016.002 v1.50).

Sendo assim, gostaria de dar duas sugestões de como resolver esta problema, e ouvir a opinião de vcs de qual será a forma mais adequada:

1. Removermos de vez este elemento "Duplicata mercantil" deste Enum, evitando assim o seu uso indevido. Mesmo que haja alguma quebra de código, seria esta uma "quebra esperada".

2. Marcarmos este elemento como Obsoleto, e desta forma ao menos alertarmos sobre os riscos de continuar utilizando o mesmo. Vejam mais sobre este atributo na documentação abaixo:
https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netframework-4.7.2

Enfim pessoal, digam ai o que vcs acham...

Assim que chegarmos numa melhor alternativa, posso implementar ela no Zeus.

Abraços

**Comment by rodrigordi** [comment]
oi @apbertoletti , acho que não pode remover o item14 não pq ele pode ter sido usado em algum momento por algum contribuinte. se voce tentar abrir um xml que tem o valor 14 informado, o deserializador irá falhar.

**Comment by robertorp** [comment]
@apbertoletti  Já tentei colocar como Obsoleto se você olhar no histórico do arquivo no git.

A serialização do xml solta uma bomba nuclear (exception) para trás se tiver esperando algum xml com 14

E não pode remover porque clientes já podem ter usado a mesma, digo isso até mesmo por min, tem ou teve clientes usando a mesma. Imagine você precisar reimprimir uma NF-e 4.00 que já foi emitida usando duplicata mercantil? Meus clientes já emitem a algum tempo NF-e 4.00 e já emitiram a nf-e 4.00

Imagine uma importação de xml que dependa da duplicata mercantil também? 

Assim se você achar uma alternativa que não envolva a remoção e não atrapalhe a serialização, ai fica perfeito.

**Comment by apbertoletti** [comment]
Obrigado pelo feedback pessoal, 

@robertorp , só uma duvida: quais passos eu faço pra poder simular aqui esta "bomba nuclear" ao usar o ObsoleteAttribute na Duplicata mercantil, que o fez remover este atributo que já havia colocado?

Vou fazer alguns testes aqui com esta informação...

**Comment by robertorp** [comment]
Coloca ele com Obsolete
Gera um XML usando duplicata mercantil (imagino eu que já vai lançar a exception)

Ou obtenha um XML que tenha duplicata mercantil e tenta fazer o load pela DLL e ele vai lançar uma exception.

Comigo deu na pratica mesmo, aqui no desenvolvimento foi imprimir uma NF-e 4.00 ou NFC-e com duplicata e deu exception. Retirei o Obsolete e funcionou lindamente. 

Meu sistema ainda emite com duplicata mercantil porque a sefaz esta rejeitando diferente de duplicata mercantil quando tem tag cobr

Vou verificar se a sefaz ate o momento dessa conversa aceita ainda com duplicata mercantil se aceitar vou emitir uma e postar o xml aqui para você

**Comment by robertorp** [comment]
Xml com Duplicata, foi emitido a varios dias atrás, a sefaz me rejeitou hoje dizendo que estou mandando os numeros das parcelas incorreto, coisa que deveria ser na proxima NT daqui uns dias, mas pelo jeito a sefaz de goiás esta um pouco adianta. 

[xml duplicata mercantil.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2146437/xml.duplicata.mercantil.txt)

**Comment by apbertoletti** [comment]
Acabei de emitir uma NFe 4.00 em homologação na SEFAZ SP, e realmente ainda está passando normalmente com a forma de pagamento Duplicata Mercantil (14).

[35180601607246000199550020000138251000358220-procNfe.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2146731/35180601607246000199550020000138251000358220-procNfe.txt)

Sendo assim, não vejo muito viabilidade mexermos nisso agora... enquanto a SEFAZ ainda está aceitando.

O que vcs acham?

**Comment by robertorp** [comment]
Acho que não tem o que mexer no momento também. Mas futuramente sim mas.. de alguma forma que não prejudique quem já emitiu usando o mesmo e claro. Manter compatibilidade com versões anteriores.

**Comment by apbertoletti** [comment]
Pessoal, 

Lendo a NT2016.002 (v1.60) com mais calma, pude perceber que a regra de validação existente para rejeitar o uso da forma de pagamento Duplicata Mercantil, aplica-se apenas ao modelo de documento 65, ou seja, somente para NFC-e.


![6-29-2018 3-42-15 pm](https://user-images.githubusercontent.com/6843493/42110052-273c7b46-7bb6-11e8-85ea-3da0c749cf9b.png)


Sendo assim, para NFe, esta forma de pagamento ainda está sendo aceita (pelo menos por enquanto, rs)

Abraços
