### ISSUE TITLE
Danfe.Nativo.Nfce.Imprimir saindo em branco

### ISSUE THREAD

**Issue by ffranzes** [ZeusAutomacao/DFe.NET#791]
Pessoal ta tudo certo com o processo de impressão do NFCe na impressão nativa?
estou com um xml 4.0 que estou carregando e passando para a função que esta me retornando um pdf em branco e na impressora não sai nada...
o que eu posso estar errando ?

Dim danfev = New NFe.Danfe.Nativo.NFCe.DanfeNativoNfce(nfeProc.ObterXmlString, _configuracaoDanfe.ConfiguracaoDanfeNfce, _configuracao.ConfiguracaoCsc.CIdToken.ToString, _configuracao.ConfiguracaoCsc.Csc.ToString, 0, 180, "Ubuntu Condensed")

danfev.Imprimir(Impressora, diretorio & arqNome.Replace(".xml", ".pdf"))

outra duvida os valores de troco e totalpago se não forem enviados como a impressão trata isso ?

**Comment by robertorp** [comment]
poste o xml para nós analisar

**Comment by ffranzes** [comment]
[5255-2-638 33180601370875000229650010000006381000052557-procNfe.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2149209/5255-2-638.33180601370875000229650010000006381000052557-procNfe.pdf)

[5255-2-638 33180601370875000229650010000006381000052557-procNfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2149211/5255-2-638.33180601370875000229650010000006381000052557-procNfe.zip)

Detalhe, imprimiu pelo FastReport, mas no nativo não esta indo

**Comment by ffranzes** [comment]
@robertorp postei nesse arquivo .zip ai, conseguiu pegar ai ?

**Comment by ffranzes** [comment]
Fiz 3 coisas que resolveram o problema:
1-Mudei as configurações para a fonte UbuntuCondensed, 
2-Reinstalei a fonte, 
3-A instrução seguinte a gerar a NFCe era envia-la por e-mail, então coloque um sleep entre as duas funcoes!
