### ISSUE TITLE
Correção em NFe.Classes de campos opcionais

### ISSUE THREAD

**Issue by scalarerp** [ZeusAutomacao/DFe.NET#792]
Migrei toda minha aplicação para o Zeus Df-e, agradeço o trabalho de todos e estou diponivel para ajudar.

Na minha aplicação encontrei estes campos que podem ser nulos e nas classes estão como obrigatórios, consequentemente está dando erro ao validar, gostaria que isso fosse corrigido por favor.

Alterações estão aqui : https://gist.github.com/scalarerp/6c482a5ee568f83175db47d9fe5d52d0

Agradeço desde já.

**Comment by robertorp** [comment]
Vou analisar, obrigado @scalarerp
