### ISSUE TITLE
Erro na Inutilização de NFCe no estado de PE em Homologação

### ISSUE THREAD

**Issue by srwil** [ZeusAutomacao/DFe.NET#795]
Quando realizo a operação de Inutilização da NFCe acontece um erro na deserialização do retorno:

` "Erro de validação de instância: '0' não é um valor válido para DFe.Classes.Entidades.Estado."`

Analisando o XML em anexo, pode se perceber que o cUF não se encontra, ocasionando problema na deserialização!

Na aplicação de teste o erro também ocorre!

[26180506800100019165001000002492000002492-inu.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2166500/26180506800100019165001000002492000002492-inu.txt)

**Comment by robertorp** [comment]
Uma pessoa reportou isso ontem, bom existem duas opções 
Uma nos alteramos o framework para suportar isso, mas de acordo com o manual sua sefaz esta incoerente. 

![image](https://user-images.githubusercontent.com/10251705/42329773-e3575504-8047-11e8-849e-ac0eb4fa1d5b.png)

Manual de Orientação Contribuinte v 6.00 - Minuta.pdf - página 50

A pessoa em questão disse que entrou em contato com a Sefaz de RS e hoje estava ajustado isso. 
Enfim... acho que vou colocar o campo como opcional para sanar esse erro da sefaz.

**Comment by uberlei** [comment]
Pode atualizar o nuget estou com esse problema tbm. Grato.

**Comment by robertorp** [comment]
vou atualizar o nuget hoje

**Comment by adeniltonbs** [comment]
Também ocorreu em SE, mas o problema é da SEFAZ. 
Os últimos pacotes de liberação de schemas, PL_009_V4_NT_2016_002_v1_60b para 4.0 e PL_008h2 para 3.1, que contém o arquivo leiauteInutNFe_*.xsd incluem o campo cUf para o tipo TRetInutNFe.
Além disso não encontrei nenhuma nota técnica que alterasse a tag de resposta retInutNFe e no manual  v6.0, conforme @robertorp  mencionou, o campo DR09 cUF - Código da UF que atendeu a solicitação é obrigatório.

**Comment by uberlei** [comment]
Boa noite @robertorp o nuget já foi atualizado? Grato.

**Comment by robertorp** [comment]
foi publicado agora, daqui alguns minutos ele aparece lá. 
E somente aguardar. Agora depende do próprio nuget uns 10 a 30 minutos imagino eu que já libera.

**Comment by uberlei** [comment]
Obrigado @robertorp  tudo ok agora.

**Comment by robertorp** [comment]
show!
