### ISSUE TITLE
Erro Seleção do Certificado

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#798]
Pessoal estou com problema na seleção de certificados no Windows 10, tenho um aplicação em C# e em clientes com maquinas Windows 10 ao clicar na opção que usa o método listar certificados a aplicação fecha, verifiquei antivirus, instalação de drivers e mesmo assim o problema persistiu, algum de vocês já passou por esse problema?

**Comment by orochasamuel** [comment]
Usa essa lib aqui e veja se resolve: https://github.com/samuelrochaoliveira/CertificateAgent.NET
Todas as máquinas em que uso são Win 7 ou Win 10.

**Comment by ThalisonSantos** [comment]
@samuelrochaoliveira peguei sua aplicação do link e testei em um dos pcs que estava ocorrendo esse problema e ele tbm fechou

**Comment by orochasamuel** [comment]
Qual a versão do seu framework?

Acontece com um certificado específico?

Na sua máquina funciona? Qual a versão do seu Windows?

Manda um GIF da ocorrência.

Tenta reinstalar o certificado usando as propriedades extendidas. É modelo A1 ou A3?

**Comment by ThalisonSantos** [comment]
net.framework 4.6.2 , não é quando seleciona o certificado mas assim quando clica para listar os certificados, não apresenta erro só fecha a aplicação, o certificado é A3.
Na minha maquina funciona normalmente, tenho Windows 10 pro v1803.

**Comment by orochasamuel** [comment]
Veja se na máquina do cliente o certificado aparece como "operacional" no administrador de cartões

**Comment by ThalisonSantos** [comment]
em um dos pcs que apresentam esse erro é o certificado da Oberthur não sei se vc conhece que administrador do token ele não fica mostrando mas pelo software próprio da oberthur mostra normalmente e vc usa ele normalmente para qualquer operação

**Comment by orochasamuel** [comment]
Conheço. Estranho ele funcionar em outras áreas.. para confirmar, tenta acessar o eCac da Receita Federal com o certificado. Se não der certo o problema é nas cadeias de certificação raiz.

**Comment by ThalisonSantos** [comment]
eu testei e funcionou normalmente

**Comment by orochasamuel** [comment]
Eita...

**Comment by ThalisonSantos** [comment]
o certificado funciona normalmente é só quando vai listar os certificados ai a aplicação fecha, para funcionar eu tive que inserir o serial do certificado direto no banco

**Comment by orochasamuel** [comment]
Entendi.

**Comment by ThalisonSantos** [comment]
ai não sei como resolver

**Comment by robertorp** [comment]
pode ser algo no próprio sistema operacional, não? ja testou em outro ?

**Comment by ThalisonSantos** [comment]
o problema aconteceu em 2 empresas distintas a única coisa em comum que o sistema era o Windows 10, acredito que possa ser mas, difícil saber o que seria exatamente

**Comment by robertorp** [comment]
aqui temos mais de 600 empresas e não temos essas ocorrências
acho que isso e somente mal de alguma coisa nesses sistemas operacionais especificamente neles, bom só acho tirando por base "aqui na empresa"

**Comment by ThalisonSantos** [comment]
eu pesquisei esse problema no google e tinha o mesmo problema no fórum do acbr embora lá o problema era a instalação do certificado coisa que aqui já descartei pq o certificado esta funcional no site ecac

**Comment by ThalisonSantos** [comment]
@robertorp a tua aplicação é winforms ou asp.net?

**Comment by robertorp** [comment]
WPF, mas uso o Zeus DFe para manipulação de certificado digital.

**Comment by adrbarros** [comment]
Bom dia
Fiz um teste aqui, Pelo Zeus, pela Lib CertificadoAgent.Net e pelo meu código aqui, que é bem similar ao da Lib., e tem hora que funciona normal ai num determinado momento fecha a aplicação sem Exception sem nada

**Comment by ThalisonSantos** [comment]
@adrbarros exatamente o que acontece aqui

**Comment by adrbarros** [comment]
Bom fazendo algumas análises com uma ferramenta aqui (RadGate), pois aquele Diagnostic Tools do Visual Studio não apresentou Exceções.
Mas o RadGate mostrou um erro de renderização da Tela Padão (Windows) para Seleção do Certificado no sistema em Execução, assim fechando a aplicação, **depurando a aplicação funciona certinho**.
Assim utilizei o metodo ListOnlyValidCerticates da classe DigitalCertificateAgent, e criei minha própria tela para seleção de certificados

![img0001](https://user-images.githubusercontent.com/15065213/42570652-fc69deb6-84ea-11e8-9426-9b7bc8a2b3e3.png)
 
![img0002](https://user-images.githubusercontent.com/15065213/42570659-0417132c-84eb-11e8-8c77-9cf7e07189ff.png)

Essa foi a minha alternativa.
Só apresentou esse Bug no Windows 10, no Windows 7 estava funcionando normalmente

**Comment by ThalisonSantos** [comment]
@adrbarros sempre o Windows 10 tem esses problemas. mas valeu pelo retorno vou adaptar o meu tbm aqui

**Comment by ThalisonSantos** [comment]
@adrbarros mas aproveitando a ocasião, já aconteceu de o sistema não abrir no Windows 10 mas mostrar que esta em execução no gerenciador de tarefas?

**Comment by adrbarros** [comment]
Já sim. em alguns casos, mas nunca parei pra ver o que faz isso acontecer.

**Comment by ThalisonSantos** [comment]
@adrbarros  Blz, Obrigado pela ajuda!

**Comment by robertorp** [comment]
@ThalisonSantos quando der problema do sistema não abrir mas aparecer executando, tente em modo de compatibilidade, aqui não deu isso mas aconteceu de os icones do sistema ficar muito pequeno em alguns windows 7 abrimos em modo de compatibilidade e funcionou perfeito
