### ISSUE TITLE
Erro na serialização do retorno de Inutilização

### ISSUE THREAD

**Issue by reislanes** [ZeusAutomacao/DFe.NET#799]
Ao inutilizar uma faixa de numeração, o xml de retorno do webservice SVRS não está vindo com a TAG UF.

Ao tentar serializar o retorno, o seguinte erro é exibido:

> System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: Instance validation error: '0' is not a valid value for DFe.Classes.Entidades.Estado.
> 

Até ontem este erro não estava ocorrendo. Mas talvez fosse interessante deixar essa TAG como 
opcional.
O erro ocorre no trecho de código seguinte

> retorno = ServicoNFe.NfeInutilizacao(emitenteBD.CNPJ_CPF, ano, ModeloDocumento.NFCe, serie, numeroInicial, numeroFinal, Justificativa)
> 

Os erros aconteceram nas UFs PA e AP

**Comment by marcosgerene** [comment]
Você usa a biblioteca via nuget ou compila as dlls? Corrigi isso faz uns 2 dias.

https://github.com/ZeusAutomacao/DFe.NET/issues/795

https://github.com/ZeusAutomacao/DFe.NET/pull/797

**Comment by reislanes** [comment]
Nuget, na sexta ainda não estava disponível. Eu não tinha visto as outras issues, correria mesmo. Vou baixar as novas versões no Nuget hoje.

**Comment by robertorp** [comment]
Coloquei no nuget agorinha 
e está disponível para atualizar. 
![image](https://user-images.githubusercontent.com/10251705/42450823-d0a68b52-835b-11e8-8328-095c6a77c887.png)

**Comment by reislanes** [comment]
Valeu mesmo. Obrigado pessoal!

**Comment by robertorp** [comment]
@reislanes  deu certo?
