### ISSUE TITLE
Campo CEP

### ISSUE THREAD

**Issue by weslley39** [ZeusAutomacao/DFe.NET#8]
Quando estava populando a NFe, percebi que o campo CEP é um long, e que tenho é String, ao converter para int64 o cep, 07115011, vai para 7115011, sem o zero inicial, o que resulta em erro quando vai validar.

É necessário o campo CEP ser long ??

**Comment by adeniltonbs** [comment]
Resolvido no commit 798467e060c9beb8edbcf46d491e85176445c5c6.

**Comment by adeniltonbs** [comment]
This issue was moved to ZeusAutomacao/DFe.NET#8
