### ISSUE TITLE
Download da NFe

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#80]
Boa noite, tudo bem?

Conheci seu projeto através de um post do ACBr, não consegui entender muito bem a parte de download da NFe... pode me dar um exemplo prático de como eu posso pegar um objeto do tipo NFe partindo de uma chave?

Obrigado,
Marcos Gerene

**Comment by adeniltonbs** [comment]
Bom dia, desculpa a demora.
Na aplicação de demonstração que acompanha a biblioteca tem um exemplo do consumo do serviço Download NFe.

![image](https://cloud.githubusercontent.com/assets/6733483/11451811/90efffba-95b1-11e5-8f95-3a50472bb2f5.png)

**Comment by marcosgerene** [comment]
Boa noite Adenilton, tudo bem?

Infelizmente não consigo fazer abrir o layout do App teste acredito que seja por causa da parte de impressão que não instalei porque usa o fast report (e quando fui atrás do fast report vi que o mesmo era pago e não uso nenhum componente pago).

Porém já havia visto essa função via F3 buscando por download e nos screenshots que você postou, porém não consegui achar a informação que pedi de forma clara... porém consegui fazer isso compilar:

```
    public static NFe.Classes.NFe DownloadNFe(string chave)
    {
        var _config = NFe.Utils.ConfiguracaoServico.Instancia;
        _config.Certificado.Serial = "serial aqui"; //preenchi corretamente no sistema, so ocultei aqui
        _config.Certificado.Senha = "senha aqui"; //idem anterior

        var _serv = new ServicosNFe(_config);
        var _ret = _serv.NfeDownloadNf(Program.DadosEmpresa.Cnpj, new List<string>() { chave });
        var _nfe = new NFe.Classes.NFe().CarregarDeXmlString(_ret.RetornoCompletoStr);                      
        return _nfe;
    }
```

Porém na linha <strong>new ServicosNFe(_config); </strong> tenho uma excessão em <strong>CertificadoDigital.cs</strong> na funcão
<strong>ObterDoRepositorio(string numeroSerial, string senha = null)</strong>  na linha <strong>var rsaCsp = new RSACryptoServiceProvider(cspParameters);</strong>

![erro](https://cloud.githubusercontent.com/assets/15945003/11460190/7ddcd65e-96cf-11e5-844d-9ffd9a45972a.png)

PS: Estou usando um certificado A1, porém pretendo usar os 2 tipos no sistema.
PS2: Meu sistema é Desktop.

**Comment by adeniltonbs** [comment]
Marcos, bom dia. 
Se desejar compilar o projeto para poder testá-lo e entendê-lo melhor, baixe e instale o fast reports, pois a versão demo não possui prazo para expiração. Apenas coloca uma marca d'água na impressão.
Obs: o projeto atualmente deve compilar normalmente no Visual Studio 2013 e 2015.

**Comment by marcosgerene** [comment]
Bom dia Adenilton,

Vou fazer o que disse. Uso o VS community 2015...
Sobre esse erro do certificado pode me dizer aonde estou errando?

Vou tentar rodar hoje o Demo... obrigado pela atenção

**Comment by marcosgerene** [comment]
Boa noite Adenilton,

Uso o Visual Studio Community 2015

Tive o mesmo problema com o App de testes, tenho um certicado A1 instalado e ao tentar fazer o download a NF-e... e o mesmo problema ocorre ao tentar consultar o XML...

![adenilton](https://cloud.githubusercontent.com/assets/15945003/11486721/fc98557c-97a1-11e5-9baa-a78213eeaca8.png)

Carreguei o certificado pelo botãozinho [..] para garantir que puxei certinho mas não funcionou...

Eu registrei as DLLs da capicom por via das dúvidas (não sei a tecnologia usada nos certificados, ainda sou um pouco cru em c#) porém não resolveu.. para testar  o certificado fiz um download da NFe pelo site do Sefaz usando o certificado e deu certo (via Internet Explorer).

Será que preciso instalar mais algo?...peço um pouco de paciencia, estou saindo agora do Delphi, ja fiz toda aplicação, só falta a NFe e queria tentar seu componente antes de apelar pro ACBrmonitor..

Muito obrigado pela atenção,

Marcos Gerene

**Comment by adeniltonbs** [comment]
Ok, já descobri seu problema.
Não informe a senha se você selecionou o certificado A1 no repositório do Windows.

Para o tipo A1, a senha serve para os casos onde você informa o arquivo .pfx

Já para o tipo A3 e Token a senha é opcional. Caso você não informe ela, este será solicitada ao usuário a cada nova instância da aplicação, no primeiro uso apenas.

**Comment by adeniltonbs** [comment]
Assim que conseguir um certificado A3 vou tratar esse erro. 
Terei que ver a diferença do objeto "cspParameters" da classe CertificadoDigital, método ObterDoRepositorio(string numeroSerial, string senha = null), conforme [1] para o A1 e o A3 para poder identificar o tipo de certificado usado e se este aceita passar a senha.

Passando a senha para o A1, o problema vai ocorrer na linha [2], na classe CertificadoDigital, método ObterDoRepositorio(string numeroSerial, string senha = null).

[1]

``` cs
var cspParameters = new CspParameters(chavePrivada.CspKeyContainerInfo.ProviderType,
    chavePrivada.CspKeyContainerInfo.ProviderName,
    chavePrivada.CspKeyContainerInfo.KeyContainerName,
    null,
    senhaSegura);
```

[2]

``` cs
var rsaCsp = new RSACryptoServiceProvider(cspParameters);
```

Acredito que o A3 e o Token se comportam da mesma maneira.

**Comment by marcosgerene** [comment]
Bom dia, obrigado pela resposta...

Eu já havia tentado sem a senha com o meu certificado A1, tentei novamente agora na aplicação de testes e o retorno é esse:

![adenilton2](https://cloud.githubusercontent.com/assets/15945003/11501946/f638c75c-981e-11e5-958d-b340e40dc726.png)

Se quiser que eu faça algum teste específico agora consigo rodar qualquer parte da ferramenta e tenho certificado A1 em mãos e acho que consigo um A3 ainda hoje...

**Comment by adeniltonbs** [comment]
Verifique as referências, recompile a solução e certifique-se que a dll NFe.Wsdl.dll foi gerada no diretório de saída da aplicação NFe.AppTeste

Note que "NFe.Wsdl" é uma biblioteca integrante da solução.

**Comment by marcosgerene** [comment]
Boa noite Adenilton,

Deu certo no programa de testes, no meu ainda não mas agora acredito que seja questão de ajustes.

Muito obrigado,

Marcos Gerene
