### ISSUE TITLE
Recuperar nome do arquivo XML gerado no eventos da NFe

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#803]
Olá pessoal, td bem?

Estive analisando o método NFe.Servicos.ServicosNFe.RecepcaoEvento() o qual é responsável por emitir os eventos vinculados a NFe (cancelamento, carta de correção, manifestação, etc...) e não encontrei nenhum lugar onde eu possa recuperar o nome completo (caminho + nome do arquivo) do arquivo XML que foi gerado neste evento.

Por exemplo, emiti uma Carta de Correção para uma determinada NFe, e o Zeus me gerou o seguinte arquivo:

> 1101103518070160724600019955001000001004100001234104-procEventoNFe.xml

Existe alguma forma de obter o nome completo deste arquivo gerado (caminho + nome) logo após cada evento, para que eu possa salvar este arquivo no meu BD? 

Como vcs estão resolvendo isso hoje?

Explico o motivo: hoje no meu sistema, na tabela interna de NotaFiscal, tenho um campo chamado "CaminhoAtualXML", o qual contém a nome completo do arquivo XML gerado pelo ultimo evento daquela NFe em questão.

Abraços

**Comment by apbertoletti** [comment]
Ah... outra coisa...

Caso realmente não exista hoje esta possibilidade, será que eu poderia implementar isso no Zeus?

Pensei em fazer isso através de uma propriedade "ArquivoXMLGerado" na própria classe NFe.Classes.Servicos.Consulta.procEventoNFe(), a qual iria conter o caminho onde o arquivo XML do evento em questão foi criado.

Claro que eu decoraria esta nova propriedade com [XmlIgnore], para não influenciar na serialização desta classe.

O que vocês acham desta abordagem?

**Comment by marcosgerene** [comment]
```
using (servicoNFe = new NFe.Servicos.ServicosNFe(ZeusConfig))
{
	var retornoCancelamento = servicoNFe.RecepcaoEventoCancelamento(
			idlote: 1,
			sequenciaEvento: 1,
			protocoloAutorizacao: nfeproc.protNFe.infProt.nProt,
			chaveNFe: gnfe.ChaveAcesso,
			justificativa: xJustificativa,
			cpfcnpj: Globals.DadosEmpresa.Cnpj);

	var retEvento = retornoCancelamento.Retorno.retEvento.FindAll(ev => ev.infEvento.tpEvento == Convert.ToInt32(TipoEventoNFe.Cancelamento)).OrderByDescending(ev => ev.infEvento.nSeqEvento).FirstOrDefault();
	resposta = retEvento.infEvento.xMotivo;
	var procEvento = retornoCancelamento.ProcEventosNFe.FindAll(tp => tp.evento.infEvento.tpEvento == Convert.ToInt32(TipoEventoNFe.Cancelamento)).FirstOrDefault();
	if (new List<int> { 101, 135, 151, 155 }.Contains(retEvento.infEvento.cStat))
	{
		using (var conexao = new Conexao())
		{
			var evento = new NFeEvento();
			evento.ChaveNFe = gnfe.ChaveAcesso;
			evento.ChaveEvento = procEvento.evento.infEvento.Id.OnlyNumber();
			evento.DataHora = procEvento.evento.infEvento.dhEvento;
			evento.Tipo = TipoEventoNFe.Cancelamento;
			evento.Motivo = xJustificativa;
			new NFeEventoDAL(conexao).Save(evento);

			string pathEvento = GArquivos.CombinarDiretorio(ZeusConfig.DiretorioSalvarXml, $"{evento.ChaveEvento}-eve.xml");
			DFe.Utils.FuncoesXml.ClasseParaArquivoXml(retornoCancelamento.Retorno.retEvento, pathEvento);
			DFe.Utils.FuncoesXml.ClasseParaArquivoXml(procEvento, pathEvento);
			new NFeXMLDAL(conexao).Save(evento.ChaveEvento, GArquivos.Xml2String(pathEvento));
			new NFeDAL(conexao).Cancelar(gnfe);
		}
	}
}






    public enum TipoEventoNFe
    {
        [Description("Cancelamento")] Cancelamento = 110111,
        [Description("Carta de Correção")] CCe = 110110,
        [Description("Encerramento")] EncerramentoMDFe = 110112,
        [Description("EPEC")] EPEC = 110140,
        [Description("Confirmação da Operação")] ConfirmacaoOperacao = 210200,
        [Description("Ciência da Emissão")] CienciaEmissao = 210210,
        [Description("Desconhecimento da Operação")] DesconhecimentoOperacao = 210220,
        [Description("Operação não Realizada")] OperacaoNaoRealizada = 210240
    }
```

**Comment by apbertoletti** [comment]
Obrigado pelo feedback @marcosgerene ,

Duas duvidas:

1) Este é o código que vc utiliza dentro do seu sistema para invocar os eventos da NFe através do Zeus, confere?

2) Neste caso é você quem determina onde o arquivo XML do evento será salvo, e não o Zeus, confere?

Obrigado

**Comment by robertorp** [comment]
Algo que pensei em fazer são eventos @apbertoletti 
Fazer eventos para retornar dados antes de enviar o xml para a sefaz
antes de validar por schemas 
e depois do envio 

ai basta escolher o melhor evento que convêm a seu cenário e usar 

isso e algo que uma hora vou colocar no Zeus. 
Se quiser colocar fique a vontade. Ele segue o padrão da Sefaz para nomear os arquivos. 

o path do arquivo onde ele esta sendo salvo você define nas configurações, depois basta seguir o padrão de nomeação da sefaz e concatenar. 

Mas fique uma ideia de como pode ser implementado uma alternativa com os eventos.

**Comment by apbertoletti** [comment]
Gostei da ideia @robertorp ,

Mas confesso que sou bem inexperiente com eventos para poder implementa-lo num projeto importante como o Zeus. 

A abordagem que sugeri foi a que tenho mais segurança nos resultados.

Mas se quiser subir um exemplo de como resolver isso via eventos, posso estudar e ir implementando nas demais chamadas.

Abraços

**Comment by marcosgerene** [comment]
@apbertoletti 

>Obrigado pelo feedback @marcosgerene ,
>
>Duas duvidas:
>
>1. Este é o código que vc utiliza dentro do seu sistema para invocar os eventos da NFe através do Zeus, confere?
>
>2. Neste caso é você quem determina onde o arquivo XML do evento será salvo, e não o Zeus, confere?
>
>Obrigado

1 e 2. Sim.

Eu salvo meus xmls no banco de dados.

**Comment by apbertoletti** [comment]
> Pensei em fazer isso através de uma propriedade "ArquivoXMLGerado" na própria classe NFe.Classes.Servicos.Consulta.procEventoNFe(), a qual iria conter o caminho onde o arquivo XML do evento em questão foi criado.
> Claro que eu decoraria esta nova propriedade com [XmlIgnore], para não influenciar na serialização desta classe.

Pessoal, por questões de prazo, Implementei esta abordagem acima mesmo. 

Posso libera-la pra comunidade?
