### ISSUE TITLE
NFSe, alguém tem implementação de Nota Fiscal Serviço Eletrônica ?

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#804]
Olá, há alguém que tenha implementação de NFSe em conjunto com o DFe.NET ?
Ou sugestão de algum projeto para que possamos trabalhar e implementar no projeto DFe.NET.

**Comment by marcosgerene** [comment]
https://github.com/ACBrNet/ACBr.Net.NFSe
