### ISSUE TITLE
NFE 4.0 PR retornando cStat  = 878

### ISSUE THREAD

**Issue by devfabricioalmeida** [ZeusAutomacao/DFe.NET#805]
Bom dia, Pessoal!
Estou com problemas para realizar o envio de NFC-e no estado do parana, esta me retornando esse xml abaixo.
<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>PR-v4_1_5</verAplic><cStat>878</cStat><xMotivo>Endereco do site da UF da Consulta por chave de acesso diverge do previsto. [URL correta:http://www.fazenda.pr.gov.br]</xMotivo><cUF>41</cUF><dhRecbto>2018-07-17T10:47:40-03:00</dhRecbto></retEnviNFe>

**Comment by robertorp** [comment]
manda print do erro
manda o xml de envio gerado também para podermos analisar melhor

**Comment by robertorp** [comment]
tudo bom @devfabricioalmeida  conseguiu resolver?
se sim poderia postar a solução

**Comment by devfabricioalmeida** [comment]
Desculpem a minha demora para responder!
Eu estava passando na função ObterUrl  sempre  TipoUrlConsultaPublica.UrlQrCode ai mudei para   TipoUrlConsultaPublica.UrlConsulta. 
Depois que fiz isso funcionou, agradeço pela ajuda!
![image](https://user-images.githubusercontent.com/40633672/43536756-c8cf59e6-9593-11e8-9799-5d3258fc815b.png)
