### ISSUE TITLE
[DUVIDA] Como corrigido a Rejeição "Campos do grupo Fatura não informados"

### ISSUE THREAD

**Issue by FabioHenriqueMF** [ZeusAutomacao/DFe.NET#806]
Boa tarde como estão corrigindo esta rejeição.
Conforme a NT 1.60 esta rejeição em PRODUÇÃO será a partir de 03/09/2018. Porém em HOMOLOGAÇÃO já está sendo validada.

Pelo que entendi a tag **vDesc** do grupo **fat** deve ser levada mesmo com valor zerado.
Então na função **ShouldSerializevDesc** deve gerar para HOMOLOGAÇÃO a tag mesmo que zerada e em PRODUÇÃO deve ser gerada mesmo que zerada a partir de 03/09???
Como fazer?

**Comment by gubarusco** [comment]
Pelo que vi em produção ainda está a versão 1.50.
Se você precisar rodar os 2, eu sugiro crias pastas separadas para as versões 1.50 e 1.60, então conforme o ambiente apontar para cada um deles.

**Comment by apbertoletti** [comment]
> Porém em HOMOLOGAÇÃO já está sendo validada.

É isso mesmo @FabioHenriqueMF , a SEFAZ já está validando isso no ambiente de homologação... 

Para auxiliar neste processo, atualize também o pacote de Esquemas XML para o mais recente (PL_009_V4_NT_2016_002_v1_60b), disponível na portal da NFe. 

![7-18-2018 11-26-49 am](https://user-images.githubusercontent.com/6843493/42915756-26bc555c-8ad8-11e8-9023-03a0d22d0018.png)

**Comment by jeisonperes** [comment]
Bom dia pessoal,
pelo que vi a NT 1.60 entrará em PRODUÇÃO dia 23/07/2018. Já a rejeição será a partir de 03/09/2018.
Então eu acho que a partir de 23/07/2018 já dá para enviar a tag vDesc do grupo fat com valor zerado.
O que vocês acham?

![image](https://user-images.githubusercontent.com/40441623/42940285-47099db8-8b2f-11e8-9383-461f8e4f8861.png)

![image](https://user-images.githubusercontent.com/40441623/42940450-e128f09c-8b2f-11e8-8c96-3ca0a0a67b4e.png)

**Comment by apbertoletti** [comment]
Exato, no ambiente de PRODUÇÃO será esta data mesmo. Mas em HOMOLOGAÇÃO já está valendo.

Por isso, pra conseguir fazer meus testes de emissão de NF aqui no sistema, tive que colocar um condicional verificando quando o sistema deveria alimentar esta tag ou não. 

![code01](https://user-images.githubusercontent.com/6843493/42942428-3c203b08-8b36-11e8-8b84-994a98358ade.png)

![code02](https://user-images.githubusercontent.com/6843493/42942434-3fac1260-8b36-11e8-9861-b5d14b43a959.png)

**Comment by ThalisonSantos** [comment]
Boa tarde pessoal. Aproveitando o assunto a tag dup não vai ser preciso informar na 4.0?

**Comment by apbertoletti** [comment]
Olá @ThalisonSantos ,

que eu saiba a obrigatoriedade deste grupo de tags dup continua a mesma.

Apenas atente-se a tag nDup, que deverá passar a seguir uma máscara padrão de formatação (999), ou seja, 001, 002, 003, etc...

![7-23-2018 2-54-05 pm](https://user-images.githubusercontent.com/6843493/43094141-817d06d6-8e88-11e8-99fc-99aa8c824837.png)

**Comment by ThalisonSantos** [comment]
@apbertoletti  e o fat qual a finalidade dele?

**Comment by apbertoletti** [comment]
Fatura e Duplicata são conceitos diferentes, cada um tem seu objetivo.

- Fatura: é o valor financeiro total que aquela operação gerou.
- Duplicata: são a(s) parcela(s) geradas para pagamento daquele total financeiro.

**Comment by ThalisonSantos** [comment]
@apbertoletti  obrigado pelo esclarecimento!!

**Comment by robertorp** [comment]
Lembrando que, no zeus vDesc continuará opcional pois a vera muitos casos de nf-e com versões anteriores.

**Comment by apbertoletti** [comment]
Segue o exemplo de como ficariam as tags, para uma venda que totalizou em R$ 160,00 e o cliente decidiu pagar 60,00 em dinheiro e o restante no boleto.

![8-1-2018 2-43-18 pm](https://user-images.githubusercontent.com/6843493/43538843-82f90cae-9599-11e8-8bd2-a128f5fcb595.png)

**Comment by ThalisonSantos** [comment]
@apbertoletti  o valor do dup tem que ser igual ao do fat? ou eu posso informar somente o valor dos a prazos no dup?

**Comment by apbertoletti** [comment]
> o valor do dup tem que ser igual ao do fat? 

Não necessariamente, neste exemplo que citei ficaram iguais pois simulei uma venda a vista, ou seja, a Fatura (fat) gerou apenas 1 parcela (dup), a qual por sua vez, foi paga pelo cliente utilizando duas formas formas de pagamento distintas (pag).

Sacou?

**Comment by ThalisonSantos** [comment]
@apbertoletti  entendi valeu pelo esclarecimento

**Comment by apbertoletti** [comment]
@rodrigordi vc estão enviando todas as tags () preenchidas com valor, conforme exige esta regra de validação na Nota Técnica da SEFAZ?

![9-3-2018 10-50-21 am](https://user-images.githubusercontent.com/6843493/44990467-79843580-af67-11e8-8cc1-7e4acac0f8a8.jpg)

Vale lembrar que em homologação, esta regra validação estava ativa já faz um tempo.

**Comment by alexjralves** [comment]
Estou com o mesmo problema, mesmo enviando vDesc como 0,00, volta a rejeição:

Erros na validação: The 'http://www.portalfiscal.inf.br/nfe:vDesc' element is invalid - The value '0.00' is invalid according to its datatype 'http://www.portalfiscal.inf.br/nfe:TDec_1302Opc' - The Pattern constraint failed.

![image](https://user-images.githubusercontent.com/4020919/44990795-95d4a200-af68-11e8-9f99-d6e0b52b7fce.png)

**Comment by marcosgerene** [comment]
>Estou com o mesmo problema, mesmo enviando vDesc como 0,00, volta a rejeição:
>
>Erros na validação: The 'http://www.portalfiscal.inf.br/nfe:vDesc' element is invalid - The value '0.00' is invalid according to its datatype 'http://www.portalfiscal.inf.br/nfe:TDec_1302Opc' - The Pattern constraint failed.

Isso é porque o schemas está desatualizado.

Solto um PR em 10 minutos, teste com ele.

**Comment by rodrigordi** [comment]
@apbertoletti a gente não informa a tag 'cobr'

**Comment by rodrigordi** [comment]
@marcosgerene se campo for 0.00 não enviar a tag. correto ?

**Comment by marcosgerene** [comment]
Na NFe 4.00 o vampo vDesc deve ser informado mesmo com o valor 0.

Respondendo sua pergunta, ele só "oculta a tag" quando o valor dela é null e não quando é zero. E esta tag deve ser preenchida.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/863

**Comment by marcosgerene** [comment]
@cleciobarbosa, @rodrigordi e @alexjralves 
Teste com essa PR: https://github.com/ZeusAutomacao/DFe.NET/pull/863  (é só atualização de Schemas)
____

Uma dica: abra uma nova issue caso a issue original esteja fechada, não "ressucite um tópico".

**Comment by alexjralves** [comment]
@marcosgerene, funcionou removendo a tag cobr quando não existe duplicadas / faturas.

**Comment by marcosgerene** [comment]
@alexjralves 

>@marcosgerene, funcionou removendo a tag cobr quando não existe duplicadas / faturas.

O problema é que sem o schemas atualizado nem preenchendo os 2 funciona.

**Comment by rodrigordi** [comment]
@marcosgerene isso mesmo. vDesc deve ser informada mesmo que tenha valor 0.00.

**Comment by andersonpda** [comment]
Boa tarde, estou tendo mesmo problema, passo como 0 e simplesmente da erro:

> Erros na validação: The 'http://www.portalfiscal.inf.br/nfe:vDesc' element is invalid - The value '0.00' is invalid according to its datatype 'http://www.portalfiscal.inf.br/nfe:TDec_1302Opc' - The Pattern constraint failed.

**Comment by apbertoletti** [comment]
Manda o XML aqui pra darmos uma olhada.

(Renomeie ele pra TXT antes)

**Comment by andersonpda** [comment]
Problema resolvido, era apenas data da duplicata menor que a data da emissão da NF, porém só achei estranho dar erro no Desconto.
