### ISSUE TITLE
Rejeicao: Emissor nao habilitado para emissao da NF-e

### ISSUE THREAD

**Issue by DEV-WEVERSON** [ZeusAutomacao/DFe.NET#808]
Opa blz! estou migrando da v3.10 para v4.00 quando coloquei a versão atualizada paro de funcionar, antes de atualizar estava funcionando na V3.10, uso no estado de Goias.

já funcionava e esta habilitado.

XML [52180728236999000191650040000000051000000053.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2213963/52180728236999000191650040000000051000000053.zip)

![erro nfce](https://user-images.githubusercontent.com/8822589/43003504-2135562a-8c03-11e8-83b1-de86c13075be.png)

**Comment by apbertoletti** [comment]
Olá @DEV-WEVERSON ,

Me explica exatamente como vc fez para colocar a versão mais atualizada do Zeus ai.

**Comment by DEV-WEVERSON** [comment]
Eu apaguei as dll antigas e coloquei as novas que baixei do https://github.com/ZeusAutomacao/DFe.NET
coloque as funcionalidades que foram mudadas no AppTeste.exe (MainWindow).

**Comment by apbertoletti** [comment]
Certo, me parece tudo ok com seu processo.

Mas pelo código deste erro que você printou (203), desconfio que o problema esteja na relação entre o emitente (empresa) que você está usando e a SEFAZ da UF em questão.

Veja algumas dicas sobre este erro aqui:
https://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-203-emitente-n%C3%A3o-habilitado-para-emiss%C3%A3o-de-nf-e-como-resolver-99.html

**Comment by DEV-WEVERSON** [comment]
Tinha visto isso, mais eu tenho a versão antiga  e esta fusionando corretamente.

**Comment by apbertoletti** [comment]
Abri seu XML aqui pra analisar.

Trata-se então de uma NFC-e (modelo 65) e não NFe (modelo 55), confere?

OBS: Sugiro que corrija o titulo desta issue, visto que são documentos fiscais diferentes.

**Comment by DEV-WEVERSON** [comment]
Isso mesmo e NFC-e (modelo 65).

**Comment by apbertoletti** [comment]
Tem um print do desta NFC-e funcionando corretamente na versão anterior?

**Comment by DEV-WEVERSON** [comment]
Sim tenho!

**Comment by apbertoletti** [comment]
Se puder emitir um NFC-e com a versão anterior neste momento, e printar o resultado aqui pra gente.

**Comment by DEV-WEVERSON** [comment]
![123](https://user-images.githubusercontent.com/8822589/43031735-f63212e4-8c7d-11e8-8961-6300905324f4.jpeg)

**Comment by DEV-WEVERSON** [comment]
[52180729126781000147650010000020001000020003-procNfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2215854/52180729126781000147650010000020001000020003-procNfe.zip)

**Comment by apbertoletti** [comment]
> 52180729126781000147650010000020001000020003-procNfe.zip

Mas este é um emitente diferente do primeiro que deu o erro 203

Faça o mesmo teste com o emitente "28236999000191 - PETTINE E SILVA ALIMENTOS LTDA - ME", e print o resultado e XML por aqui.

**Comment by DEV-WEVERSON** [comment]
![123](https://user-images.githubusercontent.com/8822589/43032395-297c9fa8-8c8c-11e8-825b-100b27b5018f.jpeg)

[52180728236999000191650040000000061000000069-procNfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2215915/52180728236999000191650040000000061000000069-procNfe.zip)

**Comment by apbertoletti** [comment]
Misterioso este caso hein @DEV-WEVERSON ,

Mas olha só, resolvi validar aquele primeiro XML que enviou (o qual está dando o erro 203), usando o próprio validador da SEFAZ-SP (www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/GeraQRCode.aspx). Com isso, eu quis descartar a hipótese de falha no schema gerado pelo Zeus, e adivinha? Validou tudo certo, sem erro algum, veja:

![7-21-2018 5-40-42 pm](https://user-images.githubusercontent.com/6843493/43039912-a1e19cd8-8d0d-11e8-85db-e4ca51ce83eb.png)

Sendo assim, a hipótese mais provável que vejo neste caso, é algum problema direto ente este emitente e a SEFAZ-GO. Ainda mais que achei mais gente reclamando disso, veja só: https://www.projetoacbr.com.br/forum/topic/34302-erro-203-porem-emissor-encontra-se-habilitado/

Enfim, recomendo que o seu emitente (ou você mesmo), entre em contato com a SEFAZ-GO para explicar a situação, e validar esta nova hipótese que estou supondo agora.

Depois dá um feedback aqui pra gente do andamento deste caso.

Abraços

**Comment by DEV-WEVERSON** [comment]
Concordo com você @apbertoletti,

Graça a você a validação foi resolvida. muito obrigado!

Agora falta o retorno **protocolo de autorização**!

Esta validando e esta retornando o **protocolo de autorização** nesta Versão v3.10.

As dll do DFe.NET da v3.10 que esta funcionado na:
Versão do assembly:   1.0.0.457
Versão do arquivo:      1.0.0.457

Esta validando só não esta retornando o **protocolo de autorização** nesta nova atualização 
tanto na v3.10 e v4.00.

As dll do DFe.NET da v3.10 e v4.00 não esta funcionado o retorno na:
Versão do assembly:   1.0.0.687
Versão do arquivo:      1.0.0.687

Retorno: Rejeição 217: NF-e não consta na base de dados da SEFAZ


Se poder de uma olha!

**Comment by apbertoletti** [comment]
Você baixa o Zeus via Nuget?

Como você está consumindo as DLLs ai?

Pergunto isso, pois a versão estável mais recente liberada lá não bate com a sua.

![7-22-2018 10-14-52 am](https://user-images.githubusercontent.com/6843493/43045962-32a48ae8-8d98-11e8-8edc-950508d69ad0.png)

**Comment by DEV-WEVERSON** [comment]
**Você baixa o Zeus via Nuget?** 
não, eu estou usando a que esta aqui no github.

**Como você está consumindo as DLLs ai?**
Importando as que baixei do github que esta nesta Versão
Versão do assembly: 1.0.0.687
Versão do arquivo: 1.0.0.687

Sempre baixei por aqui no github, nunca tive problema; so agora esta...

**Comment by apbertoletti** [comment]
Por favor, configure este emitente no projeto de NFe.AppTeste do Zeus, e tente emitir uma NFCe de testes por lá. Nesta mesma UF que está dando o problema.

Depois, printe os resultados aqui pra gente avaliar.

**Comment by DEV-WEVERSON** [comment]
@apbertoletti fiz como você me pediu mais esta dando o mesmo erro.

![erro nfce new](https://user-images.githubusercontent.com/8822589/43091052-83bfed54-8e7f-11e8-8eb6-1a4be26b5c7d.png)

![erro nfce new1](https://user-images.githubusercontent.com/8822589/43091053-83e0eb44-8e7f-11e8-99ea-6978a4bdb46a.png)

**Comment by apbertoletti** [comment]
Faça um outro teste, ainda no NFe.AppTeste.

Tente fazer a mesma emissão, porém no ambiente de homologação da SEFAZ-GO.

Compacte todos os XMLs gerados por esta emissão, e envie por aqui tb.

**Comment by DEV-WEVERSON** [comment]
Emissão no ambiente de homologação da SEFAZ-GO.

Compactados todos os XMLs gerados por esta emissão.

[52180728236999000191650010000000011000012347.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2220567/52180728236999000191650010000000011000012347.zip)

**Comment by DEV-WEVERSON** [comment]
Emissão no ambiente de homologação da SEFAZ-GO e Compactado todos os XMLs gerados.

[52180728236999000191650010000000011000012347.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2220572/52180728236999000191650010000000011000012347.zip)

**Comment by apbertoletti** [comment]
Tem como vc me enviar também os XMLs gerados no ambiente de produção da SEFAZ-GO?

**Comment by DEV-WEVERSON** [comment]
Emissão no ambiente de produção da SEFAZ-GO e Compactado todos os XMLs gerados.

[52180728236999000191650010008452131000012348.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2220649/52180728236999000191650010008452131000012348.zip)

**Comment by apbertoletti** [comment]
@DEV-WEVERSON ,

Fiz todas as analises necessárias, mas realmente não enxerguei problema algum no lado do Zeus... talvez minha pouca experiencia com NFCe tenha prejudicado esta análise (meu foco é mais NFe).

De qualquer forma, sugiro fortemente que você entre em contato com a SEFAZ-GO para validar a hipótese de problema deste emitente por lá.

O site deles parece dar um suporte bem bacana sobre isso, podendo inclusive enviar os arquivos gerados para eles analisarem. Veja:

![7-23-2018 3-56-09 pm](https://user-images.githubusercontent.com/6843493/43097123-7d9a8d14-8e91-11e8-9b81-af38dd157998.png)

Sorte ai!

Depois posta aqui o final desta novela pra ficar de lição aprendida pra comunidade ;)

**Comment by DEV-WEVERSON** [comment]
Importando as DLL pelo nuget esta na mesma Versão do github que eu sitado anterior. 

![erro nfce new2](https://user-images.githubusercontent.com/8822589/43097265-e9cc5cb0-8e91-11e8-8332-8c6c722344c1.png)

**Comment by orochasamuel** [comment]
@DEV-WEVERSON 

Acabei de resolver um problema desse que aconteceu comigo, o cliente me passou o certificado recém emitido, empresa recém aberta e tal.

Não sei se vai ser o seu caso mas eu resolvi essa mensagem de erro em uma aplicação de terceiros corrigindo o TOKEN, quem cadastrou colocou o identificador (no caso "1") no lugar do código do token. Verifica essa informação.

Verifica também se o TOKEN que você está utilizando não foi revogado. Sabe olhar?

Olha se a empresa também está credenciada para emitir NF-e/NFC-e no site da SEFAZ.

EDIT: Resolvido?

**Comment by orochasamuel** [comment]
@DEV-WEVERSON 

Encontrei algo suspeito..

No arquivo que você enviou tentando emitir em homologação, o DV está "7".

![image](https://user-images.githubusercontent.com/15462690/43101841-c28fb9cc-8e9f-11e8-9dd0-39ed7c28a562.png)

Essa imagem que você mandou está consultando em ambiente de produção a nota com DV "7" que foi emitida em homologação. Confere essa informação?

![image](https://user-images.githubusercontent.com/15462690/43101859-d49cbf52-8e9f-11e8-966d-cf90f39c6504.png)

São números de notas diferentes.

**Comment by apbertoletti** [comment]
E aí @DEV-WEVERSON , teve algum avanço por ai?

**Comment by DEV-WEVERSON** [comment]
@apbertoletti  nada ate agora, já tentei mudar, mais sem sucesso.

**Comment by adeniltonbs** [comment]
@DEV-WEVERSON 
Boa tarde,
Essa resposta por parte da SEFAZ (203 - Emitente não habilitado para emissão de NF-e) indica que a empresa não está cadastrada como emissora de NF-e na SEFAZ.

As checagens que você deve fazer são:
- O CNPJ da empresa informada no XML é realmente de GO?
- Os dados do Certificado da empresa estão corretos? (pode ter ocorrido erro por parte da empresa que gravou o certificado);
- Você está enviando o XML para a mesma UF da empresa?
- O endereço do serviço para o qual a biblioteca está enviando o XML está correto?

Se as respostas a essas perguntas forem sim e o erro persistir, entre em contato com a SEFAZ.

Vi que vc mencionou que a empresa consegue emitir NFC-e na versão 3.1 e não consegue na 4.0.
Isso mostra que o problema não está na SEFAZ?
Não. Os serviços versão 3.1 e 4.0 possuem urls diferentes e nós não conhecemos a infraestrutura por trás disso. A SEFAZ pode, por exemplo, armazenar as coisas em bancos diferentes, fazer checagens diferentes etc.

Estou tentando emitir uma NFC-e, modelo 65, e recebo a rejeição 203(Emissor não autorizado para emissão de NF-e). Isso estão correto?
Não. Para NFC-e, modelo 65, caso o emissor não esteja habilitado pela SEFAZ, o correto seria a rejeição 781 (Emissor não autorizado para emissão de NFC-e), conforme o manual de orientação do contribuinte versão 6.0, página 272. Isso também deve ser reportado a SEFAZ.

**Comment by rodrigordi** [comment]
Não tem como debugar para qual URL está sendo enviado ? E se estiver indo para servidor de NFe ao inves de servidor de NFCe ?

**Comment by DEV-WEVERSON** [comment]
Boa Tarde a todos,

Irei fazer um vídeo com os testes de cada versão (3.1 / 4.0) e estarei postando aqui.

Muito obrigado a todos que estão me ajudando.
