### ISSUE TITLE
cEAN e cEANTrib e GTIN

### ISSUE THREAD

**Issue by rodrigordi** [ZeusAutomacao/DFe.NET#810]
Olá pessoal,
quem já está na versão 4.00, está informando o que nas tags cEAN e cEANTrib ?

**Comment by PedroWilliam** [comment]
Opa, @rodrigordi 
se o produto não contém o EAN estou informando com o literal 'SEM GTIN'
conforme [Nota Técnica 2017.001 v.1.00](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=T7PfUOHhMD4=)

![image](https://user-images.githubusercontent.com/7660513/43110991-54276932-8ec5-11e8-8468-de185aa0595f.png)

**Comment by rodrigordi** [comment]
Oi @PedroWilliam até ontem estava funcionando com o campo vazio na SEFAZ SP em Produção. Agora rejeição 889. Essa NT tem uma versão 1.30 e nela as datas de implementação estão diferentes.

**Comment by robertorp** [comment]
aqui valido o código de barras também por garantia, se codigo de barras for considerado inválido
coloco SEM GTIN
