### ISSUE TITLE
Arquivos de classes sumiram de alguns projetos

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#811]
Pessoal, td bem?

Notei que depois do ultimo merge que fiz com o repositório principal do Zeus, os arquivos das classes de alguns projetos sumiram do Solution Explorer. 

![7-24-2018 11-42-27 am](https://user-images.githubusercontent.com/6843493/43146240-33005f1c-8f37-11e8-8459-dd740368d943.png)

Saberiam me dizer por que?

Estou tendo alguns problemas em produção e desconfio que seja por isso.

**Comment by apbertoletti** [comment]
@robertorp 

Grato, se puder dar uma força ai.

**Comment by rftd** [comment]
Elas foram para o projeto Shared abaixo, projeto shared é usado quando é preciso compilar a dll em mais de um framework usando uma mesma base.

**Comment by apbertoletti** [comment]
Obrigado @rftd , agora achei eles aqui.

Mas uma duvida: a qual dos projetos eu devo fazer minhas referencias agora? Ao shared project?

Pergunto isso pois estou tendo este bug abaixo depois que coloquei o Zeus em produção aqui;

![7-24-2018 10-55-11 am](https://user-images.githubusercontent.com/6843493/43160020-5ea2628c-8f5a-11e8-9bae-2362c6ff3d67.png)

Detalhe, este problema só acontece em algumas máquinas Windows 10. Em outras com Windows 7, funciona perfeitamente.

Alguma pista ?

**Comment by apbertoletti** [comment]
@adeniltonbs , vcs que utilizam os projetos Zeus dentro da mesma Solution do sistema de vcs, já tiveram algum problema depois dos shared projects?

Algum cuidado que recomenda ter depois disso?

**Comment by orochasamuel** [comment]
@apbertoletti o Adenilton já citou em outra issue que não compila o Zeus no Main Project, mas separadamente. Posso estar equivocado mas tenho quase certeza de já ter lido isso.

**Comment by apbertoletti** [comment]
@samuelrochaoliveira , vc está falando desta issue #15 ?

Se for, veja só na thread abaixo que eles compilam os projetos Zeus dentro da Solution deles sim.

https://github.com/ZeusAutomacao/DFe.NET/issues/15#issuecomment-397414770

**Comment by orochasamuel** [comment]
Hummm era essa msm.

**Comment by robertorp** [comment]
Aqui uso nuget. 
Sobre o projeto, lentamente aos poucos vou passar tudo para shared. Para ter .net core
compartilhar entre os dois frameworks como o próprio @rftd  mencionou.

**Comment by apbertoletti** [comment]
Conseguimos resolver problema do "Método não encontrado" por aqui...

Na verdade o nosso source control aqui se perdeu na hora de pegar a ultima versão das DLLs do Zeus e acabou enviando versões antigas. 

Pra garantir, também fizemos uma busca e limpeza na máquina do cliente, de todas as versões das DLLs Zeus que estavam instaladas por lá, de outros testes que estavam realizando. 

Depois destes dois ajustes, a coisa se estabilizou por aqui.

Obrigado pelo feedback pessoal.
