### ISSUE TITLE
Problema ao manifestar conhecimento da operação

### ISSUE THREAD

**Issue by gubarusco** [ZeusAutomacao/DFe.NET#812]
Olá pessoal!

Hoje começou a ocorrer um problema ao tentar manifestar ciência da operação em SP. Está retornando a msg 2261 - Falha ao acessar banco de dados. Pesquisei e vi que isso é problema interno do sefaz e só nos resta esperar.
Alguém mais está tendo esse problema?

Abraços
Gustavo

**Comment by robertorp** [comment]
Será que isso não e algum erro na própria Sefaz não?

**Comment by robertorp** [comment]
conseguiu?

**Comment by gubarusco** [comment]
Voltou a funcionar sozinho. Era problema no Sefaz mesmo.
Perguntei aqui se alguém também estava tendo problema só para confirmar.

Obrigado

**Comment by robertorp** [comment]
Ótimo, perfeito.
Qualquer coisa manda perguntas ai, no que podermos ajudar sempre estaremos ajudando.
