### ISSUE TITLE
Modalidade de Frete sem transporte 5 para 9 igual NF-e

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#814]
No Zeus ainda esta como Modalidade de Frete sem transporte 5. 
A NF-e e 9 

namespace NFe.Classes.Informacoes.Transporte
{
    public enum ModalidadeFrete
    {
        mfContaEmitenteOumfContaRemetente = 0,
        mfContaDestinatario = 1,
        mfContaTerceiros = 2,
        mfProprioContaRemente = 3,
        mfProprioContaDestinatario = 4,
        mfSemFrete = 5
    }
}

Será que rola deixar igual a NF-e?

**Comment by apbertoletti** [comment]
Olá @fabiociaf 

Já teve um issue sobre isso aqui... veja este #728 e este outro #561 

Mas resumindo: infelizmente não terá como mexer nisso agora, o jeito será vc fazer um condicional no seu código. Veja como fizemos por aqui:

![7-26-2018 4-38-29 pm](https://user-images.githubusercontent.com/6843493/43284662-e9461638-90f2-11e8-988d-c6e27a923961.png)

![7-26-2018 4-39-30 pm](https://user-images.githubusercontent.com/6843493/43284668-ef8a72f0-90f2-11e8-91be-cdf5c57b27c2.png)
