### ISSUE TITLE
Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA

### ISSUE THREAD

**Issue by devGustavoFerreira** [ZeusAutomacao/DFe.NET#815]
Estou tendo essa rejeição ao tentar transmitir NFC-e no estado de Mato Grosso. Demais estados funcionando normalmente.

`<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>3.00</verAplic><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>51</cUF><dhRecbto>2018-07-26T21:24:11-03:00</dhRecbto><nRec>0</nRec><tMed>0</tMed><protNFe versao="4.00"><infProt><tpAmb>2</tpAmb><verAplic>4.00</verAplic><chNFe>511807XXXXXXXXXXXXXX650010000000091000012344</chNFe><dhRecbto>2018-07-26T21:24:11-03:00</dhRecbto><digVal>wNmRsXFdJ4aHbR3TbjBGBgm9lOg=</digVal><cStat>813</cStat><xMotivo>Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA</xMotivo></infProt></protNFe></retEnviNFe>`

Verifiquei o arquivo gerado e está usando o CDATA corretamente conforme segue:
`<![CDATA[http://homologacao.sefaz.mt.gov.br/nfce/consultanfce?chNFe=511807XXXXXXXXXXXXXX650010000000091000012344&nVersao=100&tpAmb=2&cDest=99999999000191&dhEmi=323031382d30372d32365432313a32363a35362d30333a3030&vNF=5.00&vICMS=0.00&digVal=4e35356e38586457665273617137313366613458446457725664733d&cIdToken=000001&cHashQRCode=144a24f8797a5cbc54de905b38dba3e9a3f1e1fb]]></qrCode><urlChave>http://homologacao.sefaz.mt.gov.br/nfce/consultanfce</urlChave></infNFeSupl>`

Alguém já se deparou com esse tipo de problema?

**Comment by orochasamuel** [comment]
@devGustavoFerreira já passou por esse link?
https://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-813-qr-code-com-sequ%C3%AAncia-de-escape-para-o-e-comercial-usar-cdata-como-resolver-450.html

**Comment by devGustavoFerreira** [comment]
Já sim, mas conferi o qrcode enviado e está correto. Testei também fazendo a emissão em homologação pelo app de teste e a mesma situação foi observada.

**Comment by orochasamuel** [comment]
Posta o QR aí..

**Comment by devGustavoFerreira** [comment]
@samuelrochaoliveira Eu já havia postado mas havia esquecido de colocar como código e ele foi pro "limbo". Devidamente ajustado no post inicial.

**Comment by devGustavoFerreira** [comment]
Fiz contato na SeFaz MT e me passaram que era problema com o servidor deles. Eles subiram uma versão corrigindo essa rejeição e agora está retornando com Rejeição de erro não catalogado, que de acordo com eles já estão verificando. Então resta só aguardar mesmo. Muito obrigado pela ajuda.

**Comment by orochasamuel** [comment]
Eita, canseira...
