### ISSUE TITLE
Alterações de URL para pacote NuGet

### ISSUE THREAD

**Issue by Bertoncini** [ZeusAutomacao/DFe.NET#816]
Bom dia, quero saber quando vão colocar no nuget as correções de url feita na #802,
Ou como posso fazer as alterações das URL sendo que estou usando o NuGet ?

**Comment by robertorp** [comment]
Vou atualizar o nuget hoje ainda. Imagino eu que depois do almoço já faço isso para você.

**Comment by robertorp** [comment]
Bom dia, publicado versão nova do zeus no nuget. 
Daqui uns minutos ela aparece lá.
