### ISSUE TITLE
Falha no schema na emissão da NFe 4.00 - URGENTE

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#819]
Pessoal, 

Até ontem (1/Agosto), a NFe 4.00 do Zeus para o Estado de SP estava emitindo normal.

Porém hoje (2/Agosto), depois que saiu a 3.10 do ar, começara a rejeitar as NFes por falha de esquema.

O mais estranho é esta versão 3.10 que ainda está vindo no arquivo de retorno.

![8-2-2018 9-29-26 am](https://user-images.githubusercontent.com/6843493/43584330-7ede4e78-9638-11e8-8369-2e326992065d.png)

Alguém pode dar um help?

**Comment by apbertoletti** [comment]
@robertorp , tem alguma pista ?

**Comment by robertorp** [comment]
Esse retorno e da sefaz, o zeus não insere em local nem um 3.10 no retorno
ele simplesmente pega o xml que veio da sefaz e converte o mesmo para o objeto.

o xml de envio esta mandando ele como 4.00? 

acabei de falar com o @adrbarros  sobre erro na sefaz de SP ele esta passando por algum problema lá tem

**Comment by rodrigordi** [comment]
somente em homologação ou em produção também ? Tenho 2 clientes em produção lá e está rodando tranquilo.

**Comment by alexjralves** [comment]
O problema ocorre também em produção.

**Comment by rodrigordi** [comment]
Um cliente teve retorno de falha de schema hoje antes de atualizar o comunicador para nfe 4.00. Você tem o XML que enviou para ter esse retorno ?

**Comment by apbertoletti** [comment]
@rodrigordi , aqui nos dois ambientes está dando dando o mesmo problema. No seu seus clientes ambos estão usando o Zeus também?

@robertorp , segue o XML de envio:

![8-2-2018 9-54-46 am](https://user-images.githubusercontent.com/6843493/43585007-64392604-963a-11e8-9c2f-4f57dd0f687e.png)

segue o arquivo tb:

[NFe35180856393051000185550010000240091000493285_assinado.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2253558/NFe35180856393051000185550010000240091000493285_assinado.txt)

**Comment by robertorp** [comment]
Temos clientes nf-e em SP também e ate o momento nem uma reclamação.

**Comment by rodrigordi** [comment]
a gente usa outro comunicador. consegue debugar e conferir se está indo para url certa ?

**Comment by adrbarros** [comment]
@apbertoletti - Aqui estou com o mesmo problema, consultei algumas empresas que utilizam outros sistemas, e estão com o mesmo problema 2 com 4.00 e um que ainda esta no 3.10, o 3.10 da rejeição já na consulta status

**Comment by luksfk** [comment]
Não utilizamos o Zeus mas temos clientes em SP também e em homologação realmente estamos enfrentando problemas. Acredito que seja algum problema lá mesmo.
Porém em produção está aprovando normalmente.

**Comment by apbertoletti** [comment]
Problema encontrado!

O @marcopoloviana (grupo do Zeus no skype) descobriu que se enviar a NFe sem compactar (zipar), está dando certo. O problema só acontece quando se compacta o XML na hora do envio.

![8-2-2018 10-05-26 am](https://user-images.githubusercontent.com/6843493/43585661-0f9c162c-963c-11e8-9294-caaf718c88ba.png)

![8-2-2018 10-05-01 am](https://user-images.githubusercontent.com/6843493/43585769-4a01d07c-963c-11e8-9406-989db34f0736.png)

@robertorp , tem alguma ideia do por que isso acontece?

**Comment by FabioHenriqueMF** [comment]
Bom dia 
Estamos com o mesmo problema em todos os nossos clientes de SP
É exatamente isso que relataram:
O envio esta sendo feito na url correta _https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx_ (no caso homologação)
 _<enviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>50109</idLote><indSinc>0</indSinc><NFe><infNFe versao="4.00" Id="NFe3518081305441300010955000......_
e a sefaz responde com o xml:
_<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>SP_NFE_PL_008i2</verAplic><cStat>215</cStat><xMotivo>Rejeição: Falha no schema XML</xMotivo><cUF>35</cUF><dhRecbto>2018-08-02T10:08:51-03:00</dhRecbto></retEnviNFe>_

Em  SC temos um cliente usando o emissor e nao deu problema
?????????????????

**Comment by alexjralves** [comment]
Pessoal, em vez de chamar 

"retorno = ws.ExecuteZip(xmlCompactado);"

Utilizem

"retorno = ws.Execute(dadosEnvio);"

Dica do Marco Polo Viana do grupo Zeus.

Aqui funcionou em produção / homologação.

**Comment by robertorp** [comment]
@robertorp , tem alguma ideia do por que isso acontece?

Sim @apbertoletti  , a sefaz de SP pode ter mudado alguma coisa no retorno ou no envio da compactada , algumas sefazes fazem isso pois aparentemente não existe um padrão no envio da mensagem SOAP para compactada. 
No caso da estrutura atual do Zeus teria que criar um novo WSDL somente para SP igual fiz com alguns estados exatamente pq alguns estados tem "retornos exclusivos" principalmente na parte de compactada. 

Imagino que seja isso pois foi o que aconteceu em alguns casos. Exemplo servidor SVAN tive que fazer algo exclusivo para eles. 

`NFe.Wsdl.Autorizacao.SVAN.NFeAutorizacao4SVAN`

Não deu certo de usar a classe 

`NFe.Wsdl.Autorizacao.NFeAutorizacao4`

Pois o retorno era diferente do SOAP

na classe `NFeAutorizacao4SVAN` nos métodos `Execute` e `ExecuteZip`
veja que tem a anotação 
`[return: XmlElement("nfeAutorizacaoLoteResult", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]`

`[return: XmlElement("nfeAutorizacaoLoteZipResult", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]`

na `NFeAutorizacao4`

`[return: XmlElement("nfeResultMsg", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]`
`[return: XmlElement("nfeResultMsg", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]`

Em outras palavras o SVAN não seguiu o padrão nacional. 
resumindo nesse caso especifico do SVAN (é a vida.. rsrs)

Meus clientes provavelmente não deram erro pois uso o zeus sem compactar xml.

**Comment by rodrigordi** [comment]
@robertorp tem uma diferença no soapclient.
nfe3 :             var results = Invoke("nfeAutorizacaoLoteZip", new object[] {nfeDadosMsgZip});
nfe4:             var results = Invoke("nfeAutorizacaoLoteZIP", new object[] { nfeDadosMsgZip });

no wsdl da SEFAZ/SP : está <wsdl:operation name="nfeAutorizacaoLoteZip">

Será q essa capitulação pode ser o problema ? tive esse problema do SVAN tbm. e anteriormente no NFCe-MS tinha um problema de capitulação Nfe - NFe nas chamadas.

Estou chutando, dei uma olhada no código e vi essa diferença ai.

**Comment by adrbarros** [comment]
Sem Compactação OK, NF-e Autorizada. Grato a todos.

**Comment by rodrigordi** [comment]
Olha que interessante : "2SP_NFE_PL_008i2215Rejeição: Falha no schema XML352018-08-02T10:08:51-03:00"

Acredito que :
SP_NFE_PL_008i : isso é um servidor rodando nfe 3.10.
<verAplic>SP_NFE_PL009_V4</verAplic> : isso é um servidor rodadno nfe 4.00

**Comment by FabioHenriqueMF** [comment]
fora a alteração de compactar mensagem, algum pronunciamento da sefaz? Por que a impressão que vai dar é que o problema estava no sistema

**Comment by FabioHenriqueMF** [comment]
Alguem enviou algum email para a sefaz se posicionar?

**Comment by rodrigordi** [comment]
Pessoal, voces viram ai um bocado de pessoas reclamando que depois das 11:20 não conseguem mais conectar na SEFAZ/SP. Dai teve uma pessoa que falou q só agora desativaram os protocolos SSL.

Eu olhei no SSL Checker e está 
Protocols enabled:
TLS1.2

Será que antes estava habilitado SSL ?

**Comment by apbertoletti** [comment]
@rodrigordi não entendi qual seria a relação do SSL habilitado com o problema em questão, ou seja, o envio do arquivo compactado.

**Comment by rodrigordi** [comment]
Não tem relação. vou retirar o comentário. me desculpem.
