### ISSUE TITLE
duvida sobre os schemas onde faz o download desse aqui

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#82]
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=jQpBV9LRf7I=

ele é para a geração de CSC no meu estado não tem site para a geração do CSC , tem que ser gerado atraves da webservice de CSC ai é onde queria ver se arruma os schemas do mesmo,
ou os schema e somente usado para validar? posso montar uma webservice de envio com o xml e somente enviar?

**Comment by adeniltonbs** [comment]
Boa tarde roberto. Os schemas servem para validar os dados antes de enviar para a SEFAZ. O objetivo é que você valide os dados localmente, economizando tráfego de internet e poupando os servidores da SEFAZ de trabalho extra. Nada impede que você envie uma requisição à SEFAZ sem submetê-la ao respectivo schema.

Quanto à obtenção dos schemas para todos os serviços descritos nos manuais, poderás obter em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=

**Comment by adeniltonbs** [comment]
roberto, também procurei os schemas (admCscNFCe_v1.00.xsd e retAdmCscNFCe_v1.00.xsd) descritos no "Manual Técnico de Utilização do Web Service de Administração do Código de Segurança do Contribuinte - CSC".

Seria interessante entrar em contato com a SEFAZ e solicitar esses schemas não?

**Comment by leandrossantos** [comment]
Não lembro de uma outra NT que fale desse serviço senão a NT-NFCe 2014/001 e olhando ela dá para ver que a data de divulgação está a definir

**Comment by robertorp** [comment]
Entrei em contato estou aguardando a resposta, agora sobre o serviço que citei , eles me deram somente um link de CSC um serviço igual os outros da nfe so que para CSC

**Comment by robertorp** [comment]
link da webservice https://homolog.sefaz.go.gov.br/nfe/services/v2/CscNFCe?wsdl

enfim logo mais vou desenvolver algo para essa webservice.

Obrigado pela atenção.
Email que recebi.

Boa tarde,

A documentação que orienta o uso do serviço para administração do CSC está disponível em: http://www.nfe.fazenda.gov.br/PORTAL/listaConteudo.aspx?tipoConteudo=tW+YMyk/50s=​, ver Nota Técnica NFCe 2014.001. ​

Os arquivos do schema estão em anexo.

Você pode verificar a seção 5.1.1. Leiaute Mensagem de Entrada
com a Estrutura XML com os dados para a administração de CSC NFC-e. 

Conforme interpretação da tabela demonstrativa, os XMLs podem ser montados
da seguinte maneira:

Consulta e  Solicitação de CSC

(coloquei os xml em arquivo pois o github não mostra, não sei o porque. by roberto)
https://www.dropbox.com/s/efgnk2yanuy9z6r/exemplo%20xml.txt?dl=0

Apenas a tag de Grupo dadosCsc é opcional (AP06  dadosCsc  G  CP01    0-1) 
Obs.: os elementos deste grupo é obrigatório.

Concordo que não está muito claro na documentação, e o schema deste serviço
ainda não está disponível no portal (não sei por que motivo), embora o serviço já esteja em homologação.

De qualquer forma, na documentação tem todo as informações de consumo e
retorno do serviço. 

​Em anexo, estou de mandando o arquivo schemasCSC.zip, ​ que utilizamos para a implementação
dos serviços, porém, como lhe disse, este ainda não está disponível no portal nacional.​

Att.

Marcelo Dias da Silva
Gestor de Tecnologia da Informação
Projeto Nota Fiscal Eletrônica
Secretaria da Fazenda do Estado de Goiás

arquivos schemas do mesmo.
https://www.dropbox.com/s/h89tsf88n58q00r/schemasCSC.zip?dl=0
