### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#820]
Boa tarde pessoal... tenho alguns clientes com certificado A3 e tem dado o seguinte retorno em qualquer comunicação ate mesmo com o app de teste do zeus:

Could not create SSL/TLS secure channel

A1 roda de boa... e alguns clientes com a3 tambem...
mas tem uns que nao da certo....

net framework 4.6.2

**Comment by apbertoletti** [comment]
Boa tarde @celinolimac ,

veja se estas dicas ajudam:

https://nstecnologia.com.br/blog/resolver-problema-protocolo-tls-1-2

**Comment by celinolimac** [comment]
blz.... obg pela resposta... vou seguir estes passos ai e informo aki se deu certo!!!
Mas provavelmente eh alguma atualização na maquina do cliente mesmo...
Pois coloquei meu certificado A1 nessa mesma maquina do cliente e deu a mesma mensagem!
e aqui na empresa consigo emitir de boa com o A1

**Comment by robertorp** [comment]
Use o cache do zeus. 
Comigo isso soluciona. So da com certificado A3 ne? 
se for use o cache do Zeus. 

como falei comigo não ocorre isso.

**Comment by celinolimac** [comment]
Obrigado pessoal pelo retorno!!!
o problema foi resolvido atualizando a maquina do cliente com todas as atualizações do Windows...
para que o protocolo TLS 1.2 que eh o utilizado na versão 4.0 esteja disponivel na maquina...
vale ressaltar também que eh preciso a versão 4.6.2 ou superior do Net Framework instalada na maquina
