### ISSUE TITLE
215 - Rejeição: Falha no schema XML

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#821]
Olá queridos, boa tarde!

Estou enfrentando um problema ao emitir uma nota para um cliente na NF-e 4.0 utilizando as DLLs.
Gero ao arquivo, envio, recebo a confirmação (103 - Lote recebido com sucesso), porém quando vou consultar o recibo (servicoNFe.NFeRetAutorizacao) recebo sempre o erro:
```
<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
	<tpAmb>2</tpAmb>
	<verAplic>SP_NFE_PL009_V4</verAplic>
	<nRec/>
	<cStat>215</cStat>
	<xMotivo>Rejeição: Falha no schema XML</xMotivo>
	<cUF>35</cUF>
	<dhRecbto>2018-08-03T17:31:30-03:00</dhRecbto>
</retConsReciNFe>
```

Algum poderia me orientar, pois nao tenho ideia onde posso estar errando.

**Comment by rodrigordi** [comment]
Ideal seria você mostrar o XML que está enviando para a SEFAZ.

**Comment by ghost** [comment]
O servico NFe.NFeRetAutorizacao retorna falha no XML, porém ao consultar via chave (NfeConsultaProtocolo) retornou que ja estava autorizado. Verifiquei no sefaz homologação e estava mesmo. Acredito que seja algum erro meu no envio e consulta do lote. 

Obrigado de qualquer forma @rodrigordi.

**Comment by mvtaraujo** [comment]
Faz o envio sincrono. No Nfe autorização você já pega o retorno. Isso se você não estiver mandando muitas notas

**Comment by ghost** [comment]
Olá @mvtaraujo! Obrigado pela dica, estou fazendo assim agora.

**Comment by mvtaraujo** [comment]
Mais prático né. Vlw
