### ISSUE TITLE
[Falha na emissão] A conexão subjacente estava fechada

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#822]
Boa noite a todos,

O velho problema que eu e mais algumas pessoas tinhamos infelizmente voltou agora com a obrigatoriedade de usar o TLS 1.2.

https://github.com/ZeusAutomacao/DFe.NET/issues/706
https://github.com/ZeusAutomacao/DFe.NET/issues/222
https://github.com/ZeusAutomacao/DFe.NET/issues/338

O problema era resolvido simplesmente trocando o protocolo de envio. Eu no meu sistema identificava o erro, trocava o protocolo e ja tentava novamente, e funcionava, fazia muito tempo que não tinha suporte assim, agora com o TLS 1.2 o problema voltou, e como já é de conhecimento da comunidade só tem solução ao sair da aplicação e entrar novamente.

O problema como já foi documentado aqui ocorre somente com certificados A3.

**Comment by mvtaraujo** [comment]
Marcos. Estive conversando no particular com o Adenilton sobre isso. Pesquisando sobre encontrei o que pra mim solucionou o problema. Adenilton colocou no commit  0a2e3eb. Porém, depois foi retirado por não fazer muito sentido pra ele pois não teria nada a ver com certificado.

Bom, pra mim resolveu o problema é só acontece às vezes, o que dá a impressão de ser falha momentânea na comunicação com a sefaz pois não preciso reiniciar a aplicação.

Coloque no construtor da classe servicosnfe e faça seus testes.

ServicePointManager.Expect100Continue = true;

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/823

**Comment by marcosgerene** [comment]
@mvtaraujo ainda não sei. Mas o 100Continue não resolve.

**Comment by orochasamuel** [comment]
Bom dia,

@marcosgerene, qual a versão do seu framework? Em ambiente 'dev' você usa 4.5 e em ambiente 'prod' você usa 4.0 ou já estão todos no 4.5?

O .net 4.0 não possui suporte ao TLS 1.2, mas se você tiver a versão 4.5 poderá ser forçada essa troca na aplicação. Mas para isso na sua aplicação você precisa incluir a representação de Enum pois no .net 4.0 ainda não havia uma entrada nomeada como "Tls12":

```cs
   ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
```

Você também pode optar por alterar o Protocolo padrão via registro do Windows, assim você elimina a preocupação de saber qual versão foi "delegada" como padrão para o consumo. (essa alternativa pode ser considerada inviável devido à grande demanda de suporte).

Fontes:
https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5
https://support.solarwindsmsp.com/kb/solarwinds_n-central/How-To-Force--NET-to-use-TLS-1-2

**_*PS: Pendente de testes para validar as sugestões._**

**Comment by marcosgerene** [comment]
@samuelrochaoliveira meus projetos usam 4.6.2.

**Comment by orochasamuel** [comment]
Ok. E a versão client na máquina de Produção? É a mesma versão? Tem alguma máquina Windows 7 que está acontecendo isso?

**Comment by marcosgerene** [comment]
@samuelrochaoliveira 

E a versão client na máquina de Produção? Não entendi a pergunta.... sou uma SH, tenho vários ambientes diferentes... mas todos meus pcs rodam 4.6.2 ou superior.

Tem alguma máquina Windows 7 que está acontecendo isso? Sim.

**Comment by orochasamuel** [comment]
> E a versão client na máquina de Produção? Não entendi a pergunta.... sou uma SH, tenho vários ambientes diferentes... mas todos meus pcs rodam 4.6.2 ou superior.

Perguntei para saber se a versão era **client** ou **full**, como você sabe existe a opção completa e a compacta do framework, dependendo da versão.

> Tem alguma máquina Windows 7 que está acontecendo isso? Sim.

E mesmo depois de rodar o Windows Update com todas as atualizações pendentes não funcionou? Ou funcionou por um tempo e agora parou de novo? A questão do registro do Windows, de alterar para o protocolo padrão (default) para uso do framework, você fez? Consegue fazer para saber se corrige essa questão?

O que me chama a atenção é que esse é um problema recorrente, vira e mexe aparece novamente. Tem que haver um lastro para identificar a correção.

**Comment by marcosgerene** [comment]
@samuelrochaoliveira 

1-) Acredito que seja a versão full, o instalador tem uns 70mb, atualmente instalo a 4.7.1 se não me engano.

2-) Hoje ainda não tive suporte, então não sei a frequencia, dependo de feedback de clientes. E sim, funciona, mas para depois de um tempo, ai basta fechar o sistema e reabrir que volta.


Edit: O suporte que tive nesses ultimos dias foi apenas com CTe (fora a necessidade de update do windows). Ainda não sei se é algo só do CTe pois é muito recente, então fica dificil eu dar parâmetros melhores.  

De qualquer forma o código do NFe é relativamente organizado, então consegui fazer uma sugestão intessante no no pull https://github.com/ZeusAutomacao/DFe.NET/pull/823.

O CTe até comecei a tentar mexer no código mas achei muito bagunçado então estou migrando para o ACBr.Net.CTe do @rftd.

**Comment by orochasamuel** [comment]
Uma pergunta atoa - (acredito que não tenha nada haver mas, por curiosidade) - nas **Opções Avançadas** do **Internet Explorer** você deixou marcado **"Usar TLS 1.0"**, **"Usar TLS 1.1"** e **"Usar TLS 1.2"** **_E DESMARCOU SSL 3.0_**?

**Comment by marcosgerene** [comment]
>Uma pergunta atoa - (acredito que não tenha nada haver mas, por curiosidade) - nas Opções Avançadas do Internet Explorer você deixou marcado "Usar TLS 1.0", "Usar TLS 1.1" e "Usar TLS 1.2" E DESMARCOU SSL 3.0?

Sim na verdade deixei tudo marcado. 


Ainda não tenho o feedback para saber se foi algo momentaneo, mas como quero evitar dor de cabeça mudei algumas coisas no meu código.  Exemplo de NFe:

![image](https://user-images.githubusercontent.com/15945003/43720823-89c23192-9967-11e8-8b3d-5876f2004f84.png)


Repara que agora "eu me responsabilizo" pelo certificado, não mais a ferramenta, o código do CTe seria muito trabalhoso para mudar, então resolvi migrar de projeto.

**Comment by marcosgerene** [comment]
Testei em alguns clientes o pull https://github.com/ZeusAutomacao/DFe.NET/pull/823  e mesmo com ele o problema ainda acontece.

A minha implementação para consumo da biblioteca é esta:
![image](https://user-images.githubusercontent.com/15945003/43899033-123575c4-9bb7-11e8-93c8-0e29b2617ea2.png)

Meu certificado chama Dispose() a cada chamada. Uma coisa que notei no projeto do amigo @rftd é que ele sempre seta o Protocolo de sergurança para SSL3 | TLS | TLS11 | TLS12 antes de fazer qualquer requisição. Vou implementar isso como padrão também e volto a postar resultados.

----

Alterei minha classe de envio para sempre ajustar o protocolo de envio para o citado acima no construtor.

Alterei minha implementação para esta:

![image](https://user-images.githubusercontent.com/15945003/43899449-5830251e-9bb8-11e8-8169-f85e656bf3a8.png)

![image](https://user-images.githubusercontent.com/15945003/43899357-097dc7d2-9bb8-11e8-83a4-c7d170893dcb.png)

Postarei novos resultados.

**Comment by GuilhermeAlmeida94** [comment]
Eu também estou tendo o mesmo problema. Já utilizei "SSL3 | TLS | TLS11 | TLS12", "100Continue", Criei dispose e até "MaxServicePointIdleTime" pra ver se fazia alguma diferença, mas não fez. Aparente mente o problema está apenas nos certificados A3. Já utilizei certificados do Ceará e do Piauí.

**Comment by MisaelBeray** [comment]
Eu também estou com esse problema (A conexão subjacente estava fechada: Erro inesperado em um envio) em um cliente do MA. Ele utiliza certificado A3 da SOLUTI com leitora da certisign, a maquina é windows 10 PRO com os update em dia, as opções da internet esta habilitada o SSL3 | TLS | TLS11 | TLS12, esta instalado as cadeias de certificado, inclusive a (ICP-BRASILV5).

Notei que se executo o link do webservice da sefaz (https://hom.sefazvirtual.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx?wsdl) no navegador IE da o erro (403 - forbidden access is denied), porem se executo no firefox ou chrome abre normalmente.

Tenho clientes em outros estados que utilizam certificado A3 e não tenho o mesmo problema, e certificados A1 funcionam com mais facilidade.

Alguém conseguiria dar uma luz, algum indicio de como resolver isso ?

**Comment by GuilhermeAlmeida94** [comment]
Será que atualizar a versão do .NET vai fazer alguma mudança? Eu uso a 4.5.2. Já ouvi falar que seria interessante modificar na máquina dos usuários a versão para a 4.7.1.

**Comment by MisaelBeray** [comment]
Como padrão deixo os clientes atualizados acima da 4.6.2, no windows 10 o cliente esta com a 4.7, porem o problema persiste, apesar de que em outros que tive o mesmo problema resolveu.

Continuo a procurar uma solução para esse caso, se descobrir algo deixo a resolução aqui.

**Comment by leandrossantos** [comment]
Para quem estiver com esse erro no Windows 10, ai esta a solução. 
Basta executar esse .reg em anexo que resolve.

[FixCrypto_TLS1_2_Windows10.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2278224/FixCrypto_TLS1_2_Windows10.zip)

**Comment by marcosgerene** [comment]
>Para quem estiver com esse erro no Windows 10, ai esta a solução.
>Basta executar esse .reg em anexo que resolve.
>
>FixCrypto_TLS1_2_Windows10.zip



@leandrossantos de onde tirou essas informações? Por favor explique as soluções, ja postaram várias "mágicas" e nunca tivemos uma solução concreta, informe a fonte e o que faz o registro, numa dessas a situação pode piorar ao invés de melhorar.

Abri via notepad++ o que vc mandou e tem mais de 1080 linhas!

**Comment by orochasamuel** [comment]
Concordo com o que o @marcosgerene disse. Esse arquivo muda todos as configurações setando o protocolo padrão como TLS 1.2. O que faz isso é incluir a Flag abaixo:

![image](https://user-images.githubusercontent.com/15462690/43964988-7214f888-9c94-11e8-8719-943e9f841c3c.png)

Se houver algum serviço que não ofereça suporte ao TLS 1.2, funcione no SSL por exemplo, esse registro vai forçar a usar um protocolo diferente para o que o serviço está preparado.

Essa é uma alteração muito "melindrosa".

**Comment by MisaelBeray** [comment]
Galera pra resumir, tentei de tudo no win 10 do cliente e não consegui contornar o erro ( Não executei o script leandro), a única solução que deu certo foi trocar de versões de windows até que pegamos um Win 7 SP 1 .NET Framework 4.7 que funcionou sem problemas.

**Comment by juniorodilton** [comment]
Fala galera, eu estou 'passando' por cima deste problema fazendo uma requisição HTTP direto.

**Comment by marcosgerene** [comment]
@odilton poderia postar como faz isto?

**Comment by juniorodilton** [comment]
Claro, eu vou baixar este projeto e vou usar o padrão que vocês fazem, pois eu não utilizo. Daí fica mais fácil de entender. 

Inclusive, comecei a fazer desta forma porque os meus clientes de PA e MA (que utilizam a sefaz virtual) estavam com erro e eu não consegui adicionar o serviço no VS.

**Comment by marcosgerene** [comment]
Estou criando um console application pra minha aplicação, vou chamar ele, ele vai fazer o serviço (consultar, cancelar e enviar) e vai fechar quando concluir, com isso sempre tenho uma instancia fazendo no primeiro consumo (pra mim o problema só ocorre do segundo consumo em diante).

**Comment by juniorodilton** [comment]
@marcosgerene , desculpe a demora, estava tentando entender o padrão deste projeto.
Mas na real, eu fiz uma outra coisa ontem que deu certo para meus clientes.
Na hora de chamar StatusServiço estou tentando umas 4 vezes. Porém da seguinte forma:
1º e 3º - Uso TLS1.2
2º e 4º - Mudo para SSL3
No meu caso já resolveu a situação. O engraçado é que em algumas máquinas só vai por SSL3 e em outras pelo TSL 1.2.

**Comment by orochasamuel** [comment]
@odilton você emite NF-e ou NFC-e? As máquinas que funcionam alternadamente com SSL3 e TLS1.2 são Win7 ou Win10, ou há os 2 S.O.?

**Comment by robertorp** [comment]
aqui comigo ate o momento esta tudo normal. Acho que tive problemas em um estado (não lembro qual) que o serviço de carta correção estava incoerente (tls1.0) os de mais serviços funcionavam em tls 1.2

coisa estranha ne?
nada... coisa de sefaz mesmo normal.

**Comment by juniorodilton** [comment]
@samuelrochaoliveira emito NF-e e NFC-e.
Tivemos muitos problemas com Windows 7. Após atualizar o windows teoricamente todas passaram a funcionar normal.
Daí começaram a surgir problemas com windows 10. Aí neste caso eu implementei desta forma e até agora está funcionando muito bem. 
Deixei um log em algumas máquinas e vi que algumas mandam pelo SSL3 e outras pelo TSL1.2.
Ainda não consegui pegar um padrão.

**Comment by marcosgerene** [comment]
Acredito que tenho uma solução aqui pra mim.

Criei uma aplicação de Console que consome minhas dlls, eu passo pra ele o método e o Id e nele faço o processo, quando ele finaliza fecha.

O comportamento é:
1. Aplicação principal gera a chave e o xml e salva no banco
2. Aplicação principal chama o AppConsole passando por parametro o método e o ID
3. AppConsole recupera as informações através do ID e executa a ação
4. AppConsole termina (faço tudo no main, é um código curto pois basicamente chamo métodos que e eu já tinha antes).
5. Aplicação principal pega o retorno.

Mexi muito pouco no código, basicamente fiz micro adaptações, até agora parece que o problema foi sanado, pois sempre tenho a "instancia inicial".

**Comment by GuilhermeAlmeida94** [comment]
Eu uso o Zeus como uma dll apenas para realizar os serviços. Tem algum jeito de eu conseguir terminar ela como você faz no seu AppConsole?

**Comment by marcosgerene** [comment]
@Guiphb sim, no seu caso é até mais simples. Pelo que entendi você deserealiza o xml gerando um objeto nfe e transmite com o Zeus, procede?

Se for isso, crie a aplicação passado o evento e o path do xml, chame a aplicação, nela faça o serviço devolvendo uma resposta (um json da vida com o string do xml e o retorno em str) e pronto, ta resolvido.

**Comment by marcosgerene** [comment]
A questão foi completamente resolvida somente com a aplicação de console fazendo o processo, foi tentado tudo que está documentado na biblioteca.

O que foi tentado (que eu lembro):
- Expect100Continue
- SecurityProtocol
- Deixar sem senha
- Using (para chamar o dispose)
- Manter em cache

O problema também se repete no uso de outras bibliotecas (no meu caso com o ACBr.Net.CTe).

A solução encontrada foi o console application sendo fechado no final de cada requisição.

**Comment by orochasamuel** [comment]
> Acredito que tenho uma solução aqui pra mim.
> 
> Criei uma aplicação de Console que consome minhas dlls, eu passo pra ele o método e o Id e nele faço o processo, quando ele finaliza fecha.
> 
> O comportamento é:
> 
> 1. Aplicação principal gera a chave e o xml e salva no banco
> 2. Aplicação principal chama o AppConsole passando por parametro o método e o ID
> 3. AppConsole recupera as informações através do ID e executa a ação
> 4. AppConsole termina (faço tudo no main, é um código curto pois basicamente chamo métodos que e eu já tinha antes).
> 5. Aplicação principal pega o retorno.
> 
> Mexi muito pouco no código, basicamente fiz micro adaptações, até agora parece que o problema foi sanado, pois sempre tenho a "instancia inicial".

@marcosgerene por gentileza, você poderia me fornecer uma cópia do código no seu AppConsole? Lhe agradeço se puder fazê-lo, se não o puder, lhe agradeço também. o/

**Comment by marcosgerene** [comment]
@samuelrochaoliveira o código do console é meio inutil porque ele só chama métodos das minhas dlls, mas... segue:

```
static void Main(string[] args)
{
	string metodo = string.Empty;
	string id = string.Empty;
	string empresa = string.Empty;
	string acesso = string.Empty;
	string justificativa = string.Empty;

	try
	{
		metodo = args[0];
		id = args[1];
		empresa = args[2];
		acesso = args[3];

		GArquivos.GravarLog($"ZeusApplication: {JsonConvert.SerializeObject(args)}");

		ConfigLocal.LerConfiguracoes();
		using (var conexao = new Conexao(_poolConnection: false))
		{
			new SistemaDAL(conexao).Load();
			new ConfiguracoesDAL(conexao).Load();
			Globals.DadosEmpresa = new EmpresaDAL(conexao).Load(int.Parse(empresa));
			AcessoBO.AcessoAtual = new AcessoDAL(conexao).Load(int.Parse(acesso));
		}

		switch (metodo.ToLower())
		{
			case "nfe_transmitir":
				bool forcarOffline = string.Equals(args[4].ToLower(), "true");
				new GDFe().Transmitir(long.Parse(id), forcarOffline);
				break;
			case "nfe_transmitir_lote":
				new GDFe().TransmitirLote(id);
				break;
			case "nfe_consultar": new GDFe().Consultar(long.Parse(id)); break;
			case "nfe_cancelar":
				justificativa = args[4];
				new GDFe().Cancelar(long.Parse(id), justificativa);
				break;
			case "nfe_cartacorrecao":
				string jsonCarta = GArquivos.CombinarDiretorio(Environment.CurrentDirectory, "temp", "carta_correcao.json");
				jsonCarta = GArquivos.LerArquivoTexto(jsonCarta);

				GArquivos.GravarLog(jsonCarta);
				new GDFe().CartaCorrecao(jsonCarta);
				break;
			case "cte_transmitir": new GCTe().Transmitir(long.Parse(id)); break;
			case "cte_transmitir_lote": new GCTe().TransmitirLote(id); break;
			case "cte_consultar": new GCTe().Consultar(long.Parse(id)); break;
			case "cte_cancelar":
				justificativa = args[4];
				new GCTe().Cancelar(long.Parse(id), justificativa);
				break;
			case "mdfe_transmitir": GMDFe.Transmitir(long.Parse(id)); break;
			case "mdfe_consultar": GMDFe.Consultar(long.Parse(id)); break;
			case "mdfe_encerrar": GMDFe.Encerrar(long.Parse(id)); break;
			case "mdfe_cancelar":
				justificativa = args[4];
				GMDFe.Cancelar(long.Parse(id), justificativa);
				break;
			default:
				throw new Exception("Método não suportado");
		}
	}
	catch (Exception ex)
	{
		string PathZeus = GArquivos.CombinarDiretorio(AppDomain.CurrentDomain.BaseDirectory, "temp", "resposta.txt");

		string strLog = $"Zeus Console [Método: {metodo}] [Id: {id}] [Empresa:{empresa}] [Acesso:{acesso}]{Environment.NewLine}" +
						$"Erro: {ex.Message}{Environment.NewLine}" +
						$"Inner: {ex.InnerException}{Environment.NewLine}" +
						$"StackTrace: {ex.StackTrace}";

		GArquivos.GravarLog(strLog);

		GArquivos.ExcluirArquivo(PathZeus);
		GArquivos.EscreverTexto(PathZeus, strLog);

	}
	finally
	{
		GArquivos.GravarLog($"Finalizando ZeusApplication");
	}
}
```

Exemplo de chamada:
```
var process = new Process();
process.StartInfo.FileName = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "GereneSI.Zeus.Console.exe");
process.StartInfo.Arguments = $"NFE_TRANSMITIR {gnfe.Id} {Globals.DadosEmpresa.Codigo} {AcessoBO.AcessoAtual.Codigo} {(forcarOffline ? "true" : "false")}";
process.StartInfo.CreateNoWindow = true;
process.StartInfo.UseShellExecute = false;
process.Start();
process.WaitForExit();
```

**Comment by orochasamuel** [comment]
Show de bola!! Valeu.

**Comment by gabrielrvd** [comment]
Cheguei aqui porque acontecia o mesmo erro na minha solução apenas em uns dois clientes e parece ser um problema do .net com o SO. Nossa aplicação é própria e não utilizo o componente Zeus.

Ao invés de chamar um novo aplicativo como o @marcosgerene, eu optei por criar um novo appdomain que resolve o problema igual e deixa o código mais fácil de depurar e simples.

1 - Adicionar no Main um LoaderOptimization e assim reaproveitar o assembly já carregado, com isso o consumo de recursos é bem menor.

```
[LoaderOptimization(LoaderOptimization.MultiDomainHost)] 
static void Main()
```

2 - Criar um helper para construir o novo appdomain

```
public sealed class IsolatedCode<T> : IDisposable
        where T : MarshalByRefObject
    {
        #region Fields

        private AppDomain _domain;

        #endregion

        #region Constructors and Destructors

        public IsolatedCode()
        {
            this._domain = AppDomain.CreateDomain(
                "Isolated:" + Guid.NewGuid(),
                null,
                AppDomain.CurrentDomain.SetupInformation);

            var type = typeof(T);

            this.Value = (T) this._domain.CreateInstanceAndUnwrap(type.Assembly.FullName, type.FullName);
        }

        #endregion

        #region Public Properties

        public T Value { get; }

        #endregion

        #region Public Methods and Operators

        public void Dispose()
        {
            if (this._domain == null)
            {
                return;
            }

            AppDomain.Unload(this._domain);
            this._domain = null;
        }

        #endregion
    }
```

3 - Criar uma classe que irá executar a chamada no webservice e herda de MashalByRefObject que irá executar no novo appdomain, nesse momento é necessário buscar novamente o certificado e não podemos passar ele por parâmetro já que não é serializable e queremos acessar o certificado e store como se fosse uma nova execução de um aplicativo.

```
public class WebServiceAutorizacaoWork : MarshalByRefObject
    {
        #region Public Methods and Operators

        public string Run(string xmlEnvio, string url, string serialCertificado)
        {
            ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

            using var ws = new NFeAutorizacao.NFeAutorizacao4
                {
                    SoapVersion = SoapProtocolVersion.Soap12,
                    Url = url
                };

            ws.ClientCertificates.Add(
                CertificadoDigitalHelper.BuscarCertificado(serialCertificado));

            var xmlEnvioDocument = new XmlDocument();
             xmlEnvioDocument.LoadXml(xmlEnvio)

            var xmlResposta = ws.nfeAutorizacaoLote(xmlEnvioDocument);
            return xmlResposta.OuterXml;
        }

        #endregion
    }
```

4 - Invocar o item do passo 3 para autorizar a nota

```
using var isolated = new IsolatedCode<WebServiceAutorizacaoWork>();

//// Aqui o código está sendo executado como se fosse outro aplicativo, um novo appdomain
var xmlResposta = isolated.Value.Run(xmlEnvio, url, serialCertificado);
```
