### ISSUE TITLE
Duvida entrada via xml com Zeus

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#824]
pessoal estou querendo utilizar o zeus para ler o xml na entrada de notas mas, tive um problema como faço para obter as informações da classe tipoicms?

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/760

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/139

**Comment by ThalisonSantos** [comment]
@marcosgerene muito obrigado valeu!!!
