### ISSUE TITLE
Verificar serviço de autorização compactado em SP 

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#826]
Verificar serviço de autorização compactado em SP

**Comment by apbertoletti** [comment]
Bom dia @robertorp ,

Também estive analisando este código aqui por conta o problema enfrentado no #819 , mas não encontrei nada relevante.

Você suspeitou de algo ai?

**Comment by ThalisonSantos** [comment]
em Pernambuco também esta dando erro quando manda autorização compactada

**Comment by robertorp** [comment]
O que imagino e algo na string que esta lá de retorno, digo acho que a sefaz não segue o padrão definido na  NT_2016_002_v1_60.pdf

![image](https://user-images.githubusercontent.com/10251705/43837371-b52b16ae-9aee-11e8-85c5-3b125a25b0ec.png)
Creio eu que o erro esta nisso, a sefaz não segue o padrão logo então da o erro.
por hora somente creio nisso, não peguei para realmente verificar ainda. Estou deixando para mais o final de semana.

**Comment by ThalisonSantos** [comment]
em PE não da nem retorno gera uma exceção no aplicativo "Referência de objeto não definida para uma instância de um objeto" no serviço autorização

**Comment by rodrigordi** [comment]
acho que o nome da action está errado. @ThalisonSantos voce consegue fazer uma alteração ai e testar ?

**Comment by ThalisonSantos** [comment]
@rodrigordi aqui funcionou quando deixei o parâmetro compactar mensagem como false

**Comment by rodrigordi** [comment]
sim. ai o programa usa outro método que está funcionando. Se voce olhar no arquivo /NFe.Wsdl/Autorizacao/NFeAutorizacao4.cs voce vai ver 2 funções.
        public XmlNode Execute(....) 
e
        public XmlNode ExecuteZip(....)  <-- essa não está funcionando.

eu acho que o problema esteja aqui : 

[SoapDocumentMethod("http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZIP", Use = SoapBindingUse.Literal, ParameterStyle = SoapParameterStyle.Bare)]
        [WebMethod(MessageName = "nfeAutorizacaoLoteZIP")]
        [return: XmlElement("nfeResultMsg", Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
        public XmlNode ExecuteZip([XmlElement(Namespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")] string nfeDadosMsgZip)
        {
            var results = Invoke("nfeAutorizacaoLoteZIP", new object[] { nfeDadosMsgZip });
            return ((XmlNode)(results[0]));
        }


Todo lugar que aparece nfeAutorizacaoLoteZIP deveria ter nfeAutorizacaoLoteZip com esse final minusculo.


No WSDL da SEFAZ está :
<s:element name="nfeDadosMsgZip" type="s:string"/>
...
<wsdl:operation name="nfeAutorizacaoLoteZip">


Mas não tenho como alterar e testar. Se quiser/puder tentar.

**Comment by ThalisonSantos** [comment]
@rodrigordi eu uso pelo nuget e não os fontes do projeto. mas em outros estados o método com compactação funciona ex. Alagoas e Sergipe.

**Comment by rodrigordi** [comment]
@ThalisonSantos entendi, eu também não tenho uso os fontes. Pode ser um problema especifico na SEFAZ/SP então.
