### ISSUE TITLE
envio não consta na sefaz

### ISSUE THREAD

**Issue by Eloisio** [ZeusAutomacao/DFe.NET#83]
envio um xml ele retorna ok mas qdo consulto não consta na base do sefaz

me ajuda  grato

**Comment by robertorp** [comment]
Talvez se você criar e enviar.. ai você pega o numero de consulta de lote..
e faz a pesquisa de lote, olhe o conteúdo do lote lá no xml dele deve ter o erro em algum lugar do porque não está dando certo de fazer a consulta

**Comment by Eloisio** [comment]
então , tambem criei e enviei, apenas mudei para o meu estado 

o envio foi este

<enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>5</idLote><indSinc>0</indSinc><NFe><infNFe versao="3.10" Id="NFe35151222676702000122550010000000061000012341"><ide><cUF>35</cUF><cNF>00001234</cNF><natOp>VENDA</natOp><indPag>0</indPag><mod>55</mod><serie>1</serie><nNF>6</nNF><dhEmi>2015-12-08T11:54:00-02:00</dhEmi><dhSaiEnt>2015-12-08T11:54:00-02:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3508504</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>3.000</verProc></ide><emit><CNPJ>22676702000122</CNPJ><xNome>Eloisio de campos informatica me</xNome><xFant>Campos Evolution</xFant><enderEmit><xLgr>rua irere</xLgr><nro>26</nro><xBairro>piedade</xBairro><cMun>3508504</cMun><xMun>CAÇAPAVA</xMun><UF>SP</UF><CEP>12280000</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1236529739</fone></enderEmit><IE>234071905117</IE><CRT>1</CRT></emit><dest><CNPJ>99999999000191</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>RUA ...</xLgr><nro>S/N</nro><xBairro>CENTRO</xBairro><cMun>2802908</cMun><xMun>caçapava</xMun><UF>SP</UF><CEP>12280000</CEP><cPais>1058</cPais><xPais>BRASIL</xPais></enderDest><indIEDest>9</indIEDest><email>teste@gmail.com</email></dest><det nItem="1"><prod><cProd>00001</cProd><cEAN>7770000000012</cEAN><xProd>ABRACADEIRA NYLON 6.6 BRANCA 91X92 1</xProd><NCM>73269000</NCM><CFOP>5102</CFOP><uCom>UNID</uCom><qCom>1.0000</qCom><vUnCom>1</vUnCom><vProd>1.00</vProd><cEANTrib>7770000000012</cEANTrib><uTrib>UNID</uTrib><qTrib>1.0000</qTrib><vUnTrib>1.0000000000</vUnTrib><vDesc>0.10</vDesc><indTot>1</indTot><nItemPed>0</nItemPed></prod><imposto><vTotTrib>0.17</vTotTrib><ICMS><ICMSSN102><orig>0</orig><CSOSN>102</CSOSN></ICMSSN102></ICMS><IPI><cEnq>999</cEnq><IPITrib><CST>00</CST><vBC>1.00</vBC><pIPI>1.00</pIPI><vIPI>0.05</vIPI></IPITrib></IPI><PIS><PISNT><CST>07</CST></PISNT></PIS><COFINS><COFINSNT><CST>07</CST></COFINSNT></COFINS></imposto></det><total><ICMSTot><vBC>0</vBC><vICMS>0</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0</vBCST><vST>0</vST><vProd>1.00</vProd><vFrete>0</vFrete><vSeg>0</vSeg><vDesc>0.10</vDesc><vII>0</vII><vIPI>0.05</vIPI><vPIS>0</vPIS><vCOFINS>0</vCOFINS><vOutro>0</vOutro><vNF>0.90</vNF><vTotTrib>0.17</vTotTrib></ICMSTot></total><transp><modFrete>9</modFrete></transp><cobr><fat><nFat>12345678910</nFat><vLiq>90.00</vLiq></fat><dup><nDup>12345678</nDup><vDup>0.45</vDup></dup><dup><nDup>987654321</nDup><vDup>0.45</vDup></dup></cobr></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#NFe35151222676702000122550010000000061000012341"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>nyfCjFZZbXQ2RmMBvL5kh1WxZa4=</DigestValue></Reference></SignedInfo><SignatureValue>naPm/tBUdbBEkMP26Wm2FMCUnU1MbfseJPSsMdf13pmAGulG1GaIYMy+pPlYmm6Rkz7ArHugCpUqnZPm/TztYZeGIhmjvGbJiic60NS2ofxZL0K5yLsITL9OFE2KtkiSVOlavGDnreRxIy1CvBNPg+wPJhlpFaBcBmdqYlQGdt+6nV1p8M1CY0rTOYMdrAQhMTBwnZVzk3Y2vVHN/8KomYaYcVhVoabjBhIOhQlFQNrX6hfOpsEKhFNHKfhBJ3MGqcpaT+saixQMi7xv+g2htcm+1hPOOq1pte+M1RJoQBL4jrY6QGMVOC6BCU1ymHckHcCzoYfxvbFR4HkFiAaJBg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH/TCCBeWgAwIBAgIIM7HXtqPSsvUwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNTA3MTQxMTE1MDBaFw0xNjA3MTMxMTE1MDBaMIHgMQswCQYDVQQGEwJCUjELMAkGA1UECBMCU1AxETAPBgNVBAcTCENBQ0FQQVZBMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEogQTExEjAQBgNVBAsTCUFSIFNFUkFTQTE4MDYGA1UEAxMvRUxPSVNJTyBERSBDQU1QT1MgSU5GT1JNQVRJQ0EgTUU6MjI2NzY3MDIwMDAxMjIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCooj5k5yrJKBYbjzVH5MvDiLNXonwQp/5uep3QkugixRW1/Nq7lL1aNb4vIlCJOnhgO6CJImna41BtDQ745kuzP3KX28lGyhM+xDske7X0fVeuotIxkddNHsRIM1fhxTZpcqVwjJOO3kRiC92mYtkRerUbBZ71wGrcIIu7EhRtLEAtqucTTySuX/ybfvhZYMiVwGrYXzdXCUDUGnXHAh11i30dkiE1nI/uCje1zzu4JLXp/jXsiWFJL/uJ3zM7mUe7jg52UMCUB6wmi6gBvg4Z1drp4ib5EdBnDYPsjgX2fQlpUhLVQONotnSJ0U7n/zTM+PAT+1aROflXvKAMDMR1AgMBAAGjggMjMIIDHzCBmQYIKwYBBQUHAQEEgYwwgYkwSAYIKwYBBQUHMAKGPGh0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9jYWRlaWFzL3NlcmFzYXJmYnYyLnA3YjA9BggrBgEFBQcwAYYxaHR0cDovL29jc3AuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9zZXJhc2FyZmJ2MjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFLKgxD1GnnzIhWwIHhAylGVGcEFzMHEGA1UdIARqMGgwZgYGYEwBAgENMFwwWgYIKwYBBQUHAgEWTmh0dHA6Ly9wdWJsaWNhY2FvLmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL2RlY2xhcmFjYW8tcmZiLnBkZjCB8wYDVR0fBIHrMIHoMEqgSKBGhkRodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnYyLmNybDBEoEKgQIY+aHR0cDovL2xjci5jZXJ0aWZpY2Fkb3MuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwVKBSoFCGTmh0dHA6Ly9yZXBvc2l0b3Jpby5pY3BicmFzaWwuZ292LmJyL2xjci9TZXJhc2EvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnYyLmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIG8BgNVHREEgbQwgbGBHkVMT0lTSU9AQ0FNUE9TRVZPTFVUSU9OLkNPTS5CUqAcBgVgTAEDAqATExFFTE9JU0lPIERFIENBTVBPU6AZBgVgTAEDA6AQEw4yMjY3NjcwMjAwMDEyMqA9BgVgTAEDBKA0EzIwNjAyMTk2OTEwOTY5MzYwODk0MDAwMDAwMDAwMDAwMDAwMDAxNzYyNzQ0MlhTU1BTUKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBABcKWuKyIkjcgWsvDa+zjA7ncIXQDMew9h7Kr4BeX7uyINz5HQFlkJvL12PHOZiXXn8RQiH+dEBgsLuQh/1TUGUOBe3skIpEQ9oz5G1ijzxAyjIoATqTf3yw4THexrTzT+u5jM7kGs8fs2tTisN0Jl6fOwyzcpiUqU79e5vBhsRaipVBznJU3bmYqLOu+1K6OIe4sxMueDiuevKhZJBdF8ODge8o3Nh4CvA8DLjwaG0tC2RTqCnRdbcZTi5j0kX/V90cMNBfxzhHwKrmf+JUzIPsoTBMNA6NewU7pHwIMIenRcKVBWrTffWNm5x+8o3uHITledPxbi1AqhQSPsXY3F4fxK6zYUM7FGN5fA2TbJPgRDP6MB5HVv5sjh6tWzD9XwJsX9O8rRIwB85b6l41DqnP+LZKBTbRHA6AgvaoDvIwUa2tlrzVktaZ6xnsHidpre6FAjRxb5mRK+e+jtO6R2Xzdpl+PDJM3d44aaOiuzsQg8JtIOJJ19PT8iVODv04elo+ZC2mT++LmvqQf/w4dYfZdnE7wjeuBs1h0g2MOgCAZAcJ49XmXrv/nAyGHdO9IZsyeA2wOuXtO4JqQyjv4NU6YF5QGS1UOSDn7ASgqcM4Cg8oIcxXp1S7i/MdGMBEn9yCfwUZmoCJzzDPBfoa1KQ6pwKcuMwPfmcLr6uqhBSW</X509Certificate></X509Data></KeyInfo></Signature></NFe></enviNFe>

o retorno : 
<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SP_NFE_PL_008h1</verAplic><cStat>103</cStat><xMotivo>Lote recebido com sucesso</xMotivo><cUF>35</cUF><dhRecbto>2015-12-08T11:54:01-02:00</dhRecbto><infRec><nRec>351003182787943</nRec><tMed>1</tMed></infRec></retEnviNFe>
dados do retorno  

versao = 3.10
tpAmb = taProducao
verAplic = SP_NFE_PL_008h1
cStat = 103
xMotivo = Lote recebido com sucesso
cUF = SP
dhRecbto = 08/12/2015 11:54:01
infRec = NFe.Classes.Servicos.Recepcao.infRec

mas não consta na sefaz

**Comment by Eloisio** [comment]
cara eu pisei , entendi qto o retono pelo lote e vem o erro , já corrigi, valeu mesmo , exelente projeto parabens
