### ISSUE TITLE
Erro SSL/TLS

### ISSUE THREAD

**Issue by GuilhermeAlmeida94** [ZeusAutomacao/DFe.NET#830]
Quando emito muita nota com um certificado via cartão (A3), utilizando uma versão de maio do Zeus, recebo a informação que a conexão foi abortada porquê não foi possível estabelecer um canal seguro com o SSL/TLS. Já instalei os certificados raiz utilizando o programa da certsign (ele instala toda a raíz de certificados). Quando utilizo certificado em arquivo (A1) isso não acontece. Utilizo o armazenamento da senha por um banco de dados. Alguém pode me dar uma luz sobre como evitar esse problema?

**Comment by apbertoletti** [comment]
Olá @Guiphb , 

vc já deu uma olhada se o issue #822 (e relacionados) pode te ajudar em algo?

**Comment by GuilhermeAlmeida94** [comment]
É exatamente isso que anda acontecendo. Já tinha testado o 100Continue e usar Dispose mas nenhum dos dois funcionou.

**Comment by apbertoletti** [comment]
Troca uma ideia por lá então, talvez os envolvidos possam te trazer uma luz

**Comment by marcosgerene** [comment]
Duplicado #822
