### ISSUE TITLE
Tratamento de Caracteres Especiais no Texto de XML

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#831]
Boa noite pessoal,

Alguém sabe dizer se o Zeus possui algum tratamento para caracteres especiais, conforme mencionado no manual de integração da NFe ?

![8-9-2018 6-11-04 pm](https://user-images.githubusercontent.com/6843493/43926431-a47cbb4c-9c00-11e8-9cda-dab6e631e3ec.png)

**Comment by adeniltonbs** [comment]
@apbertoletti 
Não há um tratamento especial. O serializador nativo do c# para XML trata alguns casos.

**Comment by adeniltonbs** [comment]
Na biblioteca a classe responsável por serializar/deserializar XMLs é DFe.Utils.FuncoesXml

**Comment by apbertoletti** [comment]
Blz @adeniltonbs ,
Vou colocar lá então um método que já uso pra fazer este tratamento.
Valeu!

**Comment by adeniltonbs** [comment]
@apbertoletti. O próprio serializador do c# já faz o tratamento dos caracteres "<", ">", "&". Testei a emissão de uma NF-e com os caracteres <>&"' e funcionou normalmente. 
Você teve algum problema com esses caracteres, de forma a ser necessário um tratamento adicional?

**Comment by adeniltonbs** [comment]
No teste que fiz, coloquei no nome da empresa os caracteres <>&"', e, a própria bilbioteca serializou ele da seguinte forma:
![image](https://user-images.githubusercontent.com/6733483/44090653-50a537ca-9fa1-11e8-80c6-5e079d76f35d.png)

Os caracteres " e ' foram literais, mas a SEFAZ aceitou normalmente. Usei a versão 4.0.

**Comment by apbertoletti** [comment]
Obrigado pelo teste @adeniltonbs , realmente não sabia que o serializador do C# já tratava isso.

Mas na real, eu tive problemas com outros caracteres especiais. os quais nem estão nesta documentação da SEFAZ, dentre eles:

- Salto de linha (char 13, char 10)
- Alguns caracteres unicode (fruto de copy/paste originados de sites que o usuário do meu sistema fez na hora de cadastrar produtos) 
- Caracteres em branco no final da string.

Com isso, tivemos que fazer um método para tratar estes caracteres, e resolvi aproveitar pra tratar os demais mencionados na documentação da SEFAZ.

Pretendo liberar um PR disso no final de semana, caso seja útil pra mais alguém.
