### ISSUE TITLE
Falha na URL NFCe MS - QrCode 2.00

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#834]
Com QrCode 1.00 sucesso.

Com QrCode 2.00:
```
<retEnviNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>2</tpAmb><verAplic>MS_9.37.2</verAplic><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>50</cUF><dhRecbto>2018-08-13T13:12:56-04:00</dhRecbto><protNFe versao="4.00"><infProt><tpAmb>2</tpAmb><verAplic>MS_9.37.2</verAplic><chNFe>50180829615128000141650010000042241000042249</chNFe><dhRecbto>2018-08-13T13:12:56-04:00</dhRecbto><digVal>CRVyxjnov7GhZiI4btMonfoPFDk=</digVal><cStat>878</cStat><xMotivo>Rejeicao: Endereco do site da UF para a Consulta por chave de acesso difere do previsto</xMotivo></infProt></protNFe></retEnviNFe>
```

**Comment by adeniltonbs** [comment]
Boa tarde @marcosgerene 

Poderia postar o XML que foi enviado para a SEFAZ?

**Comment by marcosgerene** [comment]
Segue: [xmls.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2284797/xmls.zip)

**Comment by marcelokrol** [comment]
Sou do Paraná e o meu o qr-code esta com a mesma estrutura e esta apresentando o seguinte problema.
Segue o print direto do app de testes [Link](http://icecream.me/b779ecb63ef9a44b9139d06b06d0b6e0)

**Comment by marcelokrol** [comment]
Apenas atualizando as informações:
Atualizei os schemas e solucionou o erro citado acima. Mas agora estou recebendo cStat = 878, Motivo: Endereco do site da UF da Consulta por chave de acesso diverge do previsto. [Nova url:http://www.fazenda.pr.gov.br/nfce/consulta]
Creio que a URL do qr-code esta errada, mas de acordo com o [site da fazenda](http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97) paranaense esta correto.

**Comment by adeniltonbs** [comment]
Bom dia @marcosgerene 
Conferi seu XML e ele está correto. O problema está na SEFAZ. Tive esse mesmo problema na SEFAZ de SE e tive que enviar um e-mail relatando o problema e cobrar algumas vezes até que eles o corrigissem.

Note que as SEFAZes deveriam ter colocado o qr-code 2.0 em homologação no dia 02/07/2018 e em produção no dia 09/07/2018, conforme a NT 2016.002, versão 1.6
![image](https://user-images.githubusercontent.com/6733483/44091748-db02c90c-9fa4-11e8-91d1-645b3f920a88.png)

No meu caso, em SE, só colocaram em homologação ontem, mais de quarenta dias depois do prazo. Assim mesmo por que os pressionamos.

Veja por que seu problema também está na SEFAZ:
Na NT 2016.002, versão 1.6, nas informações de preenchimento do campo ZX02 - qrCode, informa que a url a ser utilizada deve ser obtida em http://nfce.encat.org/desenvolvedor/qrcode/:
![image](https://user-images.githubusercontent.com/6733483/44091381-a4485356-9fa3-11e8-97b8-4db817ca9b45.png)

No endereço citado na NT, para a UF de MS, temos a url: http://www.dfe.ms.gov.br/nfce/qrcode?
Essa foi a url que a biblioteca colocou no seu XML corretamente (note que eles usam a mesma url para produção e homologação, conforme está no site do ENCAT).

Ainda na NT 2016.002, versão 1.6, mostra que o campo ZX03 - urlChave deve ser preenchido segundo as urls disponibilizadas em http://nfce.encat.org/consumidor/consultenota/ 
![image](https://user-images.githubusercontent.com/6733483/44091513-1ad53908-9fa4-11e8-80d2-3ab400ffbfc6.png)

Ao acessar a url para o campo urlChave nos deparamos com a página que contém as opções a seguir:
![image](https://user-images.githubusercontent.com/6733483/44091556-3fe1a592-9fa4-11e8-99bb-a998504b6a98.png)

Ao clicarmos na opção 
![image](https://user-images.githubusercontent.com/6733483/44091591-58d0d21c-9fa4-11e8-837e-478d41c30426.png)
encontramos a URL www.dfe.ms.gov.br/nfce/consulta que é a mesma url que a biblioteca colocou no seu XML. Note que a UF de MS usou a mesma url de consulta para ambos os ambientes.

Ao analisar seu caso, você encontrou algo diferente do que mencionei, fato que o motivou a abrir o issue?

**Comment by marcosgerene** [comment]
@adeniltonbs na verdade apenas peguei meu sistema  adaptei para a versão 2.00 do QrCode (com configuração para poder "voltar", claro) para testar sua implementação.

Mas fica difícil testar qualquer coisa desse jeito, voltei para  o QrCode 1.00 e vou esperar mais um pouco para ativar o QrCode 2.00.

Atualmente estou preso no erro do SSL/TLS, vem me gerando um volume grande de suporte, assim que tiver um tempo disponível volto a focar no QrCode

**Comment by adeniltonbs** [comment]
@marcelokrol 
A url para consulta pela chave com qr-code 2.0 é www.fazenda.pr.gov.br/nfce/consulta, conforme está na página do ENCAT
![image](https://user-images.githubusercontent.com/6733483/44092405-be84541a-9fa6-11e8-8eaf-bf715df5f358.png)

Conforme a NT 2016.002, versão 1.6, para o campo ZX03 - urlChave, temos que utilizar as urls disponibilizadas em http://nfce.encat.org/consumidor/consultenota/, como mencionei na mensagem anterior.

Poderia verificar se a biblioteca está gerando uma url diferente da indicada no portal do ENCAT? 
Se a biblioteca estiver gerando a URL indicada no portal do ENCAT e mesmo assim a SEFAZ estiver rejeitando-a, a SEFAZ é quem deve fazer uma das correções a seguir:
1 - Corrigir a url no portal do ENCAT para que possamos corrigir na biblioteca;
2 - Corrigir o serviço para aceitar a url conforme divulgaram no portal do ENCAT, nesse caso sem a indicação do protocolo na url.

**Comment by marcelokrol** [comment]
Mudei a versão do qr-code para 1 e agora estou com outro retorno:
cStat: 395
Motivo: Endereco do site da UF da Consulta via QR-Code diverge do previsto. Novo endereco:http://www.fazenda.pr.gov.br/nfce/qrcode

Segue o xml

[TmpXml.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2287228/TmpXml.zip)
