### ISSUE TITLE
Retorno do método CTe.Servicos.ConsultaProtocolo()

### ISSUE THREAD

**Issue by jeisonperes** [ZeusAutomacao/DFe.NET#837]
Olá pessoal, bom dia
Analisando o retorno do método CTe.Servicos.ConsultaProtocolo() constatei que a deserialização das informações da propriedade retEvento não está acontecendo.

Notei que no xml de retorno da tag vem com nome de retEventoCTe, mas o atributo da propriedade está somente retEvento.
![image](https://user-images.githubusercontent.com/40441623/44147173-58942c98-a069-11e8-9dc9-ac61340c1889.png)

![image](https://user-images.githubusercontent.com/40441623/44147298-e1b6dd86-a069-11e8-94d9-e2433e7db6fc.png)

![image](https://user-images.githubusercontent.com/40441623/44147267-be510484-a069-11e8-8a3c-c5349dc51b7a.png)

No meu caso consegui solucionar o problema alterando o atributo [XmlElement("retEvento")] para [XmlElement("retEventoCTe")] na propriedade retEvento
![image](https://user-images.githubusercontent.com/40441623/44147314-f46334b6-a069-11e8-8c7e-22cf71834b73.png)

Abro uma PR pra isso?

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/832/files

**Comment by jeisonperes** [comment]
Obrigado @marcosgerene , não tinha visto o commit.
