### ISSUE TITLE
Pacote NuGet

### ISSUE THREAD

**Issue by orochasamuel** [ZeusAutomacao/DFe.NET#84]
Adenilton, boa noite.

Seria possível criar um pacote NuGet do projeto?

Abraços.

Samuel Rocha

**Comment by adeniltonbs** [comment]
Vou dar uma olhada nisso.

**Comment by renanoliveira0** [comment]
Adeniltonbs, fenomenal esse repositório, sobre o pacote Nuget, vc acha que vai rolar?

Estou com uma equipe aqui e estamos pensando em começar a contribuir com o projeto ativamente e utilizá-lo em nossos projetos, como o componente está? Está estável? O que você me diz?

**Comment by adeniltonbs** [comment]
Esse projeto foi desenvolvido e é utilizado em produção por nossa empresa, então é estável sim. Pela movimentação na comunidade acredito que haja um bom número de desenvolvedores utilizando a biblioteca. Nossa pretensão é contínuar a mante-la, e com a ajuda da comunidade podemos expandir para além das necessidades imediatas de nossa empresa.

**Comment by adeniltonbs** [comment]
Quanto ao pacote nuget ainda não tive tempo de ver, estamos finalizando alguns projetos e só depois disso poderei dar uma olhada nisso.

**Comment by renanoliveira0** [comment]
adeniltonbs, não foi vc que colocou esse aqui não?

https://www.nuget.org/packages/ZeusNfe/

**Comment by orochasamuel** [comment]
Está muito desatualizado esse pacote.

Acredito não ter sido o @adeniltonbs, caso contrário, já haveria alguma atualização superior à Dezembro/2015.

**Comment by robertorp** [comment]
@adeniltonbs , se quiser posso estar fazendo o pacote e atualizando o mesmo com frequência, este fim de semana mesmo faço

**Comment by adeniltonbs** [comment]
@robertorp Se puder agradeço. Vai ser de grande ajuda.

**Comment by adeniltonbs** [comment]
Quando criar o pacote, faz um pull request que aceito.

**Comment by kidchenko** [comment]
+1
