### ISSUE TITLE
DANFE nativo NFC-e cortando com muitos itens

### ISSUE THREAD

**Issue by SauloPacifico** [ZeusAutomacao/DFe.NET#840]
E aí, pessoal! Tudo certo?

Pois bem, estou enfrentando um problema ao utilizar a impressão nativa do DANFE da NFC-e pois a partir de uma certa quantidade de itens a impressão simplesmente para. Alguém aí já passou por esse problema? Sabem o que eu posso fazer para resolver isso? Obrigado!

![foto 15-08-18 16 43 33](https://user-images.githubusercontent.com/42419944/44169611-61796e80-a0ab-11e8-986d-7eb8bbbc6e20.jpg)

![foto 15-08-18 16 43 41](https://user-images.githubusercontent.com/42419944/44169616-64745f00-a0ab-11e8-8322-dd29a64796c3.jpg)

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/729
