### ISSUE TITLE
Consulta Cadastro com ERRO

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#846]
Bom dia, gostaria de saber se algum usuário está tendo problemas ao consultar cadastro com o ZEUS após as ultimas atualizações.
Desde que atualizei as ultimas versões do NUGET não consigo mais consultar cadastro.
Percebi que é um erro interno no zeus quando tentei usar o proprio código do zeus para fazer a consulta.
Se existir alguma solução por gentileza compartilhem...
Desde já agradeço.

**Comment by adeniltonbs** [comment]
@guimagcpd Testei na BA e funcionou. 
Mas creio que faltaram algumas informações a serem passadas para o pessoal poder te ajudar.
Qual UF?
Qual documento que tentou consultar?
Qual ambiente?
Que erro ocorreu?

**Comment by guimagcpd** [comment]
Adenilton obrigado pela rápida resposta...
o cenário é o seguinte...
Qual UF? = MT
Qual documento que tentou consultar? CNPJ = 02422951000184
Qual ambiente? = PRODUÇÃO
Que erro ocorreu? ERRO NO DOCUMENTO XML (1.2)
Note que o erro também ocorre usando o código fonte do ZEUS...

![captura de tela 1301](https://user-images.githubusercontent.com/11932503/44463474-d84fc380-a5e5-11e8-9f95-bd1a82c334a0.png)

**Comment by adeniltonbs** [comment]
@guimagcpd 

> Desde que atualizei as ultimas versões do NUGET não consigo mais consultar cadastro.

O problema que você está tendo não é necessariamente por conta da atualização da biblioteca, embora tenha começado a ocorrer depois disto. Provavelmente antes de atualizar a biblioteca você estava a consumir o serviço de consulta de cadastro versão 2.0 dessa UF e agora passou a consumir o mesmo serviço com a versão 4.0.

Bem, vamos ao problema:

**Por que ocorreu?**
Veja o XML enviado para a UF de MT:
```xml
<ConsCad versao="2.00" 
    xmlns="http://www.portalfiscal.inf.br/nfe">
    <infCons>
        <xServ>CONS-CAD</xServ>
        <UF>MT</UF>
        <CNPJ>02422951000184</CNPJ>
    </infCons>
</ConsCad>
```

Veja o retorno dessa UF para esse serviço:
```xml
<consultaCadastroResult xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4">
    <retConsCad xmlns="http://www.portalfiscal.inf.br/nfe" versao="2.00">
        <infCons>
            <verAplic>MT_A2RL-4.00</verAplic>
            <cStat>215</cStat>
            <xMotivo>Rejeicao: Falha no schema XML</xMotivo>
            <UF>MT</UF>
            <dhCons>2018-08-22T08:53:00</dhCons>
            <cUF>51</cUF>
        </infCons>
    </retConsCad>
</consultaCadastroResult>
```
A SEFAZ do MT está devolvendo para o serviço de consulta de cadastro, versão 4.0 um XML inválido.
Segundo o manual de orientação do contribuinte versão 6.0, o elemento raiz do XML de retorno deve ser "retConsCad" e não "consultaCadastroResult" como estão devolvendo.

A biblioteca está enviando corretamente o XML de consulta, conforme validação com esquema (o que pode ser conferido em [www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx](https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx), no entanto, a SEFAZ de MT está rejeitando com o motivo "Rejeicao: Falha no schema XML";

**Como resolver?**
Entre em contato com a UF do MT, passe esses problemas para eles, e cobre uma solução.

Obs: Embora o serviço de consulta de cadastro deles tenha a versão 4.0, isso não quer dizer que na montagem do XML deva ser passado a string "4.00" no campo versão, pois no esquema "leiauteConsultaCadastro_v2.00.xsd", que é o esquema mais recente para esse serviço no momento (os esquemas podem ser encontrados em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=), existe uma validação exigindo que esse campo seja preenchido com a string "2.00".

**Comment by adeniltonbs** [comment]
Para mais informações e testes, debuge o método NfeConsultaCadastro da classe NFe.Servicos.ServicosNFe.

No método NfeConsultaCadastro dessa classe, coloque breakpoints na linha "retorno = ws.Execute(dadosConsulta);", veja o que está sendo enviado, analise o retorno e compare com o manual de interação do contribuinte versão 6.0 http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=

**Comment by guimagcpd** [comment]
Muito obrigado a todos pelas Informações

**Comment by ThalisonSantos** [comment]
@adeniltonbs quando consulto para AL retorna isso aqui:
Envio:
`<ConsCad versao="2.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infCons><xServ>CONS-CAD</xServ><UF>AL</UF><IE>240739078</IE></infCons></ConsCad>`
Retorno:
`<retConsCad versao="2.00 " xmlns="http://www.portalfiscal.inf.br/nfe"><infCons><verAplic>SVRS20180816144937</verAplic><cStat>265</cStat><xMotivo>Rejeicao: Sigla da UF da consulta difere da UF do Web Service</xMotivo><UF>AL</UF><IE>240739078</IE><dhCons>2018-08-23T16:38:23-03:00</dhCons><cUF>27</cUF></infCons></retConsCad>`

**Comment by adeniltonbs** [comment]
@ThalisonSantos 
Abra uma nova issue para seu caso.
De toda forma, veja minha última resposta para conseguir ver se o XML que está sendo enviado a SEFAZ está de acordo com o manual de orientação ao contribuinte. Caso esteja, e ainda assim a SEFAZ estiver rejeitando, entre em contato com a SEFAZ.

**Comment by ThalisonSantos** [comment]
@adeniltonbs Bom dia,
não creio que seja um erro de xml, porque quando tentei consultar em são Paulo funcionou normal eu pesquisei sobre isso e no fórum do acbr dizia que alguns estados não tinham consulta não sei se procede.
[ConsCad.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2318396/ConsCad.zip)
