### ISSUE TITLE
Integração do repositório Zeus com o canal no Discord

### ISSUE THREAD

**Issue by apbertoletti** [ZeusAutomacao/DFe.NET#847]
Fala pessoal, tudo bem?

Não sei todos já estão sabendo, mas recentemente foi criado um canal de discussão do projeto Zeus no aplicativo Discord (https://discord.gg/n7QkAGF). Dentre muitas features, esta ferramenta permite que as conversas sejam organizadas por assunto, e também se mantenha um histórico das conversas, para os novos membros que chegam na comunidade.

Neste sentido, pra ajudar a conectar mais a comunidade com o projeto em si, surgiu a ideia de configurarmos o bot de integração entre o github do projeto Zeus e este canal. Com isso, o canal sempre seria notificado das atualizações ocorridas por aqui, ajudando a propagar novos issues, PRs, versões, etc,

Segue um vídeo que mostra esta integração em funcionamento:
https://youtu.be/D2LWN_s6cEE

Enfim, o que vcs acham desta proposta?

Abraços

**Comment by pessutti** [comment]
Acho válido! rsrs
Nós podemos testar, se ficar muito poluído, nós retiramos.

**Comment by robertorp** [comment]
Já tem muito tempo essa issue, mas ainda assim interessante, mas mesmo assim e algo que leva um certo tempo, @apbertoletti  isso vc consegue fazer sem muitos problemas ou necessita de algo?

**Comment by apbertoletti** [comment]
Olá @robertorp , posso fazer sim... eu só precisaria ter acesso ao settings do repositório do Zeus para poder gerar o webhook, conforme mencionado no vídeo tutorial.
Ou então, vocês gerarem o webhook por ai.

**Comment by robertorp** [comment]
@adeniltonbs  teria como gerar o webhook e passar via telegram ou por aqui se não tiver problema e claro, para estarem fazendo essa integração com o discrod
