### ISSUE TITLE
Cancelamento NFe

### ISSUE THREAD

**Issue by itsguicosta** [ZeusAutomacao/DFe.NET#85]
Estou tentando fazer um cancelamento de uma NFe para o estado do PR porém não está dando certo.

Quando vou realizar o cancelamento, aparece o seguinte erro:

Erros da validação: O atributo 'versao' é inválido - O valor '3.10' é invalido dependendo do tipo de dados 'http://www.portalfiscal.inf.br/nfe:TVerEnvEvento'
- Falha na restrição Pattern.

Este erro ocorre independente da versão que escolha, desde 1.0 a 3.10.

Vocês sabem alguma forma de corrigir este problema?

Muito obrigado.

**Comment by Eloisio** [comment]
estou tendo o mesmo erro para SP

**Comment by itsguicosta** [comment]
Consegui resolver o problema do cancelamento de NFe para o estado do PR.

@Eloisio, você pode tentar alterar a classe Enderecador no NFe.Servicos.

Fiz a mesma alteração que o @pedroegolin fez neste post, onde o problema era para o MT: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/47

Alterei no PR onde estava a versão 3.10 nesta linha

```
endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve310, TipoAmbiente.taHomologacao, emissao, Estado.PR, ModeloDocumento.NFe, "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento?wsdl"));
```

para versão 1.00

```
endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEvento, VersaoServico.ve100, TipoAmbiente.taHomologacao, emissao, Estado.PR, ModeloDocumento.NFe, "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento?wsdl"));
```

**Comment by adeniltonbs** [comment]
interessante, pois no portal da NFe consta a versão deste serviço como 3.10 (http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#PR)

Está confirmado que a versão deste serviço é realmente 1.00 (se assim for enviarei um commit com essa alteração)?
e para o ambiente de produção também é 1.00?

**Comment by marciojmuller** [comment]
O mesmo problema acontece para o RS a versão correta é 1.00 nos dois ambientes.
