### ISSUE TITLE
Falha na URL NFCe PR

### ISSUE THREAD

**Issue by vasisti** [ZeusAutomacao/DFe.NET#851]
Ola pessoal boa tarde, saudações. 
Na geração da Url do qrcode para versao 4.00 no estado do Parana, a biblioteca esta gerando como se fosse 3.10. tanto em producao como em homologacao.

conforme manual Encat.
(PARANA)
URL QRCODE NFCe 3.10 -http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?
URL da versão 3.10 continua ativa, até o encerramento dessa versão.
URL QRCODE NFCe 4.00 – http://www.fazenda.pr.gov.br/nfce/qrcode?

mas na versao 4.00 esta trazendo esta url:  http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?

**Comment by robertorp** [comment]
gera um xml para nós fazendo o favor e poste uma print do código que esta usando para obter o qrcode , esta passando a versão corretamente?

**Comment by vasisti** [comment]
[1-env-lot_.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2324008/1-env-lot_.zip)
Ola bom dia, gerei o xml na biblioteca na versao 1 do qrcode.

**Comment by vasisti** [comment]
Ola Roberto boa noite, estou homologando a versao 2.0 do qrcode, e testando a biblioteca para o estado do PR, a URL de consulta=  <urlChave>www.fazenda.pr.gov.br/nfce/consulta</urlChave> esta faltando o http:// e nao autoriza a nfce.  está no metodo CarregarURls ao carregar a variavel  urlsConsultaHomologacaoEProducao2. sem mais.
