### ISSUE TITLE
Possibilidade de carregar a classe procEventoNFe com stream

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#852]
Na classe nfeProc tem a extensão para carregar arquivos XML do modo stream com CarregardeStream gostaria de ver se tem a possibilidade de criar o mesmo método para a classe procEventoNFe visto que alguns estados como SP estão retornando o arquivo XML de evento com acentuação gráfica e colocando para carregar o XML em modo stream resolve esse problema.

**Comment by apbertoletti** [comment]
> alguns estados como SP estão retornando o arquivo XML de evento com acentuação gráfica

@leandrossantos , você poderia detalhar melhor este problema? Se possível, enviar um print (full screen) com a mensagem de erro aparecendo.

**Comment by leandrossantos** [comment]
@apbertoletti estou anexando XML e a mensagem de erro retornanda no momento de leitura do XML pelo app teste.
![screenshot_1](https://user-images.githubusercontent.com/6373944/44685239-02a3e580-aa19-11e8-9ddf-bf0ced04c552.png)

[35180803655789000107550010000007821108817268-CC-1-procEventoNfe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2325574/35180803655789000107550010000007821108817268-CC-1-procEventoNfe.zip)

**Comment by leandrossantos** [comment]
@apbertoletti  Veja os prints abaixo:
- Achei a classe de extensão no projeto Zeus como pode ver abaixo;
![screenshot_2](https://user-images.githubusercontent.com/6373944/44687183-87ddc900-aa1e-11e8-9ed0-ac4c1a6a63aa.png)

- O que estou precisando é ter essa função abaixo:
![screenshot_3](https://user-images.githubusercontent.com/6373944/44687190-8d3b1380-aa1e-11e8-98d4-c23c68eda3b5.png)

- Para poder ser usada no XML de Evento, assim como tem para ser usada no XML de NFe/NFCe
![screenshot_4](https://user-images.githubusercontent.com/6373944/44687194-91673100-aa1e-11e8-941e-6ee3857d32cd.png)


PS: Acho que assim ficou bem explicado o que estou querendo, rsrs

**Comment by leandrossantos** [comment]
@apbertoletti sim meu amigo o problema são eles mesmo, a questão que se você notar eles já vieram assim do servidor de SP, esse é o problema, por isso que dei a ideia de carregar o XML em stream pois pode ser que assim carregue o arquivo sem erro.

**Comment by robertorp** [comment]
Criado o método, basta testar
