### ISSUE TITLE
Fast Report (Off Topic)

### ISSUE THREAD

**Issue by thiagovalim** [ZeusAutomacao/DFe.NET#861]
Olá pessoal, não sei se este é o local correto para postar este assunto mais se puderem me ajudar eu agradeço. Atualmente estou utilizando esta biblioteca para geração de nfes e tenho gostado das impressões em fast reports e desejo adquiri-lo. Eu gostaria de saber de quem usa Fast Report, como é o funcionamento da distribuição das dlls, se a curva de aprendizado é grande (para quem vem do crystal reports), se vale a pena adquirir com código fonte e a versão web e se funciona em aplicativos mobile e Asp .net core. Obrigado pela atenção.

**Comment by marcosgerene** [comment]
Eu uso para aplicação desk e já testei pra Web.

Pra desktop é lindo, ferramente excelente. Pra web achei pesado
