### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by lucas-explica** [ZeusAutomacao/DFe.NET#862]
Pessoal, como vocês fazem pra distribuir o aplicativo de vocês com está licença, alguém possui alguma informação ou dica, estou com um pouco de receio em usar devido a isto.

**Comment by adrbarros** [comment]
Conforme descrição do Projeto:

Biblioteca gratuita para Geração de NFe 3.10/4.00, NFCe 3.10/4.00, MDF-e 3.0 e CT-e 3.0 e consumo dos serviços necessários à sua manutenção, conforme descritos em http://www.nfe.fazenda.gov.br/portal/principal.aspx, https://mdfe-portal.sefaz.rs.gov.br e www.cte.fazenda.gov.br/portal.

A biblioteca foi desenvolvida em C# utilizando como IDE o Visual Studio Community 2013 e é compatível com o Visual Studio Community 2015 e 2017. Atualmente utiliza o .NetFramework na versão 4.5.

Está licenciada sobre a LGPL (https://pt.wikipedia.org/wiki/GNU_Lesser_General_Public_License).

**Comment by marcosgerene** [comment]
> Está licenciada sobre a LGPL (https://pt.wikipedia.org/wiki/GNU_Lesser_General_Public_License).
