### ISSUE TITLE
Manifesto do Destinatário

### ISSUE THREAD

**Issue by facilita-tecnologia** [ZeusAutomacao/DFe.NET#864]
Olá Senhores
Alguém sabe qual parâmetro utilizo para buscar as nfe emitidas para meu CNPJ nos últimos 3 meses

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/632#issuecomment-360754161

![image](https://user-images.githubusercontent.com/15945003/45002152-1f589400-afaa-11e8-93ae-3cf056e359d6.png)

https://github.com/ZeusAutomacao/DFe.NET/issues/568#issuecomment-339607121
