### ISSUE TITLE
Problema de integração SVAN - Estado do PA

### ISSUE THREAD

**Issue by rodrigobertero** [ZeusAutomacao/DFe.NET#865]
Desde a data de 03/08/2018 não estamos conseguindo integrar NF-e com o servidor do SVAN. O XML valida corretamente no site https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx. Isto está acontecendo tanto na 3.10 como na 4.0. O retorno do código` var results = Invoke("nfeAutorizacaoLote", new object[] { nfeDadosMsg });` fica nulo. Certificado está válido e em outros estados a emissão acontece normalmente.
Tentamos atualizar o wsdl sem sucesso, alguém com algum problema semelhante?

XML e wsdl atual anexado

[xmlex.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2350618/xmlex.txt)
[NFeAutorizacao4WSDL.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2350621/NFeAutorizacao4WSDL.txt)

**Comment by leandrossantos** [comment]
@rodrigobertero boa noite, eu estava com esse problema, no PA e MA que usam o servidor SVAN, mais peço que você atualize os fontes da DLL ai que fiz isso aqui e deu tudo certo, clientes conseguindo transmitir normalmente na versão 4.00

**Comment by rodrigobertero** [comment]
@leandrossantos bom dia, foi atualizado ontem para a ultima atualização disponível aqui de master e continuamos com o problema, tanto para 3.1 quanto para 4.0. Quais DLLs atualizou e teve sucesso?

**Comment by thiagovalim** [comment]
Eu também estava com este mesmo problema, apenas atualizei as fontes e recompilei o projeto

**Comment by rodrigobertero** [comment]
Fizemos a atualização do projeto, porém, retorna mensagem de erro:
Sem comunicação com o serviço NFeAutorizacao:
O nome remoto não pôde ser resolvido: 'hom.sefazvirtual.fazenda.gov.br'

**Comment by rodrigobertero** [comment]
Em outro momento retorna erro de:
- Sem comunicação com o serviço NFeAutorizacao: A conexão subjacente estava fechada: Erro inesperado em um recebimento. 

O que poderá ser isto?

**Comment by MoacirKuhn** [comment]
Este item já foi resolvido. 
A solução estava no envio de 2 informações ao componente ZEUS:
ServiceConfig.Vesaolayout=Version;
ServiceConfig.ProtocolodeSeguranca=ServicePointManager.SecurotyProtocol;
