### ISSUE TITLE
QRCode 2.0 

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#867]
Bom, o DFe.NET já tem suporte para QRCode 2.0

Mas existem problemas talvez no seu estado.

Porque Roberto?

Bom vou dar um exemplo do estado que moro Goiás
Passei por uma dor de cabeça imensa para emtir nfc-e com qrcode 2.0 em homologação aqui, pois a sefaz não usa o mesmo URL consulta para produção e homologação (ok até ai Roberto isso é normal) 

Sim, normal as vezes alguns estados colocarem diferente o de produção e homologação, mas eles deveriam no mínimo avisar nos desenvolvedores né? 

Se eles avisam não achei em local nem um.

![image](https://user-images.githubusercontent.com/10251705/45511561-b922fc80-b773-11e8-8609-71188efa29e1.png)

Vejam a imagem diz que é para Homologação e  produção né? Em Goiás não é. Olha como esta no código fonte do zeus para autorizar
![image](https://user-images.githubusercontent.com/10251705/45511690-0d2de100-b774-11e8-87dc-093143a750d2.png)

Logo então pode ser que algum estado apresente problemas em homologação ou produção. 

Agora seu estado esta com problema? 
Reporte aqui nessa issue mesmo, e vamos trabalhar juntos na solução do mesmo. 
Se possível ache a URL de consulta correta do Estado seu e me mande que ai diminui o trabalho nosso de ter que correr atrás da url. 

Nos estados em que a empresa que trabalho atua esta funcionando tudo OK, 
lembre-se isso e uma comunidade, vamos nos ajudar a chegar em um resultado magnifico, trabalhando juntos chegamos lá e de forma gratuita. 

Roberto como você achou a url de consulta de Goiás se você não achou em lugar nem um?
Haha Teste.. Peguei da url de qrCode de homologação e joguei lá e funcionou!! kkkk .. Não e zoeira ein e verdade, e fico muito puto com isso.  

Xml emitido agora no momento do post com a url de consulta que não consta no site, como falei. 
[xml Sefaz GO.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2380798/xml.Sefaz.GO.txt)

![image](https://user-images.githubusercontent.com/10251705/45512377-f5575c80-b775-11e8-8afe-d15169428d15.png)

Não tem muito o que fazer nestes casos onde não conseguimos a informação de maneira fácil e acessível. Talvez até tenha em algum local a informação necessária. Mas não achei na época e nem agora. 

Então o negocio é, temos que nos ajudar postando qualquer problema de qrcode 2.00 aqui, e se possível como falei postem a url de homologação e produção junta, para agilizar o processo.

**Comment by Bertoncini** [comment]
Boa tarde amigos,

na pagina http://www.rsys.com.br/cliente/Host/WebServicesNFe.xml estou verificando e as url's estão atualizadas.

estarei atualizando os fontes do DFe.NET local pois estou com versão desatualizada, e estarei realizando os ajustes entre hoje e amanhã estarei subindo as correções, mas caso alguém queira realizar as alterações para subir ainda hoje fique a vontade só me avise.

**Comment by marcosgerene** [comment]
@robertorp 

Uso RN e MS, como estão atualmente?

**Comment by srwil** [comment]
Bom dia, em PE as URLs que estão no projeto estão corretas porem na NFC-e a urlChave que aparece impressa é _http://nfcehomolog.sefaz.pe.gov.br/nfce-web/consultarNFCe_ que esta certa para o usuário visitar e digitar a Chave, mas no QRCode fica:

_http://nfcehomolog.sefaz.pe.gov.br/nfce-web/consultarNFCe?p=26180905068001000191650010000025671000000000|2|2|1|d86d33e50661d471ca2b5a94a951da7cc8f813ea_
e deveria ser:
_http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta?p=26180905068001000191650010000025671000000000|2|2|1|d86d33e50661d471ca2b5a94a951da7cc8f813ea_
para ter acesso direto ao documento.

O que posso fazer para ficar correto?

Para produção as URLs são as mesmas, sem o **_homolog_**

**Comment by adeniltonbs** [comment]
@srwil Bom dia,
Onde você obteve a url [http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta](http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta)?

De acordo com a NT 2016.002, versão 1.61, as urls para qr-code e consulta devem ser informadas como estão no site do ENCAT. Conferi as urls para PE e estão de acordo com o ENCAT.
Se notou algum erro nas urls da SEFAZ, por favor reporte para SEFAZ, para que eles corrijam no ENCAT. Depois que corrigirem, solicite a alteração na biblioteca.

Seguem recortes da NT 2016.002, versão 1.61 que falam sobre as urls para qr-code e consulta:

![image](https://user-images.githubusercontent.com/6733483/45624529-f54ea980-ba60-11e8-82a6-f7c12d6d8b04.png)

![image](https://user-images.githubusercontent.com/6733483/45624537-fa135d80-ba60-11e8-865f-7aa365774ffd.png)

![image](https://user-images.githubusercontent.com/6733483/45624545-03042f00-ba61-11e8-8249-5604badc5bbb.png)

**Comment by srwil** [comment]
A URL esta no site _https://www.sefaz.pe.gov.br/Servicos/Nota-Fiscal-de-Consumidor-Eletronica/Paginas/Webservices-Producao-e-Homologacao.aspx_

Aqui também tem:
http://nfce.encat.org/desenvolvedor/url-por-uf-utilizada-para-consulta-chave-qr-code-versao-2-0/

Estamos entrando em contato com a SEFAZ-PE pois aparentemente as URLs estão trocadas no site do ENCAT.

**Comment by robertorp** [comment]
MS = OK by: @marcosgerene

**Comment by robertorp** [comment]
TO = OK by: Eu

**Comment by Yamcol** [comment]
![url](https://user-images.githubusercontent.com/39630209/45844545-2812cf00-bcf9-11e8-84b9-dad00d862651.jpg)

No caso das UFs do MA e MA, precisei colocar http:// na frente dos endereços. No site http://nfce.encat.org/desenvolvedor/qrcode/ está sem.

**Comment by robertorp** [comment]
@Yamcol feito a correção.

Preciso de um feedback seu se esta realmente funcionando emissão de NFC-e 4.00 com QRCODE 2.0 para estes dois estados MA e AM

**Comment by Yamcol** [comment]
NFC-e 4.00 com QRCODE 2.0 funcionando:
PA = OK
MA = OK
AM = OK
PI =  OK
AM =Ok

**Comment by glaubermarcelino-zz** [comment]
O ambiente de homologação MA me parece que não esta contemplando o qrCode2.0, alguém pode me confirmar, estou recebendo erro
![5082986a-d668-4400-ab3c-2676ea73a9cb](https://user-images.githubusercontent.com/7974807/45919600-3cc4a380-be6e-11e8-9c02-eaca61b23ebe.jpg)

**Comment by marcosgerene** [comment]
RN e MS em produção aqui.

**Comment by robertorp** [comment]
ES = Ok by: @Bertoncini  issue -> https://github.com/ZeusAutomacao/DFe.NET/pull/876

**Comment by rodrigofornasier** [comment]
Boa noite.
Alguém sabe informar se NFC-e 4.0 com QRCode 2.0 está funcionando no RS ?
Se alguém precisar de um certificado pra teste eu consigo. Não posso testar ainda pois não terminamos a implementação.

**Comment by ernanielyjr** [comment]
To testanto no RS e nao esta rolando. To com a versao mais atualizada

**Comment by marcosgerene** [comment]
@ernanielyjr https://github.com/ZeusAutomacao/DFe.NET/issues/904#issuecomment-437157586 RS OK

**Comment by michelbalthazar** [comment]
- Alguém sabe dizer se BA está funcionando QR Code 2.0 em homologação? Estou recebendo 
         - Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto
                 - Estou usando a url de consulta - http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx

- SP está funcionando QR Code 2.0, tanto produção como homologação.

**Comment by michelbalthazar** [comment]
- Acabei de validar, Bahia também está funcionando QR Code 2.0

**Comment by LosDeveloper** [comment]
> O ambiente de homologação MA me parece que não esta contemplando o qrCode2.0, alguém pode me confirmar, estou recebendo erro
> ![5082986a-d668-4400-ab3c-2676ea73a9cb](https://user-images.githubusercontent.com/7974807/45919600-3cc4a380-be6e-11e8-9c02-eaca61b23ebe.jpg)

Estou como este mesmo problema aqui para p estado do AM!
Conseguiu resolver? como resolveu?
