### ISSUE TITLE
Carta Correção DF

### ISSUE THREAD

**Issue by john182** [ZeusAutomacao/DFe.NET#868]
Verifiquei se pular a parte de validação do XML a carta e transmitida normalmente, porém ao validar nos schemas da erro.

erro :

TEnvEvento não localizado

**Comment by robertorp** [comment]
manda o xml gerado XML 
manda print do erro 

fontes atualizados?

**Comment by john182** [comment]
![image](https://user-images.githubusercontent.com/10438644/45560009-59336100-b81a-11e8-8d05-82aa2b2890e7.png)

ultima versão

**Comment by robertorp** [comment]
Bom dia, isso foi resolvido?
