### ISSUE TITLE
DOWNLOAD XML

### ISSUE THREAD

**Issue by gercenio** [ZeusAutomacao/DFe.NET#87]
Bom dia amigo, em primeiro lugar meus parabéns pelo projeto, bom gostaria de saber se existe algum método ou forma de realizar o download do xml apos o envio a sefaz utilizando á chave da nota você tem alguma coisa nesse sentido?

**Comment by adeniltonbs** [comment]
Bom dia gercenio, tem sim. O emitente e o destinatário da NFe, além dos CNPJs indicados na própria NFe pelo emitente desta, são autorizados a fazer o download do XML, utilizando seu certificado digital.

A biblioteca implementa o consumo deste serviço e na aplicação de demonstração de uso tem um exemplo disso.

Sugiro dá uma olhada nas demais regras para consumo deste serviço no Manual de Orientação do Contribuinte - versão 6.00 - Minuta, disponível em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=
