### ISSUE TITLE
Rejeição 385

### ISSUE THREAD

**Issue by guimagcpd** [ZeusAutomacao/DFe.NET#872]
Boa noite amigos...
Estou obtendo o erro 
Rejeição 385: Grupo de tributação ICMS900, informando dados do ICMS-ST

Acontece que estou fazendo uma NFC-e e nela não informo o grupo de ICMS apenas aponto a CSOSN 900
e mais nada...
só que a DLL está criando os demais campos com valor zero como apontado neste post

https://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-385-grupo-de-tributa%C3%A7%C3%A3o-icms900-informando-dados-do-icms-st-como-resolver-216.html

**Comment by apbertoletti** [comment]
@guimagcpd 

mande um print do seu trecho de código onde está preenchendo este CSOSN900

**Comment by guimagcpd** [comment]
![image](https://user-images.githubusercontent.com/11932503/45772606-2f14e100-bc16-11e8-9f63-1fb8950c236f.png)

Note que só é preenchido os campos se estas VARIAVEIS estiverem com valor maior que zero.
If CDec(CType(row("vBC"), String)) > 0 Then
          

 If CDec(CType(row("vBCST"), String)) > 0 Then

**Comment by apbertoletti** [comment]
Não manjo muito da sintaxe VB.Net, mas você já tentou colocar um breakpoint ai neste código, a fim de debugar se estas propriedades do Zeus (pICMSST, vBCST, vICMSST, etc) realmente estão ficando nulas, a fim de não gerar as tags no XML ?

**Comment by guimagcpd** [comment]
Sim, todos os testes ja foram feitos.
A melhor forma de obter o mesmo resultado... é
você fazer uma NFS-e ai,  com CSOSN 900
e NÃO informar os campos base como EU não estou informando...
e então obtera o mesmo problema...
Desde já agradeço o retorno.

**Comment by apbertoletti** [comment]
Por favor, envie aqui o XML que está sendo rejeitado

**Comment by apbertoletti** [comment]
Conseguiu resolver @guimagcpd ? O que era?

**Comment by guimagcpd** [comment]
boa tarde nao foi resolvido, não é suportado envio de XML por este canal

**Comment by apbertoletti** [comment]
Renomeio ele para txt e anexo por aqui

**Comment by guimagcpd** [comment]
[VSD1.tmp.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2406063/VSD1.tmp.txt)

**Comment by apbertoletti** [comment]
Cara, se você notar no manual da NFe/NFCe, notará que estas tags do CSOSN900 que vc está alimentando com zero são todas opcionais.

![image](https://user-images.githubusercontent.com/6843493/45907174-519d2a80-bdcd-11e8-8aa5-bc43411ad882.png)


E existe uma regra geral no layout que diz o seguinte: sempre que uma tag opcional tiver valor 0 (zero) ou "" (vazia), a mesma NÃO deverá ser gerada. 

![image](https://user-images.githubusercontent.com/6843493/45907310-d425ea00-bdcd-11e8-9309-4e9dd52ed2d4.png)


Sendo assim, para que o Zeus não gere estas tags, basta você setar nulo (null) para elas.
