### ISSUE TITLE
Download NFe

### ISSUE THREAD

**Issue by FabioRoesler** [ZeusAutomacao/DFe.NET#874]
Boa tarde a todos.
Estou tentando baixar uma NFe pelo app teste, porem ele retorna o erro 410. "Rejeicao: UF informada no campo cUF nao e atendida pelo Web Service". Testei varias configurações de WebService, porem não adiantou. Alguem podeia me dar uma ajuda. Meu estado é o RS. Segue print das configurações.
![imgprint](https://user-images.githubusercontent.com/24945244/45932769-fcd9eb00-bf57-11e8-9800-7b0de1538962.jpg)

**Comment by orochasamuel** [comment]
Experimente deixar tudo na versão 1.0 e marca TLS 1.2

**Comment by FabioRoesler** [comment]
Testei com estas configurações, porem agora esta dando erro de versão 1.00 não disponível para UF RS.
Fiz mais alguns teste e continua o mesmo erro.

**Comment by FabioRoesler** [comment]
Sera que este problema esta relacionado ao URL do webservice do RS?
