### ISSUE TITLE
Testar NFe em vários estados

### ISSUE THREAD

**Issue by thiagovalim** [ZeusAutomacao/DFe.NET#877]
Olá pessoal, alguém sabe como posso testar a NFe/NFc em outros estados, pois minha empresa e meu certificado é de São Paulo e não os webservices de outros estados não aceitam juntamente com cnpj e ie, eu tentei utilizar os dados cnpj e ie de clientes de outros estados e também não deu certo.

**Comment by adrbarros** [comment]
Boa tarde, você pode pegar o certificado de algum cliente de outro estado para testar em ambiente de homologação. A princípio é o único jeito que eu conheço (Ter um certificado válido em cada Estado)

**Comment by robertorp** [comment]
veja -> https://github.com/ZeusAutomacao/DFe.NET/issues/867
