### ISSUE TITLE
Rodar no Ubuntu e Mac OS

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#88]
Boa noite Adenilton, tudo bem?

Estou querendo portar minha aplicação para Ubuntu e MacOS recompilando ela no Mono.

Fiz um rápido teste na aplicação em um VM rodando Ubuntu e só não consegui usar a Interop do Excel.

Existe alguma recurso utilizado no seu componente que não possa ser utilizado em Ubuntu ou Mac OSX? 

Obrigado, Marcos

**Comment by adeniltonbs** [comment]
marcos, boa tarde. Recomendo você abrir o projeto no visual studio e dar uma olhada nas dependências das bibliotecas NFe.Classes, NFe.Servicos, NFe.Utils, NFe.Wsdl e Nfe.Impressao.

Com a lista das dependências em mãos, você deve pesquisar na documentação/comunidade do Mono para ver se alguma dessas dependências não é suportada para as plataformas citadas por você.
