### ISSUE TITLE
NFCe Danfe Fast

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#880]
Bom dia pessoal,
![2018-10-03](https://user-images.githubusercontent.com/22593917/46412645-7e1e4400-c6f5-11e8-8152-c61876050c68.png)
 o que é esse copy name que esta saindo no danfe da nfce?

**Comment by orochasamuel** [comment]
Provavelmente alguma "chave" que deveria ter sido substituída e não está sendo.

![image](https://user-images.githubusercontent.com/15462690/46413763-0aca0180-c6f8-11e8-96a3-f397508f381e.png)

Fonte: https://github.com/ZeusAutomacao/DFe.NET/blob/master/NFe.Danfe.Fast/NFCe/NFCe.frx

**Comment by ThalisonSantos** [comment]
começou a aparecer depois da ultima atualização

**Comment by ThalisonSantos** [comment]
como resolver esse problema?

**Comment by orochasamuel** [comment]
> como resolver esse problema? https://github.com/ZeusAutomacao/DFe.NET/pull/881

**Comment by ThalisonSantos** [comment]
valeu @samuelrochaoliveira

**Comment by orochasamuel** [comment]
De nada.

**Comment by marcosgerene** [comment]
Acredito que isto esteja ligado a sua versão do Fast Reports ou seu .frx está zuado... o CopyName ai é pra dizer se é via do consumidor ou do cliente, até então não vi mais reclamações disso, e a impressão é usada em larga escala...

**Comment by ThalisonSantos** [comment]
@marcosgerene mas ai no trecho do código que samuelrochaoliveira esta mostrando o parâmetro não esta sendo passado

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/pull/881#discussion_r225622727

>A alteração faria sentido se fosse mudado para imprimir a via de outra forma, somente deixar o objeto de texto em branco não é o ideal... se não for descrever qual é a via então o certo seria remover o objeto "desnecessário".
>
>De qualquer forma acredito que o problema está relacionado à versao do fast ou ao .frx ou ate mesmo à versão do Zeus da issue que resultou nisso.
>
>PrintSettings.CopyNames="Via Consumidor&#13;&#10;Via Consumidor&#13;&#10;Via do Estabelecimento"

Vou reabrir seu issue para quem alguém analise, mas o PR do @samuelrochaoliveira simplemente deixa um texto em branco, esta não é a solução esperada neste caso.

**Comment by ThalisonSantos** [comment]
@marcosgerene vou baixar os fontes atuais e testar aqui. Aproveitando seria possivel alterar danfe fast da nfe os campos vUnit e qtd para 4 casas decimais assim como é na nfce?

**Comment by marcosgerene** [comment]
@ThalisonSantos somente se for configurável. Faça o PR com configuração que testo

**Comment by ThalisonSantos** [comment]
consegui resolver o problema era o fast report
