### ISSUE TITLE
464 - Rejeicao: Codigo de Hash no QR-Code difere do calculado

### ISSUE THREAD

**Issue by ivaldojunior** [ZeusAutomacao/DFe.NET#882]
Olá, boa tarde.

Estou tendo um problema para emitir nota NFC-e especificamente deste cliente do estado de MT, alguém pode me dar uma luz ai?

464 - Rejeicao: Codigo de Hash no QR-Code difere do calculado

Já solicitei um novo CSC , revogamos o anterior... Tem um problema de fuso horário para o estado de MT será que seria isso? 
A versão do serviço é 4.0.

Obrigado

**Comment by robertorp** [comment]
Csc esta errado. 
Você pode ter pego o CSC de homologação e usado em produção mas o de produção e diferente do de homologação. 

Homologação tem CSC próprio 
Produção tem CSC próprio 

Fuso horário também pode acontecer problema mas não esse ai. (Bom pelo menos a mensagem tem nada a ver.. mas vindo de sefaz tudo é possível não descarte nada)
