### ISSUE TITLE
SEFAZ PR - Erro retorno NFeRetAutorizacao - java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by marcosmarchiore** [ZeusAutomacao/DFe.NET#883]
Olá pessoal.
Estou desde ontem 09/10/2018 as 19h com o retorno de erro no webservice da receita do Paraná.

A chamada do NFeAutorizacao esta retornando 103

Já o NFeRetAutorizacao esta retornando java.lang.reflect.UndeclaredThrowableException

Protocolo de segurança SSL3

Fiz um teste mudando o protocolo de segurança para TLS1.2 dai o retorno do NFeRetAutorizacao e 
105 Lote em Processamento, alguém está com esta dificuldade na receita do PR. 

E porque o metodo NFeAutorizacao funciona com o protocolo SSL3 e o NFeRetAutorizacao não funciona ?

**Comment by robertorp** [comment]
Se o retorno e java.lang e porque algo deu muito ruim lá na sefaz. Aguarde. Ou ligue para lá e questione isso.

**Comment by marcosmarchiore** [comment]
Exatamente isso ai, fizeram mercadoria lá e colocaram em produção.
Vou considerar como fechado Ok.
