### ISSUE TITLE
SEFAZ GO - Rejeição: XML da área de dados com codificação diferente de UTF-8

### ISSUE THREAD

**Issue by devpedrofranco** [ZeusAutomacao/DFe.NET#886]
Olá,
 Estou realizando uma transmissão de NF-e através de uma API com o .NET Framework 4.6.1 e estou recebendo a seguinte resposta da SEFAZ: 

```
{
    "versao": "4.00",
    "tpAmb": 2,
    "verAplic": "GO4.0",
    "cStat": 402,
    "xMotivo": "Rejeição: XML da área de dados com codificação diferente de UTF-8",
    "cUF": 52,
    "dhRecbto": "2018-10-11T13:08:47-03:00",
    "infRec": null,
    "nRec": 0,
    "tMed": 0,
    "protNFe": null
}
```
Já verifiquei o arquivo XML gerado e validei em um site para UTF-8 e aparentemente está ok, verifiquei as informações  que estavam sendo passadas para a nota apesar de UTF-8 permitir acento removido todos que existiam.

O que pode estar ocasionando esse erro?

**Comment by robertorp** [comment]
coloca para enviar como sincrona.. no lugar de assincrono..

**Comment by devpedrofranco** [comment]
olá, acredito já estar enviando sincrona, segue forma como estou enviando...
`var retornoEnvio = servicoNfe.NFeAutorizacao(model.Serie, IndicadorSincronizacao.Sincrono, new List<NFe.Classes.NFe> { nfpe }, true);`

**Comment by robertorp** [comment]
coloca false para zip.. 
não sei se a sefaz GO já padronizou o zip deles, mas antigamente não tinha padrão nem um (antes da nf-e 4.00) ai sempre que ia transmitir zip , dava retorno null

**Comment by robertorp** [comment]
Aqui a nfc-e uso ela síncrona para todos os estados, e funciona perfeitamente pelo menos ate o momento em todos estados que atuo esta funcionando. Acho mais fácil e pratico.

**Comment by devpedrofranco** [comment]
Bacana, deu certo!! 
As notas que vou gerar é para produtor então precisa ser NF-e, mas deu certo com o false para compactação... 
O sistema será para envio nacional de acordo com a Fazenda do Produtor... todos os estados aceitam sem ser compactado né?

**Comment by robertorp** [comment]
Sim. Todos aceitam.

**Comment by devpedrofranco** [comment]
Estou recebendo um retorno aqui agora... aproveitar um pouco de ti que está respondendo rapido... rs

Rejeição: NF-e sem grupo do PIS

Verifiquei aqui e no Manual do Contribuinte é opcional o PIS/COFINS em primeiro momento na minha aplicação não tera essas informações.... a parte de PIS por produto nao preenchi no inclusão do det, voce sabe de alguma outra configuração pra nao cair nessa validação?

**Comment by robertorp** [comment]
NF-e e obrigatório ter pis e cofins, NFC-e e opcional

**Comment by devpedrofranco** [comment]
Como é nota para produtor o PIS/COFINS está descrito como opcional na documentação. Verifiquei com pessoal aqui que tem a transmissao feita em Delphi e realmente é opcional. Eles enviam sem PIS/COFINS, mas nao souberam me passar se existem algum campo pra validar essa questão.

**Comment by robertorp** [comment]
Aí não sei. Veja o XML que esse ai em Delphi e gerado como o xml e gerado. E tente replicar preenchendo as mesmas informações. Se possível compartilhe o XML com nós para eu entender, pois nunca trabalhei com NF-e para produtor.
