### ISSUE TITLE
Ler o ICMS de um XML carregado para o objeto do tipo NFe

### ISSUE THREAD

**Issue by thomasthbm** [ZeusAutomacao/DFe.NET#889]
Para ler o ICMS da Nota, eu preciso antes saber qual é o Tipo de ICMS, para poder fazer o CAST corretamente.
Estou implementando da seguinte forma:

var icms = _nfe.infNFe.det[0].imposto.ICMS.TipoICMS as ICMS40;

Como posso fazer para obter o Tipo de ICMS e so depois fazer o CAST?

Alguem pode me ajudar?

Obrigado!

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/760

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/760#issuecomment-393336054

``` 
ICMSBasico icmsBasico = (ICMSBasico) meuobjetoNFe..infNFe.det.imposto.ICMS.TipoICMS;
ICMSGeral icmsGeral = new ICMSGeral(icmsBasico); 

var cst = icmsGeral.CST;
var base = icmsGeral.vBC;
```

**Comment by thomasthbm** [comment]
Muito obrigado! Resolveu o meu problema!
Eu percebi que o Cofins tem a mesma característica. A lógica para leitura seria a mesma?

Obrigado!

**Comment by marcosgerene** [comment]
@thomasthbm 
> Eu percebi que o Cofins tem a mesma característica. A lógica para leitura seria a mesma?

Sim, foi implementado no PR785 pelo @apbertoletti

**Comment by ThalisonSantos** [comment]
@marcosgerene e no CTe como faz?

**Comment by marcosgerene** [comment]
@ThalisonSantos não sei se o CTe tem isso, não uso o CTe do Zeus, uso o do ACBr... abra uma nova issue e marque o @robertorp, acredito que ele vai saber te explicar
