### ISSUE TITLE
NFe-C em São Paulo

### ISSUE THREAD

**Issue by gercenio** [ZeusAutomacao/DFe.NET#89]
@adeniltonbs  bom dia, estou com uma duvida a respeito da implementação da biblioteca aqui no estado de SP: aqui existe o uso do equipamento SAT, sendo assim sei que talvez a duvida seja mais fiscal do que sistema de qualquer forma apenas para deixar registrado para os demais colegas minha pergunta e podemos usar a sua biblioteca utilizando apenas os servidor de NFe-C e esquecendo do SAT?

**Comment by leandrossantos** [comment]
@gercenio boa tarde, o uso dessa biblioteca para NFCe para o estado de SP é igual para todos os outros estados. O que muda para SP é que no modo contigência a SEFAZ/SP quer que seja feito via SAT.

**Comment by gercenio** [comment]
@leandrossantos  então isso me obriga a ter um equipamento SAT, ou poderia enviar tudo via NFC-e sem necessidade de um SAT ?

**Comment by leandrossantos** [comment]
@gercenio isso mesmo, somente para o estado de SP, é necessário ter o equipamento SAT mesmo que a empresa for emitir NFCe, ou seja, eles obrigam a empresa ter o SAT independente se for usar o CFe ou NFCe.

**Comment by gercenio** [comment]
@adeniltonbs uma pergunta neste caso já esta implementado o uso do layout do SAT?

**Comment by leandrossantos** [comment]
@gercenio o componente está preparado somente para gerar o XML no leiaute de NFe e NFCe.

**Comment by adrbarros** [comment]
Eu tenho uma implementação do SAT Fiscal achei bem interessante o projeto e gostaria de contribuir com o mesmo. É bem fácil de implementar, Obs.: o Emulador funciona sim tem que fazer alguns ajustes!!!

**Comment by adeniltonbs** [comment]
Alguém de que precise do SAT gostaria de ver com @adrbarros a implementação do SAT Fiscal?

**Comment by gercenio** [comment]
Ola bom dia sim amigo eu gostaria muito e talvez também contribuir com a melhoria do plugin

**Comment by ricardo-neto** [comment]
tenho interesse no SAT... como está esse módulo? está em andamento?
atualmente uso o ACBr para a emissão do SAT, mas quero integrar diretamente em meu aplicativo

**Comment by leandrossantos** [comment]
@gercenio e @queirozqsistemas acabei de achar um projeto da ACBr que estão convertendo para C#.

Vejam [https://github.com/ACBrNet/ACBr.Net.Sat](https://github.com/ACBrNet/ACBr.Net.Sat)

**Comment by rftd** [comment]
Este projeto já esta em produção em alguns clientes.

Obs.: Tem pacote no Nuget, não tem implementado a impressão.

**Comment by ricardo-neto** [comment]
vou baixar ele
