### ISSUE TITLE
Sefaz MT - Carta de Correção(em Produção) com acentuação - Retorna Erro 

### ISSUE THREAD

**Issue by MoacirKuhn** [ZeusAutomacao/DFe.NET#893]
Na integração da carta de correção em produção no SEFAZ MT quando usado um acento, retorna erro 'Codificação diferente de UTF-8'. Porém, em ambiente de homologação não ocasiona esta mensagem de erro. Se enviar sem a acentuação integra corretamente. Qual o motivo desta rejeição?

Segue XML;

[CLIENTE COM ERRO CC NFe51181006968244000149550010000008511000008514-cce-11.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2502415/CLIENTE.COM.ERRO.CC.NFe51181006968244000149550010000008511000008514-cce-11.zip)

**Comment by MoacirKuhn** [comment]
Srs, recebi a resposta do SEFAZ do MT. Segue email recebido:

Boa tarde, 
 
Conforme analista nós aceitamos somente, dentro da Tabela ASCII, os caracteres maiores (>) que 31 e menores (<) que 126, ou os caracteres 10 e 13.
A codificação do arquivo deve em UTF-8.
 
O XML em questão não respeita essa regra pela presença de acentos etc.

**Comment by ocult** [comment]
Boa noite Srs,

Como o problema foi na acentuação do texto informado pelo usuário, coloquei isso:
detEvento.xCorrecao = detEvento.xCorrecao.RemoverAcentucaoSimples();
No mesmo ponto que você comentou.

E essa função no Conversao:
public static string RemoverAcentucaoSimples(this string texto)
        {
            string comAcentos = "ÄÅÁÂÀÃäáâàãÉÊËÈéêëèÍÎÏÌíîïìÖÓÔÒÕöóôòõÜÚÛüúûùÇçñÑ";
            string semAcentos = "AAAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUuuuuCcnN";

            for (int i = 0; i < comAcentos.Length; i++)
            {
                texto = texto.Replace(comAcentos[i].ToString(), semAcentos[i].ToString());
            }
            return texto;
        }

**Comment by robertorp** [comment]
show,
Zeus agora tem um flag para remover acentos nas config.
