### ISSUE TITLE
PDF Danfe Nativo NFC-e

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#897]
Ola, boa tarde
Estou tentando gerar o PDF do danfe nativo da NFC-e, mas quando vou abrir o arquivo sempre diz que está corrompido, alguem passou por isso que possa ajudar?

grd abs

[33181011385836000178650020000001251000001250.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2511886/33181011385836000178650020000001251000001250.pdf)

**Comment by robertorp** [comment]
Qualquer xml ocorre isso?

**Comment by alsantana** [comment]
Ola, sim 
qualquer xml, testei com o app de teste do zeus e tb aconteceu o mesmo problema

Olha um xml de teste



[XML.zip](https://github.com/ZeusAutomacao/DFe.NET/files/2511900/XML.zip)

**Comment by robertorp** [comment]
![nfce](https://user-images.githubusercontent.com/10251705/47454513-c89b5980-d7a5-11e8-9193-474838471bf5.jpeg)

fiz aqui e deu certo o nativo nfc-e 

não pode ser algo de permissão de pasta , ou exception enfim..

**Comment by alsantana** [comment]
Estou usando dessa forma

`Public nfeConfiguracaoDanfe As ConfiguracaoDanfeNfce

nfeConfiguracaoDanfe = New ConfiguracaoDanfeNfce(NfceDetalheVendaNormal.UmaLinha, NfceDetalheVendaContigencia.UmaLinha)
nfeConfiguracaoDanfe.CarregarFontePadraoNfceNativa()
nfeConfiguracaoDanfe.NfceLayoutQrCode = NfceLayoutQrCode.Lateral
nfeConfiguracaoDanfe.VersaoQrCode = VersaoQrCode.QrCodeVersao2
nfeConfiguracaoDanfe.ImprimeDescontoItem = True

Dim danfeNativo = New DanfeNativoNfce(nfeProcessada.ObterXmlString, nfeConfiguracaoDanfe, readerEmpresas!cfgNFCeToken, readerEmpresas!cfgNFCeIDCSC, pTroco, nfceValorTotal)
danfeNativo.Imprimir("MP-2800 TH")

danfeNativo.GerarJPEG(String.Format("{0}\PDF\{1}.pdf", My.Application.Info.DirectoryPath, nfeProcessada.protNFe.infProt.chNFe))
danfeNativo.Imprimir("MP-2800 TH", String.Format("{0}\PDF\{1}.pdf", My.Application.Info.DirectoryPath, nfeProcessada.protNFe.infProt.chNFe))
`

**Comment by robertorp** [comment]
Tenta extensão jpeg , pois ele gera uma imagem e não um pdf no jpeg 

`danfeNativo.GerarJPEG(String.Format("{0}\PDF{1}.pdf", My.Application.Info.DirectoryPath, `

**Comment by alsantana** [comment]
Mudei aqui o jpeg, foi sem problemas só o PDF que não

![33181011385836000178650020000001261000001266](https://user-images.githubusercontent.com/16413266/47455162-8246fa00-d7a7-11e8-9f13-bcdba4cd29be.jpeg)
[33181011385836000178650020000001261000001266.pdf](https://github.com/ZeusAutomacao/DFe.NET/files/2511951/33181011385836000178650020000001261000001266.pdf)

**Comment by robertorp** [comment]
PDF não vai mesmo, o método e para gerar somente a jpeg
para ter PDF vai ter que implementar algo que converta para PDF um outro método talvez bom, se quiser implementar faça um pull que nos aceita

**Comment by alsantana** [comment]
Ok, pode deixar
Vou tentar implementar e faço um pull

Brigadao pela ajuda, grd abs

**Comment by alsantana** [comment]
Posso usar uma biblioteca de terceiro gratuita ?

http://www.pdfsharp.net/MainPage.ashx

**Comment by robertorp** [comment]
vou fechar a issue, sobre a lib de terceiro, verifique a compatibilidade com .net core , a tendencia e que futuramente o Zeus tenha compatibilidade com .net core
