### ISSUE TITLE
[Off topic] Fast reports agora é open source!

### ISSUE THREAD

**Issue by marcosgerene** [ZeusAutomacao/DFe.NET#898]
https://www.fast-report.com/pt/news/411/

https://github.com/FastReports/FastReport

**Comment by ThalisonSantos** [comment]
Ai sim!!

**Comment by bilhega** [comment]
Que bacana!

**Comment by danpadua** [comment]
Up!!!

**Comment by robertorp** [comment]
alguém já conseguiu usar legal?

**Comment by marcosgerene** [comment]
@robertorp pretendo migrar o Zeus NFe e NFCe pra ele, mas inFELIZMENTE não venho tendo tempo

**Comment by Braytiner** [comment]
Ótima notícia!
