### ISSUE TITLE
Transmissão NFe como pessoa física

### ISSUE THREAD

**Issue by danpadua** [ZeusAutomacao/DFe.NET#899]
Estou com problemas ao gerar NFe com o certificado A1 e-CPF no AppTeste do Zeus.

Não existe um campo CPF quando está configurado para o certificado e-CPF na aba Emitente, com isso eu coloquei "000" antes no campo CNPJ do Emitente para conseguir assinar e validar uma nota.

Mais com esse "workaround" o CPF assinado na nota se difere com o CPF registrado no certificado.

Alguém sabe ou já transmitiu uma nota como pessoa física?

**Comment by danpadua** [comment]
Consegui fazer a transmissão como pessoa física no Zeus, só que tive que alterar algumas validações.
Assim que eu tiver um tempo quero contribuir com esse código para todos vocês.

Agradeço o apoio.

**Comment by robertorp** [comment]
Vou fechar essa issue, qualquer coisa reabra ela , se quiser pode fazer um pull com seus ajustes.
