### ISSUE TITLE
Cancelamento de NF-e

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#90]
Adenilton, boa tarde,

Qual método uso para cancelar uma NFC-e?

Desde já agradeço,
Roberto.

**Comment by leandrossantos** [comment]
@robertocvsiqueira  O cancelamento de NFCe é o mesmo que da NFe. Ai no exemplo que o @adeniltonbs fez tem o procedimento de como deve ser feito, lembrando que o cancelamento de NFCe tem um prazo de 30 minutos, em alguns estados é de 2 horas, mais não como da NFe que é de 24 horas.

**Comment by robertocvsiqueira** [comment]
Obrigado, @leandrossantos, vou instalar um certificado digital novo na máquina de testes, pois o atual está vencido. Aí digo o resultado.
