### ISSUE TITLE
Erro emissão NFe/NFCe

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#900]
pessoal hoje comecei e receber esse erro de alguns clientes, alguém já viu esse tipo de erro?
![2018-10-31](https://user-images.githubusercontent.com/22593917/47814066-7caf5e00-dd2b-11e8-9bd5-492cb368e43c.png)

**Comment by rodrigordi** [comment]
Qual UF ?

**Comment by ThalisonSantos** [comment]
@rodrigordi Sergipe e Alagoas ambos estados usam o SVRS

**Comment by rodrigordi** [comment]
@ThalisonSantos eu acompanho o painel de disponibilidade da SEFAZ e o SVRS, SVC-RS estão apresentando luz amarela direto hoje na parte da tarde.

**Comment by ThalisonSantos** [comment]
@rodrigordi  quando começou os erros eu fui verificar e percebi que estava variando entre verde e amarelo e até teve momentos de estar vermelho

**Comment by robertorp** [comment]
Sefaz sem sombra de dúvida.. se ler a mensagem o erro foi interno nos servidores deles.

**Comment by rodrigordi** [comment]
@ThalisonSantos sim. Quando uma webapp .net dá erro, aparece aquela tela amarela com o stacktrace. é esse html que está aparecendo ai para voce.

**Comment by ThalisonSantos** [comment]
valeu pessoal, o jeito é aguardar que eles resolvam

**Comment by marcosgerene** [comment]
Estou com o mesmo problema no RN, vou manter a issue aberta até estabilizar para servir de fonte de pesquisa

**Comment by ThalisonSantos** [comment]
@marcosgerene pensei que hoje já teria resolvido mais continua a mesma coisa

**Comment by jeisonperes** [comment]
RS também desde ontem pela manhã. Serviço sai e volta toda hora.

**Comment by marcosgerene** [comment]
![image](https://user-images.githubusercontent.com/15945003/47849996-73b59f80-ddb2-11e8-9483-5f0ca4922fba.png)
http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx

No meu caso (RN) o servidor é o SVRS

**Comment by jeisonperes** [comment]
![image](https://user-images.githubusercontent.com/40441623/47850018-8b8d2380-ddb2-11e8-8fe8-bbce8fb3587d.png)

**Comment by jeisonperes** [comment]
Resposta do Sefaz RS:
A respeito da situação que foi questionada, precisamos fazer o seguinte esclarecimento:
1)      Não está havendo nenhuma instabilidade nos servidores da SEFAZ.
2)      A transmissão dos arquivos XML para a SEFAZ é feita através de canais dedicados da internet. Se esses canais dedicados tiverem uma instabilidade, então a transmissão dos arquivos XML poderá instável, mesmo que todo o restante da internet da empresa funcione normalmente.

Aparentemente, está ocorrendo uma instabilidade nos canais dedicados de transmissão. Isso faz com que haja uma dificuldade na transmissão dos arquivos XML para a SEFAZ.
Os arquivos XML que são recebidos pela SEFAZ tem processamento normal, porém pode haver uma instabilidade no processo de transmissão. A equipe técnica está verificando a causa dessa instabilidade.
É importante ressaltar que a instabilidade na transmissão não implica em uma interrupção nas atividades de sua empresa. Sua empresa pode continuar operando normalmente, fazendo a emissão de NF-e e NFC-e em contingência.
Atualmente, há 3 formas de emissão em contingência que estão disponíveis:

·         EPEC – Evento Prévio de Emissão em Contingência;
·         Formulário de Segurança
·         Contingência Off-Line (exclusivo para NFC-e).

Sua empresa pode suar essas 3 formas de emissão, enquanto o problema nos canais de transmissão é verificado. Caso não saibam como utilizar essas 3 opções, então contatem o responsável pelo seu sistema.
Se a empresa for do RS, então ela tem também a emissão de emitir NF-e Avulsa no site da SEFAZ, no link https://www.sefaz.rs.gov.br/NFE/NFE-NFA.aspx . Essa forma de emissão está funcionando normalmente.

**Comment by robertorp** [comment]
Vou fechar a issue. Qualquer coisa abra novamente.
