### ISSUE TITLE
Rejeicao: Cabecalho - Versao do arquivo XML nao suportada

### ISSUE THREAD

**Issue by JoPierre** [ZeusAutomacao/DFe.NET#901]
Bom dia Pessoal,desde o dia 05/11/2018 estou tendo este problema com a Nfce,estou utilizando a versao 4.00 (AM),verifiquei o meu xml e a versao do mesmo esta correto (4.00) tambem verifiquei o web service para o estado do amazonas e tambem esta correto (nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao4),por favor alguem poderia me dar uma ajuda

Obrigado

**Comment by robertorp** [comment]
Mais detalhes sobre o erro por gentileza, uma print do erro o xml que deu erro enfim.. mais informações.

**Comment by JoPierre** [comment]
Bom no meu sistema da esta mensagem:
![image](https://user-images.githubusercontent.com/43068584/48141908-cb07b400-e279-11e8-8736-b174262fb419.png)

baixei o projeto e quiz emitir uma nota e tambem recebi o mesmo erro:
![image](https://user-images.githubusercontent.com/43068584/48142083-15893080-e27a-11e8-8a20-606de51b0298.png)

sao estas as configuracoes:
![image](https://user-images.githubusercontent.com/43068584/48142135-33569580-e27a-11e8-91ac-99c9cec022df.png)

**Comment by marcosgerene** [comment]
Acredito que **NFeRecepcao** e **NFeRetRecepcao** deve ser 4.00 e não 3.10.

PS: Desmarque esse "definir automaticamente a versão dos serviços", isso não funciona para todos os estados, na verdade nem sei para qual funciona e se alguém usa "em produção". Configure "serviço-a-serviço".

**Comment by JoPierre** [comment]
Boa tarde,obrigado pela resposta,mas ainda continua dando o mesmo erro,ja configurei serviço-a-serviço,tem mais um detalhe esse erro da quando eu utilizo a versao 1.0 do QR-Code,acredito que o problema seja esse,mas quando tento utilizar a versao 2.0 aparece este erro:
![image](https://user-images.githubusercontent.com/43068584/48159129-644ac080-e2a2-11e8-93c2-603ff11ebc1a.png)

**Comment by JoPierre** [comment]
Obrigado pela resposta,mas mesmo configurando servico a servico esta dando o mesmo erro,tem outro detalhe,nos testes que estou realizando estou utilizando a versao 1.0 do QR code,acredito que o problema seja isso,porem,quando tento utilizar a versao 2.0 aparece outro erro,dizendo que o valor do qrCode nao E valido

**Comment by JoPierre** [comment]
a mensagem que apareceu em homologacao:

Erros na validação:\n O elemento 'http://www.portalfiscal.inf.br/nfe:qrCode' é inválido - O valor 'homnfce.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp?p=13181117353789000167650010000000011000012346|2|2|1|72fe3f1f29a9cb02098cd34b23660e54e63a5ec5' é inválido dependendo do tipo de dados 'String' - Falha na restrição Pattern.

**Comment by robertorp** [comment]
Opá conseguiu ?
