### ISSUE TITLE
Adicionar uma Copia no NFe.Utils.Email no EmailBuilder

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#902]
Bom dia!
Gostaria de solicitar uma adição no EmailBuilder. 
Teria como adicionar para encaminhamento de copia tambem;
Seria basicamente assim:
        private readonly List<MailAddress> _copia;

        public EmailBuilder AdicionarCopia(string email, string nome = "")
        {
            if (!EmailValido(email))
                throw new ArgumentException("E-mail de copia é inválido!");

            _copia.Add(new MailAddress(email,nome,System.Text.Encoding.UTF8));
            return this;
        }

  _copia.ForEach(mensagem.Cc.Add);

Att
Fabio

**Comment by robertorp** [comment]
muito obrigado pela contribuição ! já esta aceito o pull @fabiociaf
