### ISSUE TITLE
NFce RS - QR Code 2.0

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#904]
Pessoal, 
alguém aki ta conseguindo gerar NFCE para o Rio Grande do Sul???

tenho tido o seguinte retorno:

Erros na validação:\n O elemento 'http://www.portalfiscal.inf.br/nfe:qrCode' é inválido - O valor 'https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?p=43181108178982000118650010000016031232411006|2|1|1|7b9d9ccb857f91c42010702cd950c5a0f22628f3' é inválido dependendo do tipo de dados 'String' - Falha na restrição Pattern.

**Comment by robertorp** [comment]
veja essa issue fazendo o favor e veja se ajuda em algo -> https://github.com/ZeusAutomacao/DFe.NET/issues/867

**Comment by FabioRoesler** [comment]
Boa Tarde
Estou usando no RS sem problemas. Homologação e produção.
Segue as configurações que estou usando
![imagem](https://user-images.githubusercontent.com/24945244/48227652-0abdc100-e38a-11e8-920d-7d81008a4b0b.png)

**Comment by JoPierre** [comment]
Boa tarde,provavelmente precise atualizar os Schemas,foi assim que eu consegui solucionar este problema aqui no Amazonas

**Comment by celinolimac** [comment]
Deu certo pessoal... atualizando os schemas resolveu o problema.. obrigado
