### ISSUE TITLE
Web Service NFeIntegracao SVRS

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#909]
Ola, boa tarde
Alguem já ouviu falar desse web service da Sefaz RS, onde é possivel recuperar os XML's da NF-e e NFC-e emitidos por um CNPJ com certificado digital?

https://nfe-rs-integracao-hmle.sefazvirtual.rs.gov.br/ws/NfeIntegracao/NfeIntegracao.asmx

**Comment by alsantana** [comment]
@robertorp ola meu caro, vc me ajuda a implementar esse webservice?
grd abs

**Comment by rodrigordi** [comment]
@alsantana boa tarde. Onde você conseguiu essa url ?

**Comment by alsantana** [comment]
Olá, foi direto no site da sefaz rs, baixei a documentação, so preciso de ajuda para implementar

**Comment by alsantana** [comment]
Se quiser envio tudo que consegui aqui

**Comment by robertorp** [comment]
Nunca ouvi falar disso, vc implementou ela? funcionou? 

Podemos implementar, mas antes preciso conhecer mais essa webservice para saber se ela realmente faz parte do contexto do DF-e (repositorio aqui) ou não. 

Mas de qualquer maneira ajudo a implementar em um outro repositorio se for o caso de não ficar nesse repositorio.
