### ISSUE TITLE
Busca Certificado aplicação AspNetMvc - A sessão atual não é interativa

### ISSUE THREAD

**Issue by celinolimac** [ZeusAutomacao/DFe.NET#91]
Boa tarde Adenilton,

tenho utilizado a biblioteca com sucesso em aplicação windows forms, porém estou querendo
utilizar tambem em aplicações web com Asp net mvc...

sendo que estou enfrentando o seguinte problema quando publico no IIS:

ao selecionar o certificado recebo a seguinte exceção: "A sessão atual não é interativa"

porém em modo debug da certo.. apenas quando publico que aparece esta mensagem e neste momento de pegar o certificado.

alguém poderia me dar alguma luz de como resolver isso?

**Comment by leandrossantos** [comment]
@celinolimac boa tarde,

Para usar na web você não pode usar o certificado digital instalado na máquina local e sim usar diretamente pelo arquivo, lembrando que só conseguirá usar certificado A1.

Você está fazendo isso, usando diretamente pelo arquivo pfx e passando a senha de instalação do mesmo?

**Comment by celinolimac** [comment]
Boa tarde Leandro, 

pois é minha maquina local é o meu servidor web...pensei que daria certo assim por o certificado está no meu servidor...

mas percebi aqui minha chamada ta sendo feita obter do repositório onde eu passo o numero de serie e ele varre todos e pega o q tem o numero de serie igual...
então trocando a chamada e utilizando ObterDeArquivo passando o caminho e senha terei sucesso?

Não tinha me atentado a isso.

valew pelo help demais

**Comment by rftd** [comment]
Funciona no repositório se você instalar o certificado no repositório do usuário do IIS.

**Comment by celinolimac** [comment]
Valew pessoal... deu certo.. utilizando a função ObterDeArquivo tive sucesso...  obrigado Leandro e
obg tambem Rafael Dias

**Comment by devanirgrazino** [comment]
Celino e Leandro, boa tarde.

Sou novo por aqui e preciso de uma ajuda para entender um detalhe que não ficou claro para mim.

Em uma aplicação web, eu consigo utilizar o Certificado A1, arquivo .pfx, até ai eu entendi tranquilamente. Agora só não entendi o seguinte, se este arquivo .pfx pode estar na máquina do usuário que está consumindo minha aplicação web ou se o arquivo .pfx deverá estar alocado no servidor web.

Obrigado pela atenção de todos.
