### ISSUE TITLE
Cancelamento NFCe V.1.00

### ISSUE THREAD

**Issue by Yamcol** [ZeusAutomacao/DFe.NET#913]
Boa tarde, não estou conseguindo realizar cancelamento do nfce, estou utilizando a versão 1.00 para realizar o cancelamento das notas que estão na versão 4.00. 

O erro que ocorre é: "Erro de Comunicação: Falha na rede internet: The request failed with HTTP status 404: Not Found". 

Acredito que seja porque o webservice para versão 1.00 esteja fora do ar. Tentei então utilizar a versão 4.00 para serviço de RecepcaoEventoCancelmento , mas quando tento utilizar nessa versão o sistema informa:
"Serviço RecepcaoEventoCancelmento, versão v400, não disponível para a UF PA, no ambiente de Produção para emissão tipo Normal, documento: NFC-e!".

Esse erro ocorre em varias UFs: PA, MA, PI, RO, MA.

**Comment by robertorp** [comment]
a url que ele esta pegando para o cancelamento e essa aqui  isso para homologação https://hom.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx

![image](https://user-images.githubusercontent.com/10251705/49029611-2992c480-f18c-11e8-875e-200831ed122f.png)

vou verificar produção.. e sim deu 403 ou seja.. não estou autorizado (atualizado corrigido comentário meu)


=================


Produção esta correto também url retornada pelo Zeus 
https://www.sefazvirtual.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx

![image](https://user-images.githubusercontent.com/10251705/49029941-1cc2a080-f18d-11e8-84a4-99f35cafcf7f.png)


deu o mesmo erro 403 mas isso e algo local em minha maquina, cadeia de certificado, certificado , e algum problema relacionado a protocolos ou certificado 


APPTESTE
![image](https://user-images.githubusercontent.com/10251705/49030242-f5200800-f18d-11e8-843c-c4cff43f3982.png)

**Comment by Yamcol** [comment]
Valeu  pela ajuda. Resolvido
