### ISSUE TITLE
Leitura de string XML

### ISSUE THREAD

**Issue by miltonterre** [ZeusAutomacao/DFe.NET#914]
Estou lendo arquivos XML e estou tendo um erro de "3 não é um valor válido para ModalidadeFrete". O XML é da versão 4.0 e é válido. Sei que na versão 4.0 o valor 3 é válido para ModalidadeFrete. Me parece que o desserializador está usando uma versão anterior de schema, mas não consegui achar onde informo/indico qual xsd deve ser usado.

**Comment by marcosgerene** [comment]
@miltonterre por favor poste o xml e a excessão lançada
