### ISSUE TITLE
Leitura de xml de CTe

### ISSUE THREAD

**Issue by miltonterre** [ZeusAutomacao/DFe.NET#918]
Boa tarde, galera.
Eu preciso ler um CTe de uma string xml. Eu vinha usando o seguinte código:
`
var cte = CTe.Classes.CTe.LoadXmlString(xml);
`
"xml" é um xml de CTe válido e autorizado.
Esse código me retorna uma exception 
`<cteProc xmlns='http://www.portalfiscal.inf.br/cte'> não era esperado.>`

Para desserializar uma NFe eu uso o código
`
var nfe = new NFe.Classes.NFe().CarregarDeXmlString(xml);
`
e funciona certinho, sem exception.
Fuçando na desserialização de NFe eu modifiquei um pouco o meu código para
```
var s = FuncoesXml.ObterNodeDeStringXml(typeof(CTe.Classes.CTe).Name, xml);
var cte = FuncoesXml.XmlStringParaClasse<CTe.Classes.CTe>(s);

```
Agora desserializa normalmente, sem erros.
É assim mesmo que eu devo proceder para desserializar um xml de CTe? Ou será que tem 'caca' na desserialização (função "CTe.Classes.CTe.LoadXmlString(xml)")?

**Comment by robertorp** [comment]
como você disse isso e um CT-e válido e autorizado, ou seja.. 

cteProc => verifica se o cteProc tem algum loadXml se não tiver basta usar assim

`var cteProc = FuncoesXml.XmlStringParaClasse<cteProc>(xml);`

dentro do cteProc vc encontrará seu ct-e

**Comment by miltonterre** [comment]
De fato ambas as abordagens funcionam.
Como sugestão, poderíamos ter um método igual ao da NFe
`var nfe = new NFe.Classes.NFe().CarregarDeXmlString(xml);`
Do jeito que está hoje, desserializar uma NFe é diferente de desserializar um CTe.

**Comment by marcosgerene** [comment]
@miltonterre o CTe/MDFe seguem uma estrutura COMPLETAMENTE diferente do NFe, isso é um problema do projeto a tempos ,o @robertorp começou um PR para isso faz um bom tempo, mas ainda não concluiu.

Eu hoje não uso mais o CTe do Zeus, estou usando o ACBr.Net.CTe do @rftd uso apenas o DACTe daqui ainda porque ainda não conclui o port para o ACBr

**Comment by guimagcpd** [comment]
Eu uso o CTE do ZEUS e todos os demais componentes vinculados ao projeto,.desde que ele foi criado...
Não tenho problemas com ele.. o Suporte e velocidade para resolução dos problemas oferecido pelo desenvolvedor robertorp  são imediatos e conclusivos.
Sinceramente, acredito que problemas de uso existem pois lidamos com CLIENTES também, e querendo ou não somos CLIENTES do projeto. e como clientes devemos abordar melhor as funcionalidades do uso do componente, se interar com quem sabe como usar,(PROGRAMADORES DO PROJETO) e então apontar a eles eventuais problemas para que trabalhem com a possivel solução.
O Projeto é de uso GRATIS, todos tem suas empresas suas vidas seus negócios e só o fato de manterem esse projeto aberto pra nós ja da a eles méritos.. Mais vão alem disso, melhoram atualizam e dão suporte.. na minha opinião nota 10000.
