### ISSUE TITLE
Assinatura de XML - Certificado Digital

### ISSUE THREAD

**Issue by DSBRBrasil** [ZeusAutomacao/DFe.NET#925]
**Oque**: Ao utilizar o método Assina(), uma exception (null reference) é levantada.
Detalhe: Um aplicativo que faz uso do framework Zeus não consegue identificar a origem do erro provocado pela ausência de um tipo exception customizado. 
A aplicação só acusa NullReference,  (Object reference not set to an instance of an object)
**Como reproduzir o erro:** 
1) Instalar o S.O Windows 10
2) Não deve haver certificado digital instalado.
3) Omitir o tipo de certificado, na propriedade da classe [ConfiguracaoCertificado] ex:
`cfg.Certificado = new ConfiguracaoCertificado()
            {
                //TipoCertificado = TipoCertificado.A1ByteArray,
                ArrayBytesArquivo = //Informar um array de bytes do arquivo .pfx
                Serial = //Informe aqui o serial do certificado
            };`
**Solução:**Criar uma exceptoin personalizada em na classe [CertificadoDigital] e subir o erro devidamente identifcado
Obs: Caso aprovar a issue, posso criar um pull request.
Obrigado

**Comment by marcosgerene** [comment]
@DSBRBrasil interessante, abra o PR e vamos por em discussão.
