### ISSUE TITLE
Certificado Digital  - Ordem do preenchimento causa falso erro

### ISSUE THREAD

**Issue by DSBRBrasil** [ZeusAutomacao/DFe.NET#926]
Erro no preenchimento de dados de certificado digital.
O usuário deve informar primeiro o tipo do certificado, depois, demais dados, caso contrário o sistema levanta falso erro.
Segue em anexo, como reproduzir o erro
![bug_zeus](https://user-images.githubusercontent.com/7658282/49401770-42245100-f72f-11e8-8d41-49cde095e0d1.PNG)
**Solução**: Refactore na classe [ConfiguracaoCertificado], criando um construtor, e retirando a implementação do INotifyPropertyChanged (sem função alguma)
A disposição para realizar pull request
Obrigado.

**Comment by marcosgerene** [comment]
@DSBRBrasil concordo com isso, sempre achei desnecessário essa função, acho que o tratamento pelo ERP mais interessante nestes casos, nunca mexi porque já estava assim antes, então adaptei meu código a isso.

Abra o PR, vou aguardar alguns dias para coletar a opinião dos demais commiters, se ninguém se opor ficarei feliz em aceitar.
