### ISSUE TITLE
Erro ao deserializar classe retEnviNFe quando consumo indevido

### ISSUE THREAD

**Issue by hhunterx** [ZeusAutomacao/DFe.NET#927]
Primeiramente, boa tarde e sucesso aos membros desde projeto.
Segundamente, vamos ao tópico: 
Graças a "estagiarios" aqui da empresa, estavamos recebendo o retorno de consumo indevido (em homologação somente) e acabamos caindo nesse outro erro, que é o foco do topico. O retorno era o seguinte:

`<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>RSnfce201807191353</verAplic><cStat>656</cStat><xMotivo>Rejeicao: Consumo indevido pelo aplicativo da empresa [Quantidade rejeicoes: 90, NF-e: xxxxxxxxxxxxxxxxxxxx]</xMotivo><cUF /><dhRecbto>2018-12-11T10:27:42-02:00</dhRecbto></retEnviNFe>`

Rastreando o problema, isso causava um erro ao deserializar a classe retEnviNFe pois a UF estava vazia, fazendo gerar uma exception em NFeAutorizacao (not valid XML element, ou coisa assim).

A solução pra nós foi alterar a classe retEnviNFe do Zeus na propriedade cUF, ficando assim:

`        [XmlElement("cUF")]
        public string ProxycUF
        {
            get
            {
                return cUF.HasValue ? cUF.Value.GetCodigoIbgeEmString() : null;
            }
            set
            {
                cUF = int.TryParse(value, out int ufint) ? (Estado?)ufint : null;
            }
        }

        [XmlIgnore]
        public Estado? cUF { get; set; }`

Note ali que tornei a propriedade um nullable o que poderia causar algum impacto para outras pessoas. Outra soluçao seria assumir uma UF padrão tipo (EX) porém não estaria 100% correto também.

Deixo ai então para avaliação de vcs a questão.

**Comment by robertorp** [comment]
Boa tarde, de qual estado você é?
estranho ne? 
Mas normal. 
Poderia fazer um pull request? 

Obrigado!!!

**Comment by hhunterx** [comment]
Sou do RS. 
É não teria pq não mandarem a UF ali mas enfim...
Vou fazer o PR então.
