### ISSUE TITLE
Adicionar o NFe.Danfe.Nativo no Nuget.

### ISSUE THREAD

**Issue by viiny123** [ZeusAutomacao/DFe.NET#929]
Pessoal comecei a utilizar o Zeus a pouco tempo, então desculpe se a pergunta for muito boba. Quando adicionei o Zeus NFe NFCe em meu projeto via nuget, percebi que não veio o projeto de NFe.Danfe.Nativo, é possível adicionar ele para que seja publicado no nuget tbm ? Qual a forma que vcs tem utilizado esse projeto ? Vocês simplesmente pegam o csproj e adicionam ao projeto de vocês ?

**Comment by felixsevero** [comment]
Veja essa issue que responde a sua pergunta: #951

**Comment by viiny123** [comment]
responde sim valeu :)
