### ISSUE TITLE
Passo a passo

### ISSUE THREAD

**Issue by LeonardoMoraes1989** [ZeusAutomacao/DFe.NET#93]
Olá pessoal,
Sou iniciante nesse assunto de NFe e NFCe, gostaria de perguntar se alguém da comunidade, possui algum exemplo utilizando C# e consumindo as bibliotecas que o nosso querido Adenilton passou.
Eu fico com bastante dúvidas na hora de criar o XML e se alguém puder me ajudar eu ficaria muito grato.

Agradeço a todos vocês.
Muito Obrigado,
Atenciosamente,
Leonardo Moraes.

**Comment by adeniltonbs** [comment]
Leonardo bom dia. Junto com a biblioteca há uma aplicação de demonstração de uso desta, no diretório https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.AppTeste

Lá tem o exemplo de criação de uma NFe e de uma NFCe. Basta substituir as informações estáticas que foram colocadas lá, por informações obtidas de seu banco de dados ou informadas pelo usuário. Outra coisa: É necessário que você se familiarize bem com o Manual de Orientação ao contribuinte (http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=) para ver onde e que informações colocar em cada tag.

**Comment by LeonardoMoraes1989** [comment]
Adenilton, bom dia,
Será que podemos conversar por skype?
O meu é: leo_msilva

**Comment by adeniltonbs** [comment]
Na aplicação de demonstração, na classe MainWindow, dê uma olhada no método 

``` cs
protected virtual Classes.NFe GetNf(int numero, ModeloDocumento modelo, VersaoServico versao)
```

 e nos demais que são chamados a partir deste

**Comment by adeniltonbs** [comment]
Tenho hangouts, se quiser chama lá.
adenilton.bs@gmail.com

Mas prefiro que coloque sua dúvida por aqui, afinal sua dúvida pode ser a de outra pessoa. Além disso toda comunidade pode também lhe responder

**Comment by LeonardoMoraes1989** [comment]
Valeu Adenilton,

Vou dar uma olhada nisso e te retorno.
Muito Obrigado.

**Comment by adeniltonbs** [comment]
Dê uma olhada neste artigo na WIKI do projeto:
https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki/Nunca-emiti-uma-NF,-meu-sistema-n%C3%A3o-tem-isso.-Preciso-implantar-NFe-e-agora%3F

**Comment by LeonardoMoraes1989** [comment]
Adenilton,
Valeu!
Hoje mesmo dou continuidade e te retorno.
Muito obrigado.
