### ISSUE TITLE
Rejeicao: CNPJ-Base do Emitente difere do CNPJ-Base do Certif. Digital - BA

### ISSUE THREAD

**Issue by ClovisAlves83** [ZeusAutomacao/DFe.NET#931]
Boa tarde, desde ontem a partir das 15:00 aqui na Bahia, começou a dar essa rejeição, agora 
o incrível é que são todos os clientes que começam o CNPJ com ZERO e utilizam o certificado digital A1 , já tentei pesquisar na web , passo corretamente tudo, peço que me ajudem a resolver este problema. 

O incrível a se seguir é que a nota consta na sefaz como autorizada para uso.
A nota está normal. CHAVE = 29181201541910000144550010000150101383035997

o XML da consulta da NFeRetAutorizacao:

<retConsReciNFe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
<tpAmb>1</tpAmb><verAplic>6.0</verAplic><nRec>291200179181101</nRec><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>29</cUF><dhRecbto>2018-12-19T14:47:13-03:00</dhRecbto>
<protNFe versao="4.00"><infProt xmlns="http://www.portalfiscal.inf.br/nfe" Id="NFe129180610150246"><tpAmb>1</tpAmb><verAplic>6.0</verAplic><chNFe>29181201541910000144550010000150101383035997</chNFe>
<dhRecbto>2018-12-19T14:47:13-03:00</dhRecbto><nProt>129180610150246</nProt><digVal>WwCCE5RQKN6P87O1VMvz2EQkrvI=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso da NF-e</xMotivo></infProt></protNFe>
</retConsReciNFe>

**Comment by edi46r** [comment]
Boa tarde! Estamos com o mesmo problema! Apenas emitentes com CNPJ iniciando em ZERO.
E apenas na BA

**Comment by robertorp** [comment]
manda o xml gerado para nos analisar

**Comment by ClovisAlves83** [comment]
Boa tarde, segue o xml assinado, mudei a extensão para txt para aceitar anexar.
Não gerar o arquivo no procNFe, mas vou anexar tb o xml que baixei na sefaz.

[29181201541910000144550010000150101383035997- Baixado.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2703649/29181201541910000144550010000150101383035997-.Baixado.txt)
[NFe29181201541910000144550010000150101383035997-assinado - Copia.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2703651/NFe29181201541910000144550010000150101383035997-assinado.-.Copia.txt)

[NFe29181201541910000144550010000150111608699991-assinado - Copia.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2703640/NFe29181201541910000144550010000150111608699991-assinado.-.Copia.txt)

**Comment by robertorp** [comment]
@ClovisAlves83  o cnpj https://github.com/ZeusAutomacao/DFe.NET/blob/86c7fbc5b372be9d3e072727b03f56bb0babd7dd/Shared.NFe.Classes/Informacoes/Emitente/emit.cs

ele e uma string.. vc esta mandando ele faltando o 0 se for o que entendi

**Comment by ClovisAlves83** [comment]
Bom dia, como apareceu o erro dado pela SEFAZ do nada, do nada a SEFAZ tb retomou a emissão normalmente. Obrigado pela atenção.
