### ISSUE TITLE
Atualizar o pacote NUGET com os novos webservices da NFCE de MG

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#933]
Boa tarde, 
Teria como atualizar os pacotes do NUGET com os novos webservices da NFC-e. 
Ja lancei um PULL aqui com atualização desses novos webservices, 
Também tem um ajuste para fazer.
Agora e preciso lançar uma atualização no nuget. 
Poderia realizar por gentileza. 
Obrigado Fabio

**Comment by robertorp** [comment]
estarei atualizando.

**Comment by robertorp** [comment]
Feito a atualização.
Aguarde de 20 minutos a 2 horas que o nuget atualiza.

**Comment by ghost** [comment]
@robertorp  acho que esta faltando ajustar os EnderecoConsultaPublicaNfce
Não estou entendendo a logica desse código. 
Se puder me ajudar. 


https://github.com/ZeusAutomacao/DFe.NET/blob/master/Shared.NFe.Utils/InformacoesSuplementares/ExtinfNFeSupl.cs
