### ISSUE TITLE
Duvida, como colocar o Zeus sem ser Nuget no meu projeto.

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#935]
Alguém poderia me informa, como faço para integrar o Zeus sem ser pelo Nuget.
Gostaria de integrar no meu projeto o zeus porem não queria pelo nuget.

Att
Fabio

**Comment by orochasamuel** [comment]
Baixa o projeto, compila, e referencia as DLLs no seu projeto. Não esqueça de marcar para gerar a DLL no diretório de saída.

**Comment by ghost** [comment]
Consegui colocar certinho, obrigado!
