### ISSUE TITLE
ExtinfNFe correto com o URL de MG 

### ISSUE THREAD

**Issue by ghost** [ZeusAutomacao/DFe.NET#937]
Agora sim o ExtinfNFe correto com o URL de MG 
Demorei para entender a logica e entrar em contato com SEFAZ de minas para eles me dar um posicionamento das URL. 
Agora já esta tudo certo.
Administrador, favor da uma olhada no codigo. 
Eu coloquei no meu projeto e deu certo. 
Se puder atualizar o NUGET tambem ajuda. 
Qualquer coisa so me chamar. 
Att
Fabio

**Comment by robertorp** [comment]
o que tem de errado com o nuget? 
Aqui utilizo nuget em 1000 clientes esta rodando o sistema, inclusive em MG 
bom, preciso de mais detalhes sobre o erro

**Comment by ghost** [comment]
E que no nuget nao esta atualizando o ExtinfNFe, ai coloquei o projeito. 
Nao tem nada de errado. 
hahahahhaha

Como informado esta faltando o URL de consulta, por isso atualizei. 
Demorei um pouco porque não estava certo com o webservices do portal da nfce de minas.

**Comment by ghost** [comment]
Gente, 
Em relação a o ... NFe.Utils/InformacoesSuplementares/ExtinfNFeSupl.cs
Algum administrador ou dono desse codigo poderia ajustar esse codigo, por gentileza. 
Seguindo os WEBSERVICES DA NFCE DE MINAS GERAIS tais publicado no site da SEFAZ.
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/

**Comment by LosDeveloper** [comment]
Alguma posição sobre a atualização dos webservices no Nuguet?
Não encontra a url de consulta de qrcode.

**Comment by ghost** [comment]
Para o estado de MG?

**Comment by LosDeveloper** [comment]
Sim para o estado de MG.

**Comment by robertorp** [comment]
Achei que já estava. Vou conferir.

**Comment by LosDeveloper** [comment]
Obrigado!

**Comment by robertorp** [comment]
Versão Nuget Zeus publicada. 
Daqui uns 30 minutos provavelmente o próprio Nuget libera.

**Comment by LosDeveloper** [comment]
Tudo certo agora
Muito obrigado Roberto!

**Comment by ghost** [comment]
Já foi ajustado no Zeus, obrigado.
