### ISSUE TITLE
NFC-e Cancelamento por Substituição

### ISSUE THREAD

**Issue by alsantana** [ZeusAutomacao/DFe.NET#938]
Olá, bom dia

Alguem já deu uma verifica nessa nota técnica, achei bem bacana

https://blog.tecnospeed.com.br/nota-tecnica-2018-004-nfce/?fbclid=IwAR0HMEMuBGBI9_5Phr-OqQsldxdSwMOyVTVN0VMSj-Ca_MV2M0pTUpb5wpU

**Comment by robertorp** [comment]
sim já dei uma lida! 
o Zeus acho que não tem suporte ainda, quer implementar para nós @alsantana ? fazer um pullzinho lindo e maravilhoso

**Comment by alsantana** [comment]
Ola meu caro, poxa quero sim
Vc me orienta como fazer?
grd abs e fica com Deus

**Comment by rodcardoso18** [comment]
Série Específica para a emissão da NFC-e em contingência

Prevista inicialmente para abril/2019, a série específica da NFC-e em contingência foi prorrogada para março/2020, através do Ajuste Sinief nº 6/2019.

**Comment by adeniltonbs** [comment]
@alsantana Bom dia, estou fazendo a opção de cancelamento por substituição. Assim que terminar, farei o commit.

**Comment by FrancielleWN** [comment]
Olá @adeniltonbs tem uma previsão de quando ficará pronta o cancelamento por substituição?

Pois tenho que implementar essa funcionalidade, porém tenho um prazo para entrega e gostaria muito de utilizar a sua implementação.

**Comment by adeniltonbs** [comment]
@FrancielleWN, boa tarde, no máximo terça feira faço pull. Já tá implementado no meu fork, mas ainda vou fazer alguns ajustes.

**Comment by FrancielleWN** [comment]
Que Joia! Obrigada

**Comment by adeniltonbs** [comment]
@FrancielleWN, o consumo do evento de cancelamento por substituição foi implementado no commit d5d765f5910fa3f249390808678062e3326f6130.

**Comment by FrancielleWN** [comment]
Estou encontrando um erro nos testes. Abri um novo Issues #982
