### ISSUE TITLE
Nunca emiti uma NF, meu sistema não tem isso. Preciso implantar NFe e agora?

### ISSUE THREAD

**Issue by adeniltonbs** [ZeusAutomacao/DFe.NET#94]
Breve descrição do problema que você vai encontrar pela frente:
"O projeto da NF-e deveria servir para facilitar a vida de todos e do governo, mas infelizmente o governo tem aproveitado o projeto para exigir cada vez mais informações por parte do contribuinte. 
Infelizmente não podemos mudar isso e o caminho para entender o projeto da NFe, como desenvolvedor, não é outro senão estudar bastante o projeto nacional da NFe.

Por onde começar?

1 - Adquira um certificado A1 para sua empresa ou pegue emprestado com um amigo que tenha (se não souber do que estou falando, converse com um contador);
2 - baixe a aplicação de homologação de NFe (testes) em http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=Jd9VnWmU9wY=;
3 - Emita algumas notas utilizando o aplicativo baixado no passo 2, no ambiente de testes, ao tempo em que lê o "Manual de Orientação do Contribuinte" http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=. Se não souber o que significa alguma informação exigida pelo aplicativo, converse com um contador. Essa aplicação de emissão de NFe é desenvolvida e distribuída pela Fazenda, ela vai te dar uma idéia dos dados necessários a serem adicionados no seu sistema.

Se fizeres isso entenderás o projeto da NFe.

**Comment by rftd** [comment]
Coloquei na wiki

https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/wiki/Nunca-emiti-uma-NF,-meu-sistema-n%C3%A3o-tem-isso.-Preciso-implantar-NFe-e-agora%3F

**Comment by adeniltonbs** [comment]
Boa Rafael, vlw

**Comment by rftd** [comment]
Dei uma editada no texto para ficar melhor.

**Comment by adeniltonbs** [comment]
Valeu. vou fechar esse issue então.
