### ISSUE TITLE
Não estou conseguindo acessar o grupo pelo Skype

### ISSUE THREAD

**Issue by edmilsonhora** [ZeusAutomacao/DFe.NET#941]
Bom dia! gostaria muito de participar do projeto, mas não estou conseguindo pelo skype acessar o grupo. alguma orientação?

**Comment by robertorp** [comment]
porque não ta dando certo? o que ta acontecendo?

**Comment by edmilsonhora** [comment]
Tento copiar o link para o skype, pesquiso e não aparece nada.

**Comment by edmilsonhora** [comment]
![capturar](https://user-images.githubusercontent.com/38793820/51992587-6c2a9300-2494-11e9-9dc6-490321e635f7.PNG)

**Comment by robertorp** [comment]
clica no link , creio eu que o skype vai abrir com a opção de entrar

**Comment by edmilsonhora** [comment]
Eu tenho o Skype instalado falo com várias pessoas, esse link tá querendo instalar novamente, só quero poder falar com alguém do grupo, para tirar umas dúvidas iniciais.

**Comment by edmilsonhora** [comment]
Ainda não consegui acessar o grupo pelo Skype.

**Comment by alexandresn** [comment]
Você pode tentar acessar o link pelo browser do desktop. Ou passa teu
usuário do Skype que eu te convido por lá.

Em qua, 30 de jan de 2019 16:26, edmilsonhora <notifications@github.com
escreveu:

**Comment by edmilsonhora** [comment]
Por favor me add  edmilson.silva@construtoralaterza.com.br

**Comment by alexandresn** [comment]
Te adicionei Edmilson.
