### ISSUE TITLE
OFF TOPIC - Sped Bloco K

### ISSUE THREAD

**Issue by scalarerp** [ZeusAutomacao/DFe.NET#944]
Alguem tem algum projeto para bloco K ou SPED Fiscal ?

**Comment by orochasamuel** [comment]
Dá uma olhada [aqui](https://github.com/AOPack/SPEDBr.NET).

**Comment by scalarerp** [comment]
Obrigado Samuel, já olhei isso, mas estou procurando algum projeto ou empresa que tenha algo mais concreto ou pronto para oferecer, ou pelo menos no nivel deste projeto que estamos.

**Comment by orochasamuel** [comment]
Tem a solução da [TecnoSpeed](https://tecnospeed.com.br/dfe/sped/).

Eles tem o consumo via API ou direto com a DLL.

**Comment by robertorp** [comment]
> Obrigado Samuel, já olhei isso, mas estou procurando algum projeto ou empresa que tenha algo mais concreto ou pronto para oferecer, ou pelo menos no nivel deste projeto que estamos.

defina algo mais concreto? 
porque o do @samuelrochaoliveira  gera o arquivo com base nas informações passadas, eu achava que isso era o máximo que um projeto desse pode fornecer rsrs

**Comment by orochasamuel** [comment]
Eu "acho" que entendi o que o @scalarerp quer @robertorp, que é "inputar" as informações no componente e já obter o arquivo pronto. Sem ter que montar na unha bloco a bloco e ainda calcular os valores para apuração de impostos. Eu penso que seja isso.

A ideia é chegar nesse mesmo ponto com o SPEDBr.
