### ISSUE TITLE
Nota Técnica 2018.005 - Cadastro do Responsável Técnico

### ISSUE THREAD

**Issue by rodrigordi** [ZeusAutomacao/DFe.NET#945]
Pessoal, 
alguém já investigou sobre o cadastro de Responsável Técnico definido na NT 2018.005 ?

A SEFAZ criou uma nova tag para que possa ser possível informar um CSRT que será gerado pela SEFAZ da UF do contribuinte.

Inicio em fev/2019 em homologacao e abr/2019 em produção.

Problema : onde devemos nos cadastrar para gerar o CSRT ?

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=xH2R0540Wqg=

**Comment by felixsevero** [comment]
Oi, só para comentar, até o momento não notei nenhuma diferença no ambiente de homologação para o meu estado (RS). Pelo que vi, a utilização é facultada aos estados, então, no meu caso, não fez nenhuma diferença (ainda, hehehe).

**Comment by ghost** [comment]
Olá pessoal aqui pra mim ja apareceu o erro

> 973 Rejeição: CNPJ do responsável técnico inválido

ou seja, mesmo em homologação algumas UFs já estão exigindo... 
existe uma previsão pra implantação dessa nova TAG?

**Comment by rodrigordi** [comment]
Qual UF apareceu isso para você?

Att/BR,
Rodrigo Rocha

________________________________
De: Leonardo Moura <notifications@github.com>
Enviado: domingo, março 10, 2019 10:58 AM
Para: ZeusAutomacao/DFe.NET
Cc: Rodrigo Rocha; Author
Assunto: Re: [ZeusAutomacao/DFe.NET] Nota Técnica 2018.005 - Cadastro do Responsável Técnico (#945)


Olá pessoal aqui pra mim ja apareceu o erro

973 Rejeição: CNPJ do responsável técnico inválido

ou seja, mesmo em homologação algumas UFs já estão exigindo...
existe uma previsão pra implantação dessa nova TAG?

**Comment by ghost** [comment]
foi BA

**Comment by rodrigordi** [comment]
Eu questionei SP e falaram que por enquanto nao.
Sefaz ES falou para ver novamente em abril.

Att/BR,
Rodrigo Rocha

________________________________
De: Leonardo Moura <notifications@github.com>
Enviado: domingo, março 10, 2019 11:07 AM
Para: ZeusAutomacao/DFe.NET
Cc: Rodrigo Rocha; Author
Assunto: Re: [ZeusAutomacao/DFe.NET] Nota Técnica 2018.005 - Cadastro do Responsável Técnico (#945)


foi BA

**Comment by ghost** [comment]
pois é.. a questão é q homologação ja tá exigindo (fev/2019).. pelo menos desde essa semana.. 
segue erro que mostra quanto tento transmitir em homologação para BA.

![image](https://user-images.githubusercontent.com/8151758/54086399-dbaf6000-4327-11e9-940f-b9666d07cccb.png)

**Comment by robertorp** [comment]
Irei adicionar nos próximos dias se ninguém adicionar antes. Implementar no meu projeto.

**Comment by ghost** [comment]
Excelente... Obrigado mesmo!

**Comment by EdsonRodrigoBA** [comment]
Tambem estou com esse problema em homologação aqui na BA.

**Comment by robertorp** [comment]
Se ninguém implementar antes de quarta eu implemento. Hoje e amanhã tenho compromisso.

**Comment by ghost** [comment]
Vlw Roberto obrigado..

**Comment by robertorp** [comment]
Nos commits https://github.com/ZeusAutomacao/DFe.NET/commit/e7abb10254d74149bf56f4877520e2ac8c05bf9e e https://github.com/ZeusAutomacao/DFe.NET/commit/3435bcf2f1613cdd6a45d556263bee9db7a76ca2

Adicionei já para adicionar as informações do responsável técnico 

lembrando que criei uma classe auxiliar para gerar o hashCSRT 

nome da classe `GerarHashCSRT`

Para usar ela basta usar um dos dois métodos estáticos que tem nela ambos métodos retornam o mesmo resultado.

Exemplo de uso:

```
string csrt = "G8063VRTNDMO886SFNK5LDUDEI24XJ22YIPO";
string chave = "41180678393592000146558900000006041028190697";
var hashCSRT = GerarHashCSRT.HashCSRT(csrt, chave); // retorno Njk2YmZhMmRlMTBjZTE3ZWFlZTM=
```
o mesmo retornará a hash. 

Segui o a **NT 2018.005 1.10** para gerar a hash

página 7 da **NT 2018.005 1.10**
![image](https://user-images.githubusercontent.com/10251705/54233149-19101b00-44eb-11e9-8a92-9ad187620e91.png)

**Comment by ghost** [comment]
Opa Roberto blz, ficou top.. você vai add no NuGet?

**Comment by robertorp** [comment]
https://github.com/ZeusAutomacao/DFe.NET/releases/tag/1.0.0.757

@consulpro já está lançado no nuget. Se não apareceu agora, logo logo aparecerá.

**Comment by ghost** [comment]
Já apareceu muito obrigado...

**Comment by EdsonRodrigoBA** [comment]
Obrigado, vou implementar.

**Comment by leandrossantos** [comment]
@robertorp não esta faltando o campo CSRT na classe InfRespTec ???

**Comment by FabioHenriqueMF** [comment]
@robertorp ainda nao consegui entender a questão do responsável técnico.
Pelo que entendi é uma informação  opcional a critério de cada UF.
Porém se a UF não obrigar a informação, posso enviar no XML?
Exemplo em SP estou enviando minhas NFe normalmente em homologação sem o responsável técnico.
Porém realizei a alteração para incluir, e da falha no XML.
Podem me ajudar?

**Comment by felixsevero** [comment]
@FabioHenriqueMF A nota técnica 2018.005 v1.20 adiou por tempo indeterminado o fornecimento de informações sobre o responsável técnico. Desta forma, não precisa se preocupar com isso, por enquanto.

**Comment by FabioHenriqueMF** [comment]
@felixsevero Sim foi isso que pensei mas veja:

![image](https://user-images.githubusercontent.com/21219148/55074442-137c0e80-506f-11e9-8ef0-c8f230a03b6a.png)

Da a entender que algumas UF manterão essa implementação...

**Comment by FabioHenriqueMF** [comment]
@felixsevero agradeço. É isso mesmo.


![image](https://user-images.githubusercontent.com/21219148/55074564-648c0280-506f-11e9-98b7-795296280cb9.png)

**Comment by FabioHenriqueMF** [comment]
@felixsevero mas tem um porém: essa implementação continua para algumas UFs:

![image](https://user-images.githubusercontent.com/21219148/55075349-871f1b00-5071-11e9-9b33-9c0d76178fec.png)

AL, AM, MS, PE, PR, SC e TO vão validar esse campo....
Vamos ter que criar esse grupo apenas para essas ufs?

**Comment by felixsevero** [comment]
Acredito que para essas UFs algumas informações terão sim que ser preenchidas (caso isso não mude em uma versão futura dessa nota técnica, é claro).
