### ISSUE TITLE
Impressão de código do produto com sobreposição da descrição

### ISSUE THREAD

**Issue by Leonardo-Moura** [ZeusAutomacao/DFe.NET#946]
Ao imprimir um Danfe NFCe utilizando um código de produto com 14 caracteres (código de barras), os últimos caracteres do código é sobreposto pela descrição do produto.

![danfesobreposto](https://user-images.githubusercontent.com/28692335/53087185-4cabe680-34e5-11e9-8e46-96c1890bdf72.jpg)

**Comment by robertorp** [comment]
Obrigado!
