### ISSUE TITLE
SEFAZ GO - Rejeição: XML da área de dados com codificação diferente de UTF-8 

### ISSUE THREAD

**Issue by gui-abrantes** [ZeusAutomacao/DFe.NET#948]
Me deparei com o mesmo erro desta issue, e vi q a solução seria desabilitar o envio do xml compactado....
pois bem, aqui na empresa um outro programador viu q estava faltando indicar que o xml seria em UTF-8, bastando colocar a linha --> < ? xml version="1.0" encoding="utf-8" ? > no cabeçalho do xml, visto nos testes aqui da empresa, q com esta linha tanto como o xml compactado, ou descompactado é enviado.

Dúvida, impactaria colocar esta linha ao enviar!? Poderia ser uma sugestão de pull request para o projeto.

**Comment by robertorp** [comment]
Explica isso para min melhor? quando e compactado da esse erro.. poderia postar onde você adicionou essa tag? Talvez consigo fazer isso por estado visto que não são todos estados que dão isso.

**Comment by gui-abrantes** [comment]
Oi boa noite, esse problema é referente ao issue #886 citado a 3 meses atrás onde vc deu a solução de desabilitar a compactação! Pois bem, percebemos que se colocar o enconding UTF-8 ( < ?xml version="1.0" encoding="UTF-8"? > ) na frente do XML, não dá erro! Mesmo mandando compactado!

**Comment by robertorp** [comment]
adicionei no Zeus so na parte de compactar por hora que e a que esta dando erro.. 
depois se poder testar, agradeço, aqui testei e funcionou
Lembrando que mudei toda a estrutura de emissão do Zeus também! Está melhor que antes!
![image](https://user-images.githubusercontent.com/10251705/54071458-6bcba780-424b-11e9-902b-5454c0fa6167.png)
