### ISSUE TITLE
Emissão de NFe para C# MVC Web

### ISSUE THREAD

**Issue by guilhermefmbatista** [ZeusAutomacao/DFe.NET#95]
Adenilton, bom dia!
Primeiramente parabéns pela biblioteca. Fiz o download ontem, dei uma olhada e está tudo estruturado.
Agora eu gostaria de saber se você ou alguém aqui da comunidade já utilizou a sua biblioteca para a emissão da NFe em uma aplicação web?
Vou começar a desenvolver hoje e estou com dúvidas quanto a implementação.
Caso você ou alguém da comunidade tiver algo para compartilhar, fico agradecido.
Obrigado.

**Comment by adeniltonbs** [comment]
Sim funciona para uma aplicação ASP.NET MVC, veja esse issue https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/81 e esse https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/issues/91

**Comment by celinolimac** [comment]
Bom dia Guilherme... como dito anteriormente pelo Adenilton, essas issues comprovam o funcionamento...

Tenho uma aplicação wpf e asp net mvc fazendo o uso da biblioteca e tao rodando de boa... essa biblioteca aqui é fantástica!

**Comment by guilhermefmbatista** [comment]
Ok, obrigado Adenilton e Celino pelos esclarecimentos. 
Qualquer dúvida posto algo aqui.
Abraços

**Comment by Braytiner** [comment]
@celinolimac Estou desenvolvendo uma aplicação ASP NET MVC e estou com algumas duvidas sobre como utilizar a biblioteca, você poderia dar uma força fornecendo alguns exemplos?

Obrigado!

**Comment by Dugrego** [comment]
Preciso desenvolver no meu sistema uma tela onde coloco a chave da Nfe do meu fornecedor, e me retorne todas informações dela. Alguém sabe me dizer qual o serviço  eu devo trabalhar para fazer isto?

**Comment by denernun** [comment]
Fazendo a manifestação do destinatário, você tem acesso ao xml da nota
emitida contra sua empresa.
