### ISSUE TITLE
Erro na emissão NFC-e em Produção MG

### ISSUE THREAD

**Issue by tulio-webrestaurante** [ZeusAutomacao/DFe.NET#950]
Alguém está conseguindo emitir a NFC-e em produção? Consigo emitir no ambiente de homologação normalmente, mas quando mudo para Produção ele apresenta erro na assinatura, já removi acentuação, verifiquei os dados e espaços em branco, está tudo correto, mas não consigo emitir.

*Obs.: Consegui emitir 2 notas antes do dia 26/02 após essa data sem mudar nada no sistema não consegui mais.

**Comment by robertorp** [comment]
manda mais informações sobre o erro e seu código fonte 
imagens

**Comment by tulio-webrestaurante** [comment]
O erro aparece mesmo usando a última versão baixada daqui mesmo do sistema, modificando apenas os dados do emissor.

O Xml de retorno é: 
`<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>W-1.1.25</verAplic><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>31</cUF><dhRecbto>2019-03-03T18:31:40-03:00</dhRecbto><nRec>0</nRec><tMed>0</tMed><protNFe versao="4.00"><infProt><tpAmb>1</tpAmb><verAplic>W-1.1.25</verAplic><chNFe>31190329862033000122650010000000041000012349</chNFe><dhRecbto>2019-03-03T18:31:40-03:00</dhRecbto><digVal>sex5M8IM4CJ85nYANvsBtW4NAfU=</digVal><cStat>297</cStat><xMotivo>Rejeição: Assinatura difere do calculado</xMotivo></infProt></protNFe></retEnviNFe>`

**Comment by robertorp** [comment]
Você esta alterando o xml depois de assinado, verifique o fonte seu

**Comment by tulio-webrestaurante** [comment]
O fonte é o mesmo do projeto, fiz o download e não editei nenhuma linha de código, e mesmo assim dá erro, antes do dia 25/03 consegui emitir 2 notas

**Comment by tulio-webrestaurante** [comment]
Estou usando o NFe.AppTeste, em homologação funciona normalmente, quando mudo para Produção que ele retorna a mensagem de erro

**Comment by ricardopdv** [comment]
Se estiver usando o mesmo xml tem que gerar novamente o infnfesupl e o qrcode pq muda o código do ambiente e se mudar de contingência tb tem
________________________________

**Comment by tulio-webrestaurante** [comment]
> Se estiver usando o mesmo xml tem que gerar novamente o infnfesupl e o qrcode pq muda o código do ambiente e se mudar de contingência tb tem
> […](#)
> ________________________________ From: Túlio Nogueira <notifications@github.com> Sent: Sunday, March 3, 2019 9:44:22 PM To: ZeusAutomacao/DFe.NET Cc: Subscribed Subject: Re: [ZeusAutomacao/DFe.NET] Erro na emissão NFC-e em Produção MG (#950) Estou usando o NFe.AppTeste, em homologação funciona normalmente, quando mudo para Produção que ele retorna a mensagem de erro — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZeusAutomacao%2FDFe.NET%2Fissues%2F950%23issuecomment-469084051&data=02%7C01%7C%7C9b0d50896cff48038bb308d6a03a8b8a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636872570633310730&sdata=jtsACCrBEDPRrqH34MeUNTWKUe280IX2xqnqrwaCKk8%3D&reserved=0>, or mute the thread<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANjVHVnPivULor-kIZuPXlZqJ0G7poLUks5vTGxmgaJpZM4bZ-PP&data=02%7C01%7C%7C9b0d50896cff48038bb308d6a03a8b8a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636872570633320744&sdata=5p8DFWK5BMUmhKzKHjSOKUSugvkeVI6%2BLVjMKB9GqmE%3D&reserved=0>.

Após assinar o xml e inserir o qrcode e a infnfesupl devo assinar novamente?

**Comment by robertorp** [comment]
o código de CSC e ID Token mudam 
eles são um para homologação
e outro para homologação 
como o amigo falou

**Comment by tulio-webrestaurante** [comment]
O CSC e id token só me forneceram um

**Comment by robertorp** [comment]
Seguinte.. 
como funciona o CSC e id token

![image](https://user-images.githubusercontent.com/10251705/53707608-741c8080-3e0e-11e9-8b63-7800fae0a77f.png)

Existe para produção e homologação 
ambos são diferentes.. não são iguais. 

OU seja.. você devia ter dois ai em mãos, um CSC e id token para produção e homologação 

CSC = bagunçaHomologacao
id = 1 (imagino eu)

CSC = bagunçaProdução
id = 1 (imagino eu) 

a foto que mostrei foi so pra ilustrar.. aqui em goiás o próprio contribuinte gera o id/csc, não é assim para todos estados infelizmente.

**Comment by tulio-webrestaurante** [comment]
Acabei de solicitar um novo código para produção, o estranho é que antes do dia 25/02 consegui emitir 2 NFC-e em produção.

Assim que obtiver o novo código responderei o tópico

**Comment by tulio-webrestaurante** [comment]
Não está parecendo ser o CSC, coloquei um CSC incorreto no ambiente de Homologação e a mensagem de erro foi: Rejeição: Código de Hash no QR-Code difere do calculado

Se no ambiente de produção fosse o CSC incorreto deveria retornar a mesma mansagem

**Comment by robertorp** [comment]
descobriu o que era?

**Comment by tulio-webrestaurante** [comment]
> descobriu o que era?

Descobri sim, por tentativa e erro. O objeto que deve ser assinado é o nfeLocal.infNFe.

**Comment by robertorp** [comment]
Obrigado! qualquer coisa abra uma nova issue
