### ISSUE TITLE
Instalação Via Nuget

### ISSUE THREAD

**Issue by ucaneto** [ZeusAutomacao/DFe.NET#951]
Pessoal Iniciei um sistema usando o Zeus e baixei as dlls via nuget ai fui fazer a configuração 
public ConfiguracaoApp()
{
CfgServico = ConfiguracaoServico.Instancia;
CfgServico.tpAmb = TipoAmbiente.Homologacao;
CfgServico.tpEmis = TipoEmissao.teNormal;
CfgServico.ProtocoloDeSeguranca = ServicePointManager.SecurityProtocol;
Emitente = new emit { CPF = "", CRT = CRT.SimplesNacional };
EnderecoEmitente = new enderEmit();
ConfiguracaoEmail = new ConfiguracaoEmail("email@dominio.com", "senha", "Envio de NFE", Resources.MensagemHtml, "smtp.dominio.com", 587, true, true);
ConfiguracaoCsc = new ConfiguracaoCsc("000001", "");
ConfiguracaoDanfeNfce = new ConfiguracaoDanfeNfce(NfceDetalheVendaNormal.UmaLinha, NfceDetalheVendaContigencia.UmaLinha);
}

e a linha
ConfiguracaoDanfeNfce = new ConfiguracaoDanfeNfce(NfceDetalheVendaNormal.UmaLinha, NfceDetalheVendaContigencia.UmaLinha);

não acha referencia, ela não vem quando instal o pacote via nuget?

**Comment by robertorp** [comment]
A impressão não está no nuget.
Para ter as impressões você deve baixar o projeto e compilar

**Comment by felixsevero** [comment]
Só por curiosidade agora, existe algum motivo para o código de impressão não estar no Nuget?
:)

**Comment by robertorp** [comment]
A nativa já poderia estar a muito tempo. Mas nunca coloquei. 
A maioria das pessoas pegam a impressão e adaptam para si mesmas.. fica sendo uma base somente.

**Comment by felixsevero** [comment]
Entendo. Eu utilizo sem modificações, não sei se sou uma exceção, hehehe.
Se esse for o caso para muitos, poderia ser interessante ter isso no Nuget.
Obrigado :)

**Comment by ucaneto** [comment]
Obrigador pela ajuda.
