### ISSUE TITLE
Erro consulta de CTe

### ISSUE THREAD

**Issue by FelipeOsti** [ZeusAutomacao/DFe.NET#953]
Estou encontrando erros na consulta de um CTe em especifico:
 Chave Acesso: 43190244914992002777570010021414281021414289
 UF: RS
Vi que o erro esta na deserialização do XML para string... mas não consegui identificar o motivo. Alguém pode dar uma olhada para mim? Segue anexo do retorno da Consulta em XML.

[xml_consulta_CTe.txt](https://github.com/ZeusAutomacao/DFe.NET/files/2946084/xml_consulta_CTe.txt)

**Comment by orochasamuel** [comment]
Já tentou validar?

https://www.sefaz.rs.gov.br/cte/cte-val.aspx

![image](https://user-images.githubusercontent.com/15462690/54034216-12a13c80-4195-11e9-8fd2-d6d174c1d057.png)

**Comment by FelipeOsti** [comment]
Realmente estranho não passar no validador. Mais estranho ainda, é esse ser o retorno que eu estou tendo do SEFAZ-RS na consulta da chave de acesso indicada acima. Consegue fazer a consulta da chave de acesso para ver se está ok?!

**Comment by orochasamuel** [comment]
Normal

![image](https://user-images.githubusercontent.com/15462690/54042725-9533f700-41a9-11e9-8f22-41c8a3150c7f.png)

**Comment by orochasamuel** [comment]
Cara, instala o Notepad Plus Plus ( mas a versão 64x ) e complementa a instalação com um plugin chamado "XML Tools".

Depois disso abre o XML, usa a opção "Pretty print (XML only - with line breaks) ou Ctrl + Alt + Shift + B  " para ele ficar "bonitinho" e fácil de você identificar as informações.. agora vamos lá...

![image](https://user-images.githubusercontent.com/15462690/54044030-c235d900-41ac-11e9-9e61-784f8576936d.png)

Todas tags de evento estão com o mesmo namespace, não sei se é correto. Não trabalho com CT-e. Mas é justamente isso que o validador de RS está acusando, há um elemento filho dentro de procEventoCTe inválido. Faltando o namespace .../cte:eventoCTe. Quem tem mais experiência com CT-e - até onde eu sei é o sr. @robertorp - talvez ele possa te ajudar, conforme a disponibilidade dele.

Mas faz o seguinte teste, consulta esse CT-e no endereço [http://www.cte.fazenda.gov.br/](http://www.cte.fazenda.gov.br/) e baixa o XML direto lá. E tenta validar.

**Comment by FelipeOsti** [comment]
Vi que tinha atualização nos componentes, mas mesmo após as atualizações continuo com o erro "Erro no documento XML (1, 6174)." após a requisição de consulta do CTRS com chave de acesso 35190300574193000194570010000369551000376486 do estado de SP.
@samuelrochaoliveira Independente de como esta o XML no site da receita, o problema esta acontecendo no componente CTe do Zeus. Pelo que vi, até onde acompanhei o processo, o problema estava em um deserialize do xml para os modelos do Zeus.
Aguardo retorno.

**Edit:
"StackTrace": "   em System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)\r\n   em System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)\r\n   em DFe.Utils.FuncoesXml.XmlStringParaClasse[T](String input)\r\n   em CTe.Classes.Servicos.Consulta.retConsSitCTe.LoadXml(String xml, consSitCTe consSitCTe)\r\n   em CTe.Servicos.ConsultaProtocolo.ConsultaProtcoloServico.ConsultaProtocolo(String chave)

Vi que tinha uma innerException com o seguinte valor:
"ExceptionMessage": "Erro de validação de instância: '510620' não é um valor válido para TipoEvento.",
        "ExceptionType": "System.InvalidOperationException".

Espero que consigam me ajudar.

**Comment by FelipeOsti** [comment]
Achei o Problema.

Na classe CTe.Classes.Servicos.Evento.Flags.TipoEvento não existia o Tipo de Evento 510620.

Inclui dois valores na classe:
`[XmlEnum("510620")]
PassagemAutomatica = 510620,
[XmlEnum("310620")]
RegistroPassagem = 310620`

Fiz uma breve pesquisa no https://www.oobj.com.br/bc/search.php por TpEvento e listou todos os eventos do MDFe, identifiquei que existem mais alguns eventos que não estão na lista. Vou adicionar conforme necessário para mim.

Se possível incluir esses novos códigos em uma próxima versão pois utilizo o Nuget para projetos.

Aguardo retorno.

**Edit.
Inclusão de TpEvento:
`[XmlEnum("310611")]
 MDFeCancelado = 310611,
 [XmlEnum("240130")]
 MDFeComplementarAutorizado = 240130,
 [XmlEnum("440﻿140﻿")]
 AutorizaRedespachoIntermediario = 440140
 [XmlEnum("440130")]
 AutorizadoRedespacho = 440130,
 [XmlEnum("440150")]
 AutorizadoSubContratacao = 440150`

Link com todos os tipos:
https://www.projetoacbr.com.br/forum/topic/50331-pcnconversao-bug-identificado-no-strtotpevento-problema-ao-verificar-status-de-nfc-e-cancelada-por-substitui%C3%A7%C3%A3o/?tab=comments#comment-332081

**Comment by FelipeOsti** [comment]
Ficou assim o objeto completo ajustado
`[XmlEnum("-99999")]
        NaoMapeado = -99999,
        [XmlEnum("110111")]
        Cancelamento = 110111,
        [XmlEnum("110110")]
        CartaCorrecao = 110110,
        [XmlEnum("210200﻿")]
        ManifestoDestinoConfirmacao = 210200,
        [XmlEnum("210210﻿﻿﻿﻿﻿﻿")]
        ManifestoDestinoCiencia = 210210,
        [XmlEnum("210220")]
        ManifestoDestinoDesconhecimento = 210220,
        [XmlEnum("210240")]
        ManifestoDestinatarioNaoRealizada = 210240,
        [XmlEnum("110112﻿﻿")]
        Encerramento = 110112,
        [XmlEnum("110113﻿﻿﻿")]
        EPEC = 110113,
        [XmlEnum("110114﻿﻿﻿﻿")]
        InclusaoCondutor = 110114,
        [XmlEnum("110160﻿﻿﻿﻿")]
        MultiModal = 110160,
        [XmlEnum("310620")]
        RegistroPassagem = 310620,
        [XmlEnum("510620")]
        PassagemAutomatica = 510620,
        [XmlEnum("110140﻿")]
        EPECNFe = 110140,
        [XmlEnum("610600﻿﻿")]
        RegistroCTe = 610600,
        [XmlEnum("610501﻿﻿")]
        RegistroPassagemNFeCancelado = 610501,
        [XmlEnum("610550﻿﻿﻿﻿")]
        RegistroPassagemNFeRFID = 610550,
        [XmlEnum("610601﻿﻿﻿﻿﻿")]
        CTeCancelado = 610601,
        [XmlEnum("610611﻿﻿﻿﻿﻿")]
        MDFeCancelado = 610611,
        [XmlEnum("990900﻿﻿﻿﻿﻿﻿")]
        VistoriaSuframa = 990900,
        [XmlEnum("111500﻿﻿﻿﻿﻿﻿")]
        PedidoProrrogacao1 = 111500,
        [XmlEnum("111501﻿﻿﻿﻿﻿﻿")]
        PedidoProrrogacao2 = 111501,
        [XmlEnum("111502﻿﻿﻿﻿﻿﻿")]
        CancelPedidoProrrogacao1 = 111502,
        [XmlEnum("111503")]
        CancelPedidoProrrogacao2 = 111503,
        [XmlEnum("411500")]
        EventoFiscoPP1 = 411500,
        [XmlEnum("411501")]
        EventoFiscoPP2 = 411501,
        [XmlEnum("411502")]
        CancelEventoFiscoPP1 = 411502,
        [XmlEnum("411503")]
        CancelEventoFiscoPP2 = 411503,
        [XmlEnum("610500﻿")]
        RegistroPassagemNFe = 610500,
        [XmlEnum("990910﻿")]
        ConferenciaInternalizacao = 990910,
        [XmlEnum("000000﻿")]
        CTeAutorizado = 000000,
        [XmlEnum("610610﻿﻿")]
        MDFeAutorizado = 610610,
        [XmlEnum("610110")]
        Desacordo = 610110,
        [XmlEnum("110170")]
        GTV = 110170,
        [XmlEnum("310610")]
        MDFeAutorizado2 = 310610,
        [XmlEnum("110115")]
        NaoEmbarque = 110115,
        [XmlEnum("310611")]
        MDFeCancelado2 = 310611,
        [XmlEnum("610614﻿")]
        MDFeAutorizadoCTe = 610614,
        [XmlEnum("610510﻿")]
        PassagemNFeProdMDFe = 610510,
        [XmlEnum("610514﻿﻿")]
        PassagemNFeProdMDFeCTe = 610514,
        [XmlEnum("610554﻿﻿﻿")]
        PassagemAutoMDFeCTe = 610554,
        [XmlEnum("610615﻿﻿﻿")]
        CancelaCTeAutoMDFeCTe = 610615,
        [XmlEnum("790700﻿﻿﻿")]
        AverbacoaExportacao = 790700,
        [XmlEnum("240130")]
        MDFeComplementarAutorizado = 240130,
        [XmlEnum("240131")]
        CancelaCTeComplementar = 240131,
        [XmlEnum("240140")]
        CTeSubstituicao = 240140,
        [XmlEnum("240150")]
        CTeAnulacao = 240150,
        [XmlEnum("240160")]
        LiberacaoEPEC = 240160,
        [XmlEnum("240170")]
        LiberaPrazoCancelamento = 240170,
        [XmlEnum("440130")]
        AutorizadoRedespacho = 440130,
        [XmlEnum("440﻿140﻿")]
        AutorizaRedespachoIntermediario = 440140,
        [XmlEnum("440150")]
        AutorizadoSubContratacao = 440150,
        [XmlEnum("440160")]
        AutorizaServicoMultiModal = 440160,
        [XmlEnum("110112")]
        cancelaSubstituta = 110112,
        [XmlEnum("110116")]
        AlteracaoPoltrona = 110116`

**Comment by orochasamuel** [comment]
Então a desserialização funcionou @FelipeOsti ?

**Comment by FelipeOsti** [comment]
@samuelrochaoliveira Sim, após a inclusão dos valores que citei acima na classe TipoEvento.cs, a desserialização funcionou certinho.

Acho interessante, a inclusão desses valores na classe para a nova versão do componente no NUGET.

Att,

**Comment by robertorp** [comment]
Se tiver feito um pull request disso imagino eu que já esta no nuget.
