### ISSUE TITLE
Erro ao tentar enviar Nfce versão 1.0.1.816 no nuguet

### ISSUE THREAD

**Issue by LosDeveloper** [ZeusAutomacao/DFe.NET#956]
Erro ocorre na ultima versão disponibilizada no Nuguet
Referência de objeto não definida para uma instância de um objeto.

   em DFe.Wsdl.DFeSoapHttpClientProtocol.GetTagConverter(String ret, String tag) na D:\Projetos\Visual Studio\DFe.NET-master\Shared.DFe.Wsdl\DFeSoapHttpClientProtocol.cs:linha 19
   em NFe.Wsdl.Autorizacao.NFeAutorizacao4.ExecuteZip(String nfeDadosMsgZip) na D:\Projetos\Visual Studio\DFe.NET-master\NFe.Wsdl\Autorizacao\NFeAutorizacao4.cs:linha 47
   em NFe.Servicos.ServicosNFe.NFeAutorizacao4(Int32 idLote, IndicadorSincronizacao indSinc, List`1 nFes, Boolean compactarMensagem) na D:\Projetos\Visual Studio\DFe.NET-master\NFe.Servicos\ServicosNFe.cs:linha 1083
   em NFe.Servicos.ServicosNFe.NFeAutorizacao(Int32 idLote, IndicadorSincronizacao indSinc, List`1 nFes, Boolean compactarMensagem) na D:\Projetos\Visual Studio\DFe.NET-master\NFe.Servicos\ServicosNFe.cs:linha 1039
   em NFe.AppTeste.MainWindow.BtnCriareEnviar3_Click(Object sender, RoutedEventArgs e) na D:\Projetos\Visual Studio\DFe.NET-master\NFe.AppTeste\MainWindow.xaml.cs:linha 334

**Comment by LosDeveloper** [comment]
Alguém mais pegou esse erro pro estado de MG hoje?

**Comment by robertorp** [comment]
me diz , enviou como? me manda os paramtros usados no NFeAutorizacao que você usou 

acho que já sei o que aconteceu, vou colocar um if (retorno == null) trow exception lá , estou achando que o retorno veio null e na hora de obter a tag retEnviNFe ele deu object null reference, bom estou somente presumindo

**Comment by LosDeveloper** [comment]
Parametros utilizados.
Emissao em Homologação
Tipo de emissão normal
servicoNFe.NFeAutorizacao(Convert.ToInt32(lote), IndicadorSincronizacao.Sincrono,
                        new List<NFe.Classes.NFe> { nfce }, true /*Envia a mensagem compactada para a SEFAZ*/);

**Comment by robertorp** [comment]
coloca o ultimo parâmetro como false que irá funcionar 
vou verificar o motivo de MG não esta tendo suporte pra compactação, talvez e algo especifico do estado, o retorno ou o envio

**Comment by LosDeveloper** [comment]
Tb já tentei com false e apresentou o mesmo problema.

Aparentemente o erro está nesse método:
-> nessa linha var xmlConverter = xmlList[0].OuterXml;
protected virtual string GetTagConverter(string ret, string tag)
        {
            XmlDocument doc = new XmlDocument();
            doc.Load(new System.IO.StringReader(ret));
            XmlNodeList xmlList = doc.GetElementsByTagName(tag);
            var xmlConverter = xmlList[0].OuterXml;
            return xmlConverter;
        }

**Comment by robertorp** [comment]
ta rolando um papo no skype , MG ta com problemas no servidor, estou com clientes de lá com problemas

**Comment by robertorp** [comment]
contingência de MG ta ativa mas fora do ar também

**Comment by LosDeveloper** [comment]
Entendi!
Aguardar então
Obrigado!
