### ISSUE TITLE
servicoNFe.NFeAutorizacao - FileNotFoundException

### ISSUE THREAD

**Issue by RodrigoQC** [ZeusAutomacao/DFe.NET#959]
Certificado que eu estou usando é um A1.

![Sem título](https://user-images.githubusercontent.com/22171664/54921640-04695500-4ee5-11e9-900e-1478a652e4af.png)

não sigo ver o local exato da exceção dentro da função "CriaWsdlAutorizacao" por quê estou trabalhando usando projeto pelo nuget

**Comment by RodrigoQC** [comment]
eu encontrou outra pessoa com o mesmo problema no tópico de nome "Suporte Net.core 2.0" e que não foi resolvido.

**Comment by robertorp** [comment]
vc setou o tipo de certificado digital como A1?

**Comment by RodrigoQC** [comment]
Sim, A1Repositorio

**Comment by RodrigoQC** [comment]
eu criei os projetos do .net framework dentro da solução e depois referenciei-o para o projeto .net core mas mesmo assim o erro persistiu.

**Comment by RodrigoQC** [comment]
por desencargo de consciência eu tentei importa no projeto .net core a dll do System.Web.references mas com isso ao chamar a função era disparada a Exceção BadImageFormatException

**Comment by robertorp** [comment]
já foi resolvido? se sim ok.. se não re-abra a issue.
