### ISSUE TITLE
Duvida NFE para DANFE

### ISSUE THREAD

**Issue by henriquedpereira** [ZeusAutomacao/DFe.NET#96]
Instalei o projeto teste aqui, porem quando envio o xml sempre me retorna = `O XML informado não é um NFCe!` 

Nessa linha:

```
if (proc.NFe.infNFe.ide.mod != ModeloDocumento.NFCe)
                    throw new Exception("O XML informado não é um NFCe!");

```

O valor de `proc.NFe.infNFe.ide.mod` esta = `NFe.Classes.Informacoes.Identificacao.Tipos.ModeloDocumento.NFe`, era para pegar 55.
Sabe se tenho que fazer alguma configuração a mais? obrigado.

**Comment by adeniltonbs** [comment]
Se entendi você está comparando proc.NFe.infNFe.ide.mod (modelo 55) com ModeloDocumento.NFCe (modelo 65) e esperando que seja igual é isso?

**Comment by henriquedpereira** [comment]
Oque ocorre é quando mando o xml ele informa que não é um NFCe, para mandar só NFe que é 55, não é nessa mesma opção?

**Comment by adeniltonbs** [comment]
Henrique, vc poderia enviar mais detalhes do que está tentando fazer?

**Comment by henriquedpereira** [comment]
Adenilson, oque eu preciso é gerar o pdf do danfe atras de um xml de NFe, existe essa opção no componente? Ou só tem o de NFCe? obrigado.

**Comment by adeniltonbs** [comment]
A impressão do DANFE da NFe está sendo implementada ainda. Por enquanto a biblioteca só tem recursos de imprimir/Exportar/Visualizar impressão do DANFE da NFCe.

**Comment by henriquedpereira** [comment]
entendi, era essa minha duvida, obrigado.
