### ISSUE TITLE
oque você usa para gerar as webservice de envio?

### ISSUE THREAD

**Issue by robertorp** [ZeusAutomacao/DFe.NET#97]
Teria como dizer oque é usado para envio da webservice? como você gera o código de envio? (ele é gerado né)

Obrigado.

**Comment by adeniltonbs** [comment]
As classes para consumo do webservices são montadas com base na descrição xml fornecida para cada webservice (wsdl).

Note que no final de alguns endereços dos serviços você vai encontrar "?wsdl". Se você acessar a url, passando o certificado, você vai encontrar a descrição xml para consumo do serviço. Os casos onde não há "?wsdl" no final da url, basta vc adicionar e acessá-la. Ex: https://nfe.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx?wsdl

Aqui vc vai encontrar mais informações sobre wsdl:
https://msdn.microsoft.com/en-us/library/ms996486.aspx

Se deseja saber se é utilizado um código proxy, para depois gerar o assembly em runtime, com base no wsdl, com as instruções para consumo do webservice, a resposta é NÃO.

Você pode olhar diretamente em https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe/tree/master/NFe.Wsdl e ver como tudo funciona.
