### ISSUE TITLE
Vocês ja implementaram as modificações da NT 2018.005 sobre os ST para o ICMS 60, ICMS ST e ICMS 500?

### ISSUE THREAD

**Issue by borgessys** [ZeusAutomacao/DFe.NET#974]

**Comment by adrianotrentim** [comment]
Estou com o mesmo problema, SP está exigindo o campo vICMSSubistituto

**Comment by adrianotrentim** [comment]
Dei uma olhada nos fontes, os campos já existem no CST 60 e CSOSN 500, falta no ICMSBasico e no ICMSGeral

**Comment by adrianotrentim** [comment]
Criei o PR 975, adicionando este campo no ICMSGeral

**Comment by marcosgerene** [comment]
PR Aceito

**Comment by borgessys** [comment]
o campo vICMSSubstituto tem que estar nas classes ICMS60, ICMSST e ICMS500. 
e a classe ICMSST esta faltando os seguintes campos conforme a NT2018.005 com a imagem abaixo

![image](https://user-images.githubusercontent.com/13354615/57450985-5ae0e780-7236-11e9-8744-3a2172b41230.png)

**Comment by marcosgerene** [comment]
@borgessys abra um novo PR e vamos analisar
