### ISSUE TITLE
Implementação impostos NT 2018.005 ICMS60, ICMSST, ICMSSN500

### ISSUE THREAD

**Issue by borgessys** [ZeusAutomacao/DFe.NET#976]
Incluir o campo "vICMSSubstituto" nas classes ICMS60, ICMSST e ICMSSN500.
Alterar a classe ICMSST incluindo os seguintes campos conforme a NT2018.005 conforme a imagem abaixo:

![image](https://user-images.githubusercontent.com/13354615/57479507-f3e22380-7273-11e9-85e8-ea3b287ebf0d.png)

**Comment by borgessys** [comment]
@marcosgerene

**Comment by marcosgerene** [comment]
@borgessys baixei a NT

> https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjp6v2gx5PiAhXXLLkGHagtAi8QFjAAegQIABAC&url=http%3A%2F%2Fwww.nfe.fazenda.gov.br%2Fportal%2FexibirArquivo.aspx%3Fconteudo%3DR3JORctV9L0%3D&usg=AOvVaw1P63F6NUybIEh4UiMiBdhy

Foi implementado em: https://github.com/ZeusAutomacao/DFe.NET/commit/dfc4e18c321ab4753eb2f29cd41ae179eee288b1
