### ISSUE TITLE
Danfe Fast com erro

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#979]
Retorna o seguinte erro
{"(Memo44): Erro CS0246: O nome de namespace ou o tipo 'Estado' não pôde ser encontrado. Precisa de uma diretiva using ou de uma referência de assembly?\r\n"}

**Comment by marcosgerene** [comment]
@ThalisonSantos por favor, poste o xml.

**Comment by ThalisonSantos** [comment]
@marcosgerene 
`<?xml version="1.0" encoding="ISO-8859-1"?>
<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
<NFe>
<infNFe versao="4.00" Id="NFe27190524166332000109550010000001371000001379">
<ide>
<cUF>27</cUF>
<cNF>00000137</cNF>
<natOp>VENDA MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS</natOp>
<mod>55</mod>
<serie>1</serie>
<nNF>137</nNF>
<dhEmi>2019-05-15T00:00:00-03:00</dhEmi>
<dhSaiEnt>2019-05-15T15:32:50-03:00</dhSaiEnt>
<tpNF>1</tpNF>
<idDest>1</idDest>
<cMunFG>2704302</cMunFG>
<tpImp>1</tpImp>
<tpEmis>1</tpEmis>
<cDV>9</cDV>
<tpAmb>2</tpAmb>
<finNFe>1</finNFe>
<indFinal>1</indFinal>
<indPres>1</indPres>
<procEmi>0</procEmi>
<verProc>1.2.130.0513</verProc>
</ide>
<emit>
<CNPJ>24166332000109</CNPJ>
<xNome>JALL TECNOLOGIA DA INFORMACAO LTDA</xNome>
<xFant>INTEGRASYS TECNOLOGIA</xFant>
<enderEmit>
<xLgr>RUA DURVAL COELHO NORMANDE</xLgr>
<nro>25</nro>
<xBairro>FAROL</xBairro>
<cMun>2704302</cMun>
<xMun>MACEIÓ</xMun>
<UF>AL</UF>
<CEP>57055210</CEP>
<cPais>1058</cPais>
<xPais>BRASIL</xPais>
<fone>8232212335</fone>
</enderEmit>
<IE>240739078</IE>
<CRT>3</CRT>
</emit>
<dest>
<CNPJ>24166332000109</CNPJ>
<xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
<enderDest>
<xLgr>AV MOREIRA E SILVA</xLgr>
<nro>374</nro>
<xBairro>FAROL</xBairro>
<cMun>2704302</cMun>
<xMun>MACEIÓ</xMun>
<UF>AL</UF>
<CEP>57051500</CEP>
<cPais>1058</cPais>
<xPais>Brasil</xPais>
<fone>33264900</fone>
</enderDest>
<indIEDest>1</indIEDest>
<IE>240739078</IE>
</dest>
<det nItem="1">
<prod>
<cProd>177</cProd>
<cEAN>SEM GTIN</cEAN>
<xProd>*PAPEL ALTA ALVURA ALCALINO</xProd>
<NCM>87042190</NCM>
<CEST>2501700</CEST>
<CFOP>5102</CFOP>
<uCom>UN</uCom>
<qCom>1.0000</qCom>
<vUnCom>16.5000000000</vUnCom>
<vProd>16.50</vProd>
<cEANTrib>SEM GTIN</cEANTrib>
<uTrib>UN</uTrib>
<qTrib>1.0000</qTrib>
<vUnTrib>16.5000000000</vUnTrib>
<indTot>1</indTot>
<nItemPed>1</nItemPed>
</prod>
<imposto>
<vTotTrib>4.20</vTotTrib>
<ICMS>
<ICMS40>
<orig>0</orig>
<CST>40</CST>
</ICMS40>
</ICMS>
<PIS>
<PISNT>
<CST>07</CST>
</PISNT>
</PIS>
<COFINS>
<COFINSNT>
<CST>07</CST>
</COFINSNT>
</COFINS>
</imposto>
</det>
<total>
<ICMSTot>
<vBC>0.00</vBC>
<vICMS>0.00</vICMS>
<vICMSDeson>0.00</vICMSDeson>
<vFCP>0.00</vFCP>
<vBCST>0.00</vBCST>
<vST>0.00</vST>
<vFCPST>0.00</vFCPST>
<vFCPSTRet>0.00</vFCPSTRet>
<vProd>16.50</vProd>
<vFrete>0.00</vFrete>
<vSeg>0.00</vSeg>
<vDesc>0.00</vDesc>
<vII>0.00</vII>
<vIPI>0.00</vIPI>
<vIPIDevol>0.00</vIPIDevol>
<vPIS>0.00</vPIS>
<vCOFINS>0.00</vCOFINS>
<vOutro>0.00</vOutro>
<vNF>16.50</vNF>
<vTotTrib>4.20</vTotTrib>
</ICMSTot>
</total>
<transp>
<modFrete>0</modFrete>
<vol>
<qVol>0</qVol>
<nVol>0</nVol>
<pesoL>0.000</pesoL>
<pesoB>0.000</pesoB>
</vol>
</transp>
<cobr>
<fat/>
</cobr>
<pag>
<detPag>
<tPag>90</tPag>
<vPag>0.00</vPag>
</detPag>
</pag>
<infAdic>
<infCpl>Valor aproximados dos tributos R$ 4,20 - 25,45% Fonte: IBPT;</infCpl>
</infAdic>
</infNFe>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe27190524166332000109550010000001371000001379">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>Hs2qLJcIJ5DSmMMx5udiSnM9xI8=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>VquKunseMwlufIbJTcEW/pBecU91FP1W+5CGZ/6x8OvpOhInMHpVsaRc4Xh33BRj2395TJkTwuOeuw/atw7vWo17kb7MXOC387FtZXq1frumJ/RyKC9F962DfmMJ1/YU1LNBRMhW9Fcpkl81lyT7YiJMDPz2Lc1wg9sNTy0gJflX+glWyfPtDbOkbQ1NSxHsN5DpAI1UBbYy9d4MA5nVc9O6JPrIRzY7tWyjk9lw8hjOhFj0OeFKDXCr9QzCKIKnlG8PJD1EZF39kPv957LImv/5M++klXL9Hc1YsxBjDL7RNr1JEj4MnMTSsBCSFskPmsPNPt/QZJAJDMUDl+PyEg==</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>MIIITzCCBjegAwIBAgIQQKy3kfIbEEBCQ/xf9WNlujANBgkqhkiG9w0BAQsFADCBgDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEkMCIGA1UEAxMbQUMgSW5zdGl0dXRvIEZlbmFjb24gUkZCIEczMB4XDTE4MTExOTE3NDMyOFoXDTE5MTExOTE3NDMyOFowggEKMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDELMAkGA1UECAwCQUwxDzANBgNVBAcMBk1hY2VpbzE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRYwFAYDVQQLDA1SRkIgZS1DTlBKIEExMS0wKwYDVQQLDCRBdXRlbnRpY2FkbyBwb3IgQVIgSW5zdGl0dXRvIEZlbmFjb24xSTBHBgNVBAMMQENMViBDT01FUkNJTyBWQVJFSklTVEEgREUgQVJUSUdPUyBERSBGRVNUQVMgRSBQQVA6MTM0NTkxNDYwMDAxNDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD0ZOCrnUtXvUYH0VQYFwFmVngTqzUznBw/CauZozc5nGKZ21LaAkA9BwebOzl4JDcUPJ+RiUDLYgge3hsvn+Yi5hxckBDxBnjtYJnQkN1tLReCEvLhuKZ7/VDRIjR+H3/azVqNJQ/yTv4xs05Hsa1udy1yAaPtxU2SnAcIkWjz+nzGZ2qtk4E4cZzmRjp/34uaBCvKcqiB7E7blNlV3idu0tjOq/Zj/Q1mHsEwRYEkNxE/ZkyF5Pp+6UelPXh/nOkCRqIRfUoXfaEzdznpaba6VTLitGhyMQfcAqArhJKjDzQxqV0Dit9rF1J4OHyMEk8I9Y3qcrsPJ6hMDmBaWrunAgMBAAGjggM2MIIDMjCBwAYDVR0RBIG4MIG1oD0GBWBMAQMEoDQEMjMwMDgxOTc2OTg1OTM2ODQ0OTEwMDAwMDAwMDAwMDAwMjAwMjAwMTE3OTkwNFNTUEFMoB8GBWBMAQMCoBYEFExVQ0lBTkEgRkVMSVggQkFSUk9ToBkGBWBMAQMDoBAEDjEzNDU5MTQ2MDAwMTQxoBcGBWBMAQMHoA4EDDAwMDAwMDAwMDAwMIEfY29tZXJjaWFsLXBsYXN0ZmVzdEBvdXRsb29rLmNvbTAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFCbHlD16h35/S3iKhz3gz7XOqbDaMIGGBgNVHSAEfzB9MHsGBmBMAQIBIjBxMG8GCCsGAQUFBwIBFmNodHRwOi8vaWNwLWJyYXNpbC5hY2ZlbmFjb24uY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9BQy1JbnN0aXR1dG8tRmVuYWNvbi1SRkIvRFBDX0FDX0lGZW5hY29uX1JGQi5wZGYwgcoGA1UdHwSBwjCBvzBeoFygWoZYaHR0cDovL2ljcC1icmFzaWwuYWNmZW5hY29uLmNvbS5ici9yZXBvc2l0b3Jpby9sY3IvQUNJbnN0aXR1dG9GZW5hY29uUkZCRzMvTGF0ZXN0Q1JMLmNybDBdoFugWYZXaHR0cDovL2ljcC1icmFzaWwub3V0cmFsY3IuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0luc3RpdHV0b0ZlbmFjb25SRkJHMy9MYXRlc3RDUkwuY3JsMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgbsGCCsGAQUFBwEBBIGuMIGrMGYGCCsGAQUFBzAChlpodHRwOi8vaWNwLWJyYXNpbC5hY2ZlbmFjb24uY29tLmJyL3JlcG9zaXRvcmlvL2NlcnRpZmljYWRvcy9BQ19JbnN0aXR1dG9fRmVuYWNvbl9SRkJHMy5wN2MwQQYIKwYBBQUHMAGGNWh0dHA6Ly9vY3NwLWFjLWluc3RpdHV0by1mZW5hY29uLXJmYi5jZXJ0aXNpZ24uY29tLmJyMA0GCSqGSIb3DQEBCwUAA4ICAQBRGQBcopOc8mGa7vSBHRcyWwTbT2XGe6BjuBHSyiy0kep1gHHG3R1N2gv06MTfkrYNnP9HYkXHp25K4crU4CLdfHtdDyuUm7iXmr9Z34AZmbTk6YIpZ4CUk+IzYEjYbJK9+n4XASUz99Kslve6vWeBRoHaQTb+2l2yUPW6N75LZWzTLmxvUwJKpmjvHigOmnlxgJJjgKub6b5G6bVOKhXd7UeMMzJPqXRRV5qWlddbifAjzle2J4jjz4q3gJ9BITmO0yFVuGZ+eMHd5XYGOC5rD3Yzfs48f/M940pvddDKZllxH3fyLy17oYjyxVF/kwh2ZXR4/KlxPjqvvIeZ8hZLLX1S788aXvFi4CvHI7ggmpPfnD7onzFdoPxyM0NadMP9MM+bL/NMw7DFfm/DO3M/cAizVMv5zdnRBuCzOxBHXifxS/K7YtUoNYYgSy19G7Hzx1d/o2jPMCMDUL7slFQisFKNsqoexR8t+WO1rgQCdqSeFa1yUjUgeurmBC1hIwSVfUq09CNarEmbIlggSMjRZYkjRY1CCd1DBsC7lZs4ZgsG2QxNxRHIQjj08oSaE6prqZnK0mgfmji4vBwiXPXrMh9lv2t090i1BLEobNnMAWkfmd41sjt1Ts9v0x0Z/S67XT6zhOk2Q4hZWAWIYt1ZunFTp4P/N0o+RXTHUKigDA==</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>
</NFe>
<protNFe versao="4.00">
<infProt>
<tpAmb>2</tpAmb>
<verAplic>SVRS201904120803</verAplic>
<chNFe>27190524166332000109550010000001371000001379</chNFe>
<dhRecbto>2019-05-15T15:50:06-03:00</dhRecbto>
<digVal>Hs2qLJcIJ5DSmMMx5udiSnM9xI8=</digVal>
<cStat>213</cStat>
<xMotivo>Rejeicao: CNPJ-Base do Emitente difere do CNPJ-Base do Certificado Digital</xMotivo>
</infProt>
</protNFe>
</nfeProc>
[NFe27190524166332000109550010000001371000001379.zip](https://github.com/ZeusAutomacao/DFe.NET/files/3184095/NFe27190524166332000109550010000001371000001379.zip)
`

**Comment by ThalisonSantos** [comment]
@marcosgerene 
[NFe27190524166332000109550010000001371000001379.zip](https://github.com/ZeusAutomacao/DFe.NET/files/3184098/NFe27190524166332000109550010000001371000001379.zip)

**Comment by marcosgerene** [comment]
Teste o PR https://github.com/ZeusAutomacao/DFe.NET/pull/980

**Comment by ThalisonSantos** [comment]
@marcosgerene  blz vou testar aqui

**Comment by marcosgerene** [comment]
@ThalisonSantos 
>@marcosgerene como faço pra pegar essa modificação que vc fez? baixei o projeto novamente e continuou com o mesmo erro, acho que não veio a correção que vc fez

Por favor comente da issue, eu nem tinha visto seu comentario la...

Vou aceitar o PR, testei aqui e deu certo, ai você já testa.

**Comment by ThalisonSantos** [comment]
testado e funcionando
