### ISSUE TITLE
Ambiente de inutilização de numeração de NFC-e

### ISSUE THREAD

**Issue by robertocvsiqueira** [ZeusAutomacao/DFe.NET#98]
Adenilton, boa tarde, tudo bem?

Supondo que eu digite a seguinte linha:

 _configuracoes.CfgServico.tpAmb = NFe.Classes.Informacoes.Identificacao.Tipos.TipoAmbiente.taHomologacao;

E em seguida passe a referência do objeto _configuracoes.CfgServico para a instância de ServicosNFe para em seguida a essa linha inutilizar uma numeração:

var servicoNFe = new ServicosNFe(_configuracoes.CfgServico);

Mesmo que eu não dê o comando "_configuracoes.Salvar(_path + ArquivoConfiguracao);", a dll entende que eu estou tentando inutilizar uma numeração no ambiente de homologação?

Obrigado desde já,
Roberto.

**Comment by adeniltonbs** [comment]
Sim roberto, pois a classe ServicosNFe vai ler o estado atual do objeto CfgServico passado como parâmetro. o método _configuracoes.Salvar serve apenas para persistir os dados dessa classe no disco, não para determinar uma transição de estado para este objeto.

O problema da abordagem proposta, é que neste caso, o objeto da classe CfgServico teria que ter duas propriedades  para cada configuração? um para indicar a o valor disponível no cache e outra para indicar o valor persistido no disco? Ou então a classe ServicosNFe teria que receber em seu construtor um arquivo xml persistido no disco. 

De qualquer forma, acredito que esses tratamentos devam ser feitos na aplicação que consumirá a biblioteca. Você pode, por exemplo, ter duas versões do objeto CfgServico, uma que será obtida de seu banco ou de um arquivo e será passada para a construtor de ServicosNFe e outra para ser utilizada pelo usuário enquanto este altera as configurações do sistema e antes de persisti-las.

**Comment by adeniltonbs** [comment]
Roberto, aproveitei e fiz algumas alterações na aplicação de demonstração de uso da biblioteca, conforme o commit 8a7ec7eeaa4267d6708c93b1ed49389dc4ac9d57.
