### ISSUE TITLE
DANFe usando FastReport OpenSource

### ISSUE THREAD

**Issue by leandrossantos** [ZeusAutomacao/DFe.NET#981]
Pessoal alguém já tentou ou conseguiu usar a FastReports OpenSource junto com o projeto Zeus ??

**Comment by marcosgerene** [comment]
@leandrossantos  ainda não vi, mas acredito que não deve ser nada de outro mundo.

Eu pretendo ver isso mais pra frente, quando tiver impressão direta no fast open source.

**Comment by hhunterx** [comment]
Boa tarde. Eu tentei aqui mas como a versão free não tem exportação pra Pdf e nem imprime direto não sei se vale muito a pena investir nisso. Tentei exportar pra imagem e depois gerar um pdf dela e até foi mas a qualidade não ficou muito boa.

**Comment by marcosgerene** [comment]
@hhunterx 

>Boa tarde. Eu tentei aqui mas como a versão free não tem exportação pra Pdf e nem imprime direto não sei se vale muito a pena investir nisso. Tentei exportar pra imagem e depois gerar um pdf dela e até foi mas a qualidade não ficou muito boa.

Existe exportação para PDF já, gera uma imagem-pdf, mas não deixa de ser um PDF (que para o uso na nota fiscal é o suficiente): https://github.com/FastReports/FastReport/issues/86


Sobre a impressão direta, está no roadmap: https://github.com/FastReports/FastReport/issues/79#issuecomment-481165413

Estou acompanhando (bem de longe, confesso) o crescimento do FastReports open source e acredito que ainda em 2019 teremos algo bem interessante.

**Comment by robertorp** [comment]
vou somente deixar essa issue referenciada aqui, https://github.com/ZeusAutomacao/DFe.NET/issues/647

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/1001
