### ISSUE TITLE
Danfe NFe evento com Erro

### ISSUE THREAD

**Issue by ThalisonSantos** [ZeusAutomacao/DFe.NET#983]
(Memo63): Erro CS0246: O nome de namespace ou o tipo 'NFeTipoEvento' não pôde ser encontrado. Precisa de uma diretiva using de um referencia ou assembly?
[1101102719041239289000010355001000022416100022416801-procEventoNFe.zip](https://github.com/ZeusAutomacao/DFe.NET/files/3199178/1101102719041239289000010355001000022416100022416801-procEventoNFe.zip)

**Comment by robertorp** [comment]
opá tira uma print para nos do erro? acho que você já utilizava o Zeus ne? Acho que isso foi uma mudança de nome de tipos de Enum.

**Comment by ThalisonSantos** [comment]
@robertorp 
![2019-05-20 (1)](https://user-images.githubusercontent.com/22593917/58050047-a93e9200-7b24-11e9-964b-c28426bc6e58.png)

**Comment by adeniltonbs** [comment]
Corrigido no commit e7f9362.

**Comment by ThalisonSantos** [comment]
@robertorp e @adeniltonbs  valeu, é bom também verificar o da NFCe
