### ISSUE TITLE
Erro na Função XmlStringParaClasse no Retorno do Envio de Evento (Cancelamento)

### ISSUE THREAD

**Issue by FrancielleWN** [ZeusAutomacao/DFe.NET#989]
Estou utilizando o Método XmlStringParaClasse para Converter em Classe o Retorno do XML do Envio do Evento (Cancelamento):
_**NFe.Classes.Servicos.Evento.retEnvEvento retorno = DFe.Utils.FuncoesXml.XmlStringParaClasse<NFe.Classes.Servicos.Evento.retEnvEvento>(xmlRet);**_

Porém está dando erro na Conversão do tipo Int .
Acredito que seja o IdLote, pois pela NT é um numérico de 1 a 15.

![retEnvEvento](https://user-images.githubusercontent.com/18666250/58573084-5b581700-8213-11e9-95d2-6735a28928fe.PNG)

E meu xml tem a tag IdLote enorme:

`<retEnvEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>107001000001097</idLote><tpAmb>2</tpAmb><verAplic>PR-v4_2_9</verAplic><cOrgao>41</cOrgao><cStat>128</cStat><xMotivo>Lote de Evento Processado</xMotivo><retEvento versao="1.00"><infEvento><tpAmb>2</tpAmb><verAplic>PR-v4_2_9</verAplic><cOrgao>41</cOrgao><cStat>135</cStat><xMotivo>Evento registrado e vinculado a NF-e</xMotivo><chNFe>41190583729004010790650010000010971000459809</chNFe><tpEvento>110111</tpEvento><xEvento>Cancelamento</xEvento><nSeqEvento>1</nSeqEvento><dhRegEvento>2019-05-29T10:52:53-03:00</dhRegEvento><nProt>141190000596959</nProt></infEvento></retEvento></retEnvEvento>`

Acho que ajustando a propriedade para outro tipo de variável irá funcionar

**Comment by robertorp** [comment]
Ajustado https://github.com/ZeusAutomacao/DFe.NET/commit/063e38882678dd8ba7ef84bb77dd7682d92da03f 
se poder testar nos agradecemos, obrigado!

**Comment by FrancielleWN** [comment]
Funcionou certinho @robertorp 
![image](https://user-images.githubusercontent.com/18666250/58714562-5d4ce200-839b-11e9-93e6-346defeef7a7.png)
