### ISSUE TITLE
QR Code Inválido (PR)

### ISSUE THREAD

**Issue by luanfranco** [ZeusAutomacao/DFe.NET#99]
Olá Adenilton,
Estou me deparando com o seguinte erro:

![saikobureiku](https://cloud.githubusercontent.com/assets/8163953/12847392/1040fb74-cbfa-11e5-8931-8ef92b45daed.png)

Já adicionei o "http://" na URL mas mesmo assim não está funcionando.
Alguma sugestão?
Obrigado!

**Comment by adeniltonbs** [comment]
Os schemas que estais a usar estão atualizados?

Submeta seu xml à SEFAZ RS através do portal https://www.sefaz.rs.gov.br/nfe/nfe-val.aspx.

Se estiver tudo Ok na validação do xml, poste ele aqui pra darmos uma olhada.

**Comment by robertorp** [comment]
no cIdToken não está faltando um "0" não? 000001
se olhar a NT2015.002_v1.20 lá tem um exemplo dessa url
