### ISSUE TITLE
Erro ao assinar NFe com emissor CPF

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#990]
Ao assinar a NF-e cujo emissor seja CPF a geração da chave de acesso sempre ocorre com base no campo CNPJ, causando assim, chave inválida

**Comment by robertorp** [comment]
atualize os fontes e teste novamente.. fiz uma possível correção 
https://github.com/ZeusAutomacao/DFe.NET/commit/73de7412fa7cc474027d99a5806117e04c80e914

**Comment by flavionootech** [comment]
Testei, e foi resolvido, aguardo atualização no Nuget

**Comment by flavionootech** [comment]
Situação foi resolvida
