### ISSUE TITLE
Assinatura de MDF-e com emissor CPF

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#992]
Na assinatura de MDF-e está gerando a chave de acesso inválida quando CPF

**Comment by robertorp** [comment]
Feito correção aqui https://github.com/ZeusAutomacao/DFe.NET/commit/1b92202b43f17767d5ffa9fae3a919e51c36188e

precisa que publica nuget? para testes da correção

**Comment by flavionootech** [comment]
Se possível sim

**Comment by robertorp** [comment]
está publicado no Nuget já, agorinha aparece a nova versão. (depende do Nuget a liberação, as vezes demora 5 minutos outras vezes demora 2 horas)

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/990
