### ISSUE TITLE
Evento de Cancelamento de MDF-e com emissor CPF

### ISSUE THREAD

**Issue by flavionootech** [ZeusAutomacao/DFe.NET#993]
O evento de cancelamento de MDF-e somente considera CNPJ

**Comment by robertorp** [comment]
Feito correção aqui 

https://github.com/ZeusAutomacao/DFe.NET/commit/a41c96da2651f5999c6478a4d99b611f3617686e

precisa que publica nuget? para testes da correção

**Comment by flavionootech** [comment]
Se possível sim

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/992
