### ISSUE TITLE
EPEC NFC-E

### ISSUE THREAD

**Issue by FrancielleWN** [ZeusAutomacao/DFe.NET#995]
Olá, não tem implementado a rotina de Envio EPEC de NFC-E para as contingências de SP.
Tem a possibilidade de implementação?
Me disponho a testar

**Comment by robertorp** [comment]
Não tem implementado. 
Bom, é possível fazer epec para NFC-e? se sim, tudo beleza. 
Olha, a possibilidade de implementação no momento da minha parte e difícil. Ando muito ocupado ultimamente. Se alguém quiser implementar com toda certeza irei analisar e aceitar o pull.

**Comment by felixsevero** [comment]
Não utilizo contingência, mas não seria mais prático utilizar NFC-e em Contingência Offline?

**Comment by FrancielleWN** [comment]
Em SP se o serviço da NFC-E não estiver funcionando, as únicas alternativas de contingencia é passar pelo SAT ou enviar por EPEC. Não tem Contingencia Offline habilitado em São Paulo.
Já realizo envio EPEC na minha aplicação, porém sugeri para poder utilizar o Zeus.

**Comment by felixsevero** [comment]
Entendi. Se você e/ou alguém mais quiser contribuir na implementação, seria muito bem vindo :)

**Comment by marcosgerene** [comment]
@FrancielleWN 
Em SP o SAT ativo é obrigatório para homologação do NFCe (até aonde eu sei), sendo assim não entendo o porque outra forma de contingência seria liberada... poderia postar algum documento aonde o EPEC é permitido? Eu gostaria de entender melhor esse ponto...

**Comment by FrancielleWN** [comment]
Em SP o SAT é obrigatório ter um ativo sim, porém você não é obrigado emitir as vendas neles e nem as contingências. Está informando no AJUSTE SINIEF 19/16 a alternativa do EPEC como forma de contingência.
![image](https://user-images.githubusercontent.com/18666250/61473445-c93fd580-a95c-11e9-80da-df3ed17efced.png)

No site da NFC-E SP  (http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/Contingencia.aspx)  tem o link do webservice, NT e schemas para implementação do EPEC NFC-E.
Deixo anexado o XML do EPEC(envio e retorno) dos testes de homologação que fiz.
A venda NFC-E é enviado posteriormente (com o retorno do serviço) com o tipo de emissão 4 para conciliar com o xml EPEC (se não enviar posteriormente a venda para conciliar com o xml EPEC, o sistema de NFC-E fica bloqueado)

[35190783729004002852650010000027454000461931-envEPEC.txt](https://github.com/ZeusAutomacao/DFe.NET/files/3407435/35190783729004002852650010000027454000461931-envEPEC.txt)

[35190783729004002852650010000027454000461931-retEPEC.txt](https://github.com/ZeusAutomacao/DFe.NET/files/3407437/35190783729004002852650010000027454000461931-retEPEC.txt)

**Comment by marcosgerene** [comment]
@FrancielleWN excelente material, meus parabéns, eu não tinha essa informação.

http://www.nfce.fazenda.sp.gov.br/NFCePortal/Paginas/Contingencia.aspx

![image](https://user-images.githubusercontent.com/15945003/61484993-7a069e80-a976-11e9-8a6e-505a857c1eaa.png)
