### ISSUE TITLE
Manifestar Ciencia da Operação erro TimeOut

### ISSUE THREAD

**Issue by bruno-crr** [ZeusAutomacao/DFe.NET#997]
Ao manifestar ciencia de operação estou tendo muitos problemas com timeout, apesar de que o evento fica registrado na Sefaz, isso é normal ou tem algo que posso otimizar para amenizar o problema?

**Comment by felixsevero** [comment]
Bom dia @bruno-crr, apesar de eu não realizar ciência das operações, sei que problemas com Timeout são comuns, ainda mais para alguns estados. Tente ajustar o Timeout nas configurações do Zeus e ver se resolve o seu problema.

**Comment by bruno-crr** [comment]
Boa tarde,

Obrigado pela ajuda, eu ajustei para 5 segundos, creio que amenizou um pouco mas ja vi que este não é um serviço que está 100% pelo menos não aqui na minha UF até pq nao é nem o obrigatório ainda.

**Comment by felixsevero** [comment]
Bom dia, pessoalmente eu utilizo 30 segundos de Timeout.
Mas, se o problema foi solucionado, pode fechar a Issue.
