### ISSUE TITLE
Nfe Manifestada mas retorna NfeProc Null

### ISSUE THREAD

**Issue by bruno-crr** [ZeusAutomacao/DFe.NET#998]
Estou com um caso de uma nota que foi manifestada a ciencia da operacao o evento está registrado, mas não consigo fazer o download da nfe completa, ele localiza o documento quando tento baixar com a chave mas o objeto ProcNFe está null, alguem já viu este erro e se tem alguma solução?

**Comment by robertorp** [comment]
opá boa noite! conseguiu?

**Comment by bruno-crr** [comment]
Opa, não no cnpj que estou realizando o teste, teve uma nota que realmente ela não vem e ja foi dado ciencia e confirmacao da operacao, o nfeproc vem vazio nem null não é.
Deve ser algum bug do WS mas pelo jeito só aconteceu comigo.
