### ISSUE TITLE
DACTE em MVC

### ISSUE THREAD

**Issue by douglasfranciscon** [ZeusAutomacao/DFe.NET#999]
Bom dia!

Alguém usa a geração de DACTE em asp MVC? Eu estou fazendo alguns testes com o ZEUS, e achei muito bom e produtivo, porem, só consegui gerar o DACTE com o App Teste. Em MVC, não consigo ter sucesso no "using CTe.DACTE.Base". 

Quando digito CTe., lista apenas Classes, Serviços, Utils e WSDL.

Grato pela ajuda...

**Comment by marcosgerene** [comment]
@douglasfranciscon acredito que as impressões não funcionem para web da forma que está hoje.

Precisaria converter para o FastReports open source (https://github.com/FastReports/FastReport). Na teroria é algo simples de ser feito, mas estamos esperando alguns recursos que ainda não tem, como a impressão direta.

https://github.com/FastReports/FastReport/issues/79 Direct Print.

**Comment by marcosgerene** [comment]
https://github.com/ZeusAutomacao/DFe.NET/issues/1001
